; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32p4-function-specialization -riscv-esp32p4-function-specialization=true < %s | FileCheck %s


define dso_local i32 @dsps_firmr_s16_ansi(ptr nocapture noundef %fir, ptr nocapture noundef readonly %input, ptr nocapture noundef writeonly %output, i32 noundef %input_len) local_unnamed_addr {
; CHECK-LABEL: define dso_local i32 @dsps_firmr_s16_ansi(
; CHECK-SAME: ptr noundef captures(none) [[FIR:%.*]], ptr noundef readonly captures(none) [[INPUT:%.*]], ptr noundef writeonly captures(none) [[OUTPUT:%.*]], i32 noundef [[INPUT_LEN:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[RESULT_1_LCSSA_LOC:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[RESULT_1_LCSSA_US_LOC:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[SHIFT:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 16
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[SHIFT]], align 4
; CHECK-NEXT:    [[DOTFR:%.*]] = freeze i16 [[TMP0]]
; CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[DOTFR]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[CONV]], -15
; CHECK-NEXT:    [[ROUNDING_VAL:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 24
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ROUNDING_VAL]], align 4
; CHECK-NEXT:    [[CONV1:%.*]] = sext i32 [[TMP1]] to i64
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i16 [[DOTFR]], -1
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[CONV]] to i64
; CHECK-NEXT:    [[SHR:%.*]] = ashr i64 [[CONV1]], [[SH_PROM]]
; CHECK-NEXT:    br label %[[IF_END:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[SUB9:%.*]] = sub nsw i32 0, [[CONV]]
; CHECK-NEXT:    [[SH_PROM10:%.*]] = zext nneg i32 [[SUB9]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl i64 [[CONV1]], [[SH_PROM10]]
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[ROUNDING_0_IN:%.*]] = phi i64 [ [[SHR]], %[[IF_THEN]] ], [ [[SHL]], %[[IF_ELSE]] ]
; CHECK-NEXT:    [[ROUNDING_0:%.*]] = and i64 [[ROUNDING_0_IN]], 1099511627775
; CHECK-NEXT:    [[START_POS:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 36
; CHECK-NEXT:    [[CMP13175:%.*]] = icmp sgt i32 [[INPUT_LEN]], 0
; CHECK-NEXT:    br i1 [[CMP13175]], label %[[FOR_BODY_LR_PH:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_BODY_LR_PH]]:
; CHECK-NEXT:    [[DELAY:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[DELAY]], align 4
; CHECK-NEXT:    [[POS:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 10
; CHECK-NEXT:    [[INTERP:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 32
; CHECK-NEXT:    [[DELAY_SIZE:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 30
; CHECK-NEXT:    [[CMP67:%.*]] = icmp sge i16 [[DOTFR]], 15
; CHECK-NEXT:    [[SUB76:%.*]] = sub nsw i32 15, [[CONV]]
; CHECK-NEXT:    [[SH_PROM77:%.*]] = zext nneg i32 [[SUB76]] to i64
; CHECK-NEXT:    [[SH_PROM70:%.*]] = zext nneg i32 [[SUB]] to i64
; CHECK-NEXT:    [[DECIM:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 12
; CHECK-NEXT:    [[DOTPRE188:%.*]] = load i16, ptr [[POS]], align 2
; CHECK-NEXT:    br i1 [[CMP67]], label %[[FOR_BODY_US_PREHEADER:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[INTERP]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[DELAY_SIZE]], align 2
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[FIR]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[DECIM]], align 4
; CHECK-NEXT:    [[CONV19165:%.*]] = sext i16 [[TMP3]] to i32
; CHECK-NEXT:    [[CONV26:%.*]] = sext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[CONV84:%.*]] = sext i16 [[TMP6]] to i32
; CHECK-NEXT:    [[SUB100:%.*]] = add i16 [[TMP4]], -1
; CHECK-NEXT:    [[CMP_INTERP:%.*]] = icmp eq i32 [[CONV19165]], 1
; CHECK-NEXT:    br i1 [[CMP_INTERP]], label %[[CODEREPL1_THEN:.*]], label %[[CODEREPL1_ELSE:.*]]
; CHECK:       [[FOR_BODY_US_PREHEADER]]:
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr [[INTERP]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[DELAY_SIZE]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[FIR]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[DECIM]], align 4
; CHECK-NEXT:    [[CONV19165_US:%.*]] = sext i16 [[TMP7]] to i32
; CHECK-NEXT:    [[CONV26_US_US:%.*]] = sext i16 [[TMP8]] to i32
; CHECK-NEXT:    [[CONV84_US_US:%.*]] = sext i16 [[TMP10]] to i32
; CHECK-NEXT:    [[SUB100_US:%.*]] = add i16 [[TMP8]], -1
; CHECK-NEXT:    br label %[[CODEREPL:.*]]
; CHECK:       [[CODEREPL]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[RESULT_1_LCSSA_US_LOC]])
; CHECK-NEXT:    call void @dsps_firmr_s16_ansi.for.body.us(i16 [[DOTPRE188]], ptr [[INPUT]], ptr [[TMP2]], ptr [[START_POS]], i16 [[TMP7]], ptr [[POS]], i16 [[TMP8]], ptr [[TMP9]], i32 [[CONV26_US_US]], i64 [[ROUNDING_0]], i32 [[CONV19165_US]], i64 [[SH_PROM70]], ptr [[OUTPUT]], i32 [[CONV84_US_US]], i16 [[SUB100_US]], i32 [[INPUT_LEN]], ptr [[RESULT_1_LCSSA_US_LOC]])
; CHECK-NEXT:    [[RESULT_1_LCSSA_US_RELOAD:%.*]] = load i32, ptr [[RESULT_1_LCSSA_US_LOC]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[RESULT_1_LCSSA_US_LOC]])
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP_LOOPEXIT:.*]]
; CHECK:       [[FOR_COND_CLEANUP_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
; CHECK:       [[CODEREPL1_THEN]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[RESULT_1_LCSSA_LOC]])
; CHECK-NEXT:    call void @dsps_firmr_s16_ansi.for.body(i16 [[DOTPRE188]], ptr [[INPUT]], ptr [[TMP2]], ptr [[START_POS]], i16 [[TMP3]], ptr [[POS]], i16 [[TMP4]], ptr [[TMP5]], i32 [[CONV26]], i64 [[ROUNDING_0]], i32 [[CONV19165]], i64 [[SH_PROM77]], ptr [[OUTPUT]], i32 [[CONV84]], i16 [[SUB100]], i32 [[INPUT_LEN]], ptr [[RESULT_1_LCSSA_LOC]])
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[RESULT_1_LCSSA_LOC]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[RESULT_1_LCSSA_LOC]])
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP_LOOPEXIT1:.*]]
; CHECK:       [[CODEREPL1_ELSE]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[RESULT_1_LCSSA_LOC]])
; CHECK-NEXT:    call void @dsps_firmr_s16_ansi.for.body(i16 [[DOTPRE188]], ptr [[INPUT]], ptr [[TMP2]], ptr [[START_POS]], i16 [[TMP3]], ptr [[POS]], i16 [[TMP4]], ptr [[TMP5]], i32 [[CONV26]], i64 [[ROUNDING_0]], i32 [[CONV19165]], i64 [[SH_PROM77]], ptr [[OUTPUT]], i32 [[CONV84]], i16 [[SUB100]], i32 [[INPUT_LEN]], ptr [[RESULT_1_LCSSA_LOC]])
; CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[RESULT_1_LCSSA_LOC]], align 4
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[RESULT_1_LCSSA_LOC]])
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP_LOOPEXIT1]]
; CHECK:       [[FOR_COND_CLEANUP_LOOPEXIT1]]:
; CHECK-NEXT:    [[RESULT_1_LCSSA_RELOAD_PHI:%.*]] = phi i32 [ [[TMP11]], %[[CODEREPL1_THEN]] ], [ [[TMP12]], %[[CODEREPL1_ELSE]] ]
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    [[RESULT_0_LCSSA:%.*]] = phi i32 [ 0, %[[IF_END]] ], [ [[RESULT_1_LCSSA_US_RELOAD]], %[[FOR_COND_CLEANUP_LOOPEXIT]] ], [ [[RESULT_1_LCSSA_RELOAD_PHI]], %[[FOR_COND_CLEANUP_LOOPEXIT1]] ]
; CHECK-NEXT:    ret i32 [[RESULT_0_LCSSA]]
;
entry:
  %shift = getelementptr inbounds i8, ptr %fir, i32 16
  %0 = load i16, ptr %shift, align 4
  %.fr = freeze i16 %0
  %conv = sext i16 %.fr to i32
  %sub = add nsw i32 %conv, -15
  %rounding_val = getelementptr inbounds i8, ptr %fir, i32 24
  %1 = load i32, ptr %rounding_val, align 4
  %conv1 = sext i32 %1 to i64
  %cmp = icmp sgt i16 %.fr, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %sh_prom = zext nneg i32 %conv to i64
  %shr = ashr i64 %conv1, %sh_prom
  br label %if.end

if.else:                                          ; preds = %entry
  %sub9 = sub nsw i32 0, %conv
  %sh_prom10 = zext nneg i32 %sub9 to i64
  %shl = shl i64 %conv1, %sh_prom10
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %rounding.0.in = phi i64 [ %shr, %if.then ], [ %shl, %if.else ]
  %rounding.0 = and i64 %rounding.0.in, 1099511627775
  %start_pos = getelementptr inbounds i8, ptr %fir, i32 36
  %cmp13175 = icmp sgt i32 %input_len, 0
  br i1 %cmp13175, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %if.end
  %delay = getelementptr inbounds i8, ptr %fir, i32 4
  %2 = load ptr, ptr %delay, align 4
  %pos = getelementptr inbounds i8, ptr %fir, i32 10
  %interp = getelementptr inbounds i8, ptr %fir, i32 32
  %delay_size = getelementptr inbounds i8, ptr %fir, i32 30
  %cmp67 = icmp sgt i16 %.fr, 15
  %sub76 = sub nsw i32 15, %conv
  %sh_prom77 = zext nneg i32 %sub76 to i64
  %sh_prom70 = zext nneg i32 %sub to i64
  %decim = getelementptr inbounds i8, ptr %fir, i32 12
  %.pre188 = load i16, ptr %pos, align 2
  br i1 %cmp67, label %for.body.us.preheader, label %for.body.preheader

for.body.preheader:                               ; preds = %for.body.lr.ph
  %3 = load i16, ptr %interp, align 4
  %4 = load i16, ptr %delay_size, align 2
  %5 = load ptr, ptr %fir, align 4
  %6 = load i16, ptr %decim, align 4
  %conv19165 = sext i16 %3 to i32
  %conv26 = sext i16 %4 to i32
  %conv84 = sext i16 %6 to i32
  %sub100 = add i16 %4, -1
  br label %for.body

for.body.us.preheader:                            ; preds = %for.body.lr.ph
  %7 = load i16, ptr %interp, align 4
  %8 = load i16, ptr %delay_size, align 2
  %9 = load ptr, ptr %fir, align 4
  %10 = load i16, ptr %decim, align 4
  %conv19165.us = sext i16 %7 to i32
  %conv26.us.us = sext i16 %8 to i32
  %conv84.us.us = sext i16 %10 to i32
  %sub100.us = add i16 %8, -1
  br label %for.body.us

for.body.us:                                      ; preds = %for.inc104.us, %for.body.us.preheader
  %11 = phi i16 [ %16, %for.inc104.us ], [ %.pre188, %for.body.us.preheader ]
  %i.0177.us = phi i32 [ %inc105.us, %for.inc104.us ], [ 0, %for.body.us.preheader ]
  %result.0176.us = phi i32 [ %result.1.lcssa.us, %for.inc104.us ], [ 0, %for.body.us.preheader ]
  %arrayidx.us = getelementptr inbounds i16, ptr %input, i32 %i.0177.us
  %12 = load i16, ptr %arrayidx.us, align 2
  %idxprom.us = sext i16 %11 to i32
  %arrayidx15.us = getelementptr inbounds i16, ptr %2, i32 %idxprom.us
  store i16 %12, ptr %arrayidx15.us, align 2
  %13 = load i16, ptr %start_pos, align 4
  %conv17.us = sext i16 %13 to i32
  %cmp20166.us = icmp slt i16 %13, %7
  br i1 %cmp20166.us, label %for.body22.us.us.preheader, label %for.end86.us

for.body22.us.us.preheader:                       ; preds = %for.body.us
  br label %for.body22.us.us

for.end86.us.loopexit:                            ; preds = %for.cond.cleanup48.us.us
  br label %for.end86.us

for.end86.us:                                     ; preds = %for.end86.us.loopexit, %for.body.us
  %result.1.lcssa.us = phi i32 [ %result.0176.us, %for.body.us ], [ %result.2.us.us, %for.end86.us.loopexit ]
  %m.0.lcssa.us = phi i32 [ %conv17.us, %for.body.us ], [ %add85.us.us, %for.end86.us.loopexit ]
  %14 = trunc i32 %m.0.lcssa.us to i16
  %conv90.us = sub i16 %14, %7
  store i16 %conv90.us, ptr %start_pos, align 4
  %15 = load i16, ptr %pos, align 2
  %dec.us = add i16 %15, -1
  store i16 %dec.us, ptr %pos, align 2
  %cmp95.us = icmp slt i16 %dec.us, 0
  br i1 %cmp95.us, label %if.then97.us, label %for.inc104.us

if.then97.us:                                     ; preds = %for.end86.us
  store i16 %sub100.us, ptr %pos, align 2
  br label %for.inc104.us

for.inc104.us:                                    ; preds = %if.then97.us, %for.end86.us
  %16 = phi i16 [ %sub100.us, %if.then97.us ], [ %dec.us, %for.end86.us ]
  %inc105.us = add nuw nsw i32 %i.0177.us, 1
  %exitcond187.not = icmp eq i32 %inc105.us, %input_len
  br i1 %exitcond187.not, label %for.cond.cleanup.loopexit, label %for.body.us

for.body22.us.us:                                 ; preds = %for.cond.cleanup48.us.us, %for.body22.us.us.preheader
  %m.0168.us.us = phi i32 [ %add85.us.us, %for.cond.cleanup48.us.us ], [ %conv17.us, %for.body22.us.us.preheader ]
  %result.1167.us.us = phi i32 [ %result.2.us.us, %for.cond.cleanup48.us.us ], [ %result.0176.us, %for.body22.us.us.preheader ]
  %17 = load i16, ptr %pos, align 2
  %conv24.us.us = sext i16 %17 to i32
  %cmp27153.us.us = icmp slt i16 %17, %8
  br i1 %cmp27153.us.us, label %for.body30.lr.ph.us.us, label %for.cond43.preheader.us.us

for.cond.cleanup48.us.us.loopexit:                ; preds = %for.body49.us.us
  br label %for.cond.cleanup48.us.us

for.cond.cleanup48.us.us:                         ; preds = %for.cond43.preheader.us.us, %for.cond.cleanup48.us.us.loopexit
  %acc.1.lcssa.us.us = phi i64 [ %acc.0.lcssa.us.us, %for.cond43.preheader.us.us ], [ %add63.us.us, %for.cond.cleanup48.us.us.loopexit ]
  %shl71.us.us = shl i64 %acc.1.lcssa.us.us, %sh_prom70
  %conv72.us.us = trunc i64 %shl71.us.us to i16
  %arrayidx74.us.us = getelementptr inbounds i16, ptr %output, i32 %result.1167.us.us
  store i16 %conv72.us.us, ptr %arrayidx74.us.us, align 2
  %result.2.us.us = add nsw i32 %result.1167.us.us, 1
  %add85.us.us = add nsw i32 %m.0168.us.us, %conv84.us.us
  %cmp20.us.us = icmp slt i32 %add85.us.us, %conv19165.us
  br i1 %cmp20.us.us, label %for.body22.us.us, label %for.end86.us.loopexit

for.body49.us.us:                                 ; preds = %for.body49.lr.ph.us.us, %for.body49.us.us
  %n42.0161.us.us = phi i32 [ 0, %for.body49.lr.ph.us.us ], [ %inc65.us.us, %for.body49.us.us ]
  %coeff_pos.1160.us.us = phi i32 [ %coeff_pos.0.lcssa.us.us, %for.body49.lr.ph.us.us ], [ %inc54.us.us, %for.body49.us.us ]
  %acc.1159.us.us = phi i64 [ %acc.0.lcssa.us.us, %for.body49.lr.ph.us.us ], [ %add63.us.us, %for.body49.us.us ]
  %arrayidx51.us.us = getelementptr inbounds i16, ptr %2, i32 %n42.0161.us.us
  %18 = load i16, ptr %arrayidx51.us.us, align 2
  %conv52.us.us = sext i16 %18 to i32
  %inc54.us.us = add nuw nsw i32 %coeff_pos.1160.us.us, 1
  %mul57.us.us = mul nsw i32 %coeff_pos.1160.us.us, %conv19165.us
  %gep164.us.us = getelementptr i16, ptr %invariant.gep163.us.us, i32 %mul57.us.us
  %19 = load i16, ptr %gep164.us.us, align 2
  %conv60.us.us = sext i16 %19 to i32
  %mul61.us.us = mul nsw i32 %conv60.us.us, %conv52.us.us
  %conv62.us.us = sext i32 %mul61.us.us to i64
  %add63.us.us = add nsw i64 %acc.1159.us.us, %conv62.us.us
  %inc65.us.us = add nuw nsw i32 %n42.0161.us.us, 1
  %exitcond186.not = icmp eq i32 %inc65.us.us, %conv24.us.us
  br i1 %exitcond186.not, label %for.cond.cleanup48.us.us.loopexit, label %for.body49.us.us

for.body30.us.us:                                 ; preds = %for.body30.lr.ph.us.us, %for.body30.us.us
  %n.0156.us.us = phi i32 [ %conv24.us.us, %for.body30.lr.ph.us.us ], [ %inc41.us.us, %for.body30.us.us ]
  %coeff_pos.0155.us.us = phi i32 [ 0, %for.body30.lr.ph.us.us ], [ %inc.us.us, %for.body30.us.us ]
  %acc.0154.us.us = phi i64 [ %rounding.0, %for.body30.lr.ph.us.us ], [ %add40.us.us, %for.body30.us.us ]
  %arrayidx32.us.us = getelementptr inbounds i16, ptr %2, i32 %n.0156.us.us
  %20 = load i16, ptr %arrayidx32.us.us, align 2
  %conv33.us.us = sext i16 %20 to i32
  %inc.us.us = add nuw nsw i32 %coeff_pos.0155.us.us, 1
  %mul.us.us = mul nsw i32 %coeff_pos.0155.us.us, %conv19165.us
  %gep.us.us = getelementptr i16, ptr %invariant.gep.us.us, i32 %mul.us.us
  %21 = load i16, ptr %gep.us.us, align 2
  %conv37.us.us = sext i16 %21 to i32
  %mul38.us.us = mul nsw i32 %conv37.us.us, %conv33.us.us
  %conv39.us.us = sext i32 %mul38.us.us to i64
  %add40.us.us = add nsw i64 %acc.0154.us.us, %conv39.us.us
  %inc41.us.us = add nsw i32 %n.0156.us.us, 1
  %exitcond185.not = icmp eq i32 %inc.us.us, %22
  br i1 %exitcond185.not, label %for.cond43.preheader.us.us.loopexit, label %for.body30.us.us

for.cond43.preheader.us.us.loopexit:              ; preds = %for.body30.us.us
  br label %for.cond43.preheader.us.us

for.cond43.preheader.us.us:                       ; preds = %for.cond43.preheader.us.us.loopexit, %for.body22.us.us
  %acc.0.lcssa.us.us = phi i64 [ %rounding.0, %for.body22.us.us ], [ %add40.us.us, %for.cond43.preheader.us.us.loopexit ]
  %coeff_pos.0.lcssa.us.us = phi i32 [ 0, %for.body22.us.us ], [ %22, %for.cond43.preheader.us.us.loopexit ]
  %cmp46158.us.us = icmp sgt i16 %17, 0
  br i1 %cmp46158.us.us, label %for.body49.lr.ph.us.us, label %for.cond.cleanup48.us.us

for.body30.lr.ph.us.us:                           ; preds = %for.body22.us.us
  %invariant.gep.us.us = getelementptr i16, ptr %9, i32 %m.0168.us.us
  %22 = sub nsw i32 %conv26.us.us, %conv24.us.us
  br label %for.body30.us.us

for.body49.lr.ph.us.us:                           ; preds = %for.cond43.preheader.us.us
  %invariant.gep163.us.us = getelementptr i16, ptr %9, i32 %m.0168.us.us
  br label %for.body49.us.us

for.cond.cleanup.loopexit:                        ; preds = %for.inc104.us
  br label %for.cond.cleanup

for.cond.cleanup.loopexit1:                       ; preds = %for.inc104
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit1, %for.cond.cleanup.loopexit, %if.end
  %result.0.lcssa = phi i32 [ 0, %if.end ], [ %result.1.lcssa.us, %for.cond.cleanup.loopexit ], [ %result.1.lcssa, %for.cond.cleanup.loopexit1 ]
  ret i32 %result.0.lcssa

for.body:                                         ; preds = %for.inc104, %for.body.preheader
  %23 = phi i16 [ %34, %for.inc104 ], [ %.pre188, %for.body.preheader ]
  %i.0177 = phi i32 [ %inc105, %for.inc104 ], [ 0, %for.body.preheader ]
  %result.0176 = phi i32 [ %result.1.lcssa, %for.inc104 ], [ 0, %for.body.preheader ]
  %arrayidx = getelementptr inbounds i16, ptr %input, i32 %i.0177
  %24 = load i16, ptr %arrayidx, align 2
  %idxprom = sext i16 %23 to i32
  %arrayidx15 = getelementptr inbounds i16, ptr %2, i32 %idxprom
  store i16 %24, ptr %arrayidx15, align 2
  %25 = load i16, ptr %start_pos, align 4
  %conv17 = sext i16 %25 to i32
  %cmp20166 = icmp slt i16 %25, %3
  br i1 %cmp20166, label %for.body22.preheader, label %for.end86

for.body22.preheader:                             ; preds = %for.body
  br label %for.body22

for.body22:                                       ; preds = %for.cond.cleanup48, %for.body22.preheader
  %m.0168 = phi i32 [ %add85, %for.cond.cleanup48 ], [ %conv17, %for.body22.preheader ]
  %result.1167 = phi i32 [ %result.2, %for.cond.cleanup48 ], [ %result.0176, %for.body22.preheader ]
  %26 = load i16, ptr %pos, align 2
  %conv24 = sext i16 %26 to i32
  %cmp27153 = icmp slt i16 %26, %4
  br i1 %cmp27153, label %for.body30.lr.ph, label %for.cond43.preheader

for.body30.lr.ph:                                 ; preds = %for.body22
  %invariant.gep = getelementptr i16, ptr %5, i32 %m.0168
  %27 = sub nsw i32 %conv26, %conv24
  br label %for.body30

for.cond43.preheader.loopexit:                    ; preds = %for.body30
  br label %for.cond43.preheader

for.cond43.preheader:                             ; preds = %for.cond43.preheader.loopexit, %for.body22
  %acc.0.lcssa = phi i64 [ %rounding.0, %for.body22 ], [ %add40, %for.cond43.preheader.loopexit ]
  %coeff_pos.0.lcssa = phi i32 [ 0, %for.body22 ], [ %27, %for.cond43.preheader.loopexit ]
  %cmp46158 = icmp sgt i16 %26, 0
  br i1 %cmp46158, label %for.body49.lr.ph, label %for.cond.cleanup48

for.body49.lr.ph:                                 ; preds = %for.cond43.preheader
  %invariant.gep163 = getelementptr i16, ptr %5, i32 %m.0168
  br label %for.body49

for.body30:                                       ; preds = %for.body30, %for.body30.lr.ph
  %n.0156 = phi i32 [ %conv24, %for.body30.lr.ph ], [ %inc41, %for.body30 ]
  %coeff_pos.0155 = phi i32 [ 0, %for.body30.lr.ph ], [ %inc, %for.body30 ]
  %acc.0154 = phi i64 [ %rounding.0, %for.body30.lr.ph ], [ %add40, %for.body30 ]
  %arrayidx32 = getelementptr inbounds i16, ptr %2, i32 %n.0156
  %28 = load i16, ptr %arrayidx32, align 2
  %conv33 = sext i16 %28 to i32
  %inc = add nuw nsw i32 %coeff_pos.0155, 1
  %mul = mul nsw i32 %coeff_pos.0155, %conv19165
  %gep = getelementptr i16, ptr %invariant.gep, i32 %mul
  %29 = load i16, ptr %gep, align 2
  %conv37 = sext i16 %29 to i32
  %mul38 = mul nsw i32 %conv37, %conv33
  %conv39 = sext i32 %mul38 to i64
  %add40 = add nsw i64 %acc.0154, %conv39
  %inc41 = add nsw i32 %n.0156, 1
  %exitcond.not = icmp eq i32 %inc, %27
  br i1 %exitcond.not, label %for.cond43.preheader.loopexit, label %for.body30

for.cond.cleanup48.loopexit:                      ; preds = %for.body49
  br label %for.cond.cleanup48

for.cond.cleanup48:                               ; preds = %for.cond.cleanup48.loopexit, %for.cond43.preheader
  %acc.1.lcssa = phi i64 [ %acc.0.lcssa, %for.cond43.preheader ], [ %add63, %for.cond.cleanup48.loopexit ]
  %shr78 = ashr i64 %acc.1.lcssa, %sh_prom77
  %conv79 = trunc i64 %shr78 to i16
  %arrayidx81 = getelementptr inbounds i16, ptr %output, i32 %result.1167
  store i16 %conv79, ptr %arrayidx81, align 2
  %result.2 = add nsw i32 %result.1167, 1
  %add85 = add nsw i32 %m.0168, %conv84
  %cmp20 = icmp slt i32 %add85, %conv19165
  br i1 %cmp20, label %for.body22, label %for.end86.loopexit

for.body49:                                       ; preds = %for.body49, %for.body49.lr.ph
  %n42.0161 = phi i32 [ 0, %for.body49.lr.ph ], [ %inc65, %for.body49 ]
  %coeff_pos.1160 = phi i32 [ %coeff_pos.0.lcssa, %for.body49.lr.ph ], [ %inc54, %for.body49 ]
  %acc.1159 = phi i64 [ %acc.0.lcssa, %for.body49.lr.ph ], [ %add63, %for.body49 ]
  %arrayidx51 = getelementptr inbounds i16, ptr %2, i32 %n42.0161
  %30 = load i16, ptr %arrayidx51, align 2
  %conv52 = sext i16 %30 to i32
  %inc54 = add nuw nsw i32 %coeff_pos.1160, 1
  %mul57 = mul nsw i32 %coeff_pos.1160, %conv19165
  %gep164 = getelementptr i16, ptr %invariant.gep163, i32 %mul57
  %31 = load i16, ptr %gep164, align 2
  %conv60 = sext i16 %31 to i32
  %mul61 = mul nsw i32 %conv60, %conv52
  %conv62 = sext i32 %mul61 to i64
  %add63 = add nsw i64 %acc.1159, %conv62
  %inc65 = add nuw nsw i32 %n42.0161, 1
  %exitcond183.not = icmp eq i32 %inc65, %conv24
  br i1 %exitcond183.not, label %for.cond.cleanup48.loopexit, label %for.body49

for.end86.loopexit:                               ; preds = %for.cond.cleanup48
  br label %for.end86

for.end86:                                        ; preds = %for.end86.loopexit, %for.body
  %result.1.lcssa = phi i32 [ %result.0176, %for.body ], [ %result.2, %for.end86.loopexit ]
  %m.0.lcssa = phi i32 [ %conv17, %for.body ], [ %add85, %for.end86.loopexit ]
  %32 = trunc i32 %m.0.lcssa to i16
  %conv90 = sub i16 %32, %3
  store i16 %conv90, ptr %start_pos, align 4
  %33 = load i16, ptr %pos, align 2
  %dec = add i16 %33, -1
  store i16 %dec, ptr %pos, align 2
  %cmp95 = icmp slt i16 %dec, 0
  br i1 %cmp95, label %if.then97, label %for.inc104

if.then97:                                        ; preds = %for.end86
  store i16 %sub100, ptr %pos, align 2
  br label %for.inc104

for.inc104:                                       ; preds = %if.then97, %for.end86
  %34 = phi i16 [ %dec, %for.end86 ], [ %sub100, %if.then97 ]
  %inc105 = add nuw nsw i32 %i.0177, 1
  %exitcond184.not = icmp eq i32 %inc105, %input_len
  br i1 %exitcond184.not, label %for.cond.cleanup.loopexit1, label %for.body
}

