; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-vmulas-xp.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv1v,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local ptr @test_vmulas_s8_qacc_ld_xp(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, i32 noundef %incr) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_s8_qacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.s8.qacc.ld.xp q0, a2, a3, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src1, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src2, i32 16)
  %3 = extractvalue { <16 x i8>, ptr } %2, 0
  %4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc.m()
  %5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 0
  %6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 1
  %7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 2
  %8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 3
  %9 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ld.xp.m(<16 x i8> %5, <16 x i8> %6, <16 x i8> %7, <16 x i8> %8, <16 x i8> %1, <16 x i8> %3, ptr %src3, i32 %incr)
  %10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %9, 0
  ret ptr %10
}

define dso_local ptr @test_vmulas_s8_qacc_st_xp(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %incr) local_unnamed_addr #1 {
; ASM-LABEL: test_vmulas_s8_qacc_st_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.s8.qacc.st.xp q1, a2, a3, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src1, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src2, i32 16)
  %3 = extractvalue { <16 x i8>, ptr } %2, 0
  %4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc.m()
  %5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 0
  %6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 1
  %7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 2
  %8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 3
  %9 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.st.xp.m(<16 x i8> %5, <16 x i8> %6, <16 x i8> %7, <16 x i8> %8, <16 x i8> %3, <16 x i8> %1, <16 x i8> %3, ptr %dst, i32 %incr)
  %10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %9, 0
  ret ptr %10
}

define dso_local ptr @test_vmulas_s16_qacc_ld_xp(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, i32 noundef %incr) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_s16_qacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.s16.qacc.ld.xp q0, a2, a3, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src1, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = bitcast <16 x i8> %1 to <8 x i16>
  %3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src2, i32 16)
  %4 = extractvalue { <16 x i8>, ptr } %3, 0
  %5 = bitcast <16 x i8> %4 to <8 x i16>
  %6 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc.m()
  %7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %6, 0
  %8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %6, 1
  %9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %6, 2
  %10 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %6, 3
  %11 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.ld.xp.m(<16 x i8> %7, <16 x i8> %8, <16 x i8> %9, <16 x i8> %10, <8 x i16> %2, <8 x i16> %5, ptr %src3, i32 %incr)
  %12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %11, 0
  ret ptr %12
}

define dso_local ptr @test_vmulas_u8_qacc_ld_xp(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, i32 noundef %incr) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_u8_qacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.u8.qacc.ld.xp q0, a2, a3, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src1, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src2, i32 16)
  %3 = extractvalue { <16 x i8>, ptr } %2, 0
  %4 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc.m()
  %5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 0
  %6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 1
  %7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 2
  %8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %4, 3
  %9 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.ld.xp.m(<16 x i8> %5, <16 x i8> %6, <16 x i8> %7, <16 x i8> %8, <16 x i8> %1, <16 x i8> %3, ptr %src3, i32 %incr)
  %10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %9, 0
  ret ptr %10
}

define dso_local ptr @test_vmulas_u16_qacc_ld_xp(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, i32 noundef %incr) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_u16_qacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.u16.qacc.ld.xp q0, a2, a3, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src1, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = bitcast <16 x i8> %1 to <8 x i16>
  %3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src2, i32 16)
  %4 = extractvalue { <16 x i8>, ptr } %3, 0
  %5 = bitcast <16 x i8> %4 to <8 x i16>
  %6 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc.m()
  %7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %6, 0
  %8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %6, 1
  %9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %6, 2
  %10 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %6, 3
  %11 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.ld.xp.m(<16 x i8> %7, <16 x i8> %8, <16 x i8> %9, <16 x i8> %10, <8 x i16> %2, <8 x i16> %5, ptr %src3, i32 %incr)
  %12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %11, 0
  ret ptr %12
}

define dso_local ptr @test_vmulas_s8_xacc_ld_xp(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, i32 noundef %incr) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_s8_xacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.l zero
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.xacc.h zero
; ASM-NEXT:    esp.vmulas.s8.xacc.ld.xp q0, a2, a3, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src1, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src2, i32 16)
  %3 = extractvalue { <16 x i8>, ptr } %2, 0
  %4 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.ld.xp.m(i32 0, i32 0, <16 x i8> %1, <16 x i8> %3, ptr %src3, i32 %incr)
  %5 = extractvalue { <16 x i8>, ptr, i32, i32 } %4, 1
  ret ptr %5
}

define dso_local ptr @test_vmulas_s16_xacc_ld_xp(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, i32 noundef %incr) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_s16_xacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.l zero
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.xacc.h zero
; ASM-NEXT:    esp.vmulas.s16.xacc.ld.xp q0, a2, a3, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src1, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = bitcast <16 x i8> %1 to <8 x i16>
  %3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src2, i32 16)
  %4 = extractvalue { <16 x i8>, ptr } %3, 0
  %5 = bitcast <16 x i8> %4 to <8 x i16>
  %6 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.ld.xp.m(i32 0, i32 0, <8 x i16> %2, <8 x i16> %5, ptr %src3, i32 %incr)
  %7 = extractvalue { <16 x i8>, ptr, i32, i32 } %6, 1
  ret ptr %7
}

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr, i32) #2

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc.m() #3

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ld.xp.m(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32) #2

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.st.xp.m(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.ld.xp.m(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32) #2

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.ld.xp.m(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32) #2

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.ld.xp.m(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32) #2

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.ld.xp.m(i32, i32, <16 x i8>, <16 x i8>, ptr, i32) #2

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.ld.xp.m(i32, i32, <8 x i16>, <8 x i16>, ptr, i32) #2

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { "target-features"="+32bit,+xespv" }
attributes #2 = { nounwind }
attributes #3 = { nounwind }
attributes #4 = { nounwind }


