; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-add-sub-sat.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=xespv2p1 -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vsadds_s8(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1) local_unnamed_addr #0 {
; ASM-LABEL: test_vsadds_s8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vsadds.s8 q0, q0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call <16 x i8> @llvm.riscv.esp.vsadds.s8.m(<16 x i8> %1, i32 %rs1)
  %3 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %2, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vsadds.s8.m(<16 x i8>, i32) #1

define dso_local void @test_vssubs_s8(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1) local_unnamed_addr #0 {
; ASM-LABEL: test_vssubs_s8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vssubs.s8 q0, q0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call <16 x i8> @llvm.riscv.esp.vssubs.s8.m(<16 x i8> %1, i32 %rs1)
  %3 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %2, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vssubs.s8.m(<16 x i8>, i32) #1

define dso_local void @test_vsadds_s16(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1) local_unnamed_addr #0 {
; ASM-LABEL: test_vsadds_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vsadds.s16 q0, q0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = bitcast <16 x i8> %1 to <8 x i16>
  %3 = tail call <8 x i16> @llvm.riscv.esp.vsadds.s16.m(<8 x i16> %2, i32 %rs1)
  %4 = bitcast <8 x i16> %3 to <16 x i8>
  %5 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %4, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vsadds.s16.m(<8 x i16>, i32) #1

define dso_local void @test_vssubs_s16(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1) local_unnamed_addr #0 {
; ASM-LABEL: test_vssubs_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vssubs.s16 q0, q0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = bitcast <16 x i8> %1 to <8 x i16>
  %3 = tail call <8 x i16> @llvm.riscv.esp.vssubs.s16.m(<8 x i16> %2, i32 %rs1)
  %4 = bitcast <8 x i16> %3 to <16 x i8>
  %5 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %4, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vssubs.s16.m(<8 x i16>, i32) #1

define dso_local void @test_vsadds_u8(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1) local_unnamed_addr #0 {
; ASM-LABEL: test_vsadds_u8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vsadds.u8 q0, q0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call <16 x i8> @llvm.riscv.esp.vsadds.u8.m(<16 x i8> %1, i32 %rs1)
  %3 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %2, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vsadds.u8.m(<16 x i8>, i32) #1

define dso_local void @test_vssubs_u8(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1) local_unnamed_addr #0 {
; ASM-LABEL: test_vssubs_u8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vssubs.u8 q0, q0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call <16 x i8> @llvm.riscv.esp.vssubs.u8.m(<16 x i8> %1, i32 %rs1)
  %3 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %2, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vssubs.u8.m(<16 x i8>, i32) #1

define dso_local void @test_vsadds_u16(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1) local_unnamed_addr #0 {
; ASM-LABEL: test_vsadds_u16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vsadds.u16 q0, q0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = bitcast <16 x i8> %1 to <8 x i16>
  %3 = tail call <8 x i16> @llvm.riscv.esp.vsadds.u16.m(<8 x i16> %2, i32 %rs1)
  %4 = bitcast <8 x i16> %3 to <16 x i8>
  %5 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %4, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vsadds.u16.m(<8 x i16>, i32) #1

define dso_local void @test_vssubs_u16(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1) local_unnamed_addr #0 {
; ASM-LABEL: test_vssubs_u16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vssubs.u16 q0, q0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = bitcast <16 x i8> %1 to <8 x i16>
  %3 = tail call <8 x i16> @llvm.riscv.esp.vssubs.u16.m(<8 x i16> %2, i32 %rs1)
  %4 = bitcast <8 x i16> %3 to <16 x i8>
  %5 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %4, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vssubs.u16.m(<8 x i16>, i32) #1

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr, i32) #2

declare ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8>, ptr, i32) #3

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { nounwind }
attributes #3 = { nounwind }


