; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-zip-unzip.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vzip_8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vzip_8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vzip.8 q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vzip.8(<16 x i8> %ev1, <16 x i8> %ev2)
  %ev3 = extractvalue { <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8> } %v1, 1
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev3, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst2, i32 16)
  ret void
}

define dso_local void @test_vunzip_8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vunzip_8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vunzip.8 q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vunzip.8(<16 x i8> %ev1, <16 x i8> %ev2)
  %ev3 = extractvalue { <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8> } %v1, 1
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev3, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst2, i32 16)
  ret void
}

define dso_local void @test_vzip_16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vzip_16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vzip.16 q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vzip.16(<8 x i16> %bc1, <8 x i16> %bc2)
  %ev3 = extractvalue { <8 x i16>, <8 x i16> } %v1, 0
  %ev4 = extractvalue { <8 x i16>, <8 x i16> } %v1, 1
  %bc3 = bitcast <8 x i16> %ev3 to <16 x i8>
  %bc4 = bitcast <8 x i16> %ev4 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc4, ptr %dst2, i32 16)
  ret void
}

define dso_local void @test_vzip_32(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vzip_32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vzip.32 q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <4 x i32>
  %v1 = tail call { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vzip.32(<4 x i32> %bc1, <4 x i32> %bc2)
  %ev3 = extractvalue { <4 x i32>, <4 x i32> } %v1, 0
  %ev4 = extractvalue { <4 x i32>, <4 x i32> } %v1, 1
  %bc3 = bitcast <4 x i32> %ev3 to <16 x i8>
  %bc4 = bitcast <4 x i32> %ev4 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc4, ptr %dst2, i32 16)
  ret void
}

define dso_local void @test_vunzip_16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vunzip_16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vunzip.16 q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vunzip.16(<8 x i16> %bc1, <8 x i16> %bc2)
  %ev3 = extractvalue { <8 x i16>, <8 x i16> } %v1, 0
  %ev4 = extractvalue { <8 x i16>, <8 x i16> } %v1, 1
  %bc3 = bitcast <8 x i16> %ev3 to <16 x i8>
  %bc4 = bitcast <8 x i16> %ev4 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc4, ptr %dst2, i32 16)
  ret void
}

define dso_local void @test_vunzip_32(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vunzip_32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vunzip.32 q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <4 x i32>
  %v1 = tail call { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vunzip.32(<4 x i32> %bc1, <4 x i32> %bc2)
  %ev3 = extractvalue { <4 x i32>, <4 x i32> } %v1, 0
  %ev4 = extractvalue { <4 x i32>, <4 x i32> } %v1, 1
  %bc3 = bitcast <4 x i32> %ev3 to <16 x i8>
  %bc4 = bitcast <4 x i32> %ev4 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc4, ptr %dst2, i32 16)
  ret void
}

define dso_local void @test_vzipt_8(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, ptr noundef %dst1, ptr noundef %dst2, ptr noundef %dst3) local_unnamed_addr #0 {
; ASM-LABEL: test_vzipt_8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.vzipt.8 q0, q1, q2
; ASM-NEXT:    esp.vst.128.ip q0, a3, 16
; ASM-NEXT:    esp.vst.128.ip q1, a4, 16
; ASM-NEXT:    esp.vst.128.ip q2, a5, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src3, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vzipt.8(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev5, ptr %dst2, i32 16)
  %vst_ptr.2 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev6, ptr %dst3, i32 16)
  ret void
}

define dso_local void @test_vzipt_16(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, ptr noundef %dst1, ptr noundef %dst2, ptr noundef %dst3) local_unnamed_addr #0 {
; ASM-LABEL: test_vzipt_16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.vzipt.16 q0, q1, q2
; ASM-NEXT:    esp.vst.128.ip q0, a3, 16
; ASM-NEXT:    esp.vst.128.ip q1, a4, 16
; ASM-NEXT:    esp.vst.128.ip q2, a5, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src3, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %bc3 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.riscv.esp.vzipt.16(<8 x i16> %bc1, <8 x i16> %bc2, <8 x i16> %bc3)
  %ev4 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %v1, 0
  %ev5 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %v1, 1
  %ev6 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %v1, 2
  %bc4 = bitcast <8 x i16> %ev4 to <16 x i8>
  %bc5 = bitcast <8 x i16> %ev5 to <16 x i8>
  %bc6 = bitcast <8 x i16> %ev6 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc4, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc5, ptr %dst2, i32 16)
  %vst_ptr.2 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc6, ptr %dst3, i32 16)
  ret void
}

define dso_local void @test_vunzipt_8(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, ptr noundef %dst1, ptr noundef %dst2, ptr noundef %dst3) local_unnamed_addr #0 {
; ASM-LABEL: test_vunzipt_8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.vunzipt.8 q0, q1, q2
; ASM-NEXT:    esp.vst.128.ip q0, a3, 16
; ASM-NEXT:    esp.vst.128.ip q1, a4, 16
; ASM-NEXT:    esp.vst.128.ip q2, a5, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src3, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vunzipt.8(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev5, ptr %dst2, i32 16)
  %vst_ptr.2 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev6, ptr %dst3, i32 16)
  ret void
}

define dso_local void @test_vunzipt_16(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, ptr noundef %dst1, ptr noundef %dst2, ptr noundef %dst3) local_unnamed_addr #0 {
; ASM-LABEL: test_vunzipt_16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.vunzipt.16 q0, q1, q2
; ASM-NEXT:    esp.vst.128.ip q0, a3, 16
; ASM-NEXT:    esp.vst.128.ip q1, a4, 16
; ASM-NEXT:    esp.vst.128.ip q2, a5, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src3, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %bc3 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.riscv.esp.vunzipt.16(<8 x i16> %bc1, <8 x i16> %bc2, <8 x i16> %bc3)
  %ev4 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %v1, 0
  %ev5 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %v1, 1
  %ev6 = extractvalue { <8 x i16>, <8 x i16>, <8 x i16> } %v1, 2
  %bc4 = bitcast <8 x i16> %ev4 to <16 x i8>
  %bc5 = bitcast <8 x i16> %ev5 to <16 x i8>
  %bc6 = bitcast <8 x i16> %ev6 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc4, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc5, ptr %dst2, i32 16)
  %vst_ptr.2 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc6, ptr %dst3, i32 16)
  ret void
}

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #1

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vzip.8(<16 x i8>, <16 x i8>) #2

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #3

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vunzip.8(<16 x i8>, <16 x i8>) #2

declare { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vzip.16(<8 x i16>, <8 x i16>) #2

declare { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vzip.32(<4 x i32>, <4 x i32>) #2

declare { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vunzip.16(<8 x i16>, <8 x i16>) #2

declare { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vunzip.32(<4 x i32>, <4 x i32>) #2

declare { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vzipt.8(<16 x i8>, <16 x i8>, <16 x i8>) #2

declare { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.riscv.esp.vzipt.16(<8 x i16>, <8 x i16>, <8 x i16>) #2

declare { <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vunzipt.8(<16 x i8>, <16 x i8>, <16 x i8>) #2

declare { <8 x i16>, <8 x i16>, <8 x i16> } @llvm.riscv.esp.vunzipt.16(<8 x i16>, <8 x i16>, <8 x i16>) #2

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { nounwind }
attributes #3 = { nounwind }


