; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-shift.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vsld_8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsld_8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsld.8 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vsld.8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vsld.8(<16 x i8>, <16 x i8>, i32 immarg, i32 immarg) #1

define dso_local void @test_vsrd_8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsrd_8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsrd.8 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vsrd.8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vsrd.8(<16 x i8>, <16 x i8>, i32 immarg, i32 immarg) #1

define dso_local void @test_vsld_16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsld_16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsld.16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vsld.16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vsld.16(<8 x i16>, <8 x i16>, i32 immarg, i32 immarg) #1

define dso_local void @test_vsrd_16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsrd_16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsrd.16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vsrd.16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vsrd.16(<8 x i16>, <8 x i16>, i32 immarg, i32 immarg) #1

define dso_local void @test_vsld_32(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsld_32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsld.32 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <4 x i32>
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsld.32(<4 x i32> %bc1, <4 x i32> %bc2, i32 0, i32 7)
  %bc3 = bitcast <4 x i32> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <4 x i32> @llvm.riscv.esp.vsld.32(<4 x i32>, <4 x i32>, i32 immarg, i32 immarg) #1

define dso_local void @test_vsrd_32(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsrd_32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsrd.32 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <4 x i32>
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsrd.32(<4 x i32> %bc1, <4 x i32> %bc2, i32 0, i32 7)
  %bc3 = bitcast <4 x i32> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <4 x i32> @llvm.riscv.esp.vsrd.32(<4 x i32>, <4 x i32>, i32 immarg, i32 immarg) #1

define dso_local void @test_slci_2q_m(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_slci_2q_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.slci.2q q0, q1, 5
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.slci.2q(<16 x i8> %ev1, <16 x i8> %ev2, i32 5)
  %ev3 = extractvalue { <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8> } %v1, 1
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev3, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst2, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.slci.2q(<16 x i8>, <16 x i8>, i32 immarg) #1

define dso_local void @test_srci_2q_m(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_srci_2q_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.srci.2q q0, q1, 3
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.srci.2q(<16 x i8> %ev1, <16 x i8> %ev2, i32 3)
  %ev3 = extractvalue { <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8> } %v1, 1
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev3, ptr %dst1, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst2, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.srci.2q(<16 x i8>, <16 x i8>, i32 immarg) #1

define dso_local void @test_vsr_s32(ptr noundef %src, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vsr_s32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movx.w.sar a2
; ASM-NEXT:    esp.vsr.s32 q0, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsr.s32(<4 x i32> %bc1, i32 %sar, i32 7)
  %bc2 = bitcast <4 x i32> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

declare i32 @llvm.riscv.esp.movx.w.sar(i32) #1

declare <4 x i32> @llvm.riscv.esp.vsr.s32(<4 x i32>, i32, i32 immarg) #1

define dso_local void @test_vsr_u32(ptr noundef %src, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vsr_u32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movx.w.sar a2
; ASM-NEXT:    esp.vsr.u32 q0, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsr.u32(<4 x i32> %bc1, i32 %sar, i32 7)
  %bc2 = bitcast <4 x i32> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

declare <4 x i32> @llvm.riscv.esp.vsr.u32(<4 x i32>, i32, i32 immarg) #1

define dso_local void @test_src_q(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_src_q:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar.bytes zero
; ASM-NEXT:    esp.src.q q0, q1, q0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.src.q(i32 0, <16 x i8> %ev1, <16 x i8> %ev2)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_src_q_ld_ip(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, ptr noundef %dst_qw, ptr noundef %dst_qu) local_unnamed_addr #0 {
; ASM-LABEL: test_src_q_ld_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar.bytes zero
; ASM-NEXT:    esp.src.q.ld.ip q0, a2, 16, q1, q0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    esp.vst.128.ip q0, a4, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 0, <16 x i8> %ev1, <16 x i8> %ev2, ptr %src3, i32 16)
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, ptr } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, ptr } %v1, 1
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev3, ptr %dst_qw, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst_qu, i32 16)
  ret void
}

define dso_local void @test_src_q_qup(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst_qz, ptr noundef %dst_qw) local_unnamed_addr #0 {
; ASM-LABEL: test_src_q_qup:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar.bytes zero
; ASM-NEXT:    esp.src.q.qup q0, q1, q0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.src.q.qup(i32 0, <16 x i8> %ev1, <16 x i8> %ev2)
  %ev3 = extractvalue { <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8> } %v1, 1
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev3, ptr %dst_qz, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst_qw, i32 16)
  ret void
}



define dso_local void @test_vsl_32(ptr noundef %src, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vsl_32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movx.w.sar a2
; ASM-NEXT:    esp.vsl.32 q0, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsl.32(<4 x i32> %bc1, i32 0, i32 %sar)
  %bc2 = bitcast <4 x i32> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

declare <4 x i32> @llvm.riscv.esp.vsl.32(<4 x i32>, i32 immarg, i32) #1

define dso_local void @test_srcq_128_st_incp(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_srcq_128_st_incp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar.bytes zero
; ASM-NEXT:    esp.srcq.128.st.incp q1, q0, a2
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call ptr @llvm.riscv.esp.srcq.128.st.incp(i32 0, <16 x i8> %ev1, <16 x i8> %ev2, ptr %dst)
  ret void
}

define dso_local void @test_srcxxp_2q(ptr noundef %src1, ptr noundef %src2, ptr noundef %Ptr, i32 noundef %offset, ptr noundef writeonly captures(none) initializes((0, 4)) %dst) local_unnamed_addr #3 {
; ASM-LABEL: test_srcxxp_2q:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.srcxxp.2q q0, q1, a2, a3
; ASM-NEXT:    sw a2, 0(a4)
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.srcxxp.2q(<16 x i8> %ev1, <16 x i8> %ev2, ptr %Ptr, i32 %offset)
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, ptr } %v1, 2
  store ptr %ev3, ptr %dst, align 4, !tbaa !114
  ret void
}

define dso_local void @test_slcxxp_2q(ptr noundef %src1, ptr noundef %src2, ptr noundef %Ptr, i32 noundef %offset, ptr noundef writeonly captures(none) initializes((0, 4)) %dst) local_unnamed_addr #3 {
; ASM-LABEL: test_slcxxp_2q:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.slcxxp.2q q0, q1, a2, a3
; ASM-NEXT:    sw a2, 0(a4)
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.slcxxp.2q(<16 x i8> %ev1, <16 x i8> %ev2, ptr %Ptr, i32 %offset)
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, ptr } %v1, 2
  store ptr %ev3, ptr %dst, align 4, !tbaa !114
  ret void
}

define dso_local i32 @test_srs_s_xacc(i32 noundef %Rs1) local_unnamed_addr #4 {
; ASM-LABEL: test_srs_s_xacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.l zero
; ASM-NEXT:    esp.movx.w.xacc.h zero
; ASM-NEXT:    esp.srs.s.xacc a0, a0
; ASM-NEXT:    ret
entry:
  %zero_xacc_tmp1 = tail call { i32, i32 } @llvm.riscv.esp.zero.xacc()
  %v1 = tail call { i32, i32, i32 } @llvm.riscv.esp.srs.s.xacc(i32 0, i32 0, i32 %Rs1, i32 0, i32 7)
  %ev1 = extractvalue { i32, i32, i32 } %v1, 0
  ret i32 %ev1
}

declare { i32, i32 } @llvm.riscv.esp.zero.xacc() #5

define dso_local i32 @test_srs_u_xacc(i32 noundef %Rs1) local_unnamed_addr #4 {
; ASM-LABEL: test_srs_u_xacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.l zero
; ASM-NEXT:    esp.movx.w.xacc.h zero
; ASM-NEXT:    esp.srs.u.xacc a0, a0
; ASM-NEXT:    ret
entry:
  %zero_xacc_tmp2 = tail call { i32, i32 } @llvm.riscv.esp.zero.xacc()
  %v1 = tail call { i32, i32, i32 } @llvm.riscv.esp.srs.u.xacc(i32 0, i32 0, i32 %Rs1, i32 0, i32 7)
  %ev1 = extractvalue { i32, i32, i32 } %v1, 0
  ret i32 %ev1
}

define dso_local ptr @test_st_s_xacc_ip(ptr noundef %dst) local_unnamed_addr #4 {
; ASM-LABEL: test_st_s_xacc_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.l zero
; ASM-NEXT:    esp.movx.w.xacc.h zero
; ASM-NEXT:    esp.st.s.xacc.ip a0, 8
; ASM-NEXT:    ret
entry:
  %zero_xacc_tmp3 = tail call { i32, i32 } @llvm.riscv.esp.zero.xacc()
  %v1 = tail call { ptr, i32, i32 } @llvm.riscv.esp.st.s.xacc.ip(i32 0, i32 0, ptr %dst, i32 8)
  %ev1 = extractvalue { ptr, i32, i32 } %v1, 0
  ret ptr %ev1
}

define dso_local ptr @test_st_u_xacc_ip(ptr noundef %dst) local_unnamed_addr #4 {
; ASM-LABEL: test_st_u_xacc_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.l zero
; ASM-NEXT:    esp.movx.w.xacc.h zero
; ASM-NEXT:    esp.st.u.xacc.ip a0, 8
; ASM-NEXT:    ret
entry:
  %zero_xacc_tmp4 = tail call { i32, i32 } @llvm.riscv.esp.zero.xacc()
  %v1 = tail call { ptr, i32, i32 } @llvm.riscv.esp.st.u.xacc.ip(i32 0, i32 0, ptr %dst, i32 8)
  %ev1 = extractvalue { ptr, i32, i32 } %v1, 0
  ret ptr %ev1
}

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #6

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #7

declare <16 x i8> @llvm.riscv.esp.src.q(i32, <16 x i8>, <16 x i8>) #1

declare { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32, <16 x i8>, <16 x i8>, ptr, i32) #6

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.src.q.qup(i32, <16 x i8>, <16 x i8>) #1

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc() #1

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32, i32) #1

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s8.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32) #1

declare ptr @llvm.riscv.esp.srcq.128.st.incp(i32, <16 x i8>, <16 x i8>, ptr) #7

declare { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.srcxxp.2q(<16 x i8>, <16 x i8>, ptr, i32) #1

declare { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.slcxxp.2q(<16 x i8>, <16 x i8>, ptr, i32) #1

declare { i32, i32, i32 } @llvm.riscv.esp.srs.s.xacc(i32, i32, i32, i32 immarg, i32 immarg) #1

declare { i32, i32, i32 } @llvm.riscv.esp.srs.u.xacc(i32, i32, i32, i32 immarg, i32 immarg) #1

declare { ptr, i32, i32 } @llvm.riscv.esp.st.s.xacc.ip(i32, i32, ptr, i32) #7

declare { ptr, i32, i32 } @llvm.riscv.esp.st.u.xacc.ip(i32, i32, ptr, i32) #7

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { "target-features"="+32bit,+xespv" }
attributes #4 = { "target-features"="+32bit,+xespv" }
attributes #5 = { nounwind }
attributes #6 = { nounwind }
attributes #7 = { nounwind }


!114 = !{!115, !115, i64 0}
!115 = !{!"any pointer", !116, i64 0}
!116 = !{!"omnipotent char", !117, i64 0}
!117 = !{!"Simple C/C++ TBAA"}
