; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-movx-r-w-fft-bit-width.c'
; Test ASM generation (Intrinsic -> ASM)
; llvm.riscv.esp.fft.bitrev.m is shared across 2.1 (+xespv2p1) and 2.2 (+xespv); each RUN
; uses one ISA only. test_movx_* keeps +xespv2p1; test_bitrev_* uses +xespv for 2.2 RUNs.
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM
; RUN: llc -O2 -mattr=+xespv,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM-MOVX
; RUN: llc -O2 -mattr=+xespv,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM2P2
; RUN: llc -O2 -mattr=+xespv,+espv-lowering -mtriple=riscv32 -stop-after=finalize-isel %s -o - | FileCheck %s --check-prefix=MIR

define dso_local i32 @test_movx_fft_bit_width_write_read(i32 noundef %rs1_val) local_unnamed_addr #0 {
; ASM-LABEL: test_movx_fft_bit_width_write_read:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.fft.bit.width a0
; ASM-NEXT:    esp.movx.r.fft.bit.width a0
; ASM-NEXT:    ret
;
; ASM-MOVX-LABEL: test_movx_fft_bit_width_write_read:
; ASM-MOVX:       # %bb.0: # %entry
; ASM-MOVX-NEXT:    esp.movx.w.fft.bit.width a0
; ASM-MOVX-NEXT:    esp.movx.r.fft.bit.width a0
; ASM-MOVX-NEXT:    ret
;
; MIR-LABEL: name: test_movx_fft_bit_width_write_read
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $x10
; MIR-NEXT: {{  $}}
; MIR-NEXT:   [[COPY:%[0-9]+]]:gprpie = COPY $x10
; MIR-NEXT:   [[ESP_MOVX_W_FFT_BIT_WIDTH:%[0-9]+]]:fft_bit_widthreg = ESP_MOVX_W_FFT_BIT_WIDTH [[COPY]]
; MIR-NEXT:   [[ESP_MOVX_R_FFT_BIT_WIDTH:%[0-9]+]]:gprpie = ESP_MOVX_R_FFT_BIT_WIDTH killed [[ESP_MOVX_W_FFT_BIT_WIDTH]]
; MIR-NEXT:   $x10 = COPY [[ESP_MOVX_R_FFT_BIT_WIDTH]]
; MIR-NEXT:   PseudoRET implicit $x10
entry:
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.fft.bit.width(i32 %rs1_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.r.fft.bit.width(i32 %v1)
  ret i32 %v2
}

declare i32 @llvm.riscv.esp.movx.w.fft.bit.width(i32) #1

declare i32 @llvm.riscv.esp.movx.r.fft.bit.width(i32) #1

define dso_local i32 @test_movx_fft_bit_width_write_read_2p2(i32 noundef %rs1_val) local_unnamed_addr #2 {
; ASM2P2-LABEL: test_movx_fft_bit_width_write_read_2p2:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.movx.w.fft.bit.width a0
; ASM2P2-NEXT:    # kill: killed $x10
; ASM2P2-NEXT:    esp.movx.r.fft.bit.width a0
; ASM2P2-NEXT:    ret
;
; MIR-LABEL: name: test_movx_fft_bit_width_write_read_2p2
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $x10
; MIR-NEXT: {{  $}}
; MIR-NEXT:   [[COPY:%[0-9]+]]:gprpie = COPY $x10
; MIR-NEXT:   ESP_MOVX_W_FFT_BIT_WIDTH_2P2 [[COPY]]
; MIR-NEXT:   [[TOKEN:%[0-9]+]]:gprpie = COPY [[COPY]]
; MIR-NEXT:   [[RD:%[0-9]+]]:gprpie = ESP_MOVX_R_FFT_BIT_WIDTH_M_2P2_P killed [[TOKEN]]
; MIR-NEXT:   $x10 = COPY [[RD]]
; MIR-NEXT:   PseudoRET implicit $x10
entry:
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.fft.bit.width(i32 %rs1_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.r.fft.bit.width(i32 %v1)
  ret i32 %v2
}

define dso_local ptr @test_bitrev_with_fft_bit_width(ptr noundef %Rs1, ptr noundef %dst, i32 noundef %bit_width) local_unnamed_addr #2 {
; ASM-LABEL: test_bitrev_with_fft_bit_width:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.fft.bit.width a2
; ASM-NEXT:    esp.fft.bitrev q0, a0
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_bitrev_with_fft_bit_width:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.movx.w.fft.bit.width a2
; ASM2P2-NEXT:    # kill: killed $x12
; ASM2P2-NEXT:    esp.fft.bitrev q0, a0
; ASM2P2-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM2P2-NEXT:    mv a0, a1
; ASM2P2-NEXT:    ret
; MIR-LABEL: name: test_bitrev_with_fft_bit_width
; MIR: bb.0.entry:
; MIR-NEXT:   liveins: $x10, $x11, $x12
; MIR-NEXT: {{  $}}
; MIR-NEXT:   [[BW:%[0-9]+]]:gprpie = COPY $x12
; MIR-NEXT:   [[DST:%[0-9]+]]:gprpie = COPY $x11
; MIR-NEXT:   [[RS1:%[0-9]+]]:gprpie = COPY $x10
; MIR-NEXT:   ESP_MOVX_W_FFT_BIT_WIDTH_2P2 [[BW]]
; MIR-NEXT:   [[MOVX_OUT:%[0-9]+]]:gprpie = COPY [[BW]]
; MIR-NEXT:   [[RS1R:%[0-9]+]]:gprpie, [[QV:%[0-9]+]]:qr = ESP_FFT_BITREV_2P2_M_P [[RS1]], killed [[MOVX_OUT]]
; MIR-NEXT:   [[VST:%[0-9]+]]:gprpie = ESP_VST_128_IP_2P2 killed [[QV]], [[DST]], 16 :: (store (s128) into %ir.dst)
; MIR-NEXT:   $x10 = COPY [[VST]]
; MIR-NEXT:   PseudoRET implicit $x10
entry:
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.fft.bit.width(i32 %bit_width)
  %v2 = tail call { ptr, <8 x i16> } @llvm.riscv.esp.fft.bitrev.m(ptr %Rs1, i32 %v1)
  %ev1 = extractvalue { ptr, <8 x i16> } %v2, 1
  %bc1 = bitcast <8 x i16> %ev1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc1, ptr %dst, i32 16)
  %v3 = tail call i32 @llvm.riscv.esp.movx.r.fft.bit.width(i32 %v1)
  ret ptr %vst_ptr
}

declare { ptr, <8 x i16> } @llvm.riscv.esp.fft.bitrev.m(ptr, i32) #1

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #3

attributes #0 = { "target-features"="+32bit,+xespv2p1" }
attributes #1 = { nounwind }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { nounwind }
