; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vmul_s8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vmul_s8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.vmul.s8 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vmul.s8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 7, i32 %sar)
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vmul_s16_ld_incp(ptr noundef %src1, ptr noundef %src2, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qv, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qu, ptr noundef %src_ptr, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vmul_s16_ld_incp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.vmul.s16.ld.incp q1, a4, q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.vmul.s16.ld.incp(<8 x i16> %bc1, <8 x i16> %bc2, ptr %src_ptr, i32 0, i32 7, i32 %sar)
  %ev3 = extractvalue { <8 x i16>, <16 x i8>, ptr } %v1, 0
  %ev4 = extractvalue { <8 x i16>, <16 x i8>, ptr } %v1, 1
  store <8 x i16> %ev3, ptr %dst_qv, align 16
  store <16 x i8> %ev4, ptr %dst_qu, align 16
  ret void
}

define dso_local void @test_vmul_s8_st_incp(ptr noundef %src1, ptr noundef %src2, ptr noundef %Qu, ptr noundef %dst_ptr, ptr noundef %qv_src, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vmul_s8_st_incp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.vmul.s8.st.incp q2, a3, q0, q0, q1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %Qu, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %vld4 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %qv_src, i32 16)
  %ev4 = extractvalue { <16 x i8>, ptr } %vld4, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  tail call { <16 x i8>, ptr } @llvm.riscv.esp.vmul.s8.st.incp(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, ptr %dst_ptr, <16 x i8> %ev4, i32 0, i32 7, i32 %sar)
  ret void
}

define dso_local void @test_vmul_s16_s8xs8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst_qz, ptr noundef %dst_qv, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vmul_s16_s8xs8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a4
; ASM-NEXT:    esp.vmul.s16.s8xs8 q0, q1, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vmul.s16.s8xs8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 7, i32 %sar)
  %ev3 = extractvalue { <8 x i16>, <8 x i16> } %v1, 0
  %ev4 = extractvalue { <8 x i16>, <8 x i16> } %v1, 1
  store <8 x i16> %ev3, ptr %dst_qz, align 16
  store <8 x i16> %ev4, ptr %dst_qv, align 16
  ret void
}

declare i32 @llvm.riscv.esp.movx.w.sar(i32) #1
declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32 immarg) #2
declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32 immarg) #2
declare <16 x i8> @llvm.riscv.esp.vmul.s8(<16 x i8>, <16 x i8>, i32 immarg, i32 immarg, i32) #1
declare { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.vmul.s16.ld.incp(<8 x i16>, <8 x i16>, ptr, i32 immarg, i32 immarg, i32) #3
declare { <16 x i8>, ptr } @llvm.riscv.esp.vmul.s8.st.incp(<16 x i8>, <16 x i8>, <16 x i8>, ptr, <16 x i8>, i32 immarg, i32 immarg, i32) #3
declare { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vmul.s16.s8xs8(<16 x i8>, <16 x i8>, i32 immarg, i32 immarg, i32) #1

attributes #0 = { nounwind vscale_range(1,1) }
attributes #1 = { nounwind }
attributes #2 = { nounwind }
attributes #3 = { nounwind willreturn memory(argmem: readwrite) }
