; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-vsmulas.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local ptr @test_vsmulas_s8_qacc(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsmulas_s8_qacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a2, 0
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    li a0, 1
; ASM-NEXT:    esp.vsmulas.s8.qacc q0, q0, a0
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s8.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev1, <16 x i8> %ev1, i32 1, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, i32 0, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

declare <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32, i32) #1

define dso_local ptr @test_vsmulas_s16_qacc(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsmulas_s16_qacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a2, 0
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    li a0, 2
; ASM-NEXT:    esp.vsmulas.s16.qacc q0, q0, a0
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s16.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <8 x i16> %bc1, <8 x i16> %bc1, i32 2, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, i32 0, i32 1, i32 7)
  %bc2 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

declare <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32, i32) #1

define dso_local ptr @test_vsmulas_u8_qacc(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsmulas_u8_qacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a2, 0
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    li a0, 3
; ASM-NEXT:    esp.vsmulas.u8.qacc q0, q0, a0
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u8.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev1, <16 x i8> %ev1, i32 3, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, i32 0, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vsmulas_u16_qacc(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsmulas_u16_qacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a2, 0
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    li a0, 4
; ASM-NEXT:    esp.vsmulas.u16.qacc q0, q0, a0
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u16.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <8 x i16> %bc1, <8 x i16> %bc1, i32 4, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, i32 0, i32 1, i32 7)
  %bc2 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vsmulas_s8_qacc_old(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vsmulas_s8_qacc_old:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    li a0, 5
; ASM-NEXT:    esp.vsmulas.s8.qacc q0, q1, a0
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s8.qacc(<16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev1, <16 x i8> %ev2, i32 5, i32 0)
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, <16 x i8> %ev10, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vsmulas_s16_qacc_old(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vsmulas_s16_qacc_old:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    li a0, 7
; ASM-NEXT:    esp.vsmulas.s16.qacc q0, q1, a0
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s16.qacc(<16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <8 x i16> %bc1, <8 x i16> %bc2, i32 7, i32 0)
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, <16 x i8> %ev10, i32 %shift_amount, i32 1, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vsmulas_s8_qacc_ld_incp(ptr noundef %src1, ptr noundef readnone captures(none) %src2, ptr noundef readnone captures(none) %src3, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #2 {
; ASM-LABEL: test_vsmulas_s8_qacc_ld_incp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s8.qacc q0
; ASM-NEXT:    esp.vsmulas.s8.qacc.ld.incp q0, a0, q0, q1, 3
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a4, 1
; ASM-NEXT:    mv a0, a3
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8> %ev1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s8.qacc.ld.incp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 3, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vsmulas_u8_qacc_old(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vsmulas_u8_qacc_old:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    li a0, 9
; ASM-NEXT:    esp.vsmulas.u8.qacc q0, q1, a0
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u8.qacc(<16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev1, <16 x i8> %ev2, i32 9, i32 0)
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, <16 x i8> %ev10, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vsmulas_u16_qacc_old(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vsmulas_u16_qacc_old:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    li a0, 15
; ASM-NEXT:    esp.vsmulas.u16.qacc q0, q1, a0
; ASM-NEXT:    esp.srcmb.u16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u16.qacc(<16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <8 x i16> %bc1, <8 x i16> %bc2, i32 15, i32 0)
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, <16 x i8> %ev10, i32 %shift_amount, i32 1, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

declare <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32, i32, i32) #1

define dso_local ptr @test_vsmulas_s16_qacc_ld_incp(ptr noundef %src1, ptr noundef readnone captures(none) %src2, ptr noundef readnone captures(none) %src3, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #2 {
; ASM-LABEL: test_vsmulas_s16_qacc_ld_incp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s16.qacc q0
; ASM-NEXT:    esp.vsmulas.s16.qacc.ld.incp q0, a0, q0, q1, 2
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a4, 1
; ASM-NEXT:    mv a0, a3
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16> %bc1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s16.qacc.ld.incp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 2, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vsmulas_u16_qacc_ld_incp(ptr noundef %src1, ptr noundef readnone captures(none) %src2, ptr noundef readnone captures(none) %src3, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #2 {
; ASM-LABEL: test_vsmulas_u16_qacc_ld_incp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u16.qacc q0
; ASM-NEXT:    esp.vsmulas.u16.qacc.ld.incp q0, a0, q0, q1, 4
; ASM-NEXT:    esp.srcmb.u16.qacc q0, a4, 1
; ASM-NEXT:    mv a0, a3
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16> %bc1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u16.qacc.ld.incp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 4, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vsmulas_u8_qacc_ld_incp(ptr noundef %src1, ptr noundef readnone captures(none) %src2, ptr noundef readnone captures(none) %src3, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #2 {
; ASM-LABEL: test_vsmulas_u8_qacc_ld_incp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u8.qacc q0
; ASM-NEXT:    esp.vsmulas.u8.qacc.ld.incp q0, a0, q0, q1, 5
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a4, 1
; ASM-NEXT:    mv a0, a3
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8> %ev1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u8.qacc.ld.incp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 5, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}









declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #3

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc() #1

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s8.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32) #1

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #4

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32, i32) #1

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u8.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32) #1

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32, i32) #1

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8>) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s8.qacc.ld.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #3

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16>) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.s16.qacc.ld.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #3

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16>) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u16.qacc.ld.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #3

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8>) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vsmulas.u8.qacc.ld.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #3

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { nounwind }
attributes #4 = { nounwind }


