; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; PIE 2.1-only: CFG.vxsat_en (removed in PIE 2.2; use per-instruction sat).
; movx.r/w.cfg stays unified; +xespv masks writes to 7-bit writable CFG.
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ESP21
; RUN: llc -O2 -mattr=+xespv,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ESP22
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 -stop-after=finalize-isel %s -o - | FileCheck %s --check-prefix=MIR21
; RUN: llc -O2 -mattr=+xespv,+espv-lowering -mtriple=riscv32 -stop-after=finalize-isel %s -o - | FileCheck %s --check-prefix=MIR22

define dso_local void @test_movx_cfg_read_write() {
; ESP21-LABEL: test_movx_cfg_read_write:
; ESP21:       # %bb.0:
; ESP21-NEXT:    esp.movx.r.cfg a0
; ESP21-NEXT:    esp.movx.w.cfg a0
; ESP21-NEXT:    ret
;
; ESP22-LABEL: test_movx_cfg_read_write:
; ESP22:       # %bb.0:
; ESP22-NEXT:    esp.movx.r.cfg a0
; ESP22-NEXT:    andi a0, a0, 115
; ESP22-NEXT:    esp.movx.w.cfg a0
; ESP22-NEXT:    ret
; MIR21-LABEL: name: test_movx_cfg_read_write
; MIR21: bb.0 (%ir-block.0):
; MIR21-NEXT:   [[ESP_MOVX_R_CFG:%[0-9]+]]:gprpie = ESP_MOVX_R_CFG
; MIR21-NEXT:   ESP_MOVX_W_CFG killed [[ESP_MOVX_R_CFG]]
; MIR21-NEXT:   PseudoRET
;
; MIR22-LABEL: name: test_movx_cfg_read_write
; MIR22: bb.0 (%ir-block.0):
; MIR22-NEXT:   [[ESP_MOVX_R_CFG_2P2_:%[0-9]+]]:gprpie = ESP_MOVX_R_CFG_2P2
; MIR22-NEXT:   [[ANDI:%[0-9]+]]:gprpie = ANDI killed [[ESP_MOVX_R_CFG_2P2_]], 115
; MIR22-NEXT:   ESP_MOVX_W_CFG_2P2 killed [[ANDI]]
; MIR22-NEXT:   PseudoRET
  %cfg = tail call i32 @llvm.riscv.esp.movx.r.cfg()
  tail call void @llvm.riscv.esp.movx.w.cfg(i32 %cfg)
  ret void
}

define dso_local void @test_movx_w_cfg_vxrm() {
; ESP21-LABEL: test_movx_w_cfg_vxrm:
; ESP21:       # %bb.0:
; ESP21-NEXT:    li a0, 80
; ESP21-NEXT:    esp.movx.w.cfg a0
; ESP21-NEXT:    ret
;
; ESP22-LABEL: test_movx_w_cfg_vxrm:
; ESP22:       # %bb.0:
; ESP22-NEXT:    li a0, 80
; ESP22-NEXT:    esp.movx.w.cfg a0
; ESP22-NEXT:    ret
; MIR21-LABEL: name: test_movx_w_cfg_vxrm
; MIR21: bb.0 (%ir-block.0):
; MIR21-NEXT:   [[ADDI:%[0-9]+]]:gprpie = ADDI $x0, 80
; MIR21-NEXT:   ESP_MOVX_W_CFG killed [[ADDI]]
; MIR21-NEXT:   PseudoRET
;
; MIR22-LABEL: name: test_movx_w_cfg_vxrm
; MIR22: bb.0 (%ir-block.0):
; MIR22-NEXT:   [[ADDI:%[0-9]+]]:gprpie = ADDI $x0, 80
; MIR22-NEXT:   ESP_MOVX_W_CFG_2P2 killed [[ADDI]]
; MIR22-NEXT:   PseudoRET
  ; vxrm=5 in CFG[6:4] (0x50); valid on both PIE 2.1 and 2.2.
  tail call void @llvm.riscv.esp.movx.w.cfg(i32 80)
  ret void
}

define dso_local void @test_movx_w_cfg_vxsat_en_legacy() {
; ESP21-LABEL: test_movx_w_cfg_vxsat_en_legacy:
; ESP21:       # %bb.0:
; ESP21-NEXT:    li a0, 256
; ESP21-NEXT:    esp.movx.w.cfg a0
; ESP21-NEXT:    ret
;
; ESP22-LABEL: test_movx_w_cfg_vxsat_en_legacy:
; ESP22:       # %bb.0:
; ESP22-NEXT:    li a0, 0
; ESP22-NEXT:    esp.movx.w.cfg a0
; ESP22-NEXT:    ret
; MIR21-LABEL: name: test_movx_w_cfg_vxsat_en_legacy
; MIR21: bb.0 (%ir-block.0):
; MIR21-NEXT:   [[ADDI:%[0-9]+]]:gprpie = ADDI $x0, 256
; MIR21-NEXT:   ESP_MOVX_W_CFG killed [[ADDI]]
; MIR21-NEXT:   PseudoRET
;
; MIR22-LABEL: name: test_movx_w_cfg_vxsat_en_legacy
; MIR22: bb.0 (%ir-block.0):
; MIR22-NEXT:   [[COPY:%[0-9]+]]:gprpie = COPY $x0
; MIR22-NEXT:   ESP_MOVX_W_CFG_2P2 [[COPY]]
; MIR22-NEXT:   PseudoRET
  ; 0x100: legacy CFG bit outside PIE 2.2 7-bit layout (vxsat_en region on 2.1).
  tail call void @llvm.riscv.esp.movx.w.cfg(i32 256)
  ret void
}

declare i32 @llvm.riscv.esp.movx.r.cfg()
declare void @llvm.riscv.esp.movx.w.cfg(i32)
