; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-vmulas.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering,-xespv -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local ptr @test_vmulas_s8_qacc(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_s8_qacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.s8.qacc q0, q1
; ASM-NEXT:    esp.st.qacc.l.l.128.ip a2, 16
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc(<16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev1, <16 x i8> %ev2, i32 0)
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %v3 = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8> %ev7, ptr %dst, i32 16)
  ret ptr %v3
}

declare ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8>, ptr, i32) #1

define dso_local ptr @test_vmulas_s16_qacc(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_s16_qacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.s16.qacc q0, q1
; ASM-NEXT:    esp.st.qacc.l.l.128.ip a2, 16
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc(<16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <8 x i16> %bc1, <8 x i16> %bc2, i32 0)
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %v3 = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8> %ev7, ptr %dst, i32 16)
  ret ptr %v3
}

define dso_local ptr @test_vmulas_s8_qacc_ld_ip(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3) local_unnamed_addr #2 {
; ASM-LABEL: test_vmulas_s8_qacc_ld_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.s8.qacc.ld.ip q0, a2, 16, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ld.ip(<16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev1, <16 x i8> %ev2, ptr %src3, i32 16, i32 0)
  %ev7 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev7
}

define dso_local ptr @test_vmulas_s8_qacc_st_ip(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_s8_qacc_st_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.s8.qacc.st.ip q1, a2, 16, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.st.ip(<16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev2, <16 x i8> %ev1, <16 x i8> %ev2, ptr %dst, i32 16, i32 0)
  %ev7 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev7
}

define dso_local i32 @test_vmulas_s8_xacc(ptr noundef %src1, ptr noundef %src2) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s8_xacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.l zero
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.xacc.h zero
; ASM-NEXT:    esp.vmulas.s8.xacc q0, q1
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  tail call { i32, i32 } @llvm.riscv.esp.zero.xacc()
  %v1 = tail call { i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc(i32 0, i32 0, <16 x i8> %ev1, <16 x i8> %ev2, i32 0)
  %ev3 = extractvalue { i32, i32 } %v1, 0
  %v2 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 %ev3)
  ret i32 %v2
}

declare { i32, i32 } @llvm.riscv.esp.zero.xacc() #4

declare { i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc(i32, i32, <16 x i8>, <16 x i8>, i32) #5

declare i32 @llvm.riscv.esp.movx.r.xacc.l(i32) #5

define dso_local ptr @test_vmulas_s8_qacc_ldbc_incp(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3) local_unnamed_addr #2 {
; ASM-LABEL: test_vmulas_s8_qacc_ldbc_incp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vmulas.s8.qacc.ldbc.incp q0, a2, q0, q1
; ASM-NEXT:    mv a0, a2
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ldbc.incp(<16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev1, <16 x i8> %ev2, ptr %src3, i32 0)
  %ev7 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  ret ptr %ev7
}

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #6

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc() #5

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32) #5

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32) #5

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ld.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #6

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.st.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #1

declare { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ldbc.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32) #6

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { "target-features"="+32bit,+xespv" }
attributes #4 = { nounwind }
attributes #5 = { nounwind }
attributes #6 = { nounwind }


