; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM
; RUN: llc -O2 -mattr=+xespv,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM2P2

define dso_local void @test_vadd_s8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vadd_s8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vadd.s8 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vadd_s8:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM2P2-NEXT:    esp.vadd.s8 q0, q0, q1
; ASM2P2-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vadd.s8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0)
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsub_s8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsub_s8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsub.s8 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsub_s8:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM2P2-NEXT:    esp.vsub.s8 q0, q0, q1
; ASM2P2-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vsub.s8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0)
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsadds_s8(ptr noundef %src1, ptr noundef %dst, i32 noundef %rs1) local_unnamed_addr #0 {
; ASM-LABEL: test_vsadds_s8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vsadds.s8 q0, q0, a2
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsadds_s8:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.vsadds.s8 q0, q0, a2
; ASM2P2-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vsadds.s8(<16 x i8> %ev1, i32 %rs1, i32 0)
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32 immarg) nounwind
declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32 immarg) nounwind
declare <16 x i8> @llvm.riscv.esp.vadd.s8(<16 x i8>, <16 x i8>, i32 immarg) nounwind
declare <16 x i8> @llvm.riscv.esp.vsub.s8(<16 x i8>, <16 x i8>, i32 immarg) nounwind
declare <16 x i8> @llvm.riscv.esp.vsadds.s8(<16 x i8>, i32, i32 immarg) nounwind

attributes #0 = { nounwind vscale_range(1,1) }
