; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-ld-st-qacc-ip.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local ptr @test_ld_st_qacc_h_l_128_ip_m(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_ld_st_qacc_h_l_128_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.qacc.h.l.128.ip a0, 16
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.st.qacc.h.l.128.ip a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.h.l.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %v1, 0
  %v2 = tail call ptr @llvm.riscv.esp.st.qacc.h.l.128.ip(<16 x i8> %ev1, ptr %dst, i32 16)
  ret ptr %v2
}

declare ptr @llvm.riscv.esp.st.qacc.h.l.128.ip(<16 x i8>, ptr, i32) #1

define dso_local ptr @test_ld_st_qacc_l_h_128_ip_m(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_ld_st_qacc_l_h_128_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.qacc.l.h.128.ip a0, 16
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.st.qacc.l.h.128.ip a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.l.h.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %v1, 0
  %v2 = tail call ptr @llvm.riscv.esp.st.qacc.l.h.128.ip(<16 x i8> %ev1, ptr %dst, i32 16)
  ret ptr %v2
}

declare ptr @llvm.riscv.esp.st.qacc.l.h.128.ip(<16 x i8>, ptr, i32) #1

define dso_local ptr @test_ld_st_qacc_h_h_128_ip_m(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_ld_st_qacc_h_h_128_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.qacc.h.h.128.ip a0, 16
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.st.qacc.h.h.128.ip a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.h.h.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %v1, 0
  %v2 = tail call ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8> %ev1, ptr %dst, i32 16)
  ret ptr %v2
}

declare ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8>, ptr, i32) #1

define dso_local ptr @test_ld_st_qacc_l_l_128_ip_m(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_ld_st_qacc_l_l_128_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.qacc.l.l.128.ip a0, 16
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.st.qacc.l.l.128.ip a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.l.l.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %v1, 0
  %v2 = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8> %ev1, ptr %dst, i32 16)
  ret ptr %v2
}

declare ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8>, ptr, i32) #1

define dso_local ptr @test_ldqa_s16_128_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_ldqa_s16_128_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ldqa.s16.128.ip a0, 16
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.s16.128.ip(<64 x i8> undef, ptr %src, i32 16)
  %ev1 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev2 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev3 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %ev4 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 4
  %v2 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 %shift_amount, i32 1, i32 7)
  %bc1 = bitcast <8 x i16> %v2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc1, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

declare <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32, i32 immarg) #2

define dso_local ptr @test_ldqa_s16_128_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_ldqa_s16_128_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ldqa.s16.128.xp a0, a2
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.s16.128.xp(<64 x i8> undef, ptr %src, i32 %Reg)
  %ev1 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev2 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev3 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %ev4 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 4
  %v2 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 %shift_amount, i32 1, i32 7)
  %bc1 = bitcast <8 x i16> %v2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc1, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_ldqa_s8_128_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_ldqa_s8_128_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ldqa.s8.128.ip a0, 16
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.s8.128.ip(<64 x i8> undef, ptr %src, i32 16)
  %ev1 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev2 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev3 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %ev4 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 4
  %v2 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

declare <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32, i32 immarg) #2

define dso_local ptr @test_ldqa_s8_128_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_ldqa_s8_128_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ldqa.s8.128.xp a0, a2
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.s8.128.xp(<64 x i8> undef, ptr %src, i32 %Reg)
  %ev1 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev2 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev3 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %ev4 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 4
  %v2 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_ldqa_u16_128_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_ldqa_u16_128_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ldqa.u16.128.ip a0, 16
; ASM-NEXT:    esp.srcmb.u16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.u16.128.ip(<64 x i8> undef, ptr %src, i32 16)
  %ev1 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev2 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev3 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %ev4 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 4
  %v2 = tail call <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 %shift_amount, i32 1, i32 0, i32 7)
  %bc1 = bitcast <8 x i16> %v2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc1, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

declare <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32, i32, i32 immarg) #2

define dso_local ptr @test_ldqa_u16_128_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_ldqa_u16_128_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ldqa.u16.128.xp a0, a2
; ASM-NEXT:    esp.srcmb.u16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.u16.128.xp(<64 x i8> undef, ptr %src, i32 %Reg)
  %ev1 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev2 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev3 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %ev4 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 4
  %v2 = tail call <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 %shift_amount, i32 1, i32 0, i32 7)
  %bc1 = bitcast <8 x i16> %v2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc1, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_ldqa_u8_128_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_ldqa_u8_128_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ldqa.u8.128.ip a0, 16
; ASM-NEXT:    esp.srcmb.u8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.u8.128.ip(<64 x i8> undef, ptr %src, i32 16)
  %ev1 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev2 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev3 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %ev4 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 4
  %v2 = tail call <16 x i8> @llvm.riscv.esp.srcmb.u8.qacc(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 %shift_amount, i32 1, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

declare <16 x i8> @llvm.riscv.esp.srcmb.u8.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32, i32, i32, i32 immarg) #2

define dso_local ptr @test_ldqa_u8_128_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_ldqa_u8_128_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ldqa.u8.128.xp a0, a2
; ASM-NEXT:    esp.srcmb.u8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.u8.128.xp(<64 x i8> undef, ptr %src, i32 %Reg)
  %ev1 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev2 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev3 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %ev4 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 4
  %v2 = tail call <16 x i8> @llvm.riscv.esp.srcmb.u8.qacc(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 %shift_amount, i32 1, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_mov_s16_qacc_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_mov_s16_qacc_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.mov.s16.qacc q0
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16> %bc1)
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, i32 %shift_amount, i32 1, i32 7)
  %bc2 = bitcast <8 x i16> %v2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_mov_s8_qacc_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_mov_s8_qacc_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.mov.s8.qacc q0
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8> %ev1)
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_mov_u16_qacc_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_mov_u16_qacc_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.mov.u16.qacc q0
; ASM-NEXT:    esp.srcmb.u16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16> %bc1)
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, i32 %shift_amount, i32 1, i32 0, i32 7)
  %bc2 = bitcast <8 x i16> %v2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_mov_u8_qacc_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_mov_u8_qacc_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.mov.u8.qacc q0
; ASM-NEXT:    esp.srcmb.u8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8> %ev1)
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call <16 x i8> @llvm.riscv.esp.srcmb.u8.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, i32 %shift_amount, i32 1, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_s16_qacc_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_s16_qacc_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.mov.s16.qacc q0
; ASM-NEXT:    esp.vmulas.s16.qacc q0, q0
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16> %bc1)
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <8 x i16> %bc1, <8 x i16> %bc1, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, i32 %shift_amount, i32 1, i32 7)
  %bc2 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_s16_qacc_ld_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s16_qacc_ld_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s16.qacc q0
; ASM-NEXT:    esp.vmulas.s16.qacc.ld.ip q0, a0, 16, q0, q1
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16> %bc1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.ld.ip(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 16, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_s16_qacc_ld_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s16_qacc_ld_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s16.qacc q0
; ASM-NEXT:    esp.vmulas.s16.qacc.ld.xp q0, a0, a2, q0, q1
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16> %bc1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.ld.xp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 %Reg, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_s16_qacc_st_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s16_qacc_st_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s16.qacc q0
; ASM-NEXT:    esp.vmulas.s16.qacc.st.ip q1, a1, 16, q0, q1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16> %bc1)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.st.ip(<16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev3, <8 x i16> %bc1, <8 x i16> %bc2, ptr %dst, i32 16, i32 0)
  %ev8 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev8
}

define dso_local ptr @test_vmulas_s16_qacc_st_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s16_qacc_st_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s16.qacc q0
; ASM-NEXT:    esp.vmulas.s16.qacc.st.xp q1, a1, a2, q0, q1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16> %bc1)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.st.xp(<16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev3, <8 x i16> %bc1, <8 x i16> %bc2, ptr %dst, i32 %Reg, i32 0)
  %ev8 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev8
}

define dso_local ptr @test_vmulas_s8_qacc_ld_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s8_qacc_ld_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s8.qacc q0
; ASM-NEXT:    esp.vmulas.s8.qacc.ld.ip q0, a0, 16, q0, q1
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8> %ev1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ld.ip(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 16, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_s8_qacc_ld_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s8_qacc_ld_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s8.qacc q0
; ASM-NEXT:    esp.vmulas.s8.qacc.ld.xp q0, a0, a2, q0, q1
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8> %ev1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ld.xp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 %Reg, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_s8_qacc_st_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s8_qacc_st_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s8.qacc q0
; ASM-NEXT:    esp.vmulas.s8.qacc.st.ip q1, a1, 16, q0, q1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8> %ev1)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.st.ip(<16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev3, <16 x i8> %ev1, <16 x i8> %ev3, ptr %dst, i32 16, i32 0)
  %ev8 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev8
}

define dso_local ptr @test_vmulas_s8_qacc_st_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s8_qacc_st_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s8.qacc q0
; ASM-NEXT:    esp.vmulas.s8.qacc.st.xp q1, a1, a2, q0, q1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8> %ev1)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.st.xp(<16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev3, <16 x i8> %ev1, <16 x i8> %ev3, ptr %dst, i32 %Reg, i32 0)
  %ev8 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev8
}

define dso_local ptr @test_vmulas_u16_qacc_st_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u16_qacc_st_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u16.qacc q0
; ASM-NEXT:    esp.vmulas.u16.qacc.st.ip q1, a1, 16, q0, q1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16> %bc1)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.st.ip(<16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev3, <8 x i16> %bc1, <8 x i16> %bc2, ptr %dst, i32 16, i32 0)
  %ev8 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev8
}

define dso_local ptr @test_vmulas_u16_qacc_st_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u16_qacc_st_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u16.qacc q0
; ASM-NEXT:    esp.vmulas.u16.qacc.st.xp q1, a1, a2, q0, q1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16> %bc1)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.st.xp(<16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev3, <8 x i16> %bc1, <8 x i16> %bc2, ptr %dst, i32 %Reg, i32 0)
  %ev8 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev8
}

define dso_local ptr @test_vmulas_u16_qacc_ld_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u16_qacc_ld_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u16.qacc q0
; ASM-NEXT:    esp.vmulas.u16.qacc.ld.ip q0, a0, 16, q0, q1
; ASM-NEXT:    esp.srcmb.u16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16> %bc1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.ld.ip(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 16, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_u16_qacc_ld_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u16_qacc_ld_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u16.qacc q0
; ASM-NEXT:    esp.vmulas.u16.qacc.ld.xp q0, a0, a2, q0, q1
; ASM-NEXT:    esp.srcmb.u16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16> %bc1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.ld.xp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 %Reg, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_u8_qacc_ld_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u8_qacc_ld_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u8.qacc q0
; ASM-NEXT:    esp.vmulas.u8.qacc.ld.ip q0, a0, 16, q0, q1
; ASM-NEXT:    esp.srcmb.u8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8> %ev1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.ld.ip(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 16, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.u8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_u8_qacc_ld_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u8_qacc_ld_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u8.qacc q0
; ASM-NEXT:    esp.vmulas.u8.qacc.ld.xp q0, a0, a2, q0, q1
; ASM-NEXT:    esp.srcmb.u8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8> %ev1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.ld.xp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 %Reg, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.u8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_s8_qacc_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_s8_qacc_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.mov.s8.qacc q0
; ASM-NEXT:    esp.vmulas.s8.qacc q0, q0
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8> %ev1)
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev1, <16 x i8> %ev1, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_u16_qacc_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_u16_qacc_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.mov.u16.qacc q0
; ASM-NEXT:    esp.vmulas.u16.qacc q0, q0
; ASM-NEXT:    esp.srcmb.u16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16> %bc1)
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <8 x i16> %bc1, <8 x i16> %bc1, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, i32 %shift_amount, i32 1, i32 0, i32 7)
  %bc2 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_u8_qacc_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vmulas_u8_qacc_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.mov.u8.qacc q0
; ASM-NEXT:    esp.vmulas.u8.qacc q0, q0
; ASM-NEXT:    esp.srcmb.u8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8> %ev1)
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev1, <16 x i8> %ev1, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 1
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev9 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.u8.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev9, i32 %shift_amount, i32 1, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_u8_qacc_st_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u8_qacc_st_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u8.qacc q0
; ASM-NEXT:    esp.vmulas.u8.qacc.st.ip q1, a1, 16, q0, q1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8> %ev1)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.st.ip(<16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev3, <16 x i8> %ev1, <16 x i8> %ev3, ptr %dst, i32 16, i32 0)
  %ev8 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev8
}

define dso_local ptr @test_vmulas_u8_qacc_st_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u8_qacc_st_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u8.qacc q0
; ASM-NEXT:    esp.vmulas.u8.qacc.st.xp q1, a1, a2, q0, q1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8> %ev1)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.st.xp(<16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev3, <16 x i8> %ev1, <16 x i8> %ev3, ptr %dst, i32 %Reg, i32 0)
  %ev8 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 0
  ret ptr %ev8
}

define dso_local ptr @test_vmulas_s16_qacc_ldbc_incp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s16_qacc_ldbc_incp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s16.qacc q0
; ASM-NEXT:    esp.vmulas.s16.qacc.ldbc.incp q0, a0, q0, q1
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16> %bc1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.ldbc.incp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 0)
  %ev9 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_s8_qacc_ldbc_incp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s8_qacc_ldbc_incp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.s8.qacc q0
; ASM-NEXT:    esp.vmulas.s8.qacc.ldbc.incp q0, a0, q0, q1
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8> %ev1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ldbc.incp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 0)
  %ev9 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_u16_qacc_ldbc_incp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u16_qacc_ldbc_incp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u16.qacc q0
; ASM-NEXT:    esp.vmulas.u16.qacc.ldbc.incp q0, a0, q0, q1
; ASM-NEXT:    esp.srcmb.u16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16> %bc1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.ldbc.incp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 0)
  %ev9 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.u16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vmulas_u8_qacc_ldbc_incp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u8_qacc_ldbc_incp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.mov.u8.qacc q0
; ASM-NEXT:    esp.vmulas.u8.qacc.ldbc.incp q0, a0, q0, q1
; ASM-NEXT:    esp.srcmb.u8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8> %ev1)
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.ldbc.incp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 0)
  %ev9 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %ev11 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 4
  %ev12 = extractvalue { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 5
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.u8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev11, <16 x i8> %ev12, i32 %shift_amount, i32 1, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s16_qacc_h_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s16_qacc_h_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.h q0, q0
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8> %ev4, <16 x i8> %ev5, <8 x i16> %bc1, <8 x i16> %bc1, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev6, <16 x i8> %ev7, i32 %shift_amount, i32 1, i32 7)
  %bc2 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s16_qacc_l_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s16_qacc_l_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.l q0, q0
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l(<16 x i8> %ev2, <16 x i8> %ev3, <8 x i16> %bc1, <8 x i16> %bc1, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev4, <16 x i8> %ev5, i32 %shift_amount, i32 1, i32 7)
  %bc2 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s8_qacc_h_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s8_qacc_h_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s8.qacc.h q0, q0
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h(<16 x i8> %ev4, <16 x i8> %ev5, <16 x i8> %ev1, <16 x i8> %ev1, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev6, <16 x i8> %ev7, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s8_qacc_l_m(ptr noundef %src, ptr noundef %dst, i32 noundef %Reg, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s8_qacc_l_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s8.qacc.l q0, q0
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a3, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.l(<16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev1, <16 x i8> %ev1, i32 0)
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev7 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev6, <16 x i8> %ev7, <16 x i8> %ev4, <16 x i8> %ev5, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s16_qacc_h_ld_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vcmulas_s16_qacc_h_ld_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.h.ld.ip q0, a0, 16, q0, q1
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev5 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev6 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev5 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev6, i32 16)
  %ev7 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev8 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev7 to <8 x i16>
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h.ld.ip(<16 x i8> %ev3, <16 x i8> %ev4, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev8, i32 16, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev9, <16 x i8> %ev10, i32 %shift_amount, i32 1, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s16_qacc_l_ld_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vcmulas_s16_qacc_l_ld_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.l.ld.ip q0, a0, 16, q0, q1
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l.ld.ip(<16 x i8> %ev5, <16 x i8> %ev6, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 16, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev7, <16 x i8> %ev8, i32 %shift_amount, i32 1, i32 7)
  %bc3 = bitcast <8 x i16> %v3 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s8_qacc_h_ld_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vcmulas_s8_qacc_h_ld_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s8.qacc.h.ld.ip q0, a0, 16, q0, q1
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h.ld.ip(<16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 16, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev9, <16 x i8> %ev10, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s8_qacc_l_ld_ip_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount) local_unnamed_addr #3 {
; ASM-LABEL: test_vcmulas_s8_qacc_l_ld_ip_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a0, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s8.qacc.l.ld.ip q0, a0, 16, q0, q1
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %vld1, 1
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %ev2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 1
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.l.ld.ip(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 16, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v2, 3
  %v3 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev7, <16 x i8> %ev8, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s16_qacc_h_ld_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount, i32 noundef %offset_reg) local_unnamed_addr #3 {
; ASM-LABEL: test_vcmulas_s16_qacc_h_ld_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.xp q0, a0, a3
; ASM-NEXT:    esp.vld.128.xp q1, a0, a3
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.h.ld.xp q0, a0, a3, q0, q1
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr %src, i32 %offset_reg)
  %ev1 = extractvalue { <16 x i8>, ptr } %v1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %v1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr %ev2, i32 %offset_reg)
  %ev3 = extractvalue { <16 x i8>, ptr } %v2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %v2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v3 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 3
  %v4 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h.ld.xp(<16 x i8> %ev7, <16 x i8> %ev8, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 %offset_reg, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v4, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v4, 3
  %v5 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev9, <16 x i8> %ev10, i32 %shift_amount, i32 1, i32 7)
  %bc3 = bitcast <8 x i16> %v5 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s16_qacc_l_ld_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount, i32 noundef %offset_reg) local_unnamed_addr #3 {
; ASM-LABEL: test_vcmulas_s16_qacc_l_ld_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.xp q0, a0, a3
; ASM-NEXT:    esp.vld.128.xp q1, a0, a3
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.l.ld.xp q0, a0, a3, q0, q1
; ASM-NEXT:    esp.srcmb.s16.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr %src, i32 %offset_reg)
  %ev1 = extractvalue { <16 x i8>, ptr } %v1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %v1, 1
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr %ev2, i32 %offset_reg)
  %ev3 = extractvalue { <16 x i8>, ptr } %v2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %v2, 1
  %bc2 = bitcast <16 x i8> %ev3 to <8 x i16>
  %v3 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 3
  %v4 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l.ld.xp(<16 x i8> %ev5, <16 x i8> %ev6, <8 x i16> %bc1, <8 x i16> %bc2, ptr %ev4, i32 %offset_reg, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v4, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v4, 3
  %v5 = tail call <8 x i16> @llvm.riscv.esp.srcmb.s16.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev7, <16 x i8> %ev8, i32 %shift_amount, i32 1, i32 7)
  %bc3 = bitcast <8 x i16> %v5 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s8_qacc_h_ld_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount, i32 noundef %offset_reg) local_unnamed_addr #3 {
; ASM-LABEL: test_vcmulas_s8_qacc_h_ld_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.xp q0, a0, a3
; ASM-NEXT:    esp.vld.128.xp q1, a0, a3
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s8.qacc.h.ld.xp q0, a0, a3, q0, q1
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr %src, i32 %offset_reg)
  %ev1 = extractvalue { <16 x i8>, ptr } %v1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %v1, 1
  %v2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr %ev2, i32 %offset_reg)
  %ev3 = extractvalue { <16 x i8>, ptr } %v2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %v2, 1
  %v3 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 3
  %v4 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h.ld.xp(<16 x i8> %ev7, <16 x i8> %ev8, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 %offset_reg, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v4, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v4, 3
  %v5 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev9, <16 x i8> %ev10, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v5, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

define dso_local ptr @test_vcmulas_s8_qacc_l_ld_xp_m(ptr noundef %src, ptr noundef %dst, i32 noundef %shift_amount, i32 noundef %offset_reg) local_unnamed_addr #3 {
; ASM-LABEL: test_vcmulas_s8_qacc_l_ld_xp_m:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.xp q0, a0, a3
; ASM-NEXT:    esp.vld.128.xp q1, a0, a3
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s8.qacc.l.ld.xp q0, a0, a3, q0, q1
; ASM-NEXT:    esp.srcmb.s8.qacc q0, a2, 1
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr %src, i32 %offset_reg)
  %ev1 = extractvalue { <16 x i8>, ptr } %v1, 0
  %ev2 = extractvalue { <16 x i8>, ptr } %v1, 1
  %v2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr %ev2, i32 %offset_reg)
  %ev3 = extractvalue { <16 x i8>, ptr } %v2, 0
  %ev4 = extractvalue { <16 x i8>, ptr } %v2, 1
  %v3 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 1
  %ev7 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 2
  %ev8 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v3, 3
  %v4 = tail call { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.l.ld.xp(<16 x i8> %ev5, <16 x i8> %ev6, <16 x i8> %ev1, <16 x i8> %ev3, ptr %ev4, i32 %offset_reg, i32 0)
  %ev9 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v4, 2
  %ev10 = extractvalue { ptr, <16 x i8>, <16 x i8>, <16 x i8> } %v4, 3
  %v5 = tail call <16 x i8> @llvm.riscv.esp.srcmb.s8.qacc(<16 x i8> %ev9, <16 x i8> %ev10, <16 x i8> %ev7, <16 x i8> %ev8, i32 %shift_amount, i32 1, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v5, ptr %dst, i32 16)
  ret ptr %vst_ptr
}

declare { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.h.l.128.ip(ptr, i32) #4

declare { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.l.h.128.ip(ptr, i32) #4

declare { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.h.h.128.ip(ptr, i32) #4

declare { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.l.l.128.ip(ptr, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.s16.128.ip(<64 x i8>, ptr, i32) #4

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.s16.128.xp(<64 x i8>, ptr, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.s8.128.ip(<64 x i8>, ptr, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.s8.128.xp(<64 x i8>, ptr, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.u16.128.ip(<64 x i8>, ptr, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.u16.128.xp(<64 x i8>, ptr, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.u8.128.ip(<64 x i8>, ptr, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.ldqa.u8.128.xp(<64 x i8>, ptr, i32) #4

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #4

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc(<8 x i16>) #2

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc(<16 x i8>) #2

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u16.qacc(<8 x i16>) #2

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.u8.qacc(<16 x i8>) #2

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32) #2

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.ld.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.ld.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.st.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.st.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ld.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ld.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.st.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.st.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.st.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.st.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.ld.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.ld.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.ld.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.ld.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #4

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32) #2

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32) #2

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32) #2

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.st.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #1

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.st.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #1

declare { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s16.qacc.ldbc.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32) #4

declare { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.s8.qacc.ldbc.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32) #4

declare { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u16.qacc.ldbc.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32) #4

declare { <16 x i8>, ptr, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vmulas.u8.qacc.ldbc.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32) #4

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc() #2

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32 immarg) #2

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32 immarg) #2

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32 immarg) #2

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.l(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32 immarg) #2

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h.ld.ip(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32 immarg) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l.ld.ip(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32 immarg) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h.ld.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32 immarg) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.l.ld.ip(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32 immarg) #4

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr, i32) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h.ld.xp(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32 immarg) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l.ld.xp(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32 immarg) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h.ld.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32 immarg) #4

declare { ptr, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.l.ld.xp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32 immarg) #4

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { nounwind }
attributes #3 = { "target-features"="+32bit,+xespv" }
attributes #4 = { nounwind }


