; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-clamp-relu.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vclamp_s16(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vclamp_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vclamp.s16 q0, q0, 5
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vclamp.s16(<8 x i16> %bc1, i32 5)
  %bc2 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vclamp.s16(<8 x i16>, i32 immarg) #1

define dso_local void @test_vprelu_s8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %shift) local_unnamed_addr #0 {
; ASM-LABEL: test_vprelu_s8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vprelu.s8 q0, q1, q0, a3
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vprelu.s8(<16 x i8> %ev1, <16 x i8> %ev2, i32 %shift, i32 0, i32 7)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vprelu.s8(<16 x i8>, <16 x i8>, i32, i32 immarg, i32 immarg) #1

define dso_local void @test_vprelu_s16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %shift) local_unnamed_addr #0 {
; ASM-LABEL: test_vprelu_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vprelu.s16 q0, q1, q0, a3
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vprelu.s16(<8 x i16> %bc1, <8 x i16> %bc2, i32 %shift, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vprelu.s16(<8 x i16>, <8 x i16>, i32, i32 immarg, i32 immarg) #1

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #2

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #3

attributes #0 = { "target-features"="+32bit,+xespv2p1" }
attributes #1 = { nounwind }
attributes #2 = { nounwind }
attributes #3 = { nounwind }

