; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-bitwise.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_andq(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_andq:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.andq q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.andq(<16 x i8> %ev1, <16 x i8> %ev2)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.andq(<16 x i8>, <16 x i8>) #1

define dso_local void @test_orq(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_orq:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.orq q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.orq(<16 x i8> %ev1, <16 x i8> %ev2)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.orq(<16 x i8>, <16 x i8>) #1

define dso_local void @test_xorq(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_xorq:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.xorq q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.xorq(<16 x i8> %ev1, <16 x i8> %ev2)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.xorq(<16 x i8>, <16 x i8>) #1

define dso_local void @test_notq(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_notq:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.notq q0, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.notq(<16 x i8> %ev1)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.notq(<16 x i8>) #1

define dso_local void @test_zero_q(ptr noundef %dst) local_unnamed_addr #2 {
; ASM-LABEL: test_zero_q:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.zero.q q0
; ASM-NEXT:    esp.vst.128.ip q0, a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call <16 x i8> @llvm.riscv.esp.zero.q()
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.zero.q() #1

define dso_local void @test_zero_qacc(ptr noundef %dst) local_unnamed_addr #2 {
; ASM-LABEL: test_zero_qacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.st.qacc.l.l.128.ip a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %v2 = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8> %ev1, ptr %dst, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc() #1

declare ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8>, ptr, i32) #3

define dso_local void @test_zero_qacc_use_l(ptr noundef %dst, ptr noundef readonly captures(none) %Qx, ptr noundef readonly captures(none) %Qy) local_unnamed_addr #0 {
; ASM-LABEL: test_zero_qacc_use_l:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.l q0, q1
; ASM-NEXT:    esp.st.qacc.l.l.128.ip a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %v2 = load <8 x i16>, ptr %Qx, align 16, !tbaa !27
  %v3 = load <8 x i16>, ptr %Qy, align 16, !tbaa !27
  %v4 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l(<16 x i8> %ev1, <16 x i8> %ev2, <8 x i16> %v2, <8 x i16> %v3, i32 0)
  %ev3 = extractvalue { <16 x i8>, <16 x i8> } %v4, 0
  %v5 = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8> %ev3, ptr %dst, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32 immarg) #1

define dso_local void @test_zero_qacc_use_h(ptr noundef %dst, ptr noundef readonly captures(none) %Qx, ptr noundef readonly captures(none) %Qy) local_unnamed_addr #0 {
; ASM-LABEL: test_zero_qacc_use_h:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.h q0, q1
; ASM-NEXT:    esp.st.qacc.h.h.128.ip a0, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = load <8 x i16>, ptr %Qx, align 16, !tbaa !27
  %v3 = load <8 x i16>, ptr %Qy, align 16, !tbaa !27
  %v4 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8> %ev1, <16 x i8> %ev2, <8 x i16> %v2, <8 x i16> %v3, i32 0)
  %ev3 = extractvalue { <16 x i8>, <16 x i8> } %v4, 1
  %v5 = tail call ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8> %ev3, ptr %dst, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32 immarg) #1

declare ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8>, ptr, i32) #3

define dso_local ptr @test_zero_qacc_use_both(ptr noundef %dst_l, ptr noundef %dst_h) local_unnamed_addr #2 {
; ASM-LABEL: test_zero_qacc_use_both:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.st.qacc.l.l.128.ip a0, 16
; ASM-NEXT:    esp.st.qacc.h.h.128.ip a1, 16
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %v2 = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8> %ev1, ptr %dst_l, i32 16)
  %v3 = tail call ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8> %ev2, ptr %dst_h, i32 16)
  ret ptr %v3
}

define dso_local ptr @test_zero_xacc_store(ptr noundef %Ptr) local_unnamed_addr #4 {
; ASM-LABEL: test_zero_xacc_store:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.l zero
; ASM-NEXT:    esp.movx.w.xacc.h zero
; ASM-NEXT:    esp.st.s.xacc.ip a0, 16
; ASM-NEXT:    ret
entry:
  %zero_xacc_tmp1 = tail call { i32, i32 } @llvm.riscv.esp.zero.xacc()
  %v1 = tail call { ptr, i32, i32 } @llvm.riscv.esp.st.s.xacc.ip(i32 0, i32 0, ptr %Ptr, i32 16)
  %ev1 = extractvalue { ptr, i32, i32 } %v1, 0
  ret ptr %ev1
}

declare { i32, i32 } @llvm.riscv.esp.zero.xacc() #5

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #6

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #3

declare { ptr, i32, i32 } @llvm.riscv.esp.st.s.xacc.ip(i32, i32, ptr, i32) #3

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { nounwind }
attributes #4 = { "target-features"="+32bit,+xespv" }
attributes #5 = { nounwind }
attributes #6 = { nounwind }


!27 = !{!28, !28, i64 0}
!28 = !{!"omnipotent char", !29, i64 0}
!29 = !{!"Simple C/C++ TBAA"}
