; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-load-store-64-128-split.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_64_to_128(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_64_to_128:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.h.64.ip q0, a0, 8
; ASM-NEXT:    esp.vld.l.64.ip q0, a0, 8
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr %src, i32 8)
  %ev1 = extractvalue { <8 x i8>, ptr } %v1, 0
  %ev2 = extractvalue { <8 x i8>, ptr } %v1, 1
  %v2 = tail call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr %ev2, i32 8)
  %ev3 = extractvalue { <8 x i8>, ptr } %v2, 0
  %shuffle = shufflevector <8 x i8> %ev3, <8 x i8> %ev1, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %shuffle, ptr %dst, i32 16)
  ret void
}

define dso_local ptr @test_128_to_64(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #1 {
; ASM-LABEL: test_128_to_64:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.h.64.ip q0, a0, 8
; ASM-NEXT:    esp.vst.l.64.ip q0, a0, 8
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %U.sroa.0.8.vec.extract3.i = shufflevector <16 x i8> %ev1, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %v1 = tail call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> %U.sroa.0.8.vec.extract3.i, ptr %dst, i32 8)
  %U.sroa.0.0.vec.extract3.i = shufflevector <16 x i8> %ev1, <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %v2 = tail call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> %U.sroa.0.0.vec.extract3.i, ptr %v1, i32 8)
  ret ptr %v2
}

define dso_local void @test_64_to_128_xp(ptr noundef %src, ptr noundef %dst, i32 noundef %stride_reg) local_unnamed_addr #0 {
; ASM-LABEL: test_64_to_128_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.h.64.xp q0, a0, a2
; ASM-NEXT:    esp.vld.l.64.xp q0, a0, a2
; ASM-NEXT:    esp.vst.128.xp q0, a1, a2
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.xp(ptr %src, i32 %stride_reg)
  %ev1 = extractvalue { <8 x i8>, ptr } %v1, 0
  %ev2 = extractvalue { <8 x i8>, ptr } %v1, 1
  %v2 = tail call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.xp(ptr %ev2, i32 %stride_reg)
  %ev3 = extractvalue { <8 x i8>, ptr } %v2, 0
  %shuffle = shufflevector <8 x i8> %ev3, <8 x i8> %ev1, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %v3 = tail call ptr @llvm.riscv.esp.vst.128.xp(<16 x i8> %shuffle, ptr %dst, i32 %stride_reg)
  ret void
}

define dso_local ptr @test_128_to_64_xp(ptr noundef %src, ptr noundef %dst, i32 noundef %stride_reg) local_unnamed_addr #1 {
; ASM-LABEL: test_128_to_64_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.xp q0, a0, a2
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    esp.vst.h.64.xp q0, a0, a2
; ASM-NEXT:    esp.vst.l.64.xp q0, a0, a2
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr %src, i32 %stride_reg)
  %ev1 = extractvalue { <16 x i8>, ptr } %v1, 0
  %U.sroa.0.8.vec.extract3.i = shufflevector <16 x i8> %ev1, <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %v2 = tail call ptr @llvm.riscv.esp.vst.h.64.xp(<8 x i8> %U.sroa.0.8.vec.extract3.i, ptr %dst, i32 %stride_reg)
  %U.sroa.0.0.vec.extract3.i = shufflevector <16 x i8> %ev1, <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %v3 = tail call ptr @llvm.riscv.esp.vst.l.64.xp(<8 x i8> %U.sroa.0.0.vec.extract3.i, ptr %v2, i32 %stride_reg)
  ret ptr %v3
}

define dso_local void @test_movi_8_a_subregister(ptr noundef %src, ptr noundef writeonly captures(none) initializes((0, 24)) %dst) local_unnamed_addr #2 {
; ASM-LABEL: test_movi_8_a_subregister:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movi.8.a q0, a0, 0
; ASM-NEXT:    esp.movi.8.a q0, a2, 3
; ASM-NEXT:    esp.movi.8.a q0, a3, 7
; ASM-NEXT:    esp.movi.8.a q0, a4, 8
; ASM-NEXT:    esp.movi.8.a q0, a5, 11
; ASM-NEXT:    sw a0, 0(a1)
; ASM-NEXT:    sw a2, 4(a1)
; ASM-NEXT:    sw a3, 8(a1)
; ASM-NEXT:    sw a4, 12(a1)
; ASM-NEXT:    esp.movi.8.a q0, a0, 15
; ASM-NEXT:    sw a5, 16(a1)
; ASM-NEXT:    sw a0, 20(a1)
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %ev1, i32 0)
  store i32 %v1, ptr %dst, align 4, !tbaa !27
  %v2 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %ev1, i32 3)
  %arrayidx3 = getelementptr inbounds nuw i8, ptr %dst, i32 4
  store i32 %v2, ptr %arrayidx3, align 4, !tbaa !27
  %v3 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %ev1, i32 7)
  %arrayidx6 = getelementptr inbounds nuw i8, ptr %dst, i32 8
  store i32 %v3, ptr %arrayidx6, align 4, !tbaa !27
  %v4 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %ev1, i32 8)
  %arrayidx9 = getelementptr inbounds nuw i8, ptr %dst, i32 12
  store i32 %v4, ptr %arrayidx9, align 4, !tbaa !27
  %v5 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %ev1, i32 11)
  %arrayidx12 = getelementptr inbounds nuw i8, ptr %dst, i32 16
  store i32 %v5, ptr %arrayidx12, align 4, !tbaa !27
  %v6 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %ev1, i32 15)
  %arrayidx15 = getelementptr inbounds nuw i8, ptr %dst, i32 20
  store i32 %v6, ptr %arrayidx15, align 4, !tbaa !27
  ret void
}

define dso_local void @test_movi_16_a_subregister(ptr noundef %src, ptr noundef writeonly captures(none) initializes((0, 24)) %dst) local_unnamed_addr #2 {
; ASM-LABEL: test_movi_16_a_subregister:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movi.16.a q0, a0, 0
; ASM-NEXT:    esp.movi.16.a q0, a2, 2
; ASM-NEXT:    esp.movi.16.a q0, a3, 3
; ASM-NEXT:    esp.movi.16.a q0, a4, 4
; ASM-NEXT:    esp.movi.16.a q0, a5, 6
; ASM-NEXT:    sw a0, 0(a1)
; ASM-NEXT:    sw a2, 4(a1)
; ASM-NEXT:    sw a3, 8(a1)
; ASM-NEXT:    sw a4, 12(a1)
; ASM-NEXT:    esp.movi.16.a q0, a0, 7
; ASM-NEXT:    sw a5, 16(a1)
; ASM-NEXT:    sw a0, 20(a1)
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 0)
  store i32 %v1, ptr %dst, align 4, !tbaa !27
  %v2 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 2)
  %arrayidx3 = getelementptr inbounds nuw i8, ptr %dst, i32 4
  store i32 %v2, ptr %arrayidx3, align 4, !tbaa !27
  %v3 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 3)
  %arrayidx6 = getelementptr inbounds nuw i8, ptr %dst, i32 8
  store i32 %v3, ptr %arrayidx6, align 4, !tbaa !27
  %v4 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 4)
  %arrayidx9 = getelementptr inbounds nuw i8, ptr %dst, i32 12
  store i32 %v4, ptr %arrayidx9, align 4, !tbaa !27
  %v5 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 6)
  %arrayidx12 = getelementptr inbounds nuw i8, ptr %dst, i32 16
  store i32 %v5, ptr %arrayidx12, align 4, !tbaa !27
  %v6 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 7)
  %arrayidx15 = getelementptr inbounds nuw i8, ptr %dst, i32 20
  store i32 %v6, ptr %arrayidx15, align 4, !tbaa !27
  ret void
}

define dso_local void @test_movi_32_a_subregister(ptr noundef %src, ptr noundef writeonly captures(none) initializes((0, 16)) %dst) local_unnamed_addr #2 {
; ASM-LABEL: test_movi_32_a_subregister:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movi.32.a q0, a0, 0
; ASM-NEXT:    esp.movi.32.a q0, a2, 1
; ASM-NEXT:    esp.movi.32.a q0, a3, 2
; ASM-NEXT:    esp.movi.32.a q0, a4, 3
; ASM-NEXT:    sw a0, 0(a1)
; ASM-NEXT:    sw a2, 4(a1)
; ASM-NEXT:    sw a3, 8(a1)
; ASM-NEXT:    sw a4, 12(a1)
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %v1 = tail call i32 @llvm.riscv.esp.movi.32.a(<4 x i32> %bc1, i32 0)
  store i32 %v1, ptr %dst, align 4, !tbaa !27
  %v2 = tail call i32 @llvm.riscv.esp.movi.32.a(<4 x i32> %bc1, i32 1)
  %arrayidx3 = getelementptr inbounds nuw i8, ptr %dst, i32 4
  store i32 %v2, ptr %arrayidx3, align 4, !tbaa !27
  %v3 = tail call i32 @llvm.riscv.esp.movi.32.a(<4 x i32> %bc1, i32 2)
  %arrayidx6 = getelementptr inbounds nuw i8, ptr %dst, i32 8
  store i32 %v3, ptr %arrayidx6, align 4, !tbaa !27
  %v4 = tail call i32 @llvm.riscv.esp.movi.32.a(<4 x i32> %bc1, i32 3)
  %arrayidx9 = getelementptr inbounds nuw i8, ptr %dst, i32 12
  store i32 %v4, ptr %arrayidx9, align 4, !tbaa !27
  ret void
}

define dso_local void @test_movi_from_64bit_subregister(ptr noundef %src, ptr noundef writeonly captures(none) initializes((0, 48)) %dst) local_unnamed_addr #3 {
; ASM-LABEL: test_movi_from_64bit_subregister:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    addi sp, sp, -16
; ASM-NEXT:    .cfi_def_cfa_offset 16
; ASM-NEXT:    sw s0, 12(sp) # 4-byte Folded Spill
; ASM-NEXT:    .cfi_offset s0, -4
; ASM-NEXT:    esp.vld.l.64.ip q0, a0, 8
; ASM-NEXT:    esp.vld.h.64.ip q0, a0, 8
; ASM-NEXT:    esp.movi.8.a q0, a0, 0
; ASM-NEXT:    esp.movi.8.a q0, a2, 7
; ASM-NEXT:    esp.movi.16.a q0, a3, 0
; ASM-NEXT:    esp.movi.16.a q0, a4, 3
; ASM-NEXT:    esp.movi.32.a q0, a5, 0
; ASM-NEXT:    esp.movi.32.a q0, t3, 1
; ASM-NEXT:    esp.movi.8.a q0, t4, 8
; ASM-NEXT:    esp.movi.8.a q0, t5, 15
; ASM-NEXT:    esp.movi.16.a q0, t6, 4
; ASM-NEXT:    esp.movi.16.a q0, s0, 7
; ASM-NEXT:    sw a0, 0(a1)
; ASM-NEXT:    sw a2, 4(a1)
; ASM-NEXT:    sw a3, 8(a1)
; ASM-NEXT:    sw a4, 12(a1)
; ASM-NEXT:    esp.movi.32.a q0, a0, 2
; ASM-NEXT:    sw a5, 16(a1)
; ASM-NEXT:    sw t3, 20(a1)
; ASM-NEXT:    sw t4, 24(a1)
; ASM-NEXT:    sw t5, 28(a1)
; ASM-NEXT:    esp.movi.32.a q0, a2, 3
; ASM-NEXT:    sw t6, 32(a1)
; ASM-NEXT:    sw s0, 36(a1)
; ASM-NEXT:    sw a0, 40(a1)
; ASM-NEXT:    sw a2, 44(a1)
; ASM-NEXT:    lw s0, 12(sp) # 4-byte Folded Reload
; ASM-NEXT:    .cfi_restore s0
; ASM-NEXT:    addi sp, sp, 16
; ASM-NEXT:    .cfi_def_cfa_offset 0
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr %src, i32 8)
  %ev1 = extractvalue { <8 x i8>, ptr } %v1, 0
  %ev2 = extractvalue { <8 x i8>, ptr } %v1, 1
  %v2 = tail call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr %ev2, i32 8)
  %ev3 = extractvalue { <8 x i8>, ptr } %v2, 0
  %shuffle = shufflevector <8 x i8> %ev1, <8 x i8> %ev3, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %v3 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %shuffle, i32 0)
  store i32 %v3, ptr %dst, align 4, !tbaa !27
  %v4 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %shuffle, i32 7)
  %arrayidx4 = getelementptr inbounds nuw i8, ptr %dst, i32 4
  store i32 %v4, ptr %arrayidx4, align 4, !tbaa !27
  %bc1 = bitcast <16 x i8> %shuffle to <8 x i16>
  %v5 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 0)
  %arrayidx7 = getelementptr inbounds nuw i8, ptr %dst, i32 8
  store i32 %v5, ptr %arrayidx7, align 4, !tbaa !27
  %v6 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 3)
  %arrayidx10 = getelementptr inbounds nuw i8, ptr %dst, i32 12
  store i32 %v6, ptr %arrayidx10, align 4, !tbaa !27
  %bc2 = bitcast <16 x i8> %shuffle to <4 x i32>
  %v7 = tail call i32 @llvm.riscv.esp.movi.32.a(<4 x i32> %bc2, i32 0)
  %arrayidx13 = getelementptr inbounds nuw i8, ptr %dst, i32 16
  store i32 %v7, ptr %arrayidx13, align 4, !tbaa !27
  %v8 = tail call i32 @llvm.riscv.esp.movi.32.a(<4 x i32> %bc2, i32 1)
  %arrayidx16 = getelementptr inbounds nuw i8, ptr %dst, i32 20
  store i32 %v8, ptr %arrayidx16, align 4, !tbaa !27
  %v9 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %shuffle, i32 8)
  %arrayidx19 = getelementptr inbounds nuw i8, ptr %dst, i32 24
  store i32 %v9, ptr %arrayidx19, align 4, !tbaa !27
  %v10 = tail call i32 @llvm.riscv.esp.movi.8.a(<16 x i8> %shuffle, i32 15)
  %arrayidx22 = getelementptr inbounds nuw i8, ptr %dst, i32 28
  store i32 %v10, ptr %arrayidx22, align 4, !tbaa !27
  %v11 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 4)
  %arrayidx25 = getelementptr inbounds nuw i8, ptr %dst, i32 32
  store i32 %v11, ptr %arrayidx25, align 4, !tbaa !27
  %v12 = tail call i32 @llvm.riscv.esp.movi.16.a(<8 x i16> %bc1, i32 7)
  %arrayidx28 = getelementptr inbounds nuw i8, ptr %dst, i32 36
  store i32 %v12, ptr %arrayidx28, align 4, !tbaa !27
  %v13 = tail call i32 @llvm.riscv.esp.movi.32.a(<4 x i32> %bc2, i32 2)
  %arrayidx31 = getelementptr inbounds nuw i8, ptr %dst, i32 40
  store i32 %v13, ptr %arrayidx31, align 4, !tbaa !27
  %v14 = tail call i32 @llvm.riscv.esp.movi.32.a(<4 x i32> %bc2, i32 3)
  %arrayidx34 = getelementptr inbounds nuw i8, ptr %dst, i32 44
  store i32 %v14, ptr %arrayidx34, align 4, !tbaa !27
  ret void
}

declare { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr, i32) #4

declare { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr, i32) #4

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #5

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #4

declare ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8>, ptr, i32) #5

declare ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8>, ptr, i32) #5

declare { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.xp(ptr, i32) #4

declare { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.xp(ptr, i32) #4

declare ptr @llvm.riscv.esp.vst.128.xp(<16 x i8>, ptr, i32) #5

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.xp(ptr, i32) #4

declare ptr @llvm.riscv.esp.vst.h.64.xp(<8 x i8>, ptr, i32) #5

declare ptr @llvm.riscv.esp.vst.l.64.xp(<8 x i8>, ptr, i32) #5

declare i32 @llvm.riscv.esp.movi.8.a(<16 x i8>, i32) #6

declare i32 @llvm.riscv.esp.movi.16.a(<8 x i16>, i32) #6

declare i32 @llvm.riscv.esp.movi.32.a(<4 x i32>, i32) #6

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { "target-features"="+32bit,+xespv" }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { "target-features"="+32bit,+xespv" }
attributes #4 = { nounwind }
attributes #5 = { nounwind }
attributes #6 = { nounwind }


!27 = !{!28, !28, i64 0}
!28 = !{!"int", !29, i64 0}
!29 = !{!"omnipotent char", !30, i64 0}
!30 = !{!"Simple C/C++ TBAA"}
