; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-movx-r-w-xacc.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local i32 @test_movx_xacc_h_write_read(i8 noundef zeroext %rs1_val) local_unnamed_addr #0 {
; ASM-LABEL: test_movx_xacc_h_write_read:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.h a0
; ASM-NEXT:    esp.movx.r.xacc.h a0
; ASM-NEXT:    ret
entry:
  %conv1 = zext i8 %rs1_val to i32
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 %conv1)
  %v2 = tail call i32 @llvm.riscv.esp.movx.r.xacc.h(i32 %v1)
  ret i32 %v2
}

declare i32 @llvm.riscv.esp.movx.w.xacc.h(i32) #1

declare i32 @llvm.riscv.esp.movx.r.xacc.h(i32) #1

define dso_local i32 @test_movx_xacc_l_write_read(i32 noundef %rs1_val) local_unnamed_addr #0 {
; ASM-LABEL: test_movx_xacc_l_write_read:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %rs1_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 %v1)
  ret i32 %v2
}

declare i32 @llvm.riscv.esp.movx.w.xacc.l(i32) #1

declare i32 @llvm.riscv.esp.movx.r.xacc.l(i32) #1

define dso_local i32 @test_vmulas_s16_xacc(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1) local_unnamed_addr #2 {
; ASM-LABEL: test_vmulas_s16_xacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h a3
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.movx.r.xacc.h a1
; ASM-NEXT:    zext.b a1, a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.w.xacc.h a1
; ASM-NEXT:    esp.vmulas.s16.xacc q0, q1
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <8 x i16>, ptr %0, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %conv2 = and i32 %v2, 255
  %v3 = tail call { i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc(i32 %v1, i32 %conv2, <8 x i16> %Qx, <8 x i16> %Qy, i32 0)
  %ev1 = extractvalue { i32, i32 } %v3, 0
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 %ev1)
  ret i32 %v4
}

declare { i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc(i32, i32, <8 x i16>, <8 x i16>, i32) #1

define dso_local i32 @test_vmulas_s8_xacc(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1) local_unnamed_addr #2 {
; ASM-LABEL: test_vmulas_s8_xacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h a3
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.movx.r.xacc.h a1
; ASM-NEXT:    zext.b a1, a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.w.xacc.h a1
; ASM-NEXT:    esp.vmulas.s8.xacc q0, q1
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %conv2 = and i32 %v2, 255
  %v3 = tail call { i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc(i32 %v1, i32 %conv2, <16 x i8> %Qx, <16 x i8> %Qy, i32 0)
  %ev1 = extractvalue { i32, i32 } %v3, 0
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 %ev1)
  ret i32 %v4
}

declare { i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc(i32, i32, <16 x i8>, <16 x i8>, i32) #1

define dso_local i32 @test_vmulas_u16_xacc(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1) local_unnamed_addr #2 {
; ASM-LABEL: test_vmulas_u16_xacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h a3
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.movx.r.xacc.h a1
; ASM-NEXT:    zext.b a1, a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.w.xacc.h a1
; ASM-NEXT:    esp.vmulas.u16.xacc q0, q1
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <8 x i16>, ptr %0, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %conv2 = and i32 %v2, 255
  %v3 = tail call { i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc(i32 %v1, i32 %conv2, <8 x i16> %Qx, <8 x i16> %Qy, i32 0)
  %ev1 = extractvalue { i32, i32 } %v3, 0
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 %ev1)
  ret i32 %v4
}

declare { i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc(i32, i32, <8 x i16>, <8 x i16>, i32) #1

define dso_local i32 @test_vmulas_u8_xacc(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1) local_unnamed_addr #2 {
; ASM-LABEL: test_vmulas_u8_xacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h a3
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.movx.r.xacc.h a1
; ASM-NEXT:    zext.b a1, a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.w.xacc.h a1
; ASM-NEXT:    esp.vmulas.u8.xacc q0, q1
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %conv2 = and i32 %v2, 255
  %v3 = tail call { i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc(i32 %v1, i32 %conv2, <16 x i8> %Qx, <16 x i8> %Qy, i32 0)
  %ev1 = extractvalue { i32, i32 } %v3, 0
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 %ev1)
  ret i32 %v4
}

declare { i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc(i32, i32, <16 x i8>, <16 x i8>, i32) #1

define dso_local i32 @test_srs_s_xacc(i32 noundef %init_val, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_srs_s_xacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a2, 0
; ASM-NEXT:    esp.movx.w.xacc.h a2
; ASM-NEXT:    esp.movx.r.xacc.h a2
; ASM-NEXT:    zext.b a2, a2
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.w.xacc.h a2
; ASM-NEXT:    esp.srs.s.xacc a0, a1
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %conv2 = and i32 %v2, 255
  %v3 = tail call { i32, i32, i32 } @llvm.riscv.esp.srs.s.xacc(i32 %conv2, i32 %v1, i32 %shift_amount, i32 0, i32 7)
  %ev1 = extractvalue { i32, i32, i32 } %v3, 2
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 %ev1)
  ret i32 %v4
}

declare { i32, i32, i32 } @llvm.riscv.esp.srs.s.xacc(i32, i32, i32, i32 immarg, i32 immarg) #1

define dso_local i32 @test_srs_u_xacc(i32 noundef %init_val, i32 noundef %shift_amount) local_unnamed_addr #0 {
; ASM-LABEL: test_srs_u_xacc:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a2, 0
; ASM-NEXT:    esp.movx.w.xacc.h a2
; ASM-NEXT:    esp.movx.r.xacc.h a2
; ASM-NEXT:    zext.b a2, a2
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.w.xacc.h a2
; ASM-NEXT:    esp.srs.u.xacc a0, a1
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %conv2 = and i32 %v2, 255
  %v3 = tail call { i32, i32, i32 } @llvm.riscv.esp.srs.u.xacc(i32 %conv2, i32 %v1, i32 %shift_amount, i32 0, i32 7)
  %ev1 = extractvalue { i32, i32, i32 } %v3, 2
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 %ev1)
  ret i32 %v4
}

declare { i32, i32, i32 } @llvm.riscv.esp.srs.u.xacc(i32, i32, i32, i32 immarg, i32 immarg) #1

define dso_local i32 @test_vmulas_s16_xacc_ld_ip(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly %Ptr) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s16_xacc_ld_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a0, 0
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <8 x i16>, ptr %0, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.ld.ip(i32 %v1, i32 %v2, <8 x i16> %Qx, <8 x i16> %Qy, ptr %Ptr, i32 16, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_s16_xacc_ld_xp(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly %Ptr, i32 noundef %Reg) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s16_xacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a0, 0
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <8 x i16>, ptr %0, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.ld.xp(i32 %v1, i32 %v2, <8 x i16> %Qx, <8 x i16> %Qy, ptr %Ptr, i32 %Reg, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_s16_xacc_st_ip(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef %Ptr) local_unnamed_addr #4 {
; ASM-LABEL: test_vmulas_s16_xacc_st_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a5, 0
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.vld.128.ip q2, a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h a5
; ASM-NEXT:    esp.movx.w.xacc.l a5
; ASM-NEXT:    esp.movx.r.xacc.l a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.vmulas.s16.xacc.st.ip q0, a4, 16, q1, q2
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %Qu = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qx = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %2, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.st.ip(i32 %v1, i32 %v2, <16 x i8> %Qu, <8 x i16> %Qx, <8 x i16> %Qy, ptr %Ptr, i32 16, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_s16_xacc_st_xp(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef %Ptr, i32 noundef %Reg) local_unnamed_addr #4 {
; ASM-LABEL: test_vmulas_s16_xacc_st_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li t3, 0
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.vld.128.ip q2, a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h t3
; ASM-NEXT:    esp.movx.w.xacc.l t3
; ASM-NEXT:    esp.movx.r.xacc.l a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.vmulas.s16.xacc.st.xp q0, a4, a5, q1, q2
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %Qu = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qx = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %2, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.st.xp(i32 %v1, i32 %v2, <16 x i8> %Qu, <8 x i16> %Qx, <8 x i16> %Qy, ptr %Ptr, i32 %Reg, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_s8_xacc_ld_ip(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly %Ptr) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s8_xacc_ld_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a0, 0
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.ld.ip(i32 %v1, i32 %v2, <16 x i8> %Qx, <16 x i8> %Qy, ptr %Ptr, i32 16, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_s8_xacc_ld_xp(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly %Ptr, i32 noundef %Reg) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_s8_xacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a0, 0
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.ld.xp(i32 %v1, i32 %v2, <16 x i8> %Qx, <16 x i8> %Qy, ptr %Ptr, i32 %Reg, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_s8_xacc_st_ip(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef %Ptr) local_unnamed_addr #4 {
; ASM-LABEL: test_vmulas_s8_xacc_st_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a5, 0
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.vld.128.ip q2, a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h a5
; ASM-NEXT:    esp.movx.w.xacc.l a5
; ASM-NEXT:    esp.movx.r.xacc.l a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.vmulas.s8.xacc.st.ip q0, a4, 16, q1, q2
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %Qu = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qx = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %2, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.st.ip(i32 %v1, i32 %v2, <16 x i8> %Qu, <16 x i8> %Qx, <16 x i8> %Qy, ptr %Ptr, i32 16, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_s8_xacc_st_xp(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef %Ptr, i32 noundef %Reg) local_unnamed_addr #4 {
; ASM-LABEL: test_vmulas_s8_xacc_st_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li t3, 0
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.vld.128.ip q2, a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h t3
; ASM-NEXT:    esp.movx.w.xacc.l t3
; ASM-NEXT:    esp.movx.r.xacc.l a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.vmulas.s8.xacc.st.xp q0, a4, a5, q1, q2
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %Qu = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qx = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %2, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.st.xp(i32 %v1, i32 %v2, <16 x i8> %Qu, <16 x i8> %Qx, <16 x i8> %Qy, ptr %Ptr, i32 %Reg, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_u16_xacc_ld_ip(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly %Ptr) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u16_xacc_ld_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a0, 0
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <8 x i16>, ptr %0, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc.ld.ip(i32 %v1, i32 %v2, <8 x i16> %Qx, <8 x i16> %Qy, ptr %Ptr, i32 16, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_u16_xacc_ld_xp(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly %Ptr, i32 noundef %Reg) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u16_xacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a0, 0
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <8 x i16>, ptr %0, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc.ld.xp(i32 %v1, i32 %v2, <8 x i16> %Qx, <8 x i16> %Qy, ptr %Ptr, i32 %Reg, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_u16_xacc_st_ip(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef %Ptr) local_unnamed_addr #4 {
; ASM-LABEL: test_vmulas_u16_xacc_st_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a5, 0
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.vld.128.ip q2, a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h a5
; ASM-NEXT:    esp.movx.w.xacc.l a5
; ASM-NEXT:    esp.movx.r.xacc.l a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.vmulas.u16.xacc.st.ip q0, a4, 16, q1, q2
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %Qu = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qx = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %2, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { ptr, i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc.st.ip(i32 %v1, i32 %v2, <16 x i8> %Qu, <8 x i16> %Qx, <8 x i16> %Qy, ptr %Ptr, i32 16, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_u16_xacc_st_xp(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef %Ptr, i32 noundef %Reg) local_unnamed_addr #4 {
; ASM-LABEL: test_vmulas_u16_xacc_st_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li t3, 0
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.vld.128.ip q2, a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h t3
; ASM-NEXT:    esp.movx.w.xacc.l t3
; ASM-NEXT:    esp.movx.r.xacc.l a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.vmulas.u16.xacc.st.xp q0, a4, a5, q1, q2
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %Qu = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qx = load <8 x i16>, ptr %1, align 16, !tbaa !6
  %Qy = load <8 x i16>, ptr %2, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { ptr, i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc.st.xp(i32 %v1, i32 %v2, <16 x i8> %Qu, <8 x i16> %Qx, <8 x i16> %Qy, ptr %Ptr, i32 %Reg, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_u8_xacc_ld_ip(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly %Ptr) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u8_xacc_ld_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a0, 0
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc.ld.ip(i32 %v1, i32 %v2, <16 x i8> %Qx, <16 x i8> %Qy, ptr %Ptr, i32 16, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_u8_xacc_ld_xp(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly %Ptr, i32 noundef %Reg) local_unnamed_addr #3 {
; ASM-LABEL: test_vmulas_u8_xacc_ld_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a0, 0
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.movx.r.xacc.l a0
; ASM-NEXT:    ret
entry:
  %Qx = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc.ld.xp(i32 %v1, i32 %v2, <16 x i8> %Qx, <16 x i8> %Qy, ptr %Ptr, i32 %Reg, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_u8_xacc_st_ip(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef %Ptr) local_unnamed_addr #4 {
; ASM-LABEL: test_vmulas_u8_xacc_st_ip:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a5, 0
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.vld.128.ip q2, a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h a5
; ASM-NEXT:    esp.movx.w.xacc.l a5
; ASM-NEXT:    esp.movx.r.xacc.l a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.vmulas.u8.xacc.st.ip q0, a4, 16, q1, q2
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %Qu = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qx = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %2, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { ptr, i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc.st.ip(i32 %v1, i32 %v2, <16 x i8> %Qu, <16 x i8> %Qx, <16 x i8> %Qy, ptr %Ptr, i32 16, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

define dso_local i32 @test_vmulas_u8_xacc_st_xp(i32 noundef %init_val, ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef %Ptr, i32 noundef %Reg) local_unnamed_addr #4 {
; ASM-LABEL: test_vmulas_u8_xacc_st_xp:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li t3, 0
; ASM-NEXT:    esp.vld.128.ip q0, a1, 0
; ASM-NEXT:    esp.vld.128.ip q1, a2, 0
; ASM-NEXT:    esp.vld.128.ip q2, a3, 0
; ASM-NEXT:    esp.movx.w.xacc.h t3
; ASM-NEXT:    esp.movx.w.xacc.l t3
; ASM-NEXT:    esp.movx.r.xacc.l a1
; ASM-NEXT:    esp.movx.w.xacc.l a0
; ASM-NEXT:    esp.vmulas.u8.xacc.st.xp q0, a4, a5, q1, q2
; ASM-NEXT:    mv a0, a1
; ASM-NEXT:    ret
entry:
  %Qu = load <16 x i8>, ptr %0, align 16, !tbaa !6
  %Qx = load <16 x i8>, ptr %1, align 16, !tbaa !6
  %Qy = load <16 x i8>, ptr %2, align 16, !tbaa !6
  %v1 = tail call i32 @llvm.riscv.esp.movx.w.xacc.l(i32 %init_val)
  %v2 = tail call i32 @llvm.riscv.esp.movx.w.xacc.h(i32 0)
  %v3 = tail call { ptr, i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc.st.xp(i32 %v1, i32 %v2, <16 x i8> %Qu, <16 x i8> %Qx, <16 x i8> %Qy, ptr %Ptr, i32 %Reg, i32 0)
  %v4 = tail call i32 @llvm.riscv.esp.movx.r.xacc.l(i32 0)
  ret i32 %v4
}

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.ld.ip(i32, i32, <8 x i16>, <8 x i16>, ptr, i32, i32) #5

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.ld.xp(i32, i32, <8 x i16>, <8 x i16>, ptr, i32, i32) #5

declare { ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.st.ip(i32, i32, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #6

declare { ptr, i32, i32 } @llvm.riscv.esp.vmulas.s16.xacc.st.xp(i32, i32, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #6

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.ld.ip(i32, i32, <16 x i8>, <16 x i8>, ptr, i32, i32) #5

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.ld.xp(i32, i32, <16 x i8>, <16 x i8>, ptr, i32, i32) #5

declare { ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.st.ip(i32, i32, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #6

declare { ptr, i32, i32 } @llvm.riscv.esp.vmulas.s8.xacc.st.xp(i32, i32, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #6

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc.ld.ip(i32, i32, <8 x i16>, <8 x i16>, ptr, i32, i32) #5

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc.ld.xp(i32, i32, <8 x i16>, <8 x i16>, ptr, i32, i32) #5

declare { ptr, i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc.st.ip(i32, i32, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #6

declare { ptr, i32, i32 } @llvm.riscv.esp.vmulas.u16.xacc.st.xp(i32, i32, <16 x i8>, <8 x i16>, <8 x i16>, ptr, i32, i32) #6

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc.ld.ip(i32, i32, <16 x i8>, <16 x i8>, ptr, i32, i32) #5

declare { <16 x i8>, ptr, i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc.ld.xp(i32, i32, <16 x i8>, <16 x i8>, ptr, i32, i32) #5

declare { ptr, i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc.st.ip(i32, i32, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #6

declare { ptr, i32, i32 } @llvm.riscv.esp.vmulas.u8.xacc.st.xp(i32, i32, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #6

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { "target-features"="+32bit,+xespv" }
attributes #4 = { "target-features"="+32bit,+xespv" }
attributes #5 = { nounwind }
attributes #6 = { nounwind }


!6 = !{!7, !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
