; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-movx-r-w-sar.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local i32 @test_movx_sar_write_read(i32 noundef %rs1_val) local_unnamed_addr #0 {
; ASM-LABEL: test_movx_sar_write_read:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.sar a0
; ASM-NEXT:    esp.movx.r.sar a0
; ASM-NEXT:    ret
entry:
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %rs1_val)
  %v1 = tail call i32 @llvm.riscv.esp.movx.r.sar(i32 %sar)
  ret i32 %v1
}

declare i32 @llvm.riscv.esp.movx.w.sar(i32) #1

declare i32 @llvm.riscv.esp.movx.r.sar(i32) #1

define dso_local void @test_vsr_u32_with_sar(ptr noundef %src, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_vsr_u32_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movx.w.sar a2
; ASM-NEXT:    esp.vsr.u32 q0, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsr.u32(<4 x i32> %bc1, i32 %sar, i32 7)
  %bc2 = bitcast <4 x i32> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

declare <4 x i32> @llvm.riscv.esp.vsr.u32(<4 x i32>, i32, i32 immarg) #1

define dso_local void @test_vmul_s8_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_vmul_s8_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.vmul.s8 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vmul.s8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 7, i32 %sar)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vmul.s8(<16 x i8>, <16 x i8>, i32 immarg, i32 immarg, i32) #1

define dso_local void @test_vmul_u8_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_vmul_u8_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.vmul.u8 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vmul.u8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 7, i32 %sar)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vmul.u8(<16 x i8>, <16 x i8>, i32 immarg, i32 immarg, i32) #1

define dso_local void @test_vmul_s16_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_vmul_s16_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.vmul.s16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vmul.s16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 7, i32 %sar)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vmul.s16(<8 x i16>, <8 x i16>, i32 immarg, i32 immarg, i32) #1

define dso_local void @test_vmul_u16_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_vmul_u16_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.vmul.u16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vmul.u16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 7, i32 %sar)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vmul.u16(<8 x i16>, <8 x i16>, i32 immarg, i32 immarg, i32) #1

define dso_local void @test_vmul_s16_s8xs8_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qz, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qv, i32 noundef %sar_val) local_unnamed_addr #3 {
; ASM-LABEL: test_vmul_s16_s8xs8_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a4
; ASM-NEXT:    esp.vmul.s16.s8xs8 q0, q1, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vmul.s16.s8xs8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 7, i32 %sar)
  %ev3 = extractvalue { <8 x i16>, <8 x i16> } %v1, 0
  %ev4 = extractvalue { <8 x i16>, <8 x i16> } %v1, 1
  store <8 x i16> %ev3, ptr %dst_qz, align 16
  store <8 x i16> %ev4, ptr %dst_qv, align 16
  ret void
}

declare { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vmul.s16.s8xs8(<16 x i8>, <16 x i8>, i32 immarg, i32 immarg, i32) #1

define dso_local void @test_vmul_s32_s16xs16_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qz, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qv, i32 noundef %sar_val) local_unnamed_addr #3 {
; ASM-LABEL: test_vmul_s32_s16xs16_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a4
; ASM-NEXT:    esp.vmul.s32.s16xs16 q0, q1, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vmul.s32.s16xs16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 7, i32 %sar)
  %ev3 = extractvalue { <4 x i32>, <4 x i32> } %v1, 0
  %ev4 = extractvalue { <4 x i32>, <4 x i32> } %v1, 1
  store <4 x i32> %ev3, ptr %dst_qz, align 16
  store <4 x i32> %ev4, ptr %dst_qv, align 16
  ret void
}

declare { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vmul.s32.s16xs16(<8 x i16>, <8 x i16>, i32 immarg, i32 immarg, i32) #1

define dso_local void @test_vmul_s16_ld_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qv, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qu, ptr noundef %src_ptr, i32 noundef %sar_val) local_unnamed_addr #3 {
; ASM-LABEL: test_vmul_s16_ld_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.vmul.s16.ld.incp q1, a4, q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.vmul.s16.ld.incp(<8 x i16> %bc1, <8 x i16> %bc2, ptr %src_ptr, i32 0, i32 7, i32 %sar)
  %ev3 = extractvalue { <8 x i16>, <16 x i8>, ptr } %v1, 0
  %ev4 = extractvalue { <8 x i16>, <16 x i8>, ptr } %v1, 1
  store <8 x i16> %ev3, ptr %dst_qv, align 16
  store <16 x i8> %ev4, ptr %dst_qu, align 16
  ret void
}

declare { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.vmul.s16.ld.incp(<8 x i16>, <8 x i16>, ptr, i32 immarg, i32 immarg, i32) #4

define dso_local void @test_vmul_s16_st_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %Qu, ptr noundef %dst_ptr, ptr noundef %qv_src, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_vmul_s16_st_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.vmul.s16.st.incp q2, a3, q0, q0, q1
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %Qu, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %vld4 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %qv_src, i32 16)
  %ev4 = extractvalue { <16 x i8>, ptr } %vld4, 0
  %bc3 = bitcast <16 x i8> %ev4 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call { <8 x i16>, ptr } @llvm.riscv.esp.vmul.s16.st.incp(<8 x i16> %bc1, <8 x i16> %bc2, <16 x i8> %ev3, ptr %dst_ptr, <8 x i16> %bc3, i32 0, i32 7, i32 %sar)
  ret void
}

declare { <8 x i16>, ptr } @llvm.riscv.esp.vmul.s16.st.incp(<8 x i16>, <8 x i16>, <16 x i8>, ptr, <8 x i16>, i32 immarg, i32 immarg, i32) #5

define dso_local void @test_cmul_s16_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_cmul_s16_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.cmul.s16 q0, q0, q1, 0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <8 x i16> @llvm.riscv.esp.cmul.s16(<8 x i16> undef, <8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 0, i32 7, i32 %sar)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.cmul.s16(<8 x i16>, <8 x i16>, <8 x i16>, i32 immarg, i32 immarg, i32 immarg, i32) #1

define dso_local void @test_cmul_s16_ld_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qz, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qu, ptr noundef %src_ptr, i32 noundef %sar_val) local_unnamed_addr #3 {
; ASM-LABEL: test_cmul_s16_ld_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.cmul.s16.ld.incp q1, a4, q0, q0, q1, 0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %cmul_ld_res = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.cmul.s16.ld.incp(<8 x i16> undef, <8 x i16> %bc1, <8 x i16> %bc2, ptr %src_ptr, i32 0, i32 0, i32 7, i32 %sar)
  %ev3 = extractvalue { <8 x i16>, <16 x i8>, ptr } %cmul_ld_res, 0
  %ev4 = extractvalue { <8 x i16>, <16 x i8>, ptr } %cmul_ld_res, 1
  store <8 x i16> %ev3, ptr %dst_qz, align 16
  store <16 x i8> %ev4, ptr %dst_qu, align 16
  ret void
}

declare { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.cmul.s16.ld.incp(<8 x i16>, <8 x i16>, <8 x i16>, ptr, i32 immarg, i32 immarg, i32 immarg, i32) #4

define dso_local void @test_cmul_s16_st_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %Qu, ptr noundef %dst_ptr, ptr noundef readnone captures(none) %qz_out, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_cmul_s16_st_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.cmul.s16.st.incp q2, a3, q0, q0, q1, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %Qu, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %cmul_st_res = tail call { <8 x i16>, ptr } @llvm.riscv.esp.cmul.s16.st.incp(<8 x i16> undef, <8 x i16> %bc1, <8 x i16> %bc2, <16 x i8> %ev3, ptr %dst_ptr, i32 0, i32 0, i32 7, i32 %sar)
  ret void
}

declare { <8 x i16>, ptr } @llvm.riscv.esp.cmul.s16.st.incp(<8 x i16>, <8 x i16>, <8 x i16>, <16 x i8>, ptr, i32 immarg, i32 immarg, i32 immarg, i32) #5

define dso_local void @test_cmul_s8_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_cmul_s8_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.cmul.s8 q0, q0, q1, 0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <16 x i8> @llvm.riscv.esp.cmul.s8(<16 x i8> undef, <16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 0, i32 7, i32 %sar)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.cmul.s8(<16 x i8>, <16 x i8>, <16 x i8>, i32 immarg, i32 immarg, i32 immarg, i32) #1

define dso_local void @test_cmul_s8_ld_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qz, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qu, ptr noundef %src_ptr, i32 noundef %sar_val) local_unnamed_addr #3 {
; ASM-LABEL: test_cmul_s8_ld_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.cmul.s8.ld.incp q1, a4, q0, q0, q1, 0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %cmul_ld_res = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.cmul.s8.ld.incp(<16 x i8> undef, <16 x i8> %ev1, <16 x i8> %ev2, ptr %src_ptr, i32 0, i32 0, i32 7, i32 %sar)
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, ptr } %cmul_ld_res, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, ptr } %cmul_ld_res, 1
  store <16 x i8> %ev3, ptr %dst_qz, align 16
  store <16 x i8> %ev4, ptr %dst_qu, align 16
  ret void
}

declare { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.cmul.s8.ld.incp(<16 x i8>, <16 x i8>, <16 x i8>, ptr, i32 immarg, i32 immarg, i32 immarg, i32) #4

define dso_local void @test_cmul_s8_st_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %Qu, ptr noundef %dst_ptr, ptr noundef readnone captures(none) %qz_out, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_cmul_s8_st_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.cmul.s8.st.incp q2, a3, q0, q0, q1, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %Qu, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %cmul_st_res = tail call { <16 x i8>, ptr } @llvm.riscv.esp.cmul.s8.st.incp(<16 x i8> undef, <16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, ptr %dst_ptr, i32 0, i32 0, i32 7, i32 %sar)
  ret void
}

declare { <16 x i8>, ptr } @llvm.riscv.esp.cmul.s8.st.incp(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32 immarg, i32 immarg, i32 immarg, i32) #5

define dso_local void @test_cmul_u16_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_cmul_u16_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.cmul.u16 q0, q0, q1, 0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <8 x i16> @llvm.riscv.esp.cmul.u16.m(<8 x i16> undef, <8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 %sar)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.cmul.u16.m(<8 x i16>, <8 x i16>, <8 x i16>, i32 immarg, i32) #1

define dso_local void @test_cmul_u16_ld_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qz, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qu, ptr noundef %src_ptr, i32 noundef %sar_val) local_unnamed_addr #3 {
; ASM-LABEL: test_cmul_u16_ld_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.cmul.u16.ld.incp q1, a4, q0, q0, q1, 0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %cmul_ld_res = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.cmul.u16.ld.incp.m(<8 x i16> undef, <8 x i16> %bc1, <8 x i16> %bc2, ptr %src_ptr, i32 0, i32 %sar)
  %ev3 = extractvalue { <8 x i16>, <16 x i8>, ptr } %cmul_ld_res, 0
  %ev4 = extractvalue { <8 x i16>, <16 x i8>, ptr } %cmul_ld_res, 1
  store <8 x i16> %ev3, ptr %dst_qz, align 16
  store <16 x i8> %ev4, ptr %dst_qu, align 16
  ret void
}

declare { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.cmul.u16.ld.incp.m(<8 x i16>, <8 x i16>, <8 x i16>, ptr, i32, i32) #4

define dso_local void @test_cmul_u16_st_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %Qu, ptr noundef %dst_ptr, ptr noundef readnone captures(none) %qz_out, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_cmul_u16_st_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.cmul.u16.st.incp q2, a3, q0, q0, q1, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %Qu, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %cmul_st_res = tail call { <8 x i16>, ptr } @llvm.riscv.esp.cmul.u16.st.incp.m(<8 x i16> undef, <8 x i16> %bc1, <8 x i16> %bc2, <16 x i8> %ev3, ptr %dst_ptr, i32 0, i32 %sar)
  ret void
}

declare { <8 x i16>, ptr } @llvm.riscv.esp.cmul.u16.st.incp.m(<8 x i16>, <8 x i16>, <8 x i16>, <16 x i8>, ptr, i32, i32) #5

define dso_local void @test_cmul_u8_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_cmul_u8_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.cmul.u8 q0, q0, q1, 0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <16 x i8> @llvm.riscv.esp.cmul.u8.m(<16 x i8> undef, <16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 %sar)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.cmul.u8.m(<16 x i8>, <16 x i8>, <16 x i8>, i32 immarg, i32) #1

define dso_local void @test_cmul_u8_ld_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qz, ptr noundef writeonly captures(none) initializes((0, 16)) %dst_qu, ptr noundef %src_ptr, i32 noundef %sar_val) local_unnamed_addr #3 {
; ASM-LABEL: test_cmul_u8_ld_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.cmul.u8.ld.incp q1, a4, q0, q0, q1, 0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %cmul_ld_res = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.cmul.u8.ld.incp.m(<16 x i8> undef, <16 x i8> %ev1, <16 x i8> %ev2, ptr %src_ptr, i32 0, i32 %sar)
  %ev3 = extractvalue { <16 x i8>, <16 x i8>, ptr } %cmul_ld_res, 0
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, ptr } %cmul_ld_res, 1
  store <16 x i8> %ev3, ptr %dst_qz, align 16
  store <16 x i8> %ev4, ptr %dst_qu, align 16
  ret void
}

declare { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.cmul.u8.ld.incp.m(<16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #4

define dso_local void @test_cmul_u8_st_incp_with_sar(ptr noundef %src1, ptr noundef %src2, ptr noundef %Qu, ptr noundef %dst_ptr, ptr noundef readnone captures(none) %qz_out, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_cmul_u8_st_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.cmul.u8.st.incp q2, a3, q0, q0, q1, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %Qu, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %cmul_st_res = tail call { <16 x i8>, ptr } @llvm.riscv.esp.cmul.u8.st.incp.m(<16 x i8> undef, <16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, ptr %dst_ptr, i32 0, i32 %sar)
  ret void
}

declare { <16 x i8>, ptr } @llvm.riscv.esp.cmul.u8.st.incp.m(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, ptr, i32, i32) #5

define dso_local void @test_fft_ams_s16_ld_incp_with_sar(ptr noundef %src, ptr noundef writeonly captures(none) initializes((0, 16)) %qu_out, ptr noundef writeonly captures(none) initializes((0, 16)) %qz_out, ptr noundef writeonly captures(none) initializes((0, 16)) %qv_out, i32 noundef %sar_val) local_unnamed_addr #3 {
; ASM-LABEL: test_fft_ams_s16_ld_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    mv a5, a0
; ASM-NEXT:    esp.vld.128.ip q0, a5, 16
; ASM-NEXT:    addi a5, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a5, 16
; ASM-NEXT:    addi a5, a0, 32
; ASM-NEXT:    esp.vld.128.ip q2, a5, 16
; ASM-NEXT:    esp.movx.w.sar a4
; ASM-NEXT:    esp.fft.ams.s16.ld.incp q0, a0, q1, q2, q0, q2, q1, 0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 0
; ASM-NEXT:    esp.vst.128.ip q1, a2, 0
; ASM-NEXT:    esp.vst.128.ip q2, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %add.ptr = getelementptr inbounds nuw i8, ptr %src, i32 16
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull %add.ptr, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %add.ptr1 = getelementptr inbounds nuw i8, ptr %src, i32 32
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull %add.ptr1, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %bc3 = bitcast <16 x i8> %ev3 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call { <16 x i8>, <8 x i16>, <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.ld.incp(<8 x i16> %bc1, <8 x i16> %bc2, <8 x i16> %bc3, ptr %src, i32 0, i32 0, i32 %sar)
  %ev4 = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr } %v1, 0
  %ev5 = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr } %v1, 1
  %ev6 = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr } %v1, 2
  store <16 x i8> %ev4, ptr %qu_out, align 16
  store <8 x i16> %ev5, ptr %qz_out, align 16
  store <8 x i16> %ev6, ptr %qv_out, align 16
  ret void
}

declare { <16 x i8>, <8 x i16>, <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.ld.incp(<8 x i16>, <8 x i16>, <8 x i16>, ptr, i32, i32, i32) #4

define dso_local void @test_fft_ams_s16_st_incp_with_sar(ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef readonly captures(none) %3, ptr noundef %dst, ptr noundef %rs2, ptr noundef writeonly captures(none) initializes((0, 16)) %qz_out, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_fft_ams_s16_st_incp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    mv t3, a7
; ASM-NEXT:    esp.vld.128.ip q0, a0, 0
; ASM-NEXT:    esp.vld.128.ip q1, a1, 0
; ASM-NEXT:    esp.vld.128.ip q2, a2, 0
; ASM-NEXT:    esp.vld.128.ip q3, a3, 0
; ASM-NEXT:    esp.movx.w.sar t3
; ASM-NEXT:    esp.fft.ams.s16.st.incp q3, q0, a5, a4, q0, q2, q1, 0
; ASM-NEXT:    mv a0, a6
; ASM-NEXT:    esp.vst.128.ip q0, a0, 0
; ASM-NEXT:    ret
entry:
  %Qx = load <8 x i16>, ptr %0, align 16, !tbaa !156
  %Qy = load <8 x i16>, ptr %1, align 16, !tbaa !156
  %Qw = load <8 x i16>, ptr %2, align 16, !tbaa !156
  %Qu = load <16 x i8>, ptr %3, align 16, !tbaa !156
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call { <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.st.incp(<8 x i16> %Qx, <8 x i16> %Qy, <8 x i16> %Qw, <16 x i8> %Qu, ptr %dst, ptr %rs2, i32 0, i32 0, i32 %sar)
  %ev1 = extractvalue { <8 x i16>, ptr } %v1, 0
  store <8 x i16> %ev1, ptr %qz_out, align 16
  ret void
}

declare { <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.st.incp(<8 x i16>, <8 x i16>, <8 x i16>, <16 x i8>, ptr, ptr, i32, i32, i32) #5

define dso_local void @test_fft_cmul_s16_ld_xp_with_sar(ptr noundef %src, ptr noundef %rs2, ptr noundef writeonly captures(none) initializes((0, 16)) %qz_out, ptr noundef writeonly captures(none) initializes((0, 16)) %qu_out, i32 noundef %sar_val) local_unnamed_addr #3 {
; ASM-LABEL: test_fft_cmul_s16_ld_xp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    mv a5, a0
; ASM-NEXT:    esp.vld.128.ip q0, a5, 16
; ASM-NEXT:    addi a5, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a5, 16
; ASM-NEXT:    esp.movx.w.sar a4
; ASM-NEXT:    esp.fft.cmul.s16.ld.xp q1, a0, a1, q0, q1, q0, 0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %add.ptr = getelementptr inbounds nuw i8, ptr %src, i32 16
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull %add.ptr, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.fft.cmul.s16.ld.xp(<8 x i16> %bc1, <8 x i16> %bc2, ptr %src, ptr %rs2, i32 0, i32 0, i32 %sar)
  %ev3 = extractvalue { <8 x i16>, <16 x i8>, ptr } %v1, 0
  %ev4 = extractvalue { <8 x i16>, <16 x i8>, ptr } %v1, 1
  store <8 x i16> %ev3, ptr %qz_out, align 16
  store <16 x i8> %ev4, ptr %qu_out, align 16
  ret void
}

declare { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.fft.cmul.s16.ld.xp(<8 x i16>, <8 x i16>, ptr, ptr, i32, i32, i32) #4

define dso_local void @test_fft_cmul_s16_st_xp_with_sar(ptr noundef readonly captures(none) %0, ptr noundef readonly captures(none) %1, ptr noundef readonly captures(none) %2, ptr noundef %dst, ptr noundef %rs2, i32 noundef %sar_val) local_unnamed_addr #2 {
; ASM-LABEL: test_fft_cmul_s16_st_xp_with_sar:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 0
; ASM-NEXT:    esp.vld.128.ip q1, a1, 0
; ASM-NEXT:    esp.vld.128.ip q2, a2, 0
; ASM-NEXT:    esp.movx.w.sar a5
; ASM-NEXT:    esp.fft.cmul.s16.st.xp q1, q0, q2, a3, a4, 0, 0, 0
; ASM-NEXT:    ret
entry:
  %Qx = load <8 x i16>, ptr %0, align 16, !tbaa !156
  %Qy = load <8 x i16>, ptr %1, align 16, !tbaa !156
  %Qu = load <16 x i8>, ptr %2, align 16, !tbaa !156
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call ptr @llvm.riscv.esp.fft.cmul.s16.st.xp(<8 x i16> %Qx, <8 x i16> %Qy, <16 x i8> %Qu, ptr %dst, ptr %rs2, i32 0, i32 0, i32 0, i32 0, i32 %sar)
  ret void
}

declare ptr @llvm.riscv.esp.fft.cmul.s16.st.xp(<8 x i16>, <8 x i16>, <16 x i8>, ptr, ptr, i32, i32, i32, i32, i32) #5

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #4

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #5

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { "target-features"="+32bit,+xespv" }
attributes #4 = { nounwind }
attributes #5 = { nounwind }


!156 = !{!157, !157, i64 0}
!157 = !{!"omnipotent char", !158, i64 0}
!158 = !{!"Simple C/C++ TBAA"}
