; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-vext.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vext_s8_a(ptr noundef %src, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vext_s8_a:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vext.s8 q0, q1, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    esp.vst.128.ip q1, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vext.s8(<16 x i8> %ev1)
  %ev2 = extractvalue { <8 x i16>, <8 x i16> } %v1, 0
  %ev3 = extractvalue { <8 x i16>, <8 x i16> } %v1, 1
  %bc1 = bitcast <8 x i16> %ev2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc1, ptr %dst1, i32 16)
  %bc2 = bitcast <8 x i16> %ev3 to <16 x i8>
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst2, i32 16)
  ret void
}

declare { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vext.s8(<16 x i8>) #1

define dso_local void @test_vext_s16_a(ptr noundef %src, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vext_s16_a:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vext.s16 q0, q1, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    esp.vst.128.ip q1, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vext.s16(<8 x i16> %bc1)
  %ev2 = extractvalue { <4 x i32>, <4 x i32> } %v1, 0
  %ev3 = extractvalue { <4 x i32>, <4 x i32> } %v1, 1
  %bc2 = bitcast <4 x i32> %ev2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst1, i32 16)
  %bc3 = bitcast <4 x i32> %ev3 to <16 x i8>
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst2, i32 16)
  ret void
}

declare { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vext.s16(<8 x i16>) #1

define dso_local void @test_vext_u8_a(ptr noundef %src, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vext_u8_a:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vext.u8 q0, q1, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    esp.vst.128.ip q1, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v1 = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vext.u8(<16 x i8> %ev1)
  %ev2 = extractvalue { <8 x i16>, <8 x i16> } %v1, 0
  %ev3 = extractvalue { <8 x i16>, <8 x i16> } %v1, 1
  %bc1 = bitcast <8 x i16> %ev2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc1, ptr %dst1, i32 16)
  %bc2 = bitcast <8 x i16> %ev3 to <16 x i8>
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst2, i32 16)
  ret void
}

declare { <8 x i16>, <8 x i16> } @llvm.riscv.esp.vext.u8(<16 x i8>) #1

define dso_local void @test_vext_u16_a(ptr noundef %src, ptr noundef %dst1, ptr noundef %dst2) local_unnamed_addr #0 {
; ASM-LABEL: test_vext_u16_a:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vext.u16 q0, q1, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    esp.vst.128.ip q1, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vext.u16(<8 x i16> %bc1)
  %ev2 = extractvalue { <4 x i32>, <4 x i32> } %v1, 0
  %ev3 = extractvalue { <4 x i32>, <4 x i32> } %v1, 1
  %bc2 = bitcast <4 x i32> %ev2 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst1, i32 16)
  %bc3 = bitcast <4 x i32> %ev3 to <16 x i8>
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst2, i32 16)
  ret void
}

declare { <4 x i32>, <4 x i32> } @llvm.riscv.esp.vext.u16(<8 x i16>) #1

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #2

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #3

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { nounwind }
attributes #3 = { nounwind }


