; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-vector-sat.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=xespv2p1 -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vsat_s8(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1, i32 noundef %rs2) local_unnamed_addr #0 {
; ASM-LABEL: test_vsat_s8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vsat.s8 q0, q0, a2, a3
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call <16 x i8> @llvm.riscv.esp.vsat.s8.m(<16 x i8> %1, i32 %rs1, i32 %rs2)
  %3 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %2, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vsat.s8.m(<16 x i8>, i32, i32) #1

define dso_local void @test_vsat_u8(ptr noundef %src, ptr noundef %dst, i32 noundef %rs1, i32 noundef %rs2) local_unnamed_addr #0 {
; ASM-LABEL: test_vsat_u8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vsat.u8 q0, q0, a2, a3
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %0 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr %src, i32 16)
  %1 = extractvalue { <16 x i8>, ptr } %0, 0
  %2 = tail call <16 x i8> @llvm.riscv.esp.vsat.u8.m(<16 x i8> %1, i32 %rs1, i32 %rs2)
  %3 = tail call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> %2, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vsat.u8.m(<16 x i8>, i32, i32) #1

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr, i32) #2

declare ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8>, ptr, i32) #3

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { nounwind }
attributes #3 = { nounwind }


