; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-movx-r-w-sar-bytes.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local i32 @test_movx_sar_bytes_write_read(i32 noundef %rs1_val) local_unnamed_addr #0 {
; ASM-LABEL: test_movx_sar_bytes_write_read:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.movx.w.sar.bytes a0
; ASM-NEXT:    esp.movx.r.sar.bytes a0
; ASM-NEXT:    ret
entry:
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar.bytes(i32 %rs1_val)
  %v1 = tail call i32 @llvm.riscv.esp.movx.r.sar.bytes(i32 %sar)
  ret i32 %v1
}

declare i32 @llvm.riscv.esp.movx.w.sar.bytes(i32) #1

declare i32 @llvm.riscv.esp.movx.r.sar.bytes(i32) #1

define dso_local i32 @test_ld_128_usar_ip_sar_bytes(ptr noundef %src) local_unnamed_addr #2 {
; ASM-LABEL: test_ld_128_usar_ip_sar_bytes:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.128.usar.ip q0, a0, 16
; ASM-NEXT:    esp.movx.r.sar.bytes a0
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr, i32 } %v1, 2
  %v2 = tail call i32 @llvm.riscv.esp.movx.r.sar.bytes(i32 %ev1)
  ret i32 %v2
}

define dso_local i32 @test_ld_128_usar_xp_sar_bytes(ptr noundef %src, i32 noundef %incr) local_unnamed_addr #2 {
; ASM-LABEL: test_ld_128_usar_xp_sar_bytes:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.128.usar.xp q0, a0, a1
; ASM-NEXT:    esp.movx.r.sar.bytes a0
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.xp(ptr %src, i32 %incr)
  %ev1 = extractvalue { <16 x i8>, ptr, i32 } %v1, 2
  %v2 = tail call i32 @llvm.riscv.esp.movx.r.sar.bytes(i32 %ev1)
  ret i32 %v2
}

define dso_local void @test_src_q_with_sar_bytes(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #3 {
; ASM-LABEL: test_src_q_with_sar_bytes:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.128.usar.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.src.q q0, q1, q0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr, i32 } %v1, 0
  %ev2 = extractvalue { <16 x i8>, ptr, i32 } %v1, 2
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v2 = tail call <16 x i8> @llvm.riscv.esp.src.q(i32 %ev2, <16 x i8> %ev1, <16 x i8> %ev3)
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v2, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.src.q(i32, <16 x i8>, <16 x i8>) #1

define dso_local void @test_src_q_ld_ip_with_sar_bytes(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, ptr noundef %dst_qw, ptr noundef %dst_qu) local_unnamed_addr #3 {
; ASM-LABEL: test_src_q_ld_ip_with_sar_bytes:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.128.usar.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.src.q.ld.ip q0, a2, 16, q1, q0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    esp.vst.128.ip q0, a4, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr, i32 } %v1, 0
  %ev2 = extractvalue { <16 x i8>, ptr, i32 } %v1, 2
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v2 = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 %ev2, <16 x i8> %ev1, <16 x i8> %ev3, ptr %src3, i32 16)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, ptr } %v2, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, ptr } %v2, 1
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst_qw, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev5, ptr %dst_qu, i32 16)
  ret void
}

define dso_local void @test_src_q_ld_xp_with_sar_bytes(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, ptr noundef %dst_qw, ptr noundef %dst_qu, i32 noundef %incr) local_unnamed_addr #3 {
; ASM-LABEL: test_src_q_ld_xp_with_sar_bytes:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.128.usar.xp q0, a0, a5
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.src.q.ld.xp q0, a2, a5, q1, q0
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    esp.vst.128.ip q0, a4, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.xp(ptr %src1, i32 %incr)
  %ev1 = extractvalue { <16 x i8>, ptr, i32 } %v1, 0
  %ev2 = extractvalue { <16 x i8>, ptr, i32 } %v1, 2
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v2 = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.xp(i32 %ev2, <16 x i8> %ev1, <16 x i8> %ev3, ptr %src3, i32 %incr)
  %ev4 = extractvalue { <16 x i8>, <16 x i8>, ptr } %v2, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8>, ptr } %v2, 1
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst_qw, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev5, ptr %dst_qu, i32 16)
  ret void
}

define dso_local void @test_src_q_qup_with_sar_bytes(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst_qz, ptr noundef %dst_qw) local_unnamed_addr #3 {
; ASM-LABEL: test_src_q_qup_with_sar_bytes:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.128.usar.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.src.q.qup q0, q1, q0
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    esp.vst.128.ip q1, a3, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr, i32 } %v1, 0
  %ev2 = extractvalue { <16 x i8>, ptr, i32 } %v1, 2
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.src.q.qup(i32 %ev2, <16 x i8> %ev1, <16 x i8> %ev3)
  %ev4 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev5 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev4, ptr %dst_qz, i32 16)
  %vst_ptr.1 = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %ev5, ptr %dst_qw, i32 16)
  ret void
}

define dso_local void @test_srcq_128_st_incp_with_sar_bytes(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #3 {
; ASM-LABEL: test_srcq_128_st_incp_with_sar_bytes:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.ld.128.usar.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.srcq.128.st.incp q1, q0, a2
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr, i32 } %v1, 0
  %ev2 = extractvalue { <16 x i8>, ptr, i32 } %v1, 2
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %v2 = tail call ptr @llvm.riscv.esp.srcq.128.st.incp(i32 %ev2, <16 x i8> %ev1, <16 x i8> %ev3, ptr %dst)
  ret void
}

declare ptr @llvm.riscv.esp.srcq.128.st.incp(i32, <16 x i8>, <16 x i8>, ptr) #4

declare { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr, i32) #5

declare { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.xp(ptr, i32) #5

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #5

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #4

declare { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32, <16 x i8>, <16 x i8>, ptr, i32) #5

declare { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.xp(i32, <16 x i8>, <16 x i8>, ptr, i32) #5

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.src.q.qup(i32, <16 x i8>, <16 x i8>) #1

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { "target-features"="+32bit,+xespv" }
attributes #4 = { nounwind }
attributes #5 = { nounwind }


