; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-vector-ops-16bit.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vadd_s16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vadd_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vadd.s16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vadd.s16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vadd.s16(<8 x i16>, <8 x i16>, i32) #1

define dso_local void @test_vadd_u16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vadd_u16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vadd.u16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vadd.u16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vadd.u16(<8 x i16>, <8 x i16>, i32) #1

define dso_local void @test_vsub_s16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsub_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsub.s16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vsub.s16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vsub.s16(<8 x i16>, <8 x i16>, i32) #1

define dso_local void @test_vmul_s16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vmul_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.movx.w.sar a3
; ASM-NEXT:    esp.vmul.s16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vmul.s16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 7, i32 %sar)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare i32 @llvm.riscv.esp.movx.w.sar(i32) #1

declare <8 x i16> @llvm.riscv.esp.vmul.s16(<8 x i16>, <8 x i16>, i32 immarg, i32 immarg, i32) #1

define dso_local void @test_vmax_s16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vmax_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vmax.s16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vmax.s16(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vmax.s16(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vabs_16(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vabs_16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vabs.16 q0, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vabs.16(<8 x i16> %bc1)
  %bc2 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vabs.16(<8 x i16>) #1

define dso_local i32 @test_max_s16(ptr noundef %src) local_unnamed_addr #2 {
; ASM-LABEL: test_max_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.max.s16.a q0, a0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call i32 @llvm.riscv.esp.max.s16.a(<8 x i16> %bc1)
  ret i32 %v1
}

declare i32 @llvm.riscv.esp.max.s16.a(<8 x i16>) #1

define dso_local i32 @test_min_s16(ptr noundef %src) local_unnamed_addr #2 {
; ASM-LABEL: test_min_s16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.min.s16.a q0, a0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call i32 @llvm.riscv.esp.min.s16.a(<8 x i16> %bc1)
  ret i32 %v1
}

declare i32 @llvm.riscv.esp.min.s16.a(<8 x i16>) #1

define dso_local void @test_vmax_u16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vmax_u16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vmax.u16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vmax.u16(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vmax.u16(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vmin_s16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vmin_s16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vmin.s16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vmin.s16(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vmin.s16(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vmin_u16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vmin_u16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vmin.u16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vmin.u16(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vmin.u16(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vcmp_eq_s16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmp_eq_s16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vcmp.eq.s16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vcmp.eq.s16(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vcmp.eq.s16(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vcmp_gt_s16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmp_gt_s16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vcmp.gt.s16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vcmp.gt.s16(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vcmp.gt.s16(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vcmp_lt_s16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmp_lt_s16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vcmp.lt.s16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vcmp.lt.s16(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vcmp.lt.s16(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vcmp_eq_u16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmp_eq_u16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vcmp.eq.u16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vcmp.eq.u16.m(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vcmp.eq.u16.m(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vcmp_gt_u16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmp_gt_u16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vcmp.gt.u16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vcmp.gt.u16.m(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vcmp.gt.u16.m(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vcmp_lt_u16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmp_lt_u16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vcmp.lt.u16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vcmp.lt.u16(<8 x i16> %bc1, <8 x i16> %bc2)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vcmp.lt.u16(<8 x i16>, <8 x i16>) #1

define dso_local void @test_vsat_s16_vec(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsat_s16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    li a0, 8
; ASM-NEXT:    li a2, -8
; ASM-NEXT:    esp.vsat.s16 q0, q0, a2, a0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vsat.s16(<8 x i16> %bc1, i32 -8, i32 8)
  %bc2 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vsat.s16(<8 x i16>, i32, i32) #1

define dso_local void @test_vsat_u16_vec(ptr noundef %src, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsat_u16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    li a2, 0
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    li a0, 255
; ASM-NEXT:    esp.vsat.u16 q0, q0, a2, a0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vsat.u16(<8 x i16> %bc1, i32 0, i32 255)
  %bc2 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vsat.u16(<8 x i16>, i32, i32) #1

define dso_local void @test_vsub_u16_vec(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsub_u16_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsub.u16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vsub.u16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  %vst_ptr = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

declare <8 x i16> @llvm.riscv.esp.vsub.u16(<8 x i16>, <8 x i16>, i32) #1

define dso_local i32 @test_max_u16_a_vec(ptr noundef %src) local_unnamed_addr #2 {
; ASM-LABEL: test_max_u16_a_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.max.u16.a q0, a0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call i32 @llvm.riscv.esp.max.u16.a(<8 x i16> %bc1)
  ret i32 %v1
}

declare i32 @llvm.riscv.esp.max.u16.a(<8 x i16>) #1

define dso_local i32 @test_min_u16_a_vec(ptr noundef %src) local_unnamed_addr #2 {
; ASM-LABEL: test_min_u16_a_vec:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.min.u16.a q0, a0
; ASM-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %v1 = tail call i32 @llvm.riscv.esp.min.u16.a(<8 x i16> %bc1)
  ret i32 %v1
}

declare i32 @llvm.riscv.esp.min.u16.a(<8 x i16>) #1

declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #3

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #4

attributes #0 = { "target-features"="+32bit,+xespv" }
attributes #1 = { nounwind }
attributes #2 = { "target-features"="+32bit,+xespv" }
attributes #3 = { nounwind }
attributes #4 = { nounwind }


