; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; ModuleID = './riscv-esp32p4-vcmulas.c'
; Test ASM generation (Intrinsic -> ASM)
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM

define dso_local void @test_vcmulas_s8_qacc_h(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s8_qacc_h:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s8.qacc.h q0, q1
; ASM-NEXT:    esp.st.qacc.h.l.128.ip a2, 16
; ASM-NEXT:    esp.st.qacc.h.h.128.ip a2, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 0)
  %ev5 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %v3 = tail call ptr @llvm.riscv.esp.st.qacc.h.l.128.ip(<16 x i8> %ev5, ptr %dst, i32 16)
  %v4 = tail call ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8> %ev6, ptr %v3, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.h(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32 immarg) #1

declare ptr @llvm.riscv.esp.st.qacc.h.l.128.ip(<16 x i8>, ptr, i32) #2

declare ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8>, ptr, i32) #2

define dso_local void @test_vcmulas_s16_qacc_h(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s16_qacc_h:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.h q0, q1
; ASM-NEXT:    esp.st.qacc.h.l.128.ip a2, 16
; ASM-NEXT:    esp.st.qacc.h.h.128.ip a2, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev3 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev4 to <8 x i16>
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8> %ev1, <16 x i8> %ev2, <8 x i16> %bc1, <8 x i16> %bc2, i32 0)
  %ev5 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %v3 = tail call ptr @llvm.riscv.esp.st.qacc.h.l.128.ip(<16 x i8> %ev5, ptr %dst, i32 16)
  %v4 = tail call ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8> %ev6, ptr %v3, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32 immarg) #1

define dso_local void @test_vcmulas_s8_qacc_l(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s8_qacc_l:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s8.qacc.l q0, q1
; ASM-NEXT:    esp.st.qacc.l.l.128.ip a2, 16
; ASM-NEXT:    esp.st.qacc.l.h.128.ip a2, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.l(<16 x i8> %ev1, <16 x i8> %ev2, <16 x i8> %ev3, <16 x i8> %ev4, i32 0)
  %ev5 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %v3 = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8> %ev5, ptr %dst, i32 16)
  %v4 = tail call ptr @llvm.riscv.esp.st.qacc.l.h.128.ip(<16 x i8> %ev6, ptr %v3, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s8.qacc.l(<16 x i8>, <16 x i8>, <16 x i8>, <16 x i8>, i32 immarg) #1

declare ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8>, ptr, i32) #2

declare ptr @llvm.riscv.esp.st.qacc.l.h.128.ip(<16 x i8>, ptr, i32) #2

define dso_local void @test_vcmulas_s16_qacc_l(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s16_qacc_l:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.l q0, q1
; ASM-NEXT:    esp.st.qacc.l.l.128.ip a2, 16
; ASM-NEXT:    esp.st.qacc.l.h.128.ip a2, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 0
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 1
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev3 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev4 to <8 x i16>
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l(<16 x i8> %ev1, <16 x i8> %ev2, <8 x i16> %bc1, <8 x i16> %bc2, i32 0)
  %ev5 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %v3 = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip(<16 x i8> %ev5, ptr %dst, i32 16)
  %v4 = tail call ptr @llvm.riscv.esp.st.qacc.l.h.128.ip(<16 x i8> %ev6, ptr %v3, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.l(<16 x i8>, <16 x i8>, <8 x i16>, <8 x i16>, i32 immarg) #1

define dso_local void @test_vcmulas_s16_qacc_h_accumulate(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, ptr noundef %src4, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s16_qacc_h_accumulate:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.vld.128.ip q3, a3, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.h q0, q1
; ASM-NEXT:    esp.vcmulas.s16.qacc.h q2, q3
; ASM-NEXT:    esp.st.qacc.h.l.128.ip a4, 16
; ASM-NEXT:    esp.st.qacc.h.h.128.ip a4, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev3 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev4 to <8 x i16>
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8> %ev1, <16 x i8> %ev2, <8 x i16> %bc1, <8 x i16> %bc2, i32 0)
  %ev5 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src3, i32 16)
  %ev7 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %bc3 = bitcast <16 x i8> %ev7 to <8 x i16>
  %vld4 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src4, i32 16)
  %ev8 = extractvalue { <16 x i8>, ptr } %vld4, 0
  %bc4 = bitcast <16 x i8> %ev8 to <8 x i16>
  %v3 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8> %ev5, <16 x i8> %ev6, <8 x i16> %bc3, <8 x i16> %bc4, i32 0)
  %ev9 = extractvalue { <16 x i8>, <16 x i8> } %v3, 0
  %ev10 = extractvalue { <16 x i8>, <16 x i8> } %v3, 1
  %v4 = tail call ptr @llvm.riscv.esp.st.qacc.h.l.128.ip(<16 x i8> %ev9, ptr %dst, i32 16)
  %v5 = tail call ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8> %ev10, ptr %v4, i32 16)
  ret void
}

define dso_local void @test_vcmulas_s16_qacc_h_explicit_chain(ptr noundef %src1, ptr noundef %src2, ptr noundef %src3, ptr noundef %src4, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vcmulas_s16_qacc_h_explicit_chain:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vld.128.ip q2, a2, 16
; ASM-NEXT:    esp.vld.128.ip q3, a3, 16
; ASM-NEXT:    esp.zero.qacc
; ASM-NEXT:    esp.vcmulas.s16.qacc.h q0, q1
; ASM-NEXT:    esp.vcmulas.s16.qacc.h q2, q3
; ASM-NEXT:    esp.st.qacc.h.l.128.ip a4, 16
; ASM-NEXT:    esp.st.qacc.h.h.128.ip a4, 16
; ASM-NEXT:    ret
entry:
  %v1 = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc()
  %ev1 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 2
  %ev2 = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } %v1, 3
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev3 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev3 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev4 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev4 to <8 x i16>
  %v2 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8> %ev1, <16 x i8> %ev2, <8 x i16> %bc1, <8 x i16> %bc2, i32 0)
  %ev5 = extractvalue { <16 x i8>, <16 x i8> } %v2, 0
  %ev6 = extractvalue { <16 x i8>, <16 x i8> } %v2, 1
  %vld3 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src3, i32 16)
  %ev7 = extractvalue { <16 x i8>, ptr } %vld3, 0
  %bc3 = bitcast <16 x i8> %ev7 to <8 x i16>
  %vld4 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src4, i32 16)
  %ev8 = extractvalue { <16 x i8>, ptr } %vld4, 0
  %bc4 = bitcast <16 x i8> %ev8 to <8 x i16>
  %v3 = tail call { <16 x i8>, <16 x i8> } @llvm.riscv.esp.vcmulas.s16.qacc.h(<16 x i8> %ev5, <16 x i8> %ev6, <8 x i16> %bc3, <8 x i16> %bc4, i32 0)
  %ev9 = extractvalue { <16 x i8>, <16 x i8> } %v3, 0
  %ev10 = extractvalue { <16 x i8>, <16 x i8> } %v3, 1
  %v4 = tail call ptr @llvm.riscv.esp.st.qacc.h.l.128.ip(<16 x i8> %ev9, ptr %dst, i32 16)
  %v5 = tail call ptr @llvm.riscv.esp.st.qacc.h.h.128.ip(<16 x i8> %ev10, ptr %v4, i32 16)
  ret void
}

declare { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc() #1

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #3

attributes #0 = { nounwind vscale_range(1,1) }
attributes #1 = { nounwind }
attributes #2 = { nounwind }
attributes #3 = { nounwind }


