; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; PIE 2.1-only: VCMP.EQ.U / VCMP.GT.U (deleted in PIE 2.2).
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ESP21
; RUN: not --crash llc -O2 -mattr=+xespv,-xespv2p1,+espv-lowering -mtriple=riscv32 %s -o /dev/null 2>&1 | FileCheck %s --check-prefix=ERR22

define dso_local void @test_vcmp_eq_u8(ptr %src1, ptr %src2, ptr %dst) {
; ESP21-LABEL: test_vcmp_eq_u8:
; ESP21:       # %bb.0:
; ESP21-NEXT:    esp.vld.128.ip q0, a0, 16
; ESP21-NEXT:    esp.vld.128.ip q1, a1, 16
; ESP21-NEXT:    esp.vcmp.eq.u8 q0, q0, q1
; ESP21-NEXT:    esp.vst.128.ip q0, a2, 16
; ESP21-NEXT:    ret
  %ld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %qx = extractvalue { <16 x i8>, ptr } %ld1, 0
  %ld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %qy = extractvalue { <16 x i8>, ptr } %ld2, 0
  %cmp = tail call <16 x i8> @llvm.riscv.esp.vcmp.eq.u8.m(<16 x i8> %qx, <16 x i8> %qy)
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %cmp, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vcmp_gt_u16(ptr %src1, ptr %src2, ptr %dst) {
; ESP21-LABEL: test_vcmp_gt_u16:
; ESP21:       # %bb.0:
; ESP21-NEXT:    esp.vld.128.ip q0, a0, 16
; ESP21-NEXT:    esp.vld.128.ip q1, a1, 16
; ESP21-NEXT:    esp.vcmp.gt.u16 q0, q0, q1
; ESP21-NEXT:    esp.vst.128.ip q0, a2, 16
; ESP21-NEXT:    ret
  %ld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %ld1, 0
  %qx = bitcast <16 x i8> %ev1 to <8 x i16>
  %ld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %ld2, 0
  %qy = bitcast <16 x i8> %ev2 to <8 x i16>
  %cmp = tail call <8 x i16> @llvm.riscv.esp.vcmp.gt.u16.m(<8 x i16> %qx, <8 x i16> %qy)
  %bc = bitcast <8 x i16> %cmp to <16 x i8>
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc, ptr %dst, i32 16)
  ret void
}

; ERR22: LLVM ERROR: Cannot select: intrinsic {{.*}}vcmp

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32)
declare <16 x i8> @llvm.riscv.esp.vcmp.eq.u8.m(<16 x i8>, <16 x i8>)
declare <8 x i16> @llvm.riscv.esp.vcmp.gt.u16.m(<8 x i16>, <8 x i16>)
declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32)
