; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O2 -mattr=+xespv2p1,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM
; RUN: llc -O2 -mattr=+xespv,+espv-lowering -mtriple=riscv32 %s -o - | FileCheck %s --check-prefix=ASM2P2

define dso_local void @test_vsld_8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsld_8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsld.8 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsld_8:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM2P2-NEXT:    esp.vsld.8 q0, q0, q1
; ASM2P2-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vsld.8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 7)
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsrd_8(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsrd_8:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsrd.8 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsrd_8:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM2P2-NEXT:    esp.vsrd.8 q0, q0, q1
; ASM2P2-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %v1 = tail call <16 x i8> @llvm.riscv.esp.vsrd.8(<16 x i8> %ev1, <16 x i8> %ev2, i32 0, i32 7)
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %v1, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsld_16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsld_16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsld.16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsld_16:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM2P2-NEXT:    esp.vsld.16 q0, q0, q1
; ASM2P2-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vsld.16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsrd_16(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsrd_16:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsrd.16 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsrd_16:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM2P2-NEXT:    esp.vsrd.16 q0, q0, q1
; ASM2P2-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <8 x i16>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <8 x i16>
  %v1 = tail call <8 x i16> @llvm.riscv.esp.vsrd.16(<8 x i16> %bc1, <8 x i16> %bc2, i32 0, i32 7)
  %bc3 = bitcast <8 x i16> %v1 to <16 x i8>
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsld_32(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsld_32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsld.32 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsld_32:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM2P2-NEXT:    esp.vsld.32 q0, q0, q1
; ASM2P2-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <4 x i32>
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsld.32(<4 x i32> %bc1, <4 x i32> %bc2, i32 0, i32 7)
  %bc3 = bitcast <4 x i32> %v1 to <16 x i8>
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsrd_32(ptr noundef %src1, ptr noundef %src2, ptr noundef %dst) local_unnamed_addr #0 {
; ASM-LABEL: test_vsrd_32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM-NEXT:    esp.vsrd.32 q0, q0, q1
; ASM-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsrd_32:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.vld.128.ip q1, a1, 16
; ASM2P2-NEXT:    esp.vsrd.32 q0, q0, q1
; ASM2P2-NEXT:    esp.vst.128.ip q0, a2, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src1, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %vld2 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src2, i32 16)
  %ev2 = extractvalue { <16 x i8>, ptr } %vld2, 0
  %bc2 = bitcast <16 x i8> %ev2 to <4 x i32>
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsrd.32(<4 x i32> %bc1, <4 x i32> %bc2, i32 0, i32 7)
  %bc3 = bitcast <4 x i32> %v1 to <16 x i8>
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc3, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsr_s32(ptr noundef %src, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vsr_s32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movx.w.sar a2
; ASM-NEXT:    esp.vsr.s32 q0, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsr_s32:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.movx.w.sar a2
; ASM2P2-NEXT:    esp.vsr.s32 q0, q0
; ASM2P2-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsr.s32(<4 x i32> %bc1, i32 %sar, i32 7)
  %bc2 = bitcast <4 x i32> %v1 to <16 x i8>
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsr_u32(ptr noundef %src, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vsr_u32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movx.w.sar a2
; ASM-NEXT:    esp.vsr.u32 q0, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsr_u32:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.movx.w.sar a2
; ASM2P2-NEXT:    esp.vsr.u32 q0, q0
; ASM2P2-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsr.u32(<4 x i32> %bc1, i32 %sar, i32 7)
  %bc2 = bitcast <4 x i32> %v1 to <16 x i8>
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

define dso_local void @test_vsl_32(ptr noundef %src, ptr noundef %dst, i32 noundef %sar_val) local_unnamed_addr #0 {
; ASM-LABEL: test_vsl_32:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM-NEXT:    esp.movx.w.sar a2
; ASM-NEXT:    esp.vsl.32 q0, q0
; ASM-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM-NEXT:    ret
;
; ASM2P2-LABEL: test_vsl_32:
; ASM2P2:       # %bb.0: # %entry
; ASM2P2-NEXT:    esp.vld.128.ip q0, a0, 16
; ASM2P2-NEXT:    esp.movx.w.sar a2
; ASM2P2-NEXT:    esp.vsl.32 q0, q0
; ASM2P2-NEXT:    esp.vst.128.ip q0, a1, 16
; ASM2P2-NEXT:    ret
entry:
  %vld1 = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 16)
  %ev1 = extractvalue { <16 x i8>, ptr } %vld1, 0
  %bc1 = bitcast <16 x i8> %ev1 to <4 x i32>
  %sar = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 %sar_val)
  %v1 = tail call <4 x i32> @llvm.riscv.esp.vsl.32(<4 x i32> %bc1, i32 0, i32 %sar)
  %bc2 = bitcast <4 x i32> %v1 to <16 x i8>
  tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %bc2, ptr %dst, i32 16)
  ret void
}

declare <16 x i8> @llvm.riscv.esp.vsld.8(<16 x i8>, <16 x i8>, i32 immarg, i32 immarg) #1
declare <16 x i8> @llvm.riscv.esp.vsrd.8(<16 x i8>, <16 x i8>, i32 immarg, i32 immarg) #1
declare <8 x i16> @llvm.riscv.esp.vsld.16(<8 x i16>, <8 x i16>, i32 immarg, i32 immarg) #1
declare <8 x i16> @llvm.riscv.esp.vsrd.16(<8 x i16>, <8 x i16>, i32 immarg, i32 immarg) #1
declare <4 x i32> @llvm.riscv.esp.vsld.32(<4 x i32>, <4 x i32>, i32 immarg, i32 immarg) #1
declare <4 x i32> @llvm.riscv.esp.vsrd.32(<4 x i32>, <4 x i32>, i32 immarg, i32 immarg) #1
declare <4 x i32> @llvm.riscv.esp.vsr.s32(<4 x i32>, i32, i32 immarg) #1
declare <4 x i32> @llvm.riscv.esp.vsr.u32(<4 x i32>, i32, i32 immarg) #1
declare <4 x i32> @llvm.riscv.esp.vsl.32(<4 x i32>, i32 immarg, i32) #1
declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32) #1
declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32) #1
declare i32 @llvm.riscv.esp.movx.w.sar(i32) #1

attributes #0 = { "target-features"="+32bit,+xespv2p1" }
attributes #1 = { nounwind }
