; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=xtensa -mcpu=esp32 -verify-machineinstrs < %s \
; RUN:   | FileCheck -check-prefix=XTENSA %s

declare i32 @llvm.abs.i32(i32, i1)

define i32 @abs_i32(i32 %a) {
; XTENSA-LABEL: abs_i32:
; XTENSA:         .cfi_startproc
; XTENSA-NEXT:  # %bb.0:
; XTENSA-NEXT:    entry a1, 32
; XTENSA-NEXT:    .cfi_def_cfa_offset 32
; XTENSA-NEXT:    abs a2, a2
; XTENSA-NEXT:    retw.n
  %1 = tail call i32 @llvm.abs.i32(i32 %a, i1 false)
  ret i32 %1
}

define i32 @abs_poison_i32(i32 %a) {
; XTENSA-LABEL: abs_poison_i32:
; XTENSA:         .cfi_startproc
; XTENSA-NEXT:  # %bb.0:
; XTENSA-NEXT:    entry a1, 32
; XTENSA-NEXT:    .cfi_def_cfa_offset 32
; XTENSA-NEXT:    abs a2, a2
; XTENSA-NEXT:    retw.n
  %1 = tail call i32 @llvm.abs.i32(i32 %a, i1 true)
  ret i32 %1
}
