; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O1 -mtriple=xtensa -mcpu=esp32 %s -o - | FileCheck %s

define dso_local i32 @test_fshr(i32 %value1, i32 %value2, i32 %shift) nounwind {
; CHECK-LABEL: test_fshr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    entry a1, 32
; CHECK-NEXT:    ssr a4
; CHECK-NEXT:    src a2, a2, a3
; CHECK-NEXT:    retw.n
entry:
  %0 = tail call i32 @llvm.fshr.i32(i32 %value1, i32 %value2, i32 %shift)
  ret i32 %0
}

define dso_local i32 @test_fshl(i32 %value1, i32 %value2, i32 %shift) nounwind {
; CHECK-LABEL: test_fshl:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    entry a1, 32
; CHECK-NEXT:    ssl a4
; CHECK-NEXT:    src a2, a2, a3
; CHECK-NEXT:    retw.n
entry:
  %0 = tail call i32 @llvm.fshl.i32(i32 %value1, i32 %value2, i32 %shift)
  ret i32 %0
}

declare i32 @llvm.fshr.i32(i32, i32, i32) nounwind
declare i32 @llvm.fshl.i32(i32, i32, i32) nounwind
