; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=xtensa -filetype=asm %s -o - | FileCheck %s

; CHECK:  .text
define void @f() {
; CHECK-LABEL: f:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    entry a1, 32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    retw.n
  ret void
}
