; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march xtensa -mcpu=esp32s3 | FileCheck %s -check-prefixes=CHECK

target datalayout = "e-m:e-p:32:32-v1:8:8-i64:64-i128:128-n32"
target triple = "xtensa-esp-unknown-elf"

define <4 x i1> @log_buffer_hexdump_line(<4 x i8> %0) {
; CHECK-LABEL: log_buffer_hexdump_line:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  # %bb.0:
; CHECK-NEXT:    entry a1, 32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    movi a10, 255
; CHECK-NEXT:    and a12, a3, a10
; CHECK-NEXT:    movi.n a8, 1
; CHECK-NEXT:    movi.n a9, 0
; CHECK-NEXT:    mov.n a11, a8
; CHECK-NEXT:    beq a12, a9, .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    mov.n a11, a9
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    and a13, a4, a10
; CHECK-NEXT:    mov.n a12, a8
; CHECK-NEXT:    beq a13, a9, .LBB0_4
; CHECK-NEXT:  # %bb.3:
; CHECK-NEXT:    mov.n a12, a9
; CHECK-NEXT:  .LBB0_4:
; CHECK-NEXT:    _slli a12, a12, 1
; CHECK-NEXT:    or a11, a11, a12
; CHECK-NEXT:    and a13, a5, a10
; CHECK-NEXT:    mov.n a12, a8
; CHECK-NEXT:    beq a13, a9, .LBB0_6
; CHECK-NEXT:  # %bb.5:
; CHECK-NEXT:    mov.n a12, a9
; CHECK-NEXT:  .LBB0_6:
; CHECK-NEXT:    _slli a12, a12, 2
; CHECK-NEXT:    or a11, a11, a12
; CHECK-NEXT:    and a10, a6, a10
; CHECK-NEXT:    beq a10, a9, .LBB0_8
; CHECK-NEXT:  # %bb.7:
; CHECK-NEXT:    mov.n a8, a9
; CHECK-NEXT:  .LBB0_8:
; CHECK-NEXT:    _slli a8, a8, 3
; CHECK-NEXT:    or a8, a11, a8
; CHECK-NEXT:    movi.n a9, 15
; CHECK-NEXT:    and a8, a8, a9
; CHECK-NEXT:    s8i a8, a2, 0
; CHECK-NEXT:    retw.n
  %2 = icmp eq <4 x i8> %0, zeroinitializer
  ret <4 x i1> %2
}
