; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O0 -mtriple=xtensa -mcpu=esp32 %s -o - | FileCheck %s

define <1 x i1> @test_select(<1 x i1>  %cc, <1 x i1> %t, <1 x i1> %f) {
; CHECK-LABEL: test_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    entry a1, 64
; CHECK-NEXT:    movi.n a9, 23
; CHECK-NEXT:    add.n a9, a1, a9
; CHECK-NEXT:    rsr a8, br
; CHECK-NEXT:    extui a8, a8, 1, 1
; CHECK-NEXT:    s8i a8, a9, 0
; CHECK-NEXT:    orb b1, b0, b0
; CHECK-NEXT:    movi.n a8, 23
; CHECK-NEXT:    add.n a8, a1, a8
; CHECK-NEXT:    l8ui a8, a8, 0
; CHECK-NEXT:    extui a8, a8, 0, 1
; CHECK-NEXT:    rsr a10, br
; CHECK-NEXT:    movi a9, 1022
; CHECK-NEXT:    and a10, a10, a9
; CHECK-NEXT:    or a10, a8, a10
; CHECK-NEXT:    wsr a10, br
; CHECK-NEXT:    andbc b1, b2, b1
; CHECK-NEXT:    andb b0, b0, b2
; CHECK-NEXT:    orb b0, b0, b1
; CHECK-NEXT:    retw.n
  %r = select <1 x i1> %cc, <1 x i1> %t, <1 x i1> %f
  ret <1 x i1> %r
}
