; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-dotprod-splitter -riscv-dotprod-splitter=true < %s | FileCheck %s

; Function Attrs: nofree norecurse nosync nounwind memory(read, argmem: readwrite, inaccessiblemem: none)
define dso_local range(i32 0, 458756) i32 @dspi_dotprod_off_s16_ansi(ptr nocapture noundef readonly %in_image, ptr nocapture noundef readonly %filter, ptr nocapture noundef writeonly %out_value, i32 noundef %count_x, i32 noundef %count_y, i32 noundef %shift, i16 noundef signext %offset) local_unnamed_addr {
; CHECK-LABEL: define dso_local range(i32 0, 458756) i32 @dspi_dotprod_off_s16_ansi(
; CHECK-SAME: ptr noundef readonly captures(none) [[IN_IMAGE:%.*]], ptr noundef readonly captures(none) [[FILTER:%.*]], ptr noundef writeonly captures(none) [[OUT_VALUE:%.*]], i32 noundef [[COUNT_X:%.*]], i32 noundef [[COUNT_Y:%.*]], i32 noundef [[SHIFT:%.*]], i16 noundef signext [[OFFSET:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ADD38_US_LOC:%.*]] = alloca i64, align 8
; CHECK-NEXT:    [[STEP_X:%.*]] = getelementptr inbounds i8, ptr [[IN_IMAGE]], i32 4
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[STEP_X]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP0]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X:%.*]] = getelementptr inbounds i8, ptr [[IN_IMAGE]], i32 12
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[STRIDE_X]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[MUL]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[RETURN:.*]], label %[[IF_END:.*]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[STEP_Y:%.*]] = getelementptr inbounds i8, ptr [[IN_IMAGE]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[STEP_Y]], align 4
; CHECK-NEXT:    [[MUL1:%.*]] = mul nsw i32 [[TMP2]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y:%.*]] = getelementptr inbounds i8, ptr [[IN_IMAGE]], i32 16
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[STRIDE_Y]], align 4
; CHECK-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[MUL1]], [[TMP3]]
; CHECK-NEXT:    br i1 [[CMP2]], label %[[RETURN]], label %[[IF_END4:.*]]
; CHECK:       [[IF_END4]]:
; CHECK-NEXT:    [[STEP_X5:%.*]] = getelementptr inbounds i8, ptr [[FILTER]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[STEP_X5]], align 4
; CHECK-NEXT:    [[MUL6:%.*]] = mul nsw i32 [[TMP4]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X7:%.*]] = getelementptr inbounds i8, ptr [[FILTER]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[STRIDE_X7]], align 4
; CHECK-NEXT:    [[CMP8:%.*]] = icmp sgt i32 [[MUL6]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP8]], label %[[RETURN]], label %[[IF_END10:.*]]
; CHECK:       [[IF_END10]]:
; CHECK-NEXT:    [[STEP_Y11:%.*]] = getelementptr inbounds i8, ptr [[FILTER]], i32 8
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[STEP_Y11]], align 4
; CHECK-NEXT:    [[MUL12:%.*]] = mul nsw i32 [[TMP6]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y13:%.*]] = getelementptr inbounds i8, ptr [[FILTER]], i32 16
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[STRIDE_Y13]], align 4
; CHECK-NEXT:    [[CMP14:%.*]] = icmp sgt i32 [[MUL12]], [[TMP7]]
; CHECK-NEXT:    br i1 [[CMP14]], label %[[RETURN]], label %[[IF_END16:.*]]
; CHECK:       [[IF_END16]]:
; CHECK-NEXT:    [[MUL20:%.*]] = mul nsw i32 [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[MUL23:%.*]] = mul nsw i32 [[TMP6]], [[TMP5]]
; CHECK-NEXT:    [[CMP2478:%.*]] = icmp sgt i32 [[COUNT_Y]], 0
; CHECK-NEXT:    br i1 [[CMP2478]], label %[[FOR_COND25_PREHEADER_LR_PH:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND25_PREHEADER_LR_PH]]:
; CHECK-NEXT:    [[CMP2675:%.*]] = icmp sgt i32 [[COUNT_X]], 0
; CHECK-NEXT:    [[CONV35:%.*]] = sext i16 [[OFFSET]] to i32
; CHECK-NEXT:    br i1 [[CMP2675]], label %[[FOR_COND25_PREHEADER_US_PREHEADER:.*]], label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_COND25_PREHEADER_US_PREHEADER]]:
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[IN_IMAGE]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[FILTER]], align 4
; CHECK-NEXT:    br label %[[FOR_COND25_PREHEADER_US:.*]]
; CHECK:       [[FOR_COND25_PREHEADER_US]]:
; CHECK-NEXT:    [[Y_082_US:%.*]] = phi i32 [ [[INC41_US:%.*]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US:.*]] ], [ 0, %[[FOR_COND25_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_081_US:%.*]] = phi i64 [ [[ADD_US_RELOAD:%.*]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]] ], [ 0, %[[FOR_COND25_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    [[I_DATA_080_US:%.*]] = phi ptr [ [[ADD_PTR_US:%.*]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]] ], [ [[TMP8]], %[[FOR_COND25_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    [[F_DATA_079_US:%.*]] = phi ptr [ [[ADD_PTR39_US:%.*]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]] ], [ [[TMP9]], %[[FOR_COND25_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    br label %[[CODEREPL_ENTRY:.*]]
; CHECK:       [[CODEREPL_ENTRY]]:
; CHECK-NEXT:    [[CMP_IMG_STEP1:%.*]] = icmp eq i32 [[TMP0]], 1
; CHECK-NEXT:    [[CMP_FILT_STEP1:%.*]] = icmp eq i32 [[TMP4]], 1
; CHECK-NEXT:    [[COND_STEP1:%.*]] = and i1 [[CMP_IMG_STEP1]], [[CMP_FILT_STEP1]]
; CHECK-NEXT:    br i1 [[COND_STEP1]], label %[[CALL_STEP1:.*]], label %[[CHECK_STEP2:.*]]
; CHECK:       [[CHECK_STEP2]]:
; CHECK-NEXT:    [[CMP_IMG_STEP2:%.*]] = icmp eq i32 [[TMP0]], 2
; CHECK-NEXT:    [[CMP_FILT_STEP2:%.*]] = icmp eq i32 [[TMP4]], 2
; CHECK-NEXT:    [[COND_STEP2:%.*]] = and i1 [[CMP_IMG_STEP2]], [[CMP_FILT_STEP2]]
; CHECK-NEXT:    br i1 [[COND_STEP2]], label %[[CALL_STEP2:.*]], label %[[CHECK_STEP3:.*]]
; CHECK:       [[CHECK_STEP3]]:
; CHECK-NEXT:    [[CMP_IMG_STEP3:%.*]] = icmp eq i32 [[TMP0]], 3
; CHECK-NEXT:    [[CMP_FILT_STEP3:%.*]] = icmp eq i32 [[TMP4]], 3
; CHECK-NEXT:    [[COND_STEP3:%.*]] = and i1 [[CMP_IMG_STEP3]], [[CMP_FILT_STEP3]]
; CHECK-NEXT:    br i1 [[COND_STEP3]], label %[[CALL_STEP3:.*]], label %[[CALL_GENERIC:.*]]
; CHECK:       [[CALL_STEP1]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 -1, ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    call void @dspi_dotprod_off_s16_ansi.for.body28.us(i64 [[ACC_081_US]], i32 1, ptr [[I_DATA_080_US]], i32 1, ptr [[F_DATA_079_US]], i32 [[CONV35]], i32 [[COUNT_X]], ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr [[ADD38_US_LOC]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 -1, ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    br label %[[CALL_MERGE:.*]]
; CHECK:       [[CALL_STEP2]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 -1, ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    call void @dspi_dotprod_off_s16_ansi.for.body28.us(i64 [[ACC_081_US]], i32 2, ptr [[I_DATA_080_US]], i32 2, ptr [[F_DATA_079_US]], i32 [[CONV35]], i32 [[COUNT_X]], ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    [[TMP11:%.*]] = load i64, ptr [[ADD38_US_LOC]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 -1, ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    br label %[[CALL_MERGE]]
; CHECK:       [[CALL_STEP3]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 -1, ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    call void @dspi_dotprod_off_s16_ansi.for.body28.us(i64 [[ACC_081_US]], i32 3, ptr [[I_DATA_080_US]], i32 3, ptr [[F_DATA_079_US]], i32 [[CONV35]], i32 [[COUNT_X]], ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    [[TMP12:%.*]] = load i64, ptr [[ADD38_US_LOC]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 -1, ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    br label %[[CALL_MERGE]]
; CHECK:       [[CALL_GENERIC]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 -1, ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    call void @dspi_dotprod_off_s16_ansi.for.body28.us(i64 [[ACC_081_US]], i32 [[TMP0]], ptr [[I_DATA_080_US]], i32 [[TMP4]], ptr [[F_DATA_079_US]], i32 [[CONV35]], i32 [[COUNT_X]], ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    [[ADD38_US_RELOAD_GENERIC:%.*]] = load i64, ptr [[ADD38_US_LOC]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 -1, ptr [[ADD38_US_LOC]])
; CHECK-NEXT:    br label %[[CALL_MERGE]]
; CHECK:       [[CALL_MERGE]]:
; CHECK-NEXT:    [[ADD_US_RELOAD]] = phi i64 [ [[TMP10]], %[[CALL_STEP1]] ], [ [[TMP11]], %[[CALL_STEP2]] ], [ [[TMP12]], %[[CALL_STEP3]] ], [ [[ADD38_US_RELOAD_GENERIC]], %[[CALL_GENERIC]] ]
; CHECK-NEXT:    br label %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]]
; CHECK:       [[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]]:
; CHECK-NEXT:    [[ADD_PTR_US]] = getelementptr inbounds i16, ptr [[I_DATA_080_US]], i32 [[MUL20]]
; CHECK-NEXT:    [[ADD_PTR39_US]] = getelementptr inbounds i16, ptr [[F_DATA_079_US]], i32 [[MUL23]]
; CHECK-NEXT:    [[INC41_US]] = add nuw nsw i32 [[Y_082_US]], 1
; CHECK-NEXT:    [[EXITCOND85_NOT:%.*]] = icmp eq i32 [[INC41_US]], [[COUNT_Y]]
; CHECK-NEXT:    br i1 [[EXITCOND85_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND25_PREHEADER_US]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi i64 [ 0, %[[IF_END16]] ], [ 0, %[[FOR_COND25_PREHEADER_LR_PH]] ], [ [[ADD_US_RELOAD]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]] ]
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[SHIFT]], -1
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i32 1, [[SUB]]
; CHECK-NEXT:    [[CONV43:%.*]] = sext i32 [[SHL]] to i64
; CHECK-NEXT:    [[ADD44:%.*]] = add nsw i64 [[ACC_0_LCSSA]], [[CONV43]]
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[SHIFT]] to i64
; CHECK-NEXT:    [[SHR:%.*]] = ashr i64 [[ADD44]], [[SH_PROM]]
; CHECK-NEXT:    [[CONV45:%.*]] = trunc i64 [[SHR]] to i16
; CHECK-NEXT:    store i16 [[CONV45]], ptr [[OUT_VALUE]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, %[[FOR_COND_CLEANUP]] ], [ 458755, %[[ENTRY]] ], [ 458755, %[[IF_END]] ], [ 458755, %[[IF_END4]] ], [ 458755, %[[IF_END10]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %add38.us.loc = alloca i64, align 8
  %step_x = getelementptr inbounds i8, ptr %in_image, i32 4
  %0 = load i32, ptr %step_x, align 4
  %mul = mul nsw i32 %0, %count_x
  %stride_x = getelementptr inbounds i8, ptr %in_image, i32 12
  %1 = load i32, ptr %stride_x, align 4
  %cmp = icmp sgt i32 %mul, %1
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %step_y = getelementptr inbounds i8, ptr %in_image, i32 8
  %2 = load i32, ptr %step_y, align 4
  %mul1 = mul nsw i32 %2, %count_y
  %stride_y = getelementptr inbounds i8, ptr %in_image, i32 16
  %3 = load i32, ptr %stride_y, align 4
  %cmp2 = icmp sgt i32 %mul1, %3
  br i1 %cmp2, label %return, label %if.end4

if.end4:                                          ; preds = %if.end
  %step_x5 = getelementptr inbounds i8, ptr %filter, i32 4
  %4 = load i32, ptr %step_x5, align 4
  %mul6 = mul nsw i32 %4, %count_x
  %stride_x7 = getelementptr inbounds i8, ptr %filter, i32 12
  %5 = load i32, ptr %stride_x7, align 4
  %cmp8 = icmp sgt i32 %mul6, %5
  br i1 %cmp8, label %return, label %if.end10

if.end10:                                         ; preds = %if.end4
  %step_y11 = getelementptr inbounds i8, ptr %filter, i32 8
  %6 = load i32, ptr %step_y11, align 4
  %mul12 = mul nsw i32 %6, %count_y
  %stride_y13 = getelementptr inbounds i8, ptr %filter, i32 16
  %7 = load i32, ptr %stride_y13, align 4
  %cmp14 = icmp sgt i32 %mul12, %7
  br i1 %cmp14, label %return, label %if.end16

if.end16:                                         ; preds = %if.end10
  %mul20 = mul nsw i32 %2, %1
  %mul23 = mul nsw i32 %6, %5
  %cmp2478 = icmp sgt i32 %count_y, 0
  br i1 %cmp2478, label %for.cond25.preheader.lr.ph, label %for.cond.cleanup

for.cond25.preheader.lr.ph:                       ; preds = %if.end16
  %cmp2675 = icmp sgt i32 %count_x, 0
  %conv35 = sext i16 %offset to i32
  br i1 %cmp2675, label %for.cond25.preheader.us.preheader, label %for.cond.cleanup

for.cond25.preheader.us.preheader:                ; preds = %for.cond25.preheader.lr.ph
  %8 = load ptr, ptr %in_image, align 4
  %9 = load ptr, ptr %filter, align 4
  br label %for.cond25.preheader.us

for.cond25.preheader.us:                          ; preds = %for.cond25.for.cond.cleanup27_crit_edge.us, %for.cond25.preheader.us.preheader
  %y.082.us = phi i32 [ %inc41.us, %for.cond25.for.cond.cleanup27_crit_edge.us ], [ 0, %for.cond25.preheader.us.preheader ]
  %acc.081.us = phi i64 [ %add38.us.reload, %for.cond25.for.cond.cleanup27_crit_edge.us ], [ 0, %for.cond25.preheader.us.preheader ]
  %i_data.080.us = phi ptr [ %add.ptr.us, %for.cond25.for.cond.cleanup27_crit_edge.us ], [ %8, %for.cond25.preheader.us.preheader ]
  %f_data.079.us = phi ptr [ %add.ptr39.us, %for.cond25.for.cond.cleanup27_crit_edge.us ], [ %9, %for.cond25.preheader.us.preheader ]
  br label %codeRepl

codeRepl:                                         ; preds = %for.cond25.preheader.us
  call void @llvm.lifetime.start.p0(i64 -1, ptr %add38.us.loc)
  call void @dspi_dotprod_off_s16_ansi.for.body28.us(i64 %acc.081.us, i32 %0, ptr %i_data.080.us, i32 %4, ptr %f_data.079.us, i32 %conv35, i32 %count_x, ptr %add38.us.loc)
  %add38.us.reload = load i64, ptr %add38.us.loc, align 8
  call void @llvm.lifetime.end.p0(i64 -1, ptr %add38.us.loc)
  br label %for.cond25.for.cond.cleanup27_crit_edge.us

for.cond25.for.cond.cleanup27_crit_edge.us:       ; preds = %codeRepl
  %add.ptr.us = getelementptr inbounds i16, ptr %i_data.080.us, i32 %mul20
  %add.ptr39.us = getelementptr inbounds i16, ptr %f_data.079.us, i32 %mul23
  %inc41.us = add nuw nsw i32 %y.082.us, 1
  %exitcond85.not = icmp eq i32 %inc41.us, %count_y
  br i1 %exitcond85.not, label %for.cond.cleanup, label %for.cond25.preheader.us

for.cond.cleanup:                                 ; preds = %for.cond25.for.cond.cleanup27_crit_edge.us, %for.cond25.preheader.lr.ph, %if.end16
  %acc.0.lcssa = phi i64 [ 0, %if.end16 ], [ 0, %for.cond25.preheader.lr.ph ], [ %add38.us.reload, %for.cond25.for.cond.cleanup27_crit_edge.us ]
  %sub = add nsw i32 %shift, -1
  %shl = shl nuw i32 1, %sub
  %conv43 = sext i32 %shl to i64
  %add44 = add nsw i64 %acc.0.lcssa, %conv43
  %sh_prom = zext nneg i32 %shift to i64
  %shr = ashr i64 %add44, %sh_prom
  %conv45 = trunc i64 %shr to i16
  store i16 %conv45, ptr %out_value, align 2
  br label %return

return:                                           ; preds = %for.cond.cleanup, %if.end10, %if.end4, %if.end, %entry
  %retval.0 = phi i32 [ 0, %for.cond.cleanup ], [ 458755, %entry ], [ 458755, %if.end ], [ 458755, %if.end4 ], [ 458755, %if.end10 ]
  ret i32 %retval.0
}

; Function Attrs: nofree norecurse nounwind
define internal void @dspi_dotprod_off_s16_ansi.for.body28.us(i64 %acc.081.us, i32 %img_step, ptr %i_data.080.us, i32 %filt_step, ptr %f_data.079.us, i32 %conv35, i32 %count_x, ptr %add38.us.out) {
; CHECK-LABEL: define internal void @dspi_dotprod_off_s16_ansi.for.body28.us(
; CHECK-SAME: i64 [[ACC_081_US:%.*]], i32 [[IMG_STEP:%.*]], ptr [[I_DATA_080_US:%.*]], i32 [[FILT_STEP:%.*]], ptr [[F_DATA_079_US:%.*]], i32 [[CONV35:%.*]], i32 [[COUNT_X:%.*]], ptr [[ADD38_US_OUT:%.*]]) {
; CHECK-NEXT:  [[NEWFUNCROOT:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY28_US:.*]]
; CHECK:       [[FOR_BODY28_US]]:
; CHECK-NEXT:    [[X_077_US:%.*]] = phi i32 [ 0, %[[NEWFUNCROOT]] ], [ [[INC_US:%.*]], %[[FOR_BODY28_US]] ]
; CHECK-NEXT:    [[ACC_176_US:%.*]] = phi i64 [ [[ACC_081_US]], %[[NEWFUNCROOT]] ], [ [[ADD38_US:%.*]], %[[FOR_BODY28_US]] ]
; CHECK-NEXT:    [[MUL30_US:%.*]] = mul nsw i32 [[X_077_US]], [[IMG_STEP]]
; CHECK-NEXT:    [[ARRAYIDX_US:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080_US]], i32 [[MUL30_US]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[ARRAYIDX_US]], align 2
; CHECK-NEXT:    [[CONV_US:%.*]] = sext i16 [[TMP2]] to i32
; CHECK-NEXT:    [[MUL32_US:%.*]] = mul nsw i32 [[X_077_US]], [[FILT_STEP]]
; CHECK-NEXT:    [[ARRAYIDX33_US:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079_US]], i32 [[MUL32_US]]
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[ARRAYIDX33_US]], align 2
; CHECK-NEXT:    [[CONV34_US:%.*]] = sext i16 [[TMP3]] to i32
; CHECK-NEXT:    [[ADD_US:%.*]] = add nsw i32 [[CONV34_US]], [[CONV35]]
; CHECK-NEXT:    [[MUL36_US:%.*]] = mul nsw i32 [[ADD_US]], [[CONV_US]]
; CHECK-NEXT:    [[CONV37_US:%.*]] = sext i32 [[MUL36_US]] to i64
; CHECK-NEXT:    [[ADD38_US]] = add nsw i64 [[ACC_176_US]], [[CONV37_US]]
; CHECK-NEXT:    store i64 [[ADD38_US]], ptr [[ADD38_US_OUT]], align 8
; CHECK-NEXT:    [[INC_US]] = add nuw nsw i32 [[X_077_US]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC_US]], [[COUNT_X]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US_EXITSTUB:.*]], label %[[FOR_BODY28_US]]
; CHECK:       [[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US_EXITSTUB]]:
; CHECK-NEXT:    ret void
;
newFuncRoot:
  br label %for.body28.us

for.body28.us:                                    ; preds = %newFuncRoot, %for.body28.us
  %x.077.us = phi i32 [ 0, %newFuncRoot ], [ %inc.us, %for.body28.us ]
  %acc.176.us = phi i64 [ %acc.081.us, %newFuncRoot ], [ %add38.us, %for.body28.us ]
  %mul30.us = mul nsw i32 %x.077.us, %img_step
  %arrayidx.us = getelementptr inbounds i16, ptr %i_data.080.us, i32 %mul30.us
  %2 = load i16, ptr %arrayidx.us, align 2
  %conv.us = sext i16 %2 to i32
  %mul32.us = mul nsw i32 %x.077.us, %filt_step
  %arrayidx33.us = getelementptr inbounds i16, ptr %f_data.079.us, i32 %mul32.us
  %3 = load i16, ptr %arrayidx33.us, align 2
  %conv34.us = sext i16 %3 to i32
  %add.us = add nsw i32 %conv34.us, %conv35
  %mul36.us = mul nsw i32 %add.us, %conv.us
  %conv37.us = sext i32 %mul36.us to i64
  %add38.us = add nsw i64 %acc.176.us, %conv37.us
  store i64 %add38.us, ptr %add38.us.out, align 8
  %inc.us = add nuw nsw i32 %x.077.us, 1
  %exitcond.not = icmp eq i32 %inc.us, %count_x
  br i1 %exitcond.not, label %for.cond25.for.cond.cleanup27_crit_edge.us.exitStub, label %for.body28.us

for.cond25.for.cond.cleanup27_crit_edge.us.exitStub: ; preds = %for.body28.us
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(i64 immarg, ptr nocapture)

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(i64 immarg, ptr nocapture)
