; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes='module(riscv-dotprod-conditional-loop-extractor),function(riscv-dotprod-splitter)' -riscv-dotprod-splitter=true < %s | FileCheck %s

define dso_local range(i32 0, 458756) i32 @dspi_dotprod_s16_ansi(ptr noundef readonly captures(none) %in_image, ptr noundef readonly captures(none) %filter, ptr noundef writeonly captures(none) %out_value, i32 noundef %count_x, i32 noundef %count_y, i32 noundef %shift) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local range(i32 0, 458756) i32 @dspi_dotprod_s16_ansi(
; CHECK-SAME: ptr noundef readonly captures(none) [[IN_IMAGE:%.*]], ptr noundef readonly captures(none) [[FILTER:%.*]], ptr noundef writeonly captures(none) [[OUT_VALUE:%.*]], i32 noundef [[COUNT_X:%.*]], i32 noundef [[COUNT_Y:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[ADD_US_LOC:%.*]] = alloca i64, align 8
; CHECK-NEXT:    [[STEP_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 4
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[STEP_X]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP0]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 12
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[STRIDE_X]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[MUL]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[RETURN:.*]], label %[[IF_END:.*]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[STEP_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[STEP_Y]], align 4
; CHECK-NEXT:    [[MUL1:%.*]] = mul nsw i32 [[TMP2]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 16
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[STRIDE_Y]], align 4
; CHECK-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[MUL1]], [[TMP3]]
; CHECK-NEXT:    br i1 [[CMP2]], label %[[RETURN]], label %[[IF_END4:.*]]
; CHECK:       [[IF_END4]]:
; CHECK-NEXT:    [[STEP_X5:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[STEP_X5]], align 4
; CHECK-NEXT:    [[MUL6:%.*]] = mul nsw i32 [[TMP4]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X7:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[STRIDE_X7]], align 4
; CHECK-NEXT:    [[CMP8:%.*]] = icmp sgt i32 [[MUL6]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP8]], label %[[RETURN]], label %[[IF_END10:.*]]
; CHECK:       [[IF_END10]]:
; CHECK-NEXT:    [[STEP_Y11:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 8
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[STEP_Y11]], align 4
; CHECK-NEXT:    [[MUL12:%.*]] = mul nsw i32 [[TMP6]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y13:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 16
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[STRIDE_Y13]], align 4
; CHECK-NEXT:    [[CMP14:%.*]] = icmp sgt i32 [[MUL12]], [[TMP7]]
; CHECK-NEXT:    br i1 [[CMP14]], label %[[RETURN]], label %[[IF_END16:.*]]
; CHECK:       [[IF_END16]]:
; CHECK-NEXT:    [[MUL20:%.*]] = mul nsw i32 [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[MUL23:%.*]] = mul nsw i32 [[TMP6]], [[TMP5]]
; CHECK-NEXT:    [[CMP2476:%.*]] = icmp sgt i32 [[COUNT_Y]], 0
; CHECK-NEXT:    [[CMP2673:%.*]] = icmp sgt i32 [[COUNT_X]], 0
; CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[CMP2476]], [[CMP2673]]
; CHECK-NEXT:    br i1 [[OR_COND]], label %[[FOR_COND25_PREHEADER_US_PREHEADER:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND25_PREHEADER_US_PREHEADER]]:
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[IN_IMAGE]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[FILTER]], align 4
; CHECK-NEXT:    br label %[[FOR_COND25_PREHEADER_US:.*]]
; CHECK:       [[FOR_COND25_PREHEADER_US]]:
; CHECK-NEXT:    [[Y_080_US:%.*]] = phi i32 [ [[INC39_US:%.*]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US:.*]] ], [ 0, %[[FOR_COND25_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_079_US:%.*]] = phi i64 [ [[ADD_US_RELOAD:%.*]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]] ], [ 0, %[[FOR_COND25_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    [[I_DATA_078_US:%.*]] = phi ptr [ [[ADD_PTR_US:%.*]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]] ], [ [[TMP8]], %[[FOR_COND25_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    [[F_DATA_077_US:%.*]] = phi ptr [ [[ADD_PTR37_US:%.*]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]] ], [ [[TMP9]], %[[FOR_COND25_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    br label %[[CODEREPL_ENTRY:.*]]
; CHECK:       [[CODEREPL_ENTRY]]:
; CHECK-NEXT:    [[CMP_IMG_STEP1:%.*]] = icmp eq i32 [[TMP0]], 1
; CHECK-NEXT:    [[CMP_FILT_STEP1:%.*]] = icmp eq i32 [[TMP4]], 1
; CHECK-NEXT:    [[COND_STEP1:%.*]] = and i1 [[CMP_IMG_STEP1]], [[CMP_FILT_STEP1]]
; CHECK-NEXT:    br i1 [[COND_STEP1]], label %[[CALL_STEP1:.*]], label %[[CHECK_STEP2:.*]]
; CHECK:       [[CHECK_STEP2]]:
; CHECK-NEXT:    [[CMP_IMG_STEP2:%.*]] = icmp eq i32 [[TMP0]], 2
; CHECK-NEXT:    [[CMP_FILT_STEP2:%.*]] = icmp eq i32 [[TMP4]], 2
; CHECK-NEXT:    [[COND_STEP2:%.*]] = and i1 [[CMP_IMG_STEP2]], [[CMP_FILT_STEP2]]
; CHECK-NEXT:    br i1 [[COND_STEP2]], label %[[CALL_STEP2:.*]], label %[[CHECK_STEP3:.*]]
; CHECK:       [[CHECK_STEP3]]:
; CHECK-NEXT:    [[CMP_IMG_STEP3:%.*]] = icmp eq i32 [[TMP0]], 3
; CHECK-NEXT:    [[CMP_FILT_STEP3:%.*]] = icmp eq i32 [[TMP4]], 3
; CHECK-NEXT:    [[COND_STEP3:%.*]] = and i1 [[CMP_IMG_STEP3]], [[CMP_FILT_STEP3]]
; CHECK-NEXT:    br i1 [[COND_STEP3]], label %[[CALL_STEP3:.*]], label %[[CALL_GENERIC:.*]]
; CHECK:       [[CALL_STEP1]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[ADD_US_LOC]])
; CHECK-NEXT:    call void @dspi_dotprod_s16_ansi.for.body28.us(i64 [[ACC_079_US]], i32 1, ptr [[I_DATA_078_US]], i32 1, ptr [[F_DATA_077_US]], i32 [[COUNT_X]], ptr [[ADD_US_LOC]])
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr [[ADD_US_LOC]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[ADD_US_LOC]])
; CHECK-NEXT:    br label %[[CALL_MERGE:.*]]
; CHECK:       [[CALL_STEP2]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[ADD_US_LOC]])
; CHECK-NEXT:    call void @dspi_dotprod_s16_ansi.for.body28.us(i64 [[ACC_079_US]], i32 2, ptr [[I_DATA_078_US]], i32 2, ptr [[F_DATA_077_US]], i32 [[COUNT_X]], ptr [[ADD_US_LOC]])
; CHECK-NEXT:    [[TMP11:%.*]] = load i64, ptr [[ADD_US_LOC]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[ADD_US_LOC]])
; CHECK-NEXT:    br label %[[CALL_MERGE]]
; CHECK:       [[CALL_STEP3]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[ADD_US_LOC]])
; CHECK-NEXT:    call void @dspi_dotprod_s16_ansi.for.body28.us(i64 [[ACC_079_US]], i32 3, ptr [[I_DATA_078_US]], i32 3, ptr [[F_DATA_077_US]], i32 [[COUNT_X]], ptr [[ADD_US_LOC]])
; CHECK-NEXT:    [[TMP12:%.*]] = load i64, ptr [[ADD_US_LOC]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[ADD_US_LOC]])
; CHECK-NEXT:    br label %[[CALL_MERGE]]
; CHECK:       [[CALL_GENERIC]]:
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[ADD_US_LOC]])
; CHECK-NEXT:    call void @dspi_dotprod_s16_ansi.for.body28.us(i64 [[ACC_079_US]], i32 [[TMP0]], ptr [[I_DATA_078_US]], i32 [[TMP4]], ptr [[F_DATA_077_US]], i32 [[COUNT_X]], ptr [[ADD_US_LOC]])
; CHECK-NEXT:    [[ADD_US_RELOAD_GENERIC:%.*]] = load i64, ptr [[ADD_US_LOC]], align 8
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[ADD_US_LOC]])
; CHECK-NEXT:    br label %[[CALL_MERGE]]
; CHECK:       [[CALL_MERGE]]:
; CHECK-NEXT:    [[ADD_US_RELOAD]] = phi i64 [ [[TMP10]], %[[CALL_STEP1]] ], [ [[TMP11]], %[[CALL_STEP2]] ], [ [[TMP12]], %[[CALL_STEP3]] ], [ [[ADD_US_RELOAD_GENERIC]], %[[CALL_GENERIC]] ]
; CHECK-NEXT:    br label %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]]
; CHECK:       [[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]]:
; CHECK-NEXT:    [[ADD_PTR_US]] = getelementptr inbounds i16, ptr [[I_DATA_078_US]], i32 [[MUL20]]
; CHECK-NEXT:    [[ADD_PTR37_US]] = getelementptr inbounds i16, ptr [[F_DATA_077_US]], i32 [[MUL23]]
; CHECK-NEXT:    [[INC39_US]] = add nuw nsw i32 [[Y_080_US]], 1
; CHECK-NEXT:    [[EXITCOND83_NOT:%.*]] = icmp eq i32 [[INC39_US]], [[COUNT_Y]]
; CHECK-NEXT:    br i1 [[EXITCOND83_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND25_PREHEADER_US]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi i64 [ 0, %[[IF_END16]] ], [ [[ADD_US_RELOAD]], %[[FOR_COND25_FOR_COND_CLEANUP27_CRIT_EDGE_US]] ]
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[SHIFT]], -1
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i32 1, [[SUB]]
; CHECK-NEXT:    [[CONV41:%.*]] = sext i32 [[SHL]] to i64
; CHECK-NEXT:    [[ADD42:%.*]] = add nsw i64 [[ACC_0_LCSSA]], [[CONV41]]
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[SHIFT]] to i64
; CHECK-NEXT:    [[SHR:%.*]] = ashr i64 [[ADD42]], [[SH_PROM]]
; CHECK-NEXT:    [[CONV43:%.*]] = trunc i64 [[SHR]] to i16
; CHECK-NEXT:    store i16 [[CONV43]], ptr [[OUT_VALUE]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, %[[FOR_COND_CLEANUP]] ], [ 458755, %[[ENTRY]] ], [ 458755, %[[IF_END]] ], [ 458755, %[[IF_END4]] ], [ 458755, %[[IF_END10]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %step_x = getelementptr inbounds nuw i8, ptr %in_image, i32 4
  %0 = load i32, ptr %step_x, align 4
  %mul = mul nsw i32 %0, %count_x
  %stride_x = getelementptr inbounds nuw i8, ptr %in_image, i32 12
  %1 = load i32, ptr %stride_x, align 4
  %cmp = icmp sgt i32 %mul, %1
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %step_y = getelementptr inbounds nuw i8, ptr %in_image, i32 8
  %2 = load i32, ptr %step_y, align 4
  %mul1 = mul nsw i32 %2, %count_y
  %stride_y = getelementptr inbounds nuw i8, ptr %in_image, i32 16
  %3 = load i32, ptr %stride_y, align 4
  %cmp2 = icmp sgt i32 %mul1, %3
  br i1 %cmp2, label %return, label %if.end4

if.end4:                                          ; preds = %if.end
  %step_x5 = getelementptr inbounds nuw i8, ptr %filter, i32 4
  %4 = load i32, ptr %step_x5, align 4
  %mul6 = mul nsw i32 %4, %count_x
  %stride_x7 = getelementptr inbounds nuw i8, ptr %filter, i32 12
  %5 = load i32, ptr %stride_x7, align 4
  %cmp8 = icmp sgt i32 %mul6, %5
  br i1 %cmp8, label %return, label %if.end10

if.end10:                                         ; preds = %if.end4
  %step_y11 = getelementptr inbounds nuw i8, ptr %filter, i32 8
  %6 = load i32, ptr %step_y11, align 4
  %mul12 = mul nsw i32 %6, %count_y
  %stride_y13 = getelementptr inbounds nuw i8, ptr %filter, i32 16
  %7 = load i32, ptr %stride_y13, align 4
  %cmp14 = icmp sgt i32 %mul12, %7
  br i1 %cmp14, label %return, label %if.end16

if.end16:                                         ; preds = %if.end10
  %mul20 = mul nsw i32 %2, %1
  %mul23 = mul nsw i32 %6, %5
  %cmp2476 = icmp sgt i32 %count_y, 0
  %cmp2673 = icmp sgt i32 %count_x, 0
  %or.cond = and i1 %cmp2476, %cmp2673
  br i1 %or.cond, label %for.cond25.preheader.us.preheader, label %for.cond.cleanup

for.cond25.preheader.us.preheader:                ; preds = %if.end16
  %8 = load ptr, ptr %in_image, align 4
  %9 = load ptr, ptr %filter, align 4
  br label %for.cond25.preheader.us

for.cond25.preheader.us:                          ; preds = %for.cond25.preheader.us.preheader, %for.cond25.for.cond.cleanup27_crit_edge.us
  %y.080.us = phi i32 [ %inc39.us, %for.cond25.for.cond.cleanup27_crit_edge.us ], [ 0, %for.cond25.preheader.us.preheader ]
  %acc.079.us = phi i64 [ %add.us, %for.cond25.for.cond.cleanup27_crit_edge.us ], [ 0, %for.cond25.preheader.us.preheader ]
  %i_data.078.us = phi ptr [ %add.ptr.us, %for.cond25.for.cond.cleanup27_crit_edge.us ], [ %8, %for.cond25.preheader.us.preheader ]
  %f_data.077.us = phi ptr [ %add.ptr37.us, %for.cond25.for.cond.cleanup27_crit_edge.us ], [ %9, %for.cond25.preheader.us.preheader ]
  br label %for.body28.us

for.body28.us:                                    ; preds = %for.cond25.preheader.us, %for.body28.us
  %x.075.us = phi i32 [ 0, %for.cond25.preheader.us ], [ %inc.us, %for.body28.us ]
  %acc.174.us = phi i64 [ %acc.079.us, %for.cond25.preheader.us ], [ %add.us, %for.body28.us ]
  %mul30.us = mul nsw i32 %x.075.us, %0
  %arrayidx.us = getelementptr inbounds i16, ptr %i_data.078.us, i32 %mul30.us
  %10 = load i16, ptr %arrayidx.us, align 2
  %conv.us = sext i16 %10 to i32
  %mul32.us = mul nsw i32 %x.075.us, %4
  %arrayidx33.us = getelementptr inbounds i16, ptr %f_data.077.us, i32 %mul32.us
  %11 = load i16, ptr %arrayidx33.us, align 2
  %conv34.us = sext i16 %11 to i32
  %mul35.us = mul nsw i32 %conv34.us, %conv.us
  %conv36.us = sext i32 %mul35.us to i64
  %add.us = add nsw i64 %acc.174.us, %conv36.us
  %inc.us = add nuw nsw i32 %x.075.us, 1
  %exitcond.not = icmp eq i32 %inc.us, %count_x
  br i1 %exitcond.not, label %for.cond25.for.cond.cleanup27_crit_edge.us, label %for.body28.us

for.cond25.for.cond.cleanup27_crit_edge.us:       ; preds = %for.body28.us
  %add.ptr.us = getelementptr inbounds i16, ptr %i_data.078.us, i32 %mul20
  %add.ptr37.us = getelementptr inbounds i16, ptr %f_data.077.us, i32 %mul23
  %inc39.us = add nuw nsw i32 %y.080.us, 1
  %exitcond83.not = icmp eq i32 %inc39.us, %count_y
  br i1 %exitcond83.not, label %for.cond.cleanup, label %for.cond25.preheader.us

for.cond.cleanup:                                 ; preds = %for.cond25.for.cond.cleanup27_crit_edge.us, %if.end16
  %acc.0.lcssa = phi i64 [ 0, %if.end16 ], [ %add.us, %for.cond25.for.cond.cleanup27_crit_edge.us ]
  %sub = add nsw i32 %shift, -1
  %shl = shl nuw i32 1, %sub
  %conv41 = sext i32 %shl to i64
  %add42 = add nsw i64 %acc.0.lcssa, %conv41
  %sh_prom = zext nneg i32 %shift to i64
  %shr = ashr i64 %add42, %sh_prom
  %conv43 = trunc i64 %shr to i16
  store i16 %conv43, ptr %out_value, align 2
  br label %return

return:                                           ; preds = %if.end10, %if.end4, %if.end, %entry, %for.cond.cleanup
  %retval.0 = phi i32 [ 0, %for.cond.cleanup ], [ 458755, %entry ], [ 458755, %if.end ], [ 458755, %if.end4 ], [ 458755, %if.end10 ]
  ret i32 %retval.0
}

attributes #0 = { nofree norecurse nosync nounwind memory(read, argmem: readwrite, inaccessiblemem: none) }

