; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -dspi-matrix-size=16x16 -mtriple=riscv32-esp-unknown-elf -passes=riscv-loop-unroll-and-remainder -riscv-loop-unroll-and-remainder=true < %s | FileCheck %s

%struct.image2d_s = type { ptr, i32, i32, i32, i32, i32, i32 }

; Function Attrs: nofree norecurse nosync nounwind memory(readwrite, inaccessiblemem: none)
define dso_local noundef i32 @dspi_conv_f32_ansi(ptr nocapture noundef readonly %in_image, ptr nocapture noundef readonly %filter, ptr nocapture noundef %out_image) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local noundef i32 @dspi_conv_f32_ansi(
; CHECK-SAME: ptr noalias noundef readonly captures(none) [[IN_IMAGE:%.*]], ptr noalias noundef readonly captures(none) [[FILTER:%.*]], ptr noalias noundef captures(none) [[OUT_IMAGE:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SIZE_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 20
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[SIZE_X]], align 4
; CHECK-NEXT:    [[SIZE_X1:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT_IMAGE]], i32 20
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[SIZE_X1]], align 4
; CHECK-NEXT:    [[SIZE_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 24
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[SIZE_Y]], align 4
; CHECK-NEXT:    [[SIZE_Y2:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT_IMAGE]], i32 24
; CHECK-NEXT:    store i32 [[TMP1]], ptr [[SIZE_Y2]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[IN_IMAGE]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[OUT_IMAGE]], align 4
; CHECK-NEXT:    [[SIZE_X4:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 20
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[SIZE_X4]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[TMP4]], -1
; CHECK-NEXT:    [[SHR:%.*]] = ashr i32 [[SUB]], 1
; CHECK-NEXT:    [[SIZE_Y5:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 24
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[SIZE_Y5]], align 4
; CHECK-NEXT:    [[SUB6:%.*]] = add nsw i32 [[TMP5]], -1
; CHECK-NEXT:    [[SHR7:%.*]] = ashr i32 [[SUB6]], 1
; CHECK-NEXT:    [[STRIDE_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[STRIDE_X]], align 4
; CHECK-NEXT:    [[STEP_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 8
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[STEP_Y]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP7]], [[TMP6]]
; CHECK-NEXT:    [[STRIDE_X8:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 12
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[STRIDE_X8]], align 4
; CHECK-NEXT:    [[STEP_Y9:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 8
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[STEP_Y9]], align 4
; CHECK-NEXT:    [[MUL10:%.*]] = mul nsw i32 [[TMP9]], [[TMP8]]
; CHECK-NEXT:    [[CMP938:%.*]] = icmp sgt i32 [[SHR7]], 0
; CHECK-NEXT:    [[STEP_X29:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[STEP_X29]], align 4
; CHECK-NEXT:    [[STEP_Y43:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT_IMAGE]], i32 8
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[STEP_Y43]], align 4
; CHECK-NEXT:    [[STRIDE_X41:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT_IMAGE]], i32 12
; CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[STRIDE_X41]], align 4
; CHECK-NEXT:    [[STEP_X39:%.*]] = getelementptr inbounds nuw i8, ptr [[OUT_IMAGE]], i32 4
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[STEP_X39]], align 4
; CHECK-NEXT:    [[STEP_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 4
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[STEP_X]], align 4
; CHECK-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[FILTER]], align 4
; CHECK-NEXT:    [[DIV526_NEG:%.*]] = sdiv i32 [[TMP4]], -2
; CHECK-NEXT:    [[SUB527:%.*]] = add i32 [[DIV526_NEG]], [[TMP0]]
; CHECK-NEXT:    [[DIV332:%.*]] = sdiv i32 [[TMP5]], 2
; CHECK-NEXT:    [[DOTNEG:%.*]] = sub i32 0, [[TMP1]]
; CHECK-NEXT:    [[SUB330:%.*]] = add i32 [[DIV332]], [[DOTNEG]]
; CHECK-NEXT:    [[DIV469:%.*]] = sdiv i32 [[TMP4]], 2
; CHECK-NEXT:    [[SUB467:%.*]] = sub i32 [[DIV469]], [[TMP0]]
; CHECK-NEXT:    [[SUB240:%.*]] = add i32 [[DIV526_NEG]], [[TMP0]]
; CHECK-NEXT:    [[SUB241:%.*]] = add i32 [[SUB240]], -1
; CHECK-NEXT:    [[SUB109:%.*]] = add nsw i32 [[SUB527]], -1
; CHECK-NEXT:    [[MUL2810:%.*]] = shl nsw i32 [[TMP10]], 1
; CHECK-NEXT:    [[MUL29:%.*]] = mul nsw i32 [[TMP10]], 3
; CHECK-NEXT:    [[MUL3011:%.*]] = shl nsw i32 [[TMP10]], 2
; CHECK-NEXT:    [[MUL31:%.*]] = mul nsw i32 [[TMP10]], 5
; CHECK-NEXT:    [[MUL32:%.*]] = mul nsw i32 [[TMP10]], 6
; CHECK-NEXT:    [[MUL33:%.*]] = mul nsw i32 [[TMP10]], 7
; CHECK-NEXT:    [[MUL34:%.*]] = shl nsw i32 [[TMP10]], 3
; CHECK-NEXT:    [[MUL35:%.*]] = mul nsw i32 [[TMP10]], 9
; CHECK-NEXT:    [[MUL36:%.*]] = mul nsw i32 [[TMP10]], 10
; CHECK-NEXT:    [[MUL37:%.*]] = mul nsw i32 [[TMP10]], 11
; CHECK-NEXT:    [[MUL38:%.*]] = mul nsw i32 [[TMP10]], 12
; CHECK-NEXT:    [[MUL39:%.*]] = mul nsw i32 [[TMP10]], 13
; CHECK-NEXT:    [[MUL4012:%.*]] = mul nsw i32 [[TMP10]], 14
; CHECK-NEXT:    [[MUL41:%.*]] = mul nsw i32 [[TMP10]], 15
; CHECK-NEXT:    [[MUL3413:%.*]] = shl nsw i32 [[TMP14]], 1
; CHECK-NEXT:    [[MUL3514:%.*]] = mul nsw i32 [[TMP14]], 3
; CHECK-NEXT:    [[MUL3615:%.*]] = shl nsw i32 [[TMP14]], 2
; CHECK-NEXT:    [[MUL3716:%.*]] = mul nsw i32 [[TMP14]], 5
; CHECK-NEXT:    [[MUL3817:%.*]] = mul nsw i32 [[TMP14]], 6
; CHECK-NEXT:    [[MUL3918:%.*]] = mul nsw i32 [[TMP14]], 7
; CHECK-NEXT:    [[MUL4019:%.*]] = shl nsw i32 [[TMP14]], 3
; CHECK-NEXT:    [[MUL4120:%.*]] = mul nsw i32 [[TMP14]], 9
; CHECK-NEXT:    [[MUL4221:%.*]] = mul nsw i32 [[TMP14]], 10
; CHECK-NEXT:    [[MUL43:%.*]] = mul nsw i32 [[TMP14]], 11
; CHECK-NEXT:    [[MUL4422:%.*]] = mul nsw i32 [[TMP14]], 12
; CHECK-NEXT:    [[MUL45:%.*]] = mul nsw i32 [[TMP14]], 13
; CHECK-NEXT:    [[MUL46:%.*]] = mul nsw i32 [[TMP14]], 14
; CHECK-NEXT:    [[MUL47:%.*]] = mul nsw i32 [[TMP14]], 15
; CHECK-NEXT:    [[SUB2223:%.*]] = add nsw i32 [[TMP4]], -15
; CHECK-NEXT:    [[CMP12901:%.*]] = icmp sgt i32 [[SHR]], 0
; CHECK-NEXT:    [[CMP55915:%.*]] = icmp slt i32 [[SHR]], [[SUB527]]
; CHECK-NEXT:    [[CMP72905:%.*]] = icmp sgt i32 [[TMP4]], 15
; CHECK-NEXT:    [[CMP112933_NOT:%.*]] = icmp sgt i32 [[SUB527]], [[TMP0]]
; CHECK-NEXT:    [[DIV179_NEG:%.*]] = sdiv i32 [[TMP5]], -2
; CHECK-NEXT:    [[SUB180:%.*]] = add i32 [[DIV179_NEG]], [[TMP1]]
; CHECK-NEXT:    [[CMP181973:%.*]] = icmp slt i32 [[SHR7]], [[SUB180]]
; CHECK-NEXT:    [[CMP197945:%.*]] = icmp sgt i32 [[TMP5]], 0
; CHECK-NEXT:    [[CMP244967:%.*]] = icmp slt i32 [[SUB241]], [[TMP0]]
; CHECK-NEXT:    [[CMP3131028:%.*]] = icmp slt i32 [[SUB180]], [[TMP1]]
; CHECK-NEXT:    [[CMP4431023:%.*]] = icmp slt i32 [[SUB527]], [[TMP0]]
; CHECK-NEXT:    br i1 [[CMP938]], label [[FOR_COND11_PREHEADER:%.*]], label [[FOR_COND176_PREHEADER:%.*]]
; CHECK:       for.cond11.preheader:
; CHECK-NEXT:    [[Y_0940:%.*]] = phi i32 [ [[INC173:%.*]], [[FOR_COND_CLEANUP113:%.*]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[I_POS_0939:%.*]] = phi i32 [ [[ADD171:%.*]], [[FOR_COND_CLEANUP113]] ], [ 0, [[ENTRY]] ]
; CHECK-NEXT:    [[SUB16:%.*]] = sub nsw i32 [[SHR7]], [[Y_0940]]
; CHECK-NEXT:    [[CMP19895:%.*]] = icmp slt i32 [[SUB16]], [[TMP5]]
; CHECK-NEXT:    [[MUL42:%.*]] = mul i32 [[TMP12]], [[TMP11]]
; CHECK-NEXT:    [[MUL44:%.*]] = mul i32 [[MUL42]], [[Y_0940]]
; CHECK-NEXT:    [[INVARIANT_GEP:%.*]] = getelementptr float, ptr [[TMP3]], i32 [[MUL44]]
; CHECK-NEXT:    [[INC173]] = add nuw nsw i32 [[Y_0940]], 1
; CHECK-NEXT:    br i1 [[CMP12901]], label [[FOR_BODY14:%.*]], label [[FOR_COND51_PREHEADER:%.*]]
; CHECK:       for.cond176.preheader:
; CHECK-NEXT:    br i1 [[CMP181973]], label [[FOR_COND186_PREHEADER:%.*]], label [[FOR_COND311_PREHEADER:%.*]]
; CHECK:       for.cond51.preheader:
; CHECK-NEXT:    [[I_POS_Y_0_LCSSA:%.*]] = phi i32 [ [[I_POS_0939]], [[FOR_COND11_PREHEADER]] ], [ [[ADD38:%.*]], [[FOR_COND_CLEANUP20:%.*]] ]
; CHECK-NEXT:    br i1 [[CMP55915]], label [[FOR_BODY57:%.*]], label [[FOR_COND_CLEANUP56:%.*]]
; CHECK:       for.body14:
; CHECK-NEXT:    [[X_0903:%.*]] = phi i32 [ [[INC48:%.*]], [[FOR_COND_CLEANUP20]] ], [ 0, [[FOR_COND11_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_Y_0902:%.*]] = phi i32 [ [[ADD38]], [[FOR_COND_CLEANUP20]] ], [ [[I_POS_0939]], [[FOR_COND11_PREHEADER]] ]
; CHECK-NEXT:    [[SUB22:%.*]] = sub nsw i32 [[SHR]], [[X_0903]]
; CHECK-NEXT:    [[CMP25892:%.*]] = icmp slt i32 [[SUB22]], [[SUB2223]]
; CHECK-NEXT:    [[INC48]] = add nuw nsw i32 [[X_0903]], 1
; CHECK-NEXT:    br i1 [[CMP19895]], label [[FOR_BODY21:%.*]], label [[FOR_COND_CLEANUP20]]
; CHECK:       for.cond.cleanup20:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY14]] ], [ [[ACC_1_LCSSA:%.*]], [[FOR_COND_CLEANUP26:%.*]] ]
; CHECK-NEXT:    [[ADD38]] = add nsw i32 [[I_POS_Y_0902]], [[TMP14]]
; CHECK-NEXT:    [[MUL40:%.*]] = mul nsw i32 [[X_0903]], [[TMP13]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr float, ptr [[INVARIANT_GEP]], i32 [[MUL40]]
; CHECK-NEXT:    store float [[ACC_0_LCSSA]], ptr [[GEP]], align 4
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC48]], [[SHR]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND51_PREHEADER]], label [[FOR_BODY14]]
; CHECK:       for.body21:
; CHECK-NEXT:    [[M_0899:%.*]] = phi i32 [ [[INC35:%.*]], [[FOR_COND_CLEANUP26]] ], [ [[SUB16]], [[FOR_BODY14]] ]
; CHECK-NEXT:    [[F_DATA_0898:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_COND_CLEANUP26]] ], [ [[TMP15]], [[FOR_BODY14]] ]
; CHECK-NEXT:    [[ACC_0897:%.*]] = phi float [ [[ACC_1_LCSSA]], [[FOR_COND_CLEANUP26]] ], [ 0.000000e+00, [[FOR_BODY14]] ]
; CHECK-NEXT:    [[I_POS_X_0896:%.*]] = phi i32 [ [[ADD33:%.*]], [[FOR_COND_CLEANUP26]] ], [ [[I_POS_Y_0902]], [[FOR_BODY14]] ]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr float, ptr [[TMP2]], i32 [[I_POS_X_0896]]
; CHECK-NEXT:    [[INC35]] = add nsw i32 [[M_0899]], 1
; CHECK-NEXT:    br i1 [[CMP25892]], label [[FOR_BODY27_15:%.*]], label [[FOR_COND_PREHEADER:%.*]]
; CHECK:       for.body27.15:
; CHECK-NEXT:    [[N_0894:%.*]] = phi i32 [ [[INC_15:%.*]], [[FOR_BODY27_15]] ], [ [[SUB22]], [[FOR_BODY21]] ]
; CHECK-NEXT:    [[ACC_1893:%.*]] = phi float [ [[TMP64:%.*]], [[FOR_BODY27_15]] ], [ [[ACC_0897]], [[FOR_BODY21]] ]
; CHECK-NEXT:    [[MUL28:%.*]] = mul nsw i32 [[N_0894]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr float, ptr [[TMP16]], i32 [[MUL28]]
; CHECK-NEXT:    [[TMP17:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[MUL30:%.*]] = mul nsw i32 [[N_0894]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX31:%.*]] = getelementptr float, ptr [[F_DATA_0898]], i32 [[MUL30]]
; CHECK-NEXT:    [[TMP18:%.*]] = load float, ptr [[ARRAYIDX31]], align 4
; CHECK-NEXT:    [[TMP19:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP17]], float [[TMP18]], float [[ACC_1893]])
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP20:%.*]] = load float, ptr [[ARRAYIDX_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_1:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP21:%.*]] = load float, ptr [[ARRAYIDX31_1]], align 4
; CHECK-NEXT:    [[TMP22:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP20]], float [[TMP21]], float [[TMP19]])
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL3413]]
; CHECK-NEXT:    [[TMP23:%.*]] = load float, ptr [[ARRAYIDX_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_2:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL2810]]
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr [[ARRAYIDX31_2]], align 4
; CHECK-NEXT:    [[TMP25:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP23]], float [[TMP24]], float [[TMP22]])
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL3514]]
; CHECK-NEXT:    [[TMP26:%.*]] = load float, ptr [[ARRAYIDX_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_3:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL29]]
; CHECK-NEXT:    [[TMP27:%.*]] = load float, ptr [[ARRAYIDX31_3]], align 4
; CHECK-NEXT:    [[TMP28:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP26]], float [[TMP27]], float [[TMP25]])
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL3615]]
; CHECK-NEXT:    [[TMP29:%.*]] = load float, ptr [[ARRAYIDX_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_4:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL3011]]
; CHECK-NEXT:    [[TMP30:%.*]] = load float, ptr [[ARRAYIDX31_4]], align 4
; CHECK-NEXT:    [[TMP31:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP29]], float [[TMP30]], float [[TMP28]])
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL3716]]
; CHECK-NEXT:    [[TMP32:%.*]] = load float, ptr [[ARRAYIDX_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_5:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL31]]
; CHECK-NEXT:    [[TMP33:%.*]] = load float, ptr [[ARRAYIDX31_5]], align 4
; CHECK-NEXT:    [[TMP34:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP32]], float [[TMP33]], float [[TMP31]])
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL3817]]
; CHECK-NEXT:    [[TMP35:%.*]] = load float, ptr [[ARRAYIDX_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_6:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP36:%.*]] = load float, ptr [[ARRAYIDX31_6]], align 4
; CHECK-NEXT:    [[TMP37:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP35]], float [[TMP36]], float [[TMP34]])
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL3918]]
; CHECK-NEXT:    [[TMP38:%.*]] = load float, ptr [[ARRAYIDX_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_7:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP39:%.*]] = load float, ptr [[ARRAYIDX31_7]], align 4
; CHECK-NEXT:    [[TMP40:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP38]], float [[TMP39]], float [[TMP37]])
; CHECK-NEXT:    [[ARRAYIDX_8:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL4019]]
; CHECK-NEXT:    [[TMP41:%.*]] = load float, ptr [[ARRAYIDX_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_8:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL34]]
; CHECK-NEXT:    [[TMP42:%.*]] = load float, ptr [[ARRAYIDX31_8]], align 4
; CHECK-NEXT:    [[TMP43:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP41]], float [[TMP42]], float [[TMP40]])
; CHECK-NEXT:    [[ARRAYIDX_9:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL4120]]
; CHECK-NEXT:    [[TMP44:%.*]] = load float, ptr [[ARRAYIDX_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_9:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL35]]
; CHECK-NEXT:    [[TMP45:%.*]] = load float, ptr [[ARRAYIDX31_9]], align 4
; CHECK-NEXT:    [[TMP46:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP44]], float [[TMP45]], float [[TMP43]])
; CHECK-NEXT:    [[ARRAYIDX_10:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL4221]]
; CHECK-NEXT:    [[TMP47:%.*]] = load float, ptr [[ARRAYIDX_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_10:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL36]]
; CHECK-NEXT:    [[TMP48:%.*]] = load float, ptr [[ARRAYIDX31_10]], align 4
; CHECK-NEXT:    [[TMP49:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP47]], float [[TMP48]], float [[TMP46]])
; CHECK-NEXT:    [[ARRAYIDX_11:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL43]]
; CHECK-NEXT:    [[TMP50:%.*]] = load float, ptr [[ARRAYIDX_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_11:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL37]]
; CHECK-NEXT:    [[TMP51:%.*]] = load float, ptr [[ARRAYIDX31_11]], align 4
; CHECK-NEXT:    [[TMP52:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP50]], float [[TMP51]], float [[TMP49]])
; CHECK-NEXT:    [[ARRAYIDX_12:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL4422]]
; CHECK-NEXT:    [[TMP53:%.*]] = load float, ptr [[ARRAYIDX_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_12:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL38]]
; CHECK-NEXT:    [[TMP54:%.*]] = load float, ptr [[ARRAYIDX31_12]], align 4
; CHECK-NEXT:    [[TMP55:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP53]], float [[TMP54]], float [[TMP52]])
; CHECK-NEXT:    [[ARRAYIDX_13:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL45]]
; CHECK-NEXT:    [[TMP56:%.*]] = load float, ptr [[ARRAYIDX_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_13:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL39]]
; CHECK-NEXT:    [[TMP57:%.*]] = load float, ptr [[ARRAYIDX31_13]], align 4
; CHECK-NEXT:    [[TMP58:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP56]], float [[TMP57]], float [[TMP55]])
; CHECK-NEXT:    [[ARRAYIDX_14:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL46]]
; CHECK-NEXT:    [[TMP59:%.*]] = load float, ptr [[ARRAYIDX_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_14:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL4012]]
; CHECK-NEXT:    [[TMP60:%.*]] = load float, ptr [[ARRAYIDX31_14]], align 4
; CHECK-NEXT:    [[TMP61:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP59]], float [[TMP60]], float [[TMP58]])
; CHECK-NEXT:    [[ARRAYIDX_15:%.*]] = getelementptr float, ptr [[ARRAYIDX]], i32 [[MUL47]]
; CHECK-NEXT:    [[TMP62:%.*]] = load float, ptr [[ARRAYIDX_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX31_15:%.*]] = getelementptr float, ptr [[ARRAYIDX31]], i32 [[MUL41]]
; CHECK-NEXT:    [[TMP63:%.*]] = load float, ptr [[ARRAYIDX31_15]], align 4
; CHECK-NEXT:    [[TMP64]] = tail call float @llvm.fmuladd.f32(float [[TMP62]], float [[TMP63]], float [[TMP61]])
; CHECK-NEXT:    [[INC_15]] = add nsw i32 [[N_0894]], 16
; CHECK-NEXT:    [[CMP25_15:%.*]] = icmp slt i32 [[INC_15]], [[SUB2223]]
; CHECK-NEXT:    br i1 [[CMP25_15]], label [[FOR_BODY27_15]], label [[FOR_COND_PREHEADER]]
; CHECK:       for.cond.preheader:
; CHECK-NEXT:    [[TMP65:%.*]] = phi float [ [[ACC_0897]], [[FOR_BODY21]] ], [ [[TMP64]], [[FOR_BODY27_15]] ]
; CHECK-NEXT:    [[TMP66:%.*]] = phi i32 [ [[SUB22]], [[FOR_BODY21]] ], [ [[INC_15]], [[FOR_BODY27_15]] ]
; CHECK-NEXT:    [[TMP67:%.*]] = icmp slt i32 [[TMP66]], [[TMP4]]
; CHECK-NEXT:    br i1 [[TMP67]], label [[FOR_BODY27_CLONE:%.*]], label [[FOR_COND_CLEANUP26]]
; CHECK:       for.body27.clone:
; CHECK-NEXT:    [[N_0894_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY27_CLONE]] ], [ [[TMP66]], [[FOR_COND_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_1893_CLONE:%.*]] = phi float [ [[TMP70:%.*]], [[FOR_BODY27_CLONE]] ], [ [[TMP65]], [[FOR_COND_PREHEADER]] ]
; CHECK-NEXT:    [[MUL28_CLONE:%.*]] = mul nsw i32 [[N_0894_CLONE]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr float, ptr [[TMP16]], i32 [[MUL28_CLONE]]
; CHECK-NEXT:    [[TMP68:%.*]] = load float, ptr [[ARRAYIDX_CLONE]], align 4
; CHECK-NEXT:    [[MUL30_CLONE:%.*]] = mul nsw i32 [[N_0894_CLONE]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX31_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA_0898]], i32 [[MUL30_CLONE]]
; CHECK-NEXT:    [[TMP69:%.*]] = load float, ptr [[ARRAYIDX31_CLONE]], align 4
; CHECK-NEXT:    [[TMP70]] = tail call float @llvm.fmuladd.f32(float [[TMP68]], float [[TMP69]], float [[ACC_1893_CLONE]])
; CHECK-NEXT:    [[INC_CLONE]] = add nsw i32 [[N_0894_CLONE]], 1
; CHECK-NEXT:    [[CMP25_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[TMP4]]
; CHECK-NEXT:    br i1 [[CMP25_CLONE]], label [[FOR_COND_CLEANUP26]], label [[FOR_BODY27_CLONE]]
; CHECK:       for.cond.cleanup26:
; CHECK-NEXT:    [[ACC_1_LCSSA]] = phi float [ [[TMP65]], [[FOR_COND_PREHEADER]] ], [ [[TMP70]], [[FOR_BODY27_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr inbounds float, ptr [[F_DATA_0898]], i32 [[MUL10]]
; CHECK-NEXT:    [[ADD33]] = add nsw i32 [[I_POS_X_0896]], [[MUL]]
; CHECK-NEXT:    [[CMP19:%.*]] = icmp slt i32 [[INC35]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP19]], label [[FOR_BODY21]], label [[FOR_COND_CLEANUP20]]
; CHECK:       for.cond.cleanup56:
; CHECK-NEXT:    [[I_POS_Y_1_LCSSA:%.*]] = phi i32 [ [[I_POS_Y_0_LCSSA]], [[FOR_COND51_PREHEADER]] ], [ [[ADD92:%.*]], [[FOR_COND_CLEANUP67:%.*]] ]
; CHECK-NEXT:    br i1 [[CMP112933_NOT]], label [[FOR_COND_CLEANUP113]], label [[FOR_BODY114:%.*]]
; CHECK:       for.body57:
; CHECK-NEXT:    [[X50_0917:%.*]] = phi i32 [ [[INC102:%.*]], [[FOR_COND_CLEANUP67]] ], [ [[SHR]], [[FOR_COND51_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_Y_1916:%.*]] = phi i32 [ [[ADD92]], [[FOR_COND_CLEANUP67]] ], [ [[I_POS_Y_0_LCSSA]], [[FOR_COND51_PREHEADER]] ]
; CHECK-NEXT:    [[INC102]] = add nsw i32 [[X50_0917]], 1
; CHECK-NEXT:    br i1 [[CMP19895]], label [[FOR_COND70_PREHEADER:%.*]], label [[FOR_COND_CLEANUP67]]
; CHECK:       for.cond70.preheader:
; CHECK-NEXT:    [[M62_0913:%.*]] = phi i32 [ [[INC89:%.*]], [[FOR_COND_CLEANUP73:%.*]] ], [ [[SUB16]], [[FOR_BODY57]] ]
; CHECK-NEXT:    [[F_DATA60_0912:%.*]] = phi ptr [ [[ADD_PTR86:%.*]], [[FOR_COND_CLEANUP73]] ], [ [[TMP15]], [[FOR_BODY57]] ]
; CHECK-NEXT:    [[ACC59_0911:%.*]] = phi float [ [[ACC59_1_LCSSA:%.*]], [[FOR_COND_CLEANUP73]] ], [ 0.000000e+00, [[FOR_BODY57]] ]
; CHECK-NEXT:    [[I_POS_X58_0910:%.*]] = phi i32 [ [[ADD87:%.*]], [[FOR_COND_CLEANUP73]] ], [ [[I_POS_Y_1916]], [[FOR_BODY57]] ]
; CHECK-NEXT:    [[TMP71:%.*]] = getelementptr float, ptr [[TMP2]], i32 [[I_POS_X58_0910]]
; CHECK-NEXT:    [[INC89]] = add nsw i32 [[M62_0913]], 1
; CHECK-NEXT:    br i1 [[CMP72905]], label [[FOR_BODY74_15:%.*]], label [[FOR_COND_PREHEADER24:%.*]]
; CHECK:       for.cond.cleanup67:
; CHECK-NEXT:    [[ACC59_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY57]] ], [ [[ACC59_1_LCSSA]], [[FOR_COND_CLEANUP73]] ]
; CHECK-NEXT:    [[ADD92]] = add nsw i32 [[I_POS_Y_1916]], [[TMP14]]
; CHECK-NEXT:    [[MUL94:%.*]] = mul nsw i32 [[X50_0917]], [[TMP13]]
; CHECK-NEXT:    [[GEP922:%.*]] = getelementptr float, ptr [[INVARIANT_GEP]], i32 [[MUL94]]
; CHECK-NEXT:    store float [[ACC59_0_LCSSA]], ptr [[GEP922]], align 4
; CHECK-NEXT:    [[EXITCOND1058_NOT:%.*]] = icmp eq i32 [[INC102]], [[SUB527]]
; CHECK-NEXT:    br i1 [[EXITCOND1058_NOT]], label [[FOR_COND_CLEANUP56]], label [[FOR_BODY57]]
; CHECK:       for.body74.15:
; CHECK-NEXT:    [[N69_0907:%.*]] = phi i32 [ [[INC84_15:%.*]], [[FOR_BODY74_15]] ], [ 0, [[FOR_COND70_PREHEADER]] ]
; CHECK-NEXT:    [[ACC59_1906:%.*]] = phi float [ [[TMP119:%.*]], [[FOR_BODY74_15]] ], [ [[ACC59_0911]], [[FOR_COND70_PREHEADER]] ]
; CHECK-NEXT:    [[MUL76:%.*]] = mul nsw i32 [[N69_0907]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX78:%.*]] = getelementptr float, ptr [[TMP71]], i32 [[MUL76]]
; CHECK-NEXT:    [[TMP72:%.*]] = load float, ptr [[ARRAYIDX78]], align 4
; CHECK-NEXT:    [[MUL80:%.*]] = mul nsw i32 [[N69_0907]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX81:%.*]] = getelementptr float, ptr [[F_DATA60_0912]], i32 [[MUL80]]
; CHECK-NEXT:    [[TMP73:%.*]] = load float, ptr [[ARRAYIDX81]], align 4
; CHECK-NEXT:    [[TMP74:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP72]], float [[TMP73]], float [[ACC59_1906]])
; CHECK-NEXT:    [[ARRAYIDX78_1:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP75:%.*]] = load float, ptr [[ARRAYIDX78_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_1:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP76:%.*]] = load float, ptr [[ARRAYIDX81_1]], align 4
; CHECK-NEXT:    [[TMP77:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP75]], float [[TMP76]], float [[TMP74]])
; CHECK-NEXT:    [[ARRAYIDX78_2:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL3413]]
; CHECK-NEXT:    [[TMP78:%.*]] = load float, ptr [[ARRAYIDX78_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_2:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL2810]]
; CHECK-NEXT:    [[TMP79:%.*]] = load float, ptr [[ARRAYIDX81_2]], align 4
; CHECK-NEXT:    [[TMP80:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP78]], float [[TMP79]], float [[TMP77]])
; CHECK-NEXT:    [[ARRAYIDX78_3:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL3514]]
; CHECK-NEXT:    [[TMP81:%.*]] = load float, ptr [[ARRAYIDX78_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_3:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL29]]
; CHECK-NEXT:    [[TMP82:%.*]] = load float, ptr [[ARRAYIDX81_3]], align 4
; CHECK-NEXT:    [[TMP83:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP81]], float [[TMP82]], float [[TMP80]])
; CHECK-NEXT:    [[ARRAYIDX78_4:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL3615]]
; CHECK-NEXT:    [[TMP84:%.*]] = load float, ptr [[ARRAYIDX78_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_4:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL3011]]
; CHECK-NEXT:    [[TMP85:%.*]] = load float, ptr [[ARRAYIDX81_4]], align 4
; CHECK-NEXT:    [[TMP86:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP84]], float [[TMP85]], float [[TMP83]])
; CHECK-NEXT:    [[ARRAYIDX78_5:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL3716]]
; CHECK-NEXT:    [[TMP87:%.*]] = load float, ptr [[ARRAYIDX78_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_5:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL31]]
; CHECK-NEXT:    [[TMP88:%.*]] = load float, ptr [[ARRAYIDX81_5]], align 4
; CHECK-NEXT:    [[TMP89:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP87]], float [[TMP88]], float [[TMP86]])
; CHECK-NEXT:    [[ARRAYIDX78_6:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL3817]]
; CHECK-NEXT:    [[TMP90:%.*]] = load float, ptr [[ARRAYIDX78_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_6:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP91:%.*]] = load float, ptr [[ARRAYIDX81_6]], align 4
; CHECK-NEXT:    [[TMP92:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP90]], float [[TMP91]], float [[TMP89]])
; CHECK-NEXT:    [[ARRAYIDX78_7:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL3918]]
; CHECK-NEXT:    [[TMP93:%.*]] = load float, ptr [[ARRAYIDX78_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_7:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP94:%.*]] = load float, ptr [[ARRAYIDX81_7]], align 4
; CHECK-NEXT:    [[TMP95:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP93]], float [[TMP94]], float [[TMP92]])
; CHECK-NEXT:    [[ARRAYIDX78_8:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL4019]]
; CHECK-NEXT:    [[TMP96:%.*]] = load float, ptr [[ARRAYIDX78_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_8:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL34]]
; CHECK-NEXT:    [[TMP97:%.*]] = load float, ptr [[ARRAYIDX81_8]], align 4
; CHECK-NEXT:    [[TMP98:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP96]], float [[TMP97]], float [[TMP95]])
; CHECK-NEXT:    [[ARRAYIDX78_9:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL4120]]
; CHECK-NEXT:    [[TMP99:%.*]] = load float, ptr [[ARRAYIDX78_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_9:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL35]]
; CHECK-NEXT:    [[TMP100:%.*]] = load float, ptr [[ARRAYIDX81_9]], align 4
; CHECK-NEXT:    [[TMP101:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP99]], float [[TMP100]], float [[TMP98]])
; CHECK-NEXT:    [[ARRAYIDX78_10:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL4221]]
; CHECK-NEXT:    [[TMP102:%.*]] = load float, ptr [[ARRAYIDX78_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_10:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL36]]
; CHECK-NEXT:    [[TMP103:%.*]] = load float, ptr [[ARRAYIDX81_10]], align 4
; CHECK-NEXT:    [[TMP104:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP102]], float [[TMP103]], float [[TMP101]])
; CHECK-NEXT:    [[ARRAYIDX78_11:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL43]]
; CHECK-NEXT:    [[TMP105:%.*]] = load float, ptr [[ARRAYIDX78_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_11:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL37]]
; CHECK-NEXT:    [[TMP106:%.*]] = load float, ptr [[ARRAYIDX81_11]], align 4
; CHECK-NEXT:    [[TMP107:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP105]], float [[TMP106]], float [[TMP104]])
; CHECK-NEXT:    [[ARRAYIDX78_12:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL4422]]
; CHECK-NEXT:    [[TMP108:%.*]] = load float, ptr [[ARRAYIDX78_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_12:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL38]]
; CHECK-NEXT:    [[TMP109:%.*]] = load float, ptr [[ARRAYIDX81_12]], align 4
; CHECK-NEXT:    [[TMP110:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP108]], float [[TMP109]], float [[TMP107]])
; CHECK-NEXT:    [[ARRAYIDX78_13:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL45]]
; CHECK-NEXT:    [[TMP111:%.*]] = load float, ptr [[ARRAYIDX78_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_13:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL39]]
; CHECK-NEXT:    [[TMP112:%.*]] = load float, ptr [[ARRAYIDX81_13]], align 4
; CHECK-NEXT:    [[TMP113:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP111]], float [[TMP112]], float [[TMP110]])
; CHECK-NEXT:    [[ARRAYIDX78_14:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL46]]
; CHECK-NEXT:    [[TMP114:%.*]] = load float, ptr [[ARRAYIDX78_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_14:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL4012]]
; CHECK-NEXT:    [[TMP115:%.*]] = load float, ptr [[ARRAYIDX81_14]], align 4
; CHECK-NEXT:    [[TMP116:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP114]], float [[TMP115]], float [[TMP113]])
; CHECK-NEXT:    [[ARRAYIDX78_15:%.*]] = getelementptr float, ptr [[ARRAYIDX78]], i32 [[MUL47]]
; CHECK-NEXT:    [[TMP117:%.*]] = load float, ptr [[ARRAYIDX78_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX81_15:%.*]] = getelementptr float, ptr [[ARRAYIDX81]], i32 [[MUL41]]
; CHECK-NEXT:    [[TMP118:%.*]] = load float, ptr [[ARRAYIDX81_15]], align 4
; CHECK-NEXT:    [[TMP119]] = tail call float @llvm.fmuladd.f32(float [[TMP117]], float [[TMP118]], float [[TMP116]])
; CHECK-NEXT:    [[INC84_15]] = add nuw nsw i32 [[N69_0907]], 16
; CHECK-NEXT:    [[EXITCOND1057_NOT_15:%.*]] = icmp slt i32 [[INC84_15]], [[SUB2223]]
; CHECK-NEXT:    br i1 [[EXITCOND1057_NOT_15]], label [[FOR_BODY74_15]], label [[FOR_COND_PREHEADER24]]
; CHECK:       for.cond.preheader24:
; CHECK-NEXT:    [[TMP120:%.*]] = phi float [ [[ACC59_0911]], [[FOR_COND70_PREHEADER]] ], [ [[TMP119]], [[FOR_BODY74_15]] ]
; CHECK-NEXT:    [[TMP121:%.*]] = phi i32 [ 0, [[FOR_COND70_PREHEADER]] ], [ [[INC84_15]], [[FOR_BODY74_15]] ]
; CHECK-NEXT:    [[TMP122:%.*]] = icmp slt i32 [[TMP121]], [[TMP4]]
; CHECK-NEXT:    br i1 [[TMP122]], label [[FOR_BODY74_CLONE:%.*]], label [[FOR_COND_CLEANUP73]]
; CHECK:       for.body74.clone:
; CHECK-NEXT:    [[N69_0907_CLONE:%.*]] = phi i32 [ [[INC84_CLONE:%.*]], [[FOR_BODY74_CLONE]] ], [ [[TMP121]], [[FOR_COND_PREHEADER24]] ]
; CHECK-NEXT:    [[ACC59_1906_CLONE:%.*]] = phi float [ [[TMP125:%.*]], [[FOR_BODY74_CLONE]] ], [ [[TMP120]], [[FOR_COND_PREHEADER24]] ]
; CHECK-NEXT:    [[MUL76_CLONE:%.*]] = mul nsw i32 [[N69_0907_CLONE]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX78_CLONE:%.*]] = getelementptr float, ptr [[TMP71]], i32 [[MUL76_CLONE]]
; CHECK-NEXT:    [[TMP123:%.*]] = load float, ptr [[ARRAYIDX78_CLONE]], align 4
; CHECK-NEXT:    [[MUL80_CLONE:%.*]] = mul nsw i32 [[N69_0907_CLONE]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX81_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA60_0912]], i32 [[MUL80_CLONE]]
; CHECK-NEXT:    [[TMP124:%.*]] = load float, ptr [[ARRAYIDX81_CLONE]], align 4
; CHECK-NEXT:    [[TMP125]] = tail call float @llvm.fmuladd.f32(float [[TMP123]], float [[TMP124]], float [[ACC59_1906_CLONE]])
; CHECK-NEXT:    [[INC84_CLONE]] = add nuw nsw i32 [[N69_0907_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND1057_NOT_CLONE:%.*]] = icmp eq i32 [[INC84_CLONE]], [[TMP4]]
; CHECK-NEXT:    br i1 [[EXITCOND1057_NOT_CLONE]], label [[FOR_COND_CLEANUP73]], label [[FOR_BODY74_CLONE]]
; CHECK:       for.cond.cleanup73:
; CHECK-NEXT:    [[ACC59_1_LCSSA]] = phi float [ [[TMP120]], [[FOR_COND_PREHEADER24]] ], [ [[TMP125]], [[FOR_BODY74_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR86]] = getelementptr inbounds float, ptr [[F_DATA60_0912]], i32 [[MUL10]]
; CHECK-NEXT:    [[ADD87]] = add nsw i32 [[I_POS_X58_0910]], [[MUL]]
; CHECK-NEXT:    [[CMP66:%.*]] = icmp slt i32 [[INC89]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP66]], label [[FOR_COND70_PREHEADER]], label [[FOR_COND_CLEANUP67]]
; CHECK:       for.cond.cleanup113:
; CHECK-NEXT:    [[ADD171]] = add nsw i32 [[I_POS_0939]], [[MUL]]
; CHECK-NEXT:    [[EXITCOND1060_NOT:%.*]] = icmp eq i32 [[INC173]], [[SHR7]]
; CHECK-NEXT:    br i1 [[EXITCOND1060_NOT]], label [[FOR_COND176_PREHEADER]], label [[FOR_COND11_PREHEADER]]
; CHECK:       for.body114:
; CHECK-NEXT:    [[X104_0935:%.*]] = phi i32 [ [[INC166:%.*]], [[FOR_COND_CLEANUP124:%.*]] ], [ [[SUB109]], [[FOR_COND_CLEANUP56]] ]
; CHECK-NEXT:    [[I_POS_Y_2934:%.*]] = phi i32 [ [[ADD156:%.*]], [[FOR_COND_CLEANUP124]] ], [ [[I_POS_Y_1_LCSSA]], [[FOR_COND_CLEANUP56]] ]
; CHECK-NEXT:    [[ADD133:%.*]] = add i32 [[X104_0935]], [[SUB467]]
; CHECK-NEXT:    [[ADD134_NEG:%.*]] = xor i32 [[ADD133]], -1
; CHECK-NEXT:    [[SUB135:%.*]] = add i32 [[ADD134_NEG]], [[TMP4]]
; CHECK-NEXT:    [[CMP136923:%.*]] = icmp sgt i32 [[SUB135]], 15
; CHECK-NEXT:    [[SUB216:%.*]] = add nsw i32 [[SUB135]], -15
; CHECK-NEXT:    [[INC166]] = add nsw i32 [[X104_0935]], 1
; CHECK-NEXT:    br i1 [[CMP19895]], label [[FOR_COND127_PREHEADER:%.*]], label [[FOR_COND_CLEANUP124]]
; CHECK:       for.cond127.preheader:
; CHECK-NEXT:    [[M119_0931:%.*]] = phi i32 [ [[INC153:%.*]], [[FOR_COND_CLEANUP137:%.*]] ], [ [[SUB16]], [[FOR_BODY114]] ]
; CHECK-NEXT:    [[F_DATA117_0930:%.*]] = phi ptr [ [[ADD_PTR150:%.*]], [[FOR_COND_CLEANUP137]] ], [ [[TMP15]], [[FOR_BODY114]] ]
; CHECK-NEXT:    [[ACC116_0929:%.*]] = phi float [ [[ACC116_1_LCSSA:%.*]], [[FOR_COND_CLEANUP137]] ], [ 0.000000e+00, [[FOR_BODY114]] ]
; CHECK-NEXT:    [[I_POS_X115_0928:%.*]] = phi i32 [ [[ADD151:%.*]], [[FOR_COND_CLEANUP137]] ], [ [[I_POS_Y_2934]], [[FOR_BODY114]] ]
; CHECK-NEXT:    [[TMP126:%.*]] = getelementptr float, ptr [[TMP2]], i32 [[I_POS_X115_0928]]
; CHECK-NEXT:    [[INC153]] = add nsw i32 [[M119_0931]], 1
; CHECK-NEXT:    br i1 [[CMP136923]], label [[FOR_BODY138_15:%.*]], label [[FOR_COND_PREHEADER26:%.*]]
; CHECK:       for.cond.cleanup124:
; CHECK-NEXT:    [[ACC116_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY114]] ], [ [[ACC116_1_LCSSA]], [[FOR_COND_CLEANUP137]] ]
; CHECK-NEXT:    [[ADD156]] = add nsw i32 [[I_POS_Y_2934]], [[TMP14]]
; CHECK-NEXT:    [[MUL158:%.*]] = mul nsw i32 [[X104_0935]], [[TMP13]]
; CHECK-NEXT:    [[GEP937:%.*]] = getelementptr float, ptr [[INVARIANT_GEP]], i32 [[MUL158]]
; CHECK-NEXT:    store float [[ACC116_0_LCSSA]], ptr [[GEP937]], align 4
; CHECK-NEXT:    [[EXITCOND1059_NOT:%.*]] = icmp eq i32 [[INC166]], [[TMP0]]
; CHECK-NEXT:    br i1 [[EXITCOND1059_NOT]], label [[FOR_COND_CLEANUP113]], label [[FOR_BODY114]]
; CHECK:       for.body138.15:
; CHECK-NEXT:    [[N126_0925:%.*]] = phi i32 [ [[INC148_15:%.*]], [[FOR_BODY138_15]] ], [ 0, [[FOR_COND127_PREHEADER]] ]
; CHECK-NEXT:    [[ACC116_1924:%.*]] = phi float [ [[TMP174:%.*]], [[FOR_BODY138_15]] ], [ [[ACC116_0929]], [[FOR_COND127_PREHEADER]] ]
; CHECK-NEXT:    [[MUL140:%.*]] = mul nsw i32 [[N126_0925]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX142:%.*]] = getelementptr float, ptr [[TMP126]], i32 [[MUL140]]
; CHECK-NEXT:    [[TMP127:%.*]] = load float, ptr [[ARRAYIDX142]], align 4
; CHECK-NEXT:    [[MUL144:%.*]] = mul nsw i32 [[N126_0925]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX145:%.*]] = getelementptr float, ptr [[F_DATA117_0930]], i32 [[MUL144]]
; CHECK-NEXT:    [[TMP128:%.*]] = load float, ptr [[ARRAYIDX145]], align 4
; CHECK-NEXT:    [[TMP129:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP127]], float [[TMP128]], float [[ACC116_1924]])
; CHECK-NEXT:    [[ARRAYIDX142_1:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP130:%.*]] = load float, ptr [[ARRAYIDX142_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_1:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP131:%.*]] = load float, ptr [[ARRAYIDX145_1]], align 4
; CHECK-NEXT:    [[TMP132:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP130]], float [[TMP131]], float [[TMP129]])
; CHECK-NEXT:    [[ARRAYIDX142_2:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL3413]]
; CHECK-NEXT:    [[TMP133:%.*]] = load float, ptr [[ARRAYIDX142_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_2:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL2810]]
; CHECK-NEXT:    [[TMP134:%.*]] = load float, ptr [[ARRAYIDX145_2]], align 4
; CHECK-NEXT:    [[TMP135:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP133]], float [[TMP134]], float [[TMP132]])
; CHECK-NEXT:    [[ARRAYIDX142_3:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL3514]]
; CHECK-NEXT:    [[TMP136:%.*]] = load float, ptr [[ARRAYIDX142_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_3:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL29]]
; CHECK-NEXT:    [[TMP137:%.*]] = load float, ptr [[ARRAYIDX145_3]], align 4
; CHECK-NEXT:    [[TMP138:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP136]], float [[TMP137]], float [[TMP135]])
; CHECK-NEXT:    [[ARRAYIDX142_4:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL3615]]
; CHECK-NEXT:    [[TMP139:%.*]] = load float, ptr [[ARRAYIDX142_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_4:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL3011]]
; CHECK-NEXT:    [[TMP140:%.*]] = load float, ptr [[ARRAYIDX145_4]], align 4
; CHECK-NEXT:    [[TMP141:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP139]], float [[TMP140]], float [[TMP138]])
; CHECK-NEXT:    [[ARRAYIDX142_5:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL3716]]
; CHECK-NEXT:    [[TMP142:%.*]] = load float, ptr [[ARRAYIDX142_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_5:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL31]]
; CHECK-NEXT:    [[TMP143:%.*]] = load float, ptr [[ARRAYIDX145_5]], align 4
; CHECK-NEXT:    [[TMP144:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP142]], float [[TMP143]], float [[TMP141]])
; CHECK-NEXT:    [[ARRAYIDX142_6:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL3817]]
; CHECK-NEXT:    [[TMP145:%.*]] = load float, ptr [[ARRAYIDX142_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_6:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP146:%.*]] = load float, ptr [[ARRAYIDX145_6]], align 4
; CHECK-NEXT:    [[TMP147:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP145]], float [[TMP146]], float [[TMP144]])
; CHECK-NEXT:    [[ARRAYIDX142_7:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL3918]]
; CHECK-NEXT:    [[TMP148:%.*]] = load float, ptr [[ARRAYIDX142_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_7:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP149:%.*]] = load float, ptr [[ARRAYIDX145_7]], align 4
; CHECK-NEXT:    [[TMP150:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP148]], float [[TMP149]], float [[TMP147]])
; CHECK-NEXT:    [[ARRAYIDX142_8:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL4019]]
; CHECK-NEXT:    [[TMP151:%.*]] = load float, ptr [[ARRAYIDX142_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_8:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL34]]
; CHECK-NEXT:    [[TMP152:%.*]] = load float, ptr [[ARRAYIDX145_8]], align 4
; CHECK-NEXT:    [[TMP153:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP151]], float [[TMP152]], float [[TMP150]])
; CHECK-NEXT:    [[ARRAYIDX142_9:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL4120]]
; CHECK-NEXT:    [[TMP154:%.*]] = load float, ptr [[ARRAYIDX142_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_9:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL35]]
; CHECK-NEXT:    [[TMP155:%.*]] = load float, ptr [[ARRAYIDX145_9]], align 4
; CHECK-NEXT:    [[TMP156:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP154]], float [[TMP155]], float [[TMP153]])
; CHECK-NEXT:    [[ARRAYIDX142_10:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL4221]]
; CHECK-NEXT:    [[TMP157:%.*]] = load float, ptr [[ARRAYIDX142_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_10:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL36]]
; CHECK-NEXT:    [[TMP158:%.*]] = load float, ptr [[ARRAYIDX145_10]], align 4
; CHECK-NEXT:    [[TMP159:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP157]], float [[TMP158]], float [[TMP156]])
; CHECK-NEXT:    [[ARRAYIDX142_11:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL43]]
; CHECK-NEXT:    [[TMP160:%.*]] = load float, ptr [[ARRAYIDX142_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_11:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL37]]
; CHECK-NEXT:    [[TMP161:%.*]] = load float, ptr [[ARRAYIDX145_11]], align 4
; CHECK-NEXT:    [[TMP162:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP160]], float [[TMP161]], float [[TMP159]])
; CHECK-NEXT:    [[ARRAYIDX142_12:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL4422]]
; CHECK-NEXT:    [[TMP163:%.*]] = load float, ptr [[ARRAYIDX142_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_12:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL38]]
; CHECK-NEXT:    [[TMP164:%.*]] = load float, ptr [[ARRAYIDX145_12]], align 4
; CHECK-NEXT:    [[TMP165:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP163]], float [[TMP164]], float [[TMP162]])
; CHECK-NEXT:    [[ARRAYIDX142_13:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL45]]
; CHECK-NEXT:    [[TMP166:%.*]] = load float, ptr [[ARRAYIDX142_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_13:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL39]]
; CHECK-NEXT:    [[TMP167:%.*]] = load float, ptr [[ARRAYIDX145_13]], align 4
; CHECK-NEXT:    [[TMP168:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP166]], float [[TMP167]], float [[TMP165]])
; CHECK-NEXT:    [[ARRAYIDX142_14:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL46]]
; CHECK-NEXT:    [[TMP169:%.*]] = load float, ptr [[ARRAYIDX142_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_14:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL4012]]
; CHECK-NEXT:    [[TMP170:%.*]] = load float, ptr [[ARRAYIDX145_14]], align 4
; CHECK-NEXT:    [[TMP171:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP169]], float [[TMP170]], float [[TMP168]])
; CHECK-NEXT:    [[ARRAYIDX142_15:%.*]] = getelementptr float, ptr [[ARRAYIDX142]], i32 [[MUL47]]
; CHECK-NEXT:    [[TMP172:%.*]] = load float, ptr [[ARRAYIDX142_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX145_15:%.*]] = getelementptr float, ptr [[ARRAYIDX145]], i32 [[MUL41]]
; CHECK-NEXT:    [[TMP173:%.*]] = load float, ptr [[ARRAYIDX145_15]], align 4
; CHECK-NEXT:    [[TMP174]] = tail call float @llvm.fmuladd.f32(float [[TMP172]], float [[TMP173]], float [[TMP171]])
; CHECK-NEXT:    [[INC148_15]] = add nuw nsw i32 [[N126_0925]], 16
; CHECK-NEXT:    [[CMP136_15:%.*]] = icmp slt i32 [[INC148_15]], [[SUB216]]
; CHECK-NEXT:    br i1 [[CMP136_15]], label [[FOR_BODY138_15]], label [[FOR_COND_PREHEADER26]]
; CHECK:       for.cond.preheader26:
; CHECK-NEXT:    [[TMP175:%.*]] = phi float [ [[ACC116_0929]], [[FOR_COND127_PREHEADER]] ], [ [[TMP174]], [[FOR_BODY138_15]] ]
; CHECK-NEXT:    [[TMP176:%.*]] = phi i32 [ 0, [[FOR_COND127_PREHEADER]] ], [ [[INC148_15]], [[FOR_BODY138_15]] ]
; CHECK-NEXT:    [[TMP177:%.*]] = icmp slt i32 [[TMP176]], [[SUB135]]
; CHECK-NEXT:    br i1 [[TMP177]], label [[FOR_BODY138_CLONE:%.*]], label [[FOR_COND_CLEANUP137]]
; CHECK:       for.body138.clone:
; CHECK-NEXT:    [[N126_0925_CLONE:%.*]] = phi i32 [ [[INC148_CLONE:%.*]], [[FOR_BODY138_CLONE]] ], [ [[TMP176]], [[FOR_COND_PREHEADER26]] ]
; CHECK-NEXT:    [[ACC116_1924_CLONE:%.*]] = phi float [ [[TMP180:%.*]], [[FOR_BODY138_CLONE]] ], [ [[TMP175]], [[FOR_COND_PREHEADER26]] ]
; CHECK-NEXT:    [[MUL140_CLONE:%.*]] = mul nsw i32 [[N126_0925_CLONE]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX142_CLONE:%.*]] = getelementptr float, ptr [[TMP126]], i32 [[MUL140_CLONE]]
; CHECK-NEXT:    [[TMP178:%.*]] = load float, ptr [[ARRAYIDX142_CLONE]], align 4
; CHECK-NEXT:    [[MUL144_CLONE:%.*]] = mul nsw i32 [[N126_0925_CLONE]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX145_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA117_0930]], i32 [[MUL144_CLONE]]
; CHECK-NEXT:    [[TMP179:%.*]] = load float, ptr [[ARRAYIDX145_CLONE]], align 4
; CHECK-NEXT:    [[TMP180]] = tail call float @llvm.fmuladd.f32(float [[TMP178]], float [[TMP179]], float [[ACC116_1924_CLONE]])
; CHECK-NEXT:    [[INC148_CLONE]] = add nuw nsw i32 [[N126_0925_CLONE]], 1
; CHECK-NEXT:    [[CMP136_CLONE:%.*]] = icmp eq i32 [[INC148_CLONE]], [[SUB135]]
; CHECK-NEXT:    br i1 [[CMP136_CLONE]], label [[FOR_COND_CLEANUP137]], label [[FOR_BODY138_CLONE]]
; CHECK:       for.cond.cleanup137:
; CHECK-NEXT:    [[ACC116_1_LCSSA]] = phi float [ [[TMP175]], [[FOR_COND_PREHEADER26]] ], [ [[TMP180]], [[FOR_BODY138_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR150]] = getelementptr inbounds float, ptr [[F_DATA117_0930]], i32 [[MUL10]]
; CHECK-NEXT:    [[ADD151]] = add nsw i32 [[I_POS_X115_0928]], [[MUL]]
; CHECK-NEXT:    [[CMP123:%.*]] = icmp slt i32 [[INC153]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP123]], label [[FOR_COND127_PREHEADER]], label [[FOR_COND_CLEANUP124]]
; CHECK:       for.cond186.preheader:
; CHECK-NEXT:    [[Y175_0975:%.*]] = phi i32 [ [[INC304:%.*]], [[FOR_COND_CLEANUP245:%.*]] ], [ [[SHR7]], [[FOR_COND176_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_1974:%.*]] = phi i32 [ [[ADD302:%.*]], [[FOR_COND_CLEANUP245]] ], [ 0, [[FOR_COND176_PREHEADER]] ]
; CHECK-NEXT:    [[MUL228:%.*]] = mul i32 [[TMP12]], [[TMP11]]
; CHECK-NEXT:    [[MUL230:%.*]] = mul i32 [[MUL228]], [[Y175_0975]]
; CHECK-NEXT:    [[INVARIANT_GEP955:%.*]] = getelementptr float, ptr [[TMP3]], i32 [[MUL230]]
; CHECK-NEXT:    [[INC304]] = add nsw i32 [[Y175_0975]], 1
; CHECK-NEXT:    br i1 [[CMP12901]], label [[FOR_BODY189:%.*]], label [[FOR_COND_CLEANUP188:%.*]]
; CHECK:       for.cond311.preheader:
; CHECK-NEXT:    br i1 [[CMP3131028]], label [[FOR_COND318_PREHEADER:%.*]], label [[FOR_COND513_PREHEADER:%.*]]
; CHECK:       for.cond.cleanup188:
; CHECK-NEXT:    [[I_POS_Y184_0_LCSSA:%.*]] = phi i32 [ [[I_POS_1974]], [[FOR_COND186_PREHEADER]] ], [ [[ADD224:%.*]], [[FOR_COND_CLEANUP198:%.*]] ]
; CHECK-NEXT:    br i1 [[CMP244967]], label [[FOR_BODY246:%.*]], label [[FOR_COND_CLEANUP245]]
; CHECK:       for.body189:
; CHECK-NEXT:    [[X185_0953:%.*]] = phi i32 [ [[INC234:%.*]], [[FOR_COND_CLEANUP198]] ], [ 0, [[FOR_COND186_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_Y184_0952:%.*]] = phi i32 [ [[ADD224]], [[FOR_COND_CLEANUP198]] ], [ [[I_POS_1974]], [[FOR_COND186_PREHEADER]] ]
; CHECK-NEXT:    [[SUB201:%.*]] = sub nsw i32 [[SHR]], [[X185_0953]]
; CHECK-NEXT:    [[CMP204941:%.*]] = icmp slt i32 [[SUB201]], [[SUB2223]]
; CHECK-NEXT:    [[INC234]] = add nuw nsw i32 [[X185_0953]], 1
; CHECK-NEXT:    br i1 [[CMP197945]], label [[FOR_BODY199:%.*]], label [[FOR_COND_CLEANUP198]]
; CHECK:       for.cond.cleanup198:
; CHECK-NEXT:    [[ACC191_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY189]] ], [ [[ACC191_1_LCSSA:%.*]], [[FOR_COND_CLEANUP205:%.*]] ]
; CHECK-NEXT:    [[ADD224]] = add nsw i32 [[I_POS_Y184_0952]], [[TMP14]]
; CHECK-NEXT:    [[MUL226:%.*]] = mul nsw i32 [[X185_0953]], [[TMP13]]
; CHECK-NEXT:    [[GEP956:%.*]] = getelementptr float, ptr [[INVARIANT_GEP955]], i32 [[MUL226]]
; CHECK-NEXT:    store float [[ACC191_0_LCSSA]], ptr [[GEP956]], align 4
; CHECK-NEXT:    [[EXITCOND1062_NOT:%.*]] = icmp eq i32 [[INC234]], [[SHR]]
; CHECK-NEXT:    br i1 [[EXITCOND1062_NOT]], label [[FOR_COND_CLEANUP188]], label [[FOR_BODY189]]
; CHECK:       for.body199:
; CHECK-NEXT:    [[M194_0949:%.*]] = phi i32 [ [[INC221:%.*]], [[FOR_COND_CLEANUP205]] ], [ 0, [[FOR_BODY189]] ]
; CHECK-NEXT:    [[F_DATA192_0948:%.*]] = phi ptr [ [[ADD_PTR218:%.*]], [[FOR_COND_CLEANUP205]] ], [ [[TMP15]], [[FOR_BODY189]] ]
; CHECK-NEXT:    [[ACC191_0947:%.*]] = phi float [ [[ACC191_1_LCSSA]], [[FOR_COND_CLEANUP205]] ], [ 0.000000e+00, [[FOR_BODY189]] ]
; CHECK-NEXT:    [[I_POS_X190_0946:%.*]] = phi i32 [ [[ADD219:%.*]], [[FOR_COND_CLEANUP205]] ], [ [[I_POS_Y184_0952]], [[FOR_BODY189]] ]
; CHECK-NEXT:    [[TMP181:%.*]] = getelementptr float, ptr [[TMP2]], i32 [[I_POS_X190_0946]]
; CHECK-NEXT:    [[INC221]] = add nuw nsw i32 [[M194_0949]], 1
; CHECK-NEXT:    br i1 [[CMP204941]], label [[FOR_BODY206_15:%.*]], label [[FOR_COND_PREHEADER27:%.*]]
; CHECK:       for.body206.15:
; CHECK-NEXT:    [[N200_0943:%.*]] = phi i32 [ [[INC216_15:%.*]], [[FOR_BODY206_15]] ], [ [[SUB201]], [[FOR_BODY199]] ]
; CHECK-NEXT:    [[ACC191_1942:%.*]] = phi float [ [[TMP229:%.*]], [[FOR_BODY206_15]] ], [ [[ACC191_0947]], [[FOR_BODY199]] ]
; CHECK-NEXT:    [[MUL208:%.*]] = mul nsw i32 [[N200_0943]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX210:%.*]] = getelementptr float, ptr [[TMP181]], i32 [[MUL208]]
; CHECK-NEXT:    [[TMP182:%.*]] = load float, ptr [[ARRAYIDX210]], align 4
; CHECK-NEXT:    [[MUL212:%.*]] = mul nsw i32 [[N200_0943]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX213:%.*]] = getelementptr float, ptr [[F_DATA192_0948]], i32 [[MUL212]]
; CHECK-NEXT:    [[TMP183:%.*]] = load float, ptr [[ARRAYIDX213]], align 4
; CHECK-NEXT:    [[TMP184:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP182]], float [[TMP183]], float [[ACC191_1942]])
; CHECK-NEXT:    [[ARRAYIDX210_1:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP185:%.*]] = load float, ptr [[ARRAYIDX210_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_1:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP186:%.*]] = load float, ptr [[ARRAYIDX213_1]], align 4
; CHECK-NEXT:    [[TMP187:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP185]], float [[TMP186]], float [[TMP184]])
; CHECK-NEXT:    [[ARRAYIDX210_2:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL3413]]
; CHECK-NEXT:    [[TMP188:%.*]] = load float, ptr [[ARRAYIDX210_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_2:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL2810]]
; CHECK-NEXT:    [[TMP189:%.*]] = load float, ptr [[ARRAYIDX213_2]], align 4
; CHECK-NEXT:    [[TMP190:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP188]], float [[TMP189]], float [[TMP187]])
; CHECK-NEXT:    [[ARRAYIDX210_3:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL3514]]
; CHECK-NEXT:    [[TMP191:%.*]] = load float, ptr [[ARRAYIDX210_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_3:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL29]]
; CHECK-NEXT:    [[TMP192:%.*]] = load float, ptr [[ARRAYIDX213_3]], align 4
; CHECK-NEXT:    [[TMP193:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP191]], float [[TMP192]], float [[TMP190]])
; CHECK-NEXT:    [[ARRAYIDX210_4:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL3615]]
; CHECK-NEXT:    [[TMP194:%.*]] = load float, ptr [[ARRAYIDX210_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_4:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL3011]]
; CHECK-NEXT:    [[TMP195:%.*]] = load float, ptr [[ARRAYIDX213_4]], align 4
; CHECK-NEXT:    [[TMP196:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP194]], float [[TMP195]], float [[TMP193]])
; CHECK-NEXT:    [[ARRAYIDX210_5:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL3716]]
; CHECK-NEXT:    [[TMP197:%.*]] = load float, ptr [[ARRAYIDX210_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_5:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL31]]
; CHECK-NEXT:    [[TMP198:%.*]] = load float, ptr [[ARRAYIDX213_5]], align 4
; CHECK-NEXT:    [[TMP199:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP197]], float [[TMP198]], float [[TMP196]])
; CHECK-NEXT:    [[ARRAYIDX210_6:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL3817]]
; CHECK-NEXT:    [[TMP200:%.*]] = load float, ptr [[ARRAYIDX210_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_6:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP201:%.*]] = load float, ptr [[ARRAYIDX213_6]], align 4
; CHECK-NEXT:    [[TMP202:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP200]], float [[TMP201]], float [[TMP199]])
; CHECK-NEXT:    [[ARRAYIDX210_7:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL3918]]
; CHECK-NEXT:    [[TMP203:%.*]] = load float, ptr [[ARRAYIDX210_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_7:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP204:%.*]] = load float, ptr [[ARRAYIDX213_7]], align 4
; CHECK-NEXT:    [[TMP205:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP203]], float [[TMP204]], float [[TMP202]])
; CHECK-NEXT:    [[ARRAYIDX210_8:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL4019]]
; CHECK-NEXT:    [[TMP206:%.*]] = load float, ptr [[ARRAYIDX210_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_8:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL34]]
; CHECK-NEXT:    [[TMP207:%.*]] = load float, ptr [[ARRAYIDX213_8]], align 4
; CHECK-NEXT:    [[TMP208:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP206]], float [[TMP207]], float [[TMP205]])
; CHECK-NEXT:    [[ARRAYIDX210_9:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL4120]]
; CHECK-NEXT:    [[TMP209:%.*]] = load float, ptr [[ARRAYIDX210_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_9:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL35]]
; CHECK-NEXT:    [[TMP210:%.*]] = load float, ptr [[ARRAYIDX213_9]], align 4
; CHECK-NEXT:    [[TMP211:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP209]], float [[TMP210]], float [[TMP208]])
; CHECK-NEXT:    [[ARRAYIDX210_10:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL4221]]
; CHECK-NEXT:    [[TMP212:%.*]] = load float, ptr [[ARRAYIDX210_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_10:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL36]]
; CHECK-NEXT:    [[TMP213:%.*]] = load float, ptr [[ARRAYIDX213_10]], align 4
; CHECK-NEXT:    [[TMP214:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP212]], float [[TMP213]], float [[TMP211]])
; CHECK-NEXT:    [[ARRAYIDX210_11:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL43]]
; CHECK-NEXT:    [[TMP215:%.*]] = load float, ptr [[ARRAYIDX210_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_11:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL37]]
; CHECK-NEXT:    [[TMP216:%.*]] = load float, ptr [[ARRAYIDX213_11]], align 4
; CHECK-NEXT:    [[TMP217:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP215]], float [[TMP216]], float [[TMP214]])
; CHECK-NEXT:    [[ARRAYIDX210_12:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL4422]]
; CHECK-NEXT:    [[TMP218:%.*]] = load float, ptr [[ARRAYIDX210_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_12:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL38]]
; CHECK-NEXT:    [[TMP219:%.*]] = load float, ptr [[ARRAYIDX213_12]], align 4
; CHECK-NEXT:    [[TMP220:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP218]], float [[TMP219]], float [[TMP217]])
; CHECK-NEXT:    [[ARRAYIDX210_13:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL45]]
; CHECK-NEXT:    [[TMP221:%.*]] = load float, ptr [[ARRAYIDX210_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_13:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL39]]
; CHECK-NEXT:    [[TMP222:%.*]] = load float, ptr [[ARRAYIDX213_13]], align 4
; CHECK-NEXT:    [[TMP223:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP221]], float [[TMP222]], float [[TMP220]])
; CHECK-NEXT:    [[ARRAYIDX210_14:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL46]]
; CHECK-NEXT:    [[TMP224:%.*]] = load float, ptr [[ARRAYIDX210_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_14:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL4012]]
; CHECK-NEXT:    [[TMP225:%.*]] = load float, ptr [[ARRAYIDX213_14]], align 4
; CHECK-NEXT:    [[TMP226:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP224]], float [[TMP225]], float [[TMP223]])
; CHECK-NEXT:    [[ARRAYIDX210_15:%.*]] = getelementptr float, ptr [[ARRAYIDX210]], i32 [[MUL47]]
; CHECK-NEXT:    [[TMP227:%.*]] = load float, ptr [[ARRAYIDX210_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX213_15:%.*]] = getelementptr float, ptr [[ARRAYIDX213]], i32 [[MUL41]]
; CHECK-NEXT:    [[TMP228:%.*]] = load float, ptr [[ARRAYIDX213_15]], align 4
; CHECK-NEXT:    [[TMP229]] = tail call float @llvm.fmuladd.f32(float [[TMP227]], float [[TMP228]], float [[TMP226]])
; CHECK-NEXT:    [[INC216_15]] = add nsw i32 [[N200_0943]], 16
; CHECK-NEXT:    [[CMP204_15:%.*]] = icmp slt i32 [[INC216_15]], [[SUB2223]]
; CHECK-NEXT:    br i1 [[CMP204_15]], label [[FOR_BODY206_15]], label [[FOR_COND_PREHEADER27]]
; CHECK:       for.cond.preheader27:
; CHECK-NEXT:    [[TMP230:%.*]] = phi float [ [[ACC191_0947]], [[FOR_BODY199]] ], [ [[TMP229]], [[FOR_BODY206_15]] ]
; CHECK-NEXT:    [[TMP231:%.*]] = phi i32 [ [[SUB201]], [[FOR_BODY199]] ], [ [[INC216_15]], [[FOR_BODY206_15]] ]
; CHECK-NEXT:    [[TMP232:%.*]] = icmp slt i32 [[TMP231]], [[TMP4]]
; CHECK-NEXT:    br i1 [[TMP232]], label [[FOR_BODY206_CLONE:%.*]], label [[FOR_COND_CLEANUP205]]
; CHECK:       for.body206.clone:
; CHECK-NEXT:    [[N200_0943_CLONE:%.*]] = phi i32 [ [[INC216_CLONE:%.*]], [[FOR_BODY206_CLONE]] ], [ [[TMP231]], [[FOR_COND_PREHEADER27]] ]
; CHECK-NEXT:    [[ACC191_1942_CLONE:%.*]] = phi float [ [[TMP235:%.*]], [[FOR_BODY206_CLONE]] ], [ [[TMP230]], [[FOR_COND_PREHEADER27]] ]
; CHECK-NEXT:    [[MUL208_CLONE:%.*]] = mul nsw i32 [[N200_0943_CLONE]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX210_CLONE:%.*]] = getelementptr float, ptr [[TMP181]], i32 [[MUL208_CLONE]]
; CHECK-NEXT:    [[TMP233:%.*]] = load float, ptr [[ARRAYIDX210_CLONE]], align 4
; CHECK-NEXT:    [[MUL212_CLONE:%.*]] = mul nsw i32 [[N200_0943_CLONE]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX213_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA192_0948]], i32 [[MUL212_CLONE]]
; CHECK-NEXT:    [[TMP234:%.*]] = load float, ptr [[ARRAYIDX213_CLONE]], align 4
; CHECK-NEXT:    [[TMP235]] = tail call float @llvm.fmuladd.f32(float [[TMP233]], float [[TMP234]], float [[ACC191_1942_CLONE]])
; CHECK-NEXT:    [[INC216_CLONE]] = add nsw i32 [[N200_0943_CLONE]], 1
; CHECK-NEXT:    [[CMP204_CLONE:%.*]] = icmp eq i32 [[INC216_CLONE]], [[TMP4]]
; CHECK-NEXT:    br i1 [[CMP204_CLONE]], label [[FOR_COND_CLEANUP205]], label [[FOR_BODY206_CLONE]]
; CHECK:       for.cond.cleanup205:
; CHECK-NEXT:    [[ACC191_1_LCSSA]] = phi float [ [[TMP230]], [[FOR_COND_PREHEADER27]] ], [ [[TMP235]], [[FOR_BODY206_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR218]] = getelementptr inbounds float, ptr [[F_DATA192_0948]], i32 [[MUL10]]
; CHECK-NEXT:    [[ADD219]] = add nsw i32 [[I_POS_X190_0946]], [[MUL]]
; CHECK-NEXT:    [[EXITCOND1061_NOT:%.*]] = icmp eq i32 [[INC221]], [[TMP5]]
; CHECK-NEXT:    br i1 [[EXITCOND1061_NOT]], label [[FOR_COND_CLEANUP198]], label [[FOR_BODY199]]
; CHECK:       for.cond.cleanup245:
; CHECK-NEXT:    [[ADD302]] = add nsw i32 [[I_POS_1974]], [[MUL]]
; CHECK-NEXT:    [[EXITCOND1065_NOT:%.*]] = icmp eq i32 [[INC304]], [[SUB180]]
; CHECK-NEXT:    br i1 [[EXITCOND1065_NOT]], label [[FOR_COND311_PREHEADER]], label [[FOR_COND186_PREHEADER]]
; CHECK:       for.body246:
; CHECK-NEXT:    [[X236_0969:%.*]] = phi i32 [ [[INC297:%.*]], [[FOR_COND_CLEANUP255:%.*]] ], [ [[SUB241]], [[FOR_COND_CLEANUP188]] ]
; CHECK-NEXT:    [[I_POS_Y184_1968:%.*]] = phi i32 [ [[ADD287:%.*]], [[FOR_COND_CLEANUP255]] ], [ [[I_POS_Y184_0_LCSSA]], [[FOR_COND_CLEANUP188]] ]
; CHECK-NEXT:    [[ADD264:%.*]] = add i32 [[X236_0969]], [[SUB467]]
; CHECK-NEXT:    [[ADD265_NEG:%.*]] = xor i32 [[ADD264]], -1
; CHECK-NEXT:    [[SUB266:%.*]] = add i32 [[ADD265_NEG]], [[TMP4]]
; CHECK-NEXT:    [[CMP267957:%.*]] = icmp sgt i32 [[SUB266]], 15
; CHECK-NEXT:    [[SUB21630:%.*]] = add nsw i32 [[SUB266]], -15
; CHECK-NEXT:    [[INC297]] = add nsw i32 [[X236_0969]], 1
; CHECK-NEXT:    br i1 [[CMP197945]], label [[FOR_COND258_PREHEADER:%.*]], label [[FOR_COND_CLEANUP255]]
; CHECK:       for.cond258.preheader:
; CHECK-NEXT:    [[M251_0965:%.*]] = phi i32 [ [[INC284:%.*]], [[FOR_COND_CLEANUP268:%.*]] ], [ 0, [[FOR_BODY246]] ]
; CHECK-NEXT:    [[F_DATA249_0964:%.*]] = phi ptr [ [[ADD_PTR281:%.*]], [[FOR_COND_CLEANUP268]] ], [ [[TMP15]], [[FOR_BODY246]] ]
; CHECK-NEXT:    [[ACC248_0963:%.*]] = phi float [ [[ACC248_1_LCSSA:%.*]], [[FOR_COND_CLEANUP268]] ], [ 0.000000e+00, [[FOR_BODY246]] ]
; CHECK-NEXT:    [[I_POS_X247_0962:%.*]] = phi i32 [ [[ADD282:%.*]], [[FOR_COND_CLEANUP268]] ], [ [[I_POS_Y184_1968]], [[FOR_BODY246]] ]
; CHECK-NEXT:    [[TMP236:%.*]] = getelementptr float, ptr [[TMP2]], i32 [[I_POS_X247_0962]]
; CHECK-NEXT:    [[INC284]] = add nuw nsw i32 [[M251_0965]], 1
; CHECK-NEXT:    br i1 [[CMP267957]], label [[FOR_BODY269_15:%.*]], label [[FOR_COND_PREHEADER29:%.*]]
; CHECK:       for.cond.cleanup255:
; CHECK-NEXT:    [[ACC248_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY246]] ], [ [[ACC248_1_LCSSA]], [[FOR_COND_CLEANUP268]] ]
; CHECK-NEXT:    [[ADD287]] = add nsw i32 [[I_POS_Y184_1968]], [[TMP14]]
; CHECK-NEXT:    [[MUL289:%.*]] = mul nsw i32 [[X236_0969]], [[TMP13]]
; CHECK-NEXT:    [[GEP971:%.*]] = getelementptr float, ptr [[INVARIANT_GEP955]], i32 [[MUL289]]
; CHECK-NEXT:    store float [[ACC248_0_LCSSA]], ptr [[GEP971]], align 4
; CHECK-NEXT:    [[EXITCOND1064_NOT:%.*]] = icmp eq i32 [[INC297]], [[TMP0]]
; CHECK-NEXT:    br i1 [[EXITCOND1064_NOT]], label [[FOR_COND_CLEANUP245]], label [[FOR_BODY246]]
; CHECK:       for.body269.15:
; CHECK-NEXT:    [[N257_0959:%.*]] = phi i32 [ [[INC279_15:%.*]], [[FOR_BODY269_15]] ], [ 0, [[FOR_COND258_PREHEADER]] ]
; CHECK-NEXT:    [[ACC248_1958:%.*]] = phi float [ [[TMP284:%.*]], [[FOR_BODY269_15]] ], [ [[ACC248_0963]], [[FOR_COND258_PREHEADER]] ]
; CHECK-NEXT:    [[MUL271:%.*]] = mul nsw i32 [[N257_0959]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX273:%.*]] = getelementptr float, ptr [[TMP236]], i32 [[MUL271]]
; CHECK-NEXT:    [[TMP237:%.*]] = load float, ptr [[ARRAYIDX273]], align 4
; CHECK-NEXT:    [[MUL275:%.*]] = mul nsw i32 [[N257_0959]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX276:%.*]] = getelementptr float, ptr [[F_DATA249_0964]], i32 [[MUL275]]
; CHECK-NEXT:    [[TMP238:%.*]] = load float, ptr [[ARRAYIDX276]], align 4
; CHECK-NEXT:    [[TMP239:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP237]], float [[TMP238]], float [[ACC248_1958]])
; CHECK-NEXT:    [[ARRAYIDX273_1:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP240:%.*]] = load float, ptr [[ARRAYIDX273_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_1:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP241:%.*]] = load float, ptr [[ARRAYIDX276_1]], align 4
; CHECK-NEXT:    [[TMP242:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP240]], float [[TMP241]], float [[TMP239]])
; CHECK-NEXT:    [[ARRAYIDX273_2:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL3413]]
; CHECK-NEXT:    [[TMP243:%.*]] = load float, ptr [[ARRAYIDX273_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_2:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL2810]]
; CHECK-NEXT:    [[TMP244:%.*]] = load float, ptr [[ARRAYIDX276_2]], align 4
; CHECK-NEXT:    [[TMP245:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP243]], float [[TMP244]], float [[TMP242]])
; CHECK-NEXT:    [[ARRAYIDX273_3:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL3514]]
; CHECK-NEXT:    [[TMP246:%.*]] = load float, ptr [[ARRAYIDX273_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_3:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL29]]
; CHECK-NEXT:    [[TMP247:%.*]] = load float, ptr [[ARRAYIDX276_3]], align 4
; CHECK-NEXT:    [[TMP248:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP246]], float [[TMP247]], float [[TMP245]])
; CHECK-NEXT:    [[ARRAYIDX273_4:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL3615]]
; CHECK-NEXT:    [[TMP249:%.*]] = load float, ptr [[ARRAYIDX273_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_4:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL3011]]
; CHECK-NEXT:    [[TMP250:%.*]] = load float, ptr [[ARRAYIDX276_4]], align 4
; CHECK-NEXT:    [[TMP251:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP249]], float [[TMP250]], float [[TMP248]])
; CHECK-NEXT:    [[ARRAYIDX273_5:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL3716]]
; CHECK-NEXT:    [[TMP252:%.*]] = load float, ptr [[ARRAYIDX273_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_5:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL31]]
; CHECK-NEXT:    [[TMP253:%.*]] = load float, ptr [[ARRAYIDX276_5]], align 4
; CHECK-NEXT:    [[TMP254:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP252]], float [[TMP253]], float [[TMP251]])
; CHECK-NEXT:    [[ARRAYIDX273_6:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL3817]]
; CHECK-NEXT:    [[TMP255:%.*]] = load float, ptr [[ARRAYIDX273_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_6:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP256:%.*]] = load float, ptr [[ARRAYIDX276_6]], align 4
; CHECK-NEXT:    [[TMP257:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP255]], float [[TMP256]], float [[TMP254]])
; CHECK-NEXT:    [[ARRAYIDX273_7:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL3918]]
; CHECK-NEXT:    [[TMP258:%.*]] = load float, ptr [[ARRAYIDX273_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_7:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP259:%.*]] = load float, ptr [[ARRAYIDX276_7]], align 4
; CHECK-NEXT:    [[TMP260:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP258]], float [[TMP259]], float [[TMP257]])
; CHECK-NEXT:    [[ARRAYIDX273_8:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL4019]]
; CHECK-NEXT:    [[TMP261:%.*]] = load float, ptr [[ARRAYIDX273_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_8:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL34]]
; CHECK-NEXT:    [[TMP262:%.*]] = load float, ptr [[ARRAYIDX276_8]], align 4
; CHECK-NEXT:    [[TMP263:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP261]], float [[TMP262]], float [[TMP260]])
; CHECK-NEXT:    [[ARRAYIDX273_9:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL4120]]
; CHECK-NEXT:    [[TMP264:%.*]] = load float, ptr [[ARRAYIDX273_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_9:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL35]]
; CHECK-NEXT:    [[TMP265:%.*]] = load float, ptr [[ARRAYIDX276_9]], align 4
; CHECK-NEXT:    [[TMP266:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP264]], float [[TMP265]], float [[TMP263]])
; CHECK-NEXT:    [[ARRAYIDX273_10:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL4221]]
; CHECK-NEXT:    [[TMP267:%.*]] = load float, ptr [[ARRAYIDX273_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_10:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL36]]
; CHECK-NEXT:    [[TMP268:%.*]] = load float, ptr [[ARRAYIDX276_10]], align 4
; CHECK-NEXT:    [[TMP269:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP267]], float [[TMP268]], float [[TMP266]])
; CHECK-NEXT:    [[ARRAYIDX273_11:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL43]]
; CHECK-NEXT:    [[TMP270:%.*]] = load float, ptr [[ARRAYIDX273_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_11:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL37]]
; CHECK-NEXT:    [[TMP271:%.*]] = load float, ptr [[ARRAYIDX276_11]], align 4
; CHECK-NEXT:    [[TMP272:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP270]], float [[TMP271]], float [[TMP269]])
; CHECK-NEXT:    [[ARRAYIDX273_12:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL4422]]
; CHECK-NEXT:    [[TMP273:%.*]] = load float, ptr [[ARRAYIDX273_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_12:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL38]]
; CHECK-NEXT:    [[TMP274:%.*]] = load float, ptr [[ARRAYIDX276_12]], align 4
; CHECK-NEXT:    [[TMP275:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP273]], float [[TMP274]], float [[TMP272]])
; CHECK-NEXT:    [[ARRAYIDX273_13:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL45]]
; CHECK-NEXT:    [[TMP276:%.*]] = load float, ptr [[ARRAYIDX273_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_13:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL39]]
; CHECK-NEXT:    [[TMP277:%.*]] = load float, ptr [[ARRAYIDX276_13]], align 4
; CHECK-NEXT:    [[TMP278:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP276]], float [[TMP277]], float [[TMP275]])
; CHECK-NEXT:    [[ARRAYIDX273_14:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL46]]
; CHECK-NEXT:    [[TMP279:%.*]] = load float, ptr [[ARRAYIDX273_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_14:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL4012]]
; CHECK-NEXT:    [[TMP280:%.*]] = load float, ptr [[ARRAYIDX276_14]], align 4
; CHECK-NEXT:    [[TMP281:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP279]], float [[TMP280]], float [[TMP278]])
; CHECK-NEXT:    [[ARRAYIDX273_15:%.*]] = getelementptr float, ptr [[ARRAYIDX273]], i32 [[MUL47]]
; CHECK-NEXT:    [[TMP282:%.*]] = load float, ptr [[ARRAYIDX273_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX276_15:%.*]] = getelementptr float, ptr [[ARRAYIDX276]], i32 [[MUL41]]
; CHECK-NEXT:    [[TMP283:%.*]] = load float, ptr [[ARRAYIDX276_15]], align 4
; CHECK-NEXT:    [[TMP284]] = tail call float @llvm.fmuladd.f32(float [[TMP282]], float [[TMP283]], float [[TMP281]])
; CHECK-NEXT:    [[INC279_15]] = add nuw nsw i32 [[N257_0959]], 16
; CHECK-NEXT:    [[CMP267_15:%.*]] = icmp slt i32 [[INC279_15]], [[SUB21630]]
; CHECK-NEXT:    br i1 [[CMP267_15]], label [[FOR_BODY269_15]], label [[FOR_COND_PREHEADER29]]
; CHECK:       for.cond.preheader29:
; CHECK-NEXT:    [[TMP285:%.*]] = phi float [ [[ACC248_0963]], [[FOR_COND258_PREHEADER]] ], [ [[TMP284]], [[FOR_BODY269_15]] ]
; CHECK-NEXT:    [[TMP286:%.*]] = phi i32 [ 0, [[FOR_COND258_PREHEADER]] ], [ [[INC279_15]], [[FOR_BODY269_15]] ]
; CHECK-NEXT:    [[TMP287:%.*]] = icmp slt i32 [[TMP286]], [[SUB266]]
; CHECK-NEXT:    br i1 [[TMP287]], label [[FOR_BODY269_CLONE:%.*]], label [[FOR_COND_CLEANUP268]]
; CHECK:       for.body269.clone:
; CHECK-NEXT:    [[N257_0959_CLONE:%.*]] = phi i32 [ [[INC279_CLONE:%.*]], [[FOR_BODY269_CLONE]] ], [ [[TMP286]], [[FOR_COND_PREHEADER29]] ]
; CHECK-NEXT:    [[ACC248_1958_CLONE:%.*]] = phi float [ [[TMP290:%.*]], [[FOR_BODY269_CLONE]] ], [ [[TMP285]], [[FOR_COND_PREHEADER29]] ]
; CHECK-NEXT:    [[MUL271_CLONE:%.*]] = mul nsw i32 [[N257_0959_CLONE]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX273_CLONE:%.*]] = getelementptr float, ptr [[TMP236]], i32 [[MUL271_CLONE]]
; CHECK-NEXT:    [[TMP288:%.*]] = load float, ptr [[ARRAYIDX273_CLONE]], align 4
; CHECK-NEXT:    [[MUL275_CLONE:%.*]] = mul nsw i32 [[N257_0959_CLONE]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX276_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA249_0964]], i32 [[MUL275_CLONE]]
; CHECK-NEXT:    [[TMP289:%.*]] = load float, ptr [[ARRAYIDX276_CLONE]], align 4
; CHECK-NEXT:    [[TMP290]] = tail call float @llvm.fmuladd.f32(float [[TMP288]], float [[TMP289]], float [[ACC248_1958_CLONE]])
; CHECK-NEXT:    [[INC279_CLONE]] = add nuw nsw i32 [[N257_0959_CLONE]], 1
; CHECK-NEXT:    [[CMP267_CLONE:%.*]] = icmp eq i32 [[INC279_CLONE]], [[SUB266]]
; CHECK-NEXT:    br i1 [[CMP267_CLONE]], label [[FOR_COND_CLEANUP268]], label [[FOR_BODY269_CLONE]]
; CHECK:       for.cond.cleanup268:
; CHECK-NEXT:    [[ACC248_1_LCSSA]] = phi float [ [[TMP285]], [[FOR_COND_PREHEADER29]] ], [ [[TMP290]], [[FOR_BODY269_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR281]] = getelementptr inbounds float, ptr [[F_DATA249_0964]], i32 [[MUL10]]
; CHECK-NEXT:    [[ADD282]] = add nsw i32 [[I_POS_X247_0962]], [[MUL]]
; CHECK-NEXT:    [[EXITCOND1063_NOT:%.*]] = icmp eq i32 [[INC284]], [[TMP5]]
; CHECK-NEXT:    br i1 [[EXITCOND1063_NOT]], label [[FOR_COND_CLEANUP255]], label [[FOR_COND258_PREHEADER]]
; CHECK:       for.cond318.preheader:
; CHECK-NEXT:    [[Y306_01030:%.*]] = phi i32 [ [[INC510:%.*]], [[FOR_COND_CLEANUP444:%.*]] ], [ [[SUB180]], [[FOR_COND311_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_21029:%.*]] = phi i32 [ [[ADD508:%.*]], [[FOR_COND_CLEANUP444]] ], [ 0, [[FOR_COND311_PREHEADER]] ]
; CHECK-NEXT:    [[ADD333:%.*]] = add i32 [[SUB330]], [[Y306_01030]]
; CHECK-NEXT:    [[ADD334_NEG:%.*]] = xor i32 [[ADD333]], -1
; CHECK-NEXT:    [[MUL367:%.*]] = mul i32 [[TMP12]], [[TMP11]]
; CHECK-NEXT:    [[MUL369:%.*]] = mul i32 [[MUL367]], [[Y306_01030]]
; CHECK-NEXT:    [[SUB335:%.*]] = add i32 [[ADD334_NEG]], [[TMP5]]
; CHECK-NEXT:    [[INVARIANT_GEP993:%.*]] = getelementptr float, ptr [[TMP3]], i32 [[MUL369]]
; CHECK-NEXT:    [[CMP336983:%.*]] = icmp sgt i32 [[SUB335]], 0
; CHECK-NEXT:    [[INC510]] = add nsw i32 [[Y306_01030]], 1
; CHECK-NEXT:    br i1 [[CMP12901]], label [[FOR_BODY321:%.*]], label [[FOR_COND376_PREHEADER:%.*]]
; CHECK:       for.cond513.preheader:
; CHECK-NEXT:    br i1 [[CMP181973]], label [[FOR_COND523_PREHEADER:%.*]], label [[FOR_COND_CLEANUP519:%.*]]
; CHECK:       for.cond376.preheader:
; CHECK-NEXT:    [[I_POS_Y316_0_LCSSA:%.*]] = phi i32 [ [[I_POS_21029]], [[FOR_COND318_PREHEADER]] ], [ [[ADD363:%.*]], [[FOR_COND_CLEANUP337:%.*]] ]
; CHECK-NEXT:    br i1 [[CMP55915]], label [[FOR_BODY383:%.*]], label [[FOR_COND441_PREHEADER:%.*]]
; CHECK:       for.body321:
; CHECK-NEXT:    [[X317_0991:%.*]] = phi i32 [ [[INC373:%.*]], [[FOR_COND_CLEANUP337]] ], [ 0, [[FOR_COND318_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_Y316_0990:%.*]] = phi i32 [ [[ADD363]], [[FOR_COND_CLEANUP337]] ], [ [[I_POS_21029]], [[FOR_COND318_PREHEADER]] ]
; CHECK-NEXT:    [[SUB340:%.*]] = sub nsw i32 [[SHR]], [[X317_0991]]
; CHECK-NEXT:    [[CMP343979:%.*]] = icmp slt i32 [[SUB340]], [[SUB2223]]
; CHECK-NEXT:    [[INC373]] = add nuw nsw i32 [[X317_0991]], 1
; CHECK-NEXT:    br i1 [[CMP336983]], label [[FOR_BODY338:%.*]], label [[FOR_COND_CLEANUP337]]
; CHECK:       for.cond.cleanup337:
; CHECK-NEXT:    [[ACC323_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY321]] ], [ [[ACC323_1_LCSSA:%.*]], [[FOR_COND_CLEANUP344:%.*]] ]
; CHECK-NEXT:    [[ADD363]] = add nsw i32 [[I_POS_Y316_0990]], [[TMP14]]
; CHECK-NEXT:    [[MUL365:%.*]] = mul nsw i32 [[X317_0991]], [[TMP13]]
; CHECK-NEXT:    [[GEP994:%.*]] = getelementptr float, ptr [[INVARIANT_GEP993]], i32 [[MUL365]]
; CHECK-NEXT:    store float [[ACC323_0_LCSSA]], ptr [[GEP994]], align 4
; CHECK-NEXT:    [[EXITCOND1066_NOT:%.*]] = icmp eq i32 [[INC373]], [[SHR]]
; CHECK-NEXT:    br i1 [[EXITCOND1066_NOT]], label [[FOR_COND376_PREHEADER]], label [[FOR_BODY321]]
; CHECK:       for.body338:
; CHECK-NEXT:    [[M326_0987:%.*]] = phi i32 [ [[INC360:%.*]], [[FOR_COND_CLEANUP344]] ], [ 0, [[FOR_BODY321]] ]
; CHECK-NEXT:    [[F_DATA324_0986:%.*]] = phi ptr [ [[ADD_PTR357:%.*]], [[FOR_COND_CLEANUP344]] ], [ [[TMP15]], [[FOR_BODY321]] ]
; CHECK-NEXT:    [[ACC323_0985:%.*]] = phi float [ [[ACC323_1_LCSSA]], [[FOR_COND_CLEANUP344]] ], [ 0.000000e+00, [[FOR_BODY321]] ]
; CHECK-NEXT:    [[I_POS_X322_0984:%.*]] = phi i32 [ [[ADD358:%.*]], [[FOR_COND_CLEANUP344]] ], [ [[I_POS_Y316_0990]], [[FOR_BODY321]] ]
; CHECK-NEXT:    [[TMP291:%.*]] = getelementptr float, ptr [[TMP2]], i32 [[I_POS_X322_0984]]
; CHECK-NEXT:    [[INC360]] = add nuw nsw i32 [[M326_0987]], 1
; CHECK-NEXT:    br i1 [[CMP343979]], label [[FOR_BODY345_15:%.*]], label [[FOR_COND_PREHEADER31:%.*]]
; CHECK:       for.body345.15:
; CHECK-NEXT:    [[N339_0981:%.*]] = phi i32 [ [[INC355_15:%.*]], [[FOR_BODY345_15]] ], [ [[SUB340]], [[FOR_BODY338]] ]
; CHECK-NEXT:    [[ACC323_1980:%.*]] = phi float [ [[TMP339:%.*]], [[FOR_BODY345_15]] ], [ [[ACC323_0985]], [[FOR_BODY338]] ]
; CHECK-NEXT:    [[MUL347:%.*]] = mul nsw i32 [[N339_0981]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX349:%.*]] = getelementptr float, ptr [[TMP291]], i32 [[MUL347]]
; CHECK-NEXT:    [[TMP292:%.*]] = load float, ptr [[ARRAYIDX349]], align 4
; CHECK-NEXT:    [[MUL351:%.*]] = mul nsw i32 [[N339_0981]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX352:%.*]] = getelementptr float, ptr [[F_DATA324_0986]], i32 [[MUL351]]
; CHECK-NEXT:    [[TMP293:%.*]] = load float, ptr [[ARRAYIDX352]], align 4
; CHECK-NEXT:    [[TMP294:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP292]], float [[TMP293]], float [[ACC323_1980]])
; CHECK-NEXT:    [[ARRAYIDX349_1:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP295:%.*]] = load float, ptr [[ARRAYIDX349_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_1:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP296:%.*]] = load float, ptr [[ARRAYIDX352_1]], align 4
; CHECK-NEXT:    [[TMP297:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP295]], float [[TMP296]], float [[TMP294]])
; CHECK-NEXT:    [[ARRAYIDX349_2:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL3413]]
; CHECK-NEXT:    [[TMP298:%.*]] = load float, ptr [[ARRAYIDX349_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_2:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL2810]]
; CHECK-NEXT:    [[TMP299:%.*]] = load float, ptr [[ARRAYIDX352_2]], align 4
; CHECK-NEXT:    [[TMP300:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP298]], float [[TMP299]], float [[TMP297]])
; CHECK-NEXT:    [[ARRAYIDX349_3:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL3514]]
; CHECK-NEXT:    [[TMP301:%.*]] = load float, ptr [[ARRAYIDX349_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_3:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL29]]
; CHECK-NEXT:    [[TMP302:%.*]] = load float, ptr [[ARRAYIDX352_3]], align 4
; CHECK-NEXT:    [[TMP303:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP301]], float [[TMP302]], float [[TMP300]])
; CHECK-NEXT:    [[ARRAYIDX349_4:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL3615]]
; CHECK-NEXT:    [[TMP304:%.*]] = load float, ptr [[ARRAYIDX349_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_4:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL3011]]
; CHECK-NEXT:    [[TMP305:%.*]] = load float, ptr [[ARRAYIDX352_4]], align 4
; CHECK-NEXT:    [[TMP306:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP304]], float [[TMP305]], float [[TMP303]])
; CHECK-NEXT:    [[ARRAYIDX349_5:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL3716]]
; CHECK-NEXT:    [[TMP307:%.*]] = load float, ptr [[ARRAYIDX349_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_5:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL31]]
; CHECK-NEXT:    [[TMP308:%.*]] = load float, ptr [[ARRAYIDX352_5]], align 4
; CHECK-NEXT:    [[TMP309:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP307]], float [[TMP308]], float [[TMP306]])
; CHECK-NEXT:    [[ARRAYIDX349_6:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL3817]]
; CHECK-NEXT:    [[TMP310:%.*]] = load float, ptr [[ARRAYIDX349_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_6:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP311:%.*]] = load float, ptr [[ARRAYIDX352_6]], align 4
; CHECK-NEXT:    [[TMP312:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP310]], float [[TMP311]], float [[TMP309]])
; CHECK-NEXT:    [[ARRAYIDX349_7:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL3918]]
; CHECK-NEXT:    [[TMP313:%.*]] = load float, ptr [[ARRAYIDX349_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_7:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP314:%.*]] = load float, ptr [[ARRAYIDX352_7]], align 4
; CHECK-NEXT:    [[TMP315:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP313]], float [[TMP314]], float [[TMP312]])
; CHECK-NEXT:    [[ARRAYIDX349_8:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL4019]]
; CHECK-NEXT:    [[TMP316:%.*]] = load float, ptr [[ARRAYIDX349_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_8:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL34]]
; CHECK-NEXT:    [[TMP317:%.*]] = load float, ptr [[ARRAYIDX352_8]], align 4
; CHECK-NEXT:    [[TMP318:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP316]], float [[TMP317]], float [[TMP315]])
; CHECK-NEXT:    [[ARRAYIDX349_9:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL4120]]
; CHECK-NEXT:    [[TMP319:%.*]] = load float, ptr [[ARRAYIDX349_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_9:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL35]]
; CHECK-NEXT:    [[TMP320:%.*]] = load float, ptr [[ARRAYIDX352_9]], align 4
; CHECK-NEXT:    [[TMP321:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP319]], float [[TMP320]], float [[TMP318]])
; CHECK-NEXT:    [[ARRAYIDX349_10:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL4221]]
; CHECK-NEXT:    [[TMP322:%.*]] = load float, ptr [[ARRAYIDX349_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_10:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL36]]
; CHECK-NEXT:    [[TMP323:%.*]] = load float, ptr [[ARRAYIDX352_10]], align 4
; CHECK-NEXT:    [[TMP324:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP322]], float [[TMP323]], float [[TMP321]])
; CHECK-NEXT:    [[ARRAYIDX349_11:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL43]]
; CHECK-NEXT:    [[TMP325:%.*]] = load float, ptr [[ARRAYIDX349_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_11:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL37]]
; CHECK-NEXT:    [[TMP326:%.*]] = load float, ptr [[ARRAYIDX352_11]], align 4
; CHECK-NEXT:    [[TMP327:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP325]], float [[TMP326]], float [[TMP324]])
; CHECK-NEXT:    [[ARRAYIDX349_12:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL4422]]
; CHECK-NEXT:    [[TMP328:%.*]] = load float, ptr [[ARRAYIDX349_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_12:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL38]]
; CHECK-NEXT:    [[TMP329:%.*]] = load float, ptr [[ARRAYIDX352_12]], align 4
; CHECK-NEXT:    [[TMP330:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP328]], float [[TMP329]], float [[TMP327]])
; CHECK-NEXT:    [[ARRAYIDX349_13:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL45]]
; CHECK-NEXT:    [[TMP331:%.*]] = load float, ptr [[ARRAYIDX349_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_13:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL39]]
; CHECK-NEXT:    [[TMP332:%.*]] = load float, ptr [[ARRAYIDX352_13]], align 4
; CHECK-NEXT:    [[TMP333:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP331]], float [[TMP332]], float [[TMP330]])
; CHECK-NEXT:    [[ARRAYIDX349_14:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL46]]
; CHECK-NEXT:    [[TMP334:%.*]] = load float, ptr [[ARRAYIDX349_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_14:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL4012]]
; CHECK-NEXT:    [[TMP335:%.*]] = load float, ptr [[ARRAYIDX352_14]], align 4
; CHECK-NEXT:    [[TMP336:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP334]], float [[TMP335]], float [[TMP333]])
; CHECK-NEXT:    [[ARRAYIDX349_15:%.*]] = getelementptr float, ptr [[ARRAYIDX349]], i32 [[MUL47]]
; CHECK-NEXT:    [[TMP337:%.*]] = load float, ptr [[ARRAYIDX349_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX352_15:%.*]] = getelementptr float, ptr [[ARRAYIDX352]], i32 [[MUL41]]
; CHECK-NEXT:    [[TMP338:%.*]] = load float, ptr [[ARRAYIDX352_15]], align 4
; CHECK-NEXT:    [[TMP339]] = tail call float @llvm.fmuladd.f32(float [[TMP337]], float [[TMP338]], float [[TMP336]])
; CHECK-NEXT:    [[INC355_15]] = add nsw i32 [[N339_0981]], 16
; CHECK-NEXT:    [[CMP343_15:%.*]] = icmp slt i32 [[INC355_15]], [[SUB2223]]
; CHECK-NEXT:    br i1 [[CMP343_15]], label [[FOR_BODY345_15]], label [[FOR_COND_PREHEADER31]]
; CHECK:       for.cond.preheader31:
; CHECK-NEXT:    [[TMP340:%.*]] = phi float [ [[ACC323_0985]], [[FOR_BODY338]] ], [ [[TMP339]], [[FOR_BODY345_15]] ]
; CHECK-NEXT:    [[TMP341:%.*]] = phi i32 [ [[SUB340]], [[FOR_BODY338]] ], [ [[INC355_15]], [[FOR_BODY345_15]] ]
; CHECK-NEXT:    [[TMP342:%.*]] = icmp slt i32 [[TMP341]], [[TMP4]]
; CHECK-NEXT:    br i1 [[TMP342]], label [[FOR_BODY345_CLONE:%.*]], label [[FOR_COND_CLEANUP344]]
; CHECK:       for.body345.clone:
; CHECK-NEXT:    [[N339_0981_CLONE:%.*]] = phi i32 [ [[INC355_CLONE:%.*]], [[FOR_BODY345_CLONE]] ], [ [[TMP341]], [[FOR_COND_PREHEADER31]] ]
; CHECK-NEXT:    [[ACC323_1980_CLONE:%.*]] = phi float [ [[TMP345:%.*]], [[FOR_BODY345_CLONE]] ], [ [[TMP340]], [[FOR_COND_PREHEADER31]] ]
; CHECK-NEXT:    [[MUL347_CLONE:%.*]] = mul nsw i32 [[N339_0981_CLONE]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX349_CLONE:%.*]] = getelementptr float, ptr [[TMP291]], i32 [[MUL347_CLONE]]
; CHECK-NEXT:    [[TMP343:%.*]] = load float, ptr [[ARRAYIDX349_CLONE]], align 4
; CHECK-NEXT:    [[MUL351_CLONE:%.*]] = mul nsw i32 [[N339_0981_CLONE]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX352_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA324_0986]], i32 [[MUL351_CLONE]]
; CHECK-NEXT:    [[TMP344:%.*]] = load float, ptr [[ARRAYIDX352_CLONE]], align 4
; CHECK-NEXT:    [[TMP345]] = tail call float @llvm.fmuladd.f32(float [[TMP343]], float [[TMP344]], float [[ACC323_1980_CLONE]])
; CHECK-NEXT:    [[INC355_CLONE]] = add nsw i32 [[N339_0981_CLONE]], 1
; CHECK-NEXT:    [[CMP343_CLONE:%.*]] = icmp eq i32 [[INC355_CLONE]], [[TMP4]]
; CHECK-NEXT:    br i1 [[CMP343_CLONE]], label [[FOR_COND_CLEANUP344]], label [[FOR_BODY345_CLONE]]
; CHECK:       for.cond.cleanup344:
; CHECK-NEXT:    [[ACC323_1_LCSSA]] = phi float [ [[TMP340]], [[FOR_COND_PREHEADER31]] ], [ [[TMP345]], [[FOR_BODY345_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR357]] = getelementptr inbounds float, ptr [[F_DATA324_0986]], i32 [[MUL10]]
; CHECK-NEXT:    [[ADD358]] = add nsw i32 [[I_POS_X322_0984]], [[MUL]]
; CHECK-NEXT:    [[CMP336:%.*]] = icmp slt i32 [[INC360]], [[SUB335]]
; CHECK-NEXT:    br i1 [[CMP336]], label [[FOR_BODY338]], label [[FOR_COND_CLEANUP337]]
; CHECK:       for.cond441.preheader:
; CHECK-NEXT:    [[I_POS_Y316_1_LCSSA:%.*]] = phi i32 [ [[I_POS_Y316_0_LCSSA]], [[FOR_COND376_PREHEADER]] ], [ [[ADD424:%.*]], [[FOR_COND_CLEANUP399:%.*]] ]
; CHECK-NEXT:    br i1 [[CMP4431023]], label [[FOR_BODY445:%.*]], label [[FOR_COND_CLEANUP444]]
; CHECK:       for.body383:
; CHECK-NEXT:    [[X375_01007:%.*]] = phi i32 [ [[INC434:%.*]], [[FOR_COND_CLEANUP399]] ], [ [[SHR]], [[FOR_COND376_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_Y316_11006:%.*]] = phi i32 [ [[ADD424]], [[FOR_COND_CLEANUP399]] ], [ [[I_POS_Y316_0_LCSSA]], [[FOR_COND376_PREHEADER]] ]
; CHECK-NEXT:    [[INC434]] = add nsw i32 [[X375_01007]], 1
; CHECK-NEXT:    br i1 [[CMP336983]], label [[FOR_COND402_PREHEADER:%.*]], label [[FOR_COND_CLEANUP399]]
; CHECK:       for.cond402.preheader:
; CHECK-NEXT:    [[M388_01003:%.*]] = phi i32 [ [[INC421:%.*]], [[FOR_COND_CLEANUP405:%.*]] ], [ 0, [[FOR_BODY383]] ]
; CHECK-NEXT:    [[F_DATA386_01002:%.*]] = phi ptr [ [[ADD_PTR418:%.*]], [[FOR_COND_CLEANUP405]] ], [ [[TMP15]], [[FOR_BODY383]] ]
; CHECK-NEXT:    [[ACC385_01001:%.*]] = phi float [ [[ACC385_1_LCSSA:%.*]], [[FOR_COND_CLEANUP405]] ], [ 0.000000e+00, [[FOR_BODY383]] ]
; CHECK-NEXT:    [[I_POS_X384_01000:%.*]] = phi i32 [ [[ADD419:%.*]], [[FOR_COND_CLEANUP405]] ], [ [[I_POS_Y316_11006]], [[FOR_BODY383]] ]
; CHECK-NEXT:    [[TMP346:%.*]] = getelementptr float, ptr [[TMP2]], i32 [[I_POS_X384_01000]]
; CHECK-NEXT:    [[INC421]] = add nuw nsw i32 [[M388_01003]], 1
; CHECK-NEXT:    br i1 [[CMP72905]], label [[FOR_BODY406_15:%.*]], label [[FOR_COND_PREHEADER33:%.*]]
; CHECK:       for.cond.cleanup399:
; CHECK-NEXT:    [[ACC385_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY383]] ], [ [[ACC385_1_LCSSA]], [[FOR_COND_CLEANUP405]] ]
; CHECK-NEXT:    [[ADD424]] = add nsw i32 [[I_POS_Y316_11006]], [[TMP14]]
; CHECK-NEXT:    [[MUL426:%.*]] = mul nsw i32 [[X375_01007]], [[TMP13]]
; CHECK-NEXT:    [[GEP1012:%.*]] = getelementptr float, ptr [[INVARIANT_GEP993]], i32 [[MUL426]]
; CHECK-NEXT:    store float [[ACC385_0_LCSSA]], ptr [[GEP1012]], align 4
; CHECK-NEXT:    [[EXITCOND1068_NOT:%.*]] = icmp eq i32 [[INC434]], [[SUB527]]
; CHECK-NEXT:    br i1 [[EXITCOND1068_NOT]], label [[FOR_COND441_PREHEADER]], label [[FOR_BODY383]]
; CHECK:       for.body406.15:
; CHECK-NEXT:    [[N401_0997:%.*]] = phi i32 [ [[INC416_15:%.*]], [[FOR_BODY406_15]] ], [ 0, [[FOR_COND402_PREHEADER]] ]
; CHECK-NEXT:    [[ACC385_1996:%.*]] = phi float [ [[TMP394:%.*]], [[FOR_BODY406_15]] ], [ [[ACC385_01001]], [[FOR_COND402_PREHEADER]] ]
; CHECK-NEXT:    [[MUL408:%.*]] = mul nsw i32 [[N401_0997]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX410:%.*]] = getelementptr float, ptr [[TMP346]], i32 [[MUL408]]
; CHECK-NEXT:    [[TMP347:%.*]] = load float, ptr [[ARRAYIDX410]], align 4
; CHECK-NEXT:    [[MUL412:%.*]] = mul nsw i32 [[N401_0997]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX413:%.*]] = getelementptr float, ptr [[F_DATA386_01002]], i32 [[MUL412]]
; CHECK-NEXT:    [[TMP348:%.*]] = load float, ptr [[ARRAYIDX413]], align 4
; CHECK-NEXT:    [[TMP349:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP347]], float [[TMP348]], float [[ACC385_1996]])
; CHECK-NEXT:    [[ARRAYIDX410_1:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP350:%.*]] = load float, ptr [[ARRAYIDX410_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_1:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP351:%.*]] = load float, ptr [[ARRAYIDX413_1]], align 4
; CHECK-NEXT:    [[TMP352:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP350]], float [[TMP351]], float [[TMP349]])
; CHECK-NEXT:    [[ARRAYIDX410_2:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL3413]]
; CHECK-NEXT:    [[TMP353:%.*]] = load float, ptr [[ARRAYIDX410_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_2:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL2810]]
; CHECK-NEXT:    [[TMP354:%.*]] = load float, ptr [[ARRAYIDX413_2]], align 4
; CHECK-NEXT:    [[TMP355:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP353]], float [[TMP354]], float [[TMP352]])
; CHECK-NEXT:    [[ARRAYIDX410_3:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL3514]]
; CHECK-NEXT:    [[TMP356:%.*]] = load float, ptr [[ARRAYIDX410_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_3:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL29]]
; CHECK-NEXT:    [[TMP357:%.*]] = load float, ptr [[ARRAYIDX413_3]], align 4
; CHECK-NEXT:    [[TMP358:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP356]], float [[TMP357]], float [[TMP355]])
; CHECK-NEXT:    [[ARRAYIDX410_4:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL3615]]
; CHECK-NEXT:    [[TMP359:%.*]] = load float, ptr [[ARRAYIDX410_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_4:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL3011]]
; CHECK-NEXT:    [[TMP360:%.*]] = load float, ptr [[ARRAYIDX413_4]], align 4
; CHECK-NEXT:    [[TMP361:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP359]], float [[TMP360]], float [[TMP358]])
; CHECK-NEXT:    [[ARRAYIDX410_5:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL3716]]
; CHECK-NEXT:    [[TMP362:%.*]] = load float, ptr [[ARRAYIDX410_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_5:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL31]]
; CHECK-NEXT:    [[TMP363:%.*]] = load float, ptr [[ARRAYIDX413_5]], align 4
; CHECK-NEXT:    [[TMP364:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP362]], float [[TMP363]], float [[TMP361]])
; CHECK-NEXT:    [[ARRAYIDX410_6:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL3817]]
; CHECK-NEXT:    [[TMP365:%.*]] = load float, ptr [[ARRAYIDX410_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_6:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP366:%.*]] = load float, ptr [[ARRAYIDX413_6]], align 4
; CHECK-NEXT:    [[TMP367:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP365]], float [[TMP366]], float [[TMP364]])
; CHECK-NEXT:    [[ARRAYIDX410_7:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL3918]]
; CHECK-NEXT:    [[TMP368:%.*]] = load float, ptr [[ARRAYIDX410_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_7:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP369:%.*]] = load float, ptr [[ARRAYIDX413_7]], align 4
; CHECK-NEXT:    [[TMP370:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP368]], float [[TMP369]], float [[TMP367]])
; CHECK-NEXT:    [[ARRAYIDX410_8:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL4019]]
; CHECK-NEXT:    [[TMP371:%.*]] = load float, ptr [[ARRAYIDX410_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_8:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL34]]
; CHECK-NEXT:    [[TMP372:%.*]] = load float, ptr [[ARRAYIDX413_8]], align 4
; CHECK-NEXT:    [[TMP373:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP371]], float [[TMP372]], float [[TMP370]])
; CHECK-NEXT:    [[ARRAYIDX410_9:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL4120]]
; CHECK-NEXT:    [[TMP374:%.*]] = load float, ptr [[ARRAYIDX410_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_9:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL35]]
; CHECK-NEXT:    [[TMP375:%.*]] = load float, ptr [[ARRAYIDX413_9]], align 4
; CHECK-NEXT:    [[TMP376:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP374]], float [[TMP375]], float [[TMP373]])
; CHECK-NEXT:    [[ARRAYIDX410_10:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL4221]]
; CHECK-NEXT:    [[TMP377:%.*]] = load float, ptr [[ARRAYIDX410_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_10:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL36]]
; CHECK-NEXT:    [[TMP378:%.*]] = load float, ptr [[ARRAYIDX413_10]], align 4
; CHECK-NEXT:    [[TMP379:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP377]], float [[TMP378]], float [[TMP376]])
; CHECK-NEXT:    [[ARRAYIDX410_11:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL43]]
; CHECK-NEXT:    [[TMP380:%.*]] = load float, ptr [[ARRAYIDX410_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_11:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL37]]
; CHECK-NEXT:    [[TMP381:%.*]] = load float, ptr [[ARRAYIDX413_11]], align 4
; CHECK-NEXT:    [[TMP382:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP380]], float [[TMP381]], float [[TMP379]])
; CHECK-NEXT:    [[ARRAYIDX410_12:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL4422]]
; CHECK-NEXT:    [[TMP383:%.*]] = load float, ptr [[ARRAYIDX410_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_12:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL38]]
; CHECK-NEXT:    [[TMP384:%.*]] = load float, ptr [[ARRAYIDX413_12]], align 4
; CHECK-NEXT:    [[TMP385:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP383]], float [[TMP384]], float [[TMP382]])
; CHECK-NEXT:    [[ARRAYIDX410_13:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL45]]
; CHECK-NEXT:    [[TMP386:%.*]] = load float, ptr [[ARRAYIDX410_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_13:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL39]]
; CHECK-NEXT:    [[TMP387:%.*]] = load float, ptr [[ARRAYIDX413_13]], align 4
; CHECK-NEXT:    [[TMP388:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP386]], float [[TMP387]], float [[TMP385]])
; CHECK-NEXT:    [[ARRAYIDX410_14:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL46]]
; CHECK-NEXT:    [[TMP389:%.*]] = load float, ptr [[ARRAYIDX410_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_14:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL4012]]
; CHECK-NEXT:    [[TMP390:%.*]] = load float, ptr [[ARRAYIDX413_14]], align 4
; CHECK-NEXT:    [[TMP391:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP389]], float [[TMP390]], float [[TMP388]])
; CHECK-NEXT:    [[ARRAYIDX410_15:%.*]] = getelementptr float, ptr [[ARRAYIDX410]], i32 [[MUL47]]
; CHECK-NEXT:    [[TMP392:%.*]] = load float, ptr [[ARRAYIDX410_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX413_15:%.*]] = getelementptr float, ptr [[ARRAYIDX413]], i32 [[MUL41]]
; CHECK-NEXT:    [[TMP393:%.*]] = load float, ptr [[ARRAYIDX413_15]], align 4
; CHECK-NEXT:    [[TMP394]] = tail call float @llvm.fmuladd.f32(float [[TMP392]], float [[TMP393]], float [[TMP391]])
; CHECK-NEXT:    [[INC416_15]] = add nuw nsw i32 [[N401_0997]], 16
; CHECK-NEXT:    [[EXITCOND1067_NOT_15:%.*]] = icmp slt i32 [[INC416_15]], [[SUB2223]]
; CHECK-NEXT:    br i1 [[EXITCOND1067_NOT_15]], label [[FOR_BODY406_15]], label [[FOR_COND_PREHEADER33]]
; CHECK:       for.cond.preheader33:
; CHECK-NEXT:    [[TMP395:%.*]] = phi float [ [[ACC385_01001]], [[FOR_COND402_PREHEADER]] ], [ [[TMP394]], [[FOR_BODY406_15]] ]
; CHECK-NEXT:    [[TMP396:%.*]] = phi i32 [ 0, [[FOR_COND402_PREHEADER]] ], [ [[INC416_15]], [[FOR_BODY406_15]] ]
; CHECK-NEXT:    [[TMP397:%.*]] = icmp slt i32 [[TMP396]], [[TMP4]]
; CHECK-NEXT:    br i1 [[TMP397]], label [[FOR_BODY406_CLONE:%.*]], label [[FOR_COND_CLEANUP405]]
; CHECK:       for.body406.clone:
; CHECK-NEXT:    [[N401_0997_CLONE:%.*]] = phi i32 [ [[INC416_CLONE:%.*]], [[FOR_BODY406_CLONE]] ], [ [[TMP396]], [[FOR_COND_PREHEADER33]] ]
; CHECK-NEXT:    [[ACC385_1996_CLONE:%.*]] = phi float [ [[TMP400:%.*]], [[FOR_BODY406_CLONE]] ], [ [[TMP395]], [[FOR_COND_PREHEADER33]] ]
; CHECK-NEXT:    [[MUL408_CLONE:%.*]] = mul nsw i32 [[N401_0997_CLONE]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX410_CLONE:%.*]] = getelementptr float, ptr [[TMP346]], i32 [[MUL408_CLONE]]
; CHECK-NEXT:    [[TMP398:%.*]] = load float, ptr [[ARRAYIDX410_CLONE]], align 4
; CHECK-NEXT:    [[MUL412_CLONE:%.*]] = mul nsw i32 [[N401_0997_CLONE]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX413_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA386_01002]], i32 [[MUL412_CLONE]]
; CHECK-NEXT:    [[TMP399:%.*]] = load float, ptr [[ARRAYIDX413_CLONE]], align 4
; CHECK-NEXT:    [[TMP400]] = tail call float @llvm.fmuladd.f32(float [[TMP398]], float [[TMP399]], float [[ACC385_1996_CLONE]])
; CHECK-NEXT:    [[INC416_CLONE]] = add nuw nsw i32 [[N401_0997_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND1067_NOT_CLONE:%.*]] = icmp eq i32 [[INC416_CLONE]], [[TMP4]]
; CHECK-NEXT:    br i1 [[EXITCOND1067_NOT_CLONE]], label [[FOR_COND_CLEANUP405]], label [[FOR_BODY406_CLONE]]
; CHECK:       for.cond.cleanup405:
; CHECK-NEXT:    [[ACC385_1_LCSSA]] = phi float [ [[TMP395]], [[FOR_COND_PREHEADER33]] ], [ [[TMP400]], [[FOR_BODY406_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR418]] = getelementptr inbounds float, ptr [[F_DATA386_01002]], i32 [[MUL10]]
; CHECK-NEXT:    [[ADD419]] = add nsw i32 [[I_POS_X384_01000]], [[MUL]]
; CHECK-NEXT:    [[CMP398:%.*]] = icmp slt i32 [[INC421]], [[SUB335]]
; CHECK-NEXT:    br i1 [[CMP398]], label [[FOR_COND402_PREHEADER]], label [[FOR_COND_CLEANUP399]]
; CHECK:       for.cond.cleanup444:
; CHECK-NEXT:    [[ADD508]] = add nsw i32 [[I_POS_21029]], [[MUL]]
; CHECK-NEXT:    [[EXITCOND1070_NOT:%.*]] = icmp eq i32 [[INC510]], [[TMP1]]
; CHECK-NEXT:    br i1 [[EXITCOND1070_NOT]], label [[FOR_COND513_PREHEADER]], label [[FOR_COND318_PREHEADER]]
; CHECK:       for.body445:
; CHECK-NEXT:    [[X436_01025:%.*]] = phi i32 [ [[INC503:%.*]], [[FOR_COND_CLEANUP461:%.*]] ], [ [[SUB527]], [[FOR_COND441_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_Y316_21024:%.*]] = phi i32 [ [[ADD493:%.*]], [[FOR_COND_CLEANUP461]] ], [ [[I_POS_Y316_1_LCSSA]], [[FOR_COND441_PREHEADER]] ]
; CHECK-NEXT:    [[ADD470:%.*]] = add i32 [[X436_01025]], [[SUB467]]
; CHECK-NEXT:    [[ADD471_NEG:%.*]] = xor i32 [[ADD470]], -1
; CHECK-NEXT:    [[SUB472:%.*]] = add i32 [[ADD471_NEG]], [[TMP4]]
; CHECK-NEXT:    [[CMP4731013:%.*]] = icmp sgt i32 [[SUB472]], 15
; CHECK-NEXT:    [[SUB21636:%.*]] = add nsw i32 [[SUB472]], -15
; CHECK-NEXT:    [[INC503]] = add nsw i32 [[X436_01025]], 1
; CHECK-NEXT:    br i1 [[CMP336983]], label [[FOR_COND464_PREHEADER:%.*]], label [[FOR_COND_CLEANUP461]]
; CHECK:       for.cond464.preheader:
; CHECK-NEXT:    [[M450_01021:%.*]] = phi i32 [ [[INC490:%.*]], [[FOR_COND_CLEANUP474:%.*]] ], [ 0, [[FOR_BODY445]] ]
; CHECK-NEXT:    [[F_DATA448_01020:%.*]] = phi ptr [ [[ADD_PTR487:%.*]], [[FOR_COND_CLEANUP474]] ], [ [[TMP15]], [[FOR_BODY445]] ]
; CHECK-NEXT:    [[ACC447_01019:%.*]] = phi float [ [[ACC447_1_LCSSA:%.*]], [[FOR_COND_CLEANUP474]] ], [ 0.000000e+00, [[FOR_BODY445]] ]
; CHECK-NEXT:    [[I_POS_X446_01018:%.*]] = phi i32 [ [[ADD488:%.*]], [[FOR_COND_CLEANUP474]] ], [ [[I_POS_Y316_21024]], [[FOR_BODY445]] ]
; CHECK-NEXT:    [[TMP401:%.*]] = getelementptr float, ptr [[TMP2]], i32 [[I_POS_X446_01018]]
; CHECK-NEXT:    [[INC490]] = add nuw nsw i32 [[M450_01021]], 1
; CHECK-NEXT:    br i1 [[CMP4731013]], label [[FOR_BODY475_15:%.*]], label [[FOR_COND_PREHEADER35:%.*]]
; CHECK:       for.cond.cleanup461:
; CHECK-NEXT:    [[ACC447_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY445]] ], [ [[ACC447_1_LCSSA]], [[FOR_COND_CLEANUP474]] ]
; CHECK-NEXT:    [[ADD493]] = add nsw i32 [[I_POS_Y316_21024]], [[TMP14]]
; CHECK-NEXT:    [[MUL495:%.*]] = mul nsw i32 [[X436_01025]], [[TMP13]]
; CHECK-NEXT:    [[GEP1027:%.*]] = getelementptr float, ptr [[INVARIANT_GEP993]], i32 [[MUL495]]
; CHECK-NEXT:    store float [[ACC447_0_LCSSA]], ptr [[GEP1027]], align 4
; CHECK-NEXT:    [[EXITCOND1069_NOT:%.*]] = icmp eq i32 [[INC503]], [[TMP0]]
; CHECK-NEXT:    br i1 [[EXITCOND1069_NOT]], label [[FOR_COND_CLEANUP444]], label [[FOR_BODY445]]
; CHECK:       for.body475.15:
; CHECK-NEXT:    [[N463_01015:%.*]] = phi i32 [ [[INC485_15:%.*]], [[FOR_BODY475_15]] ], [ 0, [[FOR_COND464_PREHEADER]] ]
; CHECK-NEXT:    [[ACC447_11014:%.*]] = phi float [ [[TMP449:%.*]], [[FOR_BODY475_15]] ], [ [[ACC447_01019]], [[FOR_COND464_PREHEADER]] ]
; CHECK-NEXT:    [[MUL477:%.*]] = mul nsw i32 [[N463_01015]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX479:%.*]] = getelementptr float, ptr [[TMP401]], i32 [[MUL477]]
; CHECK-NEXT:    [[TMP402:%.*]] = load float, ptr [[ARRAYIDX479]], align 4
; CHECK-NEXT:    [[MUL481:%.*]] = mul nsw i32 [[N463_01015]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX482:%.*]] = getelementptr float, ptr [[F_DATA448_01020]], i32 [[MUL481]]
; CHECK-NEXT:    [[TMP403:%.*]] = load float, ptr [[ARRAYIDX482]], align 4
; CHECK-NEXT:    [[TMP404:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP402]], float [[TMP403]], float [[ACC447_11014]])
; CHECK-NEXT:    [[ARRAYIDX479_1:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP405:%.*]] = load float, ptr [[ARRAYIDX479_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_1:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP406:%.*]] = load float, ptr [[ARRAYIDX482_1]], align 4
; CHECK-NEXT:    [[TMP407:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP405]], float [[TMP406]], float [[TMP404]])
; CHECK-NEXT:    [[ARRAYIDX479_2:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL3413]]
; CHECK-NEXT:    [[TMP408:%.*]] = load float, ptr [[ARRAYIDX479_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_2:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL2810]]
; CHECK-NEXT:    [[TMP409:%.*]] = load float, ptr [[ARRAYIDX482_2]], align 4
; CHECK-NEXT:    [[TMP410:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP408]], float [[TMP409]], float [[TMP407]])
; CHECK-NEXT:    [[ARRAYIDX479_3:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL3514]]
; CHECK-NEXT:    [[TMP411:%.*]] = load float, ptr [[ARRAYIDX479_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_3:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL29]]
; CHECK-NEXT:    [[TMP412:%.*]] = load float, ptr [[ARRAYIDX482_3]], align 4
; CHECK-NEXT:    [[TMP413:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP411]], float [[TMP412]], float [[TMP410]])
; CHECK-NEXT:    [[ARRAYIDX479_4:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL3615]]
; CHECK-NEXT:    [[TMP414:%.*]] = load float, ptr [[ARRAYIDX479_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_4:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL3011]]
; CHECK-NEXT:    [[TMP415:%.*]] = load float, ptr [[ARRAYIDX482_4]], align 4
; CHECK-NEXT:    [[TMP416:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP414]], float [[TMP415]], float [[TMP413]])
; CHECK-NEXT:    [[ARRAYIDX479_5:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL3716]]
; CHECK-NEXT:    [[TMP417:%.*]] = load float, ptr [[ARRAYIDX479_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_5:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL31]]
; CHECK-NEXT:    [[TMP418:%.*]] = load float, ptr [[ARRAYIDX482_5]], align 4
; CHECK-NEXT:    [[TMP419:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP417]], float [[TMP418]], float [[TMP416]])
; CHECK-NEXT:    [[ARRAYIDX479_6:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL3817]]
; CHECK-NEXT:    [[TMP420:%.*]] = load float, ptr [[ARRAYIDX479_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_6:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP421:%.*]] = load float, ptr [[ARRAYIDX482_6]], align 4
; CHECK-NEXT:    [[TMP422:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP420]], float [[TMP421]], float [[TMP419]])
; CHECK-NEXT:    [[ARRAYIDX479_7:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL3918]]
; CHECK-NEXT:    [[TMP423:%.*]] = load float, ptr [[ARRAYIDX479_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_7:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP424:%.*]] = load float, ptr [[ARRAYIDX482_7]], align 4
; CHECK-NEXT:    [[TMP425:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP423]], float [[TMP424]], float [[TMP422]])
; CHECK-NEXT:    [[ARRAYIDX479_8:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL4019]]
; CHECK-NEXT:    [[TMP426:%.*]] = load float, ptr [[ARRAYIDX479_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_8:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL34]]
; CHECK-NEXT:    [[TMP427:%.*]] = load float, ptr [[ARRAYIDX482_8]], align 4
; CHECK-NEXT:    [[TMP428:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP426]], float [[TMP427]], float [[TMP425]])
; CHECK-NEXT:    [[ARRAYIDX479_9:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL4120]]
; CHECK-NEXT:    [[TMP429:%.*]] = load float, ptr [[ARRAYIDX479_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_9:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL35]]
; CHECK-NEXT:    [[TMP430:%.*]] = load float, ptr [[ARRAYIDX482_9]], align 4
; CHECK-NEXT:    [[TMP431:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP429]], float [[TMP430]], float [[TMP428]])
; CHECK-NEXT:    [[ARRAYIDX479_10:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL4221]]
; CHECK-NEXT:    [[TMP432:%.*]] = load float, ptr [[ARRAYIDX479_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_10:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL36]]
; CHECK-NEXT:    [[TMP433:%.*]] = load float, ptr [[ARRAYIDX482_10]], align 4
; CHECK-NEXT:    [[TMP434:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP432]], float [[TMP433]], float [[TMP431]])
; CHECK-NEXT:    [[ARRAYIDX479_11:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL43]]
; CHECK-NEXT:    [[TMP435:%.*]] = load float, ptr [[ARRAYIDX479_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_11:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL37]]
; CHECK-NEXT:    [[TMP436:%.*]] = load float, ptr [[ARRAYIDX482_11]], align 4
; CHECK-NEXT:    [[TMP437:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP435]], float [[TMP436]], float [[TMP434]])
; CHECK-NEXT:    [[ARRAYIDX479_12:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL4422]]
; CHECK-NEXT:    [[TMP438:%.*]] = load float, ptr [[ARRAYIDX479_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_12:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL38]]
; CHECK-NEXT:    [[TMP439:%.*]] = load float, ptr [[ARRAYIDX482_12]], align 4
; CHECK-NEXT:    [[TMP440:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP438]], float [[TMP439]], float [[TMP437]])
; CHECK-NEXT:    [[ARRAYIDX479_13:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL45]]
; CHECK-NEXT:    [[TMP441:%.*]] = load float, ptr [[ARRAYIDX479_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_13:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL39]]
; CHECK-NEXT:    [[TMP442:%.*]] = load float, ptr [[ARRAYIDX482_13]], align 4
; CHECK-NEXT:    [[TMP443:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP441]], float [[TMP442]], float [[TMP440]])
; CHECK-NEXT:    [[ARRAYIDX479_14:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL46]]
; CHECK-NEXT:    [[TMP444:%.*]] = load float, ptr [[ARRAYIDX479_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_14:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL4012]]
; CHECK-NEXT:    [[TMP445:%.*]] = load float, ptr [[ARRAYIDX482_14]], align 4
; CHECK-NEXT:    [[TMP446:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP444]], float [[TMP445]], float [[TMP443]])
; CHECK-NEXT:    [[ARRAYIDX479_15:%.*]] = getelementptr float, ptr [[ARRAYIDX479]], i32 [[MUL47]]
; CHECK-NEXT:    [[TMP447:%.*]] = load float, ptr [[ARRAYIDX479_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX482_15:%.*]] = getelementptr float, ptr [[ARRAYIDX482]], i32 [[MUL41]]
; CHECK-NEXT:    [[TMP448:%.*]] = load float, ptr [[ARRAYIDX482_15]], align 4
; CHECK-NEXT:    [[TMP449]] = tail call float @llvm.fmuladd.f32(float [[TMP447]], float [[TMP448]], float [[TMP446]])
; CHECK-NEXT:    [[INC485_15]] = add nuw nsw i32 [[N463_01015]], 16
; CHECK-NEXT:    [[CMP473_15:%.*]] = icmp slt i32 [[INC485_15]], [[SUB21636]]
; CHECK-NEXT:    br i1 [[CMP473_15]], label [[FOR_BODY475_15]], label [[FOR_COND_PREHEADER35]]
; CHECK:       for.cond.preheader35:
; CHECK-NEXT:    [[TMP450:%.*]] = phi float [ [[ACC447_01019]], [[FOR_COND464_PREHEADER]] ], [ [[TMP449]], [[FOR_BODY475_15]] ]
; CHECK-NEXT:    [[TMP451:%.*]] = phi i32 [ 0, [[FOR_COND464_PREHEADER]] ], [ [[INC485_15]], [[FOR_BODY475_15]] ]
; CHECK-NEXT:    [[TMP452:%.*]] = icmp slt i32 [[TMP451]], [[SUB472]]
; CHECK-NEXT:    br i1 [[TMP452]], label [[FOR_BODY475_CLONE:%.*]], label [[FOR_COND_CLEANUP474]]
; CHECK:       for.body475.clone:
; CHECK-NEXT:    [[N463_01015_CLONE:%.*]] = phi i32 [ [[INC485_CLONE:%.*]], [[FOR_BODY475_CLONE]] ], [ [[TMP451]], [[FOR_COND_PREHEADER35]] ]
; CHECK-NEXT:    [[ACC447_11014_CLONE:%.*]] = phi float [ [[TMP455:%.*]], [[FOR_BODY475_CLONE]] ], [ [[TMP450]], [[FOR_COND_PREHEADER35]] ]
; CHECK-NEXT:    [[MUL477_CLONE:%.*]] = mul nsw i32 [[N463_01015_CLONE]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX479_CLONE:%.*]] = getelementptr float, ptr [[TMP401]], i32 [[MUL477_CLONE]]
; CHECK-NEXT:    [[TMP453:%.*]] = load float, ptr [[ARRAYIDX479_CLONE]], align 4
; CHECK-NEXT:    [[MUL481_CLONE:%.*]] = mul nsw i32 [[N463_01015_CLONE]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX482_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA448_01020]], i32 [[MUL481_CLONE]]
; CHECK-NEXT:    [[TMP454:%.*]] = load float, ptr [[ARRAYIDX482_CLONE]], align 4
; CHECK-NEXT:    [[TMP455]] = tail call float @llvm.fmuladd.f32(float [[TMP453]], float [[TMP454]], float [[ACC447_11014_CLONE]])
; CHECK-NEXT:    [[INC485_CLONE]] = add nuw nsw i32 [[N463_01015_CLONE]], 1
; CHECK-NEXT:    [[CMP473_CLONE:%.*]] = icmp eq i32 [[INC485_CLONE]], [[SUB472]]
; CHECK-NEXT:    br i1 [[CMP473_CLONE]], label [[FOR_COND_CLEANUP474]], label [[FOR_BODY475_CLONE]]
; CHECK:       for.cond.cleanup474:
; CHECK-NEXT:    [[ACC447_1_LCSSA]] = phi float [ [[TMP450]], [[FOR_COND_PREHEADER35]] ], [ [[TMP455]], [[FOR_BODY475_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR487]] = getelementptr inbounds float, ptr [[F_DATA448_01020]], i32 [[MUL10]]
; CHECK-NEXT:    [[ADD488]] = add nsw i32 [[I_POS_X446_01018]], [[MUL]]
; CHECK-NEXT:    [[CMP460:%.*]] = icmp slt i32 [[INC490]], [[SUB335]]
; CHECK-NEXT:    br i1 [[CMP460]], label [[FOR_COND464_PREHEADER]], label [[FOR_COND_CLEANUP461]]
; CHECK:       for.cond523.preheader:
; CHECK-NEXT:    [[Y512_01048:%.*]] = phi i32 [ [[INC581:%.*]], [[FOR_COND_CLEANUP529:%.*]] ], [ [[SHR7]], [[FOR_COND513_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_31047:%.*]] = phi i32 [ [[ADD579:%.*]], [[FOR_COND_CLEANUP529]] ], [ 0, [[FOR_COND513_PREHEADER]] ]
; CHECK-NEXT:    [[MUL568:%.*]] = mul i32 [[TMP12]], [[TMP11]]
; CHECK-NEXT:    [[MUL570:%.*]] = mul i32 [[MUL568]], [[Y512_01048]]
; CHECK-NEXT:    [[INVARIANT_GEP1044:%.*]] = getelementptr float, ptr [[TMP3]], i32 [[MUL570]]
; CHECK-NEXT:    [[INC581]] = add nsw i32 [[Y512_01048]], 1
; CHECK-NEXT:    br i1 [[CMP55915]], label [[FOR_BODY530:%.*]], label [[FOR_COND_CLEANUP529]]
; CHECK:       for.cond.cleanup519:
; CHECK-NEXT:    ret i32 0
; CHECK:       for.cond.cleanup529:
; CHECK-NEXT:    [[ADD579]] = add nsw i32 [[I_POS_31047]], [[MUL]]
; CHECK-NEXT:    [[EXITCOND1074_NOT:%.*]] = icmp eq i32 [[INC581]], [[SUB180]]
; CHECK-NEXT:    br i1 [[EXITCOND1074_NOT]], label [[FOR_COND_CLEANUP519]], label [[FOR_COND523_PREHEADER]]
; CHECK:       for.body530:
; CHECK-NEXT:    [[X522_01043:%.*]] = phi i32 [ [[INC574:%.*]], [[FOR_COND_CLEANUP539:%.*]] ], [ [[SHR]], [[FOR_COND523_PREHEADER]] ]
; CHECK-NEXT:    [[I_POS_Y521_01042:%.*]] = phi i32 [ [[ADD564:%.*]], [[FOR_COND_CLEANUP539]] ], [ [[I_POS_31047]], [[FOR_COND523_PREHEADER]] ]
; CHECK-NEXT:    [[INC574]] = add nsw i32 [[X522_01043]], 1
; CHECK-NEXT:    br i1 [[CMP197945]], label [[FOR_COND542_PREHEADER:%.*]], label [[FOR_COND_CLEANUP539]]
; CHECK:       for.cond542.preheader:
; CHECK-NEXT:    [[M535_01039:%.*]] = phi i32 [ [[INC561:%.*]], [[FOR_COND_CLEANUP545:%.*]] ], [ 0, [[FOR_BODY530]] ]
; CHECK-NEXT:    [[F_DATA533_01038:%.*]] = phi ptr [ [[ADD_PTR558:%.*]], [[FOR_COND_CLEANUP545]] ], [ [[TMP15]], [[FOR_BODY530]] ]
; CHECK-NEXT:    [[ACC532_01037:%.*]] = phi float [ [[ACC532_1_LCSSA:%.*]], [[FOR_COND_CLEANUP545]] ], [ 0.000000e+00, [[FOR_BODY530]] ]
; CHECK-NEXT:    [[I_POS_X531_01036:%.*]] = phi i32 [ [[ADD559:%.*]], [[FOR_COND_CLEANUP545]] ], [ [[I_POS_Y521_01042]], [[FOR_BODY530]] ]
; CHECK-NEXT:    [[TMP456:%.*]] = getelementptr float, ptr [[TMP2]], i32 [[I_POS_X531_01036]]
; CHECK-NEXT:    [[INC561]] = add nuw nsw i32 [[M535_01039]], 1
; CHECK-NEXT:    br i1 [[CMP72905]], label [[FOR_BODY546_15:%.*]], label [[FOR_COND_PREHEADER37:%.*]]
; CHECK:       for.cond.cleanup539:
; CHECK-NEXT:    [[ACC532_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY530]] ], [ [[ACC532_1_LCSSA]], [[FOR_COND_CLEANUP545]] ]
; CHECK-NEXT:    [[ADD564]] = add nsw i32 [[I_POS_Y521_01042]], [[TMP14]]
; CHECK-NEXT:    [[MUL566:%.*]] = mul nsw i32 [[X522_01043]], [[TMP13]]
; CHECK-NEXT:    [[GEP1045:%.*]] = getelementptr float, ptr [[INVARIANT_GEP1044]], i32 [[MUL566]]
; CHECK-NEXT:    store float [[ACC532_0_LCSSA]], ptr [[GEP1045]], align 4
; CHECK-NEXT:    [[EXITCOND1073_NOT:%.*]] = icmp eq i32 [[INC574]], [[SUB527]]
; CHECK-NEXT:    br i1 [[EXITCOND1073_NOT]], label [[FOR_COND_CLEANUP529]], label [[FOR_BODY530]]
; CHECK:       for.body546.15:
; CHECK-NEXT:    [[N541_01033:%.*]] = phi i32 [ [[INC556_15:%.*]], [[FOR_BODY546_15]] ], [ 0, [[FOR_COND542_PREHEADER]] ]
; CHECK-NEXT:    [[ACC532_11032:%.*]] = phi float [ [[TMP504:%.*]], [[FOR_BODY546_15]] ], [ [[ACC532_01037]], [[FOR_COND542_PREHEADER]] ]
; CHECK-NEXT:    [[MUL548:%.*]] = mul nsw i32 [[N541_01033]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX550:%.*]] = getelementptr float, ptr [[TMP456]], i32 [[MUL548]]
; CHECK-NEXT:    [[TMP457:%.*]] = load float, ptr [[ARRAYIDX550]], align 4
; CHECK-NEXT:    [[MUL552:%.*]] = mul nsw i32 [[N541_01033]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX553:%.*]] = getelementptr float, ptr [[F_DATA533_01038]], i32 [[MUL552]]
; CHECK-NEXT:    [[TMP458:%.*]] = load float, ptr [[ARRAYIDX553]], align 4
; CHECK-NEXT:    [[TMP459:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP457]], float [[TMP458]], float [[ACC532_11032]])
; CHECK-NEXT:    [[ARRAYIDX550_1:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[TMP14]]
; CHECK-NEXT:    [[TMP460:%.*]] = load float, ptr [[ARRAYIDX550_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_1:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP461:%.*]] = load float, ptr [[ARRAYIDX553_1]], align 4
; CHECK-NEXT:    [[TMP462:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP460]], float [[TMP461]], float [[TMP459]])
; CHECK-NEXT:    [[ARRAYIDX550_2:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL3413]]
; CHECK-NEXT:    [[TMP463:%.*]] = load float, ptr [[ARRAYIDX550_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_2:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL2810]]
; CHECK-NEXT:    [[TMP464:%.*]] = load float, ptr [[ARRAYIDX553_2]], align 4
; CHECK-NEXT:    [[TMP465:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP463]], float [[TMP464]], float [[TMP462]])
; CHECK-NEXT:    [[ARRAYIDX550_3:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL3514]]
; CHECK-NEXT:    [[TMP466:%.*]] = load float, ptr [[ARRAYIDX550_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_3:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL29]]
; CHECK-NEXT:    [[TMP467:%.*]] = load float, ptr [[ARRAYIDX553_3]], align 4
; CHECK-NEXT:    [[TMP468:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP466]], float [[TMP467]], float [[TMP465]])
; CHECK-NEXT:    [[ARRAYIDX550_4:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL3615]]
; CHECK-NEXT:    [[TMP469:%.*]] = load float, ptr [[ARRAYIDX550_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_4:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL3011]]
; CHECK-NEXT:    [[TMP470:%.*]] = load float, ptr [[ARRAYIDX553_4]], align 4
; CHECK-NEXT:    [[TMP471:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP469]], float [[TMP470]], float [[TMP468]])
; CHECK-NEXT:    [[ARRAYIDX550_5:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL3716]]
; CHECK-NEXT:    [[TMP472:%.*]] = load float, ptr [[ARRAYIDX550_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_5:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL31]]
; CHECK-NEXT:    [[TMP473:%.*]] = load float, ptr [[ARRAYIDX553_5]], align 4
; CHECK-NEXT:    [[TMP474:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP472]], float [[TMP473]], float [[TMP471]])
; CHECK-NEXT:    [[ARRAYIDX550_6:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL3817]]
; CHECK-NEXT:    [[TMP475:%.*]] = load float, ptr [[ARRAYIDX550_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_6:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP476:%.*]] = load float, ptr [[ARRAYIDX553_6]], align 4
; CHECK-NEXT:    [[TMP477:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP475]], float [[TMP476]], float [[TMP474]])
; CHECK-NEXT:    [[ARRAYIDX550_7:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL3918]]
; CHECK-NEXT:    [[TMP478:%.*]] = load float, ptr [[ARRAYIDX550_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_7:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP479:%.*]] = load float, ptr [[ARRAYIDX553_7]], align 4
; CHECK-NEXT:    [[TMP480:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP478]], float [[TMP479]], float [[TMP477]])
; CHECK-NEXT:    [[ARRAYIDX550_8:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL4019]]
; CHECK-NEXT:    [[TMP481:%.*]] = load float, ptr [[ARRAYIDX550_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_8:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL34]]
; CHECK-NEXT:    [[TMP482:%.*]] = load float, ptr [[ARRAYIDX553_8]], align 4
; CHECK-NEXT:    [[TMP483:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP481]], float [[TMP482]], float [[TMP480]])
; CHECK-NEXT:    [[ARRAYIDX550_9:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL4120]]
; CHECK-NEXT:    [[TMP484:%.*]] = load float, ptr [[ARRAYIDX550_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_9:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL35]]
; CHECK-NEXT:    [[TMP485:%.*]] = load float, ptr [[ARRAYIDX553_9]], align 4
; CHECK-NEXT:    [[TMP486:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP484]], float [[TMP485]], float [[TMP483]])
; CHECK-NEXT:    [[ARRAYIDX550_10:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL4221]]
; CHECK-NEXT:    [[TMP487:%.*]] = load float, ptr [[ARRAYIDX550_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_10:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL36]]
; CHECK-NEXT:    [[TMP488:%.*]] = load float, ptr [[ARRAYIDX553_10]], align 4
; CHECK-NEXT:    [[TMP489:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP487]], float [[TMP488]], float [[TMP486]])
; CHECK-NEXT:    [[ARRAYIDX550_11:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL43]]
; CHECK-NEXT:    [[TMP490:%.*]] = load float, ptr [[ARRAYIDX550_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_11:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL37]]
; CHECK-NEXT:    [[TMP491:%.*]] = load float, ptr [[ARRAYIDX553_11]], align 4
; CHECK-NEXT:    [[TMP492:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP490]], float [[TMP491]], float [[TMP489]])
; CHECK-NEXT:    [[ARRAYIDX550_12:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL4422]]
; CHECK-NEXT:    [[TMP493:%.*]] = load float, ptr [[ARRAYIDX550_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_12:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL38]]
; CHECK-NEXT:    [[TMP494:%.*]] = load float, ptr [[ARRAYIDX553_12]], align 4
; CHECK-NEXT:    [[TMP495:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP493]], float [[TMP494]], float [[TMP492]])
; CHECK-NEXT:    [[ARRAYIDX550_13:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL45]]
; CHECK-NEXT:    [[TMP496:%.*]] = load float, ptr [[ARRAYIDX550_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_13:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL39]]
; CHECK-NEXT:    [[TMP497:%.*]] = load float, ptr [[ARRAYIDX553_13]], align 4
; CHECK-NEXT:    [[TMP498:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP496]], float [[TMP497]], float [[TMP495]])
; CHECK-NEXT:    [[ARRAYIDX550_14:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL46]]
; CHECK-NEXT:    [[TMP499:%.*]] = load float, ptr [[ARRAYIDX550_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_14:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL4012]]
; CHECK-NEXT:    [[TMP500:%.*]] = load float, ptr [[ARRAYIDX553_14]], align 4
; CHECK-NEXT:    [[TMP501:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP499]], float [[TMP500]], float [[TMP498]])
; CHECK-NEXT:    [[ARRAYIDX550_15:%.*]] = getelementptr float, ptr [[ARRAYIDX550]], i32 [[MUL47]]
; CHECK-NEXT:    [[TMP502:%.*]] = load float, ptr [[ARRAYIDX550_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX553_15:%.*]] = getelementptr float, ptr [[ARRAYIDX553]], i32 [[MUL41]]
; CHECK-NEXT:    [[TMP503:%.*]] = load float, ptr [[ARRAYIDX553_15]], align 4
; CHECK-NEXT:    [[TMP504]] = tail call float @llvm.fmuladd.f32(float [[TMP502]], float [[TMP503]], float [[TMP501]])
; CHECK-NEXT:    [[INC556_15]] = add nuw nsw i32 [[N541_01033]], 16
; CHECK-NEXT:    [[EXITCOND1071_NOT_15:%.*]] = icmp slt i32 [[INC556_15]], [[SUB2223]]
; CHECK-NEXT:    br i1 [[EXITCOND1071_NOT_15]], label [[FOR_BODY546_15]], label [[FOR_COND_PREHEADER37]]
; CHECK:       for.cond.preheader37:
; CHECK-NEXT:    [[TMP505:%.*]] = phi float [ [[ACC532_01037]], [[FOR_COND542_PREHEADER]] ], [ [[TMP504]], [[FOR_BODY546_15]] ]
; CHECK-NEXT:    [[TMP506:%.*]] = phi i32 [ 0, [[FOR_COND542_PREHEADER]] ], [ [[INC556_15]], [[FOR_BODY546_15]] ]
; CHECK-NEXT:    [[TMP507:%.*]] = icmp slt i32 [[TMP506]], [[TMP4]]
; CHECK-NEXT:    br i1 [[TMP507]], label [[FOR_BODY546_CLONE:%.*]], label [[FOR_COND_CLEANUP545]]
; CHECK:       for.body546.clone:
; CHECK-NEXT:    [[N541_01033_CLONE:%.*]] = phi i32 [ [[INC556_CLONE:%.*]], [[FOR_BODY546_CLONE]] ], [ [[TMP506]], [[FOR_COND_PREHEADER37]] ]
; CHECK-NEXT:    [[ACC532_11032_CLONE:%.*]] = phi float [ [[TMP510:%.*]], [[FOR_BODY546_CLONE]] ], [ [[TMP505]], [[FOR_COND_PREHEADER37]] ]
; CHECK-NEXT:    [[MUL548_CLONE:%.*]] = mul nsw i32 [[N541_01033_CLONE]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX550_CLONE:%.*]] = getelementptr float, ptr [[TMP456]], i32 [[MUL548_CLONE]]
; CHECK-NEXT:    [[TMP508:%.*]] = load float, ptr [[ARRAYIDX550_CLONE]], align 4
; CHECK-NEXT:    [[MUL552_CLONE:%.*]] = mul nsw i32 [[N541_01033_CLONE]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX553_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA533_01038]], i32 [[MUL552_CLONE]]
; CHECK-NEXT:    [[TMP509:%.*]] = load float, ptr [[ARRAYIDX553_CLONE]], align 4
; CHECK-NEXT:    [[TMP510]] = tail call float @llvm.fmuladd.f32(float [[TMP508]], float [[TMP509]], float [[ACC532_11032_CLONE]])
; CHECK-NEXT:    [[INC556_CLONE]] = add nuw nsw i32 [[N541_01033_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND1071_NOT_CLONE:%.*]] = icmp eq i32 [[INC556_CLONE]], [[TMP4]]
; CHECK-NEXT:    br i1 [[EXITCOND1071_NOT_CLONE]], label [[FOR_COND_CLEANUP545]], label [[FOR_BODY546_CLONE]]
; CHECK:       for.cond.cleanup545:
; CHECK-NEXT:    [[ACC532_1_LCSSA]] = phi float [ [[TMP505]], [[FOR_COND_PREHEADER37]] ], [ [[TMP510]], [[FOR_BODY546_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR558]] = getelementptr inbounds float, ptr [[F_DATA533_01038]], i32 [[MUL10]]
; CHECK-NEXT:    [[ADD559]] = add nsw i32 [[I_POS_X531_01036]], [[MUL]]
; CHECK-NEXT:    [[EXITCOND1072_NOT:%.*]] = icmp eq i32 [[INC561]], [[TMP5]]
; CHECK-NEXT:    br i1 [[EXITCOND1072_NOT]], label [[FOR_COND_CLEANUP539]], label [[FOR_COND542_PREHEADER]]
;
entry:
  %size_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 5
  %0 = load i32, ptr %size_x, align 4
  %size_x1 = getelementptr inbounds %struct.image2d_s, ptr %out_image, i32 0, i32 5
  store i32 %0, ptr %size_x1, align 4
  %size_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 6
  %1 = load i32, ptr %size_y, align 4
  %size_y2 = getelementptr inbounds %struct.image2d_s, ptr %out_image, i32 0, i32 6
  store i32 %1, ptr %size_y2, align 4
  %2 = load ptr, ptr %in_image, align 4
  %3 = load ptr, ptr %out_image, align 4
  %size_x4 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 5
  %4 = load i32, ptr %size_x4, align 4
  %sub = add nsw i32 %4, -1
  %shr = ashr i32 %sub, 1
  %size_y5 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 6
  %5 = load i32, ptr %size_y5, align 4
  %sub6 = add nsw i32 %5, -1
  %shr7 = ashr i32 %sub6, 1
  %stride_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 3
  %6 = load i32, ptr %stride_x, align 4
  %step_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 2
  %7 = load i32, ptr %step_y, align 4
  %mul = mul nsw i32 %7, %6
  %stride_x8 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 3
  %8 = load i32, ptr %stride_x8, align 4
  %step_y9 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 2
  %9 = load i32, ptr %step_y9, align 4
  %mul10 = mul nsw i32 %9, %8
  %cmp938 = icmp sgt i32 %shr7, 0
  %step_x29 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 1
  %10 = load i32, ptr %step_x29, align 4
  %step_y43 = getelementptr inbounds %struct.image2d_s, ptr %out_image, i32 0, i32 2
  %11 = load i32, ptr %step_y43, align 4
  %stride_x41 = getelementptr inbounds %struct.image2d_s, ptr %out_image, i32 0, i32 3
  %12 = load i32, ptr %stride_x41, align 4
  %step_x39 = getelementptr inbounds %struct.image2d_s, ptr %out_image, i32 0, i32 1
  %13 = load i32, ptr %step_x39, align 4
  %step_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 1
  %14 = load i32, ptr %step_x, align 4
  %15 = load ptr, ptr %filter, align 4
  %div526.neg = sdiv i32 %4, -2
  %sub527 = add i32 %0, %div526.neg
  %div332 = sdiv i32 %5, 2
  %sub330 = sub i32 %div332, %1
  %div469 = sdiv i32 %4, 2
  %sub467 = sub i32 %div469, %0
  %sub240 = add nsw i32 %div526.neg, -1
  %sub241 = add i32 %sub240, %0
  %sub109 = add nsw i32 %sub527, -1
  br i1 %cmp938, label %for.cond11.preheader.lr.ph, label %for.cond176.preheader

for.cond11.preheader.lr.ph:                       ; preds = %entry
  %cmp12901 = icmp sgt i32 %shr, 0
  %cmp55915 = icmp slt i32 %shr, %sub527
  %cmp72905 = icmp sgt i32 %4, 0
  %cmp112933.not = icmp sgt i32 %sub527, %0
  br label %for.cond11.preheader

for.cond11.preheader:                             ; preds = %for.cond.cleanup113, %for.cond11.preheader.lr.ph
  %y.0940 = phi i32 [ 0, %for.cond11.preheader.lr.ph ], [ %inc173, %for.cond.cleanup113 ]
  %i_pos.0939 = phi i32 [ 0, %for.cond11.preheader.lr.ph ], [ %add171, %for.cond.cleanup113 ]
  %sub16 = sub nsw i32 %shr7, %y.0940
  %mul42 = mul nsw i32 %12, %y.0940
  %cmp19895 = icmp slt i32 %sub16, %5
  %mul44 = mul nsw i32 %mul42, %11
  %invariant.gep = getelementptr float, ptr %3, i32 %mul44
  br i1 %cmp12901, label %for.body14.lr.ph, label %for.cond51.preheader

for.body14.lr.ph:                                 ; preds = %for.cond11.preheader
  br label %for.body14

for.cond176.preheader:                            ; preds = %for.cond.cleanup113, %entry
  %div179.neg = sdiv i32 %5, -2
  %sub180 = add i32 %1, %div179.neg
  %cmp181973 = icmp slt i32 %shr7, %sub180
  br i1 %cmp181973, label %for.cond186.preheader.lr.ph, label %for.cond311.preheader

for.cond186.preheader.lr.ph:                      ; preds = %for.cond176.preheader
  %cmp187951 = icmp sgt i32 %shr, 0
  %cmp197945 = icmp sgt i32 %5, 0
  %cmp244967 = icmp slt i32 %sub241, %0
  br label %for.cond186.preheader

for.cond51.preheader:                             ; preds = %for.cond.cleanup20, %for.cond11.preheader
  %i_pos_y.0.lcssa = phi i32 [ %i_pos.0939, %for.cond11.preheader ], [ %add38, %for.cond.cleanup20 ]
  br i1 %cmp55915, label %for.body57.lr.ph, label %for.cond.cleanup56

for.body57.lr.ph:                                 ; preds = %for.cond51.preheader
  br label %for.body57

for.body14:                                       ; preds = %for.cond.cleanup20, %for.body14.lr.ph
  %x.0903 = phi i32 [ 0, %for.body14.lr.ph ], [ %inc48, %for.cond.cleanup20 ]
  %i_pos_y.0902 = phi i32 [ %i_pos.0939, %for.body14.lr.ph ], [ %add38, %for.cond.cleanup20 ]
  %sub22 = sub nsw i32 %shr, %x.0903
  %cmp25892 = icmp slt i32 %sub22, %4
  br i1 %cmp19895, label %for.body21.lr.ph, label %for.cond.cleanup20

for.body21.lr.ph:                                 ; preds = %for.body14
  br label %for.body21

for.cond.cleanup20:                               ; preds = %for.cond.cleanup26, %for.body14
  %acc.0.lcssa = phi float [ 0.000000e+00, %for.body14 ], [ %acc.1.lcssa, %for.cond.cleanup26 ]
  %add38 = add nsw i32 %14, %i_pos_y.0902
  %mul40 = mul nsw i32 %13, %x.0903
  %gep = getelementptr float, ptr %invariant.gep, i32 %mul40
  store float %acc.0.lcssa, ptr %gep, align 4
  %inc48 = add nuw nsw i32 %x.0903, 1
  %exitcond.not = icmp eq i32 %inc48, %shr
  br i1 %exitcond.not, label %for.cond51.preheader, label %for.body14

for.body21:                                       ; preds = %for.cond.cleanup26, %for.body21.lr.ph
  %m.0899 = phi i32 [ %sub16, %for.body21.lr.ph ], [ %inc35, %for.cond.cleanup26 ]
  %f_data.0898 = phi ptr [ %15, %for.body21.lr.ph ], [ %add.ptr, %for.cond.cleanup26 ]
  %acc.0897 = phi float [ 0.000000e+00, %for.body21.lr.ph ], [ %acc.1.lcssa, %for.cond.cleanup26 ]
  %i_pos_x.0896 = phi i32 [ %i_pos_y.0902, %for.body21.lr.ph ], [ %add33, %for.cond.cleanup26 ]
  %16 = getelementptr float, ptr %2, i32 %i_pos_x.0896
  br i1 %cmp25892, label %for.body27.lr.ph, label %for.cond.cleanup26

for.body27.lr.ph:                                 ; preds = %for.body21
  br label %for.body27

for.cond.cleanup26:                               ; preds = %for.body27, %for.body21
  %acc.1.lcssa = phi float [ %acc.0897, %for.body21 ], [ %19, %for.body27 ]
  %add.ptr = getelementptr inbounds float, ptr %f_data.0898, i32 %mul10
  %add33 = add nsw i32 %i_pos_x.0896, %mul
  %inc35 = add nsw i32 %m.0899, 1
  %cmp19 = icmp slt i32 %inc35, %5
  br i1 %cmp19, label %for.body21, label %for.cond.cleanup20

for.body27:                                       ; preds = %for.body27, %for.body27.lr.ph
  %n.0894 = phi i32 [ %sub22, %for.body27.lr.ph ], [ %inc, %for.body27 ]
  %acc.1893 = phi float [ %acc.0897, %for.body27.lr.ph ], [ %19, %for.body27 ]
  %mul28 = mul nsw i32 %14, %n.0894
  %arrayidx = getelementptr float, ptr %16, i32 %mul28
  %17 = load float, ptr %arrayidx, align 4
  %mul30 = mul nsw i32 %10, %n.0894
  %arrayidx31 = getelementptr inbounds float, ptr %f_data.0898, i32 %mul30
  %18 = load float, ptr %arrayidx31, align 4
  %19 = tail call float @llvm.fmuladd.f32(float %17, float %18, float %acc.1893)
  %inc = add nsw i32 %n.0894, 1
  %cmp25 = icmp slt i32 %inc, %4
  br i1 %cmp25, label %for.body27, label %for.cond.cleanup26

for.cond.cleanup56:                               ; preds = %for.cond.cleanup67, %for.cond51.preheader
  %i_pos_y.1.lcssa = phi i32 [ %i_pos_y.0.lcssa, %for.cond51.preheader ], [ %add92, %for.cond.cleanup67 ]
  br i1 %cmp112933.not, label %for.cond.cleanup113, label %for.body114.lr.ph

for.body114.lr.ph:                                ; preds = %for.cond.cleanup56
  br label %for.body114

for.body57:                                       ; preds = %for.cond.cleanup67, %for.body57.lr.ph
  %x50.0917 = phi i32 [ %shr, %for.body57.lr.ph ], [ %inc102, %for.cond.cleanup67 ]
  %i_pos_y.1916 = phi i32 [ %i_pos_y.0.lcssa, %for.body57.lr.ph ], [ %add92, %for.cond.cleanup67 ]
  br i1 %cmp19895, label %for.cond70.preheader, label %for.cond.cleanup67

for.cond70.preheader:                             ; preds = %for.body57, %for.cond.cleanup73
  %m62.0913 = phi i32 [ %inc89, %for.cond.cleanup73 ], [ %sub16, %for.body57 ]
  %f_data60.0912 = phi ptr [ %add.ptr86, %for.cond.cleanup73 ], [ %15, %for.body57 ]
  %acc59.0911 = phi float [ %acc59.1.lcssa, %for.cond.cleanup73 ], [ 0.000000e+00, %for.body57 ]
  %i_pos_x58.0910 = phi i32 [ %add87, %for.cond.cleanup73 ], [ %i_pos_y.1916, %for.body57 ]
  %20 = getelementptr float, ptr %2, i32 %i_pos_x58.0910
  br i1 %cmp72905, label %for.body74.lr.ph, label %for.cond.cleanup73

for.body74.lr.ph:                                 ; preds = %for.cond70.preheader
  br label %for.body74

for.cond.cleanup67:                               ; preds = %for.cond.cleanup73, %for.body57
  %acc59.0.lcssa = phi float [ 0.000000e+00, %for.body57 ], [ %acc59.1.lcssa, %for.cond.cleanup73 ]
  %add92 = add nsw i32 %14, %i_pos_y.1916
  %mul94 = mul nsw i32 %13, %x50.0917
  %gep922 = getelementptr float, ptr %invariant.gep, i32 %mul94
  store float %acc59.0.lcssa, ptr %gep922, align 4
  %inc102 = add nsw i32 %x50.0917, 1
  %exitcond1058.not = icmp eq i32 %inc102, %sub527
  br i1 %exitcond1058.not, label %for.cond.cleanup56, label %for.body57

for.cond.cleanup73:                               ; preds = %for.body74, %for.cond70.preheader
  %acc59.1.lcssa = phi float [ %acc59.0911, %for.cond70.preheader ], [ %23, %for.body74 ]
  %add.ptr86 = getelementptr inbounds float, ptr %f_data60.0912, i32 %mul10
  %add87 = add nsw i32 %i_pos_x58.0910, %mul
  %inc89 = add nsw i32 %m62.0913, 1
  %cmp66 = icmp slt i32 %inc89, %5
  br i1 %cmp66, label %for.cond70.preheader, label %for.cond.cleanup67

for.body74:                                       ; preds = %for.body74, %for.body74.lr.ph
  %n69.0907 = phi i32 [ 0, %for.body74.lr.ph ], [ %inc84, %for.body74 ]
  %acc59.1906 = phi float [ %acc59.0911, %for.body74.lr.ph ], [ %23, %for.body74 ]
  %mul76 = mul nsw i32 %14, %n69.0907
  %arrayidx78 = getelementptr float, ptr %20, i32 %mul76
  %21 = load float, ptr %arrayidx78, align 4
  %mul80 = mul nsw i32 %10, %n69.0907
  %arrayidx81 = getelementptr inbounds float, ptr %f_data60.0912, i32 %mul80
  %22 = load float, ptr %arrayidx81, align 4
  %23 = tail call float @llvm.fmuladd.f32(float %21, float %22, float %acc59.1906)
  %inc84 = add nuw nsw i32 %n69.0907, 1
  %exitcond1057.not = icmp eq i32 %inc84, %4
  br i1 %exitcond1057.not, label %for.cond.cleanup73, label %for.body74

for.cond.cleanup113:                              ; preds = %for.cond.cleanup124, %for.cond.cleanup56
  %add171 = add nsw i32 %i_pos.0939, %mul
  %inc173 = add nuw nsw i32 %y.0940, 1
  %exitcond1060.not = icmp eq i32 %inc173, %shr7
  br i1 %exitcond1060.not, label %for.cond176.preheader, label %for.cond11.preheader

for.body114:                                      ; preds = %for.cond.cleanup124, %for.body114.lr.ph
  %x104.0935 = phi i32 [ %sub109, %for.body114.lr.ph ], [ %inc166, %for.cond.cleanup124 ]
  %i_pos_y.2934 = phi i32 [ %i_pos_y.1.lcssa, %for.body114.lr.ph ], [ %add156, %for.cond.cleanup124 ]
  %add133 = add i32 %sub467, %x104.0935
  %add134.neg = xor i32 %add133, -1
  %sub135 = add i32 %4, %add134.neg
  %cmp136923 = icmp sgt i32 %sub135, 0
  br i1 %cmp19895, label %for.cond127.preheader.lr.ph, label %for.cond.cleanup124

for.cond127.preheader.lr.ph:                      ; preds = %for.body114
  br label %for.cond127.preheader

for.cond127.preheader:                            ; preds = %for.cond.cleanup137, %for.cond127.preheader.lr.ph
  %m119.0931 = phi i32 [ %sub16, %for.cond127.preheader.lr.ph ], [ %inc153, %for.cond.cleanup137 ]
  %f_data117.0930 = phi ptr [ %15, %for.cond127.preheader.lr.ph ], [ %add.ptr150, %for.cond.cleanup137 ]
  %acc116.0929 = phi float [ 0.000000e+00, %for.cond127.preheader.lr.ph ], [ %acc116.1.lcssa, %for.cond.cleanup137 ]
  %i_pos_x115.0928 = phi i32 [ %i_pos_y.2934, %for.cond127.preheader.lr.ph ], [ %add151, %for.cond.cleanup137 ]
  %24 = getelementptr float, ptr %2, i32 %i_pos_x115.0928
  br i1 %cmp136923, label %for.body138.lr.ph, label %for.cond.cleanup137

for.body138.lr.ph:                                ; preds = %for.cond127.preheader
  br label %for.body138

for.cond.cleanup124:                              ; preds = %for.cond.cleanup137, %for.body114
  %acc116.0.lcssa = phi float [ 0.000000e+00, %for.body114 ], [ %acc116.1.lcssa, %for.cond.cleanup137 ]
  %add156 = add nsw i32 %14, %i_pos_y.2934
  %mul158 = mul nsw i32 %13, %x104.0935
  %gep937 = getelementptr float, ptr %invariant.gep, i32 %mul158
  store float %acc116.0.lcssa, ptr %gep937, align 4
  %inc166 = add nsw i32 %x104.0935, 1
  %exitcond1059.not = icmp eq i32 %inc166, %0
  br i1 %exitcond1059.not, label %for.cond.cleanup113, label %for.body114

for.cond.cleanup137:                              ; preds = %for.body138, %for.cond127.preheader
  %acc116.1.lcssa = phi float [ %acc116.0929, %for.cond127.preheader ], [ %27, %for.body138 ]
  %add.ptr150 = getelementptr inbounds float, ptr %f_data117.0930, i32 %mul10
  %add151 = add nsw i32 %i_pos_x115.0928, %mul
  %inc153 = add nsw i32 %m119.0931, 1
  %cmp123 = icmp slt i32 %inc153, %5
  br i1 %cmp123, label %for.cond127.preheader, label %for.cond.cleanup124

for.body138:                                      ; preds = %for.body138, %for.body138.lr.ph
  %n126.0925 = phi i32 [ 0, %for.body138.lr.ph ], [ %inc148, %for.body138 ]
  %acc116.1924 = phi float [ %acc116.0929, %for.body138.lr.ph ], [ %27, %for.body138 ]
  %mul140 = mul nsw i32 %14, %n126.0925
  %arrayidx142 = getelementptr float, ptr %24, i32 %mul140
  %25 = load float, ptr %arrayidx142, align 4
  %mul144 = mul nsw i32 %10, %n126.0925
  %arrayidx145 = getelementptr inbounds float, ptr %f_data117.0930, i32 %mul144
  %26 = load float, ptr %arrayidx145, align 4
  %27 = tail call float @llvm.fmuladd.f32(float %25, float %26, float %acc116.1924)
  %inc148 = add nuw nsw i32 %n126.0925, 1
  %cmp136 = icmp slt i32 %inc148, %sub135
  br i1 %cmp136, label %for.body138, label %for.cond.cleanup137

for.cond186.preheader:                            ; preds = %for.cond.cleanup245, %for.cond186.preheader.lr.ph
  %y175.0975 = phi i32 [ %shr7, %for.cond186.preheader.lr.ph ], [ %inc304, %for.cond.cleanup245 ]
  %i_pos.1974 = phi i32 [ 0, %for.cond186.preheader.lr.ph ], [ %add302, %for.cond.cleanup245 ]
  %mul228 = mul nsw i32 %12, %y175.0975
  %mul230 = mul nsw i32 %mul228, %11
  %invariant.gep955 = getelementptr float, ptr %3, i32 %mul230
  br i1 %cmp187951, label %for.body189.lr.ph, label %for.cond.cleanup188

for.body189.lr.ph:                                ; preds = %for.cond186.preheader
  br label %for.body189

for.cond311.preheader:                            ; preds = %for.cond.cleanup245, %for.cond176.preheader
  %cmp3131028 = icmp slt i32 %sub180, %1
  br i1 %cmp3131028, label %for.cond318.preheader.lr.ph, label %for.cond513.preheader

for.cond318.preheader.lr.ph:                      ; preds = %for.cond311.preheader
  %cmp319989 = icmp sgt i32 %shr, 0
  %cmp3811005 = icmp slt i32 %shr, %sub527
  %cmp404995 = icmp sgt i32 %4, 0
  %cmp4431023 = icmp slt i32 %sub527, %0
  br label %for.cond318.preheader

for.cond.cleanup188:                              ; preds = %for.cond.cleanup198, %for.cond186.preheader
  %i_pos_y184.0.lcssa = phi i32 [ %i_pos.1974, %for.cond186.preheader ], [ %add224, %for.cond.cleanup198 ]
  br i1 %cmp244967, label %for.body246.lr.ph, label %for.cond.cleanup245

for.body246.lr.ph:                                ; preds = %for.cond.cleanup188
  br label %for.body246

for.body189:                                      ; preds = %for.cond.cleanup198, %for.body189.lr.ph
  %x185.0953 = phi i32 [ 0, %for.body189.lr.ph ], [ %inc234, %for.cond.cleanup198 ]
  %i_pos_y184.0952 = phi i32 [ %i_pos.1974, %for.body189.lr.ph ], [ %add224, %for.cond.cleanup198 ]
  %sub201 = sub nsw i32 %shr, %x185.0953
  %cmp204941 = icmp slt i32 %sub201, %4
  br i1 %cmp197945, label %for.body199.lr.ph, label %for.cond.cleanup198

for.body199.lr.ph:                                ; preds = %for.body189
  br label %for.body199

for.cond.cleanup198:                              ; preds = %for.cond.cleanup205, %for.body189
  %acc191.0.lcssa = phi float [ 0.000000e+00, %for.body189 ], [ %acc191.1.lcssa, %for.cond.cleanup205 ]
  %add224 = add nsw i32 %14, %i_pos_y184.0952
  %mul226 = mul nsw i32 %13, %x185.0953
  %gep956 = getelementptr float, ptr %invariant.gep955, i32 %mul226
  store float %acc191.0.lcssa, ptr %gep956, align 4
  %inc234 = add nuw nsw i32 %x185.0953, 1
  %exitcond1062.not = icmp eq i32 %inc234, %shr
  br i1 %exitcond1062.not, label %for.cond.cleanup188, label %for.body189

for.body199:                                      ; preds = %for.cond.cleanup205, %for.body199.lr.ph
  %m194.0949 = phi i32 [ 0, %for.body199.lr.ph ], [ %inc221, %for.cond.cleanup205 ]
  %f_data192.0948 = phi ptr [ %15, %for.body199.lr.ph ], [ %add.ptr218, %for.cond.cleanup205 ]
  %acc191.0947 = phi float [ 0.000000e+00, %for.body199.lr.ph ], [ %acc191.1.lcssa, %for.cond.cleanup205 ]
  %i_pos_x190.0946 = phi i32 [ %i_pos_y184.0952, %for.body199.lr.ph ], [ %add219, %for.cond.cleanup205 ]
  %28 = getelementptr float, ptr %2, i32 %i_pos_x190.0946
  br i1 %cmp204941, label %for.body206.lr.ph, label %for.cond.cleanup205

for.body206.lr.ph:                                ; preds = %for.body199
  br label %for.body206

for.cond.cleanup205:                              ; preds = %for.body206, %for.body199
  %acc191.1.lcssa = phi float [ %acc191.0947, %for.body199 ], [ %31, %for.body206 ]
  %add.ptr218 = getelementptr inbounds float, ptr %f_data192.0948, i32 %mul10
  %add219 = add nsw i32 %i_pos_x190.0946, %mul
  %inc221 = add nuw nsw i32 %m194.0949, 1
  %exitcond1061.not = icmp eq i32 %inc221, %5
  br i1 %exitcond1061.not, label %for.cond.cleanup198, label %for.body199

for.body206:                                      ; preds = %for.body206, %for.body206.lr.ph
  %n200.0943 = phi i32 [ %sub201, %for.body206.lr.ph ], [ %inc216, %for.body206 ]
  %acc191.1942 = phi float [ %acc191.0947, %for.body206.lr.ph ], [ %31, %for.body206 ]
  %mul208 = mul nsw i32 %14, %n200.0943
  %arrayidx210 = getelementptr float, ptr %28, i32 %mul208
  %29 = load float, ptr %arrayidx210, align 4
  %mul212 = mul nsw i32 %10, %n200.0943
  %arrayidx213 = getelementptr inbounds float, ptr %f_data192.0948, i32 %mul212
  %30 = load float, ptr %arrayidx213, align 4
  %31 = tail call float @llvm.fmuladd.f32(float %29, float %30, float %acc191.1942)
  %inc216 = add nsw i32 %n200.0943, 1
  %cmp204 = icmp slt i32 %inc216, %4
  br i1 %cmp204, label %for.body206, label %for.cond.cleanup205

for.cond.cleanup245:                              ; preds = %for.cond.cleanup255, %for.cond.cleanup188
  %add302 = add nsw i32 %i_pos.1974, %mul
  %inc304 = add nsw i32 %y175.0975, 1
  %exitcond1065.not = icmp eq i32 %inc304, %sub180
  br i1 %exitcond1065.not, label %for.cond311.preheader, label %for.cond186.preheader

for.body246:                                      ; preds = %for.cond.cleanup255, %for.body246.lr.ph
  %x236.0969 = phi i32 [ %sub241, %for.body246.lr.ph ], [ %inc297, %for.cond.cleanup255 ]
  %i_pos_y184.1968 = phi i32 [ %i_pos_y184.0.lcssa, %for.body246.lr.ph ], [ %add287, %for.cond.cleanup255 ]
  %add264 = add i32 %sub467, %x236.0969
  %add265.neg = xor i32 %add264, -1
  %sub266 = add i32 %4, %add265.neg
  %cmp267957 = icmp sgt i32 %sub266, 0
  br i1 %cmp197945, label %for.cond258.preheader.lr.ph, label %for.cond.cleanup255

for.cond258.preheader.lr.ph:                      ; preds = %for.body246
  br label %for.cond258.preheader

for.cond258.preheader:                            ; preds = %for.cond.cleanup268, %for.cond258.preheader.lr.ph
  %m251.0965 = phi i32 [ 0, %for.cond258.preheader.lr.ph ], [ %inc284, %for.cond.cleanup268 ]
  %f_data249.0964 = phi ptr [ %15, %for.cond258.preheader.lr.ph ], [ %add.ptr281, %for.cond.cleanup268 ]
  %acc248.0963 = phi float [ 0.000000e+00, %for.cond258.preheader.lr.ph ], [ %acc248.1.lcssa, %for.cond.cleanup268 ]
  %i_pos_x247.0962 = phi i32 [ %i_pos_y184.1968, %for.cond258.preheader.lr.ph ], [ %add282, %for.cond.cleanup268 ]
  %32 = getelementptr float, ptr %2, i32 %i_pos_x247.0962
  br i1 %cmp267957, label %for.body269.lr.ph, label %for.cond.cleanup268

for.body269.lr.ph:                                ; preds = %for.cond258.preheader
  br label %for.body269

for.cond.cleanup255:                              ; preds = %for.cond.cleanup268, %for.body246
  %acc248.0.lcssa = phi float [ 0.000000e+00, %for.body246 ], [ %acc248.1.lcssa, %for.cond.cleanup268 ]
  %add287 = add nsw i32 %14, %i_pos_y184.1968
  %mul289 = mul nsw i32 %13, %x236.0969
  %gep971 = getelementptr float, ptr %invariant.gep955, i32 %mul289
  store float %acc248.0.lcssa, ptr %gep971, align 4
  %inc297 = add nsw i32 %x236.0969, 1
  %exitcond1064.not = icmp eq i32 %inc297, %0
  br i1 %exitcond1064.not, label %for.cond.cleanup245, label %for.body246

for.cond.cleanup268:                              ; preds = %for.body269, %for.cond258.preheader
  %acc248.1.lcssa = phi float [ %acc248.0963, %for.cond258.preheader ], [ %35, %for.body269 ]
  %add.ptr281 = getelementptr inbounds float, ptr %f_data249.0964, i32 %mul10
  %add282 = add nsw i32 %i_pos_x247.0962, %mul
  %inc284 = add nuw nsw i32 %m251.0965, 1
  %exitcond1063.not = icmp eq i32 %inc284, %5
  br i1 %exitcond1063.not, label %for.cond.cleanup255, label %for.cond258.preheader

for.body269:                                      ; preds = %for.body269, %for.body269.lr.ph
  %n257.0959 = phi i32 [ 0, %for.body269.lr.ph ], [ %inc279, %for.body269 ]
  %acc248.1958 = phi float [ %acc248.0963, %for.body269.lr.ph ], [ %35, %for.body269 ]
  %mul271 = mul nsw i32 %14, %n257.0959
  %arrayidx273 = getelementptr float, ptr %32, i32 %mul271
  %33 = load float, ptr %arrayidx273, align 4
  %mul275 = mul nsw i32 %10, %n257.0959
  %arrayidx276 = getelementptr inbounds float, ptr %f_data249.0964, i32 %mul275
  %34 = load float, ptr %arrayidx276, align 4
  %35 = tail call float @llvm.fmuladd.f32(float %33, float %34, float %acc248.1958)
  %inc279 = add nuw nsw i32 %n257.0959, 1
  %cmp267 = icmp slt i32 %inc279, %sub266
  br i1 %cmp267, label %for.body269, label %for.cond.cleanup268

for.cond318.preheader:                            ; preds = %for.cond.cleanup444, %for.cond318.preheader.lr.ph
  %y306.01030 = phi i32 [ %sub180, %for.cond318.preheader.lr.ph ], [ %inc510, %for.cond.cleanup444 ]
  %i_pos.21029 = phi i32 [ 0, %for.cond318.preheader.lr.ph ], [ %add508, %for.cond.cleanup444 ]
  %add333 = add i32 %sub330, %y306.01030
  %mul367 = mul nsw i32 %12, %y306.01030
  %add334.neg = xor i32 %add333, -1
  %mul369 = mul nsw i32 %mul367, %11
  %sub335 = add i32 %5, %add334.neg
  %invariant.gep993 = getelementptr float, ptr %3, i32 %mul369
  %cmp336983 = icmp sgt i32 %sub335, 0
  br i1 %cmp319989, label %for.body321.lr.ph, label %for.cond376.preheader

for.body321.lr.ph:                                ; preds = %for.cond318.preheader
  br label %for.body321

for.cond513.preheader:                            ; preds = %for.cond.cleanup444, %for.cond311.preheader
  br i1 %cmp181973, label %for.cond523.preheader.lr.ph, label %for.cond.cleanup519

for.cond523.preheader.lr.ph:                      ; preds = %for.cond513.preheader
  %cmp5281041 = icmp slt i32 %shr, %sub527
  %cmp5381035 = icmp sgt i32 %5, 0
  %cmp5441031 = icmp sgt i32 %4, 0
  br label %for.cond523.preheader

for.cond376.preheader:                            ; preds = %for.cond.cleanup337, %for.cond318.preheader
  %i_pos_y316.0.lcssa = phi i32 [ %i_pos.21029, %for.cond318.preheader ], [ %add363, %for.cond.cleanup337 ]
  br i1 %cmp3811005, label %for.body383.lr.ph, label %for.cond441.preheader

for.body383.lr.ph:                                ; preds = %for.cond376.preheader
  br label %for.body383

for.body321:                                      ; preds = %for.cond.cleanup337, %for.body321.lr.ph
  %x317.0991 = phi i32 [ 0, %for.body321.lr.ph ], [ %inc373, %for.cond.cleanup337 ]
  %i_pos_y316.0990 = phi i32 [ %i_pos.21029, %for.body321.lr.ph ], [ %add363, %for.cond.cleanup337 ]
  %sub340 = sub nsw i32 %shr, %x317.0991
  %cmp343979 = icmp slt i32 %sub340, %4
  br i1 %cmp336983, label %for.body338.lr.ph, label %for.cond.cleanup337

for.body338.lr.ph:                                ; preds = %for.body321
  br label %for.body338

for.cond.cleanup337:                              ; preds = %for.cond.cleanup344, %for.body321
  %acc323.0.lcssa = phi float [ 0.000000e+00, %for.body321 ], [ %acc323.1.lcssa, %for.cond.cleanup344 ]
  %add363 = add nsw i32 %14, %i_pos_y316.0990
  %mul365 = mul nsw i32 %13, %x317.0991
  %gep994 = getelementptr float, ptr %invariant.gep993, i32 %mul365
  store float %acc323.0.lcssa, ptr %gep994, align 4
  %inc373 = add nuw nsw i32 %x317.0991, 1
  %exitcond1066.not = icmp eq i32 %inc373, %shr
  br i1 %exitcond1066.not, label %for.cond376.preheader, label %for.body321

for.body338:                                      ; preds = %for.cond.cleanup344, %for.body338.lr.ph
  %m326.0987 = phi i32 [ 0, %for.body338.lr.ph ], [ %inc360, %for.cond.cleanup344 ]
  %f_data324.0986 = phi ptr [ %15, %for.body338.lr.ph ], [ %add.ptr357, %for.cond.cleanup344 ]
  %acc323.0985 = phi float [ 0.000000e+00, %for.body338.lr.ph ], [ %acc323.1.lcssa, %for.cond.cleanup344 ]
  %i_pos_x322.0984 = phi i32 [ %i_pos_y316.0990, %for.body338.lr.ph ], [ %add358, %for.cond.cleanup344 ]
  %36 = getelementptr float, ptr %2, i32 %i_pos_x322.0984
  br i1 %cmp343979, label %for.body345.lr.ph, label %for.cond.cleanup344

for.body345.lr.ph:                                ; preds = %for.body338
  br label %for.body345

for.cond.cleanup344:                              ; preds = %for.body345, %for.body338
  %acc323.1.lcssa = phi float [ %acc323.0985, %for.body338 ], [ %39, %for.body345 ]
  %add.ptr357 = getelementptr inbounds float, ptr %f_data324.0986, i32 %mul10
  %add358 = add nsw i32 %i_pos_x322.0984, %mul
  %inc360 = add nuw nsw i32 %m326.0987, 1
  %cmp336 = icmp slt i32 %inc360, %sub335
  br i1 %cmp336, label %for.body338, label %for.cond.cleanup337

for.body345:                                      ; preds = %for.body345, %for.body345.lr.ph
  %n339.0981 = phi i32 [ %sub340, %for.body345.lr.ph ], [ %inc355, %for.body345 ]
  %acc323.1980 = phi float [ %acc323.0985, %for.body345.lr.ph ], [ %39, %for.body345 ]
  %mul347 = mul nsw i32 %14, %n339.0981
  %arrayidx349 = getelementptr float, ptr %36, i32 %mul347
  %37 = load float, ptr %arrayidx349, align 4
  %mul351 = mul nsw i32 %10, %n339.0981
  %arrayidx352 = getelementptr inbounds float, ptr %f_data324.0986, i32 %mul351
  %38 = load float, ptr %arrayidx352, align 4
  %39 = tail call float @llvm.fmuladd.f32(float %37, float %38, float %acc323.1980)
  %inc355 = add nsw i32 %n339.0981, 1
  %cmp343 = icmp slt i32 %inc355, %4
  br i1 %cmp343, label %for.body345, label %for.cond.cleanup344

for.cond441.preheader:                            ; preds = %for.cond.cleanup399, %for.cond376.preheader
  %i_pos_y316.1.lcssa = phi i32 [ %i_pos_y316.0.lcssa, %for.cond376.preheader ], [ %add424, %for.cond.cleanup399 ]
  br i1 %cmp4431023, label %for.body445.lr.ph, label %for.cond.cleanup444

for.body445.lr.ph:                                ; preds = %for.cond441.preheader
  br label %for.body445

for.body383:                                      ; preds = %for.cond.cleanup399, %for.body383.lr.ph
  %x375.01007 = phi i32 [ %shr, %for.body383.lr.ph ], [ %inc434, %for.cond.cleanup399 ]
  %i_pos_y316.11006 = phi i32 [ %i_pos_y316.0.lcssa, %for.body383.lr.ph ], [ %add424, %for.cond.cleanup399 ]
  br i1 %cmp336983, label %for.cond402.preheader, label %for.cond.cleanup399

for.cond402.preheader:                            ; preds = %for.body383, %for.cond.cleanup405
  %m388.01003 = phi i32 [ %inc421, %for.cond.cleanup405 ], [ 0, %for.body383 ]
  %f_data386.01002 = phi ptr [ %add.ptr418, %for.cond.cleanup405 ], [ %15, %for.body383 ]
  %acc385.01001 = phi float [ %acc385.1.lcssa, %for.cond.cleanup405 ], [ 0.000000e+00, %for.body383 ]
  %i_pos_x384.01000 = phi i32 [ %add419, %for.cond.cleanup405 ], [ %i_pos_y316.11006, %for.body383 ]
  %40 = getelementptr float, ptr %2, i32 %i_pos_x384.01000
  br i1 %cmp404995, label %for.body406.lr.ph, label %for.cond.cleanup405

for.body406.lr.ph:                                ; preds = %for.cond402.preheader
  br label %for.body406

for.cond.cleanup399:                              ; preds = %for.cond.cleanup405, %for.body383
  %acc385.0.lcssa = phi float [ 0.000000e+00, %for.body383 ], [ %acc385.1.lcssa, %for.cond.cleanup405 ]
  %add424 = add nsw i32 %14, %i_pos_y316.11006
  %mul426 = mul nsw i32 %13, %x375.01007
  %gep1012 = getelementptr float, ptr %invariant.gep993, i32 %mul426
  store float %acc385.0.lcssa, ptr %gep1012, align 4
  %inc434 = add nsw i32 %x375.01007, 1
  %exitcond1068.not = icmp eq i32 %inc434, %sub527
  br i1 %exitcond1068.not, label %for.cond441.preheader, label %for.body383

for.cond.cleanup405:                              ; preds = %for.body406, %for.cond402.preheader
  %acc385.1.lcssa = phi float [ %acc385.01001, %for.cond402.preheader ], [ %43, %for.body406 ]
  %add.ptr418 = getelementptr inbounds float, ptr %f_data386.01002, i32 %mul10
  %add419 = add nsw i32 %i_pos_x384.01000, %mul
  %inc421 = add nuw nsw i32 %m388.01003, 1
  %cmp398 = icmp slt i32 %inc421, %sub335
  br i1 %cmp398, label %for.cond402.preheader, label %for.cond.cleanup399

for.body406:                                      ; preds = %for.body406, %for.body406.lr.ph
  %n401.0997 = phi i32 [ 0, %for.body406.lr.ph ], [ %inc416, %for.body406 ]
  %acc385.1996 = phi float [ %acc385.01001, %for.body406.lr.ph ], [ %43, %for.body406 ]
  %mul408 = mul nsw i32 %14, %n401.0997
  %arrayidx410 = getelementptr float, ptr %40, i32 %mul408
  %41 = load float, ptr %arrayidx410, align 4
  %mul412 = mul nsw i32 %10, %n401.0997
  %arrayidx413 = getelementptr inbounds float, ptr %f_data386.01002, i32 %mul412
  %42 = load float, ptr %arrayidx413, align 4
  %43 = tail call float @llvm.fmuladd.f32(float %41, float %42, float %acc385.1996)
  %inc416 = add nuw nsw i32 %n401.0997, 1
  %exitcond1067.not = icmp eq i32 %inc416, %4
  br i1 %exitcond1067.not, label %for.cond.cleanup405, label %for.body406

for.cond.cleanup444:                              ; preds = %for.cond.cleanup461, %for.cond441.preheader
  %add508 = add nsw i32 %i_pos.21029, %mul
  %inc510 = add nsw i32 %y306.01030, 1
  %exitcond1070.not = icmp eq i32 %inc510, %1
  br i1 %exitcond1070.not, label %for.cond513.preheader, label %for.cond318.preheader

for.body445:                                      ; preds = %for.cond.cleanup461, %for.body445.lr.ph
  %x436.01025 = phi i32 [ %sub527, %for.body445.lr.ph ], [ %inc503, %for.cond.cleanup461 ]
  %i_pos_y316.21024 = phi i32 [ %i_pos_y316.1.lcssa, %for.body445.lr.ph ], [ %add493, %for.cond.cleanup461 ]
  %add470 = add i32 %sub467, %x436.01025
  %add471.neg = xor i32 %add470, -1
  %sub472 = add i32 %4, %add471.neg
  %cmp4731013 = icmp sgt i32 %sub472, 0
  br i1 %cmp336983, label %for.cond464.preheader.lr.ph, label %for.cond.cleanup461

for.cond464.preheader.lr.ph:                      ; preds = %for.body445
  br label %for.cond464.preheader

for.cond464.preheader:                            ; preds = %for.cond.cleanup474, %for.cond464.preheader.lr.ph
  %m450.01021 = phi i32 [ 0, %for.cond464.preheader.lr.ph ], [ %inc490, %for.cond.cleanup474 ]
  %f_data448.01020 = phi ptr [ %15, %for.cond464.preheader.lr.ph ], [ %add.ptr487, %for.cond.cleanup474 ]
  %acc447.01019 = phi float [ 0.000000e+00, %for.cond464.preheader.lr.ph ], [ %acc447.1.lcssa, %for.cond.cleanup474 ]
  %i_pos_x446.01018 = phi i32 [ %i_pos_y316.21024, %for.cond464.preheader.lr.ph ], [ %add488, %for.cond.cleanup474 ]
  %44 = getelementptr float, ptr %2, i32 %i_pos_x446.01018
  br i1 %cmp4731013, label %for.body475.lr.ph, label %for.cond.cleanup474

for.body475.lr.ph:                                ; preds = %for.cond464.preheader
  br label %for.body475

for.cond.cleanup461:                              ; preds = %for.cond.cleanup474, %for.body445
  %acc447.0.lcssa = phi float [ 0.000000e+00, %for.body445 ], [ %acc447.1.lcssa, %for.cond.cleanup474 ]
  %add493 = add nsw i32 %14, %i_pos_y316.21024
  %mul495 = mul nsw i32 %13, %x436.01025
  %gep1027 = getelementptr float, ptr %invariant.gep993, i32 %mul495
  store float %acc447.0.lcssa, ptr %gep1027, align 4
  %inc503 = add nsw i32 %x436.01025, 1
  %exitcond1069.not = icmp eq i32 %inc503, %0
  br i1 %exitcond1069.not, label %for.cond.cleanup444, label %for.body445

for.cond.cleanup474:                              ; preds = %for.body475, %for.cond464.preheader
  %acc447.1.lcssa = phi float [ %acc447.01019, %for.cond464.preheader ], [ %47, %for.body475 ]
  %add.ptr487 = getelementptr inbounds float, ptr %f_data448.01020, i32 %mul10
  %add488 = add nsw i32 %i_pos_x446.01018, %mul
  %inc490 = add nuw nsw i32 %m450.01021, 1
  %cmp460 = icmp slt i32 %inc490, %sub335
  br i1 %cmp460, label %for.cond464.preheader, label %for.cond.cleanup461

for.body475:                                      ; preds = %for.body475, %for.body475.lr.ph
  %n463.01015 = phi i32 [ 0, %for.body475.lr.ph ], [ %inc485, %for.body475 ]
  %acc447.11014 = phi float [ %acc447.01019, %for.body475.lr.ph ], [ %47, %for.body475 ]
  %mul477 = mul nsw i32 %14, %n463.01015
  %arrayidx479 = getelementptr float, ptr %44, i32 %mul477
  %45 = load float, ptr %arrayidx479, align 4
  %mul481 = mul nsw i32 %10, %n463.01015
  %arrayidx482 = getelementptr inbounds float, ptr %f_data448.01020, i32 %mul481
  %46 = load float, ptr %arrayidx482, align 4
  %47 = tail call float @llvm.fmuladd.f32(float %45, float %46, float %acc447.11014)
  %inc485 = add nuw nsw i32 %n463.01015, 1
  %cmp473 = icmp slt i32 %inc485, %sub472
  br i1 %cmp473, label %for.body475, label %for.cond.cleanup474

for.cond523.preheader:                            ; preds = %for.cond.cleanup529, %for.cond523.preheader.lr.ph
  %y512.01048 = phi i32 [ %shr7, %for.cond523.preheader.lr.ph ], [ %inc581, %for.cond.cleanup529 ]
  %i_pos.31047 = phi i32 [ 0, %for.cond523.preheader.lr.ph ], [ %add579, %for.cond.cleanup529 ]
  %mul568 = mul nsw i32 %12, %y512.01048
  %mul570 = mul nsw i32 %mul568, %11
  %invariant.gep1044 = getelementptr float, ptr %3, i32 %mul570
  br i1 %cmp5281041, label %for.body530.lr.ph, label %for.cond.cleanup529

for.body530.lr.ph:                                ; preds = %for.cond523.preheader
  br label %for.body530

for.cond.cleanup519:                              ; preds = %for.cond.cleanup529, %for.cond513.preheader
  ret i32 0

for.cond.cleanup529:                              ; preds = %for.cond.cleanup539, %for.cond523.preheader
  %add579 = add nsw i32 %i_pos.31047, %mul
  %inc581 = add nsw i32 %y512.01048, 1
  %exitcond1074.not = icmp eq i32 %inc581, %sub180
  br i1 %exitcond1074.not, label %for.cond.cleanup519, label %for.cond523.preheader

for.body530:                                      ; preds = %for.cond.cleanup539, %for.body530.lr.ph
  %x522.01043 = phi i32 [ %shr, %for.body530.lr.ph ], [ %inc574, %for.cond.cleanup539 ]
  %i_pos_y521.01042 = phi i32 [ %i_pos.31047, %for.body530.lr.ph ], [ %add564, %for.cond.cleanup539 ]
  br i1 %cmp5381035, label %for.cond542.preheader, label %for.cond.cleanup539

for.cond542.preheader:                            ; preds = %for.body530, %for.cond.cleanup545
  %m535.01039 = phi i32 [ %inc561, %for.cond.cleanup545 ], [ 0, %for.body530 ]
  %f_data533.01038 = phi ptr [ %add.ptr558, %for.cond.cleanup545 ], [ %15, %for.body530 ]
  %acc532.01037 = phi float [ %acc532.1.lcssa, %for.cond.cleanup545 ], [ 0.000000e+00, %for.body530 ]
  %i_pos_x531.01036 = phi i32 [ %add559, %for.cond.cleanup545 ], [ %i_pos_y521.01042, %for.body530 ]
  %48 = getelementptr float, ptr %2, i32 %i_pos_x531.01036
  br i1 %cmp5441031, label %for.body546.lr.ph, label %for.cond.cleanup545

for.body546.lr.ph:                                ; preds = %for.cond542.preheader
  br label %for.body546

for.cond.cleanup539:                              ; preds = %for.cond.cleanup545, %for.body530
  %acc532.0.lcssa = phi float [ 0.000000e+00, %for.body530 ], [ %acc532.1.lcssa, %for.cond.cleanup545 ]
  %add564 = add nsw i32 %14, %i_pos_y521.01042
  %mul566 = mul nsw i32 %13, %x522.01043
  %gep1045 = getelementptr float, ptr %invariant.gep1044, i32 %mul566
  store float %acc532.0.lcssa, ptr %gep1045, align 4
  %inc574 = add nsw i32 %x522.01043, 1
  %exitcond1073.not = icmp eq i32 %inc574, %sub527
  br i1 %exitcond1073.not, label %for.cond.cleanup529, label %for.body530

for.cond.cleanup545:                              ; preds = %for.body546, %for.cond542.preheader
  %acc532.1.lcssa = phi float [ %acc532.01037, %for.cond542.preheader ], [ %51, %for.body546 ]
  %add.ptr558 = getelementptr inbounds float, ptr %f_data533.01038, i32 %mul10
  %add559 = add nsw i32 %i_pos_x531.01036, %mul
  %inc561 = add nuw nsw i32 %m535.01039, 1
  %exitcond1072.not = icmp eq i32 %inc561, %5
  br i1 %exitcond1072.not, label %for.cond.cleanup539, label %for.cond542.preheader

for.body546:                                      ; preds = %for.body546, %for.body546.lr.ph
  %n541.01033 = phi i32 [ 0, %for.body546.lr.ph ], [ %inc556, %for.body546 ]
  %acc532.11032 = phi float [ %acc532.01037, %for.body546.lr.ph ], [ %51, %for.body546 ]
  %mul548 = mul nsw i32 %14, %n541.01033
  %arrayidx550 = getelementptr float, ptr %48, i32 %mul548
  %49 = load float, ptr %arrayidx550, align 4
  %mul552 = mul nsw i32 %10, %n541.01033
  %arrayidx553 = getelementptr inbounds float, ptr %f_data533.01038, i32 %mul552
  %50 = load float, ptr %arrayidx553, align 4
  %51 = tail call float @llvm.fmuladd.f32(float %49, float %50, float %acc532.11032)
  %inc556 = add nuw nsw i32 %n541.01033, 1
  %exitcond1071.not = icmp eq i32 %inc556, %4
  br i1 %exitcond1071.not, label %for.cond.cleanup545, label %for.body546
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.fmuladd.f32(float, float, float)
