; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-loop-unroll-and-remainder -riscv-loop-unroll-and-remainder=true < %s | FileCheck %s

%struct.image2d_s = type { ptr, i32, i32, i32, i32, i32, i32 }

; Function Attrs: nofree norecurse nosync nounwind memory(read, argmem: readwrite, inaccessiblemem: none)
define dso_local noundef i32 @dspi_dotprod_f32_ansi(ptr nocapture noundef readonly %in_image, ptr nocapture noundef readonly %filter, ptr nocapture noundef writeonly %out_value, i32 noundef %count_x, i32 noundef %count_y) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dspi_dotprod_f32_ansi(
; CHECK-SAME: ptr noalias noundef readonly captures(none) [[IN_IMAGE:%.*]], ptr noalias noundef readonly captures(none) [[FILTER:%.*]], ptr noalias noundef writeonly captures(none) [[OUT_VALUE:%.*]], i32 noundef [[COUNT_X:%.*]], i32 noundef [[COUNT_Y:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[STEP_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 4
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[STEP_X]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP0]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 12
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[STRIDE_X]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[MUL]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[STEP_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[STEP_Y]], align 4
; CHECK-NEXT:    [[MUL1:%.*]] = mul nsw i32 [[TMP2]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 16
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[STRIDE_Y]], align 4
; CHECK-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[MUL1]], [[TMP3]]
; CHECK-NEXT:    br i1 [[CMP2]], label [[RETURN]], label [[IF_END4:%.*]]
; CHECK:       if.end4:
; CHECK-NEXT:    [[STEP_X5:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[STEP_X5]], align 4
; CHECK-NEXT:    [[MUL6:%.*]] = mul nsw i32 [[TMP4]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X7:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[STRIDE_X7]], align 4
; CHECK-NEXT:    [[CMP8:%.*]] = icmp sgt i32 [[MUL6]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP8]], label [[RETURN]], label [[IF_END10:%.*]]
; CHECK:       if.end10:
; CHECK-NEXT:    [[STEP_Y11:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 8
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[STEP_Y11]], align 4
; CHECK-NEXT:    [[MUL12:%.*]] = mul nsw i32 [[TMP6]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y13:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 16
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[STRIDE_Y13]], align 4
; CHECK-NEXT:    [[CMP14:%.*]] = icmp sgt i32 [[MUL12]], [[TMP7]]
; CHECK-NEXT:    br i1 [[CMP14]], label [[RETURN]], label [[IF_END16:%.*]]
; CHECK:       if.end16:
; CHECK-NEXT:    [[MUL20:%.*]] = mul nsw i32 [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[MUL23:%.*]] = mul nsw i32 [[TMP6]], [[TMP5]]
; CHECK-NEXT:    [[CMP2468:%.*]] = icmp sgt i32 [[COUNT_Y]], 0
; CHECK-NEXT:    br i1 [[CMP2468]], label [[FOR_COND25_PREHEADER_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.cond25.preheader.lr.ph:
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[FILTER]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[IN_IMAGE]], align 4
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[COUNT_X]], -7
; CHECK-NEXT:    [[TMP10:%.*]] = and i32 [[COUNT_X]], -8
; CHECK-NEXT:    [[CMP2665:%.*]] = icmp sgt i32 [[COUNT_X]], 7
; CHECK-NEXT:    br label [[FOR_COND25_PREHEADER:%.*]]
; CHECK:       for.cond25.preheader:
; CHECK-NEXT:    [[Y_072:%.*]] = phi i32 [ 0, [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[INC37:%.*]], [[FOR_COND_CLEANUP27:%.*]] ]
; CHECK-NEXT:    [[ACC_071:%.*]] = phi float [ 0.000000e+00, [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[TMP39:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[I_DATA_070:%.*]] = phi ptr [ [[TMP9]], [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[ADD_PTR:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[F_DATA_069:%.*]] = phi ptr [ [[TMP8]], [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[ADD_PTR35:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    br i1 [[CMP2665]], label [[FOR_BODY28_7:%.*]], label [[FOR_COND128_PREHEADER:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi float [ 0.000000e+00, [[IF_END16]] ], [ [[TMP39]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    store float [[ACC_0_LCSSA]], ptr [[OUT_VALUE]], align 4
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       for.cond128.preheader:
; CHECK-NEXT:    [[X_0_LCSSA:%.*]] = phi i32 [ 0, [[FOR_COND25_PREHEADER]] ], [ [[TMP10]], [[FOR_BODY28_7]] ]
; CHECK-NEXT:    [[TMP11:%.*]] = phi float [ [[ACC_071]], [[FOR_COND25_PREHEADER]] ], [ [[TMP35:%.*]], [[FOR_BODY28_7]] ]
; CHECK-NEXT:    [[CMP129268:%.*]] = icmp slt i32 [[X_0_LCSSA]], [[COUNT_X]]
; CHECK-NEXT:    br i1 [[CMP129268]], label [[FOR_BODY28_CLONE:%.*]], label [[FOR_COND_CLEANUP27]]
; CHECK:       for.body28.7:
; CHECK-NEXT:    [[X_067:%.*]] = phi i32 [ [[INC_7:%.*]], [[FOR_BODY28_7]] ], [ 0, [[FOR_COND25_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_166:%.*]] = phi float [ [[TMP35]], [[FOR_BODY28_7]] ], [ [[ACC_071]], [[FOR_COND25_PREHEADER]] ]
; CHECK-NEXT:    [[MUL30:%.*]] = mul nsw i32 [[X_067]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL30]]
; CHECK-NEXT:    [[TMP12:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[MUL32:%.*]] = mul nsw i32 [[X_067]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33:%.*]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP13:%.*]] = load float, ptr [[ARRAYIDX33]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP12]], float [[TMP13]], float [[ACC_166]])
; CHECK-NEXT:    [[INC:%.*]] = or disjoint i32 [[X_067]], 1
; CHECK-NEXT:    [[MUL30_1:%.*]] = mul nsw i32 [[INC]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL30_1]]
; CHECK-NEXT:    [[TMP15:%.*]] = load float, ptr [[ARRAYIDX_1]], align 4
; CHECK-NEXT:    [[MUL32_1:%.*]] = mul nsw i32 [[INC]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_1:%.*]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL32_1]]
; CHECK-NEXT:    [[TMP16:%.*]] = load float, ptr [[ARRAYIDX33_1]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP15]], float [[TMP16]], float [[TMP14]])
; CHECK-NEXT:    [[INC_1:%.*]] = or disjoint i32 [[X_067]], 2
; CHECK-NEXT:    [[MUL30_2:%.*]] = mul nsw i32 [[INC_1]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL30_2]]
; CHECK-NEXT:    [[TMP18:%.*]] = load float, ptr [[ARRAYIDX_2]], align 4
; CHECK-NEXT:    [[MUL32_2:%.*]] = mul nsw i32 [[INC_1]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_2:%.*]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL32_2]]
; CHECK-NEXT:    [[TMP19:%.*]] = load float, ptr [[ARRAYIDX33_2]], align 4
; CHECK-NEXT:    [[TMP20:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP18]], float [[TMP19]], float [[TMP17]])
; CHECK-NEXT:    [[INC_2:%.*]] = or disjoint i32 [[X_067]], 3
; CHECK-NEXT:    [[MUL30_3:%.*]] = mul nsw i32 [[INC_2]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL30_3]]
; CHECK-NEXT:    [[TMP21:%.*]] = load float, ptr [[ARRAYIDX_3]], align 4
; CHECK-NEXT:    [[MUL32_3:%.*]] = mul nsw i32 [[INC_2]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_3:%.*]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL32_3]]
; CHECK-NEXT:    [[TMP22:%.*]] = load float, ptr [[ARRAYIDX33_3]], align 4
; CHECK-NEXT:    [[TMP23:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP21]], float [[TMP22]], float [[TMP20]])
; CHECK-NEXT:    [[INC_3:%.*]] = or disjoint i32 [[X_067]], 4
; CHECK-NEXT:    [[MUL30_4:%.*]] = mul nsw i32 [[INC_3]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL30_4]]
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr [[ARRAYIDX_4]], align 4
; CHECK-NEXT:    [[MUL32_4:%.*]] = mul nsw i32 [[INC_3]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_4:%.*]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL32_4]]
; CHECK-NEXT:    [[TMP25:%.*]] = load float, ptr [[ARRAYIDX33_4]], align 4
; CHECK-NEXT:    [[TMP26:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP24]], float [[TMP25]], float [[TMP23]])
; CHECK-NEXT:    [[INC_4:%.*]] = or disjoint i32 [[X_067]], 5
; CHECK-NEXT:    [[MUL30_5:%.*]] = mul nsw i32 [[INC_4]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL30_5]]
; CHECK-NEXT:    [[TMP27:%.*]] = load float, ptr [[ARRAYIDX_5]], align 4
; CHECK-NEXT:    [[MUL32_5:%.*]] = mul nsw i32 [[INC_4]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_5:%.*]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL32_5]]
; CHECK-NEXT:    [[TMP28:%.*]] = load float, ptr [[ARRAYIDX33_5]], align 4
; CHECK-NEXT:    [[TMP29:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP27]], float [[TMP28]], float [[TMP26]])
; CHECK-NEXT:    [[INC_5:%.*]] = or disjoint i32 [[X_067]], 6
; CHECK-NEXT:    [[MUL30_6:%.*]] = mul nsw i32 [[INC_5]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL30_6]]
; CHECK-NEXT:    [[TMP30:%.*]] = load float, ptr [[ARRAYIDX_6]], align 4
; CHECK-NEXT:    [[MUL32_6:%.*]] = mul nsw i32 [[INC_5]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_6:%.*]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL32_6]]
; CHECK-NEXT:    [[TMP31:%.*]] = load float, ptr [[ARRAYIDX33_6]], align 4
; CHECK-NEXT:    [[TMP32:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP30]], float [[TMP31]], float [[TMP29]])
; CHECK-NEXT:    [[INC_6:%.*]] = or disjoint i32 [[X_067]], 7
; CHECK-NEXT:    [[MUL30_7:%.*]] = mul nsw i32 [[INC_6]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL30_7]]
; CHECK-NEXT:    [[TMP33:%.*]] = load float, ptr [[ARRAYIDX_7]], align 4
; CHECK-NEXT:    [[MUL32_7:%.*]] = mul nsw i32 [[INC_6]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_7:%.*]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL32_7]]
; CHECK-NEXT:    [[TMP34:%.*]] = load float, ptr [[ARRAYIDX33_7]], align 4
; CHECK-NEXT:    [[TMP35]] = tail call float @llvm.fmuladd.f32(float [[TMP33]], float [[TMP34]], float [[TMP32]])
; CHECK-NEXT:    [[INC_7]] = add nuw nsw i32 [[X_067]], 8
; CHECK-NEXT:    [[EXITCOND_NOT_7:%.*]] = icmp slt i32 [[INC_7]], [[SUB]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_7]], label [[FOR_BODY28_7]], label [[FOR_COND128_PREHEADER]]
; CHECK:       for.body28.clone:
; CHECK-NEXT:    [[X_067_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY28_CLONE]] ], [ [[X_0_LCSSA]], [[FOR_COND128_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_166_CLONE:%.*]] = phi float [ [[TMP38:%.*]], [[FOR_BODY28_CLONE]] ], [ [[TMP11]], [[FOR_COND128_PREHEADER]] ]
; CHECK-NEXT:    [[MUL30_CLONE:%.*]] = mul nsw i32 [[X_067_CLONE]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL30_CLONE]]
; CHECK-NEXT:    [[TMP36:%.*]] = load float, ptr [[ARRAYIDX_CLONE]], align 4
; CHECK-NEXT:    [[MUL32_CLONE:%.*]] = mul nsw i32 [[X_067_CLONE]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_CLONE:%.*]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL32_CLONE]]
; CHECK-NEXT:    [[TMP37:%.*]] = load float, ptr [[ARRAYIDX33_CLONE]], align 4
; CHECK-NEXT:    [[TMP38]] = tail call float @llvm.fmuladd.f32(float [[TMP36]], float [[TMP37]], float [[ACC_166_CLONE]])
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[X_067_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[COUNT_X]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_COND_CLEANUP27]], label [[FOR_BODY28_CLONE]]
; CHECK:       for.cond.cleanup27:
; CHECK-NEXT:    [[TMP39]] = phi float [ [[TMP11]], [[FOR_COND128_PREHEADER]] ], [ [[TMP38]], [[FOR_BODY28_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr inbounds float, ptr [[I_DATA_070]], i32 [[MUL20]]
; CHECK-NEXT:    [[ADD_PTR35]] = getelementptr inbounds float, ptr [[F_DATA_069]], i32 [[MUL23]]
; CHECK-NEXT:    [[INC37]] = add nuw nsw i32 [[Y_072]], 1
; CHECK-NEXT:    [[EXITCOND74_NOT:%.*]] = icmp eq i32 [[INC37]], [[COUNT_Y]]
; CHECK-NEXT:    br i1 [[EXITCOND74_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_COND25_PREHEADER]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, [[FOR_COND_CLEANUP]] ], [ 458755, [[ENTRY:%.*]] ], [ 458755, [[IF_END]] ], [ 458755, [[IF_END4]] ], [ 458755, [[IF_END10]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %step_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 1
  %0 = load i32, ptr %step_x, align 4
  %mul = mul nsw i32 %0, %count_x
  %stride_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 3
  %1 = load i32, ptr %stride_x, align 4
  %cmp = icmp sgt i32 %mul, %1
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %step_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 2
  %2 = load i32, ptr %step_y, align 4
  %mul1 = mul nsw i32 %2, %count_y
  %stride_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 4
  %3 = load i32, ptr %stride_y, align 4
  %cmp2 = icmp sgt i32 %mul1, %3
  br i1 %cmp2, label %return, label %if.end4

if.end4:                                          ; preds = %if.end
  %step_x5 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 1
  %4 = load i32, ptr %step_x5, align 4
  %mul6 = mul nsw i32 %4, %count_x
  %stride_x7 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 3
  %5 = load i32, ptr %stride_x7, align 4
  %cmp8 = icmp sgt i32 %mul6, %5
  br i1 %cmp8, label %return, label %if.end10

if.end10:                                         ; preds = %if.end4
  %step_y11 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 2
  %6 = load i32, ptr %step_y11, align 4
  %mul12 = mul nsw i32 %6, %count_y
  %stride_y13 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 4
  %7 = load i32, ptr %stride_y13, align 4
  %cmp14 = icmp sgt i32 %mul12, %7
  br i1 %cmp14, label %return, label %if.end16

if.end16:                                         ; preds = %if.end10
  %mul20 = mul nsw i32 %2, %1
  %mul23 = mul nsw i32 %6, %5
  %cmp2468 = icmp sgt i32 %count_y, 0
  br i1 %cmp2468, label %for.cond25.preheader.lr.ph, label %for.cond.cleanup

for.cond25.preheader.lr.ph:                       ; preds = %if.end16
  %8 = load ptr, ptr %filter, align 4
  %9 = load ptr, ptr %in_image, align 4
  %cmp2665 = icmp sgt i32 %count_x, 0
  br label %for.cond25.preheader

for.cond25.preheader:                             ; preds = %for.cond.cleanup27, %for.cond25.preheader.lr.ph
  %y.072 = phi i32 [ 0, %for.cond25.preheader.lr.ph ], [ %inc37, %for.cond.cleanup27 ]
  %acc.071 = phi float [ 0.000000e+00, %for.cond25.preheader.lr.ph ], [ %acc.1.lcssa, %for.cond.cleanup27 ]
  %i_data.070 = phi ptr [ %9, %for.cond25.preheader.lr.ph ], [ %add.ptr, %for.cond.cleanup27 ]
  %f_data.069 = phi ptr [ %8, %for.cond25.preheader.lr.ph ], [ %add.ptr35, %for.cond.cleanup27 ]
  br i1 %cmp2665, label %for.body28, label %for.cond.cleanup27

for.cond.cleanup:                                 ; preds = %for.cond.cleanup27, %if.end16
  %acc.0.lcssa = phi float [ 0.000000e+00, %if.end16 ], [ %acc.1.lcssa, %for.cond.cleanup27 ]
  store float %acc.0.lcssa, ptr %out_value, align 4
  br label %return

for.cond.cleanup27:                               ; preds = %for.body28, %for.cond25.preheader
  %acc.1.lcssa = phi float [ %acc.071, %for.cond25.preheader ], [ %12, %for.body28 ]
  %add.ptr = getelementptr inbounds float, ptr %i_data.070, i32 %mul20
  %add.ptr35 = getelementptr inbounds float, ptr %f_data.069, i32 %mul23
  %inc37 = add nuw nsw i32 %y.072, 1
  %exitcond74.not = icmp eq i32 %inc37, %count_y
  br i1 %exitcond74.not, label %for.cond.cleanup, label %for.cond25.preheader

for.body28:                                       ; preds = %for.body28, %for.cond25.preheader
  %x.067 = phi i32 [ %inc, %for.body28 ], [ 0, %for.cond25.preheader ]
  %acc.166 = phi float [ %12, %for.body28 ], [ %acc.071, %for.cond25.preheader ]
  %mul30 = mul nsw i32 %x.067, %0
  %arrayidx = getelementptr inbounds float, ptr %i_data.070, i32 %mul30
  %10 = load float, ptr %arrayidx, align 4
  %mul32 = mul nsw i32 %x.067, %4
  %arrayidx33 = getelementptr inbounds float, ptr %f_data.069, i32 %mul32
  %11 = load float, ptr %arrayidx33, align 4
  %12 = tail call float @llvm.fmuladd.f32(float %10, float %11, float %acc.166)
  %inc = add nuw nsw i32 %x.067, 1
  %exitcond.not = icmp eq i32 %inc, %count_x
  br i1 %exitcond.not, label %for.cond.cleanup27, label %for.body28

return:                                           ; preds = %for.cond.cleanup, %if.end10, %if.end4, %if.end, %entry
  %retval.0 = phi i32 [ 0, %for.cond.cleanup ], [ 458755, %entry ], [ 458755, %if.end ], [ 458755, %if.end4 ], [ 458755, %if.end10 ]
  ret i32 %retval.0
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.fmuladd.f32(float, float, float)
