; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-loop-unroll-and-remainder -riscv-loop-unroll-and-remainder=true < %s | FileCheck %s

; Function Attrs: nofree norecurse nosync nounwind memory(readwrite, inaccessiblemem: none)
define dso_local noundef i32 @dspm_mulc_f32_ansi(ptr noundef readonly %input, ptr noundef writeonly %output, float noundef %C, i32 noundef %rows, i32 noundef %cols, i32 noundef %padd_in, i32 noundef %padd_out, i32 noundef %step_in, i32 noundef %step_out) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dspm_mulc_f32_ansi(
; CHECK-SAME: ptr noalias noundef readonly [[INPUT:%.*]], ptr noalias noundef writeonly [[OUTPUT:%.*]], float noundef [[C:%.*]], i32 noundef [[ROWS:%.*]], i32 noundef [[COLS:%.*]], i32 noundef [[PADD_IN:%.*]], i32 noundef [[PADD_OUT:%.*]], i32 noundef [[STEP_IN:%.*]], i32 noundef [[STEP_OUT:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[INPUT]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[OUTPUT]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    [[CMP4:%.*]] = icmp slt i32 [[ROWS]], 1
; CHECK-NEXT:    [[OR_COND51:%.*]] = or i1 [[OR_COND]], [[CMP4]]
; CHECK-NEXT:    [[CMP7:%.*]] = icmp slt i32 [[COLS]], 1
; CHECK-NEXT:    [[OR_COND52:%.*]] = or i1 [[OR_COND51]], [[CMP7]]
; CHECK-NEXT:    [[TMP0:%.*]] = or i32 [[PADD_OUT]], [[PADD_IN]]
; CHECK-NEXT:    [[TMP1:%.*]] = icmp slt i32 [[TMP0]], 0
; CHECK-NEXT:    [[OR_COND54:%.*]] = or i1 [[OR_COND52]], [[TMP1]]
; CHECK-NEXT:    [[CMP16:%.*]] = icmp slt i32 [[STEP_IN]], 1
; CHECK-NEXT:    [[OR_COND55:%.*]] = or i1 [[CMP16]], [[OR_COND54]]
; CHECK-NEXT:    [[CMP19:%.*]] = icmp slt i32 [[STEP_OUT]], 1
; CHECK-NEXT:    [[OR_COND56:%.*]] = or i1 [[CMP19]], [[OR_COND55]]
; CHECK-NEXT:    br i1 [[OR_COND56]], label [[RETURN:%.*]], label [[IF_END21:%.*]]
; CHECK:       if.end21:
; CHECK-NEXT:    [[CMP35236:%.*]] = icmp ugt i32 [[COLS]], 7
; CHECK-NEXT:    br label [[FOR_BODY27_PREHEADER:%.*]]
; CHECK:       for.body27.preheader:
; CHECK-NEXT:    [[ROW_061:%.*]] = phi i32 [ 0, [[IF_END21]] ], [ [[INC33:%.*]], [[FOR_COND_CLEANUP26:%.*]] ]
; CHECK-NEXT:    [[PTR_INPUT_060:%.*]] = phi ptr [ [[INPUT]], [[IF_END21]] ], [ [[ADD_PTR:%.*]], [[FOR_COND_CLEANUP26]] ]
; CHECK-NEXT:    [[OUTPUT_ADDR_059:%.*]] = phi ptr [ [[OUTPUT]], [[IF_END21]] ], [ [[ADD_PTR31:%.*]], [[FOR_COND_CLEANUP26]] ]
; CHECK-NEXT:    br i1 [[CMP35236]], label [[FOR_BODY27_7:%.*]], label [[FORCOND113PREHEADER:%.*]]
; CHECK:       for.body27.preheader.for.body27.7_crit_edge:
; CHECK-NEXT:    [[TMP9:%.*]] = load float, ptr [[PTR_INPUT_060]], align 4
; CHECK-NEXT:    [[ARRAYIDX_1_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw float, ptr [[PTR_INPUT_060]], i32 [[STEP_IN]]
; CHECK-NEXT:    [[DOTPRE1:%.*]] = load float, ptr [[ARRAYIDX_1_PHI_TRANS_INSERT]], align 4
; CHECK-NEXT:    br label [[FOR_BODY27_8:%.*]]
; CHECK:       forCond113Preheader:
; CHECK-NEXT:    [[COL_0_LCSSA:%.*]] = phi i32 [ 0, [[FOR_BODY27_PREHEADER]] ], [ 8, [[FOR_BODY27_8]] ]
; CHECK-NEXT:    [[CMP114238:%.*]] = icmp slt i32 [[COL_0_LCSSA]], [[COLS]]
; CHECK-NEXT:    br i1 [[CMP114238]], label [[FOR_BODY27_CLONE:%.*]], label [[FOR_COND_CLEANUP26]]
; CHECK:       for.body27.7:
; CHECK-NEXT:    [[MUL28_7:%.*]] = fmul float [[C]], [[TMP9]]
; CHECK-NEXT:    store float [[MUL28_7]], ptr [[OUTPUT_ADDR_059]], align 4
; CHECK-NEXT:    [[MUL28_1:%.*]] = fmul float [[C]], [[DOTPRE1]]
; CHECK-NEXT:    [[ARRAYIDX30_1:%.*]] = getelementptr inbounds nuw float, ptr [[OUTPUT_ADDR_059]], i32 [[STEP_OUT]]
; CHECK-NEXT:    store float [[MUL28_1]], ptr [[ARRAYIDX30_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX_2_IDX:%.*]] = shl nuw nsw i32 [[STEP_IN]], 3
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT_060]], i32 [[ARRAYIDX_2_IDX]]
; CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[ARRAYIDX_2]], align 4
; CHECK-NEXT:    [[MUL28_2:%.*]] = fmul float [[C]], [[TMP2]]
; CHECK-NEXT:    [[ARRAYIDX30_2_IDX:%.*]] = shl nuw nsw i32 [[STEP_OUT]], 3
; CHECK-NEXT:    [[ARRAYIDX30_2:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_059]], i32 [[ARRAYIDX30_2_IDX]]
; CHECK-NEXT:    store float [[MUL28_2]], ptr [[ARRAYIDX30_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX_3_IDX:%.*]] = mul nuw nsw i32 [[STEP_IN]], 12
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT_060]], i32 [[ARRAYIDX_3_IDX]]
; CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[ARRAYIDX_3]], align 4
; CHECK-NEXT:    [[MUL28_3:%.*]] = fmul float [[C]], [[TMP3]]
; CHECK-NEXT:    [[ARRAYIDX30_3_IDX:%.*]] = mul nuw nsw i32 [[STEP_OUT]], 12
; CHECK-NEXT:    [[ARRAYIDX30_3:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_059]], i32 [[ARRAYIDX30_3_IDX]]
; CHECK-NEXT:    store float [[MUL28_3]], ptr [[ARRAYIDX30_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX_4_IDX:%.*]] = shl nuw nsw i32 [[STEP_IN]], 4
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT_060]], i32 [[ARRAYIDX_4_IDX]]
; CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr [[ARRAYIDX_4]], align 4
; CHECK-NEXT:    [[MUL28_4:%.*]] = fmul float [[C]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX30_4_IDX:%.*]] = shl nuw nsw i32 [[STEP_OUT]], 4
; CHECK-NEXT:    [[ARRAYIDX30_4:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_059]], i32 [[ARRAYIDX30_4_IDX]]
; CHECK-NEXT:    store float [[MUL28_4]], ptr [[ARRAYIDX30_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX_5_IDX:%.*]] = mul nuw nsw i32 [[STEP_IN]], 20
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT_060]], i32 [[ARRAYIDX_5_IDX]]
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[ARRAYIDX_5]], align 4
; CHECK-NEXT:    [[MUL28_5:%.*]] = fmul float [[C]], [[TMP5]]
; CHECK-NEXT:    [[ARRAYIDX30_5_IDX:%.*]] = mul nuw nsw i32 [[STEP_OUT]], 20
; CHECK-NEXT:    [[ARRAYIDX30_5:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_059]], i32 [[ARRAYIDX30_5_IDX]]
; CHECK-NEXT:    store float [[MUL28_5]], ptr [[ARRAYIDX30_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX_6_IDX:%.*]] = mul nuw nsw i32 [[STEP_IN]], 24
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT_060]], i32 [[ARRAYIDX_6_IDX]]
; CHECK-NEXT:    [[TMP6:%.*]] = load float, ptr [[ARRAYIDX_6]], align 4
; CHECK-NEXT:    [[MUL28_6:%.*]] = fmul float [[C]], [[TMP6]]
; CHECK-NEXT:    [[ARRAYIDX30_6_IDX:%.*]] = mul nuw nsw i32 [[STEP_OUT]], 24
; CHECK-NEXT:    [[ARRAYIDX30_6:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_059]], i32 [[ARRAYIDX30_6_IDX]]
; CHECK-NEXT:    store float [[MUL28_6]], ptr [[ARRAYIDX30_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX_7_IDX:%.*]] = mul nuw nsw i32 [[STEP_IN]], 28
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT_060]], i32 [[ARRAYIDX_7_IDX]]
; CHECK-NEXT:    [[TMP7:%.*]] = load float, ptr [[ARRAYIDX_7]], align 4
; CHECK-NEXT:    [[MUL28_8:%.*]] = fmul float [[C]], [[TMP7]]
; CHECK-NEXT:    [[ARRAYIDX30_7_IDX:%.*]] = mul nuw nsw i32 [[STEP_OUT]], 28
; CHECK-NEXT:    [[ARRAYIDX30_7:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_059]], i32 [[ARRAYIDX30_7_IDX]]
; CHECK-NEXT:    store float [[MUL28_8]], ptr [[ARRAYIDX30_7]], align 4
; CHECK-NEXT:    br i1 false, label [[FOR_BODY27_7_FOR_BODY27_7_CRIT_EDGE:%.*]], label [[FORCOND113PREHEADER]]
; CHECK:       for.body27.7.for.body27.7_crit_edge:
; CHECK-NEXT:    br label [[FOR_BODY27_8]]
; CHECK:       for.body27.clone:
; CHECK-NEXT:    [[COL_058_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY27_CLONE]] ], [ [[COL_0_LCSSA]], [[FORCOND113PREHEADER]] ]
; CHECK-NEXT:    [[MUL_CLONE:%.*]] = mul nuw nsw i32 [[COL_058_CLONE]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds nuw float, ptr [[PTR_INPUT_060]], i32 [[MUL_CLONE]]
; CHECK-NEXT:    [[TMP10:%.*]] = load float, ptr [[ARRAYIDX_CLONE]], align 4
; CHECK-NEXT:    [[MUL28_CLONE:%.*]] = fmul float [[C]], [[TMP10]]
; CHECK-NEXT:    [[MUL29_CLONE:%.*]] = mul nuw nsw i32 [[COL_058_CLONE]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX30_CLONE:%.*]] = getelementptr inbounds nuw float, ptr [[OUTPUT_ADDR_059]], i32 [[MUL29_CLONE]]
; CHECK-NEXT:    store float [[MUL28_CLONE]], ptr [[ARRAYIDX30_CLONE]], align 4
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[COL_058_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[COLS]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_COND_CLEANUP26]], label [[FOR_BODY27_CLONE]]
; CHECK:       for.cond.cleanup26:
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr float, ptr [[PTR_INPUT_060]], i32 [[PADD_IN]]
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr float, ptr [[TMP11]], i32 [[COLS]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr float, ptr [[OUTPUT_ADDR_059]], i32 [[PADD_OUT]]
; CHECK-NEXT:    [[ADD_PTR31]] = getelementptr float, ptr [[TMP12]], i32 [[COLS]]
; CHECK-NEXT:    [[INC33]] = add nuw nsw i32 [[ROW_061]], 1
; CHECK-NEXT:    [[EXITCOND62_NOT:%.*]] = icmp eq i32 [[INC33]], [[ROWS]]
; CHECK-NEXT:    br i1 [[EXITCOND62_NOT]], label [[RETURN]], label [[FOR_BODY27_PREHEADER]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458755, [[ENTRY:%.*]] ], [ 0, [[FOR_COND_CLEANUP26]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %input, null
  %cmp1 = icmp eq ptr %output, null
  %or.cond = or i1 %cmp, %cmp1
  %cmp4 = icmp slt i32 %rows, 1
  %or.cond51 = or i1 %or.cond, %cmp4
  %cmp7 = icmp slt i32 %cols, 1
  %or.cond52 = or i1 %or.cond51, %cmp7
  %0 = or i32 %padd_out, %padd_in
  %1 = icmp slt i32 %0, 0
  %or.cond54 = or i1 %or.cond52, %1
  %cmp16 = icmp slt i32 %step_in, 1
  %or.cond55 = or i1 %cmp16, %or.cond54
  %cmp19 = icmp slt i32 %step_out, 1
  %or.cond56 = or i1 %cmp19, %or.cond55
  br i1 %or.cond56, label %return, label %if.end21

if.end21:                                         ; preds = %entry
  %add = add nuw nsw i32 %padd_in, %cols
  %add22 = add nuw nsw i32 %padd_out, %cols
  br label %for.body27.preheader

for.body27.preheader:                             ; preds = %for.cond.cleanup26, %if.end21
  %row.061 = phi i32 [ 0, %if.end21 ], [ %inc33, %for.cond.cleanup26 ]
  %ptr_input.060 = phi ptr [ %input, %if.end21 ], [ %add.ptr, %for.cond.cleanup26 ]
  %output.addr.059 = phi ptr [ %output, %if.end21 ], [ %add.ptr31, %for.cond.cleanup26 ]
  br label %for.body27

for.cond.cleanup26:                               ; preds = %for.body27
  %add.ptr = getelementptr inbounds float, ptr %ptr_input.060, i32 %add
  %add.ptr31 = getelementptr inbounds float, ptr %output.addr.059, i32 %add22
  %inc33 = add nuw nsw i32 %row.061, 1
  %exitcond62.not = icmp eq i32 %inc33, %rows
  br i1 %exitcond62.not, label %return, label %for.body27.preheader

for.body27:                                       ; preds = %for.body27, %for.body27.preheader
  %col.058 = phi i32 [ %inc, %for.body27 ], [ 0, %for.body27.preheader ]
  %mul = mul nsw i32 %col.058, %step_in
  %arrayidx = getelementptr inbounds float, ptr %ptr_input.060, i32 %mul
  %2 = load float, ptr %arrayidx, align 4
  %mul28 = fmul float %2, %C
  %mul29 = mul nsw i32 %col.058, %step_out
  %arrayidx30 = getelementptr inbounds float, ptr %output.addr.059, i32 %mul29
  store float %mul28, ptr %arrayidx30, align 4
  %inc = add nuw nsw i32 %col.058, 1
  %exitcond.not = icmp eq i32 %inc, %cols
  br i1 %exitcond.not, label %for.cond.cleanup26, label %for.body27

return:                                           ; preds = %for.cond.cleanup26, %entry
  %retval.0 = phi i32 [ 458755, %entry ], [ 0, %for.cond.cleanup26 ]
  ret i32 %retval.0
}
