; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-loop-unroll-and-remainder -riscv-loop-unroll-and-remainder=true < %s | FileCheck %s

; Function Attrs: nofree norecurse nosync nounwind memory(readwrite, inaccessiblemem: none)
define dso_local noundef i32 @dspm_add_f32_ansi(ptr noundef readonly %input1, ptr noundef readonly %input2, ptr noundef writeonly %output, i32 noundef %rows, i32 noundef %cols, i32 noundef %padd1, i32 noundef %padd2, i32 noundef %padd_out, i32 noundef %step1, i32 noundef %step2, i32 noundef %step_out) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dspm_add_f32_ansi(
; CHECK-SAME: ptr noalias noundef readonly [[INPUT1:%.*]], ptr noalias noundef readonly [[INPUT2:%.*]], ptr noalias noundef writeonly [[OUTPUT:%.*]], i32 noundef [[ROWS:%.*]], i32 noundef [[COLS:%.*]], i32 noundef [[PADD1:%.*]], i32 noundef [[PADD2:%.*]], i32 noundef [[PADD_OUT:%.*]], i32 noundef [[STEP1:%.*]], i32 noundef [[STEP2:%.*]], i32 noundef [[STEP_OUT:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[INPUT1]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[INPUT2]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    [[CMP4:%.*]] = icmp eq ptr [[OUTPUT]], null
; CHECK-NEXT:    [[OR_COND70:%.*]] = or i1 [[OR_COND]], [[CMP4]]
; CHECK-NEXT:    [[CMP7:%.*]] = icmp slt i32 [[ROWS]], 1
; CHECK-NEXT:    [[OR_COND71:%.*]] = or i1 [[OR_COND70]], [[CMP7]]
; CHECK-NEXT:    [[CMP10:%.*]] = icmp slt i32 [[COLS]], 1
; CHECK-NEXT:    [[OR_COND72:%.*]] = or i1 [[OR_COND71]], [[CMP10]]
; CHECK-NEXT:    [[TMP0:%.*]] = or i32 [[PADD2]], [[PADD1]]
; CHECK-NEXT:    [[TMP1:%.*]] = or i32 [[TMP0]], [[PADD_OUT]]
; CHECK-NEXT:    [[TMP2:%.*]] = icmp slt i32 [[TMP1]], 0
; CHECK-NEXT:    [[OR_COND75:%.*]] = or i1 [[OR_COND72]], [[TMP2]]
; CHECK-NEXT:    [[CMP22:%.*]] = icmp slt i32 [[STEP1]], 1
; CHECK-NEXT:    [[OR_COND76:%.*]] = or i1 [[CMP22]], [[OR_COND75]]
; CHECK-NEXT:    [[CMP25:%.*]] = icmp slt i32 [[STEP2]], 1
; CHECK-NEXT:    [[OR_COND77:%.*]] = or i1 [[CMP25]], [[OR_COND76]]
; CHECK-NEXT:    [[CMP28:%.*]] = icmp slt i32 [[STEP_OUT]], 1
; CHECK-NEXT:    [[OR_COND78:%.*]] = or i1 [[CMP28]], [[OR_COND77]]
; CHECK-NEXT:    br i1 [[OR_COND78]], label [[RETURN:%.*]], label [[IF_END30:%.*]]
; CHECK:       if.end30:
; CHECK-NEXT:    [[CMP3381:%.*]] = icmp sgt i32 [[ROWS]], 0
; CHECK-NEXT:    [[CMP35236:%.*]] = icmp ugt i32 [[COLS]], 7
; CHECK-NEXT:    br i1 [[CMP3381]], label [[FOR_COND34_PREHEADER:%.*]], label [[RETURN]]
; CHECK:       for.cond34.preheader:
; CHECK-NEXT:    [[ROW_085:%.*]] = phi i32 [ [[INC46:%.*]], [[FOR_COND_CLEANUP36:%.*]] ], [ 0, [[IF_END30]] ]
; CHECK-NEXT:    [[PTR_INPUT2_084:%.*]] = phi ptr [ [[ADD_PTR43:%.*]], [[FOR_COND_CLEANUP36]] ], [ [[INPUT2]], [[IF_END30]] ]
; CHECK-NEXT:    [[PTR_INPUT1_083:%.*]] = phi ptr [ [[ADD_PTR:%.*]], [[FOR_COND_CLEANUP36]] ], [ [[INPUT1]], [[IF_END30]] ]
; CHECK-NEXT:    [[OUTPUT_ADDR_082:%.*]] = phi ptr [ [[ADD_PTR44:%.*]], [[FOR_COND_CLEANUP36]] ], [ [[OUTPUT]], [[IF_END30]] ]
; CHECK-NEXT:    br i1 [[CMP35236]], label [[FOR_BODY37_7:%.*]], label [[FORCOND113PREHEADER:%.*]]
; CHECK:       for.cond34.preheader.for.body37.7_crit_edge:
; CHECK-NEXT:    [[TMP17:%.*]] = load float, ptr [[PTR_INPUT1_083]], align 4
; CHECK-NEXT:    [[TMP18:%.*]] = load float, ptr [[PTR_INPUT2_084]], align 4
; CHECK-NEXT:    [[ARRAYIDX_1_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw float, ptr [[PTR_INPUT1_083]], i32 [[STEP1]]
; CHECK-NEXT:    [[DOTPRE2:%.*]] = load float, ptr [[ARRAYIDX_1_PHI_TRANS_INSERT]], align 4
; CHECK-NEXT:    [[ARRAYIDX39_1_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw float, ptr [[PTR_INPUT2_084]], i32 [[STEP2]]
; CHECK-NEXT:    [[DOTPRE3:%.*]] = load float, ptr [[ARRAYIDX39_1_PHI_TRANS_INSERT]], align 4
; CHECK-NEXT:    br label [[FOR_BODY37_8:%.*]]
; CHECK:       forCond113Preheader:
; CHECK-NEXT:    [[COL_0_LCSSA:%.*]] = phi i32 [ 0, [[FOR_COND34_PREHEADER]] ], [ 8, [[FOR_BODY37_8]] ]
; CHECK-NEXT:    [[CMP114238:%.*]] = icmp slt i32 [[COL_0_LCSSA]], [[COLS]]
; CHECK-NEXT:    br i1 [[CMP114238]], label [[FOR_BODY37_CLONE:%.*]], label [[FOR_COND_CLEANUP36]]
; CHECK:       for.body37.7:
; CHECK-NEXT:    [[ADD40_7:%.*]] = fadd float [[TMP17]], [[TMP18]]
; CHECK-NEXT:    store float [[ADD40_7]], ptr [[OUTPUT_ADDR_082]], align 4
; CHECK-NEXT:    [[ADD40_1:%.*]] = fadd float [[DOTPRE2]], [[DOTPRE3]]
; CHECK-NEXT:    [[ARRAYIDX42_1:%.*]] = getelementptr inbounds nuw float, ptr [[OUTPUT_ADDR_082]], i32 [[STEP_OUT]]
; CHECK-NEXT:    store float [[ADD40_1]], ptr [[ARRAYIDX42_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX_2_IDX:%.*]] = shl nuw nsw i32 [[STEP1]], 3
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT1_083]], i32 [[ARRAYIDX_2_IDX]]
; CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[ARRAYIDX_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX39_2_IDX:%.*]] = shl nuw nsw i32 [[STEP2]], 3
; CHECK-NEXT:    [[ARRAYIDX39_2:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT2_084]], i32 [[ARRAYIDX39_2_IDX]]
; CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr [[ARRAYIDX39_2]], align 4
; CHECK-NEXT:    [[ADD40_2:%.*]] = fadd float [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX42_2_IDX:%.*]] = shl nuw nsw i32 [[STEP_OUT]], 3
; CHECK-NEXT:    [[ARRAYIDX42_2:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_082]], i32 [[ARRAYIDX42_2_IDX]]
; CHECK-NEXT:    store float [[ADD40_2]], ptr [[ARRAYIDX42_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX_3_IDX:%.*]] = mul nuw nsw i32 [[STEP1]], 12
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT1_083]], i32 [[ARRAYIDX_3_IDX]]
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[ARRAYIDX_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX39_3_IDX:%.*]] = mul nuw nsw i32 [[STEP2]], 12
; CHECK-NEXT:    [[ARRAYIDX39_3:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT2_084]], i32 [[ARRAYIDX39_3_IDX]]
; CHECK-NEXT:    [[TMP6:%.*]] = load float, ptr [[ARRAYIDX39_3]], align 4
; CHECK-NEXT:    [[ADD40_3:%.*]] = fadd float [[TMP5]], [[TMP6]]
; CHECK-NEXT:    [[ARRAYIDX42_3_IDX:%.*]] = mul nuw nsw i32 [[STEP_OUT]], 12
; CHECK-NEXT:    [[ARRAYIDX42_3:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_082]], i32 [[ARRAYIDX42_3_IDX]]
; CHECK-NEXT:    store float [[ADD40_3]], ptr [[ARRAYIDX42_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX_4_IDX:%.*]] = shl nuw nsw i32 [[STEP1]], 4
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT1_083]], i32 [[ARRAYIDX_4_IDX]]
; CHECK-NEXT:    [[TMP7:%.*]] = load float, ptr [[ARRAYIDX_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX39_4_IDX:%.*]] = shl nuw nsw i32 [[STEP2]], 4
; CHECK-NEXT:    [[ARRAYIDX39_4:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT2_084]], i32 [[ARRAYIDX39_4_IDX]]
; CHECK-NEXT:    [[TMP8:%.*]] = load float, ptr [[ARRAYIDX39_4]], align 4
; CHECK-NEXT:    [[ADD40_4:%.*]] = fadd float [[TMP7]], [[TMP8]]
; CHECK-NEXT:    [[ARRAYIDX42_4_IDX:%.*]] = shl nuw nsw i32 [[STEP_OUT]], 4
; CHECK-NEXT:    [[ARRAYIDX42_4:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_082]], i32 [[ARRAYIDX42_4_IDX]]
; CHECK-NEXT:    store float [[ADD40_4]], ptr [[ARRAYIDX42_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX_5_IDX:%.*]] = mul nuw nsw i32 [[STEP1]], 20
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT1_083]], i32 [[ARRAYIDX_5_IDX]]
; CHECK-NEXT:    [[TMP9:%.*]] = load float, ptr [[ARRAYIDX_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX39_5_IDX:%.*]] = mul nuw nsw i32 [[STEP2]], 20
; CHECK-NEXT:    [[ARRAYIDX39_5:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT2_084]], i32 [[ARRAYIDX39_5_IDX]]
; CHECK-NEXT:    [[TMP10:%.*]] = load float, ptr [[ARRAYIDX39_5]], align 4
; CHECK-NEXT:    [[ADD40_5:%.*]] = fadd float [[TMP9]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX42_5_IDX:%.*]] = mul nuw nsw i32 [[STEP_OUT]], 20
; CHECK-NEXT:    [[ARRAYIDX42_5:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_082]], i32 [[ARRAYIDX42_5_IDX]]
; CHECK-NEXT:    store float [[ADD40_5]], ptr [[ARRAYIDX42_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX_6_IDX:%.*]] = mul nuw nsw i32 [[STEP1]], 24
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT1_083]], i32 [[ARRAYIDX_6_IDX]]
; CHECK-NEXT:    [[TMP11:%.*]] = load float, ptr [[ARRAYIDX_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX39_6_IDX:%.*]] = mul nuw nsw i32 [[STEP2]], 24
; CHECK-NEXT:    [[ARRAYIDX39_6:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT2_084]], i32 [[ARRAYIDX39_6_IDX]]
; CHECK-NEXT:    [[TMP12:%.*]] = load float, ptr [[ARRAYIDX39_6]], align 4
; CHECK-NEXT:    [[ADD40_6:%.*]] = fadd float [[TMP11]], [[TMP12]]
; CHECK-NEXT:    [[ARRAYIDX42_6_IDX:%.*]] = mul nuw nsw i32 [[STEP_OUT]], 24
; CHECK-NEXT:    [[ARRAYIDX42_6:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_082]], i32 [[ARRAYIDX42_6_IDX]]
; CHECK-NEXT:    store float [[ADD40_6]], ptr [[ARRAYIDX42_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX_7_IDX:%.*]] = mul nuw nsw i32 [[STEP1]], 28
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT1_083]], i32 [[ARRAYIDX_7_IDX]]
; CHECK-NEXT:    [[TMP13:%.*]] = load float, ptr [[ARRAYIDX_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX39_7_IDX:%.*]] = mul nuw nsw i32 [[STEP2]], 28
; CHECK-NEXT:    [[ARRAYIDX39_7:%.*]] = getelementptr inbounds nuw i8, ptr [[PTR_INPUT2_084]], i32 [[ARRAYIDX39_7_IDX]]
; CHECK-NEXT:    [[TMP14:%.*]] = load float, ptr [[ARRAYIDX39_7]], align 4
; CHECK-NEXT:    [[ADD40_8:%.*]] = fadd float [[TMP13]], [[TMP14]]
; CHECK-NEXT:    [[ARRAYIDX42_7_IDX:%.*]] = mul nuw nsw i32 [[STEP_OUT]], 28
; CHECK-NEXT:    [[ARRAYIDX42_7:%.*]] = getelementptr inbounds nuw i8, ptr [[OUTPUT_ADDR_082]], i32 [[ARRAYIDX42_7_IDX]]
; CHECK-NEXT:    store float [[ADD40_8]], ptr [[ARRAYIDX42_7]], align 4
; CHECK-NEXT:    br i1 false, label [[FOR_BODY37_7_FOR_BODY37_7_CRIT_EDGE:%.*]], label [[FORCOND113PREHEADER]]
; CHECK:       for.body37.7.for.body37.7_crit_edge:
; CHECK-NEXT:    br label [[FOR_BODY37_8]]
; CHECK:       for.body37.clone:
; CHECK-NEXT:    [[COL_080_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY37_CLONE]] ], [ [[COL_0_LCSSA]], [[FORCOND113PREHEADER]] ]
; CHECK-NEXT:    [[MUL_CLONE:%.*]] = mul nuw nsw i32 [[COL_080_CLONE]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds nuw float, ptr [[PTR_INPUT1_083]], i32 [[MUL_CLONE]]
; CHECK-NEXT:    [[TMP19:%.*]] = load float, ptr [[ARRAYIDX_CLONE]], align 4
; CHECK-NEXT:    [[MUL38_CLONE:%.*]] = mul nuw nsw i32 [[COL_080_CLONE]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX39_CLONE:%.*]] = getelementptr inbounds nuw float, ptr [[PTR_INPUT2_084]], i32 [[MUL38_CLONE]]
; CHECK-NEXT:    [[TMP20:%.*]] = load float, ptr [[ARRAYIDX39_CLONE]], align 4
; CHECK-NEXT:    [[ADD40_CLONE:%.*]] = fadd float [[TMP19]], [[TMP20]]
; CHECK-NEXT:    [[MUL41_CLONE:%.*]] = mul nuw nsw i32 [[COL_080_CLONE]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX42_CLONE:%.*]] = getelementptr inbounds nuw float, ptr [[OUTPUT_ADDR_082]], i32 [[MUL41_CLONE]]
; CHECK-NEXT:    store float [[ADD40_CLONE]], ptr [[ARRAYIDX42_CLONE]], align 4
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[COL_080_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[COLS]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_COND_CLEANUP36]], label [[FOR_BODY37_CLONE]]
; CHECK:       for.cond.cleanup36:
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr float, ptr [[PTR_INPUT1_083]], i32 [[PADD1]]
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr float, ptr [[TMP21]], i32 [[COLS]]
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr float, ptr [[PTR_INPUT2_084]], i32 [[PADD2]]
; CHECK-NEXT:    [[ADD_PTR43]] = getelementptr float, ptr [[TMP22]], i32 [[COLS]]
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr float, ptr [[OUTPUT_ADDR_082]], i32 [[PADD_OUT]]
; CHECK-NEXT:    [[ADD_PTR44]] = getelementptr float, ptr [[TMP23]], i32 [[COLS]]
; CHECK-NEXT:    [[INC46]] = add nuw nsw i32 [[ROW_085]], 1
; CHECK-NEXT:    [[EXITCOND86_NOT:%.*]] = icmp eq i32 [[INC46]], [[ROWS]]
; CHECK-NEXT:    br i1 [[EXITCOND86_NOT]], label [[RETURN]], label [[FOR_COND34_PREHEADER]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458755, [[ENTRY:%.*]] ], [ 0, [[IF_END30]] ], [ 0, [[FOR_COND_CLEANUP36]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %input1, null
  %cmp1 = icmp eq ptr %input2, null
  %or.cond = or i1 %cmp, %cmp1
  %cmp4 = icmp eq ptr %output, null
  %or.cond70 = or i1 %or.cond, %cmp4
  %cmp7 = icmp slt i32 %rows, 1
  %or.cond71 = or i1 %or.cond70, %cmp7
  %cmp10 = icmp slt i32 %cols, 1
  %or.cond72 = or i1 %or.cond71, %cmp10
  %0 = or i32 %padd2, %padd1
  %1 = or i32 %0, %padd_out
  %2 = icmp slt i32 %1, 0
  %or.cond75 = or i1 %or.cond72, %2
  %cmp22 = icmp slt i32 %step1, 1
  %or.cond76 = or i1 %cmp22, %or.cond75
  %cmp25 = icmp slt i32 %step2, 1
  %or.cond77 = or i1 %cmp25, %or.cond76
  %cmp28 = icmp slt i32 %step_out, 1
  %or.cond78 = or i1 %cmp28, %or.cond77
  br i1 %or.cond78, label %return, label %if.end30

if.end30:                                         ; preds = %entry
  %add = add nuw nsw i32 %padd1, %cols
  %add31 = add nuw nsw i32 %padd2, %cols
  %add32 = add nuw nsw i32 %padd_out, %cols
  %cmp3381 = icmp sgt i32 %rows, 0
  br i1 %cmp3381, label %for.cond34.preheader, label %return

for.cond34.preheader:                             ; preds = %for.cond.cleanup36, %if.end30
  %row.085 = phi i32 [ %inc46, %for.cond.cleanup36 ], [ 0, %if.end30 ]
  %ptr_input2.084 = phi ptr [ %add.ptr43, %for.cond.cleanup36 ], [ %input2, %if.end30 ]
  %ptr_input1.083 = phi ptr [ %add.ptr, %for.cond.cleanup36 ], [ %input1, %if.end30 ]
  %output.addr.082 = phi ptr [ %add.ptr44, %for.cond.cleanup36 ], [ %output, %if.end30 ]
  br label %for.body37

for.cond.cleanup36:                               ; preds = %for.body37
  %add.ptr = getelementptr inbounds float, ptr %ptr_input1.083, i32 %add
  %add.ptr43 = getelementptr inbounds float, ptr %ptr_input2.084, i32 %add31
  %add.ptr44 = getelementptr inbounds float, ptr %output.addr.082, i32 %add32
  %inc46 = add nuw nsw i32 %row.085, 1
  %exitcond86.not = icmp eq i32 %inc46, %rows
  br i1 %exitcond86.not, label %return, label %for.cond34.preheader

for.body37:                                       ; preds = %for.body37, %for.cond34.preheader
  %col.080 = phi i32 [ %inc, %for.body37 ], [ 0, %for.cond34.preheader ]
  %mul = mul nsw i32 %col.080, %step1
  %arrayidx = getelementptr inbounds float, ptr %ptr_input1.083, i32 %mul
  %3 = load float, ptr %arrayidx, align 4
  %mul38 = mul nsw i32 %col.080, %step2
  %arrayidx39 = getelementptr inbounds float, ptr %ptr_input2.084, i32 %mul38
  %4 = load float, ptr %arrayidx39, align 4
  %add40 = fadd float %3, %4
  %mul41 = mul nsw i32 %col.080, %step_out
  %arrayidx42 = getelementptr inbounds float, ptr %output.addr.082, i32 %mul41
  store float %add40, ptr %arrayidx42, align 4
  %inc = add nuw nsw i32 %col.080, 1
  %exitcond.not = icmp eq i32 %inc, %cols
  br i1 %exitcond.not, label %for.cond.cleanup36, label %for.body37

return:                                           ; preds = %for.cond.cleanup36, %if.end30, %entry
  %retval.0 = phi i32 [ 458755, %entry ], [ 0, %if.end30 ], [ 0, %for.cond.cleanup36 ]
  ret i32 %retval.0
}
