; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-loop-unroll-and-remainder -riscv-loop-unroll-and-remainder=true < %s | FileCheck %s
define dso_local noundef i32 @dsps_corr_f32_ansi(ptr noundef readonly %Signal, i32 noundef %siglen, ptr noundef readonly %Pattern, i32 noundef %patlen, ptr noundef writeonly %dest) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dsps_corr_f32_ansi(
; CHECK-SAME: ptr noalias noundef readonly [[SIGNAL:%.*]], i32 noundef [[SIGLEN:%.*]], ptr noalias noundef readonly [[PATTERN:%.*]], i32 noundef [[PATLEN:%.*]], ptr noalias noundef writeonly [[DEST:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[PATLEN_NEG:%.*]] = sub i32 0, [[PATLEN]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[SIGNAL]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[PATTERN]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    [[CMP4:%.*]] = icmp eq ptr [[DEST]], null
; CHECK-NEXT:    [[OR_COND33:%.*]] = or i1 [[OR_COND]], [[CMP4]]
; CHECK-NEXT:    [[CMP7:%.*]] = icmp slt i32 [[SIGLEN]], [[PATLEN]]
; CHECK-NEXT:    [[OR_COND34:%.*]] = or i1 [[CMP7]], [[OR_COND33]]
; CHECK-NEXT:    br i1 [[OR_COND34]], label [[RETURN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[SIGLEN]], [[PATLEN]]
; CHECK-NEXT:    [[SUB6:%.*]] = add nsw i32 [[SUB]], -15
; CHECK-NEXT:    [[CMP1235_NOT:%.*]] = icmp sgt i32 [[SUB]], 15
; CHECK-NEXT:    br i1 [[CMP1235_NOT]], label [[FOR_COND8_PREHEADER_LR_PH:%.*]], label [[FOR_COND91_PREHEADER:%.*]]
; CHECK:       for.cond8.preheader.lr.ph:
; CHECK-NEXT:    [[CMP9242:%.*]] = icmp sgt i32 [[PATLEN]], 0
; CHECK-NEXT:    [[SCEVGEP62:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 60
; CHECK-NEXT:    [[SCEVGEP66:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 56
; CHECK-NEXT:    [[SCEVGEP68:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 52
; CHECK-NEXT:    [[SCEVGEP70:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 48
; CHECK-NEXT:    [[SCEVGEP72:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 44
; CHECK-NEXT:    [[SCEVGEP74:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 40
; CHECK-NEXT:    [[SCEVGEP76:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 36
; CHECK-NEXT:    [[SCEVGEP78:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 32
; CHECK-NEXT:    [[SCEVGEP80:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 28
; CHECK-NEXT:    [[SCEVGEP82:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 24
; CHECK-NEXT:    [[SCEVGEP84:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 20
; CHECK-NEXT:    [[SCEVGEP86:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 16
; CHECK-NEXT:    [[SCEVGEP88:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 12
; CHECK-NEXT:    [[SCEVGEP90:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 8
; CHECK-NEXT:    [[SCEVGEP92:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 4
; CHECK-NEXT:    br label [[FOR_COND8_PREHEADER:%.*]]
; CHECK:       for.cond8.preheader:
; CHECK-NEXT:    [[LSR_IV95:%.*]] = phi ptr [ [[SCEVGEP96:%.*]], [[FOR_COND_CLEANUP:%.*]] ], [ [[SIGNAL]], [[FOR_COND8_PREHEADER_LR_PH]] ]
; CHECK-NEXT:    [[N_0276:%.*]] = phi i32 [ 0, [[FOR_COND8_PREHEADER_LR_PH]] ], [ [[ADD89:%.*]], [[FOR_COND_CLEANUP]] ]
; CHECK-NEXT:    br i1 [[CMP9242]], label [[FOR_BODY10_LR_PH:%.*]], label [[FOR_COND_CLEANUP]]
; CHECK:       for.body10.lr.ph:
; CHECK-NEXT:    br label [[FOR_BODY14_US_UNROLL:%.*]]
; CHECK:       for.cond91.preheader.loopexit:
; CHECK-NEXT:    br label [[FOR_COND91_PREHEADER]]
; CHECK:       for.cond91.preheader:
; CHECK-NEXT:    [[N_0_LCSSA:%.*]] = phi i32 [ 0, [[IF_END]] ], [ [[ADD89]], [[FOR_COND91_PREHEADER_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    [[CMP92_NOT282:%.*]] = icmp sgt i32 [[N_0_LCSSA]], [[SUB]]
; CHECK-NEXT:    br i1 [[CMP92_NOT282]], label [[RETURN]], label [[FOR_COND95_PREHEADER_LR_PH:%.*]]
; CHECK:       for.cond95.preheader.lr.ph:
; CHECK-NEXT:    [[CMP92678:%.*]] = icmp sgt i32 [[PATLEN]], 0
; CHECK-NEXT:    br i1 [[CMP92678]], label [[FOR_COND11_PREHEADER_US_PREHEADER:%.*]], label [[FOR_COND11_PREHEADER_PREHEADER:%.*]]
; CHECK:       for.cond11.preheader.preheader:
; CHECK-NEXT:    [[TMP0:%.*]] = shl i32 [[N_0_LCSSA]], 2
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[DEST]], i32 [[TMP0]]
; CHECK-NEXT:    [[N_0_LCSSA_NEG:%.*]] = sub i32 0, [[N_0_LCSSA]]
; CHECK-NEXT:    [[DOTNEG:%.*]] = add i32 [[SIGLEN]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i32 [[DOTNEG]], [[PATLEN_NEG]]
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], [[N_0_LCSSA_NEG]]
; CHECK-NEXT:    [[TMP3:%.*]] = shl i32 [[TMP2]], 2
; CHECK-NEXT:    tail call void @llvm.memset.p0.i32(ptr nonnull align 4 [[SCEVGEP]], i8 0, i32 [[TMP3]], i1 false)
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       for.cond11.preheader.us.preheader:
; CHECK-NEXT:    [[TMP4:%.*]] = add i32 [[SIGLEN]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = add i32 [[TMP4]], [[PATLEN_NEG]]
; CHECK-NEXT:    [[TMP6:%.*]] = shl i32 [[N_0_LCSSA]], 2
; CHECK-NEXT:    [[SCEVGEP102:%.*]] = getelementptr i8, ptr [[SIGNAL]], i32 [[TMP6]]
; CHECK-NEXT:    br label [[FOR_COND11_PREHEADER_US:%.*]]
; CHECK:       for.cond11.preheader.us:
; CHECK-NEXT:    [[LSR_IV103:%.*]] = phi ptr [ [[SCEVGEP104:%.*]], [[FOR_COND11_FOR_COND_CLEANUP13_CRIT_EDGE_US:%.*]] ], [ [[SCEVGEP102]], [[FOR_COND11_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    [[N_038_US:%.*]] = phi i32 [ [[INC18_US:%.*]], [[FOR_COND11_FOR_COND_CLEANUP13_CRIT_EDGE_US]] ], [ [[N_0_LCSSA]], [[FOR_COND11_PREHEADER_US_PREHEADER]] ]
; CHECK-NEXT:    br label [[FOR_BODY14_US:%.*]]
; CHECK:       for.body14.us:
; CHECK-NEXT:    [[LSR_IV105:%.*]] = phi ptr [ [[SCEVGEP106:%.*]], [[FOR_BODY14_US]] ], [ [[LSR_IV103]], [[FOR_COND11_PREHEADER_US]] ]
; CHECK-NEXT:    [[LSR_IV100:%.*]] = phi ptr [ [[SCEVGEP101:%.*]], [[FOR_BODY14_US]] ], [ [[PATTERN]], [[FOR_COND11_PREHEADER_US]] ]
; CHECK-NEXT:    [[LSR_IV98:%.*]] = phi i32 [ [[LSR_IV_NEXT99:%.*]], [[FOR_BODY14_US]] ], [ [[PATLEN]], [[FOR_COND11_PREHEADER_US]] ]
; CHECK-NEXT:    [[K_CORR_036_US:%.*]] = phi float [ 0.000000e+00, [[FOR_COND11_PREHEADER_US]] ], [ [[TMP9:%.*]], [[FOR_BODY14_US]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = load float, ptr [[LSR_IV105]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = load float, ptr [[LSR_IV100]], align 4
; CHECK-NEXT:    [[TMP9]] = tail call float @llvm.fmuladd.f32(float [[TMP7]], float [[TMP8]], float [[K_CORR_036_US]])
; CHECK-NEXT:    [[LSR_IV_NEXT99]] = add i32 [[LSR_IV98]], -1
; CHECK-NEXT:    [[SCEVGEP101]] = getelementptr i8, ptr [[LSR_IV100]], i32 4
; CHECK-NEXT:    [[SCEVGEP106]] = getelementptr i8, ptr [[LSR_IV105]], i32 4
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[LSR_IV_NEXT99]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND11_FOR_COND_CLEANUP13_CRIT_EDGE_US]], label [[FOR_BODY14_US]]
; CHECK:       for.cond11.for.cond.cleanup13_crit_edge.us:
; CHECK-NEXT:    [[ARRAYIDX16_US:%.*]] = getelementptr inbounds float, ptr [[DEST]], i32 [[N_038_US]]
; CHECK-NEXT:    store float [[TMP9]], ptr [[ARRAYIDX16_US]], align 4
; CHECK-NEXT:    [[INC18_US]] = add nuw i32 [[N_038_US]], 1
; CHECK-NEXT:    [[SCEVGEP104]] = getelementptr i8, ptr [[LSR_IV103]], i32 4
; CHECK-NEXT:    [[CMP10_NOT_US_NOT:%.*]] = icmp eq i32 [[INC18_US]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP10_NOT_US_NOT]], label [[RETURN_LOOPEXIT:%.*]], label [[FOR_COND11_PREHEADER_US]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[TMP10:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP58:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    [[TMP11:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP59:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP12:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP60:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP13:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP61:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP14:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP62:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP15:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP63:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP16:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP64:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP17:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP65:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP18:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP66:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP19:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP67:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP20:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP68:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP21:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP69:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP22:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP70:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP23:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP71:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP24:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP72:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP25:%.*]] = phi float [ 0.000000e+00, [[FOR_COND8_PREHEADER]] ], [ [[TMP73:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[ADD89]] = add nuw nsw i32 [[N_0276]], 16
; CHECK-NEXT:    [[ADD:%.*]] = or disjoint i32 [[N_0276]], 1
; CHECK-NEXT:    [[ADD17:%.*]] = or disjoint i32 [[N_0276]], 2
; CHECK-NEXT:    [[ADD19:%.*]] = or disjoint i32 [[N_0276]], 3
; CHECK-NEXT:    [[ADD21:%.*]] = or disjoint i32 [[N_0276]], 4
; CHECK-NEXT:    [[ADD23:%.*]] = or disjoint i32 [[N_0276]], 5
; CHECK-NEXT:    [[ADD25:%.*]] = or disjoint i32 [[N_0276]], 6
; CHECK-NEXT:    [[ADD27:%.*]] = or disjoint i32 [[N_0276]], 7
; CHECK-NEXT:    [[ADD29:%.*]] = or disjoint i32 [[N_0276]], 8
; CHECK-NEXT:    [[ADD31:%.*]] = or disjoint i32 [[N_0276]], 9
; CHECK-NEXT:    [[ADD33:%.*]] = or disjoint i32 [[N_0276]], 10
; CHECK-NEXT:    [[ADD35:%.*]] = or disjoint i32 [[N_0276]], 11
; CHECK-NEXT:    [[ADD37:%.*]] = or disjoint i32 [[N_0276]], 12
; CHECK-NEXT:    [[ADD39:%.*]] = or disjoint i32 [[N_0276]], 13
; CHECK-NEXT:    [[ADD41:%.*]] = or disjoint i32 [[N_0276]], 14
; CHECK-NEXT:    [[ADD43:%.*]] = or disjoint i32 [[N_0276]], 15
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr float, ptr [[DEST]], i32 [[N_0276]]
; CHECK-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD]]
; CHECK-NEXT:    [[ARRAYIDX18:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD17]]
; CHECK-NEXT:    [[ARRAYIDX20:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD19]]
; CHECK-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD21]]
; CHECK-NEXT:    [[ARRAYIDX24:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD23]]
; CHECK-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD25]]
; CHECK-NEXT:    [[ARRAYIDX28:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD27]]
; CHECK-NEXT:    [[ARRAYIDX30:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD29]]
; CHECK-NEXT:    [[ARRAYIDX32:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD31]]
; CHECK-NEXT:    [[ARRAYIDX34:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD33]]
; CHECK-NEXT:    [[ARRAYIDX36:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD35]]
; CHECK-NEXT:    [[ARRAYIDX38:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD37]]
; CHECK-NEXT:    [[ARRAYIDX40:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD39]]
; CHECK-NEXT:    [[ARRAYIDX42:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD41]]
; CHECK-NEXT:    [[ARRAYIDX44:%.*]] = getelementptr float, ptr [[DEST]], i32 [[ADD43]]
; CHECK-NEXT:    store float [[TMP10]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    store float [[TMP11]], ptr [[ARRAYIDX16]], align 4
; CHECK-NEXT:    store float [[TMP12]], ptr [[ARRAYIDX18]], align 4
; CHECK-NEXT:    store float [[TMP13]], ptr [[ARRAYIDX20]], align 4
; CHECK-NEXT:    store float [[TMP14]], ptr [[ARRAYIDX22]], align 4
; CHECK-NEXT:    store float [[TMP15]], ptr [[ARRAYIDX24]], align 4
; CHECK-NEXT:    store float [[TMP16]], ptr [[ARRAYIDX26]], align 4
; CHECK-NEXT:    store float [[TMP17]], ptr [[ARRAYIDX28]], align 4
; CHECK-NEXT:    store float [[TMP18]], ptr [[ARRAYIDX30]], align 4
; CHECK-NEXT:    store float [[TMP19]], ptr [[ARRAYIDX32]], align 4
; CHECK-NEXT:    store float [[TMP20]], ptr [[ARRAYIDX34]], align 4
; CHECK-NEXT:    store float [[TMP21]], ptr [[ARRAYIDX36]], align 4
; CHECK-NEXT:    store float [[TMP22]], ptr [[ARRAYIDX38]], align 4
; CHECK-NEXT:    store float [[TMP23]], ptr [[ARRAYIDX40]], align 4
; CHECK-NEXT:    store float [[TMP24]], ptr [[ARRAYIDX42]], align 4
; CHECK-NEXT:    store float [[TMP25]], ptr [[ARRAYIDX44]], align 4
; CHECK-NEXT:    [[SCEVGEP96]] = getelementptr i8, ptr [[LSR_IV95]], i32 64
; CHECK-NEXT:    [[CMP745:%.*]] = icmp slt i32 [[ADD89]], [[SUB6]]
; CHECK-NEXT:    br i1 [[CMP745]], label [[FOR_COND8_PREHEADER]], label [[FOR_COND91_PREHEADER_LOOPEXIT]]
; CHECK:       for.body14.us.unroll:
; CHECK-NEXT:    [[LSR_IV63:%.*]] = phi i32 [ 0, [[FOR_BODY10_LR_PH]] ], [ [[LSR_IV_NEXT64:%.*]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i32 [ [[PATLEN]], [[FOR_BODY10_LR_PH]] ], [ [[LSR_IV_NEXT:%.*]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[K_CORR_036_US_UNROLL:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP58]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP26:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP59]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP27:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP60]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP28:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP61]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP29:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP62]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP30:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP63]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP31:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP64]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP32:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP65]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP33:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP66]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP34:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP67]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP35:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP68]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP36:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP69]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP37:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP70]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP38:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP71]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP39:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP72]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[TMP40:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY10_LR_PH]] ], [ [[TMP73]], [[FOR_BODY14_US_UNROLL]] ]
; CHECK-NEXT:    [[SCEVGEP94:%.*]] = getelementptr i8, ptr [[PATTERN]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP97:%.*]] = getelementptr i8, ptr [[LSR_IV95]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP93:%.*]] = getelementptr i8, ptr [[SCEVGEP92]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP91:%.*]] = getelementptr i8, ptr [[SCEVGEP90]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP89:%.*]] = getelementptr i8, ptr [[SCEVGEP88]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP87:%.*]] = getelementptr i8, ptr [[SCEVGEP86]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP85:%.*]] = getelementptr i8, ptr [[SCEVGEP84]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP83:%.*]] = getelementptr i8, ptr [[SCEVGEP82]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP81:%.*]] = getelementptr i8, ptr [[SCEVGEP80]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP79:%.*]] = getelementptr i8, ptr [[SCEVGEP78]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP77:%.*]] = getelementptr i8, ptr [[SCEVGEP76]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP75:%.*]] = getelementptr i8, ptr [[SCEVGEP74]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP73:%.*]] = getelementptr i8, ptr [[SCEVGEP72]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP71:%.*]] = getelementptr i8, ptr [[SCEVGEP70]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP69:%.*]] = getelementptr i8, ptr [[SCEVGEP68]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP67:%.*]] = getelementptr i8, ptr [[SCEVGEP66]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[SCEVGEP65:%.*]] = getelementptr i8, ptr [[SCEVGEP62]], i32 [[LSR_IV63]]
; CHECK-NEXT:    [[TMP41:%.*]] = load float, ptr [[SCEVGEP94]], align 4
; CHECK-NEXT:    [[TMP42:%.*]] = load float, ptr [[SCEVGEP97]], align 4
; CHECK-NEXT:    [[TMP43:%.*]] = load float, ptr [[SCEVGEP93]], align 4
; CHECK-NEXT:    [[TMP44:%.*]] = load float, ptr [[SCEVGEP91]], align 4
; CHECK-NEXT:    [[TMP45:%.*]] = load float, ptr [[SCEVGEP89]], align 4
; CHECK-NEXT:    [[TMP46:%.*]] = load float, ptr [[SCEVGEP87]], align 4
; CHECK-NEXT:    [[TMP47:%.*]] = load float, ptr [[SCEVGEP85]], align 4
; CHECK-NEXT:    [[TMP48:%.*]] = load float, ptr [[SCEVGEP83]], align 4
; CHECK-NEXT:    [[TMP49:%.*]] = load float, ptr [[SCEVGEP81]], align 4
; CHECK-NEXT:    [[TMP50:%.*]] = load float, ptr [[SCEVGEP79]], align 4
; CHECK-NEXT:    [[TMP51:%.*]] = load float, ptr [[SCEVGEP77]], align 4
; CHECK-NEXT:    [[TMP52:%.*]] = load float, ptr [[SCEVGEP75]], align 4
; CHECK-NEXT:    [[TMP53:%.*]] = load float, ptr [[SCEVGEP73]], align 4
; CHECK-NEXT:    [[TMP54:%.*]] = load float, ptr [[SCEVGEP71]], align 4
; CHECK-NEXT:    [[TMP55:%.*]] = load float, ptr [[SCEVGEP69]], align 4
; CHECK-NEXT:    [[TMP56:%.*]] = load float, ptr [[SCEVGEP67]], align 4
; CHECK-NEXT:    [[TMP57:%.*]] = load float, ptr [[SCEVGEP65]], align 4
; CHECK-NEXT:    [[TMP58]] = tail call float @llvm.fmuladd.f32(float [[TMP42]], float [[TMP41]], float [[K_CORR_036_US_UNROLL]])
; CHECK-NEXT:    [[TMP59]] = tail call float @llvm.fmuladd.f32(float [[TMP43]], float [[TMP41]], float [[TMP26]])
; CHECK-NEXT:    [[TMP60]] = tail call float @llvm.fmuladd.f32(float [[TMP44]], float [[TMP41]], float [[TMP27]])
; CHECK-NEXT:    [[TMP61]] = tail call float @llvm.fmuladd.f32(float [[TMP45]], float [[TMP41]], float [[TMP28]])
; CHECK-NEXT:    [[TMP62]] = tail call float @llvm.fmuladd.f32(float [[TMP46]], float [[TMP41]], float [[TMP29]])
; CHECK-NEXT:    [[TMP63]] = tail call float @llvm.fmuladd.f32(float [[TMP47]], float [[TMP41]], float [[TMP30]])
; CHECK-NEXT:    [[TMP64]] = tail call float @llvm.fmuladd.f32(float [[TMP48]], float [[TMP41]], float [[TMP31]])
; CHECK-NEXT:    [[TMP65]] = tail call float @llvm.fmuladd.f32(float [[TMP49]], float [[TMP41]], float [[TMP32]])
; CHECK-NEXT:    [[TMP66]] = tail call float @llvm.fmuladd.f32(float [[TMP50]], float [[TMP41]], float [[TMP33]])
; CHECK-NEXT:    [[TMP67]] = tail call float @llvm.fmuladd.f32(float [[TMP51]], float [[TMP41]], float [[TMP34]])
; CHECK-NEXT:    [[TMP68]] = tail call float @llvm.fmuladd.f32(float [[TMP52]], float [[TMP41]], float [[TMP35]])
; CHECK-NEXT:    [[TMP69]] = tail call float @llvm.fmuladd.f32(float [[TMP53]], float [[TMP41]], float [[TMP36]])
; CHECK-NEXT:    [[TMP70]] = tail call float @llvm.fmuladd.f32(float [[TMP54]], float [[TMP41]], float [[TMP37]])
; CHECK-NEXT:    [[TMP71]] = tail call float @llvm.fmuladd.f32(float [[TMP55]], float [[TMP41]], float [[TMP38]])
; CHECK-NEXT:    [[TMP72]] = tail call float @llvm.fmuladd.f32(float [[TMP56]], float [[TMP41]], float [[TMP39]])
; CHECK-NEXT:    [[TMP73]] = tail call float @llvm.fmuladd.f32(float [[TMP57]], float [[TMP41]], float [[TMP40]])
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i32 [[LSR_IV]], -1
; CHECK-NEXT:    [[LSR_IV_NEXT64]] = add nuw i32 [[LSR_IV63]], 4
; CHECK-NEXT:    [[EXITCOND_NOT_UNROLL:%.*]] = icmp eq i32 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_UNROLL]], label [[FOR_COND_CLEANUP_LOOPEXIT]], label [[FOR_BODY14_US_UNROLL]]
; CHECK:       return.loopexit:
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458755, [[ENTRY:%.*]] ], [ 0, [[FOR_COND11_PREHEADER_PREHEADER]] ], [ 0, [[FOR_COND91_PREHEADER]] ], [ 0, [[RETURN_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %Signal, null
  %cmp1 = icmp eq ptr %Pattern, null
  %or.cond = or i1 %cmp, %cmp1
  %cmp4 = icmp eq ptr %dest, null
  %or.cond33 = or i1 %or.cond, %cmp4
  %cmp7 = icmp slt i32 %siglen, %patlen
  %or.cond34 = or i1 %cmp7, %or.cond33
  br i1 %or.cond34, label %return, label %for.cond.preheader

for.cond.preheader:                               ; preds = %entry
  %sub = sub nsw i32 %siglen, %patlen
  %cmp1235.not = icmp eq i32 %patlen, 0
  br i1 %cmp1235.not, label %for.cond11.preheader.preheader, label %for.cond11.preheader.us

for.cond11.preheader.preheader:                   ; preds = %for.cond.preheader
  %0 = shl i32 %siglen, 2
  %1 = add i32 %0, 4
  tail call void @llvm.memset.p0.i32(ptr nonnull align 4 %dest, i8 0, i32 %1, i1 false)
  br label %return

for.cond11.preheader.us:                          ; preds = %for.cond11.for.cond.cleanup13_crit_edge.us, %for.cond.preheader
  %n.038.us = phi i32 [ %inc18.us, %for.cond11.for.cond.cleanup13_crit_edge.us ], [ 0, %for.cond.preheader ]
  %2 = getelementptr float, ptr %Signal, i32 %n.038.us
  br label %for.body14.us

for.body14.us:                                    ; preds = %for.body14.us, %for.cond11.preheader.us
  %m.037.us = phi i32 [ 0, %for.cond11.preheader.us ], [ %inc.us, %for.body14.us ]
  %k_corr.036.us = phi float [ 0.000000e+00, %for.cond11.preheader.us ], [ %5, %for.body14.us ]
  %arrayidx.us = getelementptr float, ptr %2, i32 %m.037.us
  %3 = load float, ptr %arrayidx.us, align 4
  %arrayidx15.us = getelementptr inbounds float, ptr %Pattern, i32 %m.037.us
  %4 = load float, ptr %arrayidx15.us, align 4
  %5 = tail call float @llvm.fmuladd.f32(float %3, float %4, float %k_corr.036.us)
  %inc.us = add nuw i32 %m.037.us, 1
  %exitcond.not = icmp eq i32 %inc.us, %patlen
  br i1 %exitcond.not, label %for.cond11.for.cond.cleanup13_crit_edge.us, label %for.body14.us

for.cond11.for.cond.cleanup13_crit_edge.us:       ; preds = %for.body14.us
  %arrayidx16.us = getelementptr inbounds float, ptr %dest, i32 %n.038.us
  store float %5, ptr %arrayidx16.us, align 4
  %inc18.us = add nuw i32 %n.038.us, 1
  %cmp10.not.us.not = icmp ult i32 %n.038.us, %sub
  br i1 %cmp10.not.us.not, label %for.cond11.preheader.us, label %return

return:                                           ; preds = %for.cond11.for.cond.cleanup13_crit_edge.us, %for.cond11.preheader.preheader, %entry
  %retval.0 = phi i32 [ 458755, %entry ], [ 0, %for.cond11.preheader.preheader ], [ 0, %for.cond11.for.cond.cleanup13_crit_edge.us ]
  ret i32 %retval.0
}
