; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt --dsps-fft2r-fc32-n=64 -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-loop-unroll-and-remainder -riscv-loop-unroll-and-remainder=true < %s | FileCheck %s

@dsps_fft2r_initialized = external dso_local local_unnamed_addr global i8, align 1

; Function Attrs: nounwind
define dso_local noundef i32 @dsps_fft2r_fc32_ansi(ptr nocapture noundef %data, i32 noundef %N, ptr nocapture noundef readonly %w) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local noundef i32 @dsps_fft2r_fc32_ansi(
; CHECK-SAME: ptr noalias noundef captures(none) [[DATA:%.*]], i32 noundef [[N:%.*]], ptr noalias noundef readonly captures(none) [[W:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = tail call zeroext i1 @dsp_is_power_of_two(i32 noundef [[N]])
; CHECK-NEXT:    br i1 [[CALL]], label [[IF_END:%.*]], label [[RETURN:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr @dsps_fft2r_initialized, align 1
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i8 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[RETURN]], label [[IF_END2:%.*]]
; CHECK:       if.end2:
; CHECK-NEXT:    [[CMP103:%.*]] = icmp sgt i32 [[N]], 1
; CHECK-NEXT:    br i1 [[CMP103]], label [[FOR_COND3_PREHEADER:%.*]], label [[RETURN]]
; CHECK:       for.cond3.preheader:
; CHECK-NEXT:    [[N2_0105_IN:%.*]] = phi i32 [ [[N2_0105:%.*]], [[FOR_COND_CLEANUP5:%.*]] ], [ [[N]], [[IF_END2]] ]
; CHECK-NEXT:    [[IE_0104:%.*]] = phi i32 [ [[SHL:%.*]], [[FOR_COND_CLEANUP5]] ], [ 1, [[IF_END2]] ]
; CHECK-NEXT:    [[N2_0105]] = lshr i32 [[N2_0105_IN]], 1
; CHECK-NEXT:    [[CMP4100:%.*]] = icmp sgt i32 [[IE_0104]], 0
; CHECK-NEXT:    br i1 [[CMP4100]], label [[FOR_BODY6_LR_PH:%.*]], label [[FOR_COND_CLEANUP5]]
; CHECK:       for.body6.lr.ph:
; CHECK-NEXT:    [[CMP1097_NOT:%.*]] = icmp ult i32 [[N2_0105_IN]], 2
; CHECK-NEXT:    br label [[FOR_BODY6:%.*]]
; CHECK:       for.cond.cleanup5.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP5]]
; CHECK:       for.cond.cleanup5:
; CHECK-NEXT:    [[SHL]] = shl i32 [[IE_0104]], 1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ult i32 [[N2_0105_IN]], 4
; CHECK-NEXT:    br i1 [[CMP_NOT]], label [[RETURN]], label [[FOR_COND3_PREHEADER]]
; CHECK:       for.body6:
; CHECK-NEXT:    [[J_0102:%.*]] = phi i32 [ 0, [[FOR_BODY6_LR_PH]] ], [ [[INC54:%.*]], [[FOR_COND_CLEANUP11:%.*]] ]
; CHECK-NEXT:    [[IA_0101:%.*]] = phi i32 [ 0, [[FOR_BODY6_LR_PH]] ], [ [[ADD52:%.*]], [[FOR_COND_CLEANUP11]] ]
; CHECK-NEXT:    [[MUL:%.*]] = shl nuw nsw i32 [[J_0102]], 1
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[W]], i32 [[MUL]]
; CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[ADD:%.*]] = or disjoint i32 [[MUL]], 1
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds float, ptr [[W]], i32 [[ADD]]
; CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[ARRAYIDX8]], align 4
; CHECK-NEXT:    br i1 [[CMP1097_NOT]], label [[FOR_COND_CLEANUP11]], label [[FOR_BODY12_LR_PH:%.*]]
; CHECK:       for.body12.lr.ph:
; CHECK-NEXT:    [[TMP3:%.*]] = fneg float [[TMP2]]
; CHECK-NEXT:    br label [[FOR_BODY12:%.*]]
; CHECK:       for.cond.cleanup11.loopexit:
; CHECK-NEXT:    [[INC_LCSSA:%.*]] = phi i32 [ [[INC:%.*]], [[FOR_BODY12]] ], [ [[INC_1:%.*]], [[FOR_BODY12_1:%.*]] ], [ [[INC_2:%.*]], [[FOR_BODY12_2:%.*]] ], [ [[INC_3:%.*]], [[FOR_BODY12_3:%.*]] ]
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP11]]
; CHECK:       for.cond.cleanup11:
; CHECK-NEXT:    [[IA_1_LCSSA:%.*]] = phi i32 [ [[IA_0101]], [[FOR_BODY6]] ], [ [[INC_LCSSA]], [[FOR_COND_CLEANUP11_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    [[ADD52]] = add nsw i32 [[IA_1_LCSSA]], [[N2_0105]]
; CHECK-NEXT:    [[INC54]] = add nuw nsw i32 [[J_0102]], 1
; CHECK-NEXT:    [[EXITCOND106_NOT:%.*]] = icmp eq i32 [[INC54]], [[IE_0104]]
; CHECK-NEXT:    br i1 [[EXITCOND106_NOT]], label [[FOR_COND_CLEANUP5_LOOPEXIT:%.*]], label [[FOR_BODY6]]
; CHECK:       for.body12:
; CHECK-NEXT:    [[I_099:%.*]] = phi i32 [ 0, [[FOR_BODY12_LR_PH]] ], [ [[INC51_3:%.*]], [[FOR_BODY12_3]] ]
; CHECK-NEXT:    [[IA_198:%.*]] = phi i32 [ [[IA_0101]], [[FOR_BODY12_LR_PH]] ], [ [[INC_3]], [[FOR_BODY12_3]] ]
; CHECK-NEXT:    [[ADD13:%.*]] = add nsw i32 [[IA_198]], [[N2_0105]]
; CHECK-NEXT:    [[INC]] = add nsw i32 [[IA_198]], 1
; CHECK-NEXT:    [[INC51:%.*]] = add nuw nsw i32 [[I_099]], 1
; CHECK-NEXT:    [[MUL14:%.*]] = shl nsw i32 [[ADD13]], 1
; CHECK-NEXT:    [[MUL28:%.*]] = shl nsw i32 [[IA_198]], 1
; CHECK-NEXT:    [[ADD18:%.*]] = or disjoint i32 [[MUL14]], 1
; CHECK-NEXT:    [[ADD33:%.*]] = or disjoint i32 [[MUL28]], 1
; CHECK-NEXT:    [[ARRAYIDX15:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[MUL14]]
; CHECK-NEXT:    [[ARRAYIDX19:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[ADD18]]
; CHECK-NEXT:    [[ARRAYIDX29:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[MUL28]]
; CHECK-NEXT:    [[ARRAYIDX34:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[ADD33]]
; CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr [[ARRAYIDX15]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[ARRAYIDX19]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = load float, ptr [[ARRAYIDX29]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = load float, ptr [[ARRAYIDX34]], align 4
; CHECK-NEXT:    [[MUL20:%.*]] = fmul float [[TMP2]], [[TMP5]]
; CHECK-NEXT:    [[NEG:%.*]] = fmul float [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[TMP8:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP4]], float [[MUL20]])
; CHECK-NEXT:    [[TMP9:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP5]], float [[NEG]])
; CHECK-NEXT:    [[ADD41:%.*]] = fadd float [[TMP6]], [[TMP8]]
; CHECK-NEXT:    [[ADD47:%.*]] = fadd float [[TMP9]], [[TMP7]]
; CHECK-NEXT:    [[SUB:%.*]] = fsub float [[TMP6]], [[TMP8]]
; CHECK-NEXT:    [[SUB35:%.*]] = fsub float [[TMP7]], [[TMP9]]
; CHECK-NEXT:    store float [[SUB]], ptr [[ARRAYIDX15]], align 4
; CHECK-NEXT:    store float [[SUB35]], ptr [[ARRAYIDX19]], align 4
; CHECK-NEXT:    store float [[ADD41]], ptr [[ARRAYIDX29]], align 4
; CHECK-NEXT:    store float [[ADD47]], ptr [[ARRAYIDX34]], align 4
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC51]], [[N2_0105]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP11_LOOPEXIT]], label [[FOR_BODY12_1]]
; CHECK:       for.body12.1:
; CHECK-NEXT:    [[ADD13_1:%.*]] = add nsw i32 [[INC]], [[N2_0105]]
; CHECK-NEXT:    [[INC_1]] = add nsw i32 [[IA_198]], 2
; CHECK-NEXT:    [[INC51_1:%.*]] = add nuw nsw i32 [[I_099]], 2
; CHECK-NEXT:    [[MUL14_1:%.*]] = shl nsw i32 [[ADD13_1]], 1
; CHECK-NEXT:    [[MUL28_1:%.*]] = shl nsw i32 [[INC]], 1
; CHECK-NEXT:    [[ADD18_1:%.*]] = or disjoint i32 [[MUL14_1]], 1
; CHECK-NEXT:    [[ADD33_1:%.*]] = or disjoint i32 [[MUL28_1]], 1
; CHECK-NEXT:    [[ARRAYIDX15_1:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[MUL14_1]]
; CHECK-NEXT:    [[ARRAYIDX19_1:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[ADD18_1]]
; CHECK-NEXT:    [[ARRAYIDX29_1:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[MUL28_1]]
; CHECK-NEXT:    [[ARRAYIDX34_1:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[ADD33_1]]
; CHECK-NEXT:    [[TMP10:%.*]] = load float, ptr [[ARRAYIDX15_1]], align 4
; CHECK-NEXT:    [[TMP11:%.*]] = load float, ptr [[ARRAYIDX19_1]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = load float, ptr [[ARRAYIDX29_1]], align 4
; CHECK-NEXT:    [[TMP13:%.*]] = load float, ptr [[ARRAYIDX34_1]], align 4
; CHECK-NEXT:    [[MUL20_1:%.*]] = fmul float [[TMP2]], [[TMP11]]
; CHECK-NEXT:    [[NEG_1:%.*]] = fmul float [[TMP3]], [[TMP10]]
; CHECK-NEXT:    [[TMP14:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP10]], float [[MUL20_1]])
; CHECK-NEXT:    [[TMP15:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP11]], float [[NEG_1]])
; CHECK-NEXT:    [[ADD41_1:%.*]] = fadd float [[TMP12]], [[TMP14]]
; CHECK-NEXT:    [[ADD47_1:%.*]] = fadd float [[TMP15]], [[TMP13]]
; CHECK-NEXT:    [[SUB_1:%.*]] = fsub float [[TMP12]], [[TMP14]]
; CHECK-NEXT:    [[SUB35_1:%.*]] = fsub float [[TMP13]], [[TMP15]]
; CHECK-NEXT:    store float [[SUB_1]], ptr [[ARRAYIDX15_1]], align 4
; CHECK-NEXT:    store float [[SUB35_1]], ptr [[ARRAYIDX19_1]], align 4
; CHECK-NEXT:    store float [[ADD41_1]], ptr [[ARRAYIDX29_1]], align 4
; CHECK-NEXT:    store float [[ADD47_1]], ptr [[ARRAYIDX34_1]], align 4
; CHECK-NEXT:    [[EXITCOND_NOT_1:%.*]] = icmp eq i32 [[INC51_1]], [[N2_0105]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_1]], label [[FOR_COND_CLEANUP11_LOOPEXIT]], label [[FOR_BODY12_2]]
; CHECK:       for.body12.2:
; CHECK-NEXT:    [[ADD13_2:%.*]] = add nsw i32 [[INC_1]], [[N2_0105]]
; CHECK-NEXT:    [[INC_2]] = add nsw i32 [[IA_198]], 3
; CHECK-NEXT:    [[INC51_2:%.*]] = add nuw nsw i32 [[I_099]], 3
; CHECK-NEXT:    [[MUL14_2:%.*]] = shl nsw i32 [[ADD13_2]], 1
; CHECK-NEXT:    [[MUL28_2:%.*]] = shl nsw i32 [[INC_1]], 1
; CHECK-NEXT:    [[ADD18_2:%.*]] = or disjoint i32 [[MUL14_2]], 1
; CHECK-NEXT:    [[ADD33_2:%.*]] = or disjoint i32 [[MUL28_2]], 1
; CHECK-NEXT:    [[ARRAYIDX15_2:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[MUL14_2]]
; CHECK-NEXT:    [[ARRAYIDX19_2:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[ADD18_2]]
; CHECK-NEXT:    [[ARRAYIDX29_2:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[MUL28_2]]
; CHECK-NEXT:    [[ARRAYIDX34_2:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[ADD33_2]]
; CHECK-NEXT:    [[TMP16:%.*]] = load float, ptr [[ARRAYIDX15_2]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = load float, ptr [[ARRAYIDX19_2]], align 4
; CHECK-NEXT:    [[TMP18:%.*]] = load float, ptr [[ARRAYIDX29_2]], align 4
; CHECK-NEXT:    [[TMP19:%.*]] = load float, ptr [[ARRAYIDX34_2]], align 4
; CHECK-NEXT:    [[MUL20_2:%.*]] = fmul float [[TMP2]], [[TMP17]]
; CHECK-NEXT:    [[NEG_2:%.*]] = fmul float [[TMP3]], [[TMP16]]
; CHECK-NEXT:    [[TMP20:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP16]], float [[MUL20_2]])
; CHECK-NEXT:    [[TMP21:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP17]], float [[NEG_2]])
; CHECK-NEXT:    [[ADD41_2:%.*]] = fadd float [[TMP18]], [[TMP20]]
; CHECK-NEXT:    [[ADD47_2:%.*]] = fadd float [[TMP21]], [[TMP19]]
; CHECK-NEXT:    [[SUB_2:%.*]] = fsub float [[TMP18]], [[TMP20]]
; CHECK-NEXT:    [[SUB35_2:%.*]] = fsub float [[TMP19]], [[TMP21]]
; CHECK-NEXT:    store float [[SUB_2]], ptr [[ARRAYIDX15_2]], align 4
; CHECK-NEXT:    store float [[SUB35_2]], ptr [[ARRAYIDX19_2]], align 4
; CHECK-NEXT:    store float [[ADD41_2]], ptr [[ARRAYIDX29_2]], align 4
; CHECK-NEXT:    store float [[ADD47_2]], ptr [[ARRAYIDX34_2]], align 4
; CHECK-NEXT:    [[EXITCOND_NOT_2:%.*]] = icmp eq i32 [[INC51_2]], [[N2_0105]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_2]], label [[FOR_COND_CLEANUP11_LOOPEXIT]], label [[FOR_BODY12_3]]
; CHECK:       for.body12.3:
; CHECK-NEXT:    [[ADD13_3:%.*]] = add nsw i32 [[INC_2]], [[N2_0105]]
; CHECK-NEXT:    [[INC_3]] = add nsw i32 [[IA_198]], 4
; CHECK-NEXT:    [[INC51_3]] = add nuw nsw i32 [[I_099]], 4
; CHECK-NEXT:    [[MUL14_3:%.*]] = shl nsw i32 [[ADD13_3]], 1
; CHECK-NEXT:    [[MUL28_3:%.*]] = shl nsw i32 [[INC_2]], 1
; CHECK-NEXT:    [[ADD18_3:%.*]] = or disjoint i32 [[MUL14_3]], 1
; CHECK-NEXT:    [[ADD33_3:%.*]] = or disjoint i32 [[MUL28_3]], 1
; CHECK-NEXT:    [[ARRAYIDX15_3:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[MUL14_3]]
; CHECK-NEXT:    [[ARRAYIDX19_3:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[ADD18_3]]
; CHECK-NEXT:    [[ARRAYIDX29_3:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[MUL28_3]]
; CHECK-NEXT:    [[ARRAYIDX34_3:%.*]] = getelementptr inbounds float, ptr [[DATA]], i32 [[ADD33_3]]
; CHECK-NEXT:    [[TMP22:%.*]] = load float, ptr [[ARRAYIDX15_3]], align 4
; CHECK-NEXT:    [[TMP23:%.*]] = load float, ptr [[ARRAYIDX19_3]], align 4
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr [[ARRAYIDX29_3]], align 4
; CHECK-NEXT:    [[TMP25:%.*]] = load float, ptr [[ARRAYIDX34_3]], align 4
; CHECK-NEXT:    [[MUL20_3:%.*]] = fmul float [[TMP2]], [[TMP23]]
; CHECK-NEXT:    [[NEG_3:%.*]] = fmul float [[TMP3]], [[TMP22]]
; CHECK-NEXT:    [[TMP26:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP22]], float [[MUL20_3]])
; CHECK-NEXT:    [[TMP27:%.*]] = tail call float @llvm.fmuladd.f32(float [[TMP1]], float [[TMP23]], float [[NEG_3]])
; CHECK-NEXT:    [[ADD41_3:%.*]] = fadd float [[TMP24]], [[TMP26]]
; CHECK-NEXT:    [[ADD47_3:%.*]] = fadd float [[TMP27]], [[TMP25]]
; CHECK-NEXT:    [[SUB_3:%.*]] = fsub float [[TMP24]], [[TMP26]]
; CHECK-NEXT:    [[SUB35_3:%.*]] = fsub float [[TMP25]], [[TMP27]]
; CHECK-NEXT:    store float [[SUB_3]], ptr [[ARRAYIDX15_3]], align 4
; CHECK-NEXT:    store float [[SUB35_3]], ptr [[ARRAYIDX19_3]], align 4
; CHECK-NEXT:    store float [[ADD41_3]], ptr [[ARRAYIDX29_3]], align 4
; CHECK-NEXT:    store float [[ADD47_3]], ptr [[ARRAYIDX34_3]], align 4
; CHECK-NEXT:    [[EXITCOND_NOT_3:%.*]] = icmp eq i32 [[INC51_3]], [[N2_0105]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_3]], label [[FOR_COND_CLEANUP11_LOOPEXIT]], label [[FOR_BODY12]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458753, [[ENTRY:%.*]] ], [ 458756, [[IF_END]] ], [ 0, [[IF_END2]] ], [ 0, [[FOR_COND_CLEANUP5]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %call = tail call zeroext i1 @dsp_is_power_of_two(i32 noundef %N)
  br i1 %call, label %if.end, label %return

if.end:                                           ; preds = %entry
  %0 = load i8, ptr @dsps_fft2r_initialized, align 1
  %tobool.not = icmp eq i8 %0, 0
  br i1 %tobool.not, label %return, label %if.end2

if.end2:                                          ; preds = %if.end
  %cmp103 = icmp sgt i32 %N, 1
  br i1 %cmp103, label %for.cond3.preheader, label %return

for.cond3.preheader:                              ; preds = %for.cond.cleanup5, %if.end2
  %N2.0105.in = phi i32 [ %N2.0105, %for.cond.cleanup5 ], [ %N, %if.end2 ]
  %ie.0104 = phi i32 [ %shl, %for.cond.cleanup5 ], [ 1, %if.end2 ]
  %N2.0105 = lshr i32 %N2.0105.in, 1
  %cmp4100 = icmp sgt i32 %ie.0104, 0
  br i1 %cmp4100, label %for.body6.lr.ph, label %for.cond.cleanup5

for.body6.lr.ph:                                  ; preds = %for.cond3.preheader
  %cmp1097.not = icmp ult i32 %N2.0105.in, 2
  br label %for.body6

for.cond.cleanup5:                                ; preds = %for.cond.cleanup11, %for.cond3.preheader
  %shl = shl i32 %ie.0104, 1
  %cmp.not = icmp ult i32 %N2.0105.in, 4
  br i1 %cmp.not, label %return, label %for.cond3.preheader

for.body6:                                        ; preds = %for.cond.cleanup11, %for.body6.lr.ph
  %j.0102 = phi i32 [ 0, %for.body6.lr.ph ], [ %inc54, %for.cond.cleanup11 ]
  %ia.0101 = phi i32 [ 0, %for.body6.lr.ph ], [ %add52, %for.cond.cleanup11 ]
  %mul = shl nuw nsw i32 %j.0102, 1
  %arrayidx = getelementptr inbounds float, ptr %w, i32 %mul
  %1 = load float, ptr %arrayidx, align 4
  %add = or disjoint i32 %mul, 1
  %arrayidx8 = getelementptr inbounds float, ptr %w, i32 %add
  %2 = load float, ptr %arrayidx8, align 4
  br i1 %cmp1097.not, label %for.cond.cleanup11, label %for.body12.lr.ph

for.body12.lr.ph:                                 ; preds = %for.body6
  %3 = fneg float %2
  br label %for.body12

for.cond.cleanup11:                               ; preds = %for.body12, %for.body6
  %ia.1.lcssa = phi i32 [ %ia.0101, %for.body6 ], [ %inc, %for.body12 ]
  %add52 = add nsw i32 %ia.1.lcssa, %N2.0105
  %inc54 = add nuw nsw i32 %j.0102, 1
  %exitcond106.not = icmp eq i32 %inc54, %ie.0104
  br i1 %exitcond106.not, label %for.cond.cleanup5, label %for.body6

for.body12:                                       ; preds = %for.body12, %for.body12.lr.ph
  %i.099 = phi i32 [ 0, %for.body12.lr.ph ], [ %inc51, %for.body12 ]
  %ia.198 = phi i32 [ %ia.0101, %for.body12.lr.ph ], [ %inc, %for.body12 ]
  %add13 = add nsw i32 %ia.198, %N2.0105
  %inc = add nsw i32 %ia.198, 1
  %inc51 = add nuw nsw i32 %i.099, 1
  %mul14 = shl nsw i32 %add13, 1
  %mul28 = shl nsw i32 %ia.198, 1
  %add18 = or disjoint i32 %mul14, 1
  %add33 = or disjoint i32 %mul28, 1
  %arrayidx15 = getelementptr inbounds float, ptr %data, i32 %mul14
  %arrayidx19 = getelementptr inbounds float, ptr %data, i32 %add18
  %arrayidx29 = getelementptr inbounds float, ptr %data, i32 %mul28
  %arrayidx34 = getelementptr inbounds float, ptr %data, i32 %add33
  %4 = load float, ptr %arrayidx15, align 4
  %5 = load float, ptr %arrayidx19, align 4
  %6 = load float, ptr %arrayidx29, align 4
  %7 = load float, ptr %arrayidx34, align 4
  %mul20 = fmul float %2, %5
  %neg = fmul float %4, %3
  %8 = tail call float @llvm.fmuladd.f32(float %1, float %4, float %mul20)
  %9 = tail call float @llvm.fmuladd.f32(float %1, float %5, float %neg)
  %add41 = fadd float %6, %8
  %add47 = fadd float %9, %7
  %sub = fsub float %6, %8
  %sub35 = fsub float %7, %9
  store float %sub, ptr %arrayidx15, align 4
  store float %sub35, ptr %arrayidx19, align 4
  store float %add41, ptr %arrayidx29, align 4
  store float %add47, ptr %arrayidx34, align 4
  %exitcond.not = icmp eq i32 %inc51, %N2.0105
  br i1 %exitcond.not, label %for.cond.cleanup11, label %for.body12

return:                                           ; preds = %for.cond.cleanup5, %if.end2, %if.end, %entry
  %retval.0 = phi i32 [ 458753, %entry ], [ 458756, %if.end ], [ 0, %if.end2 ], [ 0, %for.cond.cleanup5 ]
  ret i32 %retval.0
}

declare dso_local zeroext i1 @dsp_is_power_of_two(i32 noundef) local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.fmuladd.f32(float, float, float)


