; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-loop-unroll-and-remainder -riscv-loop-unroll-and-remainder=true < %s | FileCheck %s

; Function Attrs: nofree nounwind memory(write)
define dso_local void @dsps_wind_hann_f32(ptr nocapture noundef writeonly %window, i32 noundef %len) local_unnamed_addr {
; CHECK-LABEL: define dso_local void @dsps_wind_hann_f32(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[WINDOW:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP15:%.*]] = icmp sgt i32 [[LEN]], 0
; CHECK-NEXT:    br i1 [[CMP15]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[LEN]], -1
; CHECK-NEXT:    [[CONV:%.*]] = sitofp i32 [[SUB]] to float
; CHECK-NEXT:    [[DIV:%.*]] = fdiv nnan float 1.000000e+00, [[CONV]]
; CHECK-NEXT:    [[CONV4:%.*]] = fpext nnan float [[DIV]] to double
; CHECK-NEXT:    [[MUL1:%.*]] = fmul nnan double [[CONV4]], f0x401921FB54442D18
; CHECK-NEXT:    [[CONV22:%.*]] = fptrunc double [[MUL1]] to float
; CHECK-NEXT:    [[SUB4:%.*]] = add nsw i32 [[LEN]], -7
; CHECK-NEXT:    [[CMP169:%.*]] = icmp sgt i32 [[LEN]], 7
; CHECK-NEXT:    br i1 [[CMP169]], label [[FOR_BODY_7:%.*]], label [[FOR_COND97_PREHEADER:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.cond97.preheader:
; CHECK-NEXT:    [[I_0_LCSSA:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[INC_7:%.*]], [[FOR_BODY_7]] ]
; CHECK-NEXT:    [[CMP98171:%.*]] = icmp slt i32 [[I_0_LCSSA]], [[LEN]]
; CHECK-NEXT:    br i1 [[CMP98171]], label [[FOR_BODY_CLONE:%.*]], label [[FOR_COND_CLEANUP]]
; CHECK:       for.body.7:
; CHECK-NEXT:    [[I_016:%.*]] = phi i32 [ [[INC_7]], [[FOR_BODY_7]] ], [ 0, [[FOR_BODY_LR_PH]] ]
; CHECK-NEXT:    [[CONV5:%.*]] = uitofp nneg i32 [[I_016]] to float
; CHECK-NEXT:    [[MUL6:%.*]] = fmul float [[CONV22]], [[CONV5]]
; CHECK-NEXT:    [[CALL:%.*]] = tail call float @cosf(float noundef [[MUL6]])
; CHECK-NEXT:    [[SUB7:%.*]] = fsub float 1.000000e+00, [[CALL]]
; CHECK-NEXT:    [[CONV10:%.*]] = fmul float [[SUB7]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[WINDOW]], i32 [[I_016]]
; CHECK-NEXT:    store float [[CONV10]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[INC:%.*]] = or disjoint i32 [[I_016]], 1
; CHECK-NEXT:    [[CONV5_1:%.*]] = uitofp nneg i32 [[INC]] to float
; CHECK-NEXT:    [[MUL6_1:%.*]] = fmul nnan float [[CONV22]], [[CONV5_1]]
; CHECK-NEXT:    [[CALL_1:%.*]] = tail call float @cosf(float noundef [[MUL6_1]])
; CHECK-NEXT:    [[SUB7_1:%.*]] = fsub float 1.000000e+00, [[CALL_1]]
; CHECK-NEXT:    [[CONV10_1:%.*]] = fmul float [[SUB7_1]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[WINDOW]], i32 [[INC]]
; CHECK-NEXT:    store float [[CONV10_1]], ptr [[ARRAYIDX_1]], align 4
; CHECK-NEXT:    [[INC_1:%.*]] = or disjoint i32 [[I_016]], 2
; CHECK-NEXT:    [[CONV5_2:%.*]] = uitofp nneg i32 [[INC_1]] to float
; CHECK-NEXT:    [[MUL6_2:%.*]] = fmul nnan float [[CONV22]], [[CONV5_2]]
; CHECK-NEXT:    [[CALL_2:%.*]] = tail call float @cosf(float noundef [[MUL6_2]])
; CHECK-NEXT:    [[SUB7_2:%.*]] = fsub float 1.000000e+00, [[CALL_2]]
; CHECK-NEXT:    [[CONV10_2:%.*]] = fmul float [[SUB7_2]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[WINDOW]], i32 [[INC_1]]
; CHECK-NEXT:    store float [[CONV10_2]], ptr [[ARRAYIDX_2]], align 4
; CHECK-NEXT:    [[INC_2:%.*]] = or disjoint i32 [[I_016]], 3
; CHECK-NEXT:    [[CONV5_3:%.*]] = uitofp nneg i32 [[INC_2]] to float
; CHECK-NEXT:    [[MUL6_3:%.*]] = fmul nnan float [[CONV22]], [[CONV5_3]]
; CHECK-NEXT:    [[CALL_3:%.*]] = tail call float @cosf(float noundef [[MUL6_3]])
; CHECK-NEXT:    [[SUB7_3:%.*]] = fsub float 1.000000e+00, [[CALL_3]]
; CHECK-NEXT:    [[CONV10_3:%.*]] = fmul float [[SUB7_3]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[WINDOW]], i32 [[INC_2]]
; CHECK-NEXT:    store float [[CONV10_3]], ptr [[ARRAYIDX_3]], align 4
; CHECK-NEXT:    [[INC_3:%.*]] = or disjoint i32 [[I_016]], 4
; CHECK-NEXT:    [[CONV5_4:%.*]] = uitofp nneg i32 [[INC_3]] to float
; CHECK-NEXT:    [[MUL6_4:%.*]] = fmul nnan float [[CONV22]], [[CONV5_4]]
; CHECK-NEXT:    [[CALL_4:%.*]] = tail call float @cosf(float noundef [[MUL6_4]])
; CHECK-NEXT:    [[SUB7_4:%.*]] = fsub float 1.000000e+00, [[CALL_4]]
; CHECK-NEXT:    [[CONV10_4:%.*]] = fmul float [[SUB7_4]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[WINDOW]], i32 [[INC_3]]
; CHECK-NEXT:    store float [[CONV10_4]], ptr [[ARRAYIDX_4]], align 4
; CHECK-NEXT:    [[INC_4:%.*]] = or disjoint i32 [[I_016]], 5
; CHECK-NEXT:    [[CONV5_5:%.*]] = uitofp nneg i32 [[INC_4]] to float
; CHECK-NEXT:    [[MUL6_5:%.*]] = fmul nnan float [[CONV22]], [[CONV5_5]]
; CHECK-NEXT:    [[CALL_5:%.*]] = tail call float @cosf(float noundef [[MUL6_5]])
; CHECK-NEXT:    [[SUB7_5:%.*]] = fsub float 1.000000e+00, [[CALL_5]]
; CHECK-NEXT:    [[CONV10_5:%.*]] = fmul float [[SUB7_5]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[WINDOW]], i32 [[INC_4]]
; CHECK-NEXT:    store float [[CONV10_5]], ptr [[ARRAYIDX_5]], align 4
; CHECK-NEXT:    [[INC_5:%.*]] = or disjoint i32 [[I_016]], 6
; CHECK-NEXT:    [[CONV5_6:%.*]] = uitofp nneg i32 [[INC_5]] to float
; CHECK-NEXT:    [[MUL6_6:%.*]] = fmul nnan float [[CONV22]], [[CONV5_6]]
; CHECK-NEXT:    [[CALL_6:%.*]] = tail call float @cosf(float noundef [[MUL6_6]])
; CHECK-NEXT:    [[SUB7_6:%.*]] = fsub float 1.000000e+00, [[CALL_6]]
; CHECK-NEXT:    [[CONV10_6:%.*]] = fmul float [[SUB7_6]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[WINDOW]], i32 [[INC_5]]
; CHECK-NEXT:    store float [[CONV10_6]], ptr [[ARRAYIDX_6]], align 4
; CHECK-NEXT:    [[INC_6:%.*]] = or disjoint i32 [[I_016]], 7
; CHECK-NEXT:    [[CONV5_7:%.*]] = uitofp nneg i32 [[INC_6]] to float
; CHECK-NEXT:    [[MUL6_7:%.*]] = fmul nnan float [[CONV22]], [[CONV5_7]]
; CHECK-NEXT:    [[CALL_7:%.*]] = tail call float @cosf(float noundef [[MUL6_7]])
; CHECK-NEXT:    [[SUB7_7:%.*]] = fsub float 1.000000e+00, [[CALL_7]]
; CHECK-NEXT:    [[CONV10_7:%.*]] = fmul float [[SUB7_7]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds nuw [4 x i8], ptr [[WINDOW]], i32 [[INC_6]]
; CHECK-NEXT:    store float [[CONV10_7]], ptr [[ARRAYIDX_7]], align 4
; CHECK-NEXT:    [[INC_7]] = add nuw nsw i32 [[I_016]], 8
; CHECK-NEXT:    [[EXITCOND_NOT_7:%.*]] = icmp slt i32 [[INC_7]], [[SUB4]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_7]], label [[FOR_BODY_7]], label [[FOR_COND97_PREHEADER]]
; CHECK:       for.body.clone:
; CHECK-NEXT:    [[I_016_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY_CLONE]] ], [ [[I_0_LCSSA]], [[FOR_COND97_PREHEADER]] ]
; CHECK-NEXT:    [[CONV5_CLONE:%.*]] = sitofp i32 [[I_016_CLONE]] to float
; CHECK-NEXT:    [[MUL6_CLONE:%.*]] = fmul float [[CONV22]], [[CONV5_CLONE]]
; CHECK-NEXT:    [[CALL_CLONE:%.*]] = tail call float @cosf(float noundef [[MUL6_CLONE]])
; CHECK-NEXT:    [[SUB7_CLONE:%.*]] = fsub float 1.000000e+00, [[CALL_CLONE]]
; CHECK-NEXT:    [[CONV10_CLONE:%.*]] = fmul float [[SUB7_CLONE]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds [4 x i8], ptr [[WINDOW]], i32 [[I_016_CLONE]]
; CHECK-NEXT:    store float [[CONV10_CLONE]], ptr [[ARRAYIDX_CLONE]], align 4
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[I_016_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY_CLONE]]
;
entry:
  %cmp15 = icmp sgt i32 %len, 0
  br i1 %cmp15, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %sub = add nsw i32 %len, -1
  %conv = sitofp i32 %sub to float
  %div = fdiv float 1.000000e+00, %conv
  %conv4 = fpext float %div to double
  %mul1 = fmul double %conv4, 0x401921FB54442D18
  %conv22 = fptrunc double %mul1 to float
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %i.016 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %conv5 = sitofp i32 %i.016 to float
  %mul6 = fmul float %conv22, %conv5
  %call = tail call float @cosf(float noundef %mul6)
  %sub7 = fsub float 1.000000e+00, %call
  %conv10 = fmul float %sub7, 5.000000e-01
  %arrayidx = getelementptr inbounds float, ptr %window, i32 %i.016
  store float %conv10, ptr %arrayidx, align 4
  %inc = add nuw nsw i32 %i.016, 1
  %exitcond.not = icmp eq i32 %inc, %len
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

; Function Attrs: mustprogress nofree nounwind willreturn memory(write)
declare dso_local float @cosf(float noundef) local_unnamed_addr

