; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-loop-unroll-and-remainder -riscv-loop-unroll-and-remainder=true < %s | FileCheck %s

; Function Attrs: nofree nounwind memory(write)
define dso_local void @dsps_wind_blackman_nuttall_f32(ptr nocapture noundef writeonly %window, i32 noundef %len) local_unnamed_addr {
; CHECK-LABEL: define dso_local void @dsps_wind_blackman_nuttall_f32(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[WINDOW:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP32:%.*]] = icmp sgt i32 [[LEN]], 0
; CHECK-NEXT:    br i1 [[CMP32]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[LEN]], -1
; CHECK-NEXT:    [[CONV:%.*]] = sitofp i32 [[SUB]] to float
; CHECK-NEXT:    [[DIV:%.*]] = fdiv float 1.000000e+00, [[CONV]]
; CHECK-NEXT:    [[CONV4:%.*]] = fpext float [[DIV]] to double
; CHECK-NEXT:    [[MUL1:%.*]] = fmul double [[CONV4]], 0x401921FB54442D18
; CHECK-NEXT:    [[CONV22:%.*]] = fptrunc double [[MUL1]] to float
; CHECK-NEXT:    [[MUL33:%.*]] = fmul float [[CONV22]], 2.000000e+00
; CHECK-NEXT:    [[MUL4:%.*]] = fmul float [[CONV22]], 3.000000e+00
; CHECK-NEXT:    [[SUB4:%.*]] = add nsw i32 [[LEN]], -7
; CHECK-NEXT:    [[CMP169:%.*]] = icmp sgt i32 [[LEN]], 7
; CHECK-NEXT:    br i1 [[CMP169]], label [[FOR_BODY_7:%.*]], label [[FOR_COND97_PREHEADER:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.cond97.preheader:
; CHECK-NEXT:    [[I_0_LCSSA:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[INC_7:%.*]], [[FOR_BODY_7]] ]
; CHECK-NEXT:    [[CMP98171:%.*]] = icmp slt i32 [[I_0_LCSSA]], [[LEN]]
; CHECK-NEXT:    br i1 [[CMP98171]], label [[FOR_BODY_CLONE:%.*]], label [[FOR_COND_CLEANUP]]
; CHECK:       for.body.7:
; CHECK-NEXT:    [[I_033:%.*]] = phi i32 [ [[INC_7]], [[FOR_BODY_7]] ], [ 0, [[FOR_BODY_LR_PH]] ]
; CHECK-NEXT:    [[CONV5:%.*]] = uitofp nneg i32 [[I_033]] to float
; CHECK-NEXT:    [[MUL6:%.*]] = fmul float [[CONV22]], [[CONV5]]
; CHECK-NEXT:    [[CALL:%.*]] = tail call float @cosf(float noundef [[MUL6]])
; CHECK-NEXT:    [[TMP0:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL]], float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
; CHECK-NEXT:    [[MUL9:%.*]] = fmul float [[MUL33]], [[CONV5]]
; CHECK-NEXT:    [[CALL14:%.*]] = tail call float @cosf(float noundef [[MUL9]])
; CHECK-NEXT:    [[TMP1:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL14]], float 0x3FC17C17A0000000, float [[TMP0]])
; CHECK-NEXT:    [[MUL124:%.*]] = fmul float [[MUL4]], [[CONV5]]
; CHECK-NEXT:    [[CALL22:%.*]] = tail call float @cosf(float noundef [[MUL124]])
; CHECK-NEXT:    [[TMP2:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL22]], float 0xBF85CB0040000000, float [[TMP1]])
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw float, ptr [[WINDOW]], i32 [[I_033]]
; CHECK-NEXT:    store float [[TMP2]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[INC:%.*]] = or disjoint i32 [[I_033]], 1
; CHECK-NEXT:    [[CONV5_1:%.*]] = uitofp nneg i32 [[INC]] to float
; CHECK-NEXT:    [[MUL6_1:%.*]] = fmul float [[CONV22]], [[CONV5_1]]
; CHECK-NEXT:    [[CALL_1:%.*]] = tail call float @cosf(float noundef [[MUL6_1]])
; CHECK-NEXT:    [[TMP3:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL_1]], float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
; CHECK-NEXT:    [[MUL9_1:%.*]] = fmul float [[MUL33]], [[CONV5_1]]
; CHECK-NEXT:    [[CALL14_1:%.*]] = tail call float @cosf(float noundef [[MUL9_1]])
; CHECK-NEXT:    [[TMP4:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL14_1]], float 0x3FC17C17A0000000, float [[TMP3]])
; CHECK-NEXT:    [[MUL124_1:%.*]] = fmul float [[MUL4]], [[CONV5_1]]
; CHECK-NEXT:    [[CALL22_1:%.*]] = tail call float @cosf(float noundef [[MUL124_1]])
; CHECK-NEXT:    [[TMP5:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL22_1]], float 0xBF85CB0040000000, float [[TMP4]])
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds nuw float, ptr [[WINDOW]], i32 [[INC]]
; CHECK-NEXT:    store float [[TMP5]], ptr [[ARRAYIDX_1]], align 4
; CHECK-NEXT:    [[INC_1:%.*]] = or disjoint i32 [[I_033]], 2
; CHECK-NEXT:    [[CONV5_2:%.*]] = uitofp nneg i32 [[INC_1]] to float
; CHECK-NEXT:    [[MUL6_2:%.*]] = fmul float [[CONV22]], [[CONV5_2]]
; CHECK-NEXT:    [[CALL_2:%.*]] = tail call float @cosf(float noundef [[MUL6_2]])
; CHECK-NEXT:    [[TMP6:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL_2]], float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
; CHECK-NEXT:    [[MUL9_2:%.*]] = fmul float [[MUL33]], [[CONV5_2]]
; CHECK-NEXT:    [[CALL14_2:%.*]] = tail call float @cosf(float noundef [[MUL9_2]])
; CHECK-NEXT:    [[TMP7:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL14_2]], float 0x3FC17C17A0000000, float [[TMP6]])
; CHECK-NEXT:    [[MUL124_2:%.*]] = fmul float [[MUL4]], [[CONV5_2]]
; CHECK-NEXT:    [[CALL22_2:%.*]] = tail call float @cosf(float noundef [[MUL124_2]])
; CHECK-NEXT:    [[TMP8:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL22_2]], float 0xBF85CB0040000000, float [[TMP7]])
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds nuw float, ptr [[WINDOW]], i32 [[INC_1]]
; CHECK-NEXT:    store float [[TMP8]], ptr [[ARRAYIDX_2]], align 4
; CHECK-NEXT:    [[INC_2:%.*]] = or disjoint i32 [[I_033]], 3
; CHECK-NEXT:    [[CONV5_3:%.*]] = uitofp nneg i32 [[INC_2]] to float
; CHECK-NEXT:    [[MUL6_3:%.*]] = fmul float [[CONV22]], [[CONV5_3]]
; CHECK-NEXT:    [[CALL_3:%.*]] = tail call float @cosf(float noundef [[MUL6_3]])
; CHECK-NEXT:    [[TMP9:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL_3]], float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
; CHECK-NEXT:    [[MUL9_3:%.*]] = fmul float [[MUL33]], [[CONV5_3]]
; CHECK-NEXT:    [[CALL14_3:%.*]] = tail call float @cosf(float noundef [[MUL9_3]])
; CHECK-NEXT:    [[TMP10:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL14_3]], float 0x3FC17C17A0000000, float [[TMP9]])
; CHECK-NEXT:    [[MUL124_3:%.*]] = fmul float [[MUL4]], [[CONV5_3]]
; CHECK-NEXT:    [[CALL22_3:%.*]] = tail call float @cosf(float noundef [[MUL124_3]])
; CHECK-NEXT:    [[TMP11:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL22_3]], float 0xBF85CB0040000000, float [[TMP10]])
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds nuw float, ptr [[WINDOW]], i32 [[INC_2]]
; CHECK-NEXT:    store float [[TMP11]], ptr [[ARRAYIDX_3]], align 4
; CHECK-NEXT:    [[INC_3:%.*]] = or disjoint i32 [[I_033]], 4
; CHECK-NEXT:    [[CONV5_4:%.*]] = uitofp nneg i32 [[INC_3]] to float
; CHECK-NEXT:    [[MUL6_4:%.*]] = fmul float [[CONV22]], [[CONV5_4]]
; CHECK-NEXT:    [[CALL_4:%.*]] = tail call float @cosf(float noundef [[MUL6_4]])
; CHECK-NEXT:    [[TMP12:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL_4]], float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
; CHECK-NEXT:    [[MUL9_4:%.*]] = fmul float [[MUL33]], [[CONV5_4]]
; CHECK-NEXT:    [[CALL14_4:%.*]] = tail call float @cosf(float noundef [[MUL9_4]])
; CHECK-NEXT:    [[TMP13:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL14_4]], float 0x3FC17C17A0000000, float [[TMP12]])
; CHECK-NEXT:    [[MUL124_4:%.*]] = fmul float [[MUL4]], [[CONV5_4]]
; CHECK-NEXT:    [[CALL22_4:%.*]] = tail call float @cosf(float noundef [[MUL124_4]])
; CHECK-NEXT:    [[TMP14:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL22_4]], float 0xBF85CB0040000000, float [[TMP13]])
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds nuw float, ptr [[WINDOW]], i32 [[INC_3]]
; CHECK-NEXT:    store float [[TMP14]], ptr [[ARRAYIDX_4]], align 4
; CHECK-NEXT:    [[INC_4:%.*]] = or disjoint i32 [[I_033]], 5
; CHECK-NEXT:    [[CONV5_5:%.*]] = uitofp nneg i32 [[INC_4]] to float
; CHECK-NEXT:    [[MUL6_5:%.*]] = fmul float [[CONV22]], [[CONV5_5]]
; CHECK-NEXT:    [[CALL_5:%.*]] = tail call float @cosf(float noundef [[MUL6_5]])
; CHECK-NEXT:    [[TMP15:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL_5]], float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
; CHECK-NEXT:    [[MUL9_5:%.*]] = fmul float [[MUL33]], [[CONV5_5]]
; CHECK-NEXT:    [[CALL14_5:%.*]] = tail call float @cosf(float noundef [[MUL9_5]])
; CHECK-NEXT:    [[TMP16:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL14_5]], float 0x3FC17C17A0000000, float [[TMP15]])
; CHECK-NEXT:    [[MUL124_5:%.*]] = fmul float [[MUL4]], [[CONV5_5]]
; CHECK-NEXT:    [[CALL22_5:%.*]] = tail call float @cosf(float noundef [[MUL124_5]])
; CHECK-NEXT:    [[TMP17:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL22_5]], float 0xBF85CB0040000000, float [[TMP16]])
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds nuw float, ptr [[WINDOW]], i32 [[INC_4]]
; CHECK-NEXT:    store float [[TMP17]], ptr [[ARRAYIDX_5]], align 4
; CHECK-NEXT:    [[INC_5:%.*]] = or disjoint i32 [[I_033]], 6
; CHECK-NEXT:    [[CONV5_6:%.*]] = uitofp nneg i32 [[INC_5]] to float
; CHECK-NEXT:    [[MUL6_6:%.*]] = fmul float [[CONV22]], [[CONV5_6]]
; CHECK-NEXT:    [[CALL_6:%.*]] = tail call float @cosf(float noundef [[MUL6_6]])
; CHECK-NEXT:    [[TMP18:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL_6]], float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
; CHECK-NEXT:    [[MUL9_6:%.*]] = fmul float [[MUL33]], [[CONV5_6]]
; CHECK-NEXT:    [[CALL14_6:%.*]] = tail call float @cosf(float noundef [[MUL9_6]])
; CHECK-NEXT:    [[TMP19:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL14_6]], float 0x3FC17C17A0000000, float [[TMP18]])
; CHECK-NEXT:    [[MUL124_6:%.*]] = fmul float [[MUL4]], [[CONV5_6]]
; CHECK-NEXT:    [[CALL22_6:%.*]] = tail call float @cosf(float noundef [[MUL124_6]])
; CHECK-NEXT:    [[TMP20:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL22_6]], float 0xBF85CB0040000000, float [[TMP19]])
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds nuw float, ptr [[WINDOW]], i32 [[INC_5]]
; CHECK-NEXT:    store float [[TMP20]], ptr [[ARRAYIDX_6]], align 4
; CHECK-NEXT:    [[INC_6:%.*]] = or disjoint i32 [[I_033]], 7
; CHECK-NEXT:    [[CONV5_7:%.*]] = uitofp nneg i32 [[INC_6]] to float
; CHECK-NEXT:    [[MUL6_7:%.*]] = fmul float [[CONV22]], [[CONV5_7]]
; CHECK-NEXT:    [[CALL_7:%.*]] = tail call float @cosf(float noundef [[MUL6_7]])
; CHECK-NEXT:    [[TMP21:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL_7]], float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
; CHECK-NEXT:    [[MUL9_7:%.*]] = fmul float [[MUL33]], [[CONV5_7]]
; CHECK-NEXT:    [[CALL14_7:%.*]] = tail call float @cosf(float noundef [[MUL9_7]])
; CHECK-NEXT:    [[TMP22:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL14_7]], float 0x3FC17C17A0000000, float [[TMP21]])
; CHECK-NEXT:    [[MUL124_7:%.*]] = fmul float [[MUL4]], [[CONV5_7]]
; CHECK-NEXT:    [[CALL22_7:%.*]] = tail call float @cosf(float noundef [[MUL124_7]])
; CHECK-NEXT:    [[TMP23:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL22_7]], float 0xBF85CB0040000000, float [[TMP22]])
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds nuw float, ptr [[WINDOW]], i32 [[INC_6]]
; CHECK-NEXT:    store float [[TMP23]], ptr [[ARRAYIDX_7]], align 4
; CHECK-NEXT:    [[INC_7]] = add nuw nsw i32 [[I_033]], 8
; CHECK-NEXT:    [[EXITCOND_NOT_7:%.*]] = icmp slt i32 [[INC_7]], [[SUB4]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_7]], label [[FOR_BODY_7]], label [[FOR_COND97_PREHEADER]]
; CHECK:       for.body.clone:
; CHECK-NEXT:    [[I_033_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY_CLONE]] ], [ [[I_0_LCSSA]], [[FOR_COND97_PREHEADER]] ]
; CHECK-NEXT:    [[CONV5_CLONE:%.*]] = sitofp i32 [[I_033_CLONE]] to float
; CHECK-NEXT:    [[MUL6_CLONE:%.*]] = fmul float [[CONV22]], [[CONV5_CLONE]]
; CHECK-NEXT:    [[CALL_CLONE:%.*]] = tail call float @cosf(float noundef [[MUL6_CLONE]])
; CHECK-NEXT:    [[TMP24:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL_CLONE]], float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
; CHECK-NEXT:    [[MUL9_CLONE:%.*]] = fmul float [[MUL33]], [[CONV5_CLONE]]
; CHECK-NEXT:    [[CALL14_CLONE:%.*]] = tail call float @cosf(float noundef [[MUL9_CLONE]])
; CHECK-NEXT:    [[TMP25:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL14_CLONE]], float 0x3FC17C17A0000000, float [[TMP24]])
; CHECK-NEXT:    [[MUL124_CLONE:%.*]] = fmul float [[MUL4]], [[CONV5_CLONE]]
; CHECK-NEXT:    [[CALL22_CLONE:%.*]] = tail call float @cosf(float noundef [[MUL124_CLONE]])
; CHECK-NEXT:    [[TMP26:%.*]] = tail call float @llvm.fmuladd.f32(float [[CALL22_CLONE]], float 0xBF85CB0040000000, float [[TMP25]])
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds float, ptr [[WINDOW]], i32 [[I_033_CLONE]]
; CHECK-NEXT:    store float [[TMP26]], ptr [[ARRAYIDX_CLONE]], align 4
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[I_033_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY_CLONE]]
;
entry:
  %cmp32 = icmp sgt i32 %len, 0
  br i1 %cmp32, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %sub = add nsw i32 %len, -1
  %conv = sitofp i32 %sub to float
  %div = fdiv float 1.000000e+00, %conv
  %conv4 = fpext float %div to double
  %mul1 = fmul double %conv4, 0x401921FB54442D18
  %conv22 = fptrunc double %mul1 to float
  %mul33 = fmul float %conv22, 2.000000e+00
  %mul4 = fmul float %conv22, 3.000000e+00
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %i.033 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %conv5 = sitofp i32 %i.033 to float
  %mul6 = fmul float %conv22, %conv5
  %call = tail call float @cosf(float noundef %mul6)
  %0 = tail call float @llvm.fmuladd.f32(float %call, float 0xBFDF4EAF20000000, float 0x3FD744ED00000000)
  %mul9 = fmul float %mul33, %conv5
  %call14 = tail call float @cosf(float noundef %mul9)
  %1 = tail call float @llvm.fmuladd.f32(float %call14, float 0x3FC17C17A0000000, float %0)
  %mul124 = fmul float %mul4, %conv5
  %call22 = tail call float @cosf(float noundef %mul124)
  %2 = tail call float @llvm.fmuladd.f32(float %call22, float 0xBF85CB0040000000, float %1)
  %arrayidx = getelementptr inbounds float, ptr %window, i32 %i.033
  store float %2, ptr %arrayidx, align 4
  %inc = add nuw nsw i32 %i.033, 1
  %exitcond.not = icmp eq i32 %inc, %len
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

; Function Attrs: mustprogress nofree nounwind willreturn memory(write)
declare dso_local float @cosf(float noundef) local_unnamed_addr

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare float @llvm.fmuladd.f32(float, float, float)
