; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-loop-unroll-and-remainder -riscv-loop-unroll-and-remainder=true < %s | FileCheck %s
define dso_local noundef i32 @dsps_conv_f32_ansi(ptr noundef readonly %Signal, i32 noundef %siglen, ptr noundef readonly %Kernel, i32 noundef %kernlen, ptr noundef writeonly %convout) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dsps_conv_f32_ansi(
; CHECK-SAME: ptr noalias noundef readonly [[SIGNAL:%.*]], i32 noundef [[SIGLEN:%.*]], ptr noalias noundef readonly [[KERNEL:%.*]], i32 noundef [[KERNLEN:%.*]], ptr noalias noundef writeonly [[CONVOUT:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[SIGNAL]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[KERNEL]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    [[CMP4:%.*]] = icmp eq ptr [[CONVOUT]], null
; CHECK-NEXT:    [[OR_COND118:%.*]] = or i1 [[OR_COND]], [[CMP4]]
; CHECK-NEXT:    br i1 [[OR_COND118]], label [[RETURN:%.*]], label [[IF_END6:%.*]]
; CHECK:       if.end6:
; CHECK-NEXT:    [[CMP7:%.*]] = icmp slt i32 [[SIGLEN]], [[KERNLEN]]
; CHECK-NEXT:    br i1 [[CMP7]], label [[IF_THEN8:%.*]], label [[IF_END9:%.*]]
; CHECK:       if.then8:
; CHECK-NEXT:    br label [[IF_END9]]
; CHECK:       if.end9:
; CHECK-NEXT:    [[LKERN_0:%.*]] = phi i32 [ [[SIGLEN]], [[IF_THEN8]] ], [ [[KERNLEN]], [[IF_END6]] ]
; CHECK-NEXT:    [[LSIG_0:%.*]] = phi i32 [ [[KERNLEN]], [[IF_THEN8]] ], [ [[SIGLEN]], [[IF_END6]] ]
; CHECK-NEXT:    [[KERN_0:%.*]] = phi ptr [ [[SIGNAL]], [[IF_THEN8]] ], [ [[KERNEL]], [[IF_END6]] ]
; CHECK-NEXT:    [[SIG_0:%.*]] = phi ptr [ [[KERNEL]], [[IF_THEN8]] ], [ [[SIGNAL]], [[IF_END6]] ]
; CHECK-NEXT:    [[CMP10120:%.*]] = icmp sgt i32 [[LKERN_0]], 0
; CHECK-NEXT:    br i1 [[CMP10120]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND21_PREHEADER:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond21.preheader.loopexit:
; CHECK-NEXT:    br label [[FOR_COND21_PREHEADER]]
; CHECK:       for.cond21.preheader:
; CHECK-NEXT:    [[CMP22125:%.*]] = icmp slt i32 [[LKERN_0]], [[LSIG_0]]
; CHECK-NEXT:    br i1 [[CMP22125]], label [[FOR_BODY24_PREHEADER:%.*]], label [[FOR_COND42_PREHEADER:%.*]]
; CHECK:       for.body24.preheader:
; CHECK-NEXT:    [[DIV536:%.*]] = and i32 [[LKERN_0]], -16
; CHECK-NEXT:    br label [[FOR_BODY24:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i32 [ [[INDVARS_IV_NEXT:%.*]], [[FOR_END:%.*]] ], [ 1, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[N_0121:%.*]] = phi i32 [ [[INC18:%.*]], [[FOR_END]] ], [ 0, [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = and i32 [[N_0121]], -8
; CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[N_0121]], 2147483640
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i32 [[TMP1]], 0
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[CONVOUT]], i32 [[N_0121]]
; CHECK-NEXT:    br i1 [[TMP2]], label [[FOR_BODY13_CLONE_PREHEADER:%.*]], label [[FOR_BODY13_7:%.*]]
; CHECK:       for.body13.7:
; CHECK-NEXT:    [[K_0119:%.*]] = phi i32 [ 0, [[FOR_BODY]] ], [ [[INC_7:%.*]], [[FOR_BODY13_7]] ]
; CHECK-NEXT:    [[DOTPHI:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY]] ], [ [[TMP19:%.*]], [[FOR_BODY13_7]] ]
; CHECK-NEXT:    [[DOTPHI1:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY]] ], [ [[TMP20:%.*]], [[FOR_BODY13_7]] ]
; CHECK-NEXT:    [[DOTPHI2:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY]] ], [ [[TMP21:%.*]], [[FOR_BODY13_7]] ]
; CHECK-NEXT:    [[DOTPHI3:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY]] ], [ [[TMP22:%.*]], [[FOR_BODY13_7]] ]
; CHECK-NEXT:    [[DOTPHI4:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY]] ], [ [[TMP23:%.*]], [[FOR_BODY13_7]] ]
; CHECK-NEXT:    [[DOTPHI5:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY]] ], [ [[TMP24:%.*]], [[FOR_BODY13_7]] ]
; CHECK-NEXT:    [[DOTPHI6:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY]] ], [ [[TMP25:%.*]], [[FOR_BODY13_7]] ]
; CHECK-NEXT:    [[DOTPHI7:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY]] ], [ [[TMP26:%.*]], [[FOR_BODY13_7]] ]
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i32 [[K_0119]], 1
; CHECK-NEXT:    [[INC_1:%.*]] = add nuw nsw i32 [[K_0119]], 2
; CHECK-NEXT:    [[INC_2:%.*]] = add nuw nsw i32 [[K_0119]], 3
; CHECK-NEXT:    [[INC_3:%.*]] = add nuw nsw i32 [[K_0119]], 4
; CHECK-NEXT:    [[INC_4:%.*]] = add nuw nsw i32 [[K_0119]], 5
; CHECK-NEXT:    [[INC_5:%.*]] = add nuw nsw i32 [[K_0119]], 6
; CHECK-NEXT:    [[INC_6:%.*]] = add nuw nsw i32 [[K_0119]], 7
; CHECK-NEXT:    [[INC_7]] = add nuw nsw i32 [[K_0119]], 8
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[N_0121]], [[K_0119]]
; CHECK-NEXT:    [[SUB_1:%.*]] = sub nsw i32 [[N_0121]], [[INC]]
; CHECK-NEXT:    [[SUB_2:%.*]] = sub nsw i32 [[N_0121]], [[INC_1]]
; CHECK-NEXT:    [[SUB_3:%.*]] = sub nsw i32 [[N_0121]], [[INC_2]]
; CHECK-NEXT:    [[SUB_4:%.*]] = sub nsw i32 [[N_0121]], [[INC_3]]
; CHECK-NEXT:    [[SUB_5:%.*]] = sub nsw i32 [[N_0121]], [[INC_4]]
; CHECK-NEXT:    [[SUB_6:%.*]] = sub nsw i32 [[N_0121]], [[INC_5]]
; CHECK-NEXT:    [[SUB_7:%.*]] = sub nsw i32 [[N_0121]], [[INC_6]]
; CHECK-NEXT:    [[ARRAYIDX14:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K_0119]]
; CHECK-NEXT:    [[ARRAYIDX15:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB]]
; CHECK-NEXT:    [[ARRAYIDX14_1:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[INC]]
; CHECK-NEXT:    [[ARRAYIDX15_1:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB_1]]
; CHECK-NEXT:    [[ARRAYIDX14_2:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[INC_1]]
; CHECK-NEXT:    [[ARRAYIDX15_2:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB_2]]
; CHECK-NEXT:    [[ARRAYIDX14_3:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[INC_2]]
; CHECK-NEXT:    [[ARRAYIDX15_3:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB_3]]
; CHECK-NEXT:    [[ARRAYIDX14_4:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[INC_3]]
; CHECK-NEXT:    [[ARRAYIDX15_4:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB_4]]
; CHECK-NEXT:    [[ARRAYIDX14_5:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[INC_4]]
; CHECK-NEXT:    [[ARRAYIDX15_5:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB_5]]
; CHECK-NEXT:    [[ARRAYIDX14_6:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[INC_5]]
; CHECK-NEXT:    [[ARRAYIDX15_6:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB_6]]
; CHECK-NEXT:    [[ARRAYIDX14_7:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[INC_6]]
; CHECK-NEXT:    [[ARRAYIDX15_7:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB_7]]
; CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[ARRAYIDX14]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = load float, ptr [[ARRAYIDX15]], align 4
; CHECK-NEXT:    [[TMP5:%.*]] = load float, ptr [[ARRAYIDX14_1]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = load float, ptr [[ARRAYIDX15_1]], align 4
; CHECK-NEXT:    [[TMP7:%.*]] = load float, ptr [[ARRAYIDX14_2]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = load float, ptr [[ARRAYIDX15_2]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = load float, ptr [[ARRAYIDX14_3]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = load float, ptr [[ARRAYIDX15_3]], align 4
; CHECK-NEXT:    [[TMP11:%.*]] = load float, ptr [[ARRAYIDX14_4]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = load float, ptr [[ARRAYIDX15_4]], align 4
; CHECK-NEXT:    [[TMP13:%.*]] = load float, ptr [[ARRAYIDX14_5]], align 4
; CHECK-NEXT:    [[TMP14:%.*]] = load float, ptr [[ARRAYIDX15_5]], align 4
; CHECK-NEXT:    [[TMP15:%.*]] = load float, ptr [[ARRAYIDX14_6]], align 4
; CHECK-NEXT:    [[TMP16:%.*]] = load float, ptr [[ARRAYIDX15_6]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = load float, ptr [[ARRAYIDX14_7]], align 4
; CHECK-NEXT:    [[TMP18:%.*]] = load float, ptr [[ARRAYIDX15_7]], align 4
; CHECK-NEXT:    [[TMP19]] = tail call float @llvm.fmuladd.f32(float [[TMP3]], float [[TMP4]], float [[DOTPHI]])
; CHECK-NEXT:    [[TMP20]] = tail call float @llvm.fmuladd.f32(float [[TMP5]], float [[TMP6]], float [[DOTPHI1]])
; CHECK-NEXT:    [[TMP21]] = tail call float @llvm.fmuladd.f32(float [[TMP7]], float [[TMP8]], float [[DOTPHI2]])
; CHECK-NEXT:    [[TMP22]] = tail call float @llvm.fmuladd.f32(float [[TMP9]], float [[TMP10]], float [[DOTPHI3]])
; CHECK-NEXT:    [[TMP23]] = tail call float @llvm.fmuladd.f32(float [[TMP11]], float [[TMP12]], float [[DOTPHI4]])
; CHECK-NEXT:    [[TMP24]] = tail call float @llvm.fmuladd.f32(float [[TMP13]], float [[TMP14]], float [[DOTPHI5]])
; CHECK-NEXT:    [[TMP25]] = tail call float @llvm.fmuladd.f32(float [[TMP15]], float [[TMP16]], float [[DOTPHI6]])
; CHECK-NEXT:    [[TMP26]] = tail call float @llvm.fmuladd.f32(float [[TMP17]], float [[TMP18]], float [[DOTPHI7]])
; CHECK-NEXT:    [[EXITCOND_7:%.*]] = icmp ult i32 [[INC_7]], [[TMP1]]
; CHECK-NEXT:    br i1 [[EXITCOND_7]], label [[FOR_BODY13_7]], label [[FOR_END8:%.*]]
; CHECK:       for.end8:
; CHECK-NEXT:    [[SUM:%.*]] = fadd float [[TMP19]], [[TMP20]]
; CHECK-NEXT:    [[SUM23:%.*]] = fadd float [[TMP21]], [[TMP22]]
; CHECK-NEXT:    [[SUM24:%.*]] = fadd float [[TMP23]], [[TMP24]]
; CHECK-NEXT:    [[SUM25:%.*]] = fadd float [[TMP25]], [[TMP26]]
; CHECK-NEXT:    [[SUM26:%.*]] = fadd float [[SUM]], [[SUM23]]
; CHECK-NEXT:    [[SUM27:%.*]] = fadd float [[SUM24]], [[SUM25]]
; CHECK-NEXT:    [[SUM28:%.*]] = fadd float [[SUM26]], [[SUM27]]
; CHECK-NEXT:    store float [[SUM28]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    br i1 false, label [[FOR_END]], label [[FOR_BODY13_CLONE_PREHEADER]]
; CHECK:       for.body13.clone.preheader:
; CHECK-NEXT:    [[SUM_PHI:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY]] ], [ [[SUM28]], [[FOR_END8]] ]
; CHECK-NEXT:    [[ADD_PHI:%.*]] = phi i32 [ 0, [[FOR_BODY]] ], [ [[TMP0]], [[FOR_END8]] ]
; CHECK-NEXT:    br label [[FOR_BODY13_CLONE:%.*]]
; CHECK:       for.body13.clone:
; CHECK-NEXT:    [[K_0119_CLONE:%.*]] = phi i32 [ [[ADD_PHI]], [[FOR_BODY13_CLONE_PREHEADER]] ], [ [[INC_CLONE:%.*]], [[FOR_BODY13_CLONE]] ]
; CHECK-NEXT:    [[TMP27:%.*]] = phi float [ [[SUM_PHI]], [[FOR_BODY13_CLONE_PREHEADER]] ], [ [[TMP30:%.*]], [[FOR_BODY13_CLONE]] ]
; CHECK-NEXT:    [[ARRAYIDX14_CLONE:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K_0119_CLONE]]
; CHECK-NEXT:    [[TMP28:%.*]] = load float, ptr [[ARRAYIDX14_CLONE]], align 4
; CHECK-NEXT:    [[SUB_CLONE:%.*]] = sub nsw i32 [[N_0121]], [[K_0119_CLONE]]
; CHECK-NEXT:    [[ARRAYIDX15_CLONE:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB_CLONE]]
; CHECK-NEXT:    [[TMP29:%.*]] = load float, ptr [[ARRAYIDX15_CLONE]], align 4
; CHECK-NEXT:    [[TMP30]] = tail call float @llvm.fmuladd.f32(float [[TMP28]], float [[TMP29]], float [[TMP27]])
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[K_0119_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[INDVARS_IV]]
; CHECK-NEXT:    br i1 [[EXITCOND_CLONE]], label [[FOR_COND_FOR_END_CRIT_EDGE:%.*]], label [[FOR_BODY13_CLONE]]
; CHECK:       for.cond.for.end_crit_edge:
; CHECK-NEXT:    store float [[TMP30]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    br label [[FOR_END]]
; CHECK:       for.end:
; CHECK-NEXT:    [[INC18]] = add nuw nsw i32 [[N_0121]], 1
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw i32 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND132_NOT:%.*]] = icmp eq i32 [[INC18]], [[LKERN_0]]
; CHECK-NEXT:    br i1 [[EXITCOND132_NOT]], label [[FOR_COND21_PREHEADER_LOOPEXIT:%.*]], label [[FOR_BODY]]
; CHECK:       for.cond42.preheader.loopexit:
; CHECK-NEXT:    br label [[FOR_COND42_PREHEADER]]
; CHECK:       for.cond42.preheader:
; CHECK-NEXT:    [[ADD43:%.*]] = add i32 [[SIGLEN]], -1
; CHECK-NEXT:    [[SUB44:%.*]] = add i32 [[ADD43]], [[KERNLEN]]
; CHECK-NEXT:    [[CMP45130:%.*]] = icmp slt i32 [[LSIG_0]], [[SUB44]]
; CHECK-NEXT:    br i1 [[CMP45130]], label [[FOR_BODY47_LR_PH:%.*]], label [[RETURN]]
; CHECK:       for.body47.lr.ph:
; CHECK-NEXT:    [[SUB54:%.*]] = add nsw i32 [[LSIG_0]], -1
; CHECK-NEXT:    br label [[FOR_BODY47:%.*]]
; CHECK:       for.body24:
; CHECK-NEXT:    [[N20_0126:%.*]] = phi i32 [ [[INC39:%.*]], [[FOR_END37:%.*]] ], [ [[LKERN_0]], [[FOR_BODY24_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX26:%.*]] = getelementptr inbounds float, ptr [[CONVOUT]], i32 [[N20_0126]]
; CHECK-NEXT:    [[SUB27:%.*]] = sub nuw nsw i32 [[N20_0126]], [[LKERN_0]]
; CHECK-NEXT:    [[K25_0122:%.*]] = add i32 [[SUB27]], 1
; CHECK-NEXT:    [[ADD60:%.*]] = add i32 [[K25_0122]], [[DIV536]]
; CHECK-NEXT:    [[CMP29_NOT123:%.*]] = icmp ult i32 [[K25_0122]], [[ADD60]]
; CHECK-NEXT:    br i1 [[CMP29_NOT123]], label [[FOR_BODY30_PREHEADER:%.*]], label [[FOR_END164:%.*]]
; CHECK:       for.body30.preheader:
; CHECK-NEXT:    br label [[FOR_BODY30_15:%.*]]
; CHECK:       for.body30.15:
; CHECK-NEXT:    [[K25_0124:%.*]] = phi i32 [ [[K25_0122]], [[FOR_BODY30_PREHEADER]] ], [ [[K25_0_15:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI9:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP63:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI10:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP64:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI11:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP65:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI12:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP66:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI13:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP67:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI14:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP68:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI15:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP69:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI16:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP70:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI17:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP71:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI18:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP72:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI19:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP73:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI20:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP74:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI21:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP75:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI22:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP76:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI23:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP77:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[DOTPHI24:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY30_PREHEADER]] ], [ [[TMP78:%.*]], [[FOR_BODY30_15]] ]
; CHECK-NEXT:    [[K25_0:%.*]] = add i32 [[K25_0124]], 1
; CHECK-NEXT:    [[K25_0_1:%.*]] = add i32 [[K25_0124]], 2
; CHECK-NEXT:    [[K25_0_2:%.*]] = add i32 [[K25_0124]], 3
; CHECK-NEXT:    [[K25_0_3:%.*]] = add i32 [[K25_0124]], 4
; CHECK-NEXT:    [[K25_0_4:%.*]] = add i32 [[K25_0124]], 5
; CHECK-NEXT:    [[K25_0_5:%.*]] = add i32 [[K25_0124]], 6
; CHECK-NEXT:    [[K25_0_6:%.*]] = add i32 [[K25_0124]], 7
; CHECK-NEXT:    [[K25_0_7:%.*]] = add i32 [[K25_0124]], 8
; CHECK-NEXT:    [[K25_0_8:%.*]] = add i32 [[K25_0124]], 9
; CHECK-NEXT:    [[K25_0_9:%.*]] = add i32 [[K25_0124]], 10
; CHECK-NEXT:    [[K25_0_10:%.*]] = add i32 [[K25_0124]], 11
; CHECK-NEXT:    [[K25_0_11:%.*]] = add i32 [[K25_0124]], 12
; CHECK-NEXT:    [[K25_0_12:%.*]] = add i32 [[K25_0124]], 13
; CHECK-NEXT:    [[K25_0_13:%.*]] = add i32 [[K25_0124]], 14
; CHECK-NEXT:    [[K25_0_14:%.*]] = add i32 [[K25_0124]], 15
; CHECK-NEXT:    [[K25_0_15]] = add i32 [[K25_0124]], 16
; CHECK-NEXT:    [[SUB32:%.*]] = sub i32 [[N20_0126]], [[K25_0124]]
; CHECK-NEXT:    [[SUB32_1:%.*]] = sub i32 [[N20_0126]], [[K25_0]]
; CHECK-NEXT:    [[SUB32_2:%.*]] = sub i32 [[N20_0126]], [[K25_0_1]]
; CHECK-NEXT:    [[SUB32_3:%.*]] = sub i32 [[N20_0126]], [[K25_0_2]]
; CHECK-NEXT:    [[SUB32_4:%.*]] = sub i32 [[N20_0126]], [[K25_0_3]]
; CHECK-NEXT:    [[SUB32_5:%.*]] = sub i32 [[N20_0126]], [[K25_0_4]]
; CHECK-NEXT:    [[SUB32_6:%.*]] = sub i32 [[N20_0126]], [[K25_0_5]]
; CHECK-NEXT:    [[SUB32_7:%.*]] = sub i32 [[N20_0126]], [[K25_0_6]]
; CHECK-NEXT:    [[SUB32_8:%.*]] = sub i32 [[N20_0126]], [[K25_0_7]]
; CHECK-NEXT:    [[SUB32_9:%.*]] = sub i32 [[N20_0126]], [[K25_0_8]]
; CHECK-NEXT:    [[SUB32_10:%.*]] = sub i32 [[N20_0126]], [[K25_0_9]]
; CHECK-NEXT:    [[SUB32_11:%.*]] = sub i32 [[N20_0126]], [[K25_0_10]]
; CHECK-NEXT:    [[SUB32_12:%.*]] = sub i32 [[N20_0126]], [[K25_0_11]]
; CHECK-NEXT:    [[SUB32_13:%.*]] = sub i32 [[N20_0126]], [[K25_0_12]]
; CHECK-NEXT:    [[SUB32_14:%.*]] = sub i32 [[N20_0126]], [[K25_0_13]]
; CHECK-NEXT:    [[SUB32_15:%.*]] = sub i32 [[N20_0126]], [[K25_0_14]]
; CHECK-NEXT:    [[ARRAYIDX31:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0124]]
; CHECK-NEXT:    [[ARRAYIDX33:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32]]
; CHECK-NEXT:    [[ARRAYIDX31_1:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0]]
; CHECK-NEXT:    [[ARRAYIDX33_1:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_1]]
; CHECK-NEXT:    [[ARRAYIDX31_2:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_1]]
; CHECK-NEXT:    [[ARRAYIDX33_2:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_2]]
; CHECK-NEXT:    [[ARRAYIDX31_3:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_2]]
; CHECK-NEXT:    [[ARRAYIDX33_3:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_3]]
; CHECK-NEXT:    [[ARRAYIDX31_4:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_3]]
; CHECK-NEXT:    [[ARRAYIDX33_4:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_4]]
; CHECK-NEXT:    [[ARRAYIDX31_5:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_4]]
; CHECK-NEXT:    [[ARRAYIDX33_5:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_5]]
; CHECK-NEXT:    [[ARRAYIDX31_6:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_5]]
; CHECK-NEXT:    [[ARRAYIDX33_6:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_6]]
; CHECK-NEXT:    [[ARRAYIDX31_7:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_6]]
; CHECK-NEXT:    [[ARRAYIDX33_7:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_7]]
; CHECK-NEXT:    [[ARRAYIDX31_8:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_7]]
; CHECK-NEXT:    [[ARRAYIDX33_8:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_8]]
; CHECK-NEXT:    [[ARRAYIDX31_9:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_8]]
; CHECK-NEXT:    [[ARRAYIDX33_9:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_9]]
; CHECK-NEXT:    [[ARRAYIDX31_10:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_9]]
; CHECK-NEXT:    [[ARRAYIDX33_10:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_10]]
; CHECK-NEXT:    [[ARRAYIDX31_11:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_10]]
; CHECK-NEXT:    [[ARRAYIDX33_11:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_11]]
; CHECK-NEXT:    [[ARRAYIDX31_12:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_11]]
; CHECK-NEXT:    [[ARRAYIDX33_12:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_12]]
; CHECK-NEXT:    [[ARRAYIDX31_13:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_12]]
; CHECK-NEXT:    [[ARRAYIDX33_13:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_13]]
; CHECK-NEXT:    [[ARRAYIDX31_14:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_13]]
; CHECK-NEXT:    [[ARRAYIDX33_14:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_14]]
; CHECK-NEXT:    [[ARRAYIDX31_15:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0_14]]
; CHECK-NEXT:    [[ARRAYIDX33_15:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_15]]
; CHECK-NEXT:    [[TMP31:%.*]] = load float, ptr [[ARRAYIDX31]], align 4
; CHECK-NEXT:    [[TMP32:%.*]] = load float, ptr [[ARRAYIDX33]], align 4
; CHECK-NEXT:    [[TMP33:%.*]] = load float, ptr [[ARRAYIDX31_1]], align 4
; CHECK-NEXT:    [[TMP34:%.*]] = load float, ptr [[ARRAYIDX33_1]], align 4
; CHECK-NEXT:    [[TMP35:%.*]] = load float, ptr [[ARRAYIDX31_2]], align 4
; CHECK-NEXT:    [[TMP36:%.*]] = load float, ptr [[ARRAYIDX33_2]], align 4
; CHECK-NEXT:    [[TMP37:%.*]] = load float, ptr [[ARRAYIDX31_3]], align 4
; CHECK-NEXT:    [[TMP38:%.*]] = load float, ptr [[ARRAYIDX33_3]], align 4
; CHECK-NEXT:    [[TMP39:%.*]] = load float, ptr [[ARRAYIDX31_4]], align 4
; CHECK-NEXT:    [[TMP40:%.*]] = load float, ptr [[ARRAYIDX33_4]], align 4
; CHECK-NEXT:    [[TMP41:%.*]] = load float, ptr [[ARRAYIDX31_5]], align 4
; CHECK-NEXT:    [[TMP42:%.*]] = load float, ptr [[ARRAYIDX33_5]], align 4
; CHECK-NEXT:    [[TMP43:%.*]] = load float, ptr [[ARRAYIDX31_6]], align 4
; CHECK-NEXT:    [[TMP44:%.*]] = load float, ptr [[ARRAYIDX33_6]], align 4
; CHECK-NEXT:    [[TMP45:%.*]] = load float, ptr [[ARRAYIDX31_7]], align 4
; CHECK-NEXT:    [[TMP46:%.*]] = load float, ptr [[ARRAYIDX33_7]], align 4
; CHECK-NEXT:    [[TMP47:%.*]] = load float, ptr [[ARRAYIDX31_8]], align 4
; CHECK-NEXT:    [[TMP48:%.*]] = load float, ptr [[ARRAYIDX33_8]], align 4
; CHECK-NEXT:    [[TMP49:%.*]] = load float, ptr [[ARRAYIDX31_9]], align 4
; CHECK-NEXT:    [[TMP50:%.*]] = load float, ptr [[ARRAYIDX33_9]], align 4
; CHECK-NEXT:    [[TMP51:%.*]] = load float, ptr [[ARRAYIDX31_10]], align 4
; CHECK-NEXT:    [[TMP52:%.*]] = load float, ptr [[ARRAYIDX33_10]], align 4
; CHECK-NEXT:    [[TMP53:%.*]] = load float, ptr [[ARRAYIDX31_11]], align 4
; CHECK-NEXT:    [[TMP54:%.*]] = load float, ptr [[ARRAYIDX33_11]], align 4
; CHECK-NEXT:    [[TMP55:%.*]] = load float, ptr [[ARRAYIDX31_12]], align 4
; CHECK-NEXT:    [[TMP56:%.*]] = load float, ptr [[ARRAYIDX33_12]], align 4
; CHECK-NEXT:    [[TMP57:%.*]] = load float, ptr [[ARRAYIDX31_13]], align 4
; CHECK-NEXT:    [[TMP58:%.*]] = load float, ptr [[ARRAYIDX33_13]], align 4
; CHECK-NEXT:    [[TMP59:%.*]] = load float, ptr [[ARRAYIDX31_14]], align 4
; CHECK-NEXT:    [[TMP60:%.*]] = load float, ptr [[ARRAYIDX33_14]], align 4
; CHECK-NEXT:    [[TMP61:%.*]] = load float, ptr [[ARRAYIDX31_15]], align 4
; CHECK-NEXT:    [[TMP62:%.*]] = load float, ptr [[ARRAYIDX33_15]], align 4
; CHECK-NEXT:    [[TMP63]] = tail call float @llvm.fmuladd.f32(float [[TMP31]], float [[TMP32]], float [[DOTPHI9]])
; CHECK-NEXT:    [[TMP64]] = tail call float @llvm.fmuladd.f32(float [[TMP33]], float [[TMP34]], float [[DOTPHI10]])
; CHECK-NEXT:    [[TMP65]] = tail call float @llvm.fmuladd.f32(float [[TMP35]], float [[TMP36]], float [[DOTPHI11]])
; CHECK-NEXT:    [[TMP66]] = tail call float @llvm.fmuladd.f32(float [[TMP37]], float [[TMP38]], float [[DOTPHI12]])
; CHECK-NEXT:    [[TMP67]] = tail call float @llvm.fmuladd.f32(float [[TMP39]], float [[TMP40]], float [[DOTPHI13]])
; CHECK-NEXT:    [[TMP68]] = tail call float @llvm.fmuladd.f32(float [[TMP41]], float [[TMP42]], float [[DOTPHI14]])
; CHECK-NEXT:    [[TMP69]] = tail call float @llvm.fmuladd.f32(float [[TMP43]], float [[TMP44]], float [[DOTPHI15]])
; CHECK-NEXT:    [[TMP70]] = tail call float @llvm.fmuladd.f32(float [[TMP45]], float [[TMP46]], float [[DOTPHI16]])
; CHECK-NEXT:    [[TMP71]] = tail call float @llvm.fmuladd.f32(float [[TMP47]], float [[TMP48]], float [[DOTPHI17]])
; CHECK-NEXT:    [[TMP72]] = tail call float @llvm.fmuladd.f32(float [[TMP49]], float [[TMP50]], float [[DOTPHI18]])
; CHECK-NEXT:    [[TMP73]] = tail call float @llvm.fmuladd.f32(float [[TMP51]], float [[TMP52]], float [[DOTPHI19]])
; CHECK-NEXT:    [[TMP74]] = tail call float @llvm.fmuladd.f32(float [[TMP53]], float [[TMP54]], float [[DOTPHI20]])
; CHECK-NEXT:    [[TMP75]] = tail call float @llvm.fmuladd.f32(float [[TMP55]], float [[TMP56]], float [[DOTPHI21]])
; CHECK-NEXT:    [[TMP76]] = tail call float @llvm.fmuladd.f32(float [[TMP57]], float [[TMP58]], float [[DOTPHI22]])
; CHECK-NEXT:    [[TMP77]] = tail call float @llvm.fmuladd.f32(float [[TMP59]], float [[TMP60]], float [[DOTPHI23]])
; CHECK-NEXT:    [[TMP78]] = tail call float @llvm.fmuladd.f32(float [[TMP61]], float [[TMP62]], float [[DOTPHI24]])
; CHECK-NEXT:    [[CMP29_NOT_15:%.*]] = icmp ult i32 [[K25_0_15]], [[ADD60]]
; CHECK-NEXT:    br i1 [[CMP29_NOT_15]], label [[FOR_BODY30_15]], label [[FOR_END37_LOOPEXIT:%.*]]
; CHECK:       for.end37.loopexit:
; CHECK-NEXT:    [[SUM45:%.*]] = fadd float [[TMP63]], [[TMP64]]
; CHECK-NEXT:    [[SUM46:%.*]] = fadd float [[TMP65]], [[TMP66]]
; CHECK-NEXT:    [[SUM47:%.*]] = fadd float [[TMP67]], [[TMP68]]
; CHECK-NEXT:    [[SUM48:%.*]] = fadd float [[TMP69]], [[TMP70]]
; CHECK-NEXT:    [[SUM49:%.*]] = fadd float [[TMP71]], [[TMP72]]
; CHECK-NEXT:    [[SUM50:%.*]] = fadd float [[TMP73]], [[TMP74]]
; CHECK-NEXT:    [[SUM51:%.*]] = fadd float [[TMP75]], [[TMP76]]
; CHECK-NEXT:    [[SUM52:%.*]] = fadd float [[TMP77]], [[TMP78]]
; CHECK-NEXT:    [[SUM53:%.*]] = fadd float [[SUM45]], [[SUM46]]
; CHECK-NEXT:    [[SUM54:%.*]] = fadd float [[SUM47]], [[SUM48]]
; CHECK-NEXT:    [[SUM55:%.*]] = fadd float [[SUM49]], [[SUM50]]
; CHECK-NEXT:    [[SUM56:%.*]] = fadd float [[SUM51]], [[SUM52]]
; CHECK-NEXT:    [[SUM57:%.*]] = fadd float [[SUM53]], [[SUM54]]
; CHECK-NEXT:    [[SUM58:%.*]] = fadd float [[SUM55]], [[SUM56]]
; CHECK-NEXT:    [[SUM59:%.*]] = fadd float [[SUM57]], [[SUM58]]
; CHECK-NEXT:    br label [[FOR_END164]]
; CHECK:       for.end164:
; CHECK-NEXT:    [[PHI_SUM:%.*]] = phi i32 [ [[K25_0122]], [[FOR_BODY24]] ], [ [[K25_0_15]], [[FOR_END37_LOOPEXIT]] ]
; CHECK-NEXT:    [[PHI_FLOAT:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY24]] ], [ [[SUM59]], [[FOR_END37_LOOPEXIT]] ]
; CHECK-NEXT:    store float [[PHI_FLOAT]], ptr [[ARRAYIDX26]], align 4
; CHECK-NEXT:    [[CMP182_NOT587:%.*]] = icmp ugt i32 [[PHI_SUM]], [[N20_0126]]
; CHECK-NEXT:    br i1 [[CMP182_NOT587]], label [[FOR_END37]], label [[FOR_BODY30_CLONE:%.*]]
; CHECK:       for.body30.clone:
; CHECK-NEXT:    [[TMP79:%.*]] = phi float [ [[TMP82:%.*]], [[FOR_BODY30_CLONE]] ], [ [[PHI_FLOAT]], [[FOR_END164]] ]
; CHECK-NEXT:    [[K25_0124_CLONE:%.*]] = phi i32 [ [[K25_0_CLONE:%.*]], [[FOR_BODY30_CLONE]] ], [ [[PHI_SUM]], [[FOR_END164]] ]
; CHECK-NEXT:    [[ARRAYIDX31_CLONE:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K25_0124_CLONE]]
; CHECK-NEXT:    [[TMP80:%.*]] = load float, ptr [[ARRAYIDX31_CLONE]], align 4
; CHECK-NEXT:    [[SUB32_CLONE:%.*]] = sub i32 [[N20_0126]], [[K25_0124_CLONE]]
; CHECK-NEXT:    [[ARRAYIDX33_CLONE:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB32_CLONE]]
; CHECK-NEXT:    [[TMP81:%.*]] = load float, ptr [[ARRAYIDX33_CLONE]], align 4
; CHECK-NEXT:    [[TMP82]] = tail call float @llvm.fmuladd.f32(float [[TMP80]], float [[TMP81]], float [[TMP79]])
; CHECK-NEXT:    [[K25_0_CLONE]] = add i32 [[K25_0124_CLONE]], 1
; CHECK-NEXT:    [[CMP29_NOT_CLONE:%.*]] = icmp ugt i32 [[K25_0_CLONE]], [[N20_0126]]
; CHECK-NEXT:    br i1 [[CMP29_NOT_CLONE]], label [[FOR_COND_FOR_END_CRIT_EDGE25:%.*]], label [[FOR_BODY30_CLONE]]
; CHECK:       for.cond.for.end_crit_edge25:
; CHECK-NEXT:    store float [[TMP82]], ptr [[ARRAYIDX26]], align 4
; CHECK-NEXT:    br label [[FOR_END37]]
; CHECK:       for.end37:
; CHECK-NEXT:    [[INC39]] = add nuw nsw i32 [[N20_0126]], 1
; CHECK-NEXT:    [[EXITCOND133_NOT:%.*]] = icmp eq i32 [[INC39]], [[LSIG_0]]
; CHECK-NEXT:    br i1 [[EXITCOND133_NOT]], label [[FOR_COND42_PREHEADER_LOOPEXIT:%.*]], label [[FOR_BODY24]]
; CHECK:       for.body47:
; CHECK-NEXT:    [[N41_0131:%.*]] = phi i32 [ [[LSIG_0]], [[FOR_BODY47_LR_PH]] ], [ [[INC66:%.*]], [[FOR_END64:%.*]] ]
; CHECK-NEXT:    [[ARRAYIDX51:%.*]] = getelementptr inbounds float, ptr [[CONVOUT]], i32 [[N41_0131]]
; CHECK-NEXT:    [[SUB52:%.*]] = sub nsw i32 [[N41_0131]], [[LKERN_0]]
; CHECK-NEXT:    [[K50_0127:%.*]] = add i32 [[SUB52]], 1
; CHECK-NEXT:    [[ADD207_NEG:%.*]] = xor i32 [[SUB52]], -1
; CHECK-NEXT:    [[ADD211:%.*]] = add i32 [[ADD207_NEG]], [[LSIG_0]]
; CHECK-NEXT:    [[DIV212535:%.*]] = and i32 [[ADD211]], -8
; CHECK-NEXT:    [[ADD214:%.*]] = add i32 [[DIV212535]], [[K50_0127]]
; CHECK-NEXT:    [[CMP56_NOT128:%.*]] = icmp ult i32 [[K50_0127]], [[ADD214]]
; CHECK-NEXT:    br i1 [[CMP56_NOT128]], label [[FOR_BODY57_PREHEADER:%.*]], label [[FOR_END16434:%.*]]
; CHECK:       for.body57.preheader:
; CHECK-NEXT:    br label [[FOR_BODY57_7:%.*]]
; CHECK:       for.body57.7:
; CHECK-NEXT:    [[K50_0129:%.*]] = phi i32 [ [[K50_0127]], [[FOR_BODY57_PREHEADER]] ], [ [[K50_0_7:%.*]], [[FOR_BODY57_7]] ]
; CHECK-NEXT:    [[DOTPHI26:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY57_PREHEADER]] ], [ [[TMP99:%.*]], [[FOR_BODY57_7]] ]
; CHECK-NEXT:    [[DOTPHI27:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY57_PREHEADER]] ], [ [[TMP100:%.*]], [[FOR_BODY57_7]] ]
; CHECK-NEXT:    [[DOTPHI28:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY57_PREHEADER]] ], [ [[TMP101:%.*]], [[FOR_BODY57_7]] ]
; CHECK-NEXT:    [[DOTPHI29:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY57_PREHEADER]] ], [ [[TMP102:%.*]], [[FOR_BODY57_7]] ]
; CHECK-NEXT:    [[DOTPHI30:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY57_PREHEADER]] ], [ [[TMP103:%.*]], [[FOR_BODY57_7]] ]
; CHECK-NEXT:    [[DOTPHI31:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY57_PREHEADER]] ], [ [[TMP104:%.*]], [[FOR_BODY57_7]] ]
; CHECK-NEXT:    [[DOTPHI32:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY57_PREHEADER]] ], [ [[TMP105:%.*]], [[FOR_BODY57_7]] ]
; CHECK-NEXT:    [[DOTPHI33:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY57_PREHEADER]] ], [ [[TMP106:%.*]], [[FOR_BODY57_7]] ]
; CHECK-NEXT:    [[K50_0:%.*]] = add i32 [[K50_0129]], 1
; CHECK-NEXT:    [[K50_0_1:%.*]] = add i32 [[K50_0129]], 2
; CHECK-NEXT:    [[K50_0_2:%.*]] = add i32 [[K50_0129]], 3
; CHECK-NEXT:    [[K50_0_3:%.*]] = add i32 [[K50_0129]], 4
; CHECK-NEXT:    [[K50_0_4:%.*]] = add i32 [[K50_0129]], 5
; CHECK-NEXT:    [[K50_0_5:%.*]] = add i32 [[K50_0129]], 6
; CHECK-NEXT:    [[K50_0_6:%.*]] = add i32 [[K50_0129]], 7
; CHECK-NEXT:    [[K50_0_7]] = add i32 [[K50_0129]], 8
; CHECK-NEXT:    [[SUB59:%.*]] = sub i32 [[N41_0131]], [[K50_0129]]
; CHECK-NEXT:    [[SUB59_1:%.*]] = sub i32 [[N41_0131]], [[K50_0]]
; CHECK-NEXT:    [[SUB59_2:%.*]] = sub i32 [[N41_0131]], [[K50_0_1]]
; CHECK-NEXT:    [[SUB59_3:%.*]] = sub i32 [[N41_0131]], [[K50_0_2]]
; CHECK-NEXT:    [[SUB59_4:%.*]] = sub i32 [[N41_0131]], [[K50_0_3]]
; CHECK-NEXT:    [[SUB59_5:%.*]] = sub i32 [[N41_0131]], [[K50_0_4]]
; CHECK-NEXT:    [[SUB59_6:%.*]] = sub i32 [[N41_0131]], [[K50_0_5]]
; CHECK-NEXT:    [[SUB59_7:%.*]] = sub i32 [[N41_0131]], [[K50_0_6]]
; CHECK-NEXT:    [[ARRAYIDX58:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K50_0129]]
; CHECK-NEXT:    [[ARRAYIDX60:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB59]]
; CHECK-NEXT:    [[ARRAYIDX58_1:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K50_0]]
; CHECK-NEXT:    [[ARRAYIDX60_1:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB59_1]]
; CHECK-NEXT:    [[ARRAYIDX58_2:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K50_0_1]]
; CHECK-NEXT:    [[ARRAYIDX60_2:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB59_2]]
; CHECK-NEXT:    [[ARRAYIDX58_3:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K50_0_2]]
; CHECK-NEXT:    [[ARRAYIDX60_3:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB59_3]]
; CHECK-NEXT:    [[ARRAYIDX58_4:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K50_0_3]]
; CHECK-NEXT:    [[ARRAYIDX60_4:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB59_4]]
; CHECK-NEXT:    [[ARRAYIDX58_5:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K50_0_4]]
; CHECK-NEXT:    [[ARRAYIDX60_5:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB59_5]]
; CHECK-NEXT:    [[ARRAYIDX58_6:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K50_0_5]]
; CHECK-NEXT:    [[ARRAYIDX60_6:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB59_6]]
; CHECK-NEXT:    [[ARRAYIDX58_7:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K50_0_6]]
; CHECK-NEXT:    [[ARRAYIDX60_7:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB59_7]]
; CHECK-NEXT:    [[TMP83:%.*]] = load float, ptr [[ARRAYIDX58]], align 4
; CHECK-NEXT:    [[TMP84:%.*]] = load float, ptr [[ARRAYIDX60]], align 4
; CHECK-NEXT:    [[TMP85:%.*]] = load float, ptr [[ARRAYIDX58_1]], align 4
; CHECK-NEXT:    [[TMP86:%.*]] = load float, ptr [[ARRAYIDX60_1]], align 4
; CHECK-NEXT:    [[TMP87:%.*]] = load float, ptr [[ARRAYIDX58_2]], align 4
; CHECK-NEXT:    [[TMP88:%.*]] = load float, ptr [[ARRAYIDX60_2]], align 4
; CHECK-NEXT:    [[TMP89:%.*]] = load float, ptr [[ARRAYIDX58_3]], align 4
; CHECK-NEXT:    [[TMP90:%.*]] = load float, ptr [[ARRAYIDX60_3]], align 4
; CHECK-NEXT:    [[TMP91:%.*]] = load float, ptr [[ARRAYIDX58_4]], align 4
; CHECK-NEXT:    [[TMP92:%.*]] = load float, ptr [[ARRAYIDX60_4]], align 4
; CHECK-NEXT:    [[TMP93:%.*]] = load float, ptr [[ARRAYIDX58_5]], align 4
; CHECK-NEXT:    [[TMP94:%.*]] = load float, ptr [[ARRAYIDX60_5]], align 4
; CHECK-NEXT:    [[TMP95:%.*]] = load float, ptr [[ARRAYIDX58_6]], align 4
; CHECK-NEXT:    [[TMP96:%.*]] = load float, ptr [[ARRAYIDX60_6]], align 4
; CHECK-NEXT:    [[TMP97:%.*]] = load float, ptr [[ARRAYIDX58_7]], align 4
; CHECK-NEXT:    [[TMP98:%.*]] = load float, ptr [[ARRAYIDX60_7]], align 4
; CHECK-NEXT:    [[TMP99]] = tail call float @llvm.fmuladd.f32(float [[TMP83]], float [[TMP84]], float [[DOTPHI26]])
; CHECK-NEXT:    [[TMP100]] = tail call float @llvm.fmuladd.f32(float [[TMP85]], float [[TMP86]], float [[DOTPHI27]])
; CHECK-NEXT:    [[TMP101]] = tail call float @llvm.fmuladd.f32(float [[TMP87]], float [[TMP88]], float [[DOTPHI28]])
; CHECK-NEXT:    [[TMP102]] = tail call float @llvm.fmuladd.f32(float [[TMP89]], float [[TMP90]], float [[DOTPHI29]])
; CHECK-NEXT:    [[TMP103]] = tail call float @llvm.fmuladd.f32(float [[TMP91]], float [[TMP92]], float [[DOTPHI30]])
; CHECK-NEXT:    [[TMP104]] = tail call float @llvm.fmuladd.f32(float [[TMP93]], float [[TMP94]], float [[DOTPHI31]])
; CHECK-NEXT:    [[TMP105]] = tail call float @llvm.fmuladd.f32(float [[TMP95]], float [[TMP96]], float [[DOTPHI32]])
; CHECK-NEXT:    [[TMP106]] = tail call float @llvm.fmuladd.f32(float [[TMP97]], float [[TMP98]], float [[DOTPHI33]])
; CHECK-NEXT:    [[CMP56_NOT_7:%.*]] = icmp ult i32 [[K50_0_7]], [[ADD214]]
; CHECK-NEXT:    br i1 [[CMP56_NOT_7]], label [[FOR_BODY57_7]], label [[FOR_END64_LOOPEXIT:%.*]]
; CHECK:       for.end64.loopexit:
; CHECK-NEXT:    [[SUM60:%.*]] = fadd float [[TMP99]], [[TMP100]]
; CHECK-NEXT:    [[SUM61:%.*]] = fadd float [[TMP101]], [[TMP102]]
; CHECK-NEXT:    [[SUM62:%.*]] = fadd float [[TMP103]], [[TMP104]]
; CHECK-NEXT:    [[SUM63:%.*]] = fadd float [[TMP105]], [[TMP106]]
; CHECK-NEXT:    [[SUM64:%.*]] = fadd float [[SUM60]], [[SUM61]]
; CHECK-NEXT:    [[SUM65:%.*]] = fadd float [[SUM62]], [[SUM63]]
; CHECK-NEXT:    [[SUM66:%.*]] = fadd float [[SUM64]], [[SUM65]]
; CHECK-NEXT:    br label [[FOR_END16434]]
; CHECK:       for.end16434:
; CHECK-NEXT:    [[PHI_SUM35:%.*]] = phi i32 [ [[K50_0127]], [[FOR_BODY47]] ], [ [[K50_0_7]], [[FOR_END64_LOOPEXIT]] ]
; CHECK-NEXT:    [[PHI_FLOAT36:%.*]] = phi float [ 0.000000e+00, [[FOR_BODY47]] ], [ [[SUM66]], [[FOR_END64_LOOPEXIT]] ]
; CHECK-NEXT:    store float [[PHI_FLOAT36]], ptr [[ARRAYIDX51]], align 4
; CHECK-NEXT:    [[CMP182_NOT58737:%.*]] = icmp ugt i32 [[PHI_SUM35]], [[SUB54]]
; CHECK-NEXT:    br i1 [[CMP182_NOT58737]], label [[FOR_END64]], label [[FOR_BODY57_CLONE:%.*]]
; CHECK:       for.body57.clone:
; CHECK-NEXT:    [[TMP107:%.*]] = phi float [ [[TMP110:%.*]], [[FOR_BODY57_CLONE]] ], [ [[PHI_FLOAT36]], [[FOR_END16434]] ]
; CHECK-NEXT:    [[K50_0129_CLONE:%.*]] = phi i32 [ [[K50_0_CLONE:%.*]], [[FOR_BODY57_CLONE]] ], [ [[PHI_SUM35]], [[FOR_END16434]] ]
; CHECK-NEXT:    [[ARRAYIDX58_CLONE:%.*]] = getelementptr inbounds float, ptr [[SIG_0]], i32 [[K50_0129_CLONE]]
; CHECK-NEXT:    [[TMP108:%.*]] = load float, ptr [[ARRAYIDX58_CLONE]], align 4
; CHECK-NEXT:    [[SUB59_CLONE:%.*]] = sub i32 [[N41_0131]], [[K50_0129_CLONE]]
; CHECK-NEXT:    [[ARRAYIDX60_CLONE:%.*]] = getelementptr inbounds float, ptr [[KERN_0]], i32 [[SUB59_CLONE]]
; CHECK-NEXT:    [[TMP109:%.*]] = load float, ptr [[ARRAYIDX60_CLONE]], align 4
; CHECK-NEXT:    [[TMP110]] = tail call float @llvm.fmuladd.f32(float [[TMP108]], float [[TMP109]], float [[TMP107]])
; CHECK-NEXT:    [[K50_0_CLONE]] = add i32 [[K50_0129_CLONE]], 1
; CHECK-NEXT:    [[CMP56_NOT_CLONE:%.*]] = icmp ugt i32 [[K50_0_CLONE]], [[SUB54]]
; CHECK-NEXT:    br i1 [[CMP56_NOT_CLONE]], label [[FOR_COND_FOR_END_CRIT_EDGE38:%.*]], label [[FOR_BODY57_CLONE]]
; CHECK:       for.cond.for.end_crit_edge38:
; CHECK-NEXT:    store float [[TMP110]], ptr [[ARRAYIDX51]], align 4
; CHECK-NEXT:    br label [[FOR_END64]]
; CHECK:       for.end64:
; CHECK-NEXT:    [[INC66]] = add nsw i32 [[N41_0131]], 1
; CHECK-NEXT:    [[EXITCOND134_NOT:%.*]] = icmp eq i32 [[INC66]], [[SUB44]]
; CHECK-NEXT:    br i1 [[EXITCOND134_NOT]], label [[RETURN_LOOPEXIT:%.*]], label [[FOR_BODY47]]
; CHECK:       return.loopexit:
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458755, [[ENTRY:%.*]] ], [ 0, [[FOR_COND42_PREHEADER]] ], [ 0, [[RETURN_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %Signal, null
  %cmp1 = icmp eq ptr %Kernel, null
  %or.cond = or i1 %cmp, %cmp1
  %cmp4 = icmp eq ptr %convout, null
  %or.cond118 = or i1 %or.cond, %cmp4
  br i1 %or.cond118, label %return, label %if.end6

if.end6:                                          ; preds = %entry
  %cmp7 = icmp slt i32 %siglen, %kernlen
  br i1 %cmp7, label %if.then8, label %if.end9

if.then8:                                         ; preds = %if.end6
  br label %if.end9

if.end9:                                          ; preds = %if.then8, %if.end6
  %lkern.0 = phi i32 [ %siglen, %if.then8 ], [ %kernlen, %if.end6 ]
  %lsig.0 = phi i32 [ %kernlen, %if.then8 ], [ %siglen, %if.end6 ]
  %kern.0 = phi ptr [ %Signal, %if.then8 ], [ %Kernel, %if.end6 ]
  %sig.0 = phi ptr [ %Kernel, %if.then8 ], [ %Signal, %if.end6 ]
  %cmp10120 = icmp sgt i32 %lkern.0, 0
  br i1 %cmp10120, label %for.body, label %for.cond21.preheader

for.cond21.preheader:                             ; preds = %for.end, %if.end9
  %cmp22125 = icmp slt i32 %lkern.0, %lsig.0
  br i1 %cmp22125, label %for.body24, label %for.cond42.preheader

for.body:                                         ; preds = %for.end, %if.end9
  %indvars.iv = phi i32 [ %indvars.iv.next, %for.end ], [ 1, %if.end9 ]
  %n.0121 = phi i32 [ %inc18, %for.end ], [ 0, %if.end9 ]
  %arrayidx = getelementptr inbounds float, ptr %convout, i32 %n.0121
  store float 0.000000e+00, ptr %arrayidx, align 4
  br label %for.body13

for.body13:                                       ; preds = %for.body13, %for.body
  %k.0119 = phi i32 [ 0, %for.body ], [ %inc, %for.body13 ]
  %0 = phi float [ 0.000000e+00, %for.body ], [ %3, %for.body13 ]
  %arrayidx14 = getelementptr inbounds float, ptr %sig.0, i32 %k.0119
  %1 = load float, ptr %arrayidx14, align 4
  %sub = sub nsw i32 %n.0121, %k.0119
  %arrayidx15 = getelementptr inbounds float, ptr %kern.0, i32 %sub
  %2 = load float, ptr %arrayidx15, align 4
  %3 = tail call float @llvm.fmuladd.f32(float %1, float %2, float %0)
  store float %3, ptr %arrayidx, align 4
  %inc = add nuw nsw i32 %k.0119, 1
  %exitcond = icmp eq i32 %inc, %indvars.iv
  br i1 %exitcond, label %for.end, label %for.body13

for.end:                                          ; preds = %for.body13
  %inc18 = add nuw nsw i32 %n.0121, 1
  %indvars.iv.next = add nuw i32 %indvars.iv, 1
  %exitcond132.not = icmp eq i32 %inc18, %lkern.0
  br i1 %exitcond132.not, label %for.cond21.preheader, label %for.body

for.cond42.preheader:                             ; preds = %for.end37, %for.cond21.preheader
  %add43 = add i32 %siglen, -1
  %sub44 = add i32 %add43, %kernlen
  %cmp45130 = icmp slt i32 %lsig.0, %sub44
  br i1 %cmp45130, label %for.body47.lr.ph, label %return

for.body47.lr.ph:                                 ; preds = %for.cond42.preheader
  %sub54 = add nsw i32 %lsig.0, -1
  br label %for.body47

for.body24:                                       ; preds = %for.end37, %for.cond21.preheader
  %n20.0126 = phi i32 [ %inc39, %for.end37 ], [ %lkern.0, %for.cond21.preheader ]
  %arrayidx26 = getelementptr inbounds float, ptr %convout, i32 %n20.0126
  store float 0.000000e+00, ptr %arrayidx26, align 4
  %sub27 = sub nuw nsw i32 %n20.0126, %lkern.0
  %k25.0122 = add i32 %sub27, 1
  %cmp29.not123 = icmp ugt i32 %k25.0122, %n20.0126
  br i1 %cmp29.not123, label %for.end37, label %for.body30

for.body30:                                       ; preds = %for.body30, %for.body24
  %4 = phi float [ %7, %for.body30 ], [ 0.000000e+00, %for.body24 ]
  %k25.0124 = phi i32 [ %k25.0, %for.body30 ], [ %k25.0122, %for.body24 ]
  %arrayidx31 = getelementptr inbounds float, ptr %sig.0, i32 %k25.0124
  %5 = load float, ptr %arrayidx31, align 4
  %sub32 = sub i32 %n20.0126, %k25.0124
  %arrayidx33 = getelementptr inbounds float, ptr %kern.0, i32 %sub32
  %6 = load float, ptr %arrayidx33, align 4
  %7 = tail call float @llvm.fmuladd.f32(float %5, float %6, float %4)
  store float %7, ptr %arrayidx26, align 4
  %k25.0 = add i32 %k25.0124, 1
  %cmp29.not = icmp ugt i32 %k25.0, %n20.0126
  br i1 %cmp29.not, label %for.end37, label %for.body30

for.end37:                                        ; preds = %for.body30, %for.body24
  %inc39 = add nuw nsw i32 %n20.0126, 1
  %exitcond133.not = icmp eq i32 %inc39, %lsig.0
  br i1 %exitcond133.not, label %for.cond42.preheader, label %for.body24

for.body47:                                       ; preds = %for.end64, %for.body47.lr.ph
  %n41.0131 = phi i32 [ %lsig.0, %for.body47.lr.ph ], [ %inc66, %for.end64 ]
  %arrayidx51 = getelementptr inbounds float, ptr %convout, i32 %n41.0131
  store float 0.000000e+00, ptr %arrayidx51, align 4
  %sub52 = sub nsw i32 %n41.0131, %lkern.0
  %k50.0127 = add i32 %sub52, 1
  %cmp56.not128 = icmp ugt i32 %k50.0127, %sub54
  br i1 %cmp56.not128, label %for.end64, label %for.body57

for.body57:                                       ; preds = %for.body57, %for.body47
  %8 = phi float [ %11, %for.body57 ], [ 0.000000e+00, %for.body47 ]
  %k50.0129 = phi i32 [ %k50.0, %for.body57 ], [ %k50.0127, %for.body47 ]
  %arrayidx58 = getelementptr inbounds float, ptr %sig.0, i32 %k50.0129
  %9 = load float, ptr %arrayidx58, align 4
  %sub59 = sub i32 %n41.0131, %k50.0129
  %arrayidx60 = getelementptr inbounds float, ptr %kern.0, i32 %sub59
  %10 = load float, ptr %arrayidx60, align 4
  %11 = tail call float @llvm.fmuladd.f32(float %9, float %10, float %8)
  store float %11, ptr %arrayidx51, align 4
  %k50.0 = add i32 %k50.0129, 1
  %cmp56.not = icmp ugt i32 %k50.0, %sub54
  br i1 %cmp56.not, label %for.end64, label %for.body57

for.end64:                                        ; preds = %for.body57, %for.body47
  %inc66 = add nsw i32 %n41.0131, 1
  %exitcond134.not = icmp eq i32 %inc66, %sub44
  br i1 %exitcond134.not, label %return, label %for.body47

return:                                           ; preds = %for.end64, %for.cond42.preheader, %entry
  %retval.0 = phi i32 [ 458755, %entry ], [ 0, %for.cond42.preheader ], [ 0, %for.end64 ]
  ret i32 %retval.0
}
