; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32p4-loop-vectorize-extractor -riscv-esp32p4-loop-vectorize-extractor=true < %s | FileCheck %s


; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite)
define dso_local range(i32 0, 458756) i32 @dsps_mulc_s16_ansi(ptr noundef readonly %input, ptr noundef writeonly %output, i32 noundef %len, i16 noundef signext %C, i32 noundef %step_in, i32 noundef %step_out) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local range(i32 0, 458756) i32 @dsps_mulc_s16_ansi(
; CHECK-SAME: ptr noundef readonly [[INPUT:%.*]], ptr noundef writeonly [[OUTPUT:%.*]], i32 noundef [[LEN:%.*]], i16 noundef signext [[C:%.*]], i32 noundef [[STEP_IN:%.*]], i32 noundef [[STEP_OUT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[INPUT4:%.*]] = ptrtoaddr ptr [[INPUT]] to i32
; CHECK-NEXT:    [[OUTPUT3:%.*]] = ptrtoaddr ptr [[OUTPUT]] to i32
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[INPUT]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[OUTPUT]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    br i1 [[OR_COND]], label %[[RETURN:.*]], label %[[FOR_COND_PREHEADER:.*]]
; CHECK:       [[FOR_COND_PREHEADER]]:
; CHECK-NEXT:    [[CMP415:%.*]] = icmp sgt i32 [[LEN]], 0
; CHECK-NEXT:    br i1 [[CMP415]], label %[[FOR_BODY_LR_PH:.*]], label %[[RETURN]]
; CHECK:       [[FOR_BODY_LR_PH]]:
; CHECK-NEXT:    [[CONV5:%.*]] = sext i16 [[C]] to i32
; CHECK-NEXT:    [[STRIDE_IS_ONE:%.*]] = icmp eq i32 [[STEP_OUT]], 1
; CHECK-NEXT:    [[STRIDE_IS_ONE1:%.*]] = icmp eq i32 [[STEP_IN]], 1
; CHECK-NEXT:    [[TMP0:%.*]] = and i1 [[STRIDE_IS_ONE]], [[STRIDE_IS_ONE1]]
; CHECK-NEXT:    br i1 [[TMP0]], label %[[FAST_PATH_PREHEADER:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[LEN]], 6
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_SCEVCHECK:.*]]
; CHECK:       [[VECTOR_SCEVCHECK]]:
; CHECK-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i32 [[STEP_OUT]], 1
; CHECK-NEXT:    [[IDENT_CHECK2:%.*]] = icmp ne i32 [[STEP_IN]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = or i1 [[IDENT_CHECK]], [[IDENT_CHECK2]]
; CHECK-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH]], label %[[VECTOR_MEMCHECK:.*]]
; CHECK:       [[VECTOR_MEMCHECK]]:
; CHECK-NEXT:    [[TMP2:%.*]] = sub i32 [[OUTPUT3]], [[INPUT4]]
; CHECK-NEXT:    [[DIFF_CHECK:%.*]] = icmp ult i32 [[TMP2]], 4
; CHECK-NEXT:    br i1 [[DIFF_CHECK]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i32 [[LEN]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i32 [[LEN]], [[N_MOD_VF]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <2 x i32> poison, i32 [[CONV5]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <2 x i32> [[BROADCAST_SPLATINSERT]], <2 x i32> poison, <2 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[LSR_IV30:%.*]] = phi ptr [ [[SCEVGEP31:%.*]], %[[VECTOR_BODY]] ], [ [[INPUT]], %[[VECTOR_PH]] ]
; CHECK-NEXT:    [[LSR_IV28:%.*]] = phi ptr [ [[SCEVGEP29:%.*]], %[[VECTOR_BODY]] ], [ [[OUTPUT]], %[[VECTOR_PH]] ]
; CHECK-NEXT:    [[LSR_IV26:%.*]] = phi i32 [ [[LSR_IV_NEXT27:%.*]], %[[VECTOR_BODY]] ], [ [[N_VEC]], %[[VECTOR_PH]] ]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x i16>, ptr [[LSR_IV30]], align 2, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[TMP3:%.*]] = sext <2 x i16> [[WIDE_LOAD]] to <2 x i32>
; CHECK-NEXT:    [[TMP4:%.*]] = mul nsw <2 x i32> [[TMP3]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP5:%.*]] = lshr <2 x i32> [[TMP4]], splat (i32 15)
; CHECK-NEXT:    [[TMP6:%.*]] = trunc <2 x i32> [[TMP5]] to <2 x i16>
; CHECK-NEXT:    store <2 x i16> [[TMP6]], ptr [[LSR_IV28]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[LSR_IV_NEXT27]] = add i32 [[LSR_IV26]], -2
; CHECK-NEXT:    [[SCEVGEP29]] = getelementptr i8, ptr [[LSR_IV28]], i32 4
; CHECK-NEXT:    [[SCEVGEP31]] = getelementptr i8, ptr [[LSR_IV30]], i32 4
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[LSR_IV_NEXT27]], 0
; CHECK-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i32 [[LEN]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[RETURN_LOOPEXIT_LOOPEXIT1:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[FOR_BODY_PREHEADER]] ], [ 0, %[[VECTOR_SCEVCHECK]] ], [ 0, %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = sub i32 [[LEN]], [[BC_RESUME_VAL]]
; CHECK-NEXT:    [[TMP9:%.*]] = mul i32 [[BC_RESUME_VAL]], [[STEP_OUT]]
; CHECK-NEXT:    [[TMP10:%.*]] = shl i32 [[TMP9]], 1
; CHECK-NEXT:    [[SCEVGEP34:%.*]] = getelementptr i8, ptr [[OUTPUT]], i32 [[TMP10]]
; CHECK-NEXT:    [[TMP11:%.*]] = shl i32 [[STEP_OUT]], 1
; CHECK-NEXT:    [[TMP12:%.*]] = mul i32 [[BC_RESUME_VAL]], [[STEP_IN]]
; CHECK-NEXT:    [[TMP13:%.*]] = shl i32 [[TMP12]], 1
; CHECK-NEXT:    [[SCEVGEP37:%.*]] = getelementptr i8, ptr [[INPUT]], i32 [[TMP13]]
; CHECK-NEXT:    [[TMP14:%.*]] = shl i32 [[STEP_IN]], 1
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FAST_PATH_PREHEADER]]:
; CHECK-NEXT:    [[CONV5_FAST:%.*]] = sext i16 [[C]] to i32
; CHECK-NEXT:    [[MIN_ITERS_CHECK11:%.*]] = icmp ult i32 [[LEN]], 8
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK11]], label %[[SCALAR_PH9:.*]], label %[[VECTOR_MEMCHECK5:.*]]
; CHECK:       [[VECTOR_MEMCHECK5]]:
; CHECK-NEXT:    [[TMP15:%.*]] = sub i32 [[OUTPUT3]], [[INPUT4]]
; CHECK-NEXT:    [[DIFF_CHECK8:%.*]] = icmp ult i32 [[TMP15]], 16
; CHECK-NEXT:    br i1 [[DIFF_CHECK8]], label %[[SCALAR_PH9]], label %[[VECTOR_PH11:.*]]
; CHECK:       [[VECTOR_PH11]]:
; CHECK-NEXT:    [[N_MOD_VF13:%.*]] = urem i32 [[LEN]], 8
; CHECK-NEXT:    [[N_VEC14:%.*]] = sub i32 [[LEN]], [[N_MOD_VF13]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT19:%.*]] = insertelement <8 x i32> poison, i32 [[CONV5_FAST]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT20:%.*]] = shufflevector <8 x i32> [[BROADCAST_SPLATINSERT19]], <8 x i32> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY16:.*]]
; CHECK:       [[VECTOR_BODY16]]:
; CHECK-NEXT:    [[LSR_IV24:%.*]] = phi ptr [ [[SCEVGEP25:%.*]], %[[VECTOR_BODY16]] ], [ [[INPUT]], %[[VECTOR_PH11]] ]
; CHECK-NEXT:    [[LSR_IV23:%.*]] = phi ptr [ [[SCEVGEP:%.*]], %[[VECTOR_BODY16]] ], [ [[OUTPUT]], %[[VECTOR_PH11]] ]
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i32 [ [[LSR_IV_NEXT:%.*]], %[[VECTOR_BODY16]] ], [ [[N_VEC14]], %[[VECTOR_PH11]] ]
; CHECK-NEXT:    [[WIDE_LOAD18:%.*]] = load <8 x i16>, ptr [[LSR_IV24]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP16:%.*]] = sext <8 x i16> [[WIDE_LOAD18]] to <8 x i32>
; CHECK-NEXT:    [[TMP17:%.*]] = mul nsw <8 x i32> [[TMP16]], [[BROADCAST_SPLAT20]]
; CHECK-NEXT:    [[TMP18:%.*]] = lshr <8 x i32> [[TMP17]], splat (i32 15)
; CHECK-NEXT:    [[TMP19:%.*]] = trunc <8 x i32> [[TMP18]] to <8 x i16>
; CHECK-NEXT:    store <8 x i16> [[TMP19]], ptr [[LSR_IV23]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i32 [[LSR_IV]], -8
; CHECK-NEXT:    [[SCEVGEP]] = getelementptr i8, ptr [[LSR_IV23]], i32 16
; CHECK-NEXT:    [[SCEVGEP25]] = getelementptr i8, ptr [[LSR_IV24]], i32 16
; CHECK-NEXT:    [[TMP20:%.*]] = icmp eq i32 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[TMP20]], label %[[MIDDLE_BLOCK20:.*]], label %[[VECTOR_BODY16]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK20]]:
; CHECK-NEXT:    [[CMP_N22:%.*]] = icmp eq i32 [[LEN]], [[N_VEC14]]
; CHECK-NEXT:    br i1 [[CMP_N22]], label %[[RETURN_LOOPEXIT_LOOPEXIT:.*]], label %[[SCALAR_PH9]]
; CHECK:       [[SCALAR_PH9]]:
; CHECK-NEXT:    [[BC_RESUME_VAL15:%.*]] = phi i32 [ [[N_VEC14]], %[[MIDDLE_BLOCK20]] ], [ 0, %[[FAST_PATH_PREHEADER]] ], [ 0, %[[VECTOR_MEMCHECK5]] ]
; CHECK-NEXT:    [[TMP21:%.*]] = sub i32 [[LEN]], [[BC_RESUME_VAL15]]
; CHECK-NEXT:    [[TMP22:%.*]] = shl i32 [[BC_RESUME_VAL15]], 1
; CHECK-NEXT:    [[SCEVGEP42:%.*]] = getelementptr i8, ptr [[OUTPUT]], i32 [[TMP22]]
; CHECK-NEXT:    [[SCEVGEP45:%.*]] = getelementptr i8, ptr [[INPUT]], i32 [[TMP22]]
; CHECK-NEXT:    br label %[[FOR_BODY_FAST:.*]]
; CHECK:       [[FOR_BODY_FAST]]:
; CHECK-NEXT:    [[LSR_IV46:%.*]] = phi ptr [ [[SCEVGEP45]], %[[SCALAR_PH9]] ], [ [[SCEVGEP47:%.*]], %[[FOR_BODY_FAST]] ]
; CHECK-NEXT:    [[LSR_IV43:%.*]] = phi ptr [ [[SCEVGEP42]], %[[SCALAR_PH9]] ], [ [[SCEVGEP44:%.*]], %[[FOR_BODY_FAST]] ]
; CHECK-NEXT:    [[LSR_IV40:%.*]] = phi i32 [ [[TMP21]], %[[SCALAR_PH9]] ], [ [[LSR_IV_NEXT41:%.*]], %[[FOR_BODY_FAST]] ]
; CHECK-NEXT:    [[TMP23:%.*]] = load i16, ptr [[LSR_IV46]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[CONV_FAST:%.*]] = sext i16 [[TMP23]] to i32
; CHECK-NEXT:    [[MUL6_FAST:%.*]] = mul nsw i32 [[CONV_FAST]], [[CONV5_FAST]]
; CHECK-NEXT:    [[SHR_FAST:%.*]] = lshr i32 [[MUL6_FAST]], 15
; CHECK-NEXT:    [[CONV7_FAST:%.*]] = trunc i32 [[SHR_FAST]] to i16
; CHECK-NEXT:    store i16 [[CONV7_FAST]], ptr [[LSR_IV43]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[LSR_IV_NEXT41]] = add i32 [[LSR_IV40]], -1
; CHECK-NEXT:    [[SCEVGEP44]] = getelementptr i8, ptr [[LSR_IV43]], i32 2
; CHECK-NEXT:    [[SCEVGEP47]] = getelementptr i8, ptr [[LSR_IV46]], i32 2
; CHECK-NEXT:    [[EXITCOND_NOT_FAST:%.*]] = icmp eq i32 [[LSR_IV_NEXT41]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_FAST]], label %[[RETURN_LOOPEXIT_LOOPEXIT_LOOPEXIT:.*]], label %[[FOR_BODY_FAST]], !llvm.loop [[LOOP15:![0-9]+]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[LSR_IV38:%.*]] = phi ptr [ [[SCEVGEP37]], %[[SCALAR_PH]] ], [ [[SCEVGEP39:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[LSR_IV35:%.*]] = phi ptr [ [[SCEVGEP34]], %[[SCALAR_PH]] ], [ [[SCEVGEP36:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[LSR_IV32:%.*]] = phi i32 [ [[TMP8]], %[[SCALAR_PH]] ], [ [[LSR_IV_NEXT33:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP24:%.*]] = load i16, ptr [[LSR_IV38]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP24]] to i32
; CHECK-NEXT:    [[MUL6:%.*]] = mul nsw i32 [[CONV]], [[CONV5]]
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[MUL6]], 15
; CHECK-NEXT:    [[CONV7:%.*]] = trunc i32 [[SHR]] to i16
; CHECK-NEXT:    store i16 [[CONV7]], ptr [[LSR_IV35]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[LSR_IV_NEXT33]] = add i32 [[LSR_IV32]], -1
; CHECK-NEXT:    [[SCEVGEP36]] = getelementptr i8, ptr [[LSR_IV35]], i32 [[TMP11]]
; CHECK-NEXT:    [[SCEVGEP39]] = getelementptr i8, ptr [[LSR_IV38]], i32 [[TMP14]]
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[LSR_IV_NEXT33]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[RETURN_LOOPEXIT_LOOPEXIT1_LOOPEXIT:.*]], label %[[FOR_BODY]], !llvm.loop [[LOOP16:![0-9]+]]
; CHECK:       [[RETURN_LOOPEXIT_LOOPEXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[RETURN_LOOPEXIT_LOOPEXIT]]
; CHECK:       [[RETURN_LOOPEXIT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[RETURN_LOOPEXIT:.*]]
; CHECK:       [[RETURN_LOOPEXIT_LOOPEXIT1_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[RETURN_LOOPEXIT_LOOPEXIT1]]
; CHECK:       [[RETURN_LOOPEXIT_LOOPEXIT1]]:
; CHECK-NEXT:    br label %[[RETURN_LOOPEXIT]]
; CHECK:       [[RETURN_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458755, %[[ENTRY]] ], [ 0, %[[FOR_COND_PREHEADER]] ], [ 0, %[[RETURN_LOOPEXIT]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %input, null
  %cmp1 = icmp eq ptr %output, null
  %or.cond = or i1 %cmp, %cmp1
  br i1 %or.cond, label %return, label %for.cond.preheader

for.cond.preheader:                               ; preds = %entry
  %cmp415 = icmp sgt i32 %len, 0
  br i1 %cmp415, label %for.body.lr.ph, label %return

for.body.lr.ph:                                   ; preds = %for.cond.preheader
  %conv5 = sext i16 %C to i32
  %stride.is.one = icmp eq i32 %step_out, 1
  %stride.is.one1 = icmp eq i32 %step_in, 1
  %0 = and i1 %stride.is.one, %stride.is.one1
  br i1 %0, label %fast.path.preheader, label %for.body

fast.path.preheader:                              ; preds = %for.body.lr.ph
  %conv5.fast = sext i16 %C to i32
  br label %for.body.fast

for.body.fast:                                    ; preds = %for.body.fast, %fast.path.preheader
  %i.016.fast = phi i32 [ 0, %fast.path.preheader ], [ %inc.fast, %for.body.fast ]
  %arrayidx.fast = getelementptr inbounds i16, ptr %input, i32 %i.016.fast
  %1 = load i16, ptr %arrayidx.fast, align 2, !tbaa !6
  %conv.fast = sext i16 %1 to i32
  %mul6.fast = mul nsw i32 %conv.fast, %conv5.fast
  %shr.fast = lshr i32 %mul6.fast, 15
  %conv7.fast = trunc i32 %shr.fast to i16
  %arrayidx9.fast = getelementptr inbounds i16, ptr %output, i32 %i.016.fast
  store i16 %conv7.fast, ptr %arrayidx9.fast, align 2, !tbaa !6
  %inc.fast = add nuw nsw i32 %i.016.fast, 1
  %exitcond.not.fast = icmp eq i32 %inc.fast, %len
  br i1 %exitcond.not.fast, label %return.loopexit, label %for.body.fast, !llvm.loop !10

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %i.016 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %mul = mul nsw i32 %i.016, %step_in
  %arrayidx = getelementptr inbounds i16, ptr %input, i32 %mul
  %2 = load i16, ptr %arrayidx, align 2, !tbaa !6
  %conv = sext i16 %2 to i32
  %mul6 = mul nsw i32 %conv, %conv5
  %shr = lshr i32 %mul6, 15
  %conv7 = trunc i32 %shr to i16
  %mul8 = mul nsw i32 %i.016, %step_out
  %arrayidx9 = getelementptr inbounds i16, ptr %output, i32 %mul8
  store i16 %conv7, ptr %arrayidx9, align 2, !tbaa !6
  %inc = add nuw nsw i32 %i.016, 1
  %exitcond.not = icmp eq i32 %inc, %len
  br i1 %exitcond.not, label %return.loopexit, label %for.body, !llvm.loop !10

return.loopexit:                                  ; preds = %for.body, %for.body.fast
  br label %return

return:                                           ; preds = %return.loopexit, %for.cond.preheader, %entry
  %retval.0 = phi i32 [ 458755, %entry ], [ 0, %for.cond.preheader ], [ 0, %return.loopexit ]
  ret i32 %retval.0
}

attributes #0 = { nofree norecurse nosync nounwind memory(argmem: readwrite) "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic-rv32" "target-features"="+32bit,+a,+c,+f,+m,+relax,+xesppie,+zca,+zcmp,+zicsr,+zifencei,+zmmul,-b,-d,-e,-experimental-smmpm,-experimental-smnpm,-experimental-ssnpm,-experimental-sspm,-experimental-ssqosid,-experimental-supm,-experimental-zacas,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-h,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smepmp,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-v,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }

!llvm.module.flags = !{!0, !1, !2, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"ilp32f"}
!2 = !{i32 6, !"riscv-isa", !3}
!3 = !{!"rv32i2p1_m2p0_a2p1_f2p2_c2p0_zicsr2p0_zifencei2p0_zmmul1p0_zca1p0_zcmp1p0_xesppie1p0"}
!4 = !{i32 8, !"SmallDataLimit", i32 8}
!5 = !{!"Espressif clang version 17.0.1 (https://gitlab.espressif.cn:6688/idf/llvm-project.git llvmorg-19.1.2-277-gbe3198f esp-18.1.2_20240912-657-ge1dc1cc esp-18.1.2_20240912-657-ge1dc1cc esp-18.1.2_20240912-685-g8c39bf5 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 esp-18.1.2_20240912-694-g4a14fa0 esp-18.1.2_20240912-694-g4a14fa0 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-282-gf0df22b llvmorg-19.1.2-282-g61f783f llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-289-g6ab7981 llvmorg-19.1.2-294-ga687ee8 llvmorg-19.1.2-282-gded6180 llvmorg-19.1.2-295-gd6b9c67 llvmorg-19.1.2-296-g2bb38d3 llvmorg-19.1.2-302-gb46e43e llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-ga193982 llvmorg-19.1.2-310-g012c995 llvmorg-19.1.2-373-g483ac18 llvmorg-19.1.2-373-g483ac18 llvmorg-19.1.2-373-g483ac18 esp-19.1.2_20250225-2-g2444a40 esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g5a99af4 esp-19.1.2_20250225-2-g5a99af4 esp-19.1.2_20250225-4-g6ad288c esp-19.1.2_20250225-2-g78646ff esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312-1-gbfbef3f esp-19.1.2_20250225-3-g153f4c7 esp-19.1.2_20250312-2-gf1328c0 esp-19.1.2_20250312-1-ga44194f esp-19.1.2_20250312-2-g6ad288c esp-19.1.2_20250225-5-gabba736 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-1-ge8e26d4 esp-19.1.2_20250225-6-g1102ab9 esp-19.1.2_20250312-1-ga44194f esp-19.1.2_20250312-1-gfaf5f34 esp-19.1.2_20250312-2-g912da7e esp-19.1.2_20250312-12-g40fcb86 esp-19.1.2_20250312-22-g150517d esp-19.1.2_20250312-36-g3725281 esp-19.1.2_20250312-36-g3725281 esp-19.1.2_20250312-37-gd7ad151 esp-19.1.2_20250312-43-g1fdfc46 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250312-67-g1b9c1af esp-19.1.2_20250312-67-g1b9c1af esp-19.1.2_20250312-2-g590a30f esp-19.1.2_20250312-2-g590a30f esp-19.1.2_20250312-68-g65bae88 esp-19.1.2_20250312-68-g65bae88 llvmorg-19.1.2-286-g58c0b0a esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-2-gaccea5b esp-19.1.2_20250312-79-g85b8bac esp-19.1.2_20250312-1-g5bd87a5 esp-19.1.2_20250312-2-g398f0e9 esp-19.1.2_20250312-2-gfa1159a esp-19.1.2_20250312 esp-19.1.2_20250312-1-g190f2f0 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312-1-gdb3618a esp-19.1.2_20250312-5-g53503ec esp-19.1.2_20250312-14-gbd1030c esp-19.1.2_20250312-14-gbd1030c esp-19.1.2_20250312-94-ga50fb83 esp-19.1.2_20250312-21-g2d4e527 esp-19.1.2_20250312-22-gd828f8c esp-19.1.2_20250312-25-ga0db53c esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-50-g36efec3 esp-19.1.2_20250312-49-g66c7bd3 esp-19.1.2_20250312-68-gef601b8 esp-19.1.2_20250312-84-g3338f1a esp-19.1.2_20250225-105-gfa4c43d esp-19.1.2_20250312-99-gcad4d17 esp-19.1.2_20250312-2-g7c53768 esp-19.1.2_20250312-2-g7c53768 esp-19.1.2_20250312-3-g77450217 esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-7-ge58b5b9 esp-19.1.2_20250312-7-ge58b5b9 esp-19.1.2_20250312-9-gf8d929c esp-19.1.2_20250312-9-gf8d929c esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-14-gcc23a57 esp-19.1.2_20250312-15-gb030eec esp-19.1.2_20250312-16-g5e690f7 esp-19.1.2_20250312-18-g64518b8 esp-19.1.2_20250312-19-gf837620 esp-19.1.2_20250312-30-gce11723)"}
!6 = !{!7, !7, i64 0}
!7 = !{!"short", !8, i64 0}
!8 = !{!"omnipotent char", !9, i64 0}
!9 = !{!"Simple C/C++ TBAA"}
!10 = distinct !{!10, !11}
!11 = !{!"llvm.loop.mustprogress"}
;.
; CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; CHECK: [[META7]] = !{!"short", [[META8:![0-9]+]], i64 0}
; CHECK: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; CHECK: [[META9]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]], [[META12:![0-9]+]], [[META13:![0-9]+]]}
; CHECK: [[META11]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[META12]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META13]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP14]] = distinct !{[[LOOP14]], [[META11]], [[META12]], [[META13]]}
; CHECK: [[LOOP15]] = distinct !{[[LOOP15]], [[META11]], [[META12]]}
; CHECK: [[LOOP16]] = distinct !{[[LOOP16]], [[META11]], [[META12]]}
;.
