; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-custom-licm -riscv-custom-licm=true < %s | FileCheck %s

; Function Attrs: nofree nounwind memory(write)
define dso_local void @dsps_wind_hann_f32(ptr nocapture noundef writeonly %window, i32 noundef %len) local_unnamed_addr {
; CHECK-LABEL: define dso_local void @dsps_wind_hann_f32(
; CHECK-SAME: ptr noundef writeonly captures(none) [[WINDOW:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP15:%.*]] = icmp sgt i32 [[LEN]], 0
; CHECK-NEXT:    br i1 [[CMP15]], label [[FOR_BODY_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[LEN]], -1
; CHECK-NEXT:    [[CONV:%.*]] = sitofp i32 [[SUB]] to float
; CHECK-NEXT:    [[DIV:%.*]] = fdiv float 1.000000e+00, [[CONV]]
; CHECK-NEXT:    [[CONV4:%.*]] = fpext float [[DIV]] to double
; CHECK-NEXT:    [[MUL1:%.*]] = fmul double [[CONV4]], f0x401921FB54442D18
; CHECK-NEXT:    [[CONV22:%.*]] = fptrunc double [[MUL1]] to float
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[I_016:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[INC:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[CONV5:%.*]] = sitofp i32 [[I_016]] to float
; CHECK-NEXT:    [[MUL6:%.*]] = fmul float [[CONV22]], [[CONV5]]
; CHECK-NEXT:    [[CALL:%.*]] = tail call float @cosf(float noundef [[MUL6]])
; CHECK-NEXT:    [[SUB7:%.*]] = fsub float 1.000000e+00, [[CALL]]
; CHECK-NEXT:    [[CONV10:%.*]] = fmul float [[SUB7]], 5.000000e-01
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[WINDOW]], i32 [[I_016]]
; CHECK-NEXT:    store float [[CONV10]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_016]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]]
;
entry:
  %cmp15 = icmp sgt i32 %len, 0
  br i1 %cmp15, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %entry
  %sub = add nsw i32 %len, -1
  %conv = sitofp i32 %sub to float
  %div = fdiv float 1.000000e+00, %conv
  %conv4 = fpext float %div to double
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %i.016 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %mul = shl nuw nsw i32 %i.016, 1
  %conv2 = sitofp i32 %mul to double
  %mul3 = fmul double %conv2, 0x400921FB54442D18
  %mul5 = fmul double %mul3, %conv4
  %conv6 = fptrunc double %mul5 to float
  %call = tail call float @cosf(float noundef %conv6)
  %sub7 = fsub float 1.000000e+00, %call
  %conv10 = fmul float %sub7, 5.000000e-01
  %arrayidx = getelementptr inbounds float, ptr %window, i32 %i.016
  store float %conv10, ptr %arrayidx, align 4
  %inc = add nuw nsw i32 %i.016, 1
  %exitcond.not = icmp eq i32 %inc, %len
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

; Function Attrs: mustprogress nofree nounwind willreturn memory(write)
declare dso_local float @cosf(float noundef) local_unnamed_addr

