; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32-p4-mem-intrin -riscv-esp32-p4-mem-intrin=true < %s | FileCheck %s
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "riscv32-esp-unknown-elf"

define void @test_src16_dst16_variable_size(ptr %a, ptr %b, i32 %size) {
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 %a, ptr noundef nonnull align 16 %b, i32 %size, i1 false)
  ret void
}

define void @test_src16_dst8_variable_size(ptr %a, ptr %b, i32 %size) {
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 %a, ptr noundef nonnull align 16 %b, i32 %size, i1 false)
  ret void
}

define void @test_src8_dst16_variable_size(ptr %a, ptr %b, i32 %size) {
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 %a, ptr noundef nonnull align 8 %b, i32 %size, i1 false)
  ret void
}

define void @test_src8_dst8_variable_size(ptr %a, ptr %b, i32 %size) {
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 %a, ptr noundef nonnull align 8 %b, i32 %size, i1 false)
  ret void
}

define void @test_src16_dstunalign_variable_size(ptr %a, ptr %b, i32 %size) {
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 %a, ptr noundef nonnull align 16 %b, i32 %size, i1 false)
  ret void
}

define void @test_src8_dstunalign_variable_size(ptr %a, ptr %b, i32 %size) {
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 %a, ptr noundef nonnull align 8 %b, i32 %size, i1 false)
  ret void
}

define void @test_srcunalign_dst16_variable_size(ptr %a, ptr %b, i32 %size) {
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 %a, ptr noundef nonnull align 1 %b, i32 %size, i1 false)
  ret void
}

define void @test_srcunalign_dst8_variable_size(ptr %a, ptr %b, i32 %size) {
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 %a, ptr noundef nonnull align 1 %b, i32 %size, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_variable_size(ptr %a, ptr %b, i32 %size) {
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 %a, ptr noundef nonnull align 1 %b, i32 %size, i1 false)
  ret void
}

declare void @llvm.memcpy.p0.p0.i32(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i32, i1 immarg)

; Function Attrs: noinline nounwind
define internal void @esp32p4MemCpySrc16Dst16From1To7Opt(ptr %dst, ptr %src, i32 %size)  {
entry:
  switch i32 %size, label %return [
  i32 1, label %sw.bb1
  i32 2, label %sw.bb2
  i32 3, label %sw.bb3
  i32 4, label %sw.bb4
  i32 5, label %sw.bb5
  i32 6, label %sw.bb6
  i32 7, label %sw.bb7
  ]

return:                                           ; preds = %sw.bb7, %sw.bb6, %sw.bb5, %sw.bb4, %sw.bb3, %sw.bb2, %sw.bb1, %entry
  ret void

sw.bb1:                                           ; preds = %entry
  %src.gep.i8 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i8 = getelementptr i8, ptr %dst, i32 0
  %0 = load i8, ptr %src.gep.i8, align 1
  store i8 %0, ptr %dst.gep.i8, align 1
  br label %return

sw.bb2:                                           ; preds = %entry
  %src.gep.i16 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i16 = getelementptr i8, ptr %dst, i32 0
  %1 = load i16, ptr %src.gep.i16, align 2
  store i16 %1, ptr %dst.gep.i16, align 2
  br label %return

sw.bb3:                                           ; preds = %entry
  %src.gep.i161 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i162 = getelementptr i8, ptr %dst, i32 0
  %2 = load i16, ptr %src.gep.i161, align 2
  store i16 %2, ptr %dst.gep.i162, align 2
  %src.gep.i83 = getelementptr i8, ptr %src, i32 2
  %dst.gep.i84 = getelementptr i8, ptr %dst, i32 2
  %3 = load i8, ptr %src.gep.i83, align 1
  store i8 %3, ptr %dst.gep.i84, align 1
  br label %return

sw.bb4:                                           ; preds = %entry
  %src.gep.i32 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i32 = getelementptr i8, ptr %dst, i32 0
  %4 = load i32, ptr %src.gep.i32, align 4
  store i32 %4, ptr %dst.gep.i32, align 4
  br label %return

sw.bb5:                                           ; preds = %entry
  %src.gep.i325 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i326 = getelementptr i8, ptr %dst, i32 0
  %5 = load i32, ptr %src.gep.i325, align 4
  store i32 %5, ptr %dst.gep.i326, align 4
  %src.gep.i87 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i88 = getelementptr i8, ptr %dst, i32 4
  %6 = load i8, ptr %src.gep.i87, align 1
  store i8 %6, ptr %dst.gep.i88, align 1
  br label %return

sw.bb6:                                           ; preds = %entry
  %src.gep.i329 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i3210 = getelementptr i8, ptr %dst, i32 0
  %7 = load i32, ptr %src.gep.i329, align 4
  store i32 %7, ptr %dst.gep.i3210, align 4
  %src.gep.i1611 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1612 = getelementptr i8, ptr %dst, i32 4
  %8 = load i16, ptr %src.gep.i1611, align 2
  store i16 %8, ptr %dst.gep.i1612, align 2
  br label %return

sw.bb7:                                           ; preds = %entry
  %src.gep.i3213 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i3214 = getelementptr i8, ptr %dst, i32 0
  %9 = load i32, ptr %src.gep.i3213, align 4
  store i32 %9, ptr %dst.gep.i3214, align 4
  %src.gep.i1615 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1616 = getelementptr i8, ptr %dst, i32 4
  %10 = load i16, ptr %src.gep.i1615, align 2
  store i16 %10, ptr %dst.gep.i1616, align 2
  %src.gep.i817 = getelementptr i8, ptr %src, i32 6
  %dst.gep.i818 = getelementptr i8, ptr %dst, i32 6
  %11 = load i8, ptr %src.gep.i817, align 1
  store i8 %11, ptr %dst.gep.i818, align 1
  br label %return
}

; Function Attrs: nounwind
declare i32 @llvm.riscv.esp.vld.l.64.ip(i32, i32 immarg, i32 immarg)

; Function Attrs: nounwind
declare i32 @llvm.riscv.esp.vst.l.64.ip(i32 immarg, i32, i32 immarg)

; Function Attrs: nounwind
declare i32 @llvm.riscv.esp.vld.128.ip(i32, i32 immarg, i32 immarg)

; Function Attrs: nounwind
declare i32 @llvm.riscv.esp.vst.128.ip(i32 immarg, i32, i32 immarg)

; Function Attrs: noinline nounwind
define internal void @esp32p4MemCpySrc16Dst8From1To7Opt(ptr %dst, ptr %src, i32 %size)  {
entry:
  switch i32 %size, label %return [
  i32 1, label %sw.bb1
  i32 2, label %sw.bb2
  i32 3, label %sw.bb3
  i32 4, label %sw.bb4
  i32 5, label %sw.bb5
  i32 6, label %sw.bb6
  i32 7, label %sw.bb7
  ]

return:                                           ; preds = %sw.bb7, %sw.bb6, %sw.bb5, %sw.bb4, %sw.bb3, %sw.bb2, %sw.bb1, %entry
  ret void

sw.bb1:                                           ; preds = %entry
  %src.gep.i8 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i8 = getelementptr i8, ptr %dst, i32 0
  %0 = load i8, ptr %src.gep.i8, align 1
  store i8 %0, ptr %dst.gep.i8, align 1
  br label %return

sw.bb2:                                           ; preds = %entry
  %src.gep.i16 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i16 = getelementptr i8, ptr %dst, i32 0
  %1 = load i16, ptr %src.gep.i16, align 2
  store i16 %1, ptr %dst.gep.i16, align 2
  br label %return

sw.bb3:                                           ; preds = %entry
  %src.gep.i161 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i162 = getelementptr i8, ptr %dst, i32 0
  %2 = load i16, ptr %src.gep.i161, align 2
  store i16 %2, ptr %dst.gep.i162, align 2
  %src.gep.i83 = getelementptr i8, ptr %src, i32 2
  %dst.gep.i84 = getelementptr i8, ptr %dst, i32 2
  %3 = load i8, ptr %src.gep.i83, align 1
  store i8 %3, ptr %dst.gep.i84, align 1
  br label %return

sw.bb4:                                           ; preds = %entry
  %src.gep.i32 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i32 = getelementptr i8, ptr %dst, i32 0
  %4 = load i32, ptr %src.gep.i32, align 4
  store i32 %4, ptr %dst.gep.i32, align 4
  br label %return

sw.bb5:                                           ; preds = %entry
  %src.gep.i325 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i326 = getelementptr i8, ptr %dst, i32 0
  %5 = load i32, ptr %src.gep.i325, align 4
  store i32 %5, ptr %dst.gep.i326, align 4
  %src.gep.i87 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i88 = getelementptr i8, ptr %dst, i32 4
  %6 = load i8, ptr %src.gep.i87, align 1
  store i8 %6, ptr %dst.gep.i88, align 1
  br label %return

sw.bb6:                                           ; preds = %entry
  %src.gep.i329 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i3210 = getelementptr i8, ptr %dst, i32 0
  %7 = load i32, ptr %src.gep.i329, align 4
  store i32 %7, ptr %dst.gep.i3210, align 4
  %src.gep.i1611 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1612 = getelementptr i8, ptr %dst, i32 4
  %8 = load i16, ptr %src.gep.i1611, align 2
  store i16 %8, ptr %dst.gep.i1612, align 2
  br label %return

sw.bb7:                                           ; preds = %entry
  %src.gep.i3213 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i3214 = getelementptr i8, ptr %dst, i32 0
  %9 = load i32, ptr %src.gep.i3213, align 4
  store i32 %9, ptr %dst.gep.i3214, align 4
  %src.gep.i1615 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1616 = getelementptr i8, ptr %dst, i32 4
  %10 = load i16, ptr %src.gep.i1615, align 2
  store i16 %10, ptr %dst.gep.i1616, align 2
  %src.gep.i817 = getelementptr i8, ptr %src, i32 6
  %dst.gep.i818 = getelementptr i8, ptr %dst, i32 6
  %11 = load i8, ptr %src.gep.i817, align 1
  store i8 %11, ptr %dst.gep.i818, align 1
  br label %return
}

; Function Attrs: nounwind
declare i32 @llvm.riscv.esp.vst.h.64.ip(i32 immarg, i32, i32 immarg)

; Function Attrs: noinline nounwind
define internal void @esp32p4MemCpySrc16DstunalignVar(ptr %dst, ptr %src, i32 %size, i32 %dst_align)  {
entry:
  %head.size = sub i32 16, %dst_align
  %need.split = icmp ult i32 %head.size, %size
  br i1 %need.split, label %handle.tail, label %handle.head

handle.head:                                      ; preds = %entry
  switch i32 %size, label %return [
  i32 1, label %sw.bb1.i65
  i32 2, label %sw.bb2.i64
  i32 3, label %sw.bb3.i61
  i32 4, label %sw.bb4.i60
  i32 5, label %sw.bb5.i57
  i32 6, label %sw.bb6.i54
  i32 7, label %sw.bb7.i49
  i32 8, label %sw.bb8.i46
  i32 9, label %sw.bb9.i41
  i32 10, label %sw.bb10.i36
  i32 11, label %sw.bb11.i29
  i32 12, label %sw.bb12.i24
  i32 13, label %sw.bb13.i17
  i32 14, label %sw.bb14.i10
  i32 15, label %sw.bb15.i1
  ]

sw.bb1.i65:                                       ; preds = %handle.head
  %0 = load i8, ptr %src, align 1
  store i8 %0, ptr %dst, align 1
  br label %return

sw.bb2.i64:                                       ; preds = %handle.head
  %1 = load i16, ptr %src, align 2
  store i16 %1, ptr %dst, align 2
  br label %return

sw.bb3.i61:                                       ; preds = %handle.head
  %2 = load i16, ptr %src, align 2
  store i16 %2, ptr %dst, align 2
  %src.gep.i83.i62 = getelementptr i8, ptr %src, i32 2
  %dst.gep.i84.i63 = getelementptr i8, ptr %dst, i32 2
  %3 = load i8, ptr %src.gep.i83.i62, align 1
  store i8 %3, ptr %dst.gep.i84.i63, align 1
  br label %return

sw.bb4.i60:                                       ; preds = %handle.head
  %4 = load i32, ptr %src, align 4
  store i32 %4, ptr %dst, align 4
  br label %return

sw.bb5.i57:                                       ; preds = %handle.head
  %5 = load i32, ptr %src, align 4
  store i32 %5, ptr %dst, align 4
  %src.gep.i87.i58 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i88.i59 = getelementptr i8, ptr %dst, i32 4
  %6 = load i8, ptr %src.gep.i87.i58, align 1
  store i8 %6, ptr %dst.gep.i88.i59, align 1
  br label %return

sw.bb6.i54:                                       ; preds = %handle.head
  %7 = load i32, ptr %src, align 4
  store i32 %7, ptr %dst, align 4
  %src.gep.i1611.i55 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1612.i56 = getelementptr i8, ptr %dst, i32 4
  %8 = load i16, ptr %src.gep.i1611.i55, align 2
  store i16 %8, ptr %dst.gep.i1612.i56, align 2
  br label %return

sw.bb7.i49:                                       ; preds = %handle.head
  %9 = load i32, ptr %src, align 4
  store i32 %9, ptr %dst, align 4
  %src.gep.i1615.i50 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1616.i51 = getelementptr i8, ptr %dst, i32 4
  %10 = load i16, ptr %src.gep.i1615.i50, align 2
  store i16 %10, ptr %dst.gep.i1616.i51, align 2
  %src.gep.i817.i52 = getelementptr i8, ptr %src, i32 6
  %dst.gep.i818.i53 = getelementptr i8, ptr %dst, i32 6
  %11 = load i8, ptr %src.gep.i817.i52, align 1
  store i8 %11, ptr %dst.gep.i818.i53, align 1
  br label %return

sw.bb8.i46:                                       ; preds = %handle.head
  %12 = load i32, ptr %src, align 4
  store i32 %12, ptr %dst, align 4
  %src.gep.i3221.i47 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3222.i48 = getelementptr i8, ptr %dst, i32 4
  %13 = load i32, ptr %src.gep.i3221.i47, align 4
  store i32 %13, ptr %dst.gep.i3222.i48, align 4
  br label %return

sw.bb9.i41:                                       ; preds = %handle.head
  %14 = load i32, ptr %src, align 4
  store i32 %14, ptr %dst, align 4
  %src.gep.i3225.i42 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3226.i43 = getelementptr i8, ptr %dst, i32 4
  %15 = load i32, ptr %src.gep.i3225.i42, align 4
  store i32 %15, ptr %dst.gep.i3226.i43, align 4
  %src.gep.i827.i44 = getelementptr i8, ptr %src, i32 8
  %dst.gep.i828.i45 = getelementptr i8, ptr %dst, i32 8
  %16 = load i8, ptr %src.gep.i827.i44, align 1
  store i8 %16, ptr %dst.gep.i828.i45, align 1
  br label %return

sw.bb10.i36:                                      ; preds = %handle.head
  %17 = load i32, ptr %src, align 4
  store i32 %17, ptr %dst, align 4
  %src.gep.i3231.i37 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3232.i38 = getelementptr i8, ptr %dst, i32 4
  %18 = load i32, ptr %src.gep.i3231.i37, align 4
  store i32 %18, ptr %dst.gep.i3232.i38, align 4
  %src.gep.i1633.i39 = getelementptr i8, ptr %src, i32 8
  %dst.gep.i1634.i40 = getelementptr i8, ptr %dst, i32 8
  %19 = load i16, ptr %src.gep.i1633.i39, align 2
  store i16 %19, ptr %dst.gep.i1634.i40, align 2
  br label %return

sw.bb11.i29:                                      ; preds = %handle.head
  %20 = load i32, ptr %src, align 4
  store i32 %20, ptr %dst, align 4
  %src.gep.i3237.i30 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3238.i31 = getelementptr i8, ptr %dst, i32 4
  %21 = load i32, ptr %src.gep.i3237.i30, align 4
  store i32 %21, ptr %dst.gep.i3238.i31, align 4
  %src.gep.i1639.i32 = getelementptr i8, ptr %src, i32 8
  %dst.gep.i1640.i33 = getelementptr i8, ptr %dst, i32 8
  %22 = load i16, ptr %src.gep.i1639.i32, align 2
  store i16 %22, ptr %dst.gep.i1640.i33, align 2
  %src.gep.i841.i34 = getelementptr i8, ptr %src, i32 10
  %dst.gep.i842.i35 = getelementptr i8, ptr %dst, i32 10
  %23 = load i8, ptr %src.gep.i841.i34, align 1
  store i8 %23, ptr %dst.gep.i842.i35, align 1
  br label %return

sw.bb12.i24:                                      ; preds = %handle.head
  %24 = load i32, ptr %src, align 4
  store i32 %24, ptr %dst, align 4
  %src.gep.i3245.i25 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3246.i26 = getelementptr i8, ptr %dst, i32 4
  %25 = load i32, ptr %src.gep.i3245.i25, align 4
  store i32 %25, ptr %dst.gep.i3246.i26, align 4
  %src.gep.i3247.i27 = getelementptr i8, ptr %src, i32 8
  %dst.gep.i3248.i28 = getelementptr i8, ptr %dst, i32 8
  %26 = load i32, ptr %src.gep.i3247.i27, align 4
  store i32 %26, ptr %dst.gep.i3248.i28, align 4
  br label %return

sw.bb13.i17:                                      ; preds = %handle.head
  %27 = load i32, ptr %src, align 4
  store i32 %27, ptr %dst, align 4
  %src.gep.i3251.i18 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3252.i19 = getelementptr i8, ptr %dst, i32 4
  %28 = load i32, ptr %src.gep.i3251.i18, align 4
  store i32 %28, ptr %dst.gep.i3252.i19, align 4
  %src.gep.i3253.i20 = getelementptr i8, ptr %src, i32 8
  %dst.gep.i3254.i21 = getelementptr i8, ptr %dst, i32 8
  %29 = load i32, ptr %src.gep.i3253.i20, align 4
  store i32 %29, ptr %dst.gep.i3254.i21, align 4
  %src.gep.i855.i22 = getelementptr i8, ptr %src, i32 12
  %dst.gep.i856.i23 = getelementptr i8, ptr %dst, i32 12
  %30 = load i8, ptr %src.gep.i855.i22, align 1
  store i8 %30, ptr %dst.gep.i856.i23, align 1
  br label %return

sw.bb14.i10:                                      ; preds = %handle.head
  %31 = load i32, ptr %src, align 4
  store i32 %31, ptr %dst, align 4
  %src.gep.i3259.i11 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3260.i12 = getelementptr i8, ptr %dst, i32 4
  %32 = load i32, ptr %src.gep.i3259.i11, align 4
  store i32 %32, ptr %dst.gep.i3260.i12, align 4
  %src.gep.i3261.i13 = getelementptr i8, ptr %src, i32 8
  %dst.gep.i3262.i14 = getelementptr i8, ptr %dst, i32 8
  %33 = load i32, ptr %src.gep.i3261.i13, align 4
  store i32 %33, ptr %dst.gep.i3262.i14, align 4
  %src.gep.i1663.i15 = getelementptr i8, ptr %src, i32 12
  %dst.gep.i1664.i16 = getelementptr i8, ptr %dst, i32 12
  %34 = load i16, ptr %src.gep.i1663.i15, align 2
  store i16 %34, ptr %dst.gep.i1664.i16, align 2
  br label %return

sw.bb15.i1:                                       ; preds = %handle.head
  %35 = load i32, ptr %src, align 4
  store i32 %35, ptr %dst, align 4
  %src.gep.i3267.i2 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3268.i3 = getelementptr i8, ptr %dst, i32 4
  %36 = load i32, ptr %src.gep.i3267.i2, align 4
  store i32 %36, ptr %dst.gep.i3268.i3, align 4
  %src.gep.i3269.i4 = getelementptr i8, ptr %src, i32 8
  %dst.gep.i3270.i5 = getelementptr i8, ptr %dst, i32 8
  %37 = load i32, ptr %src.gep.i3269.i4, align 4
  store i32 %37, ptr %dst.gep.i3270.i5, align 4
  %src.gep.i1671.i6 = getelementptr i8, ptr %src, i32 12
  %dst.gep.i1672.i7 = getelementptr i8, ptr %dst, i32 12
  %38 = load i16, ptr %src.gep.i1671.i6, align 2
  store i16 %38, ptr %dst.gep.i1672.i7, align 2
  %src.gep.i873.i8 = getelementptr i8, ptr %src, i32 14
  %dst.gep.i874.i9 = getelementptr i8, ptr %dst, i32 14
  %39 = load i8, ptr %src.gep.i873.i8, align 1
  store i8 %39, ptr %dst.gep.i874.i9, align 1
  br label %return

handle.tail:                                      ; preds = %entry
  switch i32 %dst_align, label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit [
  i32 15, label %sw.bb1.i
  i32 14, label %sw.bb2.i
  i32 13, label %sw.bb3.i
  i32 12, label %sw.bb4.i
  i32 11, label %sw.bb5.i
  i32 10, label %sw.bb6.i
  i32 9, label %sw.bb7.i
  i32 8, label %sw.bb8.i
  i32 7, label %sw.bb9.i
  i32 6, label %sw.bb10.i
  i32 5, label %sw.bb11.i
  i32 4, label %sw.bb12.i
  i32 3, label %sw.bb13.i
  i32 2, label %sw.bb14.i
  i32 1, label %sw.bb15.i
  ]

sw.bb1.i:                                         ; preds = %handle.tail
  %40 = load i8, ptr %src, align 1
  store i8 %40, ptr %dst, align 1
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb2.i:                                         ; preds = %handle.tail
  %41 = load i16, ptr %src, align 2
  store i16 %41, ptr %dst, align 2
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb3.i:                                         ; preds = %handle.tail
  %42 = load i16, ptr %src, align 2
  store i16 %42, ptr %dst, align 2
  %src.gep.i83.i = getelementptr i8, ptr %src, i32 2
  %dst.gep.i84.i = getelementptr i8, ptr %dst, i32 2
  %43 = load i8, ptr %src.gep.i83.i, align 1
  store i8 %43, ptr %dst.gep.i84.i, align 1
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb4.i:                                         ; preds = %handle.tail
  %44 = load i32, ptr %src, align 4
  store i32 %44, ptr %dst, align 4
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb5.i:                                         ; preds = %handle.tail
  %45 = load i32, ptr %src, align 4
  store i32 %45, ptr %dst, align 4
  %src.gep.i87.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i88.i = getelementptr i8, ptr %dst, i32 4
  %46 = load i8, ptr %src.gep.i87.i, align 1
  store i8 %46, ptr %dst.gep.i88.i, align 1
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb6.i:                                         ; preds = %handle.tail
  %47 = load i32, ptr %src, align 4
  store i32 %47, ptr %dst, align 4
  %src.gep.i1611.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1612.i = getelementptr i8, ptr %dst, i32 4
  %48 = load i16, ptr %src.gep.i1611.i, align 2
  store i16 %48, ptr %dst.gep.i1612.i, align 2
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb7.i:                                         ; preds = %handle.tail
  %49 = load i32, ptr %src, align 4
  store i32 %49, ptr %dst, align 4
  %src.gep.i1615.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1616.i = getelementptr i8, ptr %dst, i32 4
  %50 = load i16, ptr %src.gep.i1615.i, align 2
  store i16 %50, ptr %dst.gep.i1616.i, align 2
  %src.gep.i817.i = getelementptr i8, ptr %src, i32 6
  %dst.gep.i818.i = getelementptr i8, ptr %dst, i32 6
  %51 = load i8, ptr %src.gep.i817.i, align 1
  store i8 %51, ptr %dst.gep.i818.i, align 1
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb8.i:                                         ; preds = %handle.tail
  %52 = load i32, ptr %src, align 4
  store i32 %52, ptr %dst, align 4
  %src.gep.i3221.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3222.i = getelementptr i8, ptr %dst, i32 4
  %53 = load i32, ptr %src.gep.i3221.i, align 4
  store i32 %53, ptr %dst.gep.i3222.i, align 4
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb9.i:                                         ; preds = %handle.tail
  %54 = load i32, ptr %src, align 4
  store i32 %54, ptr %dst, align 4
  %src.gep.i3225.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3226.i = getelementptr i8, ptr %dst, i32 4
  %55 = load i32, ptr %src.gep.i3225.i, align 4
  store i32 %55, ptr %dst.gep.i3226.i, align 4
  %src.gep.i827.i = getelementptr i8, ptr %src, i32 8
  %dst.gep.i828.i = getelementptr i8, ptr %dst, i32 8
  %56 = load i8, ptr %src.gep.i827.i, align 1
  store i8 %56, ptr %dst.gep.i828.i, align 1
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb10.i:                                        ; preds = %handle.tail
  %57 = load i32, ptr %src, align 4
  store i32 %57, ptr %dst, align 4
  %src.gep.i3231.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3232.i = getelementptr i8, ptr %dst, i32 4
  %58 = load i32, ptr %src.gep.i3231.i, align 4
  store i32 %58, ptr %dst.gep.i3232.i, align 4
  %src.gep.i1633.i = getelementptr i8, ptr %src, i32 8
  %dst.gep.i1634.i = getelementptr i8, ptr %dst, i32 8
  %59 = load i16, ptr %src.gep.i1633.i, align 2
  store i16 %59, ptr %dst.gep.i1634.i, align 2
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb11.i:                                        ; preds = %handle.tail
  %60 = load i32, ptr %src, align 4
  store i32 %60, ptr %dst, align 4
  %src.gep.i3237.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3238.i = getelementptr i8, ptr %dst, i32 4
  %61 = load i32, ptr %src.gep.i3237.i, align 4
  store i32 %61, ptr %dst.gep.i3238.i, align 4
  %src.gep.i1639.i = getelementptr i8, ptr %src, i32 8
  %dst.gep.i1640.i = getelementptr i8, ptr %dst, i32 8
  %62 = load i16, ptr %src.gep.i1639.i, align 2
  store i16 %62, ptr %dst.gep.i1640.i, align 2
  %src.gep.i841.i = getelementptr i8, ptr %src, i32 10
  %dst.gep.i842.i = getelementptr i8, ptr %dst, i32 10
  %63 = load i8, ptr %src.gep.i841.i, align 1
  store i8 %63, ptr %dst.gep.i842.i, align 1
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb12.i:                                        ; preds = %handle.tail
  %64 = load i32, ptr %src, align 4
  store i32 %64, ptr %dst, align 4
  %src.gep.i3245.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3246.i = getelementptr i8, ptr %dst, i32 4
  %65 = load i32, ptr %src.gep.i3245.i, align 4
  store i32 %65, ptr %dst.gep.i3246.i, align 4
  %src.gep.i3247.i = getelementptr i8, ptr %src, i32 8
  %dst.gep.i3248.i = getelementptr i8, ptr %dst, i32 8
  %66 = load i32, ptr %src.gep.i3247.i, align 4
  store i32 %66, ptr %dst.gep.i3248.i, align 4
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb13.i:                                        ; preds = %handle.tail
  %67 = load i32, ptr %src, align 4
  store i32 %67, ptr %dst, align 4
  %src.gep.i3251.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3252.i = getelementptr i8, ptr %dst, i32 4
  %68 = load i32, ptr %src.gep.i3251.i, align 4
  store i32 %68, ptr %dst.gep.i3252.i, align 4
  %src.gep.i3253.i = getelementptr i8, ptr %src, i32 8
  %dst.gep.i3254.i = getelementptr i8, ptr %dst, i32 8
  %69 = load i32, ptr %src.gep.i3253.i, align 4
  store i32 %69, ptr %dst.gep.i3254.i, align 4
  %src.gep.i855.i = getelementptr i8, ptr %src, i32 12
  %dst.gep.i856.i = getelementptr i8, ptr %dst, i32 12
  %70 = load i8, ptr %src.gep.i855.i, align 1
  store i8 %70, ptr %dst.gep.i856.i, align 1
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb14.i:                                        ; preds = %handle.tail
  %71 = load i32, ptr %src, align 4
  store i32 %71, ptr %dst, align 4
  %src.gep.i3259.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3260.i = getelementptr i8, ptr %dst, i32 4
  %72 = load i32, ptr %src.gep.i3259.i, align 4
  store i32 %72, ptr %dst.gep.i3260.i, align 4
  %src.gep.i3261.i = getelementptr i8, ptr %src, i32 8
  %dst.gep.i3262.i = getelementptr i8, ptr %dst, i32 8
  %73 = load i32, ptr %src.gep.i3261.i, align 4
  store i32 %73, ptr %dst.gep.i3262.i, align 4
  %src.gep.i1663.i = getelementptr i8, ptr %src, i32 12
  %dst.gep.i1664.i = getelementptr i8, ptr %dst, i32 12
  %74 = load i16, ptr %src.gep.i1663.i, align 2
  store i16 %74, ptr %dst.gep.i1664.i, align 2
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

sw.bb15.i:                                        ; preds = %handle.tail
  %75 = load i32, ptr %src, align 4
  store i32 %75, ptr %dst, align 4
  %src.gep.i3267.i = getelementptr i8, ptr %src, i32 4
  %dst.gep.i3268.i = getelementptr i8, ptr %dst, i32 4
  %76 = load i32, ptr %src.gep.i3267.i, align 4
  store i32 %76, ptr %dst.gep.i3268.i, align 4
  %src.gep.i3269.i = getelementptr i8, ptr %src, i32 8
  %dst.gep.i3270.i = getelementptr i8, ptr %dst, i32 8
  %77 = load i32, ptr %src.gep.i3269.i, align 4
  store i32 %77, ptr %dst.gep.i3270.i, align 4
  %src.gep.i1671.i = getelementptr i8, ptr %src, i32 12
  %dst.gep.i1672.i = getelementptr i8, ptr %dst, i32 12
  %78 = load i16, ptr %src.gep.i1671.i, align 2
  store i16 %78, ptr %dst.gep.i1672.i, align 2
  %src.gep.i873.i = getelementptr i8, ptr %src, i32 14
  %dst.gep.i874.i = getelementptr i8, ptr %dst, i32 14
  %79 = load i8, ptr %src.gep.i873.i, align 1
  store i8 %79, ptr %dst.gep.i874.i, align 1
  br label %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit

esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit: ; preds = %handle.tail, %sw.bb1.i, %sw.bb2.i, %sw.bb3.i, %sw.bb4.i, %sw.bb5.i, %sw.bb6.i, %sw.bb7.i, %sw.bb8.i, %sw.bb9.i, %sw.bb10.i, %sw.bb11.i, %sw.bb12.i, %sw.bb13.i, %sw.bb14.i, %sw.bb15.i
  %remaining.size = sub i32 %size, %head.size
  %dst.aligned.ptr = getelementptr i8, ptr %dst, i32 %head.size
  %src.aligned.ptr = getelementptr i8, ptr %src, i32 %head.size
  %80 = ptrtoint ptr %src.aligned.ptr to i32
  %81 = ptrtoint ptr %dst.aligned.ptr to i32
  %size.is.small.i = icmp ult i32 %remaining.size, 16
  br i1 %size.is.small.i, label %final.cleanup.i, label %process.main.loop.i

process.main.loop.i:                              ; preds = %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit
  %blocks.48.count.i = udiv i32 %remaining.size, 48
  %.neg = mul i32 %blocks.48.count.i, -48
  %remainder.after.48blocks.i = add i32 %.neg, %remaining.size
  %ld128usarip.i = call i32 @llvm.riscv.esp.ld.128.usar.ip(i32 %80, i32 16, i32 0)
  %ld128usarip1.i = call i32 @llvm.riscv.esp.ld.128.usar.ip(i32 %ld128usarip.i, i32 16, i32 1)
  %no.48byte.blocks.i = icmp ult i32 %remaining.size, 48
  br i1 %no.48byte.blocks.i, label %handle.remainder.i, label %main.loop.body.i

handle.remainder.i:                               ; preds = %main.loop.body.i, %process.main.loop.i
  %src.ptr.after.main.loop.i = phi i32 [ %ld128usarip1.i, %process.main.loop.i ], [ %srcqldip4.after.block.i, %main.loop.body.i ]
  %dst.ptr.after.main.loop.i = phi i32 [ %81, %process.main.loop.i ], [ %vst128ip5.after.block.i, %main.loop.body.i ]
  %remainder.has.no.32bytes.i = icmp ult i32 %remainder.after.48blocks.i, 32
  br i1 %remainder.has.no.32bytes.i, label %check.16byte.tail.i, label %process.32byte.tail.i

main.loop.body.i:                                 ; preds = %main.loop.body.i, %process.main.loop.i
  %loop.index.i = phi i32 [ 0, %process.main.loop.i ], [ %loop.index.incremented.i, %main.loop.body.i ]
  %src.ptr.in.loop.i = phi i32 [ %ld128usarip1.i, %process.main.loop.i ], [ %srcqldip4.after.block.i, %main.loop.body.i ]
  %dst.ptr.in.loop.i = phi i32 [ %81, %process.main.loop.i ], [ %vst128ip5.after.block.i, %main.loop.body.i ]
  %srcqldip.i = call i32 @llvm.riscv.esp.src.q.ld.ip(i32 1, i32 %src.ptr.in.loop.i, i32 0, i32 16, i32 2)
  %vst128ip.i = call i32 @llvm.riscv.esp.vst.128.ip(i32 0, i32 %dst.ptr.in.loop.i, i32 16)
  %srcqldip2.i = call i32 @llvm.riscv.esp.src.q.ld.ip(i32 2, i32 %srcqldip.i, i32 1, i32 16, i32 0)
  %vst128ip3.i = call i32 @llvm.riscv.esp.vst.128.ip(i32 1, i32 %vst128ip.i, i32 16)
  %srcqldip4.after.block.i = call i32 @llvm.riscv.esp.src.q.ld.ip(i32 0, i32 %srcqldip2.i, i32 2, i32 16, i32 1)
  %vst128ip5.after.block.i = call i32 @llvm.riscv.esp.vst.128.ip(i32 2, i32 %vst128ip3.i, i32 16)
  %loop.index.incremented.i = add nuw nsw i32 %loop.index.i, 1
  %loop.completed.i = icmp eq i32 %loop.index.incremented.i, %blocks.48.count.i
  br i1 %loop.completed.i, label %handle.remainder.i, label %main.loop.body.i

process.32byte.tail.i:                            ; preds = %handle.remainder.i
  %srcqldip6.i = call i32 @llvm.riscv.esp.src.q.ld.ip(i32 1, i32 %src.ptr.after.main.loop.i, i32 0, i32 0, i32 2)
  %vst128ip7.i = call i32 @llvm.riscv.esp.vst.128.ip(i32 0, i32 %dst.ptr.after.main.loop.i, i32 16)
  call void @llvm.riscv.esp.src.q(i32 2, i32 1, i32 1)
  %vst128ip8.i = call i32 @llvm.riscv.esp.vst.128.ip(i32 1, i32 %vst128ip7.i, i32 16)
  %remainder.after.32byte.processing.i = add nsw i32 %remainder.after.48blocks.i, -32
  br label %final.cleanup.i

check.16byte.tail.i:                              ; preds = %handle.remainder.i
  %remainder.has.no.16bytes.i = icmp ult i32 %remainder.after.48blocks.i, 16
  br i1 %remainder.has.no.16bytes.i, label %skip.tail.processing.i, label %process.16byte.tail.i

process.16byte.tail.i:                            ; preds = %check.16byte.tail.i
  call void @llvm.riscv.esp.src.q(i32 1, i32 0, i32 0)
  %vst128ip9.i = call i32 @llvm.riscv.esp.vst.128.ip(i32 0, i32 %dst.ptr.after.main.loop.i, i32 16)
  %src.after.16byte.processing.i = add i32 %src.ptr.after.main.loop.i, -16
  %remainder.after.16byte.processing.i = add nsw i32 %remainder.after.48blocks.i, -16
  br label %final.cleanup.i

skip.tail.processing.i:                           ; preds = %check.16byte.tail.i
  %src.adjusted.for.unaligned.i = add i32 %src.ptr.after.main.loop.i, -32
  br label %final.cleanup.i

final.cleanup.i:                                  ; preds = %skip.tail.processing.i, %process.16byte.tail.i, %process.32byte.tail.i, %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit
  %src.for.final.processing.i = phi i32 [ %srcqldip6.i, %process.32byte.tail.i ], [ %src.after.16byte.processing.i, %process.16byte.tail.i ], [ %80, %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit ], [ %src.adjusted.for.unaligned.i, %skip.tail.processing.i ]
  %dst.for.final.processing.i = phi i32 [ %vst128ip8.i, %process.32byte.tail.i ], [ %vst128ip9.i, %process.16byte.tail.i ], [ %81, %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit ], [ %dst.ptr.after.main.loop.i, %skip.tail.processing.i ]
  %remainder.for.final.processing.i = phi i32 [ %remainder.after.32byte.processing.i, %process.32byte.tail.i ], [ %remainder.after.16byte.processing.i, %process.16byte.tail.i ], [ %remaining.size, %esp32p4MemCpySrcUnalignDstUnalignFrom1To15Opt.exit ], [ %remainder.after.48blocks.i, %skip.tail.processing.i ]
  %has.no.remaining.bytes.i = icmp eq i32 %remainder.for.final.processing.i, 0
  br i1 %has.no.remaining.bytes.i, label %return, label %call.small.size.cleanup.i

call.small.size.cleanup.i:                        ; preds = %final.cleanup.i
  %dst.ptr.for.small.size.cleanup.i = inttoptr i32 %dst.for.final.processing.i to ptr
  %src.ptr.for.small.size.cleanup.i = inttoptr i32 %src.for.final.processing.i to ptr
  switch i32 %remainder.for.final.processing.i, label %return [
  i32 1, label %sw.bb1.i131
  i32 2, label %sw.bb2.i130
  i32 3, label %sw.bb3.i127
  i32 4, label %sw.bb4.i126
  i32 5, label %sw.bb5.i123
  i32 6, label %sw.bb6.i120
  i32 7, label %sw.bb7.i115
  i32 8, label %sw.bb8.i112
  i32 9, label %sw.bb9.i107
  i32 10, label %sw.bb10.i102
  i32 11, label %sw.bb11.i95
  i32 12, label %sw.bb12.i90
  i32 13, label %sw.bb13.i83
  i32 14, label %sw.bb14.i76
  i32 15, label %sw.bb15.i67
  ]

sw.bb1.i131:                                      ; preds = %call.small.size.cleanup.i
  %82 = load i8, ptr %src.ptr.for.small.size.cleanup.i, align 1
  store i8 %82, ptr %dst.ptr.for.small.size.cleanup.i, align 1
  br label %return

sw.bb2.i130:                                      ; preds = %call.small.size.cleanup.i
  %83 = load i16, ptr %src.ptr.for.small.size.cleanup.i, align 2
  store i16 %83, ptr %dst.ptr.for.small.size.cleanup.i, align 2
  br label %return

sw.bb3.i127:                                      ; preds = %call.small.size.cleanup.i
  %84 = load i16, ptr %src.ptr.for.small.size.cleanup.i, align 2
  store i16 %84, ptr %dst.ptr.for.small.size.cleanup.i, align 2
  %src.gep.i83.i128 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 2
  %dst.gep.i84.i129 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 2
  %85 = load i8, ptr %src.gep.i83.i128, align 1
  store i8 %85, ptr %dst.gep.i84.i129, align 1
  br label %return

sw.bb4.i126:                                      ; preds = %call.small.size.cleanup.i
  %86 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %86, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  br label %return

sw.bb5.i123:                                      ; preds = %call.small.size.cleanup.i
  %87 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %87, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i87.i124 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i88.i125 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %88 = load i8, ptr %src.gep.i87.i124, align 1
  store i8 %88, ptr %dst.gep.i88.i125, align 1
  br label %return

sw.bb6.i120:                                      ; preds = %call.small.size.cleanup.i
  %89 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %89, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i1611.i121 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i1612.i122 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %90 = load i16, ptr %src.gep.i1611.i121, align 2
  store i16 %90, ptr %dst.gep.i1612.i122, align 2
  br label %return

sw.bb7.i115:                                      ; preds = %call.small.size.cleanup.i
  %91 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %91, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i1615.i116 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i1616.i117 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %92 = load i16, ptr %src.gep.i1615.i116, align 2
  store i16 %92, ptr %dst.gep.i1616.i117, align 2
  %src.gep.i817.i118 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 6
  %dst.gep.i818.i119 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 6
  %93 = load i8, ptr %src.gep.i817.i118, align 1
  store i8 %93, ptr %dst.gep.i818.i119, align 1
  br label %return

sw.bb8.i112:                                      ; preds = %call.small.size.cleanup.i
  %94 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %94, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i3221.i113 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i3222.i114 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %95 = load i32, ptr %src.gep.i3221.i113, align 4
  store i32 %95, ptr %dst.gep.i3222.i114, align 4
  br label %return

sw.bb9.i107:                                      ; preds = %call.small.size.cleanup.i
  %96 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %96, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i3225.i108 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i3226.i109 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %97 = load i32, ptr %src.gep.i3225.i108, align 4
  store i32 %97, ptr %dst.gep.i3226.i109, align 4
  %src.gep.i827.i110 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 8
  %dst.gep.i828.i111 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 8
  %98 = load i8, ptr %src.gep.i827.i110, align 1
  store i8 %98, ptr %dst.gep.i828.i111, align 1
  br label %return

sw.bb10.i102:                                     ; preds = %call.small.size.cleanup.i
  %99 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %99, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i3231.i103 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i3232.i104 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %100 = load i32, ptr %src.gep.i3231.i103, align 4
  store i32 %100, ptr %dst.gep.i3232.i104, align 4
  %src.gep.i1633.i105 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 8
  %dst.gep.i1634.i106 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 8
  %101 = load i16, ptr %src.gep.i1633.i105, align 2
  store i16 %101, ptr %dst.gep.i1634.i106, align 2
  br label %return

sw.bb11.i95:                                      ; preds = %call.small.size.cleanup.i
  %102 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %102, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i3237.i96 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i3238.i97 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %103 = load i32, ptr %src.gep.i3237.i96, align 4
  store i32 %103, ptr %dst.gep.i3238.i97, align 4
  %src.gep.i1639.i98 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 8
  %dst.gep.i1640.i99 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 8
  %104 = load i16, ptr %src.gep.i1639.i98, align 2
  store i16 %104, ptr %dst.gep.i1640.i99, align 2
  %src.gep.i841.i100 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 10
  %dst.gep.i842.i101 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 10
  %105 = load i8, ptr %src.gep.i841.i100, align 1
  store i8 %105, ptr %dst.gep.i842.i101, align 1
  br label %return

sw.bb12.i90:                                      ; preds = %call.small.size.cleanup.i
  %106 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %106, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i3245.i91 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i3246.i92 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %107 = load i32, ptr %src.gep.i3245.i91, align 4
  store i32 %107, ptr %dst.gep.i3246.i92, align 4
  %src.gep.i3247.i93 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 8
  %dst.gep.i3248.i94 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 8
  %108 = load i32, ptr %src.gep.i3247.i93, align 4
  store i32 %108, ptr %dst.gep.i3248.i94, align 4
  br label %return

sw.bb13.i83:                                      ; preds = %call.small.size.cleanup.i
  %109 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %109, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i3251.i84 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i3252.i85 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %110 = load i32, ptr %src.gep.i3251.i84, align 4
  store i32 %110, ptr %dst.gep.i3252.i85, align 4
  %src.gep.i3253.i86 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 8
  %dst.gep.i3254.i87 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 8
  %111 = load i32, ptr %src.gep.i3253.i86, align 4
  store i32 %111, ptr %dst.gep.i3254.i87, align 4
  %src.gep.i855.i88 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 12
  %dst.gep.i856.i89 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 12
  %112 = load i8, ptr %src.gep.i855.i88, align 1
  store i8 %112, ptr %dst.gep.i856.i89, align 1
  br label %return

sw.bb14.i76:                                      ; preds = %call.small.size.cleanup.i
  %113 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %113, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i3259.i77 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i3260.i78 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %114 = load i32, ptr %src.gep.i3259.i77, align 4
  store i32 %114, ptr %dst.gep.i3260.i78, align 4
  %src.gep.i3261.i79 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 8
  %dst.gep.i3262.i80 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 8
  %115 = load i32, ptr %src.gep.i3261.i79, align 4
  store i32 %115, ptr %dst.gep.i3262.i80, align 4
  %src.gep.i1663.i81 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 12
  %dst.gep.i1664.i82 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 12
  %116 = load i16, ptr %src.gep.i1663.i81, align 2
  store i16 %116, ptr %dst.gep.i1664.i82, align 2
  br label %return

sw.bb15.i67:                                      ; preds = %call.small.size.cleanup.i
  %117 = load i32, ptr %src.ptr.for.small.size.cleanup.i, align 4
  store i32 %117, ptr %dst.ptr.for.small.size.cleanup.i, align 4
  %src.gep.i3267.i68 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 4
  %dst.gep.i3268.i69 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 4
  %118 = load i32, ptr %src.gep.i3267.i68, align 4
  store i32 %118, ptr %dst.gep.i3268.i69, align 4
  %src.gep.i3269.i70 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 8
  %dst.gep.i3270.i71 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 8
  %119 = load i32, ptr %src.gep.i3269.i70, align 4
  store i32 %119, ptr %dst.gep.i3270.i71, align 4
  %src.gep.i1671.i72 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 12
  %dst.gep.i1672.i73 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 12
  %120 = load i16, ptr %src.gep.i1671.i72, align 2
  store i16 %120, ptr %dst.gep.i1672.i73, align 2
  %src.gep.i873.i74 = getelementptr i8, ptr %src.ptr.for.small.size.cleanup.i, i32 14
  %dst.gep.i874.i75 = getelementptr i8, ptr %dst.ptr.for.small.size.cleanup.i, i32 14
  %121 = load i8, ptr %src.gep.i873.i74, align 1
  store i8 %121, ptr %dst.gep.i874.i75, align 1
  br label %return

return:                                           ; preds = %final.cleanup.i, %call.small.size.cleanup.i, %sw.bb1.i131, %sw.bb2.i130, %sw.bb3.i127, %sw.bb4.i126, %sw.bb5.i123, %sw.bb6.i120, %sw.bb7.i115, %sw.bb8.i112, %sw.bb9.i107, %sw.bb10.i102, %sw.bb11.i95, %sw.bb12.i90, %sw.bb13.i83, %sw.bb14.i76, %sw.bb15.i67, %sw.bb15.i1, %sw.bb14.i10, %sw.bb13.i17, %sw.bb12.i24, %sw.bb11.i29, %sw.bb10.i36, %sw.bb9.i41, %sw.bb8.i46, %sw.bb7.i49, %sw.bb6.i54, %sw.bb5.i57, %sw.bb4.i60, %sw.bb3.i61, %sw.bb2.i64, %sw.bb1.i65, %handle.head
  ret void
}

; Function Attrs: noinline nounwind
define internal void @esp32p4MemCpySrc8Dst16From1To7Opt(ptr %dst, ptr %src, i32 %size)  {
entry:
  switch i32 %size, label %return [
  i32 1, label %sw.bb1
  i32 2, label %sw.bb2
  i32 3, label %sw.bb3
  i32 4, label %sw.bb4
  i32 5, label %sw.bb5
  i32 6, label %sw.bb6
  i32 7, label %sw.bb7
  ]

return:                                           ; preds = %sw.bb7, %sw.bb6, %sw.bb5, %sw.bb4, %sw.bb3, %sw.bb2, %sw.bb1, %entry
  ret void

sw.bb1:                                           ; preds = %entry
  %src.gep.i8 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i8 = getelementptr i8, ptr %dst, i32 0
  %0 = load i8, ptr %src.gep.i8, align 1
  store i8 %0, ptr %dst.gep.i8, align 1
  br label %return

sw.bb2:                                           ; preds = %entry
  %src.gep.i16 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i16 = getelementptr i8, ptr %dst, i32 0
  %1 = load i16, ptr %src.gep.i16, align 2
  store i16 %1, ptr %dst.gep.i16, align 2
  br label %return

sw.bb3:                                           ; preds = %entry
  %src.gep.i161 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i162 = getelementptr i8, ptr %dst, i32 0
  %2 = load i16, ptr %src.gep.i161, align 2
  store i16 %2, ptr %dst.gep.i162, align 2
  %src.gep.i83 = getelementptr i8, ptr %src, i32 2
  %dst.gep.i84 = getelementptr i8, ptr %dst, i32 2
  %3 = load i8, ptr %src.gep.i83, align 1
  store i8 %3, ptr %dst.gep.i84, align 1
  br label %return

sw.bb4:                                           ; preds = %entry
  %src.gep.i32 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i32 = getelementptr i8, ptr %dst, i32 0
  %4 = load i32, ptr %src.gep.i32, align 4
  store i32 %4, ptr %dst.gep.i32, align 4
  br label %return

sw.bb5:                                           ; preds = %entry
  %src.gep.i325 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i326 = getelementptr i8, ptr %dst, i32 0
  %5 = load i32, ptr %src.gep.i325, align 4
  store i32 %5, ptr %dst.gep.i326, align 4
  %src.gep.i87 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i88 = getelementptr i8, ptr %dst, i32 4
  %6 = load i8, ptr %src.gep.i87, align 1
  store i8 %6, ptr %dst.gep.i88, align 1
  br label %return

sw.bb6:                                           ; preds = %entry
  %src.gep.i329 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i3210 = getelementptr i8, ptr %dst, i32 0
  %7 = load i32, ptr %src.gep.i329, align 4
  store i32 %7, ptr %dst.gep.i3210, align 4
  %src.gep.i1611 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1612 = getelementptr i8, ptr %dst, i32 4
  %8 = load i16, ptr %src.gep.i1611, align 2
  store i16 %8, ptr %dst.gep.i1612, align 2
  br label %return

sw.bb7:                                           ; preds = %entry
  %src.gep.i3213 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i3214 = getelementptr i8, ptr %dst, i32 0
  %9 = load i32, ptr %src.gep.i3213, align 4
  store i32 %9, ptr %dst.gep.i3214, align 4
  %src.gep.i1615 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1616 = getelementptr i8, ptr %dst, i32 4
  %10 = load i16, ptr %src.gep.i1615, align 2
  store i16 %10, ptr %dst.gep.i1616, align 2
  %src.gep.i817 = getelementptr i8, ptr %src, i32 6
  %dst.gep.i818 = getelementptr i8, ptr %dst, i32 6
  %11 = load i8, ptr %src.gep.i817, align 1
  store i8 %11, ptr %dst.gep.i818, align 1
  br label %return
}

; Function Attrs: nounwind
declare i32 @llvm.riscv.esp.vld.h.64.ip(i32, i32 immarg, i32 immarg)

; Function Attrs: noinline nounwind
define internal void @esp32p4MemCpySrc8Dst8From1To7Opt(ptr %dst, ptr %src, i32 %size)  {
entry:
  switch i32 %size, label %return [
  i32 1, label %sw.bb1
  i32 2, label %sw.bb2
  i32 3, label %sw.bb3
  i32 4, label %sw.bb4
  i32 5, label %sw.bb5
  i32 6, label %sw.bb6
  i32 7, label %sw.bb7
  ]

return:                                           ; preds = %sw.bb7, %sw.bb6, %sw.bb5, %sw.bb4, %sw.bb3, %sw.bb2, %sw.bb1, %entry
  ret void

sw.bb1:                                           ; preds = %entry
  %src.gep.i8 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i8 = getelementptr i8, ptr %dst, i32 0
  %0 = load i8, ptr %src.gep.i8, align 1
  store i8 %0, ptr %dst.gep.i8, align 1
  br label %return

sw.bb2:                                           ; preds = %entry
  %src.gep.i16 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i16 = getelementptr i8, ptr %dst, i32 0
  %1 = load i16, ptr %src.gep.i16, align 2
  store i16 %1, ptr %dst.gep.i16, align 2
  br label %return

sw.bb3:                                           ; preds = %entry
  %src.gep.i161 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i162 = getelementptr i8, ptr %dst, i32 0
  %2 = load i16, ptr %src.gep.i161, align 2
  store i16 %2, ptr %dst.gep.i162, align 2
  %src.gep.i83 = getelementptr i8, ptr %src, i32 2
  %dst.gep.i84 = getelementptr i8, ptr %dst, i32 2
  %3 = load i8, ptr %src.gep.i83, align 1
  store i8 %3, ptr %dst.gep.i84, align 1
  br label %return

sw.bb4:                                           ; preds = %entry
  %src.gep.i32 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i32 = getelementptr i8, ptr %dst, i32 0
  %4 = load i32, ptr %src.gep.i32, align 4
  store i32 %4, ptr %dst.gep.i32, align 4
  br label %return

sw.bb5:                                           ; preds = %entry
  %src.gep.i325 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i326 = getelementptr i8, ptr %dst, i32 0
  %5 = load i32, ptr %src.gep.i325, align 4
  store i32 %5, ptr %dst.gep.i326, align 4
  %src.gep.i87 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i88 = getelementptr i8, ptr %dst, i32 4
  %6 = load i8, ptr %src.gep.i87, align 1
  store i8 %6, ptr %dst.gep.i88, align 1
  br label %return

sw.bb6:                                           ; preds = %entry
  %src.gep.i329 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i3210 = getelementptr i8, ptr %dst, i32 0
  %7 = load i32, ptr %src.gep.i329, align 4
  store i32 %7, ptr %dst.gep.i3210, align 4
  %src.gep.i1611 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1612 = getelementptr i8, ptr %dst, i32 4
  %8 = load i16, ptr %src.gep.i1611, align 2
  store i16 %8, ptr %dst.gep.i1612, align 2
  br label %return

sw.bb7:                                           ; preds = %entry
  %src.gep.i3213 = getelementptr i8, ptr %src, i32 0
  %dst.gep.i3214 = getelementptr i8, ptr %dst, i32 0
  %9 = load i32, ptr %src.gep.i3213, align 4
  store i32 %9, ptr %dst.gep.i3214, align 4
  %src.gep.i1615 = getelementptr i8, ptr %src, i32 4
  %dst.gep.i1616 = getelementptr i8, ptr %dst, i32 4
  %10 = load i16, ptr %src.gep.i1615, align 2
  store i16 %10, ptr %dst.gep.i1616, align 2
  %src.gep.i817 = getelementptr i8, ptr %src, i32 6
  %dst.gep.i818 = getelementptr i8, ptr %dst, i32 6
  %11 = load i8, ptr %src.gep.i817, align 1
  store i8 %11, ptr %dst.gep.i818, align 1
  br label %return
}
; CHECK-LABEL: define void @test_src16_dst16_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrc16Dst16Var(ptr [[A]], ptr [[B]], i32 [[SIZE]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @test_src16_dst8_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrc16Dst8Var(ptr [[A]], ptr [[B]], i32 [[SIZE]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @test_src8_dst16_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrc8Dst16Var(ptr [[A]], ptr [[B]], i32 [[SIZE]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @test_src8_dst8_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrc8Dst8Var(ptr [[A]], ptr [[B]], i32 [[SIZE]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @test_src16_dstunalign_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 [[SIZE]], i32 1)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @test_src8_dstunalign_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 [[SIZE]], i32 1)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @test_srcunalign_dst16_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP_I:%.*]] = icmp ult i32 [[SIZE]], 16
; CHECK-NEXT:    br i1 [[CMP_I]], label %[[FINAL_CLEANUP_I:.*]], label %[[PROCESS_MAIN_LOOP_I:.*]]
; CHECK:       [[PROCESS_MAIN_LOOP_I]]:
; CHECK-NEXT:    [[DIV_I:%.*]] = udiv i32 [[SIZE]], 48
; CHECK-NEXT:    [[DOTNEG:%.*]] = mul i32 [[DIV_I]], -48
; CHECK-NEXT:    [[REM_DECOMPOSED_I:%.*]] = add i32 [[DOTNEG]], [[SIZE]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip.m(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip.m(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    [[CMP21_NOT_I:%.*]] = icmp ult i32 [[SIZE]], 48
; CHECK-NEXT:    br i1 [[CMP21_NOT_I]], label %[[HANDLE_REMAINDER_I:.*]], label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[HANDLE_REMAINDER_I]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_MAIN_LOOP_I:%.*]] = phi ptr [ [[TMP43]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP45:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_MAIN_LOOP_I:%.*]] = phi ptr [ [[A]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[VST128IP_M5_I:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V0_AFTER_MAIN_LOOP_I:%.*]] = phi <16 x i8> [ [[TMP0]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP46:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V1_AFTER_MAIN_LOOP_I:%.*]] = phi <16 x i8> [ [[TMP42]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP47:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[TOBOOL_NOT_I:%.*]] = icmp ult i32 [[REM_DECOMPOSED_I]], 32
; CHECK-NEXT:    br i1 [[TOBOOL_NOT_I]], label %[[CHECK_16BYTE_TAIL_I:.*]], label %[[PROCESS_32BYTE_TAIL_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[I_022_I:%.*]] = phi i32 [ 0, %[[PROCESS_MAIN_LOOP_I]] ], [ [[INC_I:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[SRC_PTR_IN_LOOP_I:%.*]] = phi ptr [ [[TMP43]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP45]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[DST_PTR_IN_LOOP_I:%.*]] = phi ptr [ [[A]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[VST128IP_M5_I]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V0_I:%.*]] = phi <16 x i8> [ [[TMP0]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP46]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V1_I:%.*]] = phi <16 x i8> [ [[TMP42]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP47]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[SRCQLDIP_M_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP44]], <16 x i8> [[V1_I]], <16 x i8> [[V0_I]], ptr [[SRC_PTR_IN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M_I]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M_I]], 1
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP48]], ptr [[DST_PTR_IN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP_M2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP44]], <16 x i8> [[TMP49]], <16 x i8> [[V1_I]], ptr [[TMP50]], i32 16)
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M2_I]], 0
; CHECK-NEXT:    [[TMP46]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M2_I]], 1
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP51]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP_M4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP44]], <16 x i8> [[TMP46]], <16 x i8> [[TMP49]], ptr [[TMP52]], i32 16)
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M4_I]], 0
; CHECK-NEXT:    [[TMP47]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M4_I]], 1
; CHECK-NEXT:    [[TMP45]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M4_I]], 2
; CHECK-NEXT:    [[VST128IP_M5_I]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP53]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    [[INC_I]] = add nuw nsw i32 [[I_022_I]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i32 [[INC_I]], [[DIV_I]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I]], label %[[HANDLE_REMAINDER_I]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[PROCESS_32BYTE_TAIL_I]]:
; CHECK-NEXT:    [[SRCQLDIP_M6_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP44]], <16 x i8> [[V1_AFTER_MAIN_LOOP_I]], <16 x i8> [[V0_AFTER_MAIN_LOOP_I]], ptr [[SRC_PTR_AFTER_MAIN_LOOP_I]], i32 0)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M6_I]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M6_I]], 1
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M6_I]], 2
; CHECK-NEXT:    [[VST128IP_M7_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP54]], ptr [[DST_PTR_AFTER_MAIN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[SRCQ_M_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q.m(i32 [[TMP44]], <16 x i8> [[TMP55]], <16 x i8> [[V1_AFTER_MAIN_LOOP_I]])
; CHECK-NEXT:    [[VST128IP_M8_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[SRCQ_M_I]], ptr [[VST128IP_M7_I]], i32 16)
; CHECK-NEXT:    [[SUB1_I:%.*]] = add nsw i32 [[REM_DECOMPOSED_I]], -32
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[CHECK_16BYTE_TAIL_I]]:
; CHECK-NEXT:    [[TOBOOL5_NOT_I:%.*]] = icmp ult i32 [[REM_DECOMPOSED_I]], 16
; CHECK-NEXT:    br i1 [[TOBOOL5_NOT_I]], label %[[SKIP_TAIL_PROCESSING_I:.*]], label %[[PROCESS_16BYTE_TAIL_I:.*]]
; CHECK:       [[PROCESS_16BYTE_TAIL_I]]:
; CHECK-NEXT:    [[SRCQ_M9_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q.m(i32 [[TMP44]], <16 x i8> [[V1_AFTER_MAIN_LOOP_I]], <16 x i8> [[V0_AFTER_MAIN_LOOP_I]])
; CHECK-NEXT:    [[VST128IP_M10_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[SRCQ_M9_I]], ptr [[DST_PTR_AFTER_MAIN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[SRC_AFTER_16BYTE_PROCESSING_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_AFTER_MAIN_LOOP_I]], i32 -16
; CHECK-NEXT:    [[SUB9_I:%.*]] = add nsw i32 [[REM_DECOMPOSED_I]], -16
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[SKIP_TAIL_PROCESSING_I]]:
; CHECK-NEXT:    [[SRC_ADJUSTED_FOR_UNALIGNED_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_AFTER_MAIN_LOOP_I]], i32 -32
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[FINAL_CLEANUP_I]]:
; CHECK-NEXT:    [[SRC_PTR_FINAL_I:%.*]] = phi ptr [ [[TMP56]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[SRC_AFTER_16BYTE_PROCESSING_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[B]], %[[ENTRY]] ], [ [[SRC_ADJUSTED_FOR_UNALIGNED_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    [[DST_PTR_FINAL_I:%.*]] = phi ptr [ [[VST128IP_M8_I]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[VST128IP_M10_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[A]], %[[ENTRY]] ], [ [[DST_PTR_AFTER_MAIN_LOOP_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    [[REM_FINAL_I:%.*]] = phi i32 [ [[SUB1_I]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[SUB9_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[SIZE]], %[[ENTRY]] ], [ [[REM_DECOMPOSED_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    switch i32 [[REM_FINAL_I]], label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]] [
; CHECK-NEXT:      i32 15, label %[[SW_BB15_I:.*]]
; CHECK-NEXT:      i32 1, label %[[SW_BB1_I:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2_I:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3_I:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4_I:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5_I:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6_I:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7_I:.*]]
; CHECK-NEXT:      i32 8, label %[[SW_BB8_I:.*]]
; CHECK-NEXT:      i32 9, label %[[SW_BB9_I:.*]]
; CHECK-NEXT:      i32 10, label %[[SW_BB10_I:.*]]
; CHECK-NEXT:      i32 11, label %[[SW_BB11_I:.*]]
; CHECK-NEXT:      i32 12, label %[[SW_BB12_I:.*]]
; CHECK-NEXT:      i32 13, label %[[SW_BB13_I:.*]]
; CHECK-NEXT:      i32 14, label %[[SW_BB14_I:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB1_I]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[SRC_PTR_FINAL_I]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[DST_PTR_FINAL_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB2_I]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[SRC_PTR_FINAL_I]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[DST_PTR_FINAL_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB3_I]]:
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[SRC_PTR_FINAL_I]], align 2
; CHECK-NEXT:    store i16 [[TMP4]], ptr [[DST_PTR_FINAL_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 2
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[SRC_GEP_I83_I]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[DST_GEP_I84_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB4_I]]:
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP6]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB5_I]]:
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[SRC_GEP_I87_I]], align 1
; CHECK-NEXT:    store i8 [[TMP8]], ptr [[DST_GEP_I88_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB6_I]]:
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[SRC_GEP_I1611_I]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[DST_GEP_I1612_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB7_I]]:
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[SRC_GEP_I1615_I]], align 2
; CHECK-NEXT:    store i16 [[TMP12]], ptr [[DST_GEP_I1616_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 6
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[SRC_GEP_I817_I]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[DST_GEP_I818_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB8_I]]:
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP14]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3221_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3222_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[SRC_GEP_I3221_I]], align 4
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[DST_GEP_I3222_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB9_I]]:
; CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP16]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3225_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3226_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[SRC_GEP_I3225_I]], align 4
; CHECK-NEXT:    store i32 [[TMP17]], ptr [[DST_GEP_I3226_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I827_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I828_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP18:%.*]] = load i8, ptr [[SRC_GEP_I827_I]], align 1
; CHECK-NEXT:    store i8 [[TMP18]], ptr [[DST_GEP_I828_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB10_I]]:
; CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP19]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3231_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3232_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP20:%.*]] = load i32, ptr [[SRC_GEP_I3231_I]], align 4
; CHECK-NEXT:    store i32 [[TMP20]], ptr [[DST_GEP_I3232_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1633_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1634_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[SRC_GEP_I1633_I]], align 2
; CHECK-NEXT:    store i16 [[TMP21]], ptr [[DST_GEP_I1634_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB11_I]]:
; CHECK-NEXT:    [[TMP22:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP22]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3237_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3238_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP23:%.*]] = load i32, ptr [[SRC_GEP_I3237_I]], align 4
; CHECK-NEXT:    store i32 [[TMP23]], ptr [[DST_GEP_I3238_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1639_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1640_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP24:%.*]] = load i16, ptr [[SRC_GEP_I1639_I]], align 2
; CHECK-NEXT:    store i16 [[TMP24]], ptr [[DST_GEP_I1640_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I841_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 10
; CHECK-NEXT:    [[DST_GEP_I842_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 10
; CHECK-NEXT:    [[TMP25:%.*]] = load i8, ptr [[SRC_GEP_I841_I]], align 1
; CHECK-NEXT:    store i8 [[TMP25]], ptr [[DST_GEP_I842_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB12_I]]:
; CHECK-NEXT:    [[TMP26:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP26]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3245_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3246_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP27:%.*]] = load i32, ptr [[SRC_GEP_I3245_I]], align 4
; CHECK-NEXT:    store i32 [[TMP27]], ptr [[DST_GEP_I3246_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3247_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3248_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP28:%.*]] = load i32, ptr [[SRC_GEP_I3247_I]], align 4
; CHECK-NEXT:    store i32 [[TMP28]], ptr [[DST_GEP_I3248_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB13_I]]:
; CHECK-NEXT:    [[TMP29:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP29]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3251_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3252_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP30:%.*]] = load i32, ptr [[SRC_GEP_I3251_I]], align 4
; CHECK-NEXT:    store i32 [[TMP30]], ptr [[DST_GEP_I3252_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3253_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3254_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[SRC_GEP_I3253_I]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[DST_GEP_I3254_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I855_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I856_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP32:%.*]] = load i8, ptr [[SRC_GEP_I855_I]], align 1
; CHECK-NEXT:    store i8 [[TMP32]], ptr [[DST_GEP_I856_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB14_I]]:
; CHECK-NEXT:    [[TMP33:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP33]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3259_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3260_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP34:%.*]] = load i32, ptr [[SRC_GEP_I3259_I]], align 4
; CHECK-NEXT:    store i32 [[TMP34]], ptr [[DST_GEP_I3260_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3261_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3262_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP35:%.*]] = load i32, ptr [[SRC_GEP_I3261_I]], align 4
; CHECK-NEXT:    store i32 [[TMP35]], ptr [[DST_GEP_I3262_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1663_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1664_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP36:%.*]] = load i16, ptr [[SRC_GEP_I1663_I]], align 2
; CHECK-NEXT:    store i16 [[TMP36]], ptr [[DST_GEP_I1664_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB15_I]]:
; CHECK-NEXT:    [[TMP37:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP37]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3267_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3268_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP38:%.*]] = load i32, ptr [[SRC_GEP_I3267_I]], align 4
; CHECK-NEXT:    store i32 [[TMP38]], ptr [[DST_GEP_I3268_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3269_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3270_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP39:%.*]] = load i32, ptr [[SRC_GEP_I3269_I]], align 4
; CHECK-NEXT:    store i32 [[TMP39]], ptr [[DST_GEP_I3270_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1671_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1672_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP40:%.*]] = load i16, ptr [[SRC_GEP_I1671_I]], align 2
; CHECK-NEXT:    store i16 [[TMP40]], ptr [[DST_GEP_I1672_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I873_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 14
; CHECK-NEXT:    [[DST_GEP_I874_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 14
; CHECK-NEXT:    [[TMP41:%.*]] = load i8, ptr [[SRC_GEP_I873_I]], align 1
; CHECK-NEXT:    store i8 [[TMP41]], ptr [[DST_GEP_I874_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @test_srcunalign_dst8_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ult i32 [[SIZE]], 8
; CHECK-NEXT:    br i1 [[TMP0]], label %[[IF_THEN_I:.*]], label %[[IF_END_I:.*]]
; CHECK:       [[IF_THEN_I]]:
; CHECK-NEXT:    switch i32 [[SIZE]], label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT:.*]] [
; CHECK-NEXT:      i32 1, label %[[SW_BB1_I:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2_I:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3_I:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4_I:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5_I:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6_I:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7_I:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB1_I]]:
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    store i8 [[TMP1]], ptr [[A]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB2_I]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[A]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB3_I]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[A]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83_I:%.*]] = getelementptr i8, ptr [[B]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84_I:%.*]] = getelementptr i8, ptr [[A]], i32 2
; CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[SRC_GEP_I83_I]], align 1
; CHECK-NEXT:    store i8 [[TMP4]], ptr [[DST_GEP_I84_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB4_I]]:
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[A]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB5_I]]:
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP6]], ptr [[A]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87_I:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88_I:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[SRC_GEP_I87_I]], align 1
; CHECK-NEXT:    store i8 [[TMP7]], ptr [[DST_GEP_I88_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB6_I]]:
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP8]], ptr [[A]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611_I:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612_I:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP9:%.*]] = load i16, ptr [[SRC_GEP_I1611_I]], align 2
; CHECK-NEXT:    store i16 [[TMP9]], ptr [[DST_GEP_I1612_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB7_I]]:
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP10]], ptr [[A]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615_I:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616_I:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP11:%.*]] = load i16, ptr [[SRC_GEP_I1615_I]], align 2
; CHECK-NEXT:    store i16 [[TMP11]], ptr [[DST_GEP_I1616_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817_I:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818_I:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[SRC_GEP_I817_I]], align 1
; CHECK-NEXT:    store i8 [[TMP12]], ptr [[DST_GEP_I818_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[IF_END_I]]:
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[B]], align 1
; CHECK-NEXT:    store i32 [[TMP13]], ptr [[A]], align 1
; CHECK-NEXT:    [[SRC_4_I:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[DST_4_I:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP74:%.*]] = load i32, ptr [[SRC_4_I]], align 1
; CHECK-NEXT:    store i32 [[TMP74]], ptr [[DST_4_I]], align 1
; CHECK-NEXT:    [[TMP14:%.*]] = add i32 [[SIZE]], -8
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[CMP_I:%.*]] = icmp ult i32 [[TMP14]], 16
; CHECK-NEXT:    br i1 [[CMP_I]], label %[[FINAL_CLEANUP_I:.*]], label %[[PROCESS_MAIN_LOOP_I:.*]]
; CHECK:       [[PROCESS_MAIN_LOOP_I]]:
; CHECK-NEXT:    [[DIV_I:%.*]] = udiv i32 [[TMP14]], 48
; CHECK-NEXT:    [[DOTNEG:%.*]] = mul i32 [[DIV_I]], -48
; CHECK-NEXT:    [[REM_DECOMPOSED_I:%.*]] = add i32 [[DOTNEG]], [[TMP14]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip.m(ptr [[TMP16]], i32 16)
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip.m(ptr [[TMP60]], i32 16)
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    [[CMP21_NOT_I:%.*]] = icmp ult i32 [[TMP14]], 48
; CHECK-NEXT:    br i1 [[CMP21_NOT_I]], label %[[HANDLE_REMAINDER_I:.*]], label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[HANDLE_REMAINDER_I]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_MAIN_LOOP_I:%.*]] = phi ptr [ [[TMP17]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP62:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_MAIN_LOOP_I:%.*]] = phi ptr [ [[TMP15]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[VST128IP_M5_I:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V0_AFTER_MAIN_LOOP_I:%.*]] = phi <16 x i8> [ [[TMP59]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP63:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V1_AFTER_MAIN_LOOP_I:%.*]] = phi <16 x i8> [ [[TMP61]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP64:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[TOBOOL_NOT_I:%.*]] = icmp ult i32 [[REM_DECOMPOSED_I]], 32
; CHECK-NEXT:    br i1 [[TOBOOL_NOT_I]], label %[[CHECK_16BYTE_TAIL_I:.*]], label %[[PROCESS_32BYTE_TAIL_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[I_022_I:%.*]] = phi i32 [ 0, %[[PROCESS_MAIN_LOOP_I]] ], [ [[INC_I:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[SRC_PTR_IN_LOOP_I:%.*]] = phi ptr [ [[TMP17]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP62]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[DST_PTR_IN_LOOP_I:%.*]] = phi ptr [ [[TMP15]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[VST128IP_M5_I]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V0_I:%.*]] = phi <16 x i8> [ [[TMP59]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP63]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V1_I:%.*]] = phi <16 x i8> [ [[TMP61]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP64]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[SRCQLDIP_M_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP18]], <16 x i8> [[V1_I]], <16 x i8> [[V0_I]], ptr [[SRC_PTR_IN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M_I]], 0
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M_I]], 1
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP65]], ptr [[DST_PTR_IN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP_M2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP18]], <16 x i8> [[TMP66]], <16 x i8> [[V1_I]], ptr [[TMP67]], i32 16)
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M2_I]], 0
; CHECK-NEXT:    [[TMP63]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M2_I]], 1
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP68]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP_M4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP18]], <16 x i8> [[TMP63]], <16 x i8> [[TMP66]], ptr [[TMP69]], i32 16)
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M4_I]], 0
; CHECK-NEXT:    [[TMP64]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M4_I]], 1
; CHECK-NEXT:    [[TMP62]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M4_I]], 2
; CHECK-NEXT:    [[VST128IP_M5_I]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP70]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    [[INC_I]] = add nuw nsw i32 [[I_022_I]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i32 [[INC_I]], [[DIV_I]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I]], label %[[HANDLE_REMAINDER_I]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[PROCESS_32BYTE_TAIL_I]]:
; CHECK-NEXT:    [[SRCQLDIP_M6_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP18]], <16 x i8> [[V1_AFTER_MAIN_LOOP_I]], <16 x i8> [[V0_AFTER_MAIN_LOOP_I]], ptr [[SRC_PTR_AFTER_MAIN_LOOP_I]], i32 0)
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M6_I]], 0
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M6_I]], 1
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M6_I]], 2
; CHECK-NEXT:    [[VST128IP_M7_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP71]], ptr [[DST_PTR_AFTER_MAIN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[SRCQ_M_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q.m(i32 [[TMP18]], <16 x i8> [[TMP72]], <16 x i8> [[V1_AFTER_MAIN_LOOP_I]])
; CHECK-NEXT:    [[VST128IP_M8_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[SRCQ_M_I]], ptr [[VST128IP_M7_I]], i32 16)
; CHECK-NEXT:    [[SUB1_I:%.*]] = add nsw i32 [[REM_DECOMPOSED_I]], -32
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[CHECK_16BYTE_TAIL_I]]:
; CHECK-NEXT:    [[TOBOOL5_NOT_I:%.*]] = icmp ult i32 [[REM_DECOMPOSED_I]], 16
; CHECK-NEXT:    br i1 [[TOBOOL5_NOT_I]], label %[[SKIP_TAIL_PROCESSING_I:.*]], label %[[PROCESS_16BYTE_TAIL_I:.*]]
; CHECK:       [[PROCESS_16BYTE_TAIL_I]]:
; CHECK-NEXT:    [[SRCQ_M9_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q.m(i32 [[TMP18]], <16 x i8> [[V1_AFTER_MAIN_LOOP_I]], <16 x i8> [[V0_AFTER_MAIN_LOOP_I]])
; CHECK-NEXT:    [[VST128IP_M10_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[SRCQ_M9_I]], ptr [[DST_PTR_AFTER_MAIN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[SRC_AFTER_16BYTE_PROCESSING_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_AFTER_MAIN_LOOP_I]], i32 -16
; CHECK-NEXT:    [[SUB9_I:%.*]] = add nsw i32 [[REM_DECOMPOSED_I]], -16
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[SKIP_TAIL_PROCESSING_I]]:
; CHECK-NEXT:    [[SRC_ADJUSTED_FOR_UNALIGNED_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_AFTER_MAIN_LOOP_I]], i32 -32
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[FINAL_CLEANUP_I]]:
; CHECK-NEXT:    [[SRC_PTR_FINAL_I:%.*]] = phi ptr [ [[TMP73]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[SRC_AFTER_16BYTE_PROCESSING_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[TMP16]], %[[IF_END_I]] ], [ [[SRC_ADJUSTED_FOR_UNALIGNED_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    [[DST_PTR_FINAL_I:%.*]] = phi ptr [ [[VST128IP_M8_I]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[VST128IP_M10_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[TMP15]], %[[IF_END_I]] ], [ [[DST_PTR_AFTER_MAIN_LOOP_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    [[REM_FINAL_I:%.*]] = phi i32 [ [[SUB1_I]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[SUB9_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[TMP14]], %[[IF_END_I]] ], [ [[REM_DECOMPOSED_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    switch i32 [[REM_FINAL_I]], label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]] [
; CHECK-NEXT:      i32 15, label %[[SW_BB15_I:.*]]
; CHECK-NEXT:      i32 1, label %[[SW_BB1_I17:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2_I16:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3_I13:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4_I12:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5_I9:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6_I6:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7_I1:.*]]
; CHECK-NEXT:      i32 8, label %[[SW_BB8_I:.*]]
; CHECK-NEXT:      i32 9, label %[[SW_BB9_I:.*]]
; CHECK-NEXT:      i32 10, label %[[SW_BB10_I:.*]]
; CHECK-NEXT:      i32 11, label %[[SW_BB11_I:.*]]
; CHECK-NEXT:      i32 12, label %[[SW_BB12_I:.*]]
; CHECK-NEXT:      i32 13, label %[[SW_BB13_I:.*]]
; CHECK-NEXT:      i32 14, label %[[SW_BB14_I:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB1_I17]]:
; CHECK-NEXT:    [[TMP19:%.*]] = load i8, ptr [[SRC_PTR_FINAL_I]], align 1
; CHECK-NEXT:    store i8 [[TMP19]], ptr [[DST_PTR_FINAL_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB2_I16]]:
; CHECK-NEXT:    [[TMP20:%.*]] = load i16, ptr [[SRC_PTR_FINAL_I]], align 2
; CHECK-NEXT:    store i16 [[TMP20]], ptr [[DST_PTR_FINAL_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB3_I13]]:
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[SRC_PTR_FINAL_I]], align 2
; CHECK-NEXT:    store i16 [[TMP21]], ptr [[DST_PTR_FINAL_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83_I15:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84_I16:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 2
; CHECK-NEXT:    [[TMP22:%.*]] = load i8, ptr [[SRC_GEP_I83_I15]], align 1
; CHECK-NEXT:    store i8 [[TMP22]], ptr [[DST_GEP_I84_I16]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB4_I12]]:
; CHECK-NEXT:    [[TMP23:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP23]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB5_I9]]:
; CHECK-NEXT:    [[TMP24:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP24]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87_I11:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88_I12:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP25:%.*]] = load i8, ptr [[SRC_GEP_I87_I11]], align 1
; CHECK-NEXT:    store i8 [[TMP25]], ptr [[DST_GEP_I88_I12]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB6_I6]]:
; CHECK-NEXT:    [[TMP26:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP26]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611_I8:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612_I9:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP27:%.*]] = load i16, ptr [[SRC_GEP_I1611_I8]], align 2
; CHECK-NEXT:    store i16 [[TMP27]], ptr [[DST_GEP_I1612_I9]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB7_I1]]:
; CHECK-NEXT:    [[TMP28:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP28]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615_I3:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616_I4:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP29:%.*]] = load i16, ptr [[SRC_GEP_I1615_I3]], align 2
; CHECK-NEXT:    store i16 [[TMP29]], ptr [[DST_GEP_I1616_I4]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817_I5:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818_I6:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 6
; CHECK-NEXT:    [[TMP30:%.*]] = load i8, ptr [[SRC_GEP_I817_I5]], align 1
; CHECK-NEXT:    store i8 [[TMP30]], ptr [[DST_GEP_I818_I6]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB8_I]]:
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3221_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3222_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP32:%.*]] = load i32, ptr [[SRC_GEP_I3221_I]], align 4
; CHECK-NEXT:    store i32 [[TMP32]], ptr [[DST_GEP_I3222_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB9_I]]:
; CHECK-NEXT:    [[TMP33:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP33]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3225_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3226_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP34:%.*]] = load i32, ptr [[SRC_GEP_I3225_I]], align 4
; CHECK-NEXT:    store i32 [[TMP34]], ptr [[DST_GEP_I3226_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I827_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I828_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP35:%.*]] = load i8, ptr [[SRC_GEP_I827_I]], align 1
; CHECK-NEXT:    store i8 [[TMP35]], ptr [[DST_GEP_I828_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB10_I]]:
; CHECK-NEXT:    [[TMP36:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP36]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3231_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3232_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP37:%.*]] = load i32, ptr [[SRC_GEP_I3231_I]], align 4
; CHECK-NEXT:    store i32 [[TMP37]], ptr [[DST_GEP_I3232_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1633_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1634_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP38:%.*]] = load i16, ptr [[SRC_GEP_I1633_I]], align 2
; CHECK-NEXT:    store i16 [[TMP38]], ptr [[DST_GEP_I1634_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB11_I]]:
; CHECK-NEXT:    [[TMP39:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP39]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3237_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3238_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP40:%.*]] = load i32, ptr [[SRC_GEP_I3237_I]], align 4
; CHECK-NEXT:    store i32 [[TMP40]], ptr [[DST_GEP_I3238_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1639_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1640_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP41:%.*]] = load i16, ptr [[SRC_GEP_I1639_I]], align 2
; CHECK-NEXT:    store i16 [[TMP41]], ptr [[DST_GEP_I1640_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I841_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 10
; CHECK-NEXT:    [[DST_GEP_I842_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 10
; CHECK-NEXT:    [[TMP42:%.*]] = load i8, ptr [[SRC_GEP_I841_I]], align 1
; CHECK-NEXT:    store i8 [[TMP42]], ptr [[DST_GEP_I842_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB12_I]]:
; CHECK-NEXT:    [[TMP43:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP43]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3245_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3246_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP44:%.*]] = load i32, ptr [[SRC_GEP_I3245_I]], align 4
; CHECK-NEXT:    store i32 [[TMP44]], ptr [[DST_GEP_I3246_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3247_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3248_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP45:%.*]] = load i32, ptr [[SRC_GEP_I3247_I]], align 4
; CHECK-NEXT:    store i32 [[TMP45]], ptr [[DST_GEP_I3248_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB13_I]]:
; CHECK-NEXT:    [[TMP46:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP46]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3251_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3252_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP47:%.*]] = load i32, ptr [[SRC_GEP_I3251_I]], align 4
; CHECK-NEXT:    store i32 [[TMP47]], ptr [[DST_GEP_I3252_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3253_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3254_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP48:%.*]] = load i32, ptr [[SRC_GEP_I3253_I]], align 4
; CHECK-NEXT:    store i32 [[TMP48]], ptr [[DST_GEP_I3254_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I855_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I856_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP49:%.*]] = load i8, ptr [[SRC_GEP_I855_I]], align 1
; CHECK-NEXT:    store i8 [[TMP49]], ptr [[DST_GEP_I856_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB14_I]]:
; CHECK-NEXT:    [[TMP50:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP50]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3259_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3260_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP51:%.*]] = load i32, ptr [[SRC_GEP_I3259_I]], align 4
; CHECK-NEXT:    store i32 [[TMP51]], ptr [[DST_GEP_I3260_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3261_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3262_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP52:%.*]] = load i32, ptr [[SRC_GEP_I3261_I]], align 4
; CHECK-NEXT:    store i32 [[TMP52]], ptr [[DST_GEP_I3262_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1663_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1664_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP53:%.*]] = load i16, ptr [[SRC_GEP_I1663_I]], align 2
; CHECK-NEXT:    store i16 [[TMP53]], ptr [[DST_GEP_I1664_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[SW_BB15_I]]:
; CHECK-NEXT:    [[TMP54:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP54]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3267_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3268_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP55:%.*]] = load i32, ptr [[SRC_GEP_I3267_I]], align 4
; CHECK-NEXT:    store i32 [[TMP55]], ptr [[DST_GEP_I3268_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3269_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3270_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP56:%.*]] = load i32, ptr [[SRC_GEP_I3269_I]], align 4
; CHECK-NEXT:    store i32 [[TMP56]], ptr [[DST_GEP_I3270_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1671_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1672_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP57:%.*]] = load i16, ptr [[SRC_GEP_I1671_I]], align 2
; CHECK-NEXT:    store i16 [[TMP57]], ptr [[DST_GEP_I1672_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I873_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 14
; CHECK-NEXT:    [[DST_GEP_I874_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 14
; CHECK-NEXT:    [[TMP58:%.*]] = load i8, ptr [[SRC_GEP_I873_I]], align 1
; CHECK-NEXT:    store i8 [[TMP58]], ptr [[DST_GEP_I874_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNDST8VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP_I:%.*]] = icmp ult i32 [[SIZE]], 16
; CHECK-NEXT:    br i1 [[CMP_I]], label %[[FINAL_CLEANUP_I:.*]], label %[[PROCESS_MAIN_LOOP_I:.*]]
; CHECK:       [[PROCESS_MAIN_LOOP_I]]:
; CHECK-NEXT:    [[DIV_I:%.*]] = udiv i32 [[SIZE]], 48
; CHECK-NEXT:    [[DOTNEG:%.*]] = mul i32 [[DIV_I]], -48
; CHECK-NEXT:    [[REM_DECOMPOSED_I:%.*]] = add i32 [[DOTNEG]], [[SIZE]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip.m(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip.m(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    [[CMP21_NOT_I:%.*]] = icmp ult i32 [[SIZE]], 48
; CHECK-NEXT:    br i1 [[CMP21_NOT_I]], label %[[HANDLE_REMAINDER_I:.*]], label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[HANDLE_REMAINDER_I]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_MAIN_LOOP_I:%.*]] = phi ptr [ [[TMP43]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP45:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_MAIN_LOOP_I:%.*]] = phi ptr [ [[A]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[VST128IP_M5_I:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V0_AFTER_MAIN_LOOP_I:%.*]] = phi <16 x i8> [ [[TMP0]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP46:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V1_AFTER_MAIN_LOOP_I:%.*]] = phi <16 x i8> [ [[TMP42]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP47:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[TOBOOL_NOT_I:%.*]] = icmp ult i32 [[REM_DECOMPOSED_I]], 32
; CHECK-NEXT:    br i1 [[TOBOOL_NOT_I]], label %[[CHECK_16BYTE_TAIL_I:.*]], label %[[PROCESS_32BYTE_TAIL_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[I_022_I:%.*]] = phi i32 [ 0, %[[PROCESS_MAIN_LOOP_I]] ], [ [[INC_I:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[SRC_PTR_IN_LOOP_I:%.*]] = phi ptr [ [[TMP43]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP45]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[DST_PTR_IN_LOOP_I:%.*]] = phi ptr [ [[A]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[VST128IP_M5_I]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V0_I:%.*]] = phi <16 x i8> [ [[TMP0]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP46]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[V1_I:%.*]] = phi <16 x i8> [ [[TMP42]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[TMP47]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[SRCQLDIP_M_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP44]], <16 x i8> [[V1_I]], <16 x i8> [[V0_I]], ptr [[SRC_PTR_IN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M_I]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M_I]], 1
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP48]], ptr [[DST_PTR_IN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP_M2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP44]], <16 x i8> [[TMP49]], <16 x i8> [[V1_I]], ptr [[TMP50]], i32 16)
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M2_I]], 0
; CHECK-NEXT:    [[TMP46]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M2_I]], 1
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP51]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP_M4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP44]], <16 x i8> [[TMP46]], <16 x i8> [[TMP49]], ptr [[TMP52]], i32 16)
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M4_I]], 0
; CHECK-NEXT:    [[TMP47]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M4_I]], 1
; CHECK-NEXT:    [[TMP45]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M4_I]], 2
; CHECK-NEXT:    [[VST128IP_M5_I]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP53]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    [[INC_I]] = add nuw nsw i32 [[I_022_I]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i32 [[INC_I]], [[DIV_I]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I]], label %[[HANDLE_REMAINDER_I]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[PROCESS_32BYTE_TAIL_I]]:
; CHECK-NEXT:    [[SRCQLDIP_M6_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip.m(i32 [[TMP44]], <16 x i8> [[V1_AFTER_MAIN_LOOP_I]], <16 x i8> [[V0_AFTER_MAIN_LOOP_I]], ptr [[SRC_PTR_AFTER_MAIN_LOOP_I]], i32 0)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M6_I]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M6_I]], 1
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_M6_I]], 2
; CHECK-NEXT:    [[VST128IP_M7_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP54]], ptr [[DST_PTR_AFTER_MAIN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[SRCQ_M_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q.m(i32 [[TMP44]], <16 x i8> [[TMP55]], <16 x i8> [[V1_AFTER_MAIN_LOOP_I]])
; CHECK-NEXT:    [[VST128IP_M8_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[SRCQ_M_I]], ptr [[VST128IP_M7_I]], i32 16)
; CHECK-NEXT:    [[SUB1_I:%.*]] = add nsw i32 [[REM_DECOMPOSED_I]], -32
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[CHECK_16BYTE_TAIL_I]]:
; CHECK-NEXT:    [[TOBOOL5_NOT_I:%.*]] = icmp ult i32 [[REM_DECOMPOSED_I]], 16
; CHECK-NEXT:    br i1 [[TOBOOL5_NOT_I]], label %[[SKIP_TAIL_PROCESSING_I:.*]], label %[[PROCESS_16BYTE_TAIL_I:.*]]
; CHECK:       [[PROCESS_16BYTE_TAIL_I]]:
; CHECK-NEXT:    [[SRCQ_M9_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q.m(i32 [[TMP44]], <16 x i8> [[V1_AFTER_MAIN_LOOP_I]], <16 x i8> [[V0_AFTER_MAIN_LOOP_I]])
; CHECK-NEXT:    [[VST128IP_M10_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[SRCQ_M9_I]], ptr [[DST_PTR_AFTER_MAIN_LOOP_I]], i32 16)
; CHECK-NEXT:    [[SRC_AFTER_16BYTE_PROCESSING_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_AFTER_MAIN_LOOP_I]], i32 -16
; CHECK-NEXT:    [[SUB9_I:%.*]] = add nsw i32 [[REM_DECOMPOSED_I]], -16
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[SKIP_TAIL_PROCESSING_I]]:
; CHECK-NEXT:    [[SRC_ADJUSTED_FOR_UNALIGNED_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_AFTER_MAIN_LOOP_I]], i32 -32
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[FINAL_CLEANUP_I]]:
; CHECK-NEXT:    [[SRC_PTR_FINAL_I:%.*]] = phi ptr [ [[TMP56]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[SRC_AFTER_16BYTE_PROCESSING_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[B]], %[[ENTRY]] ], [ [[SRC_ADJUSTED_FOR_UNALIGNED_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    [[DST_PTR_FINAL_I:%.*]] = phi ptr [ [[VST128IP_M8_I]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[VST128IP_M10_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[A]], %[[ENTRY]] ], [ [[DST_PTR_AFTER_MAIN_LOOP_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    [[REM_FINAL_I:%.*]] = phi i32 [ [[SUB1_I]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[SUB9_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[SIZE]], %[[ENTRY]] ], [ [[REM_DECOMPOSED_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    switch i32 [[REM_FINAL_I]], label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]] [
; CHECK-NEXT:      i32 15, label %[[SW_BB15_I:.*]]
; CHECK-NEXT:      i32 1, label %[[SW_BB1_I:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2_I:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3_I:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4_I:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5_I:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6_I:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7_I:.*]]
; CHECK-NEXT:      i32 8, label %[[SW_BB8_I:.*]]
; CHECK-NEXT:      i32 9, label %[[SW_BB9_I:.*]]
; CHECK-NEXT:      i32 10, label %[[SW_BB10_I:.*]]
; CHECK-NEXT:      i32 11, label %[[SW_BB11_I:.*]]
; CHECK-NEXT:      i32 12, label %[[SW_BB12_I:.*]]
; CHECK-NEXT:      i32 13, label %[[SW_BB13_I:.*]]
; CHECK-NEXT:      i32 14, label %[[SW_BB14_I:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB1_I]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[SRC_PTR_FINAL_I]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[DST_PTR_FINAL_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB2_I]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[SRC_PTR_FINAL_I]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[DST_PTR_FINAL_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB3_I]]:
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[SRC_PTR_FINAL_I]], align 2
; CHECK-NEXT:    store i16 [[TMP4]], ptr [[DST_PTR_FINAL_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 2
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[SRC_GEP_I83_I]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[DST_GEP_I84_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB4_I]]:
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP6]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB5_I]]:
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[SRC_GEP_I87_I]], align 1
; CHECK-NEXT:    store i8 [[TMP8]], ptr [[DST_GEP_I88_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB6_I]]:
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[SRC_GEP_I1611_I]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[DST_GEP_I1612_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB7_I]]:
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[SRC_GEP_I1615_I]], align 2
; CHECK-NEXT:    store i16 [[TMP12]], ptr [[DST_GEP_I1616_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 6
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[SRC_GEP_I817_I]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[DST_GEP_I818_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB8_I]]:
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP14]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3221_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3222_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[SRC_GEP_I3221_I]], align 4
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[DST_GEP_I3222_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB9_I]]:
; CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP16]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3225_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3226_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[SRC_GEP_I3225_I]], align 4
; CHECK-NEXT:    store i32 [[TMP17]], ptr [[DST_GEP_I3226_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I827_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I828_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP18:%.*]] = load i8, ptr [[SRC_GEP_I827_I]], align 1
; CHECK-NEXT:    store i8 [[TMP18]], ptr [[DST_GEP_I828_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB10_I]]:
; CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP19]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3231_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3232_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP20:%.*]] = load i32, ptr [[SRC_GEP_I3231_I]], align 4
; CHECK-NEXT:    store i32 [[TMP20]], ptr [[DST_GEP_I3232_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1633_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1634_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[SRC_GEP_I1633_I]], align 2
; CHECK-NEXT:    store i16 [[TMP21]], ptr [[DST_GEP_I1634_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB11_I]]:
; CHECK-NEXT:    [[TMP22:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP22]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3237_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3238_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP23:%.*]] = load i32, ptr [[SRC_GEP_I3237_I]], align 4
; CHECK-NEXT:    store i32 [[TMP23]], ptr [[DST_GEP_I3238_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1639_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1640_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP24:%.*]] = load i16, ptr [[SRC_GEP_I1639_I]], align 2
; CHECK-NEXT:    store i16 [[TMP24]], ptr [[DST_GEP_I1640_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I841_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 10
; CHECK-NEXT:    [[DST_GEP_I842_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 10
; CHECK-NEXT:    [[TMP25:%.*]] = load i8, ptr [[SRC_GEP_I841_I]], align 1
; CHECK-NEXT:    store i8 [[TMP25]], ptr [[DST_GEP_I842_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB12_I]]:
; CHECK-NEXT:    [[TMP26:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP26]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3245_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3246_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP27:%.*]] = load i32, ptr [[SRC_GEP_I3245_I]], align 4
; CHECK-NEXT:    store i32 [[TMP27]], ptr [[DST_GEP_I3246_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3247_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3248_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP28:%.*]] = load i32, ptr [[SRC_GEP_I3247_I]], align 4
; CHECK-NEXT:    store i32 [[TMP28]], ptr [[DST_GEP_I3248_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB13_I]]:
; CHECK-NEXT:    [[TMP29:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP29]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3251_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3252_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP30:%.*]] = load i32, ptr [[SRC_GEP_I3251_I]], align 4
; CHECK-NEXT:    store i32 [[TMP30]], ptr [[DST_GEP_I3252_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3253_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3254_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[SRC_GEP_I3253_I]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[DST_GEP_I3254_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I855_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I856_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP32:%.*]] = load i8, ptr [[SRC_GEP_I855_I]], align 1
; CHECK-NEXT:    store i8 [[TMP32]], ptr [[DST_GEP_I856_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB14_I]]:
; CHECK-NEXT:    [[TMP33:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP33]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3259_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3260_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP34:%.*]] = load i32, ptr [[SRC_GEP_I3259_I]], align 4
; CHECK-NEXT:    store i32 [[TMP34]], ptr [[DST_GEP_I3260_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3261_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3262_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP35:%.*]] = load i32, ptr [[SRC_GEP_I3261_I]], align 4
; CHECK-NEXT:    store i32 [[TMP35]], ptr [[DST_GEP_I3262_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1663_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1664_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP36:%.*]] = load i16, ptr [[SRC_GEP_I1663_I]], align 2
; CHECK-NEXT:    store i16 [[TMP36]], ptr [[DST_GEP_I1664_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[SW_BB15_I]]:
; CHECK-NEXT:    [[TMP37:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP37]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3267_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3268_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP38:%.*]] = load i32, ptr [[SRC_GEP_I3267_I]], align 4
; CHECK-NEXT:    store i32 [[TMP38]], ptr [[DST_GEP_I3268_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3269_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3270_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP39:%.*]] = load i32, ptr [[SRC_GEP_I3269_I]], align 4
; CHECK-NEXT:    store i32 [[TMP39]], ptr [[DST_GEP_I3270_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1671_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1672_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP40:%.*]] = load i16, ptr [[SRC_GEP_I1671_I]], align 2
; CHECK-NEXT:    store i16 [[TMP40]], ptr [[DST_GEP_I1672_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I873_I:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 14
; CHECK-NEXT:    [[DST_GEP_I874_I:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 14
; CHECK-NEXT:    [[TMP41:%.*]] = load i8, ptr [[SRC_GEP_I873_I]], align 1
; CHECK-NEXT:    store i8 [[TMP41]], ptr [[DST_GEP_I874_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @esp32p4MemCpySrc16Dst16From1To7Opt(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    switch i32 [[SIZE]], label %[[RETURN:.*]] [
; CHECK-NEXT:      i32 1, label %[[SW_BB1:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[SW_BB1]]:
; CHECK-NEXT:    [[SRC_GEP_I8:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I8:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[SRC_GEP_I8]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[DST_GEP_I8]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB2]]:
; CHECK-NEXT:    [[SRC_GEP_I16:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I16:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[SRC_GEP_I16]], align 2
; CHECK-NEXT:    store i16 [[TMP1]], ptr [[DST_GEP_I16]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB3]]:
; CHECK-NEXT:    [[SRC_GEP_I161:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I162:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[SRC_GEP_I161]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[DST_GEP_I162]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83:%.*]] = getelementptr i8, ptr [[SRC]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84:%.*]] = getelementptr i8, ptr [[DST]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[SRC_GEP_I83]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[DST_GEP_I84]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB4]]:
; CHECK-NEXT:    [[SRC_GEP_I32:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I32:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[SRC_GEP_I32]], align 4
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[DST_GEP_I32]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB5]]:
; CHECK-NEXT:    [[SRC_GEP_I325:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I326:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[SRC_GEP_I325]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[DST_GEP_I326]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[SRC_GEP_I87]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[DST_GEP_I88]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB6]]:
; CHECK-NEXT:    [[SRC_GEP_I329:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I3210:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[SRC_GEP_I329]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[DST_GEP_I3210]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[SRC_GEP_I1611]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[DST_GEP_I1612]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB7]]:
; CHECK-NEXT:    [[SRC_GEP_I3213:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I3214:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[SRC_GEP_I3213]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[DST_GEP_I3214]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[SRC_GEP_I1615]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[DST_GEP_I1616]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817:%.*]] = getelementptr i8, ptr [[SRC]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818:%.*]] = getelementptr i8, ptr [[DST]], i32 6
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[SRC_GEP_I817]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[DST_GEP_I818]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
;
;
; CHECK-LABEL: define internal void @esp32p4MemCpySrc16Dst8From1To7Opt(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    switch i32 [[SIZE]], label %[[RETURN:.*]] [
; CHECK-NEXT:      i32 1, label %[[SW_BB1:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[SW_BB1]]:
; CHECK-NEXT:    [[SRC_GEP_I8:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I8:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[SRC_GEP_I8]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[DST_GEP_I8]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB2]]:
; CHECK-NEXT:    [[SRC_GEP_I16:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I16:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[SRC_GEP_I16]], align 2
; CHECK-NEXT:    store i16 [[TMP1]], ptr [[DST_GEP_I16]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB3]]:
; CHECK-NEXT:    [[SRC_GEP_I161:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I162:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[SRC_GEP_I161]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[DST_GEP_I162]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83:%.*]] = getelementptr i8, ptr [[SRC]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84:%.*]] = getelementptr i8, ptr [[DST]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[SRC_GEP_I83]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[DST_GEP_I84]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB4]]:
; CHECK-NEXT:    [[SRC_GEP_I32:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I32:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[SRC_GEP_I32]], align 4
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[DST_GEP_I32]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB5]]:
; CHECK-NEXT:    [[SRC_GEP_I325:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I326:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[SRC_GEP_I325]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[DST_GEP_I326]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[SRC_GEP_I87]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[DST_GEP_I88]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB6]]:
; CHECK-NEXT:    [[SRC_GEP_I329:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I3210:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[SRC_GEP_I329]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[DST_GEP_I3210]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[SRC_GEP_I1611]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[DST_GEP_I1612]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB7]]:
; CHECK-NEXT:    [[SRC_GEP_I3213:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I3214:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[SRC_GEP_I3213]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[DST_GEP_I3214]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[SRC_GEP_I1615]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[DST_GEP_I1616]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817:%.*]] = getelementptr i8, ptr [[SRC]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818:%.*]] = getelementptr i8, ptr [[DST]], i32 6
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[SRC_GEP_I817]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[DST_GEP_I818]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
;
;
; CHECK-LABEL: define internal void @esp32p4MemCpySrc16DstunalignVar(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]], i32 [[DST_ALIGN:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SUB:%.*]] = sub i32 16, [[DST_ALIGN]]
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp ult i32 [[SUB]], [[SIZE]]
; CHECK-NEXT:    br i1 [[CMP_NOT]], label %[[HANDLE_TAIL:.*]], label %[[HANDLE_HEAD:.*]]
; CHECK:       [[HANDLE_HEAD]]:
; CHECK-NEXT:    switch i32 [[SIZE]], label %[[RETURN:.*]] [
; CHECK-NEXT:      i32 1, label %[[SW_BB1_I65:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2_I64:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3_I61:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4_I60:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5_I57:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6_I54:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7_I49:.*]]
; CHECK-NEXT:      i32 8, label %[[SW_BB8_I46:.*]]
; CHECK-NEXT:      i32 9, label %[[SW_BB9_I41:.*]]
; CHECK-NEXT:      i32 10, label %[[SW_BB10_I36:.*]]
; CHECK-NEXT:      i32 11, label %[[SW_BB11_I29:.*]]
; CHECK-NEXT:      i32 12, label %[[SW_BB12_I24:.*]]
; CHECK-NEXT:      i32 13, label %[[SW_BB13_I17:.*]]
; CHECK-NEXT:      i32 14, label %[[SW_BB14_I10:.*]]
; CHECK-NEXT:      i32 15, label %[[SW_BB15_I1:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB1_I65]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[SRC]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[DST]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB2_I64]]:
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[SRC]], align 2
; CHECK-NEXT:    store i16 [[TMP1]], ptr [[DST]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB3_I61]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[SRC]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[DST]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83_I62:%.*]] = getelementptr i8, ptr [[SRC]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84_I63:%.*]] = getelementptr i8, ptr [[DST]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[SRC_GEP_I83_I62]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[DST_GEP_I84_I63]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB4_I60]]:
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[DST]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB5_I57]]:
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87_I58:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88_I59:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[SRC_GEP_I87_I58]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[DST_GEP_I88_I59]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB6_I54]]:
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611_I55:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612_I56:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[SRC_GEP_I1611_I55]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[DST_GEP_I1612_I56]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB7_I49]]:
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615_I50:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616_I51:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[SRC_GEP_I1615_I50]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[DST_GEP_I1616_I51]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817_I52:%.*]] = getelementptr i8, ptr [[SRC]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818_I53:%.*]] = getelementptr i8, ptr [[DST]], i32 6
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[SRC_GEP_I817_I52]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[DST_GEP_I818_I53]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB8_I46]]:
; CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP12]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3221_I47:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3222_I48:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[SRC_GEP_I3221_I47]], align 4
; CHECK-NEXT:    store i32 [[TMP13]], ptr [[DST_GEP_I3222_I48]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB9_I41]]:
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP14]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3225_I42:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3226_I43:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[SRC_GEP_I3225_I42]], align 4
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[DST_GEP_I3226_I43]], align 4
; CHECK-NEXT:    [[SRC_GEP_I827_I44:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I828_I45:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[SRC_GEP_I827_I44]], align 1
; CHECK-NEXT:    store i8 [[TMP16]], ptr [[DST_GEP_I828_I45]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB10_I36]]:
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP17]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3231_I37:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3232_I38:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP18:%.*]] = load i32, ptr [[SRC_GEP_I3231_I37]], align 4
; CHECK-NEXT:    store i32 [[TMP18]], ptr [[DST_GEP_I3232_I38]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1633_I39:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1634_I40:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[SRC_GEP_I1633_I39]], align 2
; CHECK-NEXT:    store i16 [[TMP19]], ptr [[DST_GEP_I1634_I40]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB11_I29]]:
; CHECK-NEXT:    [[TMP20:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP20]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3237_I30:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3238_I31:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP21:%.*]] = load i32, ptr [[SRC_GEP_I3237_I30]], align 4
; CHECK-NEXT:    store i32 [[TMP21]], ptr [[DST_GEP_I3238_I31]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1639_I32:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1640_I33:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP22:%.*]] = load i16, ptr [[SRC_GEP_I1639_I32]], align 2
; CHECK-NEXT:    store i16 [[TMP22]], ptr [[DST_GEP_I1640_I33]], align 2
; CHECK-NEXT:    [[SRC_GEP_I841_I34:%.*]] = getelementptr i8, ptr [[SRC]], i32 10
; CHECK-NEXT:    [[DST_GEP_I842_I35:%.*]] = getelementptr i8, ptr [[DST]], i32 10
; CHECK-NEXT:    [[TMP23:%.*]] = load i8, ptr [[SRC_GEP_I841_I34]], align 1
; CHECK-NEXT:    store i8 [[TMP23]], ptr [[DST_GEP_I842_I35]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB12_I24]]:
; CHECK-NEXT:    [[TMP24:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP24]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3245_I25:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3246_I26:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP25:%.*]] = load i32, ptr [[SRC_GEP_I3245_I25]], align 4
; CHECK-NEXT:    store i32 [[TMP25]], ptr [[DST_GEP_I3246_I26]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3247_I27:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3248_I28:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP26:%.*]] = load i32, ptr [[SRC_GEP_I3247_I27]], align 4
; CHECK-NEXT:    store i32 [[TMP26]], ptr [[DST_GEP_I3248_I28]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB13_I17]]:
; CHECK-NEXT:    [[TMP27:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP27]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3251_I18:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3252_I19:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP28:%.*]] = load i32, ptr [[SRC_GEP_I3251_I18]], align 4
; CHECK-NEXT:    store i32 [[TMP28]], ptr [[DST_GEP_I3252_I19]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3253_I20:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3254_I21:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP29:%.*]] = load i32, ptr [[SRC_GEP_I3253_I20]], align 4
; CHECK-NEXT:    store i32 [[TMP29]], ptr [[DST_GEP_I3254_I21]], align 4
; CHECK-NEXT:    [[SRC_GEP_I855_I22:%.*]] = getelementptr i8, ptr [[SRC]], i32 12
; CHECK-NEXT:    [[DST_GEP_I856_I23:%.*]] = getelementptr i8, ptr [[DST]], i32 12
; CHECK-NEXT:    [[TMP30:%.*]] = load i8, ptr [[SRC_GEP_I855_I22]], align 1
; CHECK-NEXT:    store i8 [[TMP30]], ptr [[DST_GEP_I856_I23]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB14_I10]]:
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3259_I11:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3260_I12:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP32:%.*]] = load i32, ptr [[SRC_GEP_I3259_I11]], align 4
; CHECK-NEXT:    store i32 [[TMP32]], ptr [[DST_GEP_I3260_I12]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3261_I13:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3262_I14:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP33:%.*]] = load i32, ptr [[SRC_GEP_I3261_I13]], align 4
; CHECK-NEXT:    store i32 [[TMP33]], ptr [[DST_GEP_I3262_I14]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1663_I15:%.*]] = getelementptr i8, ptr [[SRC]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1664_I16:%.*]] = getelementptr i8, ptr [[DST]], i32 12
; CHECK-NEXT:    [[TMP34:%.*]] = load i16, ptr [[SRC_GEP_I1663_I15]], align 2
; CHECK-NEXT:    store i16 [[TMP34]], ptr [[DST_GEP_I1664_I16]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB15_I1]]:
; CHECK-NEXT:    [[TMP35:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP35]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3267_I2:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3268_I3:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP36:%.*]] = load i32, ptr [[SRC_GEP_I3267_I2]], align 4
; CHECK-NEXT:    store i32 [[TMP36]], ptr [[DST_GEP_I3268_I3]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3269_I4:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3270_I5:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP37:%.*]] = load i32, ptr [[SRC_GEP_I3269_I4]], align 4
; CHECK-NEXT:    store i32 [[TMP37]], ptr [[DST_GEP_I3270_I5]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1671_I6:%.*]] = getelementptr i8, ptr [[SRC]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1672_I7:%.*]] = getelementptr i8, ptr [[DST]], i32 12
; CHECK-NEXT:    [[TMP38:%.*]] = load i16, ptr [[SRC_GEP_I1671_I6]], align 2
; CHECK-NEXT:    store i16 [[TMP38]], ptr [[DST_GEP_I1672_I7]], align 2
; CHECK-NEXT:    [[SRC_GEP_I873_I8:%.*]] = getelementptr i8, ptr [[SRC]], i32 14
; CHECK-NEXT:    [[DST_GEP_I874_I9:%.*]] = getelementptr i8, ptr [[DST]], i32 14
; CHECK-NEXT:    [[TMP39:%.*]] = load i8, ptr [[SRC_GEP_I873_I8]], align 1
; CHECK-NEXT:    store i8 [[TMP39]], ptr [[DST_GEP_I874_I9]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[HANDLE_TAIL]]:
; CHECK-NEXT:    switch i32 [[DST_ALIGN]], label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT:.*]] [
; CHECK-NEXT:      i32 15, label %[[SW_BB1_I:.*]]
; CHECK-NEXT:      i32 14, label %[[SW_BB2_I:.*]]
; CHECK-NEXT:      i32 13, label %[[SW_BB3_I:.*]]
; CHECK-NEXT:      i32 12, label %[[SW_BB4_I:.*]]
; CHECK-NEXT:      i32 11, label %[[SW_BB5_I:.*]]
; CHECK-NEXT:      i32 10, label %[[SW_BB6_I:.*]]
; CHECK-NEXT:      i32 9, label %[[SW_BB7_I:.*]]
; CHECK-NEXT:      i32 8, label %[[SW_BB8_I:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB9_I:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB10_I:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB11_I:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB12_I:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB13_I:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB14_I:.*]]
; CHECK-NEXT:      i32 1, label %[[SW_BB15_I:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB1_I]]:
; CHECK-NEXT:    [[TMP40:%.*]] = load i8, ptr [[SRC]], align 1
; CHECK-NEXT:    store i8 [[TMP40]], ptr [[DST]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB2_I]]:
; CHECK-NEXT:    [[TMP41:%.*]] = load i16, ptr [[SRC]], align 2
; CHECK-NEXT:    store i16 [[TMP41]], ptr [[DST]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB3_I]]:
; CHECK-NEXT:    [[TMP42:%.*]] = load i16, ptr [[SRC]], align 2
; CHECK-NEXT:    store i16 [[TMP42]], ptr [[DST]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84_I:%.*]] = getelementptr i8, ptr [[DST]], i32 2
; CHECK-NEXT:    [[TMP43:%.*]] = load i8, ptr [[SRC_GEP_I83_I]], align 1
; CHECK-NEXT:    store i8 [[TMP43]], ptr [[DST_GEP_I84_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB4_I]]:
; CHECK-NEXT:    [[TMP44:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP44]], ptr [[DST]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB5_I]]:
; CHECK-NEXT:    [[TMP45:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP45]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP46:%.*]] = load i8, ptr [[SRC_GEP_I87_I]], align 1
; CHECK-NEXT:    store i8 [[TMP46]], ptr [[DST_GEP_I88_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB6_I]]:
; CHECK-NEXT:    [[TMP47:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP47]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP48:%.*]] = load i16, ptr [[SRC_GEP_I1611_I]], align 2
; CHECK-NEXT:    store i16 [[TMP48]], ptr [[DST_GEP_I1612_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB7_I]]:
; CHECK-NEXT:    [[TMP49:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP49]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP50:%.*]] = load i16, ptr [[SRC_GEP_I1615_I]], align 2
; CHECK-NEXT:    store i16 [[TMP50]], ptr [[DST_GEP_I1616_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818_I:%.*]] = getelementptr i8, ptr [[DST]], i32 6
; CHECK-NEXT:    [[TMP51:%.*]] = load i8, ptr [[SRC_GEP_I817_I]], align 1
; CHECK-NEXT:    store i8 [[TMP51]], ptr [[DST_GEP_I818_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB8_I]]:
; CHECK-NEXT:    [[TMP52:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP52]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3221_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3222_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP53:%.*]] = load i32, ptr [[SRC_GEP_I3221_I]], align 4
; CHECK-NEXT:    store i32 [[TMP53]], ptr [[DST_GEP_I3222_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB9_I]]:
; CHECK-NEXT:    [[TMP54:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP54]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3225_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3226_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP55:%.*]] = load i32, ptr [[SRC_GEP_I3225_I]], align 4
; CHECK-NEXT:    store i32 [[TMP55]], ptr [[DST_GEP_I3226_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I827_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I828_I:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP56:%.*]] = load i8, ptr [[SRC_GEP_I827_I]], align 1
; CHECK-NEXT:    store i8 [[TMP56]], ptr [[DST_GEP_I828_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB10_I]]:
; CHECK-NEXT:    [[TMP57:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP57]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3231_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3232_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP58:%.*]] = load i32, ptr [[SRC_GEP_I3231_I]], align 4
; CHECK-NEXT:    store i32 [[TMP58]], ptr [[DST_GEP_I3232_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1633_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1634_I:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP59:%.*]] = load i16, ptr [[SRC_GEP_I1633_I]], align 2
; CHECK-NEXT:    store i16 [[TMP59]], ptr [[DST_GEP_I1634_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB11_I]]:
; CHECK-NEXT:    [[TMP60:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP60]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3237_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3238_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP61:%.*]] = load i32, ptr [[SRC_GEP_I3237_I]], align 4
; CHECK-NEXT:    store i32 [[TMP61]], ptr [[DST_GEP_I3238_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1639_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1640_I:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP62:%.*]] = load i16, ptr [[SRC_GEP_I1639_I]], align 2
; CHECK-NEXT:    store i16 [[TMP62]], ptr [[DST_GEP_I1640_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I841_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 10
; CHECK-NEXT:    [[DST_GEP_I842_I:%.*]] = getelementptr i8, ptr [[DST]], i32 10
; CHECK-NEXT:    [[TMP63:%.*]] = load i8, ptr [[SRC_GEP_I841_I]], align 1
; CHECK-NEXT:    store i8 [[TMP63]], ptr [[DST_GEP_I842_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB12_I]]:
; CHECK-NEXT:    [[TMP64:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP64]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3245_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3246_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP65:%.*]] = load i32, ptr [[SRC_GEP_I3245_I]], align 4
; CHECK-NEXT:    store i32 [[TMP65]], ptr [[DST_GEP_I3246_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3247_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3248_I:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP66:%.*]] = load i32, ptr [[SRC_GEP_I3247_I]], align 4
; CHECK-NEXT:    store i32 [[TMP66]], ptr [[DST_GEP_I3248_I]], align 4
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB13_I]]:
; CHECK-NEXT:    [[TMP67:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP67]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3251_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3252_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP68:%.*]] = load i32, ptr [[SRC_GEP_I3251_I]], align 4
; CHECK-NEXT:    store i32 [[TMP68]], ptr [[DST_GEP_I3252_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3253_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3254_I:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP69:%.*]] = load i32, ptr [[SRC_GEP_I3253_I]], align 4
; CHECK-NEXT:    store i32 [[TMP69]], ptr [[DST_GEP_I3254_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I855_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 12
; CHECK-NEXT:    [[DST_GEP_I856_I:%.*]] = getelementptr i8, ptr [[DST]], i32 12
; CHECK-NEXT:    [[TMP70:%.*]] = load i8, ptr [[SRC_GEP_I855_I]], align 1
; CHECK-NEXT:    store i8 [[TMP70]], ptr [[DST_GEP_I856_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB14_I]]:
; CHECK-NEXT:    [[TMP71:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP71]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3259_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3260_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP72:%.*]] = load i32, ptr [[SRC_GEP_I3259_I]], align 4
; CHECK-NEXT:    store i32 [[TMP72]], ptr [[DST_GEP_I3260_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3261_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3262_I:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP73:%.*]] = load i32, ptr [[SRC_GEP_I3261_I]], align 4
; CHECK-NEXT:    store i32 [[TMP73]], ptr [[DST_GEP_I3262_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1663_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1664_I:%.*]] = getelementptr i8, ptr [[DST]], i32 12
; CHECK-NEXT:    [[TMP74:%.*]] = load i16, ptr [[SRC_GEP_I1663_I]], align 2
; CHECK-NEXT:    store i16 [[TMP74]], ptr [[DST_GEP_I1664_I]], align 2
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[SW_BB15_I]]:
; CHECK-NEXT:    [[TMP75:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    store i32 [[TMP75]], ptr [[DST]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3267_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3268_I:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP76:%.*]] = load i32, ptr [[SRC_GEP_I3267_I]], align 4
; CHECK-NEXT:    store i32 [[TMP76]], ptr [[DST_GEP_I3268_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3269_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3270_I:%.*]] = getelementptr i8, ptr [[DST]], i32 8
; CHECK-NEXT:    [[TMP77:%.*]] = load i32, ptr [[SRC_GEP_I3269_I]], align 4
; CHECK-NEXT:    store i32 [[TMP77]], ptr [[DST_GEP_I3270_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1671_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1672_I:%.*]] = getelementptr i8, ptr [[DST]], i32 12
; CHECK-NEXT:    [[TMP78:%.*]] = load i16, ptr [[SRC_GEP_I1671_I]], align 2
; CHECK-NEXT:    store i16 [[TMP78]], ptr [[DST_GEP_I1672_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I873_I:%.*]] = getelementptr i8, ptr [[SRC]], i32 14
; CHECK-NEXT:    [[DST_GEP_I874_I:%.*]] = getelementptr i8, ptr [[DST]], i32 14
; CHECK-NEXT:    [[TMP79:%.*]] = load i8, ptr [[SRC_GEP_I873_I]], align 1
; CHECK-NEXT:    store i8 [[TMP79]], ptr [[DST_GEP_I874_I]], align 1
; CHECK-NEXT:    br label %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]]:
; CHECK-NEXT:    [[SUB2:%.*]] = sub i32 [[SIZE]], [[SUB]]
; CHECK-NEXT:    [[ADD_PTR1:%.*]] = getelementptr i8, ptr [[DST]], i32 [[SUB]]
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr i8, ptr [[SRC]], i32 [[SUB]]
; CHECK-NEXT:    [[TMP80:%.*]] = ptrtoint ptr [[ADD_PTR]] to i32
; CHECK-NEXT:    [[TMP81:%.*]] = ptrtoint ptr [[ADD_PTR1]] to i32
; CHECK-NEXT:    [[CMP_I:%.*]] = icmp ult i32 [[SUB2]], 16
; CHECK-NEXT:    br i1 [[CMP_I]], label %[[FINAL_CLEANUP_I:.*]], label %[[PROCESS_MAIN_LOOP_I:.*]]
; CHECK:       [[PROCESS_MAIN_LOOP_I]]:
; CHECK-NEXT:    [[DIV_I:%.*]] = udiv i32 [[SUB2]], 48
; CHECK-NEXT:    [[DOTNEG:%.*]] = mul i32 [[DIV_I]], -48
; CHECK-NEXT:    [[REM_DECOMPOSED_I:%.*]] = add i32 [[DOTNEG]], [[SUB2]]
; CHECK-NEXT:    [[LD128USARIP_I:%.*]] = call i32 @llvm.riscv.esp.ld.128.usar.ip(i32 [[TMP80]], i32 16, i32 0)
; CHECK-NEXT:    [[LD128USARIP1_I:%.*]] = call i32 @llvm.riscv.esp.ld.128.usar.ip(i32 [[LD128USARIP_I]], i32 16, i32 1)
; CHECK-NEXT:    [[CMP21_NOT_I:%.*]] = icmp ult i32 [[SUB2]], 48
; CHECK-NEXT:    br i1 [[CMP21_NOT_I]], label %[[HANDLE_REMAINDER_I:.*]], label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[HANDLE_REMAINDER_I]]:
; CHECK-NEXT:    [[SRC_PTR_AFTERLOOP_I:%.*]] = phi i32 [ [[LD128USARIP1_I]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[SRCQLDIP4_FINAL_I:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[DST_PTR_AFTERLOOP_I:%.*]] = phi i32 [ [[TMP81]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[VST128IP5_FINAL_I:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[TOBOOL_NOT_I:%.*]] = icmp ult i32 [[REM_DECOMPOSED_I]], 32
; CHECK-NEXT:    br i1 [[TOBOOL_NOT_I]], label %[[CHECK_16BYTE_TAIL_I:.*]], label %[[PROCESS_32BYTE_TAIL_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[I_022_I:%.*]] = phi i32 [ 0, %[[PROCESS_MAIN_LOOP_I]] ], [ [[INC_I:%.*]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[SRC_PTR_PHI_I:%.*]] = phi i32 [ [[LD128USARIP1_I]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[SRCQLDIP4_FINAL_I]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[DST_PTR_PHI_I:%.*]] = phi i32 [ [[TMP81]], %[[PROCESS_MAIN_LOOP_I]] ], [ [[VST128IP5_FINAL_I]], %[[MAIN_LOOP_BODY_I]] ]
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call i32 @llvm.riscv.esp.src.q.ld.ip(i32 1, i32 [[SRC_PTR_PHI_I]], i32 0, i32 16, i32 2)
; CHECK-NEXT:    [[VST128IP_I:%.*]] = call i32 @llvm.riscv.esp.vst.128.ip(i32 0, i32 [[DST_PTR_PHI_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call i32 @llvm.riscv.esp.src.q.ld.ip(i32 2, i32 [[SRCQLDIP_I]], i32 1, i32 16, i32 0)
; CHECK-NEXT:    [[VST128IP3_I:%.*]] = call i32 @llvm.riscv.esp.vst.128.ip(i32 1, i32 [[VST128IP_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_FINAL_I]] = call i32 @llvm.riscv.esp.src.q.ld.ip(i32 0, i32 [[SRCQLDIP2_I]], i32 2, i32 16, i32 1)
; CHECK-NEXT:    [[VST128IP5_FINAL_I]] = call i32 @llvm.riscv.esp.vst.128.ip(i32 2, i32 [[VST128IP3_I]], i32 16)
; CHECK-NEXT:    [[INC_I]] = add nuw nsw i32 [[I_022_I]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_I:%.*]] = icmp eq i32 [[INC_I]], [[DIV_I]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_I]], label %[[HANDLE_REMAINDER_I]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[PROCESS_32BYTE_TAIL_I]]:
; CHECK-NEXT:    [[SRCQLDIP6_I:%.*]] = call i32 @llvm.riscv.esp.src.q.ld.ip(i32 1, i32 [[SRC_PTR_AFTERLOOP_I]], i32 0, i32 0, i32 2)
; CHECK-NEXT:    [[VST128IP7_I:%.*]] = call i32 @llvm.riscv.esp.vst.128.ip(i32 0, i32 [[DST_PTR_AFTERLOOP_I]], i32 16)
; CHECK-NEXT:    call void @llvm.riscv.esp.src.q(i32 2, i32 1, i32 1)
; CHECK-NEXT:    [[VST128IP8_I:%.*]] = call i32 @llvm.riscv.esp.vst.128.ip(i32 1, i32 [[VST128IP7_I]], i32 16)
; CHECK-NEXT:    [[SUB1_I:%.*]] = add nsw i32 [[REM_DECOMPOSED_I]], -32
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[CHECK_16BYTE_TAIL_I]]:
; CHECK-NEXT:    [[TOBOOL5_NOT_I:%.*]] = icmp ult i32 [[REM_DECOMPOSED_I]], 16
; CHECK-NEXT:    br i1 [[TOBOOL5_NOT_I]], label %[[SKIP_TAIL_PROCESSING_I:.*]], label %[[PROCESS_16BYTE_TAIL_I:.*]]
; CHECK:       [[PROCESS_16BYTE_TAIL_I]]:
; CHECK-NEXT:    call void @llvm.riscv.esp.src.q(i32 1, i32 0, i32 0)
; CHECK-NEXT:    [[VST128IP9_I:%.*]] = call i32 @llvm.riscv.esp.vst.128.ip(i32 0, i32 [[DST_PTR_AFTERLOOP_I]], i32 16)
; CHECK-NEXT:    [[SUB_SRC_I:%.*]] = add i32 [[SRC_PTR_AFTERLOOP_I]], -16
; CHECK-NEXT:    [[SUB9_I:%.*]] = add nsw i32 [[REM_DECOMPOSED_I]], -16
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[SKIP_TAIL_PROCESSING_I]]:
; CHECK-NEXT:    [[SRC_END7_I:%.*]] = add i32 [[SRC_PTR_AFTERLOOP_I]], -32
; CHECK-NEXT:    br label %[[FINAL_CLEANUP_I]]
; CHECK:       [[FINAL_CLEANUP_I]]:
; CHECK-NEXT:    [[SRC_FINAL_I:%.*]] = phi i32 [ [[SRCQLDIP6_I]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[SUB_SRC_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[TMP80]], %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]] ], [ [[SRC_END7_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    [[DST_FINAL_I:%.*]] = phi i32 [ [[VST128IP8_I]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[VST128IP9_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[TMP81]], %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]] ], [ [[DST_PTR_AFTERLOOP_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    [[REM_FINAL_I:%.*]] = phi i32 [ [[SUB1_I]], %[[PROCESS_32BYTE_TAIL_I]] ], [ [[SUB9_I]], %[[PROCESS_16BYTE_TAIL_I]] ], [ [[SUB2]], %[[ESP32P4MEMCPYSRCUNALIGNDSTUNALIGNFROM1TO15OPT_EXIT]] ], [ [[REM_DECOMPOSED_I]], %[[SKIP_TAIL_PROCESSING_I]] ]
; CHECK-NEXT:    [[CMP_FINAL_I:%.*]] = icmp eq i32 [[REM_FINAL_I]], 0
; CHECK-NEXT:    br i1 [[CMP_FINAL_I]], label %[[RETURN]], label %[[CALL_SMALL_SIZE_CLEANUP_I:.*]]
; CHECK:       [[CALL_SMALL_SIZE_CLEANUP_I]]:
; CHECK-NEXT:    [[DST_PTR_FINAL_I:%.*]] = inttoptr i32 [[DST_FINAL_I]] to ptr
; CHECK-NEXT:    [[SRC_PTR_FINAL_I:%.*]] = inttoptr i32 [[SRC_FINAL_I]] to ptr
; CHECK-NEXT:    switch i32 [[REM_FINAL_I]], label %[[RETURN]] [
; CHECK-NEXT:      i32 1, label %[[SW_BB1_I131:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2_I130:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3_I127:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4_I126:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5_I123:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6_I120:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7_I115:.*]]
; CHECK-NEXT:      i32 8, label %[[SW_BB8_I112:.*]]
; CHECK-NEXT:      i32 9, label %[[SW_BB9_I107:.*]]
; CHECK-NEXT:      i32 10, label %[[SW_BB10_I102:.*]]
; CHECK-NEXT:      i32 11, label %[[SW_BB11_I95:.*]]
; CHECK-NEXT:      i32 12, label %[[SW_BB12_I90:.*]]
; CHECK-NEXT:      i32 13, label %[[SW_BB13_I83:.*]]
; CHECK-NEXT:      i32 14, label %[[SW_BB14_I76:.*]]
; CHECK-NEXT:      i32 15, label %[[SW_BB15_I67:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[SW_BB1_I131]]:
; CHECK-NEXT:    [[TMP82:%.*]] = load i8, ptr [[SRC_PTR_FINAL_I]], align 1
; CHECK-NEXT:    store i8 [[TMP82]], ptr [[DST_PTR_FINAL_I]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB2_I130]]:
; CHECK-NEXT:    [[TMP83:%.*]] = load i16, ptr [[SRC_PTR_FINAL_I]], align 2
; CHECK-NEXT:    store i16 [[TMP83]], ptr [[DST_PTR_FINAL_I]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB3_I127]]:
; CHECK-NEXT:    [[TMP84:%.*]] = load i16, ptr [[SRC_PTR_FINAL_I]], align 2
; CHECK-NEXT:    store i16 [[TMP84]], ptr [[DST_PTR_FINAL_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83_I128:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84_I129:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 2
; CHECK-NEXT:    [[TMP85:%.*]] = load i8, ptr [[SRC_GEP_I83_I128]], align 1
; CHECK-NEXT:    store i8 [[TMP85]], ptr [[DST_GEP_I84_I129]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB4_I126]]:
; CHECK-NEXT:    [[TMP86:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP86]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB5_I123]]:
; CHECK-NEXT:    [[TMP87:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP87]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87_I124:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88_I125:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP88:%.*]] = load i8, ptr [[SRC_GEP_I87_I124]], align 1
; CHECK-NEXT:    store i8 [[TMP88]], ptr [[DST_GEP_I88_I125]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB6_I120]]:
; CHECK-NEXT:    [[TMP89:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP89]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611_I121:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612_I122:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP90:%.*]] = load i16, ptr [[SRC_GEP_I1611_I121]], align 2
; CHECK-NEXT:    store i16 [[TMP90]], ptr [[DST_GEP_I1612_I122]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB7_I115]]:
; CHECK-NEXT:    [[TMP91:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP91]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615_I116:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616_I117:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP92:%.*]] = load i16, ptr [[SRC_GEP_I1615_I116]], align 2
; CHECK-NEXT:    store i16 [[TMP92]], ptr [[DST_GEP_I1616_I117]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817_I118:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818_I119:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 6
; CHECK-NEXT:    [[TMP93:%.*]] = load i8, ptr [[SRC_GEP_I817_I118]], align 1
; CHECK-NEXT:    store i8 [[TMP93]], ptr [[DST_GEP_I818_I119]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB8_I112]]:
; CHECK-NEXT:    [[TMP94:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP94]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3221_I113:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3222_I114:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP95:%.*]] = load i32, ptr [[SRC_GEP_I3221_I113]], align 4
; CHECK-NEXT:    store i32 [[TMP95]], ptr [[DST_GEP_I3222_I114]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB9_I107]]:
; CHECK-NEXT:    [[TMP96:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP96]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3225_I108:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3226_I109:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP97:%.*]] = load i32, ptr [[SRC_GEP_I3225_I108]], align 4
; CHECK-NEXT:    store i32 [[TMP97]], ptr [[DST_GEP_I3226_I109]], align 4
; CHECK-NEXT:    [[SRC_GEP_I827_I110:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I828_I111:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP98:%.*]] = load i8, ptr [[SRC_GEP_I827_I110]], align 1
; CHECK-NEXT:    store i8 [[TMP98]], ptr [[DST_GEP_I828_I111]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB10_I102]]:
; CHECK-NEXT:    [[TMP99:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP99]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3231_I103:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3232_I104:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP100:%.*]] = load i32, ptr [[SRC_GEP_I3231_I103]], align 4
; CHECK-NEXT:    store i32 [[TMP100]], ptr [[DST_GEP_I3232_I104]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1633_I105:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1634_I106:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP101:%.*]] = load i16, ptr [[SRC_GEP_I1633_I105]], align 2
; CHECK-NEXT:    store i16 [[TMP101]], ptr [[DST_GEP_I1634_I106]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB11_I95]]:
; CHECK-NEXT:    [[TMP102:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP102]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3237_I96:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3238_I97:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP103:%.*]] = load i32, ptr [[SRC_GEP_I3237_I96]], align 4
; CHECK-NEXT:    store i32 [[TMP103]], ptr [[DST_GEP_I3238_I97]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1639_I98:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I1640_I99:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP104:%.*]] = load i16, ptr [[SRC_GEP_I1639_I98]], align 2
; CHECK-NEXT:    store i16 [[TMP104]], ptr [[DST_GEP_I1640_I99]], align 2
; CHECK-NEXT:    [[SRC_GEP_I841_I100:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 10
; CHECK-NEXT:    [[DST_GEP_I842_I101:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 10
; CHECK-NEXT:    [[TMP105:%.*]] = load i8, ptr [[SRC_GEP_I841_I100]], align 1
; CHECK-NEXT:    store i8 [[TMP105]], ptr [[DST_GEP_I842_I101]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB12_I90]]:
; CHECK-NEXT:    [[TMP106:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP106]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3245_I91:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3246_I92:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP107:%.*]] = load i32, ptr [[SRC_GEP_I3245_I91]], align 4
; CHECK-NEXT:    store i32 [[TMP107]], ptr [[DST_GEP_I3246_I92]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3247_I93:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3248_I94:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP108:%.*]] = load i32, ptr [[SRC_GEP_I3247_I93]], align 4
; CHECK-NEXT:    store i32 [[TMP108]], ptr [[DST_GEP_I3248_I94]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB13_I83]]:
; CHECK-NEXT:    [[TMP109:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP109]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3251_I84:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3252_I85:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP110:%.*]] = load i32, ptr [[SRC_GEP_I3251_I84]], align 4
; CHECK-NEXT:    store i32 [[TMP110]], ptr [[DST_GEP_I3252_I85]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3253_I86:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3254_I87:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP111:%.*]] = load i32, ptr [[SRC_GEP_I3253_I86]], align 4
; CHECK-NEXT:    store i32 [[TMP111]], ptr [[DST_GEP_I3254_I87]], align 4
; CHECK-NEXT:    [[SRC_GEP_I855_I88:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I856_I89:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP112:%.*]] = load i8, ptr [[SRC_GEP_I855_I88]], align 1
; CHECK-NEXT:    store i8 [[TMP112]], ptr [[DST_GEP_I856_I89]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB14_I76]]:
; CHECK-NEXT:    [[TMP113:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP113]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3259_I77:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3260_I78:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP114:%.*]] = load i32, ptr [[SRC_GEP_I3259_I77]], align 4
; CHECK-NEXT:    store i32 [[TMP114]], ptr [[DST_GEP_I3260_I78]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3261_I79:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3262_I80:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP115:%.*]] = load i32, ptr [[SRC_GEP_I3261_I79]], align 4
; CHECK-NEXT:    store i32 [[TMP115]], ptr [[DST_GEP_I3262_I80]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1663_I81:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1664_I82:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP116:%.*]] = load i16, ptr [[SRC_GEP_I1663_I81]], align 2
; CHECK-NEXT:    store i16 [[TMP116]], ptr [[DST_GEP_I1664_I82]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB15_I67]]:
; CHECK-NEXT:    [[TMP117:%.*]] = load i32, ptr [[SRC_PTR_FINAL_I]], align 4
; CHECK-NEXT:    store i32 [[TMP117]], ptr [[DST_PTR_FINAL_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3267_I68:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3268_I69:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 4
; CHECK-NEXT:    [[TMP118:%.*]] = load i32, ptr [[SRC_GEP_I3267_I68]], align 4
; CHECK-NEXT:    store i32 [[TMP118]], ptr [[DST_GEP_I3268_I69]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3269_I70:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3270_I71:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 8
; CHECK-NEXT:    [[TMP119:%.*]] = load i32, ptr [[SRC_GEP_I3269_I70]], align 4
; CHECK-NEXT:    store i32 [[TMP119]], ptr [[DST_GEP_I3270_I71]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1671_I72:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1672_I73:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 12
; CHECK-NEXT:    [[TMP120:%.*]] = load i16, ptr [[SRC_GEP_I1671_I72]], align 2
; CHECK-NEXT:    store i16 [[TMP120]], ptr [[DST_GEP_I1672_I73]], align 2
; CHECK-NEXT:    [[SRC_GEP_I873_I74:%.*]] = getelementptr i8, ptr [[SRC_PTR_FINAL_I]], i32 14
; CHECK-NEXT:    [[DST_GEP_I874_I75:%.*]] = getelementptr i8, ptr [[DST_PTR_FINAL_I]], i32 14
; CHECK-NEXT:    [[TMP121:%.*]] = load i8, ptr [[SRC_GEP_I873_I74]], align 1
; CHECK-NEXT:    store i8 [[TMP121]], ptr [[DST_GEP_I874_I75]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal void @esp32p4MemCpySrc8Dst16From1To7Opt(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    switch i32 [[SIZE]], label %[[RETURN:.*]] [
; CHECK-NEXT:      i32 1, label %[[SW_BB1:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[SW_BB1]]:
; CHECK-NEXT:    [[SRC_GEP_I8:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I8:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[SRC_GEP_I8]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[DST_GEP_I8]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB2]]:
; CHECK-NEXT:    [[SRC_GEP_I16:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I16:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[SRC_GEP_I16]], align 2
; CHECK-NEXT:    store i16 [[TMP1]], ptr [[DST_GEP_I16]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB3]]:
; CHECK-NEXT:    [[SRC_GEP_I161:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I162:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[SRC_GEP_I161]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[DST_GEP_I162]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83:%.*]] = getelementptr i8, ptr [[SRC]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84:%.*]] = getelementptr i8, ptr [[DST]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[SRC_GEP_I83]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[DST_GEP_I84]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB4]]:
; CHECK-NEXT:    [[SRC_GEP_I32:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I32:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[SRC_GEP_I32]], align 4
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[DST_GEP_I32]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB5]]:
; CHECK-NEXT:    [[SRC_GEP_I325:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I326:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[SRC_GEP_I325]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[DST_GEP_I326]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[SRC_GEP_I87]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[DST_GEP_I88]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB6]]:
; CHECK-NEXT:    [[SRC_GEP_I329:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I3210:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[SRC_GEP_I329]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[DST_GEP_I3210]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[SRC_GEP_I1611]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[DST_GEP_I1612]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB7]]:
; CHECK-NEXT:    [[SRC_GEP_I3213:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I3214:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[SRC_GEP_I3213]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[DST_GEP_I3214]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[SRC_GEP_I1615]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[DST_GEP_I1616]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817:%.*]] = getelementptr i8, ptr [[SRC]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818:%.*]] = getelementptr i8, ptr [[DST]], i32 6
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[SRC_GEP_I817]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[DST_GEP_I818]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
;
;
; CHECK-LABEL: define internal void @esp32p4MemCpySrc8Dst8From1To7Opt(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    switch i32 [[SIZE]], label %[[RETURN:.*]] [
; CHECK-NEXT:      i32 1, label %[[SW_BB1:.*]]
; CHECK-NEXT:      i32 2, label %[[SW_BB2:.*]]
; CHECK-NEXT:      i32 3, label %[[SW_BB3:.*]]
; CHECK-NEXT:      i32 4, label %[[SW_BB4:.*]]
; CHECK-NEXT:      i32 5, label %[[SW_BB5:.*]]
; CHECK-NEXT:      i32 6, label %[[SW_BB6:.*]]
; CHECK-NEXT:      i32 7, label %[[SW_BB7:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[SW_BB1]]:
; CHECK-NEXT:    [[SRC_GEP_I8:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I8:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[SRC_GEP_I8]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[DST_GEP_I8]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB2]]:
; CHECK-NEXT:    [[SRC_GEP_I16:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I16:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[SRC_GEP_I16]], align 2
; CHECK-NEXT:    store i16 [[TMP1]], ptr [[DST_GEP_I16]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB3]]:
; CHECK-NEXT:    [[SRC_GEP_I161:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I162:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[SRC_GEP_I161]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[DST_GEP_I162]], align 2
; CHECK-NEXT:    [[SRC_GEP_I83:%.*]] = getelementptr i8, ptr [[SRC]], i32 2
; CHECK-NEXT:    [[DST_GEP_I84:%.*]] = getelementptr i8, ptr [[DST]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[SRC_GEP_I83]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[DST_GEP_I84]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB4]]:
; CHECK-NEXT:    [[SRC_GEP_I32:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I32:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[SRC_GEP_I32]], align 4
; CHECK-NEXT:    store i32 [[TMP4]], ptr [[DST_GEP_I32]], align 4
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB5]]:
; CHECK-NEXT:    [[SRC_GEP_I325:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I326:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[SRC_GEP_I325]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[DST_GEP_I326]], align 4
; CHECK-NEXT:    [[SRC_GEP_I87:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I88:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[SRC_GEP_I87]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[DST_GEP_I88]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB6]]:
; CHECK-NEXT:    [[SRC_GEP_I329:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I3210:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[SRC_GEP_I329]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[DST_GEP_I3210]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1611:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1612:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[SRC_GEP_I1611]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[DST_GEP_I1612]], align 2
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[SW_BB7]]:
; CHECK-NEXT:    [[SRC_GEP_I3213:%.*]] = getelementptr i8, ptr [[SRC]], i32 0
; CHECK-NEXT:    [[DST_GEP_I3214:%.*]] = getelementptr i8, ptr [[DST]], i32 0
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[SRC_GEP_I3213]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[DST_GEP_I3214]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1615:%.*]] = getelementptr i8, ptr [[SRC]], i32 4
; CHECK-NEXT:    [[DST_GEP_I1616:%.*]] = getelementptr i8, ptr [[DST]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[SRC_GEP_I1615]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[DST_GEP_I1616]], align 2
; CHECK-NEXT:    [[SRC_GEP_I817:%.*]] = getelementptr i8, ptr [[SRC]], i32 6
; CHECK-NEXT:    [[DST_GEP_I818:%.*]] = getelementptr i8, ptr [[DST]], i32 6
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[SRC_GEP_I817]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[DST_GEP_I818]], align 1
; CHECK-NEXT:    br label %[[RETURN]]
;
;
; CHECK-LABEL: define internal void @esp32p4MemCpySrc16Dst16Var(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[IS_LT_8:%.*]] = icmp ult i32 [[SIZE]], 8
; CHECK-NEXT:    br i1 [[IS_LT_8]], label %[[HANDLE_SMALL_SIZE:.*]], label %[[CHECK_MID_RANGE:.*]]
; CHECK:       [[HANDLE_SMALL_SIZE]]:
; CHECK-NEXT:    call void @esp32p4MemCpySrc16Dst16From1To7Opt(ptr [[DST]], ptr [[SRC]], i32 [[SIZE]])
; CHECK-NEXT:    br label %[[RETURN:.*]]
; CHECK:       [[CHECK_MID_RANGE]]:
; CHECK-NEXT:    [[IS_LT_16:%.*]] = icmp ult i32 [[SIZE]], 16
; CHECK-NEXT:    br i1 [[IS_LT_16]], label %[[HANDLE_MID_SIZE:.*]], label %[[HANDLE_LARGE_LOOP:.*]]
; CHECK:       [[HANDLE_MID_SIZE]]:
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP0]], ptr [[DST]], i32 8)
; CHECK-NEXT:    [[SIZE_MINUS_8:%.*]] = add nsw i32 [[SIZE]], -8
; CHECK-NEXT:    call void @esp32p4MemCpySrc16Dst16From1To7Opt(ptr [[VSTL64IP_M]], ptr [[TMP1]], i32 [[SIZE_MINUS_8]])
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[HANDLE_LARGE_LOOP]]:
; CHECK-NEXT:    [[NUM_128B_BLOCKS:%.*]] = lshr i32 [[SIZE]], 7
; CHECK-NEXT:    [[NUM_16B_BLOCKS:%.*]] = lshr i32 [[SIZE]], 4
; CHECK-NEXT:    [[REMAINING_16B_BLOCKS:%.*]] = and i32 [[NUM_16B_BLOCKS]], 7
; CHECK-NEXT:    [[REMAINING_BYTES:%.*]] = and i32 [[SIZE]], 7
; CHECK-NEXT:    [[IS_LT_128:%.*]] = icmp ult i32 [[SIZE]], 128
; CHECK-NEXT:    br i1 [[IS_LT_128]], label %[[LOOP_EXIT_CLEANUP:.*]], label %[[LOOP_BODY_128B:.*]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[LOOP_EXIT_CLEANUP]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_LOOP:%.*]] = phi ptr [ [[SRC]], %[[HANDLE_LARGE_LOOP]] ], [ [[TMP17:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_LOOP:%.*]] = phi ptr [ [[DST]], %[[HANDLE_LARGE_LOOP]] ], [ [[VST128IP_M14:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    switch i32 [[REMAINING_16B_BLOCKS]], label %[[INVALID_SWITCH_TRAP:.*]] [
; CHECK-NEXT:      i32 1, label %[[TAIL_CASE_1:.*]]
; CHECK-NEXT:      i32 2, label %[[TAIL_CASE_2:.*]]
; CHECK-NEXT:      i32 3, label %[[TAIL_CASE_3:.*]]
; CHECK-NEXT:      i32 4, label %[[TAIL_CASE_4:.*]]
; CHECK-NEXT:      i32 5, label %[[TAIL_CASE_5:.*]]
; CHECK-NEXT:      i32 6, label %[[TAIL_CASE_6:.*]]
; CHECK-NEXT:      i32 7, label %[[TAIL_CASE_7:.*]]
; CHECK-NEXT:      i32 0, label %[[HANDLE_TAIL_SWITCH:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[LOOP_BODY_128B]]:
; CHECK-NEXT:    [[LOOP_INDEX:%.*]] = phi i32 [ 0, %[[HANDLE_LARGE_LOOP]] ], [ [[LOOP_INC:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[SRC_PTR_LOOP:%.*]] = phi ptr [ [[SRC]], %[[HANDLE_LARGE_LOOP]] ], [ [[TMP17]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[DST_PTR_LOOP:%.*]] = phi ptr [ [[DST]], %[[HANDLE_LARGE_LOOP]] ], [ [[VST128IP_M14]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP2]], ptr [[DST_PTR_LOOP]], i32 16)
; CHECK-NEXT:    [[VST128IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP4]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP6]], ptr [[VST128IP_M4]], i32 16)
; CHECK-NEXT:    [[VST128IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP8]], ptr [[VST128IP_M5]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 1
; CHECK-NEXT:    [[VLD128IP_M8:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M8]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M8]], 1
; CHECK-NEXT:    [[VLD128IP_M9:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M9]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M9]], 1
; CHECK-NEXT:    [[VLD128IP_M10:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP15]], i32 16)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M10]], 0
; CHECK-NEXT:    [[TMP17]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M10]], 1
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP10]], ptr [[VST128IP_M6]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP12]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    [[VST128IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP14]], ptr [[VST128IP_M12]], i32 16)
; CHECK-NEXT:    [[VST128IP_M14]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP16]], ptr [[VST128IP_M13]], i32 16)
; CHECK-NEXT:    [[LOOP_INC]] = add nuw nsw i32 [[LOOP_INDEX]], 1
; CHECK-NEXT:    [[LOOP_DONE:%.*]] = icmp eq i32 [[LOOP_INC]], [[NUM_128B_BLOCKS]]
; CHECK-NEXT:    br i1 [[LOOP_DONE]], label %[[LOOP_EXIT_CLEANUP]], label %[[LOOP_BODY_128B]]
; CHECK:       [[HANDLE_TAIL_SWITCH]]:
; CHECK-NEXT:    [[SRC_PTR_TAIL:%.*]] = phi ptr [ [[SRC_PTR_AFTER_LOOP]], %[[LOOP_EXIT_CLEANUP]] ], [ [[TMP24:%.*]], %[[TAIL_CASE_1]] ], [ [[TMP28:%.*]], %[[TAIL_CASE_2]] ], [ [[TMP34:%.*]], %[[TAIL_CASE_3]] ], [ [[TMP42:%.*]], %[[TAIL_CASE_4]] ], [ [[TMP52:%.*]], %[[TAIL_CASE_5]] ], [ [[TMP64:%.*]], %[[TAIL_CASE_6]] ], [ [[TMP78:%.*]], %[[TAIL_CASE_7]] ]
; CHECK-NEXT:    [[DST_PTR_TAIL:%.*]] = phi ptr [ [[DST_PTR_AFTER_LOOP]], %[[LOOP_EXIT_CLEANUP]] ], [ [[VST128IP_M16:%.*]], %[[TAIL_CASE_1]] ], [ [[VST128IP_M20:%.*]], %[[TAIL_CASE_2]] ], [ [[VST128IP_M26:%.*]], %[[TAIL_CASE_3]] ], [ [[VST128IP_M34:%.*]], %[[TAIL_CASE_4]] ], [ [[VST128IP_M44:%.*]], %[[TAIL_CASE_5]] ], [ [[VST128IP_M56:%.*]], %[[TAIL_CASE_6]] ], [ [[VST128IP_M70:%.*]], %[[TAIL_CASE_7]] ]
; CHECK-NEXT:    [[TMP18:%.*]] = and i32 [[SIZE]], 8
; CHECK-NEXT:    [[TMP19:%.*]] = icmp eq i32 [[TMP18]], 0
; CHECK-NEXT:    br i1 [[TMP19]], label %[[AFTER_8B_TAIL:.*]], label %[[HANDLE_8B_TAIL:.*]]
; CHECK:       [[INVALID_SWITCH_TRAP]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[HANDLE_8B_TAIL]]:
; CHECK-NEXT:    [[VLDL64IP_M71:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_TAIL]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 1
; CHECK-NEXT:    [[VSTL64IP_M72:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP20]], ptr [[DST_PTR_TAIL]], i32 8)
; CHECK-NEXT:    br label %[[AFTER_8B_TAIL]]
; CHECK:       [[AFTER_8B_TAIL]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_8B:%.*]] = phi ptr [ [[SRC_PTR_TAIL]], %[[HANDLE_TAIL_SWITCH]] ], [ [[TMP21]], %[[HANDLE_8B_TAIL]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_8B:%.*]] = phi ptr [ [[DST_PTR_TAIL]], %[[HANDLE_TAIL_SWITCH]] ], [ [[VSTL64IP_M72]], %[[HANDLE_8B_TAIL]] ]
; CHECK-NEXT:    [[TMP22:%.*]] = icmp eq i32 [[REMAINING_BYTES]], 0
; CHECK-NEXT:    br i1 [[TMP22]], label %[[RETURN]], label %[[HANDLE_REMAINING_BYTES:.*]]
; CHECK:       [[TAIL_CASE_1]]:
; CHECK-NEXT:    [[VLD128IP_M15:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 0
; CHECK-NEXT:    [[TMP24]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 1
; CHECK-NEXT:    [[VST128IP_M16]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP23]], ptr [[DST_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_2]]:
; CHECK-NEXT:    [[VLD128IP_M17:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 0
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 1
; CHECK-NEXT:    [[VLD128IP_M18:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP26]], i32 16)
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 0
; CHECK-NEXT:    [[TMP28]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 1
; CHECK-NEXT:    [[VST128IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP25]], ptr [[DST_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[VST128IP_M20]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP27]], ptr [[VST128IP_M19]], i32 16)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_3]]:
; CHECK-NEXT:    [[VLD128IP_M21:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M21]], 0
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M21]], 1
; CHECK-NEXT:    [[VLD128IP_M22:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP30]], i32 16)
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 0
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 1
; CHECK-NEXT:    [[VLD128IP_M23:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP32]], i32 16)
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 0
; CHECK-NEXT:    [[TMP34]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 1
; CHECK-NEXT:    [[VST128IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP29]], ptr [[DST_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[VST128IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP31]], ptr [[VST128IP_M24]], i32 16)
; CHECK-NEXT:    [[VST128IP_M26]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP33]], ptr [[VST128IP_M25]], i32 16)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_4]]:
; CHECK-NEXT:    [[VLD128IP_M27:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 0
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 1
; CHECK-NEXT:    [[VLD128IP_M28:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP36]], i32 16)
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M28]], 0
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M28]], 1
; CHECK-NEXT:    [[VLD128IP_M29:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP38]], i32 16)
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M29]], 0
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M29]], 1
; CHECK-NEXT:    [[VLD128IP_M30:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP40]], i32 16)
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M30]], 0
; CHECK-NEXT:    [[TMP42]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M30]], 1
; CHECK-NEXT:    [[VST128IP_M31:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP35]], ptr [[DST_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[VST128IP_M32:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP37]], ptr [[VST128IP_M31]], i32 16)
; CHECK-NEXT:    [[VST128IP_M33:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP39]], ptr [[VST128IP_M32]], i32 16)
; CHECK-NEXT:    [[VST128IP_M34]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP41]], ptr [[VST128IP_M33]], i32 16)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_5]]:
; CHECK-NEXT:    [[VLD128IP_M35:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M35]], 0
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M35]], 1
; CHECK-NEXT:    [[VLD128IP_M36:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP44]], i32 16)
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M36]], 0
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M36]], 1
; CHECK-NEXT:    [[VLD128IP_M37:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP46]], i32 16)
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M37]], 0
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M37]], 1
; CHECK-NEXT:    [[VLD128IP_M38:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP48]], i32 16)
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M38]], 0
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M38]], 1
; CHECK-NEXT:    [[VST128IP_M39:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP43]], ptr [[DST_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[VST128IP_M40:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP45]], ptr [[VST128IP_M39]], i32 16)
; CHECK-NEXT:    [[VST128IP_M41:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP47]], ptr [[VST128IP_M40]], i32 16)
; CHECK-NEXT:    [[VST128IP_M42:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP49]], ptr [[VST128IP_M41]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M43:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP50]], i32 16)
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M43]], 0
; CHECK-NEXT:    [[TMP52]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M43]], 1
; CHECK-NEXT:    [[VST128IP_M44]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP51]], ptr [[VST128IP_M42]], i32 16)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_6]]:
; CHECK-NEXT:    [[VLD128IP_M45:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M45]], 0
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M45]], 1
; CHECK-NEXT:    [[VLD128IP_M46:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP54]], i32 16)
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M46]], 0
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M46]], 1
; CHECK-NEXT:    [[VLD128IP_M47:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP56]], i32 16)
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 0
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 1
; CHECK-NEXT:    [[VLD128IP_M48:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP58]], i32 16)
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 0
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 1
; CHECK-NEXT:    [[VST128IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP53]], ptr [[DST_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[VST128IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP55]], ptr [[VST128IP_M49]], i32 16)
; CHECK-NEXT:    [[VST128IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP57]], ptr [[VST128IP_M50]], i32 16)
; CHECK-NEXT:    [[VST128IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP59]], ptr [[VST128IP_M51]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M53:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP60]], i32 16)
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 0
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 1
; CHECK-NEXT:    [[VLD128IP_M54:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP62]], i32 16)
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M54]], 0
; CHECK-NEXT:    [[TMP64]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M54]], 1
; CHECK-NEXT:    [[VST128IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP61]], ptr [[VST128IP_M52]], i32 16)
; CHECK-NEXT:    [[VST128IP_M56]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP63]], ptr [[VST128IP_M55]], i32 16)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_7]]:
; CHECK-NEXT:    [[VLD128IP_M57:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M57]], 0
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M57]], 1
; CHECK-NEXT:    [[VLD128IP_M58:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP66]], i32 16)
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M58]], 0
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M58]], 1
; CHECK-NEXT:    [[VLD128IP_M59:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP68]], i32 16)
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M59]], 0
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M59]], 1
; CHECK-NEXT:    [[VLD128IP_M60:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP70]], i32 16)
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M60]], 0
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M60]], 1
; CHECK-NEXT:    [[VST128IP_M61:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP65]], ptr [[DST_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[VST128IP_M62:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP67]], ptr [[VST128IP_M61]], i32 16)
; CHECK-NEXT:    [[VST128IP_M63:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP69]], ptr [[VST128IP_M62]], i32 16)
; CHECK-NEXT:    [[VST128IP_M64:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP71]], ptr [[VST128IP_M63]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M65:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP72]], i32 16)
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M65]], 0
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M65]], 1
; CHECK-NEXT:    [[VLD128IP_M66:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP74]], i32 16)
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M66]], 0
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M66]], 1
; CHECK-NEXT:    [[VLD128IP_M67:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP76]], i32 16)
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M67]], 0
; CHECK-NEXT:    [[TMP78]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M67]], 1
; CHECK-NEXT:    [[VST128IP_M68:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP73]], ptr [[VST128IP_M64]], i32 16)
; CHECK-NEXT:    [[VST128IP_M69:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP75]], ptr [[VST128IP_M68]], i32 16)
; CHECK-NEXT:    [[VST128IP_M70]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP77]], ptr [[VST128IP_M69]], i32 16)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[HANDLE_REMAINING_BYTES]]:
; CHECK-NEXT:    call void @esp32p4MemCpySrc16Dst16From1To7Opt(ptr [[DST_PTR_AFTER_8B]], ptr [[SRC_PTR_AFTER_8B]], i32 [[REMAINING_BYTES]])
; CHECK-NEXT:    br label %[[RETURN]]
;
;
; CHECK-LABEL: define internal void @esp32p4MemCpySrc16Dst8Var(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[IS_LT_8:%.*]] = icmp ult i32 [[SIZE]], 8
; CHECK-NEXT:    br i1 [[IS_LT_8]], label %[[HANDLE_SMALL_SIZE:.*]], label %[[CHECK_MID_RANGE:.*]]
; CHECK:       [[HANDLE_SMALL_SIZE]]:
; CHECK-NEXT:    call void @esp32p4MemCpySrc16Dst8From1To7Opt(ptr [[DST]], ptr [[SRC]], i32 [[SIZE]])
; CHECK-NEXT:    br label %[[RETURN:.*]]
; CHECK:       [[CHECK_MID_RANGE]]:
; CHECK-NEXT:    [[IS_LT_16:%.*]] = icmp ult i32 [[SIZE]], 16
; CHECK-NEXT:    br i1 [[IS_LT_16]], label %[[HANDLE_MID_SIZE:.*]], label %[[HANDLE_LARGE_LOOP:.*]]
; CHECK:       [[HANDLE_MID_SIZE]]:
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP0]], ptr [[DST]], i32 8)
; CHECK-NEXT:    [[SIZE_MINUS_8:%.*]] = add nsw i32 [[SIZE]], -8
; CHECK-NEXT:    call void @esp32p4MemCpySrc16Dst8From1To7Opt(ptr [[VSTL64IP_M]], ptr [[TMP1]], i32 [[SIZE_MINUS_8]])
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[HANDLE_LARGE_LOOP]]:
; CHECK-NEXT:    [[NUM_128B_BLOCKS:%.*]] = lshr i32 [[SIZE]], 7
; CHECK-NEXT:    [[NUM_16B_BLOCKS:%.*]] = lshr i32 [[SIZE]], 4
; CHECK-NEXT:    [[REMAINING_16B_BLOCKS:%.*]] = and i32 [[NUM_16B_BLOCKS]], 7
; CHECK-NEXT:    [[REMAINING_BYTES:%.*]] = and i32 [[SIZE]], 7
; CHECK-NEXT:    [[IS_LT_128:%.*]] = icmp ult i32 [[SIZE]], 128
; CHECK-NEXT:    br i1 [[IS_LT_128]], label %[[LOOP_EXIT_CLEANUP:.*]], label %[[LOOP_BODY_128B:.*]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[LOOP_EXIT_CLEANUP]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_LOOP:%.*]] = phi ptr [ [[SRC]], %[[HANDLE_LARGE_LOOP]] ], [ [[TMP33:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_LOOP:%.*]] = phi ptr [ [[DST]], %[[HANDLE_LARGE_LOOP]] ], [ [[VSTH64IP_M30:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    switch i32 [[REMAINING_16B_BLOCKS]], label %[[INVALID_SWITCH_TRAP:.*]] [
; CHECK-NEXT:      i32 1, label %[[TAIL_CASE_1:.*]]
; CHECK-NEXT:      i32 2, label %[[TAIL_CASE_2:.*]]
; CHECK-NEXT:      i32 3, label %[[TAIL_CASE_3:.*]]
; CHECK-NEXT:      i32 4, label %[[TAIL_CASE_4:.*]]
; CHECK-NEXT:      i32 5, label %[[TAIL_CASE_5:.*]]
; CHECK-NEXT:      i32 6, label %[[TAIL_CASE_6:.*]]
; CHECK-NEXT:      i32 7, label %[[TAIL_CASE_7:.*]]
; CHECK-NEXT:      i32 0, label %[[HANDLE_TAIL_SWITCH:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[LOOP_BODY_128B]]:
; CHECK-NEXT:    [[LOOP_INDEX:%.*]] = phi i32 [ 0, %[[HANDLE_LARGE_LOOP]] ], [ [[LOOP_INC:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[SRC_PTR_LOOP:%.*]] = phi ptr [ [[SRC]], %[[HANDLE_LARGE_LOOP]] ], [ [[TMP33]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[DST_PTR_LOOP:%.*]] = phi ptr [ [[DST]], %[[HANDLE_LARGE_LOOP]] ], [ [[VSTH64IP_M30]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M2]], 1
; CHECK-NEXT:    [[VLDH64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M3]], 1
; CHECK-NEXT:    [[VLDL64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 1
; CHECK-NEXT:    [[VLDH64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M5]], 1
; CHECK-NEXT:    [[VLDL64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M6]], 1
; CHECK-NEXT:    [[VLDH64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M7]], 1
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP2]], ptr [[DST_PTR_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP4]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP6]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP8]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP10]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP12]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP14]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M15:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M15]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M15]], 1
; CHECK-NEXT:    [[VLDH64IP_M16:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M16]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M16]], 1
; CHECK-NEXT:    [[VLDL64IP_M17:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M17]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M17]], 1
; CHECK-NEXT:    [[VLDH64IP_M18:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M18]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M18]], 1
; CHECK-NEXT:    [[VLDL64IP_M19:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M19]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M19]], 1
; CHECK-NEXT:    [[VLDH64IP_M20:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M20]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M20]], 1
; CHECK-NEXT:    [[VLDL64IP_M21:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 1
; CHECK-NEXT:    [[VLDH64IP_M22:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M22]], 0
; CHECK-NEXT:    [[TMP33]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M22]], 1
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP18]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP20]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP22]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP24]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP26]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP28]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M29:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP30]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M30]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP32]], ptr [[VSTL64IP_M29]], i32 8)
; CHECK-NEXT:    [[LOOP_INC]] = add nuw nsw i32 [[LOOP_INDEX]], 1
; CHECK-NEXT:    [[LOOP_DONE:%.*]] = icmp eq i32 [[LOOP_INC]], [[NUM_128B_BLOCKS]]
; CHECK-NEXT:    br i1 [[LOOP_DONE]], label %[[LOOP_EXIT_CLEANUP]], label %[[LOOP_BODY_128B]]
; CHECK:       [[HANDLE_TAIL_SWITCH]]:
; CHECK-NEXT:    [[SRC_PTR_TAIL:%.*]] = phi ptr [ [[SRC_PTR_AFTER_LOOP]], %[[LOOP_EXIT_CLEANUP]] ], [ [[TMP40:%.*]], %[[TAIL_CASE_1]] ], [ [[TMP46:%.*]], %[[TAIL_CASE_2]] ], [ [[TMP56:%.*]], %[[TAIL_CASE_3]] ], [ [[TMP70:%.*]], %[[TAIL_CASE_4]] ], [ [[TMP96:%.*]], %[[TAIL_CASE_5]] ], [ [[TMP118:%.*]], %[[TAIL_CASE_6]] ], [ [[TMP144:%.*]], %[[TAIL_CASE_7]] ]
; CHECK-NEXT:    [[DST_PTR_TAIL:%.*]] = phi ptr [ [[DST_PTR_AFTER_LOOP]], %[[LOOP_EXIT_CLEANUP]] ], [ [[VSTH64IP_M32:%.*]], %[[TAIL_CASE_1]] ], [ [[VSTH64IP_M38:%.*]], %[[TAIL_CASE_2]] ], [ [[VSTH64IP_M47:%.*]], %[[TAIL_CASE_3]] ], [ [[VSTH64IP_M59:%.*]], %[[TAIL_CASE_4]] ], [ [[VSTH64IP_M74:%.*]], %[[TAIL_CASE_5]] ], [ [[VSTH64IP_M92:%.*]], %[[TAIL_CASE_6]] ], [ [[VSTH64IP_M113:%.*]], %[[TAIL_CASE_7]] ]
; CHECK-NEXT:    [[TMP34:%.*]] = and i32 [[SIZE]], 8
; CHECK-NEXT:    [[TMP35:%.*]] = icmp eq i32 [[TMP34]], 0
; CHECK-NEXT:    br i1 [[TMP35]], label %[[AFTER_8B_TAIL:.*]], label %[[HANDLE_8B_TAIL:.*]]
; CHECK:       [[INVALID_SWITCH_TRAP]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[HANDLE_8B_TAIL]]:
; CHECK-NEXT:    [[VLDL64IP_M114:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_TAIL]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M114]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M114]], 1
; CHECK-NEXT:    [[VSTL64IP_M115:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP36]], ptr [[DST_PTR_TAIL]], i32 8)
; CHECK-NEXT:    br label %[[AFTER_8B_TAIL]]
; CHECK:       [[AFTER_8B_TAIL]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_8B:%.*]] = phi ptr [ [[SRC_PTR_TAIL]], %[[HANDLE_TAIL_SWITCH]] ], [ [[TMP37]], %[[HANDLE_8B_TAIL]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_8B:%.*]] = phi ptr [ [[DST_PTR_TAIL]], %[[HANDLE_TAIL_SWITCH]] ], [ [[VSTL64IP_M115]], %[[HANDLE_8B_TAIL]] ]
; CHECK-NEXT:    [[TMP38:%.*]] = icmp eq i32 [[REMAINING_BYTES]], 0
; CHECK-NEXT:    br i1 [[TMP38]], label %[[RETURN]], label %[[HANDLE_REMAINING_BYTES:.*]]
; CHECK:       [[TAIL_CASE_1]]:
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP40]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[TMP41:%.*]] = shufflevector <16 x i8> [[TMP39]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP42:%.*]] = shufflevector <16 x i8> [[TMP39]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M31:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP41]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M32]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP42]], ptr [[VSTL64IP_M31]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_2]]:
; CHECK-NEXT:    [[VLD128IP_M33:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M33]], 0
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M33]], 1
; CHECK-NEXT:    [[VLD128IP_M34:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP44]], i32 16)
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M34]], 0
; CHECK-NEXT:    [[TMP46]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M34]], 1
; CHECK-NEXT:    [[TMP47:%.*]] = shufflevector <16 x i8> [[TMP43]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP48:%.*]] = shufflevector <16 x i8> [[TMP43]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M35:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP47]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M36:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP48]], ptr [[VSTL64IP_M35]], i32 8)
; CHECK-NEXT:    [[TMP49:%.*]] = shufflevector <16 x i8> [[TMP45]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP50:%.*]] = shufflevector <16 x i8> [[TMP45]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M37:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP49]], ptr [[VSTH64IP_M36]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M38]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M37]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_3]]:
; CHECK-NEXT:    [[VLD128IP_M39:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M39]], 0
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M39]], 1
; CHECK-NEXT:    [[VLD128IP_M40:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP52]], i32 16)
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M40]], 0
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M40]], 1
; CHECK-NEXT:    [[VLD128IP_M41:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP54]], i32 16)
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M41]], 0
; CHECK-NEXT:    [[TMP56]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M41]], 1
; CHECK-NEXT:    [[TMP57:%.*]] = shufflevector <16 x i8> [[TMP51]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP58:%.*]] = shufflevector <16 x i8> [[TMP51]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M42:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP57]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M43:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M42]], i32 8)
; CHECK-NEXT:    [[TMP59:%.*]] = shufflevector <16 x i8> [[TMP53]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP60:%.*]] = shufflevector <16 x i8> [[TMP53]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M44:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP59]], ptr [[VSTH64IP_M43]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP60]], ptr [[VSTL64IP_M44]], i32 8)
; CHECK-NEXT:    [[TMP61:%.*]] = shufflevector <16 x i8> [[TMP55]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP62:%.*]] = shufflevector <16 x i8> [[TMP55]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP61]], ptr [[VSTH64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M47]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP62]], ptr [[VSTL64IP_M46]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_4]]:
; CHECK-NEXT:    [[VLD128IP_M48:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 0
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 1
; CHECK-NEXT:    [[VLD128IP_M49:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP64]], i32 16)
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 0
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 1
; CHECK-NEXT:    [[VLD128IP_M50:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP66]], i32 16)
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 0
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 1
; CHECK-NEXT:    [[VLD128IP_M51:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP68]], i32 16)
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 0
; CHECK-NEXT:    [[TMP70]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 1
; CHECK-NEXT:    [[TMP71:%.*]] = shufflevector <16 x i8> [[TMP63]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP72:%.*]] = shufflevector <16 x i8> [[TMP63]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP71]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP72]], ptr [[VSTL64IP_M52]], i32 8)
; CHECK-NEXT:    [[TMP73:%.*]] = shufflevector <16 x i8> [[TMP65]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP74:%.*]] = shufflevector <16 x i8> [[TMP65]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP73]], ptr [[VSTH64IP_M53]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP74]], ptr [[VSTL64IP_M54]], i32 8)
; CHECK-NEXT:    [[TMP75:%.*]] = shufflevector <16 x i8> [[TMP67]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP76:%.*]] = shufflevector <16 x i8> [[TMP67]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP75]], ptr [[VSTH64IP_M55]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP76]], ptr [[VSTL64IP_M56]], i32 8)
; CHECK-NEXT:    [[TMP77:%.*]] = shufflevector <16 x i8> [[TMP69]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP78:%.*]] = shufflevector <16 x i8> [[TMP69]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP77]], ptr [[VSTH64IP_M57]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M59]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP78]], ptr [[VSTL64IP_M58]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_5]]:
; CHECK-NEXT:    [[VLD128IP_M60:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M60]], 0
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M60]], 1
; CHECK-NEXT:    [[VLD128IP_M61:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP80]], i32 16)
; CHECK-NEXT:    [[TMP81:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M61]], 0
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M61]], 1
; CHECK-NEXT:    [[VLD128IP_M62:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP82]], i32 16)
; CHECK-NEXT:    [[TMP83:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M62]], 0
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M62]], 1
; CHECK-NEXT:    [[VLD128IP_M63:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP84]], i32 16)
; CHECK-NEXT:    [[TMP85:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M63]], 0
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M63]], 1
; CHECK-NEXT:    [[TMP87:%.*]] = shufflevector <16 x i8> [[TMP79]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP88:%.*]] = shufflevector <16 x i8> [[TMP79]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M64:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP87]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M65:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP88]], ptr [[VSTL64IP_M64]], i32 8)
; CHECK-NEXT:    [[TMP89:%.*]] = shufflevector <16 x i8> [[TMP81]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP90:%.*]] = shufflevector <16 x i8> [[TMP81]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M66:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP89]], ptr [[VSTH64IP_M65]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M67:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP90]], ptr [[VSTL64IP_M66]], i32 8)
; CHECK-NEXT:    [[TMP91:%.*]] = shufflevector <16 x i8> [[TMP83]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP92:%.*]] = shufflevector <16 x i8> [[TMP83]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M68:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP91]], ptr [[VSTH64IP_M67]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M69:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP92]], ptr [[VSTL64IP_M68]], i32 8)
; CHECK-NEXT:    [[TMP93:%.*]] = shufflevector <16 x i8> [[TMP85]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP94:%.*]] = shufflevector <16 x i8> [[TMP85]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M70:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP93]], ptr [[VSTH64IP_M69]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M71:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP94]], ptr [[VSTL64IP_M70]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M72:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP86]], i32 16)
; CHECK-NEXT:    [[TMP95:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M72]], 0
; CHECK-NEXT:    [[TMP96]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M72]], 1
; CHECK-NEXT:    [[TMP97:%.*]] = shufflevector <16 x i8> [[TMP95]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP98:%.*]] = shufflevector <16 x i8> [[TMP95]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M73:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP97]], ptr [[VSTH64IP_M71]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M74]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP98]], ptr [[VSTL64IP_M73]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_6]]:
; CHECK-NEXT:    [[VLD128IP_M75:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M75]], 0
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M75]], 1
; CHECK-NEXT:    [[VLD128IP_M76:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP100]], i32 16)
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M76]], 0
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M76]], 1
; CHECK-NEXT:    [[VLD128IP_M77:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP102]], i32 16)
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M77]], 0
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M77]], 1
; CHECK-NEXT:    [[VLD128IP_M78:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP104]], i32 16)
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M78]], 0
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M78]], 1
; CHECK-NEXT:    [[TMP107:%.*]] = shufflevector <16 x i8> [[TMP99]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP108:%.*]] = shufflevector <16 x i8> [[TMP99]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M79:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP107]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP108]], ptr [[VSTL64IP_M79]], i32 8)
; CHECK-NEXT:    [[TMP109:%.*]] = shufflevector <16 x i8> [[TMP101]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP110:%.*]] = shufflevector <16 x i8> [[TMP101]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M81:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP109]], ptr [[VSTH64IP_M80]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M82:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP110]], ptr [[VSTL64IP_M81]], i32 8)
; CHECK-NEXT:    [[TMP111:%.*]] = shufflevector <16 x i8> [[TMP103]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP112:%.*]] = shufflevector <16 x i8> [[TMP103]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M83:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP111]], ptr [[VSTH64IP_M82]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M84:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP112]], ptr [[VSTL64IP_M83]], i32 8)
; CHECK-NEXT:    [[TMP113:%.*]] = shufflevector <16 x i8> [[TMP105]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP114:%.*]] = shufflevector <16 x i8> [[TMP105]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M85:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP113]], ptr [[VSTH64IP_M84]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M86:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP114]], ptr [[VSTL64IP_M85]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M87:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP106]], i32 16)
; CHECK-NEXT:    [[TMP115:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M87]], 0
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M87]], 1
; CHECK-NEXT:    [[VLD128IP_M88:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP116]], i32 16)
; CHECK-NEXT:    [[TMP117:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M88]], 0
; CHECK-NEXT:    [[TMP118]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M88]], 1
; CHECK-NEXT:    [[TMP119:%.*]] = shufflevector <16 x i8> [[TMP115]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP120:%.*]] = shufflevector <16 x i8> [[TMP115]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP119]], ptr [[VSTH64IP_M86]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M90:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP120]], ptr [[VSTL64IP_M89]], i32 8)
; CHECK-NEXT:    [[TMP121:%.*]] = shufflevector <16 x i8> [[TMP117]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP122:%.*]] = shufflevector <16 x i8> [[TMP117]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M91:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP121]], ptr [[VSTH64IP_M90]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M92]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP122]], ptr [[VSTL64IP_M91]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_7]]:
; CHECK-NEXT:    [[VLD128IP_M93:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 16)
; CHECK-NEXT:    [[TMP123:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M93]], 0
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M93]], 1
; CHECK-NEXT:    [[VLD128IP_M94:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP124]], i32 16)
; CHECK-NEXT:    [[TMP125:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M94]], 0
; CHECK-NEXT:    [[TMP126:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M94]], 1
; CHECK-NEXT:    [[VLD128IP_M95:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP126]], i32 16)
; CHECK-NEXT:    [[TMP127:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 0
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 1
; CHECK-NEXT:    [[VLD128IP_M96:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP128]], i32 16)
; CHECK-NEXT:    [[TMP129:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 0
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 1
; CHECK-NEXT:    [[TMP131:%.*]] = shufflevector <16 x i8> [[TMP123]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP132:%.*]] = shufflevector <16 x i8> [[TMP123]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M97:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP131]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M98:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP132]], ptr [[VSTL64IP_M97]], i32 8)
; CHECK-NEXT:    [[TMP133:%.*]] = shufflevector <16 x i8> [[TMP125]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP134:%.*]] = shufflevector <16 x i8> [[TMP125]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M99:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP133]], ptr [[VSTH64IP_M98]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M100:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP134]], ptr [[VSTL64IP_M99]], i32 8)
; CHECK-NEXT:    [[TMP135:%.*]] = shufflevector <16 x i8> [[TMP127]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP136:%.*]] = shufflevector <16 x i8> [[TMP127]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M101:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP135]], ptr [[VSTH64IP_M100]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M102:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP136]], ptr [[VSTL64IP_M101]], i32 8)
; CHECK-NEXT:    [[TMP137:%.*]] = shufflevector <16 x i8> [[TMP129]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP138:%.*]] = shufflevector <16 x i8> [[TMP129]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M103:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP137]], ptr [[VSTH64IP_M102]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M104:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP138]], ptr [[VSTL64IP_M103]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M105:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP130]], i32 16)
; CHECK-NEXT:    [[TMP139:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M105]], 0
; CHECK-NEXT:    [[TMP140:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M105]], 1
; CHECK-NEXT:    [[VLD128IP_M106:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP140]], i32 16)
; CHECK-NEXT:    [[TMP141:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M106]], 0
; CHECK-NEXT:    [[TMP142:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M106]], 1
; CHECK-NEXT:    [[VLD128IP_M107:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[TMP142]], i32 16)
; CHECK-NEXT:    [[TMP143:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M107]], 0
; CHECK-NEXT:    [[TMP144]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M107]], 1
; CHECK-NEXT:    [[TMP145:%.*]] = shufflevector <16 x i8> [[TMP139]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP146:%.*]] = shufflevector <16 x i8> [[TMP139]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M108:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP145]], ptr [[VSTH64IP_M104]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M109:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP146]], ptr [[VSTL64IP_M108]], i32 8)
; CHECK-NEXT:    [[TMP147:%.*]] = shufflevector <16 x i8> [[TMP141]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP148:%.*]] = shufflevector <16 x i8> [[TMP141]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M110:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP147]], ptr [[VSTH64IP_M109]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M111:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP148]], ptr [[VSTL64IP_M110]], i32 8)
; CHECK-NEXT:    [[TMP149:%.*]] = shufflevector <16 x i8> [[TMP143]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP150:%.*]] = shufflevector <16 x i8> [[TMP143]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M112:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP149]], ptr [[VSTH64IP_M111]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M113]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP150]], ptr [[VSTL64IP_M112]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[HANDLE_REMAINING_BYTES]]:
; CHECK-NEXT:    call void @esp32p4MemCpySrc16Dst8From1To7Opt(ptr [[DST_PTR_AFTER_8B]], ptr [[SRC_PTR_AFTER_8B]], i32 [[REMAINING_BYTES]])
; CHECK-NEXT:    br label %[[RETURN]]
;
;
; CHECK-LABEL: define internal void @esp32p4MemCpySrc8Dst16Var(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[IS_LT_8:%.*]] = icmp ult i32 [[SIZE]], 8
; CHECK-NEXT:    br i1 [[IS_LT_8]], label %[[HANDLE_SMALL_SIZE:.*]], label %[[CHECK_MID_RANGE:.*]]
; CHECK:       [[HANDLE_SMALL_SIZE]]:
; CHECK-NEXT:    call void @esp32p4MemCpySrc8Dst16From1To7Opt(ptr [[DST]], ptr [[SRC]], i32 [[SIZE]])
; CHECK-NEXT:    br label %[[RETURN:.*]]
; CHECK:       [[CHECK_MID_RANGE]]:
; CHECK-NEXT:    [[IS_LT_16:%.*]] = icmp ult i32 [[SIZE]], 16
; CHECK-NEXT:    br i1 [[IS_LT_16]], label %[[HANDLE_MID_SIZE:.*]], label %[[HANDLE_LARGE_LOOP:.*]]
; CHECK:       [[HANDLE_MID_SIZE]]:
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP0]], ptr [[DST]], i32 8)
; CHECK-NEXT:    [[SIZE_MINUS_8:%.*]] = add nsw i32 [[SIZE]], -8
; CHECK-NEXT:    call void @esp32p4MemCpySrc8Dst16From1To7Opt(ptr [[VSTL64IP_M]], ptr [[TMP1]], i32 [[SIZE_MINUS_8]])
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[HANDLE_LARGE_LOOP]]:
; CHECK-NEXT:    [[NUM_128B_BLOCKS:%.*]] = lshr i32 [[SIZE]], 7
; CHECK-NEXT:    [[NUM_16B_BLOCKS:%.*]] = lshr i32 [[SIZE]], 4
; CHECK-NEXT:    [[REMAINING_16B_BLOCKS:%.*]] = and i32 [[NUM_16B_BLOCKS]], 7
; CHECK-NEXT:    [[REMAINING_BYTES:%.*]] = and i32 [[SIZE]], 7
; CHECK-NEXT:    [[IS_LT_128:%.*]] = icmp ult i32 [[SIZE]], 128
; CHECK-NEXT:    br i1 [[IS_LT_128]], label %[[LOOP_EXIT_CLEANUP:.*]], label %[[LOOP_BODY_128B:.*]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[LOOP_EXIT_CLEANUP]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_LOOP:%.*]] = phi ptr [ [[SRC]], %[[HANDLE_LARGE_LOOP]] ], [ [[TMP33:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_LOOP:%.*]] = phi ptr [ [[DST]], %[[HANDLE_LARGE_LOOP]] ], [ [[VSTH64IP_M30:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    switch i32 [[REMAINING_16B_BLOCKS]], label %[[INVALID_SWITCH_TRAP:.*]] [
; CHECK-NEXT:      i32 1, label %[[TAIL_CASE_1:.*]]
; CHECK-NEXT:      i32 2, label %[[TAIL_CASE_2:.*]]
; CHECK-NEXT:      i32 3, label %[[TAIL_CASE_3:.*]]
; CHECK-NEXT:      i32 4, label %[[TAIL_CASE_4:.*]]
; CHECK-NEXT:      i32 5, label %[[TAIL_CASE_5:.*]]
; CHECK-NEXT:      i32 6, label %[[TAIL_CASE_6:.*]]
; CHECK-NEXT:      i32 7, label %[[TAIL_CASE_7:.*]]
; CHECK-NEXT:      i32 0, label %[[HANDLE_TAIL_SWITCH:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[LOOP_BODY_128B]]:
; CHECK-NEXT:    [[LOOP_INDEX:%.*]] = phi i32 [ 0, %[[HANDLE_LARGE_LOOP]] ], [ [[LOOP_INC:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[SRC_PTR_LOOP:%.*]] = phi ptr [ [[SRC]], %[[HANDLE_LARGE_LOOP]] ], [ [[TMP33]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[DST_PTR_LOOP:%.*]] = phi ptr [ [[DST]], %[[HANDLE_LARGE_LOOP]] ], [ [[VSTH64IP_M30]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M2]], 1
; CHECK-NEXT:    [[VLDH64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M3]], 1
; CHECK-NEXT:    [[VLDL64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 1
; CHECK-NEXT:    [[VLDH64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M5]], 1
; CHECK-NEXT:    [[VLDL64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M6]], 1
; CHECK-NEXT:    [[VLDH64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M7]], 1
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP2]], ptr [[DST_PTR_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP4]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP6]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP8]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP10]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP12]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP14]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M15:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M15]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M15]], 1
; CHECK-NEXT:    [[VLDH64IP_M16:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M16]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M16]], 1
; CHECK-NEXT:    [[VLDL64IP_M17:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M17]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M17]], 1
; CHECK-NEXT:    [[VLDH64IP_M18:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M18]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M18]], 1
; CHECK-NEXT:    [[VLDL64IP_M19:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M19]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M19]], 1
; CHECK-NEXT:    [[VLDH64IP_M20:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M20]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M20]], 1
; CHECK-NEXT:    [[VLDL64IP_M21:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 1
; CHECK-NEXT:    [[VLDH64IP_M22:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M22]], 0
; CHECK-NEXT:    [[TMP33]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M22]], 1
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP18]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP20]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP22]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP24]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP26]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP28]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M29:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP30]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M30]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP32]], ptr [[VSTL64IP_M29]], i32 8)
; CHECK-NEXT:    [[LOOP_INC]] = add nuw nsw i32 [[LOOP_INDEX]], 1
; CHECK-NEXT:    [[LOOP_DONE:%.*]] = icmp eq i32 [[LOOP_INC]], [[NUM_128B_BLOCKS]]
; CHECK-NEXT:    br i1 [[LOOP_DONE]], label %[[LOOP_EXIT_CLEANUP]], label %[[LOOP_BODY_128B]]
; CHECK:       [[HANDLE_TAIL_SWITCH]]:
; CHECK-NEXT:    [[SRC_PTR_TAIL:%.*]] = phi ptr [ [[SRC_PTR_AFTER_LOOP]], %[[LOOP_EXIT_CLEANUP]] ], [ [[TMP42:%.*]], %[[TAIL_CASE_1]] ], [ [[TMP50:%.*]], %[[TAIL_CASE_2]] ], [ [[TMP62:%.*]], %[[TAIL_CASE_3]] ], [ [[TMP78:%.*]], %[[TAIL_CASE_4]] ], [ [[TMP98:%.*]], %[[TAIL_CASE_5]] ], [ [[TMP122:%.*]], %[[TAIL_CASE_6]] ], [ [[TMP150:%.*]], %[[TAIL_CASE_7]] ]
; CHECK-NEXT:    [[DST_PTR_TAIL:%.*]] = phi ptr [ [[DST_PTR_AFTER_LOOP]], %[[LOOP_EXIT_CLEANUP]] ], [ [[VSTH64IP_M34:%.*]], %[[TAIL_CASE_1]] ], [ [[VSTH64IP_M42:%.*]], %[[TAIL_CASE_2]] ], [ [[VSTH64IP_M54:%.*]], %[[TAIL_CASE_3]] ], [ [[VSTH64IP_M70:%.*]], %[[TAIL_CASE_4]] ], [ [[VSTH64IP_M90:%.*]], %[[TAIL_CASE_5]] ], [ [[VSTH64IP_M114:%.*]], %[[TAIL_CASE_6]] ], [ [[VSTH64IP_M142:%.*]], %[[TAIL_CASE_7]] ]
; CHECK-NEXT:    [[TMP34:%.*]] = and i32 [[SIZE]], 8
; CHECK-NEXT:    [[TMP35:%.*]] = icmp eq i32 [[TMP34]], 0
; CHECK-NEXT:    br i1 [[TMP35]], label %[[AFTER_8B_TAIL:.*]], label %[[HANDLE_8B_TAIL:.*]]
; CHECK:       [[INVALID_SWITCH_TRAP]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[HANDLE_8B_TAIL]]:
; CHECK-NEXT:    [[VLDL64IP_M143:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_TAIL]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M143]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M143]], 1
; CHECK-NEXT:    [[VSTL64IP_M144:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP36]], ptr [[DST_PTR_TAIL]], i32 8)
; CHECK-NEXT:    br label %[[AFTER_8B_TAIL]]
; CHECK:       [[AFTER_8B_TAIL]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_8B:%.*]] = phi ptr [ [[SRC_PTR_TAIL]], %[[HANDLE_TAIL_SWITCH]] ], [ [[TMP37]], %[[HANDLE_8B_TAIL]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_8B:%.*]] = phi ptr [ [[DST_PTR_TAIL]], %[[HANDLE_TAIL_SWITCH]] ], [ [[VSTL64IP_M144]], %[[HANDLE_8B_TAIL]] ]
; CHECK-NEXT:    [[TMP38:%.*]] = icmp eq i32 [[REMAINING_BYTES]], 0
; CHECK-NEXT:    br i1 [[TMP38]], label %[[RETURN]], label %[[HANDLE_REMAINING_BYTES:.*]]
; CHECK:       [[TAIL_CASE_1]]:
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP40]], i32 8)
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP42]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VSTL64IP_M33:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP39]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M34]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP41]], ptr [[VSTL64IP_M33]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_2]]:
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP44]], i32 8)
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP46]], i32 8)
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP48]], i32 8)
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP50]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VSTL64IP_M39:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP43]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M40:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP45]], ptr [[VSTL64IP_M39]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M41:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP47]], ptr [[VSTH64IP_M40]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M42]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP49]], ptr [[VSTL64IP_M41]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_3]]:
; CHECK-NEXT:    [[VLDL64IP_M43:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 0
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 1
; CHECK-NEXT:    [[VLDH64IP_M44:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP52]], i32 8)
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 0
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 1
; CHECK-NEXT:    [[VLDL64IP_M45:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP54]], i32 8)
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M45]], 0
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M45]], 1
; CHECK-NEXT:    [[VLDH64IP_M46:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP56]], i32 8)
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M46]], 0
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M46]], 1
; CHECK-NEXT:    [[VLDL64IP_M47:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP58]], i32 8)
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M47]], 0
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M47]], 1
; CHECK-NEXT:    [[VLDH64IP_M48:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP60]], i32 8)
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M48]], 0
; CHECK-NEXT:    [[TMP62]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M48]], 1
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP51]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP53]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP55]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP57]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP59]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP61]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_4]]:
; CHECK-NEXT:    [[VLDL64IP_M55:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M55]], 0
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M55]], 1
; CHECK-NEXT:    [[VLDH64IP_M56:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP64]], i32 8)
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M56]], 0
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M56]], 1
; CHECK-NEXT:    [[VLDL64IP_M57:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP66]], i32 8)
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M57]], 0
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M57]], 1
; CHECK-NEXT:    [[VLDH64IP_M58:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP68]], i32 8)
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M58]], 0
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M58]], 1
; CHECK-NEXT:    [[VLDL64IP_M59:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP70]], i32 8)
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M59]], 0
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M59]], 1
; CHECK-NEXT:    [[VLDH64IP_M60:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP72]], i32 8)
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M60]], 0
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M60]], 1
; CHECK-NEXT:    [[VLDL64IP_M61:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP74]], i32 8)
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 0
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 1
; CHECK-NEXT:    [[VLDH64IP_M62:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP76]], i32 8)
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 0
; CHECK-NEXT:    [[TMP78]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 1
; CHECK-NEXT:    [[VSTL64IP_M63:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP63]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M64:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP65]], ptr [[VSTL64IP_M63]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M65:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP67]], ptr [[VSTH64IP_M64]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M66:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP69]], ptr [[VSTL64IP_M65]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M67:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP71]], ptr [[VSTH64IP_M66]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M68:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP73]], ptr [[VSTL64IP_M67]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M69:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP75]], ptr [[VSTH64IP_M68]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M70]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP77]], ptr [[VSTL64IP_M69]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_5]]:
; CHECK-NEXT:    [[VLDL64IP_M71:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 0
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 1
; CHECK-NEXT:    [[VLDH64IP_M72:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP80]], i32 8)
; CHECK-NEXT:    [[TMP81:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 0
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 1
; CHECK-NEXT:    [[VLDL64IP_M73:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP82]], i32 8)
; CHECK-NEXT:    [[TMP83:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 0
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 1
; CHECK-NEXT:    [[VLDH64IP_M74:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP84]], i32 8)
; CHECK-NEXT:    [[TMP85:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 0
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 1
; CHECK-NEXT:    [[VLDL64IP_M75:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP86]], i32 8)
; CHECK-NEXT:    [[TMP87:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 0
; CHECK-NEXT:    [[TMP88:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 1
; CHECK-NEXT:    [[VLDH64IP_M76:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP88]], i32 8)
; CHECK-NEXT:    [[TMP89:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 0
; CHECK-NEXT:    [[TMP90:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 1
; CHECK-NEXT:    [[VLDL64IP_M77:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP90]], i32 8)
; CHECK-NEXT:    [[TMP91:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M77]], 0
; CHECK-NEXT:    [[TMP92:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M77]], 1
; CHECK-NEXT:    [[VLDH64IP_M78:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP92]], i32 8)
; CHECK-NEXT:    [[TMP93:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M78]], 0
; CHECK-NEXT:    [[TMP94:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M78]], 1
; CHECK-NEXT:    [[VSTL64IP_M79:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP79]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP81]], ptr [[VSTL64IP_M79]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M81:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP83]], ptr [[VSTH64IP_M80]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M82:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP85]], ptr [[VSTL64IP_M81]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M83:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP87]], ptr [[VSTH64IP_M82]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M84:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP89]], ptr [[VSTL64IP_M83]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M85:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP91]], ptr [[VSTH64IP_M84]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M86:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP93]], ptr [[VSTL64IP_M85]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M87:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP94]], i32 8)
; CHECK-NEXT:    [[TMP95:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M87]], 0
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M87]], 1
; CHECK-NEXT:    [[VLDH64IP_M88:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP96]], i32 8)
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M88]], 0
; CHECK-NEXT:    [[TMP98]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M88]], 1
; CHECK-NEXT:    [[VSTL64IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP95]], ptr [[VSTH64IP_M86]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M90]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP97]], ptr [[VSTL64IP_M89]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_6]]:
; CHECK-NEXT:    [[VLDL64IP_M91:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M91]], 0
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M91]], 1
; CHECK-NEXT:    [[VLDH64IP_M92:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP100]], i32 8)
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M92]], 0
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M92]], 1
; CHECK-NEXT:    [[VLDL64IP_M93:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP102]], i32 8)
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 0
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 1
; CHECK-NEXT:    [[VLDH64IP_M94:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP104]], i32 8)
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 0
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 1
; CHECK-NEXT:    [[VLDL64IP_M95:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP106]], i32 8)
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 0
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 1
; CHECK-NEXT:    [[VLDH64IP_M96:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP108]], i32 8)
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 0
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 1
; CHECK-NEXT:    [[VLDL64IP_M97:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP110]], i32 8)
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 0
; CHECK-NEXT:    [[TMP112:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 1
; CHECK-NEXT:    [[VLDH64IP_M98:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP112]], i32 8)
; CHECK-NEXT:    [[TMP113:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 0
; CHECK-NEXT:    [[TMP114:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 1
; CHECK-NEXT:    [[VSTL64IP_M99:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP99]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M100:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP101]], ptr [[VSTL64IP_M99]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M101:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP103]], ptr [[VSTH64IP_M100]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M102:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP105]], ptr [[VSTL64IP_M101]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M103:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP107]], ptr [[VSTH64IP_M102]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M104:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP109]], ptr [[VSTL64IP_M103]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M105:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP111]], ptr [[VSTH64IP_M104]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M106:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP113]], ptr [[VSTL64IP_M105]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M107:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP114]], i32 8)
; CHECK-NEXT:    [[TMP115:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 0
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 1
; CHECK-NEXT:    [[VLDH64IP_M108:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP116]], i32 8)
; CHECK-NEXT:    [[TMP117:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 0
; CHECK-NEXT:    [[TMP118:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 1
; CHECK-NEXT:    [[VLDL64IP_M109:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP118]], i32 8)
; CHECK-NEXT:    [[TMP119:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M109]], 0
; CHECK-NEXT:    [[TMP120:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M109]], 1
; CHECK-NEXT:    [[VLDH64IP_M110:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP120]], i32 8)
; CHECK-NEXT:    [[TMP121:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M110]], 0
; CHECK-NEXT:    [[TMP122]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M110]], 1
; CHECK-NEXT:    [[VSTL64IP_M111:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP115]], ptr [[VSTH64IP_M106]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M112:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP117]], ptr [[VSTL64IP_M111]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M113:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP119]], ptr [[VSTH64IP_M112]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M114]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP121]], ptr [[VSTL64IP_M113]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_7]]:
; CHECK-NEXT:    [[VLDL64IP_M115:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP123:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M115]], 0
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M115]], 1
; CHECK-NEXT:    [[VLDH64IP_M116:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP124]], i32 8)
; CHECK-NEXT:    [[TMP125:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M116]], 0
; CHECK-NEXT:    [[TMP126:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M116]], 1
; CHECK-NEXT:    [[VLDL64IP_M117:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP126]], i32 8)
; CHECK-NEXT:    [[TMP127:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M117]], 0
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M117]], 1
; CHECK-NEXT:    [[VLDH64IP_M118:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP128]], i32 8)
; CHECK-NEXT:    [[TMP129:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M118]], 0
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M118]], 1
; CHECK-NEXT:    [[VLDL64IP_M119:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP130]], i32 8)
; CHECK-NEXT:    [[TMP131:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M119]], 0
; CHECK-NEXT:    [[TMP132:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M119]], 1
; CHECK-NEXT:    [[VLDH64IP_M120:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP132]], i32 8)
; CHECK-NEXT:    [[TMP133:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M120]], 0
; CHECK-NEXT:    [[TMP134:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M120]], 1
; CHECK-NEXT:    [[VLDL64IP_M121:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP134]], i32 8)
; CHECK-NEXT:    [[TMP135:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M121]], 0
; CHECK-NEXT:    [[TMP136:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M121]], 1
; CHECK-NEXT:    [[VLDH64IP_M122:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP136]], i32 8)
; CHECK-NEXT:    [[TMP137:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M122]], 0
; CHECK-NEXT:    [[TMP138:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M122]], 1
; CHECK-NEXT:    [[VSTL64IP_M123:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP123]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M124:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP125]], ptr [[VSTL64IP_M123]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M125:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP127]], ptr [[VSTH64IP_M124]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M126:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP129]], ptr [[VSTL64IP_M125]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M127:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP131]], ptr [[VSTH64IP_M126]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M128:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP133]], ptr [[VSTL64IP_M127]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M129:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP135]], ptr [[VSTH64IP_M128]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M130:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP137]], ptr [[VSTL64IP_M129]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M131:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP138]], i32 8)
; CHECK-NEXT:    [[TMP139:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 0
; CHECK-NEXT:    [[TMP140:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 1
; CHECK-NEXT:    [[VLDH64IP_M132:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP140]], i32 8)
; CHECK-NEXT:    [[TMP141:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 0
; CHECK-NEXT:    [[TMP142:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 1
; CHECK-NEXT:    [[VLDL64IP_M133:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP142]], i32 8)
; CHECK-NEXT:    [[TMP143:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 0
; CHECK-NEXT:    [[TMP144:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 1
; CHECK-NEXT:    [[VLDH64IP_M134:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP144]], i32 8)
; CHECK-NEXT:    [[TMP145:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 0
; CHECK-NEXT:    [[TMP146:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 1
; CHECK-NEXT:    [[VLDL64IP_M135:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP146]], i32 8)
; CHECK-NEXT:    [[TMP147:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 0
; CHECK-NEXT:    [[TMP148:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 1
; CHECK-NEXT:    [[VLDH64IP_M136:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP148]], i32 8)
; CHECK-NEXT:    [[TMP149:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 0
; CHECK-NEXT:    [[TMP150]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 1
; CHECK-NEXT:    [[VSTL64IP_M137:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP139]], ptr [[VSTH64IP_M130]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M138:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP141]], ptr [[VSTL64IP_M137]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M139:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP143]], ptr [[VSTH64IP_M138]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M140:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP145]], ptr [[VSTL64IP_M139]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M141:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP147]], ptr [[VSTH64IP_M140]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M142]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP149]], ptr [[VSTL64IP_M141]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[HANDLE_REMAINING_BYTES]]:
; CHECK-NEXT:    call void @esp32p4MemCpySrc8Dst16From1To7Opt(ptr [[DST_PTR_AFTER_8B]], ptr [[SRC_PTR_AFTER_8B]], i32 [[REMAINING_BYTES]])
; CHECK-NEXT:    br label %[[RETURN]]
;
;
; CHECK-LABEL: define internal void @esp32p4MemCpySrc8Dst8Var(
; CHECK-SAME: ptr [[DST:%.*]], ptr [[SRC:%.*]], i32 [[SIZE:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[IS_LT_8:%.*]] = icmp ult i32 [[SIZE]], 8
; CHECK-NEXT:    br i1 [[IS_LT_8]], label %[[HANDLE_SMALL_SIZE:.*]], label %[[CHECK_MID_RANGE:.*]]
; CHECK:       [[HANDLE_SMALL_SIZE]]:
; CHECK-NEXT:    call void @esp32p4MemCpySrc8Dst8From1To7Opt(ptr [[DST]], ptr [[SRC]], i32 [[SIZE]])
; CHECK-NEXT:    br label %[[RETURN:.*]]
; CHECK:       [[CHECK_MID_RANGE]]:
; CHECK-NEXT:    [[IS_LT_16:%.*]] = icmp ult i32 [[SIZE]], 16
; CHECK-NEXT:    br i1 [[IS_LT_16]], label %[[HANDLE_MID_SIZE:.*]], label %[[HANDLE_LARGE_LOOP:.*]]
; CHECK:       [[HANDLE_MID_SIZE]]:
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP0]], ptr [[DST]], i32 8)
; CHECK-NEXT:    [[SIZE_MINUS_8:%.*]] = add nsw i32 [[SIZE]], -8
; CHECK-NEXT:    call void @esp32p4MemCpySrc8Dst8From1To7Opt(ptr [[VSTL64IP_M]], ptr [[TMP1]], i32 [[SIZE_MINUS_8]])
; CHECK-NEXT:    br label %[[RETURN]]
; CHECK:       [[HANDLE_LARGE_LOOP]]:
; CHECK-NEXT:    [[NUM_128B_BLOCKS:%.*]] = lshr i32 [[SIZE]], 7
; CHECK-NEXT:    [[NUM_16B_BLOCKS:%.*]] = lshr i32 [[SIZE]], 4
; CHECK-NEXT:    [[REMAINING_16B_BLOCKS:%.*]] = and i32 [[NUM_16B_BLOCKS]], 7
; CHECK-NEXT:    [[REMAINING_BYTES:%.*]] = and i32 [[SIZE]], 7
; CHECK-NEXT:    [[IS_LT_128:%.*]] = icmp ult i32 [[SIZE]], 128
; CHECK-NEXT:    br i1 [[IS_LT_128]], label %[[LOOP_EXIT_CLEANUP:.*]], label %[[LOOP_BODY_128B:.*]]
; CHECK:       [[RETURN]]:
; CHECK-NEXT:    ret void
; CHECK:       [[LOOP_EXIT_CLEANUP]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_LOOP:%.*]] = phi ptr [ [[SRC]], %[[HANDLE_LARGE_LOOP]] ], [ [[TMP33:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_LOOP:%.*]] = phi ptr [ [[DST]], %[[HANDLE_LARGE_LOOP]] ], [ [[VSTH64IP_M30:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    switch i32 [[REMAINING_16B_BLOCKS]], label %[[INVALID_SWITCH_TRAP:.*]] [
; CHECK-NEXT:      i32 1, label %[[TAIL_CASE_1:.*]]
; CHECK-NEXT:      i32 2, label %[[TAIL_CASE_2:.*]]
; CHECK-NEXT:      i32 3, label %[[TAIL_CASE_3:.*]]
; CHECK-NEXT:      i32 4, label %[[TAIL_CASE_4:.*]]
; CHECK-NEXT:      i32 5, label %[[TAIL_CASE_5:.*]]
; CHECK-NEXT:      i32 6, label %[[TAIL_CASE_6:.*]]
; CHECK-NEXT:      i32 7, label %[[TAIL_CASE_7:.*]]
; CHECK-NEXT:      i32 0, label %[[HANDLE_TAIL_SWITCH:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[LOOP_BODY_128B]]:
; CHECK-NEXT:    [[LOOP_INDEX:%.*]] = phi i32 [ 0, %[[HANDLE_LARGE_LOOP]] ], [ [[LOOP_INC:%.*]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[SRC_PTR_LOOP:%.*]] = phi ptr [ [[SRC]], %[[HANDLE_LARGE_LOOP]] ], [ [[TMP33]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[DST_PTR_LOOP:%.*]] = phi ptr [ [[DST]], %[[HANDLE_LARGE_LOOP]] ], [ [[VSTH64IP_M30]], %[[LOOP_BODY_128B]] ]
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M2]], 1
; CHECK-NEXT:    [[VLDH64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M3]], 1
; CHECK-NEXT:    [[VLDL64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 1
; CHECK-NEXT:    [[VLDH64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M5]], 1
; CHECK-NEXT:    [[VLDL64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M6]], 1
; CHECK-NEXT:    [[VLDH64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M7]], 1
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP2]], ptr [[DST_PTR_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP4]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP6]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP8]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP10]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP12]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP14]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M15:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M15]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M15]], 1
; CHECK-NEXT:    [[VLDH64IP_M16:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M16]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M16]], 1
; CHECK-NEXT:    [[VLDL64IP_M17:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M17]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M17]], 1
; CHECK-NEXT:    [[VLDH64IP_M18:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M18]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M18]], 1
; CHECK-NEXT:    [[VLDL64IP_M19:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M19]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M19]], 1
; CHECK-NEXT:    [[VLDH64IP_M20:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M20]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M20]], 1
; CHECK-NEXT:    [[VLDL64IP_M21:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 1
; CHECK-NEXT:    [[VLDH64IP_M22:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M22]], 0
; CHECK-NEXT:    [[TMP33]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M22]], 1
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP18]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP20]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP22]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP24]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP26]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP28]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M29:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP30]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M30]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP32]], ptr [[VSTL64IP_M29]], i32 8)
; CHECK-NEXT:    [[LOOP_INC]] = add nuw nsw i32 [[LOOP_INDEX]], 1
; CHECK-NEXT:    [[LOOP_DONE:%.*]] = icmp eq i32 [[LOOP_INC]], [[NUM_128B_BLOCKS]]
; CHECK-NEXT:    br i1 [[LOOP_DONE]], label %[[LOOP_EXIT_CLEANUP]], label %[[LOOP_BODY_128B]]
; CHECK:       [[HANDLE_TAIL_SWITCH]]:
; CHECK-NEXT:    [[SRC_PTR_TAIL:%.*]] = phi ptr [ [[SRC_PTR_AFTER_LOOP]], %[[LOOP_EXIT_CLEANUP]] ], [ [[TMP42:%.*]], %[[TAIL_CASE_1]] ], [ [[TMP50:%.*]], %[[TAIL_CASE_2]] ], [ [[TMP62:%.*]], %[[TAIL_CASE_3]] ], [ [[TMP78:%.*]], %[[TAIL_CASE_4]] ], [ [[TMP98:%.*]], %[[TAIL_CASE_5]] ], [ [[TMP122:%.*]], %[[TAIL_CASE_6]] ], [ [[TMP150:%.*]], %[[TAIL_CASE_7]] ]
; CHECK-NEXT:    [[DST_PTR_TAIL:%.*]] = phi ptr [ [[DST_PTR_AFTER_LOOP]], %[[LOOP_EXIT_CLEANUP]] ], [ [[VSTH64IP_M34:%.*]], %[[TAIL_CASE_1]] ], [ [[VSTH64IP_M42:%.*]], %[[TAIL_CASE_2]] ], [ [[VSTH64IP_M54:%.*]], %[[TAIL_CASE_3]] ], [ [[VSTH64IP_M70:%.*]], %[[TAIL_CASE_4]] ], [ [[VSTH64IP_M90:%.*]], %[[TAIL_CASE_5]] ], [ [[VSTH64IP_M114:%.*]], %[[TAIL_CASE_6]] ], [ [[VSTH64IP_M142:%.*]], %[[TAIL_CASE_7]] ]
; CHECK-NEXT:    [[TMP34:%.*]] = and i32 [[SIZE]], 8
; CHECK-NEXT:    [[TMP35:%.*]] = icmp eq i32 [[TMP34]], 0
; CHECK-NEXT:    br i1 [[TMP35]], label %[[AFTER_8B_TAIL:.*]], label %[[HANDLE_8B_TAIL:.*]]
; CHECK:       [[INVALID_SWITCH_TRAP]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[HANDLE_8B_TAIL]]:
; CHECK-NEXT:    [[VLDL64IP_M143:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_TAIL]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M143]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M143]], 1
; CHECK-NEXT:    [[VSTL64IP_M144:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP36]], ptr [[DST_PTR_TAIL]], i32 8)
; CHECK-NEXT:    br label %[[AFTER_8B_TAIL]]
; CHECK:       [[AFTER_8B_TAIL]]:
; CHECK-NEXT:    [[SRC_PTR_AFTER_8B:%.*]] = phi ptr [ [[SRC_PTR_TAIL]], %[[HANDLE_TAIL_SWITCH]] ], [ [[TMP37]], %[[HANDLE_8B_TAIL]] ]
; CHECK-NEXT:    [[DST_PTR_AFTER_8B:%.*]] = phi ptr [ [[DST_PTR_TAIL]], %[[HANDLE_TAIL_SWITCH]] ], [ [[VSTL64IP_M144]], %[[HANDLE_8B_TAIL]] ]
; CHECK-NEXT:    [[TMP38:%.*]] = icmp eq i32 [[REMAINING_BYTES]], 0
; CHECK-NEXT:    br i1 [[TMP38]], label %[[RETURN]], label %[[HANDLE_REMAINING_BYTES:.*]]
; CHECK:       [[TAIL_CASE_1]]:
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP40]], i32 8)
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP42]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VSTL64IP_M33:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP39]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M34]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP41]], ptr [[VSTL64IP_M33]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_2]]:
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP44]], i32 8)
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP46]], i32 8)
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP48]], i32 8)
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP50]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VSTL64IP_M39:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP43]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M40:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP45]], ptr [[VSTL64IP_M39]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M41:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP47]], ptr [[VSTH64IP_M40]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M42]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP49]], ptr [[VSTL64IP_M41]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_3]]:
; CHECK-NEXT:    [[VLDL64IP_M43:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 0
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 1
; CHECK-NEXT:    [[VLDH64IP_M44:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP52]], i32 8)
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 0
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 1
; CHECK-NEXT:    [[VLDL64IP_M45:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP54]], i32 8)
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M45]], 0
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M45]], 1
; CHECK-NEXT:    [[VLDH64IP_M46:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP56]], i32 8)
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M46]], 0
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M46]], 1
; CHECK-NEXT:    [[VLDL64IP_M47:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP58]], i32 8)
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M47]], 0
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M47]], 1
; CHECK-NEXT:    [[VLDH64IP_M48:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP60]], i32 8)
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M48]], 0
; CHECK-NEXT:    [[TMP62]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M48]], 1
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP51]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP53]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP55]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP57]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP59]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP61]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_4]]:
; CHECK-NEXT:    [[VLDL64IP_M55:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M55]], 0
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M55]], 1
; CHECK-NEXT:    [[VLDH64IP_M56:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP64]], i32 8)
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M56]], 0
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M56]], 1
; CHECK-NEXT:    [[VLDL64IP_M57:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP66]], i32 8)
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M57]], 0
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M57]], 1
; CHECK-NEXT:    [[VLDH64IP_M58:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP68]], i32 8)
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M58]], 0
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M58]], 1
; CHECK-NEXT:    [[VLDL64IP_M59:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP70]], i32 8)
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M59]], 0
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M59]], 1
; CHECK-NEXT:    [[VLDH64IP_M60:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP72]], i32 8)
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M60]], 0
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M60]], 1
; CHECK-NEXT:    [[VLDL64IP_M61:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP74]], i32 8)
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 0
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 1
; CHECK-NEXT:    [[VLDH64IP_M62:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP76]], i32 8)
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 0
; CHECK-NEXT:    [[TMP78]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 1
; CHECK-NEXT:    [[VSTL64IP_M63:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP63]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M64:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP65]], ptr [[VSTL64IP_M63]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M65:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP67]], ptr [[VSTH64IP_M64]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M66:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP69]], ptr [[VSTL64IP_M65]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M67:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP71]], ptr [[VSTH64IP_M66]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M68:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP73]], ptr [[VSTL64IP_M67]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M69:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP75]], ptr [[VSTH64IP_M68]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M70]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP77]], ptr [[VSTL64IP_M69]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_5]]:
; CHECK-NEXT:    [[VLDL64IP_M71:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 0
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 1
; CHECK-NEXT:    [[VLDH64IP_M72:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP80]], i32 8)
; CHECK-NEXT:    [[TMP81:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 0
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 1
; CHECK-NEXT:    [[VLDL64IP_M73:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP82]], i32 8)
; CHECK-NEXT:    [[TMP83:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 0
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 1
; CHECK-NEXT:    [[VLDH64IP_M74:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP84]], i32 8)
; CHECK-NEXT:    [[TMP85:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 0
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 1
; CHECK-NEXT:    [[VLDL64IP_M75:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP86]], i32 8)
; CHECK-NEXT:    [[TMP87:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 0
; CHECK-NEXT:    [[TMP88:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 1
; CHECK-NEXT:    [[VLDH64IP_M76:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP88]], i32 8)
; CHECK-NEXT:    [[TMP89:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 0
; CHECK-NEXT:    [[TMP90:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 1
; CHECK-NEXT:    [[VLDL64IP_M77:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP90]], i32 8)
; CHECK-NEXT:    [[TMP91:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M77]], 0
; CHECK-NEXT:    [[TMP92:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M77]], 1
; CHECK-NEXT:    [[VLDH64IP_M78:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP92]], i32 8)
; CHECK-NEXT:    [[TMP93:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M78]], 0
; CHECK-NEXT:    [[TMP94:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M78]], 1
; CHECK-NEXT:    [[VSTL64IP_M79:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP79]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP81]], ptr [[VSTL64IP_M79]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M81:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP83]], ptr [[VSTH64IP_M80]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M82:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP85]], ptr [[VSTL64IP_M81]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M83:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP87]], ptr [[VSTH64IP_M82]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M84:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP89]], ptr [[VSTL64IP_M83]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M85:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP91]], ptr [[VSTH64IP_M84]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M86:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP93]], ptr [[VSTL64IP_M85]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M87:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP94]], i32 8)
; CHECK-NEXT:    [[TMP95:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M87]], 0
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M87]], 1
; CHECK-NEXT:    [[VLDH64IP_M88:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP96]], i32 8)
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M88]], 0
; CHECK-NEXT:    [[TMP98]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M88]], 1
; CHECK-NEXT:    [[VSTL64IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP95]], ptr [[VSTH64IP_M86]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M90]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP97]], ptr [[VSTL64IP_M89]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_6]]:
; CHECK-NEXT:    [[VLDL64IP_M91:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M91]], 0
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M91]], 1
; CHECK-NEXT:    [[VLDH64IP_M92:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP100]], i32 8)
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M92]], 0
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M92]], 1
; CHECK-NEXT:    [[VLDL64IP_M93:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP102]], i32 8)
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 0
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 1
; CHECK-NEXT:    [[VLDH64IP_M94:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP104]], i32 8)
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 0
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 1
; CHECK-NEXT:    [[VLDL64IP_M95:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP106]], i32 8)
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 0
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 1
; CHECK-NEXT:    [[VLDH64IP_M96:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP108]], i32 8)
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 0
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 1
; CHECK-NEXT:    [[VLDL64IP_M97:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP110]], i32 8)
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 0
; CHECK-NEXT:    [[TMP112:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 1
; CHECK-NEXT:    [[VLDH64IP_M98:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP112]], i32 8)
; CHECK-NEXT:    [[TMP113:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 0
; CHECK-NEXT:    [[TMP114:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 1
; CHECK-NEXT:    [[VSTL64IP_M99:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP99]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M100:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP101]], ptr [[VSTL64IP_M99]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M101:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP103]], ptr [[VSTH64IP_M100]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M102:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP105]], ptr [[VSTL64IP_M101]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M103:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP107]], ptr [[VSTH64IP_M102]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M104:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP109]], ptr [[VSTL64IP_M103]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M105:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP111]], ptr [[VSTH64IP_M104]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M106:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP113]], ptr [[VSTL64IP_M105]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M107:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP114]], i32 8)
; CHECK-NEXT:    [[TMP115:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 0
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 1
; CHECK-NEXT:    [[VLDH64IP_M108:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP116]], i32 8)
; CHECK-NEXT:    [[TMP117:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 0
; CHECK-NEXT:    [[TMP118:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 1
; CHECK-NEXT:    [[VLDL64IP_M109:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP118]], i32 8)
; CHECK-NEXT:    [[TMP119:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M109]], 0
; CHECK-NEXT:    [[TMP120:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M109]], 1
; CHECK-NEXT:    [[VLDH64IP_M110:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP120]], i32 8)
; CHECK-NEXT:    [[TMP121:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M110]], 0
; CHECK-NEXT:    [[TMP122]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M110]], 1
; CHECK-NEXT:    [[VSTL64IP_M111:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP115]], ptr [[VSTH64IP_M106]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M112:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP117]], ptr [[VSTL64IP_M111]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M113:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP119]], ptr [[VSTH64IP_M112]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M114]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP121]], ptr [[VSTL64IP_M113]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[TAIL_CASE_7]]:
; CHECK-NEXT:    [[VLDL64IP_M115:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[SRC_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[TMP123:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M115]], 0
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M115]], 1
; CHECK-NEXT:    [[VLDH64IP_M116:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP124]], i32 8)
; CHECK-NEXT:    [[TMP125:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M116]], 0
; CHECK-NEXT:    [[TMP126:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M116]], 1
; CHECK-NEXT:    [[VLDL64IP_M117:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP126]], i32 8)
; CHECK-NEXT:    [[TMP127:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M117]], 0
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M117]], 1
; CHECK-NEXT:    [[VLDH64IP_M118:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP128]], i32 8)
; CHECK-NEXT:    [[TMP129:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M118]], 0
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M118]], 1
; CHECK-NEXT:    [[VLDL64IP_M119:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP130]], i32 8)
; CHECK-NEXT:    [[TMP131:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M119]], 0
; CHECK-NEXT:    [[TMP132:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M119]], 1
; CHECK-NEXT:    [[VLDH64IP_M120:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP132]], i32 8)
; CHECK-NEXT:    [[TMP133:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M120]], 0
; CHECK-NEXT:    [[TMP134:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M120]], 1
; CHECK-NEXT:    [[VLDL64IP_M121:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP134]], i32 8)
; CHECK-NEXT:    [[TMP135:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M121]], 0
; CHECK-NEXT:    [[TMP136:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M121]], 1
; CHECK-NEXT:    [[VLDH64IP_M122:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP136]], i32 8)
; CHECK-NEXT:    [[TMP137:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M122]], 0
; CHECK-NEXT:    [[TMP138:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M122]], 1
; CHECK-NEXT:    [[VSTL64IP_M123:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP123]], ptr [[DST_PTR_AFTER_LOOP]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M124:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP125]], ptr [[VSTL64IP_M123]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M125:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP127]], ptr [[VSTH64IP_M124]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M126:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP129]], ptr [[VSTL64IP_M125]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M127:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP131]], ptr [[VSTH64IP_M126]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M128:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP133]], ptr [[VSTL64IP_M127]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M129:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP135]], ptr [[VSTH64IP_M128]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M130:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP137]], ptr [[VSTL64IP_M129]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M131:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP138]], i32 8)
; CHECK-NEXT:    [[TMP139:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 0
; CHECK-NEXT:    [[TMP140:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 1
; CHECK-NEXT:    [[VLDH64IP_M132:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP140]], i32 8)
; CHECK-NEXT:    [[TMP141:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 0
; CHECK-NEXT:    [[TMP142:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 1
; CHECK-NEXT:    [[VLDL64IP_M133:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP142]], i32 8)
; CHECK-NEXT:    [[TMP143:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 0
; CHECK-NEXT:    [[TMP144:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 1
; CHECK-NEXT:    [[VLDH64IP_M134:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP144]], i32 8)
; CHECK-NEXT:    [[TMP145:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 0
; CHECK-NEXT:    [[TMP146:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 1
; CHECK-NEXT:    [[VLDL64IP_M135:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP146]], i32 8)
; CHECK-NEXT:    [[TMP147:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 0
; CHECK-NEXT:    [[TMP148:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 1
; CHECK-NEXT:    [[VLDH64IP_M136:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip.m(ptr [[TMP148]], i32 8)
; CHECK-NEXT:    [[TMP149:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 0
; CHECK-NEXT:    [[TMP150]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 1
; CHECK-NEXT:    [[VSTL64IP_M137:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP139]], ptr [[VSTH64IP_M130]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M138:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP141]], ptr [[VSTL64IP_M137]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M139:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP143]], ptr [[VSTH64IP_M138]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M140:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP145]], ptr [[VSTL64IP_M139]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M141:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip.m(<8 x i8> [[TMP147]], ptr [[VSTH64IP_M140]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M142]] = call ptr @llvm.riscv.esp.vst.h.64.ip.m(<8 x i8> [[TMP149]], ptr [[VSTL64IP_M141]], i32 8)
; CHECK-NEXT:    br label %[[HANDLE_TAIL_SWITCH]]
; CHECK:       [[HANDLE_REMAINING_BYTES]]:
; CHECK-NEXT:    call void @esp32p4MemCpySrc8Dst8From1To7Opt(ptr [[DST_PTR_AFTER_8B]], ptr [[SRC_PTR_AFTER_8B]], i32 [[REMAINING_BYTES]])
; CHECK-NEXT:    br label %[[RETURN]]
;
