; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+zcmp -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=RV32-ZCMP
; RUN: llc -mtriple=riscv32 -mattr=+zcmp,+cm-popret,+cm-push-reverse -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=WORKAROUND

declare i32 @bar(i32)

; 2 callee-saved registers: ra, s0
define i32 @callee_saved_2regs(i32 %a, i32 %b) {
; RV32-ZCMP-LABEL: callee_saved_2regs:
; RV32-ZCMP:       # %bb.0:
; RV32-ZCMP-NEXT:    cm.push {ra, s0}, -16
; RV32-ZCMP-NEXT:    .cfi_def_cfa_offset 16
; RV32-ZCMP-NEXT:    .cfi_offset ra, -8
; RV32-ZCMP-NEXT:    .cfi_offset s0, -4
; RV32-ZCMP-NEXT:    mv s0, a1
; RV32-ZCMP-NEXT:    call bar
; RV32-ZCMP-NEXT:    add a0, a0, s0
; RV32-ZCMP-NEXT:    cm.popret {ra, s0}, 16
;
; WORKAROUND-LABEL: callee_saved_2regs:
; WORKAROUND:       # %bb.0:
; WORKAROUND-NEXT:    cm.push {ra, s0}, -16
; WORKAROUND-NEXT:    .cfi_def_cfa_offset 16
; WORKAROUND-NEXT:    .cfi_offset ra, -4
; WORKAROUND-NEXT:    .cfi_offset s0, -8
; WORKAROUND-NEXT:    mv s0, a1
; WORKAROUND-NEXT:    call bar
; WORKAROUND-NEXT:    add a0, a0, s0
; WORKAROUND-NEXT:    cm.pop {ra, s0}, 16
; WORKAROUND-NEXT:    ret
  %call = call i32 @bar(i32 %a)
  %add = add i32 %call, %b
  ret i32 %add
}

; 3 callee-saved registers: ra, s0, s1
define i32 @callee_saved_3regs(i32 %a, i32 %b, i32 %c) {
; RV32-ZCMP-LABEL: callee_saved_3regs:
; RV32-ZCMP:       # %bb.0:
; RV32-ZCMP-NEXT:    cm.push {ra, s0-s1}, -16
; RV32-ZCMP-NEXT:    .cfi_def_cfa_offset 16
; RV32-ZCMP-NEXT:    .cfi_offset ra, -12
; RV32-ZCMP-NEXT:    .cfi_offset s0, -8
; RV32-ZCMP-NEXT:    .cfi_offset s1, -4
; RV32-ZCMP-NEXT:    mv s0, a2
; RV32-ZCMP-NEXT:    mv s1, a1
; RV32-ZCMP-NEXT:    call bar
; RV32-ZCMP-NEXT:    add s0, s0, s1
; RV32-ZCMP-NEXT:    add a0, a0, s0
; RV32-ZCMP-NEXT:    cm.popret {ra, s0-s1}, 16
;
; WORKAROUND-LABEL: callee_saved_3regs:
; WORKAROUND:       # %bb.0:
; WORKAROUND-NEXT:    cm.push {ra, s0-s1}, -16
; WORKAROUND-NEXT:    .cfi_def_cfa_offset 16
; WORKAROUND-NEXT:    .cfi_offset ra, -4
; WORKAROUND-NEXT:    .cfi_offset s0, -8
; WORKAROUND-NEXT:    .cfi_offset s1, -12
; WORKAROUND-NEXT:    mv s0, a2
; WORKAROUND-NEXT:    mv s1, a1
; WORKAROUND-NEXT:    call bar
; WORKAROUND-NEXT:    add s0, s0, s1
; WORKAROUND-NEXT:    add a0, a0, s0
; WORKAROUND-NEXT:    cm.pop {ra, s0-s1}, 16
; WORKAROUND-NEXT:    ret
  %call = call i32 @bar(i32 %a)
  %add1 = add i32 %call, %b
  %add2 = add i32 %add1, %c
  ret i32 %add2
}
