; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32-p4-mem-intrin -riscv-esp32-p4-mem-intrin=true < %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "riscv32-esp-unknown-elf"

; src16 dst16
define void @test_src16_dst16_size_0(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_0(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void
;
  entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(1) %a, ptr noundef nonnull align 16 dereferenceable(1) %b, i32 0, i1 false)
  ret void
}

define void @test_src16_dst16_size_1(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(1) %a, ptr noundef nonnull align 16 dereferenceable(1) %b, i32 1, i1 false)
  ret void
}

define void @test_src16_dst16_size_2(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_2(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(2) %a, ptr noundef nonnull align 16 dereferenceable(2) %b, i32 2, i1 false)
  ret void
}

define void @test_src16_dst16_size_3(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_3(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(3) %a, ptr noundef nonnull align 16 dereferenceable(3) %b, i32 3, i1 false)
  ret void
}

define void @test_src16_dst16_size_4(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_4(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(4) %a, ptr noundef nonnull align 16 dereferenceable(4) %b, i32 4, i1 false)
  ret void
}

define void @test_src16_dst16_size_5(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_5(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(5) %a, ptr noundef nonnull align 16 dereferenceable(5) %b, i32 5, i1 false)
  ret void
}

define void @test_src16_dst16_size_6(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_6(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(6) %a, ptr noundef nonnull align 16 dereferenceable(6) %b, i32 6, i1 false)
  ret void
}

define void @test_src16_dst16_size_7(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_7(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(7) %a, ptr noundef nonnull align 16 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_src16_dst16_size_8(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_8(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(8) %a, ptr noundef nonnull align 16 dereferenceable(8) %b, i32 8, i1 false)
  ret void
}

define void @test_src16_dst16_size_9(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_9(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[VSTL64IP_M]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(9) %a, ptr noundef nonnull align 16 dereferenceable(9) %b, i32 9, i1 false)
  ret void
}

define void @test_src16_dst16_size_10(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_10(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[VSTL64IP_M]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(10) %a, ptr noundef nonnull align 16 dereferenceable(10) %b, i32 10, i1 false)
  ret void
}

define void @test_src16_dst16_size_11(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_11(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[VSTL64IP_M]], align 2
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 2
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(11) %a, ptr noundef nonnull align 16 dereferenceable(11) %b, i32 11, i1 false)
  ret void
}

define void @test_src16_dst16_size_12(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_12(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(12) %a, ptr noundef nonnull align 16 dereferenceable(12) %b, i32 12, i1 false)
  ret void
}

define void @test_src16_dst16_size_13(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_13(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(13) %a, ptr noundef nonnull align 16 dereferenceable(13) %b, i32 13, i1 false)
  ret void
}

define void @test_src16_dst16_size_14(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_14(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    store i16 [[TMP5]], ptr [[TMP4]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(14) %a, ptr noundef nonnull align 16 dereferenceable(14) %b, i32 14, i1 false)
  ret void
}

define void @test_src16_dst16_size_15(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_15(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    store i16 [[TMP5]], ptr [[TMP4]], align 2
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[TMP1]], i32 6
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[TMP6]], align 1
; CHECK-NEXT:    store i8 [[TMP8]], ptr [[TMP7]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(15) %a, ptr noundef nonnull align 16 dereferenceable(15) %b, i32 15, i1 false)
  ret void
}

define void @test_src16_dst16_size_16(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(16) %a, ptr noundef nonnull align 16 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_src16_dst16_size_17(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_17(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(17) %a, ptr noundef nonnull align 16 dereferenceable(17) %b, i32 17, i1 false)
  ret void
}

define void @test_src16_dst16_size_31(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_31(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP3]], ptr [[TMP2]], i32 8)
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[TMP4]], i32 4
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[TMP6]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[TMP7]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[TMP4]], i32 6
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP9]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[TMP10]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(31) %a, ptr noundef nonnull align 16 dereferenceable(31) %b, i32 31, i1 false)
  ret void
}

define void @test_src16_dst16_size_32(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_32(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M2:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(32) %a, ptr noundef nonnull align 16 dereferenceable(32) %b, i32 32, i1 false)
  ret void
}

define void @test_src16_dst16_size_33(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_33(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M2:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(33) %a, ptr noundef nonnull align 16 dereferenceable(33) %b, i32 33, i1 false)
  ret void
}

define void @test_src16_dst16_size_47(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M2:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[TMP4]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP6]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP6]], i32 4
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[TMP8]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[TMP9]], align 2
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[TMP6]], i32 6
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[TMP11]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[TMP12]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(47) %a, ptr noundef nonnull align 16 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

define void @test_src16_dst16_size_48(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M3]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(48) %a, ptr noundef nonnull align 16 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_src16_dst16_size_49(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_49(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[TMP7:%.*]] = load i8, ptr [[TMP5]], align 1
; CHECK-NEXT:    store i8 [[TMP7]], ptr [[TMP6]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(49) %a, ptr noundef nonnull align 16 dereferenceable(49) %b, i32 49, i1 false)
  ret void
}

define void @test_src16_dst16_size_63(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_63(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP7]], ptr [[TMP6]], i32 8)
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP8]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[TMP8]], i32 4
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[TMP10]], align 2
; CHECK-NEXT:    store i16 [[TMP12]], ptr [[TMP11]], align 2
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[TMP8]], i32 6
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[TMP13]], align 1
; CHECK-NEXT:    store i8 [[TMP15]], ptr [[TMP14]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(63) %a, ptr noundef nonnull align 16 dereferenceable(63) %b, i32 63, i1 false)
  ret void
}

define void @test_src16_dst16_size_64(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_64(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M4]], i32 16)
; CHECK-NEXT:    [[VST128IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M5]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(64) %a, ptr noundef nonnull align 16 dereferenceable(64) %b, i32 64, i1 false)
  ret void
}

define void @test_src16_dst16_size_65(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_65(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M4]], i32 16)
; CHECK-NEXT:    [[VST128IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M5]], i32 16)
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 64
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 64
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[TMP8]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(65) %a, ptr noundef nonnull align 16 dereferenceable(65) %b, i32 65, i1 false)
  ret void
}

define void @test_src16_dst16_size_80(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_80(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M5]], i32 16)
; CHECK-NEXT:    [[VST128IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M6]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M7]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(80) %a, ptr noundef nonnull align 16 dereferenceable(80) %b, i32 80, i1 false)
  ret void
}

define void @test_src16_dst16_size_81(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_81(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M5]], i32 16)
; CHECK-NEXT:    [[VST128IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M6]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M7]], i32 16)
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[B]], i32 80
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[A]], i32 80
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP9]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[TMP10]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(81) %a, ptr noundef nonnull align 16 dereferenceable(81) %b, i32 81, i1 false)
  ret void
}

define void @test_src16_dst16_size_88(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_88(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M5]], i32 16)
; CHECK-NEXT:    [[VST128IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M6]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M7]], i32 16)
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP10]], ptr [[VST128IP_M8]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(88) %a, ptr noundef nonnull align 16 dereferenceable(88) %b, i32 88, i1 false)
  ret void
}

define void @test_src16_dst16_size_96(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_96(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M6]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M7]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(96) %a, ptr noundef nonnull align 16 dereferenceable(96) %b, i32 96, i1 false)
  ret void
}

define void @test_src16_dst16_size_112(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_112(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M7]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M10]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(112) %a, ptr noundef nonnull align 16 dereferenceable(112) %b, i32 112, i1 false)
  ret void
}

define void @test_src16_dst16_size_124(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_124(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M7]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M10]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[TMP14]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[TMP16]], align 4
; CHECK-NEXT:    store i32 [[TMP17]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(124) %a, ptr noundef nonnull align 16 dereferenceable(124) %b, i32 124, i1 false)
  ret void
}

define void @test_src16_dst16_size_127(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_127(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M7]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M10]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[TMP14]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[TMP16]], align 4
; CHECK-NEXT:    store i32 [[TMP17]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr i8, ptr [[TMP16]], i32 4
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP20:%.*]] = load i16, ptr [[TMP18]], align 2
; CHECK-NEXT:    store i16 [[TMP20]], ptr [[TMP19]], align 2
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr i8, ptr [[TMP16]], i32 6
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP23:%.*]] = load i8, ptr [[TMP21]], align 1
; CHECK-NEXT:    store i8 [[TMP23]], ptr [[TMP22]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(127) %a, ptr noundef nonnull align 16 dereferenceable(127) %b, i32 127, i1 false)
  ret void
}

define void @test_src16_dst16_size_128(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M10]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    [[VST128IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[VST128IP_M12]], i32 16)
; CHECK-NEXT:    [[VST128IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP14]], ptr [[VST128IP_M13]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(128) %a, ptr noundef nonnull align 16 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_src16_dst16_size_129(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_129(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M10]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    [[VST128IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[VST128IP_M12]], i32 16)
; CHECK-NEXT:    [[VST128IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP14]], ptr [[VST128IP_M13]], i32 16)
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[B]], i32 128
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[A]], i32 128
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[TMP15]], align 1
; CHECK-NEXT:    store i8 [[TMP17]], ptr [[TMP16]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(129) %a, ptr noundef nonnull align 16 dereferenceable(129) %b, i32 129, i1 false)
  ret void
}

define void @test_src16_dst16_size_255(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_255(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 1
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M10]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    [[VST128IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[VST128IP_M12]], i32 16)
; CHECK-NEXT:    [[VST128IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP14]], ptr [[VST128IP_M13]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M15:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP15]], i32 16)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 1
; CHECK-NEXT:    [[VLD128IP_M16:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP17]], i32 16)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M16]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M16]], 1
; CHECK-NEXT:    [[VLD128IP_M17:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP19]], i32 16)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 1
; CHECK-NEXT:    [[VLD128IP_M18:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP21]], i32 16)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 1
; CHECK-NEXT:    [[VLD128IP_M19:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP23]], i32 16)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M19]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M19]], 1
; CHECK-NEXT:    [[VLD128IP_M20:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP25]], i32 16)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M20]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M20]], 1
; CHECK-NEXT:    [[VLD128IP_M21:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP27]], i32 16)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M21]], 0
; CHECK-NEXT:    [[VST128IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP16]], ptr [[VST128IP_M14]], i32 16)
; CHECK-NEXT:    [[VST128IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP18]], ptr [[VST128IP_M22]], i32 16)
; CHECK-NEXT:    [[VST128IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP20]], ptr [[VST128IP_M23]], i32 16)
; CHECK-NEXT:    [[VST128IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP22]], ptr [[VST128IP_M24]], i32 16)
; CHECK-NEXT:    [[VST128IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP24]], ptr [[VST128IP_M25]], i32 16)
; CHECK-NEXT:    [[VST128IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP26]], ptr [[VST128IP_M26]], i32 16)
; CHECK-NEXT:    [[VST128IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP28]], ptr [[VST128IP_M27]], i32 16)
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr i8, ptr [[B]], i32 240
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr i8, ptr [[A]], i32 240
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP31]], ptr [[TMP30]], i32 8)
; CHECK-NEXT:    [[TMP33:%.*]] = load i32, ptr [[TMP32]], align 4
; CHECK-NEXT:    store i32 [[TMP33]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr i8, ptr [[TMP32]], i32 4
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP36:%.*]] = load i16, ptr [[TMP34]], align 2
; CHECK-NEXT:    store i16 [[TMP36]], ptr [[TMP35]], align 2
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr i8, ptr [[TMP32]], i32 6
; CHECK-NEXT:    [[TMP38:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP39:%.*]] = load i8, ptr [[TMP37]], align 1
; CHECK-NEXT:    store i8 [[TMP39]], ptr [[TMP38]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(255) %a, ptr noundef nonnull align 16 dereferenceable(255) %b, i32 255, i1 false)
  ret void
}

define void @test_src16_dst16_size_256(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 1
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M10]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    [[VST128IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[VST128IP_M12]], i32 16)
; CHECK-NEXT:    [[VST128IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP14]], ptr [[VST128IP_M13]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M15:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP15]], i32 16)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 1
; CHECK-NEXT:    [[VLD128IP_M16:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP17]], i32 16)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M16]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M16]], 1
; CHECK-NEXT:    [[VLD128IP_M17:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP19]], i32 16)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 1
; CHECK-NEXT:    [[VLD128IP_M18:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP21]], i32 16)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 1
; CHECK-NEXT:    [[VLD128IP_M19:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP23]], i32 16)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M19]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M19]], 1
; CHECK-NEXT:    [[VLD128IP_M20:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP25]], i32 16)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M20]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M20]], 1
; CHECK-NEXT:    [[VLD128IP_M21:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP27]], i32 16)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M21]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M21]], 1
; CHECK-NEXT:    [[VLD128IP_M22:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP29]], i32 16)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 0
; CHECK-NEXT:    [[VST128IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP16]], ptr [[VST128IP_M14]], i32 16)
; CHECK-NEXT:    [[VST128IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP18]], ptr [[VST128IP_M23]], i32 16)
; CHECK-NEXT:    [[VST128IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP20]], ptr [[VST128IP_M24]], i32 16)
; CHECK-NEXT:    [[VST128IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP22]], ptr [[VST128IP_M25]], i32 16)
; CHECK-NEXT:    [[VST128IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP24]], ptr [[VST128IP_M26]], i32 16)
; CHECK-NEXT:    [[VST128IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP26]], ptr [[VST128IP_M27]], i32 16)
; CHECK-NEXT:    [[VST128IP_M29:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP28]], ptr [[VST128IP_M28]], i32 16)
; CHECK-NEXT:    [[VST128IP_M30:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP30]], ptr [[VST128IP_M29]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(256) %a, ptr noundef nonnull align 16 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

define void @test_src16_dst16_size_1023(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_1023(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 1
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M10]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    [[VST128IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[VST128IP_M12]], i32 16)
; CHECK-NEXT:    [[VST128IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP14]], ptr [[VST128IP_M13]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M15:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP15]], i32 16)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 1
; CHECK-NEXT:    [[VLD128IP_M16:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP17]], i32 16)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M16]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M16]], 1
; CHECK-NEXT:    [[VLD128IP_M17:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP19]], i32 16)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 1
; CHECK-NEXT:    [[VLD128IP_M18:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP21]], i32 16)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 1
; CHECK-NEXT:    [[VLD128IP_M19:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP23]], i32 16)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M19]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M19]], 1
; CHECK-NEXT:    [[VLD128IP_M20:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP25]], i32 16)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M20]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M20]], 1
; CHECK-NEXT:    [[VLD128IP_M21:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP27]], i32 16)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M21]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M21]], 1
; CHECK-NEXT:    [[VLD128IP_M22:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP29]], i32 16)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 1
; CHECK-NEXT:    [[VST128IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP16]], ptr [[VST128IP_M14]], i32 16)
; CHECK-NEXT:    [[VST128IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP18]], ptr [[VST128IP_M23]], i32 16)
; CHECK-NEXT:    [[VST128IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP20]], ptr [[VST128IP_M24]], i32 16)
; CHECK-NEXT:    [[VST128IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP22]], ptr [[VST128IP_M25]], i32 16)
; CHECK-NEXT:    [[VST128IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP24]], ptr [[VST128IP_M26]], i32 16)
; CHECK-NEXT:    [[VST128IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP26]], ptr [[VST128IP_M27]], i32 16)
; CHECK-NEXT:    [[VST128IP_M29:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP28]], ptr [[VST128IP_M28]], i32 16)
; CHECK-NEXT:    [[VST128IP_M30:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP30]], ptr [[VST128IP_M29]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M31:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP31]], i32 16)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M31]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M31]], 1
; CHECK-NEXT:    [[VLD128IP_M32:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP33]], i32 16)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M32]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M32]], 1
; CHECK-NEXT:    [[VLD128IP_M33:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP35]], i32 16)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M33]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M33]], 1
; CHECK-NEXT:    [[VLD128IP_M34:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP37]], i32 16)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M34]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M34]], 1
; CHECK-NEXT:    [[VLD128IP_M35:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP39]], i32 16)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M35]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M35]], 1
; CHECK-NEXT:    [[VLD128IP_M36:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP41]], i32 16)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M36]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M36]], 1
; CHECK-NEXT:    [[VLD128IP_M37:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP43]], i32 16)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M37]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M37]], 1
; CHECK-NEXT:    [[VLD128IP_M38:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP45]], i32 16)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M38]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M38]], 1
; CHECK-NEXT:    [[VST128IP_M39:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP32]], ptr [[VST128IP_M30]], i32 16)
; CHECK-NEXT:    [[VST128IP_M40:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP34]], ptr [[VST128IP_M39]], i32 16)
; CHECK-NEXT:    [[VST128IP_M41:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP36]], ptr [[VST128IP_M40]], i32 16)
; CHECK-NEXT:    [[VST128IP_M42:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP38]], ptr [[VST128IP_M41]], i32 16)
; CHECK-NEXT:    [[VST128IP_M43:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP40]], ptr [[VST128IP_M42]], i32 16)
; CHECK-NEXT:    [[VST128IP_M44:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP42]], ptr [[VST128IP_M43]], i32 16)
; CHECK-NEXT:    [[VST128IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP44]], ptr [[VST128IP_M44]], i32 16)
; CHECK-NEXT:    [[VST128IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP46]], ptr [[VST128IP_M45]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M47:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP47]], i32 16)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 1
; CHECK-NEXT:    [[VLD128IP_M48:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP49]], i32 16)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 1
; CHECK-NEXT:    [[VLD128IP_M49:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP51]], i32 16)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 1
; CHECK-NEXT:    [[VLD128IP_M50:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP53]], i32 16)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 1
; CHECK-NEXT:    [[VLD128IP_M51:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP55]], i32 16)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 1
; CHECK-NEXT:    [[VLD128IP_M52:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP57]], i32 16)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M52]], 0
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M52]], 1
; CHECK-NEXT:    [[VLD128IP_M53:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP59]], i32 16)
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 1
; CHECK-NEXT:    [[VLD128IP_M54:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP61]], i32 16)
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M54]], 0
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M54]], 1
; CHECK-NEXT:    [[VST128IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP48]], ptr [[VST128IP_M46]], i32 16)
; CHECK-NEXT:    [[VST128IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP50]], ptr [[VST128IP_M55]], i32 16)
; CHECK-NEXT:    [[VST128IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP52]], ptr [[VST128IP_M56]], i32 16)
; CHECK-NEXT:    [[VST128IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP54]], ptr [[VST128IP_M57]], i32 16)
; CHECK-NEXT:    [[VST128IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP56]], ptr [[VST128IP_M58]], i32 16)
; CHECK-NEXT:    [[VST128IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP58]], ptr [[VST128IP_M59]], i32 16)
; CHECK-NEXT:    [[VST128IP_M61:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP60]], ptr [[VST128IP_M60]], i32 16)
; CHECK-NEXT:    [[VST128IP_M62:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP62]], ptr [[VST128IP_M61]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M63:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP63]], i32 16)
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M63]], 0
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M63]], 1
; CHECK-NEXT:    [[VLD128IP_M64:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP65]], i32 16)
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M64]], 0
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M64]], 1
; CHECK-NEXT:    [[VLD128IP_M65:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP67]], i32 16)
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M65]], 0
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M65]], 1
; CHECK-NEXT:    [[VLD128IP_M66:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP69]], i32 16)
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M66]], 0
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M66]], 1
; CHECK-NEXT:    [[VLD128IP_M67:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP71]], i32 16)
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M67]], 0
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M67]], 1
; CHECK-NEXT:    [[VLD128IP_M68:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP73]], i32 16)
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M68]], 0
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M68]], 1
; CHECK-NEXT:    [[VLD128IP_M69:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP75]], i32 16)
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M69]], 0
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M69]], 1
; CHECK-NEXT:    [[VLD128IP_M70:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP77]], i32 16)
; CHECK-NEXT:    [[TMP78:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M70]], 0
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M70]], 1
; CHECK-NEXT:    [[VST128IP_M71:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP64]], ptr [[VST128IP_M62]], i32 16)
; CHECK-NEXT:    [[VST128IP_M72:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP66]], ptr [[VST128IP_M71]], i32 16)
; CHECK-NEXT:    [[VST128IP_M73:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP68]], ptr [[VST128IP_M72]], i32 16)
; CHECK-NEXT:    [[VST128IP_M74:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP70]], ptr [[VST128IP_M73]], i32 16)
; CHECK-NEXT:    [[VST128IP_M75:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP72]], ptr [[VST128IP_M74]], i32 16)
; CHECK-NEXT:    [[VST128IP_M76:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP74]], ptr [[VST128IP_M75]], i32 16)
; CHECK-NEXT:    [[VST128IP_M77:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP76]], ptr [[VST128IP_M76]], i32 16)
; CHECK-NEXT:    [[VST128IP_M78:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP78]], ptr [[VST128IP_M77]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M79:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP79]], i32 16)
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M79]], 0
; CHECK-NEXT:    [[TMP81:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M79]], 1
; CHECK-NEXT:    [[VLD128IP_M80:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP81]], i32 16)
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M80]], 0
; CHECK-NEXT:    [[TMP83:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M80]], 1
; CHECK-NEXT:    [[VLD128IP_M81:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP83]], i32 16)
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M81]], 0
; CHECK-NEXT:    [[TMP85:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M81]], 1
; CHECK-NEXT:    [[VLD128IP_M82:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP85]], i32 16)
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M82]], 0
; CHECK-NEXT:    [[TMP87:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M82]], 1
; CHECK-NEXT:    [[VLD128IP_M83:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP87]], i32 16)
; CHECK-NEXT:    [[TMP88:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M83]], 0
; CHECK-NEXT:    [[TMP89:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M83]], 1
; CHECK-NEXT:    [[VLD128IP_M84:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP89]], i32 16)
; CHECK-NEXT:    [[TMP90:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M84]], 0
; CHECK-NEXT:    [[TMP91:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M84]], 1
; CHECK-NEXT:    [[VLD128IP_M85:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP91]], i32 16)
; CHECK-NEXT:    [[TMP92:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M85]], 0
; CHECK-NEXT:    [[TMP93:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M85]], 1
; CHECK-NEXT:    [[VLD128IP_M86:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP93]], i32 16)
; CHECK-NEXT:    [[TMP94:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M86]], 0
; CHECK-NEXT:    [[TMP95:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M86]], 1
; CHECK-NEXT:    [[VST128IP_M87:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP80]], ptr [[VST128IP_M78]], i32 16)
; CHECK-NEXT:    [[VST128IP_M88:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP82]], ptr [[VST128IP_M87]], i32 16)
; CHECK-NEXT:    [[VST128IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP84]], ptr [[VST128IP_M88]], i32 16)
; CHECK-NEXT:    [[VST128IP_M90:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP86]], ptr [[VST128IP_M89]], i32 16)
; CHECK-NEXT:    [[VST128IP_M91:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP88]], ptr [[VST128IP_M90]], i32 16)
; CHECK-NEXT:    [[VST128IP_M92:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP90]], ptr [[VST128IP_M91]], i32 16)
; CHECK-NEXT:    [[VST128IP_M93:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP92]], ptr [[VST128IP_M92]], i32 16)
; CHECK-NEXT:    [[VST128IP_M94:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP94]], ptr [[VST128IP_M93]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M95:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP95]], i32 16)
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 0
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 1
; CHECK-NEXT:    [[VLD128IP_M96:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP97]], i32 16)
; CHECK-NEXT:    [[TMP98:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 0
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 1
; CHECK-NEXT:    [[VLD128IP_M97:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP99]], i32 16)
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M97]], 0
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M97]], 1
; CHECK-NEXT:    [[VLD128IP_M98:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP101]], i32 16)
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M98]], 0
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M98]], 1
; CHECK-NEXT:    [[VLD128IP_M99:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP103]], i32 16)
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M99]], 0
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M99]], 1
; CHECK-NEXT:    [[VLD128IP_M100:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP105]], i32 16)
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M100]], 0
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M100]], 1
; CHECK-NEXT:    [[VLD128IP_M101:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP107]], i32 16)
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M101]], 0
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M101]], 1
; CHECK-NEXT:    [[VLD128IP_M102:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP109]], i32 16)
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M102]], 0
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M102]], 1
; CHECK-NEXT:    [[VST128IP_M103:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP96]], ptr [[VST128IP_M94]], i32 16)
; CHECK-NEXT:    [[VST128IP_M104:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP98]], ptr [[VST128IP_M103]], i32 16)
; CHECK-NEXT:    [[VST128IP_M105:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP100]], ptr [[VST128IP_M104]], i32 16)
; CHECK-NEXT:    [[VST128IP_M106:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP102]], ptr [[VST128IP_M105]], i32 16)
; CHECK-NEXT:    [[VST128IP_M107:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP104]], ptr [[VST128IP_M106]], i32 16)
; CHECK-NEXT:    [[VST128IP_M108:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP106]], ptr [[VST128IP_M107]], i32 16)
; CHECK-NEXT:    [[VST128IP_M109:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP108]], ptr [[VST128IP_M108]], i32 16)
; CHECK-NEXT:    [[VST128IP_M110:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP110]], ptr [[VST128IP_M109]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M111:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP111]], i32 16)
; CHECK-NEXT:    [[TMP112:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M111]], 0
; CHECK-NEXT:    [[TMP113:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M111]], 1
; CHECK-NEXT:    [[VLD128IP_M112:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP113]], i32 16)
; CHECK-NEXT:    [[TMP114:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M112]], 0
; CHECK-NEXT:    [[TMP115:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M112]], 1
; CHECK-NEXT:    [[VLD128IP_M113:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP115]], i32 16)
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M113]], 0
; CHECK-NEXT:    [[TMP117:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M113]], 1
; CHECK-NEXT:    [[VLD128IP_M114:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP117]], i32 16)
; CHECK-NEXT:    [[TMP118:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M114]], 0
; CHECK-NEXT:    [[TMP119:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M114]], 1
; CHECK-NEXT:    [[VLD128IP_M115:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP119]], i32 16)
; CHECK-NEXT:    [[TMP120:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M115]], 0
; CHECK-NEXT:    [[TMP121:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M115]], 1
; CHECK-NEXT:    [[VLD128IP_M116:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP121]], i32 16)
; CHECK-NEXT:    [[TMP122:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M116]], 0
; CHECK-NEXT:    [[TMP123:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M116]], 1
; CHECK-NEXT:    [[VLD128IP_M117:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP123]], i32 16)
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M117]], 0
; CHECK-NEXT:    [[VST128IP_M118:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP112]], ptr [[VST128IP_M110]], i32 16)
; CHECK-NEXT:    [[VST128IP_M119:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP114]], ptr [[VST128IP_M118]], i32 16)
; CHECK-NEXT:    [[VST128IP_M120:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP116]], ptr [[VST128IP_M119]], i32 16)
; CHECK-NEXT:    [[VST128IP_M121:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP118]], ptr [[VST128IP_M120]], i32 16)
; CHECK-NEXT:    [[VST128IP_M122:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP120]], ptr [[VST128IP_M121]], i32 16)
; CHECK-NEXT:    [[VST128IP_M123:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP122]], ptr [[VST128IP_M122]], i32 16)
; CHECK-NEXT:    [[VST128IP_M124:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP124]], ptr [[VST128IP_M123]], i32 16)
; CHECK-NEXT:    [[TMP125:%.*]] = getelementptr i8, ptr [[B]], i32 1008
; CHECK-NEXT:    [[TMP126:%.*]] = getelementptr i8, ptr [[A]], i32 1008
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP125]], i32 8)
; CHECK-NEXT:    [[TMP127:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP127]], ptr [[TMP126]], i32 8)
; CHECK-NEXT:    [[TMP129:%.*]] = load i32, ptr [[TMP128]], align 4
; CHECK-NEXT:    store i32 [[TMP129]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP130:%.*]] = getelementptr i8, ptr [[TMP128]], i32 4
; CHECK-NEXT:    [[TMP131:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP132:%.*]] = load i16, ptr [[TMP130]], align 2
; CHECK-NEXT:    store i16 [[TMP132]], ptr [[TMP131]], align 2
; CHECK-NEXT:    [[TMP133:%.*]] = getelementptr i8, ptr [[TMP128]], i32 6
; CHECK-NEXT:    [[TMP134:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP135:%.*]] = load i8, ptr [[TMP133]], align 1
; CHECK-NEXT:    store i8 [[TMP135]], ptr [[TMP134]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(1023) %a, ptr noundef nonnull align 16 dereferenceable(1023) %b, i32 1023, i1 false)
  ret void
}

define void @test_src16_dst16_size_1024(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_1024(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 1
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP0]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[VST128IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[VST128IP_M]], i32 16)
; CHECK-NEXT:    [[VST128IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[VST128IP_M8]], i32 16)
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP6]], ptr [[VST128IP_M9]], i32 16)
; CHECK-NEXT:    [[VST128IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M10]], i32 16)
; CHECK-NEXT:    [[VST128IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP10]], ptr [[VST128IP_M11]], i32 16)
; CHECK-NEXT:    [[VST128IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[VST128IP_M12]], i32 16)
; CHECK-NEXT:    [[VST128IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP14]], ptr [[VST128IP_M13]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M15:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP15]], i32 16)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M15]], 1
; CHECK-NEXT:    [[VLD128IP_M16:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP17]], i32 16)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M16]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M16]], 1
; CHECK-NEXT:    [[VLD128IP_M17:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP19]], i32 16)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M17]], 1
; CHECK-NEXT:    [[VLD128IP_M18:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP21]], i32 16)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M18]], 1
; CHECK-NEXT:    [[VLD128IP_M19:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP23]], i32 16)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M19]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M19]], 1
; CHECK-NEXT:    [[VLD128IP_M20:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP25]], i32 16)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M20]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M20]], 1
; CHECK-NEXT:    [[VLD128IP_M21:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP27]], i32 16)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M21]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M21]], 1
; CHECK-NEXT:    [[VLD128IP_M22:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP29]], i32 16)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 1
; CHECK-NEXT:    [[VST128IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP16]], ptr [[VST128IP_M14]], i32 16)
; CHECK-NEXT:    [[VST128IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP18]], ptr [[VST128IP_M23]], i32 16)
; CHECK-NEXT:    [[VST128IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP20]], ptr [[VST128IP_M24]], i32 16)
; CHECK-NEXT:    [[VST128IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP22]], ptr [[VST128IP_M25]], i32 16)
; CHECK-NEXT:    [[VST128IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP24]], ptr [[VST128IP_M26]], i32 16)
; CHECK-NEXT:    [[VST128IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP26]], ptr [[VST128IP_M27]], i32 16)
; CHECK-NEXT:    [[VST128IP_M29:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP28]], ptr [[VST128IP_M28]], i32 16)
; CHECK-NEXT:    [[VST128IP_M30:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP30]], ptr [[VST128IP_M29]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M31:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP31]], i32 16)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M31]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M31]], 1
; CHECK-NEXT:    [[VLD128IP_M32:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP33]], i32 16)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M32]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M32]], 1
; CHECK-NEXT:    [[VLD128IP_M33:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP35]], i32 16)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M33]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M33]], 1
; CHECK-NEXT:    [[VLD128IP_M34:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP37]], i32 16)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M34]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M34]], 1
; CHECK-NEXT:    [[VLD128IP_M35:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP39]], i32 16)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M35]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M35]], 1
; CHECK-NEXT:    [[VLD128IP_M36:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP41]], i32 16)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M36]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M36]], 1
; CHECK-NEXT:    [[VLD128IP_M37:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP43]], i32 16)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M37]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M37]], 1
; CHECK-NEXT:    [[VLD128IP_M38:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP45]], i32 16)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M38]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M38]], 1
; CHECK-NEXT:    [[VST128IP_M39:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP32]], ptr [[VST128IP_M30]], i32 16)
; CHECK-NEXT:    [[VST128IP_M40:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP34]], ptr [[VST128IP_M39]], i32 16)
; CHECK-NEXT:    [[VST128IP_M41:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP36]], ptr [[VST128IP_M40]], i32 16)
; CHECK-NEXT:    [[VST128IP_M42:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP38]], ptr [[VST128IP_M41]], i32 16)
; CHECK-NEXT:    [[VST128IP_M43:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP40]], ptr [[VST128IP_M42]], i32 16)
; CHECK-NEXT:    [[VST128IP_M44:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP42]], ptr [[VST128IP_M43]], i32 16)
; CHECK-NEXT:    [[VST128IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP44]], ptr [[VST128IP_M44]], i32 16)
; CHECK-NEXT:    [[VST128IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP46]], ptr [[VST128IP_M45]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M47:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP47]], i32 16)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 1
; CHECK-NEXT:    [[VLD128IP_M48:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP49]], i32 16)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 1
; CHECK-NEXT:    [[VLD128IP_M49:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP51]], i32 16)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 1
; CHECK-NEXT:    [[VLD128IP_M50:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP53]], i32 16)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 1
; CHECK-NEXT:    [[VLD128IP_M51:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP55]], i32 16)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 1
; CHECK-NEXT:    [[VLD128IP_M52:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP57]], i32 16)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M52]], 0
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M52]], 1
; CHECK-NEXT:    [[VLD128IP_M53:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP59]], i32 16)
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 1
; CHECK-NEXT:    [[VLD128IP_M54:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP61]], i32 16)
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M54]], 0
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M54]], 1
; CHECK-NEXT:    [[VST128IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP48]], ptr [[VST128IP_M46]], i32 16)
; CHECK-NEXT:    [[VST128IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP50]], ptr [[VST128IP_M55]], i32 16)
; CHECK-NEXT:    [[VST128IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP52]], ptr [[VST128IP_M56]], i32 16)
; CHECK-NEXT:    [[VST128IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP54]], ptr [[VST128IP_M57]], i32 16)
; CHECK-NEXT:    [[VST128IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP56]], ptr [[VST128IP_M58]], i32 16)
; CHECK-NEXT:    [[VST128IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP58]], ptr [[VST128IP_M59]], i32 16)
; CHECK-NEXT:    [[VST128IP_M61:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP60]], ptr [[VST128IP_M60]], i32 16)
; CHECK-NEXT:    [[VST128IP_M62:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP62]], ptr [[VST128IP_M61]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M63:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP63]], i32 16)
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M63]], 0
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M63]], 1
; CHECK-NEXT:    [[VLD128IP_M64:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP65]], i32 16)
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M64]], 0
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M64]], 1
; CHECK-NEXT:    [[VLD128IP_M65:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP67]], i32 16)
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M65]], 0
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M65]], 1
; CHECK-NEXT:    [[VLD128IP_M66:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP69]], i32 16)
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M66]], 0
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M66]], 1
; CHECK-NEXT:    [[VLD128IP_M67:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP71]], i32 16)
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M67]], 0
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M67]], 1
; CHECK-NEXT:    [[VLD128IP_M68:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP73]], i32 16)
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M68]], 0
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M68]], 1
; CHECK-NEXT:    [[VLD128IP_M69:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP75]], i32 16)
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M69]], 0
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M69]], 1
; CHECK-NEXT:    [[VLD128IP_M70:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP77]], i32 16)
; CHECK-NEXT:    [[TMP78:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M70]], 0
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M70]], 1
; CHECK-NEXT:    [[VST128IP_M71:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP64]], ptr [[VST128IP_M62]], i32 16)
; CHECK-NEXT:    [[VST128IP_M72:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP66]], ptr [[VST128IP_M71]], i32 16)
; CHECK-NEXT:    [[VST128IP_M73:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP68]], ptr [[VST128IP_M72]], i32 16)
; CHECK-NEXT:    [[VST128IP_M74:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP70]], ptr [[VST128IP_M73]], i32 16)
; CHECK-NEXT:    [[VST128IP_M75:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP72]], ptr [[VST128IP_M74]], i32 16)
; CHECK-NEXT:    [[VST128IP_M76:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP74]], ptr [[VST128IP_M75]], i32 16)
; CHECK-NEXT:    [[VST128IP_M77:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP76]], ptr [[VST128IP_M76]], i32 16)
; CHECK-NEXT:    [[VST128IP_M78:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP78]], ptr [[VST128IP_M77]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M79:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP79]], i32 16)
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M79]], 0
; CHECK-NEXT:    [[TMP81:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M79]], 1
; CHECK-NEXT:    [[VLD128IP_M80:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP81]], i32 16)
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M80]], 0
; CHECK-NEXT:    [[TMP83:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M80]], 1
; CHECK-NEXT:    [[VLD128IP_M81:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP83]], i32 16)
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M81]], 0
; CHECK-NEXT:    [[TMP85:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M81]], 1
; CHECK-NEXT:    [[VLD128IP_M82:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP85]], i32 16)
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M82]], 0
; CHECK-NEXT:    [[TMP87:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M82]], 1
; CHECK-NEXT:    [[VLD128IP_M83:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP87]], i32 16)
; CHECK-NEXT:    [[TMP88:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M83]], 0
; CHECK-NEXT:    [[TMP89:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M83]], 1
; CHECK-NEXT:    [[VLD128IP_M84:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP89]], i32 16)
; CHECK-NEXT:    [[TMP90:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M84]], 0
; CHECK-NEXT:    [[TMP91:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M84]], 1
; CHECK-NEXT:    [[VLD128IP_M85:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP91]], i32 16)
; CHECK-NEXT:    [[TMP92:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M85]], 0
; CHECK-NEXT:    [[TMP93:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M85]], 1
; CHECK-NEXT:    [[VLD128IP_M86:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP93]], i32 16)
; CHECK-NEXT:    [[TMP94:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M86]], 0
; CHECK-NEXT:    [[TMP95:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M86]], 1
; CHECK-NEXT:    [[VST128IP_M87:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP80]], ptr [[VST128IP_M78]], i32 16)
; CHECK-NEXT:    [[VST128IP_M88:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP82]], ptr [[VST128IP_M87]], i32 16)
; CHECK-NEXT:    [[VST128IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP84]], ptr [[VST128IP_M88]], i32 16)
; CHECK-NEXT:    [[VST128IP_M90:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP86]], ptr [[VST128IP_M89]], i32 16)
; CHECK-NEXT:    [[VST128IP_M91:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP88]], ptr [[VST128IP_M90]], i32 16)
; CHECK-NEXT:    [[VST128IP_M92:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP90]], ptr [[VST128IP_M91]], i32 16)
; CHECK-NEXT:    [[VST128IP_M93:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP92]], ptr [[VST128IP_M92]], i32 16)
; CHECK-NEXT:    [[VST128IP_M94:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP94]], ptr [[VST128IP_M93]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M95:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP95]], i32 16)
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 0
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 1
; CHECK-NEXT:    [[VLD128IP_M96:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP97]], i32 16)
; CHECK-NEXT:    [[TMP98:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 0
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 1
; CHECK-NEXT:    [[VLD128IP_M97:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP99]], i32 16)
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M97]], 0
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M97]], 1
; CHECK-NEXT:    [[VLD128IP_M98:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP101]], i32 16)
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M98]], 0
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M98]], 1
; CHECK-NEXT:    [[VLD128IP_M99:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP103]], i32 16)
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M99]], 0
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M99]], 1
; CHECK-NEXT:    [[VLD128IP_M100:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP105]], i32 16)
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M100]], 0
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M100]], 1
; CHECK-NEXT:    [[VLD128IP_M101:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP107]], i32 16)
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M101]], 0
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M101]], 1
; CHECK-NEXT:    [[VLD128IP_M102:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP109]], i32 16)
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M102]], 0
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M102]], 1
; CHECK-NEXT:    [[VST128IP_M103:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP96]], ptr [[VST128IP_M94]], i32 16)
; CHECK-NEXT:    [[VST128IP_M104:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP98]], ptr [[VST128IP_M103]], i32 16)
; CHECK-NEXT:    [[VST128IP_M105:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP100]], ptr [[VST128IP_M104]], i32 16)
; CHECK-NEXT:    [[VST128IP_M106:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP102]], ptr [[VST128IP_M105]], i32 16)
; CHECK-NEXT:    [[VST128IP_M107:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP104]], ptr [[VST128IP_M106]], i32 16)
; CHECK-NEXT:    [[VST128IP_M108:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP106]], ptr [[VST128IP_M107]], i32 16)
; CHECK-NEXT:    [[VST128IP_M109:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP108]], ptr [[VST128IP_M108]], i32 16)
; CHECK-NEXT:    [[VST128IP_M110:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP110]], ptr [[VST128IP_M109]], i32 16)
; CHECK-NEXT:    [[VLD128IP_M111:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP111]], i32 16)
; CHECK-NEXT:    [[TMP112:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M111]], 0
; CHECK-NEXT:    [[TMP113:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M111]], 1
; CHECK-NEXT:    [[VLD128IP_M112:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP113]], i32 16)
; CHECK-NEXT:    [[TMP114:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M112]], 0
; CHECK-NEXT:    [[TMP115:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M112]], 1
; CHECK-NEXT:    [[VLD128IP_M113:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP115]], i32 16)
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M113]], 0
; CHECK-NEXT:    [[TMP117:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M113]], 1
; CHECK-NEXT:    [[VLD128IP_M114:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP117]], i32 16)
; CHECK-NEXT:    [[TMP118:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M114]], 0
; CHECK-NEXT:    [[TMP119:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M114]], 1
; CHECK-NEXT:    [[VLD128IP_M115:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP119]], i32 16)
; CHECK-NEXT:    [[TMP120:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M115]], 0
; CHECK-NEXT:    [[TMP121:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M115]], 1
; CHECK-NEXT:    [[VLD128IP_M116:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP121]], i32 16)
; CHECK-NEXT:    [[TMP122:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M116]], 0
; CHECK-NEXT:    [[TMP123:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M116]], 1
; CHECK-NEXT:    [[VLD128IP_M117:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP123]], i32 16)
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M117]], 0
; CHECK-NEXT:    [[TMP125:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M117]], 1
; CHECK-NEXT:    [[VLD128IP_M118:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP125]], i32 16)
; CHECK-NEXT:    [[TMP126:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M118]], 0
; CHECK-NEXT:    [[VST128IP_M119:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP112]], ptr [[VST128IP_M110]], i32 16)
; CHECK-NEXT:    [[VST128IP_M120:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP114]], ptr [[VST128IP_M119]], i32 16)
; CHECK-NEXT:    [[VST128IP_M121:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP116]], ptr [[VST128IP_M120]], i32 16)
; CHECK-NEXT:    [[VST128IP_M122:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP118]], ptr [[VST128IP_M121]], i32 16)
; CHECK-NEXT:    [[VST128IP_M123:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP120]], ptr [[VST128IP_M122]], i32 16)
; CHECK-NEXT:    [[VST128IP_M124:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP122]], ptr [[VST128IP_M123]], i32 16)
; CHECK-NEXT:    [[VST128IP_M125:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP124]], ptr [[VST128IP_M124]], i32 16)
; CHECK-NEXT:    [[VST128IP_M126:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP126]], ptr [[VST128IP_M125]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(1024) %a, ptr noundef nonnull align 16 dereferenceable(1024) %b, i32 1024, i1 false)
  ret void
}

define void @test_src16_dst16_size_20000(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst16_size_20000(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrc16Dst16Const16(ptr [[A]], ptr [[B]], i32 20000)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(20000) %a, ptr noundef nonnull align 16 dereferenceable(20000) %b, i32 20000, i1 false)
  ret void
}

define void @test_src16_dst8_size_1(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(1) %a, ptr noundef nonnull align 16 dereferenceable(1) %b, i32 1, i1 false)
  ret void
}

define void @test_src16_dst8_size_2(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_2(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(2) %a, ptr noundef nonnull align 16 dereferenceable(2) %b, i32 2, i1 false)
  ret void
}

define void @test_src16_dst8_size_3(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_3(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(3) %a, ptr noundef nonnull align 16 dereferenceable(3) %b, i32 3, i1 false)
  ret void
}

define void @test_src16_dst8_size_4(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_4(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(4) %a, ptr noundef nonnull align 16 dereferenceable(4) %b, i32 4, i1 false)
  ret void
}

define void @test_src16_dst8_size_5(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_5(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(5) %a, ptr noundef nonnull align 16 dereferenceable(5) %b, i32 5, i1 false)
  ret void
}

define void @test_src16_dst8_size_6(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_6(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(6) %a, ptr noundef nonnull align 16 dereferenceable(6) %b, i32 6, i1 false)
  ret void
}

define void @test_src16_dst8_size_7(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_7(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(7) %a, ptr noundef nonnull align 16 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_src16_dst8_size_8(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_8(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(8) %a, ptr noundef nonnull align 16 dereferenceable(8) %b, i32 8, i1 false)
  ret void
}

define void @test_src16_dst8_size_9(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_9(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[VSTL64IP_M]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(9) %a, ptr noundef nonnull align 16 dereferenceable(9) %b, i32 9, i1 false)
  ret void
}

define void @test_src16_dst8_size_10(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_10(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[VSTL64IP_M]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(10) %a, ptr noundef nonnull align 16 dereferenceable(10) %b, i32 10, i1 false)
  ret void
}

define void @test_src16_dst8_size_11(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_11(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[VSTL64IP_M]], align 2
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 2
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(11) %a, ptr noundef nonnull align 16 dereferenceable(11) %b, i32 11, i1 false)
  ret void
}

define void @test_src16_dst8_size_12(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_12(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(12) %a, ptr noundef nonnull align 16 dereferenceable(12) %b, i32 12, i1 false)
  ret void
}

define void @test_src16_dst8_size_13(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_13(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(13) %a, ptr noundef nonnull align 16 dereferenceable(13) %b, i32 13, i1 false)
  ret void
}

define void @test_src16_dst8_size_14(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_14(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    store i16 [[TMP5]], ptr [[TMP4]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(14) %a, ptr noundef nonnull align 16 dereferenceable(14) %b, i32 14, i1 false)
  ret void
}

define void @test_src16_dst8_size_15(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_15(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    store i16 [[TMP5]], ptr [[TMP4]], align 2
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[TMP1]], i32 6
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[TMP6]], align 1
; CHECK-NEXT:    store i8 [[TMP8]], ptr [[TMP7]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(15) %a, ptr noundef nonnull align 16 dereferenceable(15) %b, i32 15, i1 false)
  ret void
}

define void @test_src16_dst8_size_16(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP1]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(16) %a, ptr noundef nonnull align 16 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_src16_dst8_size_17(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_17(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP1]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(17) %a, ptr noundef nonnull align 16 dereferenceable(17) %b, i32 17, i1 false)
  ret void
}

define void @test_src16_dst8_size_31(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_31(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP1]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M1:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[TMP4]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP6]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[VSTL64IP_M1]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP6]], i32 4
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[VSTL64IP_M1]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[TMP8]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[TMP9]], align 2
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[TMP6]], i32 6
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[VSTL64IP_M1]], i32 6
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[TMP11]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[TMP12]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(31) %a, ptr noundef nonnull align 16 dereferenceable(31) %b, i32 31, i1 false)
  ret void
}

define void @test_src16_dst8_size_32(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_32(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP3]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP4]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M2:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M2]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(32) %a, ptr noundef nonnull align 16 dereferenceable(32) %b, i32 32, i1 false)
  ret void
}

define void @test_src16_dst8_size_33(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_33(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP3]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP4]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M2:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M2]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[TMP8]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(33) %a, ptr noundef nonnull align 16 dereferenceable(33) %b, i32 33, i1 false)
  ret void
}

define void @test_src16_dst8_size_47(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP3]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP4]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M2:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M2]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[TMP8]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[TMP10]], align 4
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[VSTL64IP_M4]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[TMP10]], i32 4
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[VSTL64IP_M4]], i32 4
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[TMP12]], align 2
; CHECK-NEXT:    store i16 [[TMP14]], ptr [[TMP13]], align 2
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[TMP10]], i32 6
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[VSTL64IP_M4]], i32 6
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[TMP15]], align 1
; CHECK-NEXT:    store i8 [[TMP17]], ptr [[TMP16]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(47) %a, ptr noundef nonnull align 16 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

define void @test_src16_dst8_size_48(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP7]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP8]], ptr [[VSTL64IP_M3]], i32 8)
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[VSTH64IP_M4]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(48) %a, ptr noundef nonnull align 16 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_src16_dst8_size_49(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_49(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP7]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP8]], ptr [[VSTL64IP_M3]], i32 8)
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[VSTH64IP_M4]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[TMP11]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[TMP12]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(49) %a, ptr noundef nonnull align 16 dereferenceable(49) %b, i32 49, i1 false)
  ret void
}

define void @test_src16_dst8_size_63(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_63(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP7]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP8]], ptr [[VSTL64IP_M3]], i32 8)
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[VSTH64IP_M4]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[TMP12]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[TMP14]], align 4
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[VSTL64IP_M7]], align 4
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[TMP14]], i32 4
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr i8, ptr [[VSTL64IP_M7]], i32 4
; CHECK-NEXT:    [[TMP18:%.*]] = load i16, ptr [[TMP16]], align 2
; CHECK-NEXT:    store i16 [[TMP18]], ptr [[TMP17]], align 2
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[TMP14]], i32 6
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i8, ptr [[VSTL64IP_M7]], i32 6
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[TMP19]], align 1
; CHECK-NEXT:    store i8 [[TMP21]], ptr [[TMP20]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(63) %a, ptr noundef nonnull align 16 dereferenceable(63) %b, i32 63, i1 false)
  ret void
}

define void @test_src16_dst8_size_64(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_64(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP7]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP8]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M4]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP11]], ptr [[VSTH64IP_M5]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP12]], ptr [[VSTL64IP_M6]], i32 8)
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[VSTH64IP_M7]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(64) %a, ptr noundef nonnull align 16 dereferenceable(64) %b, i32 64, i1 false)
  ret void
}

define void @test_src16_dst8_size_65(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_65(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP7]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP8]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M4]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP11]], ptr [[VSTH64IP_M5]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP12]], ptr [[VSTL64IP_M6]], i32 8)
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[VSTH64IP_M7]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[B]], i32 64
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[A]], i32 64
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[TMP15]], align 1
; CHECK-NEXT:    store i8 [[TMP17]], ptr [[TMP16]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(65) %a, ptr noundef nonnull align 16 dereferenceable(65) %b, i32 65, i1 false)
  ret void
}

define void @test_src16_dst8_size_80(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_80(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP11]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP12]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[VSTH64IP_M6]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP17]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(80) %a, ptr noundef nonnull align 16 dereferenceable(80) %b, i32 80, i1 false)
  ret void
}

define void @test_src16_dst8_size_81(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_81(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP11]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP12]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[VSTH64IP_M6]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP17]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[B]], i32 80
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i8, ptr [[A]], i32 80
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[TMP19]], align 1
; CHECK-NEXT:    store i8 [[TMP21]], ptr [[TMP20]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(81) %a, ptr noundef nonnull align 16 dereferenceable(81) %b, i32 81, i1 false)
  ret void
}

define void @test_src16_dst8_size_88(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_88(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP10]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP11]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP13]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP14]], ptr [[VSTH64IP_M6]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP15]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP17]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP18]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP19]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(88) %a, ptr noundef nonnull align 16 dereferenceable(88) %b, i32 88, i1 false)
  ret void
}

define void @test_src16_dst8_size_96(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_96(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP11]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP12]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M6]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[VSTH64IP_M7]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP17]], ptr [[VSTH64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M10]], i32 8)
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP19]], ptr [[VSTH64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP20]], ptr [[VSTL64IP_M12]], i32 8)
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP21]], ptr [[VSTH64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M14]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(96) %a, ptr noundef nonnull align 16 dereferenceable(96) %b, i32 96, i1 false)
  ret void
}

define void @test_src16_dst8_size_112(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_112(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP17]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP19]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP20]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP21]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP23]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP24]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP25]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(112) %a, ptr noundef nonnull align 16 dereferenceable(112) %b, i32 112, i1 false)
  ret void
}

define void @test_src16_dst8_size_124(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_124(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP17]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP19]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP20]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP21]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP23]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP24]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP25]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP29]], ptr [[TMP28]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[TMP30]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[VSTL64IP_M19]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(124) %a, ptr noundef nonnull align 16 dereferenceable(124) %b, i32 124, i1 false)
  ret void
}

define void @test_src16_dst8_size_127(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_127(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP17]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP19]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP20]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP21]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP23]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP24]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP25]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP29]], ptr [[TMP28]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[TMP30]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[VSTL64IP_M19]], align 4
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr i8, ptr [[TMP30]], i32 4
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr i8, ptr [[VSTL64IP_M19]], i32 4
; CHECK-NEXT:    [[TMP34:%.*]] = load i16, ptr [[TMP32]], align 2
; CHECK-NEXT:    store i16 [[TMP34]], ptr [[TMP33]], align 2
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr i8, ptr [[TMP30]], i32 6
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr i8, ptr [[VSTL64IP_M19]], i32 6
; CHECK-NEXT:    [[TMP37:%.*]] = load i8, ptr [[TMP35]], align 1
; CHECK-NEXT:    store i8 [[TMP37]], ptr [[TMP36]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(127) %a, ptr noundef nonnull align 16 dereferenceable(127) %b, i32 127, i1 false)
  ret void
}

define void @test_src16_dst8_size_128(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP17]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP19]], ptr [[VSTH64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP20]], ptr [[VSTL64IP_M10]], i32 8)
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP21]], ptr [[VSTH64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M12]], i32 8)
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP23]], ptr [[VSTH64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP24]], ptr [[VSTL64IP_M14]], i32 8)
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP25]], ptr [[VSTH64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M16]], i32 8)
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP27]], ptr [[VSTH64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP28]], ptr [[VSTL64IP_M18]], i32 8)
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP30:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP29]], ptr [[VSTH64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M20]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(128) %a, ptr noundef nonnull align 16 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_src16_dst8_size_129(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_129(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP15]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP16]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP17]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP19]], ptr [[VSTH64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP20]], ptr [[VSTL64IP_M10]], i32 8)
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP21]], ptr [[VSTH64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M12]], i32 8)
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP23]], ptr [[VSTH64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP24]], ptr [[VSTL64IP_M14]], i32 8)
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP25]], ptr [[VSTH64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M16]], i32 8)
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP27]], ptr [[VSTH64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP28]], ptr [[VSTL64IP_M18]], i32 8)
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP30:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP29]], ptr [[VSTH64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M20]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr i8, ptr [[B]], i32 128
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr i8, ptr [[A]], i32 128
; CHECK-NEXT:    [[TMP33:%.*]] = load i8, ptr [[TMP31]], align 1
; CHECK-NEXT:    store i8 [[TMP33]], ptr [[TMP32]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(129) %a, ptr noundef nonnull align 16 dereferenceable(129) %b, i32 129, i1 false)
  ret void
}

define void @test_src16_dst8_size_255(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_255(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 1
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP17]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP18]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP19]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP21]], ptr [[VSTL64IP_M10]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP22]], ptr [[VSTH64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP23]], ptr [[VSTL64IP_M12]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP25]], ptr [[VSTL64IP_M14]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP26]], ptr [[VSTH64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP27]], ptr [[VSTL64IP_M16]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP29]], ptr [[VSTL64IP_M18]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP31:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP30]], ptr [[VSTH64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP31]], ptr [[VSTL64IP_M20]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M22:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP15]], i32 16)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 1
; CHECK-NEXT:    [[VLD128IP_M23:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP33]], i32 16)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 1
; CHECK-NEXT:    [[VLD128IP_M24:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP35]], i32 16)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M24]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M24]], 1
; CHECK-NEXT:    [[VLD128IP_M25:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP37]], i32 16)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M25]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M25]], 1
; CHECK-NEXT:    [[VLD128IP_M26:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP39]], i32 16)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M26]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M26]], 1
; CHECK-NEXT:    [[VLD128IP_M27:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP41]], i32 16)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 1
; CHECK-NEXT:    [[VLD128IP_M28:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP43]], i32 16)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M28]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = shufflevector <16 x i8> [[TMP32]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP46:%.*]] = shufflevector <16 x i8> [[TMP32]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M29:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP45]], ptr [[VSTH64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M30:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP46]], ptr [[VSTL64IP_M29]], i32 8)
; CHECK-NEXT:    [[TMP47:%.*]] = shufflevector <16 x i8> [[TMP34]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP48:%.*]] = shufflevector <16 x i8> [[TMP34]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M31:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP47]], ptr [[VSTH64IP_M30]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M32:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP48]], ptr [[VSTL64IP_M31]], i32 8)
; CHECK-NEXT:    [[TMP49:%.*]] = shufflevector <16 x i8> [[TMP36]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP50:%.*]] = shufflevector <16 x i8> [[TMP36]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M33:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP49]], ptr [[VSTH64IP_M32]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M34:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M33]], i32 8)
; CHECK-NEXT:    [[TMP51:%.*]] = shufflevector <16 x i8> [[TMP38]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP52:%.*]] = shufflevector <16 x i8> [[TMP38]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M35:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP51]], ptr [[VSTH64IP_M34]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M36:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP52]], ptr [[VSTL64IP_M35]], i32 8)
; CHECK-NEXT:    [[TMP53:%.*]] = shufflevector <16 x i8> [[TMP40]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP54:%.*]] = shufflevector <16 x i8> [[TMP40]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M37:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP53]], ptr [[VSTH64IP_M36]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M38:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M37]], i32 8)
; CHECK-NEXT:    [[TMP55:%.*]] = shufflevector <16 x i8> [[TMP42]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP56:%.*]] = shufflevector <16 x i8> [[TMP42]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M39:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP55]], ptr [[VSTH64IP_M38]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M40:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP56]], ptr [[VSTL64IP_M39]], i32 8)
; CHECK-NEXT:    [[TMP57:%.*]] = shufflevector <16 x i8> [[TMP44]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP58:%.*]] = shufflevector <16 x i8> [[TMP44]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M41:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP57]], ptr [[VSTH64IP_M40]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M42:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M41]], i32 8)
; CHECK-NEXT:    [[TMP59:%.*]] = getelementptr i8, ptr [[B]], i32 240
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr i8, ptr [[A]], i32 240
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP59]], i32 8)
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M43:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP61]], ptr [[TMP60]], i32 8)
; CHECK-NEXT:    [[TMP63:%.*]] = load i32, ptr [[TMP62]], align 4
; CHECK-NEXT:    store i32 [[TMP63]], ptr [[VSTL64IP_M43]], align 4
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr i8, ptr [[TMP62]], i32 4
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr i8, ptr [[VSTL64IP_M43]], i32 4
; CHECK-NEXT:    [[TMP66:%.*]] = load i16, ptr [[TMP64]], align 2
; CHECK-NEXT:    store i16 [[TMP66]], ptr [[TMP65]], align 2
; CHECK-NEXT:    [[TMP67:%.*]] = getelementptr i8, ptr [[TMP62]], i32 6
; CHECK-NEXT:    [[TMP68:%.*]] = getelementptr i8, ptr [[VSTL64IP_M43]], i32 6
; CHECK-NEXT:    [[TMP69:%.*]] = load i8, ptr [[TMP67]], align 1
; CHECK-NEXT:    store i8 [[TMP69]], ptr [[TMP68]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(255) %a, ptr noundef nonnull align 16 dereferenceable(255) %b, i32 255, i1 false)
  ret void
}

define void @test_src16_dst8_size_256(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 1
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP17]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP18]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP19]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP21]], ptr [[VSTL64IP_M10]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP22]], ptr [[VSTH64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP23]], ptr [[VSTL64IP_M12]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP25]], ptr [[VSTL64IP_M14]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP26]], ptr [[VSTH64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP27]], ptr [[VSTL64IP_M16]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP29]], ptr [[VSTL64IP_M18]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP31:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP30]], ptr [[VSTH64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP31]], ptr [[VSTL64IP_M20]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M22:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP15]], i32 16)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 1
; CHECK-NEXT:    [[VLD128IP_M23:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP33]], i32 16)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 1
; CHECK-NEXT:    [[VLD128IP_M24:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP35]], i32 16)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M24]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M24]], 1
; CHECK-NEXT:    [[VLD128IP_M25:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP37]], i32 16)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M25]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M25]], 1
; CHECK-NEXT:    [[VLD128IP_M26:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP39]], i32 16)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M26]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M26]], 1
; CHECK-NEXT:    [[VLD128IP_M27:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP41]], i32 16)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 1
; CHECK-NEXT:    [[VLD128IP_M28:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP43]], i32 16)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M28]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M28]], 1
; CHECK-NEXT:    [[VLD128IP_M29:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP45]], i32 16)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M29]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = shufflevector <16 x i8> [[TMP32]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP48:%.*]] = shufflevector <16 x i8> [[TMP32]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M30:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP47]], ptr [[VSTH64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M31:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP48]], ptr [[VSTL64IP_M30]], i32 8)
; CHECK-NEXT:    [[TMP49:%.*]] = shufflevector <16 x i8> [[TMP34]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP50:%.*]] = shufflevector <16 x i8> [[TMP34]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M32:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP49]], ptr [[VSTH64IP_M31]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M33:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M32]], i32 8)
; CHECK-NEXT:    [[TMP51:%.*]] = shufflevector <16 x i8> [[TMP36]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP52:%.*]] = shufflevector <16 x i8> [[TMP36]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M34:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP51]], ptr [[VSTH64IP_M33]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M35:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP52]], ptr [[VSTL64IP_M34]], i32 8)
; CHECK-NEXT:    [[TMP53:%.*]] = shufflevector <16 x i8> [[TMP38]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP54:%.*]] = shufflevector <16 x i8> [[TMP38]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M36:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP53]], ptr [[VSTH64IP_M35]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M37:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M36]], i32 8)
; CHECK-NEXT:    [[TMP55:%.*]] = shufflevector <16 x i8> [[TMP40]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP56:%.*]] = shufflevector <16 x i8> [[TMP40]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M38:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP55]], ptr [[VSTH64IP_M37]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M39:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP56]], ptr [[VSTL64IP_M38]], i32 8)
; CHECK-NEXT:    [[TMP57:%.*]] = shufflevector <16 x i8> [[TMP42]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP58:%.*]] = shufflevector <16 x i8> [[TMP42]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M40:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP57]], ptr [[VSTH64IP_M39]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M41:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M40]], i32 8)
; CHECK-NEXT:    [[TMP59:%.*]] = shufflevector <16 x i8> [[TMP44]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP60:%.*]] = shufflevector <16 x i8> [[TMP44]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M42:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP59]], ptr [[VSTH64IP_M41]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M43:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP60]], ptr [[VSTL64IP_M42]], i32 8)
; CHECK-NEXT:    [[TMP61:%.*]] = shufflevector <16 x i8> [[TMP46]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP62:%.*]] = shufflevector <16 x i8> [[TMP46]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M44:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP61]], ptr [[VSTH64IP_M43]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP62]], ptr [[VSTL64IP_M44]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(256) %a, ptr noundef nonnull align 16 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

define void @test_src16_dst8_size_1023(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_1023(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 1
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP17]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP18]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP19]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP21]], ptr [[VSTL64IP_M10]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP22]], ptr [[VSTH64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP23]], ptr [[VSTL64IP_M12]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP25]], ptr [[VSTL64IP_M14]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP26]], ptr [[VSTH64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP27]], ptr [[VSTL64IP_M16]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP29]], ptr [[VSTL64IP_M18]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP31:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP30]], ptr [[VSTH64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP31]], ptr [[VSTL64IP_M20]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M22:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP15]], i32 16)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 1
; CHECK-NEXT:    [[VLD128IP_M23:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP33]], i32 16)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 1
; CHECK-NEXT:    [[VLD128IP_M24:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP35]], i32 16)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M24]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M24]], 1
; CHECK-NEXT:    [[VLD128IP_M25:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP37]], i32 16)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M25]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M25]], 1
; CHECK-NEXT:    [[VLD128IP_M26:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP39]], i32 16)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M26]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M26]], 1
; CHECK-NEXT:    [[VLD128IP_M27:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP41]], i32 16)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 1
; CHECK-NEXT:    [[VLD128IP_M28:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP43]], i32 16)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M28]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M28]], 1
; CHECK-NEXT:    [[VLD128IP_M29:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP45]], i32 16)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M29]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M29]], 1
; CHECK-NEXT:    [[TMP48:%.*]] = shufflevector <16 x i8> [[TMP32]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP49:%.*]] = shufflevector <16 x i8> [[TMP32]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M30:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M31:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP49]], ptr [[VSTL64IP_M30]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = shufflevector <16 x i8> [[TMP34]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP51:%.*]] = shufflevector <16 x i8> [[TMP34]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M32:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP50]], ptr [[VSTH64IP_M31]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M33:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP51]], ptr [[VSTL64IP_M32]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = shufflevector <16 x i8> [[TMP36]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP53:%.*]] = shufflevector <16 x i8> [[TMP36]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M34:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M33]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M35:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP53]], ptr [[VSTL64IP_M34]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = shufflevector <16 x i8> [[TMP38]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP55:%.*]] = shufflevector <16 x i8> [[TMP38]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M36:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP54]], ptr [[VSTH64IP_M35]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M37:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP55]], ptr [[VSTL64IP_M36]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = shufflevector <16 x i8> [[TMP40]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP57:%.*]] = shufflevector <16 x i8> [[TMP40]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M38:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M37]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M39:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP57]], ptr [[VSTL64IP_M38]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = shufflevector <16 x i8> [[TMP42]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP59:%.*]] = shufflevector <16 x i8> [[TMP42]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M40:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP58]], ptr [[VSTH64IP_M39]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M41:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP59]], ptr [[VSTL64IP_M40]], i32 8)
; CHECK-NEXT:    [[TMP60:%.*]] = shufflevector <16 x i8> [[TMP44]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP61:%.*]] = shufflevector <16 x i8> [[TMP44]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M42:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP60]], ptr [[VSTH64IP_M41]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M43:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP61]], ptr [[VSTL64IP_M42]], i32 8)
; CHECK-NEXT:    [[TMP62:%.*]] = shufflevector <16 x i8> [[TMP46]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP63:%.*]] = shufflevector <16 x i8> [[TMP46]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M44:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP62]], ptr [[VSTH64IP_M43]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP63]], ptr [[VSTL64IP_M44]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M46:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP47]], i32 16)
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M46]], 0
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M46]], 1
; CHECK-NEXT:    [[VLD128IP_M47:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP65]], i32 16)
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 0
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 1
; CHECK-NEXT:    [[VLD128IP_M48:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP67]], i32 16)
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 0
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 1
; CHECK-NEXT:    [[VLD128IP_M49:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP69]], i32 16)
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 0
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 1
; CHECK-NEXT:    [[VLD128IP_M50:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP71]], i32 16)
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 0
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 1
; CHECK-NEXT:    [[VLD128IP_M51:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP73]], i32 16)
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 0
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 1
; CHECK-NEXT:    [[VLD128IP_M52:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP75]], i32 16)
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M52]], 0
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M52]], 1
; CHECK-NEXT:    [[VLD128IP_M53:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP77]], i32 16)
; CHECK-NEXT:    [[TMP78:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 0
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 1
; CHECK-NEXT:    [[TMP80:%.*]] = shufflevector <16 x i8> [[TMP64]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP81:%.*]] = shufflevector <16 x i8> [[TMP64]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP80]], ptr [[VSTH64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP81]], ptr [[VSTL64IP_M54]], i32 8)
; CHECK-NEXT:    [[TMP82:%.*]] = shufflevector <16 x i8> [[TMP66]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP83:%.*]] = shufflevector <16 x i8> [[TMP66]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP82]], ptr [[VSTH64IP_M55]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP83]], ptr [[VSTL64IP_M56]], i32 8)
; CHECK-NEXT:    [[TMP84:%.*]] = shufflevector <16 x i8> [[TMP68]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP85:%.*]] = shufflevector <16 x i8> [[TMP68]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP84]], ptr [[VSTH64IP_M57]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP85]], ptr [[VSTL64IP_M58]], i32 8)
; CHECK-NEXT:    [[TMP86:%.*]] = shufflevector <16 x i8> [[TMP70]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP87:%.*]] = shufflevector <16 x i8> [[TMP70]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP86]], ptr [[VSTH64IP_M59]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M61:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP87]], ptr [[VSTL64IP_M60]], i32 8)
; CHECK-NEXT:    [[TMP88:%.*]] = shufflevector <16 x i8> [[TMP72]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP89:%.*]] = shufflevector <16 x i8> [[TMP72]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M62:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP88]], ptr [[VSTH64IP_M61]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M63:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP89]], ptr [[VSTL64IP_M62]], i32 8)
; CHECK-NEXT:    [[TMP90:%.*]] = shufflevector <16 x i8> [[TMP74]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP91:%.*]] = shufflevector <16 x i8> [[TMP74]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M64:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP90]], ptr [[VSTH64IP_M63]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M65:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP91]], ptr [[VSTL64IP_M64]], i32 8)
; CHECK-NEXT:    [[TMP92:%.*]] = shufflevector <16 x i8> [[TMP76]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP93:%.*]] = shufflevector <16 x i8> [[TMP76]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M66:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP92]], ptr [[VSTH64IP_M65]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M67:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP93]], ptr [[VSTL64IP_M66]], i32 8)
; CHECK-NEXT:    [[TMP94:%.*]] = shufflevector <16 x i8> [[TMP78]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP95:%.*]] = shufflevector <16 x i8> [[TMP78]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M68:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP94]], ptr [[VSTH64IP_M67]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M69:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP95]], ptr [[VSTL64IP_M68]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M70:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP79]], i32 16)
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M70]], 0
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M70]], 1
; CHECK-NEXT:    [[VLD128IP_M71:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP97]], i32 16)
; CHECK-NEXT:    [[TMP98:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M71]], 0
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M71]], 1
; CHECK-NEXT:    [[VLD128IP_M72:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP99]], i32 16)
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M72]], 0
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M72]], 1
; CHECK-NEXT:    [[VLD128IP_M73:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP101]], i32 16)
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M73]], 0
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M73]], 1
; CHECK-NEXT:    [[VLD128IP_M74:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP103]], i32 16)
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M74]], 0
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M74]], 1
; CHECK-NEXT:    [[VLD128IP_M75:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP105]], i32 16)
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M75]], 0
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M75]], 1
; CHECK-NEXT:    [[VLD128IP_M76:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP107]], i32 16)
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M76]], 0
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M76]], 1
; CHECK-NEXT:    [[VLD128IP_M77:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP109]], i32 16)
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M77]], 0
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M77]], 1
; CHECK-NEXT:    [[TMP112:%.*]] = shufflevector <16 x i8> [[TMP96]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP113:%.*]] = shufflevector <16 x i8> [[TMP96]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M78:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP112]], ptr [[VSTH64IP_M69]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M79:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP113]], ptr [[VSTL64IP_M78]], i32 8)
; CHECK-NEXT:    [[TMP114:%.*]] = shufflevector <16 x i8> [[TMP98]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP115:%.*]] = shufflevector <16 x i8> [[TMP98]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP114]], ptr [[VSTH64IP_M79]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M81:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP115]], ptr [[VSTL64IP_M80]], i32 8)
; CHECK-NEXT:    [[TMP116:%.*]] = shufflevector <16 x i8> [[TMP100]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP117:%.*]] = shufflevector <16 x i8> [[TMP100]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M82:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP116]], ptr [[VSTH64IP_M81]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M83:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP117]], ptr [[VSTL64IP_M82]], i32 8)
; CHECK-NEXT:    [[TMP118:%.*]] = shufflevector <16 x i8> [[TMP102]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP119:%.*]] = shufflevector <16 x i8> [[TMP102]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M84:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP118]], ptr [[VSTH64IP_M83]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M85:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP119]], ptr [[VSTL64IP_M84]], i32 8)
; CHECK-NEXT:    [[TMP120:%.*]] = shufflevector <16 x i8> [[TMP104]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP121:%.*]] = shufflevector <16 x i8> [[TMP104]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M86:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP120]], ptr [[VSTH64IP_M85]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M87:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP121]], ptr [[VSTL64IP_M86]], i32 8)
; CHECK-NEXT:    [[TMP122:%.*]] = shufflevector <16 x i8> [[TMP106]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP123:%.*]] = shufflevector <16 x i8> [[TMP106]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M88:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP122]], ptr [[VSTH64IP_M87]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP123]], ptr [[VSTL64IP_M88]], i32 8)
; CHECK-NEXT:    [[TMP124:%.*]] = shufflevector <16 x i8> [[TMP108]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP125:%.*]] = shufflevector <16 x i8> [[TMP108]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M90:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP124]], ptr [[VSTH64IP_M89]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M91:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP125]], ptr [[VSTL64IP_M90]], i32 8)
; CHECK-NEXT:    [[TMP126:%.*]] = shufflevector <16 x i8> [[TMP110]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP127:%.*]] = shufflevector <16 x i8> [[TMP110]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M92:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP126]], ptr [[VSTH64IP_M91]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M93:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP127]], ptr [[VSTL64IP_M92]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M94:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP111]], i32 16)
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M94]], 0
; CHECK-NEXT:    [[TMP129:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M94]], 1
; CHECK-NEXT:    [[VLD128IP_M95:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP129]], i32 16)
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 0
; CHECK-NEXT:    [[TMP131:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 1
; CHECK-NEXT:    [[VLD128IP_M96:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP131]], i32 16)
; CHECK-NEXT:    [[TMP132:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 0
; CHECK-NEXT:    [[TMP133:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 1
; CHECK-NEXT:    [[VLD128IP_M97:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP133]], i32 16)
; CHECK-NEXT:    [[TMP134:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M97]], 0
; CHECK-NEXT:    [[TMP135:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M97]], 1
; CHECK-NEXT:    [[VLD128IP_M98:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP135]], i32 16)
; CHECK-NEXT:    [[TMP136:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M98]], 0
; CHECK-NEXT:    [[TMP137:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M98]], 1
; CHECK-NEXT:    [[VLD128IP_M99:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP137]], i32 16)
; CHECK-NEXT:    [[TMP138:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M99]], 0
; CHECK-NEXT:    [[TMP139:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M99]], 1
; CHECK-NEXT:    [[VLD128IP_M100:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP139]], i32 16)
; CHECK-NEXT:    [[TMP140:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M100]], 0
; CHECK-NEXT:    [[TMP141:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M100]], 1
; CHECK-NEXT:    [[VLD128IP_M101:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP141]], i32 16)
; CHECK-NEXT:    [[TMP142:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M101]], 0
; CHECK-NEXT:    [[TMP143:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M101]], 1
; CHECK-NEXT:    [[TMP144:%.*]] = shufflevector <16 x i8> [[TMP128]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP145:%.*]] = shufflevector <16 x i8> [[TMP128]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M102:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP144]], ptr [[VSTH64IP_M93]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M103:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP145]], ptr [[VSTL64IP_M102]], i32 8)
; CHECK-NEXT:    [[TMP146:%.*]] = shufflevector <16 x i8> [[TMP130]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP147:%.*]] = shufflevector <16 x i8> [[TMP130]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M104:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP146]], ptr [[VSTH64IP_M103]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M105:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP147]], ptr [[VSTL64IP_M104]], i32 8)
; CHECK-NEXT:    [[TMP148:%.*]] = shufflevector <16 x i8> [[TMP132]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP149:%.*]] = shufflevector <16 x i8> [[TMP132]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M106:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP148]], ptr [[VSTH64IP_M105]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M107:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP149]], ptr [[VSTL64IP_M106]], i32 8)
; CHECK-NEXT:    [[TMP150:%.*]] = shufflevector <16 x i8> [[TMP134]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP151:%.*]] = shufflevector <16 x i8> [[TMP134]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M108:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP150]], ptr [[VSTH64IP_M107]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M109:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP151]], ptr [[VSTL64IP_M108]], i32 8)
; CHECK-NEXT:    [[TMP152:%.*]] = shufflevector <16 x i8> [[TMP136]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP153:%.*]] = shufflevector <16 x i8> [[TMP136]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M110:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP152]], ptr [[VSTH64IP_M109]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M111:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP153]], ptr [[VSTL64IP_M110]], i32 8)
; CHECK-NEXT:    [[TMP154:%.*]] = shufflevector <16 x i8> [[TMP138]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP155:%.*]] = shufflevector <16 x i8> [[TMP138]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M112:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP154]], ptr [[VSTH64IP_M111]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M113:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP155]], ptr [[VSTL64IP_M112]], i32 8)
; CHECK-NEXT:    [[TMP156:%.*]] = shufflevector <16 x i8> [[TMP140]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP157:%.*]] = shufflevector <16 x i8> [[TMP140]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M114:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP156]], ptr [[VSTH64IP_M113]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M115:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP157]], ptr [[VSTL64IP_M114]], i32 8)
; CHECK-NEXT:    [[TMP158:%.*]] = shufflevector <16 x i8> [[TMP142]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP159:%.*]] = shufflevector <16 x i8> [[TMP142]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M116:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP158]], ptr [[VSTH64IP_M115]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M117:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP159]], ptr [[VSTL64IP_M116]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M118:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP143]], i32 16)
; CHECK-NEXT:    [[TMP160:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M118]], 0
; CHECK-NEXT:    [[TMP161:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M118]], 1
; CHECK-NEXT:    [[VLD128IP_M119:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP161]], i32 16)
; CHECK-NEXT:    [[TMP162:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M119]], 0
; CHECK-NEXT:    [[TMP163:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M119]], 1
; CHECK-NEXT:    [[VLD128IP_M120:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP163]], i32 16)
; CHECK-NEXT:    [[TMP164:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M120]], 0
; CHECK-NEXT:    [[TMP165:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M120]], 1
; CHECK-NEXT:    [[VLD128IP_M121:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP165]], i32 16)
; CHECK-NEXT:    [[TMP166:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M121]], 0
; CHECK-NEXT:    [[TMP167:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M121]], 1
; CHECK-NEXT:    [[VLD128IP_M122:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP167]], i32 16)
; CHECK-NEXT:    [[TMP168:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M122]], 0
; CHECK-NEXT:    [[TMP169:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M122]], 1
; CHECK-NEXT:    [[VLD128IP_M123:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP169]], i32 16)
; CHECK-NEXT:    [[TMP170:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M123]], 0
; CHECK-NEXT:    [[TMP171:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M123]], 1
; CHECK-NEXT:    [[VLD128IP_M124:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP171]], i32 16)
; CHECK-NEXT:    [[TMP172:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M124]], 0
; CHECK-NEXT:    [[TMP173:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M124]], 1
; CHECK-NEXT:    [[VLD128IP_M125:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP173]], i32 16)
; CHECK-NEXT:    [[TMP174:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M125]], 0
; CHECK-NEXT:    [[TMP175:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M125]], 1
; CHECK-NEXT:    [[TMP176:%.*]] = shufflevector <16 x i8> [[TMP160]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP177:%.*]] = shufflevector <16 x i8> [[TMP160]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M126:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP176]], ptr [[VSTH64IP_M117]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M127:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP177]], ptr [[VSTL64IP_M126]], i32 8)
; CHECK-NEXT:    [[TMP178:%.*]] = shufflevector <16 x i8> [[TMP162]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP179:%.*]] = shufflevector <16 x i8> [[TMP162]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M128:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP178]], ptr [[VSTH64IP_M127]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M129:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP179]], ptr [[VSTL64IP_M128]], i32 8)
; CHECK-NEXT:    [[TMP180:%.*]] = shufflevector <16 x i8> [[TMP164]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP181:%.*]] = shufflevector <16 x i8> [[TMP164]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M130:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP180]], ptr [[VSTH64IP_M129]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M131:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP181]], ptr [[VSTL64IP_M130]], i32 8)
; CHECK-NEXT:    [[TMP182:%.*]] = shufflevector <16 x i8> [[TMP166]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP183:%.*]] = shufflevector <16 x i8> [[TMP166]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M132:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP182]], ptr [[VSTH64IP_M131]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M133:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP183]], ptr [[VSTL64IP_M132]], i32 8)
; CHECK-NEXT:    [[TMP184:%.*]] = shufflevector <16 x i8> [[TMP168]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP185:%.*]] = shufflevector <16 x i8> [[TMP168]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M134:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP184]], ptr [[VSTH64IP_M133]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M135:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP185]], ptr [[VSTL64IP_M134]], i32 8)
; CHECK-NEXT:    [[TMP186:%.*]] = shufflevector <16 x i8> [[TMP170]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP187:%.*]] = shufflevector <16 x i8> [[TMP170]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M136:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP186]], ptr [[VSTH64IP_M135]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M137:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP187]], ptr [[VSTL64IP_M136]], i32 8)
; CHECK-NEXT:    [[TMP188:%.*]] = shufflevector <16 x i8> [[TMP172]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP189:%.*]] = shufflevector <16 x i8> [[TMP172]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M138:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP188]], ptr [[VSTH64IP_M137]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M139:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP189]], ptr [[VSTL64IP_M138]], i32 8)
; CHECK-NEXT:    [[TMP190:%.*]] = shufflevector <16 x i8> [[TMP174]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP191:%.*]] = shufflevector <16 x i8> [[TMP174]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M140:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP190]], ptr [[VSTH64IP_M139]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M141:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP191]], ptr [[VSTL64IP_M140]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M142:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP175]], i32 16)
; CHECK-NEXT:    [[TMP192:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M142]], 0
; CHECK-NEXT:    [[TMP193:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M142]], 1
; CHECK-NEXT:    [[VLD128IP_M143:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP193]], i32 16)
; CHECK-NEXT:    [[TMP194:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M143]], 0
; CHECK-NEXT:    [[TMP195:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M143]], 1
; CHECK-NEXT:    [[VLD128IP_M144:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP195]], i32 16)
; CHECK-NEXT:    [[TMP196:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M144]], 0
; CHECK-NEXT:    [[TMP197:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M144]], 1
; CHECK-NEXT:    [[VLD128IP_M145:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP197]], i32 16)
; CHECK-NEXT:    [[TMP198:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M145]], 0
; CHECK-NEXT:    [[TMP199:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M145]], 1
; CHECK-NEXT:    [[VLD128IP_M146:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP199]], i32 16)
; CHECK-NEXT:    [[TMP200:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M146]], 0
; CHECK-NEXT:    [[TMP201:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M146]], 1
; CHECK-NEXT:    [[VLD128IP_M147:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP201]], i32 16)
; CHECK-NEXT:    [[TMP202:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M147]], 0
; CHECK-NEXT:    [[TMP203:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M147]], 1
; CHECK-NEXT:    [[VLD128IP_M148:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP203]], i32 16)
; CHECK-NEXT:    [[TMP204:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M148]], 0
; CHECK-NEXT:    [[TMP205:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M148]], 1
; CHECK-NEXT:    [[VLD128IP_M149:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP205]], i32 16)
; CHECK-NEXT:    [[TMP206:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M149]], 0
; CHECK-NEXT:    [[TMP207:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M149]], 1
; CHECK-NEXT:    [[TMP208:%.*]] = shufflevector <16 x i8> [[TMP192]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP209:%.*]] = shufflevector <16 x i8> [[TMP192]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M150:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP208]], ptr [[VSTH64IP_M141]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M151:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP209]], ptr [[VSTL64IP_M150]], i32 8)
; CHECK-NEXT:    [[TMP210:%.*]] = shufflevector <16 x i8> [[TMP194]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP211:%.*]] = shufflevector <16 x i8> [[TMP194]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M152:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP210]], ptr [[VSTH64IP_M151]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M153:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP211]], ptr [[VSTL64IP_M152]], i32 8)
; CHECK-NEXT:    [[TMP212:%.*]] = shufflevector <16 x i8> [[TMP196]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP213:%.*]] = shufflevector <16 x i8> [[TMP196]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M154:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP212]], ptr [[VSTH64IP_M153]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M155:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP213]], ptr [[VSTL64IP_M154]], i32 8)
; CHECK-NEXT:    [[TMP214:%.*]] = shufflevector <16 x i8> [[TMP198]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP215:%.*]] = shufflevector <16 x i8> [[TMP198]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M156:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP214]], ptr [[VSTH64IP_M155]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M157:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP215]], ptr [[VSTL64IP_M156]], i32 8)
; CHECK-NEXT:    [[TMP216:%.*]] = shufflevector <16 x i8> [[TMP200]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP217:%.*]] = shufflevector <16 x i8> [[TMP200]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M158:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP216]], ptr [[VSTH64IP_M157]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M159:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP217]], ptr [[VSTL64IP_M158]], i32 8)
; CHECK-NEXT:    [[TMP218:%.*]] = shufflevector <16 x i8> [[TMP202]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP219:%.*]] = shufflevector <16 x i8> [[TMP202]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M160:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP218]], ptr [[VSTH64IP_M159]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M161:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP219]], ptr [[VSTL64IP_M160]], i32 8)
; CHECK-NEXT:    [[TMP220:%.*]] = shufflevector <16 x i8> [[TMP204]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP221:%.*]] = shufflevector <16 x i8> [[TMP204]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M162:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP220]], ptr [[VSTH64IP_M161]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M163:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP221]], ptr [[VSTL64IP_M162]], i32 8)
; CHECK-NEXT:    [[TMP222:%.*]] = shufflevector <16 x i8> [[TMP206]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP223:%.*]] = shufflevector <16 x i8> [[TMP206]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M164:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP222]], ptr [[VSTH64IP_M163]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M165:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP223]], ptr [[VSTL64IP_M164]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M166:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP207]], i32 16)
; CHECK-NEXT:    [[TMP224:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M166]], 0
; CHECK-NEXT:    [[TMP225:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M166]], 1
; CHECK-NEXT:    [[VLD128IP_M167:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP225]], i32 16)
; CHECK-NEXT:    [[TMP226:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M167]], 0
; CHECK-NEXT:    [[TMP227:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M167]], 1
; CHECK-NEXT:    [[VLD128IP_M168:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP227]], i32 16)
; CHECK-NEXT:    [[TMP228:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M168]], 0
; CHECK-NEXT:    [[TMP229:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M168]], 1
; CHECK-NEXT:    [[VLD128IP_M169:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP229]], i32 16)
; CHECK-NEXT:    [[TMP230:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M169]], 0
; CHECK-NEXT:    [[TMP231:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M169]], 1
; CHECK-NEXT:    [[VLD128IP_M170:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP231]], i32 16)
; CHECK-NEXT:    [[TMP232:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M170]], 0
; CHECK-NEXT:    [[TMP233:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M170]], 1
; CHECK-NEXT:    [[VLD128IP_M171:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP233]], i32 16)
; CHECK-NEXT:    [[TMP234:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M171]], 0
; CHECK-NEXT:    [[TMP235:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M171]], 1
; CHECK-NEXT:    [[VLD128IP_M172:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP235]], i32 16)
; CHECK-NEXT:    [[TMP236:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M172]], 0
; CHECK-NEXT:    [[TMP237:%.*]] = shufflevector <16 x i8> [[TMP224]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP238:%.*]] = shufflevector <16 x i8> [[TMP224]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M173:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP237]], ptr [[VSTH64IP_M165]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M174:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP238]], ptr [[VSTL64IP_M173]], i32 8)
; CHECK-NEXT:    [[TMP239:%.*]] = shufflevector <16 x i8> [[TMP226]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP240:%.*]] = shufflevector <16 x i8> [[TMP226]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M175:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP239]], ptr [[VSTH64IP_M174]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M176:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP240]], ptr [[VSTL64IP_M175]], i32 8)
; CHECK-NEXT:    [[TMP241:%.*]] = shufflevector <16 x i8> [[TMP228]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP242:%.*]] = shufflevector <16 x i8> [[TMP228]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M177:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP241]], ptr [[VSTH64IP_M176]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M178:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP242]], ptr [[VSTL64IP_M177]], i32 8)
; CHECK-NEXT:    [[TMP243:%.*]] = shufflevector <16 x i8> [[TMP230]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP244:%.*]] = shufflevector <16 x i8> [[TMP230]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M179:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP243]], ptr [[VSTH64IP_M178]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M180:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP244]], ptr [[VSTL64IP_M179]], i32 8)
; CHECK-NEXT:    [[TMP245:%.*]] = shufflevector <16 x i8> [[TMP232]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP246:%.*]] = shufflevector <16 x i8> [[TMP232]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M181:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP245]], ptr [[VSTH64IP_M180]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M182:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP246]], ptr [[VSTL64IP_M181]], i32 8)
; CHECK-NEXT:    [[TMP247:%.*]] = shufflevector <16 x i8> [[TMP234]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP248:%.*]] = shufflevector <16 x i8> [[TMP234]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M183:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP247]], ptr [[VSTH64IP_M182]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M184:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP248]], ptr [[VSTL64IP_M183]], i32 8)
; CHECK-NEXT:    [[TMP249:%.*]] = shufflevector <16 x i8> [[TMP236]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP250:%.*]] = shufflevector <16 x i8> [[TMP236]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M185:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP249]], ptr [[VSTH64IP_M184]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M186:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP250]], ptr [[VSTL64IP_M185]], i32 8)
; CHECK-NEXT:    [[TMP251:%.*]] = getelementptr i8, ptr [[B]], i32 1008
; CHECK-NEXT:    [[TMP252:%.*]] = getelementptr i8, ptr [[A]], i32 1008
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP251]], i32 8)
; CHECK-NEXT:    [[TMP253:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP254:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M187:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP253]], ptr [[TMP252]], i32 8)
; CHECK-NEXT:    [[TMP255:%.*]] = load i32, ptr [[TMP254]], align 4
; CHECK-NEXT:    store i32 [[TMP255]], ptr [[VSTL64IP_M187]], align 4
; CHECK-NEXT:    [[TMP256:%.*]] = getelementptr i8, ptr [[TMP254]], i32 4
; CHECK-NEXT:    [[TMP257:%.*]] = getelementptr i8, ptr [[VSTL64IP_M187]], i32 4
; CHECK-NEXT:    [[TMP258:%.*]] = load i16, ptr [[TMP256]], align 2
; CHECK-NEXT:    store i16 [[TMP258]], ptr [[TMP257]], align 2
; CHECK-NEXT:    [[TMP259:%.*]] = getelementptr i8, ptr [[TMP254]], i32 6
; CHECK-NEXT:    [[TMP260:%.*]] = getelementptr i8, ptr [[VSTL64IP_M187]], i32 6
; CHECK-NEXT:    [[TMP261:%.*]] = load i8, ptr [[TMP259]], align 1
; CHECK-NEXT:    store i8 [[TMP261]], ptr [[TMP260]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(1023) %a, ptr noundef nonnull align 16 dereferenceable(1023) %b, i32 1023, i1 false)
  ret void
}

define void @test_src16_dst8_size_1024(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_1024(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VLD128IP_M1:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M1]], 1
; CHECK-NEXT:    [[VLD128IP_M2:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M2]], 1
; CHECK-NEXT:    [[VLD128IP_M3:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP5]], i32 16)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M3]], 1
; CHECK-NEXT:    [[VLD128IP_M4:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M4]], 1
; CHECK-NEXT:    [[VLD128IP_M5:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP9]], i32 16)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M5]], 1
; CHECK-NEXT:    [[VLD128IP_M6:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP11]], i32 16)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M6]], 1
; CHECK-NEXT:    [[VLD128IP_M7:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP13]], i32 16)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M7]], 1
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i8> [[TMP0]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP17]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <16 x i8> [[TMP2]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP18]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP19]], ptr [[VSTL64IP_M8]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i8> [[TMP4]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP21]], ptr [[VSTL64IP_M10]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP6]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP22]], ptr [[VSTH64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP23]], ptr [[VSTL64IP_M12]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP25]], ptr [[VSTL64IP_M14]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <16 x i8> [[TMP10]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP26]], ptr [[VSTH64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP27]], ptr [[VSTL64IP_M16]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP29]], ptr [[VSTL64IP_M18]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP31:%.*]] = shufflevector <16 x i8> [[TMP14]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP30]], ptr [[VSTH64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP31]], ptr [[VSTL64IP_M20]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M22:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP15]], i32 16)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M22]], 1
; CHECK-NEXT:    [[VLD128IP_M23:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP33]], i32 16)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M23]], 1
; CHECK-NEXT:    [[VLD128IP_M24:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP35]], i32 16)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M24]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M24]], 1
; CHECK-NEXT:    [[VLD128IP_M25:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP37]], i32 16)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M25]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M25]], 1
; CHECK-NEXT:    [[VLD128IP_M26:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP39]], i32 16)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M26]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M26]], 1
; CHECK-NEXT:    [[VLD128IP_M27:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP41]], i32 16)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M27]], 1
; CHECK-NEXT:    [[VLD128IP_M28:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP43]], i32 16)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M28]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M28]], 1
; CHECK-NEXT:    [[VLD128IP_M29:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP45]], i32 16)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M29]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M29]], 1
; CHECK-NEXT:    [[TMP48:%.*]] = shufflevector <16 x i8> [[TMP32]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP49:%.*]] = shufflevector <16 x i8> [[TMP32]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M30:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M31:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP49]], ptr [[VSTL64IP_M30]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = shufflevector <16 x i8> [[TMP34]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP51:%.*]] = shufflevector <16 x i8> [[TMP34]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M32:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP50]], ptr [[VSTH64IP_M31]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M33:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP51]], ptr [[VSTL64IP_M32]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = shufflevector <16 x i8> [[TMP36]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP53:%.*]] = shufflevector <16 x i8> [[TMP36]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M34:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M33]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M35:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP53]], ptr [[VSTL64IP_M34]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = shufflevector <16 x i8> [[TMP38]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP55:%.*]] = shufflevector <16 x i8> [[TMP38]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M36:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP54]], ptr [[VSTH64IP_M35]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M37:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP55]], ptr [[VSTL64IP_M36]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = shufflevector <16 x i8> [[TMP40]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP57:%.*]] = shufflevector <16 x i8> [[TMP40]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M38:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M37]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M39:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP57]], ptr [[VSTL64IP_M38]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = shufflevector <16 x i8> [[TMP42]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP59:%.*]] = shufflevector <16 x i8> [[TMP42]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M40:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP58]], ptr [[VSTH64IP_M39]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M41:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP59]], ptr [[VSTL64IP_M40]], i32 8)
; CHECK-NEXT:    [[TMP60:%.*]] = shufflevector <16 x i8> [[TMP44]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP61:%.*]] = shufflevector <16 x i8> [[TMP44]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M42:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP60]], ptr [[VSTH64IP_M41]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M43:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP61]], ptr [[VSTL64IP_M42]], i32 8)
; CHECK-NEXT:    [[TMP62:%.*]] = shufflevector <16 x i8> [[TMP46]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP63:%.*]] = shufflevector <16 x i8> [[TMP46]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M44:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP62]], ptr [[VSTH64IP_M43]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP63]], ptr [[VSTL64IP_M44]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M46:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP47]], i32 16)
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M46]], 0
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M46]], 1
; CHECK-NEXT:    [[VLD128IP_M47:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP65]], i32 16)
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 0
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M47]], 1
; CHECK-NEXT:    [[VLD128IP_M48:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP67]], i32 16)
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 0
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M48]], 1
; CHECK-NEXT:    [[VLD128IP_M49:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP69]], i32 16)
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 0
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M49]], 1
; CHECK-NEXT:    [[VLD128IP_M50:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP71]], i32 16)
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 0
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M50]], 1
; CHECK-NEXT:    [[VLD128IP_M51:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP73]], i32 16)
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 0
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M51]], 1
; CHECK-NEXT:    [[VLD128IP_M52:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP75]], i32 16)
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M52]], 0
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M52]], 1
; CHECK-NEXT:    [[VLD128IP_M53:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP77]], i32 16)
; CHECK-NEXT:    [[TMP78:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 0
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M53]], 1
; CHECK-NEXT:    [[TMP80:%.*]] = shufflevector <16 x i8> [[TMP64]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP81:%.*]] = shufflevector <16 x i8> [[TMP64]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP80]], ptr [[VSTH64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP81]], ptr [[VSTL64IP_M54]], i32 8)
; CHECK-NEXT:    [[TMP82:%.*]] = shufflevector <16 x i8> [[TMP66]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP83:%.*]] = shufflevector <16 x i8> [[TMP66]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP82]], ptr [[VSTH64IP_M55]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP83]], ptr [[VSTL64IP_M56]], i32 8)
; CHECK-NEXT:    [[TMP84:%.*]] = shufflevector <16 x i8> [[TMP68]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP85:%.*]] = shufflevector <16 x i8> [[TMP68]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP84]], ptr [[VSTH64IP_M57]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP85]], ptr [[VSTL64IP_M58]], i32 8)
; CHECK-NEXT:    [[TMP86:%.*]] = shufflevector <16 x i8> [[TMP70]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP87:%.*]] = shufflevector <16 x i8> [[TMP70]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP86]], ptr [[VSTH64IP_M59]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M61:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP87]], ptr [[VSTL64IP_M60]], i32 8)
; CHECK-NEXT:    [[TMP88:%.*]] = shufflevector <16 x i8> [[TMP72]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP89:%.*]] = shufflevector <16 x i8> [[TMP72]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M62:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP88]], ptr [[VSTH64IP_M61]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M63:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP89]], ptr [[VSTL64IP_M62]], i32 8)
; CHECK-NEXT:    [[TMP90:%.*]] = shufflevector <16 x i8> [[TMP74]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP91:%.*]] = shufflevector <16 x i8> [[TMP74]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M64:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP90]], ptr [[VSTH64IP_M63]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M65:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP91]], ptr [[VSTL64IP_M64]], i32 8)
; CHECK-NEXT:    [[TMP92:%.*]] = shufflevector <16 x i8> [[TMP76]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP93:%.*]] = shufflevector <16 x i8> [[TMP76]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M66:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP92]], ptr [[VSTH64IP_M65]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M67:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP93]], ptr [[VSTL64IP_M66]], i32 8)
; CHECK-NEXT:    [[TMP94:%.*]] = shufflevector <16 x i8> [[TMP78]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP95:%.*]] = shufflevector <16 x i8> [[TMP78]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M68:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP94]], ptr [[VSTH64IP_M67]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M69:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP95]], ptr [[VSTL64IP_M68]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M70:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP79]], i32 16)
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M70]], 0
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M70]], 1
; CHECK-NEXT:    [[VLD128IP_M71:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP97]], i32 16)
; CHECK-NEXT:    [[TMP98:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M71]], 0
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M71]], 1
; CHECK-NEXT:    [[VLD128IP_M72:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP99]], i32 16)
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M72]], 0
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M72]], 1
; CHECK-NEXT:    [[VLD128IP_M73:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP101]], i32 16)
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M73]], 0
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M73]], 1
; CHECK-NEXT:    [[VLD128IP_M74:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP103]], i32 16)
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M74]], 0
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M74]], 1
; CHECK-NEXT:    [[VLD128IP_M75:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP105]], i32 16)
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M75]], 0
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M75]], 1
; CHECK-NEXT:    [[VLD128IP_M76:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP107]], i32 16)
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M76]], 0
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M76]], 1
; CHECK-NEXT:    [[VLD128IP_M77:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP109]], i32 16)
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M77]], 0
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M77]], 1
; CHECK-NEXT:    [[TMP112:%.*]] = shufflevector <16 x i8> [[TMP96]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP113:%.*]] = shufflevector <16 x i8> [[TMP96]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M78:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP112]], ptr [[VSTH64IP_M69]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M79:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP113]], ptr [[VSTL64IP_M78]], i32 8)
; CHECK-NEXT:    [[TMP114:%.*]] = shufflevector <16 x i8> [[TMP98]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP115:%.*]] = shufflevector <16 x i8> [[TMP98]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP114]], ptr [[VSTH64IP_M79]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M81:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP115]], ptr [[VSTL64IP_M80]], i32 8)
; CHECK-NEXT:    [[TMP116:%.*]] = shufflevector <16 x i8> [[TMP100]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP117:%.*]] = shufflevector <16 x i8> [[TMP100]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M82:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP116]], ptr [[VSTH64IP_M81]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M83:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP117]], ptr [[VSTL64IP_M82]], i32 8)
; CHECK-NEXT:    [[TMP118:%.*]] = shufflevector <16 x i8> [[TMP102]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP119:%.*]] = shufflevector <16 x i8> [[TMP102]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M84:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP118]], ptr [[VSTH64IP_M83]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M85:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP119]], ptr [[VSTL64IP_M84]], i32 8)
; CHECK-NEXT:    [[TMP120:%.*]] = shufflevector <16 x i8> [[TMP104]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP121:%.*]] = shufflevector <16 x i8> [[TMP104]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M86:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP120]], ptr [[VSTH64IP_M85]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M87:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP121]], ptr [[VSTL64IP_M86]], i32 8)
; CHECK-NEXT:    [[TMP122:%.*]] = shufflevector <16 x i8> [[TMP106]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP123:%.*]] = shufflevector <16 x i8> [[TMP106]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M88:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP122]], ptr [[VSTH64IP_M87]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP123]], ptr [[VSTL64IP_M88]], i32 8)
; CHECK-NEXT:    [[TMP124:%.*]] = shufflevector <16 x i8> [[TMP108]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP125:%.*]] = shufflevector <16 x i8> [[TMP108]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M90:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP124]], ptr [[VSTH64IP_M89]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M91:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP125]], ptr [[VSTL64IP_M90]], i32 8)
; CHECK-NEXT:    [[TMP126:%.*]] = shufflevector <16 x i8> [[TMP110]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP127:%.*]] = shufflevector <16 x i8> [[TMP110]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M92:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP126]], ptr [[VSTH64IP_M91]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M93:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP127]], ptr [[VSTL64IP_M92]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M94:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP111]], i32 16)
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M94]], 0
; CHECK-NEXT:    [[TMP129:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M94]], 1
; CHECK-NEXT:    [[VLD128IP_M95:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP129]], i32 16)
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 0
; CHECK-NEXT:    [[TMP131:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M95]], 1
; CHECK-NEXT:    [[VLD128IP_M96:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP131]], i32 16)
; CHECK-NEXT:    [[TMP132:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 0
; CHECK-NEXT:    [[TMP133:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M96]], 1
; CHECK-NEXT:    [[VLD128IP_M97:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP133]], i32 16)
; CHECK-NEXT:    [[TMP134:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M97]], 0
; CHECK-NEXT:    [[TMP135:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M97]], 1
; CHECK-NEXT:    [[VLD128IP_M98:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP135]], i32 16)
; CHECK-NEXT:    [[TMP136:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M98]], 0
; CHECK-NEXT:    [[TMP137:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M98]], 1
; CHECK-NEXT:    [[VLD128IP_M99:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP137]], i32 16)
; CHECK-NEXT:    [[TMP138:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M99]], 0
; CHECK-NEXT:    [[TMP139:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M99]], 1
; CHECK-NEXT:    [[VLD128IP_M100:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP139]], i32 16)
; CHECK-NEXT:    [[TMP140:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M100]], 0
; CHECK-NEXT:    [[TMP141:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M100]], 1
; CHECK-NEXT:    [[VLD128IP_M101:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP141]], i32 16)
; CHECK-NEXT:    [[TMP142:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M101]], 0
; CHECK-NEXT:    [[TMP143:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M101]], 1
; CHECK-NEXT:    [[TMP144:%.*]] = shufflevector <16 x i8> [[TMP128]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP145:%.*]] = shufflevector <16 x i8> [[TMP128]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M102:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP144]], ptr [[VSTH64IP_M93]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M103:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP145]], ptr [[VSTL64IP_M102]], i32 8)
; CHECK-NEXT:    [[TMP146:%.*]] = shufflevector <16 x i8> [[TMP130]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP147:%.*]] = shufflevector <16 x i8> [[TMP130]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M104:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP146]], ptr [[VSTH64IP_M103]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M105:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP147]], ptr [[VSTL64IP_M104]], i32 8)
; CHECK-NEXT:    [[TMP148:%.*]] = shufflevector <16 x i8> [[TMP132]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP149:%.*]] = shufflevector <16 x i8> [[TMP132]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M106:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP148]], ptr [[VSTH64IP_M105]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M107:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP149]], ptr [[VSTL64IP_M106]], i32 8)
; CHECK-NEXT:    [[TMP150:%.*]] = shufflevector <16 x i8> [[TMP134]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP151:%.*]] = shufflevector <16 x i8> [[TMP134]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M108:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP150]], ptr [[VSTH64IP_M107]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M109:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP151]], ptr [[VSTL64IP_M108]], i32 8)
; CHECK-NEXT:    [[TMP152:%.*]] = shufflevector <16 x i8> [[TMP136]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP153:%.*]] = shufflevector <16 x i8> [[TMP136]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M110:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP152]], ptr [[VSTH64IP_M109]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M111:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP153]], ptr [[VSTL64IP_M110]], i32 8)
; CHECK-NEXT:    [[TMP154:%.*]] = shufflevector <16 x i8> [[TMP138]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP155:%.*]] = shufflevector <16 x i8> [[TMP138]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M112:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP154]], ptr [[VSTH64IP_M111]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M113:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP155]], ptr [[VSTL64IP_M112]], i32 8)
; CHECK-NEXT:    [[TMP156:%.*]] = shufflevector <16 x i8> [[TMP140]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP157:%.*]] = shufflevector <16 x i8> [[TMP140]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M114:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP156]], ptr [[VSTH64IP_M113]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M115:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP157]], ptr [[VSTL64IP_M114]], i32 8)
; CHECK-NEXT:    [[TMP158:%.*]] = shufflevector <16 x i8> [[TMP142]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP159:%.*]] = shufflevector <16 x i8> [[TMP142]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M116:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP158]], ptr [[VSTH64IP_M115]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M117:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP159]], ptr [[VSTL64IP_M116]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M118:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP143]], i32 16)
; CHECK-NEXT:    [[TMP160:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M118]], 0
; CHECK-NEXT:    [[TMP161:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M118]], 1
; CHECK-NEXT:    [[VLD128IP_M119:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP161]], i32 16)
; CHECK-NEXT:    [[TMP162:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M119]], 0
; CHECK-NEXT:    [[TMP163:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M119]], 1
; CHECK-NEXT:    [[VLD128IP_M120:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP163]], i32 16)
; CHECK-NEXT:    [[TMP164:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M120]], 0
; CHECK-NEXT:    [[TMP165:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M120]], 1
; CHECK-NEXT:    [[VLD128IP_M121:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP165]], i32 16)
; CHECK-NEXT:    [[TMP166:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M121]], 0
; CHECK-NEXT:    [[TMP167:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M121]], 1
; CHECK-NEXT:    [[VLD128IP_M122:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP167]], i32 16)
; CHECK-NEXT:    [[TMP168:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M122]], 0
; CHECK-NEXT:    [[TMP169:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M122]], 1
; CHECK-NEXT:    [[VLD128IP_M123:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP169]], i32 16)
; CHECK-NEXT:    [[TMP170:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M123]], 0
; CHECK-NEXT:    [[TMP171:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M123]], 1
; CHECK-NEXT:    [[VLD128IP_M124:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP171]], i32 16)
; CHECK-NEXT:    [[TMP172:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M124]], 0
; CHECK-NEXT:    [[TMP173:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M124]], 1
; CHECK-NEXT:    [[VLD128IP_M125:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP173]], i32 16)
; CHECK-NEXT:    [[TMP174:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M125]], 0
; CHECK-NEXT:    [[TMP175:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M125]], 1
; CHECK-NEXT:    [[TMP176:%.*]] = shufflevector <16 x i8> [[TMP160]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP177:%.*]] = shufflevector <16 x i8> [[TMP160]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M126:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP176]], ptr [[VSTH64IP_M117]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M127:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP177]], ptr [[VSTL64IP_M126]], i32 8)
; CHECK-NEXT:    [[TMP178:%.*]] = shufflevector <16 x i8> [[TMP162]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP179:%.*]] = shufflevector <16 x i8> [[TMP162]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M128:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP178]], ptr [[VSTH64IP_M127]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M129:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP179]], ptr [[VSTL64IP_M128]], i32 8)
; CHECK-NEXT:    [[TMP180:%.*]] = shufflevector <16 x i8> [[TMP164]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP181:%.*]] = shufflevector <16 x i8> [[TMP164]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M130:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP180]], ptr [[VSTH64IP_M129]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M131:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP181]], ptr [[VSTL64IP_M130]], i32 8)
; CHECK-NEXT:    [[TMP182:%.*]] = shufflevector <16 x i8> [[TMP166]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP183:%.*]] = shufflevector <16 x i8> [[TMP166]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M132:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP182]], ptr [[VSTH64IP_M131]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M133:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP183]], ptr [[VSTL64IP_M132]], i32 8)
; CHECK-NEXT:    [[TMP184:%.*]] = shufflevector <16 x i8> [[TMP168]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP185:%.*]] = shufflevector <16 x i8> [[TMP168]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M134:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP184]], ptr [[VSTH64IP_M133]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M135:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP185]], ptr [[VSTL64IP_M134]], i32 8)
; CHECK-NEXT:    [[TMP186:%.*]] = shufflevector <16 x i8> [[TMP170]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP187:%.*]] = shufflevector <16 x i8> [[TMP170]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M136:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP186]], ptr [[VSTH64IP_M135]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M137:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP187]], ptr [[VSTL64IP_M136]], i32 8)
; CHECK-NEXT:    [[TMP188:%.*]] = shufflevector <16 x i8> [[TMP172]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP189:%.*]] = shufflevector <16 x i8> [[TMP172]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M138:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP188]], ptr [[VSTH64IP_M137]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M139:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP189]], ptr [[VSTL64IP_M138]], i32 8)
; CHECK-NEXT:    [[TMP190:%.*]] = shufflevector <16 x i8> [[TMP174]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP191:%.*]] = shufflevector <16 x i8> [[TMP174]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M140:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP190]], ptr [[VSTH64IP_M139]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M141:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP191]], ptr [[VSTL64IP_M140]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M142:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP175]], i32 16)
; CHECK-NEXT:    [[TMP192:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M142]], 0
; CHECK-NEXT:    [[TMP193:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M142]], 1
; CHECK-NEXT:    [[VLD128IP_M143:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP193]], i32 16)
; CHECK-NEXT:    [[TMP194:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M143]], 0
; CHECK-NEXT:    [[TMP195:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M143]], 1
; CHECK-NEXT:    [[VLD128IP_M144:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP195]], i32 16)
; CHECK-NEXT:    [[TMP196:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M144]], 0
; CHECK-NEXT:    [[TMP197:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M144]], 1
; CHECK-NEXT:    [[VLD128IP_M145:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP197]], i32 16)
; CHECK-NEXT:    [[TMP198:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M145]], 0
; CHECK-NEXT:    [[TMP199:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M145]], 1
; CHECK-NEXT:    [[VLD128IP_M146:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP199]], i32 16)
; CHECK-NEXT:    [[TMP200:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M146]], 0
; CHECK-NEXT:    [[TMP201:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M146]], 1
; CHECK-NEXT:    [[VLD128IP_M147:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP201]], i32 16)
; CHECK-NEXT:    [[TMP202:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M147]], 0
; CHECK-NEXT:    [[TMP203:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M147]], 1
; CHECK-NEXT:    [[VLD128IP_M148:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP203]], i32 16)
; CHECK-NEXT:    [[TMP204:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M148]], 0
; CHECK-NEXT:    [[TMP205:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M148]], 1
; CHECK-NEXT:    [[VLD128IP_M149:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP205]], i32 16)
; CHECK-NEXT:    [[TMP206:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M149]], 0
; CHECK-NEXT:    [[TMP207:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M149]], 1
; CHECK-NEXT:    [[TMP208:%.*]] = shufflevector <16 x i8> [[TMP192]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP209:%.*]] = shufflevector <16 x i8> [[TMP192]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M150:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP208]], ptr [[VSTH64IP_M141]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M151:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP209]], ptr [[VSTL64IP_M150]], i32 8)
; CHECK-NEXT:    [[TMP210:%.*]] = shufflevector <16 x i8> [[TMP194]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP211:%.*]] = shufflevector <16 x i8> [[TMP194]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M152:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP210]], ptr [[VSTH64IP_M151]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M153:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP211]], ptr [[VSTL64IP_M152]], i32 8)
; CHECK-NEXT:    [[TMP212:%.*]] = shufflevector <16 x i8> [[TMP196]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP213:%.*]] = shufflevector <16 x i8> [[TMP196]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M154:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP212]], ptr [[VSTH64IP_M153]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M155:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP213]], ptr [[VSTL64IP_M154]], i32 8)
; CHECK-NEXT:    [[TMP214:%.*]] = shufflevector <16 x i8> [[TMP198]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP215:%.*]] = shufflevector <16 x i8> [[TMP198]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M156:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP214]], ptr [[VSTH64IP_M155]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M157:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP215]], ptr [[VSTL64IP_M156]], i32 8)
; CHECK-NEXT:    [[TMP216:%.*]] = shufflevector <16 x i8> [[TMP200]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP217:%.*]] = shufflevector <16 x i8> [[TMP200]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M158:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP216]], ptr [[VSTH64IP_M157]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M159:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP217]], ptr [[VSTL64IP_M158]], i32 8)
; CHECK-NEXT:    [[TMP218:%.*]] = shufflevector <16 x i8> [[TMP202]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP219:%.*]] = shufflevector <16 x i8> [[TMP202]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M160:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP218]], ptr [[VSTH64IP_M159]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M161:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP219]], ptr [[VSTL64IP_M160]], i32 8)
; CHECK-NEXT:    [[TMP220:%.*]] = shufflevector <16 x i8> [[TMP204]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP221:%.*]] = shufflevector <16 x i8> [[TMP204]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M162:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP220]], ptr [[VSTH64IP_M161]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M163:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP221]], ptr [[VSTL64IP_M162]], i32 8)
; CHECK-NEXT:    [[TMP222:%.*]] = shufflevector <16 x i8> [[TMP206]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP223:%.*]] = shufflevector <16 x i8> [[TMP206]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M164:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP222]], ptr [[VSTH64IP_M163]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M165:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP223]], ptr [[VSTL64IP_M164]], i32 8)
; CHECK-NEXT:    [[VLD128IP_M166:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP207]], i32 16)
; CHECK-NEXT:    [[TMP224:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M166]], 0
; CHECK-NEXT:    [[TMP225:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M166]], 1
; CHECK-NEXT:    [[VLD128IP_M167:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP225]], i32 16)
; CHECK-NEXT:    [[TMP226:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M167]], 0
; CHECK-NEXT:    [[TMP227:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M167]], 1
; CHECK-NEXT:    [[VLD128IP_M168:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP227]], i32 16)
; CHECK-NEXT:    [[TMP228:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M168]], 0
; CHECK-NEXT:    [[TMP229:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M168]], 1
; CHECK-NEXT:    [[VLD128IP_M169:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP229]], i32 16)
; CHECK-NEXT:    [[TMP230:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M169]], 0
; CHECK-NEXT:    [[TMP231:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M169]], 1
; CHECK-NEXT:    [[VLD128IP_M170:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP231]], i32 16)
; CHECK-NEXT:    [[TMP232:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M170]], 0
; CHECK-NEXT:    [[TMP233:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M170]], 1
; CHECK-NEXT:    [[VLD128IP_M171:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP233]], i32 16)
; CHECK-NEXT:    [[TMP234:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M171]], 0
; CHECK-NEXT:    [[TMP235:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M171]], 1
; CHECK-NEXT:    [[VLD128IP_M172:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP235]], i32 16)
; CHECK-NEXT:    [[TMP236:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M172]], 0
; CHECK-NEXT:    [[TMP237:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M172]], 1
; CHECK-NEXT:    [[VLD128IP_M173:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP237]], i32 16)
; CHECK-NEXT:    [[TMP238:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M173]], 0
; CHECK-NEXT:    [[TMP239:%.*]] = shufflevector <16 x i8> [[TMP224]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP240:%.*]] = shufflevector <16 x i8> [[TMP224]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M174:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP239]], ptr [[VSTH64IP_M165]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M175:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP240]], ptr [[VSTL64IP_M174]], i32 8)
; CHECK-NEXT:    [[TMP241:%.*]] = shufflevector <16 x i8> [[TMP226]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP242:%.*]] = shufflevector <16 x i8> [[TMP226]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M176:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP241]], ptr [[VSTH64IP_M175]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M177:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP242]], ptr [[VSTL64IP_M176]], i32 8)
; CHECK-NEXT:    [[TMP243:%.*]] = shufflevector <16 x i8> [[TMP228]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP244:%.*]] = shufflevector <16 x i8> [[TMP228]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M178:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP243]], ptr [[VSTH64IP_M177]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M179:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP244]], ptr [[VSTL64IP_M178]], i32 8)
; CHECK-NEXT:    [[TMP245:%.*]] = shufflevector <16 x i8> [[TMP230]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP246:%.*]] = shufflevector <16 x i8> [[TMP230]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M180:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP245]], ptr [[VSTH64IP_M179]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M181:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP246]], ptr [[VSTL64IP_M180]], i32 8)
; CHECK-NEXT:    [[TMP247:%.*]] = shufflevector <16 x i8> [[TMP232]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP248:%.*]] = shufflevector <16 x i8> [[TMP232]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M182:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP247]], ptr [[VSTH64IP_M181]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M183:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP248]], ptr [[VSTL64IP_M182]], i32 8)
; CHECK-NEXT:    [[TMP249:%.*]] = shufflevector <16 x i8> [[TMP234]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP250:%.*]] = shufflevector <16 x i8> [[TMP234]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M184:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP249]], ptr [[VSTH64IP_M183]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M185:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP250]], ptr [[VSTL64IP_M184]], i32 8)
; CHECK-NEXT:    [[TMP251:%.*]] = shufflevector <16 x i8> [[TMP236]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP252:%.*]] = shufflevector <16 x i8> [[TMP236]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M186:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP251]], ptr [[VSTH64IP_M185]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M187:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP252]], ptr [[VSTL64IP_M186]], i32 8)
; CHECK-NEXT:    [[TMP253:%.*]] = shufflevector <16 x i8> [[TMP238]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP254:%.*]] = shufflevector <16 x i8> [[TMP238]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M188:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP253]], ptr [[VSTH64IP_M187]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M189:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP254]], ptr [[VSTL64IP_M188]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(1024) %a, ptr noundef nonnull align 16 dereferenceable(1024) %b, i32 1024, i1 false)
  ret void
}

define void @test_src16_dst8_size_20000(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dst8_size_20000(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrc16Dst8Const16(ptr [[A]], ptr [[B]], i32 20000)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(20000) %a, ptr noundef nonnull align 16 dereferenceable(20000) %b, i32 20000, i1 false)
  ret void
}

define void @test_src8_dst16_size_1(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(1) %a, ptr noundef nonnull align 8 dereferenceable(1) %b, i32 1, i1 false)
  ret void
}

define void @test_src8_dst16_size_2(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_2(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(2) %a, ptr noundef nonnull align 8 dereferenceable(2) %b, i32 2, i1 false)
  ret void
}

define void @test_src8_dst16_size_3(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_3(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(3) %a, ptr noundef nonnull align 8 dereferenceable(3) %b, i32 3, i1 false)
  ret void
}

define void @test_src8_dst16_size_4(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_4(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(4) %a, ptr noundef nonnull align 8 dereferenceable(4) %b, i32 4, i1 false)
  ret void
}

define void @test_src8_dst16_size_5(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_5(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(5) %a, ptr noundef nonnull align 8 dereferenceable(5) %b, i32 5, i1 false)
  ret void
}

define void @test_src8_dst16_size_6(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_6(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(6) %a, ptr noundef nonnull align 8 dereferenceable(6) %b, i32 6, i1 false)
  ret void
}

define void @test_src8_dst16_size_7(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_7(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(7) %a, ptr noundef nonnull align 8 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_src8_dst16_size_8(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_8(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(8) %a, ptr noundef nonnull align 8 dereferenceable(8) %b, i32 8, i1 false)
  ret void
}

define void @test_src8_dst16_size_9(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_9(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[VSTL64IP_M]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(9) %a, ptr noundef nonnull align 8 dereferenceable(9) %b, i32 9, i1 false)
  ret void
}

define void @test_src8_dst16_size_10(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_10(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[VSTL64IP_M]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(10) %a, ptr noundef nonnull align 8 dereferenceable(10) %b, i32 10, i1 false)
  ret void
}

define void @test_src8_dst16_size_11(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_11(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[VSTL64IP_M]], align 2
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 2
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(11) %a, ptr noundef nonnull align 8 dereferenceable(11) %b, i32 11, i1 false)
  ret void
}

define void @test_src8_dst16_size_12(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_12(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(12) %a, ptr noundef nonnull align 8 dereferenceable(12) %b, i32 12, i1 false)
  ret void
}

define void @test_src8_dst16_size_13(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_13(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(13) %a, ptr noundef nonnull align 8 dereferenceable(13) %b, i32 13, i1 false)
  ret void
}

define void @test_src8_dst16_size_14(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_14(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    store i16 [[TMP5]], ptr [[TMP4]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(14) %a, ptr noundef nonnull align 8 dereferenceable(14) %b, i32 14, i1 false)
  ret void
}

define void @test_src8_dst16_size_15(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_15(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    store i16 [[TMP5]], ptr [[TMP4]], align 2
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[TMP1]], i32 6
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[TMP6]], align 1
; CHECK-NEXT:    store i8 [[TMP8]], ptr [[TMP7]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(15) %a, ptr noundef nonnull align 8 dereferenceable(15) %b, i32 15, i1 false)
  ret void
}

define void @test_src8_dst16_size_16(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(16) %a, ptr noundef nonnull align 8 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_src8_dst16_size_17(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_17(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(17) %a, ptr noundef nonnull align 8 dereferenceable(17) %b, i32 17, i1 false)
  ret void
}

define void @test_src8_dst16_size_31(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_31(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VSTL64IP_M2:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[TMP4]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP6]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[VSTL64IP_M2]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP6]], i32 4
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[VSTL64IP_M2]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[TMP8]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[TMP9]], align 2
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[TMP6]], i32 6
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[VSTL64IP_M2]], i32 6
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[TMP11]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[TMP12]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(31) %a, ptr noundef nonnull align 8 dereferenceable(31) %b, i32 31, i1 false)
  ret void
}

define void @test_src8_dst16_size_32(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_32(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M3]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(32) %a, ptr noundef nonnull align 8 dereferenceable(32) %b, i32 32, i1 false)
  ret void
}

define void @test_src8_dst16_size_33(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_33(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M3]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[TMP8]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(33) %a, ptr noundef nonnull align 8 dereferenceable(33) %b, i32 33, i1 false)
  ret void
}

define void @test_src8_dst16_size_47(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M3]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VSTL64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[TMP8]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[TMP10]], align 4
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[VSTL64IP_M6]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[TMP10]], i32 4
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[VSTL64IP_M6]], i32 4
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[TMP12]], align 2
; CHECK-NEXT:    store i16 [[TMP14]], ptr [[TMP13]], align 2
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[TMP10]], i32 6
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[VSTL64IP_M6]], i32 6
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[TMP15]], align 1
; CHECK-NEXT:    store i8 [[TMP17]], ptr [[TMP16]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(47) %a, ptr noundef nonnull align 8 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

define void @test_src8_dst16_size_48(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M6]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(48) %a, ptr noundef nonnull align 8 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_src8_dst16_size_49(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_49(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M6]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[TMP11]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[TMP12]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(49) %a, ptr noundef nonnull align 8 dereferenceable(49) %b, i32 49, i1 false)
  ret void
}

define void @test_src8_dst16_size_63(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_63(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M6]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VSTL64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[TMP12]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[TMP14]], align 4
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[VSTL64IP_M10]], align 4
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[TMP14]], i32 4
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr i8, ptr [[VSTL64IP_M10]], i32 4
; CHECK-NEXT:    [[TMP18:%.*]] = load i16, ptr [[TMP16]], align 2
; CHECK-NEXT:    store i16 [[TMP18]], ptr [[TMP17]], align 2
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[TMP14]], i32 6
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i8, ptr [[VSTL64IP_M10]], i32 6
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[TMP19]], align 1
; CHECK-NEXT:    store i8 [[TMP21]], ptr [[TMP20]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(63) %a, ptr noundef nonnull align 8 dereferenceable(63) %b, i32 63, i1 false)
  ret void
}

define void @test_src8_dst16_size_64(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_64(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(64) %a, ptr noundef nonnull align 8 dereferenceable(64) %b, i32 64, i1 false)
  ret void
}

define void @test_src8_dst16_size_65(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_65(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[B]], i32 64
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[A]], i32 64
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[TMP15]], align 1
; CHECK-NEXT:    store i8 [[TMP17]], ptr [[TMP16]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(65) %a, ptr noundef nonnull align 8 dereferenceable(65) %b, i32 65, i1 false)
  ret void
}

define void @test_src8_dst16_size_80(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_80(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(80) %a, ptr noundef nonnull align 8 dereferenceable(80) %b, i32 80, i1 false)
  ret void
}

define void @test_src8_dst16_size_81(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_81(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[B]], i32 80
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i8, ptr [[A]], i32 80
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[TMP19]], align 1
; CHECK-NEXT:    store i8 [[TMP21]], ptr [[TMP20]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(81) %a, ptr noundef nonnull align 8 dereferenceable(81) %b, i32 81, i1 false)
  ret void
}

define void @test_src8_dst16_size_88(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_88(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M17:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M17]], 0
; CHECK-NEXT:    [[VSTL64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(88) %a, ptr noundef nonnull align 8 dereferenceable(88) %b, i32 88, i1 false)
  ret void
}

define void @test_src8_dst16_size_96(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_96(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(96) %a, ptr noundef nonnull align 8 dereferenceable(96) %b, i32 96, i1 false)
  ret void
}

define void @test_src8_dst16_size_112(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_112(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(112) %a, ptr noundef nonnull align 8 dereferenceable(112) %b, i32 112, i1 false)
  ret void
}

define void @test_src8_dst16_size_124(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_124(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[VLDL64IP_M25:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 0
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 1
; CHECK-NEXT:    [[VSTL64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP29]], ptr [[TMP28]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[TMP30]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[VSTL64IP_M26]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(124) %a, ptr noundef nonnull align 8 dereferenceable(124) %b, i32 124, i1 false)
  ret void
}

define void @test_src8_dst16_size_127(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_127(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[VLDL64IP_M25:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 0
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 1
; CHECK-NEXT:    [[VSTL64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP29]], ptr [[TMP28]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[TMP30]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[VSTL64IP_M26]], align 4
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr i8, ptr [[TMP30]], i32 4
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr i8, ptr [[VSTL64IP_M26]], i32 4
; CHECK-NEXT:    [[TMP34:%.*]] = load i16, ptr [[TMP32]], align 2
; CHECK-NEXT:    store i16 [[TMP34]], ptr [[TMP33]], align 2
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr i8, ptr [[TMP30]], i32 6
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr i8, ptr [[VSTL64IP_M26]], i32 6
; CHECK-NEXT:    [[TMP37:%.*]] = load i8, ptr [[TMP35]], align 1
; CHECK-NEXT:    store i8 [[TMP37]], ptr [[TMP36]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(127) %a, ptr noundef nonnull align 8 dereferenceable(127) %b, i32 127, i1 false)
  ret void
}

define void @test_src8_dst16_size_128(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(128) %a, ptr noundef nonnull align 8 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_src8_dst16_size_129(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_129(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr i8, ptr [[B]], i32 128
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr i8, ptr [[A]], i32 128
; CHECK-NEXT:    [[TMP33:%.*]] = load i8, ptr [[TMP31]], align 1
; CHECK-NEXT:    store i8 [[TMP33]], ptr [[TMP32]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(129) %a, ptr noundef nonnull align 8 dereferenceable(129) %b, i32 129, i1 false)
  ret void
}

define void @test_src8_dst16_size_255(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_255(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M29:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 1
; CHECK-NEXT:    [[VLDH64IP_M30:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP33]], i32 8)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 1
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP35]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP37]], i32 8)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M33:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP39]], i32 8)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 1
; CHECK-NEXT:    [[VLDH64IP_M34:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP41]], i32 8)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP43]], i32 8)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP45]], i32 8)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP47]], i32 8)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP49]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP51]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDH64IP_M40:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP53]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 1
; CHECK-NEXT:    [[VLDL64IP_M41:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP55]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 1
; CHECK-NEXT:    [[VLDH64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP57]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 0
; CHECK-NEXT:    [[VSTL64IP_M43:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP32]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M44:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP34]], ptr [[VSTL64IP_M43]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP36]], ptr [[VSTH64IP_M44]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP38]], ptr [[VSTL64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M47:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP40]], ptr [[VSTH64IP_M46]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M48:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP42]], ptr [[VSTL64IP_M47]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP44]], ptr [[VSTH64IP_M48]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP46]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M54]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M55]], i32 8)
; CHECK-NEXT:    [[TMP59:%.*]] = getelementptr i8, ptr [[B]], i32 240
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr i8, ptr [[A]], i32 240
; CHECK-NEXT:    [[VLDL64IP_M57:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP59]], i32 8)
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M57]], 0
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M57]], 1
; CHECK-NEXT:    [[VSTL64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP61]], ptr [[TMP60]], i32 8)
; CHECK-NEXT:    [[TMP63:%.*]] = load i32, ptr [[TMP62]], align 4
; CHECK-NEXT:    store i32 [[TMP63]], ptr [[VSTL64IP_M58]], align 4
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr i8, ptr [[TMP62]], i32 4
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr i8, ptr [[VSTL64IP_M58]], i32 4
; CHECK-NEXT:    [[TMP66:%.*]] = load i16, ptr [[TMP64]], align 2
; CHECK-NEXT:    store i16 [[TMP66]], ptr [[TMP65]], align 2
; CHECK-NEXT:    [[TMP67:%.*]] = getelementptr i8, ptr [[TMP62]], i32 6
; CHECK-NEXT:    [[TMP68:%.*]] = getelementptr i8, ptr [[VSTL64IP_M58]], i32 6
; CHECK-NEXT:    [[TMP69:%.*]] = load i8, ptr [[TMP67]], align 1
; CHECK-NEXT:    store i8 [[TMP69]], ptr [[TMP68]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(255) %a, ptr noundef nonnull align 8 dereferenceable(255) %b, i32 255, i1 false)
  ret void
}

define void @test_src8_dst16_size_256(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M29:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 1
; CHECK-NEXT:    [[VLDH64IP_M30:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP33]], i32 8)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 1
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP35]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP37]], i32 8)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M33:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP39]], i32 8)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 1
; CHECK-NEXT:    [[VLDH64IP_M34:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP41]], i32 8)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP43]], i32 8)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP45]], i32 8)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP47]], i32 8)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP49]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP51]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDH64IP_M40:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP53]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 1
; CHECK-NEXT:    [[VLDL64IP_M41:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP55]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 1
; CHECK-NEXT:    [[VLDH64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP57]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 0
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 1
; CHECK-NEXT:    [[VLDL64IP_M43:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP59]], i32 8)
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 1
; CHECK-NEXT:    [[VLDH64IP_M44:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP61]], i32 8)
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 0
; CHECK-NEXT:    [[VSTL64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP32]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP34]], ptr [[VSTL64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M47:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP36]], ptr [[VSTH64IP_M46]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M48:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP38]], ptr [[VSTL64IP_M47]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP40]], ptr [[VSTH64IP_M48]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP42]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP44]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP46]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M54]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M55]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M56]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M57]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP60]], ptr [[VSTH64IP_M58]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP62]], ptr [[VSTL64IP_M59]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(256) %a, ptr noundef nonnull align 8 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

define void @test_src8_dst16_size_1023(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_1023(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M29:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 1
; CHECK-NEXT:    [[VLDH64IP_M30:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP33]], i32 8)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 1
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP35]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP37]], i32 8)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M33:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP39]], i32 8)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 1
; CHECK-NEXT:    [[VLDH64IP_M34:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP41]], i32 8)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP43]], i32 8)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP45]], i32 8)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP47]], i32 8)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP49]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP51]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDH64IP_M40:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP53]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 1
; CHECK-NEXT:    [[VLDL64IP_M41:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP55]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 1
; CHECK-NEXT:    [[VLDH64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP57]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 0
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 1
; CHECK-NEXT:    [[VLDL64IP_M43:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP59]], i32 8)
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 1
; CHECK-NEXT:    [[VLDH64IP_M44:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP61]], i32 8)
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 0
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 1
; CHECK-NEXT:    [[VSTL64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP32]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP34]], ptr [[VSTL64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M47:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP36]], ptr [[VSTH64IP_M46]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M48:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP38]], ptr [[VSTL64IP_M47]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP40]], ptr [[VSTH64IP_M48]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP42]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP44]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP46]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M54]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M55]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M56]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M57]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP60]], ptr [[VSTH64IP_M58]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP62]], ptr [[VSTL64IP_M59]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M61:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP63]], i32 8)
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 0
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 1
; CHECK-NEXT:    [[VLDH64IP_M62:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP65]], i32 8)
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 0
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 1
; CHECK-NEXT:    [[VLDL64IP_M63:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP67]], i32 8)
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 0
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 1
; CHECK-NEXT:    [[VLDH64IP_M64:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP69]], i32 8)
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M64]], 0
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M64]], 1
; CHECK-NEXT:    [[VLDL64IP_M65:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP71]], i32 8)
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M65]], 0
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M65]], 1
; CHECK-NEXT:    [[VLDH64IP_M66:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP73]], i32 8)
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M66]], 0
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M66]], 1
; CHECK-NEXT:    [[VLDL64IP_M67:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP75]], i32 8)
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 0
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 1
; CHECK-NEXT:    [[VLDH64IP_M68:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP77]], i32 8)
; CHECK-NEXT:    [[TMP78:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M68]], 0
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M68]], 1
; CHECK-NEXT:    [[VLDL64IP_M69:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP79]], i32 8)
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M69]], 0
; CHECK-NEXT:    [[TMP81:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M69]], 1
; CHECK-NEXT:    [[VLDH64IP_M70:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP81]], i32 8)
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M70]], 0
; CHECK-NEXT:    [[TMP83:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M70]], 1
; CHECK-NEXT:    [[VLDL64IP_M71:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP83]], i32 8)
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 0
; CHECK-NEXT:    [[TMP85:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 1
; CHECK-NEXT:    [[VLDH64IP_M72:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP85]], i32 8)
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 0
; CHECK-NEXT:    [[TMP87:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 1
; CHECK-NEXT:    [[VLDL64IP_M73:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP87]], i32 8)
; CHECK-NEXT:    [[TMP88:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 0
; CHECK-NEXT:    [[TMP89:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 1
; CHECK-NEXT:    [[VLDH64IP_M74:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP89]], i32 8)
; CHECK-NEXT:    [[TMP90:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 0
; CHECK-NEXT:    [[TMP91:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 1
; CHECK-NEXT:    [[VLDL64IP_M75:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP91]], i32 8)
; CHECK-NEXT:    [[TMP92:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 0
; CHECK-NEXT:    [[TMP93:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 1
; CHECK-NEXT:    [[VLDH64IP_M76:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP93]], i32 8)
; CHECK-NEXT:    [[TMP94:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 0
; CHECK-NEXT:    [[TMP95:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 1
; CHECK-NEXT:    [[VSTL64IP_M77:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP64]], ptr [[VSTH64IP_M60]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M78:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP66]], ptr [[VSTL64IP_M77]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M79:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP68]], ptr [[VSTH64IP_M78]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP70]], ptr [[VSTL64IP_M79]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M81:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP72]], ptr [[VSTH64IP_M80]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M82:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP74]], ptr [[VSTL64IP_M81]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M83:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP76]], ptr [[VSTH64IP_M82]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M84:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP78]], ptr [[VSTL64IP_M83]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M85:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP80]], ptr [[VSTH64IP_M84]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M86:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP82]], ptr [[VSTL64IP_M85]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M87:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP84]], ptr [[VSTH64IP_M86]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M88:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP86]], ptr [[VSTL64IP_M87]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP88]], ptr [[VSTH64IP_M88]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M90:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP90]], ptr [[VSTL64IP_M89]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M91:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP92]], ptr [[VSTH64IP_M90]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M92:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP94]], ptr [[VSTL64IP_M91]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M93:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP95]], i32 8)
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 0
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 1
; CHECK-NEXT:    [[VLDH64IP_M94:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP97]], i32 8)
; CHECK-NEXT:    [[TMP98:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 0
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 1
; CHECK-NEXT:    [[VLDL64IP_M95:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP99]], i32 8)
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 0
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 1
; CHECK-NEXT:    [[VLDH64IP_M96:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP101]], i32 8)
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 0
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 1
; CHECK-NEXT:    [[VLDL64IP_M97:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP103]], i32 8)
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 0
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 1
; CHECK-NEXT:    [[VLDH64IP_M98:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP105]], i32 8)
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 0
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 1
; CHECK-NEXT:    [[VLDL64IP_M99:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP107]], i32 8)
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M99]], 0
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M99]], 1
; CHECK-NEXT:    [[VLDH64IP_M100:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP109]], i32 8)
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M100]], 0
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M100]], 1
; CHECK-NEXT:    [[VLDL64IP_M101:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP111]], i32 8)
; CHECK-NEXT:    [[TMP112:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M101]], 0
; CHECK-NEXT:    [[TMP113:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M101]], 1
; CHECK-NEXT:    [[VLDH64IP_M102:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP113]], i32 8)
; CHECK-NEXT:    [[TMP114:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M102]], 0
; CHECK-NEXT:    [[TMP115:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M102]], 1
; CHECK-NEXT:    [[VLDL64IP_M103:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP115]], i32 8)
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M103]], 0
; CHECK-NEXT:    [[TMP117:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M103]], 1
; CHECK-NEXT:    [[VLDH64IP_M104:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP117]], i32 8)
; CHECK-NEXT:    [[TMP118:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M104]], 0
; CHECK-NEXT:    [[TMP119:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M104]], 1
; CHECK-NEXT:    [[VLDL64IP_M105:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP119]], i32 8)
; CHECK-NEXT:    [[TMP120:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 0
; CHECK-NEXT:    [[TMP121:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 1
; CHECK-NEXT:    [[VLDH64IP_M106:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP121]], i32 8)
; CHECK-NEXT:    [[TMP122:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M106]], 0
; CHECK-NEXT:    [[TMP123:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M106]], 1
; CHECK-NEXT:    [[VLDL64IP_M107:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP123]], i32 8)
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 0
; CHECK-NEXT:    [[TMP125:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 1
; CHECK-NEXT:    [[VLDH64IP_M108:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP125]], i32 8)
; CHECK-NEXT:    [[TMP126:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 0
; CHECK-NEXT:    [[TMP127:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 1
; CHECK-NEXT:    [[VSTL64IP_M109:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP96]], ptr [[VSTH64IP_M92]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M110:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP98]], ptr [[VSTL64IP_M109]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M111:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP100]], ptr [[VSTH64IP_M110]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M112:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP102]], ptr [[VSTL64IP_M111]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M113:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP104]], ptr [[VSTH64IP_M112]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M114:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP106]], ptr [[VSTL64IP_M113]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M115:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP108]], ptr [[VSTH64IP_M114]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M116:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP110]], ptr [[VSTL64IP_M115]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M117:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP112]], ptr [[VSTH64IP_M116]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M118:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP114]], ptr [[VSTL64IP_M117]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M119:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP116]], ptr [[VSTH64IP_M118]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M120:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP118]], ptr [[VSTL64IP_M119]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M121:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP120]], ptr [[VSTH64IP_M120]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M122:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP122]], ptr [[VSTL64IP_M121]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M123:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP124]], ptr [[VSTH64IP_M122]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M124:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP126]], ptr [[VSTL64IP_M123]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M125:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP127]], i32 8)
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M125]], 0
; CHECK-NEXT:    [[TMP129:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M125]], 1
; CHECK-NEXT:    [[VLDH64IP_M126:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP129]], i32 8)
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M126]], 0
; CHECK-NEXT:    [[TMP131:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M126]], 1
; CHECK-NEXT:    [[VLDL64IP_M127:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP131]], i32 8)
; CHECK-NEXT:    [[TMP132:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M127]], 0
; CHECK-NEXT:    [[TMP133:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M127]], 1
; CHECK-NEXT:    [[VLDH64IP_M128:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP133]], i32 8)
; CHECK-NEXT:    [[TMP134:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M128]], 0
; CHECK-NEXT:    [[TMP135:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M128]], 1
; CHECK-NEXT:    [[VLDL64IP_M129:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP135]], i32 8)
; CHECK-NEXT:    [[TMP136:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M129]], 0
; CHECK-NEXT:    [[TMP137:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M129]], 1
; CHECK-NEXT:    [[VLDH64IP_M130:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP137]], i32 8)
; CHECK-NEXT:    [[TMP138:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M130]], 0
; CHECK-NEXT:    [[TMP139:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M130]], 1
; CHECK-NEXT:    [[VLDL64IP_M131:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP139]], i32 8)
; CHECK-NEXT:    [[TMP140:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 0
; CHECK-NEXT:    [[TMP141:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 1
; CHECK-NEXT:    [[VLDH64IP_M132:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP141]], i32 8)
; CHECK-NEXT:    [[TMP142:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 0
; CHECK-NEXT:    [[TMP143:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 1
; CHECK-NEXT:    [[VLDL64IP_M133:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP143]], i32 8)
; CHECK-NEXT:    [[TMP144:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 0
; CHECK-NEXT:    [[TMP145:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 1
; CHECK-NEXT:    [[VLDH64IP_M134:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP145]], i32 8)
; CHECK-NEXT:    [[TMP146:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 0
; CHECK-NEXT:    [[TMP147:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 1
; CHECK-NEXT:    [[VLDL64IP_M135:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP147]], i32 8)
; CHECK-NEXT:    [[TMP148:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 0
; CHECK-NEXT:    [[TMP149:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 1
; CHECK-NEXT:    [[VLDH64IP_M136:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP149]], i32 8)
; CHECK-NEXT:    [[TMP150:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 0
; CHECK-NEXT:    [[TMP151:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 1
; CHECK-NEXT:    [[VLDL64IP_M137:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP151]], i32 8)
; CHECK-NEXT:    [[TMP152:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M137]], 0
; CHECK-NEXT:    [[TMP153:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M137]], 1
; CHECK-NEXT:    [[VLDH64IP_M138:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP153]], i32 8)
; CHECK-NEXT:    [[TMP154:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M138]], 0
; CHECK-NEXT:    [[TMP155:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M138]], 1
; CHECK-NEXT:    [[VLDL64IP_M139:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP155]], i32 8)
; CHECK-NEXT:    [[TMP156:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M139]], 0
; CHECK-NEXT:    [[TMP157:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M139]], 1
; CHECK-NEXT:    [[VLDH64IP_M140:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP157]], i32 8)
; CHECK-NEXT:    [[TMP158:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M140]], 0
; CHECK-NEXT:    [[TMP159:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M140]], 1
; CHECK-NEXT:    [[VSTL64IP_M141:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP128]], ptr [[VSTH64IP_M124]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M142:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP130]], ptr [[VSTL64IP_M141]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M143:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP132]], ptr [[VSTH64IP_M142]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M144:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP134]], ptr [[VSTL64IP_M143]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M145:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP136]], ptr [[VSTH64IP_M144]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M146:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP138]], ptr [[VSTL64IP_M145]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M147:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP140]], ptr [[VSTH64IP_M146]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M148:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP142]], ptr [[VSTL64IP_M147]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M149:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP144]], ptr [[VSTH64IP_M148]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M150:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP146]], ptr [[VSTL64IP_M149]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M151:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP148]], ptr [[VSTH64IP_M150]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M152:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP150]], ptr [[VSTL64IP_M151]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M153:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP152]], ptr [[VSTH64IP_M152]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M154:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP154]], ptr [[VSTL64IP_M153]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M155:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP156]], ptr [[VSTH64IP_M154]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M156:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP158]], ptr [[VSTL64IP_M155]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M157:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP159]], i32 8)
; CHECK-NEXT:    [[TMP160:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M157]], 0
; CHECK-NEXT:    [[TMP161:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M157]], 1
; CHECK-NEXT:    [[VLDH64IP_M158:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP161]], i32 8)
; CHECK-NEXT:    [[TMP162:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M158]], 0
; CHECK-NEXT:    [[TMP163:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M158]], 1
; CHECK-NEXT:    [[VLDL64IP_M159:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP163]], i32 8)
; CHECK-NEXT:    [[TMP164:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M159]], 0
; CHECK-NEXT:    [[TMP165:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M159]], 1
; CHECK-NEXT:    [[VLDH64IP_M160:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP165]], i32 8)
; CHECK-NEXT:    [[TMP166:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M160]], 0
; CHECK-NEXT:    [[TMP167:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M160]], 1
; CHECK-NEXT:    [[VLDL64IP_M161:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP167]], i32 8)
; CHECK-NEXT:    [[TMP168:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M161]], 0
; CHECK-NEXT:    [[TMP169:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M161]], 1
; CHECK-NEXT:    [[VLDH64IP_M162:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP169]], i32 8)
; CHECK-NEXT:    [[TMP170:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M162]], 0
; CHECK-NEXT:    [[TMP171:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M162]], 1
; CHECK-NEXT:    [[VLDL64IP_M163:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP171]], i32 8)
; CHECK-NEXT:    [[TMP172:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M163]], 0
; CHECK-NEXT:    [[TMP173:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M163]], 1
; CHECK-NEXT:    [[VLDH64IP_M164:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP173]], i32 8)
; CHECK-NEXT:    [[TMP174:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M164]], 0
; CHECK-NEXT:    [[TMP175:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M164]], 1
; CHECK-NEXT:    [[VLDL64IP_M165:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP175]], i32 8)
; CHECK-NEXT:    [[TMP176:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M165]], 0
; CHECK-NEXT:    [[TMP177:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M165]], 1
; CHECK-NEXT:    [[VLDH64IP_M166:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP177]], i32 8)
; CHECK-NEXT:    [[TMP178:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M166]], 0
; CHECK-NEXT:    [[TMP179:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M166]], 1
; CHECK-NEXT:    [[VLDL64IP_M167:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP179]], i32 8)
; CHECK-NEXT:    [[TMP180:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M167]], 0
; CHECK-NEXT:    [[TMP181:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M167]], 1
; CHECK-NEXT:    [[VLDH64IP_M168:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP181]], i32 8)
; CHECK-NEXT:    [[TMP182:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M168]], 0
; CHECK-NEXT:    [[TMP183:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M168]], 1
; CHECK-NEXT:    [[VLDL64IP_M169:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP183]], i32 8)
; CHECK-NEXT:    [[TMP184:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M169]], 0
; CHECK-NEXT:    [[TMP185:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M169]], 1
; CHECK-NEXT:    [[VLDH64IP_M170:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP185]], i32 8)
; CHECK-NEXT:    [[TMP186:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M170]], 0
; CHECK-NEXT:    [[TMP187:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M170]], 1
; CHECK-NEXT:    [[VLDL64IP_M171:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP187]], i32 8)
; CHECK-NEXT:    [[TMP188:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M171]], 0
; CHECK-NEXT:    [[TMP189:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M171]], 1
; CHECK-NEXT:    [[VLDH64IP_M172:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP189]], i32 8)
; CHECK-NEXT:    [[TMP190:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M172]], 0
; CHECK-NEXT:    [[TMP191:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M172]], 1
; CHECK-NEXT:    [[VSTL64IP_M173:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP160]], ptr [[VSTH64IP_M156]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M174:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP162]], ptr [[VSTL64IP_M173]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M175:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP164]], ptr [[VSTH64IP_M174]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M176:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP166]], ptr [[VSTL64IP_M175]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M177:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP168]], ptr [[VSTH64IP_M176]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M178:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP170]], ptr [[VSTL64IP_M177]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M179:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP172]], ptr [[VSTH64IP_M178]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M180:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP174]], ptr [[VSTL64IP_M179]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M181:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP176]], ptr [[VSTH64IP_M180]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M182:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP178]], ptr [[VSTL64IP_M181]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M183:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP180]], ptr [[VSTH64IP_M182]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M184:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP182]], ptr [[VSTL64IP_M183]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M185:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP184]], ptr [[VSTH64IP_M184]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M186:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP186]], ptr [[VSTL64IP_M185]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M187:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP188]], ptr [[VSTH64IP_M186]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M188:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP190]], ptr [[VSTL64IP_M187]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M189:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP191]], i32 8)
; CHECK-NEXT:    [[TMP192:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M189]], 0
; CHECK-NEXT:    [[TMP193:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M189]], 1
; CHECK-NEXT:    [[VLDH64IP_M190:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP193]], i32 8)
; CHECK-NEXT:    [[TMP194:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M190]], 0
; CHECK-NEXT:    [[TMP195:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M190]], 1
; CHECK-NEXT:    [[VLDL64IP_M191:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP195]], i32 8)
; CHECK-NEXT:    [[TMP196:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M191]], 0
; CHECK-NEXT:    [[TMP197:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M191]], 1
; CHECK-NEXT:    [[VLDH64IP_M192:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP197]], i32 8)
; CHECK-NEXT:    [[TMP198:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M192]], 0
; CHECK-NEXT:    [[TMP199:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M192]], 1
; CHECK-NEXT:    [[VLDL64IP_M193:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP199]], i32 8)
; CHECK-NEXT:    [[TMP200:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M193]], 0
; CHECK-NEXT:    [[TMP201:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M193]], 1
; CHECK-NEXT:    [[VLDH64IP_M194:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP201]], i32 8)
; CHECK-NEXT:    [[TMP202:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M194]], 0
; CHECK-NEXT:    [[TMP203:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M194]], 1
; CHECK-NEXT:    [[VLDL64IP_M195:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP203]], i32 8)
; CHECK-NEXT:    [[TMP204:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M195]], 0
; CHECK-NEXT:    [[TMP205:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M195]], 1
; CHECK-NEXT:    [[VLDH64IP_M196:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP205]], i32 8)
; CHECK-NEXT:    [[TMP206:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M196]], 0
; CHECK-NEXT:    [[TMP207:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M196]], 1
; CHECK-NEXT:    [[VLDL64IP_M197:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP207]], i32 8)
; CHECK-NEXT:    [[TMP208:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M197]], 0
; CHECK-NEXT:    [[TMP209:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M197]], 1
; CHECK-NEXT:    [[VLDH64IP_M198:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP209]], i32 8)
; CHECK-NEXT:    [[TMP210:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M198]], 0
; CHECK-NEXT:    [[TMP211:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M198]], 1
; CHECK-NEXT:    [[VLDL64IP_M199:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP211]], i32 8)
; CHECK-NEXT:    [[TMP212:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M199]], 0
; CHECK-NEXT:    [[TMP213:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M199]], 1
; CHECK-NEXT:    [[VLDH64IP_M200:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP213]], i32 8)
; CHECK-NEXT:    [[TMP214:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M200]], 0
; CHECK-NEXT:    [[TMP215:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M200]], 1
; CHECK-NEXT:    [[VLDL64IP_M201:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP215]], i32 8)
; CHECK-NEXT:    [[TMP216:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M201]], 0
; CHECK-NEXT:    [[TMP217:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M201]], 1
; CHECK-NEXT:    [[VLDH64IP_M202:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP217]], i32 8)
; CHECK-NEXT:    [[TMP218:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M202]], 0
; CHECK-NEXT:    [[TMP219:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M202]], 1
; CHECK-NEXT:    [[VLDL64IP_M203:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP219]], i32 8)
; CHECK-NEXT:    [[TMP220:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M203]], 0
; CHECK-NEXT:    [[TMP221:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M203]], 1
; CHECK-NEXT:    [[VLDH64IP_M204:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP221]], i32 8)
; CHECK-NEXT:    [[TMP222:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M204]], 0
; CHECK-NEXT:    [[TMP223:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M204]], 1
; CHECK-NEXT:    [[VSTL64IP_M205:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP192]], ptr [[VSTH64IP_M188]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M206:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP194]], ptr [[VSTL64IP_M205]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M207:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP196]], ptr [[VSTH64IP_M206]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M208:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP198]], ptr [[VSTL64IP_M207]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M209:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP200]], ptr [[VSTH64IP_M208]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M210:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP202]], ptr [[VSTL64IP_M209]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M211:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP204]], ptr [[VSTH64IP_M210]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M212:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP206]], ptr [[VSTL64IP_M211]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M213:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP208]], ptr [[VSTH64IP_M212]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M214:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP210]], ptr [[VSTL64IP_M213]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M215:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP212]], ptr [[VSTH64IP_M214]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M216:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP214]], ptr [[VSTL64IP_M215]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M217:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP216]], ptr [[VSTH64IP_M216]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M218:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP218]], ptr [[VSTL64IP_M217]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M219:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP220]], ptr [[VSTH64IP_M218]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M220:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP222]], ptr [[VSTL64IP_M219]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M221:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP223]], i32 8)
; CHECK-NEXT:    [[TMP224:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M221]], 0
; CHECK-NEXT:    [[TMP225:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M221]], 1
; CHECK-NEXT:    [[VLDH64IP_M222:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP225]], i32 8)
; CHECK-NEXT:    [[TMP226:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M222]], 0
; CHECK-NEXT:    [[TMP227:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M222]], 1
; CHECK-NEXT:    [[VLDL64IP_M223:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP227]], i32 8)
; CHECK-NEXT:    [[TMP228:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M223]], 0
; CHECK-NEXT:    [[TMP229:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M223]], 1
; CHECK-NEXT:    [[VLDH64IP_M224:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP229]], i32 8)
; CHECK-NEXT:    [[TMP230:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M224]], 0
; CHECK-NEXT:    [[TMP231:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M224]], 1
; CHECK-NEXT:    [[VLDL64IP_M225:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP231]], i32 8)
; CHECK-NEXT:    [[TMP232:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M225]], 0
; CHECK-NEXT:    [[TMP233:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M225]], 1
; CHECK-NEXT:    [[VLDH64IP_M226:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP233]], i32 8)
; CHECK-NEXT:    [[TMP234:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M226]], 0
; CHECK-NEXT:    [[TMP235:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M226]], 1
; CHECK-NEXT:    [[VLDL64IP_M227:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP235]], i32 8)
; CHECK-NEXT:    [[TMP236:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M227]], 0
; CHECK-NEXT:    [[TMP237:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M227]], 1
; CHECK-NEXT:    [[VLDH64IP_M228:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP237]], i32 8)
; CHECK-NEXT:    [[TMP238:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M228]], 0
; CHECK-NEXT:    [[TMP239:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M228]], 1
; CHECK-NEXT:    [[VLDL64IP_M229:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP239]], i32 8)
; CHECK-NEXT:    [[TMP240:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M229]], 0
; CHECK-NEXT:    [[TMP241:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M229]], 1
; CHECK-NEXT:    [[VLDH64IP_M230:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP241]], i32 8)
; CHECK-NEXT:    [[TMP242:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M230]], 0
; CHECK-NEXT:    [[TMP243:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M230]], 1
; CHECK-NEXT:    [[VLDL64IP_M231:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP243]], i32 8)
; CHECK-NEXT:    [[TMP244:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M231]], 0
; CHECK-NEXT:    [[TMP245:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M231]], 1
; CHECK-NEXT:    [[VLDH64IP_M232:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP245]], i32 8)
; CHECK-NEXT:    [[TMP246:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M232]], 0
; CHECK-NEXT:    [[TMP247:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M232]], 1
; CHECK-NEXT:    [[VLDL64IP_M233:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP247]], i32 8)
; CHECK-NEXT:    [[TMP248:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M233]], 0
; CHECK-NEXT:    [[TMP249:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M233]], 1
; CHECK-NEXT:    [[VLDH64IP_M234:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP249]], i32 8)
; CHECK-NEXT:    [[TMP250:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M234]], 0
; CHECK-NEXT:    [[VSTL64IP_M235:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP224]], ptr [[VSTH64IP_M220]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M236:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP226]], ptr [[VSTL64IP_M235]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M237:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP228]], ptr [[VSTH64IP_M236]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M238:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP230]], ptr [[VSTL64IP_M237]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M239:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP232]], ptr [[VSTH64IP_M238]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M240:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP234]], ptr [[VSTL64IP_M239]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M241:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP236]], ptr [[VSTH64IP_M240]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M242:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP238]], ptr [[VSTL64IP_M241]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M243:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP240]], ptr [[VSTH64IP_M242]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M244:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP242]], ptr [[VSTL64IP_M243]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M245:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP244]], ptr [[VSTH64IP_M244]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M246:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP246]], ptr [[VSTL64IP_M245]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M247:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP248]], ptr [[VSTH64IP_M246]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M248:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP250]], ptr [[VSTL64IP_M247]], i32 8)
; CHECK-NEXT:    [[TMP251:%.*]] = getelementptr i8, ptr [[B]], i32 1008
; CHECK-NEXT:    [[TMP252:%.*]] = getelementptr i8, ptr [[A]], i32 1008
; CHECK-NEXT:    [[VLDL64IP_M249:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP251]], i32 8)
; CHECK-NEXT:    [[TMP253:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M249]], 0
; CHECK-NEXT:    [[TMP254:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M249]], 1
; CHECK-NEXT:    [[VSTL64IP_M250:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP253]], ptr [[TMP252]], i32 8)
; CHECK-NEXT:    [[TMP255:%.*]] = load i32, ptr [[TMP254]], align 4
; CHECK-NEXT:    store i32 [[TMP255]], ptr [[VSTL64IP_M250]], align 4
; CHECK-NEXT:    [[TMP256:%.*]] = getelementptr i8, ptr [[TMP254]], i32 4
; CHECK-NEXT:    [[TMP257:%.*]] = getelementptr i8, ptr [[VSTL64IP_M250]], i32 4
; CHECK-NEXT:    [[TMP258:%.*]] = load i16, ptr [[TMP256]], align 2
; CHECK-NEXT:    store i16 [[TMP258]], ptr [[TMP257]], align 2
; CHECK-NEXT:    [[TMP259:%.*]] = getelementptr i8, ptr [[TMP254]], i32 6
; CHECK-NEXT:    [[TMP260:%.*]] = getelementptr i8, ptr [[VSTL64IP_M250]], i32 6
; CHECK-NEXT:    [[TMP261:%.*]] = load i8, ptr [[TMP259]], align 1
; CHECK-NEXT:    store i8 [[TMP261]], ptr [[TMP260]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(1023) %a, ptr noundef nonnull align 8 dereferenceable(1023) %b, i32 1023, i1 false)
  ret void
}

define void @test_src8_dst16_size_1024(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_1024(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M29:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 1
; CHECK-NEXT:    [[VLDH64IP_M30:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP33]], i32 8)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 1
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP35]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP37]], i32 8)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M33:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP39]], i32 8)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 1
; CHECK-NEXT:    [[VLDH64IP_M34:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP41]], i32 8)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP43]], i32 8)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP45]], i32 8)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP47]], i32 8)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP49]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP51]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDH64IP_M40:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP53]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 1
; CHECK-NEXT:    [[VLDL64IP_M41:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP55]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 1
; CHECK-NEXT:    [[VLDH64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP57]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 0
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 1
; CHECK-NEXT:    [[VLDL64IP_M43:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP59]], i32 8)
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 1
; CHECK-NEXT:    [[VLDH64IP_M44:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP61]], i32 8)
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 0
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 1
; CHECK-NEXT:    [[VSTL64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP32]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP34]], ptr [[VSTL64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M47:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP36]], ptr [[VSTH64IP_M46]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M48:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP38]], ptr [[VSTL64IP_M47]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP40]], ptr [[VSTH64IP_M48]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP42]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP44]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP46]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M54]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M55]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M56]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M57]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP60]], ptr [[VSTH64IP_M58]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP62]], ptr [[VSTL64IP_M59]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M61:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP63]], i32 8)
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 0
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 1
; CHECK-NEXT:    [[VLDH64IP_M62:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP65]], i32 8)
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 0
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 1
; CHECK-NEXT:    [[VLDL64IP_M63:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP67]], i32 8)
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 0
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 1
; CHECK-NEXT:    [[VLDH64IP_M64:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP69]], i32 8)
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M64]], 0
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M64]], 1
; CHECK-NEXT:    [[VLDL64IP_M65:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP71]], i32 8)
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M65]], 0
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M65]], 1
; CHECK-NEXT:    [[VLDH64IP_M66:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP73]], i32 8)
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M66]], 0
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M66]], 1
; CHECK-NEXT:    [[VLDL64IP_M67:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP75]], i32 8)
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 0
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 1
; CHECK-NEXT:    [[VLDH64IP_M68:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP77]], i32 8)
; CHECK-NEXT:    [[TMP78:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M68]], 0
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M68]], 1
; CHECK-NEXT:    [[VLDL64IP_M69:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP79]], i32 8)
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M69]], 0
; CHECK-NEXT:    [[TMP81:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M69]], 1
; CHECK-NEXT:    [[VLDH64IP_M70:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP81]], i32 8)
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M70]], 0
; CHECK-NEXT:    [[TMP83:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M70]], 1
; CHECK-NEXT:    [[VLDL64IP_M71:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP83]], i32 8)
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 0
; CHECK-NEXT:    [[TMP85:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 1
; CHECK-NEXT:    [[VLDH64IP_M72:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP85]], i32 8)
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 0
; CHECK-NEXT:    [[TMP87:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 1
; CHECK-NEXT:    [[VLDL64IP_M73:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP87]], i32 8)
; CHECK-NEXT:    [[TMP88:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 0
; CHECK-NEXT:    [[TMP89:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 1
; CHECK-NEXT:    [[VLDH64IP_M74:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP89]], i32 8)
; CHECK-NEXT:    [[TMP90:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 0
; CHECK-NEXT:    [[TMP91:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 1
; CHECK-NEXT:    [[VLDL64IP_M75:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP91]], i32 8)
; CHECK-NEXT:    [[TMP92:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 0
; CHECK-NEXT:    [[TMP93:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 1
; CHECK-NEXT:    [[VLDH64IP_M76:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP93]], i32 8)
; CHECK-NEXT:    [[TMP94:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 0
; CHECK-NEXT:    [[TMP95:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 1
; CHECK-NEXT:    [[VSTL64IP_M77:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP64]], ptr [[VSTH64IP_M60]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M78:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP66]], ptr [[VSTL64IP_M77]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M79:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP68]], ptr [[VSTH64IP_M78]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP70]], ptr [[VSTL64IP_M79]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M81:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP72]], ptr [[VSTH64IP_M80]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M82:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP74]], ptr [[VSTL64IP_M81]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M83:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP76]], ptr [[VSTH64IP_M82]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M84:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP78]], ptr [[VSTL64IP_M83]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M85:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP80]], ptr [[VSTH64IP_M84]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M86:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP82]], ptr [[VSTL64IP_M85]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M87:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP84]], ptr [[VSTH64IP_M86]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M88:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP86]], ptr [[VSTL64IP_M87]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP88]], ptr [[VSTH64IP_M88]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M90:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP90]], ptr [[VSTL64IP_M89]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M91:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP92]], ptr [[VSTH64IP_M90]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M92:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP94]], ptr [[VSTL64IP_M91]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M93:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP95]], i32 8)
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 0
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 1
; CHECK-NEXT:    [[VLDH64IP_M94:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP97]], i32 8)
; CHECK-NEXT:    [[TMP98:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 0
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 1
; CHECK-NEXT:    [[VLDL64IP_M95:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP99]], i32 8)
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 0
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 1
; CHECK-NEXT:    [[VLDH64IP_M96:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP101]], i32 8)
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 0
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 1
; CHECK-NEXT:    [[VLDL64IP_M97:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP103]], i32 8)
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 0
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 1
; CHECK-NEXT:    [[VLDH64IP_M98:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP105]], i32 8)
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 0
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 1
; CHECK-NEXT:    [[VLDL64IP_M99:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP107]], i32 8)
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M99]], 0
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M99]], 1
; CHECK-NEXT:    [[VLDH64IP_M100:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP109]], i32 8)
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M100]], 0
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M100]], 1
; CHECK-NEXT:    [[VLDL64IP_M101:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP111]], i32 8)
; CHECK-NEXT:    [[TMP112:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M101]], 0
; CHECK-NEXT:    [[TMP113:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M101]], 1
; CHECK-NEXT:    [[VLDH64IP_M102:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP113]], i32 8)
; CHECK-NEXT:    [[TMP114:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M102]], 0
; CHECK-NEXT:    [[TMP115:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M102]], 1
; CHECK-NEXT:    [[VLDL64IP_M103:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP115]], i32 8)
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M103]], 0
; CHECK-NEXT:    [[TMP117:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M103]], 1
; CHECK-NEXT:    [[VLDH64IP_M104:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP117]], i32 8)
; CHECK-NEXT:    [[TMP118:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M104]], 0
; CHECK-NEXT:    [[TMP119:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M104]], 1
; CHECK-NEXT:    [[VLDL64IP_M105:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP119]], i32 8)
; CHECK-NEXT:    [[TMP120:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 0
; CHECK-NEXT:    [[TMP121:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 1
; CHECK-NEXT:    [[VLDH64IP_M106:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP121]], i32 8)
; CHECK-NEXT:    [[TMP122:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M106]], 0
; CHECK-NEXT:    [[TMP123:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M106]], 1
; CHECK-NEXT:    [[VLDL64IP_M107:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP123]], i32 8)
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 0
; CHECK-NEXT:    [[TMP125:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 1
; CHECK-NEXT:    [[VLDH64IP_M108:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP125]], i32 8)
; CHECK-NEXT:    [[TMP126:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 0
; CHECK-NEXT:    [[TMP127:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 1
; CHECK-NEXT:    [[VSTL64IP_M109:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP96]], ptr [[VSTH64IP_M92]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M110:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP98]], ptr [[VSTL64IP_M109]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M111:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP100]], ptr [[VSTH64IP_M110]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M112:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP102]], ptr [[VSTL64IP_M111]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M113:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP104]], ptr [[VSTH64IP_M112]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M114:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP106]], ptr [[VSTL64IP_M113]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M115:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP108]], ptr [[VSTH64IP_M114]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M116:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP110]], ptr [[VSTL64IP_M115]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M117:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP112]], ptr [[VSTH64IP_M116]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M118:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP114]], ptr [[VSTL64IP_M117]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M119:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP116]], ptr [[VSTH64IP_M118]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M120:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP118]], ptr [[VSTL64IP_M119]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M121:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP120]], ptr [[VSTH64IP_M120]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M122:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP122]], ptr [[VSTL64IP_M121]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M123:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP124]], ptr [[VSTH64IP_M122]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M124:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP126]], ptr [[VSTL64IP_M123]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M125:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP127]], i32 8)
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M125]], 0
; CHECK-NEXT:    [[TMP129:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M125]], 1
; CHECK-NEXT:    [[VLDH64IP_M126:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP129]], i32 8)
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M126]], 0
; CHECK-NEXT:    [[TMP131:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M126]], 1
; CHECK-NEXT:    [[VLDL64IP_M127:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP131]], i32 8)
; CHECK-NEXT:    [[TMP132:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M127]], 0
; CHECK-NEXT:    [[TMP133:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M127]], 1
; CHECK-NEXT:    [[VLDH64IP_M128:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP133]], i32 8)
; CHECK-NEXT:    [[TMP134:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M128]], 0
; CHECK-NEXT:    [[TMP135:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M128]], 1
; CHECK-NEXT:    [[VLDL64IP_M129:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP135]], i32 8)
; CHECK-NEXT:    [[TMP136:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M129]], 0
; CHECK-NEXT:    [[TMP137:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M129]], 1
; CHECK-NEXT:    [[VLDH64IP_M130:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP137]], i32 8)
; CHECK-NEXT:    [[TMP138:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M130]], 0
; CHECK-NEXT:    [[TMP139:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M130]], 1
; CHECK-NEXT:    [[VLDL64IP_M131:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP139]], i32 8)
; CHECK-NEXT:    [[TMP140:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 0
; CHECK-NEXT:    [[TMP141:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 1
; CHECK-NEXT:    [[VLDH64IP_M132:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP141]], i32 8)
; CHECK-NEXT:    [[TMP142:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 0
; CHECK-NEXT:    [[TMP143:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 1
; CHECK-NEXT:    [[VLDL64IP_M133:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP143]], i32 8)
; CHECK-NEXT:    [[TMP144:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 0
; CHECK-NEXT:    [[TMP145:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 1
; CHECK-NEXT:    [[VLDH64IP_M134:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP145]], i32 8)
; CHECK-NEXT:    [[TMP146:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 0
; CHECK-NEXT:    [[TMP147:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 1
; CHECK-NEXT:    [[VLDL64IP_M135:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP147]], i32 8)
; CHECK-NEXT:    [[TMP148:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 0
; CHECK-NEXT:    [[TMP149:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 1
; CHECK-NEXT:    [[VLDH64IP_M136:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP149]], i32 8)
; CHECK-NEXT:    [[TMP150:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 0
; CHECK-NEXT:    [[TMP151:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 1
; CHECK-NEXT:    [[VLDL64IP_M137:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP151]], i32 8)
; CHECK-NEXT:    [[TMP152:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M137]], 0
; CHECK-NEXT:    [[TMP153:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M137]], 1
; CHECK-NEXT:    [[VLDH64IP_M138:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP153]], i32 8)
; CHECK-NEXT:    [[TMP154:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M138]], 0
; CHECK-NEXT:    [[TMP155:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M138]], 1
; CHECK-NEXT:    [[VLDL64IP_M139:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP155]], i32 8)
; CHECK-NEXT:    [[TMP156:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M139]], 0
; CHECK-NEXT:    [[TMP157:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M139]], 1
; CHECK-NEXT:    [[VLDH64IP_M140:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP157]], i32 8)
; CHECK-NEXT:    [[TMP158:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M140]], 0
; CHECK-NEXT:    [[TMP159:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M140]], 1
; CHECK-NEXT:    [[VSTL64IP_M141:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP128]], ptr [[VSTH64IP_M124]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M142:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP130]], ptr [[VSTL64IP_M141]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M143:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP132]], ptr [[VSTH64IP_M142]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M144:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP134]], ptr [[VSTL64IP_M143]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M145:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP136]], ptr [[VSTH64IP_M144]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M146:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP138]], ptr [[VSTL64IP_M145]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M147:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP140]], ptr [[VSTH64IP_M146]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M148:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP142]], ptr [[VSTL64IP_M147]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M149:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP144]], ptr [[VSTH64IP_M148]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M150:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP146]], ptr [[VSTL64IP_M149]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M151:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP148]], ptr [[VSTH64IP_M150]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M152:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP150]], ptr [[VSTL64IP_M151]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M153:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP152]], ptr [[VSTH64IP_M152]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M154:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP154]], ptr [[VSTL64IP_M153]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M155:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP156]], ptr [[VSTH64IP_M154]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M156:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP158]], ptr [[VSTL64IP_M155]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M157:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP159]], i32 8)
; CHECK-NEXT:    [[TMP160:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M157]], 0
; CHECK-NEXT:    [[TMP161:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M157]], 1
; CHECK-NEXT:    [[VLDH64IP_M158:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP161]], i32 8)
; CHECK-NEXT:    [[TMP162:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M158]], 0
; CHECK-NEXT:    [[TMP163:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M158]], 1
; CHECK-NEXT:    [[VLDL64IP_M159:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP163]], i32 8)
; CHECK-NEXT:    [[TMP164:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M159]], 0
; CHECK-NEXT:    [[TMP165:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M159]], 1
; CHECK-NEXT:    [[VLDH64IP_M160:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP165]], i32 8)
; CHECK-NEXT:    [[TMP166:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M160]], 0
; CHECK-NEXT:    [[TMP167:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M160]], 1
; CHECK-NEXT:    [[VLDL64IP_M161:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP167]], i32 8)
; CHECK-NEXT:    [[TMP168:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M161]], 0
; CHECK-NEXT:    [[TMP169:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M161]], 1
; CHECK-NEXT:    [[VLDH64IP_M162:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP169]], i32 8)
; CHECK-NEXT:    [[TMP170:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M162]], 0
; CHECK-NEXT:    [[TMP171:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M162]], 1
; CHECK-NEXT:    [[VLDL64IP_M163:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP171]], i32 8)
; CHECK-NEXT:    [[TMP172:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M163]], 0
; CHECK-NEXT:    [[TMP173:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M163]], 1
; CHECK-NEXT:    [[VLDH64IP_M164:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP173]], i32 8)
; CHECK-NEXT:    [[TMP174:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M164]], 0
; CHECK-NEXT:    [[TMP175:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M164]], 1
; CHECK-NEXT:    [[VLDL64IP_M165:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP175]], i32 8)
; CHECK-NEXT:    [[TMP176:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M165]], 0
; CHECK-NEXT:    [[TMP177:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M165]], 1
; CHECK-NEXT:    [[VLDH64IP_M166:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP177]], i32 8)
; CHECK-NEXT:    [[TMP178:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M166]], 0
; CHECK-NEXT:    [[TMP179:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M166]], 1
; CHECK-NEXT:    [[VLDL64IP_M167:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP179]], i32 8)
; CHECK-NEXT:    [[TMP180:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M167]], 0
; CHECK-NEXT:    [[TMP181:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M167]], 1
; CHECK-NEXT:    [[VLDH64IP_M168:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP181]], i32 8)
; CHECK-NEXT:    [[TMP182:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M168]], 0
; CHECK-NEXT:    [[TMP183:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M168]], 1
; CHECK-NEXT:    [[VLDL64IP_M169:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP183]], i32 8)
; CHECK-NEXT:    [[TMP184:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M169]], 0
; CHECK-NEXT:    [[TMP185:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M169]], 1
; CHECK-NEXT:    [[VLDH64IP_M170:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP185]], i32 8)
; CHECK-NEXT:    [[TMP186:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M170]], 0
; CHECK-NEXT:    [[TMP187:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M170]], 1
; CHECK-NEXT:    [[VLDL64IP_M171:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP187]], i32 8)
; CHECK-NEXT:    [[TMP188:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M171]], 0
; CHECK-NEXT:    [[TMP189:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M171]], 1
; CHECK-NEXT:    [[VLDH64IP_M172:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP189]], i32 8)
; CHECK-NEXT:    [[TMP190:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M172]], 0
; CHECK-NEXT:    [[TMP191:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M172]], 1
; CHECK-NEXT:    [[VSTL64IP_M173:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP160]], ptr [[VSTH64IP_M156]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M174:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP162]], ptr [[VSTL64IP_M173]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M175:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP164]], ptr [[VSTH64IP_M174]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M176:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP166]], ptr [[VSTL64IP_M175]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M177:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP168]], ptr [[VSTH64IP_M176]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M178:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP170]], ptr [[VSTL64IP_M177]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M179:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP172]], ptr [[VSTH64IP_M178]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M180:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP174]], ptr [[VSTL64IP_M179]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M181:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP176]], ptr [[VSTH64IP_M180]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M182:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP178]], ptr [[VSTL64IP_M181]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M183:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP180]], ptr [[VSTH64IP_M182]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M184:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP182]], ptr [[VSTL64IP_M183]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M185:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP184]], ptr [[VSTH64IP_M184]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M186:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP186]], ptr [[VSTL64IP_M185]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M187:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP188]], ptr [[VSTH64IP_M186]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M188:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP190]], ptr [[VSTL64IP_M187]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M189:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP191]], i32 8)
; CHECK-NEXT:    [[TMP192:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M189]], 0
; CHECK-NEXT:    [[TMP193:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M189]], 1
; CHECK-NEXT:    [[VLDH64IP_M190:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP193]], i32 8)
; CHECK-NEXT:    [[TMP194:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M190]], 0
; CHECK-NEXT:    [[TMP195:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M190]], 1
; CHECK-NEXT:    [[VLDL64IP_M191:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP195]], i32 8)
; CHECK-NEXT:    [[TMP196:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M191]], 0
; CHECK-NEXT:    [[TMP197:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M191]], 1
; CHECK-NEXT:    [[VLDH64IP_M192:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP197]], i32 8)
; CHECK-NEXT:    [[TMP198:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M192]], 0
; CHECK-NEXT:    [[TMP199:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M192]], 1
; CHECK-NEXT:    [[VLDL64IP_M193:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP199]], i32 8)
; CHECK-NEXT:    [[TMP200:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M193]], 0
; CHECK-NEXT:    [[TMP201:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M193]], 1
; CHECK-NEXT:    [[VLDH64IP_M194:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP201]], i32 8)
; CHECK-NEXT:    [[TMP202:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M194]], 0
; CHECK-NEXT:    [[TMP203:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M194]], 1
; CHECK-NEXT:    [[VLDL64IP_M195:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP203]], i32 8)
; CHECK-NEXT:    [[TMP204:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M195]], 0
; CHECK-NEXT:    [[TMP205:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M195]], 1
; CHECK-NEXT:    [[VLDH64IP_M196:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP205]], i32 8)
; CHECK-NEXT:    [[TMP206:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M196]], 0
; CHECK-NEXT:    [[TMP207:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M196]], 1
; CHECK-NEXT:    [[VLDL64IP_M197:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP207]], i32 8)
; CHECK-NEXT:    [[TMP208:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M197]], 0
; CHECK-NEXT:    [[TMP209:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M197]], 1
; CHECK-NEXT:    [[VLDH64IP_M198:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP209]], i32 8)
; CHECK-NEXT:    [[TMP210:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M198]], 0
; CHECK-NEXT:    [[TMP211:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M198]], 1
; CHECK-NEXT:    [[VLDL64IP_M199:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP211]], i32 8)
; CHECK-NEXT:    [[TMP212:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M199]], 0
; CHECK-NEXT:    [[TMP213:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M199]], 1
; CHECK-NEXT:    [[VLDH64IP_M200:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP213]], i32 8)
; CHECK-NEXT:    [[TMP214:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M200]], 0
; CHECK-NEXT:    [[TMP215:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M200]], 1
; CHECK-NEXT:    [[VLDL64IP_M201:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP215]], i32 8)
; CHECK-NEXT:    [[TMP216:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M201]], 0
; CHECK-NEXT:    [[TMP217:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M201]], 1
; CHECK-NEXT:    [[VLDH64IP_M202:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP217]], i32 8)
; CHECK-NEXT:    [[TMP218:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M202]], 0
; CHECK-NEXT:    [[TMP219:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M202]], 1
; CHECK-NEXT:    [[VLDL64IP_M203:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP219]], i32 8)
; CHECK-NEXT:    [[TMP220:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M203]], 0
; CHECK-NEXT:    [[TMP221:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M203]], 1
; CHECK-NEXT:    [[VLDH64IP_M204:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP221]], i32 8)
; CHECK-NEXT:    [[TMP222:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M204]], 0
; CHECK-NEXT:    [[TMP223:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M204]], 1
; CHECK-NEXT:    [[VSTL64IP_M205:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP192]], ptr [[VSTH64IP_M188]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M206:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP194]], ptr [[VSTL64IP_M205]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M207:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP196]], ptr [[VSTH64IP_M206]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M208:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP198]], ptr [[VSTL64IP_M207]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M209:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP200]], ptr [[VSTH64IP_M208]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M210:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP202]], ptr [[VSTL64IP_M209]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M211:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP204]], ptr [[VSTH64IP_M210]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M212:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP206]], ptr [[VSTL64IP_M211]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M213:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP208]], ptr [[VSTH64IP_M212]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M214:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP210]], ptr [[VSTL64IP_M213]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M215:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP212]], ptr [[VSTH64IP_M214]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M216:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP214]], ptr [[VSTL64IP_M215]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M217:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP216]], ptr [[VSTH64IP_M216]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M218:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP218]], ptr [[VSTL64IP_M217]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M219:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP220]], ptr [[VSTH64IP_M218]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M220:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP222]], ptr [[VSTL64IP_M219]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M221:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP223]], i32 8)
; CHECK-NEXT:    [[TMP224:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M221]], 0
; CHECK-NEXT:    [[TMP225:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M221]], 1
; CHECK-NEXT:    [[VLDH64IP_M222:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP225]], i32 8)
; CHECK-NEXT:    [[TMP226:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M222]], 0
; CHECK-NEXT:    [[TMP227:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M222]], 1
; CHECK-NEXT:    [[VLDL64IP_M223:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP227]], i32 8)
; CHECK-NEXT:    [[TMP228:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M223]], 0
; CHECK-NEXT:    [[TMP229:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M223]], 1
; CHECK-NEXT:    [[VLDH64IP_M224:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP229]], i32 8)
; CHECK-NEXT:    [[TMP230:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M224]], 0
; CHECK-NEXT:    [[TMP231:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M224]], 1
; CHECK-NEXT:    [[VLDL64IP_M225:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP231]], i32 8)
; CHECK-NEXT:    [[TMP232:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M225]], 0
; CHECK-NEXT:    [[TMP233:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M225]], 1
; CHECK-NEXT:    [[VLDH64IP_M226:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP233]], i32 8)
; CHECK-NEXT:    [[TMP234:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M226]], 0
; CHECK-NEXT:    [[TMP235:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M226]], 1
; CHECK-NEXT:    [[VLDL64IP_M227:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP235]], i32 8)
; CHECK-NEXT:    [[TMP236:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M227]], 0
; CHECK-NEXT:    [[TMP237:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M227]], 1
; CHECK-NEXT:    [[VLDH64IP_M228:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP237]], i32 8)
; CHECK-NEXT:    [[TMP238:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M228]], 0
; CHECK-NEXT:    [[TMP239:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M228]], 1
; CHECK-NEXT:    [[VLDL64IP_M229:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP239]], i32 8)
; CHECK-NEXT:    [[TMP240:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M229]], 0
; CHECK-NEXT:    [[TMP241:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M229]], 1
; CHECK-NEXT:    [[VLDH64IP_M230:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP241]], i32 8)
; CHECK-NEXT:    [[TMP242:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M230]], 0
; CHECK-NEXT:    [[TMP243:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M230]], 1
; CHECK-NEXT:    [[VLDL64IP_M231:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP243]], i32 8)
; CHECK-NEXT:    [[TMP244:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M231]], 0
; CHECK-NEXT:    [[TMP245:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M231]], 1
; CHECK-NEXT:    [[VLDH64IP_M232:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP245]], i32 8)
; CHECK-NEXT:    [[TMP246:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M232]], 0
; CHECK-NEXT:    [[TMP247:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M232]], 1
; CHECK-NEXT:    [[VLDL64IP_M233:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP247]], i32 8)
; CHECK-NEXT:    [[TMP248:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M233]], 0
; CHECK-NEXT:    [[TMP249:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M233]], 1
; CHECK-NEXT:    [[VLDH64IP_M234:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP249]], i32 8)
; CHECK-NEXT:    [[TMP250:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M234]], 0
; CHECK-NEXT:    [[TMP251:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M234]], 1
; CHECK-NEXT:    [[VLDL64IP_M235:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP251]], i32 8)
; CHECK-NEXT:    [[TMP252:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M235]], 0
; CHECK-NEXT:    [[TMP253:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M235]], 1
; CHECK-NEXT:    [[VLDH64IP_M236:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP253]], i32 8)
; CHECK-NEXT:    [[TMP254:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M236]], 0
; CHECK-NEXT:    [[VSTL64IP_M237:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP224]], ptr [[VSTH64IP_M220]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M238:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP226]], ptr [[VSTL64IP_M237]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M239:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP228]], ptr [[VSTH64IP_M238]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M240:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP230]], ptr [[VSTL64IP_M239]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M241:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP232]], ptr [[VSTH64IP_M240]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M242:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP234]], ptr [[VSTL64IP_M241]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M243:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP236]], ptr [[VSTH64IP_M242]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M244:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP238]], ptr [[VSTL64IP_M243]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M245:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP240]], ptr [[VSTH64IP_M244]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M246:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP242]], ptr [[VSTL64IP_M245]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M247:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP244]], ptr [[VSTH64IP_M246]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M248:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP246]], ptr [[VSTL64IP_M247]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M249:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP248]], ptr [[VSTH64IP_M248]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M250:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP250]], ptr [[VSTL64IP_M249]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M251:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP252]], ptr [[VSTH64IP_M250]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M252:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP254]], ptr [[VSTL64IP_M251]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(1024) %a, ptr noundef nonnull align 8 dereferenceable(1024) %b, i32 1024, i1 false)
  ret void
}

define void @test_src8_dst16_size_20000(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst16_size_20000(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrc8Dst16Const16(ptr [[A]], ptr [[B]], i32 20000)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(20000) %a, ptr noundef nonnull align 8 dereferenceable(20000) %b, i32 20000, i1 false)
  ret void
}

define void @test_src8_dst8_size_1(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(1) %a, ptr noundef nonnull align 8 dereferenceable(1) %b, i32 1, i1 false)
  ret void
}

define void @test_src8_dst8_size_2(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_2(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(2) %a, ptr noundef nonnull align 8 dereferenceable(2) %b, i32 2, i1 false)
  ret void
}

define void @test_src8_dst8_size_3(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_3(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(3) %a, ptr noundef nonnull align 8 dereferenceable(3) %b, i32 3, i1 false)
  ret void
}

define void @test_src8_dst8_size_4(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_4(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(4) %a, ptr noundef nonnull align 8 dereferenceable(4) %b, i32 4, i1 false)
  ret void
}

define void @test_src8_dst8_size_5(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_5(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(5) %a, ptr noundef nonnull align 8 dereferenceable(5) %b, i32 5, i1 false)
  ret void
}

define void @test_src8_dst8_size_6(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_6(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(6) %a, ptr noundef nonnull align 8 dereferenceable(6) %b, i32 6, i1 false)
  ret void
}

define void @test_src8_dst8_size_7(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_7(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(7) %a, ptr noundef nonnull align 8 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_src8_dst8_size_8(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_8(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(8) %a, ptr noundef nonnull align 8 dereferenceable(8) %b, i32 8, i1 false)
  ret void
}

define void @test_src8_dst8_size_9(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_9(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[VSTL64IP_M]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(9) %a, ptr noundef nonnull align 8 dereferenceable(9) %b, i32 9, i1 false)
  ret void
}

define void @test_src8_dst8_size_10(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_10(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[VSTL64IP_M]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(10) %a, ptr noundef nonnull align 8 dereferenceable(10) %b, i32 10, i1 false)
  ret void
}

define void @test_src8_dst8_size_11(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_11(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP2]], ptr [[VSTL64IP_M]], align 2
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 2
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(11) %a, ptr noundef nonnull align 8 dereferenceable(11) %b, i32 11, i1 false)
  ret void
}

define void @test_src8_dst8_size_12(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_12(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(12) %a, ptr noundef nonnull align 8 dereferenceable(12) %b, i32 12, i1 false)
  ret void
}

define void @test_src8_dst8_size_13(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_13(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(13) %a, ptr noundef nonnull align 8 dereferenceable(13) %b, i32 13, i1 false)
  ret void
}

define void @test_src8_dst8_size_14(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_14(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    store i16 [[TMP5]], ptr [[TMP4]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(14) %a, ptr noundef nonnull align 8 dereferenceable(14) %b, i32 14, i1 false)
  ret void
}

define void @test_src8_dst8_size_15(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_15(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP2]], ptr [[VSTL64IP_M]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[TMP1]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 4
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[TMP3]], align 2
; CHECK-NEXT:    store i16 [[TMP5]], ptr [[TMP4]], align 2
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[TMP1]], i32 6
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[VSTL64IP_M]], i32 6
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[TMP6]], align 1
; CHECK-NEXT:    store i8 [[TMP8]], ptr [[TMP7]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(15) %a, ptr noundef nonnull align 8 dereferenceable(15) %b, i32 15, i1 false)
  ret void
}

define void @test_src8_dst8_size_16(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(16) %a, ptr noundef nonnull align 8 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_src8_dst8_size_17(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_17(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[TMP3]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[TMP4]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(17) %a, ptr noundef nonnull align 8 dereferenceable(17) %b, i32 17, i1 false)
  ret void
}

define void @test_src8_dst8_size_31(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_31(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VSTL64IP_M2:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP5]], ptr [[TMP4]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP6]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[VSTL64IP_M2]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[TMP6]], i32 4
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[VSTL64IP_M2]], i32 4
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[TMP8]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[TMP9]], align 2
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[TMP6]], i32 6
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[VSTL64IP_M2]], i32 6
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[TMP11]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[TMP12]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(31) %a, ptr noundef nonnull align 8 dereferenceable(31) %b, i32 31, i1 false)
  ret void
}

define void @test_src8_dst8_size_32(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_32(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M3]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(32) %a, ptr noundef nonnull align 8 dereferenceable(32) %b, i32 32, i1 false)
  ret void
}

define void @test_src8_dst8_size_33(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_33(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M3]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[TMP8]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(33) %a, ptr noundef nonnull align 8 dereferenceable(33) %b, i32 33, i1 false)
  ret void
}

define void @test_src8_dst8_size_47(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M3:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M4:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M3]], i32 8)
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VSTL64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[TMP8]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[TMP10]], align 4
; CHECK-NEXT:    store i32 [[TMP11]], ptr [[VSTL64IP_M6]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[TMP10]], i32 4
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[VSTL64IP_M6]], i32 4
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[TMP12]], align 2
; CHECK-NEXT:    store i16 [[TMP14]], ptr [[TMP13]], align 2
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[TMP10]], i32 6
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[VSTL64IP_M6]], i32 6
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[TMP15]], align 1
; CHECK-NEXT:    store i8 [[TMP17]], ptr [[TMP16]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(47) %a, ptr noundef nonnull align 8 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

define void @test_src8_dst8_size_48(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M6]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(48) %a, ptr noundef nonnull align 8 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_src8_dst8_size_49(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_49(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M6]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[TMP11]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[TMP12]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(49) %a, ptr noundef nonnull align 8 dereferenceable(49) %b, i32 49, i1 false)
  ret void
}

define void @test_src8_dst8_size_63(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_63(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M5:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M6:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M5]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M6]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VSTL64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP13]], ptr [[TMP12]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[TMP14]], align 4
; CHECK-NEXT:    store i32 [[TMP15]], ptr [[VSTL64IP_M10]], align 4
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[TMP14]], i32 4
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr i8, ptr [[VSTL64IP_M10]], i32 4
; CHECK-NEXT:    [[TMP18:%.*]] = load i16, ptr [[TMP16]], align 2
; CHECK-NEXT:    store i16 [[TMP18]], ptr [[TMP17]], align 2
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[TMP14]], i32 6
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i8, ptr [[VSTL64IP_M10]], i32 6
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[TMP19]], align 1
; CHECK-NEXT:    store i8 [[TMP21]], ptr [[TMP20]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(63) %a, ptr noundef nonnull align 8 dereferenceable(63) %b, i32 63, i1 false)
  ret void
}

define void @test_src8_dst8_size_64(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_64(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(64) %a, ptr noundef nonnull align 8 dereferenceable(64) %b, i32 64, i1 false)
  ret void
}

define void @test_src8_dst8_size_65(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_65(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M7:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M7]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[B]], i32 64
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr i8, ptr [[A]], i32 64
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[TMP15]], align 1
; CHECK-NEXT:    store i8 [[TMP17]], ptr [[TMP16]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(65) %a, ptr noundef nonnull align 8 dereferenceable(65) %b, i32 65, i1 false)
  ret void
}

define void @test_src8_dst8_size_80(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_80(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(80) %a, ptr noundef nonnull align 8 dereferenceable(80) %b, i32 80, i1 false)
  ret void
}

define void @test_src8_dst8_size_81(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_81(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr i8, ptr [[B]], i32 80
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i8, ptr [[A]], i32 80
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[TMP19]], align 1
; CHECK-NEXT:    store i8 [[TMP21]], ptr [[TMP20]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(81) %a, ptr noundef nonnull align 8 dereferenceable(81) %b, i32 81, i1 false)
  ret void
}

define void @test_src8_dst8_size_88(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_88(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M1]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDH64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M3]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDH64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M5]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDH64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M7]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M7]], 1
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M8:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M9:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M8]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTH64IP_M9]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M10]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTH64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTH64IP_M13]], i32 8)
; CHECK-NEXT:    [[VLDH64IP_M15:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M15]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M15]], 1
; CHECK-NEXT:    [[VLDH64IP_M16:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M16]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M16]], 1
; CHECK-NEXT:    [[VLDH64IP_M17:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M17]], 0
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M19]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(88) %a, ptr noundef nonnull align 8 dereferenceable(88) %b, i32 88, i1 false)
  ret void
}

define void @test_src8_dst8_size_96(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_96(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M11:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M12:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M11]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M12]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(96) %a, ptr noundef nonnull align 8 dereferenceable(96) %b, i32 96, i1 false)
  ret void
}

define void @test_src8_dst8_size_112(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_112(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(112) %a, ptr noundef nonnull align 8 dereferenceable(112) %b, i32 112, i1 false)
  ret void
}

define void @test_src8_dst8_size_124(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_124(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[VLDL64IP_M25:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 0
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 1
; CHECK-NEXT:    [[VSTL64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP29]], ptr [[TMP28]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[TMP30]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[VSTL64IP_M26]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(124) %a, ptr noundef nonnull align 8 dereferenceable(124) %b, i32 124, i1 false)
  ret void
}

define void @test_src8_dst8_size_127(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_127(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M13:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M14:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M13]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M14]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[VLDL64IP_M25:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 0
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 1
; CHECK-NEXT:    [[VSTL64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP29]], ptr [[TMP28]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = load i32, ptr [[TMP30]], align 4
; CHECK-NEXT:    store i32 [[TMP31]], ptr [[VSTL64IP_M26]], align 4
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr i8, ptr [[TMP30]], i32 4
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr i8, ptr [[VSTL64IP_M26]], i32 4
; CHECK-NEXT:    [[TMP34:%.*]] = load i16, ptr [[TMP32]], align 2
; CHECK-NEXT:    store i16 [[TMP34]], ptr [[TMP33]], align 2
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr i8, ptr [[TMP30]], i32 6
; CHECK-NEXT:    [[TMP36:%.*]] = getelementptr i8, ptr [[VSTL64IP_M26]], i32 6
; CHECK-NEXT:    [[TMP37:%.*]] = load i8, ptr [[TMP35]], align 1
; CHECK-NEXT:    store i8 [[TMP37]], ptr [[TMP36]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(127) %a, ptr noundef nonnull align 8 dereferenceable(127) %b, i32 127, i1 false)
  ret void
}

define void @test_src8_dst8_size_128(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(128) %a, ptr noundef nonnull align 8 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_src8_dst8_size_129(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_129(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr i8, ptr [[B]], i32 128
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr i8, ptr [[A]], i32 128
; CHECK-NEXT:    [[TMP33:%.*]] = load i8, ptr [[TMP31]], align 1
; CHECK-NEXT:    store i8 [[TMP33]], ptr [[TMP32]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(129) %a, ptr noundef nonnull align 8 dereferenceable(129) %b, i32 129, i1 false)
  ret void
}

define void @test_src8_dst8_size_255(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_255(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M29:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 1
; CHECK-NEXT:    [[VLDH64IP_M30:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP33]], i32 8)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 1
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP35]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP37]], i32 8)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M33:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP39]], i32 8)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 1
; CHECK-NEXT:    [[VLDH64IP_M34:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP41]], i32 8)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP43]], i32 8)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP45]], i32 8)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP47]], i32 8)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP49]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP51]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDH64IP_M40:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP53]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 1
; CHECK-NEXT:    [[VLDL64IP_M41:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP55]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 1
; CHECK-NEXT:    [[VLDH64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP57]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 0
; CHECK-NEXT:    [[VSTL64IP_M43:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP32]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M44:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP34]], ptr [[VSTL64IP_M43]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP36]], ptr [[VSTH64IP_M44]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP38]], ptr [[VSTL64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M47:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP40]], ptr [[VSTH64IP_M46]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M48:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP42]], ptr [[VSTL64IP_M47]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP44]], ptr [[VSTH64IP_M48]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP46]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M54]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M55]], i32 8)
; CHECK-NEXT:    [[TMP59:%.*]] = getelementptr i8, ptr [[B]], i32 240
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr i8, ptr [[A]], i32 240
; CHECK-NEXT:    [[VLDL64IP_M57:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP59]], i32 8)
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M57]], 0
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M57]], 1
; CHECK-NEXT:    [[VSTL64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP61]], ptr [[TMP60]], i32 8)
; CHECK-NEXT:    [[TMP63:%.*]] = load i32, ptr [[TMP62]], align 4
; CHECK-NEXT:    store i32 [[TMP63]], ptr [[VSTL64IP_M58]], align 4
; CHECK-NEXT:    [[TMP64:%.*]] = getelementptr i8, ptr [[TMP62]], i32 4
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr i8, ptr [[VSTL64IP_M58]], i32 4
; CHECK-NEXT:    [[TMP66:%.*]] = load i16, ptr [[TMP64]], align 2
; CHECK-NEXT:    store i16 [[TMP66]], ptr [[TMP65]], align 2
; CHECK-NEXT:    [[TMP67:%.*]] = getelementptr i8, ptr [[TMP62]], i32 6
; CHECK-NEXT:    [[TMP68:%.*]] = getelementptr i8, ptr [[VSTL64IP_M58]], i32 6
; CHECK-NEXT:    [[TMP69:%.*]] = load i8, ptr [[TMP67]], align 1
; CHECK-NEXT:    store i8 [[TMP69]], ptr [[TMP68]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(255) %a, ptr noundef nonnull align 8 dereferenceable(255) %b, i32 255, i1 false)
  ret void
}

define void @test_src8_dst8_size_256(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M29:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 1
; CHECK-NEXT:    [[VLDH64IP_M30:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP33]], i32 8)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 1
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP35]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP37]], i32 8)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M33:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP39]], i32 8)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 1
; CHECK-NEXT:    [[VLDH64IP_M34:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP41]], i32 8)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP43]], i32 8)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP45]], i32 8)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP47]], i32 8)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP49]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP51]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDH64IP_M40:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP53]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 1
; CHECK-NEXT:    [[VLDL64IP_M41:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP55]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 1
; CHECK-NEXT:    [[VLDH64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP57]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 0
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 1
; CHECK-NEXT:    [[VLDL64IP_M43:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP59]], i32 8)
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 1
; CHECK-NEXT:    [[VLDH64IP_M44:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP61]], i32 8)
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 0
; CHECK-NEXT:    [[VSTL64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP32]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP34]], ptr [[VSTL64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M47:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP36]], ptr [[VSTH64IP_M46]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M48:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP38]], ptr [[VSTL64IP_M47]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP40]], ptr [[VSTH64IP_M48]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP42]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP44]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP46]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M54]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M55]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M56]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M57]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP60]], ptr [[VSTH64IP_M58]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP62]], ptr [[VSTL64IP_M59]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(256) %a, ptr noundef nonnull align 8 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

define void @test_src8_dst8_size_1023(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_1023(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M29:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 1
; CHECK-NEXT:    [[VLDH64IP_M30:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP33]], i32 8)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 1
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP35]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP37]], i32 8)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M33:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP39]], i32 8)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 1
; CHECK-NEXT:    [[VLDH64IP_M34:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP41]], i32 8)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP43]], i32 8)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP45]], i32 8)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP47]], i32 8)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP49]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP51]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDH64IP_M40:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP53]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 1
; CHECK-NEXT:    [[VLDL64IP_M41:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP55]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 1
; CHECK-NEXT:    [[VLDH64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP57]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 0
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 1
; CHECK-NEXT:    [[VLDL64IP_M43:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP59]], i32 8)
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 1
; CHECK-NEXT:    [[VLDH64IP_M44:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP61]], i32 8)
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 0
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 1
; CHECK-NEXT:    [[VSTL64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP32]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP34]], ptr [[VSTL64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M47:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP36]], ptr [[VSTH64IP_M46]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M48:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP38]], ptr [[VSTL64IP_M47]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP40]], ptr [[VSTH64IP_M48]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP42]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP44]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP46]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M54]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M55]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M56]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M57]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP60]], ptr [[VSTH64IP_M58]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP62]], ptr [[VSTL64IP_M59]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M61:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP63]], i32 8)
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 0
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 1
; CHECK-NEXT:    [[VLDH64IP_M62:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP65]], i32 8)
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 0
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 1
; CHECK-NEXT:    [[VLDL64IP_M63:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP67]], i32 8)
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 0
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 1
; CHECK-NEXT:    [[VLDH64IP_M64:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP69]], i32 8)
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M64]], 0
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M64]], 1
; CHECK-NEXT:    [[VLDL64IP_M65:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP71]], i32 8)
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M65]], 0
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M65]], 1
; CHECK-NEXT:    [[VLDH64IP_M66:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP73]], i32 8)
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M66]], 0
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M66]], 1
; CHECK-NEXT:    [[VLDL64IP_M67:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP75]], i32 8)
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 0
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 1
; CHECK-NEXT:    [[VLDH64IP_M68:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP77]], i32 8)
; CHECK-NEXT:    [[TMP78:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M68]], 0
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M68]], 1
; CHECK-NEXT:    [[VLDL64IP_M69:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP79]], i32 8)
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M69]], 0
; CHECK-NEXT:    [[TMP81:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M69]], 1
; CHECK-NEXT:    [[VLDH64IP_M70:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP81]], i32 8)
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M70]], 0
; CHECK-NEXT:    [[TMP83:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M70]], 1
; CHECK-NEXT:    [[VLDL64IP_M71:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP83]], i32 8)
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 0
; CHECK-NEXT:    [[TMP85:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 1
; CHECK-NEXT:    [[VLDH64IP_M72:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP85]], i32 8)
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 0
; CHECK-NEXT:    [[TMP87:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 1
; CHECK-NEXT:    [[VLDL64IP_M73:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP87]], i32 8)
; CHECK-NEXT:    [[TMP88:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 0
; CHECK-NEXT:    [[TMP89:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 1
; CHECK-NEXT:    [[VLDH64IP_M74:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP89]], i32 8)
; CHECK-NEXT:    [[TMP90:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 0
; CHECK-NEXT:    [[TMP91:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 1
; CHECK-NEXT:    [[VLDL64IP_M75:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP91]], i32 8)
; CHECK-NEXT:    [[TMP92:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 0
; CHECK-NEXT:    [[TMP93:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 1
; CHECK-NEXT:    [[VLDH64IP_M76:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP93]], i32 8)
; CHECK-NEXT:    [[TMP94:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 0
; CHECK-NEXT:    [[TMP95:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 1
; CHECK-NEXT:    [[VSTL64IP_M77:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP64]], ptr [[VSTH64IP_M60]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M78:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP66]], ptr [[VSTL64IP_M77]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M79:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP68]], ptr [[VSTH64IP_M78]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP70]], ptr [[VSTL64IP_M79]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M81:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP72]], ptr [[VSTH64IP_M80]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M82:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP74]], ptr [[VSTL64IP_M81]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M83:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP76]], ptr [[VSTH64IP_M82]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M84:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP78]], ptr [[VSTL64IP_M83]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M85:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP80]], ptr [[VSTH64IP_M84]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M86:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP82]], ptr [[VSTL64IP_M85]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M87:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP84]], ptr [[VSTH64IP_M86]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M88:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP86]], ptr [[VSTL64IP_M87]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP88]], ptr [[VSTH64IP_M88]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M90:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP90]], ptr [[VSTL64IP_M89]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M91:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP92]], ptr [[VSTH64IP_M90]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M92:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP94]], ptr [[VSTL64IP_M91]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M93:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP95]], i32 8)
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 0
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 1
; CHECK-NEXT:    [[VLDH64IP_M94:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP97]], i32 8)
; CHECK-NEXT:    [[TMP98:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 0
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 1
; CHECK-NEXT:    [[VLDL64IP_M95:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP99]], i32 8)
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 0
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 1
; CHECK-NEXT:    [[VLDH64IP_M96:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP101]], i32 8)
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 0
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 1
; CHECK-NEXT:    [[VLDL64IP_M97:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP103]], i32 8)
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 0
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 1
; CHECK-NEXT:    [[VLDH64IP_M98:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP105]], i32 8)
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 0
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 1
; CHECK-NEXT:    [[VLDL64IP_M99:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP107]], i32 8)
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M99]], 0
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M99]], 1
; CHECK-NEXT:    [[VLDH64IP_M100:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP109]], i32 8)
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M100]], 0
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M100]], 1
; CHECK-NEXT:    [[VLDL64IP_M101:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP111]], i32 8)
; CHECK-NEXT:    [[TMP112:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M101]], 0
; CHECK-NEXT:    [[TMP113:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M101]], 1
; CHECK-NEXT:    [[VLDH64IP_M102:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP113]], i32 8)
; CHECK-NEXT:    [[TMP114:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M102]], 0
; CHECK-NEXT:    [[TMP115:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M102]], 1
; CHECK-NEXT:    [[VLDL64IP_M103:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP115]], i32 8)
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M103]], 0
; CHECK-NEXT:    [[TMP117:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M103]], 1
; CHECK-NEXT:    [[VLDH64IP_M104:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP117]], i32 8)
; CHECK-NEXT:    [[TMP118:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M104]], 0
; CHECK-NEXT:    [[TMP119:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M104]], 1
; CHECK-NEXT:    [[VLDL64IP_M105:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP119]], i32 8)
; CHECK-NEXT:    [[TMP120:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 0
; CHECK-NEXT:    [[TMP121:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 1
; CHECK-NEXT:    [[VLDH64IP_M106:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP121]], i32 8)
; CHECK-NEXT:    [[TMP122:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M106]], 0
; CHECK-NEXT:    [[TMP123:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M106]], 1
; CHECK-NEXT:    [[VLDL64IP_M107:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP123]], i32 8)
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 0
; CHECK-NEXT:    [[TMP125:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 1
; CHECK-NEXT:    [[VLDH64IP_M108:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP125]], i32 8)
; CHECK-NEXT:    [[TMP126:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 0
; CHECK-NEXT:    [[TMP127:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 1
; CHECK-NEXT:    [[VSTL64IP_M109:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP96]], ptr [[VSTH64IP_M92]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M110:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP98]], ptr [[VSTL64IP_M109]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M111:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP100]], ptr [[VSTH64IP_M110]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M112:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP102]], ptr [[VSTL64IP_M111]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M113:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP104]], ptr [[VSTH64IP_M112]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M114:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP106]], ptr [[VSTL64IP_M113]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M115:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP108]], ptr [[VSTH64IP_M114]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M116:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP110]], ptr [[VSTL64IP_M115]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M117:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP112]], ptr [[VSTH64IP_M116]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M118:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP114]], ptr [[VSTL64IP_M117]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M119:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP116]], ptr [[VSTH64IP_M118]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M120:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP118]], ptr [[VSTL64IP_M119]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M121:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP120]], ptr [[VSTH64IP_M120]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M122:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP122]], ptr [[VSTL64IP_M121]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M123:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP124]], ptr [[VSTH64IP_M122]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M124:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP126]], ptr [[VSTL64IP_M123]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M125:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP127]], i32 8)
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M125]], 0
; CHECK-NEXT:    [[TMP129:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M125]], 1
; CHECK-NEXT:    [[VLDH64IP_M126:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP129]], i32 8)
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M126]], 0
; CHECK-NEXT:    [[TMP131:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M126]], 1
; CHECK-NEXT:    [[VLDL64IP_M127:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP131]], i32 8)
; CHECK-NEXT:    [[TMP132:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M127]], 0
; CHECK-NEXT:    [[TMP133:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M127]], 1
; CHECK-NEXT:    [[VLDH64IP_M128:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP133]], i32 8)
; CHECK-NEXT:    [[TMP134:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M128]], 0
; CHECK-NEXT:    [[TMP135:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M128]], 1
; CHECK-NEXT:    [[VLDL64IP_M129:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP135]], i32 8)
; CHECK-NEXT:    [[TMP136:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M129]], 0
; CHECK-NEXT:    [[TMP137:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M129]], 1
; CHECK-NEXT:    [[VLDH64IP_M130:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP137]], i32 8)
; CHECK-NEXT:    [[TMP138:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M130]], 0
; CHECK-NEXT:    [[TMP139:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M130]], 1
; CHECK-NEXT:    [[VLDL64IP_M131:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP139]], i32 8)
; CHECK-NEXT:    [[TMP140:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 0
; CHECK-NEXT:    [[TMP141:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 1
; CHECK-NEXT:    [[VLDH64IP_M132:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP141]], i32 8)
; CHECK-NEXT:    [[TMP142:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 0
; CHECK-NEXT:    [[TMP143:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 1
; CHECK-NEXT:    [[VLDL64IP_M133:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP143]], i32 8)
; CHECK-NEXT:    [[TMP144:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 0
; CHECK-NEXT:    [[TMP145:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 1
; CHECK-NEXT:    [[VLDH64IP_M134:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP145]], i32 8)
; CHECK-NEXT:    [[TMP146:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 0
; CHECK-NEXT:    [[TMP147:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 1
; CHECK-NEXT:    [[VLDL64IP_M135:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP147]], i32 8)
; CHECK-NEXT:    [[TMP148:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 0
; CHECK-NEXT:    [[TMP149:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 1
; CHECK-NEXT:    [[VLDH64IP_M136:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP149]], i32 8)
; CHECK-NEXT:    [[TMP150:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 0
; CHECK-NEXT:    [[TMP151:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 1
; CHECK-NEXT:    [[VLDL64IP_M137:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP151]], i32 8)
; CHECK-NEXT:    [[TMP152:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M137]], 0
; CHECK-NEXT:    [[TMP153:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M137]], 1
; CHECK-NEXT:    [[VLDH64IP_M138:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP153]], i32 8)
; CHECK-NEXT:    [[TMP154:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M138]], 0
; CHECK-NEXT:    [[TMP155:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M138]], 1
; CHECK-NEXT:    [[VLDL64IP_M139:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP155]], i32 8)
; CHECK-NEXT:    [[TMP156:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M139]], 0
; CHECK-NEXT:    [[TMP157:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M139]], 1
; CHECK-NEXT:    [[VLDH64IP_M140:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP157]], i32 8)
; CHECK-NEXT:    [[TMP158:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M140]], 0
; CHECK-NEXT:    [[TMP159:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M140]], 1
; CHECK-NEXT:    [[VSTL64IP_M141:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP128]], ptr [[VSTH64IP_M124]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M142:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP130]], ptr [[VSTL64IP_M141]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M143:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP132]], ptr [[VSTH64IP_M142]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M144:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP134]], ptr [[VSTL64IP_M143]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M145:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP136]], ptr [[VSTH64IP_M144]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M146:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP138]], ptr [[VSTL64IP_M145]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M147:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP140]], ptr [[VSTH64IP_M146]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M148:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP142]], ptr [[VSTL64IP_M147]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M149:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP144]], ptr [[VSTH64IP_M148]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M150:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP146]], ptr [[VSTL64IP_M149]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M151:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP148]], ptr [[VSTH64IP_M150]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M152:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP150]], ptr [[VSTL64IP_M151]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M153:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP152]], ptr [[VSTH64IP_M152]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M154:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP154]], ptr [[VSTL64IP_M153]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M155:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP156]], ptr [[VSTH64IP_M154]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M156:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP158]], ptr [[VSTL64IP_M155]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M157:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP159]], i32 8)
; CHECK-NEXT:    [[TMP160:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M157]], 0
; CHECK-NEXT:    [[TMP161:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M157]], 1
; CHECK-NEXT:    [[VLDH64IP_M158:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP161]], i32 8)
; CHECK-NEXT:    [[TMP162:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M158]], 0
; CHECK-NEXT:    [[TMP163:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M158]], 1
; CHECK-NEXT:    [[VLDL64IP_M159:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP163]], i32 8)
; CHECK-NEXT:    [[TMP164:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M159]], 0
; CHECK-NEXT:    [[TMP165:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M159]], 1
; CHECK-NEXT:    [[VLDH64IP_M160:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP165]], i32 8)
; CHECK-NEXT:    [[TMP166:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M160]], 0
; CHECK-NEXT:    [[TMP167:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M160]], 1
; CHECK-NEXT:    [[VLDL64IP_M161:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP167]], i32 8)
; CHECK-NEXT:    [[TMP168:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M161]], 0
; CHECK-NEXT:    [[TMP169:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M161]], 1
; CHECK-NEXT:    [[VLDH64IP_M162:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP169]], i32 8)
; CHECK-NEXT:    [[TMP170:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M162]], 0
; CHECK-NEXT:    [[TMP171:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M162]], 1
; CHECK-NEXT:    [[VLDL64IP_M163:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP171]], i32 8)
; CHECK-NEXT:    [[TMP172:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M163]], 0
; CHECK-NEXT:    [[TMP173:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M163]], 1
; CHECK-NEXT:    [[VLDH64IP_M164:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP173]], i32 8)
; CHECK-NEXT:    [[TMP174:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M164]], 0
; CHECK-NEXT:    [[TMP175:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M164]], 1
; CHECK-NEXT:    [[VLDL64IP_M165:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP175]], i32 8)
; CHECK-NEXT:    [[TMP176:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M165]], 0
; CHECK-NEXT:    [[TMP177:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M165]], 1
; CHECK-NEXT:    [[VLDH64IP_M166:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP177]], i32 8)
; CHECK-NEXT:    [[TMP178:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M166]], 0
; CHECK-NEXT:    [[TMP179:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M166]], 1
; CHECK-NEXT:    [[VLDL64IP_M167:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP179]], i32 8)
; CHECK-NEXT:    [[TMP180:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M167]], 0
; CHECK-NEXT:    [[TMP181:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M167]], 1
; CHECK-NEXT:    [[VLDH64IP_M168:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP181]], i32 8)
; CHECK-NEXT:    [[TMP182:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M168]], 0
; CHECK-NEXT:    [[TMP183:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M168]], 1
; CHECK-NEXT:    [[VLDL64IP_M169:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP183]], i32 8)
; CHECK-NEXT:    [[TMP184:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M169]], 0
; CHECK-NEXT:    [[TMP185:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M169]], 1
; CHECK-NEXT:    [[VLDH64IP_M170:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP185]], i32 8)
; CHECK-NEXT:    [[TMP186:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M170]], 0
; CHECK-NEXT:    [[TMP187:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M170]], 1
; CHECK-NEXT:    [[VLDL64IP_M171:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP187]], i32 8)
; CHECK-NEXT:    [[TMP188:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M171]], 0
; CHECK-NEXT:    [[TMP189:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M171]], 1
; CHECK-NEXT:    [[VLDH64IP_M172:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP189]], i32 8)
; CHECK-NEXT:    [[TMP190:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M172]], 0
; CHECK-NEXT:    [[TMP191:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M172]], 1
; CHECK-NEXT:    [[VSTL64IP_M173:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP160]], ptr [[VSTH64IP_M156]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M174:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP162]], ptr [[VSTL64IP_M173]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M175:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP164]], ptr [[VSTH64IP_M174]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M176:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP166]], ptr [[VSTL64IP_M175]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M177:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP168]], ptr [[VSTH64IP_M176]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M178:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP170]], ptr [[VSTL64IP_M177]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M179:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP172]], ptr [[VSTH64IP_M178]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M180:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP174]], ptr [[VSTL64IP_M179]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M181:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP176]], ptr [[VSTH64IP_M180]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M182:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP178]], ptr [[VSTL64IP_M181]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M183:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP180]], ptr [[VSTH64IP_M182]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M184:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP182]], ptr [[VSTL64IP_M183]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M185:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP184]], ptr [[VSTH64IP_M184]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M186:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP186]], ptr [[VSTL64IP_M185]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M187:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP188]], ptr [[VSTH64IP_M186]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M188:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP190]], ptr [[VSTL64IP_M187]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M189:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP191]], i32 8)
; CHECK-NEXT:    [[TMP192:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M189]], 0
; CHECK-NEXT:    [[TMP193:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M189]], 1
; CHECK-NEXT:    [[VLDH64IP_M190:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP193]], i32 8)
; CHECK-NEXT:    [[TMP194:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M190]], 0
; CHECK-NEXT:    [[TMP195:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M190]], 1
; CHECK-NEXT:    [[VLDL64IP_M191:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP195]], i32 8)
; CHECK-NEXT:    [[TMP196:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M191]], 0
; CHECK-NEXT:    [[TMP197:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M191]], 1
; CHECK-NEXT:    [[VLDH64IP_M192:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP197]], i32 8)
; CHECK-NEXT:    [[TMP198:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M192]], 0
; CHECK-NEXT:    [[TMP199:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M192]], 1
; CHECK-NEXT:    [[VLDL64IP_M193:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP199]], i32 8)
; CHECK-NEXT:    [[TMP200:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M193]], 0
; CHECK-NEXT:    [[TMP201:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M193]], 1
; CHECK-NEXT:    [[VLDH64IP_M194:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP201]], i32 8)
; CHECK-NEXT:    [[TMP202:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M194]], 0
; CHECK-NEXT:    [[TMP203:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M194]], 1
; CHECK-NEXT:    [[VLDL64IP_M195:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP203]], i32 8)
; CHECK-NEXT:    [[TMP204:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M195]], 0
; CHECK-NEXT:    [[TMP205:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M195]], 1
; CHECK-NEXT:    [[VLDH64IP_M196:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP205]], i32 8)
; CHECK-NEXT:    [[TMP206:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M196]], 0
; CHECK-NEXT:    [[TMP207:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M196]], 1
; CHECK-NEXT:    [[VLDL64IP_M197:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP207]], i32 8)
; CHECK-NEXT:    [[TMP208:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M197]], 0
; CHECK-NEXT:    [[TMP209:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M197]], 1
; CHECK-NEXT:    [[VLDH64IP_M198:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP209]], i32 8)
; CHECK-NEXT:    [[TMP210:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M198]], 0
; CHECK-NEXT:    [[TMP211:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M198]], 1
; CHECK-NEXT:    [[VLDL64IP_M199:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP211]], i32 8)
; CHECK-NEXT:    [[TMP212:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M199]], 0
; CHECK-NEXT:    [[TMP213:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M199]], 1
; CHECK-NEXT:    [[VLDH64IP_M200:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP213]], i32 8)
; CHECK-NEXT:    [[TMP214:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M200]], 0
; CHECK-NEXT:    [[TMP215:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M200]], 1
; CHECK-NEXT:    [[VLDL64IP_M201:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP215]], i32 8)
; CHECK-NEXT:    [[TMP216:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M201]], 0
; CHECK-NEXT:    [[TMP217:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M201]], 1
; CHECK-NEXT:    [[VLDH64IP_M202:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP217]], i32 8)
; CHECK-NEXT:    [[TMP218:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M202]], 0
; CHECK-NEXT:    [[TMP219:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M202]], 1
; CHECK-NEXT:    [[VLDL64IP_M203:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP219]], i32 8)
; CHECK-NEXT:    [[TMP220:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M203]], 0
; CHECK-NEXT:    [[TMP221:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M203]], 1
; CHECK-NEXT:    [[VLDH64IP_M204:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP221]], i32 8)
; CHECK-NEXT:    [[TMP222:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M204]], 0
; CHECK-NEXT:    [[TMP223:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M204]], 1
; CHECK-NEXT:    [[VSTL64IP_M205:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP192]], ptr [[VSTH64IP_M188]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M206:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP194]], ptr [[VSTL64IP_M205]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M207:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP196]], ptr [[VSTH64IP_M206]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M208:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP198]], ptr [[VSTL64IP_M207]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M209:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP200]], ptr [[VSTH64IP_M208]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M210:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP202]], ptr [[VSTL64IP_M209]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M211:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP204]], ptr [[VSTH64IP_M210]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M212:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP206]], ptr [[VSTL64IP_M211]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M213:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP208]], ptr [[VSTH64IP_M212]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M214:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP210]], ptr [[VSTL64IP_M213]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M215:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP212]], ptr [[VSTH64IP_M214]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M216:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP214]], ptr [[VSTL64IP_M215]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M217:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP216]], ptr [[VSTH64IP_M216]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M218:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP218]], ptr [[VSTL64IP_M217]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M219:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP220]], ptr [[VSTH64IP_M218]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M220:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP222]], ptr [[VSTL64IP_M219]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M221:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP223]], i32 8)
; CHECK-NEXT:    [[TMP224:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M221]], 0
; CHECK-NEXT:    [[TMP225:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M221]], 1
; CHECK-NEXT:    [[VLDH64IP_M222:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP225]], i32 8)
; CHECK-NEXT:    [[TMP226:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M222]], 0
; CHECK-NEXT:    [[TMP227:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M222]], 1
; CHECK-NEXT:    [[VLDL64IP_M223:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP227]], i32 8)
; CHECK-NEXT:    [[TMP228:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M223]], 0
; CHECK-NEXT:    [[TMP229:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M223]], 1
; CHECK-NEXT:    [[VLDH64IP_M224:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP229]], i32 8)
; CHECK-NEXT:    [[TMP230:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M224]], 0
; CHECK-NEXT:    [[TMP231:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M224]], 1
; CHECK-NEXT:    [[VLDL64IP_M225:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP231]], i32 8)
; CHECK-NEXT:    [[TMP232:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M225]], 0
; CHECK-NEXT:    [[TMP233:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M225]], 1
; CHECK-NEXT:    [[VLDH64IP_M226:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP233]], i32 8)
; CHECK-NEXT:    [[TMP234:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M226]], 0
; CHECK-NEXT:    [[TMP235:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M226]], 1
; CHECK-NEXT:    [[VLDL64IP_M227:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP235]], i32 8)
; CHECK-NEXT:    [[TMP236:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M227]], 0
; CHECK-NEXT:    [[TMP237:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M227]], 1
; CHECK-NEXT:    [[VLDH64IP_M228:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP237]], i32 8)
; CHECK-NEXT:    [[TMP238:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M228]], 0
; CHECK-NEXT:    [[TMP239:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M228]], 1
; CHECK-NEXT:    [[VLDL64IP_M229:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP239]], i32 8)
; CHECK-NEXT:    [[TMP240:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M229]], 0
; CHECK-NEXT:    [[TMP241:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M229]], 1
; CHECK-NEXT:    [[VLDH64IP_M230:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP241]], i32 8)
; CHECK-NEXT:    [[TMP242:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M230]], 0
; CHECK-NEXT:    [[TMP243:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M230]], 1
; CHECK-NEXT:    [[VLDL64IP_M231:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP243]], i32 8)
; CHECK-NEXT:    [[TMP244:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M231]], 0
; CHECK-NEXT:    [[TMP245:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M231]], 1
; CHECK-NEXT:    [[VLDH64IP_M232:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP245]], i32 8)
; CHECK-NEXT:    [[TMP246:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M232]], 0
; CHECK-NEXT:    [[TMP247:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M232]], 1
; CHECK-NEXT:    [[VLDL64IP_M233:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP247]], i32 8)
; CHECK-NEXT:    [[TMP248:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M233]], 0
; CHECK-NEXT:    [[TMP249:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M233]], 1
; CHECK-NEXT:    [[VLDH64IP_M234:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP249]], i32 8)
; CHECK-NEXT:    [[TMP250:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M234]], 0
; CHECK-NEXT:    [[VSTL64IP_M235:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP224]], ptr [[VSTH64IP_M220]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M236:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP226]], ptr [[VSTL64IP_M235]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M237:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP228]], ptr [[VSTH64IP_M236]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M238:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP230]], ptr [[VSTL64IP_M237]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M239:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP232]], ptr [[VSTH64IP_M238]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M240:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP234]], ptr [[VSTL64IP_M239]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M241:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP236]], ptr [[VSTH64IP_M240]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M242:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP238]], ptr [[VSTL64IP_M241]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M243:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP240]], ptr [[VSTH64IP_M242]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M244:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP242]], ptr [[VSTL64IP_M243]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M245:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP244]], ptr [[VSTH64IP_M244]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M246:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP246]], ptr [[VSTL64IP_M245]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M247:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP248]], ptr [[VSTH64IP_M246]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M248:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP250]], ptr [[VSTL64IP_M247]], i32 8)
; CHECK-NEXT:    [[TMP251:%.*]] = getelementptr i8, ptr [[B]], i32 1008
; CHECK-NEXT:    [[TMP252:%.*]] = getelementptr i8, ptr [[A]], i32 1008
; CHECK-NEXT:    [[VLDL64IP_M249:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP251]], i32 8)
; CHECK-NEXT:    [[TMP253:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M249]], 0
; CHECK-NEXT:    [[TMP254:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M249]], 1
; CHECK-NEXT:    [[VSTL64IP_M250:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP253]], ptr [[TMP252]], i32 8)
; CHECK-NEXT:    [[TMP255:%.*]] = load i32, ptr [[TMP254]], align 4
; CHECK-NEXT:    store i32 [[TMP255]], ptr [[VSTL64IP_M250]], align 4
; CHECK-NEXT:    [[TMP256:%.*]] = getelementptr i8, ptr [[TMP254]], i32 4
; CHECK-NEXT:    [[TMP257:%.*]] = getelementptr i8, ptr [[VSTL64IP_M250]], i32 4
; CHECK-NEXT:    [[TMP258:%.*]] = load i16, ptr [[TMP256]], align 2
; CHECK-NEXT:    store i16 [[TMP258]], ptr [[TMP257]], align 2
; CHECK-NEXT:    [[TMP259:%.*]] = getelementptr i8, ptr [[TMP254]], i32 6
; CHECK-NEXT:    [[TMP260:%.*]] = getelementptr i8, ptr [[VSTL64IP_M250]], i32 6
; CHECK-NEXT:    [[TMP261:%.*]] = load i8, ptr [[TMP259]], align 1
; CHECK-NEXT:    store i8 [[TMP261]], ptr [[TMP260]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(1023) %a, ptr noundef nonnull align 8 dereferenceable(1023) %b, i32 1023, i1 false)
  ret void
}

define void @test_src8_dst8_size_1024(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_1024(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[B]], i32 8)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDH64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP1]], i32 8)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP3]], i32 8)
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[VLDH64IP_M2:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP5]], i32 8)
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 0
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M2]], 1
; CHECK-NEXT:    [[VLDL64IP_M3:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP7]], i32 8)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M3]], 1
; CHECK-NEXT:    [[VLDH64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP9]], i32 8)
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 0
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M5:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP11]], i32 8)
; CHECK-NEXT:    [[TMP12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 0
; CHECK-NEXT:    [[TMP13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M5]], 1
; CHECK-NEXT:    [[VLDH64IP_M6:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP13]], i32 8)
; CHECK-NEXT:    [[TMP14:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 0
; CHECK-NEXT:    [[TMP15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M6]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP15]], i32 8)
; CHECK-NEXT:    [[TMP16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[VLDH64IP_M8:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP17]], i32 8)
; CHECK-NEXT:    [[TMP18:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 0
; CHECK-NEXT:    [[TMP19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M8]], 1
; CHECK-NEXT:    [[VLDL64IP_M9:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP19]], i32 8)
; CHECK-NEXT:    [[TMP20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 0
; CHECK-NEXT:    [[TMP21:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M9]], 1
; CHECK-NEXT:    [[VLDH64IP_M10:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP21]], i32 8)
; CHECK-NEXT:    [[TMP22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 0
; CHECK-NEXT:    [[TMP23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M10]], 1
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP23]], i32 8)
; CHECK-NEXT:    [[TMP24:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[TMP25:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDH64IP_M12:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP25]], i32 8)
; CHECK-NEXT:    [[TMP26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M12]], 1
; CHECK-NEXT:    [[VLDL64IP_M13:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP27]], i32 8)
; CHECK-NEXT:    [[TMP28:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 0
; CHECK-NEXT:    [[TMP29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M13]], 1
; CHECK-NEXT:    [[VLDH64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP29]], i32 8)
; CHECK-NEXT:    [[TMP30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 0
; CHECK-NEXT:    [[TMP31:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M14]], 1
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP0]], ptr [[A]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP2]], ptr [[VSTL64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M15:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP4]], ptr [[VSTH64IP_M]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M16:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP6]], ptr [[VSTL64IP_M15]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTH64IP_M16]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M18:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP10]], ptr [[VSTL64IP_M17]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M19:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP12]], ptr [[VSTH64IP_M18]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M20:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP14]], ptr [[VSTL64IP_M19]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M21:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP16]], ptr [[VSTH64IP_M20]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M22:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP18]], ptr [[VSTL64IP_M21]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M23:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP20]], ptr [[VSTH64IP_M22]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP22]], ptr [[VSTL64IP_M23]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M25:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP24]], ptr [[VSTH64IP_M24]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M26:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP26]], ptr [[VSTL64IP_M25]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M27:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP28]], ptr [[VSTH64IP_M26]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M28:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP30]], ptr [[VSTL64IP_M27]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M29:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP31]], i32 8)
; CHECK-NEXT:    [[TMP32:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 0
; CHECK-NEXT:    [[TMP33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M29]], 1
; CHECK-NEXT:    [[VLDH64IP_M30:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP33]], i32 8)
; CHECK-NEXT:    [[TMP34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 0
; CHECK-NEXT:    [[TMP35:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M30]], 1
; CHECK-NEXT:    [[VLDL64IP_M31:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP35]], i32 8)
; CHECK-NEXT:    [[TMP36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 0
; CHECK-NEXT:    [[TMP37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M31]], 1
; CHECK-NEXT:    [[VLDH64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP37]], i32 8)
; CHECK-NEXT:    [[TMP38:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 0
; CHECK-NEXT:    [[TMP39:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M33:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP39]], i32 8)
; CHECK-NEXT:    [[TMP40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 0
; CHECK-NEXT:    [[TMP41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M33]], 1
; CHECK-NEXT:    [[VLDH64IP_M34:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP41]], i32 8)
; CHECK-NEXT:    [[TMP42:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 0
; CHECK-NEXT:    [[TMP43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M34]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP43]], i32 8)
; CHECK-NEXT:    [[TMP44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[TMP45:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[VLDH64IP_M36:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP45]], i32 8)
; CHECK-NEXT:    [[TMP46:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 0
; CHECK-NEXT:    [[TMP47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M36]], 1
; CHECK-NEXT:    [[VLDL64IP_M37:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP47]], i32 8)
; CHECK-NEXT:    [[TMP48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 0
; CHECK-NEXT:    [[TMP49:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M37]], 1
; CHECK-NEXT:    [[VLDH64IP_M38:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP49]], i32 8)
; CHECK-NEXT:    [[TMP50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 0
; CHECK-NEXT:    [[TMP51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M38]], 1
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP51]], i32 8)
; CHECK-NEXT:    [[TMP52:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[TMP53:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDH64IP_M40:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP53]], i32 8)
; CHECK-NEXT:    [[TMP54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 0
; CHECK-NEXT:    [[TMP55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M40]], 1
; CHECK-NEXT:    [[VLDL64IP_M41:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP55]], i32 8)
; CHECK-NEXT:    [[TMP56:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 0
; CHECK-NEXT:    [[TMP57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M41]], 1
; CHECK-NEXT:    [[VLDH64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP57]], i32 8)
; CHECK-NEXT:    [[TMP58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 0
; CHECK-NEXT:    [[TMP59:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M42]], 1
; CHECK-NEXT:    [[VLDL64IP_M43:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP59]], i32 8)
; CHECK-NEXT:    [[TMP60:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M43]], 1
; CHECK-NEXT:    [[VLDH64IP_M44:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP61]], i32 8)
; CHECK-NEXT:    [[TMP62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 0
; CHECK-NEXT:    [[TMP63:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M44]], 1
; CHECK-NEXT:    [[VSTL64IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP32]], ptr [[VSTH64IP_M28]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M46:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP34]], ptr [[VSTL64IP_M45]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M47:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP36]], ptr [[VSTH64IP_M46]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M48:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP38]], ptr [[VSTL64IP_M47]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M49:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP40]], ptr [[VSTH64IP_M48]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M50:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP42]], ptr [[VSTL64IP_M49]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M51:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP44]], ptr [[VSTH64IP_M50]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP46]], ptr [[VSTL64IP_M51]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M53:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP48]], ptr [[VSTH64IP_M52]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M54:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP50]], ptr [[VSTL64IP_M53]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M55:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP52]], ptr [[VSTH64IP_M54]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M56:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP54]], ptr [[VSTL64IP_M55]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M57:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP56]], ptr [[VSTH64IP_M56]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M58:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP58]], ptr [[VSTL64IP_M57]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP60]], ptr [[VSTH64IP_M58]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M60:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP62]], ptr [[VSTL64IP_M59]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M61:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP63]], i32 8)
; CHECK-NEXT:    [[TMP64:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 0
; CHECK-NEXT:    [[TMP65:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M61]], 1
; CHECK-NEXT:    [[VLDH64IP_M62:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP65]], i32 8)
; CHECK-NEXT:    [[TMP66:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 0
; CHECK-NEXT:    [[TMP67:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M62]], 1
; CHECK-NEXT:    [[VLDL64IP_M63:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP67]], i32 8)
; CHECK-NEXT:    [[TMP68:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 0
; CHECK-NEXT:    [[TMP69:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 1
; CHECK-NEXT:    [[VLDH64IP_M64:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP69]], i32 8)
; CHECK-NEXT:    [[TMP70:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M64]], 0
; CHECK-NEXT:    [[TMP71:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M64]], 1
; CHECK-NEXT:    [[VLDL64IP_M65:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP71]], i32 8)
; CHECK-NEXT:    [[TMP72:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M65]], 0
; CHECK-NEXT:    [[TMP73:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M65]], 1
; CHECK-NEXT:    [[VLDH64IP_M66:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP73]], i32 8)
; CHECK-NEXT:    [[TMP74:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M66]], 0
; CHECK-NEXT:    [[TMP75:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M66]], 1
; CHECK-NEXT:    [[VLDL64IP_M67:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP75]], i32 8)
; CHECK-NEXT:    [[TMP76:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 0
; CHECK-NEXT:    [[TMP77:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 1
; CHECK-NEXT:    [[VLDH64IP_M68:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP77]], i32 8)
; CHECK-NEXT:    [[TMP78:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M68]], 0
; CHECK-NEXT:    [[TMP79:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M68]], 1
; CHECK-NEXT:    [[VLDL64IP_M69:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP79]], i32 8)
; CHECK-NEXT:    [[TMP80:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M69]], 0
; CHECK-NEXT:    [[TMP81:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M69]], 1
; CHECK-NEXT:    [[VLDH64IP_M70:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP81]], i32 8)
; CHECK-NEXT:    [[TMP82:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M70]], 0
; CHECK-NEXT:    [[TMP83:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M70]], 1
; CHECK-NEXT:    [[VLDL64IP_M71:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP83]], i32 8)
; CHECK-NEXT:    [[TMP84:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 0
; CHECK-NEXT:    [[TMP85:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M71]], 1
; CHECK-NEXT:    [[VLDH64IP_M72:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP85]], i32 8)
; CHECK-NEXT:    [[TMP86:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 0
; CHECK-NEXT:    [[TMP87:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M72]], 1
; CHECK-NEXT:    [[VLDL64IP_M73:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP87]], i32 8)
; CHECK-NEXT:    [[TMP88:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 0
; CHECK-NEXT:    [[TMP89:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M73]], 1
; CHECK-NEXT:    [[VLDH64IP_M74:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP89]], i32 8)
; CHECK-NEXT:    [[TMP90:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 0
; CHECK-NEXT:    [[TMP91:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M74]], 1
; CHECK-NEXT:    [[VLDL64IP_M75:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP91]], i32 8)
; CHECK-NEXT:    [[TMP92:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 0
; CHECK-NEXT:    [[TMP93:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M75]], 1
; CHECK-NEXT:    [[VLDH64IP_M76:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP93]], i32 8)
; CHECK-NEXT:    [[TMP94:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 0
; CHECK-NEXT:    [[TMP95:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M76]], 1
; CHECK-NEXT:    [[VSTL64IP_M77:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP64]], ptr [[VSTH64IP_M60]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M78:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP66]], ptr [[VSTL64IP_M77]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M79:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP68]], ptr [[VSTH64IP_M78]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP70]], ptr [[VSTL64IP_M79]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M81:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP72]], ptr [[VSTH64IP_M80]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M82:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP74]], ptr [[VSTL64IP_M81]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M83:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP76]], ptr [[VSTH64IP_M82]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M84:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP78]], ptr [[VSTL64IP_M83]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M85:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP80]], ptr [[VSTH64IP_M84]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M86:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP82]], ptr [[VSTL64IP_M85]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M87:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP84]], ptr [[VSTH64IP_M86]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M88:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP86]], ptr [[VSTL64IP_M87]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M89:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP88]], ptr [[VSTH64IP_M88]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M90:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP90]], ptr [[VSTL64IP_M89]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M91:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP92]], ptr [[VSTH64IP_M90]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M92:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP94]], ptr [[VSTL64IP_M91]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M93:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP95]], i32 8)
; CHECK-NEXT:    [[TMP96:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 0
; CHECK-NEXT:    [[TMP97:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M93]], 1
; CHECK-NEXT:    [[VLDH64IP_M94:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP97]], i32 8)
; CHECK-NEXT:    [[TMP98:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 0
; CHECK-NEXT:    [[TMP99:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M94]], 1
; CHECK-NEXT:    [[VLDL64IP_M95:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP99]], i32 8)
; CHECK-NEXT:    [[TMP100:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 0
; CHECK-NEXT:    [[TMP101:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 1
; CHECK-NEXT:    [[VLDH64IP_M96:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP101]], i32 8)
; CHECK-NEXT:    [[TMP102:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 0
; CHECK-NEXT:    [[TMP103:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M96]], 1
; CHECK-NEXT:    [[VLDL64IP_M97:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP103]], i32 8)
; CHECK-NEXT:    [[TMP104:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 0
; CHECK-NEXT:    [[TMP105:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M97]], 1
; CHECK-NEXT:    [[VLDH64IP_M98:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP105]], i32 8)
; CHECK-NEXT:    [[TMP106:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 0
; CHECK-NEXT:    [[TMP107:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M98]], 1
; CHECK-NEXT:    [[VLDL64IP_M99:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP107]], i32 8)
; CHECK-NEXT:    [[TMP108:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M99]], 0
; CHECK-NEXT:    [[TMP109:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M99]], 1
; CHECK-NEXT:    [[VLDH64IP_M100:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP109]], i32 8)
; CHECK-NEXT:    [[TMP110:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M100]], 0
; CHECK-NEXT:    [[TMP111:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M100]], 1
; CHECK-NEXT:    [[VLDL64IP_M101:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP111]], i32 8)
; CHECK-NEXT:    [[TMP112:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M101]], 0
; CHECK-NEXT:    [[TMP113:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M101]], 1
; CHECK-NEXT:    [[VLDH64IP_M102:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP113]], i32 8)
; CHECK-NEXT:    [[TMP114:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M102]], 0
; CHECK-NEXT:    [[TMP115:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M102]], 1
; CHECK-NEXT:    [[VLDL64IP_M103:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP115]], i32 8)
; CHECK-NEXT:    [[TMP116:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M103]], 0
; CHECK-NEXT:    [[TMP117:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M103]], 1
; CHECK-NEXT:    [[VLDH64IP_M104:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP117]], i32 8)
; CHECK-NEXT:    [[TMP118:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M104]], 0
; CHECK-NEXT:    [[TMP119:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M104]], 1
; CHECK-NEXT:    [[VLDL64IP_M105:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP119]], i32 8)
; CHECK-NEXT:    [[TMP120:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 0
; CHECK-NEXT:    [[TMP121:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 1
; CHECK-NEXT:    [[VLDH64IP_M106:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP121]], i32 8)
; CHECK-NEXT:    [[TMP122:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M106]], 0
; CHECK-NEXT:    [[TMP123:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M106]], 1
; CHECK-NEXT:    [[VLDL64IP_M107:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP123]], i32 8)
; CHECK-NEXT:    [[TMP124:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 0
; CHECK-NEXT:    [[TMP125:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M107]], 1
; CHECK-NEXT:    [[VLDH64IP_M108:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP125]], i32 8)
; CHECK-NEXT:    [[TMP126:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 0
; CHECK-NEXT:    [[TMP127:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M108]], 1
; CHECK-NEXT:    [[VSTL64IP_M109:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP96]], ptr [[VSTH64IP_M92]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M110:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP98]], ptr [[VSTL64IP_M109]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M111:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP100]], ptr [[VSTH64IP_M110]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M112:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP102]], ptr [[VSTL64IP_M111]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M113:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP104]], ptr [[VSTH64IP_M112]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M114:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP106]], ptr [[VSTL64IP_M113]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M115:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP108]], ptr [[VSTH64IP_M114]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M116:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP110]], ptr [[VSTL64IP_M115]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M117:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP112]], ptr [[VSTH64IP_M116]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M118:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP114]], ptr [[VSTL64IP_M117]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M119:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP116]], ptr [[VSTH64IP_M118]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M120:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP118]], ptr [[VSTL64IP_M119]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M121:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP120]], ptr [[VSTH64IP_M120]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M122:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP122]], ptr [[VSTL64IP_M121]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M123:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP124]], ptr [[VSTH64IP_M122]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M124:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP126]], ptr [[VSTL64IP_M123]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M125:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP127]], i32 8)
; CHECK-NEXT:    [[TMP128:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M125]], 0
; CHECK-NEXT:    [[TMP129:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M125]], 1
; CHECK-NEXT:    [[VLDH64IP_M126:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP129]], i32 8)
; CHECK-NEXT:    [[TMP130:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M126]], 0
; CHECK-NEXT:    [[TMP131:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M126]], 1
; CHECK-NEXT:    [[VLDL64IP_M127:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP131]], i32 8)
; CHECK-NEXT:    [[TMP132:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M127]], 0
; CHECK-NEXT:    [[TMP133:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M127]], 1
; CHECK-NEXT:    [[VLDH64IP_M128:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP133]], i32 8)
; CHECK-NEXT:    [[TMP134:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M128]], 0
; CHECK-NEXT:    [[TMP135:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M128]], 1
; CHECK-NEXT:    [[VLDL64IP_M129:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP135]], i32 8)
; CHECK-NEXT:    [[TMP136:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M129]], 0
; CHECK-NEXT:    [[TMP137:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M129]], 1
; CHECK-NEXT:    [[VLDH64IP_M130:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP137]], i32 8)
; CHECK-NEXT:    [[TMP138:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M130]], 0
; CHECK-NEXT:    [[TMP139:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M130]], 1
; CHECK-NEXT:    [[VLDL64IP_M131:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP139]], i32 8)
; CHECK-NEXT:    [[TMP140:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 0
; CHECK-NEXT:    [[TMP141:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M131]], 1
; CHECK-NEXT:    [[VLDH64IP_M132:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP141]], i32 8)
; CHECK-NEXT:    [[TMP142:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 0
; CHECK-NEXT:    [[TMP143:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M132]], 1
; CHECK-NEXT:    [[VLDL64IP_M133:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP143]], i32 8)
; CHECK-NEXT:    [[TMP144:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 0
; CHECK-NEXT:    [[TMP145:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M133]], 1
; CHECK-NEXT:    [[VLDH64IP_M134:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP145]], i32 8)
; CHECK-NEXT:    [[TMP146:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 0
; CHECK-NEXT:    [[TMP147:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M134]], 1
; CHECK-NEXT:    [[VLDL64IP_M135:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP147]], i32 8)
; CHECK-NEXT:    [[TMP148:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 0
; CHECK-NEXT:    [[TMP149:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M135]], 1
; CHECK-NEXT:    [[VLDH64IP_M136:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP149]], i32 8)
; CHECK-NEXT:    [[TMP150:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 0
; CHECK-NEXT:    [[TMP151:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M136]], 1
; CHECK-NEXT:    [[VLDL64IP_M137:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP151]], i32 8)
; CHECK-NEXT:    [[TMP152:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M137]], 0
; CHECK-NEXT:    [[TMP153:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M137]], 1
; CHECK-NEXT:    [[VLDH64IP_M138:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP153]], i32 8)
; CHECK-NEXT:    [[TMP154:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M138]], 0
; CHECK-NEXT:    [[TMP155:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M138]], 1
; CHECK-NEXT:    [[VLDL64IP_M139:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP155]], i32 8)
; CHECK-NEXT:    [[TMP156:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M139]], 0
; CHECK-NEXT:    [[TMP157:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M139]], 1
; CHECK-NEXT:    [[VLDH64IP_M140:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP157]], i32 8)
; CHECK-NEXT:    [[TMP158:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M140]], 0
; CHECK-NEXT:    [[TMP159:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M140]], 1
; CHECK-NEXT:    [[VSTL64IP_M141:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP128]], ptr [[VSTH64IP_M124]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M142:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP130]], ptr [[VSTL64IP_M141]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M143:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP132]], ptr [[VSTH64IP_M142]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M144:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP134]], ptr [[VSTL64IP_M143]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M145:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP136]], ptr [[VSTH64IP_M144]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M146:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP138]], ptr [[VSTL64IP_M145]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M147:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP140]], ptr [[VSTH64IP_M146]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M148:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP142]], ptr [[VSTL64IP_M147]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M149:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP144]], ptr [[VSTH64IP_M148]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M150:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP146]], ptr [[VSTL64IP_M149]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M151:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP148]], ptr [[VSTH64IP_M150]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M152:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP150]], ptr [[VSTL64IP_M151]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M153:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP152]], ptr [[VSTH64IP_M152]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M154:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP154]], ptr [[VSTL64IP_M153]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M155:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP156]], ptr [[VSTH64IP_M154]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M156:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP158]], ptr [[VSTL64IP_M155]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M157:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP159]], i32 8)
; CHECK-NEXT:    [[TMP160:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M157]], 0
; CHECK-NEXT:    [[TMP161:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M157]], 1
; CHECK-NEXT:    [[VLDH64IP_M158:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP161]], i32 8)
; CHECK-NEXT:    [[TMP162:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M158]], 0
; CHECK-NEXT:    [[TMP163:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M158]], 1
; CHECK-NEXT:    [[VLDL64IP_M159:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP163]], i32 8)
; CHECK-NEXT:    [[TMP164:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M159]], 0
; CHECK-NEXT:    [[TMP165:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M159]], 1
; CHECK-NEXT:    [[VLDH64IP_M160:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP165]], i32 8)
; CHECK-NEXT:    [[TMP166:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M160]], 0
; CHECK-NEXT:    [[TMP167:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M160]], 1
; CHECK-NEXT:    [[VLDL64IP_M161:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP167]], i32 8)
; CHECK-NEXT:    [[TMP168:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M161]], 0
; CHECK-NEXT:    [[TMP169:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M161]], 1
; CHECK-NEXT:    [[VLDH64IP_M162:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP169]], i32 8)
; CHECK-NEXT:    [[TMP170:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M162]], 0
; CHECK-NEXT:    [[TMP171:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M162]], 1
; CHECK-NEXT:    [[VLDL64IP_M163:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP171]], i32 8)
; CHECK-NEXT:    [[TMP172:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M163]], 0
; CHECK-NEXT:    [[TMP173:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M163]], 1
; CHECK-NEXT:    [[VLDH64IP_M164:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP173]], i32 8)
; CHECK-NEXT:    [[TMP174:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M164]], 0
; CHECK-NEXT:    [[TMP175:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M164]], 1
; CHECK-NEXT:    [[VLDL64IP_M165:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP175]], i32 8)
; CHECK-NEXT:    [[TMP176:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M165]], 0
; CHECK-NEXT:    [[TMP177:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M165]], 1
; CHECK-NEXT:    [[VLDH64IP_M166:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP177]], i32 8)
; CHECK-NEXT:    [[TMP178:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M166]], 0
; CHECK-NEXT:    [[TMP179:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M166]], 1
; CHECK-NEXT:    [[VLDL64IP_M167:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP179]], i32 8)
; CHECK-NEXT:    [[TMP180:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M167]], 0
; CHECK-NEXT:    [[TMP181:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M167]], 1
; CHECK-NEXT:    [[VLDH64IP_M168:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP181]], i32 8)
; CHECK-NEXT:    [[TMP182:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M168]], 0
; CHECK-NEXT:    [[TMP183:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M168]], 1
; CHECK-NEXT:    [[VLDL64IP_M169:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP183]], i32 8)
; CHECK-NEXT:    [[TMP184:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M169]], 0
; CHECK-NEXT:    [[TMP185:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M169]], 1
; CHECK-NEXT:    [[VLDH64IP_M170:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP185]], i32 8)
; CHECK-NEXT:    [[TMP186:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M170]], 0
; CHECK-NEXT:    [[TMP187:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M170]], 1
; CHECK-NEXT:    [[VLDL64IP_M171:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP187]], i32 8)
; CHECK-NEXT:    [[TMP188:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M171]], 0
; CHECK-NEXT:    [[TMP189:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M171]], 1
; CHECK-NEXT:    [[VLDH64IP_M172:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP189]], i32 8)
; CHECK-NEXT:    [[TMP190:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M172]], 0
; CHECK-NEXT:    [[TMP191:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M172]], 1
; CHECK-NEXT:    [[VSTL64IP_M173:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP160]], ptr [[VSTH64IP_M156]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M174:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP162]], ptr [[VSTL64IP_M173]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M175:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP164]], ptr [[VSTH64IP_M174]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M176:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP166]], ptr [[VSTL64IP_M175]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M177:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP168]], ptr [[VSTH64IP_M176]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M178:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP170]], ptr [[VSTL64IP_M177]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M179:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP172]], ptr [[VSTH64IP_M178]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M180:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP174]], ptr [[VSTL64IP_M179]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M181:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP176]], ptr [[VSTH64IP_M180]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M182:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP178]], ptr [[VSTL64IP_M181]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M183:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP180]], ptr [[VSTH64IP_M182]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M184:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP182]], ptr [[VSTL64IP_M183]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M185:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP184]], ptr [[VSTH64IP_M184]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M186:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP186]], ptr [[VSTL64IP_M185]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M187:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP188]], ptr [[VSTH64IP_M186]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M188:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP190]], ptr [[VSTL64IP_M187]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M189:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP191]], i32 8)
; CHECK-NEXT:    [[TMP192:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M189]], 0
; CHECK-NEXT:    [[TMP193:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M189]], 1
; CHECK-NEXT:    [[VLDH64IP_M190:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP193]], i32 8)
; CHECK-NEXT:    [[TMP194:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M190]], 0
; CHECK-NEXT:    [[TMP195:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M190]], 1
; CHECK-NEXT:    [[VLDL64IP_M191:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP195]], i32 8)
; CHECK-NEXT:    [[TMP196:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M191]], 0
; CHECK-NEXT:    [[TMP197:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M191]], 1
; CHECK-NEXT:    [[VLDH64IP_M192:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP197]], i32 8)
; CHECK-NEXT:    [[TMP198:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M192]], 0
; CHECK-NEXT:    [[TMP199:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M192]], 1
; CHECK-NEXT:    [[VLDL64IP_M193:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP199]], i32 8)
; CHECK-NEXT:    [[TMP200:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M193]], 0
; CHECK-NEXT:    [[TMP201:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M193]], 1
; CHECK-NEXT:    [[VLDH64IP_M194:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP201]], i32 8)
; CHECK-NEXT:    [[TMP202:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M194]], 0
; CHECK-NEXT:    [[TMP203:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M194]], 1
; CHECK-NEXT:    [[VLDL64IP_M195:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP203]], i32 8)
; CHECK-NEXT:    [[TMP204:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M195]], 0
; CHECK-NEXT:    [[TMP205:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M195]], 1
; CHECK-NEXT:    [[VLDH64IP_M196:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP205]], i32 8)
; CHECK-NEXT:    [[TMP206:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M196]], 0
; CHECK-NEXT:    [[TMP207:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M196]], 1
; CHECK-NEXT:    [[VLDL64IP_M197:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP207]], i32 8)
; CHECK-NEXT:    [[TMP208:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M197]], 0
; CHECK-NEXT:    [[TMP209:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M197]], 1
; CHECK-NEXT:    [[VLDH64IP_M198:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP209]], i32 8)
; CHECK-NEXT:    [[TMP210:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M198]], 0
; CHECK-NEXT:    [[TMP211:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M198]], 1
; CHECK-NEXT:    [[VLDL64IP_M199:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP211]], i32 8)
; CHECK-NEXT:    [[TMP212:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M199]], 0
; CHECK-NEXT:    [[TMP213:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M199]], 1
; CHECK-NEXT:    [[VLDH64IP_M200:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP213]], i32 8)
; CHECK-NEXT:    [[TMP214:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M200]], 0
; CHECK-NEXT:    [[TMP215:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M200]], 1
; CHECK-NEXT:    [[VLDL64IP_M201:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP215]], i32 8)
; CHECK-NEXT:    [[TMP216:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M201]], 0
; CHECK-NEXT:    [[TMP217:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M201]], 1
; CHECK-NEXT:    [[VLDH64IP_M202:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP217]], i32 8)
; CHECK-NEXT:    [[TMP218:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M202]], 0
; CHECK-NEXT:    [[TMP219:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M202]], 1
; CHECK-NEXT:    [[VLDL64IP_M203:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP219]], i32 8)
; CHECK-NEXT:    [[TMP220:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M203]], 0
; CHECK-NEXT:    [[TMP221:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M203]], 1
; CHECK-NEXT:    [[VLDH64IP_M204:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP221]], i32 8)
; CHECK-NEXT:    [[TMP222:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M204]], 0
; CHECK-NEXT:    [[TMP223:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M204]], 1
; CHECK-NEXT:    [[VSTL64IP_M205:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP192]], ptr [[VSTH64IP_M188]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M206:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP194]], ptr [[VSTL64IP_M205]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M207:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP196]], ptr [[VSTH64IP_M206]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M208:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP198]], ptr [[VSTL64IP_M207]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M209:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP200]], ptr [[VSTH64IP_M208]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M210:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP202]], ptr [[VSTL64IP_M209]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M211:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP204]], ptr [[VSTH64IP_M210]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M212:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP206]], ptr [[VSTL64IP_M211]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M213:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP208]], ptr [[VSTH64IP_M212]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M214:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP210]], ptr [[VSTL64IP_M213]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M215:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP212]], ptr [[VSTH64IP_M214]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M216:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP214]], ptr [[VSTL64IP_M215]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M217:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP216]], ptr [[VSTH64IP_M216]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M218:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP218]], ptr [[VSTL64IP_M217]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M219:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP220]], ptr [[VSTH64IP_M218]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M220:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP222]], ptr [[VSTL64IP_M219]], i32 8)
; CHECK-NEXT:    [[VLDL64IP_M221:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP223]], i32 8)
; CHECK-NEXT:    [[TMP224:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M221]], 0
; CHECK-NEXT:    [[TMP225:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M221]], 1
; CHECK-NEXT:    [[VLDH64IP_M222:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP225]], i32 8)
; CHECK-NEXT:    [[TMP226:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M222]], 0
; CHECK-NEXT:    [[TMP227:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M222]], 1
; CHECK-NEXT:    [[VLDL64IP_M223:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP227]], i32 8)
; CHECK-NEXT:    [[TMP228:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M223]], 0
; CHECK-NEXT:    [[TMP229:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M223]], 1
; CHECK-NEXT:    [[VLDH64IP_M224:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP229]], i32 8)
; CHECK-NEXT:    [[TMP230:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M224]], 0
; CHECK-NEXT:    [[TMP231:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M224]], 1
; CHECK-NEXT:    [[VLDL64IP_M225:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP231]], i32 8)
; CHECK-NEXT:    [[TMP232:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M225]], 0
; CHECK-NEXT:    [[TMP233:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M225]], 1
; CHECK-NEXT:    [[VLDH64IP_M226:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP233]], i32 8)
; CHECK-NEXT:    [[TMP234:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M226]], 0
; CHECK-NEXT:    [[TMP235:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M226]], 1
; CHECK-NEXT:    [[VLDL64IP_M227:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP235]], i32 8)
; CHECK-NEXT:    [[TMP236:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M227]], 0
; CHECK-NEXT:    [[TMP237:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M227]], 1
; CHECK-NEXT:    [[VLDH64IP_M228:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP237]], i32 8)
; CHECK-NEXT:    [[TMP238:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M228]], 0
; CHECK-NEXT:    [[TMP239:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M228]], 1
; CHECK-NEXT:    [[VLDL64IP_M229:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP239]], i32 8)
; CHECK-NEXT:    [[TMP240:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M229]], 0
; CHECK-NEXT:    [[TMP241:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M229]], 1
; CHECK-NEXT:    [[VLDH64IP_M230:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP241]], i32 8)
; CHECK-NEXT:    [[TMP242:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M230]], 0
; CHECK-NEXT:    [[TMP243:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M230]], 1
; CHECK-NEXT:    [[VLDL64IP_M231:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP243]], i32 8)
; CHECK-NEXT:    [[TMP244:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M231]], 0
; CHECK-NEXT:    [[TMP245:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M231]], 1
; CHECK-NEXT:    [[VLDH64IP_M232:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP245]], i32 8)
; CHECK-NEXT:    [[TMP246:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M232]], 0
; CHECK-NEXT:    [[TMP247:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M232]], 1
; CHECK-NEXT:    [[VLDL64IP_M233:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP247]], i32 8)
; CHECK-NEXT:    [[TMP248:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M233]], 0
; CHECK-NEXT:    [[TMP249:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M233]], 1
; CHECK-NEXT:    [[VLDH64IP_M234:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP249]], i32 8)
; CHECK-NEXT:    [[TMP250:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M234]], 0
; CHECK-NEXT:    [[TMP251:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M234]], 1
; CHECK-NEXT:    [[VLDL64IP_M235:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr [[TMP251]], i32 8)
; CHECK-NEXT:    [[TMP252:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M235]], 0
; CHECK-NEXT:    [[TMP253:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M235]], 1
; CHECK-NEXT:    [[VLDH64IP_M236:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.h.64.ip(ptr [[TMP253]], i32 8)
; CHECK-NEXT:    [[TMP254:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDH64IP_M236]], 0
; CHECK-NEXT:    [[VSTL64IP_M237:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP224]], ptr [[VSTH64IP_M220]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M238:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP226]], ptr [[VSTL64IP_M237]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M239:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP228]], ptr [[VSTH64IP_M238]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M240:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP230]], ptr [[VSTL64IP_M239]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M241:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP232]], ptr [[VSTH64IP_M240]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M242:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP234]], ptr [[VSTL64IP_M241]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M243:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP236]], ptr [[VSTH64IP_M242]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M244:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP238]], ptr [[VSTL64IP_M243]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M245:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP240]], ptr [[VSTH64IP_M244]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M246:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP242]], ptr [[VSTL64IP_M245]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M247:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP244]], ptr [[VSTH64IP_M246]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M248:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP246]], ptr [[VSTL64IP_M247]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M249:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP248]], ptr [[VSTH64IP_M248]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M250:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP250]], ptr [[VSTL64IP_M249]], i32 8)
; CHECK-NEXT:    [[VSTL64IP_M251:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP252]], ptr [[VSTH64IP_M250]], i32 8)
; CHECK-NEXT:    [[VSTH64IP_M252:%.*]] = call ptr @llvm.riscv.esp.vst.h.64.ip(<8 x i8> [[TMP254]], ptr [[VSTL64IP_M251]], i32 8)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(1024) %a, ptr noundef nonnull align 8 dereferenceable(1024) %b, i32 1024, i1 false)
  ret void
}

define void @test_src8_dst8_size_20000(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dst8_size_20000(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrc8Dst8Const16(ptr [[A]], ptr [[B]], i32 20000)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(20000) %a, ptr noundef nonnull align 8 dereferenceable(20000) %b, i32 20000, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_1(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1) %a, ptr noundef nonnull align 16 dereferenceable(1) %b, i32 1, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_2(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_2(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(2) %a, ptr noundef nonnull align 16 dereferenceable(2) %b, i32 2, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_3(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_3(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(3) %a, ptr noundef nonnull align 16 dereferenceable(3) %b, i32 3, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_4(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_4(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(4) %a, ptr noundef nonnull align 16 dereferenceable(4) %b, i32 4, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_5(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_5(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(5) %a, ptr noundef nonnull align 16 dereferenceable(5) %b, i32 5, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_6(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_6(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(6) %a, ptr noundef nonnull align 16 dereferenceable(6) %b, i32 6, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_7(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_7(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(7) %a, ptr noundef nonnull align 16 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_8(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_8(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 8, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(8) %a, ptr noundef nonnull align 16 dereferenceable(8) %b, i32 8, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_9(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_9(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(9) %a, ptr noundef nonnull align 16 dereferenceable(9) %b, i32 9, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_10(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_10(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(10) %a, ptr noundef nonnull align 16 dereferenceable(10) %b, i32 10, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_11(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_11(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 10
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 10
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(11) %a, ptr noundef nonnull align 16 dereferenceable(11) %b, i32 11, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_12(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_12(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(12) %a, ptr noundef nonnull align 16 dereferenceable(12) %b, i32 12, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_13(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_13(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(13) %a, ptr noundef nonnull align 16 dereferenceable(13) %b, i32 13, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_14(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_14(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    store i16 [[TMP6]], ptr [[TMP5]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(14) %a, ptr noundef nonnull align 16 dereferenceable(14) %b, i32 14, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_15(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_15(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    store i16 [[TMP6]], ptr [[TMP5]], align 2
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 14
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 14
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[TMP8]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(15) %a, ptr noundef nonnull align 16 dereferenceable(15) %b, i32 15, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_16(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 16, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(16) %a, ptr noundef nonnull align 16 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_17(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_17(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 17, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(17) %a, ptr noundef nonnull align 16 dereferenceable(17) %b, i32 17, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_31(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_31(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 31, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(31) %a, ptr noundef nonnull align 16 dereferenceable(31) %b, i32 31, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_32(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_32(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 32, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(32) %a, ptr noundef nonnull align 16 dereferenceable(32) %b, i32 32, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_33(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_33(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 33, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(33) %a, ptr noundef nonnull align 16 dereferenceable(33) %b, i32 33, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_47(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 47, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(47) %a, ptr noundef nonnull align 16 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_48(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 48, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(48) %a, ptr noundef nonnull align 16 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_49(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_49(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 49, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(49) %a, ptr noundef nonnull align 16 dereferenceable(49) %b, i32 49, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_63(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_63(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 63, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(63) %a, ptr noundef nonnull align 16 dereferenceable(63) %b, i32 63, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_64(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_64(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 64, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(64) %a, ptr noundef nonnull align 16 dereferenceable(64) %b, i32 64, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_65(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_65(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 65, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(65) %a, ptr noundef nonnull align 16 dereferenceable(65) %b, i32 65, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_80(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_80(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 80, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(80) %a, ptr noundef nonnull align 16 dereferenceable(80) %b, i32 80, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_81(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_81(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 81, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(81) %a, ptr noundef nonnull align 16 dereferenceable(81) %b, i32 81, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_88(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_88(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 88, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(88) %a, ptr noundef nonnull align 16 dereferenceable(88) %b, i32 88, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_96(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_96(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 96, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(96) %a, ptr noundef nonnull align 16 dereferenceable(96) %b, i32 96, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_112(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_112(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 112, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(112) %a, ptr noundef nonnull align 16 dereferenceable(112) %b, i32 112, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_124(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_124(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 124, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(124) %a, ptr noundef nonnull align 16 dereferenceable(124) %b, i32 124, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_127(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_127(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 127, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(127) %a, ptr noundef nonnull align 16 dereferenceable(127) %b, i32 127, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_128(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 128, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(128) %a, ptr noundef nonnull align 16 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_129(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_129(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 129, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(129) %a, ptr noundef nonnull align 16 dereferenceable(129) %b, i32 129, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_255(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_255(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 255, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(255) %a, ptr noundef nonnull align 16 dereferenceable(255) %b, i32 255, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_256(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 256, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(256) %a, ptr noundef nonnull align 16 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_1023(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_1023(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 1023, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1023) %a, ptr noundef nonnull align 16 dereferenceable(1023) %b, i32 1023, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_1024(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_1024(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 1024, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1024) %a, ptr noundef nonnull align 16 dereferenceable(1024) %b, i32 1024, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_1(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1) %a, ptr noundef nonnull align 8 dereferenceable(1) %b, i32 1, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_2(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_2(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(2) %a, ptr noundef nonnull align 8 dereferenceable(2) %b, i32 2, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_3(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_3(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(3) %a, ptr noundef nonnull align 8 dereferenceable(3) %b, i32 3, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_4(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_4(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(4) %a, ptr noundef nonnull align 8 dereferenceable(4) %b, i32 4, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_5(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_5(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(5) %a, ptr noundef nonnull align 8 dereferenceable(5) %b, i32 5, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_6(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_6(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(6) %a, ptr noundef nonnull align 8 dereferenceable(6) %b, i32 6, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_7(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_7(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(7) %a, ptr noundef nonnull align 8 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_8(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_8(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 8, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(8) %a, ptr noundef nonnull align 8 dereferenceable(8) %b, i32 8, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_9(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_9(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(9) %a, ptr noundef nonnull align 8 dereferenceable(9) %b, i32 9, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_10(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_10(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(10) %a, ptr noundef nonnull align 8 dereferenceable(10) %b, i32 10, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_11(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_11(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 10
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 10
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(11) %a, ptr noundef nonnull align 8 dereferenceable(11) %b, i32 11, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_12(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_12(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(12) %a, ptr noundef nonnull align 8 dereferenceable(12) %b, i32 12, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_13(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_13(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(13) %a, ptr noundef nonnull align 8 dereferenceable(13) %b, i32 13, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_14(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_14(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    store i16 [[TMP6]], ptr [[TMP5]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(14) %a, ptr noundef nonnull align 8 dereferenceable(14) %b, i32 14, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_15(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_15(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    store i16 [[TMP6]], ptr [[TMP5]], align 2
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 14
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 14
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[TMP8]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(15) %a, ptr noundef nonnull align 8 dereferenceable(15) %b, i32 15, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_16(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 16, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(16) %a, ptr noundef nonnull align 8 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_17(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_17(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 17, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(17) %a, ptr noundef nonnull align 8 dereferenceable(17) %b, i32 17, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_31(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_31(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 31, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(31) %a, ptr noundef nonnull align 8 dereferenceable(31) %b, i32 31, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_32(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_32(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 32, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(32) %a, ptr noundef nonnull align 8 dereferenceable(32) %b, i32 32, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_33(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_33(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 33, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(33) %a, ptr noundef nonnull align 8 dereferenceable(33) %b, i32 33, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_47(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 47, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(47) %a, ptr noundef nonnull align 8 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_48(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 48, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(48) %a, ptr noundef nonnull align 8 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_49(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_49(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 49, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(49) %a, ptr noundef nonnull align 8 dereferenceable(49) %b, i32 49, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_63(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_63(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 63, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(63) %a, ptr noundef nonnull align 8 dereferenceable(63) %b, i32 63, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_64(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_64(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 64, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(64) %a, ptr noundef nonnull align 8 dereferenceable(64) %b, i32 64, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_65(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_65(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 65, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(65) %a, ptr noundef nonnull align 8 dereferenceable(65) %b, i32 65, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_80(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_80(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 80, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(80) %a, ptr noundef nonnull align 8 dereferenceable(80) %b, i32 80, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_81(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_81(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 81, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(81) %a, ptr noundef nonnull align 8 dereferenceable(81) %b, i32 81, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_88(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_88(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 88, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(88) %a, ptr noundef nonnull align 8 dereferenceable(88) %b, i32 88, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_96(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_96(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 96, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(96) %a, ptr noundef nonnull align 8 dereferenceable(96) %b, i32 96, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_112(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_112(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 112, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(112) %a, ptr noundef nonnull align 8 dereferenceable(112) %b, i32 112, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_124(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_124(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 124, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(124) %a, ptr noundef nonnull align 8 dereferenceable(124) %b, i32 124, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_127(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_127(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 127, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(127) %a, ptr noundef nonnull align 8 dereferenceable(127) %b, i32 127, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_128(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 128, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(128) %a, ptr noundef nonnull align 8 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_129(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_129(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 129, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(129) %a, ptr noundef nonnull align 8 dereferenceable(129) %b, i32 129, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_255(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_255(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 255, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(255) %a, ptr noundef nonnull align 8 dereferenceable(255) %b, i32 255, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_256(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 256, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(256) %a, ptr noundef nonnull align 8 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_1023(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_1023(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 1023, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1023) %a, ptr noundef nonnull align 8 dereferenceable(1023) %b, i32 1023, i1 false)
  ret void
}

define void @test_src8_dstunalign_constant_size_1024(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_src8_dstunalign_constant_size_1024(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrc16DstunalignVar(ptr [[A]], ptr [[B]], i32 1024, i32 1)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1024) %a, ptr noundef nonnull align 8 dereferenceable(1024) %b, i32 1024, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(7) %a, ptr noundef nonnull align 1 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_15(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_15(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    store i16 [[TMP6]], ptr [[TMP5]], align 2
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 14
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 14
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[TMP8]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(15) %a, ptr noundef nonnull align 1 dereferenceable(15) %b, i32 15, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_16(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From16to31Index0(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(16) %a, ptr noundef nonnull align 1 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_17(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_17(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From16to31Index1(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP0]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[TMP1]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(17) %a, ptr noundef nonnull align 1 dereferenceable(17) %b, i32 17, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_31(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_31(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From16to31Index2(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 24
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 24
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP3]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[B]], i32 28
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[A]], i32 28
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[TMP6]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[TMP7]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[B]], i32 30
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[A]], i32 30
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP9]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[TMP10]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(31) %a, ptr noundef nonnull align 1 dereferenceable(31) %b, i32 31, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_32(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_32(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From32To47(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(32) %a, ptr noundef nonnull align 1 dereferenceable(32) %b, i32 32, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_33(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_33(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From32To47(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP0]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[TMP1]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(33) %a, ptr noundef nonnull align 1 dereferenceable(33) %b, i32 33, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_47(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From32To47(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 40
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 40
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP3]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[B]], i32 44
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[A]], i32 44
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[TMP6]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[TMP7]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[B]], i32 46
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[A]], i32 46
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP9]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[TMP10]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(47) %a, ptr noundef nonnull align 1 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_48(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index0(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(48) %a, ptr noundef nonnull align 1 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_49(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_49(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index1(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP0]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[TMP1]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(49) %a, ptr noundef nonnull align 1 dereferenceable(49) %b, i32 49, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_63(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_63(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index2(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 56
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 56
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP3]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[B]], i32 60
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[A]], i32 60
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[TMP6]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[TMP7]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[B]], i32 62
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[A]], i32 62
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP9]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[TMP10]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(63) %a, ptr noundef nonnull align 1 dereferenceable(63) %b, i32 63, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_64(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_64(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.0(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(64) %a, ptr noundef nonnull align 1 dereferenceable(64) %b, i32 64, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_65(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_65(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.1(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 64
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 64
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP0]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[TMP1]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(65) %a, ptr noundef nonnull align 1 dereferenceable(65) %b, i32 65, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_80(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_80(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From32To47Index0(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(80) %a, ptr noundef nonnull align 1 dereferenceable(80) %b, i32 80, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_81(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_81(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From32To47Index1(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 80
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 80
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP0]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[TMP1]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(81) %a, ptr noundef nonnull align 1 dereferenceable(81) %b, i32 81, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_88(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_88(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From32To47Index2(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 80
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 80
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TMP0]], align 1
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP1]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(88) %a, ptr noundef nonnull align 1 dereferenceable(88) %b, i32 88, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_96(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_96(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index3(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(96) %a, ptr noundef nonnull align 1 dereferenceable(96) %b, i32 96, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_112(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_112(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.2(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(112) %a, ptr noundef nonnull align 1 dereferenceable(112) %b, i32 112, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_124(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_124(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.3(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 120
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 120
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP3]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[TMP4]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(124) %a, ptr noundef nonnull align 1 dereferenceable(124) %b, i32 124, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_127(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_127(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.4(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 120
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 120
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP3]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[B]], i32 124
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[A]], i32 124
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[TMP6]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[TMP7]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[B]], i32 126
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[A]], i32 126
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP9]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[TMP10]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(127) %a, ptr noundef nonnull align 1 dereferenceable(127) %b, i32 127, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_128(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From32To47Index3(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(128) %a, ptr noundef nonnull align 1 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_129(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_129(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From32To47Index4(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 128
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 128
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[TMP0]], align 1
; CHECK-NEXT:    store i8 [[TMP2]], ptr [[TMP1]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(129) %a, ptr noundef nonnull align 1 dereferenceable(129) %b, i32 129, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_255(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_255(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index4(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 240
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 240
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 248
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 248
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP3]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[B]], i32 252
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[A]], i32 252
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[TMP6]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[TMP7]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[B]], i32 254
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[A]], i32 254
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP9]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[TMP10]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(255) %a, ptr noundef nonnull align 1 dereferenceable(255) %b, i32 255, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_256(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.5(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(256) %a, ptr noundef nonnull align 1 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_1023(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_1023(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index5(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[B]], i32 1008
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[A]], i32 1008
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[TMP0]], align 8
; CHECK-NEXT:    store i64 [[TMP2]], ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[B]], i32 1016
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[A]], i32 1016
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP3]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[B]], i32 1020
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[A]], i32 1020
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[TMP6]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[TMP7]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[B]], i32 1022
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[A]], i32 1022
; CHECK-NEXT:    [[TMP11:%.*]] = load i8, ptr [[TMP9]], align 1
; CHECK-NEXT:    store i8 [[TMP11]], ptr [[TMP10]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(1023) %a, ptr noundef nonnull align 1 dereferenceable(1023) %b, i32 1023, i1 false)
  ret void
}

define void @test_srcunalign_dst16_constant_size_1024(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst16_constant_size_1024(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.6(ptr [[A]], ptr [[B]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(1024) %a, ptr noundef nonnull align 1 dereferenceable(1024) %b, i32 1024, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_1(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(1) %a, ptr noundef nonnull align 1 dereferenceable(1) %b, i32 1, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_2(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_2(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(2) %a, ptr noundef nonnull align 1 dereferenceable(2) %b, i32 2, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_3(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_3(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(3) %a, ptr noundef nonnull align 1 dereferenceable(3) %b, i32 3, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_4(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_4(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(4) %a, ptr noundef nonnull align 1 dereferenceable(4) %b, i32 4, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_5(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_5(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(5) %a, ptr noundef nonnull align 1 dereferenceable(5) %b, i32 5, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_6(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_6(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(6) %a, ptr noundef nonnull align 1 dereferenceable(6) %b, i32 6, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_7(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_7(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(7) %a, ptr noundef nonnull align 1 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_8(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_8(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(8) [[A]], ptr noundef nonnull align 1 dereferenceable(8) [[B]], i32 8, i1 false)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(8) %a, ptr noundef nonnull align 1 dereferenceable(8) %b, i32 8, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_9(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_9(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(9) %a, ptr noundef nonnull align 1 dereferenceable(9) %b, i32 9, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_10(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_10(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(10) %a, ptr noundef nonnull align 1 dereferenceable(10) %b, i32 10, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_11(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_11(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 10
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 10
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(11) %a, ptr noundef nonnull align 1 dereferenceable(11) %b, i32 11, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_12(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_12(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(12) %a, ptr noundef nonnull align 1 dereferenceable(12) %b, i32 12, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_13(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_13(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(13) %a, ptr noundef nonnull align 1 dereferenceable(13) %b, i32 13, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_14(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_14(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    store i16 [[TMP6]], ptr [[TMP5]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(14) %a, ptr noundef nonnull align 1 dereferenceable(14) %b, i32 14, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_15(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_15(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    store i16 [[TMP6]], ptr [[TMP5]], align 2
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 14
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 14
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[TMP8]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(15) %a, ptr noundef nonnull align 1 dereferenceable(15) %b, i32 15, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_16(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[SRC_OFFSET_BY_8BYTES_I]], align 1
; CHECK-NEXT:    store i64 [[TMP1]], ptr [[DST_OFFSET_BY_8BYTES_I]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(16) %a, ptr noundef nonnull align 1 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_17(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_17(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[SRC_OFFSET_BY_8BYTES_I]], align 1
; CHECK-NEXT:    store i64 [[TMP1]], ptr [[DST_OFFSET_BY_8BYTES_I]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[TMP2]], align 1
; CHECK-NEXT:    store i8 [[TMP4]], ptr [[TMP3]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(17) %a, ptr noundef nonnull align 1 dereferenceable(17) %b, i32 17, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_31(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_31(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[SRC_OFFSET_BY_8BYTES_I]], align 1
; CHECK-NEXT:    store i64 [[TMP1]], ptr [[DST_OFFSET_BY_8BYTES_I]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[B]], i32 16
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr [[A]], i32 16
; CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr [[TMP2]], align 8
; CHECK-NEXT:    store i64 [[TMP4]], ptr [[TMP3]], align 8
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[B]], i32 24
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[A]], i32 24
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[TMP5]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[TMP6]], align 4
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[B]], i32 28
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i8, ptr [[A]], i32 28
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[TMP8]], align 2
; CHECK-NEXT:    store i16 [[TMP10]], ptr [[TMP9]], align 2
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[B]], i32 30
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i8, ptr [[A]], i32 30
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[TMP11]], align 1
; CHECK-NEXT:    store i8 [[TMP13]], ptr [[TMP12]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(31) %a, ptr noundef nonnull align 1 dereferenceable(31) %b, i32 31, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_32(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_32(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From16to31Index3(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 24
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 24
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(32) %a, ptr noundef nonnull align 1 dereferenceable(32) %b, i32 32, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_33(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_33(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From16to31Index4(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 24
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 24
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(33) %a, ptr noundef nonnull align 1 dereferenceable(33) %b, i32 33, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_47(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From16to31Index5(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 24
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 24
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 32
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 32
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr [[TMP4]], align 8
; CHECK-NEXT:    store i64 [[TMP6]], ptr [[TMP5]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 40
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 40
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[TMP8]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[B]], i32 44
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[A]], i32 44
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[TMP10]], align 2
; CHECK-NEXT:    store i16 [[TMP12]], ptr [[TMP11]], align 2
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[B]], i32 46
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[A]], i32 46
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[TMP13]], align 1
; CHECK-NEXT:    store i8 [[TMP15]], ptr [[TMP14]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(47) %a, ptr noundef nonnull align 1 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_48(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From32To47(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 40
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 40
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(48) %a, ptr noundef nonnull align 1 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_49(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_49(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From32To47(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 40
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 40
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(49) %a, ptr noundef nonnull align 1 dereferenceable(49) %b, i32 49, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_63(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_63(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    call void @esp32p4MemCpySrcunalignedDst16From32To47(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 40
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 40
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 48
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 48
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr [[TMP4]], align 8
; CHECK-NEXT:    store i64 [[TMP6]], ptr [[TMP5]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 56
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 56
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[TMP8]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[B]], i32 60
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[A]], i32 60
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[TMP10]], align 2
; CHECK-NEXT:    store i16 [[TMP12]], ptr [[TMP11]], align 2
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[B]], i32 62
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[A]], i32 62
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[TMP13]], align 1
; CHECK-NEXT:    store i8 [[TMP15]], ptr [[TMP14]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(63) %a, ptr noundef nonnull align 1 dereferenceable(63) %b, i32 63, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_64(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_64(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index6(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 56
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 56
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(64) %a, ptr noundef nonnull align 1 dereferenceable(64) %b, i32 64, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_65(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_65(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index7(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 56
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 56
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 64
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 64
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(65) %a, ptr noundef nonnull align 1 dereferenceable(65) %b, i32 65, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_80(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_80(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.7(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 72
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 72
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(80) %a, ptr noundef nonnull align 1 dereferenceable(80) %b, i32 80, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_81(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_81(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.8(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 72
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 72
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 80
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 80
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(81) %a, ptr noundef nonnull align 1 dereferenceable(81) %b, i32 81, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_88(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_88(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From32To47Index5(ptr [[TMP2]], ptr [[TMP1]])
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(88) %a, ptr noundef nonnull align 1 dereferenceable(88) %b, i32 88, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_96(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_96(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From32To47Index6(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 88
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 88
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(96) %a, ptr noundef nonnull align 1 dereferenceable(96) %b, i32 96, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_112(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_112(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index8(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 104
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 104
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(112) %a, ptr noundef nonnull align 1 dereferenceable(112) %b, i32 112, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_124(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_124(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index9(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 104
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 104
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr [[TMP4]], align 8
; CHECK-NEXT:    store i64 [[TMP6]], ptr [[TMP5]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 120
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 120
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[TMP8]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(124) %a, ptr noundef nonnull align 1 dereferenceable(124) %b, i32 124, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_127(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_127(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index10(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 104
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 104
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 112
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 112
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr [[TMP4]], align 8
; CHECK-NEXT:    store i64 [[TMP6]], ptr [[TMP5]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 120
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 120
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[TMP8]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[B]], i32 124
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[A]], i32 124
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[TMP10]], align 2
; CHECK-NEXT:    store i16 [[TMP12]], ptr [[TMP11]], align 2
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[B]], i32 126
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[A]], i32 126
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[TMP13]], align 1
; CHECK-NEXT:    store i8 [[TMP15]], ptr [[TMP14]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(127) %a, ptr noundef nonnull align 1 dereferenceable(127) %b, i32 127, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_128(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.9(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 120
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 120
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(128) %a, ptr noundef nonnull align 1 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_129(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_129(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From16to31.10(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 120
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 120
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 128
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 128
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(129) %a, ptr noundef nonnull align 1 dereferenceable(129) %b, i32 129, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_255(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_255(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From32To47Index7(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 232
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 232
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 240
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 240
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr [[TMP4]], align 8
; CHECK-NEXT:    store i64 [[TMP6]], ptr [[TMP5]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 248
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 248
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[TMP8]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[B]], i32 252
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[A]], i32 252
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[TMP10]], align 2
; CHECK-NEXT:    store i16 [[TMP12]], ptr [[TMP11]], align 2
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[B]], i32 254
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[A]], i32 254
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[TMP13]], align 1
; CHECK-NEXT:    store i8 [[TMP15]], ptr [[TMP14]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(255) %a, ptr noundef nonnull align 1 dereferenceable(255) %b, i32 255, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_256(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index11(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 248
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 248
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(256) %a, ptr noundef nonnull align 1 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_1023(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_1023(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16mod48From32To47Index8(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 1000
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 1000
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 1008
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 1008
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr [[TMP4]], align 8
; CHECK-NEXT:    store i64 [[TMP6]], ptr [[TMP5]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 1016
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 1016
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[TMP8]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i8, ptr [[B]], i32 1020
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[A]], i32 1020
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[TMP10]], align 2
; CHECK-NEXT:    store i16 [[TMP12]], ptr [[TMP11]], align 2
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr i8, ptr [[B]], i32 1022
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr i8, ptr [[A]], i32 1022
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[TMP13]], align 1
; CHECK-NEXT:    store i8 [[TMP15]], ptr [[TMP14]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(1023) %a, ptr noundef nonnull align 1 dereferenceable(1023) %b, i32 1023, i1 false)
  ret void
}

define void @test_srcunalign_dst8_constant_size_1024(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dst8_constant_size_1024(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    [[DST_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[SRC_OFFSET_BY_8BYTES_I:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    tail call void @esp32p4MemCpySrcunalignedDst16Div48Index12(ptr [[DST_OFFSET_BY_8BYTES_I]], ptr [[SRC_OFFSET_BY_8BYTES_I]])
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 1016
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 1016
; CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[TMP2]], align 16
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(1024) %a, ptr noundef nonnull align 1 dereferenceable(1024) %b, i32 1024, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_1(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[B]], align 1
; CHECK-NEXT:    store i8 [[TMP0]], ptr [[A]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1) %a, ptr noundef nonnull align 1 dereferenceable(1) %b, i32 1, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_2(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_2(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(2) %a, ptr noundef nonnull align 1 dereferenceable(2) %b, i32 2, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_3(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_3(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[B]], align 2
; CHECK-NEXT:    store i16 [[TMP0]], ptr [[A]], align 2
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(3) %a, ptr noundef nonnull align 1 dereferenceable(3) %b, i32 3, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_4(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_4(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(4) %a, ptr noundef nonnull align 1 dereferenceable(4) %b, i32 4, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_5(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_5(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(5) %a, ptr noundef nonnull align 1 dereferenceable(5) %b, i32 5, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_6(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_6(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(6) %a, ptr noundef nonnull align 1 dereferenceable(6) %b, i32 6, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_7(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_7(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[B]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 6
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 6
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(7) %a, ptr noundef nonnull align 1 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_8(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_8(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(8) %a, ptr noundef nonnull align 1 dereferenceable(8) %b, i32 8, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_9(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_9(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[TMP1]], align 1
; CHECK-NEXT:    store i8 [[TMP3]], ptr [[TMP2]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(9) %a, ptr noundef nonnull align 1 dereferenceable(9) %b, i32 9, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_10(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_10(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(10) %a, ptr noundef nonnull align 1 dereferenceable(10) %b, i32 10, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_11(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_11(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[TMP1]], align 2
; CHECK-NEXT:    store i16 [[TMP3]], ptr [[TMP2]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 10
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 10
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(11) %a, ptr noundef nonnull align 1 dereferenceable(11) %b, i32 11, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_12(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_12(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(12) %a, ptr noundef nonnull align 1 dereferenceable(12) %b, i32 12, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_13(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_13(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[TMP4]], align 1
; CHECK-NEXT:    store i8 [[TMP6]], ptr [[TMP5]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(13) %a, ptr noundef nonnull align 1 dereferenceable(13) %b, i32 13, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_14(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_14(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    store i16 [[TMP6]], ptr [[TMP5]], align 2
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(14) %a, ptr noundef nonnull align 1 dereferenceable(14) %b, i32 14, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_15(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_15(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    store i64 [[TMP0]], ptr [[A]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr [[B]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr [[A]], i32 8
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP2]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[B]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr [[A]], i32 12
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[TMP4]], align 2
; CHECK-NEXT:    store i16 [[TMP6]], ptr [[TMP5]], align 2
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr i8, ptr [[B]], i32 14
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr i8, ptr [[A]], i32 14
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[TMP8]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(15) %a, ptr noundef nonnull align 1 dereferenceable(15) %b, i32 15, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_16(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    [[SRCQ9_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q(i32 [[TMP3]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]])
; CHECK-NEXT:    [[VST128IP_M10_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[SRCQ9_I]], ptr [[A]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(16) %a, ptr noundef nonnull align 1 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_17(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_17(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    [[SRCQ9_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]])
; CHECK-NEXT:    [[VST128IP_M10_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[SRCQ9_I]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRC_AFTER_16BYTE_PROCESSING_I:%.*]] = getelementptr i8, ptr [[TMP3]], i32 -16
; CHECK-NEXT:    [[TMP5:%.*]] = load i8, ptr [[SRC_AFTER_16BYTE_PROCESSING_I]], align 1
; CHECK-NEXT:    store i8 [[TMP5]], ptr [[VST128IP_M10_I]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(17) %a, ptr noundef nonnull align 1 dereferenceable(17) %b, i32 17, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_31(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_31(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    [[SRCQ9_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]])
; CHECK-NEXT:    [[VST128IP_M10_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[SRCQ9_I]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRC_AFTER_16BYTE_PROCESSING_I:%.*]] = getelementptr i8, ptr [[TMP3]], i32 -16
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[SRC_AFTER_16BYTE_PROCESSING_I]], align 4
; CHECK-NEXT:    store i32 [[TMP5]], ptr [[VST128IP_M10_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3267_I:%.*]] = getelementptr i8, ptr [[TMP3]], i32 -12
; CHECK-NEXT:    [[DST_GEP_I3268_I:%.*]] = getelementptr i8, ptr [[VST128IP_M10_I]], i32 4
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[SRC_GEP_I3267_I]], align 4
; CHECK-NEXT:    store i32 [[TMP6]], ptr [[DST_GEP_I3268_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3269_I:%.*]] = getelementptr i8, ptr [[TMP3]], i32 -8
; CHECK-NEXT:    [[DST_GEP_I3270_I:%.*]] = getelementptr i8, ptr [[VST128IP_M10_I]], i32 8
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[SRC_GEP_I3269_I]], align 4
; CHECK-NEXT:    store i32 [[TMP7]], ptr [[DST_GEP_I3270_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1671_I:%.*]] = getelementptr i8, ptr [[TMP3]], i32 -4
; CHECK-NEXT:    [[DST_GEP_I1672_I:%.*]] = getelementptr i8, ptr [[VST128IP_M10_I]], i32 12
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[SRC_GEP_I1671_I]], align 2
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[DST_GEP_I1672_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I873_I:%.*]] = getelementptr i8, ptr [[TMP3]], i32 -2
; CHECK-NEXT:    [[DST_GEP_I874_I:%.*]] = getelementptr i8, ptr [[VST128IP_M10_I]], i32 14
; CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[SRC_GEP_I873_I]], align 1
; CHECK-NEXT:    store i8 [[TMP9]], ptr [[DST_GEP_I874_I]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(31) %a, ptr noundef nonnull align 1 dereferenceable(31) %b, i32 31, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_32(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_32(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    [[SRCQLDIP6_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 0)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP6_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP6_I]], 1
; CHECK-NEXT:    [[VST128IP_M7_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQ_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]])
; CHECK-NEXT:    [[VST128IP_M8_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[SRCQ_I]], ptr [[VST128IP_M7_I]], i32 16)
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(32) %a, ptr noundef nonnull align 1 dereferenceable(32) %b, i32 32, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_33(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_33(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    [[SRCQLDIP6_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 0)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP6_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP6_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP6_I]], 2
; CHECK-NEXT:    [[VST128IP_M7_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQ_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]])
; CHECK-NEXT:    [[VST128IP_M8_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[SRCQ_I]], ptr [[VST128IP_M7_I]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = load i8, ptr [[TMP7]], align 1
; CHECK-NEXT:    store i8 [[TMP8]], ptr [[VST128IP_M8_I]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(33) %a, ptr noundef nonnull align 1 dereferenceable(33) %b, i32 33, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_47(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    [[SRCQLDIP6_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 0)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP6_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP6_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP6_I]], 2
; CHECK-NEXT:    [[VST128IP_M7_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQ_I:%.*]] = call <16 x i8> @llvm.riscv.esp.src.q(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]])
; CHECK-NEXT:    [[VST128IP_M8_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[SRCQ_I]], ptr [[VST128IP_M7_I]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[TMP7]], align 4
; CHECK-NEXT:    store i32 [[TMP8]], ptr [[VST128IP_M8_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3267_I:%.*]] = getelementptr i8, ptr [[TMP7]], i32 4
; CHECK-NEXT:    [[DST_GEP_I3268_I:%.*]] = getelementptr i8, ptr [[VST128IP_M8_I]], i32 4
; CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[SRC_GEP_I3267_I]], align 4
; CHECK-NEXT:    store i32 [[TMP9]], ptr [[DST_GEP_I3268_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I3269_I:%.*]] = getelementptr i8, ptr [[TMP7]], i32 8
; CHECK-NEXT:    [[DST_GEP_I3270_I:%.*]] = getelementptr i8, ptr [[VST128IP_M8_I]], i32 8
; CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[SRC_GEP_I3269_I]], align 4
; CHECK-NEXT:    store i32 [[TMP10]], ptr [[DST_GEP_I3270_I]], align 4
; CHECK-NEXT:    [[SRC_GEP_I1671_I:%.*]] = getelementptr i8, ptr [[TMP7]], i32 12
; CHECK-NEXT:    [[DST_GEP_I1672_I:%.*]] = getelementptr i8, ptr [[VST128IP_M8_I]], i32 12
; CHECK-NEXT:    [[TMP11:%.*]] = load i16, ptr [[SRC_GEP_I1671_I]], align 2
; CHECK-NEXT:    store i16 [[TMP11]], ptr [[DST_GEP_I1672_I]], align 2
; CHECK-NEXT:    [[SRC_GEP_I873_I:%.*]] = getelementptr i8, ptr [[TMP7]], i32 14
; CHECK-NEXT:    [[DST_GEP_I874_I:%.*]] = getelementptr i8, ptr [[VST128IP_M8_I]], i32 14
; CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[SRC_GEP_I873_I]], align 1
; CHECK-NEXT:    store i8 [[TMP12]], ptr [[DST_GEP_I874_I]], align 1
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(47) %a, ptr noundef nonnull align 1 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_48(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(48) %a, ptr noundef nonnull align 1 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_49(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_49(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(49) %a, ptr noundef nonnull align 1 dereferenceable(49) %b, i32 49, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_63(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_63(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(63) %a, ptr noundef nonnull align 1 dereferenceable(63) %b, i32 63, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_64(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_64(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(64) %a, ptr noundef nonnull align 1 dereferenceable(64) %b, i32 64, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_65(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_65(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(65) %a, ptr noundef nonnull align 1 dereferenceable(65) %b, i32 65, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_80(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_80(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(80) %a, ptr noundef nonnull align 1 dereferenceable(80) %b, i32 80, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_81(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_81(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(81) %a, ptr noundef nonnull align 1 dereferenceable(81) %b, i32 81, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_88(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_88(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(88) %a, ptr noundef nonnull align 1 dereferenceable(88) %b, i32 88, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_96(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_96(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(96) %a, ptr noundef nonnull align 1 dereferenceable(96) %b, i32 96, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_112(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_112(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(112) %a, ptr noundef nonnull align 1 dereferenceable(112) %b, i32 112, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_124(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_124(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(124) %a, ptr noundef nonnull align 1 dereferenceable(124) %b, i32 124, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_127(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_127(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(127) %a, ptr noundef nonnull align 1 dereferenceable(127) %b, i32 127, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_128(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(128) %a, ptr noundef nonnull align 1 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_129(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_129(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(129) %a, ptr noundef nonnull align 1 dereferenceable(129) %b, i32 129, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_255(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_255(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(255) %a, ptr noundef nonnull align 1 dereferenceable(255) %b, i32 255, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_256(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(256) %a, ptr noundef nonnull align 1 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_1023(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_1023(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1023) %a, ptr noundef nonnull align 1 dereferenceable(1023) %b, i32 1023, i1 false)
  ret void
}

define void @test_srcunalign_dstunalign_constant_size_1024(ptr %a, ptr %b) {
;
; CHECK-LABEL: define void @test_srcunalign_dstunalign_constant_size_1024(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LD128USARIP_M_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[B]], i32 16)
; CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M_I]], 1
; CHECK-NEXT:    [[LD128USARIP_M1_I:%.*]] = call { <16 x i8>, ptr, i32 } @llvm.riscv.esp.ld.128.usar.ip(ptr [[TMP1]], i32 16)
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr, i32 } [[LD128USARIP_M1_I]], 2
; CHECK-NEXT:    br label %[[MAIN_LOOP_BODY_I:.*]]
; CHECK:       [[MAIN_LOOP_BODY_I]]:
; CHECK-NEXT:    [[SRCQLDIP_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP2]], <16 x i8> [[TMP0]], ptr [[TMP3]], i32 16)
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP_I]], 2
; CHECK-NEXT:    [[VST128IP_M_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[A]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP2_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP6]], <16 x i8> [[TMP2]], ptr [[TMP7]], i32 16)
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 0
; CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP2_I]], 2
; CHECK-NEXT:    [[VST128IP_M3_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[VST128IP_M_I]], i32 16)
; CHECK-NEXT:    [[SRCQLDIP4_I:%.*]] = call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.src.q.ld.ip(i32 [[TMP4]], <16 x i8> [[TMP9]], <16 x i8> [[TMP6]], ptr [[TMP10]], i32 16)
; CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[SRCQLDIP4_I]], 0
; CHECK-NEXT:    [[VST128IP_M5_I:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[VST128IP_M3_I]], i32 16)
; CHECK-NEXT:    br i1 true, label %[[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT:.*]], label %[[MAIN_LOOP_BODY_I]]
; CHECK:       [[ESP32P4MEMCPYSRCUNALIGNEDDST16VAR_EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memcpy.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1024) %a, ptr noundef nonnull align 1 dereferenceable(1024) %b, i32 1024, i1 false)
  ret void
}


declare void @llvm.memcpy.p0.p0.i32(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i32, i1 immarg)

attributes #0 = { "target-features"="+32bit" }
