; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O1 -mtriple=riscv32 -mattr=+xespv,+espv-lowering -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=CHECK

define void @test(){
; CHECK-LABEL: test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    sw s0, 28(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s1, 24(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s8, 20(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s9, 16(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s10, 12(sp) # 4-byte Folded Spill
; CHECK-NEXT:    sw s11, 8(sp) # 4-byte Folded Spill
; CHECK-NEXT:    .cfi_offset s0, -4
; CHECK-NEXT:    .cfi_offset s1, -8
; CHECK-NEXT:    .cfi_offset s8, -12
; CHECK-NEXT:    .cfi_offset s9, -16
; CHECK-NEXT:    .cfi_offset s10, -20
; CHECK-NEXT:    .cfi_offset s11, -24
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    li a1, 8
; CHECK-NEXT:    esp.vld.128.ip q0, a1, 496
; CHECK-NEXT:    esp.vld.128.ip q1, a1, 496
; CHECK-NEXT:    esp.vld.128.ip q2, a1, 496
; CHECK-NEXT:    esp.vld.128.ip q3, a1, 496
; CHECK-NEXT:    esp.vld.128.ip q4, a1, 496
; CHECK-NEXT:    esp.vld.128.ip q5, a1, 496
; CHECK-NEXT:    esp.vld.128.ip q6, a1, 496
; CHECK-NEXT:    esp.vld.128.ip q7, a1, 496
; CHECK-NEXT:    li a1, 9
; CHECK-NEXT:    esp.vcmulas.s16.qacc.h q6, q7
; CHECK-NEXT:    esp.vcmulas.s16.qacc.h.ld.ip q6, a1, 32, q2, q1, trunc
; CHECK-NEXT:    li a1, 11
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    esp.vcmulas.s16.qacc.h.ld.xp q3, a2, a1, q6, q5, trunc
; CHECK-NEXT:    esp.vcmulas.s16.qacc.l q2, q3
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    li a3, 13
; CHECK-NEXT:    esp.vcmulas.s16.qacc.l.ld.ip q5, a2, -64, q1, q2
; CHECK-NEXT:    esp.vcmulas.s16.qacc.l.ld.xp q2, a3, a0, q3, q1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.vcmulas.s8.qacc.h q1, q6, trunc
; CHECK-NEXT:    esp.vcmulas.s8.qacc.h.ld.ip q0, a2, -128, q0, q0, trunc
; CHECK-NEXT:    li a2, 8
; CHECK-NEXT:    li a3, 2
; CHECK-NEXT:    li a4, 3
; CHECK-NEXT:    esp.vcmulas.s8.qacc.h.ld.xp q1, a3, a2, q1, q0
; CHECK-NEXT:    esp.vcmulas.s8.qacc.l q0, q0, trunc
; CHECK-NEXT:    esp.vcmulas.s8.qacc.l.ld.ip q2, a4, -96, q5, q5, trunc
; CHECK-NEXT:    li a4, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a5, 10
; CHECK-NEXT:    esp.vcmulas.s8.qacc.l.ld.xp q6, a5, a4, q2, q1, trunc
; CHECK-NEXT:    li a5, 11
; CHECK-NEXT:    li t3, 3
; CHECK-NEXT:    esp.vmulas.s16.qacc q2, q4
; CHECK-NEXT:    esp.vmulas.s16.qacc.ld.ip q1, a5, 96, q6, q7, trunc
; CHECK-NEXT:    esp.vmulas.s16.qacc.ld.xp q4, t3, a2, q2, q7
; CHECK-NEXT:    li a5, 1
; CHECK-NEXT:    esp.vmulas.s16.qacc.st.ip q3, a5, -32, q6, q0
; CHECK-NEXT:    li a5, 14
; CHECK-NEXT:    esp.vmulas.s16.qacc.st.xp q2, a5, a0, q4, q5, trunc
; CHECK-NEXT:    li t3, 3
; CHECK-NEXT:    li a5, 6
; CHECK-NEXT:    li t4, 6
; CHECK-NEXT:    esp.vmulas.s16.xacc q1, q4, trunc
; CHECK-NEXT:    esp.vmulas.s16.xacc.ld.ip q0, a5, -128, q6, q3
; CHECK-NEXT:    esp.vmulas.s16.xacc.ld.xp q1, t4, t3, q2, q7, trunc
; CHECK-NEXT:    li a5, 4
; CHECK-NEXT:    esp.vmulas.s16.xacc.st.ip q3, a5, -80, q4, q4
; CHECK-NEXT:    li s1, 9
; CHECK-NEXT:    li t4, 6
; CHECK-NEXT:    esp.vmulas.s16.xacc.st.xp q3, t4, s1, q4, q1
; CHECK-NEXT:    esp.vmulas.s8.qacc q6, q2, trunc
; CHECK-NEXT:    li t4, 8
; CHECK-NEXT:    esp.vmulas.s8.qacc.ld.ip q6, t4, -80, q5, q3, trunc
; CHECK-NEXT:    li t4, 13
; CHECK-NEXT:    esp.vmulas.s8.qacc.ld.xp q6, t4, t3, q5, q6, trunc
; CHECK-NEXT:    li t4, 10
; CHECK-NEXT:    esp.vmulas.s8.qacc.st.ip q6, t4, 64, q6, q2, trunc
; CHECK-NEXT:    li t4, 13
; CHECK-NEXT:    li t5, 11
; CHECK-NEXT:    esp.vmulas.s8.qacc.st.xp q5, t5, t4, q5, q2, trunc
; CHECK-NEXT:    li t5, 5
; CHECK-NEXT:    esp.vmulas.s8.xacc q7, q3
; CHECK-NEXT:    esp.vmulas.s8.xacc.ld.ip q3, t5, -64, q1, q4, trunc
; CHECK-NEXT:    li t6, 6
; CHECK-NEXT:    li t5, 8
; CHECK-NEXT:    esp.vmulas.s8.xacc.ld.xp q5, t5, t6, q3, q2, trunc
; CHECK-NEXT:    li t5, 9
; CHECK-NEXT:    esp.vmulas.s8.xacc.st.ip q1, t5, 64, q4, q1
; CHECK-NEXT:    li t5, 2
; CHECK-NEXT:    esp.vmulas.s8.xacc.st.xp q0, t5, a4, q4, q0, trunc
; CHECK-NEXT:    esp.vmulas.u16.qacc q2, q5
; CHECK-NEXT:    li t5, 13
; CHECK-NEXT:    esp.vmulas.u16.qacc.ld.ip q0, t5, 64, q5, q7
; CHECK-NEXT:    li t5, 4
; CHECK-NEXT:    li s0, 12
; CHECK-NEXT:    esp.vmulas.u16.qacc.ld.xp q6, s0, t5, q6, q0
; CHECK-NEXT:    li s0, 4
; CHECK-NEXT:    esp.vmulas.u16.qacc.st.ip q1, s0, 16, q3, q3, trunc
; CHECK-NEXT:    li s0, 9
; CHECK-NEXT:    esp.vmulas.u16.qacc.st.xp q6, s0, a4, q4, q7, trunc
; CHECK-NEXT:    li a2, 10
; CHECK-NEXT:    li s0, 14
; CHECK-NEXT:    li s8, 7
; CHECK-NEXT:    esp.vmulas.u16.xacc q0, q0, trunc
; CHECK-NEXT:    esp.vmulas.u16.xacc.ld.ip q3, s0, 32, q0, q1
; CHECK-NEXT:    esp.vmulas.u16.xacc.ld.xp q7, s8, a2, q4, q1
; CHECK-NEXT:    li s0, 6
; CHECK-NEXT:    esp.vmulas.u16.xacc.st.ip q1, s0, -48, q0, q6
; CHECK-NEXT:    li s0, 7
; CHECK-NEXT:    li s8, 1
; CHECK-NEXT:    esp.vmulas.u16.xacc.st.xp q3, s8, s0, q6, q4, trunc
; CHECK-NEXT:    li s8, 8
; CHECK-NEXT:    esp.vmulas.u8.qacc q3, q6, trunc
; CHECK-NEXT:    esp.vmulas.u8.qacc.ld.ip q4, s8, 32, q7, q6, trunc
; CHECK-NEXT:    li s8, 4
; CHECK-NEXT:    esp.vmulas.u8.qacc.ld.xp q0, s8, a0, q4, q1, trunc
; CHECK-NEXT:    li s8, 8
; CHECK-NEXT:    esp.vmulas.u8.qacc.st.ip q3, s8, 0, q2, q4
; CHECK-NEXT:    li s8, 1
; CHECK-NEXT:    esp.vmulas.u8.qacc.st.xp q6, s8, s8, q3, q1
; CHECK-NEXT:    li s8, 7
; CHECK-NEXT:    esp.vmulas.u8.xacc q3, q5
; CHECK-NEXT:    esp.vmulas.u8.xacc.ld.ip q5, s8, 80, q3, q2
; CHECK-NEXT:    li s8, 14
; CHECK-NEXT:    li s9, 7
; CHECK-NEXT:    esp.vmulas.u8.xacc.ld.xp q4, s9, s8, q1, q0
; CHECK-NEXT:    li s9, 0
; CHECK-NEXT:    esp.vmulas.u8.xacc.st.ip q5, s9, -112, q6, q6, trunc
; CHECK-NEXT:    li s9, 11
; CHECK-NEXT:    esp.vmulas.u8.xacc.st.xp q2, s9, s8, q6, q0, trunc
; CHECK-NEXT:    li s9, 5
; CHECK-NEXT:    li s10, 6
; CHECK-NEXT:    li s11, 6
; CHECK-NEXT:    esp.vmulas.s16.qacc.ldbc.incp q5, s9, q3, q5, trunc
; CHECK-NEXT:    esp.vmulas.s8.qacc.ldbc.incp q5, s10, q1, q6, trunc
; CHECK-NEXT:    esp.vmulas.u16.qacc.ldbc.incp q1, s11, q6, q0
; CHECK-NEXT:    li s9, 1
; CHECK-NEXT:    li s10, 8
; CHECK-NEXT:    li s11, 8
; CHECK-NEXT:    esp.vmulas.u8.qacc.ldbc.incp q4, s9, q1, q7, trunc
; CHECK-NEXT:    li s9, 13
; CHECK-NEXT:    esp.vsmulas.s16.qacc q7, q7, 13
; CHECK-NEXT:    esp.vsmulas.s16.qacc.ld.incp q4, s10, q5, q5, 1, trunc
; CHECK-NEXT:    li s10, 0
; CHECK-NEXT:    esp.vsmulas.s8.qacc q7, q7, 2, trunc
; CHECK-NEXT:    esp.vsmulas.s8.qacc.ld.incp q4, s11, q7, q3, 10, trunc
; CHECK-NEXT:    esp.vsmulas.u16.qacc q7, q7, 6, trunc
; CHECK-NEXT:    esp.vsmulas.u16.qacc.ld.incp q0, s9, q2, q7, 14
; CHECK-NEXT:    esp.vsmulas.u8.qacc q7, q5, 10, trunc
; CHECK-NEXT:    esp.vsmulas.u8.qacc.ld.incp q3, s10, q5, q1, 11, trunc
; CHECK-NEXT:    li s9, 2
; CHECK-NEXT:    li s10, 4
; CHECK-NEXT:    li s11, 2
; CHECK-NEXT:    esp.cmul.s16 q2, q7, q3, 0, rup
; CHECK-NEXT:    esp.cmul.s16.ld.incp q0, s9, q1, q7, q2, 1, trunc, rhtz
; CHECK-NEXT:    esp.cmul.s16.st.incp q3, s10, q1, q7, q5, 3, trunc, raz
; CHECK-NEXT:    esp.cmul.s8 q4, q1, q4, 2, trunc, rhtz
; CHECK-NEXT:    esp.cmul.s8.ld.incp q5, s11, q6, q3, q7, 2, rtz
; CHECK-NEXT:    li s9, 12
; CHECK-NEXT:    li s10, 13
; CHECK-NEXT:    esp.cmul.s8.st.incp q1, s9, q0, q1, q6, 0, rdn
; CHECK-NEXT:    esp.cmul.u16 q6, q7, q2, 3, rup
; CHECK-NEXT:    esp.cmul.u16.ld.incp q6, s10, q6, q5, q0, 0, rne
; CHECK-NEXT:    li s9, 4
; CHECK-NEXT:    li s10, 8
; CHECK-NEXT:    esp.cmul.u16.st.incp q5, s9, q6, q6, q4, 1, raz
; CHECK-NEXT:    esp.cmul.u8 q2, q5, q1, 3, trunc, rhtz
; CHECK-NEXT:    esp.cmul.u8.ld.incp q1, s10, q6, q6, q4, 3, trunc
; CHECK-NEXT:    li s9, 12
; CHECK-NEXT:    esp.cmul.u8.st.incp q2, s9, q3, q4, q6, 0, rdn
; CHECK-NEXT:    li s9, 5
; CHECK-NEXT:    li s10, 14
; CHECK-NEXT:    li s11, 10
; CHECK-NEXT:    esp.max.s16.a q2, a2
; CHECK-NEXT:    esp.max.s32.a q2, a2
; CHECK-NEXT:    esp.max.s8.a q5, a2
; CHECK-NEXT:    esp.max.u16.a q1, a2
; CHECK-NEXT:    esp.max.u32.a q4, a2
; CHECK-NEXT:    esp.max.u8.a q2, a2
; CHECK-NEXT:    esp.min.s16.a q5, a2
; CHECK-NEXT:    esp.min.s32.a q7, a2
; CHECK-NEXT:    esp.min.s8.a q1, a2
; CHECK-NEXT:    esp.min.u16.a q5, a2
; CHECK-NEXT:    esp.min.u32.a q1, a2
; CHECK-NEXT:    esp.min.u8.a q1, a2
; CHECK-NEXT:    esp.vabs.16 q0, q7
; CHECK-NEXT:    esp.vabs.32 q4, q1
; CHECK-NEXT:    esp.vabs.8 q7, q7
; CHECK-NEXT:    esp.vadd.s16 q2, q6, q4, trunc
; CHECK-NEXT:    esp.vadd.s16.ld.incp q3, s9, q3, q7, q6, trunc
; CHECK-NEXT:    esp.vadd.s16.st.incp q4, s10, q3, q6, q4
; CHECK-NEXT:    esp.vadd.s32 q4, q3, q7
; CHECK-NEXT:    esp.vadd.s32.ld.incp q5, s11, q2, q6, q0
; CHECK-NEXT:    li a2, 4
; CHECK-NEXT:    li s9, 4
; CHECK-NEXT:    esp.vadd.s32.st.incp q6, a2, q0, q4, q4, trunc
; CHECK-NEXT:    esp.vadd.s8 q3, q3, q5, trunc
; CHECK-NEXT:    esp.vadd.s8.ld.incp q0, s9, q4, q4, q0, trunc
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.vadd.s8.st.incp q4, a2, q4, q1, q5, trunc
; CHECK-NEXT:    li a2, 12
; CHECK-NEXT:    esp.vadd.u16 q2, q5, q6
; CHECK-NEXT:    esp.vadd.u16.ld.incp q4, a2, q5, q7, q5, trunc
; CHECK-NEXT:    li a2, 11
; CHECK-NEXT:    li s9, 8
; CHECK-NEXT:    esp.vadd.u16.st.incp q1, a2, q1, q0, q4
; CHECK-NEXT:    esp.vadd.u32 q5, q1, q1
; CHECK-NEXT:    esp.vadd.u32.ld.incp q4, s9, q0, q7, q5, trunc
; CHECK-NEXT:    li a2, 8
; CHECK-NEXT:    li s9, 14
; CHECK-NEXT:    esp.vadd.u32.st.incp q3, a2, q5, q4, q7, trunc
; CHECK-NEXT:    esp.vadd.u8 q1, q3, q2
; CHECK-NEXT:    esp.vadd.u8.ld.incp q0, s9, q6, q4, q7, trunc
; CHECK-NEXT:    li a2, 8
; CHECK-NEXT:    li s9, 14
; CHECK-NEXT:    esp.vadd.u8.st.incp q5, a2, q6, q0, q4, trunc
; CHECK-NEXT:    esp.vclamp.s16 q2, q7, 1
; CHECK-NEXT:    esp.vmax.s16 q2, q2, q3
; CHECK-NEXT:    esp.vmax.s16.ld.incp q0, s9, q7, q7, q6
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    li s9, 10
; CHECK-NEXT:    esp.vmax.s16.st.incp q0, a2, q0, q7, q2
; CHECK-NEXT:    esp.vmax.s32 q4, q3, q3
; CHECK-NEXT:    esp.vmax.s32.ld.incp q6, s9, q4, q4, q7
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li s9, 13
; CHECK-NEXT:    esp.vmax.s32.st.incp q4, a2, q3, q1, q0
; CHECK-NEXT:    esp.vmax.s8 q5, q4, q5
; CHECK-NEXT:    esp.vmax.s8.ld.incp q6, s9, q5, q2, q4
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    li s9, 12
; CHECK-NEXT:    esp.vmax.s8.st.incp q1, a2, q3, q6, q3
; CHECK-NEXT:    esp.vmax.u16 q6, q4, q6
; CHECK-NEXT:    esp.vmax.u16.ld.incp q7, s9, q1, q6, q4
; CHECK-NEXT:    li a2, 10
; CHECK-NEXT:    li s9, 13
; CHECK-NEXT:    li s10, 3
; CHECK-NEXT:    esp.vmax.u16.st.incp q2, a2, q7, q4, q7
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.vmax.u32 q0, q4, q6
; CHECK-NEXT:    esp.vmax.u32.ld.incp q7, s9, q5, q0, q4
; CHECK-NEXT:    esp.vmax.u32.st.incp q4, s10, q5, q0, q4
; CHECK-NEXT:    esp.vmax.u8 q0, q4, q0
; CHECK-NEXT:    esp.vmax.u8.ld.incp q2, a2, q2, q2, q1
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    li s9, 2
; CHECK-NEXT:    esp.vmax.u8.st.incp q0, a2, q6, q2, q0
; CHECK-NEXT:    esp.vmin.s16 q1, q3, q6
; CHECK-NEXT:    esp.vmin.s16.ld.incp q4, s9, q5, q7, q5
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    li s9, 4
; CHECK-NEXT:    li s10, 3
; CHECK-NEXT:    esp.vmin.s16.st.incp q6, a2, q7, q5, q7
; CHECK-NEXT:    esp.vmin.s32 q0, q7, q2
; CHECK-NEXT:    esp.vmin.s32.ld.incp q4, s9, q4, q3, q6
; CHECK-NEXT:    esp.vmin.s32.st.incp q6, s10, q3, q2, q5
; CHECK-NEXT:    li a2, 7
; CHECK-NEXT:    esp.vmin.s8 q0, q0, q7
; CHECK-NEXT:    esp.vmin.s8.ld.incp q3, a2, q5, q4, q3
; CHECK-NEXT:    li a2, 14
; CHECK-NEXT:    li s9, 7
; CHECK-NEXT:    esp.vmin.s8.st.incp q2, a2, q3, q1, q3
; CHECK-NEXT:    esp.vmin.u16 q1, q4, q6
; CHECK-NEXT:    esp.vmin.u16.ld.incp q6, s9, q5, q5, q0
; CHECK-NEXT:    li a2, 11
; CHECK-NEXT:    li s9, 8
; CHECK-NEXT:    esp.vmin.u16.st.incp q3, a2, q6, q0, q5
; CHECK-NEXT:    esp.vmin.u32 q6, q1, q0
; CHECK-NEXT:    esp.vmin.u32.ld.incp q4, s9, q5, q0, q5
; CHECK-NEXT:    li a2, 12
; CHECK-NEXT:    li s9, 6
; CHECK-NEXT:    esp.vmin.u32.st.incp q0, a2, q1, q3, q0
; CHECK-NEXT:    esp.vmin.u8 q7, q4, q4
; CHECK-NEXT:    esp.vmin.u8.ld.incp q3, s9, q5, q2, q5
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    li s9, 8
; CHECK-NEXT:    li s10, 0
; CHECK-NEXT:    esp.vmin.u8.st.incp q3, a2, q1, q2, q4
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:    esp.vmul.s16 q4, q7, q7, rne
; CHECK-NEXT:    esp.vmul.s16.ld.incp q0, s9, q7, q1, q5, trunc, rhaz
; CHECK-NEXT:    li s9, 6
; CHECK-NEXT:    esp.vmul.s16.s8xs8 q1, q2, q2, q1
; CHECK-NEXT:    esp.vmul.s16.st.incp q3, s10, q7, q6, q5, trunc, raz
; CHECK-NEXT:    li s10, 5
; CHECK-NEXT:    esp.vmul.s32.s16xs16 q1, q2, q3, q0, rhaz
; CHECK-NEXT:    esp.vmul.s8 q5, q3, q5, trunc, raz
; CHECK-NEXT:    esp.vmul.s8.ld.incp q3, a2, q3, q3, q6, trunc, rtz
; CHECK-NEXT:    esp.vmul.s8.st.incp q6, s9, q5, q1, q1, rne
; CHECK-NEXT:    esp.vmul.u16 q7, q4, q4, rup
; CHECK-NEXT:    esp.vmul.u16.ld.incp q4, s10, q5, q4, q0, trunc, rne
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.vmul.u16.st.incp q3, a2, q3, q1, q4, raz
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.vmul.u8 q7, q7, q4, rup
; CHECK-NEXT:    esp.vmul.u8.ld.incp q2, a2, q4, q5, q0, trunc, rdn
; CHECK-NEXT:    li s9, 5
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:    li s10, 6
; CHECK-NEXT:    esp.vmul.u8.st.incp q7, a2, q6, q1, q6, trunc, rne
; CHECK-NEXT:    li a2, 10
; CHECK-NEXT:    esp.vprelu.s16 q1, q6, q4, a2, trunc, rtz
; CHECK-NEXT:    esp.vprelu.s8 q7, q2, q6, s0, raz
; CHECK-NEXT:    esp.vrelu.s16 q6, t6, s0, trunc, rhtz
; CHECK-NEXT:    esp.vrelu.s8 q0, a0, t5, rup
; CHECK-NEXT:    esp.vsadds.s16 q5, q3, s9
; CHECK-NEXT:    esp.vsadds.s8 q1, q1, s1
; CHECK-NEXT:    esp.vsadds.u16 q5, q0, a1, trunc
; CHECK-NEXT:    li a3, 8
; CHECK-NEXT:    esp.vsadds.u8 q7, q3, a3, trunc
; CHECK-NEXT:    esp.vsat.s16 q7, q3, a2, a2
; CHECK-NEXT:    esp.vsat.s32 q5, q7, a1, a0
; CHECK-NEXT:    esp.vsat.s8 q1, q6, s0, s0
; CHECK-NEXT:    esp.vsat.u16 q3, q7, a4, t6
; CHECK-NEXT:    esp.vsat.u32 q0, q6, t4, a1
; CHECK-NEXT:    esp.vsat.u8 q1, q6, a4, t3
; CHECK-NEXT:    esp.vssubs.s16 q1, q3, t5, trunc
; CHECK-NEXT:    esp.vssubs.s8 q5, q3, a0
; CHECK-NEXT:    esp.vssubs.u16 q7, q3, t3
; CHECK-NEXT:    esp.vssubs.u8 q6, q2, a2
; CHECK-NEXT:    esp.vsub.s16 q2, q1, q1
; CHECK-NEXT:    esp.vsub.s16.ld.incp q6, s10, q5, q0, q7
; CHECK-NEXT:    li a2, 11
; CHECK-NEXT:    li s10, 1
; CHECK-NEXT:    esp.vsub.s16.st.incp q6, a2, q2, q0, q6
; CHECK-NEXT:    li a2, 14
; CHECK-NEXT:    esp.vsub.s32 q4, q1, q6
; CHECK-NEXT:    esp.vsub.s32.ld.incp q0, s10, q7, q1, q7, trunc
; CHECK-NEXT:    esp.vsub.s32.st.incp q5, a2, q5, q6, q3, trunc
; CHECK-NEXT:    esp.vsub.s8 q0, q5, q4, trunc
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    esp.vsub.s8.ld.incp q2, a2, q2, q7, q2
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    li s10, 3
; CHECK-NEXT:    esp.vsub.s8.st.incp q2, a2, q1, q7, q1
; CHECK-NEXT:    li a2, 11
; CHECK-NEXT:    esp.vsub.u16 q7, q6, q4, trunc
; CHECK-NEXT:    esp.vsub.u16.ld.incp q2, s10, q0, q5, q1, trunc
; CHECK-NEXT:    li s10, 1
; CHECK-NEXT:    esp.vsub.u16.st.incp q3, a2, q2, q7, q3
; CHECK-NEXT:    esp.vsub.u32 q2, q3, q3, trunc
; CHECK-NEXT:    esp.vsub.u32.ld.incp q2, s10, q4, q4, q2, trunc
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li s10, 7
; CHECK-NEXT:    esp.vsub.u32.st.incp q7, a2, q3, q7, q2, trunc
; CHECK-NEXT:    esp.vsub.u8 q4, q4, q7, trunc
; CHECK-NEXT:    esp.vsub.u8.ld.incp q0, s10, q7, q2, q7
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li s10, 13
; CHECK-NEXT:    esp.vsub.u8.st.incp q7, a2, q6, q6, q0
; CHECK-NEXT:    li s11, 5
; CHECK-NEXT:    esp.addx2 a2, s0, t5
; CHECK-NEXT:    esp.addx4 a2, t5, t4
; CHECK-NEXT:    esp.sat s10, a1, a0
; CHECK-NEXT:    li s10, 2
; CHECK-NEXT:    esp.subx2 a2, s10, t3
; CHECK-NEXT:    esp.subx4 a2, s9, t6
; CHECK-NEXT:    esp.vcmp.eq.s16 q5, q5, q2
; CHECK-NEXT:    esp.vcmp.eq.s32 q3, q0, q1
; CHECK-NEXT:    esp.vcmp.eq.s8 q7, q3, q2
; CHECK-NEXT:    esp.vcmp.eq.u16 q1, q4, q1
; CHECK-NEXT:    esp.vcmp.eq.u32 q3, q6, q1
; CHECK-NEXT:    esp.vcmp.eq.u8 q4, q0, q3
; CHECK-NEXT:    esp.vcmp.gt.s16 q6, q2, q1
; CHECK-NEXT:    esp.vcmp.gt.s32 q5, q0, q6
; CHECK-NEXT:    esp.vcmp.gt.s8 q1, q7, q2
; CHECK-NEXT:    esp.vcmp.gt.u16 q2, q6, q3
; CHECK-NEXT:    esp.vcmp.gt.u32 q3, q4, q6
; CHECK-NEXT:    esp.vcmp.gt.u8 q1, q3, q2
; CHECK-NEXT:    esp.vcmp.lt.s16 q4, q2, q7
; CHECK-NEXT:    esp.vcmp.lt.s32 q3, q1, q3
; CHECK-NEXT:    esp.vcmp.lt.s8 q0, q7, q7
; CHECK-NEXT:    esp.vcmp.lt.u16 q2, q5, q0
; CHECK-NEXT:    esp.vcmp.lt.u32 q0, q6, q4
; CHECK-NEXT:    esp.vcmp.lt.u8 q7, q1, q2
; CHECK-NEXT:    esp.mov.s16.qacc q3
; CHECK-NEXT:    esp.mov.s8.qacc q7
; CHECK-NEXT:    esp.mov.u16.qacc q6
; CHECK-NEXT:    esp.mov.u8.qacc q7
; CHECK-NEXT:    esp.movi.16.a q1, a2, 6
; CHECK-NEXT:    esp.movi.16.q q5, a1, 0
; CHECK-NEXT:    esp.movi.32.a q5, a2, 0
; CHECK-NEXT:    esp.movi.32.q q3, a0, 3
; CHECK-NEXT:    esp.movi.8.a q1, a2, 4
; CHECK-NEXT:    esp.movi.8.q q3, t6, 10
; CHECK-NEXT:    esp.movx.r.cfg a2
; CHECK-NEXT:    esp.movx.r.fft.bit.width a2
; CHECK-NEXT:    esp.movx.r.perf a2, a3
; CHECK-NEXT:    li a5, 8
; CHECK-NEXT:    esp.movx.r.sar a2
; CHECK-NEXT:    esp.movx.r.sar.bytes a2
; CHECK-NEXT:    esp.movx.r.xacc.h a2
; CHECK-NEXT:    esp.movx.r.xacc.l a2
; CHECK-NEXT:    esp.movx.w.cfg t3
; CHECK-NEXT:    esp.movx.w.fft.bit.width s8
; CHECK-NEXT:    esp.movx.w.perf s10
; CHECK-NEXT:    li a3, 2
; CHECK-NEXT:    esp.movx.w.sar s9
; CHECK-NEXT:    esp.movx.w.sar.bytes a0
; CHECK-NEXT:    esp.movx.w.xacc.h s9
; CHECK-NEXT:    esp.movx.w.xacc.l s8
; CHECK-NEXT:    esp.vext.s16 q2, q0, q6
; CHECK-NEXT:    esp.vext.s8 q2, q5, q7
; CHECK-NEXT:    esp.vext.u16 q0, q2, q3
; CHECK-NEXT:    esp.vext.u8 q1, q4, q4
; CHECK-NEXT:    esp.vunzip.16 q6, q5
; CHECK-NEXT:    esp.vunzip.32 q2, q5
; CHECK-NEXT:    esp.vunzip.8 q5, q2
; CHECK-NEXT:    esp.vunzipt.16 q7, q0, q1
; CHECK-NEXT:    esp.vunzipt.8 q5, q3, q0
; CHECK-NEXT:    esp.vzip.16 q6, q0
; CHECK-NEXT:    esp.vzip.32 q7, q3
; CHECK-NEXT:    esp.vzip.8 q6, q1
; CHECK-NEXT:    esp.vzipt.16 q2, q6, q4
; CHECK-NEXT:    esp.vzipt.8 q6, q0, q4
; CHECK-NEXT:    esp.zero.q q1
; CHECK-NEXT:    esp.zero.qacc
; CHECK-NEXT:    esp.zero.xacc
; CHECK-NEXT:    esp.fft.ams.s16.ld.incp q2, s11, q7, q1, q4, q2, q6, 1
; CHECK-NEXT:    li a2, 8
; CHECK-NEXT:    li s10, 2
; CHECK-NEXT:    esp.fft.ams.s16.ld.incp.uaup q0, a2, q7, q4, q1, q5, q5, 1, trunc
; CHECK-NEXT:    esp.fft.ams.s16.ld.r32.decp q0, s10, q3, q1, q6, q1, q3, 1
; CHECK-NEXT:    li a2, 6
; CHECK-NEXT:    li s10, 6
; CHECK-NEXT:    esp.fft.ams.s16.st.incp q4, q3, s10, a2, q4, q5, q3, 1, trunc
; CHECK-NEXT:    li s10, 12
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    esp.fft.bitrev q2, a2
; CHECK-NEXT:    li a2, 6
; CHECK-NEXT:    esp.fft.cmul.s16.ld.xp q6, a2, a2, q1, q6, q3, 4, trunc
; CHECK-NEXT:    li a2, 14
; CHECK-NEXT:    esp.fft.cmul.s16.st.xp q5, q2, q5, a2, t4, 6, 2, 3, trunc
; CHECK-NEXT:    li a2, 5
; CHECK-NEXT:    esp.fft.r2bf.s16 q3, q2, q3, q4, 1
; CHECK-NEXT:    esp.fft.r2bf.s16.st.incp q7, q4, q6, a2, 0, trunc
; CHECK-NEXT:    li a2, 7
; CHECK-NEXT:    esp.fft.vst.r32.decp q1, a2, 1
; CHECK-NEXT:    li a2, 14
; CHECK-NEXT:    esp.ld.128.usar.ip q4, a2, -576
; CHECK-NEXT:    li a2, 4
; CHECK-NEXT:    esp.ld.128.usar.xp q1, a2, s9
; CHECK-NEXT:    li a2, 8
; CHECK-NEXT:    esp.ld.xacc.ip a2, -768
; CHECK-NEXT:    li a2, 7
; CHECK-NEXT:    esp.ldqa.s16.128.ip a2, 1280
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.ldqa.s16.128.xp a2, t3
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.ldqa.s8.128.ip a2, -384
; CHECK-NEXT:    li a2, 10
; CHECK-NEXT:    esp.ldqa.s8.128.xp a2, s10
; CHECK-NEXT:    li a2, 5
; CHECK-NEXT:    esp.ldqa.u16.128.ip a2, -1856
; CHECK-NEXT:    li a2, 8
; CHECK-NEXT:    esp.ldqa.u16.128.xp a2, s0
; CHECK-NEXT:    li a2, 4
; CHECK-NEXT:    esp.ldqa.u8.128.ip a2, 448
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    esp.ldqa.u8.128.xp a2, s8
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.vldbc.16.ip q6, a2, 200
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.vldbc.16.xp q2, a2, a4
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.vldbc.32.ip q7, a2, -332
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.vldbc.32.xp q5, a2, s10
; CHECK-NEXT:    li a2, 11
; CHECK-NEXT:    esp.vldbc.8.ip q7, a2, -80
; CHECK-NEXT:    li a2, 5
; CHECK-NEXT:    esp.vldbc.8.xp q7, a2, s1
; CHECK-NEXT:    li a2, 8
; CHECK-NEXT:    esp.vldext.s16.ip q7, q6, a2, 64
; CHECK-NEXT:    li a2, 9
; CHECK-NEXT:    esp.vldext.s16.xp q4, q4, a2, t4
; CHECK-NEXT:    li a2, 8
; CHECK-NEXT:    esp.vldext.s8.ip q3, q6, a2, -48
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    esp.vldext.s8.xp q3, q4, a2, s10
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    esp.vldext.u16.ip q0, q4, a2, 96
; CHECK-NEXT:    li a2, 5
; CHECK-NEXT:    esp.vldext.u16.xp q7, q1, a2, s0
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.vldext.u8.ip q1, q5, a2, 32
; CHECK-NEXT:    li a2, 8
; CHECK-NEXT:    esp.vldext.u8.xp q2, q5, a2, s9
; CHECK-NEXT:    li a2, 10
; CHECK-NEXT:    esp.vldhbc.16.incp q2, q4, a2
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    esp.ld.qacc.h.h.128.ip a2, -1088
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    esp.ld.qacc.h.l.128.ip a2, -1808
; CHECK-NEXT:    li a2, 11
; CHECK-NEXT:    esp.ld.qacc.l.h.128.ip a2, -1136
; CHECK-NEXT:    li a2, 12
; CHECK-NEXT:    esp.ld.qacc.l.l.128.ip a2, 624
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.ld.ua.state.ip a2, -1600
; CHECK-NEXT:    li a2, 6
; CHECK-NEXT:    esp.ldxq.32 q3, q7, t3, 1, 1
; CHECK-NEXT:    esp.st.qacc.h.h.128.ip a2, 1424
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.st.qacc.h.l.128.ip a2, 176
; CHECK-NEXT:    li a2, 1
; CHECK-NEXT:    esp.st.qacc.l.h.128.ip a2, 1152
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.st.qacc.l.l.128.ip a2, 1472
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.st.ua.state.ip a2, -160
; CHECK-NEXT:    li a2, 10
; CHECK-NEXT:    esp.stxq.32 q0, q7, a2, 2, 6
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.vld.128.ip q7, a2, -1904
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:    esp.vld.128.xp q0, a2, a4
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.vld.h.64.ip q3, a2, -88
; CHECK-NEXT:    li a2, 12
; CHECK-NEXT:    esp.vld.h.64.xp q1, a2, s8
; CHECK-NEXT:    esp.vld.l.64.ip q3, s8, -344
; CHECK-NEXT:    esp.vld.l.64.xp q6, t6, t6
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.vst.128.ip q7, a2, 1888
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    esp.vst.128.xp q2, a2, s10
; CHECK-NEXT:    li a2, 7
; CHECK-NEXT:    esp.vst.h.64.ip q5, a2, -88
; CHECK-NEXT:    li a2, 4
; CHECK-NEXT:    esp.vst.h.64.xp q6, a2, t3
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.vst.l.64.ip q3, a2, -440
; CHECK-NEXT:    esp.vst.l.64.xp q2, s0, a0
; CHECK-NEXT:    esp.slci.2q q3, q2, 12
; CHECK-NEXT:    esp.slcxxp.2q q2, q3, t3, s1
; CHECK-NEXT:    li a2, 13
; CHECK-NEXT:    esp.src.q q1, q2, q3
; CHECK-NEXT:    esp.src.q.ld.ip q6, a2, -464, q1, q3
; CHECK-NEXT:    esp.src.q.ld.xp q4, s10, a1, q3, q5
; CHECK-NEXT:    esp.src.q.qup q5, q1, q7
; CHECK-NEXT:    esp.srci.2q q3, q5, 8
; CHECK-NEXT:    esp.srcmb.s16.q.qacc q2, q4, trunc, rhtz
; CHECK-NEXT:    esp.srcmb.s16.qacc q6, s1, trunc, rdn
; CHECK-NEXT:    esp.srcmb.s8.q.qacc q7, q7, rhaz
; CHECK-NEXT:    esp.srcmb.s8.qacc q2, a4, trunc, rhaz
; CHECK-NEXT:    esp.srcmb.u16.q.qacc q2, q5, trunc, rhtz
; CHECK-NEXT:    esp.srcmb.u16.qacc q1, t4, trunc, rdn
; CHECK-NEXT:    esp.srcmb.u8.q.qacc q1, q2, trunc, raz
; CHECK-NEXT:    esp.srcmb.u8.qacc q2, a4, trunc, rne
; CHECK-NEXT:    li a1, 8
; CHECK-NEXT:    esp.srcq.128.st.incp q1, q7, a1
; CHECK-NEXT:    esp.srcxxp.2q q4, q0, s1, t4
; CHECK-NEXT:    esp.srs.s.xacc a1, a5, rtz
; CHECK-NEXT:    esp.srs.u.xacc a1, a3, trunc, rhaz
; CHECK-NEXT:    esp.vsl.s32 q3, q1, trunc
; CHECK-NEXT:    esp.vsl.u32 q7, q0, trunc
; CHECK-NEXT:    esp.vsld.16 q2, q7, q0, trunc, rne
; CHECK-NEXT:    esp.vsld.32 q1, q2, q0, rne
; CHECK-NEXT:    esp.vsld.8 q6, q6, q2, trunc, raz
; CHECK-NEXT:    esp.vsr.s32 q0, q3, rne
; CHECK-NEXT:    esp.vsr.u32 q1, q3, rup
; CHECK-NEXT:    esp.vsrd.16 q0, q2, q2, raz
; CHECK-NEXT:    esp.vsrd.32 q5, q6, q0, trunc
; CHECK-NEXT:    esp.vsrd.8 q2, q2, q0, rtz
; CHECK-NEXT:    esp.st.s.xacc.ip t5, -600
; CHECK-NEXT:    esp.st.u.xacc.ip a0, 680
; CHECK-NEXT:    lw s0, 28(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s1, 24(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s8, 20(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s9, 16(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s10, 12(sp) # 4-byte Folded Reload
; CHECK-NEXT:    lw s11, 8(sp) # 4-byte Folded Reload
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    .cfi_restore s8
; CHECK-NEXT:    .cfi_restore s9
; CHECK-NEXT:    .cfi_restore s10
; CHECK-NEXT:    .cfi_restore s11
; CHECK-NEXT:    addi sp, sp, 32
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
	%1 = tail call i32 @llvm.riscv.esp.vld.128.ip.2p2(i32 8, i32 496, i32 0)
	%2 = tail call i32 @llvm.riscv.esp.vld.128.ip.2p2(i32 %1, i32 496, i32 1)
	%3 = tail call i32 @llvm.riscv.esp.vld.128.ip.2p2(i32 %2, i32 496, i32 2)
	%4 = tail call i32 @llvm.riscv.esp.vld.128.ip.2p2(i32 %3, i32 496, i32 3)
	%5 = tail call i32 @llvm.riscv.esp.vld.128.ip.2p2(i32 %4, i32 496, i32 4)
	%6 = tail call i32 @llvm.riscv.esp.vld.128.ip.2p2(i32 %5, i32 496, i32 5)
	%7 = tail call i32 @llvm.riscv.esp.vld.128.ip.2p2(i32 %6, i32 496, i32 6)
	%8 = tail call i32 @llvm.riscv.esp.vld.128.ip.2p2(i32 %7, i32 496, i32 7)
	tail call void @llvm.riscv.esp.vcmulas.s16.qacc.h.2p2(i32 6, i32 7, i32 1)
	%9 = tail call i32 @llvm.riscv.esp.vcmulas.s16.qacc.h.ld.ip.2p2(i32 2, i32 1, i32 9, i32 0, i32 32, i32 6)
	%10 = tail call i32 @llvm.riscv.esp.vcmulas.s16.qacc.h.ld.xp.2p2(i32 11, i32 6, i32 5, i32 1, i32 0, i32 3)
	tail call void @llvm.riscv.esp.vcmulas.s16.qacc.l.2p2(i32 2, i32 3, i32 1)
	%11 = tail call i32 @llvm.riscv.esp.vcmulas.s16.qacc.l.ld.ip.2p2(i32 1, i32 2, i32 3, i32 1, i32 -64, i32 5)
	%12 = tail call i32 @llvm.riscv.esp.vcmulas.s16.qacc.l.ld.xp.2p2(i32 0, i32 3, i32 1, i32 13, i32 1, i32 2)
	tail call void @llvm.riscv.esp.vcmulas.s8.qacc.h.2p2(i32 1, i32 6, i32 0)
	%13 = tail call i32 @llvm.riscv.esp.vcmulas.s8.qacc.h.ld.ip.2p2(i32 0, i32 0, i32 2, i32 0, i32 -128, i32 0)
	%14 = tail call i32 @llvm.riscv.esp.vcmulas.s8.qacc.h.ld.xp.2p2(i32 8, i32 1, i32 0, i32 2, i32 1, i32 1)
	tail call void @llvm.riscv.esp.vcmulas.s8.qacc.l.2p2(i32 0, i32 0, i32 0)
	%15 = tail call i32 @llvm.riscv.esp.vcmulas.s8.qacc.l.ld.ip.2p2(i32 5, i32 5, i32 3, i32 0, i32 -96, i32 2)
	%16 = tail call i32 @llvm.riscv.esp.vcmulas.s8.qacc.l.ld.xp.2p2(i32 1, i32 2, i32 1, i32 10, i32 0, i32 6)
	tail call void @llvm.riscv.esp.vmulas.s16.qacc.2p2(i32 2, i32 4, i32 1)
	%17 = tail call i32 @llvm.riscv.esp.vmulas.s16.qacc.ld.ip.2p2(i32 6, i32 7, i32 11, i32 0, i32 96, i32 1)
	%18 = tail call i32 @llvm.riscv.esp.vmulas.s16.qacc.ld.xp.2p2(i32 2, i32 2, i32 7, i32 3, i32 1, i32 4)
	%19 = tail call i32 @llvm.riscv.esp.vmulas.s16.qacc.st.ip.2p2(i32 6, i32 0, i32 3, i32 1, i32 1, i32 -32)
	%20 = tail call i32 @llvm.riscv.esp.vmulas.s16.qacc.st.xp.2p2(i32 0, i32 4, i32 5, i32 2, i32 14, i32 0)
	tail call void @llvm.riscv.esp.vmulas.s16.xacc.2p2(i32 1, i32 4, i32 0)
	%21 = tail call i32 @llvm.riscv.esp.vmulas.s16.xacc.ld.ip.2p2(i32 6, i32 3, i32 6, i32 1, i32 -128, i32 0)
	%22 = tail call i32 @llvm.riscv.esp.vmulas.s16.xacc.ld.xp.2p2(i32 3, i32 2, i32 7, i32 6, i32 0, i32 1)
	%23 = tail call i32 @llvm.riscv.esp.vmulas.s16.xacc.st.ip.2p2(i32 4, i32 4, i32 3, i32 4, i32 1, i32 -80)
	%24 = tail call i32 @llvm.riscv.esp.vmulas.s16.xacc.st.xp.2p2(i32 9, i32 4, i32 1, i32 3, i32 6, i32 1)
	tail call void @llvm.riscv.esp.vmulas.s8.qacc.2p2(i32 6, i32 2, i32 0)
	%25 = tail call i32 @llvm.riscv.esp.vmulas.s8.qacc.ld.ip.2p2(i32 5, i32 3, i32 8, i32 0, i32 -80, i32 6)
	%26 = tail call i32 @llvm.riscv.esp.vmulas.s8.qacc.ld.xp.2p2(i32 3, i32 5, i32 6, i32 13, i32 0, i32 6)
	%27 = tail call i32 @llvm.riscv.esp.vmulas.s8.qacc.st.ip.2p2(i32 6, i32 2, i32 6, i32 10, i32 0, i32 64)
	%28 = tail call i32 @llvm.riscv.esp.vmulas.s8.qacc.st.xp.2p2(i32 13, i32 5, i32 2, i32 5, i32 11, i32 0)
	tail call void @llvm.riscv.esp.vmulas.s8.xacc.2p2(i32 7, i32 3, i32 1)
	%29 = tail call i32 @llvm.riscv.esp.vmulas.s8.xacc.ld.ip.2p2(i32 1, i32 4, i32 5, i32 0, i32 -64, i32 3)
	%30 = tail call i32 @llvm.riscv.esp.vmulas.s8.xacc.ld.xp.2p2(i32 6, i32 3, i32 2, i32 8, i32 0, i32 5)
	%31 = tail call i32 @llvm.riscv.esp.vmulas.s8.xacc.st.ip.2p2(i32 4, i32 1, i32 1, i32 9, i32 1, i32 64)
	%32 = tail call i32 @llvm.riscv.esp.vmulas.s8.xacc.st.xp.2p2(i32 1, i32 4, i32 0, i32 0, i32 2, i32 0)
	tail call void @llvm.riscv.esp.vmulas.u16.qacc.2p2(i32 2, i32 5, i32 1)
	%33 = tail call i32 @llvm.riscv.esp.vmulas.u16.qacc.ld.ip.2p2(i32 5, i32 7, i32 13, i32 1, i32 64, i32 0)
	%34 = tail call i32 @llvm.riscv.esp.vmulas.u16.qacc.ld.xp.2p2(i32 4, i32 6, i32 0, i32 12, i32 1, i32 6)
	%35 = tail call i32 @llvm.riscv.esp.vmulas.u16.qacc.st.ip.2p2(i32 3, i32 3, i32 1, i32 4, i32 0, i32 16)
	%36 = tail call i32 @llvm.riscv.esp.vmulas.u16.qacc.st.xp.2p2(i32 1, i32 4, i32 7, i32 6, i32 9, i32 0)
	tail call void @llvm.riscv.esp.vmulas.u16.xacc.2p2(i32 0, i32 0, i32 0)
	%37 = tail call i32 @llvm.riscv.esp.vmulas.u16.xacc.ld.ip.2p2(i32 0, i32 1, i32 14, i32 1, i32 32, i32 3)
	%38 = tail call i32 @llvm.riscv.esp.vmulas.u16.xacc.ld.xp.2p2(i32 10, i32 4, i32 1, i32 7, i32 1, i32 7)
	%39 = tail call i32 @llvm.riscv.esp.vmulas.u16.xacc.st.ip.2p2(i32 0, i32 6, i32 1, i32 6, i32 1, i32 -48)
	%40 = tail call i32 @llvm.riscv.esp.vmulas.u16.xacc.st.xp.2p2(i32 7, i32 6, i32 4, i32 3, i32 1, i32 0)
	tail call void @llvm.riscv.esp.vmulas.u8.qacc.2p2(i32 3, i32 6, i32 0)
	%41 = tail call i32 @llvm.riscv.esp.vmulas.u8.qacc.ld.ip.2p2(i32 7, i32 6, i32 8, i32 0, i32 32, i32 4)
	%42 = tail call i32 @llvm.riscv.esp.vmulas.u8.qacc.ld.xp.2p2(i32 0, i32 4, i32 1, i32 4, i32 0, i32 0)
	%43 = tail call i32 @llvm.riscv.esp.vmulas.u8.qacc.st.ip.2p2(i32 2, i32 4, i32 3, i32 8, i32 1, i32 0)
	%44 = tail call i32 @llvm.riscv.esp.vmulas.u8.qacc.st.xp.2p2(i32 1, i32 3, i32 1, i32 6, i32 1, i32 1)
	tail call void @llvm.riscv.esp.vmulas.u8.xacc.2p2(i32 3, i32 5, i32 1)
	%45 = tail call i32 @llvm.riscv.esp.vmulas.u8.xacc.ld.ip.2p2(i32 3, i32 2, i32 7, i32 1, i32 80, i32 5)
	%46 = tail call i32 @llvm.riscv.esp.vmulas.u8.xacc.ld.xp.2p2(i32 14, i32 1, i32 0, i32 7, i32 1, i32 4)
	%47 = tail call i32 @llvm.riscv.esp.vmulas.u8.xacc.st.ip.2p2(i32 6, i32 6, i32 5, i32 0, i32 0, i32 -112)
	%48 = tail call i32 @llvm.riscv.esp.vmulas.u8.xacc.st.xp.2p2(i32 14, i32 6, i32 0, i32 2, i32 11, i32 0)
	%49 = tail call i32 @llvm.riscv.esp.vmulas.s16.qacc.ldbc.incp.2p2(i32 3, i32 5, i32 5, i32 0, i32 5)
	%50 = tail call i32 @llvm.riscv.esp.vmulas.s8.qacc.ldbc.incp.2p2(i32 1, i32 6, i32 6, i32 0, i32 5)
	%51 = tail call i32 @llvm.riscv.esp.vmulas.u16.qacc.ldbc.incp.2p2(i32 6, i32 0, i32 6, i32 1, i32 1)
	%52 = tail call i32 @llvm.riscv.esp.vmulas.u8.qacc.ldbc.incp.2p2(i32 1, i32 7, i32 1, i32 0, i32 4)
	tail call void @llvm.riscv.esp.vsmulas.s16.qacc.2p2(i32 7, i32 7, i32 1, i32 13)
	%53 = tail call i32 @llvm.riscv.esp.vsmulas.s16.qacc.ld.incp.2p2(i32 5, i32 5, i32 8, i32 0, i32 1, i32 4)
	tail call void @llvm.riscv.esp.vsmulas.s8.qacc.2p2(i32 7, i32 7, i32 0, i32 2)
	%54 = tail call i32 @llvm.riscv.esp.vsmulas.s8.qacc.ld.incp.2p2(i32 7, i32 3, i32 8, i32 0, i32 10, i32 4)
	tail call void @llvm.riscv.esp.vsmulas.u16.qacc.2p2(i32 7, i32 7, i32 0, i32 6)
	%55 = tail call i32 @llvm.riscv.esp.vsmulas.u16.qacc.ld.incp.2p2(i32 2, i32 7, i32 13, i32 1, i32 14, i32 0)
	tail call void @llvm.riscv.esp.vsmulas.u8.qacc.2p2(i32 7, i32 5, i32 0, i32 10)
	%56 = tail call i32 @llvm.riscv.esp.vsmulas.u8.qacc.ld.incp.2p2(i32 5, i32 1, i32 0, i32 0, i32 11, i32 3)
	tail call void @llvm.riscv.esp.cmul.s16.2p2(i32 7, i32 3, i32 1, i32 0, i32 1, i32 2)
	%57 = tail call i32 @llvm.riscv.esp.cmul.s16.ld.incp.2p2(i32 7, i32 2, i32 2, i32 0, i32 1, i32 5, i32 1, i32 0)
	%58 = tail call i32 @llvm.riscv.esp.cmul.s16.st.incp.2p2(i32 7, i32 5, i32 3, i32 4, i32 0, i32 3, i32 2, i32 1)
	tail call void @llvm.riscv.esp.cmul.s8.2p2(i32 1, i32 4, i32 0, i32 2, i32 5, i32 4)
	%59 = tail call i32 @llvm.riscv.esp.cmul.s8.ld.incp.2p2(i32 3, i32 7, i32 2, i32 1, i32 2, i32 3, i32 6, i32 5)
	%60 = tail call i32 @llvm.riscv.esp.cmul.s8.st.incp.2p2(i32 1, i32 6, i32 1, i32 12, i32 1, i32 0, i32 0, i32 0)
	tail call void @llvm.riscv.esp.cmul.u16.2p2(i32 7, i32 2, i32 1, i32 3, i32 1, i32 6)
	%61 = tail call i32 @llvm.riscv.esp.cmul.u16.ld.incp.2p2(i32 5, i32 0, i32 13, i32 1, i32 0, i32 6, i32 6, i32 6)
	%62 = tail call i32 @llvm.riscv.esp.cmul.u16.st.incp.2p2(i32 6, i32 4, i32 5, i32 4, i32 1, i32 1, i32 2, i32 6)
	tail call void @llvm.riscv.esp.cmul.u8.2p2(i32 5, i32 1, i32 0, i32 3, i32 5, i32 2)
	%63 = tail call i32 @llvm.riscv.esp.cmul.u8.ld.incp.2p2(i32 6, i32 4, i32 8, i32 0, i32 3, i32 7, i32 6, i32 1)
	%64 = tail call i32 @llvm.riscv.esp.cmul.u8.st.incp.2p2(i32 4, i32 6, i32 2, i32 12, i32 1, i32 0, i32 0, i32 3)
	tail call void @llvm.riscv.esp.max.s16.a.2p2(i32 2, i32 7)
	tail call void @llvm.riscv.esp.max.s32.a.2p2(i32 2, i32 2)
	tail call void @llvm.riscv.esp.max.s8.a.2p2(i32 5, i32 2)
	tail call void @llvm.riscv.esp.max.u16.a.2p2(i32 1, i32 0)
	tail call void @llvm.riscv.esp.max.u32.a.2p2(i32 4, i32 13)
	tail call void @llvm.riscv.esp.max.u8.a.2p2(i32 2, i32 4)
	tail call void @llvm.riscv.esp.min.s16.a.2p2(i32 5, i32 4)
	tail call void @llvm.riscv.esp.min.s32.a.2p2(i32 7, i32 6)
	tail call void @llvm.riscv.esp.min.s8.a.2p2(i32 1, i32 13)
	tail call void @llvm.riscv.esp.min.u16.a.2p2(i32 5, i32 8)
	tail call void @llvm.riscv.esp.min.u32.a.2p2(i32 1, i32 10)
	tail call void @llvm.riscv.esp.min.u8.a.2p2(i32 1, i32 1)
	tail call void @llvm.riscv.esp.vabs.16.2p2(i32 7, i32 0)
	tail call void @llvm.riscv.esp.vabs.32.2p2(i32 1, i32 4)
	tail call void @llvm.riscv.esp.vabs.8.2p2(i32 7, i32 7)
	tail call void @llvm.riscv.esp.vadd.s16.2p2(i32 6, i32 4, i32 0, i32 2)
	%65 = tail call i32 @llvm.riscv.esp.vadd.s16.ld.incp.2p2(i32 7, i32 6, i32 5, i32 0, i32 3, i32 3)
	%66 = tail call i32 @llvm.riscv.esp.vadd.s16.st.incp.2p2(i32 6, i32 4, i32 4, i32 14, i32 1, i32 3)
	tail call void @llvm.riscv.esp.vadd.s32.2p2(i32 3, i32 7, i32 1, i32 4)
	%67 = tail call i32 @llvm.riscv.esp.vadd.s32.ld.incp.2p2(i32 6, i32 0, i32 10, i32 1, i32 2, i32 5)
	%68 = tail call i32 @llvm.riscv.esp.vadd.s32.st.incp.2p2(i32 4, i32 4, i32 6, i32 4, i32 0, i32 0)
	tail call void @llvm.riscv.esp.vadd.s8.2p2(i32 3, i32 5, i32 0, i32 3)
	%69 = tail call i32 @llvm.riscv.esp.vadd.s8.ld.incp.2p2(i32 4, i32 0, i32 4, i32 0, i32 4, i32 0)
	%70 = tail call i32 @llvm.riscv.esp.vadd.s8.st.incp.2p2(i32 1, i32 5, i32 4, i32 13, i32 0, i32 4)
	tail call void @llvm.riscv.esp.vadd.u16.2p2(i32 5, i32 6, i32 1, i32 2)
	%71 = tail call i32 @llvm.riscv.esp.vadd.u16.ld.incp.2p2(i32 7, i32 5, i32 12, i32 0, i32 5, i32 4)
	%72 = tail call i32 @llvm.riscv.esp.vadd.u16.st.incp.2p2(i32 0, i32 4, i32 1, i32 11, i32 1, i32 1)
	tail call void @llvm.riscv.esp.vadd.u32.2p2(i32 1, i32 1, i32 1, i32 5)
	%73 = tail call i32 @llvm.riscv.esp.vadd.u32.ld.incp.2p2(i32 7, i32 5, i32 8, i32 0, i32 0, i32 4)
	%74 = tail call i32 @llvm.riscv.esp.vadd.u32.st.incp.2p2(i32 4, i32 7, i32 3, i32 8, i32 0, i32 5)
	tail call void @llvm.riscv.esp.vadd.u8.2p2(i32 3, i32 2, i32 1, i32 1)
	%75 = tail call i32 @llvm.riscv.esp.vadd.u8.ld.incp.2p2(i32 4, i32 7, i32 14, i32 0, i32 6, i32 0)
	%76 = tail call i32 @llvm.riscv.esp.vadd.u8.st.incp.2p2(i32 0, i32 4, i32 5, i32 8, i32 0, i32 6)
	tail call void @llvm.riscv.esp.vclamp.s16.2p2(i32 7, i32 1, i32 2)
	tail call void @llvm.riscv.esp.vmax.s16.2p2(i32 2, i32 3, i32 2)
	%77 = tail call i32 @llvm.riscv.esp.vmax.s16.ld.incp.2p2(i32 7, i32 6, i32 14, i32 7, i32 0)
	%78 = tail call i32 @llvm.riscv.esp.vmax.s16.st.incp.2p2(i32 7, i32 2, i32 0, i32 1, i32 0)
	tail call void @llvm.riscv.esp.vmax.s32.2p2(i32 3, i32 3, i32 4)
	%79 = tail call i32 @llvm.riscv.esp.vmax.s32.ld.incp.2p2(i32 4, i32 7, i32 10, i32 4, i32 6)
	%80 = tail call i32 @llvm.riscv.esp.vmax.s32.st.incp.2p2(i32 1, i32 0, i32 4, i32 2, i32 3)
	tail call void @llvm.riscv.esp.vmax.s8.2p2(i32 4, i32 5, i32 5)
	%81 = tail call i32 @llvm.riscv.esp.vmax.s8.ld.incp.2p2(i32 2, i32 4, i32 13, i32 5, i32 6)
	%82 = tail call i32 @llvm.riscv.esp.vmax.s8.st.incp.2p2(i32 6, i32 3, i32 1, i32 13, i32 3)
	tail call void @llvm.riscv.esp.vmax.u16.2p2(i32 4, i32 6, i32 6)
	%83 = tail call i32 @llvm.riscv.esp.vmax.u16.ld.incp.2p2(i32 6, i32 4, i32 12, i32 1, i32 7)
	%84 = tail call i32 @llvm.riscv.esp.vmax.u16.st.incp.2p2(i32 4, i32 7, i32 2, i32 10, i32 7)
	tail call void @llvm.riscv.esp.vmax.u32.2p2(i32 4, i32 6, i32 0)
	%85 = tail call i32 @llvm.riscv.esp.vmax.u32.ld.incp.2p2(i32 0, i32 4, i32 13, i32 5, i32 7)
	%86 = tail call i32 @llvm.riscv.esp.vmax.u32.st.incp.2p2(i32 0, i32 4, i32 4, i32 3, i32 5)
	tail call void @llvm.riscv.esp.vmax.u8.2p2(i32 4, i32 0, i32 0)
	%87 = tail call i32 @llvm.riscv.esp.vmax.u8.ld.incp.2p2(i32 2, i32 1, i32 2, i32 2, i32 2)
	%88 = tail call i32 @llvm.riscv.esp.vmax.u8.st.incp.2p2(i32 2, i32 0, i32 0, i32 3, i32 6)
	tail call void @llvm.riscv.esp.vmin.s16.2p2(i32 3, i32 6, i32 1)
	%89 = tail call i32 @llvm.riscv.esp.vmin.s16.ld.incp.2p2(i32 7, i32 5, i32 2, i32 5, i32 4)
	%90 = tail call i32 @llvm.riscv.esp.vmin.s16.st.incp.2p2(i32 5, i32 7, i32 6, i32 13, i32 7)
	tail call void @llvm.riscv.esp.vmin.s32.2p2(i32 7, i32 2, i32 0)
	%91 = tail call i32 @llvm.riscv.esp.vmin.s32.ld.incp.2p2(i32 3, i32 6, i32 4, i32 4, i32 4)
	%92 = tail call i32 @llvm.riscv.esp.vmin.s32.st.incp.2p2(i32 2, i32 5, i32 6, i32 3, i32 3)
	tail call void @llvm.riscv.esp.vmin.s8.2p2(i32 0, i32 7, i32 0)
	%93 = tail call i32 @llvm.riscv.esp.vmin.s8.ld.incp.2p2(i32 4, i32 3, i32 7, i32 5, i32 3)
	%94 = tail call i32 @llvm.riscv.esp.vmin.s8.st.incp.2p2(i32 1, i32 3, i32 2, i32 14, i32 3)
	tail call void @llvm.riscv.esp.vmin.u16.2p2(i32 4, i32 6, i32 1)
	%95 = tail call i32 @llvm.riscv.esp.vmin.u16.ld.incp.2p2(i32 5, i32 0, i32 7, i32 5, i32 6)
	%96 = tail call i32 @llvm.riscv.esp.vmin.u16.st.incp.2p2(i32 0, i32 5, i32 3, i32 11, i32 6)
	tail call void @llvm.riscv.esp.vmin.u32.2p2(i32 1, i32 0, i32 6)
	%97 = tail call i32 @llvm.riscv.esp.vmin.u32.ld.incp.2p2(i32 0, i32 5, i32 8, i32 5, i32 4)
	%98 = tail call i32 @llvm.riscv.esp.vmin.u32.st.incp.2p2(i32 3, i32 0, i32 0, i32 12, i32 1)
	tail call void @llvm.riscv.esp.vmin.u8.2p2(i32 4, i32 4, i32 7)
	%99 = tail call i32 @llvm.riscv.esp.vmin.u8.ld.incp.2p2(i32 2, i32 5, i32 6, i32 5, i32 3)
	%100 = tail call i32 @llvm.riscv.esp.vmin.u8.st.incp.2p2(i32 2, i32 4, i32 3, i32 1, i32 1)
	tail call void @llvm.riscv.esp.vmul.s16.2p2(i32 7, i32 7, i32 1, i32 6, i32 4)
	%101 = tail call i32 @llvm.riscv.esp.vmul.s16.ld.incp.2p2(i32 1, i32 5, i32 8, i32 0, i32 4, i32 7, i32 0)
	tail call void @llvm.riscv.esp.vmul.s16.s8xs8.2p2(i32 2, i32 1, i32 7, i32 1, i32 2)
	%102 = tail call i32 @llvm.riscv.esp.vmul.s16.st.incp.2p2(i32 6, i32 5, i32 3, i32 0, i32 0, i32 2, i32 7)
	tail call void @llvm.riscv.esp.vmul.s32.s16xs16.2p2(i32 3, i32 0, i32 4, i32 1, i32 2)
	tail call void @llvm.riscv.esp.vmul.s8.2p2(i32 3, i32 5, i32 0, i32 2, i32 5)
	%103 = tail call i32 @llvm.riscv.esp.vmul.s8.ld.incp.2p2(i32 3, i32 6, i32 0, i32 0, i32 3, i32 3, i32 3)
	%104 = tail call i32 @llvm.riscv.esp.vmul.s8.st.incp.2p2(i32 1, i32 1, i32 6, i32 6, i32 1, i32 6, i32 5)
	tail call void @llvm.riscv.esp.vmul.u16.2p2(i32 4, i32 4, i32 1, i32 1, i32 7)
	%105 = tail call i32 @llvm.riscv.esp.vmul.u16.ld.incp.2p2(i32 4, i32 0, i32 5, i32 0, i32 6, i32 5, i32 4)
	%106 = tail call i32 @llvm.riscv.esp.vmul.u16.st.incp.2p2(i32 1, i32 4, i32 3, i32 13, i32 1, i32 2, i32 3)
	tail call void @llvm.riscv.esp.vmul.u8.2p2(i32 7, i32 4, i32 1, i32 1, i32 7)
	%107 = tail call i32 @llvm.riscv.esp.vmul.u8.ld.incp.2p2(i32 5, i32 0, i32 2, i32 0, i32 0, i32 4, i32 2)
	%108 = tail call i32 @llvm.riscv.esp.vmul.u8.st.incp.2p2(i32 1, i32 6, i32 7, i32 0, i32 0, i32 6, i32 6)
	tail call void @llvm.riscv.esp.vprelu.s16.2p2(i32 10, i32 4, i32 6, i32 0, i32 3, i32 1)
	tail call void @llvm.riscv.esp.vprelu.s8.2p2(i32 7, i32 6, i32 2, i32 1, i32 2, i32 7)
	tail call void @llvm.riscv.esp.vrelu.s16.2p2(i32 7, i32 6, i32 6, i32 0, i32 5)
	tail call void @llvm.riscv.esp.vrelu.s8.2p2(i32 4, i32 0, i32 0, i32 1, i32 1)
	tail call void @llvm.riscv.esp.vsadds.s16.2p2(i32 5, i32 3, i32 1, i32 5)
	tail call void @llvm.riscv.esp.vsadds.s8.2p2(i32 9, i32 1, i32 1, i32 1)
	tail call void @llvm.riscv.esp.vsadds.u16.2p2(i32 11, i32 0, i32 0, i32 5)
	tail call void @llvm.riscv.esp.vsadds.u8.2p2(i32 8, i32 3, i32 0, i32 7)
	tail call void @llvm.riscv.esp.vsat.s16.2p2(i32 10, i32 10, i32 3, i32 7)
	tail call void @llvm.riscv.esp.vsat.s32.2p2(i32 11, i32 0, i32 7, i32 5)
	tail call void @llvm.riscv.esp.vsat.s8.2p2(i32 7, i32 7, i32 6, i32 1)
	tail call void @llvm.riscv.esp.vsat.u16.2p2(i32 1, i32 6, i32 7, i32 3)
	tail call void @llvm.riscv.esp.vsat.u32.2p2(i32 13, i32 11, i32 6, i32 0)
	tail call void @llvm.riscv.esp.vsat.u8.2p2(i32 1, i32 3, i32 6, i32 1)
	tail call void @llvm.riscv.esp.vssubs.s16.2p2(i32 4, i32 3, i32 0, i32 1)
	tail call void @llvm.riscv.esp.vssubs.s8.2p2(i32 0, i32 3, i32 1, i32 5)
	tail call void @llvm.riscv.esp.vssubs.u16.2p2(i32 3, i32 3, i32 1, i32 7)
	tail call void @llvm.riscv.esp.vssubs.u8.2p2(i32 10, i32 2, i32 1, i32 6)
	tail call void @llvm.riscv.esp.vsub.s16.2p2(i32 1, i32 1, i32 1, i32 2)
	%109 = tail call i32 @llvm.riscv.esp.vsub.s16.ld.incp.2p2(i32 0, i32 7, i32 6, i32 1, i32 5, i32 6)
	%110 = tail call i32 @llvm.riscv.esp.vsub.s16.st.incp.2p2(i32 0, i32 6, i32 6, i32 11, i32 1, i32 2)
	tail call void @llvm.riscv.esp.vsub.s32.2p2(i32 1, i32 6, i32 1, i32 4)
	%111 = tail call i32 @llvm.riscv.esp.vsub.s32.ld.incp.2p2(i32 1, i32 7, i32 1, i32 0, i32 7, i32 0)
	%112 = tail call i32 @llvm.riscv.esp.vsub.s32.st.incp.2p2(i32 6, i32 3, i32 5, i32 14, i32 0, i32 5)
	tail call void @llvm.riscv.esp.vsub.s8.2p2(i32 5, i32 4, i32 0, i32 0)
	%113 = tail call i32 @llvm.riscv.esp.vsub.s8.ld.incp.2p2(i32 7, i32 2, i32 3, i32 1, i32 2, i32 2)
	%114 = tail call i32 @llvm.riscv.esp.vsub.s8.st.incp.2p2(i32 7, i32 1, i32 2, i32 1, i32 1, i32 1)
	tail call void @llvm.riscv.esp.vsub.u16.2p2(i32 6, i32 4, i32 0, i32 7)
	%115 = tail call i32 @llvm.riscv.esp.vsub.u16.ld.incp.2p2(i32 5, i32 1, i32 3, i32 0, i32 0, i32 2)
	%116 = tail call i32 @llvm.riscv.esp.vsub.u16.st.incp.2p2(i32 7, i32 3, i32 3, i32 11, i32 1, i32 2)
	tail call void @llvm.riscv.esp.vsub.u32.2p2(i32 3, i32 3, i32 0, i32 2)
	%117 = tail call i32 @llvm.riscv.esp.vsub.u32.ld.incp.2p2(i32 4, i32 2, i32 1, i32 0, i32 4, i32 2)
	%118 = tail call i32 @llvm.riscv.esp.vsub.u32.st.incp.2p2(i32 7, i32 2, i32 7, i32 2, i32 0, i32 3)
	tail call void @llvm.riscv.esp.vsub.u8.2p2(i32 4, i32 7, i32 0, i32 4)
	%119 = tail call i32 @llvm.riscv.esp.vsub.u8.ld.incp.2p2(i32 2, i32 7, i32 7, i32 1, i32 7, i32 0)
	%120 = tail call i32 @llvm.riscv.esp.vsub.u8.st.incp.2p2(i32 6, i32 0, i32 7, i32 2, i32 1, i32 6)
	tail call void @llvm.riscv.esp.addx2.2p2(i32 7, i32 4, i32 2)
	tail call void @llvm.riscv.esp.addx4.2p2(i32 4, i32 13, i32 14)
	%121 = tail call i32 @llvm.riscv.esp.sat.2p2(i32 11, i32 0, i32 13)
	tail call void @llvm.riscv.esp.subx2.2p2(i32 2, i32 3, i32 13)
	tail call void @llvm.riscv.esp.subx4.2p2(i32 5, i32 6, i32 14)
	tail call void @llvm.riscv.esp.vcmp.eq.s16.2p2(i32 5, i32 2, i32 5)
	tail call void @llvm.riscv.esp.vcmp.eq.s32.2p2(i32 0, i32 1, i32 3)
	tail call void @llvm.riscv.esp.vcmp.eq.s8.2p2(i32 3, i32 2, i32 7)
	tail call void @llvm.riscv.esp.vcmp.eq.u16.2p2(i32 4, i32 1, i32 1)
	tail call void @llvm.riscv.esp.vcmp.eq.u32.2p2(i32 6, i32 1, i32 3)
	tail call void @llvm.riscv.esp.vcmp.eq.u8.2p2(i32 0, i32 3, i32 4)
	tail call void @llvm.riscv.esp.vcmp.gt.s16.2p2(i32 2, i32 1, i32 6)
	tail call void @llvm.riscv.esp.vcmp.gt.s32.2p2(i32 0, i32 6, i32 5)
	tail call void @llvm.riscv.esp.vcmp.gt.s8.2p2(i32 7, i32 2, i32 1)
	tail call void @llvm.riscv.esp.vcmp.gt.u16.2p2(i32 6, i32 3, i32 2)
	tail call void @llvm.riscv.esp.vcmp.gt.u32.2p2(i32 4, i32 6, i32 3)
	tail call void @llvm.riscv.esp.vcmp.gt.u8.2p2(i32 3, i32 2, i32 1)
	tail call void @llvm.riscv.esp.vcmp.lt.s16.2p2(i32 2, i32 7, i32 4)
	tail call void @llvm.riscv.esp.vcmp.lt.s32.2p2(i32 1, i32 3, i32 3)
	tail call void @llvm.riscv.esp.vcmp.lt.s8.2p2(i32 7, i32 7, i32 0)
	tail call void @llvm.riscv.esp.vcmp.lt.u16.2p2(i32 5, i32 0, i32 2)
	tail call void @llvm.riscv.esp.vcmp.lt.u32.2p2(i32 6, i32 4, i32 0)
	tail call void @llvm.riscv.esp.vcmp.lt.u8.2p2(i32 1, i32 2, i32 7)
	tail call void @llvm.riscv.esp.mov.s16.qacc.2p2(i32 3)
	tail call void @llvm.riscv.esp.mov.s8.qacc.2p2(i32 7)
	tail call void @llvm.riscv.esp.mov.u16.qacc.2p2(i32 6)
	tail call void @llvm.riscv.esp.mov.u8.qacc.2p2(i32 7)
	tail call void @llvm.riscv.esp.movi.16.a.2p2(i32 1, i32 6, i32 9)
	tail call void @llvm.riscv.esp.movi.16.q.2p2(i32 11, i32 0, i32 5)
	tail call void @llvm.riscv.esp.movi.32.a.2p2(i32 5, i32 0, i32 2)
	tail call void @llvm.riscv.esp.movi.32.q.2p2(i32 0, i32 3, i32 3)
	tail call void @llvm.riscv.esp.movi.8.a.2p2(i32 1, i32 4, i32 6)
	tail call void @llvm.riscv.esp.movi.8.q.2p2(i32 6, i32 10, i32 3)
	tail call void @llvm.riscv.esp.movx.r.cfg.2p2(i32 14)
	tail call void @llvm.riscv.esp.movx.r.fft.bit.width.2p2(i32 10)
	tail call void @llvm.riscv.esp.movx.r.perf.2p2(i32 8, i32 6)
	tail call void @llvm.riscv.esp.movx.r.sar.2p2(i32 4)
	tail call void @llvm.riscv.esp.movx.r.sar.bytes.2p2(i32 11)
	tail call void @llvm.riscv.esp.movx.r.xacc.h.2p2(i32 2)
	tail call void @llvm.riscv.esp.movx.r.xacc.l.2p2(i32 3)
	tail call void @llvm.riscv.esp.movx.w.cfg.2p2(i32 3)
	tail call void @llvm.riscv.esp.movx.w.fft.bit.width.2p2(i32 14)
	tail call void @llvm.riscv.esp.movx.w.perf.2p2(i32 2)
	tail call void @llvm.riscv.esp.movx.w.sar.2p2(i32 5)
	tail call void @llvm.riscv.esp.movx.w.sar.bytes.2p2(i32 0)
	tail call void @llvm.riscv.esp.movx.w.xacc.h.2p2(i32 5)
	tail call void @llvm.riscv.esp.movx.w.xacc.l.2p2(i32 14)
	tail call void @llvm.riscv.esp.vext.s16.2p2(i32 6, i32 2, i32 0)
	tail call void @llvm.riscv.esp.vext.s8.2p2(i32 7, i32 2, i32 5)
	tail call void @llvm.riscv.esp.vext.u16.2p2(i32 3, i32 0, i32 2)
	tail call void @llvm.riscv.esp.vext.u8.2p2(i32 4, i32 1, i32 4)
	tail call void @llvm.riscv.esp.vunzip.16.2p2(i32 6, i32 5)
	tail call void @llvm.riscv.esp.vunzip.32.2p2(i32 2, i32 5)
	tail call void @llvm.riscv.esp.vunzip.8.2p2(i32 5, i32 2)
	tail call void @llvm.riscv.esp.vunzipt.16.2p2(i32 7, i32 0, i32 1)
	tail call void @llvm.riscv.esp.vunzipt.8.2p2(i32 5, i32 3, i32 0)
	tail call void @llvm.riscv.esp.vzip.16.2p2(i32 6, i32 0)
	tail call void @llvm.riscv.esp.vzip.32.2p2(i32 7, i32 3)
	tail call void @llvm.riscv.esp.vzip.8.2p2(i32 6, i32 1)
	tail call void @llvm.riscv.esp.vzipt.16.2p2(i32 2, i32 6, i32 4)
	tail call void @llvm.riscv.esp.vzipt.8.2p2(i32 6, i32 0, i32 4)
	tail call void @llvm.riscv.esp.zero.q.2p2(i32 1)
	tail call void @llvm.riscv.esp.zero.qacc.2p2()
	tail call void @llvm.riscv.esp.zero.xacc.2p2()
	%122 = tail call i32 @llvm.riscv.esp.fft.ams.s16.ld.incp.2p2(i32 4, i32 6, i32 2, i32 5, i32 1, i32 1, i32 2, i32 7, i32 1)
	%123 = tail call i32 @llvm.riscv.esp.fft.ams.s16.ld.incp.uaup.2p2(i32 1, i32 5, i32 5, i32 8, i32 1, i32 0, i32 0, i32 7, i32 4)
	%124 = tail call i32 @llvm.riscv.esp.fft.ams.s16.ld.r32.decp.2p2(i32 6, i32 3, i32 1, i32 2, i32 1, i32 1, i32 0, i32 3, i32 1)
	tail call void @llvm.riscv.esp.fft.ams.s16.st.incp.2p2(i32 4, i32 3, i32 5, i32 4, i32 6, i32 6, i32 1, i32 0, i32 3)
	%125 = tail call i32 @llvm.riscv.esp.fft.bitrev.2p2(i32 3, i32 2)
	%126 = tail call i32 @llvm.riscv.esp.fft.cmul.s16.ld.xp.2p2(i32 6, i32 3, i32 6, i32 6, i32 0, i32 4, i32 1, i32 6)
	%127 = tail call i32 @llvm.riscv.esp.fft.cmul.s16.st.xp.2p2(i32 13, i32 2, i32 5, i32 5, i32 14, i32 0, i32 3, i32 2, i32 6)
	tail call void @llvm.riscv.esp.fft.r2bf.s16.2p2(i32 3, i32 4, i32 1, i32 1, i32 3, i32 2)
	%128 = tail call i32 @llvm.riscv.esp.fft.r2bf.s16.st.incp.2p2(i32 4, i32 6, i32 5, i32 0, i32 0, i32 7)
	%129 = tail call i32 @llvm.riscv.esp.fft.vst.r32.decp.2p2(i32 1, i32 7, i32 1)
	%130 = tail call i32 @llvm.riscv.esp.ld.128.usar.ip.2p2(i32 14, i32 -576, i32 4)
	%131 = tail call i32 @llvm.riscv.esp.ld.128.usar.xp.2p2(i32 5, i32 4, i32 1)
	%132 = tail call i32 @llvm.riscv.esp.ld.xacc.ip.2p2(i32 8, i32 -768)
	%133 = tail call i32 @llvm.riscv.esp.ldqa.s16.128.ip.2p2(i32 7, i32 1280)
	%134 = tail call i32 @llvm.riscv.esp.ldqa.s16.128.xp.2p2(i32 3, i32 2)
	%135 = tail call i32 @llvm.riscv.esp.ldqa.s8.128.ip.2p2(i32 2, i32 -384)
	%136 = tail call i32 @llvm.riscv.esp.ldqa.s8.128.xp.2p2(i32 12, i32 10)
	%137 = tail call i32 @llvm.riscv.esp.ldqa.u16.128.ip.2p2(i32 5, i32 -1856)
	%138 = tail call i32 @llvm.riscv.esp.ldqa.u16.128.xp.2p2(i32 7, i32 8)
	%139 = tail call i32 @llvm.riscv.esp.ldqa.u8.128.ip.2p2(i32 4, i32 448)
	%140 = tail call i32 @llvm.riscv.esp.ldqa.u8.128.xp.2p2(i32 14, i32 1)
	%141 = tail call i32 @llvm.riscv.esp.vldbc.16.ip.2p2(i32 13, i32 200, i32 6)
	%142 = tail call i32 @llvm.riscv.esp.vldbc.16.xp.2p2(i32 1, i32 13, i32 2)
	%143 = tail call i32 @llvm.riscv.esp.vldbc.32.ip.2p2(i32 13, i32 -332, i32 7)
	%144 = tail call i32 @llvm.riscv.esp.vldbc.32.xp.2p2(i32 12, i32 2, i32 5)
	%145 = tail call i32 @llvm.riscv.esp.vldbc.8.ip.2p2(i32 11, i32 -80, i32 7)
	%146 = tail call i32 @llvm.riscv.esp.vldbc.8.xp.2p2(i32 9, i32 5, i32 7)
	%147 = tail call i32 @llvm.riscv.esp.vldext.s16.ip.2p2(i32 8, i32 64, i32 7, i32 6)
	%148 = tail call i32 @llvm.riscv.esp.vldext.s16.xp.2p2(i32 13, i32 9, i32 4, i32 4)
	%149 = tail call i32 @llvm.riscv.esp.vldext.s8.ip.2p2(i32 8, i32 -48, i32 3, i32 6)
	%150 = tail call i32 @llvm.riscv.esp.vldext.s8.xp.2p2(i32 12, i32 1, i32 3, i32 4)
	%151 = tail call i32 @llvm.riscv.esp.vldext.u16.ip.2p2(i32 1, i32 96, i32 0, i32 4)
	%152 = tail call i32 @llvm.riscv.esp.vldext.u16.xp.2p2(i32 7, i32 5, i32 7, i32 1)
	%153 = tail call i32 @llvm.riscv.esp.vldext.u8.ip.2p2(i32 13, i32 32, i32 1, i32 5)
	%154 = tail call i32 @llvm.riscv.esp.vldext.u8.xp.2p2(i32 5, i32 8, i32 2, i32 5)
	%155 = tail call i32 @llvm.riscv.esp.vldhbc.16.incp.2p2(i32 10, i32 2, i32 4)
	%156 = tail call i32 @llvm.riscv.esp.ld.qacc.h.h.128.ip.2p2(i32 3, i32 -1088)
	%157 = tail call i32 @llvm.riscv.esp.ld.qacc.h.l.128.ip.2p2(i32 1, i32 -1808)
	%158 = tail call i32 @llvm.riscv.esp.ld.qacc.l.h.128.ip.2p2(i32 11, i32 -1136)
	%159 = tail call i32 @llvm.riscv.esp.ld.qacc.l.l.128.ip.2p2(i32 12, i32 624)
	%160 = tail call i32 @llvm.riscv.esp.ld.ua.state.ip.2p2(i32 2, i32 -1600)
	tail call void @llvm.riscv.esp.ldxq.32.2p2(i32 3, i32 7, i32 1, i32 1, i32 3)
	%161 = tail call i32 @llvm.riscv.esp.st.qacc.h.h.128.ip.2p2(i32 6, i32 1424)
	%162 = tail call i32 @llvm.riscv.esp.st.qacc.h.l.128.ip.2p2(i32 13, i32 176)
	%163 = tail call i32 @llvm.riscv.esp.st.qacc.l.h.128.ip.2p2(i32 1, i32 1152)
	%164 = tail call i32 @llvm.riscv.esp.st.qacc.l.l.128.ip.2p2(i32 2, i32 1472)
	%165 = tail call i32 @llvm.riscv.esp.st.ua.state.ip.2p2(i32 13, i32 -160)
	tail call void @llvm.riscv.esp.stxq.32.2p2(i32 10, i32 7, i32 0, i32 2, i32 6)
	%166 = tail call i32 @llvm.riscv.esp.vld.128.ip.2p2(i32 13, i32 -1904, i32 7)
	%167 = tail call i32 @llvm.riscv.esp.vld.128.xp.2p2(i32 1, i32 0, i32 0)
	%168 = tail call i32 @llvm.riscv.esp.vld.h.64.ip.2p2(i32 2, i32 -88, i32 3)
	%169 = tail call i32 @llvm.riscv.esp.vld.h.64.xp.2p2(i32 14, i32 12, i32 1)
	%170 = tail call i32 @llvm.riscv.esp.vld.l.64.ip.2p2(i32 14, i32 -344, i32 3)
	%171 = tail call i32 @llvm.riscv.esp.vld.l.64.xp.2p2(i32 6, i32 6, i32 6)
	%172 = tail call i32 @llvm.riscv.esp.vst.128.ip.2p2(i32 7, i32 13, i32 1888)
	%173 = tail call i32 @llvm.riscv.esp.vst.128.xp.2p2(i32 12, i32 2, i32 2)
	%174 = tail call i32 @llvm.riscv.esp.vst.h.64.ip.2p2(i32 5, i32 7, i32 -88)
	%175 = tail call i32 @llvm.riscv.esp.vst.h.64.xp.2p2(i32 3, i32 6, i32 4)
	%176 = tail call i32 @llvm.riscv.esp.vst.l.64.ip.2p2(i32 3, i32 13, i32 -440)
	%177 = tail call i32 @llvm.riscv.esp.vst.l.64.xp.2p2(i32 0, i32 2, i32 7)
	tail call void @llvm.riscv.esp.slci.2q.2p2(i32 3, i32 2, i32 12)
	tail call void @llvm.riscv.esp.slcxxp.2q.2p2(i32 3, i32 9, i32 2, i32 3)
	tail call void @llvm.riscv.esp.src.q.2p2(i32 3, i32 2, i32 1)
	%178 = tail call i32 @llvm.riscv.esp.src.q.ld.ip.2p2(i32 3, i32 13, i32 1, i32 -464, i32 6)
	%179 = tail call i32 @llvm.riscv.esp.src.q.ld.xp.2p2(i32 11, i32 5, i32 12, i32 3, i32 4)
	tail call void @llvm.riscv.esp.src.q.qup.2p2(i32 7, i32 1, i32 5)
	tail call void @llvm.riscv.esp.srci.2q.2p2(i32 3, i32 5, i32 8)
	tail call void @llvm.riscv.esp.srcmb.s16.q.qacc.2p2(i32 4, i32 0, i32 5, i32 2)
	tail call void @llvm.riscv.esp.srcmb.s16.qacc.2p2(i32 9, i32 0, i32 0, i32 6)
	tail call void @llvm.riscv.esp.srcmb.s8.q.qacc.2p2(i32 7, i32 1, i32 4, i32 7)
	tail call void @llvm.riscv.esp.srcmb.s8.qacc.2p2(i32 1, i32 0, i32 4, i32 2)
	tail call void @llvm.riscv.esp.srcmb.u16.q.qacc.2p2(i32 5, i32 0, i32 5, i32 2)
	tail call void @llvm.riscv.esp.srcmb.u16.qacc.2p2(i32 13, i32 0, i32 0, i32 1)
	tail call void @llvm.riscv.esp.srcmb.u8.q.qacc.2p2(i32 2, i32 0, i32 2, i32 1)
	tail call void @llvm.riscv.esp.srcmb.u8.qacc.2p2(i32 1, i32 0, i32 6, i32 2)
	%180 = tail call i32 @llvm.riscv.esp.srcq.128.st.incp.2p2(i32 7, i32 1, i32 8)
	tail call void @llvm.riscv.esp.srcxxp.2q.2p2(i32 9, i32 13, i32 4, i32 0)
	tail call void @llvm.riscv.esp.srs.s.xacc.2p2(i32 8, i32 1, i32 3, i32 14)
	tail call void @llvm.riscv.esp.srs.u.xacc.2p2(i32 2, i32 0, i32 4, i32 13)
	tail call void @llvm.riscv.esp.vsl.s32.2p2(i32 1, i32 0, i32 3)
	tail call void @llvm.riscv.esp.vsl.u32.2p2(i32 0, i32 0, i32 7)
	tail call void @llvm.riscv.esp.vsld.16.2p2(i32 7, i32 0, i32 0, i32 6, i32 2)
	tail call void @llvm.riscv.esp.vsld.32.2p2(i32 2, i32 0, i32 1, i32 6, i32 1)
	tail call void @llvm.riscv.esp.vsld.8.2p2(i32 6, i32 2, i32 0, i32 2, i32 6)
	tail call void @llvm.riscv.esp.vsr.s32.2p2(i32 3, i32 6, i32 0)
	tail call void @llvm.riscv.esp.vsr.u32.2p2(i32 3, i32 1, i32 1)
	tail call void @llvm.riscv.esp.vsrd.16.2p2(i32 2, i32 2, i32 1, i32 2, i32 0)
	tail call void @llvm.riscv.esp.vsrd.32.2p2(i32 6, i32 0, i32 0, i32 7, i32 5)
	tail call void @llvm.riscv.esp.vsrd.8.2p2(i32 2, i32 0, i32 1, i32 3, i32 2)
	%181 = tail call i32 @llvm.riscv.esp.st.s.xacc.ip.2p2(i32 4, i32 -600)
	%182 = tail call i32 @llvm.riscv.esp.st.u.xacc.ip.2p2(i32 0, i32 680)
	ret void
}

declare void @llvm.riscv.esp.vcmulas.s16.qacc.h.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vcmulas.s16.qacc.h.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vcmulas.s16.qacc.h.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmulas.s16.qacc.l.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vcmulas.s16.qacc.l.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vcmulas.s16.qacc.l.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmulas.s8.qacc.h.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vcmulas.s8.qacc.h.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vcmulas.s8.qacc.h.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmulas.s8.qacc.l.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vcmulas.s8.qacc.l.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vcmulas.s8.qacc.l.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmulas.s16.qacc.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s16.qacc.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s16.qacc.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s16.qacc.st.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s16.qacc.st.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmulas.s16.xacc.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s16.xacc.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s16.xacc.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s16.xacc.st.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s16.xacc.st.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmulas.s8.qacc.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s8.qacc.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s8.qacc.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s8.qacc.st.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s8.qacc.st.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmulas.s8.xacc.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s8.xacc.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s8.xacc.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s8.xacc.st.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s8.xacc.st.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmulas.u16.qacc.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u16.qacc.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u16.qacc.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u16.qacc.st.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u16.qacc.st.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmulas.u16.xacc.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u16.xacc.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u16.xacc.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u16.xacc.st.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u16.xacc.st.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmulas.u8.qacc.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u8.qacc.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u8.qacc.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u8.qacc.st.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u8.qacc.st.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmulas.u8.xacc.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u8.xacc.ld.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u8.xacc.ld.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u8.xacc.st.ip.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u8.xacc.st.xp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s16.qacc.ldbc.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.s8.qacc.ldbc.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u16.qacc.ldbc.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmulas.u8.qacc.ldbc.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsmulas.s16.qacc.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsmulas.s16.qacc.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsmulas.s8.qacc.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsmulas.s8.qacc.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsmulas.u16.qacc.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsmulas.u16.qacc.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsmulas.u8.qacc.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsmulas.u8.qacc.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.cmul.s16.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.cmul.s16.ld.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.cmul.s16.st.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.cmul.s8.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.cmul.s8.ld.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.cmul.s8.st.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.cmul.u16.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.cmul.u16.ld.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.cmul.u16.st.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.cmul.u8.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.cmul.u8.ld.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.cmul.u8.st.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.max.s16.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.max.s32.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.max.s8.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.max.u16.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.max.u32.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.max.u8.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.min.s16.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.min.s32.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.min.s8.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.min.u16.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.min.u32.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.min.u8.a.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vabs.16.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vabs.32.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vabs.8.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vadd.s16.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.s16.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.s16.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vadd.s32.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.s32.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.s32.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vadd.s8.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.s8.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.s8.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vadd.u16.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.u16.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.u16.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vadd.u32.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.u32.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.u32.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vadd.u8.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.u8.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vadd.u8.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vclamp.s16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmax.s16.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.s16.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.s16.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmax.s32.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.s32.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.s32.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmax.s8.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.s8.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.s8.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmax.u16.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.u16.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.u16.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmax.u32.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.u32.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.u32.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmax.u8.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.u8.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmax.u8.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmin.s16.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.s16.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.s16.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmin.s32.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.s32.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.s32.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmin.s8.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.s8.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.s8.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmin.u16.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.u16.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.u16.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmin.u32.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.u32.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.u32.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmin.u8.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.u8.ld.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmin.u8.st.incp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmul.s16.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmul.s16.ld.incp.2p2(i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmul.s16.s8xs8.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmul.s16.st.incp.2p2(i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmul.s32.s16xs16.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmul.s8.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmul.s8.ld.incp.2p2(i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmul.s8.st.incp.2p2(i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmul.u16.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmul.u16.ld.incp.2p2(i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmul.u16.st.incp.2p2(i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vmul.u8.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmul.u8.ld.incp.2p2(i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vmul.u8.st.incp.2p2(i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vprelu.s16.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vprelu.s8.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vrelu.s16.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vrelu.s8.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsadds.s16.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsadds.s8.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsadds.u16.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsadds.u8.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsat.s16.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsat.s32.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsat.s8.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsat.u16.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsat.u32.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsat.u8.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vssubs.s16.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vssubs.s8.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vssubs.u16.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vssubs.u8.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsub.s16.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.s16.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.s16.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsub.s32.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.s32.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.s32.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsub.s8.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.s8.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.s8.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsub.u16.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.u16.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.u16.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsub.u32.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.u32.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.u32.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsub.u8.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.u8.ld.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vsub.u8.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.addx2.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.addx4.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.sat.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.subx2.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.subx4.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.eq.s16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.eq.s32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.eq.s8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.eq.u16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.eq.u32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.eq.u8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.gt.s16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.gt.s32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.gt.s8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.gt.u16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.gt.u32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.gt.u8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.lt.s16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.lt.s32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.lt.s8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.lt.u16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.lt.u32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vcmp.lt.u8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.mov.s16.qacc.2p2(i32) nounwind
declare void @llvm.riscv.esp.mov.s8.qacc.2p2(i32) nounwind
declare void @llvm.riscv.esp.mov.u16.qacc.2p2(i32) nounwind
declare void @llvm.riscv.esp.mov.u8.qacc.2p2(i32) nounwind
declare void @llvm.riscv.esp.movi.16.a.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.movi.16.q.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.movi.32.a.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.movi.32.q.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.movi.8.a.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.movi.8.q.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.movx.r.cfg.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.r.fft.bit.width.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.r.perf.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.movx.r.sar.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.r.sar.bytes.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.r.xacc.h.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.r.xacc.l.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.w.cfg.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.w.fft.bit.width.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.w.perf.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.w.sar.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.w.sar.bytes.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.w.xacc.h.2p2(i32) nounwind
declare void @llvm.riscv.esp.movx.w.xacc.l.2p2(i32) nounwind
declare void @llvm.riscv.esp.vext.s16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vext.s8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vext.u16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vext.u8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vunzip.16.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vunzip.32.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vunzip.8.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vunzipt.16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vunzipt.8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vzip.16.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vzip.32.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vzip.8.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.vzipt.16.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vzipt.8.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.zero.q.2p2(i32) nounwind
declare void @llvm.riscv.esp.zero.qacc.2p2() nounwind
declare void @llvm.riscv.esp.zero.xacc.2p2() nounwind
declare i32 @llvm.riscv.esp.fft.ams.s16.ld.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.fft.ams.s16.ld.incp.uaup.2p2(i32, i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.fft.ams.s16.ld.r32.decp.2p2(i32, i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.fft.ams.s16.st.incp.2p2(i32, i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.fft.bitrev.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.fft.cmul.s16.ld.xp.2p2(i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.fft.cmul.s16.st.xp.2p2(i32, i32, i32, i32, i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.fft.r2bf.s16.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.fft.r2bf.s16.st.incp.2p2(i32, i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.fft.vst.r32.decp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.ld.128.usar.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.ld.128.usar.xp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.ld.xacc.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ldqa.s16.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ldqa.s16.128.xp.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ldqa.s8.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ldqa.s8.128.xp.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ldqa.u16.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ldqa.u16.128.xp.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ldqa.u8.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ldqa.u8.128.xp.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldbc.16.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldbc.16.xp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldbc.32.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldbc.32.xp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldbc.8.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldbc.8.xp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldext.s16.ip.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldext.s16.xp.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldext.s8.ip.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldext.s8.xp.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldext.u16.ip.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldext.u16.xp.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldext.u8.ip.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldext.u8.xp.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vldhbc.16.incp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.ld.qacc.h.h.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ld.qacc.h.l.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ld.qacc.l.h.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ld.qacc.l.l.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.ld.ua.state.ip.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.ldxq.32.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.st.qacc.h.h.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.st.qacc.h.l.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.st.qacc.l.h.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.st.qacc.l.l.128.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.st.ua.state.ip.2p2(i32, i32) nounwind
declare void @llvm.riscv.esp.stxq.32.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vld.128.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vld.128.xp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vld.h.64.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vld.h.64.xp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vld.l.64.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vld.l.64.xp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vst.128.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vst.128.xp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vst.h.64.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vst.h.64.xp.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vst.l.64.ip.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.vst.l.64.xp.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.slci.2q.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.slcxxp.2q.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.src.q.2p2(i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.src.q.ld.ip.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.src.q.ld.xp.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.src.q.qup.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srci.2q.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srcmb.s16.q.qacc.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srcmb.s16.qacc.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srcmb.s8.q.qacc.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srcmb.s8.qacc.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srcmb.u16.q.qacc.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srcmb.u16.qacc.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srcmb.u8.q.qacc.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srcmb.u8.qacc.2p2(i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.srcq.128.st.incp.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srcxxp.2q.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srs.s.xacc.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.srs.u.xacc.2p2(i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsl.s32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsl.u32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsld.16.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsld.32.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsld.8.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsr.s32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsr.u32.2p2(i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsrd.16.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsrd.32.2p2(i32, i32, i32, i32, i32) nounwind
declare void @llvm.riscv.esp.vsrd.8.2p2(i32, i32, i32, i32, i32) nounwind
declare i32 @llvm.riscv.esp.st.s.xacc.ip.2p2(i32, i32) nounwind
declare i32 @llvm.riscv.esp.st.u.xacc.ip.2p2(i32, i32) nounwind

