; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+experimental-xtheadmatrix -verify-machineinstrs < %s \
; RUN:   | FileCheck %s
; ModuleID = '/tmp/gen_all_intrinsics.c'
source_filename = "/tmp/gen_all_intrinsics.c"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-unknown"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_config(i64 noundef %val) local_unnamed_addr #0 {
; CHECK-LABEL: test_config:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mrelease
; CHECK-NEXT:    th.msettilemi 8
; CHECK-NEXT:    th.msettilem a0
; CHECK-NEXT:    th.msettileki 16
; CHECK-NEXT:    th.msettilek a0
; CHECK-NEXT:    th.msettileni 4
; CHECK-NEXT:    th.msettilen a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.mrelease()
  tail call void @llvm.riscv.th.msettilemi.i64(i64 8)
  tail call void @llvm.riscv.th.msettilem.i64(i64 %val)
  tail call void @llvm.riscv.th.msettileki.i64(i64 16)
  tail call void @llvm.riscv.th.msettilek.i64(i64 %val)
  tail call void @llvm.riscv.th.msettileni.i64(i64 4)
  tail call void @llvm.riscv.th.msettilen.i64(i64 %val)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mrelease() #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.msettilemi.i64(i64 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.msettilem.i64(i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.msettileki.i64(i64 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.msettilek.i64(i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.msettileni.i64(i64 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.msettilen.i64(i64) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_loads(ptr noundef captures(none) %ptr, i64 noundef %stride) local_unnamed_addr #0 {
; CHECK-LABEL: test_loads:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mlae8 tr0, (a0), a1
; CHECK-NEXT:    th.mlae16 tr0, (a0), a1
; CHECK-NEXT:    th.mlae32 tr0, (a0), a1
; CHECK-NEXT:    th.mlae64 tr0, (a0), a1
; CHECK-NEXT:    th.mlbe8 tr1, (a0), a1
; CHECK-NEXT:    th.mlbe16 tr1, (a0), a1
; CHECK-NEXT:    th.mlbe32 tr1, (a0), a1
; CHECK-NEXT:    th.mlbe64 tr1, (a0), a1
; CHECK-NEXT:    th.mlce8 acc0, (a0), a1
; CHECK-NEXT:    th.mlce16 acc0, (a0), a1
; CHECK-NEXT:    th.mlce32 acc0, (a0), a1
; CHECK-NEXT:    th.mlce64 acc0, (a0), a1
; CHECK-NEXT:    th.mlate8 tr2, (a0), a1
; CHECK-NEXT:    th.mlate16 tr2, (a0), a1
; CHECK-NEXT:    th.mlate32 tr2, (a0), a1
; CHECK-NEXT:    th.mlate64 tr2, (a0), a1
; CHECK-NEXT:    th.mlbte8 tr3, (a0), a1
; CHECK-NEXT:    th.mlbte16 tr3, (a0), a1
; CHECK-NEXT:    th.mlbte32 tr3, (a0), a1
; CHECK-NEXT:    th.mlbte64 tr3, (a0), a1
; CHECK-NEXT:    th.mlcte8 acc1, (a0), a1
; CHECK-NEXT:    th.mlcte16 acc1, (a0), a1
; CHECK-NEXT:    th.mlcte32 acc1, (a0), a1
; CHECK-NEXT:    th.mlcte64 acc1, (a0), a1
; CHECK-NEXT:    th.mlme8 tr0, (a0)
; CHECK-NEXT:    th.mlme16 tr0, (a0)
; CHECK-NEXT:    th.mlme32 tr0, (a0)
; CHECK-NEXT:    th.mlme64 tr0, (a0)
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.mlae8.i64(i32 0, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlae16.i64(i32 0, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlae32.i64(i32 0, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlae64.i64(i32 0, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlbe8.i64(i32 1, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlbe16.i64(i32 1, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlbe32.i64(i32 1, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlbe64.i64(i32 1, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlce8.i64(i32 4, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlce16.i64(i32 4, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlce32.i64(i32 4, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlce64.i64(i32 4, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlate8.i64(i32 2, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlate16.i64(i32 2, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlate32.i64(i32 2, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlate64.i64(i32 2, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlbte8.i64(i32 3, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlbte16.i64(i32 3, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlbte32.i64(i32 3, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlbte64.i64(i32 3, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlcte8.i64(i32 5, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlcte16.i64(i32 5, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlcte32.i64(i32 5, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlcte64.i64(i32 5, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mlme8(i32 0, ptr %ptr)
  tail call void @llvm.riscv.th.mlme16(i32 0, ptr %ptr)
  tail call void @llvm.riscv.th.mlme32(i32 0, ptr %ptr)
  tail call void @llvm.riscv.th.mlme64(i32 0, ptr %ptr)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlae8.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlae16.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlae32.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlae64.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlbe8.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlbe16.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlbe32.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlbe64.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlce8.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlce16.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlce32.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlce64.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlate8.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlate16.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlate32.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlate64.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlbte8.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlbte16.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlbte32.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlbte64.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlcte8.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlcte16.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlcte32.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlcte64.i64(i32 immarg, ptr captures(none), i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlme8(i32 immarg, ptr captures(none)) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlme16(i32 immarg, ptr captures(none)) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlme32(i32 immarg, ptr captures(none)) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mlme64(i32 immarg, ptr captures(none)) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(write)
define dso_local void @test_stores(ptr noundef writeonly captures(none) %ptr, i64 noundef %stride) local_unnamed_addr #2 {
; CHECK-LABEL: test_stores:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.msae8 tr0, (a0), a1
; CHECK-NEXT:    th.msae16 tr0, (a0), a1
; CHECK-NEXT:    th.msae32 tr0, (a0), a1
; CHECK-NEXT:    th.msae64 tr0, (a0), a1
; CHECK-NEXT:    th.msbe8 tr1, (a0), a1
; CHECK-NEXT:    th.msbe16 tr1, (a0), a1
; CHECK-NEXT:    th.msbe32 tr1, (a0), a1
; CHECK-NEXT:    th.msbe64 tr1, (a0), a1
; CHECK-NEXT:    th.msce8 acc0, (a0), a1
; CHECK-NEXT:    th.msce16 acc0, (a0), a1
; CHECK-NEXT:    th.msce32 acc0, (a0), a1
; CHECK-NEXT:    th.msce64 acc0, (a0), a1
; CHECK-NEXT:    th.msate8 tr2, (a0), a1
; CHECK-NEXT:    th.msate16 tr2, (a0), a1
; CHECK-NEXT:    th.msate32 tr2, (a0), a1
; CHECK-NEXT:    th.msate64 tr2, (a0), a1
; CHECK-NEXT:    th.msbte8 tr3, (a0), a1
; CHECK-NEXT:    th.msbte16 tr3, (a0), a1
; CHECK-NEXT:    th.msbte32 tr3, (a0), a1
; CHECK-NEXT:    th.msbte64 tr3, (a0), a1
; CHECK-NEXT:    th.mscte8 acc1, (a0), a1
; CHECK-NEXT:    th.mscte16 acc1, (a0), a1
; CHECK-NEXT:    th.mscte32 acc1, (a0), a1
; CHECK-NEXT:    th.mscte64 acc1, (a0), a1
; CHECK-NEXT:    th.msme8 tr0, (a0)
; CHECK-NEXT:    th.msme16 tr0, (a0)
; CHECK-NEXT:    th.msme32 tr0, (a0)
; CHECK-NEXT:    th.msme64 tr0, (a0)
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.msae8.i64(i32 0, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msae16.i64(i32 0, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msae32.i64(i32 0, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msae64.i64(i32 0, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msbe8.i64(i32 1, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msbe16.i64(i32 1, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msbe32.i64(i32 1, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msbe64.i64(i32 1, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msce8.i64(i32 4, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msce16.i64(i32 4, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msce32.i64(i32 4, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msce64.i64(i32 4, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msate8.i64(i32 2, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msate16.i64(i32 2, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msate32.i64(i32 2, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msate64.i64(i32 2, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msbte8.i64(i32 3, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msbte16.i64(i32 3, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msbte32.i64(i32 3, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msbte64.i64(i32 3, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mscte8.i64(i32 5, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mscte16.i64(i32 5, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mscte32.i64(i32 5, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.mscte64.i64(i32 5, ptr %ptr, i64 %stride)
  tail call void @llvm.riscv.th.msme8(i32 0, ptr %ptr)
  tail call void @llvm.riscv.th.msme16(i32 0, ptr %ptr)
  tail call void @llvm.riscv.th.msme32(i32 0, ptr %ptr)
  tail call void @llvm.riscv.th.msme64(i32 0, ptr %ptr)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msae8.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msae16.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msae32.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msae64.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msbe8.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msbe16.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msbe32.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msbe64.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msce8.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msce16.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msce32.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msce64.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msate8.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msate16.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msate32.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msate64.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msbte8.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msbte16.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msbte32.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msbte64.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.mscte8.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.mscte16.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.mscte32.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.mscte64.i64(i32 immarg, ptr captures(none), i64) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msme8(i32 immarg, ptr captures(none)) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msme16(i32 immarg, ptr captures(none)) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msme32(i32 immarg, ptr captures(none)) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(write)
declare void @llvm.riscv.th.msme64(i32 immarg, ptr captures(none)) #3

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_matmul() local_unnamed_addr #0 {
; CHECK-LABEL: test_matmul:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mfmacc.h.e5 acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.h.e4 acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.bf16.e5 acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.bf16.e4 acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.s.e5 acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.s.e4 acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.h acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.s.h acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.s.bf16 acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.s.tf32 acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.s acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.d.s acc0, tr1, tr0
; CHECK-NEXT:    th.mfmacc.d acc0, tr1, tr0
; CHECK-NEXT:    th.mmaccu.w.b acc0, tr1, tr0
; CHECK-NEXT:    th.mmaccus.w.b acc0, tr1, tr0
; CHECK-NEXT:    th.mmaccsu.w.b acc0, tr1, tr0
; CHECK-NEXT:    th.mmacc.w.b acc0, tr1, tr0
; CHECK-NEXT:    th.pmmaccu.w.b acc0, tr1, tr0
; CHECK-NEXT:    th.pmmaccus.w.b acc0, tr1, tr0
; CHECK-NEXT:    th.pmmaccsu.w.b acc0, tr1, tr0
; CHECK-NEXT:    th.pmmacc.w.b acc0, tr1, tr0
; CHECK-NEXT:    th.mmaccu.d.h acc0, tr1, tr0
; CHECK-NEXT:    th.mmaccus.d.h acc0, tr1, tr0
; CHECK-NEXT:    th.mmaccsu.d.h acc0, tr1, tr0
; CHECK-NEXT:    th.mmacc.d.h acc0, tr1, tr0
; CHECK-NEXT:    th.mmaccu.w.bp acc0, tr1, tr0
; CHECK-NEXT:    th.mmacc.w.bp acc0, tr1, tr0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.mfmacc.h.e5(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.h.e4(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.bf16.e5(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.bf16.e4(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.s.e5(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.s.e4(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.h(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.s.h(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.s.bf16(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.s.tf32(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.s(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.d.s(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mfmacc.d(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmaccu.w.b(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmaccus.w.b(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmaccsu.w.b(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmacc.w.b(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.pmmaccu.w.b(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.pmmaccus.w.b(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.pmmaccsu.w.b(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.pmmacc.w.b(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmaccu.d.h(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmaccus.d.h(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmaccsu.d.h(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmacc.d.h(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmaccu.w.bp(i32 4, i32 1, i32 0)
  tail call void @llvm.riscv.th.mmacc.w.bp(i32 4, i32 1, i32 0)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.h.e5(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.h.e4(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.bf16.e5(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.bf16.e4(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.s.e5(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.s.e4(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.h(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.s.h(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.s.bf16(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.s.tf32(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.s(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.d.s(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfmacc.d(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmaccu.w.b(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmaccus.w.b(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmaccsu.w.b(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmacc.w.b(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.pmmaccu.w.b(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.pmmaccus.w.b(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.pmmaccsu.w.b(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.pmmacc.w.b(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmaccu.d.h(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmaccus.d.h(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmaccsu.d.h(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmacc.d.h(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmaccu.w.bp(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmacc.w.bp(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_misc(i64 noundef %idx, i64 noundef %val) local_unnamed_addr #0 {
; CHECK-LABEL: test_misc:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mzero acc0
; CHECK-NEXT:    th.mzero2r tr0
; CHECK-NEXT:    th.mzero4r tr0
; CHECK-NEXT:    th.mzero8r tr0
; CHECK-NEXT:    th.mmov.mm tr0, tr1
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.mzero(i32 4)
  tail call void @llvm.riscv.th.mzero2r(i32 0)
  tail call void @llvm.riscv.th.mzero4r(i32 0)
  tail call void @llvm.riscv.th.mzero8r(i32 0)
  tail call void @llvm.riscv.th.mmov.mm(i32 0, i32 1)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mzero(i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mzero2r(i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mzero4r(i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mzero8r(i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmov.mm(i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local i64 @test_mov_togpr(i64 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: test_mov_togpr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mmovw.x.m a0, tr0, a0
; CHECK-NEXT:    ret
entry:
  %0 = tail call i64 @llvm.riscv.th.mmovw.x.m.i64(i32 0, i64 %idx)
  ret i64 %0
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare i64 @llvm.riscv.th.mmovw.x.m.i64(i32 immarg, i64) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_mov_fromgpr(i64 noundef %val, i64 noundef %idx) local_unnamed_addr #0 {
; CHECK-LABEL: test_mov_fromgpr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mmovw.m.x tr0, a0, a1
; CHECK-NEXT:    th.mdupw.m.x tr0, a0
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.mmovw.m.x.i64(i32 0, i64 %val, i64 %idx)
  tail call void @llvm.riscv.th.mdupw.m.x.i64(i32 0, i64 %val)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mmovw.m.x.i64(i32 immarg, i64, i64) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mdupw.m.x.i64(i32 immarg, i64) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_pack() local_unnamed_addr #0 {
; CHECK-LABEL: test_pack:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mpack tr0, tr2, tr1
; CHECK-NEXT:    th.mpackhl tr0, tr2, tr1
; CHECK-NEXT:    th.mpackhh tr0, tr2, tr1
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.mpack(i32 0, i32 2, i32 1)
  tail call void @llvm.riscv.th.mpackhl(i32 0, i32 2, i32 1)
  tail call void @llvm.riscv.th.mpackhh(i32 0, i32 2, i32 1)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mpack(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mpackhl(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mpackhh(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_slides() local_unnamed_addr #0 {
; CHECK-LABEL: test_slides:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mrslidedown tr0, tr1, 3
; CHECK-NEXT:    th.mrslideup tr0, tr1, 2
; CHECK-NEXT:    th.mcslidedown.b tr0, tr1, 1
; CHECK-NEXT:    th.mcslideup.w tr0, tr1, 4
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.mrslidedown.i32(i32 0, i32 1, i32 3)
  tail call void @llvm.riscv.th.mrslideup.i32(i32 0, i32 1, i32 2)
  tail call void @llvm.riscv.th.mcslidedown.b.i32(i32 0, i32 1, i32 1)
  tail call void @llvm.riscv.th.mcslideup.w.i32(i32 0, i32 1, i32 4)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mrslidedown.i32(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mrslideup.i32(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mcslidedown.b.i32(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mcslideup.w.i32(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_broadcasts() local_unnamed_addr #0 {
; CHECK-LABEL: test_broadcasts:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mrbca.mv.i tr0, tr1, 5
; CHECK-NEXT:    th.mcbcab.mv.i tr0, tr1, 1
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.mrbca.mv.i.i32(i32 0, i32 1, i32 5)
  tail call void @llvm.riscv.th.mcbcab.mv.i.i32(i32 0, i32 1, i32 1)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mrbca.mv.i.i32(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mcbcab.mv.i.i32(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_conversions() local_unnamed_addr #0 {
; CHECK-LABEL: test_conversions:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.mfcvtl.h.e4 acc0, acc1
; CHECK-NEXT:    th.mfcvth.s.bf16 acc0, acc1
; CHECK-NEXT:    th.mfcvt.tf32.s acc0, acc1
; CHECK-NEXT:    th.msfcvtl.h.b acc0, acc1
; CHECK-NEXT:    th.mfucvtl.b.h acc0, acc1
; CHECK-NEXT:    th.msfcvt.s.w acc0, acc1
; CHECK-NEXT:    th.mfscvt.w.s acc0, acc1
; CHECK-NEXT:    th.mucvtl.b.p acc0, acc1
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.mfcvtl.h.e4(i32 4, i32 5)
  tail call void @llvm.riscv.th.mfcvth.s.bf16(i32 4, i32 5)
  tail call void @llvm.riscv.th.mfcvt.tf32.s(i32 4, i32 5)
  tail call void @llvm.riscv.th.msfcvtl.h.b(i32 4, i32 5)
  tail call void @llvm.riscv.th.mfucvtl.b.h(i32 4, i32 5)
  tail call void @llvm.riscv.th.msfcvt.s.w(i32 4, i32 5)
  tail call void @llvm.riscv.th.mfscvt.w.s(i32 4, i32 5)
  tail call void @llvm.riscv.th.mucvtl.b.p(i32 4, i32 5)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfcvtl.h.e4(i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfcvth.s.bf16(i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfcvt.tf32.s(i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.msfcvtl.h.b(i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfucvtl.b.h(i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.msfcvt.s.w(i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfscvt.w.s(i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mucvtl.b.p(i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
define dso_local void @test_ew_arith() local_unnamed_addr #0 {
; CHECK-LABEL: test_ew_arith:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    th.madd.w.mm acc0, acc2, acc1
; CHECK-NEXT:    th.madd.w.mv.i acc0, acc2, acc1, 3
; CHECK-NEXT:    th.mfadd.h.mm acc0, acc2, acc1
; CHECK-NEXT:    th.mfadd.s.mv.i acc0, acc2, acc1, 2
; CHECK-NEXT:    th.mn4clipl.w.mm acc0, acc2, acc1
; CHECK-NEXT:    th.mn4clipl.w.mv.i acc0, acc2, acc1, 1
; CHECK-NEXT:    ret
entry:
  tail call void @llvm.riscv.th.madd.w.mm(i32 4, i32 6, i32 5)
  tail call void @llvm.riscv.th.madd.w.mv.i.i32(i32 4, i32 6, i32 5, i32 3)
  tail call void @llvm.riscv.th.mfadd.h.mm(i32 4, i32 6, i32 5)
  tail call void @llvm.riscv.th.mfadd.s.mv.i.i32(i32 4, i32 6, i32 5, i32 2)
  tail call void @llvm.riscv.th.mn4clipl.w.mm(i32 4, i32 6, i32 5)
  tail call void @llvm.riscv.th.mn4clipl.w.mv.i.i32(i32 4, i32 6, i32 5, i32 1)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.madd.w.mm(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.madd.w.mv.i.i32(i32 immarg, i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfadd.h.mm(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mfadd.s.mv.i.i32(i32 immarg, i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mn4clipl.w.mm(i32 immarg, i32 immarg, i32 immarg) #1

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.riscv.th.mn4clipl.w.mv.i.i32(i32 immarg, i32 immarg, i32 immarg, i32 immarg) #1

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic-rv64" "target-features"="+64bit,+experimental,+experimental-xtheadmatrix,+i,+relax,-a,-b,-c,-d,-e,-experimental-p,-experimental-smpmpmt,-experimental-svukte,-experimental-xrivosvisni,-experimental-xrivosvizip,-experimental-xsfmclic,-experimental-xsfsclic,-experimental-zibi,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvfbfa,-experimental-zvfofp8min,-experimental-zvkgs,-experimental-zvqdotq,-f,-h,-m,-q,-sdext,-sdtrig,-sha,-shcounterenw,-shgatpa,-shlcofideleg,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcntrpmf,-smcsrind,-smctr,-smdbltrp,-smepmp,-smmpm,-smnpm,-smrnmi,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssctr,-ssdbltrp,-ssnpm,-sspm,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-supm,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-svvptc,-v,-xandesbfhcvt,-xandesperf,-xandesvbfhcvt,-xandesvdot,-xandesvpackfph,-xandesvsinth,-xandesvsintload,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xmipscbop,-xmipscmov,-xmipsexectl,-xmipslsp,-xqccmp,-xqci,-xqcia,-xqciac,-xqcibi,-xqcibm,-xqcicli,-xqcicm,-xqcics,-xqcicsr,-xqciint,-xqciio,-xqcilb,-xqcili,-xqcilia,-xqcilo,-xqcilsm,-xqcisim,-xqcisls,-xqcisync,-xsfcease,-xsfmm128t,-xsfmm16t,-xsfmm32a16f,-xsfmm32a32f,-xsfmm32a8f,-xsfmm32a8i,-xsfmm32t,-xsfmm64a64f,-xsfmm64t,-xsfmmbase,-xsfvcp,-xsfvfbfexp16e,-xsfvfexp16e,-xsfvfexp32e,-xsfvfexpa,-xsfvfexpa64e,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xsmtvdot,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zacas,-zalasr,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zclsd,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccamoc,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zicsr,-zifencei,-zihintntl,-zihintpause,-zihpm,-zilsd,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-zmmul,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn }
attributes #2 = { mustprogress nofree norecurse nosync nounwind willreturn memory(write) "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic-rv64" "target-features"="+64bit,+experimental,+experimental-xtheadmatrix,+i,+relax,-a,-b,-c,-d,-e,-experimental-p,-experimental-smpmpmt,-experimental-svukte,-experimental-xrivosvisni,-experimental-xrivosvizip,-experimental-xsfmclic,-experimental-xsfsclic,-experimental-zibi,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvfbfa,-experimental-zvfofp8min,-experimental-zvkgs,-experimental-zvqdotq,-f,-h,-m,-q,-sdext,-sdtrig,-sha,-shcounterenw,-shgatpa,-shlcofideleg,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcntrpmf,-smcsrind,-smctr,-smdbltrp,-smepmp,-smmpm,-smnpm,-smrnmi,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssctr,-ssdbltrp,-ssnpm,-sspm,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-supm,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-svvptc,-v,-xandesbfhcvt,-xandesperf,-xandesvbfhcvt,-xandesvdot,-xandesvpackfph,-xandesvsinth,-xandesvsintload,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xmipscbop,-xmipscmov,-xmipsexectl,-xmipslsp,-xqccmp,-xqci,-xqcia,-xqciac,-xqcibi,-xqcibm,-xqcicli,-xqcicm,-xqcics,-xqcicsr,-xqciint,-xqciio,-xqcilb,-xqcili,-xqcilia,-xqcilo,-xqcilsm,-xqcisim,-xqcisls,-xqcisync,-xsfcease,-xsfmm128t,-xsfmm16t,-xsfmm32a16f,-xsfmm32a32f,-xsfmm32a8f,-xsfmm32a8i,-xsfmm32t,-xsfmm64a64f,-xsfmm64t,-xsfmmbase,-xsfvcp,-xsfvfbfexp16e,-xsfvfexp16e,-xsfvfexp32e,-xsfvfexpa,-xsfvfexpa64e,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xsmtvdot,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zacas,-zalasr,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zclsd,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccamoc,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zicsr,-zifencei,-zihintntl,-zihintpause,-zihpm,-zilsd,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-zmmul,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }
attributes #3 = { mustprogress nocallback nofree nosync nounwind willreturn memory(write) }

!llvm.module.flags = !{!0, !1, !2, !4}
!llvm.ident = !{!5}
!llvm.errno.tbaa = !{!6}

; ==========================================================================
; Register flexibility tests — verify ISel reads register indices from args
; ==========================================================================

; Multi-accumulator matmul: same A/B regs, two different accumulators
; CHECK-LABEL: test_multi_acc_matmul:
; CHECK: th.mzero acc0
; CHECK: th.mfmacc.h.e4 acc0, tr1, tr0
; CHECK: th.mzero acc1
; CHECK: th.mfmacc.h.e4 acc1, tr1, tr0
define void @test_multi_acc_matmul() #0 {
  call void @llvm.riscv.th.mzero(i32 4)
  call void @llvm.riscv.th.mfmacc.h.e4(i32 4, i32 1, i32 0)
  call void @llvm.riscv.th.mzero(i32 5)
  call void @llvm.riscv.th.mfmacc.h.e4(i32 5, i32 1, i32 0)
  ret void
}

; Custom register selection: matmul with tr2/tr3 pair
; CHECK-LABEL: test_custom_tile_pair:
; CHECK: th.mfmacc.s acc2, tr3, tr2
define void @test_custom_tile_pair() #0 {
  call void @llvm.riscv.th.mfmacc.s(i32 6, i32 3, i32 2)
  ret void
}

; Zero targeting different registers
; CHECK-LABEL: test_mzero_all_regs:
; CHECK: th.mzero tr0
; CHECK: th.mzero tr1
; CHECK: th.mzero tr2
; CHECK: th.mzero tr3
; CHECK: th.mzero acc0
; CHECK: th.mzero acc1
; CHECK: th.mzero acc2
; CHECK: th.mzero acc3
define void @test_mzero_all_regs() #0 {
  call void @llvm.riscv.th.mzero(i32 0)
  call void @llvm.riscv.th.mzero(i32 1)
  call void @llvm.riscv.th.mzero(i32 2)
  call void @llvm.riscv.th.mzero(i32 3)
  call void @llvm.riscv.th.mzero(i32 4)
  call void @llvm.riscv.th.mzero(i32 5)
  call void @llvm.riscv.th.mzero(i32 6)
  call void @llvm.riscv.th.mzero(i32 7)
  ret void
}

; EW on different acc register combinations
; CHECK-LABEL: test_ew_custom_acc:
; CHECK: th.mfadd.h.mm acc1, acc3, acc2
define void @test_ew_custom_acc() #0 {
  call void @llvm.riscv.th.mfadd.h.mm(i32 5, i32 7, i32 6)
  ret void
}

; Load A into non-default tile register (tr2)
; CHECK-LABEL: test_custom_load_reg:
; CHECK: th.mlae8 tr2
define void @test_custom_load_reg(ptr %p, i64 %s) #0 {
  call void @llvm.riscv.th.mlae8.i64(i32 2, ptr %p, i64 %s)
  ret void
}

; Store C from non-default acc register (acc1)
; CHECK-LABEL: test_custom_store_reg:
; CHECK: th.msce32 acc1
define void @test_custom_store_reg(ptr %p, i64 %s) #0 {
  call void @llvm.riscv.th.msce32.i64(i32 5, ptr %p, i64 %s)
  ret void
}

; Conversion with different acc registers
; CHECK-LABEL: test_custom_cvt_regs:
; CHECK: th.mfcvtl.h.e4 acc2, acc3
define void @test_custom_cvt_regs() #0 {
  call void @llvm.riscv.th.mfcvtl.h.e4(i32 6, i32 7)
  ret void
}

; mmov.mm between acc registers
; CHECK-LABEL: test_mmov_acc_to_acc:
; CHECK: th.mmov.mm acc1, acc0
define void @test_mmov_acc_to_acc() #0 {
  call void @llvm.riscv.th.mmov.mm(i32 5, i32 4)
  ret void
}

; Slide with acc registers
; CHECK-LABEL: test_slide_acc:
; CHECK: th.mrslidedown acc0, acc1
define void @test_slide_acc() #0 {
  call void @llvm.riscv.th.mrslidedown.i32(i32 4, i32 5, i32 2)
  ret void
}

; Full dual-GEMM pipeline: two independent matmuls sharing same tile regs
; CHECK-LABEL: test_dual_gemm_pipeline:
; CHECK: th.mlae8 tr0
; CHECK: th.mlbe8 tr1
; CHECK: th.mzero acc0
; CHECK: th.mmacc.w.b acc0, tr1, tr0
; CHECK: th.mlbe8 tr1
; CHECK: th.mzero acc1
; CHECK: th.mmacc.w.b acc1, tr1, tr0
; CHECK: th.msce32 acc0
; CHECK: th.msce32 acc1
define void @test_dual_gemm_pipeline(ptr %a, ptr %b1, ptr %b2,
                                     ptr %c1, ptr %c2, i64 %s) #0 {
  ; Load A
  call void @llvm.riscv.th.mlae8.i64(i32 0, ptr %a, i64 %s)
  ; GEMM 1: B1 → acc0
  call void @llvm.riscv.th.mlbe8.i64(i32 1, ptr %b1, i64 %s)
  call void @llvm.riscv.th.mzero(i32 4)
  call void @llvm.riscv.th.mmacc.w.b(i32 4, i32 1, i32 0)
  ; GEMM 2: B2 → acc1
  call void @llvm.riscv.th.mlbe8.i64(i32 1, ptr %b2, i64 %s)
  call void @llvm.riscv.th.mzero(i32 5)
  call void @llvm.riscv.th.mmacc.w.b(i32 5, i32 1, i32 0)
  ; Store both
  call void @llvm.riscv.th.msce32.i64(i32 4, ptr %c1, i64 %s)
  call void @llvm.riscv.th.msce32.i64(i32 5, ptr %c2, i64 %s)
  ret void
}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"lp64"}
!2 = !{i32 6, !"riscv-isa", !3}
!3 = !{!"rv64i2p1_xtheadmatrix0p6"}
!4 = !{i32 8, !"SmallDataLimit", i32 0}
!5 = !{!"clang version 22.1.1 (https://github.com/llvm/llvm-project.git 5e1b2084e9b53e49eeed5b676b972d7157c9a175)"}
!6 = !{!7, !7, i64 0}
!7 = !{!"int", !8, i64 0}
!8 = !{!"omnipotent char", !9, i64 0}
!9 = !{!"Simple C/C++ TBAA"}
