; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-xtheadzmpanel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s
;
; Tests for the Zmpanel (Panel-Aware 2x2 Matrix Tiling) intrinsics.
; All 30 intrinsics are tested individually, plus a combined usage pattern.

target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-unknown"

;; ============================================================================
;; Configuration intrinsics (12 total) — take one i64 GPR operand
;; ============================================================================

define void @test_mset22adra(i64 %val) {
; CHECK-LABEL: test_mset22adra:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22adra a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22adra(i64 %val)
  ret void
}

define void @test_mset22adrb(i64 %val) {
; CHECK-LABEL: test_mset22adrb:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22adrb a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22adrb(i64 %val)
  ret void
}

define void @test_mset22adrd(i64 %val) {
; CHECK-LABEL: test_mset22adrd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22adrd a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22adrd(i64 %val)
  ret void
}

define void @test_mset22rsba(i64 %val) {
; CHECK-LABEL: test_mset22rsba:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22rsba a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22rsba(i64 %val)
  ret void
}

define void @test_mset22rsbb(i64 %val) {
; CHECK-LABEL: test_mset22rsbb:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22rsbb a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22rsbb(i64 %val)
  ret void
}

define void @test_mset22rsbd(i64 %val) {
; CHECK-LABEL: test_mset22rsbd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22rsbd a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22rsbd(i64 %val)
  ret void
}

define void @test_mset22m(i64 %val) {
; CHECK-LABEL: test_mset22m:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22m a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22m(i64 %val)
  ret void
}

define void @test_mset22n(i64 %val) {
; CHECK-LABEL: test_mset22n:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22n a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22n(i64 %val)
  ret void
}

define void @test_mset22k(i64 %val) {
; CHECK-LABEL: test_mset22k:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22k a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22k(i64 %val)
  ret void
}

define void @test_msetrstptr(i64 %val) {
; CHECK-LABEL: test_msetrstptr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.msetrstptr a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.msetrstptr(i64 %val)
  ret void
}

define void @test_msetaccum(i64 %val) {
; CHECK-LABEL: test_msetaccum:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.msetaccum a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.msetaccum(i64 %val)
  ret void
}

define void @test_msetoob(i64 %val) {
; CHECK-LABEL: test_msetoob:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.msetoob a0
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.msetoob(i64 %val)
  ret void
}

;; ============================================================================
;; Load macro instructions (2 total) — no operands
;; ============================================================================

define void @test_ml22e8() {
; CHECK-LABEL: test_ml22e8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.ml22e8
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.ml22e8()
  ret void
}

define void @test_ml22e16() {
; CHECK-LABEL: test_ml22e16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.ml22e16
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.ml22e16()
  ret void
}

;; ============================================================================
;; Store macro instructions (2 total) — no operands
;; ============================================================================

define void @test_msc22e16() {
; CHECK-LABEL: test_msc22e16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.msc22e16
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.msc22e16()
  ret void
}

define void @test_msc22e32() {
; CHECK-LABEL: test_msc22e32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.msc22e32
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.msc22e32()
  ret void
}

;; ============================================================================
;; FP compute macro instructions (10 total) — no operands
;; ============================================================================

define void @test_mfmacc22_h_e5() {
; CHECK-LABEL: test_mfmacc22_h_e5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.h.e5
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.h.e5()
  ret void
}

define void @test_mfmacc22_h_e4() {
; CHECK-LABEL: test_mfmacc22_h_e4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.h.e4
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.h.e4()
  ret void
}

define void @test_mfmacc22_bf16_e5() {
; CHECK-LABEL: test_mfmacc22_bf16_e5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.bf16.e5
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.bf16.e5()
  ret void
}

define void @test_mfmacc22_bf16_e4() {
; CHECK-LABEL: test_mfmacc22_bf16_e4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.bf16.e4
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.bf16.e4()
  ret void
}

define void @test_mfmacc22_s_e5() {
; CHECK-LABEL: test_mfmacc22_s_e5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.s.e5
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.s.e5()
  ret void
}

define void @test_mfmacc22_s_e4() {
; CHECK-LABEL: test_mfmacc22_s_e4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.s.e4
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.s.e4()
  ret void
}

define void @test_mfmacc22_h() {
; CHECK-LABEL: test_mfmacc22_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.h
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.h()
  ret void
}

define void @test_mfmacc22_s_h() {
; CHECK-LABEL: test_mfmacc22_s_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.s.h
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.s.h()
  ret void
}

define void @test_mfmacc22_s_bf16() {
; CHECK-LABEL: test_mfmacc22_s_bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.s.bf16
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.s.bf16()
  ret void
}

define void @test_mfmacc22_s() {
; CHECK-LABEL: test_mfmacc22_s:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mfmacc22.s
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mfmacc22.s()
  ret void
}

;; ============================================================================
;; INT compute macro instructions (4 total) — no operands
;; ============================================================================

define void @test_mmacc22_w_b() {
; CHECK-LABEL: test_mmacc22_w_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mmacc22.w.b
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mmacc22.w.b()
  ret void
}

define void @test_mmaccu22_w_b() {
; CHECK-LABEL: test_mmaccu22_w_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mmaccu22.w.b
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mmaccu22.w.b()
  ret void
}

define void @test_mmaccus22_w_b() {
; CHECK-LABEL: test_mmaccus22_w_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mmaccus22.w.b
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mmaccus22.w.b()
  ret void
}

define void @test_mmaccsu22_w_b() {
; CHECK-LABEL: test_mmaccsu22_w_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mmaccsu22.w.b
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mmaccsu22.w.b()
  ret void
}

;; ============================================================================
;; Combined test: typical panel GEMM usage pattern
;; ============================================================================

define void @test_panel_gemm_int8(i64 %addr_a, i64 %addr_b, i64 %addr_d,
                                  i64 %rsba, i64 %m, i64 %k) {
; CHECK-LABEL: test_panel_gemm_int8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22adra a0
; CHECK-NEXT:    th.mset22adrb a1
; CHECK-NEXT:    th.mset22adrd a2
; CHECK-NEXT:    th.mset22rsba a3
; CHECK-NEXT:    th.mset22m a4
; CHECK-NEXT:    th.mset22k a5
; CHECK-NEXT:    th.msetaccum zero
; CHECK-NEXT:    th.ml22e8
; CHECK-NEXT:    th.mmacc22.w.b
; CHECK-NEXT:    th.msc22e32
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22adra(i64 %addr_a)
  call void @llvm.riscv.th.mset22adrb(i64 %addr_b)
  call void @llvm.riscv.th.mset22adrd(i64 %addr_d)
  call void @llvm.riscv.th.mset22rsba(i64 %rsba)
  call void @llvm.riscv.th.mset22m(i64 %m)
  call void @llvm.riscv.th.mset22k(i64 %k)
  call void @llvm.riscv.th.msetaccum(i64 0)
  call void @llvm.riscv.th.ml22e8()
  call void @llvm.riscv.th.mmacc22.w.b()
  call void @llvm.riscv.th.msc22e32()
  ret void
}

define void @test_panel_gemm_fp16(i64 %addr_a, i64 %addr_b, i64 %addr_d,
                                  i64 %rsba, i64 %m, i64 %k) {
; CHECK-LABEL: test_panel_gemm_fp16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    th.mset22adra a0
; CHECK-NEXT:    th.mset22adrb a1
; CHECK-NEXT:    th.mset22adrd a2
; CHECK-NEXT:    th.mset22rsba a3
; CHECK-NEXT:    th.mset22m a4
; CHECK-NEXT:    th.mset22k a5
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    th.msetaccum a0
; CHECK-NEXT:    th.ml22e16
; CHECK-NEXT:    th.mfmacc22.h
; CHECK-NEXT:    th.msc22e16
; CHECK-NEXT:    ret
  call void @llvm.riscv.th.mset22adra(i64 %addr_a)
  call void @llvm.riscv.th.mset22adrb(i64 %addr_b)
  call void @llvm.riscv.th.mset22adrd(i64 %addr_d)
  call void @llvm.riscv.th.mset22rsba(i64 %rsba)
  call void @llvm.riscv.th.mset22m(i64 %m)
  call void @llvm.riscv.th.mset22k(i64 %k)
  call void @llvm.riscv.th.msetaccum(i64 1)
  call void @llvm.riscv.th.ml22e16()
  call void @llvm.riscv.th.mfmacc22.h()
  call void @llvm.riscv.th.msc22e16()
  ret void
}

;; ============================================================================
;; Intrinsic declarations
;; ============================================================================

; Configuration
declare void @llvm.riscv.th.mset22adra(i64)
declare void @llvm.riscv.th.mset22adrb(i64)
declare void @llvm.riscv.th.mset22adrd(i64)
declare void @llvm.riscv.th.mset22rsba(i64)
declare void @llvm.riscv.th.mset22rsbb(i64)
declare void @llvm.riscv.th.mset22rsbd(i64)
declare void @llvm.riscv.th.mset22m(i64)
declare void @llvm.riscv.th.mset22n(i64)
declare void @llvm.riscv.th.mset22k(i64)
declare void @llvm.riscv.th.msetrstptr(i64)
declare void @llvm.riscv.th.msetaccum(i64)
declare void @llvm.riscv.th.msetoob(i64)

; Load
declare void @llvm.riscv.th.ml22e8()
declare void @llvm.riscv.th.ml22e16()

; Store
declare void @llvm.riscv.th.msc22e16()
declare void @llvm.riscv.th.msc22e32()

; FP compute
declare void @llvm.riscv.th.mfmacc22.h.e5()
declare void @llvm.riscv.th.mfmacc22.h.e4()
declare void @llvm.riscv.th.mfmacc22.bf16.e5()
declare void @llvm.riscv.th.mfmacc22.bf16.e4()
declare void @llvm.riscv.th.mfmacc22.s.e5()
declare void @llvm.riscv.th.mfmacc22.s.e4()
declare void @llvm.riscv.th.mfmacc22.h()
declare void @llvm.riscv.th.mfmacc22.s.h()
declare void @llvm.riscv.th.mfmacc22.s.bf16()
declare void @llvm.riscv.th.mfmacc22.s()

; INT compute
declare void @llvm.riscv.th.mmacc22.w.b()
declare void @llvm.riscv.th.mmaccu22.w.b()
declare void @llvm.riscv.th.mmaccus22.w.b()
declare void @llvm.riscv.th.mmaccsu22.w.b()
