// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// Test IR generation (Builtin -> Intrinsic)
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv2p1 -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s --check-prefix=CHECK-2P2


#include <stdint.h>
#include <riscv_esp32p4.h>

// ESP.FFT.AMS.S16.LD.INCP.UAUP - FFT AMS with UA update and explicit state passing
// Using wrapper function with explicit phantom operands
// Initialize implicit registers using builtins before calling FFT instruction
// CHECK-LABEL: define dso_local void @test_fft_ams_s16_ld_incp_uaup(
// CHECK-2P2-LABEL: define dso_local void @test_fft_ams_s16_ld_incp_uaup(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar.bytes(i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.ua.state.ip(<16 x i8> undef, ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP5]] to <8 x i16>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { <16 x i8>, <8 x i16>, <8 x i16>, ptr, <16 x i8> } @llvm.riscv.esp.fft.ams.s16.ld.incp.uaup(<8 x i16> [[TMP6]], <8 x i16> [[TMP6]], <8 x i16> [[TMP6]], ptr [[SRC]], i32 0, i32 0, <16 x i8> [[TMP3]], i32 [[TMP1]], i32 [[TMP0]])
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr, <16 x i8> } [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr, <16 x i8> } [[TMP7]], 1
// CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr, <16 x i8> } [[TMP7]], 2
// CHECK-NEXT:    [[TMP11:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[DST]], i32 16)
// CHECK-NEXT:    [[TMP12:%.*]] = bitcast <8 x i16> [[TMP9]] to <16 x i8>
// CHECK-NEXT:    [[TMP13:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[DST]], i32 16)
// CHECK-NEXT:    [[TMP14:%.*]] = bitcast <8 x i16> [[TMP10]] to <16 x i8>
// CHECK-NEXT:    [[TMP15:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP14]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
// CHECK-2P2-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-2P2-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar.bytes(i32 0)
// CHECK-2P2-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.ua.state.ip(<16 x i8> undef, ptr [[SRC]], i32 16)
// CHECK-2P2-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-2P2-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-2P2-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP4]], 0
// CHECK-2P2-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP5]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP7:%.*]] = tail call { <16 x i8>, <8 x i16>, <8 x i16>, ptr, <16 x i8> } @llvm.riscv.esp.fft.ams.s16.ld.incp.uaup(<8 x i16> [[TMP6]], <8 x i16> [[TMP6]], <8 x i16> [[TMP6]], ptr [[SRC]], i32 0, i32 0, <16 x i8> [[TMP3]], i32 [[TMP1]], i32 [[TMP0]])
// CHECK-2P2-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr, <16 x i8> } [[TMP7]], 0
// CHECK-2P2-NEXT:    [[TMP9:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr, <16 x i8> } [[TMP7]], 1
// CHECK-2P2-NEXT:    [[TMP10:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr, <16 x i8> } [[TMP7]], 2
// CHECK-2P2-NEXT:    [[TMP11:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[DST]], i32 16)
// CHECK-2P2-NEXT:    [[TMP12:%.*]] = bitcast <8 x i16> [[TMP9]] to <16 x i8>
// CHECK-2P2-NEXT:    [[TMP13:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP12]], ptr [[DST]], i32 16)
// CHECK-2P2-NEXT:    [[TMP14:%.*]] = bitcast <8 x i16> [[TMP10]] to <16 x i8>
// CHECK-2P2-NEXT:    [[TMP15:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP14]], ptr [[DST]], i32 16)
// CHECK-2P2-NEXT:    ret void
//
void test_fft_ams_s16_ld_incp_uaup(void const *src, void *dst) {
    // Initialize UA_STATE, SAR_BYTES, SAR registers using builtins
    // Initialize SAR register (returns unsigned int for explicit state passing)
    unsigned int sar_in = __builtin_riscv_esp_movx_w_sar(0);

    // Initialize SAR_BYTES register (returns unsigned int for explicit state passing)
    unsigned int sar_bytes_in = __builtin_riscv_esp_movx_w_sar_bytes(0);

    // Initialize UA_STATE register by loading from memory
esp_ua_state_res_t ua_state_init;
  // Builtin signature: void*(void const *, int, void *)
  // Parameters: (src, offset, ua_state_out)
  // Returns: void* (updated pointer)
  // UA_STATE value is returned through output parameter
  ua_state_init.Ptr = __builtin_riscv_esp_ld_ua_state_ip(src, 16, &ua_state_init.UaState);

    // Load input vectors
esp_vld_res_t res_qx;
  res_qx.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &res_qx.Val.V8);
esp_vld_res_t res_qy;
  res_qy.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &res_qy.Val.V8);
esp_vld_res_t res_qw;
  res_qw.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &res_qw.Val.V8);

    // Call FFT AMS LD.INCP.UAUP using wrapper function (Sel2 = 0)
    // Note: Rs1 should point to the Data to be loaded (after UA_STATE initialization)
esp_fft_ams_s16_ld_incp_uaup_res_t Res;
  // Call builtin with explicit phantom operands
  Res.Ptr = __builtin_riscv_esp_fft_ams_s16_ld_incp_uaup(
      res_qx.Val.V16, res_qy.Val.V16, res_qw.Val.V16, src, 0, 0, &Res.Qu, &Res.Qz, &Res.Qv, ua_state_init.UaState,
      &Res.UaState, sar_bytes_in, sar_in);

    // Store results back to memory using esp.vst.128.ip
    // Note: v8i16 and v16i8 have the same memory layout (128 bits), so we can use union for conversion
    union {
        esp_vec128_16_t V16;
        esp_vec128_t V8;
    } qz_conv, QvConv;

    qz_conv.V16 = Res.Qz;
    QvConv.V16 = Res.Qv;

    (void)__builtin_riscv_esp_vst_128_ip(Res.Qu, dst, 16);           // Store Qu (v16i8)
    (void)__builtin_riscv_esp_vst_128_ip(qz_conv.V8, dst, 16);  // Store Qz (v8i16 converted to v16i8)
    (void)__builtin_riscv_esp_vst_128_ip(QvConv.V8, dst, 16);  // Store Qv (v8i16 converted to v16i8)
}

