// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// Test IR generation (Builtin -> Intrinsic)
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s

#include <stdint.h>
#include <riscv_esp32p4.h>

// ESP.LD.UA.STATE.IP - Load 128-bit Data from memory to UA_STATE register
// Then ESP.ST.UA.STATE.IP - Store UA_STATE register to memory
// Test flow: src -> UaState -> dst
// CHECK-LABEL: define dso_local void @test_ld_st_ua_state_ip(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.ua.state.ip.m(<16 x i8> undef, ptr [[SRC]], i32 16), !noalias [[META6:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.st.ua.state.ip.m(<16 x i8> [[TMP1]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_ld_st_ua_state_ip(void const *src, void *dst) {
    // Load 128-bit Data from src to UA_STATE register
    esp_ua_state_res_t Res = esp_ld_ua_state_ip_m(src, 16);
    // Store UA_STATE register to dst
    esp_st_ua_state_ip_m(Res.UaState, dst, 16);
}

//.
// CHECK: [[META6]] = !{[[META7:![0-9]+]]}
// CHECK: [[META7]] = distinct !{[[META7]], [[META8:![0-9]+]], !"esp_ld_ua_state_ip_m: %agg.result"}
// CHECK: [[META8]] = distinct !{[[META8]], !"esp_ld_ua_state_ip_m"}
//.
