// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// Test IR generation (Builtin -> Intrinsic)
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s

#include <stdint.h>
#include <riscv_esp32p4.h>
esp_vec128_t __builtin_riscv_esp_vmax_s8(esp_vec128_t, esp_vec128_t);
esp_vec128_t __builtin_riscv_esp_vmin_s8(esp_vec128_t, esp_vec128_t);
esp_vec128_t __builtin_riscv_esp_vmax_u8(esp_vec128_t, esp_vec128_t);
esp_vec128_t __builtin_riscv_esp_vmin_u8(esp_vec128_t, esp_vec128_t);


// Vector max/min (8-bit)
// CHECK-LABEL: define dso_local void @test_vmax_s8(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <16 x i8> @llvm.riscv.esp.vmax.s8(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vmax_s8(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_t max_val = __builtin_riscv_esp_vmax_s8(Res1.Val.V8, Res2.Val.V8);
    (void)__builtin_riscv_esp_vst_128_ip(max_val, dst, 16);
}

//


// CHECK-LABEL: define dso_local void @test_vmin_s8(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <16 x i8> @llvm.riscv.esp.vmin.s8(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vmin_s8(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_t min_val = __builtin_riscv_esp_vmin_s8(Res1.Val.V8, Res2.Val.V8);
    (void)__builtin_riscv_esp_vst_128_ip(min_val, dst, 16);
}

//


// CHECK-LABEL: define dso_local void @test_vmax_u8(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <16 x i8> @llvm.riscv.esp.vmax.u8(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vmax_u8(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_t max_val = __builtin_riscv_esp_vmax_u8(Res1.Val.V8, Res2.Val.V8);
    (void)__builtin_riscv_esp_vst_128_ip(max_val, dst, 16);
}

//


// CHECK-LABEL: define dso_local void @test_vmin_u8(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <16 x i8> @llvm.riscv.esp.vmin.u8(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vmin_u8(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_t min_val = __builtin_riscv_esp_vmin_u8(Res1.Val.V8, Res2.Val.V8);
    (void)__builtin_riscv_esp_vst_128_ip(min_val, dst, 16);
}

// GPR ALU (.m): Builtin -> Intrinsic (@llvm.riscv.esp.*.m)
unsigned int __builtin_riscv_esp_addx2_m(unsigned int, unsigned int);
unsigned int __builtin_riscv_esp_addx4_m(unsigned int, unsigned int);
unsigned int __builtin_riscv_esp_subx2_m(unsigned int, unsigned int);
unsigned int __builtin_riscv_esp_subx4_m(unsigned int, unsigned int);

// CHECK-LABEL: define dso_local i32 @test_gpr_addx2_m(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.addx2.m(i32 [[A]], i32 [[B]])
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned test_gpr_addx2_m(unsigned a, unsigned b) {
  return __builtin_riscv_esp_addx2_m(a, b);
}

// CHECK-LABEL: define dso_local i32 @test_gpr_addx4_m(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.addx4.m(i32 [[A]], i32 [[B]])
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned test_gpr_addx4_m(unsigned a, unsigned b) {
  return __builtin_riscv_esp_addx4_m(a, b);
}

// CHECK-LABEL: define dso_local i32 @test_gpr_subx2_m(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.subx2.m(i32 [[A]], i32 [[B]])
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned test_gpr_subx2_m(unsigned a, unsigned b) {
  return __builtin_riscv_esp_subx2_m(a, b);
}

// CHECK-LABEL: define dso_local i32 @test_gpr_subx4_m(
// CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.subx4.m(i32 [[A]], i32 [[B]])
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned test_gpr_subx4_m(unsigned a, unsigned b) {
  return __builtin_riscv_esp_subx4_m(a, b);
}

// Vector absolute value (8-bit)
//

