// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// Test IR generation (Builtin -> Intrinsic)
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv2p1 -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s --check-prefix=CHECK-2P2


#include <stdint.h>
#include <riscv_esp32p4.h>

// Additional type definitions

// Note: SAR register is now passed explicitly in _m version for better optimization.
// The _m version returns the new SAR value for chaining.
unsigned int __builtin_riscv_esp_movx_w_sar(unsigned int Rs1);
unsigned int __builtin_riscv_esp_movx_w_sar_bytes(unsigned int Rs1);
void __builtin_riscv_esp_fft_r2bf_s16(esp_vec128_16_t Qx, esp_vec128_16_t Qy, int Sel2, unsigned int sat, void *qz_out, void *qv_out);
void *__builtin_riscv_esp_fft_r2bf_s16_st_incp(esp_vec128_16_t Qx, esp_vec128_16_t Qy, void *Rs1, int sel4, unsigned int sat, void *qz_out);
void *__builtin_riscv_esp_fft_ams_s16_ld_incp(esp_vec128_16_t Qx, esp_vec128_16_t Qy, esp_vec128_16_t Qw, void const *Rs1, int Sel2, unsigned int sat, void *qu_out, void *qz_out, void *qv_out, unsigned int sar);
void *__builtin_riscv_esp_fft_ams_s16_ld_incp_uaup(esp_vec128_16_t Qx, esp_vec128_16_t Qy, esp_vec128_16_t Qw, void const *Rs1, int Sel2, unsigned int sat, void *qu_out, void *qz_out, void *qv_out, esp_vec128_t UaState, void *ua_ptr, unsigned int sar, unsigned int sar_bytes);
void *__builtin_riscv_esp_fft_ams_s16_ld_r32_decp(esp_vec128_16_t Qx, esp_vec128_16_t Qy, esp_vec128_16_t Qw, void const *Rs1, int Sel2, unsigned int sat, void *qu_out, void *qz_out, void *qv_out, unsigned int sar);
void *__builtin_riscv_esp_fft_ams_s16_st_incp(esp_vec128_16_t Qx, esp_vec128_16_t Qy, esp_vec128_16_t Qw, esp_vec128_t Qu, void *Rs1, void *rs2, void *qz_out, int Sel2, unsigned int sat, unsigned int sar);
void *__builtin_riscv_esp_fft_bitrev(void *Rs1, void *qv_out, unsigned int fft_bit_width);
void *__builtin_riscv_esp_fft_cmul_s16_ld_xp(esp_vec128_16_t Qx, esp_vec128_16_t Qy, void const *Rs1, void *rs2, int sel8, unsigned int sat, void *qz_out, void *qu_out, unsigned int sar);
void *__builtin_riscv_esp_fft_cmul_s16_st_xp(esp_vec128_16_t Qx, esp_vec128_16_t Qy, esp_vec128_t Qu, void *Rs1, void *rs2, int sel8, int upd4, int sel4, unsigned int sat, unsigned int sar);
void *__builtin_riscv_esp_fft_vst_r32_decp(esp_vec128_t Qu, void *Rs1, int Sel2);

// FFT.R2BF.S16 - Radix-2 Butterfly
// CHECK-LABEL: define dso_local void @test_fft_r2bf_s16_m(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST1:%.*]], ptr noundef [[DST2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.fft.r2bf.s16(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i16>, <8 x i16> } [[TMP6]], 0
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i16>, <8 x i16> } [[TMP6]], 1
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <8 x i16> [[TMP7]] to <16 x i8>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP9]], ptr [[DST1]], i32 16)
// CHECK-NEXT:    [[TMP11:%.*]] = bitcast <8 x i16> [[TMP8]] to <16 x i8>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[DST2]], i32 16)
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_r2bf_s16_m(
// CHECK-2P2-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST1:%.*]], ptr noundef [[DST2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-2P2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-2P2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-2P2-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-2P2-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.fft.r2bf.s16(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], i32 0, i32 0)
// CHECK-2P2-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i16>, <8 x i16> } [[TMP6]], 0
// CHECK-2P2-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i16>, <8 x i16> } [[TMP6]], 1
// CHECK-2P2-NEXT:    [[TMP9:%.*]] = bitcast <8 x i16> [[TMP7]] to <16 x i8>
// CHECK-2P2-NEXT:    [[TMP10:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP9]], ptr [[DST1]], i32 16)
// CHECK-2P2-NEXT:    [[TMP11:%.*]] = bitcast <8 x i16> [[TMP8]] to <16 x i8>
// CHECK-2P2-NEXT:    [[TMP12:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[DST2]], i32 16)
// CHECK-2P2-NEXT:    ret void
//
void test_fft_r2bf_s16_m(void *src1, void *src2, void *dst1, void *dst2) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_16_t Qz, Qv;
    __builtin_riscv_esp_fft_r2bf_s16(Res1.Val.V16, Res2.Val.V16, 0, 0, &Qz, &Qv);
    union { esp_vec128_t V8; esp_vec128_16_t V16; } u1, u2;
    u1.V16 = Qz;
    u2.V16 = Qv;
    (void)__builtin_riscv_esp_vst_128_ip(u1.V8, dst1, 16);
    (void)__builtin_riscv_esp_vst_128_ip(u2.V8, dst2, 16);
}

// FFT.R2BF.S16.ST.INCP
// CHECK-LABEL: define dso_local void @test_fft_r2bf_s16_st_incp_m(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, ptr } @llvm.riscv.esp.fft.r2bf.s16.st.incp(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], ptr [[DST]], i32 0, i32 0)
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_r2bf_s16_st_incp_m(
// CHECK-2P2-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-2P2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-2P2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-2P2-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-2P2-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, ptr } @llvm.riscv.esp.fft.r2bf.s16.st.incp(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], ptr [[DST]], i32 0, i32 0)
// CHECK-2P2-NEXT:    ret void
//
void test_fft_r2bf_s16_st_incp_m(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_16_t Qz;
    void *new_ptr = __builtin_riscv_esp_fft_r2bf_s16_st_incp(Res1.Val.V16, Res2.Val.V16, dst, 0, 0, &Qz);
    (void)new_ptr;
    (void)Qz;
}

// FFT.AMS.S16.LD.INCP
// CHECK-LABEL: define dso_local void @test_fft_ams_s16_ld_incp_m(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP2]] to <8 x i16>
// CHECK-NEXT:    [[ADD_PTR3:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 16
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR3]], i32 16)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP5]] to <8 x i16>
// CHECK-NEXT:    [[ADD_PTR8:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 32
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR8]], i32 16)
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <16 x i8> [[TMP8]] to <8 x i16>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { <16 x i8>, <8 x i16>, <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.ld.incp(<8 x i16> [[TMP3]], <8 x i16> [[TMP6]], <8 x i16> [[TMP9]], ptr [[SRC]], i32 0, i32 0, i32 [[TMP0]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr } [[TMP10]], 0
// CHECK-NEXT:    [[TMP12:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_ams_s16_ld_incp_m(
// CHECK-2P2-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-2P2-NEXT:    [[TMP1:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-2P2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP1]], 0
// CHECK-2P2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP2]] to <8 x i16>
// CHECK-2P2-NEXT:    [[ADD_PTR3:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 16
// CHECK-2P2-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR3]], i32 16)
// CHECK-2P2-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP4]], 0
// CHECK-2P2-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP5]] to <8 x i16>
// CHECK-2P2-NEXT:    [[ADD_PTR8:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 32
// CHECK-2P2-NEXT:    [[TMP7:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR8]], i32 16)
// CHECK-2P2-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP7]], 0
// CHECK-2P2-NEXT:    [[TMP9:%.*]] = bitcast <16 x i8> [[TMP8]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP10:%.*]] = tail call { <16 x i8>, <8 x i16>, <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.ld.incp(<8 x i16> [[TMP3]], <8 x i16> [[TMP6]], <8 x i16> [[TMP9]], ptr [[SRC]], i32 0, i32 0, i32 [[TMP0]])
// CHECK-2P2-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr } [[TMP10]], 0
// CHECK-2P2-NEXT:    [[TMP12:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[DST]], i32 16)
// CHECK-2P2-NEXT:    ret void
//
void test_fft_ams_s16_ld_incp_m(void *src, void *dst) {
    // Set SAR register before FFT AMS operation
    unsigned int sar = __builtin_riscv_esp_movx_w_sar(0);  // Initialize SAR, chain the return value
esp_vld_res_t res_qx;
  res_qx.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &res_qx.Val.V8);
esp_vld_res_t res_qy;
  res_qy.Ptr = __builtin_riscv_esp_vld_128_ip((char*)src + 16, 16, &res_qy.Val.V8);
esp_vld_res_t res_qw;
  res_qw.Ptr = __builtin_riscv_esp_vld_128_ip((char*)src + 32, 16, &res_qw.Val.V8);
    esp_vec128_t Qu;
    esp_vec128_16_t Qz, Qv;
    void *new_ptr = __builtin_riscv_esp_fft_ams_s16_ld_incp(res_qx.Val.V16, res_qy.Val.V16, res_qw.Val.V16, src, 0, 0, &Qu, &Qz, &Qv, sar);
    // Actually use return value to prevent optimization
    (void)__builtin_riscv_esp_vst_128_ip(Qu, dst, 16);
    (void)new_ptr; (void)Qz; (void)Qv;
}



// FFT.AMS.S16.LD.R32.DECP
// CHECK-LABEL: define dso_local void @test_fft_ams_s16_ld_r32_decp_m(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP2]] to <8 x i16>
// CHECK-NEXT:    [[ADD_PTR3:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 16
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR3]], i32 16)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP5]] to <8 x i16>
// CHECK-NEXT:    [[ADD_PTR8:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 32
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR8]], i32 16)
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <16 x i8> [[TMP8]] to <8 x i16>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call { <16 x i8>, <8 x i16>, <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.ld.r32.decp(<8 x i16> [[TMP3]], <8 x i16> [[TMP6]], <8 x i16> [[TMP9]], ptr [[SRC]], i32 0, i32 0, i32 [[TMP0]])
// CHECK-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr } [[TMP10]], 0
// CHECK-NEXT:    [[TMP12:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_ams_s16_ld_r32_decp_m(
// CHECK-2P2-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-2P2-NEXT:    [[TMP1:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-2P2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP1]], 0
// CHECK-2P2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP2]] to <8 x i16>
// CHECK-2P2-NEXT:    [[ADD_PTR3:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 16
// CHECK-2P2-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR3]], i32 16)
// CHECK-2P2-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP4]], 0
// CHECK-2P2-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP5]] to <8 x i16>
// CHECK-2P2-NEXT:    [[ADD_PTR8:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 32
// CHECK-2P2-NEXT:    [[TMP7:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR8]], i32 16)
// CHECK-2P2-NEXT:    [[TMP8:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP7]], 0
// CHECK-2P2-NEXT:    [[TMP9:%.*]] = bitcast <16 x i8> [[TMP8]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP10:%.*]] = tail call { <16 x i8>, <8 x i16>, <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.ld.r32.decp(<8 x i16> [[TMP3]], <8 x i16> [[TMP6]], <8 x i16> [[TMP9]], ptr [[SRC]], i32 0, i32 0, i32 [[TMP0]])
// CHECK-2P2-NEXT:    [[TMP11:%.*]] = extractvalue { <16 x i8>, <8 x i16>, <8 x i16>, ptr } [[TMP10]], 0
// CHECK-2P2-NEXT:    [[TMP12:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[DST]], i32 16)
// CHECK-2P2-NEXT:    ret void
//
void test_fft_ams_s16_ld_r32_decp_m(void *src, void *dst) {
    // Set SAR register before FFT AMS operation
    // SAR is passed explicitly as phantom operand for explicit state passing
    unsigned int sar = __builtin_riscv_esp_movx_w_sar(0);
esp_vld_res_t res_qx;
  res_qx.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &res_qx.Val.V8);
esp_vld_res_t res_qy;
  res_qy.Ptr = __builtin_riscv_esp_vld_128_ip((char*)src + 16, 16, &res_qy.Val.V8);
esp_vld_res_t res_qw;
  res_qw.Ptr = __builtin_riscv_esp_vld_128_ip((char*)src + 32, 16, &res_qw.Val.V8);
    esp_vec128_t Qu;
    esp_vec128_16_t Qz, Qv;
    void *new_ptr = __builtin_riscv_esp_fft_ams_s16_ld_r32_decp(res_qx.Val.V16, res_qy.Val.V16, res_qw.Val.V16, src, 0, 0, &Qu, &Qz, &Qv, sar);
    // Actually use return value to prevent optimization
    (void)__builtin_riscv_esp_vst_128_ip(Qu, dst, 16);
    (void)new_ptr; (void)Qz; (void)Qv;
}

// FFT.AMS.S16.ST.INCP
// CHECK-LABEL: define dso_local void @test_fft_ams_s16_st_incp_m(
// CHECK-SAME: ptr dead_on_return noundef readonly captures(none) [[TMP0:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP1:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP2:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP3:%.*]], ptr noundef [[DST:%.*]], ptr noundef [[RS2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[QX:%.*]] = load <8 x i16>, ptr [[TMP0]], align 16, !tbaa [[TBAA10:![0-9]+]]
// CHECK-NEXT:    [[QY:%.*]] = load <8 x i16>, ptr [[TMP1]], align 16, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[QW:%.*]] = load <8 x i16>, ptr [[TMP2]], align 16, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[QU:%.*]] = load <16 x i8>, ptr [[TMP3]], align 16, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP4:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = tail call { <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.st.incp(<8 x i16> [[QX]], <8 x i16> [[QY]], <8 x i16> [[QW]], <16 x i8> [[QU]], ptr [[DST]], ptr [[RS2]], i32 0, i32 0, i32 [[TMP4]])
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_ams_s16_st_incp_m(
// CHECK-2P2-SAME: ptr dead_on_return noundef readonly captures(none) [[TMP0:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP1:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP2:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP3:%.*]], ptr noundef [[DST:%.*]], ptr noundef [[RS2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[QX:%.*]] = load <8 x i16>, ptr [[TMP0]], align 16, !tbaa [[TBAA10:![0-9]+]]
// CHECK-2P2-NEXT:    [[QY:%.*]] = load <8 x i16>, ptr [[TMP1]], align 16, !tbaa [[TBAA10]]
// CHECK-2P2-NEXT:    [[QW:%.*]] = load <8 x i16>, ptr [[TMP2]], align 16, !tbaa [[TBAA10]]
// CHECK-2P2-NEXT:    [[QU:%.*]] = load <16 x i8>, ptr [[TMP3]], align 16, !tbaa [[TBAA10]]
// CHECK-2P2-NEXT:    [[TMP4:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-2P2-NEXT:    [[TMP5:%.*]] = tail call { <8 x i16>, ptr } @llvm.riscv.esp.fft.ams.s16.st.incp(<8 x i16> [[QX]], <8 x i16> [[QY]], <8 x i16> [[QW]], <16 x i8> [[QU]], ptr [[DST]], ptr [[RS2]], i32 0, i32 0, i32 [[TMP4]])
// CHECK-2P2-NEXT:    ret void
//
void test_fft_ams_s16_st_incp_m(esp_vec128_16_t Qx, esp_vec128_16_t Qy, esp_vec128_16_t Qw, esp_vec128_t Qu, void *dst, void *rs2) {
    // Set SAR register before FFT AMS operation
    unsigned int sar = __builtin_riscv_esp_movx_w_sar(0);  // Initialize SAR, chain the return value
    (void)sar;  // SAR value may be used for chaining in future
    esp_vec128_16_t Qz;
    void *new_ptr = __builtin_riscv_esp_fft_ams_s16_st_incp(Qx, Qy, Qw, Qu, dst, rs2, &Qz, 0, 0, sar);
    (void)new_ptr;
    (void)Qz;
}

// FFT.BITREV
// CHECK-LABEL: define dso_local void @test_fft_bitrev_m(
// CHECK-SAME: ptr noundef [[RS1:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { ptr, <8 x i16> } @llvm.riscv.esp.fft.bitrev.m(ptr [[RS1]], i32 4)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { ptr, <8 x i16> } [[TMP0]], 1
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16> [[TMP1]] to <16 x i8>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_bitrev_m(
// CHECK-2P2-SAME: ptr noundef [[RS1:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[TMP0:%.*]] = tail call { ptr, <8 x i16> } @llvm.riscv.esp.fft.bitrev.m(ptr [[RS1]], i32 4)
// CHECK-2P2-NEXT:    [[TMP1:%.*]] = extractvalue { ptr, <8 x i16> } [[TMP0]], 1
// CHECK-2P2-NEXT:    [[TMP2:%.*]] = bitcast <8 x i16> [[TMP1]] to <16 x i8>
// CHECK-2P2-NEXT:    [[TMP3:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP2]], ptr [[DST]], i32 16)
// CHECK-2P2-NEXT:    ret void
//
void test_fft_bitrev_m(void *Rs1, void *dst) {
    esp_vec128_16_t Qv;
    // FFT_BIT_WIDTH = 4 (for 4-bit bit reversal)
    void *new_ptr = __builtin_riscv_esp_fft_bitrev_m(Rs1, &Qv, 4);
    // Actually use return value to prevent optimization
    union { esp_vec128_t V8; esp_vec128_16_t V16; } u = {.V16 = Qv};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
    (void)new_ptr;
}

// FFT.CMUL.S16.LD.XP
// CHECK-LABEL: define dso_local void @test_fft_cmul_s16_ld_xp_m(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[RS2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP1]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP2]] to <8 x i16>
// CHECK-NEXT:    [[ADD_PTR3:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 16
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR3]], i32 16)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP5]] to <8 x i16>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.fft.cmul.s16.ld.xp(<8 x i16> [[TMP3]], <8 x i16> [[TMP6]], ptr [[SRC]], ptr [[RS2]], i32 0, i32 0, i32 [[TMP0]])
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i16>, <16 x i8>, ptr } [[TMP7]], 1
// CHECK-NEXT:    [[TMP9:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_cmul_s16_ld_xp_m(
// CHECK-2P2-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[RS2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-2P2-NEXT:    [[TMP1:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-2P2-NEXT:    [[TMP2:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP1]], 0
// CHECK-2P2-NEXT:    [[TMP3:%.*]] = bitcast <16 x i8> [[TMP2]] to <8 x i16>
// CHECK-2P2-NEXT:    [[ADD_PTR3:%.*]] = getelementptr inbounds nuw i8, ptr [[SRC]], i32 16
// CHECK-2P2-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr nonnull [[ADD_PTR3]], i32 16)
// CHECK-2P2-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP4]], 0
// CHECK-2P2-NEXT:    [[TMP6:%.*]] = bitcast <16 x i8> [[TMP5]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP7:%.*]] = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.fft.cmul.s16.ld.xp(<8 x i16> [[TMP3]], <8 x i16> [[TMP6]], ptr [[SRC]], ptr [[RS2]], i32 0, i32 0, i32 [[TMP0]])
// CHECK-2P2-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i16>, <16 x i8>, ptr } [[TMP7]], 1
// CHECK-2P2-NEXT:    [[TMP9:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[DST]], i32 16)
// CHECK-2P2-NEXT:    ret void
//
void test_fft_cmul_s16_ld_xp_m(void *src, void *rs2, void *dst) {
    // Set SAR register before FFT CMUL operation
    unsigned int sar = __builtin_riscv_esp_movx_w_sar(0);  // Initialize SAR, chain the return value
esp_vld_res_t res_qx;
  res_qx.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &res_qx.Val.V8);
esp_vld_res_t res_qy;
  res_qy.Ptr = __builtin_riscv_esp_vld_128_ip((char*)src + 16, 16, &res_qy.Val.V8);
    esp_vec128_16_t Qz;
    esp_vec128_t Qu;
    void *new_ptr = __builtin_riscv_esp_fft_cmul_s16_ld_xp(res_qx.Val.V16, res_qy.Val.V16, src, rs2, 0, 0, &Qz, &Qu, sar);
    // Actually use return value to prevent optimization
    (void)__builtin_riscv_esp_vst_128_ip(Qu, dst, 16);
    (void)new_ptr; (void)Qz;
}

// FFT.CMUL.S16.ST.XP
// CHECK-LABEL: define dso_local void @test_fft_cmul_s16_st_xp_m(
// CHECK-SAME: ptr dead_on_return noundef readonly captures(none) [[TMP0:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP1:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP2:%.*]], ptr noundef [[DST:%.*]], ptr noundef [[RS2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[QX:%.*]] = load <8 x i16>, ptr [[TMP0]], align 16, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[QY:%.*]] = load <8 x i16>, ptr [[TMP1]], align 16, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[QU:%.*]] = load <16 x i8>, ptr [[TMP2]], align 16, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = tail call ptr @llvm.riscv.esp.fft.cmul.s16.st.xp(<8 x i16> [[QX]], <8 x i16> [[QY]], <16 x i8> [[QU]], ptr [[DST]], ptr [[RS2]], i32 0, i32 0, i32 0, i32 0, i32 [[TMP3]])
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_cmul_s16_st_xp_m(
// CHECK-2P2-SAME: ptr dead_on_return noundef readonly captures(none) [[TMP0:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP1:%.*]], ptr dead_on_return noundef readonly captures(none) [[TMP2:%.*]], ptr noundef [[DST:%.*]], ptr noundef [[RS2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[QX:%.*]] = load <8 x i16>, ptr [[TMP0]], align 16, !tbaa [[TBAA10]]
// CHECK-2P2-NEXT:    [[QY:%.*]] = load <8 x i16>, ptr [[TMP1]], align 16, !tbaa [[TBAA10]]
// CHECK-2P2-NEXT:    [[QU:%.*]] = load <16 x i8>, ptr [[TMP2]], align 16, !tbaa [[TBAA10]]
// CHECK-2P2-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.riscv.esp.movx.w.sar(i32 0)
// CHECK-2P2-NEXT:    [[TMP4:%.*]] = tail call ptr @llvm.riscv.esp.fft.cmul.s16.st.xp(<8 x i16> [[QX]], <8 x i16> [[QY]], <16 x i8> [[QU]], ptr [[DST]], ptr [[RS2]], i32 0, i32 0, i32 0, i32 0, i32 [[TMP3]])
// CHECK-2P2-NEXT:    ret void
//
void test_fft_cmul_s16_st_xp_m(esp_vec128_16_t Qx, esp_vec128_16_t Qy, esp_vec128_t Qu, void *dst, void *rs2) {
    // Set SAR register before FFT CMUL operation
    unsigned int sar = __builtin_riscv_esp_movx_w_sar(0);  // Initialize SAR, chain the return value
    (void)sar;  // SAR value may be used for chaining in future
    void *new_ptr = __builtin_riscv_esp_fft_cmul_s16_st_xp(Qx, Qy, Qu, dst, rs2, 0, 0, 0, 0, sar);
    (void)new_ptr;
}

// FFT.VST.R32.DECP
// CHECK-LABEL: define dso_local void @test_fft_vst_r32_decp_m(
// CHECK-SAME: ptr dead_on_return noundef readonly captures(none) [[TMP0:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[QU:%.*]] = load <16 x i8>, ptr [[TMP0]], align 16, !tbaa [[TBAA10]]
// CHECK-NEXT:    [[TMP1:%.*]] = tail call ptr @llvm.riscv.esp.fft.vst.r32.decp.m(<16 x i8> [[QU]], ptr [[DST]], i32 0)
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_vst_r32_decp_m(
// CHECK-2P2-SAME: ptr dead_on_return noundef readonly captures(none) [[TMP0:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[QU:%.*]] = load <16 x i8>, ptr [[TMP0]], align 16, !tbaa [[TBAA10]]
// CHECK-2P2-NEXT:    [[TMP1:%.*]] = tail call ptr @llvm.riscv.esp.fft.vst.r32.decp.m(<16 x i8> [[QU]], ptr [[DST]], i32 0)
// CHECK-2P2-NEXT:    ret void
//
void test_fft_vst_r32_decp_m(esp_vec128_t Qu, void *dst) {
    void *new_ptr = __builtin_riscv_esp_fft_vst_r32_decp_m(Qu, dst, 0);
    (void)new_ptr;
}

// FFT pipeline: Load -> Butterfly -> Store
// CHECK-LABEL: define dso_local void @test_fft_pipeline_complete_m(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST1:%.*]], ptr noundef [[DST2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.fft.r2bf.s16(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i16>, <8 x i16> } [[TMP6]], 0
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i16>, <8 x i16> } [[TMP6]], 1
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <8 x i16> [[TMP7]] to <16 x i8>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP9]], ptr [[DST1]], i32 16)
// CHECK-NEXT:    [[TMP11:%.*]] = bitcast <8 x i16> [[TMP8]] to <16 x i8>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[DST2]], i32 16)
// CHECK-NEXT:    ret void
//
// CHECK-2P2-LABEL: define dso_local void @test_fft_pipeline_complete_m(
// CHECK-2P2-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST1:%.*]], ptr noundef [[DST2:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-2P2-NEXT:  [[ENTRY:.*:]]
// CHECK-2P2-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-2P2-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-2P2-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-2P2-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-2P2-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-2P2-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, <8 x i16> } @llvm.riscv.esp.fft.r2bf.s16(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], i32 0, i32 0)
// CHECK-2P2-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i16>, <8 x i16> } [[TMP6]], 0
// CHECK-2P2-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i16>, <8 x i16> } [[TMP6]], 1
// CHECK-2P2-NEXT:    [[TMP9:%.*]] = bitcast <8 x i16> [[TMP7]] to <16 x i8>
// CHECK-2P2-NEXT:    [[TMP10:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP9]], ptr [[DST1]], i32 16)
// CHECK-2P2-NEXT:    [[TMP11:%.*]] = bitcast <8 x i16> [[TMP8]] to <16 x i8>
// CHECK-2P2-NEXT:    [[TMP12:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP11]], ptr [[DST2]], i32 16)
// CHECK-2P2-NEXT:    ret void
//
void test_fft_pipeline_complete_m(void *src1, void *src2, void *dst1, void *dst2) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_16_t Qz, Qv;
    __builtin_riscv_esp_fft_r2bf_s16(Res1.Val.V16, Res2.Val.V16, 0, 0, &Qz, &Qv);
    union { esp_vec128_t V8; esp_vec128_16_t V16; } u1, u2;
    u1.V16 = Qz;
    u2.V16 = Qv;
    (void)__builtin_riscv_esp_vst_128_ip(u1.V8, dst1, 16);
    (void)__builtin_riscv_esp_vst_128_ip(u2.V8, dst2, 16);
}

//.
// CHECK: [[META8:![0-9]+]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
// CHECK: [[META9]] = !{!"Simple C/C++ TBAA"}
// CHECK: [[TBAA10]] = !{[[META8]], [[META8]], i64 0}
//.
// CHECK-2P2: [[META8:![0-9]+]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
// CHECK-2P2: [[META9]] = !{!"Simple C/C++ TBAA"}
// CHECK-2P2: [[TBAA10]] = !{[[META8]], [[META8]], i64 0}
//.
