// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// Test IR generation (Builtin -> Intrinsic)
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s

#include <stdint.h>
#include <riscv_esp32p4.h>

// Test ZERO.QACC - Zero QACC accumulator
// QACC is used internally, stored to memory to ensure complete Data flow
// CHECK-LABEL: define dso_local ptr @test_zero_qacc(
// CHECK-SAME: ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.zero.qacc.m()
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip.m(<16 x i8> [[TMP1]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret ptr [[TMP2]]
//
void *test_zero_qacc(void *dst) {
esp_qacc_4x128_t qacc;
  __builtin_riscv_esp_zero_qacc_m(&qacc.v0, &qacc.v1, &qacc.v2, &qacc.v3);
    // Store QACC_L[127:0] to memory to ensure complete Data flow
    return __builtin_riscv_esp_st_qacc_l_l_128_ip_m(qacc.v0, dst, 16);
}

// Test MOV.S8.QACC - Move vector to QACC (S8)
// QACC is used internally, stored to memory to ensure complete Data flow
// CHECK-LABEL: define dso_local ptr @test_mov_s8_qacc(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s8.qacc.m(<16 x i8> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip.m(<16 x i8> [[TMP3]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret ptr [[TMP4]]
//
void *test_mov_s8_qacc(void const *src, void *dst) {
esp_vld_res_t Res;
  Res.Ptr = __builtin_riscv_esp_vld_128_ip_m(src, 16, &Res.Val.V8);
esp_mov_qacc_res_t qacc;
  __builtin_riscv_esp_mov_s8_qacc_m(Res.Val.V8, &qacc.v0, &qacc.v1, &qacc.v2, &qacc.v3);
    // Store QACC_L[127:0] to memory to ensure complete Data flow
    return __builtin_riscv_esp_st_qacc_l_l_128_ip_m(qacc.v0, dst, 16);
}

// Test MOV.S16.QACC - Move vector to QACC (S16)
// QACC is used internally, stored to memory to ensure complete Data flow
// CHECK-LABEL: define dso_local ptr @test_mov_s16_qacc(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR3]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip.m(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } @llvm.riscv.esp.mov.s16.qacc.m(<8 x i16> [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, <16 x i8>, <16 x i8>, <16 x i8> } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip.m(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret ptr [[TMP5]]
//
void *test_mov_s16_qacc(void const *src, void *dst) {
esp_vld_res_t Res;
  Res.Ptr = __builtin_riscv_esp_vld_128_ip_m(src, 16, &Res.Val.V8);
esp_mov_qacc_res_t qacc;
  __builtin_riscv_esp_mov_s16_qacc_m(Res.Val.V16, &qacc.v0, &qacc.v1, &qacc.v2, &qacc.v3);
    // Store QACC_L[127:0] to memory to ensure complete Data flow
    return __builtin_riscv_esp_st_qacc_l_l_128_ip_m(qacc.v0, dst, 16);
}
