// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// Test IR generation (Builtin -> Intrinsic)
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s

#include <riscv_esp32p4.h>

// Additional type definitions
esp_vec128_32_t __builtin_riscv_esp_vadd_s32(esp_vec128_32_t, esp_vec128_32_t, int);
esp_vec128_32_t __builtin_riscv_esp_vadd_u32(esp_vec128_32_t, esp_vec128_32_t, int);
esp_vec128_32_t __builtin_riscv_esp_vsub_s32(esp_vec128_32_t, esp_vec128_32_t, int);
esp_vec128_32_t __builtin_riscv_esp_vsub_u32(esp_vec128_32_t, esp_vec128_32_t, int);
esp_vec128_32_t __builtin_riscv_esp_vmax_s32(esp_vec128_32_t, esp_vec128_32_t);
esp_vec128_32_t __builtin_riscv_esp_vmin_s32(esp_vec128_32_t, esp_vec128_32_t);
esp_vec128_32_t __builtin_riscv_esp_vmax_u32(esp_vec128_32_t, esp_vec128_32_t);
esp_vec128_32_t __builtin_riscv_esp_vmin_u32(esp_vec128_32_t, esp_vec128_32_t);
esp_vec128_32_t __builtin_riscv_esp_vabs_32(esp_vec128_32_t);
esp_vec128_32_t __builtin_riscv_esp_vsat_s32(esp_vec128_32_t, int, int);
esp_vec128_32_t __builtin_riscv_esp_vsat_u32(esp_vec128_32_t, int, int);
int __builtin_riscv_esp_max_s32_a(esp_vec128_32_t);
int __builtin_riscv_esp_min_s32_a(esp_vec128_32_t);
int __builtin_riscv_esp_max_u32_a(esp_vec128_32_t);
int __builtin_riscv_esp_min_u32_a(esp_vec128_32_t);
esp_vec128_32_t __builtin_riscv_esp_vcmp_eq_s32(esp_vec128_32_t,
                                                  esp_vec128_32_t);
esp_vec128_32_t __builtin_riscv_esp_vcmp_gt_s32(esp_vec128_32_t,
                                                  esp_vec128_32_t);
esp_vec128_32_t __builtin_riscv_esp_vcmp_lt_s32(esp_vec128_32_t,
                                                  esp_vec128_32_t);
// VCMP.EQ.U / VCMP.GT.U: +xespv2p1 only (Sema/esp32p4-vcmp-u21-only.c).
esp_vec128_32_t __builtin_riscv_esp_vcmp_lt_u32(esp_vec128_32_t,
                                                  esp_vec128_32_t);
void *__builtin_riscv_esp_vst_128_ip(esp_vec128_t Data, void *Ptr, int Imm);

// Vector addition (32-bit)
// CHECK-LABEL: define dso_local void @test_vadd_s32(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vadd.s32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vadd_s32(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_32_t sum = __builtin_riscv_esp_vadd_s32(Res1.Val.V32, Res2.Val.V32, 0);
    union { esp_vec128_t V8; esp_vec128_32_t V32; } u = {.V32 = sum};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vadd_u32(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vadd.u32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vadd_u32(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_32_t sum = __builtin_riscv_esp_vadd_u32(Res1.Val.V32, Res2.Val.V32, 0);
    union { esp_vec128_t V8; esp_vec128_32_t V32; } u = {.V32 = sum};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// Vector subtraction (32-bit)
// CHECK-LABEL: define dso_local void @test_vsub_s32(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vsub.s32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vsub_s32(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_32_t diff = __builtin_riscv_esp_vsub_s32(Res1.Val.V32, Res2.Val.V32, 0);
    union { esp_vec128_t V8; esp_vec128_32_t V32; } u = {.V32 = diff};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// Vector max/min (32-bit)
// CHECK-LABEL: define dso_local void @test_vmax_s32(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vmax.s32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vmax_s32(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_32_t max_val = __builtin_riscv_esp_vmax_s32(Res1.Val.V32, Res2.Val.V32);
    union { esp_vec128_t V8; esp_vec128_32_t V32; } u = {.V32 = max_val};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// Vector absolute value (32-bit)
// CHECK-LABEL: define dso_local void @test_vabs_32(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vabs.32(<4 x i32> [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <4 x i32> [[TMP3]] to <16 x i8>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vabs_32(void *src, void *dst) {
esp_vld_res_t Res;
  Res.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &Res.Val.V8);
    esp_vec128_32_t abs_val = __builtin_riscv_esp_vabs_32(Res.Val.V32);
    union { esp_vec128_t V8; esp_vec128_32_t V32; } u = {.V32 = abs_val};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// Reduction operations (max/min) - 32-bit
// CHECK-LABEL: define dso_local i32 @test_max_s32(
// CHECK-SAME: ptr noundef [[SRC:%.*]]) local_unnamed_addr #[[ATTR4:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.riscv.esp.max.s32.a(<4 x i32> [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_max_s32(void *src) {
esp_vld_res_t Res;
  Res.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &Res.Val.V8);
    return __builtin_riscv_esp_max_s32_a(Res.Val.V32);
}

// CHECK-LABEL: define dso_local i32 @test_min_s32(
// CHECK-SAME: ptr noundef [[SRC:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.riscv.esp.min.s32.a(<4 x i32> [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_min_s32(void *src) {
esp_vld_res_t Res;
  Res.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &Res.Val.V8);
    return __builtin_riscv_esp_min_s32_a(Res.Val.V32);
}

// Additional ESPVM 32-bit coverage (see esp32p4-espvm-mc-coverage.md).
// CHECK-LABEL: define dso_local void @test_vmax_u32_vec(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vmax.u32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vmax_u32_vec(void *src1, void *src2, void *dst) {
esp_vld_res_t R1;
  R1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &R1.Val.V8);
esp_vld_res_t R2;
  R2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &R2.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vmax_u32(R1.Val.V32, R2.Val.V32);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vmin_s32_vec(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vmin.s32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vmin_s32_vec(void *src1, void *src2, void *dst) {
esp_vld_res_t R1;
  R1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &R1.Val.V8);
esp_vld_res_t R2;
  R2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &R2.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vmin_s32(R1.Val.V32, R2.Val.V32);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vmin_u32_vec(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vmin.u32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vmin_u32_vec(void *src1, void *src2, void *dst) {
esp_vld_res_t R1;
  R1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &R1.Val.V8);
esp_vld_res_t R2;
  R2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &R2.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vmin_u32(R1.Val.V32, R2.Val.V32);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vcmp_eq_s32_vec(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vcmp.eq.s32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vcmp_eq_s32_vec(void *src1, void *src2, void *dst) {
esp_vld_res_t R1;
  R1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &R1.Val.V8);
esp_vld_res_t R2;
  R2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &R2.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vcmp_eq_s32(R1.Val.V32, R2.Val.V32);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vcmp_gt_s32_vec(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vcmp.gt.s32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vcmp_gt_s32_vec(void *src1, void *src2, void *dst) {
esp_vld_res_t R1;
  R1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &R1.Val.V8);
esp_vld_res_t R2;
  R2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &R2.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vcmp_gt_s32(R1.Val.V32, R2.Val.V32);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vcmp_lt_s32_vec(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vcmp.lt.s32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vcmp_lt_s32_vec(void *src1, void *src2, void *dst) {
esp_vld_res_t R1;
  R1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &R1.Val.V8);
esp_vld_res_t R2;
  R2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &R2.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vcmp_lt_s32(R1.Val.V32, R2.Val.V32);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vcmp_lt_u32_vec(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vcmp.lt.u32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]])
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vcmp_lt_u32_vec(void *src1, void *src2, void *dst) {
esp_vld_res_t R1;
  R1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &R1.Val.V8);
esp_vld_res_t R2;
  R2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &R2.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vcmp_lt_u32(R1.Val.V32, R2.Val.V32);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vsat_s32_vec(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vsat.s32(<4 x i32> [[TMP2]], i32 -128, i32 127)
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <4 x i32> [[TMP3]] to <16 x i8>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vsat_s32_vec(void *src, void *dst) {
esp_vld_res_t R;
  R.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &R.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vsat_s32(R.Val.V32, -128, 127);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vsat_u32_vec(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vsat.u32(<4 x i32> [[TMP2]], i32 0, i32 65535)
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <4 x i32> [[TMP3]] to <16 x i8>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vsat_u32_vec(void *src, void *dst) {
esp_vld_res_t R;
  R.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &R.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vsat_u32(R.Val.V32, 0, 65535);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local void @test_vsub_u32_vec(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <4 x i32>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i32> @llvm.riscv.esp.vsub.u32(<4 x i32> [[TMP2]], <4 x i32> [[TMP5]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i32> [[TMP6]] to <16 x i8>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP7]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vsub_u32_vec(void *src1, void *src2, void *dst) {
esp_vld_res_t R1;
  R1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &R1.Val.V8);
esp_vld_res_t R2;
  R2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &R2.Val.V8);
    esp_vec128_32_t V =
        __builtin_riscv_esp_vsub_u32(R1.Val.V32, R2.Val.V32, 0);
    union {
        esp_vec128_t V8;
        esp_vec128_32_t V32;
    } u = {.V32 = V};
    (void)__builtin_riscv_esp_vst_128_ip(u.V8, dst, 16);
}

// CHECK-LABEL: define dso_local i32 @test_max_u32_a_vec(
// CHECK-SAME: ptr noundef [[SRC:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.riscv.esp.max.u32.a(<4 x i32> [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_max_u32_a_vec(void *src) {
esp_vld_res_t R;
  R.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &R.Val.V8);
    return __builtin_riscv_esp_max_u32_a(R.Val.V32);
}

// CHECK-LABEL: define dso_local i32 @test_min_u32_a_vec(
// CHECK-SAME: ptr noundef [[SRC:%.*]]) local_unnamed_addr #[[ATTR4]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <4 x i32>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.riscv.esp.min.u32.a(<4 x i32> [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_min_u32_a_vec(void *src) {
esp_vld_res_t R;
  R.Ptr = __builtin_riscv_esp_vld_128_ip(src, 16, &R.Val.V8);
    return __builtin_riscv_esp_min_u32_a(R.Val.V32);
}

