// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// Test IR generation (Builtin -> Intrinsic)
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s


#include <stdint.h>
#include <riscv_esp32p4.h>

// Additional type definitions






// VADD LD.INCP (8-bit)
// CHECK-LABEL: define dso_local void @test_vadd_s8_ld_incp_simple(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.vadd.s8.ld.incp(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], ptr [[SRC1]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vadd_s8_ld_incp_simple(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
esp_vop_ld_incp_res_t vadd_res;
  vadd_res.Ptr =
      __builtin_riscv_esp_vadd_s8_ld_incp(Res1.Val.V8, Res2.Val.V8, src1, &vadd_res.Qv.v8, &vadd_res.Qu, 0);
    // Actually use return value to prevent optimization
    (void)__builtin_riscv_esp_vst_128_ip(vadd_res.Qv.v8, dst, 16);
    (void)vadd_res.Qu; (void)vadd_res.Ptr;
}

// CHECK-LABEL: define dso_local void @test_vadd_u8_ld_incp_simple(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.vadd.u8.ld.incp(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], ptr [[SRC1]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP5]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vadd_u8_ld_incp_simple(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
esp_vop_ld_incp_res_t vadd_res;
  vadd_res.Ptr =
      __builtin_riscv_esp_vadd_u8_ld_incp(Res1.Val.V8, Res2.Val.V8, src1, &vadd_res.Qv.v8, &vadd_res.Qu, 0);
    // Actually use return value to prevent optimization
    (void)__builtin_riscv_esp_vst_128_ip(vadd_res.Qv.v8, dst, 16);
    (void)vadd_res.Qu; (void)vadd_res.Ptr;
}

// CHECK-LABEL: define dso_local void @test_vadd_s16_ld_incp_simple(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.vadd.s16.ld.incp(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], ptr [[SRC1]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i16>, <16 x i8>, ptr } [[TMP6]], 0
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <8 x i16> [[TMP7]] to <16 x i8>
// CHECK-NEXT:    [[TMP9:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vadd_s16_ld_incp_simple(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_16_t Qx = Res1.Val.V16;
    esp_vec128_16_t Qy = Res2.Val.V16;
esp_vop_ld_incp_res_t vadd_res;
  // qv_out is esp_vec128_t*; vadd_res.Qv.v8 and vadd_res.Qv.v16 alias the same 128 bits.
  vadd_res.Ptr =
      __builtin_riscv_esp_vadd_s16_ld_incp(Qx, Qy, src1, &vadd_res.Qv.v8, &vadd_res.Qu, 0);
    // Actually use return value to prevent optimization
    (void)__builtin_riscv_esp_vst_128_ip(vadd_res.Qv.v8, dst, 16);
    (void)vadd_res.Qu; (void)vadd_res.Ptr;
}

// CHECK-LABEL: define dso_local void @test_vadd_u16_ld_incp_simple(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.vadd.u16.ld.incp(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], ptr [[SRC1]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i16>, <16 x i8>, ptr } [[TMP6]], 0
// CHECK-NEXT:    [[TMP8:%.*]] = bitcast <8 x i16> [[TMP7]] to <16 x i8>
// CHECK-NEXT:    [[TMP9:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP8]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vadd_u16_ld_incp_simple(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_16_t Qx = Res1.Val.V16;
    esp_vec128_16_t Qy = Res2.Val.V16;
esp_vop_ld_incp_res_t vadd_res;
  vadd_res.Ptr =
      __builtin_riscv_esp_vadd_u16_ld_incp(Qx, Qy, src1, &vadd_res.Qv.v8, &vadd_res.Qu, 0);
    // Actually use return value to prevent optimization
    (void)__builtin_riscv_esp_vst_128_ip(vadd_res.Qv.v8, dst, 16);
    (void)vadd_res.Qu; (void)vadd_res.Ptr;
}

// VADD ST.INCP (8-bit)
// CHECK-LABEL: define dso_local void @test_vadd_s8_st_incp(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.vadd.s8.ld.incp(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], ptr [[SRC1]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vadd.s8.st.incp(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], <16 x i8> [[TMP6]], ptr [[DST]], <16 x i8> [[TMP5]], i32 0)
// CHECK-NEXT:    ret void
//
void test_vadd_s8_st_incp(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
esp_vop_ld_incp_res_t vadd_res;
  vadd_res.Ptr =
      __builtin_riscv_esp_vadd_s8_ld_incp(Res1.Val.V8, Res2.Val.V8, src1, &vadd_res.Qv.v8, &vadd_res.Qu, 0);
    esp_vec128_t Qv = vadd_res.Qv.v8;
    esp_vec128_t Qu = vadd_res.Qu;
    __builtin_riscv_esp_vadd_s8_st_incp(Res1.Val.V8, Res2.Val.V8, Qu, dst, Qv, 0);
}

// CHECK-LABEL: define dso_local void @test_vadd_u8_st_incp(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call { <16 x i8>, <16 x i8>, ptr } @llvm.riscv.esp.vadd.u8.ld.incp(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], ptr [[SRC1]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[TMP4]], 0
// CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <16 x i8>, <16 x i8>, ptr } [[TMP4]], 1
// CHECK-NEXT:    [[TMP7:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vadd.u8.st.incp(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], <16 x i8> [[TMP6]], ptr [[DST]], <16 x i8> [[TMP5]], i32 0)
// CHECK-NEXT:    ret void
//
void test_vadd_u8_st_incp(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
esp_vop_ld_incp_res_t vadd_res;
  vadd_res.Ptr =
      __builtin_riscv_esp_vadd_u8_ld_incp(Res1.Val.V8, Res2.Val.V8, src1, &vadd_res.Qv.v8, &vadd_res.Qu, 0);
    esp_vec128_t Qv = vadd_res.Qv.v8;
    esp_vec128_t Qu = vadd_res.Qu;
    __builtin_riscv_esp_vadd_u8_st_incp(Res1.Val.V8, Res2.Val.V8, Qu, dst, Qv, 0);
}

// CHECK-LABEL: define dso_local void @test_vadd_s16_st_incp(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.vadd.s16.ld.incp(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], ptr [[SRC1]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i16>, <16 x i8>, ptr } [[TMP6]], 0
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i16>, <16 x i8>, ptr } [[TMP6]], 1
// CHECK-NEXT:    [[TMP9:%.*]] = tail call { <8 x i16>, ptr } @llvm.riscv.esp.vadd.s16.st.incp(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], <16 x i8> [[TMP8]], ptr [[DST]], <8 x i16> [[TMP7]], i32 0)
// CHECK-NEXT:    ret void
//
void test_vadd_s16_st_incp(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_16_t Qx = Res1.Val.V16;
    esp_vec128_16_t Qy = Res2.Val.V16;
esp_vop_ld_incp_res_t vadd_res;
  // qv_out is esp_vec128_t*; vadd_res.Qv.v8 and vadd_res.Qv.v16 alias the same 128 bits.
  vadd_res.Ptr =
      __builtin_riscv_esp_vadd_s16_ld_incp(Qx, Qy, src1, &vadd_res.Qv.v8, &vadd_res.Qu, 0);
    esp_vec128_16_t Qv = vadd_res.Qv.v16;
    esp_vec128_t Qu = vadd_res.Qu;
    __builtin_riscv_esp_vadd_s16_st_incp(Qx, Qy, Qu, dst, Qv, 0);
}

// CHECK-LABEL: define dso_local void @test_vadd_u16_st_incp(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = bitcast <16 x i8> [[TMP1]] to <8 x i16>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP3]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = bitcast <16 x i8> [[TMP4]] to <8 x i16>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call { <8 x i16>, <16 x i8>, ptr } @llvm.riscv.esp.vadd.u16.ld.incp(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], ptr [[SRC1]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <8 x i16>, <16 x i8>, ptr } [[TMP6]], 0
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <8 x i16>, <16 x i8>, ptr } [[TMP6]], 1
// CHECK-NEXT:    [[TMP9:%.*]] = tail call { <8 x i16>, ptr } @llvm.riscv.esp.vadd.u16.st.incp(<8 x i16> [[TMP2]], <8 x i16> [[TMP5]], <16 x i8> [[TMP8]], ptr [[DST]], <8 x i16> [[TMP7]], i32 0)
// CHECK-NEXT:    ret void
//
void test_vadd_u16_st_incp(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_16_t Qx = Res1.Val.V16;
    esp_vec128_16_t Qy = Res2.Val.V16;
esp_vop_ld_incp_res_t vadd_res;
  vadd_res.Ptr =
      __builtin_riscv_esp_vadd_u16_ld_incp(Qx, Qy, src1, &vadd_res.Qv.v8, &vadd_res.Qu, 0);
    esp_vec128_16_t Qv = vadd_res.Qv.v16;
    esp_vec128_t Qu = vadd_res.Qu;
    __builtin_riscv_esp_vadd_u16_st_incp(Qx, Qy, Qu, dst, Qv, 0);
}

