// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// Test IR generation (Builtin -> Intrinsic)
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s

#include <stdint.h>
#include <riscv_esp32p4.h>
esp_vec128_t __builtin_riscv_esp_vadd_s8(esp_vec128_t, esp_vec128_t, int);
esp_vec128_t __builtin_riscv_esp_vadd_u8(esp_vec128_t, esp_vec128_t, int);
esp_vec128_t __builtin_riscv_esp_vsub_s8(esp_vec128_t, esp_vec128_t, int);
esp_vec128_t __builtin_riscv_esp_vsub_u8(esp_vec128_t, esp_vec128_t, int);


// Vector addition (8-bit)
// CHECK-LABEL: define dso_local void @test_vadd_s8(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <16 x i8> @llvm.riscv.esp.vadd.s8(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vadd_s8(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_t sum = __builtin_riscv_esp_vadd_s8(Res1.Val.V8, Res2.Val.V8, 0);
    (void)__builtin_riscv_esp_vst_128_ip(sum, dst, 16);
}

//


// CHECK-LABEL: define dso_local void @test_vadd_u8(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <16 x i8> @llvm.riscv.esp.vadd.u8(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vadd_u8(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_t sum = __builtin_riscv_esp_vadd_u8(Res1.Val.V8, Res2.Val.V8, 0);
    (void)__builtin_riscv_esp_vst_128_ip(sum, dst, 16);
}

// Vector subtraction (8-bit)
//


// Vector subtraction (8-bit)
// CHECK-LABEL: define dso_local void @test_vsub_s8(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <16 x i8> @llvm.riscv.esp.vsub.s8(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vsub_s8(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_t diff = __builtin_riscv_esp_vsub_s8(Res1.Val.V8, Res2.Val.V8, 0);
    (void)__builtin_riscv_esp_vst_128_ip(diff, dst, 16);
}

//


// CHECK-LABEL: define dso_local void @test_vsub_u8(
// CHECK-SAME: ptr noundef [[SRC1:%.*]], ptr noundef [[SRC2:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC1]], i32 16)
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[SRC2]], i32 16)
// CHECK-NEXT:    [[TMP3:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <16 x i8> @llvm.riscv.esp.vsub.u8(<16 x i8> [[TMP1]], <16 x i8> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[TMP4]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret void
//
void test_vsub_u8(void *src1, void *src2, void *dst) {
esp_vld_res_t Res1;
  Res1.Ptr = __builtin_riscv_esp_vld_128_ip(src1, 16, &Res1.Val.V8);
esp_vld_res_t Res2;
  Res2.Ptr = __builtin_riscv_esp_vld_128_ip(src2, 16, &Res2.Val.V8);
    esp_vec128_t diff = __builtin_riscv_esp_vsub_u8(Res1.Val.V8, Res2.Val.V8, 0);
    (void)__builtin_riscv_esp_vst_128_ip(diff, dst, 16);
}

// Vector multiplication (8-bit)
//

