// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// Test IR generation (Builtin -> Intrinsic)
// RUN: %clang_cc1 -internal-isystem %S/../../../../lib/Headers -triple riscv32 -target-feature +xespv -emit-llvm -O1 -o - %s \
// RUN: | FileCheck %s

// LDQA/MOV/VMULAS/VCMULAS/SRCMB _m coverage lives in a follow-up MR once EmitRISCVBuiltinExpr
// supports those builtin IDs (current clang aborts with "unexpected builtin ID").

#include <stdint.h>
#include <riscv_esp32p4.h>

// ESP.LD.QACC.H.L.128.IP + ESP.ST.QACC.H.L.128.IP - Load and store QACC_H[127:0] (_m version)
// Load: QACC_H[127:0] = load128(src), src = src + (Imm << 4)
// Store: MEM(dst) = QACC_H[127:0], dst = dst + (Imm << 4)
// Offset range: -2048 to 2032, step 16
// CHECK-LABEL: define dso_local ptr @test_ld_st_qacc_h_l_128_ip_m(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.h.l.128.ip.m(ptr [[SRC]], i32 16), !noalias [[META6:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call ptr @llvm.riscv.esp.st.qacc.h.l.128.ip.m(<16 x i8> [[TMP1]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret ptr [[TMP2]]
//
void *test_ld_st_qacc_h_l_128_ip_m(void const *src, void *dst) {
    // Load 128-bit Data to QACC_H[127:0]
    // Returns structure with QACC_H value and updated pointer
    esp_qacc_128_res_t Res = esp_ld_qacc_h_l_128_ip_m(src, 16);
    // Store QACC_H[127:0] to memory
    // Pass QACC_H value for explicit state passing Data flow
    return __builtin_riscv_esp_st_qacc_h_l_128_ip_m(Res.qacc_128, dst, 16);
}

// ESP.LD.QACC.L.H.128.IP + ESP.ST.QACC.L.H.128.IP - Load and store QACC_L[255:128] (_m version)
// Load: QACC_L[255:128] = load128(src), src = src + (Imm << 4)
// Store: MEM(dst) = QACC_L[255:128], dst = dst + (Imm << 4)
// Offset range: -2048 to 2032, step 16
// CHECK-LABEL: define dso_local ptr @test_ld_st_qacc_l_h_128_ip_m(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.l.h.128.ip.m(ptr [[SRC]], i32 16), !noalias [[META9:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call ptr @llvm.riscv.esp.st.qacc.l.h.128.ip.m(<16 x i8> [[TMP1]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret ptr [[TMP2]]
//
void *test_ld_st_qacc_l_h_128_ip_m(void const *src, void *dst) {
    // Load 128-bit Data to QACC_L[255:128]
    // Returns structure with QACC_L value and updated pointer
    esp_qacc_128_res_t Res = esp_ld_qacc_l_h_128_ip_m(src, 16);
    // Store QACC_L[255:128] to memory
    // Pass QACC_L value for explicit state passing Data flow
    return __builtin_riscv_esp_st_qacc_l_h_128_ip_m(Res.qacc_128, dst, 16);
}

// ESP.LD.QACC.H.H.128.IP + ESP.ST.QACC.H.H.128.IP - Load and store QACC_H[255:128] (_m version)
// Load: QACC_H[255:128] = load128(src), src = src + (Imm << 4)
// Store: MEM(dst) = QACC_H[255:128], dst = dst + (Imm << 4)
// Offset range: -2048 to 2032, step 16
// CHECK-LABEL: define dso_local ptr @test_ld_st_qacc_h_h_128_ip_m(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.h.h.128.ip.m(ptr [[SRC]], i32 16), !noalias [[META12:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call ptr @llvm.riscv.esp.st.qacc.h.h.128.ip.m(<16 x i8> [[TMP1]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret ptr [[TMP2]]
//
void *test_ld_st_qacc_h_h_128_ip_m(void const *src, void *dst) {
    // Load 128-bit Data to QACC_H[255:128]
    // Returns structure with QACC_H value and updated pointer
    esp_qacc_128_res_t Res = esp_ld_qacc_h_h_128_ip_m(src, 16);
    // Store QACC_H[255:128] to memory
    // Pass QACC_H value for explicit state passing Data flow
    return __builtin_riscv_esp_st_qacc_h_h_128_ip_m(Res.qacc_128, dst, 16);
}

// ESP.LD.QACC.L.L.128.IP + ESP.ST.QACC.L.L.128.IP - Load and store QACC_L[127:0] (_m version)
// Load: QACC_L[127:0] = load128(src), src = src + (Imm << 4)
// Store: MEM(dst) = QACC_L[127:0], dst = dst + (Imm << 4)
// Offset range: -2048 to 2032, step 16
// CHECK-LABEL: define dso_local ptr @test_ld_st_qacc_l_l_128_ip_m(
// CHECK-SAME: ptr noundef [[SRC:%.*]], ptr noundef [[DST:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { <16 x i8>, ptr } @llvm.riscv.esp.ld.qacc.l.l.128.ip.m(ptr [[SRC]], i32 16), !noalias [[META15:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { <16 x i8>, ptr } [[TMP0]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call ptr @llvm.riscv.esp.st.qacc.l.l.128.ip.m(<16 x i8> [[TMP1]], ptr [[DST]], i32 16)
// CHECK-NEXT:    ret ptr [[TMP2]]
//
void *test_ld_st_qacc_l_l_128_ip_m(void const *src, void *dst) {
    // Load 128-bit Data to QACC_L[127:0]
    // Returns structure with QACC_L value and updated pointer
    esp_qacc_128_res_t Res = esp_ld_qacc_l_l_128_ip_m(src, 16);
    // Store QACC_L[127:0] to memory
    // Pass QACC_L value for explicit state passing Data flow
    return __builtin_riscv_esp_st_qacc_l_l_128_ip_m(Res.qacc_128, dst, 16);
}

//.
// CHECK: [[META6]] = !{[[META7:![0-9]+]]}
// CHECK: [[META7]] = distinct !{[[META7]], [[META8:![0-9]+]], !"esp_ld_qacc_h_l_128_ip_m: %agg.result"}
// CHECK: [[META8]] = distinct !{[[META8]], !"esp_ld_qacc_h_l_128_ip_m"}
// CHECK: [[META9]] = !{[[META10:![0-9]+]]}
// CHECK: [[META10]] = distinct !{[[META10]], [[META11:![0-9]+]], !"esp_ld_qacc_l_h_128_ip_m: %agg.result"}
// CHECK: [[META11]] = distinct !{[[META11]], !"esp_ld_qacc_l_h_128_ip_m"}
// CHECK: [[META12]] = !{[[META13:![0-9]+]]}
// CHECK: [[META13]] = distinct !{[[META13]], [[META14:![0-9]+]], !"esp_ld_qacc_h_h_128_ip_m: %agg.result"}
// CHECK: [[META14]] = distinct !{[[META14]], !"esp_ld_qacc_h_h_128_ip_m"}
// CHECK: [[META15]] = !{[[META16:![0-9]+]]}
// CHECK: [[META16]] = distinct !{[[META16]], [[META17:![0-9]+]], !"esp_ld_qacc_l_l_128_ip_m: %agg.result"}
// CHECK: [[META17]] = distinct !{[[META17]], !"esp_ld_qacc_l_l_128_ip_m"}
//.
