; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-int-loop-unroll-and-remainder -riscv-int-loop-unroll-and-remainder=true < %s | FileCheck %s
%struct.image2d_s = type { ptr, i32, i32, i32, i32, i32, i32 }

; Function Attrs: nofree norecurse nosync nounwind memory(read, argmem: readwrite, inaccessiblemem: none)
define dso_local noundef i32 @dspi_dotprod_off_u16_ansi(ptr nocapture noundef readonly %in_image, ptr nocapture noundef readonly %filter, ptr nocapture noundef writeonly %out_value, i32 noundef %count_x, i32 noundef %count_y, i32 noundef %shift, i16 noundef zeroext %offset) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dspi_dotprod_off_u16_ansi(
; CHECK-SAME: ptr noalias noundef readonly captures(none) [[IN_IMAGE:%.*]], ptr noalias noundef readonly captures(none) [[FILTER:%.*]], ptr noalias noundef writeonly captures(none) [[OUT_VALUE:%.*]], i32 noundef [[COUNT_X:%.*]], i32 noundef [[COUNT_Y:%.*]], i32 noundef [[SHIFT:%.*]], i16 noundef zeroext [[OFFSET:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[STEP_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 4
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[STEP_X]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP0]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 12
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[STRIDE_X]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[MUL]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[STEP_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[STEP_Y]], align 4
; CHECK-NEXT:    [[MUL1:%.*]] = mul nsw i32 [[TMP2]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 16
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[STRIDE_Y]], align 4
; CHECK-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[MUL1]], [[TMP3]]
; CHECK-NEXT:    br i1 [[CMP2]], label [[RETURN]], label [[IF_END4:%.*]]
; CHECK:       if.end4:
; CHECK-NEXT:    [[STEP_X5:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[STEP_X5]], align 4
; CHECK-NEXT:    [[MUL6:%.*]] = mul nsw i32 [[TMP4]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X7:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[STRIDE_X7]], align 4
; CHECK-NEXT:    [[CMP8:%.*]] = icmp sgt i32 [[MUL6]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP8]], label [[RETURN]], label [[IF_END10:%.*]]
; CHECK:       if.end10:
; CHECK-NEXT:    [[STEP_Y11:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 8
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[STEP_Y11]], align 4
; CHECK-NEXT:    [[MUL12:%.*]] = mul nsw i32 [[TMP6]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y13:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 16
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[STRIDE_Y13]], align 4
; CHECK-NEXT:    [[CMP14:%.*]] = icmp sgt i32 [[MUL12]], [[TMP7]]
; CHECK-NEXT:    br i1 [[CMP14]], label [[RETURN]], label [[IF_END16:%.*]]
; CHECK:       if.end16:
; CHECK-NEXT:    [[MUL20:%.*]] = mul nsw i32 [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[MUL23:%.*]] = mul nsw i32 [[TMP6]], [[TMP5]]
; CHECK-NEXT:    [[CMP2478:%.*]] = icmp sgt i32 [[COUNT_Y]], 0
; CHECK-NEXT:    br i1 [[CMP2478]], label [[FOR_COND25_PREHEADER_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.cond25.preheader.lr.ph:
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[FILTER]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[IN_IMAGE]], align 4
; CHECK-NEXT:    [[SUB1:%.*]] = add nsw i32 [[COUNT_X]], -7
; CHECK-NEXT:    [[TMP10:%.*]] = and i32 [[COUNT_X]], -8
; CHECK-NEXT:    [[CMP2675:%.*]] = icmp sgt i32 [[COUNT_X]], 7
; CHECK-NEXT:    [[CONV35:%.*]] = zext i16 [[OFFSET]] to i32
; CHECK-NEXT:    br label [[FOR_COND25_PREHEADER:%.*]]
; CHECK:       for.cond25.preheader:
; CHECK-NEXT:    [[Y_082:%.*]] = phi i32 [ 0, [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[INC41:%.*]], [[FOR_COND_CLEANUP27:%.*]] ]
; CHECK-NEXT:    [[ACC_081:%.*]] = phi i64 [ 0, [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[TMP30:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[I_DATA_080:%.*]] = phi ptr [ [[TMP9]], [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[ADD_PTR:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[F_DATA_079:%.*]] = phi ptr [ [[TMP8]], [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[ADD_PTR39:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    br i1 [[CMP2675]], label [[FOR_BODY28_7:%.*]], label [[FOR_COND128_PREHEADER:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi i64 [ 0, [[IF_END16]] ], [ [[TMP30]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[SHIFT]], -1
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i32 1, [[SUB]]
; CHECK-NEXT:    [[CONV43:%.*]] = sext i32 [[SHL]] to i64
; CHECK-NEXT:    [[ADD44:%.*]] = add nsw i64 [[ACC_0_LCSSA]], [[CONV43]]
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[SHIFT]] to i64
; CHECK-NEXT:    [[SHR:%.*]] = ashr i64 [[ADD44]], [[SH_PROM]]
; CHECK-NEXT:    [[CONV45:%.*]] = trunc i64 [[SHR]] to i16
; CHECK-NEXT:    store i16 [[CONV45]], ptr [[OUT_VALUE]], align 2
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       for.cond128.preheader:
; CHECK-NEXT:    [[X_0_LCSSA:%.*]] = phi i32 [ 0, [[FOR_COND25_PREHEADER]] ], [ [[TMP10]], [[FOR_BODY28_7]] ]
; CHECK-NEXT:    [[TMP11:%.*]] = phi i64 [ [[ACC_081]], [[FOR_COND25_PREHEADER]] ], [ [[ADD38_7:%.*]], [[FOR_BODY28_7]] ]
; CHECK-NEXT:    [[CMP129268:%.*]] = icmp slt i32 [[X_0_LCSSA]], [[COUNT_X]]
; CHECK-NEXT:    br i1 [[CMP129268]], label [[FOR_BODY28_CLONE:%.*]], label [[FOR_COND_CLEANUP27]]
; CHECK:       for.body28.7:
; CHECK-NEXT:    [[X_077:%.*]] = phi i32 [ [[INC_7:%.*]], [[FOR_BODY28_7]] ], [ 0, [[FOR_COND25_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_176:%.*]] = phi i64 [ [[ADD38_7]], [[FOR_BODY28_7]] ], [ [[ACC_081]], [[FOR_COND25_PREHEADER]] ]
; CHECK-NEXT:    [[MUL30:%.*]] = mul nsw i32 [[X_077]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL30]]
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[ARRAYIDX]], align 2
; CHECK-NEXT:    [[CONV:%.*]] = zext i16 [[TMP12]] to i32
; CHECK-NEXT:    [[MUL32:%.*]] = mul nsw i32 [[X_077]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL32]]
; CHECK-NEXT:    [[TMP13:%.*]] = load i16, ptr [[ARRAYIDX33]], align 2
; CHECK-NEXT:    [[CONV34:%.*]] = zext i16 [[TMP13]] to i32
; CHECK-NEXT:    [[ADD:%.*]] = add nuw nsw i32 [[CONV34]], [[CONV35]]
; CHECK-NEXT:    [[MUL36:%.*]] = mul nuw nsw i32 [[ADD]], [[CONV]]
; CHECK-NEXT:    [[CONV37:%.*]] = zext nneg i32 [[MUL36]] to i64
; CHECK-NEXT:    [[ADD38:%.*]] = add nsw i64 [[ACC_176]], [[CONV37]]
; CHECK-NEXT:    [[INC:%.*]] = or disjoint i32 [[X_077]], 1
; CHECK-NEXT:    [[MUL30_1:%.*]] = mul nsw i32 [[INC]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL30_1]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[ARRAYIDX_1]], align 2
; CHECK-NEXT:    [[CONV_1:%.*]] = zext i16 [[TMP14]] to i32
; CHECK-NEXT:    [[MUL32_1:%.*]] = mul nsw i32 [[INC]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_1:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL32_1]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[ARRAYIDX33_1]], align 2
; CHECK-NEXT:    [[CONV34_1:%.*]] = zext i16 [[TMP15]] to i32
; CHECK-NEXT:    [[ADD_1:%.*]] = add nuw nsw i32 [[CONV34_1]], [[CONV35]]
; CHECK-NEXT:    [[MUL36_1:%.*]] = mul nuw nsw i32 [[ADD_1]], [[CONV_1]]
; CHECK-NEXT:    [[CONV37_1:%.*]] = zext nneg i32 [[MUL36_1]] to i64
; CHECK-NEXT:    [[ADD38_1:%.*]] = add nsw i64 [[ADD38]], [[CONV37_1]]
; CHECK-NEXT:    [[INC_1:%.*]] = or disjoint i32 [[X_077]], 2
; CHECK-NEXT:    [[MUL30_2:%.*]] = mul nsw i32 [[INC_1]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL30_2]]
; CHECK-NEXT:    [[TMP16:%.*]] = load i16, ptr [[ARRAYIDX_2]], align 2
; CHECK-NEXT:    [[CONV_2:%.*]] = zext i16 [[TMP16]] to i32
; CHECK-NEXT:    [[MUL32_2:%.*]] = mul nsw i32 [[INC_1]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_2:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL32_2]]
; CHECK-NEXT:    [[TMP17:%.*]] = load i16, ptr [[ARRAYIDX33_2]], align 2
; CHECK-NEXT:    [[CONV34_2:%.*]] = zext i16 [[TMP17]] to i32
; CHECK-NEXT:    [[ADD_2:%.*]] = add nuw nsw i32 [[CONV34_2]], [[CONV35]]
; CHECK-NEXT:    [[MUL36_2:%.*]] = mul nuw nsw i32 [[ADD_2]], [[CONV_2]]
; CHECK-NEXT:    [[CONV37_2:%.*]] = zext nneg i32 [[MUL36_2]] to i64
; CHECK-NEXT:    [[ADD38_2:%.*]] = add nsw i64 [[ADD38_1]], [[CONV37_2]]
; CHECK-NEXT:    [[INC_2:%.*]] = or disjoint i32 [[X_077]], 3
; CHECK-NEXT:    [[MUL30_3:%.*]] = mul nsw i32 [[INC_2]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL30_3]]
; CHECK-NEXT:    [[TMP18:%.*]] = load i16, ptr [[ARRAYIDX_3]], align 2
; CHECK-NEXT:    [[CONV_3:%.*]] = zext i16 [[TMP18]] to i32
; CHECK-NEXT:    [[MUL32_3:%.*]] = mul nsw i32 [[INC_2]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_3:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL32_3]]
; CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[ARRAYIDX33_3]], align 2
; CHECK-NEXT:    [[CONV34_3:%.*]] = zext i16 [[TMP19]] to i32
; CHECK-NEXT:    [[ADD_3:%.*]] = add nuw nsw i32 [[CONV34_3]], [[CONV35]]
; CHECK-NEXT:    [[MUL36_3:%.*]] = mul nuw nsw i32 [[ADD_3]], [[CONV_3]]
; CHECK-NEXT:    [[CONV37_3:%.*]] = zext nneg i32 [[MUL36_3]] to i64
; CHECK-NEXT:    [[ADD38_3:%.*]] = add nsw i64 [[ADD38_2]], [[CONV37_3]]
; CHECK-NEXT:    [[INC_3:%.*]] = or disjoint i32 [[X_077]], 4
; CHECK-NEXT:    [[MUL30_4:%.*]] = mul nsw i32 [[INC_3]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL30_4]]
; CHECK-NEXT:    [[TMP20:%.*]] = load i16, ptr [[ARRAYIDX_4]], align 2
; CHECK-NEXT:    [[CONV_4:%.*]] = zext i16 [[TMP20]] to i32
; CHECK-NEXT:    [[MUL32_4:%.*]] = mul nsw i32 [[INC_3]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_4:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL32_4]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[ARRAYIDX33_4]], align 2
; CHECK-NEXT:    [[CONV34_4:%.*]] = zext i16 [[TMP21]] to i32
; CHECK-NEXT:    [[ADD_4:%.*]] = add nuw nsw i32 [[CONV34_4]], [[CONV35]]
; CHECK-NEXT:    [[MUL36_4:%.*]] = mul nuw nsw i32 [[ADD_4]], [[CONV_4]]
; CHECK-NEXT:    [[CONV37_4:%.*]] = zext nneg i32 [[MUL36_4]] to i64
; CHECK-NEXT:    [[ADD38_4:%.*]] = add nsw i64 [[ADD38_3]], [[CONV37_4]]
; CHECK-NEXT:    [[INC_4:%.*]] = or disjoint i32 [[X_077]], 5
; CHECK-NEXT:    [[MUL30_5:%.*]] = mul nsw i32 [[INC_4]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL30_5]]
; CHECK-NEXT:    [[TMP22:%.*]] = load i16, ptr [[ARRAYIDX_5]], align 2
; CHECK-NEXT:    [[CONV_5:%.*]] = zext i16 [[TMP22]] to i32
; CHECK-NEXT:    [[MUL32_5:%.*]] = mul nsw i32 [[INC_4]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_5:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL32_5]]
; CHECK-NEXT:    [[TMP23:%.*]] = load i16, ptr [[ARRAYIDX33_5]], align 2
; CHECK-NEXT:    [[CONV34_5:%.*]] = zext i16 [[TMP23]] to i32
; CHECK-NEXT:    [[ADD_5:%.*]] = add nuw nsw i32 [[CONV34_5]], [[CONV35]]
; CHECK-NEXT:    [[MUL36_5:%.*]] = mul nuw nsw i32 [[ADD_5]], [[CONV_5]]
; CHECK-NEXT:    [[CONV37_5:%.*]] = zext nneg i32 [[MUL36_5]] to i64
; CHECK-NEXT:    [[ADD38_5:%.*]] = add nsw i64 [[ADD38_4]], [[CONV37_5]]
; CHECK-NEXT:    [[INC_5:%.*]] = or disjoint i32 [[X_077]], 6
; CHECK-NEXT:    [[MUL30_6:%.*]] = mul nsw i32 [[INC_5]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL30_6]]
; CHECK-NEXT:    [[TMP24:%.*]] = load i16, ptr [[ARRAYIDX_6]], align 2
; CHECK-NEXT:    [[CONV_6:%.*]] = zext i16 [[TMP24]] to i32
; CHECK-NEXT:    [[MUL32_6:%.*]] = mul nsw i32 [[INC_5]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_6:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL32_6]]
; CHECK-NEXT:    [[TMP25:%.*]] = load i16, ptr [[ARRAYIDX33_6]], align 2
; CHECK-NEXT:    [[CONV34_6:%.*]] = zext i16 [[TMP25]] to i32
; CHECK-NEXT:    [[ADD_6:%.*]] = add nuw nsw i32 [[CONV34_6]], [[CONV35]]
; CHECK-NEXT:    [[MUL36_6:%.*]] = mul nuw nsw i32 [[ADD_6]], [[CONV_6]]
; CHECK-NEXT:    [[CONV37_6:%.*]] = zext nneg i32 [[MUL36_6]] to i64
; CHECK-NEXT:    [[ADD38_6:%.*]] = add nsw i64 [[ADD38_5]], [[CONV37_6]]
; CHECK-NEXT:    [[INC_6:%.*]] = or disjoint i32 [[X_077]], 7
; CHECK-NEXT:    [[MUL30_7:%.*]] = mul nsw i32 [[INC_6]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL30_7]]
; CHECK-NEXT:    [[TMP26:%.*]] = load i16, ptr [[ARRAYIDX_7]], align 2
; CHECK-NEXT:    [[CONV_7:%.*]] = zext i16 [[TMP26]] to i32
; CHECK-NEXT:    [[MUL32_7:%.*]] = mul nsw i32 [[INC_6]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_7:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL32_7]]
; CHECK-NEXT:    [[TMP27:%.*]] = load i16, ptr [[ARRAYIDX33_7]], align 2
; CHECK-NEXT:    [[CONV34_7:%.*]] = zext i16 [[TMP27]] to i32
; CHECK-NEXT:    [[ADD_7:%.*]] = add nuw nsw i32 [[CONV34_7]], [[CONV35]]
; CHECK-NEXT:    [[MUL36_7:%.*]] = mul nuw nsw i32 [[ADD_7]], [[CONV_7]]
; CHECK-NEXT:    [[CONV37_7:%.*]] = zext nneg i32 [[MUL36_7]] to i64
; CHECK-NEXT:    [[ADD38_7]] = add nsw i64 [[ADD38_6]], [[CONV37_7]]
; CHECK-NEXT:    [[INC_7]] = add nuw nsw i32 [[X_077]], 8
; CHECK-NEXT:    [[EXITCOND_NOT_7:%.*]] = icmp slt i32 [[INC_7]], [[SUB1]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_7]], label [[FOR_BODY28_7]], label [[FOR_COND128_PREHEADER]]
; CHECK:       for.body28.clone:
; CHECK-NEXT:    [[X_077_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY28_CLONE]] ], [ [[X_0_LCSSA]], [[FOR_COND128_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_176_CLONE:%.*]] = phi i64 [ [[ADD38_CLONE:%.*]], [[FOR_BODY28_CLONE]] ], [ [[TMP11]], [[FOR_COND128_PREHEADER]] ]
; CHECK-NEXT:    [[MUL30_CLONE:%.*]] = mul nsw i32 [[X_077_CLONE]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL30_CLONE]]
; CHECK-NEXT:    [[TMP28:%.*]] = load i16, ptr [[ARRAYIDX_CLONE]], align 2
; CHECK-NEXT:    [[CONV_CLONE:%.*]] = zext i16 [[TMP28]] to i32
; CHECK-NEXT:    [[MUL32_CLONE:%.*]] = mul nsw i32 [[X_077_CLONE]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_CLONE:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL32_CLONE]]
; CHECK-NEXT:    [[TMP29:%.*]] = load i16, ptr [[ARRAYIDX33_CLONE]], align 2
; CHECK-NEXT:    [[CONV34_CLONE:%.*]] = zext i16 [[TMP29]] to i32
; CHECK-NEXT:    [[ADD_CLONE:%.*]] = add nuw nsw i32 [[CONV34_CLONE]], [[CONV35]]
; CHECK-NEXT:    [[MUL36_CLONE:%.*]] = mul nuw nsw i32 [[ADD_CLONE]], [[CONV_CLONE]]
; CHECK-NEXT:    [[CONV37_CLONE:%.*]] = zext nneg i32 [[MUL36_CLONE]] to i64
; CHECK-NEXT:    [[ADD38_CLONE]] = add nsw i64 [[ACC_176_CLONE]], [[CONV37_CLONE]]
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[X_077_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[COUNT_X]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_COND_CLEANUP27]], label [[FOR_BODY28_CLONE]]
; CHECK:       for.cond.cleanup27:
; CHECK-NEXT:    [[TMP30]] = phi i64 [ [[TMP11]], [[FOR_COND128_PREHEADER]] ], [ [[ADD38_CLONE]], [[FOR_BODY28_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr inbounds i16, ptr [[I_DATA_080]], i32 [[MUL20]]
; CHECK-NEXT:    [[ADD_PTR39]] = getelementptr inbounds i16, ptr [[F_DATA_079]], i32 [[MUL23]]
; CHECK-NEXT:    [[INC41]] = add nuw nsw i32 [[Y_082]], 1
; CHECK-NEXT:    [[EXITCOND84_NOT:%.*]] = icmp eq i32 [[INC41]], [[COUNT_Y]]
; CHECK-NEXT:    br i1 [[EXITCOND84_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_COND25_PREHEADER]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, [[FOR_COND_CLEANUP]] ], [ 458755, [[ENTRY:%.*]] ], [ 458755, [[IF_END]] ], [ 458755, [[IF_END4]] ], [ 458755, [[IF_END10]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %step_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 1
  %0 = load i32, ptr %step_x, align 4
  %mul = mul nsw i32 %0, %count_x
  %stride_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 3
  %1 = load i32, ptr %stride_x, align 4
  %cmp = icmp sgt i32 %mul, %1
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %step_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 2
  %2 = load i32, ptr %step_y, align 4
  %mul1 = mul nsw i32 %2, %count_y
  %stride_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 4
  %3 = load i32, ptr %stride_y, align 4
  %cmp2 = icmp sgt i32 %mul1, %3
  br i1 %cmp2, label %return, label %if.end4

if.end4:                                          ; preds = %if.end
  %step_x5 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 1
  %4 = load i32, ptr %step_x5, align 4
  %mul6 = mul nsw i32 %4, %count_x
  %stride_x7 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 3
  %5 = load i32, ptr %stride_x7, align 4
  %cmp8 = icmp sgt i32 %mul6, %5
  br i1 %cmp8, label %return, label %if.end10

if.end10:                                         ; preds = %if.end4
  %step_y11 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 2
  %6 = load i32, ptr %step_y11, align 4
  %mul12 = mul nsw i32 %6, %count_y
  %stride_y13 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 4
  %7 = load i32, ptr %stride_y13, align 4
  %cmp14 = icmp sgt i32 %mul12, %7
  br i1 %cmp14, label %return, label %if.end16

if.end16:                                         ; preds = %if.end10
  %mul20 = mul nsw i32 %2, %1
  %mul23 = mul nsw i32 %6, %5
  %cmp2478 = icmp sgt i32 %count_y, 0
  br i1 %cmp2478, label %for.cond25.preheader.lr.ph, label %for.cond.cleanup

for.cond25.preheader.lr.ph:                       ; preds = %if.end16
  %8 = load ptr, ptr %filter, align 4
  %9 = load ptr, ptr %in_image, align 4
  %cmp2675 = icmp sgt i32 %count_x, 0
  %conv35 = zext i16 %offset to i32
  br label %for.cond25.preheader

for.cond25.preheader:                             ; preds = %for.cond.cleanup27, %for.cond25.preheader.lr.ph
  %y.082 = phi i32 [ 0, %for.cond25.preheader.lr.ph ], [ %inc41, %for.cond.cleanup27 ]
  %acc.081 = phi i64 [ 0, %for.cond25.preheader.lr.ph ], [ %acc.1.lcssa, %for.cond.cleanup27 ]
  %i_data.080 = phi ptr [ %9, %for.cond25.preheader.lr.ph ], [ %add.ptr, %for.cond.cleanup27 ]
  %f_data.079 = phi ptr [ %8, %for.cond25.preheader.lr.ph ], [ %add.ptr39, %for.cond.cleanup27 ]
  br i1 %cmp2675, label %for.body28, label %for.cond.cleanup27

for.cond.cleanup:                                 ; preds = %for.cond.cleanup27, %if.end16
  %acc.0.lcssa = phi i64 [ 0, %if.end16 ], [ %acc.1.lcssa, %for.cond.cleanup27 ]
  %sub = add nsw i32 %shift, -1
  %shl = shl nuw i32 1, %sub
  %conv43 = sext i32 %shl to i64
  %add44 = add nsw i64 %acc.0.lcssa, %conv43
  %sh_prom = zext nneg i32 %shift to i64
  %shr = ashr i64 %add44, %sh_prom
  %conv45 = trunc i64 %shr to i16
  store i16 %conv45, ptr %out_value, align 2
  br label %return

for.cond.cleanup27:                               ; preds = %for.body28, %for.cond25.preheader
  %acc.1.lcssa = phi i64 [ %acc.081, %for.cond25.preheader ], [ %add38, %for.body28 ]
  %add.ptr = getelementptr inbounds i16, ptr %i_data.080, i32 %mul20
  %add.ptr39 = getelementptr inbounds i16, ptr %f_data.079, i32 %mul23
  %inc41 = add nuw nsw i32 %y.082, 1
  %exitcond84.not = icmp eq i32 %inc41, %count_y
  br i1 %exitcond84.not, label %for.cond.cleanup, label %for.cond25.preheader

for.body28:                                       ; preds = %for.body28, %for.cond25.preheader
  %x.077 = phi i32 [ %inc, %for.body28 ], [ 0, %for.cond25.preheader ]
  %acc.176 = phi i64 [ %add38, %for.body28 ], [ %acc.081, %for.cond25.preheader ]
  %mul30 = mul nsw i32 %x.077, %0
  %arrayidx = getelementptr inbounds i16, ptr %i_data.080, i32 %mul30
  %10 = load i16, ptr %arrayidx, align 2
  %conv = zext i16 %10 to i32
  %mul32 = mul nsw i32 %x.077, %4
  %arrayidx33 = getelementptr inbounds i16, ptr %f_data.079, i32 %mul32
  %11 = load i16, ptr %arrayidx33, align 2
  %conv34 = zext i16 %11 to i32
  %add = add nuw nsw i32 %conv34, %conv35
  %mul36 = mul nsw i32 %add, %conv
  %conv37 = zext nneg i32 %mul36 to i64
  %add38 = add nsw i64 %acc.176, %conv37
  %inc = add nuw nsw i32 %x.077, 1
  %exitcond.not = icmp eq i32 %inc, %count_x
  br i1 %exitcond.not, label %for.cond.cleanup27, label %for.body28

return:                                           ; preds = %for.cond.cleanup, %if.end10, %if.end4, %if.end, %entry
  %retval.0 = phi i32 [ 0, %for.cond.cleanup ], [ 458755, %entry ], [ 458755, %if.end ], [ 458755, %if.end4 ], [ 458755, %if.end10 ]
  ret i32 %retval.0
}
