; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-int-loop-unroll-and-remainder -riscv-int-loop-unroll-and-remainder=false < %s | FileCheck %s
%struct.image2d_s = type { ptr, i32, i32, i32, i32, i32, i32 }

; Function Attrs: nofree norecurse nosync nounwind memory(read, argmem: readwrite, inaccessiblemem: none)
define dso_local noundef i32 @dspi_dotprod_s16_ansi(ptr nocapture noundef readonly %in_image, ptr nocapture noundef readonly %filter, ptr nocapture noundef writeonly %out_value, i32 noundef %count_x, i32 noundef %count_y, i32 noundef %shift) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dspi_dotprod_s16_ansi(
; CHECK-SAME: ptr nocapture noundef readonly [[IN_IMAGE:%.*]], ptr nocapture noundef readonly [[FILTER:%.*]], ptr nocapture noundef writeonly [[OUT_VALUE:%.*]], i32 noundef [[COUNT_X:%.*]], i32 noundef [[COUNT_Y:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[STEP_X:%.*]] = getelementptr inbounds [[STRUCT_IMAGE2D_S:%.*]], ptr [[IN_IMAGE]], i32 0, i32 1
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[STEP_X]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP0]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X:%.*]] = getelementptr inbounds [[STRUCT_IMAGE2D_S]], ptr [[IN_IMAGE]], i32 0, i32 3
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[STRIDE_X]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[MUL]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[STEP_Y:%.*]] = getelementptr inbounds [[STRUCT_IMAGE2D_S]], ptr [[IN_IMAGE]], i32 0, i32 2
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[STEP_Y]], align 4
; CHECK-NEXT:    [[MUL1:%.*]] = mul nsw i32 [[TMP2]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y:%.*]] = getelementptr inbounds [[STRUCT_IMAGE2D_S]], ptr [[IN_IMAGE]], i32 0, i32 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[STRIDE_Y]], align 4
; CHECK-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[MUL1]], [[TMP3]]
; CHECK-NEXT:    br i1 [[CMP2]], label [[RETURN]], label [[IF_END4:%.*]]
; CHECK:       if.end4:
; CHECK-NEXT:    [[STEP_X5:%.*]] = getelementptr inbounds [[STRUCT_IMAGE2D_S]], ptr [[FILTER]], i32 0, i32 1
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[STEP_X5]], align 4
; CHECK-NEXT:    [[MUL6:%.*]] = mul nsw i32 [[TMP4]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X7:%.*]] = getelementptr inbounds [[STRUCT_IMAGE2D_S]], ptr [[FILTER]], i32 0, i32 3
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[STRIDE_X7]], align 4
; CHECK-NEXT:    [[CMP8:%.*]] = icmp sgt i32 [[MUL6]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP8]], label [[RETURN]], label [[IF_END10:%.*]]
; CHECK:       if.end10:
; CHECK-NEXT:    [[STEP_Y11:%.*]] = getelementptr inbounds [[STRUCT_IMAGE2D_S]], ptr [[FILTER]], i32 0, i32 2
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[STEP_Y11]], align 4
; CHECK-NEXT:    [[MUL12:%.*]] = mul nsw i32 [[TMP6]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y13:%.*]] = getelementptr inbounds [[STRUCT_IMAGE2D_S]], ptr [[FILTER]], i32 0, i32 4
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[STRIDE_Y13]], align 4
; CHECK-NEXT:    [[CMP14:%.*]] = icmp sgt i32 [[MUL12]], [[TMP7]]
; CHECK-NEXT:    br i1 [[CMP14]], label [[RETURN]], label [[IF_END16:%.*]]
; CHECK:       if.end16:
; CHECK-NEXT:    [[MUL20:%.*]] = mul nsw i32 [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[MUL23:%.*]] = mul nsw i32 [[TMP6]], [[TMP5]]
; CHECK-NEXT:    [[CMP2476:%.*]] = icmp sgt i32 [[COUNT_Y]], 0
; CHECK-NEXT:    br i1 [[CMP2476]], label [[FOR_COND25_PREHEADER_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.cond25.preheader.lr.ph:
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[FILTER]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[IN_IMAGE]], align 4
; CHECK-NEXT:    [[CMP2673:%.*]] = icmp sgt i32 [[COUNT_X]], 0
; CHECK-NEXT:    br label [[FOR_COND25_PREHEADER:%.*]]
; CHECK:       for.cond25.preheader:
; CHECK-NEXT:    [[Y_080:%.*]] = phi i32 [ 0, [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[INC39:%.*]], [[FOR_COND_CLEANUP27:%.*]] ]
; CHECK-NEXT:    [[ACC_079:%.*]] = phi i64 [ 0, [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[TMP30:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[I_DATA_078:%.*]] = phi ptr [ [[TMP9]], [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[ADD_PTR:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[F_DATA_077:%.*]] = phi ptr [ [[TMP8]], [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[ADD_PTR37:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    br i1 [[CMP2673]], label [[FOR_BODY28:%.*]], label [[FOR_COND_CLEANUP27]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi i64 [ 0, [[IF_END16]] ], [ [[TMP30]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[SHIFT]], -1
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i32 1, [[SUB]]
; CHECK-NEXT:    [[CONV41:%.*]] = sext i32 [[SHL]] to i64
; CHECK-NEXT:    [[ADD42:%.*]] = add nsw i64 [[ACC_0_LCSSA]], [[CONV41]]
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[SHIFT]] to i64
; CHECK-NEXT:    [[SHR:%.*]] = ashr i64 [[ADD42]], [[SH_PROM]]
; CHECK-NEXT:    [[CONV43:%.*]] = trunc i64 [[SHR]] to i16
; CHECK-NEXT:    store i16 [[CONV43]], ptr [[OUT_VALUE]], align 2
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       for.cond.cleanup27:
; CHECK-NEXT:    [[TMP30]] = phi i64 [ [[ACC_079]], [[FOR_COND25_PREHEADER]] ], [ [[ADD_CLONE:%.*]], [[FOR_BODY28]] ]
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr inbounds i16, ptr [[I_DATA_078]], i32 [[MUL20]]
; CHECK-NEXT:    [[ADD_PTR37]] = getelementptr inbounds i16, ptr [[F_DATA_077]], i32 [[MUL23]]
; CHECK-NEXT:    [[INC39]] = add nuw nsw i32 [[Y_080]], 1
; CHECK-NEXT:    [[EXITCOND82_NOT:%.*]] = icmp eq i32 [[INC39]], [[COUNT_Y]]
; CHECK-NEXT:    br i1 [[EXITCOND82_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_COND25_PREHEADER]]
; CHECK:       for.body28:
; CHECK-NEXT:    [[X_075_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY28]] ], [ 0, [[FOR_COND25_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_174_CLONE:%.*]] = phi i64 [ [[ADD_CLONE]], [[FOR_BODY28]] ], [ [[ACC_079]], [[FOR_COND25_PREHEADER]] ]
; CHECK-NEXT:    [[MUL30_CLONE:%.*]] = mul nsw i32 [[X_075_CLONE]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds i16, ptr [[I_DATA_078]], i32 [[MUL30_CLONE]]
; CHECK-NEXT:    [[TMP28:%.*]] = load i16, ptr [[ARRAYIDX_CLONE]], align 2
; CHECK-NEXT:    [[CONV_CLONE:%.*]] = sext i16 [[TMP28]] to i32
; CHECK-NEXT:    [[MUL32_CLONE:%.*]] = mul nsw i32 [[X_075_CLONE]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX33_CLONE:%.*]] = getelementptr inbounds i16, ptr [[F_DATA_077]], i32 [[MUL32_CLONE]]
; CHECK-NEXT:    [[TMP29:%.*]] = load i16, ptr [[ARRAYIDX33_CLONE]], align 2
; CHECK-NEXT:    [[CONV34_CLONE:%.*]] = sext i16 [[TMP29]] to i32
; CHECK-NEXT:    [[MUL35_CLONE:%.*]] = mul nsw i32 [[CONV34_CLONE]], [[CONV_CLONE]]
; CHECK-NEXT:    [[CONV36_CLONE:%.*]] = sext i32 [[MUL35_CLONE]] to i64
; CHECK-NEXT:    [[ADD_CLONE]] = add nsw i64 [[ACC_174_CLONE]], [[CONV36_CLONE]]
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[X_075_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[COUNT_X]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_COND_CLEANUP27]], label [[FOR_BODY28]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, [[FOR_COND_CLEANUP]] ], [ 458755, [[ENTRY:%.*]] ], [ 458755, [[IF_END]] ], [ 458755, [[IF_END4]] ], [ 458755, [[IF_END10]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %step_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 1
  %0 = load i32, ptr %step_x, align 4
  %mul = mul nsw i32 %0, %count_x
  %stride_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 3
  %1 = load i32, ptr %stride_x, align 4
  %cmp = icmp sgt i32 %mul, %1
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %step_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 2
  %2 = load i32, ptr %step_y, align 4
  %mul1 = mul nsw i32 %2, %count_y
  %stride_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 4
  %3 = load i32, ptr %stride_y, align 4
  %cmp2 = icmp sgt i32 %mul1, %3
  br i1 %cmp2, label %return, label %if.end4

if.end4:                                          ; preds = %if.end
  %step_x5 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 1
  %4 = load i32, ptr %step_x5, align 4
  %mul6 = mul nsw i32 %4, %count_x
  %stride_x7 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 3
  %5 = load i32, ptr %stride_x7, align 4
  %cmp8 = icmp sgt i32 %mul6, %5
  br i1 %cmp8, label %return, label %if.end10

if.end10:                                         ; preds = %if.end4
  %step_y11 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 2
  %6 = load i32, ptr %step_y11, align 4
  %mul12 = mul nsw i32 %6, %count_y
  %stride_y13 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 4
  %7 = load i32, ptr %stride_y13, align 4
  %cmp14 = icmp sgt i32 %mul12, %7
  br i1 %cmp14, label %return, label %if.end16

if.end16:                                         ; preds = %if.end10
  %mul20 = mul nsw i32 %2, %1
  %mul23 = mul nsw i32 %6, %5
  %cmp2476 = icmp sgt i32 %count_y, 0
  br i1 %cmp2476, label %for.cond25.preheader.lr.ph, label %for.cond.cleanup

for.cond25.preheader.lr.ph:                       ; preds = %if.end16
  %8 = load ptr, ptr %filter, align 4
  %9 = load ptr, ptr %in_image, align 4
  %cmp2673 = icmp sgt i32 %count_x, 0
  br label %for.cond25.preheader

for.cond25.preheader:                             ; preds = %for.cond.cleanup27, %for.cond25.preheader.lr.ph
  %y.080 = phi i32 [ 0, %for.cond25.preheader.lr.ph ], [ %inc39, %for.cond.cleanup27 ]
  %acc.079 = phi i64 [ 0, %for.cond25.preheader.lr.ph ], [ %acc.1.lcssa, %for.cond.cleanup27 ]
  %i_data.078 = phi ptr [ %9, %for.cond25.preheader.lr.ph ], [ %add.ptr, %for.cond.cleanup27 ]
  %f_data.077 = phi ptr [ %8, %for.cond25.preheader.lr.ph ], [ %add.ptr37, %for.cond.cleanup27 ]
  br i1 %cmp2673, label %for.body28, label %for.cond.cleanup27

for.cond.cleanup:                                 ; preds = %for.cond.cleanup27, %if.end16
  %acc.0.lcssa = phi i64 [ 0, %if.end16 ], [ %acc.1.lcssa, %for.cond.cleanup27 ]
  %sub = add nsw i32 %shift, -1
  %shl = shl nuw i32 1, %sub
  %conv41 = sext i32 %shl to i64
  %add42 = add nsw i64 %acc.0.lcssa, %conv41
  %sh_prom = zext nneg i32 %shift to i64
  %shr = ashr i64 %add42, %sh_prom
  %conv43 = trunc i64 %shr to i16
  store i16 %conv43, ptr %out_value, align 2
  br label %return

for.cond.cleanup27:                               ; preds = %for.body28, %for.cond25.preheader
  %acc.1.lcssa = phi i64 [ %acc.079, %for.cond25.preheader ], [ %add, %for.body28 ]
  %add.ptr = getelementptr inbounds i16, ptr %i_data.078, i32 %mul20
  %add.ptr37 = getelementptr inbounds i16, ptr %f_data.077, i32 %mul23
  %inc39 = add nuw nsw i32 %y.080, 1
  %exitcond82.not = icmp eq i32 %inc39, %count_y
  br i1 %exitcond82.not, label %for.cond.cleanup, label %for.cond25.preheader

for.body28:                                       ; preds = %for.body28, %for.cond25.preheader
  %x.075 = phi i32 [ %inc, %for.body28 ], [ 0, %for.cond25.preheader ]
  %acc.174 = phi i64 [ %add, %for.body28 ], [ %acc.079, %for.cond25.preheader ]
  %mul30 = mul nsw i32 %x.075, %0
  %arrayidx = getelementptr inbounds i16, ptr %i_data.078, i32 %mul30
  %10 = load i16, ptr %arrayidx, align 2
  %conv = sext i16 %10 to i32
  %mul32 = mul nsw i32 %x.075, %4
  %arrayidx33 = getelementptr inbounds i16, ptr %f_data.077, i32 %mul32
  %11 = load i16, ptr %arrayidx33, align 2
  %conv34 = sext i16 %11 to i32
  %mul35 = mul nsw i32 %conv34, %conv
  %conv36 = sext i32 %mul35 to i64
  %add = add nsw i64 %acc.174, %conv36
  %inc = add nuw nsw i32 %x.075, 1
  %exitcond.not = icmp eq i32 %inc, %count_x
  br i1 %exitcond.not, label %for.cond.cleanup27, label %for.body28

return:                                           ; preds = %for.cond.cleanup, %if.end10, %if.end4, %if.end, %entry
  %retval.0 = phi i32 [ 0, %for.cond.cleanup ], [ 458755, %entry ], [ 458755, %if.end ], [ 458755, %if.end4 ], [ 458755, %if.end10 ]
  ret i32 %retval.0
}
