; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-int-loop-unroll-and-remainder -riscv-int-loop-unroll-and-remainder=true < %s | FileCheck %s
%struct.image2d_s = type { ptr, i32, i32, i32, i32, i32, i32 }

; Function Attrs: nofree norecurse nosync nounwind memory(read, argmem: readwrite, inaccessiblemem: none)
define dso_local noundef i32 @dspi_dotprod_off_u8_ansi(ptr nocapture noundef readonly %in_image, ptr nocapture noundef readonly %filter, ptr nocapture noundef writeonly %out_value, i32 noundef %count_x, i32 noundef %count_y, i32 noundef %shift, i8 noundef zeroext %offset) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dspi_dotprod_off_u8_ansi(
; CHECK-SAME: ptr noalias noundef readonly captures(none) [[IN_IMAGE:%.*]], ptr noalias noundef readonly captures(none) [[FILTER:%.*]], ptr noalias noundef writeonly captures(none) [[OUT_VALUE:%.*]], i32 noundef [[COUNT_X:%.*]], i32 noundef [[COUNT_Y:%.*]], i32 noundef [[SHIFT:%.*]], i8 noundef zeroext [[OFFSET:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[STEP_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 4
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[STEP_X]], align 4
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP0]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 12
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[STRIDE_X]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[MUL]], [[TMP1]]
; CHECK-NEXT:    br i1 [[CMP]], label [[RETURN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    [[STEP_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 8
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[STEP_Y]], align 4
; CHECK-NEXT:    [[MUL1:%.*]] = mul nsw i32 [[TMP2]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y:%.*]] = getelementptr inbounds nuw i8, ptr [[IN_IMAGE]], i32 16
; CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[STRIDE_Y]], align 4
; CHECK-NEXT:    [[CMP2:%.*]] = icmp sgt i32 [[MUL1]], [[TMP3]]
; CHECK-NEXT:    br i1 [[CMP2]], label [[RETURN]], label [[IF_END4:%.*]]
; CHECK:       if.end4:
; CHECK-NEXT:    [[STEP_X5:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[STEP_X5]], align 4
; CHECK-NEXT:    [[MUL6:%.*]] = mul nsw i32 [[TMP4]], [[COUNT_X]]
; CHECK-NEXT:    [[STRIDE_X7:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 12
; CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[STRIDE_X7]], align 4
; CHECK-NEXT:    [[CMP8:%.*]] = icmp sgt i32 [[MUL6]], [[TMP5]]
; CHECK-NEXT:    br i1 [[CMP8]], label [[RETURN]], label [[IF_END10:%.*]]
; CHECK:       if.end10:
; CHECK-NEXT:    [[STEP_Y11:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 8
; CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[STEP_Y11]], align 4
; CHECK-NEXT:    [[MUL12:%.*]] = mul nsw i32 [[TMP6]], [[COUNT_Y]]
; CHECK-NEXT:    [[STRIDE_Y13:%.*]] = getelementptr inbounds nuw i8, ptr [[FILTER]], i32 16
; CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[STRIDE_Y13]], align 4
; CHECK-NEXT:    [[CMP14:%.*]] = icmp sgt i32 [[MUL12]], [[TMP7]]
; CHECK-NEXT:    br i1 [[CMP14]], label [[RETURN]], label [[IF_END16:%.*]]
; CHECK:       if.end16:
; CHECK-NEXT:    [[MUL20:%.*]] = mul nsw i32 [[TMP2]], [[TMP1]]
; CHECK-NEXT:    [[MUL23:%.*]] = mul nsw i32 [[TMP6]], [[TMP5]]
; CHECK-NEXT:    [[CMP2479:%.*]] = icmp sgt i32 [[COUNT_Y]], 0
; CHECK-NEXT:    br i1 [[CMP2479]], label [[FOR_COND25_PREHEADER_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.cond25.preheader.lr.ph:
; CHECK-NEXT:    [[TMP8:%.*]] = load ptr, ptr [[FILTER]], align 4
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[IN_IMAGE]], align 4
; CHECK-NEXT:    [[SUB1:%.*]] = add nsw i32 [[COUNT_X]], -7
; CHECK-NEXT:    [[TMP10:%.*]] = and i32 [[COUNT_X]], -8
; CHECK-NEXT:    [[CMP2676:%.*]] = icmp sgt i32 [[COUNT_X]], 7
; CHECK-NEXT:    [[CONV38:%.*]] = zext i8 [[OFFSET]] to i32
; CHECK-NEXT:    br label [[FOR_COND25_PREHEADER:%.*]]
; CHECK:       for.cond25.preheader:
; CHECK-NEXT:    [[Y_083:%.*]] = phi i32 [ 0, [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[INC43:%.*]], [[FOR_COND_CLEANUP27:%.*]] ]
; CHECK-NEXT:    [[ACC_082:%.*]] = phi i32 [ 0, [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[TMP30:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[I_DATA_081:%.*]] = phi ptr [ [[TMP9]], [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[ADD_PTR:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[F_DATA_080:%.*]] = phi ptr [ [[TMP8]], [[FOR_COND25_PREHEADER_LR_PH]] ], [ [[ADD_PTR41:%.*]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    br i1 [[CMP2676]], label [[FOR_BODY28_7:%.*]], label [[FOR_COND128_PREHEADER:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi i32 [ 0, [[IF_END16]] ], [ [[TMP30]], [[FOR_COND_CLEANUP27]] ]
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[SHIFT]], -1
; CHECK-NEXT:    [[SHL:%.*]] = shl nuw i32 1, [[SUB]]
; CHECK-NEXT:    [[ADD45:%.*]] = add nsw i32 [[ACC_0_LCSSA]], [[SHL]]
; CHECK-NEXT:    [[SHR:%.*]] = ashr i32 [[ADD45]], [[SHIFT]]
; CHECK-NEXT:    [[CONV46:%.*]] = trunc i32 [[SHR]] to i8
; CHECK-NEXT:    store i8 [[CONV46]], ptr [[OUT_VALUE]], align 1
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       for.cond128.preheader:
; CHECK-NEXT:    [[X_0_LCSSA:%.*]] = phi i32 [ 0, [[FOR_COND25_PREHEADER]] ], [ [[TMP10]], [[FOR_BODY28_7]] ]
; CHECK-NEXT:    [[TMP11:%.*]] = phi i32 [ [[ACC_082]], [[FOR_COND25_PREHEADER]] ], [ [[ADD40_7:%.*]], [[FOR_BODY28_7]] ]
; CHECK-NEXT:    [[CMP129268:%.*]] = icmp slt i32 [[X_0_LCSSA]], [[COUNT_X]]
; CHECK-NEXT:    br i1 [[CMP129268]], label [[FOR_BODY28_CLONE:%.*]], label [[FOR_COND_CLEANUP27]]
; CHECK:       for.body28.7:
; CHECK-NEXT:    [[X_078:%.*]] = phi i32 [ [[INC_7:%.*]], [[FOR_BODY28_7]] ], [ 0, [[FOR_COND25_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_177:%.*]] = phi i32 [ [[ADD40_7]], [[FOR_BODY28_7]] ], [ [[ACC_082]], [[FOR_COND25_PREHEADER]] ]
; CHECK-NEXT:    [[MUL30:%.*]] = mul nsw i32 [[X_078]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL30]]
; CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CONV31:%.*]] = zext i8 [[TMP12]] to i32
; CHECK-NEXT:    [[MUL33:%.*]] = mul nsw i32 [[X_078]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX34:%.*]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL33]]
; CHECK-NEXT:    [[TMP13:%.*]] = load i8, ptr [[ARRAYIDX34]], align 1
; CHECK-NEXT:    [[CONV36:%.*]] = zext i8 [[TMP13]] to i32
; CHECK-NEXT:    [[ADD:%.*]] = add nuw nsw i32 [[CONV36]], [[CONV38]]
; CHECK-NEXT:    [[MUL39:%.*]] = mul nuw nsw i32 [[ADD]], [[CONV31]]
; CHECK-NEXT:    [[ADD40:%.*]] = add nsw i32 [[MUL39]], [[ACC_177]]
; CHECK-NEXT:    [[INC:%.*]] = or disjoint i32 [[X_078]], 1
; CHECK-NEXT:    [[MUL30_1:%.*]] = mul nsw i32 [[INC]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL30_1]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i8, ptr [[ARRAYIDX_1]], align 1
; CHECK-NEXT:    [[CONV31_1:%.*]] = zext i8 [[TMP14]] to i32
; CHECK-NEXT:    [[MUL33_1:%.*]] = mul nsw i32 [[INC]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX34_1:%.*]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL33_1]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i8, ptr [[ARRAYIDX34_1]], align 1
; CHECK-NEXT:    [[CONV36_1:%.*]] = zext i8 [[TMP15]] to i32
; CHECK-NEXT:    [[ADD_1:%.*]] = add nuw nsw i32 [[CONV36_1]], [[CONV38]]
; CHECK-NEXT:    [[MUL39_1:%.*]] = mul nuw nsw i32 [[ADD_1]], [[CONV31_1]]
; CHECK-NEXT:    [[ADD40_1:%.*]] = add nsw i32 [[MUL39_1]], [[ADD40]]
; CHECK-NEXT:    [[INC_1:%.*]] = or disjoint i32 [[X_078]], 2
; CHECK-NEXT:    [[MUL30_2:%.*]] = mul nsw i32 [[INC_1]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL30_2]]
; CHECK-NEXT:    [[TMP16:%.*]] = load i8, ptr [[ARRAYIDX_2]], align 1
; CHECK-NEXT:    [[CONV31_2:%.*]] = zext i8 [[TMP16]] to i32
; CHECK-NEXT:    [[MUL33_2:%.*]] = mul nsw i32 [[INC_1]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX34_2:%.*]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL33_2]]
; CHECK-NEXT:    [[TMP17:%.*]] = load i8, ptr [[ARRAYIDX34_2]], align 1
; CHECK-NEXT:    [[CONV36_2:%.*]] = zext i8 [[TMP17]] to i32
; CHECK-NEXT:    [[ADD_2:%.*]] = add nuw nsw i32 [[CONV36_2]], [[CONV38]]
; CHECK-NEXT:    [[MUL39_2:%.*]] = mul nuw nsw i32 [[ADD_2]], [[CONV31_2]]
; CHECK-NEXT:    [[ADD40_2:%.*]] = add nsw i32 [[MUL39_2]], [[ADD40_1]]
; CHECK-NEXT:    [[INC_2:%.*]] = or disjoint i32 [[X_078]], 3
; CHECK-NEXT:    [[MUL30_3:%.*]] = mul nsw i32 [[INC_2]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL30_3]]
; CHECK-NEXT:    [[TMP18:%.*]] = load i8, ptr [[ARRAYIDX_3]], align 1
; CHECK-NEXT:    [[CONV31_3:%.*]] = zext i8 [[TMP18]] to i32
; CHECK-NEXT:    [[MUL33_3:%.*]] = mul nsw i32 [[INC_2]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX34_3:%.*]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL33_3]]
; CHECK-NEXT:    [[TMP19:%.*]] = load i8, ptr [[ARRAYIDX34_3]], align 1
; CHECK-NEXT:    [[CONV36_3:%.*]] = zext i8 [[TMP19]] to i32
; CHECK-NEXT:    [[ADD_3:%.*]] = add nuw nsw i32 [[CONV36_3]], [[CONV38]]
; CHECK-NEXT:    [[MUL39_3:%.*]] = mul nuw nsw i32 [[ADD_3]], [[CONV31_3]]
; CHECK-NEXT:    [[ADD40_3:%.*]] = add nsw i32 [[MUL39_3]], [[ADD40_2]]
; CHECK-NEXT:    [[INC_3:%.*]] = or disjoint i32 [[X_078]], 4
; CHECK-NEXT:    [[MUL30_4:%.*]] = mul nsw i32 [[INC_3]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL30_4]]
; CHECK-NEXT:    [[TMP20:%.*]] = load i8, ptr [[ARRAYIDX_4]], align 1
; CHECK-NEXT:    [[CONV31_4:%.*]] = zext i8 [[TMP20]] to i32
; CHECK-NEXT:    [[MUL33_4:%.*]] = mul nsw i32 [[INC_3]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX34_4:%.*]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL33_4]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i8, ptr [[ARRAYIDX34_4]], align 1
; CHECK-NEXT:    [[CONV36_4:%.*]] = zext i8 [[TMP21]] to i32
; CHECK-NEXT:    [[ADD_4:%.*]] = add nuw nsw i32 [[CONV36_4]], [[CONV38]]
; CHECK-NEXT:    [[MUL39_4:%.*]] = mul nuw nsw i32 [[ADD_4]], [[CONV31_4]]
; CHECK-NEXT:    [[ADD40_4:%.*]] = add nsw i32 [[MUL39_4]], [[ADD40_3]]
; CHECK-NEXT:    [[INC_4:%.*]] = or disjoint i32 [[X_078]], 5
; CHECK-NEXT:    [[MUL30_5:%.*]] = mul nsw i32 [[INC_4]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL30_5]]
; CHECK-NEXT:    [[TMP22:%.*]] = load i8, ptr [[ARRAYIDX_5]], align 1
; CHECK-NEXT:    [[CONV31_5:%.*]] = zext i8 [[TMP22]] to i32
; CHECK-NEXT:    [[MUL33_5:%.*]] = mul nsw i32 [[INC_4]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX34_5:%.*]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL33_5]]
; CHECK-NEXT:    [[TMP23:%.*]] = load i8, ptr [[ARRAYIDX34_5]], align 1
; CHECK-NEXT:    [[CONV36_5:%.*]] = zext i8 [[TMP23]] to i32
; CHECK-NEXT:    [[ADD_5:%.*]] = add nuw nsw i32 [[CONV36_5]], [[CONV38]]
; CHECK-NEXT:    [[MUL39_5:%.*]] = mul nuw nsw i32 [[ADD_5]], [[CONV31_5]]
; CHECK-NEXT:    [[ADD40_5:%.*]] = add nsw i32 [[MUL39_5]], [[ADD40_4]]
; CHECK-NEXT:    [[INC_5:%.*]] = or disjoint i32 [[X_078]], 6
; CHECK-NEXT:    [[MUL30_6:%.*]] = mul nsw i32 [[INC_5]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL30_6]]
; CHECK-NEXT:    [[TMP24:%.*]] = load i8, ptr [[ARRAYIDX_6]], align 1
; CHECK-NEXT:    [[CONV31_6:%.*]] = zext i8 [[TMP24]] to i32
; CHECK-NEXT:    [[MUL33_6:%.*]] = mul nsw i32 [[INC_5]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX34_6:%.*]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL33_6]]
; CHECK-NEXT:    [[TMP25:%.*]] = load i8, ptr [[ARRAYIDX34_6]], align 1
; CHECK-NEXT:    [[CONV36_6:%.*]] = zext i8 [[TMP25]] to i32
; CHECK-NEXT:    [[ADD_6:%.*]] = add nuw nsw i32 [[CONV36_6]], [[CONV38]]
; CHECK-NEXT:    [[MUL39_6:%.*]] = mul nuw nsw i32 [[ADD_6]], [[CONV31_6]]
; CHECK-NEXT:    [[ADD40_6:%.*]] = add nsw i32 [[MUL39_6]], [[ADD40_5]]
; CHECK-NEXT:    [[INC_6:%.*]] = or disjoint i32 [[X_078]], 7
; CHECK-NEXT:    [[MUL30_7:%.*]] = mul nsw i32 [[INC_6]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL30_7]]
; CHECK-NEXT:    [[TMP26:%.*]] = load i8, ptr [[ARRAYIDX_7]], align 1
; CHECK-NEXT:    [[CONV31_7:%.*]] = zext i8 [[TMP26]] to i32
; CHECK-NEXT:    [[MUL33_7:%.*]] = mul nsw i32 [[INC_6]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX34_7:%.*]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL33_7]]
; CHECK-NEXT:    [[TMP27:%.*]] = load i8, ptr [[ARRAYIDX34_7]], align 1
; CHECK-NEXT:    [[CONV36_7:%.*]] = zext i8 [[TMP27]] to i32
; CHECK-NEXT:    [[ADD_7:%.*]] = add nuw nsw i32 [[CONV36_7]], [[CONV38]]
; CHECK-NEXT:    [[MUL39_7:%.*]] = mul nuw nsw i32 [[ADD_7]], [[CONV31_7]]
; CHECK-NEXT:    [[ADD40_7]] = add nsw i32 [[MUL39_7]], [[ADD40_6]]
; CHECK-NEXT:    [[INC_7]] = add nuw nsw i32 [[X_078]], 8
; CHECK-NEXT:    [[EXITCOND_NOT_7:%.*]] = icmp slt i32 [[INC_7]], [[SUB1]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_7]], label [[FOR_BODY28_7]], label [[FOR_COND128_PREHEADER]]
; CHECK:       for.body28.clone:
; CHECK-NEXT:    [[X_078_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY28_CLONE]] ], [ [[X_0_LCSSA]], [[FOR_COND128_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_177_CLONE:%.*]] = phi i32 [ [[ADD40_CLONE:%.*]], [[FOR_BODY28_CLONE]] ], [ [[TMP11]], [[FOR_COND128_PREHEADER]] ]
; CHECK-NEXT:    [[MUL30_CLONE:%.*]] = mul nsw i32 [[X_078_CLONE]], [[TMP0]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL30_CLONE]]
; CHECK-NEXT:    [[TMP28:%.*]] = load i8, ptr [[ARRAYIDX_CLONE]], align 1
; CHECK-NEXT:    [[CONV31_CLONE:%.*]] = zext i8 [[TMP28]] to i32
; CHECK-NEXT:    [[MUL33_CLONE:%.*]] = mul nsw i32 [[X_078_CLONE]], [[TMP4]]
; CHECK-NEXT:    [[ARRAYIDX34_CLONE:%.*]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL33_CLONE]]
; CHECK-NEXT:    [[TMP29:%.*]] = load i8, ptr [[ARRAYIDX34_CLONE]], align 1
; CHECK-NEXT:    [[CONV36_CLONE:%.*]] = zext i8 [[TMP29]] to i32
; CHECK-NEXT:    [[ADD_CLONE:%.*]] = add nuw nsw i32 [[CONV36_CLONE]], [[CONV38]]
; CHECK-NEXT:    [[MUL39_CLONE:%.*]] = mul nuw nsw i32 [[ADD_CLONE]], [[CONV31_CLONE]]
; CHECK-NEXT:    [[ADD40_CLONE]] = add nsw i32 [[MUL39_CLONE]], [[ACC_177_CLONE]]
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[X_078_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[COUNT_X]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_COND_CLEANUP27]], label [[FOR_BODY28_CLONE]]
; CHECK:       for.cond.cleanup27:
; CHECK-NEXT:    [[TMP30]] = phi i32 [ [[TMP11]], [[FOR_COND128_PREHEADER]] ], [ [[ADD40_CLONE]], [[FOR_BODY28_CLONE]] ]
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[I_DATA_081]], i32 [[MUL20]]
; CHECK-NEXT:    [[ADD_PTR41]] = getelementptr inbounds i8, ptr [[F_DATA_080]], i32 [[MUL23]]
; CHECK-NEXT:    [[INC43]] = add nuw nsw i32 [[Y_083]], 1
; CHECK-NEXT:    [[EXITCOND85_NOT:%.*]] = icmp eq i32 [[INC43]], [[COUNT_Y]]
; CHECK-NEXT:    br i1 [[EXITCOND85_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_COND25_PREHEADER]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, [[FOR_COND_CLEANUP]] ], [ 458755, [[ENTRY:%.*]] ], [ 458755, [[IF_END]] ], [ 458755, [[IF_END4]] ], [ 458755, [[IF_END10]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %step_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 1
  %0 = load i32, ptr %step_x, align 4
  %mul = mul nsw i32 %0, %count_x
  %stride_x = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 3
  %1 = load i32, ptr %stride_x, align 4
  %cmp = icmp sgt i32 %mul, %1
  br i1 %cmp, label %return, label %if.end

if.end:                                           ; preds = %entry
  %step_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 2
  %2 = load i32, ptr %step_y, align 4
  %mul1 = mul nsw i32 %2, %count_y
  %stride_y = getelementptr inbounds %struct.image2d_s, ptr %in_image, i32 0, i32 4
  %3 = load i32, ptr %stride_y, align 4
  %cmp2 = icmp sgt i32 %mul1, %3
  br i1 %cmp2, label %return, label %if.end4

if.end4:                                          ; preds = %if.end
  %step_x5 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 1
  %4 = load i32, ptr %step_x5, align 4
  %mul6 = mul nsw i32 %4, %count_x
  %stride_x7 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 3
  %5 = load i32, ptr %stride_x7, align 4
  %cmp8 = icmp sgt i32 %mul6, %5
  br i1 %cmp8, label %return, label %if.end10

if.end10:                                         ; preds = %if.end4
  %step_y11 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 2
  %6 = load i32, ptr %step_y11, align 4
  %mul12 = mul nsw i32 %6, %count_y
  %stride_y13 = getelementptr inbounds %struct.image2d_s, ptr %filter, i32 0, i32 4
  %7 = load i32, ptr %stride_y13, align 4
  %cmp14 = icmp sgt i32 %mul12, %7
  br i1 %cmp14, label %return, label %if.end16

if.end16:                                         ; preds = %if.end10
  %mul20 = mul nsw i32 %2, %1
  %mul23 = mul nsw i32 %6, %5
  %cmp2479 = icmp sgt i32 %count_y, 0
  br i1 %cmp2479, label %for.cond25.preheader.lr.ph, label %for.cond.cleanup

for.cond25.preheader.lr.ph:                       ; preds = %if.end16
  %8 = load ptr, ptr %filter, align 4
  %9 = load ptr, ptr %in_image, align 4
  %cmp2676 = icmp sgt i32 %count_x, 0
  %conv38 = zext i8 %offset to i32
  br label %for.cond25.preheader

for.cond25.preheader:                             ; preds = %for.cond.cleanup27, %for.cond25.preheader.lr.ph
  %y.083 = phi i32 [ 0, %for.cond25.preheader.lr.ph ], [ %inc43, %for.cond.cleanup27 ]
  %acc.082 = phi i32 [ 0, %for.cond25.preheader.lr.ph ], [ %acc.1.lcssa, %for.cond.cleanup27 ]
  %i_data.081 = phi ptr [ %9, %for.cond25.preheader.lr.ph ], [ %add.ptr, %for.cond.cleanup27 ]
  %f_data.080 = phi ptr [ %8, %for.cond25.preheader.lr.ph ], [ %add.ptr41, %for.cond.cleanup27 ]
  br i1 %cmp2676, label %for.body28, label %for.cond.cleanup27

for.cond.cleanup:                                 ; preds = %for.cond.cleanup27, %if.end16
  %acc.0.lcssa = phi i32 [ 0, %if.end16 ], [ %acc.1.lcssa, %for.cond.cleanup27 ]
  %sub = add nsw i32 %shift, -1
  %shl = shl nuw i32 1, %sub
  %add45 = add nsw i32 %acc.0.lcssa, %shl
  %shr = ashr i32 %add45, %shift
  %conv46 = trunc i32 %shr to i8
  store i8 %conv46, ptr %out_value, align 1
  br label %return

for.cond.cleanup27:                               ; preds = %for.body28, %for.cond25.preheader
  %acc.1.lcssa = phi i32 [ %acc.082, %for.cond25.preheader ], [ %add40, %for.body28 ]
  %add.ptr = getelementptr inbounds i8, ptr %i_data.081, i32 %mul20
  %add.ptr41 = getelementptr inbounds i8, ptr %f_data.080, i32 %mul23
  %inc43 = add nuw nsw i32 %y.083, 1
  %exitcond85.not = icmp eq i32 %inc43, %count_y
  br i1 %exitcond85.not, label %for.cond.cleanup, label %for.cond25.preheader

for.body28:                                       ; preds = %for.body28, %for.cond25.preheader
  %x.078 = phi i32 [ %inc, %for.body28 ], [ 0, %for.cond25.preheader ]
  %acc.177 = phi i32 [ %add40, %for.body28 ], [ %acc.082, %for.cond25.preheader ]
  %mul30 = mul nsw i32 %x.078, %0
  %arrayidx = getelementptr inbounds i8, ptr %i_data.081, i32 %mul30
  %10 = load i8, ptr %arrayidx, align 1
  %conv31 = zext i8 %10 to i32
  %mul33 = mul nsw i32 %x.078, %4
  %arrayidx34 = getelementptr inbounds i8, ptr %f_data.080, i32 %mul33
  %11 = load i8, ptr %arrayidx34, align 1
  %conv36 = zext i8 %11 to i32
  %add = add nuw nsw i32 %conv36, %conv38
  %mul39 = mul nuw nsw i32 %add, %conv31
  %add40 = add nsw i32 %mul39, %acc.177
  %inc = add nuw nsw i32 %x.078, 1
  %exitcond.not = icmp eq i32 %inc, %count_x
  br i1 %exitcond.not, label %for.cond.cleanup27, label %for.body28

return:                                           ; preds = %for.cond.cleanup, %if.end10, %if.end4, %if.end, %entry
  %retval.0 = phi i32 [ 0, %for.cond.cleanup ], [ 458755, %entry ], [ 458755, %if.end ], [ 458755, %if.end4 ], [ 458755, %if.end10 ]
  ret i32 %retval.0
}

