; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-int-loop-unroll-and-remainder -riscv-int-loop-unroll-and-remainder=false < %s | FileCheck %s

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite)
define dso_local noundef i32 @dsps_mulc_s16_ansi(ptr noundef readonly %input, ptr noundef writeonly %output, i32 noundef %len, i16 noundef signext %C, i32 noundef %step_in, i32 noundef %step_out) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dsps_mulc_s16_ansi(
; CHECK-SAME: ptr noundef readonly [[INPUT:%.*]], ptr noundef writeonly [[OUTPUT:%.*]], i32 noundef [[LEN:%.*]], i16 noundef signext [[C:%.*]], i32 noundef [[STEP_IN:%.*]], i32 noundef [[STEP_OUT:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[INPUT]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[OUTPUT]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    br i1 [[OR_COND]], label [[RETURN:%.*]], label [[FOR_COND_PREHEADER:%.*]]
; CHECK:       for.cond.preheader:
; CHECK-NEXT:    [[CMP415:%.*]] = icmp sgt i32 [[LEN]], 0
; CHECK-NEXT:    br i1 [[CMP415]], label [[FOR_BODY_LR_PH:%.*]], label [[RETURN]]
; CHECK:       for.body.lr.ph:
; CHECK-NEXT:    [[CONV5:%.*]] = sext i16 [[C]] to i32
; CHECK-NEXT:    br label [[FOR_BODY_CLONE:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_016_CLONE:%.*]] = phi i32 [ 0, [[FOR_BODY_LR_PH]] ], [ [[INC_CLONE:%.*]], [[FOR_BODY_CLONE]] ]
; CHECK-NEXT:    [[MUL_CLONE:%.*]] = mul nsw i32 [[I_016_CLONE]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_CLONE]]
; CHECK-NEXT:    [[TMP16:%.*]] = load i16, ptr [[ARRAYIDX_CLONE]], align 2
; CHECK-NEXT:    [[CONV_CLONE:%.*]] = sext i16 [[TMP16]] to i32
; CHECK-NEXT:    [[MUL6_CLONE:%.*]] = mul nsw i32 [[CONV_CLONE]], [[CONV5]]
; CHECK-NEXT:    [[SHR_CLONE:%.*]] = lshr i32 [[MUL6_CLONE]], 15
; CHECK-NEXT:    [[CONV7_CLONE:%.*]] = trunc i32 [[SHR_CLONE]] to i16
; CHECK-NEXT:    [[MUL8_CLONE:%.*]] = mul nsw i32 [[I_016_CLONE]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_CLONE:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_CLONE]]
; CHECK-NEXT:    store i16 [[CONV7_CLONE]], ptr [[ARRAYIDX9_CLONE]], align 2
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[I_016_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[RETURN]], label [[FOR_BODY_CLONE]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458755, [[ENTRY:%.*]] ], [ 0, [[FOR_COND_PREHEADER]] ], [ 0, [[FOR_BODY_CLONE]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %input, null
  %cmp1 = icmp eq ptr %output, null
  %or.cond = or i1 %cmp, %cmp1
  br i1 %or.cond, label %return, label %for.cond.preheader

for.cond.preheader:                               ; preds = %entry
  %cmp415 = icmp sgt i32 %len, 0
  br i1 %cmp415, label %for.body.lr.ph, label %return

for.body.lr.ph:                                   ; preds = %for.cond.preheader
  %conv5 = sext i16 %C to i32
  br label %for.body

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %i.016 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %mul = mul nsw i32 %i.016, %step_in
  %arrayidx = getelementptr inbounds i16, ptr %input, i32 %mul
  %0 = load i16, ptr %arrayidx, align 2
  %conv = sext i16 %0 to i32
  %mul6 = mul nsw i32 %conv, %conv5
  %shr = lshr i32 %mul6, 15
  %conv7 = trunc i32 %shr to i16
  %mul8 = mul nsw i32 %i.016, %step_out
  %arrayidx9 = getelementptr inbounds i16, ptr %output, i32 %mul8
  store i16 %conv7, ptr %arrayidx9, align 2
  %inc = add nuw nsw i32 %i.016, 1
  %exitcond.not = icmp eq i32 %inc, %len
  br i1 %exitcond.not, label %return, label %for.body

return:                                           ; preds = %for.body, %for.cond.preheader, %entry
  %retval.0 = phi i32 [ 458755, %entry ], [ 0, %for.cond.preheader ], [ 0, %for.body ]
  ret i32 %retval.0
}
