; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-int-loop-unroll-and-remainder -riscv-int-loop-unroll-and-remainder=false < %s | FileCheck %s

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite)
define dso_local noundef i32 @dsps_sub_s16_ansi(ptr noundef readonly %input1, ptr noundef readonly %input2, ptr noundef writeonly %output, i32 noundef %len, i32 noundef %step1, i32 noundef %step2, i32 noundef %step_out, i32 noundef %shift) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dsps_sub_s16_ansi(
; CHECK-SAME: ptr noundef readonly [[INPUT1:%.*]], ptr noundef readonly [[INPUT2:%.*]], ptr noundef writeonly [[OUTPUT:%.*]], i32 noundef [[LEN:%.*]], i32 noundef [[STEP1:%.*]], i32 noundef [[STEP2:%.*]], i32 noundef [[STEP_OUT:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[INPUT1]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[INPUT2]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    [[CMP4:%.*]] = icmp eq ptr [[OUTPUT]], null
; CHECK-NEXT:    [[OR_COND21:%.*]] = or i1 [[OR_COND]], [[CMP4]]
; CHECK-NEXT:    br i1 [[OR_COND21]], label [[RETURN:%.*]], label [[FOR_COND_PREHEADER:%.*]]
; CHECK:       for.cond.preheader:
; CHECK-NEXT:    [[CMP226415:%.*]] = icmp sgt i32 [[LEN]], 0
; CHECK-NEXT:    br i1 [[CMP226415]], label [[FOR_BODY_CLONE:%.*]], label [[RETURN]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I_023_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY_CLONE]] ], [ 0, [[FOR_COND_PREHEADER]] ]
; CHECK-NEXT:    [[MUL_CLONE:%.*]] = mul nsw i32 [[I_023_CLONE]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds i16, ptr [[INPUT1]], i32 [[MUL_CLONE]]
; CHECK-NEXT:    [[TMP32:%.*]] = load i16, ptr [[ARRAYIDX_CLONE]], align 2
; CHECK-NEXT:    [[CONV_CLONE:%.*]] = sext i16 [[TMP32]] to i32
; CHECK-NEXT:    [[MUL8_CLONE:%.*]] = mul nsw i32 [[I_023_CLONE]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_CLONE:%.*]] = getelementptr inbounds i16, ptr [[INPUT2]], i32 [[MUL8_CLONE]]
; CHECK-NEXT:    [[TMP33:%.*]] = load i16, ptr [[ARRAYIDX9_CLONE]], align 2
; CHECK-NEXT:    [[CONV10_CLONE:%.*]] = sext i16 [[TMP33]] to i32
; CHECK-NEXT:    [[SUB_CLONE:%.*]] = sub nsw i32 [[CONV_CLONE]], [[CONV10_CLONE]]
; CHECK-NEXT:    [[SHR_CLONE:%.*]] = ashr i32 [[SUB_CLONE]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_CLONE:%.*]] = trunc i32 [[SHR_CLONE]] to i16
; CHECK-NEXT:    [[MUL12_CLONE:%.*]] = mul nsw i32 [[I_023_CLONE]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_CLONE:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL12_CLONE]]
; CHECK-NEXT:    store i16 [[CONV11_CLONE]], ptr [[ARRAYIDX13_CLONE]], align 2
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[I_023_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[RETURN]], label [[FOR_BODY_CLONE]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458755, [[ENTRY:%.*]] ], [ 0, [[FOR_COND_PREHEADER]] ], [ 0, [[FOR_BODY_CLONE]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %input1, null
  %cmp1 = icmp eq ptr %input2, null
  %or.cond = or i1 %cmp, %cmp1
  %cmp4 = icmp eq ptr %output, null
  %or.cond21 = or i1 %or.cond, %cmp4
  br i1 %or.cond21, label %return, label %for.cond.preheader

for.cond.preheader:                               ; preds = %entry
  %cmp722 = icmp sgt i32 %len, 0
  br i1 %cmp722, label %for.body, label %return

for.body:                                         ; preds = %for.body, %for.cond.preheader
  %i.023 = phi i32 [ %inc, %for.body ], [ 0, %for.cond.preheader ]
  %mul = mul nsw i32 %i.023, %step1
  %arrayidx = getelementptr inbounds i16, ptr %input1, i32 %mul
  %0 = load i16, ptr %arrayidx, align 2
  %conv = sext i16 %0 to i32
  %mul8 = mul nsw i32 %i.023, %step2
  %arrayidx9 = getelementptr inbounds i16, ptr %input2, i32 %mul8
  %1 = load i16, ptr %arrayidx9, align 2
  %conv10 = sext i16 %1 to i32
  %sub = sub nsw i32 %conv, %conv10
  %shr = ashr i32 %sub, %shift
  %conv11 = trunc i32 %shr to i16
  %mul12 = mul nsw i32 %i.023, %step_out
  %arrayidx13 = getelementptr inbounds i16, ptr %output, i32 %mul12
  store i16 %conv11, ptr %arrayidx13, align 2
  %inc = add nuw nsw i32 %i.023, 1
  %exitcond.not = icmp eq i32 %inc, %len
  br i1 %exitcond.not, label %return, label %for.body

return:                                           ; preds = %for.body, %for.cond.preheader, %entry
  %retval.0 = phi i32 [ 458755, %entry ], [ 0, %for.cond.preheader ], [ 0, %for.body ]
  ret i32 %retval.0
}

