; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-int-loop-unroll-and-remainder -riscv-int-loop-unroll-and-remainder=true < %s | FileCheck %s

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite)
define dso_local noundef i32 @dsps_dotprod_s16_ansi(ptr nocapture noundef readonly %src1, ptr nocapture noundef readonly %src2, ptr nocapture noundef writeonly %dest, i32 noundef %len, i8 noundef signext %shift) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dsps_dotprod_s16_ansi(
; CHECK-SAME: ptr noalias noundef readonly captures(none) [[SRC1:%.*]], ptr noalias noundef readonly captures(none) [[SRC2:%.*]], ptr noalias noundef writeonly captures(none) [[DEST:%.*]], i32 noundef [[LEN:%.*]], i8 noundef signext [[SHIFT:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CONV:%.*]] = sext i8 [[SHIFT]] to i32
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 32767, [[CONV]]
; CHECK-NEXT:    [[CONV1:%.*]] = zext nneg i32 [[SHR]] to i64
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[LEN]], -8
; CHECK-NEXT:    [[CMP24:%.*]] = icmp sgt i32 [[LEN]], 7
; CHECK-NEXT:    br i1 [[CMP24]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND73_PREHEADER:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i32 [[AND]], -1
; CHECK-NEXT:    [[TMP1:%.*]] = and i32 [[TMP0]], -8
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[TMP1]], 8
; CHECK-NEXT:    br label [[FOR_COND73_PREHEADER]]
; CHECK:       for.cond73.preheader:
; CHECK-NEXT:    [[I_0_LCSSA:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[TMP2]], [[FOR_COND_CLEANUP_LOOPEXIT1:%.*]] ]
; CHECK-NEXT:    [[RESULT0_0_LCSSA:%.*]] = phi i64 [ [[CONV1]], [[ENTRY]] ], [ [[ADD_7:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT1]] ]
; CHECK-NEXT:    [[CMP74172:%.*]] = icmp slt i32 [[I_0_LCSSA]], [[LEN]]
; CHECK-NEXT:    br i1 [[CMP74172]], label [[FOR_BODY_CLONE:%.*]], label [[FOR_END85:%.*]]
; CHECK:       for.body.7:
; CHECK-NEXT:    [[RESULT0_0:%.*]] = phi i64 [ [[CONV1]], [[FOR_BODY_PREHEADER]] ], [ [[ADD_7]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[I_025:%.*]] = phi i32 [ 0, [[FOR_BODY_PREHEADER]] ], [ [[INC_7:%.*]], [[FOR_COND_CLEANUP_LOOPEXIT]] ]
; CHECK-NEXT:    [[INC:%.*]] = or disjoint i32 [[I_025]], 1
; CHECK-NEXT:    [[INC_1:%.*]] = or disjoint i32 [[I_025]], 2
; CHECK-NEXT:    [[INC_2:%.*]] = or disjoint i32 [[I_025]], 3
; CHECK-NEXT:    [[INC_3:%.*]] = or disjoint i32 [[I_025]], 4
; CHECK-NEXT:    [[INC_4:%.*]] = or disjoint i32 [[I_025]], 5
; CHECK-NEXT:    [[INC_5:%.*]] = or disjoint i32 [[I_025]], 6
; CHECK-NEXT:    [[INC_6:%.*]] = or disjoint i32 [[I_025]], 7
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC1]], i32 [[I_025]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC2]], i32 [[I_025]]
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC1]], i32 [[INC]]
; CHECK-NEXT:    [[ARRAYIDX4_1:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC2]], i32 [[INC]]
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC1]], i32 [[INC_1]]
; CHECK-NEXT:    [[ARRAYIDX4_2:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC2]], i32 [[INC_1]]
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC1]], i32 [[INC_2]]
; CHECK-NEXT:    [[ARRAYIDX4_3:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC2]], i32 [[INC_2]]
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC1]], i32 [[INC_3]]
; CHECK-NEXT:    [[ARRAYIDX4_4:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC2]], i32 [[INC_3]]
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC1]], i32 [[INC_4]]
; CHECK-NEXT:    [[ARRAYIDX4_5:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC2]], i32 [[INC_4]]
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC1]], i32 [[INC_5]]
; CHECK-NEXT:    [[ARRAYIDX4_6:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC2]], i32 [[INC_5]]
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC1]], i32 [[INC_6]]
; CHECK-NEXT:    [[ARRAYIDX4_7:%.*]] = getelementptr inbounds nuw i16, ptr [[SRC2]], i32 [[INC_6]]
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[ARRAYIDX]], align 2
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[ARRAYIDX4]], align 2
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[ARRAYIDX_1]], align 2
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[ARRAYIDX4_1]], align 2
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr [[ARRAYIDX_2]], align 2
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[ARRAYIDX4_2]], align 2
; CHECK-NEXT:    [[TMP9:%.*]] = load i16, ptr [[ARRAYIDX_3]], align 2
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[ARRAYIDX4_3]], align 2
; CHECK-NEXT:    [[TMP11:%.*]] = load i16, ptr [[ARRAYIDX_4]], align 2
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[ARRAYIDX4_4]], align 2
; CHECK-NEXT:    [[TMP13:%.*]] = load i16, ptr [[ARRAYIDX_5]], align 2
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[ARRAYIDX4_5]], align 2
; CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[ARRAYIDX_6]], align 2
; CHECK-NEXT:    [[TMP16:%.*]] = load i16, ptr [[ARRAYIDX4_6]], align 2
; CHECK-NEXT:    [[TMP17:%.*]] = load i16, ptr [[ARRAYIDX_7]], align 2
; CHECK-NEXT:    [[TMP18:%.*]] = load i16, ptr [[ARRAYIDX4_7]], align 2
; CHECK-NEXT:    [[CONV3:%.*]] = sext i16 [[TMP3]] to i32
; CHECK-NEXT:    [[CONV5:%.*]] = sext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[CONV3_1:%.*]] = sext i16 [[TMP5]] to i32
; CHECK-NEXT:    [[CONV5_1:%.*]] = sext i16 [[TMP6]] to i32
; CHECK-NEXT:    [[CONV3_2:%.*]] = sext i16 [[TMP7]] to i32
; CHECK-NEXT:    [[CONV5_2:%.*]] = sext i16 [[TMP8]] to i32
; CHECK-NEXT:    [[CONV3_3:%.*]] = sext i16 [[TMP9]] to i32
; CHECK-NEXT:    [[CONV5_3:%.*]] = sext i16 [[TMP10]] to i32
; CHECK-NEXT:    [[CONV3_4:%.*]] = sext i16 [[TMP11]] to i32
; CHECK-NEXT:    [[CONV5_4:%.*]] = sext i16 [[TMP12]] to i32
; CHECK-NEXT:    [[CONV3_5:%.*]] = sext i16 [[TMP13]] to i32
; CHECK-NEXT:    [[CONV5_5:%.*]] = sext i16 [[TMP14]] to i32
; CHECK-NEXT:    [[CONV3_6:%.*]] = sext i16 [[TMP15]] to i32
; CHECK-NEXT:    [[CONV5_6:%.*]] = sext i16 [[TMP16]] to i32
; CHECK-NEXT:    [[CONV3_7:%.*]] = sext i16 [[TMP17]] to i32
; CHECK-NEXT:    [[CONV5_7:%.*]] = sext i16 [[TMP18]] to i32
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[CONV5]], [[CONV3]]
; CHECK-NEXT:    [[MUL_1:%.*]] = mul nsw i32 [[CONV5_1]], [[CONV3_1]]
; CHECK-NEXT:    [[MUL_2:%.*]] = mul nsw i32 [[CONV5_2]], [[CONV3_2]]
; CHECK-NEXT:    [[MUL_3:%.*]] = mul nsw i32 [[CONV5_3]], [[CONV3_3]]
; CHECK-NEXT:    [[MUL_4:%.*]] = mul nsw i32 [[CONV5_4]], [[CONV3_4]]
; CHECK-NEXT:    [[MUL_5:%.*]] = mul nsw i32 [[CONV5_5]], [[CONV3_5]]
; CHECK-NEXT:    [[MUL_6:%.*]] = mul nsw i32 [[CONV5_6]], [[CONV3_6]]
; CHECK-NEXT:    [[MUL_7:%.*]] = mul nsw i32 [[CONV5_7]], [[CONV3_7]]
; CHECK-NEXT:    [[CONV6:%.*]] = sext i32 [[MUL]] to i64
; CHECK-NEXT:    [[CONV6_1:%.*]] = sext i32 [[MUL_1]] to i64
; CHECK-NEXT:    [[CONV6_2:%.*]] = sext i32 [[MUL_2]] to i64
; CHECK-NEXT:    [[CONV6_3:%.*]] = sext i32 [[MUL_3]] to i64
; CHECK-NEXT:    [[CONV6_4:%.*]] = sext i32 [[MUL_4]] to i64
; CHECK-NEXT:    [[CONV6_5:%.*]] = sext i32 [[MUL_5]] to i64
; CHECK-NEXT:    [[CONV6_6:%.*]] = sext i32 [[MUL_6]] to i64
; CHECK-NEXT:    [[CONV6_7:%.*]] = sext i32 [[MUL_7]] to i64
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i64 [[RESULT0_0]], [[CONV6]]
; CHECK-NEXT:    [[ADD_1:%.*]] = add nsw i64 [[ADD]], [[CONV6_1]]
; CHECK-NEXT:    [[ADD_2:%.*]] = add nsw i64 [[ADD_1]], [[CONV6_2]]
; CHECK-NEXT:    [[ADD_3:%.*]] = add nsw i64 [[ADD_2]], [[CONV6_3]]
; CHECK-NEXT:    [[ADD_4:%.*]] = add nsw i64 [[ADD_3]], [[CONV6_4]]
; CHECK-NEXT:    [[ADD_5:%.*]] = add nsw i64 [[ADD_4]], [[CONV6_5]]
; CHECK-NEXT:    [[ADD_6:%.*]] = add nsw i64 [[ADD_5]], [[CONV6_6]]
; CHECK-NEXT:    [[ADD_7]] = add nsw i64 [[ADD_6]], [[CONV6_7]]
; CHECK-NEXT:    [[INC_7]] = add nuw nsw i32 [[I_025]], 8
; CHECK-NEXT:    [[EXITCOND_NOT_7:%.*]] = icmp slt i32 [[INC_7]], [[AND]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_7]], label [[FOR_COND_CLEANUP_LOOPEXIT]], label [[FOR_COND_CLEANUP_LOOPEXIT1]]
; CHECK:       for.body.clone:
; CHECK-NEXT:    [[TMP19:%.*]] = phi i64 [ [[ADD_CLONE:%.*]], [[FOR_BODY_CLONE]] ], [ [[RESULT0_0_LCSSA]], [[FOR_COND73_PREHEADER]] ]
; CHECK-NEXT:    [[I_025_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY_CLONE]] ], [ [[I_0_LCSSA]], [[FOR_COND73_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds i16, ptr [[SRC1]], i32 [[I_025_CLONE]]
; CHECK-NEXT:    [[TMP20:%.*]] = load i16, ptr [[ARRAYIDX_CLONE]], align 2
; CHECK-NEXT:    [[CONV3_CLONE:%.*]] = sext i16 [[TMP20]] to i32
; CHECK-NEXT:    [[ARRAYIDX4_CLONE:%.*]] = getelementptr inbounds i16, ptr [[SRC2]], i32 [[I_025_CLONE]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[ARRAYIDX4_CLONE]], align 2
; CHECK-NEXT:    [[CONV5_CLONE:%.*]] = sext i16 [[TMP21]] to i32
; CHECK-NEXT:    [[MUL_CLONE:%.*]] = mul nsw i32 [[CONV5_CLONE]], [[CONV3_CLONE]]
; CHECK-NEXT:    [[CONV6_CLONE:%.*]] = sext i32 [[MUL_CLONE]] to i64
; CHECK-NEXT:    [[ADD_CLONE]] = add nsw i64 [[TMP19]], [[CONV6_CLONE]]
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[I_025_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_END85]], label [[FOR_BODY_CLONE]]
; CHECK:       for.end85:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi i64 [ [[RESULT0_0_LCSSA]], [[FOR_COND73_PREHEADER]] ], [ [[ADD_CLONE]], [[FOR_BODY_CLONE]] ]
; CHECK-NEXT:    [[CMP8:%.*]] = icmp sgt i8 [[SHIFT]], 15
; CHECK-NEXT:    br i1 [[CMP8]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[CONV]], -15
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[SUB]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl i64 [[ACC_0_LCSSA]], [[SH_PROM]]
; CHECK-NEXT:    br label [[IF_END:%.*]]
; CHECK:       if.else:
; CHECK-NEXT:    [[SUB11:%.*]] = sub nsw i32 15, [[CONV]]
; CHECK-NEXT:    [[SH_PROM12:%.*]] = zext nneg i32 [[SUB11]] to i64
; CHECK-NEXT:    [[SHR13:%.*]] = ashr i64 [[ACC_0_LCSSA]], [[SH_PROM12]]
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[SHR13_SINK:%.*]] = phi i64 [ [[SHR13]], [[IF_ELSE]] ], [ [[SHL]], [[IF_THEN]] ]
; CHECK-NEXT:    [[EXTRACT_T28:%.*]] = trunc i64 [[SHR13_SINK]] to i16
; CHECK-NEXT:    store i16 [[EXTRACT_T28]], ptr [[DEST]], align 2
; CHECK-NEXT:    ret i32 0
;
entry:
  %conv = sext i8 %shift to i32
  %shr = lshr i32 32767, %conv
  %conv1 = zext nneg i32 %shr to i64
  %cmp24 = icmp sgt i32 %len, 0
  br i1 %cmp24, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body, %entry
  %acc.0.lcssa = phi i64 [ %conv1, %entry ], [ %add, %for.body ]
  %cmp8 = icmp sgt i8 %shift, 15
  br i1 %cmp8, label %if.then, label %if.else

for.body:                                         ; preds = %for.body, %entry
  %acc.026 = phi i64 [ %add, %for.body ], [ %conv1, %entry ]
  %i.025 = phi i32 [ %inc, %for.body ], [ 0, %entry ]
  %arrayidx = getelementptr inbounds i16, ptr %src1, i32 %i.025
  %0 = load i16, ptr %arrayidx, align 2
  %conv3 = sext i16 %0 to i32
  %arrayidx4 = getelementptr inbounds i16, ptr %src2, i32 %i.025
  %1 = load i16, ptr %arrayidx4, align 2
  %conv5 = sext i16 %1 to i32
  %mul = mul nsw i32 %conv5, %conv3
  %conv6 = sext i32 %mul to i64
  %add = add nsw i64 %acc.026, %conv6
  %inc = add nuw nsw i32 %i.025, 1
  %exitcond.not = icmp eq i32 %inc, %len
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body

if.then:                                          ; preds = %for.cond.cleanup
  %sub = add nsw i32 %conv, -15
  %sh_prom = zext nneg i32 %sub to i64
  %shl = shl i64 %acc.0.lcssa, %sh_prom
  %extract.t29 = trunc i64 %shl to i16
  br label %if.end

if.else:                                          ; preds = %for.cond.cleanup
  %sub11 = sub nsw i32 15, %conv
  %sh_prom12 = zext nneg i32 %sub11 to i64
  %shr13 = ashr i64 %acc.0.lcssa, %sh_prom12
  %extract.t28 = trunc i64 %shr13 to i16
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %shr13.sink.off0 = phi i16 [ %extract.t28, %if.else ], [ %extract.t29, %if.then ]
  store i16 %shr13.sink.off0, ptr %dest, align 2
  ret i32 0
}

