; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-int-loop-unroll-and-remainder -riscv-int-loop-unroll-and-remainder=true < %s | FileCheck %s

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite)
define dso_local noundef i32 @dsps_mulc_s16_ansi(ptr noundef readonly %input, ptr noundef writeonly %output, i32 noundef %len, i16 noundef signext %C, i32 noundef %step_in, i32 noundef %step_out) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dsps_mulc_s16_ansi(
; CHECK-SAME: ptr noalias noundef readonly [[INPUT:%.*]], ptr noalias noundef writeonly [[OUTPUT:%.*]], i32 noundef [[LEN:%.*]], i16 noundef signext [[C:%.*]], i32 noundef [[STEP_IN:%.*]], i32 noundef [[STEP_OUT:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[INPUT]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[OUTPUT]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    br i1 [[OR_COND]], label [[RETURN:%.*]], label [[FOR_COND_PREHEADER:%.*]]
; CHECK:       for.cond.preheader:
; CHECK-NEXT:    [[CONV5:%.*]] = sext i16 [[C]] to i32
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[LEN]], -15
; CHECK-NEXT:    [[CMP415:%.*]] = icmp sgt i32 [[AND]], 0
; CHECK-NEXT:    br i1 [[CMP415]], label [[FOR_BODY_15:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[I_0_LCSSA:%.*]] = phi i32 [ 0, [[FOR_COND_PREHEADER]] ], [ [[INC_15:%.*]], [[FOR_BODY_15]] ]
; CHECK-NEXT:    [[CMP226415:%.*]] = icmp slt i32 [[I_0_LCSSA]], [[LEN]]
; CHECK-NEXT:    br i1 [[CMP226415]], label [[FOR_BODY_CLONE:%.*]], label [[RETURN]]
; CHECK:       for.body.15:
; CHECK-NEXT:    [[I_016:%.*]] = phi i32 [ [[INC_15]], [[FOR_BODY_15]] ], [ 0, [[FOR_COND_PREHEADER]] ]
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[I_016]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[ARRAYIDX]], align 2
; CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP0]] to i32
; CHECK-NEXT:    [[MUL6:%.*]] = mul nsw i32 [[CONV]], [[CONV5]]
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[MUL6]], 15
; CHECK-NEXT:    [[CONV7:%.*]] = trunc i32 [[SHR]] to i16
; CHECK-NEXT:    [[MUL8:%.*]] = mul nsw i32 [[I_016]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8]]
; CHECK-NEXT:    store i16 [[CONV7]], ptr [[ARRAYIDX9]], align 2
; CHECK-NEXT:    [[INC:%.*]] = or disjoint i32 [[I_016]], 1
; CHECK-NEXT:    [[MUL_1:%.*]] = mul nsw i32 [[INC]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_1]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[ARRAYIDX_1]], align 2
; CHECK-NEXT:    [[CONV_1:%.*]] = sext i16 [[TMP1]] to i32
; CHECK-NEXT:    [[MUL6_1:%.*]] = mul nsw i32 [[CONV_1]], [[CONV5]]
; CHECK-NEXT:    [[SHR_1:%.*]] = lshr i32 [[MUL6_1]], 15
; CHECK-NEXT:    [[CONV7_1:%.*]] = trunc i32 [[SHR_1]] to i16
; CHECK-NEXT:    [[MUL8_1:%.*]] = mul nsw i32 [[INC]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_1:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_1]]
; CHECK-NEXT:    store i16 [[CONV7_1]], ptr [[ARRAYIDX9_1]], align 2
; CHECK-NEXT:    [[INC_1:%.*]] = or disjoint i32 [[I_016]], 2
; CHECK-NEXT:    [[MUL_2:%.*]] = mul nsw i32 [[INC_1]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_2]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[ARRAYIDX_2]], align 2
; CHECK-NEXT:    [[CONV_2:%.*]] = sext i16 [[TMP2]] to i32
; CHECK-NEXT:    [[MUL6_2:%.*]] = mul nsw i32 [[CONV_2]], [[CONV5]]
; CHECK-NEXT:    [[SHR_2:%.*]] = lshr i32 [[MUL6_2]], 15
; CHECK-NEXT:    [[CONV7_2:%.*]] = trunc i32 [[SHR_2]] to i16
; CHECK-NEXT:    [[MUL8_2:%.*]] = mul nsw i32 [[INC_1]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_2:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_2]]
; CHECK-NEXT:    store i16 [[CONV7_2]], ptr [[ARRAYIDX9_2]], align 2
; CHECK-NEXT:    [[INC_2:%.*]] = or disjoint i32 [[I_016]], 3
; CHECK-NEXT:    [[MUL_3:%.*]] = mul nsw i32 [[INC_2]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_3]]
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[ARRAYIDX_3]], align 2
; CHECK-NEXT:    [[CONV_3:%.*]] = sext i16 [[TMP3]] to i32
; CHECK-NEXT:    [[MUL6_3:%.*]] = mul nsw i32 [[CONV_3]], [[CONV5]]
; CHECK-NEXT:    [[SHR_3:%.*]] = lshr i32 [[MUL6_3]], 15
; CHECK-NEXT:    [[CONV7_3:%.*]] = trunc i32 [[SHR_3]] to i16
; CHECK-NEXT:    [[MUL8_3:%.*]] = mul nsw i32 [[INC_2]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_3:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_3]]
; CHECK-NEXT:    store i16 [[CONV7_3]], ptr [[ARRAYIDX9_3]], align 2
; CHECK-NEXT:    [[INC_3:%.*]] = or disjoint i32 [[I_016]], 4
; CHECK-NEXT:    [[MUL_4:%.*]] = mul nsw i32 [[INC_3]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_4]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[ARRAYIDX_4]], align 2
; CHECK-NEXT:    [[CONV_4:%.*]] = sext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[MUL6_4:%.*]] = mul nsw i32 [[CONV_4]], [[CONV5]]
; CHECK-NEXT:    [[SHR_4:%.*]] = lshr i32 [[MUL6_4]], 15
; CHECK-NEXT:    [[CONV7_4:%.*]] = trunc i32 [[SHR_4]] to i16
; CHECK-NEXT:    [[MUL8_4:%.*]] = mul nsw i32 [[INC_3]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_4:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_4]]
; CHECK-NEXT:    store i16 [[CONV7_4]], ptr [[ARRAYIDX9_4]], align 2
; CHECK-NEXT:    [[INC_4:%.*]] = or disjoint i32 [[I_016]], 5
; CHECK-NEXT:    [[MUL_5:%.*]] = mul nsw i32 [[INC_4]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_5]]
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[ARRAYIDX_5]], align 2
; CHECK-NEXT:    [[CONV_5:%.*]] = sext i16 [[TMP5]] to i32
; CHECK-NEXT:    [[MUL6_5:%.*]] = mul nsw i32 [[CONV_5]], [[CONV5]]
; CHECK-NEXT:    [[SHR_5:%.*]] = lshr i32 [[MUL6_5]], 15
; CHECK-NEXT:    [[CONV7_5:%.*]] = trunc i32 [[SHR_5]] to i16
; CHECK-NEXT:    [[MUL8_5:%.*]] = mul nsw i32 [[INC_4]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_5:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_5]]
; CHECK-NEXT:    store i16 [[CONV7_5]], ptr [[ARRAYIDX9_5]], align 2
; CHECK-NEXT:    [[INC_5:%.*]] = or disjoint i32 [[I_016]], 6
; CHECK-NEXT:    [[MUL_6:%.*]] = mul nsw i32 [[INC_5]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_6]]
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[ARRAYIDX_6]], align 2
; CHECK-NEXT:    [[CONV_6:%.*]] = sext i16 [[TMP6]] to i32
; CHECK-NEXT:    [[MUL6_6:%.*]] = mul nsw i32 [[CONV_6]], [[CONV5]]
; CHECK-NEXT:    [[SHR_6:%.*]] = lshr i32 [[MUL6_6]], 15
; CHECK-NEXT:    [[CONV7_6:%.*]] = trunc i32 [[SHR_6]] to i16
; CHECK-NEXT:    [[MUL8_6:%.*]] = mul nsw i32 [[INC_5]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_6:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_6]]
; CHECK-NEXT:    store i16 [[CONV7_6]], ptr [[ARRAYIDX9_6]], align 2
; CHECK-NEXT:    [[INC_6:%.*]] = or disjoint i32 [[I_016]], 7
; CHECK-NEXT:    [[MUL_7:%.*]] = mul nsw i32 [[INC_6]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_7]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr [[ARRAYIDX_7]], align 2
; CHECK-NEXT:    [[CONV_7:%.*]] = sext i16 [[TMP7]] to i32
; CHECK-NEXT:    [[MUL6_7:%.*]] = mul nsw i32 [[CONV_7]], [[CONV5]]
; CHECK-NEXT:    [[SHR_7:%.*]] = lshr i32 [[MUL6_7]], 15
; CHECK-NEXT:    [[CONV7_7:%.*]] = trunc i32 [[SHR_7]] to i16
; CHECK-NEXT:    [[MUL8_7:%.*]] = mul nsw i32 [[INC_6]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_7:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_7]]
; CHECK-NEXT:    store i16 [[CONV7_7]], ptr [[ARRAYIDX9_7]], align 2
; CHECK-NEXT:    [[INC_7:%.*]] = or disjoint i32 [[I_016]], 8
; CHECK-NEXT:    [[MUL_8:%.*]] = mul nsw i32 [[INC_7]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_8:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_8]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[ARRAYIDX_8]], align 2
; CHECK-NEXT:    [[CONV_8:%.*]] = sext i16 [[TMP8]] to i32
; CHECK-NEXT:    [[MUL6_8:%.*]] = mul nsw i32 [[CONV_8]], [[CONV5]]
; CHECK-NEXT:    [[SHR_8:%.*]] = lshr i32 [[MUL6_8]], 15
; CHECK-NEXT:    [[CONV7_8:%.*]] = trunc i32 [[SHR_8]] to i16
; CHECK-NEXT:    [[MUL8_8:%.*]] = mul nsw i32 [[INC_7]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_8:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_8]]
; CHECK-NEXT:    store i16 [[CONV7_8]], ptr [[ARRAYIDX9_8]], align 2
; CHECK-NEXT:    [[INC_8:%.*]] = or disjoint i32 [[I_016]], 9
; CHECK-NEXT:    [[MUL_9:%.*]] = mul nsw i32 [[INC_8]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_9:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_9]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i16, ptr [[ARRAYIDX_9]], align 2
; CHECK-NEXT:    [[CONV_9:%.*]] = sext i16 [[TMP9]] to i32
; CHECK-NEXT:    [[MUL6_9:%.*]] = mul nsw i32 [[CONV_9]], [[CONV5]]
; CHECK-NEXT:    [[SHR_9:%.*]] = lshr i32 [[MUL6_9]], 15
; CHECK-NEXT:    [[CONV7_9:%.*]] = trunc i32 [[SHR_9]] to i16
; CHECK-NEXT:    [[MUL8_9:%.*]] = mul nsw i32 [[INC_8]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_9:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_9]]
; CHECK-NEXT:    store i16 [[CONV7_9]], ptr [[ARRAYIDX9_9]], align 2
; CHECK-NEXT:    [[INC_9:%.*]] = or disjoint i32 [[I_016]], 10
; CHECK-NEXT:    [[MUL_10:%.*]] = mul nsw i32 [[INC_9]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_10:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_10]]
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[ARRAYIDX_10]], align 2
; CHECK-NEXT:    [[CONV_10:%.*]] = sext i16 [[TMP10]] to i32
; CHECK-NEXT:    [[MUL6_10:%.*]] = mul nsw i32 [[CONV_10]], [[CONV5]]
; CHECK-NEXT:    [[SHR_10:%.*]] = lshr i32 [[MUL6_10]], 15
; CHECK-NEXT:    [[CONV7_10:%.*]] = trunc i32 [[SHR_10]] to i16
; CHECK-NEXT:    [[MUL8_10:%.*]] = mul nsw i32 [[INC_9]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_10:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_10]]
; CHECK-NEXT:    store i16 [[CONV7_10]], ptr [[ARRAYIDX9_10]], align 2
; CHECK-NEXT:    [[INC_10:%.*]] = or disjoint i32 [[I_016]], 11
; CHECK-NEXT:    [[MUL_11:%.*]] = mul nsw i32 [[INC_10]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_11:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_11]]
; CHECK-NEXT:    [[TMP11:%.*]] = load i16, ptr [[ARRAYIDX_11]], align 2
; CHECK-NEXT:    [[CONV_11:%.*]] = sext i16 [[TMP11]] to i32
; CHECK-NEXT:    [[MUL6_11:%.*]] = mul nsw i32 [[CONV_11]], [[CONV5]]
; CHECK-NEXT:    [[SHR_11:%.*]] = lshr i32 [[MUL6_11]], 15
; CHECK-NEXT:    [[CONV7_11:%.*]] = trunc i32 [[SHR_11]] to i16
; CHECK-NEXT:    [[MUL8_11:%.*]] = mul nsw i32 [[INC_10]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_11:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_11]]
; CHECK-NEXT:    store i16 [[CONV7_11]], ptr [[ARRAYIDX9_11]], align 2
; CHECK-NEXT:    [[INC_11:%.*]] = or disjoint i32 [[I_016]], 12
; CHECK-NEXT:    [[MUL_12:%.*]] = mul nsw i32 [[INC_11]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_12:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_12]]
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[ARRAYIDX_12]], align 2
; CHECK-NEXT:    [[CONV_12:%.*]] = sext i16 [[TMP12]] to i32
; CHECK-NEXT:    [[MUL6_12:%.*]] = mul nsw i32 [[CONV_12]], [[CONV5]]
; CHECK-NEXT:    [[SHR_12:%.*]] = lshr i32 [[MUL6_12]], 15
; CHECK-NEXT:    [[CONV7_12:%.*]] = trunc i32 [[SHR_12]] to i16
; CHECK-NEXT:    [[MUL8_12:%.*]] = mul nsw i32 [[INC_11]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_12:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_12]]
; CHECK-NEXT:    store i16 [[CONV7_12]], ptr [[ARRAYIDX9_12]], align 2
; CHECK-NEXT:    [[INC_12:%.*]] = or disjoint i32 [[I_016]], 13
; CHECK-NEXT:    [[MUL_13:%.*]] = mul nsw i32 [[INC_12]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_13:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_13]]
; CHECK-NEXT:    [[TMP13:%.*]] = load i16, ptr [[ARRAYIDX_13]], align 2
; CHECK-NEXT:    [[CONV_13:%.*]] = sext i16 [[TMP13]] to i32
; CHECK-NEXT:    [[MUL6_13:%.*]] = mul nsw i32 [[CONV_13]], [[CONV5]]
; CHECK-NEXT:    [[SHR_13:%.*]] = lshr i32 [[MUL6_13]], 15
; CHECK-NEXT:    [[CONV7_13:%.*]] = trunc i32 [[SHR_13]] to i16
; CHECK-NEXT:    [[MUL8_13:%.*]] = mul nsw i32 [[INC_12]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_13:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_13]]
; CHECK-NEXT:    store i16 [[CONV7_13]], ptr [[ARRAYIDX9_13]], align 2
; CHECK-NEXT:    [[INC_13:%.*]] = or disjoint i32 [[I_016]], 14
; CHECK-NEXT:    [[MUL_14:%.*]] = mul nsw i32 [[INC_13]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_14:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_14]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[ARRAYIDX_14]], align 2
; CHECK-NEXT:    [[CONV_14:%.*]] = sext i16 [[TMP14]] to i32
; CHECK-NEXT:    [[MUL6_14:%.*]] = mul nsw i32 [[CONV_14]], [[CONV5]]
; CHECK-NEXT:    [[SHR_14:%.*]] = lshr i32 [[MUL6_14]], 15
; CHECK-NEXT:    [[CONV7_14:%.*]] = trunc i32 [[SHR_14]] to i16
; CHECK-NEXT:    [[MUL8_14:%.*]] = mul nsw i32 [[INC_13]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_14:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_14]]
; CHECK-NEXT:    store i16 [[CONV7_14]], ptr [[ARRAYIDX9_14]], align 2
; CHECK-NEXT:    [[INC_14:%.*]] = or disjoint i32 [[I_016]], 15
; CHECK-NEXT:    [[MUL_15:%.*]] = mul nsw i32 [[INC_14]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_15:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_15]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[ARRAYIDX_15]], align 2
; CHECK-NEXT:    [[CONV_15:%.*]] = sext i16 [[TMP15]] to i32
; CHECK-NEXT:    [[MUL6_15:%.*]] = mul nsw i32 [[CONV_15]], [[CONV5]]
; CHECK-NEXT:    [[SHR_15:%.*]] = lshr i32 [[MUL6_15]], 15
; CHECK-NEXT:    [[CONV7_15:%.*]] = trunc i32 [[SHR_15]] to i16
; CHECK-NEXT:    [[MUL8_15:%.*]] = mul nsw i32 [[INC_14]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_15:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_15]]
; CHECK-NEXT:    store i16 [[CONV7_15]], ptr [[ARRAYIDX9_15]], align 2
; CHECK-NEXT:    [[INC_15]] = add nuw nsw i32 [[I_016]], 16
; CHECK-NEXT:    [[EXITCOND_NOT_15:%.*]] = icmp slt i32 [[INC_15]], [[AND]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_15]], label [[FOR_BODY_15]], label [[FOR_BODY_PREHEADER]]
; CHECK:       for.body.clone:
; CHECK-NEXT:    [[I_016_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY_CLONE]] ], [ [[I_0_LCSSA]], [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[MUL_CLONE:%.*]] = mul nsw i32 [[I_016_CLONE]], [[STEP_IN]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[MUL_CLONE]]
; CHECK-NEXT:    [[TMP16:%.*]] = load i16, ptr [[ARRAYIDX_CLONE]], align 2
; CHECK-NEXT:    [[CONV_CLONE:%.*]] = sext i16 [[TMP16]] to i32
; CHECK-NEXT:    [[MUL6_CLONE:%.*]] = mul nsw i32 [[CONV_CLONE]], [[CONV5]]
; CHECK-NEXT:    [[SHR_CLONE:%.*]] = lshr i32 [[MUL6_CLONE]], 15
; CHECK-NEXT:    [[CONV7_CLONE:%.*]] = trunc i32 [[SHR_CLONE]] to i16
; CHECK-NEXT:    [[MUL8_CLONE:%.*]] = mul nsw i32 [[I_016_CLONE]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX9_CLONE:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[MUL8_CLONE]]
; CHECK-NEXT:    store i16 [[CONV7_CLONE]], ptr [[ARRAYIDX9_CLONE]], align 2
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[I_016_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[RETURN]], label [[FOR_BODY_CLONE]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458755, [[ENTRY:%.*]] ], [ 0, [[FOR_BODY_PREHEADER]] ], [ 0, [[FOR_BODY_CLONE]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %input, null
  %cmp1 = icmp eq ptr %output, null
  %or.cond = or i1 %cmp, %cmp1
  br i1 %or.cond, label %return, label %for.cond.preheader

for.cond.preheader:                               ; preds = %entry
  %cmp415 = icmp sgt i32 %len, 0
  br i1 %cmp415, label %for.body.lr.ph, label %return

for.body.lr.ph:                                   ; preds = %for.cond.preheader
  %conv5 = sext i16 %C to i32
  br label %for.body

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %i.016 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %for.body ]
  %mul = mul nsw i32 %i.016, %step_in
  %arrayidx = getelementptr inbounds i16, ptr %input, i32 %mul
  %0 = load i16, ptr %arrayidx, align 2
  %conv = sext i16 %0 to i32
  %mul6 = mul nsw i32 %conv, %conv5
  %shr = lshr i32 %mul6, 15
  %conv7 = trunc i32 %shr to i16
  %mul8 = mul nsw i32 %i.016, %step_out
  %arrayidx9 = getelementptr inbounds i16, ptr %output, i32 %mul8
  store i16 %conv7, ptr %arrayidx9, align 2
  %inc = add nuw nsw i32 %i.016, 1
  %exitcond.not = icmp eq i32 %inc, %len
  br i1 %exitcond.not, label %return, label %for.body

return:                                           ; preds = %for.body, %for.cond.preheader, %entry
  %retval.0 = phi i32 [ 458755, %entry ], [ 0, %for.cond.preheader ], [ 0, %for.body ]
  ret i32 %retval.0
}
