; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-int-loop-unroll-and-remainder -riscv-int-loop-unroll-and-remainder=true < %s | FileCheck %s


; Function Attrs: nofree norecurse nosync nounwind memory(readwrite, inaccessiblemem: none)
define dso_local noundef i32 @dsps_fird_s16_ansi(ptr nocapture noundef %fir, ptr nocapture noundef readonly %input, ptr nocapture noundef writeonly %output, i32 noundef %len) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dsps_fird_s16_ansi(
; CHECK-SAME: ptr noalias noundef captures(none) [[FIR:%.*]], ptr noalias noundef readonly captures(none) [[INPUT:%.*]], ptr noalias noundef writeonly captures(none) [[OUTPUT:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[FIR]], align 4
; CHECK-NEXT:    [[SHIFT:%.*]] = getelementptr inbounds nuw i8, ptr [[FIR]], i32 16
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[SHIFT]], align 4
; CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP1]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[CONV]], -15
; CHECK-NEXT:    [[ROUNDING_VAL:%.*]] = getelementptr inbounds nuw i8, ptr [[FIR]], i32 24
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[ROUNDING_VAL]], align 4
; CHECK-NEXT:    [[CONV1:%.*]] = sext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i16 [[TMP1]], -1
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[CONV]] to i64
; CHECK-NEXT:    [[SHR:%.*]] = ashr i64 [[CONV1]], [[SH_PROM]]
; CHECK-NEXT:    br label [[IF_END:%.*]]
; CHECK:       if.else:
; CHECK-NEXT:    [[SUB9:%.*]] = sub nsw i32 0, [[CONV]]
; CHECK-NEXT:    [[SH_PROM10:%.*]] = zext nneg i32 [[SUB9]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl i64 [[CONV1]], [[SH_PROM10]]
; CHECK-NEXT:    br label [[IF_END]]
; CHECK:       if.end:
; CHECK-NEXT:    [[ROUNDING_0_IN:%.*]] = phi i64 [ [[SHR]], [[IF_THEN]] ], [ [[SHL]], [[IF_ELSE]] ]
; CHECK-NEXT:    [[ROUNDING_0:%.*]] = and i64 [[ROUNDING_0_IN]], 1099511627775
; CHECK-NEXT:    [[CMP12153:%.*]] = icmp sgt i32 [[LEN]], 0
; CHECK-NEXT:    br i1 [[CMP12153]], label [[FOR_COND14_PREHEADER_LR_PH:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.cond14.preheader.lr.ph:
; CHECK-NEXT:    [[DECIM:%.*]] = getelementptr inbounds nuw i8, ptr [[FIR]], i32 12
; CHECK-NEXT:    [[D_POS:%.*]] = getelementptr inbounds nuw i8, ptr [[FIR]], i32 14
; CHECK-NEXT:    [[POS:%.*]] = getelementptr inbounds nuw i8, ptr [[FIR]], i32 10
; CHECK-NEXT:    [[COEFFS_LEN:%.*]] = getelementptr inbounds nuw i8, ptr [[FIR]], i32 8
; CHECK-NEXT:    [[DELAY:%.*]] = getelementptr inbounds nuw i8, ptr [[FIR]], i32 4
; CHECK-NEXT:    [[CMP79:%.*]] = icmp sgt i16 [[TMP1]], 15
; CHECK-NEXT:    [[SUB88:%.*]] = sub nsw i32 15, [[CONV]]
; CHECK-NEXT:    [[SH_PROM89:%.*]] = zext nneg i32 [[SUB88]] to i64
; CHECK-NEXT:    [[SH_PROM82:%.*]] = zext nneg i32 [[SUB]] to i64
; CHECK-NEXT:    [[DELAY_PTR_HOISTED:%.*]] = load ptr, ptr [[DELAY]], align 4
; CHECK-NEXT:    br label [[FOR_COND14_PREHEADER:%.*]]
; CHECK:       for.cond14.preheader:
; CHECK-NEXT:    [[I_0156:%.*]] = phi i32 [ 0, [[FOR_COND14_PREHEADER_LR_PH]] ], [ [[INC96:%.*]], [[FOR_COND_CLEANUP63:%.*]] ]
; CHECK-NEXT:    [[INPUT_POS_0154:%.*]] = phi i32 [ 0, [[FOR_COND14_PREHEADER_LR_PH]] ], [ [[INPUT_POS_1_LCSSA:%.*]], [[FOR_COND_CLEANUP63]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[DECIM]], align 4
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[D_POS]], align 2
; CHECK-NEXT:    [[CMP18138:%.*]] = icmp sgt i16 [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[DOTPRE3:%.*]] = load i16, ptr [[COEFFS_LEN]], align 4
; CHECK-NEXT:    [[DOTPRE4:%.*]] = load i16, ptr [[POS]], align 2
; CHECK-NEXT:    br i1 [[CMP18138]], label [[FOR_COND14_PREHEADER_FOR_BODY21_CRIT_EDGE:%.*]], label [[FOR_COND_CLEANUP20:%.*]]
; CHECK:       for.cond14.preheader.for.body21_crit_edge:
; CHECK-NEXT:    br label [[FOR_BODY21:%.*]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    [[RESULT_0_LCSSA:%.*]] = phi i32 [ 0, [[IF_END]] ], [ [[LEN]], [[FOR_COND_CLEANUP63]] ]
; CHECK-NEXT:    ret i32 [[RESULT_0_LCSSA]]
; CHECK:       for.cond.cleanup20:
; CHECK-NEXT:    [[TMP5:%.*]] = phi i16 [ [[DOTPRE4]], [[FOR_COND14_PREHEADER]] ], [ [[INC30:%.*]], [[IF_END28:%.*]] ]
; CHECK-NEXT:    [[INPUT_POS_1_LCSSA]] = phi i32 [ [[INPUT_POS_0154]], [[FOR_COND14_PREHEADER]] ], [ [[INC:%.*]], [[IF_END28]] ]
; CHECK-NEXT:    store i16 0, ptr [[D_POS]], align 2
; CHECK-NEXT:    [[CONV39:%.*]] = sext i16 [[TMP5]] to i32
; CHECK-NEXT:    [[CONV42:%.*]] = sext i16 [[DOTPRE3]] to i32
; CHECK-NEXT:    [[COEFF_POS_0141:%.*]] = add i16 [[DOTPRE3]], -1
; CHECK-NEXT:    [[SUB45:%.*]] = add nsw i32 [[CONV42]], -15
; CHECK-NEXT:    [[CMP43142:%.*]] = icmp sgt i32 [[SUB45]], [[CONV39]]
; CHECK-NEXT:    br i1 [[CMP43142]], label [[FOR_BODY46_15:%.*]], label [[FOR_COND58_PREHEADER:%.*]]
; CHECK:       for.body21:
; CHECK-NEXT:    [[TMP6:%.*]] = phi i16 [ [[INC30]], [[IF_END28]] ], [ [[DOTPRE4]], [[FOR_COND14_PREHEADER_FOR_BODY21_CRIT_EDGE]] ]
; CHECK-NEXT:    [[J_0140:%.*]] = phi i32 [ [[INC32:%.*]], [[IF_END28]] ], [ 0, [[FOR_COND14_PREHEADER_FOR_BODY21_CRIT_EDGE]] ]
; CHECK-NEXT:    [[INPUT_POS_1139:%.*]] = phi i32 [ [[INC]], [[IF_END28]] ], [ [[INPUT_POS_0154]], [[FOR_COND14_PREHEADER_FOR_BODY21_CRIT_EDGE]] ]
; CHECK-NEXT:    [[CMP24_NOT:%.*]] = icmp slt i16 [[TMP6]], [[DOTPRE3]]
; CHECK-NEXT:    br i1 [[CMP24_NOT]], label [[IF_END28]], label [[IF_THEN26:%.*]]
; CHECK:       if.then26:
; CHECK-NEXT:    store i16 0, ptr [[POS]], align 2
; CHECK-NEXT:    br label [[IF_END28]]
; CHECK:       if.end28:
; CHECK-NEXT:    [[TMP7:%.*]] = phi i16 [ 0, [[IF_THEN26]] ], [ [[TMP6]], [[FOR_BODY21]] ]
; CHECK-NEXT:    [[INC]] = add nsw i32 [[INPUT_POS_1139]], 1
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[INPUT_POS_1139]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[ARRAYIDX]], align 2
; CHECK-NEXT:    [[INC30]] = add nsw i16 [[TMP7]], 1
; CHECK-NEXT:    store i16 [[INC30]], ptr [[POS]], align 2
; CHECK-NEXT:    [[IDXPROM:%.*]] = sext i16 [[TMP7]] to i32
; CHECK-NEXT:    [[ARRAYIDX31:%.*]] = getelementptr inbounds i16, ptr [[DELAY_PTR_HOISTED]], i32 [[IDXPROM]]
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[ARRAYIDX31]], align 2
; CHECK-NEXT:    [[INC32]] = add nuw nsw i32 [[J_0140]], 1
; CHECK-NEXT:    [[CONV15:%.*]] = sext i16 [[TMP3]] to i32
; CHECK-NEXT:    [[CONV16:%.*]] = sext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[SUB17:%.*]] = sub nsw i32 [[CONV15]], [[CONV16]]
; CHECK-NEXT:    [[CMP18:%.*]] = icmp slt i32 [[INC32]], [[SUB17]]
; CHECK-NEXT:    br i1 [[CMP18]], label [[FOR_BODY21]], label [[FOR_COND_CLEANUP20]]
; CHECK:       for.cond58.preheader:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi i64 [ [[ROUNDING_0]], [[FOR_COND_CLEANUP20]] ], [ [[ADD_15:%.*]], [[FOR_BODY46_15]] ]
; CHECK-NEXT:    [[COEFF_POS_0_LCSSA:%.*]] = phi i16 [ [[COEFF_POS_0141]], [[FOR_COND_CLEANUP20]] ], [ [[COEFF_POS_0_15:%.*]], [[FOR_BODY46_15]] ]
; CHECK-NEXT:    [[N_0_LCSSA:%.*]] = phi i32 [ [[CONV39]], [[FOR_COND_CLEANUP20]] ], [ [[INC55_15:%.*]], [[FOR_BODY46_15]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = trunc i32 [[N_0_LCSSA]] to i16
; CHECK-NEXT:    [[CMP61148:%.*]] = icmp slt i32 [[N_0_LCSSA]], [[CONV42]]
; CHECK-NEXT:    br i1 [[CMP61148]], label [[FOR_BODY46_CLONE:%.*]], label [[FOR_COND227_PREHEADER:%.*]]
; CHECK:       for.body46.15:
; CHECK-NEXT:    [[COEFF_POS_0145:%.*]] = phi i16 [ [[COEFF_POS_0_15]], [[FOR_BODY46_15]] ], [ [[COEFF_POS_0141]], [[FOR_COND_CLEANUP20]] ]
; CHECK-NEXT:    [[N_0144:%.*]] = phi i32 [ [[INC55_15]], [[FOR_BODY46_15]] ], [ [[CONV39]], [[FOR_COND_CLEANUP20]] ]
; CHECK-NEXT:    [[ACC_0143:%.*]] = phi i64 [ [[ADD_15]], [[FOR_BODY46_15]] ], [ [[ROUNDING_0]], [[FOR_COND_CLEANUP20]] ]
; CHECK-NEXT:    [[IDXPROM47:%.*]] = sext i16 [[COEFF_POS_0145]] to i32
; CHECK-NEXT:    [[ARRAYIDX48:%.*]] = getelementptr inbounds i16, ptr [[TMP0]], i32 [[IDXPROM47]]
; CHECK-NEXT:    [[ARRAYIDX51:%.*]] = getelementptr inbounds i16, ptr [[DELAY_PTR_HOISTED]], i32 [[N_0144]]
; CHECK-NEXT:    [[ARRAYIDX48_1:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -2
; CHECK-NEXT:    [[ARRAYIDX51_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 2
; CHECK-NEXT:    [[ARRAYIDX48_2:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -4
; CHECK-NEXT:    [[ARRAYIDX51_2:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 4
; CHECK-NEXT:    [[ARRAYIDX48_3:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -6
; CHECK-NEXT:    [[ARRAYIDX51_3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 6
; CHECK-NEXT:    [[ARRAYIDX48_4:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -8
; CHECK-NEXT:    [[ARRAYIDX51_4:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 8
; CHECK-NEXT:    [[ARRAYIDX48_5:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -10
; CHECK-NEXT:    [[ARRAYIDX51_5:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 10
; CHECK-NEXT:    [[ARRAYIDX48_6:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -12
; CHECK-NEXT:    [[ARRAYIDX51_6:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 12
; CHECK-NEXT:    [[ARRAYIDX48_7:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -14
; CHECK-NEXT:    [[ARRAYIDX51_7:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 14
; CHECK-NEXT:    [[ARRAYIDX48_8:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -16
; CHECK-NEXT:    [[ARRAYIDX51_8:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 16
; CHECK-NEXT:    [[ARRAYIDX48_9:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -18
; CHECK-NEXT:    [[ARRAYIDX51_9:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 18
; CHECK-NEXT:    [[ARRAYIDX48_10:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -20
; CHECK-NEXT:    [[ARRAYIDX51_10:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 20
; CHECK-NEXT:    [[ARRAYIDX48_11:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -22
; CHECK-NEXT:    [[ARRAYIDX51_11:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 22
; CHECK-NEXT:    [[ARRAYIDX48_12:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -24
; CHECK-NEXT:    [[ARRAYIDX51_12:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 24
; CHECK-NEXT:    [[ARRAYIDX48_13:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -26
; CHECK-NEXT:    [[ARRAYIDX51_13:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 26
; CHECK-NEXT:    [[ARRAYIDX48_14:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -28
; CHECK-NEXT:    [[ARRAYIDX51_14:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 28
; CHECK-NEXT:    [[ARRAYIDX48_15:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX48]], i32 -30
; CHECK-NEXT:    [[ARRAYIDX51_15:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX51]], i32 30
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[ARRAYIDX48]], align 2
; CHECK-NEXT:    [[TMP11:%.*]] = load i16, ptr [[ARRAYIDX51]], align 2
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[ARRAYIDX48_1]], align 2
; CHECK-NEXT:    [[TMP13:%.*]] = load i16, ptr [[ARRAYIDX51_1]], align 2
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[ARRAYIDX48_2]], align 2
; CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[ARRAYIDX51_2]], align 2
; CHECK-NEXT:    [[TMP16:%.*]] = load i16, ptr [[ARRAYIDX48_3]], align 2
; CHECK-NEXT:    [[TMP17:%.*]] = load i16, ptr [[ARRAYIDX51_3]], align 2
; CHECK-NEXT:    [[TMP18:%.*]] = load i16, ptr [[ARRAYIDX48_4]], align 2
; CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[ARRAYIDX51_4]], align 2
; CHECK-NEXT:    [[TMP20:%.*]] = load i16, ptr [[ARRAYIDX48_5]], align 2
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[ARRAYIDX51_5]], align 2
; CHECK-NEXT:    [[TMP22:%.*]] = load i16, ptr [[ARRAYIDX48_6]], align 2
; CHECK-NEXT:    [[TMP23:%.*]] = load i16, ptr [[ARRAYIDX51_6]], align 2
; CHECK-NEXT:    [[TMP24:%.*]] = load i16, ptr [[ARRAYIDX48_7]], align 2
; CHECK-NEXT:    [[TMP25:%.*]] = load i16, ptr [[ARRAYIDX51_7]], align 2
; CHECK-NEXT:    [[TMP26:%.*]] = load i16, ptr [[ARRAYIDX48_8]], align 2
; CHECK-NEXT:    [[TMP27:%.*]] = load i16, ptr [[ARRAYIDX51_8]], align 2
; CHECK-NEXT:    [[TMP28:%.*]] = load i16, ptr [[ARRAYIDX48_9]], align 2
; CHECK-NEXT:    [[TMP29:%.*]] = load i16, ptr [[ARRAYIDX51_9]], align 2
; CHECK-NEXT:    [[TMP30:%.*]] = load i16, ptr [[ARRAYIDX48_10]], align 2
; CHECK-NEXT:    [[TMP31:%.*]] = load i16, ptr [[ARRAYIDX51_10]], align 2
; CHECK-NEXT:    [[TMP32:%.*]] = load i16, ptr [[ARRAYIDX48_11]], align 2
; CHECK-NEXT:    [[TMP33:%.*]] = load i16, ptr [[ARRAYIDX51_11]], align 2
; CHECK-NEXT:    [[TMP34:%.*]] = load i16, ptr [[ARRAYIDX48_12]], align 2
; CHECK-NEXT:    [[TMP35:%.*]] = load i16, ptr [[ARRAYIDX51_12]], align 2
; CHECK-NEXT:    [[TMP36:%.*]] = load i16, ptr [[ARRAYIDX48_13]], align 2
; CHECK-NEXT:    [[TMP37:%.*]] = load i16, ptr [[ARRAYIDX51_13]], align 2
; CHECK-NEXT:    [[TMP38:%.*]] = load i16, ptr [[ARRAYIDX48_14]], align 2
; CHECK-NEXT:    [[TMP39:%.*]] = load i16, ptr [[ARRAYIDX51_14]], align 2
; CHECK-NEXT:    [[TMP40:%.*]] = load i16, ptr [[ARRAYIDX48_15]], align 2
; CHECK-NEXT:    [[TMP41:%.*]] = load i16, ptr [[ARRAYIDX51_15]], align 2
; CHECK-NEXT:    [[CONV49:%.*]] = sext i16 [[TMP10]] to i32
; CHECK-NEXT:    [[CONV52:%.*]] = sext i16 [[TMP11]] to i32
; CHECK-NEXT:    [[CONV49_1:%.*]] = sext i16 [[TMP12]] to i32
; CHECK-NEXT:    [[CONV52_1:%.*]] = sext i16 [[TMP13]] to i32
; CHECK-NEXT:    [[CONV49_2:%.*]] = sext i16 [[TMP14]] to i32
; CHECK-NEXT:    [[CONV52_2:%.*]] = sext i16 [[TMP15]] to i32
; CHECK-NEXT:    [[CONV49_3:%.*]] = sext i16 [[TMP16]] to i32
; CHECK-NEXT:    [[CONV52_3:%.*]] = sext i16 [[TMP17]] to i32
; CHECK-NEXT:    [[CONV49_4:%.*]] = sext i16 [[TMP18]] to i32
; CHECK-NEXT:    [[CONV52_4:%.*]] = sext i16 [[TMP19]] to i32
; CHECK-NEXT:    [[CONV49_5:%.*]] = sext i16 [[TMP20]] to i32
; CHECK-NEXT:    [[CONV52_5:%.*]] = sext i16 [[TMP21]] to i32
; CHECK-NEXT:    [[CONV49_6:%.*]] = sext i16 [[TMP22]] to i32
; CHECK-NEXT:    [[CONV52_6:%.*]] = sext i16 [[TMP23]] to i32
; CHECK-NEXT:    [[CONV49_7:%.*]] = sext i16 [[TMP24]] to i32
; CHECK-NEXT:    [[CONV52_7:%.*]] = sext i16 [[TMP25]] to i32
; CHECK-NEXT:    [[CONV49_8:%.*]] = sext i16 [[TMP26]] to i32
; CHECK-NEXT:    [[CONV52_8:%.*]] = sext i16 [[TMP27]] to i32
; CHECK-NEXT:    [[CONV49_9:%.*]] = sext i16 [[TMP28]] to i32
; CHECK-NEXT:    [[CONV52_9:%.*]] = sext i16 [[TMP29]] to i32
; CHECK-NEXT:    [[CONV49_10:%.*]] = sext i16 [[TMP30]] to i32
; CHECK-NEXT:    [[CONV52_10:%.*]] = sext i16 [[TMP31]] to i32
; CHECK-NEXT:    [[CONV49_11:%.*]] = sext i16 [[TMP32]] to i32
; CHECK-NEXT:    [[CONV52_11:%.*]] = sext i16 [[TMP33]] to i32
; CHECK-NEXT:    [[CONV49_12:%.*]] = sext i16 [[TMP34]] to i32
; CHECK-NEXT:    [[CONV52_12:%.*]] = sext i16 [[TMP35]] to i32
; CHECK-NEXT:    [[CONV49_13:%.*]] = sext i16 [[TMP36]] to i32
; CHECK-NEXT:    [[CONV52_13:%.*]] = sext i16 [[TMP37]] to i32
; CHECK-NEXT:    [[CONV49_14:%.*]] = sext i16 [[TMP38]] to i32
; CHECK-NEXT:    [[CONV52_14:%.*]] = sext i16 [[TMP39]] to i32
; CHECK-NEXT:    [[CONV49_15:%.*]] = sext i16 [[TMP40]] to i32
; CHECK-NEXT:    [[CONV52_15:%.*]] = sext i16 [[TMP41]] to i32
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[CONV52]], [[CONV49]]
; CHECK-NEXT:    [[MUL_1:%.*]] = mul nsw i32 [[CONV52_1]], [[CONV49_1]]
; CHECK-NEXT:    [[MUL_2:%.*]] = mul nsw i32 [[CONV52_2]], [[CONV49_2]]
; CHECK-NEXT:    [[MUL_3:%.*]] = mul nsw i32 [[CONV52_3]], [[CONV49_3]]
; CHECK-NEXT:    [[MUL_4:%.*]] = mul nsw i32 [[CONV52_4]], [[CONV49_4]]
; CHECK-NEXT:    [[MUL_5:%.*]] = mul nsw i32 [[CONV52_5]], [[CONV49_5]]
; CHECK-NEXT:    [[MUL_6:%.*]] = mul nsw i32 [[CONV52_6]], [[CONV49_6]]
; CHECK-NEXT:    [[MUL_7:%.*]] = mul nsw i32 [[CONV52_7]], [[CONV49_7]]
; CHECK-NEXT:    [[MUL_8:%.*]] = mul nsw i32 [[CONV52_8]], [[CONV49_8]]
; CHECK-NEXT:    [[MUL_9:%.*]] = mul nsw i32 [[CONV52_9]], [[CONV49_9]]
; CHECK-NEXT:    [[MUL_10:%.*]] = mul nsw i32 [[CONV52_10]], [[CONV49_10]]
; CHECK-NEXT:    [[MUL_11:%.*]] = mul nsw i32 [[CONV52_11]], [[CONV49_11]]
; CHECK-NEXT:    [[MUL_12:%.*]] = mul nsw i32 [[CONV52_12]], [[CONV49_12]]
; CHECK-NEXT:    [[MUL_13:%.*]] = mul nsw i32 [[CONV52_13]], [[CONV49_13]]
; CHECK-NEXT:    [[MUL_14:%.*]] = mul nsw i32 [[CONV52_14]], [[CONV49_14]]
; CHECK-NEXT:    [[MUL_15:%.*]] = mul nsw i32 [[CONV52_15]], [[CONV49_15]]
; CHECK-NEXT:    [[CONV53:%.*]] = sext i32 [[MUL]] to i64
; CHECK-NEXT:    [[CONV53_1:%.*]] = sext i32 [[MUL_1]] to i64
; CHECK-NEXT:    [[CONV53_2:%.*]] = sext i32 [[MUL_2]] to i64
; CHECK-NEXT:    [[CONV53_3:%.*]] = sext i32 [[MUL_3]] to i64
; CHECK-NEXT:    [[CONV53_4:%.*]] = sext i32 [[MUL_4]] to i64
; CHECK-NEXT:    [[CONV53_5:%.*]] = sext i32 [[MUL_5]] to i64
; CHECK-NEXT:    [[CONV53_6:%.*]] = sext i32 [[MUL_6]] to i64
; CHECK-NEXT:    [[CONV53_7:%.*]] = sext i32 [[MUL_7]] to i64
; CHECK-NEXT:    [[CONV53_8:%.*]] = sext i32 [[MUL_8]] to i64
; CHECK-NEXT:    [[CONV53_9:%.*]] = sext i32 [[MUL_9]] to i64
; CHECK-NEXT:    [[CONV53_10:%.*]] = sext i32 [[MUL_10]] to i64
; CHECK-NEXT:    [[CONV53_11:%.*]] = sext i32 [[MUL_11]] to i64
; CHECK-NEXT:    [[CONV53_12:%.*]] = sext i32 [[MUL_12]] to i64
; CHECK-NEXT:    [[CONV53_13:%.*]] = sext i32 [[MUL_13]] to i64
; CHECK-NEXT:    [[CONV53_14:%.*]] = sext i32 [[MUL_14]] to i64
; CHECK-NEXT:    [[CONV53_15:%.*]] = sext i32 [[MUL_15]] to i64
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i64 [[ACC_0143]], [[CONV53]]
; CHECK-NEXT:    [[ADD_1:%.*]] = add nsw i64 [[ADD]], [[CONV53_1]]
; CHECK-NEXT:    [[ADD_2:%.*]] = add nsw i64 [[ADD_1]], [[CONV53_2]]
; CHECK-NEXT:    [[ADD_3:%.*]] = add nsw i64 [[ADD_2]], [[CONV53_3]]
; CHECK-NEXT:    [[ADD_4:%.*]] = add nsw i64 [[ADD_3]], [[CONV53_4]]
; CHECK-NEXT:    [[ADD_5:%.*]] = add nsw i64 [[ADD_4]], [[CONV53_5]]
; CHECK-NEXT:    [[ADD_6:%.*]] = add nsw i64 [[ADD_5]], [[CONV53_6]]
; CHECK-NEXT:    [[ADD_7:%.*]] = add nsw i64 [[ADD_6]], [[CONV53_7]]
; CHECK-NEXT:    [[ADD_8:%.*]] = add nsw i64 [[ADD_7]], [[CONV53_8]]
; CHECK-NEXT:    [[ADD_9:%.*]] = add nsw i64 [[ADD_8]], [[CONV53_9]]
; CHECK-NEXT:    [[ADD_10:%.*]] = add nsw i64 [[ADD_9]], [[CONV53_10]]
; CHECK-NEXT:    [[ADD_11:%.*]] = add nsw i64 [[ADD_10]], [[CONV53_11]]
; CHECK-NEXT:    [[ADD_12:%.*]] = add nsw i64 [[ADD_11]], [[CONV53_12]]
; CHECK-NEXT:    [[ADD_13:%.*]] = add nsw i64 [[ADD_12]], [[CONV53_13]]
; CHECK-NEXT:    [[ADD_14:%.*]] = add nsw i64 [[ADD_13]], [[CONV53_14]]
; CHECK-NEXT:    [[ADD_15]] = add nsw i64 [[ADD_14]], [[CONV53_15]]
; CHECK-NEXT:    [[INC55_15]] = add nsw i32 [[N_0144]], 16
; CHECK-NEXT:    [[COEFF_POS_0_15]] = add i16 [[COEFF_POS_0145]], -16
; CHECK-NEXT:    [[EXITCOND_NOT_15:%.*]] = icmp slt i32 [[INC55_15]], [[SUB45]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_15]], label [[FOR_BODY46_15]], label [[FOR_COND58_PREHEADER]]
; CHECK:       for.cond227.preheader.loopexit:
; CHECK-NEXT:    [[TMP42:%.*]] = sub i16 [[COEFF_POS_0_LCSSA]], [[DOTPRE3]]
; CHECK-NEXT:    [[TMP43:%.*]] = add i16 [[TMP42]], [[TMP9]]
; CHECK-NEXT:    br label [[FOR_COND227_PREHEADER]]
; CHECK:       for.cond227.preheader:
; CHECK-NEXT:    [[ACC_1_LCSSA1:%.*]] = phi i64 [ [[ACC_0_LCSSA]], [[FOR_COND58_PREHEADER]] ], [ [[ADD_CLONE:%.*]], [[FOR_COND227_PREHEADER_LOOPEXIT:%.*]] ]
; CHECK-NEXT:    [[COEFF_POS_1_LCSSA:%.*]] = phi i16 [ [[COEFF_POS_0_LCSSA]], [[FOR_COND58_PREHEADER]] ], [ [[TMP43]], [[FOR_COND227_PREHEADER_LOOPEXIT]] ]
; CHECK-NEXT:    [[CMP231659:%.*]] = icmp sgt i16 [[TMP5]], 15
; CHECK-NEXT:    br i1 [[CMP231659]], label [[FOR_BODY233_PREHEADER:%.*]], label [[FOR_COND398_PREHEADER:%.*]]
; CHECK:       for.body233.preheader:
; CHECK-NEXT:    [[M47:%.*]] = and i32 [[CONV39]], 32752
; CHECK-NEXT:    [[ARRAYIDX71_7_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 14
; CHECK-NEXT:    [[DOTPRE:%.*]] = load i16, ptr [[ARRAYIDX71_7_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[IDXPROM67_PHI_TRANS_INSERT:%.*]] = sext i16 [[COEFF_POS_1_LCSSA]] to i32
; CHECK-NEXT:    [[ARRAYIDX68_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds i16, ptr [[TMP0]], i32 [[IDXPROM67_PHI_TRANS_INSERT]]
; CHECK-NEXT:    [[ARRAYIDX68_8_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -16
; CHECK-NEXT:    [[DOTPRE5:%.*]] = load i16, ptr [[ARRAYIDX68_8_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX71_8_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 16
; CHECK-NEXT:    [[DOTPRE6:%.*]] = load i16, ptr [[ARRAYIDX71_8_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX68_9_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -18
; CHECK-NEXT:    [[DOTPRE9:%.*]] = load i16, ptr [[ARRAYIDX68_9_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX71_9_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 18
; CHECK-NEXT:    [[DOTPRE10:%.*]] = load i16, ptr [[ARRAYIDX71_9_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX68_10_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -20
; CHECK-NEXT:    [[DOTPRE13:%.*]] = load i16, ptr [[ARRAYIDX68_10_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX71_10_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 20
; CHECK-NEXT:    [[DOTPRE14:%.*]] = load i16, ptr [[ARRAYIDX71_10_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX68_11_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -22
; CHECK-NEXT:    [[DOTPRE17:%.*]] = load i16, ptr [[ARRAYIDX68_11_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX71_11_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 22
; CHECK-NEXT:    [[DOTPRE18:%.*]] = load i16, ptr [[ARRAYIDX71_11_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX68_12_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -24
; CHECK-NEXT:    [[DOTPRE21:%.*]] = load i16, ptr [[ARRAYIDX68_12_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX71_12_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 24
; CHECK-NEXT:    [[DOTPRE22:%.*]] = load i16, ptr [[ARRAYIDX71_12_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX68_13_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -26
; CHECK-NEXT:    [[DOTPRE25:%.*]] = load i16, ptr [[ARRAYIDX68_13_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX71_13_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 26
; CHECK-NEXT:    [[DOTPRE26:%.*]] = load i16, ptr [[ARRAYIDX71_13_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX68_14_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -28
; CHECK-NEXT:    [[DOTPRE29:%.*]] = load i16, ptr [[ARRAYIDX68_14_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX71_14_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 28
; CHECK-NEXT:    [[DOTPRE30:%.*]] = load i16, ptr [[ARRAYIDX71_14_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX68_15_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -30
; CHECK-NEXT:    [[DOTPRE33:%.*]] = load i16, ptr [[ARRAYIDX68_15_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[ARRAYIDX71_15_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 30
; CHECK-NEXT:    [[DOTPRE34:%.*]] = load i16, ptr [[ARRAYIDX71_15_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    [[DOTPRE35:%.*]] = load i16, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], align 2
; CHECK-NEXT:    br label [[FOR_BODY64_15:%.*]]
; CHECK:       for.body46.clone:
; CHECK-NEXT:    [[COEFF_POS_0145_CLONE:%.*]] = phi i16 [ [[COEFF_POS_0_CLONE:%.*]], [[FOR_BODY46_CLONE]] ], [ [[COEFF_POS_0_LCSSA]], [[FOR_COND58_PREHEADER]] ]
; CHECK-NEXT:    [[N_0144_CLONE:%.*]] = phi i32 [ [[INC55_CLONE:%.*]], [[FOR_BODY46_CLONE]] ], [ [[N_0_LCSSA]], [[FOR_COND58_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_0143_CLONE:%.*]] = phi i64 [ [[ADD_CLONE]], [[FOR_BODY46_CLONE]] ], [ [[ACC_0_LCSSA]], [[FOR_COND58_PREHEADER]] ]
; CHECK-NEXT:    [[IDXPROM47_CLONE:%.*]] = sext i16 [[COEFF_POS_0145_CLONE]] to i32
; CHECK-NEXT:    [[ARRAYIDX48_CLONE:%.*]] = getelementptr inbounds i16, ptr [[TMP0]], i32 [[IDXPROM47_CLONE]]
; CHECK-NEXT:    [[TMP44:%.*]] = load i16, ptr [[ARRAYIDX48_CLONE]], align 2
; CHECK-NEXT:    [[CONV49_CLONE:%.*]] = sext i16 [[TMP44]] to i32
; CHECK-NEXT:    [[ARRAYIDX51_CLONE:%.*]] = getelementptr inbounds i16, ptr [[DELAY_PTR_HOISTED]], i32 [[N_0144_CLONE]]
; CHECK-NEXT:    [[TMP45:%.*]] = load i16, ptr [[ARRAYIDX51_CLONE]], align 2
; CHECK-NEXT:    [[CONV52_CLONE:%.*]] = sext i16 [[TMP45]] to i32
; CHECK-NEXT:    [[MUL_CLONE:%.*]] = mul nsw i32 [[CONV52_CLONE]], [[CONV49_CLONE]]
; CHECK-NEXT:    [[CONV53_CLONE:%.*]] = sext i32 [[MUL_CLONE]] to i64
; CHECK-NEXT:    [[ADD_CLONE]] = add nsw i64 [[ACC_0143_CLONE]], [[CONV53_CLONE]]
; CHECK-NEXT:    [[INC55_CLONE]] = add nsw i32 [[N_0144_CLONE]], 1
; CHECK-NEXT:    [[COEFF_POS_0_CLONE]] = add i16 [[COEFF_POS_0145_CLONE]], -1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC55_CLONE]], [[CONV42]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[FOR_COND227_PREHEADER_LOOPEXIT]], label [[FOR_BODY46_CLONE]]
; CHECK:       for.cond398.preheader:
; CHECK-NEXT:    [[TMP46:%.*]] = phi i64 [ [[ACC_1_LCSSA1]], [[FOR_COND227_PREHEADER]] ], [ [[ADD75_15:%.*]], [[FOR_BODY64_15]] ]
; CHECK-NEXT:    [[TMP47:%.*]] = phi i16 [ [[COEFF_POS_1_LCSSA]], [[FOR_COND227_PREHEADER]] ], [ [[DEC66_15:%.*]], [[FOR_BODY64_15]] ]
; CHECK-NEXT:    [[TMP48:%.*]] = phi i32 [ 0, [[FOR_COND227_PREHEADER]] ], [ [[M47]], [[FOR_BODY64_15]] ]
; CHECK-NEXT:    [[CMP401666:%.*]] = icmp slt i32 [[TMP48]], [[CONV39]]
; CHECK-NEXT:    br i1 [[CMP401666]], label [[FOR_BODY64_CLONE:%.*]], label [[FOR_COND_CLEANUP63]]
; CHECK:       for.body64.15:
; CHECK-NEXT:    [[ARRAYIDX68_1:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -2
; CHECK-NEXT:    [[ARRAYIDX71_1:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 2
; CHECK-NEXT:    [[ARRAYIDX68_2:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -4
; CHECK-NEXT:    [[ARRAYIDX71_2:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 4
; CHECK-NEXT:    [[ARRAYIDX68_3:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -6
; CHECK-NEXT:    [[ARRAYIDX71_3:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 6
; CHECK-NEXT:    [[ARRAYIDX68_4:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -8
; CHECK-NEXT:    [[ARRAYIDX71_4:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 8
; CHECK-NEXT:    [[ARRAYIDX68_5:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -10
; CHECK-NEXT:    [[ARRAYIDX71_5:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 10
; CHECK-NEXT:    [[ARRAYIDX68_6:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -12
; CHECK-NEXT:    [[ARRAYIDX71_6:%.*]] = getelementptr inbounds nuw i8, ptr [[DELAY_PTR_HOISTED]], i32 12
; CHECK-NEXT:    [[ARRAYIDX68_7:%.*]] = getelementptr inbounds i8, ptr [[ARRAYIDX68_PHI_TRANS_INSERT]], i32 -14
; CHECK-NEXT:    [[TMP49:%.*]] = load i16, ptr [[DELAY_PTR_HOISTED]], align 2
; CHECK-NEXT:    [[TMP50:%.*]] = load i16, ptr [[ARRAYIDX68_1]], align 2
; CHECK-NEXT:    [[TMP51:%.*]] = load i16, ptr [[ARRAYIDX71_1]], align 2
; CHECK-NEXT:    [[TMP52:%.*]] = load i16, ptr [[ARRAYIDX68_2]], align 2
; CHECK-NEXT:    [[TMP53:%.*]] = load i16, ptr [[ARRAYIDX71_2]], align 2
; CHECK-NEXT:    [[TMP54:%.*]] = load i16, ptr [[ARRAYIDX68_3]], align 2
; CHECK-NEXT:    [[TMP55:%.*]] = load i16, ptr [[ARRAYIDX71_3]], align 2
; CHECK-NEXT:    [[TMP56:%.*]] = load i16, ptr [[ARRAYIDX68_4]], align 2
; CHECK-NEXT:    [[TMP57:%.*]] = load i16, ptr [[ARRAYIDX71_4]], align 2
; CHECK-NEXT:    [[TMP58:%.*]] = load i16, ptr [[ARRAYIDX68_5]], align 2
; CHECK-NEXT:    [[TMP59:%.*]] = load i16, ptr [[ARRAYIDX71_5]], align 2
; CHECK-NEXT:    [[TMP60:%.*]] = load i16, ptr [[ARRAYIDX68_6]], align 2
; CHECK-NEXT:    [[TMP61:%.*]] = load i16, ptr [[ARRAYIDX71_6]], align 2
; CHECK-NEXT:    [[TMP62:%.*]] = load i16, ptr [[ARRAYIDX68_7]], align 2
; CHECK-NEXT:    [[CONV69:%.*]] = sext i16 [[DOTPRE35]] to i32
; CHECK-NEXT:    [[CONV72:%.*]] = sext i16 [[TMP49]] to i32
; CHECK-NEXT:    [[CONV69_1:%.*]] = sext i16 [[TMP50]] to i32
; CHECK-NEXT:    [[CONV72_1:%.*]] = sext i16 [[TMP51]] to i32
; CHECK-NEXT:    [[CONV69_2:%.*]] = sext i16 [[TMP52]] to i32
; CHECK-NEXT:    [[CONV72_2:%.*]] = sext i16 [[TMP53]] to i32
; CHECK-NEXT:    [[CONV69_3:%.*]] = sext i16 [[TMP54]] to i32
; CHECK-NEXT:    [[CONV72_3:%.*]] = sext i16 [[TMP55]] to i32
; CHECK-NEXT:    [[CONV69_4:%.*]] = sext i16 [[TMP56]] to i32
; CHECK-NEXT:    [[CONV72_4:%.*]] = sext i16 [[TMP57]] to i32
; CHECK-NEXT:    [[CONV69_5:%.*]] = sext i16 [[TMP58]] to i32
; CHECK-NEXT:    [[CONV72_5:%.*]] = sext i16 [[TMP59]] to i32
; CHECK-NEXT:    [[CONV69_6:%.*]] = sext i16 [[TMP60]] to i32
; CHECK-NEXT:    [[CONV72_6:%.*]] = sext i16 [[TMP61]] to i32
; CHECK-NEXT:    [[CONV69_7:%.*]] = sext i16 [[TMP62]] to i32
; CHECK-NEXT:    [[CONV72_7:%.*]] = sext i16 [[DOTPRE]] to i32
; CHECK-NEXT:    [[CONV69_8:%.*]] = sext i16 [[DOTPRE5]] to i32
; CHECK-NEXT:    [[CONV72_8:%.*]] = sext i16 [[DOTPRE6]] to i32
; CHECK-NEXT:    [[CONV69_9:%.*]] = sext i16 [[DOTPRE9]] to i32
; CHECK-NEXT:    [[CONV72_9:%.*]] = sext i16 [[DOTPRE10]] to i32
; CHECK-NEXT:    [[CONV69_10:%.*]] = sext i16 [[DOTPRE13]] to i32
; CHECK-NEXT:    [[CONV72_10:%.*]] = sext i16 [[DOTPRE14]] to i32
; CHECK-NEXT:    [[CONV69_11:%.*]] = sext i16 [[DOTPRE17]] to i32
; CHECK-NEXT:    [[CONV72_11:%.*]] = sext i16 [[DOTPRE18]] to i32
; CHECK-NEXT:    [[CONV69_12:%.*]] = sext i16 [[DOTPRE21]] to i32
; CHECK-NEXT:    [[CONV72_12:%.*]] = sext i16 [[DOTPRE22]] to i32
; CHECK-NEXT:    [[CONV69_13:%.*]] = sext i16 [[DOTPRE25]] to i32
; CHECK-NEXT:    [[CONV72_13:%.*]] = sext i16 [[DOTPRE26]] to i32
; CHECK-NEXT:    [[CONV69_14:%.*]] = sext i16 [[DOTPRE29]] to i32
; CHECK-NEXT:    [[CONV72_14:%.*]] = sext i16 [[DOTPRE30]] to i32
; CHECK-NEXT:    [[CONV69_15:%.*]] = sext i16 [[DOTPRE33]] to i32
; CHECK-NEXT:    [[CONV72_15:%.*]] = sext i16 [[DOTPRE34]] to i32
; CHECK-NEXT:    [[MUL73:%.*]] = mul nsw i32 [[CONV72]], [[CONV69]]
; CHECK-NEXT:    [[MUL73_1:%.*]] = mul nsw i32 [[CONV72_1]], [[CONV69_1]]
; CHECK-NEXT:    [[MUL73_2:%.*]] = mul nsw i32 [[CONV72_2]], [[CONV69_2]]
; CHECK-NEXT:    [[MUL73_3:%.*]] = mul nsw i32 [[CONV72_3]], [[CONV69_3]]
; CHECK-NEXT:    [[MUL73_4:%.*]] = mul nsw i32 [[CONV72_4]], [[CONV69_4]]
; CHECK-NEXT:    [[MUL73_5:%.*]] = mul nsw i32 [[CONV72_5]], [[CONV69_5]]
; CHECK-NEXT:    [[MUL73_6:%.*]] = mul nsw i32 [[CONV72_6]], [[CONV69_6]]
; CHECK-NEXT:    [[MUL73_7:%.*]] = mul nsw i32 [[CONV72_7]], [[CONV69_7]]
; CHECK-NEXT:    [[MUL73_8:%.*]] = mul nsw i32 [[CONV72_8]], [[CONV69_8]]
; CHECK-NEXT:    [[MUL73_9:%.*]] = mul nsw i32 [[CONV72_9]], [[CONV69_9]]
; CHECK-NEXT:    [[MUL73_10:%.*]] = mul nsw i32 [[CONV72_10]], [[CONV69_10]]
; CHECK-NEXT:    [[MUL73_11:%.*]] = mul nsw i32 [[CONV72_11]], [[CONV69_11]]
; CHECK-NEXT:    [[MUL73_12:%.*]] = mul nsw i32 [[CONV72_12]], [[CONV69_12]]
; CHECK-NEXT:    [[MUL73_13:%.*]] = mul nsw i32 [[CONV72_13]], [[CONV69_13]]
; CHECK-NEXT:    [[MUL73_14:%.*]] = mul nsw i32 [[CONV72_14]], [[CONV69_14]]
; CHECK-NEXT:    [[MUL73_15:%.*]] = mul nsw i32 [[CONV72_15]], [[CONV69_15]]
; CHECK-NEXT:    [[CONV74:%.*]] = sext i32 [[MUL73]] to i64
; CHECK-NEXT:    [[CONV74_1:%.*]] = sext i32 [[MUL73_1]] to i64
; CHECK-NEXT:    [[CONV74_2:%.*]] = sext i32 [[MUL73_2]] to i64
; CHECK-NEXT:    [[CONV74_3:%.*]] = sext i32 [[MUL73_3]] to i64
; CHECK-NEXT:    [[CONV74_4:%.*]] = sext i32 [[MUL73_4]] to i64
; CHECK-NEXT:    [[CONV74_5:%.*]] = sext i32 [[MUL73_5]] to i64
; CHECK-NEXT:    [[CONV74_6:%.*]] = sext i32 [[MUL73_6]] to i64
; CHECK-NEXT:    [[CONV74_7:%.*]] = sext i32 [[MUL73_7]] to i64
; CHECK-NEXT:    [[CONV74_8:%.*]] = sext i32 [[MUL73_8]] to i64
; CHECK-NEXT:    [[CONV74_9:%.*]] = sext i32 [[MUL73_9]] to i64
; CHECK-NEXT:    [[CONV74_10:%.*]] = sext i32 [[MUL73_10]] to i64
; CHECK-NEXT:    [[CONV74_11:%.*]] = sext i32 [[MUL73_11]] to i64
; CHECK-NEXT:    [[CONV74_12:%.*]] = sext i32 [[MUL73_12]] to i64
; CHECK-NEXT:    [[CONV74_13:%.*]] = sext i32 [[MUL73_13]] to i64
; CHECK-NEXT:    [[CONV74_14:%.*]] = sext i32 [[MUL73_14]] to i64
; CHECK-NEXT:    [[CONV74_15:%.*]] = sext i32 [[MUL73_15]] to i64
; CHECK-NEXT:    [[ADD75:%.*]] = add nsw i64 [[ACC_1_LCSSA1]], [[CONV74]]
; CHECK-NEXT:    [[ADD75_1:%.*]] = add nsw i64 [[ADD75]], [[CONV74_1]]
; CHECK-NEXT:    [[ADD75_2:%.*]] = add nsw i64 [[ADD75_1]], [[CONV74_2]]
; CHECK-NEXT:    [[ADD75_3:%.*]] = add nsw i64 [[ADD75_2]], [[CONV74_3]]
; CHECK-NEXT:    [[ADD75_4:%.*]] = add nsw i64 [[ADD75_3]], [[CONV74_4]]
; CHECK-NEXT:    [[ADD75_5:%.*]] = add nsw i64 [[ADD75_4]], [[CONV74_5]]
; CHECK-NEXT:    [[ADD75_6:%.*]] = add nsw i64 [[ADD75_5]], [[CONV74_6]]
; CHECK-NEXT:    [[ADD75_7:%.*]] = add nsw i64 [[ADD75_6]], [[CONV74_7]]
; CHECK-NEXT:    [[ADD75_8:%.*]] = add nsw i64 [[ADD75_7]], [[CONV74_8]]
; CHECK-NEXT:    [[ADD75_9:%.*]] = add nsw i64 [[ADD75_8]], [[CONV74_9]]
; CHECK-NEXT:    [[ADD75_10:%.*]] = add nsw i64 [[ADD75_9]], [[CONV74_10]]
; CHECK-NEXT:    [[ADD75_11:%.*]] = add nsw i64 [[ADD75_10]], [[CONV74_11]]
; CHECK-NEXT:    [[ADD75_12:%.*]] = add nsw i64 [[ADD75_11]], [[CONV74_12]]
; CHECK-NEXT:    [[ADD75_13:%.*]] = add nsw i64 [[ADD75_12]], [[CONV74_13]]
; CHECK-NEXT:    [[ADD75_14:%.*]] = add nsw i64 [[ADD75_13]], [[CONV74_14]]
; CHECK-NEXT:    [[DEC66_15]] = add i16 [[COEFF_POS_1_LCSSA]], -16
; CHECK-NEXT:    [[ADD75_15]] = add nsw i64 [[ADD75_14]], [[CONV74_15]]
; CHECK-NEXT:    br i1 false, label [[FOR_BODY64_15_FOR_BODY64_15_CRIT_EDGE:%.*]], label [[FOR_COND398_PREHEADER]]
; CHECK:       for.body64.15.for.body64.15_crit_edge:
; CHECK-NEXT:    br label [[FOR_BODY64_15]]
; CHECK:       for.body64.clone:
; CHECK-NEXT:    [[N57_0151_CLONE:%.*]] = phi i32 [ [[INC77_CLONE:%.*]], [[FOR_BODY64_CLONE]] ], [ [[TMP48]], [[FOR_COND398_PREHEADER]] ]
; CHECK-NEXT:    [[COEFF_POS_1150_CLONE:%.*]] = phi i16 [ [[DEC66_CLONE:%.*]], [[FOR_BODY64_CLONE]] ], [ [[TMP47]], [[FOR_COND398_PREHEADER]] ]
; CHECK-NEXT:    [[ACC_1149_CLONE:%.*]] = phi i64 [ [[ADD75_CLONE:%.*]], [[FOR_BODY64_CLONE]] ], [ [[TMP46]], [[FOR_COND398_PREHEADER]] ]
; CHECK-NEXT:    [[DEC66_CLONE]] = add i16 [[COEFF_POS_1150_CLONE]], -1
; CHECK-NEXT:    [[IDXPROM67_CLONE:%.*]] = sext i16 [[COEFF_POS_1150_CLONE]] to i32
; CHECK-NEXT:    [[ARRAYIDX68_CLONE:%.*]] = getelementptr inbounds i16, ptr [[TMP0]], i32 [[IDXPROM67_CLONE]]
; CHECK-NEXT:    [[TMP63:%.*]] = load i16, ptr [[ARRAYIDX68_CLONE]], align 2
; CHECK-NEXT:    [[CONV69_CLONE:%.*]] = sext i16 [[TMP63]] to i32
; CHECK-NEXT:    [[ARRAYIDX71_CLONE:%.*]] = getelementptr inbounds nuw i16, ptr [[DELAY_PTR_HOISTED]], i32 [[N57_0151_CLONE]]
; CHECK-NEXT:    [[TMP64:%.*]] = load i16, ptr [[ARRAYIDX71_CLONE]], align 2
; CHECK-NEXT:    [[CONV72_CLONE:%.*]] = sext i16 [[TMP64]] to i32
; CHECK-NEXT:    [[MUL73_CLONE:%.*]] = mul nsw i32 [[CONV72_CLONE]], [[CONV69_CLONE]]
; CHECK-NEXT:    [[CONV74_CLONE:%.*]] = sext i32 [[MUL73_CLONE]] to i64
; CHECK-NEXT:    [[ADD75_CLONE]] = add nsw i64 [[ACC_1149_CLONE]], [[CONV74_CLONE]]
; CHECK-NEXT:    [[INC77_CLONE]] = add nuw nsw i32 [[N57_0151_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND159_NOT_CLONE:%.*]] = icmp eq i32 [[INC77_CLONE]], [[CONV39]]
; CHECK-NEXT:    br i1 [[EXITCOND159_NOT_CLONE]], label [[FOR_COND_CLEANUP63]], label [[FOR_BODY64_CLONE]]
; CHECK:       for.cond.cleanup63:
; CHECK-NEXT:    [[ACC_3_LCSSA:%.*]] = phi i64 [ [[TMP46]], [[FOR_COND398_PREHEADER]] ], [ [[ADD75_CLONE]], [[FOR_BODY64_CLONE]] ]
; CHECK-NEXT:    [[SHR90:%.*]] = ashr i64 [[ACC_3_LCSSA]], [[SH_PROM89]]
; CHECK-NEXT:    [[SHL83:%.*]] = shl i64 [[ACC_3_LCSSA]], [[SH_PROM82]]
; CHECK-NEXT:    [[SHR90_SINK:%.*]] = select i1 [[CMP79]], i64 [[SHL83]], i64 [[SHR90]]
; CHECK-NEXT:    [[CONV91:%.*]] = trunc i64 [[SHR90_SINK]] to i16
; CHECK-NEXT:    [[TMP65:%.*]] = getelementptr inbounds nuw i16, ptr [[OUTPUT]], i32 [[I_0156]]
; CHECK-NEXT:    store i16 [[CONV91]], ptr [[TMP65]], align 2
; CHECK-NEXT:    [[INC96]] = add nuw nsw i32 [[I_0156]], 1
; CHECK-NEXT:    [[EXITCOND160_NOT:%.*]] = icmp eq i32 [[INC96]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND160_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_COND14_PREHEADER]]
;
entry:
  %shift = getelementptr inbounds nuw i8, ptr %fir, i32 16
  %0 = load i16, ptr %shift, align 4
  %conv = sext i16 %0 to i32
  %sub = add nsw i32 %conv, -15
  %rounding_val = getelementptr inbounds nuw i8, ptr %fir, i32 24
  %1 = load i32, ptr %rounding_val, align 4
  %conv1 = sext i32 %1 to i64
  %cmp = icmp sgt i16 %0, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %sh_prom = zext nneg i32 %conv to i64
  %shr = ashr i64 %conv1, %sh_prom
  br label %if.end

if.else:                                          ; preds = %entry
  %sub9 = sub nsw i32 0, %conv
  %sh_prom10 = zext nneg i32 %sub9 to i64
  %shl = shl i64 %conv1, %sh_prom10
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %rounding.0.in = phi i64 [ %shr, %if.then ], [ %shl, %if.else ]
  %rounding.0 = and i64 %rounding.0.in, 1099511627775
  %cmp12153 = icmp sgt i32 %len, 0
  br i1 %cmp12153, label %for.cond14.preheader.lr.ph, label %for.cond.cleanup

for.cond14.preheader.lr.ph:                       ; preds = %if.end
  %decim = getelementptr inbounds nuw i8, ptr %fir, i32 12
  %d_pos = getelementptr inbounds nuw i8, ptr %fir, i32 14
  %pos = getelementptr inbounds nuw i8, ptr %fir, i32 10
  %coeffs_len = getelementptr inbounds nuw i8, ptr %fir, i32 8
  %delay = getelementptr inbounds nuw i8, ptr %fir, i32 4
  %cmp79 = icmp sgt i16 %0, 15
  %sub88 = sub nsw i32 15, %conv
  %sh_prom89 = zext nneg i32 %sub88 to i64
  %sh_prom82 = zext nneg i32 %sub to i64
  br label %for.cond14.preheader

for.cond14.preheader:                             ; preds = %for.cond.cleanup63, %for.cond14.preheader.lr.ph
  %i.0156 = phi i32 [ 0, %for.cond14.preheader.lr.ph ], [ %inc96, %for.cond.cleanup63 ]
  %input_pos.0154 = phi i32 [ 0, %for.cond14.preheader.lr.ph ], [ %input_pos.1.lcssa, %for.cond.cleanup63 ]
  %2 = load i16, ptr %decim, align 4
  %3 = load i16, ptr %d_pos, align 2
  %cmp18138 = icmp sgt i16 %2, %3
  br i1 %cmp18138, label %for.body21.lr.ph, label %for.cond.cleanup20

for.body21.lr.ph:                                 ; preds = %for.cond14.preheader
  %4 = load ptr, ptr %delay, align 4
  br label %for.body21

for.cond.cleanup:                                 ; preds = %for.cond.cleanup63, %if.end
  %result.0.lcssa = phi i32 [ 0, %if.end ], [ %len, %for.cond.cleanup63 ]
  ret i32 %result.0.lcssa

for.cond.cleanup20:                               ; preds = %if.end28, %for.cond14.preheader
  %input_pos.1.lcssa = phi i32 [ %input_pos.0154, %for.cond14.preheader ], [ %inc, %if.end28 ]
  store i16 0, ptr %d_pos, align 2
  %5 = load i16, ptr %coeffs_len, align 4
  %6 = load i16, ptr %pos, align 2
  %conv39 = sext i16 %6 to i32
  %conv42 = sext i16 %5 to i32
  %coeff_pos.0141 = add i16 %5, -1
  %cmp43142 = icmp slt i16 %6, %5
  br i1 %cmp43142, label %for.body46.lr.ph, label %for.cond58.preheader

for.body46.lr.ph:                                 ; preds = %for.cond.cleanup20
  %7 = load ptr, ptr %fir, align 4
  %8 = load ptr, ptr %delay, align 4
  br label %for.body46

for.body21:                                       ; preds = %if.end28, %for.body21.lr.ph
  %j.0140 = phi i32 [ 0, %for.body21.lr.ph ], [ %inc32, %if.end28 ]
  %input_pos.1139 = phi i32 [ %input_pos.0154, %for.body21.lr.ph ], [ %inc, %if.end28 ]
  %9 = load i16, ptr %pos, align 2
  %10 = load i16, ptr %coeffs_len, align 4
  %cmp24.not = icmp slt i16 %9, %10
  br i1 %cmp24.not, label %if.end28, label %if.then26

if.then26:                                        ; preds = %for.body21
  store i16 0, ptr %pos, align 2
  br label %if.end28

if.end28:                                         ; preds = %if.then26, %for.body21
  %11 = phi i16 [ 0, %if.then26 ], [ %9, %for.body21 ]
  %inc = add nsw i32 %input_pos.1139, 1
  %arrayidx = getelementptr inbounds i16, ptr %input, i32 %input_pos.1139
  %12 = load i16, ptr %arrayidx, align 2
  %inc30 = add nsw i16 %11, 1
  store i16 %inc30, ptr %pos, align 2
  %idxprom = sext i16 %11 to i32
  %arrayidx31 = getelementptr inbounds i16, ptr %4, i32 %idxprom
  store i16 %12, ptr %arrayidx31, align 2
  %inc32 = add nuw nsw i32 %j.0140, 1
  %13 = load i16, ptr %decim, align 4
  %conv15 = sext i16 %13 to i32
  %14 = load i16, ptr %d_pos, align 2
  %conv16 = sext i16 %14 to i32
  %sub17 = sub nsw i32 %conv15, %conv16
  %cmp18 = icmp slt i32 %inc32, %sub17
  br i1 %cmp18, label %for.body21, label %for.cond.cleanup20

for.cond58.preheader.loopexit:                    ; preds = %for.body46
  %15 = add i16 %6, -1
  br label %for.cond58.preheader

for.cond58.preheader:                             ; preds = %for.cond58.preheader.loopexit, %for.cond.cleanup20
  %acc.0.lcssa = phi i64 [ %rounding.0, %for.cond.cleanup20 ], [ %add, %for.cond58.preheader.loopexit ]
  %coeff_pos.0.lcssa = phi i16 [ %coeff_pos.0141, %for.cond.cleanup20 ], [ %15, %for.cond58.preheader.loopexit ]
  %cmp61148 = icmp sgt i16 %6, 0
  br i1 %cmp61148, label %for.body64.lr.ph, label %for.cond.cleanup63

for.body64.lr.ph:                                 ; preds = %for.cond58.preheader
  %16 = load ptr, ptr %fir, align 4
  %17 = load ptr, ptr %delay, align 4
  br label %for.body64

for.body46:                                       ; preds = %for.body46, %for.body46.lr.ph
  %coeff_pos.0145 = phi i16 [ %coeff_pos.0141, %for.body46.lr.ph ], [ %coeff_pos.0, %for.body46 ]
  %n.0144 = phi i32 [ %conv39, %for.body46.lr.ph ], [ %inc55, %for.body46 ]
  %acc.0143 = phi i64 [ %rounding.0, %for.body46.lr.ph ], [ %add, %for.body46 ]
  %idxprom47 = sext i16 %coeff_pos.0145 to i32
  %arrayidx48 = getelementptr inbounds i16, ptr %7, i32 %idxprom47
  %18 = load i16, ptr %arrayidx48, align 2
  %conv49 = sext i16 %18 to i32
  %arrayidx51 = getelementptr inbounds i16, ptr %8, i32 %n.0144
  %19 = load i16, ptr %arrayidx51, align 2
  %conv52 = sext i16 %19 to i32
  %mul = mul nsw i32 %conv52, %conv49
  %conv53 = sext i32 %mul to i64
  %add = add nsw i64 %acc.0143, %conv53
  %inc55 = add nsw i32 %n.0144, 1
  %coeff_pos.0 = add i16 %coeff_pos.0145, -1
  %exitcond.not = icmp eq i32 %inc55, %conv42
  br i1 %exitcond.not, label %for.cond58.preheader.loopexit, label %for.body46

for.cond.cleanup63:                               ; preds = %for.body64, %for.cond58.preheader
  %acc.1.lcssa = phi i64 [ %acc.0.lcssa, %for.cond58.preheader ], [ %add75, %for.body64 ]
  %shr90 = ashr i64 %acc.1.lcssa, %sh_prom89
  %shl83 = shl i64 %acc.1.lcssa, %sh_prom82
  %shr90.sink = select i1 %cmp79, i64 %shl83, i64 %shr90
  %conv91 = trunc i64 %shr90.sink to i16
  %20 = getelementptr inbounds nuw i16, ptr %output, i32 %i.0156
  store i16 %conv91, ptr %20, align 2
  %inc96 = add nuw nsw i32 %i.0156, 1
  %exitcond160.not = icmp eq i32 %inc96, %len
  br i1 %exitcond160.not, label %for.cond.cleanup, label %for.cond14.preheader

for.body64:                                       ; preds = %for.body64, %for.body64.lr.ph
  %n57.0151 = phi i32 [ 0, %for.body64.lr.ph ], [ %inc77, %for.body64 ]
  %coeff_pos.1150 = phi i16 [ %coeff_pos.0.lcssa, %for.body64.lr.ph ], [ %dec66, %for.body64 ]
  %acc.1149 = phi i64 [ %acc.0.lcssa, %for.body64.lr.ph ], [ %add75, %for.body64 ]
  %dec66 = add i16 %coeff_pos.1150, -1
  %idxprom67 = sext i16 %coeff_pos.1150 to i32
  %arrayidx68 = getelementptr inbounds i16, ptr %16, i32 %idxprom67
  %21 = load i16, ptr %arrayidx68, align 2
  %conv69 = sext i16 %21 to i32
  %arrayidx71 = getelementptr inbounds nuw i16, ptr %17, i32 %n57.0151
  %22 = load i16, ptr %arrayidx71, align 2
  %conv72 = sext i16 %22 to i32
  %mul73 = mul nsw i32 %conv72, %conv69
  %conv74 = sext i32 %mul73 to i64
  %add75 = add nsw i64 %acc.1149, %conv74
  %inc77 = add nuw nsw i32 %n57.0151, 1
  %exitcond159.not = icmp eq i32 %inc77, %conv39
  br i1 %exitcond159.not, label %for.cond.cleanup63, label %for.body64
}

