; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-int-loop-unroll-and-remainder -riscv-int-loop-unroll-and-remainder=true < %s | FileCheck %s

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite)
define dso_local noundef i32 @dsps_add_s16_ansi(ptr noundef readonly %input1, ptr noundef readonly %input2, ptr noundef writeonly %output, i32 noundef %len, i32 noundef %step1, i32 noundef %step2, i32 noundef %step_out, i32 noundef %shift) local_unnamed_addr {
; CHECK-LABEL: define dso_local noundef i32 @dsps_add_s16_ansi(
; CHECK-SAME: ptr noalias noundef readonly [[INPUT1:%.*]], ptr noalias noundef readonly [[INPUT2:%.*]], ptr noalias noundef writeonly [[OUTPUT:%.*]], i32 noundef [[LEN:%.*]], i32 noundef [[STEP1:%.*]], i32 noundef [[STEP2:%.*]], i32 noundef [[STEP_OUT:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr [[INPUT1]], null
; CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr [[INPUT2]], null
; CHECK-NEXT:    [[OR_COND:%.*]] = or i1 [[CMP]], [[CMP1]]
; CHECK-NEXT:    [[CMP4:%.*]] = icmp eq ptr [[OUTPUT]], null
; CHECK-NEXT:    [[OR_COND21:%.*]] = or i1 [[OR_COND]], [[CMP4]]
; CHECK-NEXT:    br i1 [[OR_COND21]], label [[RETURN:%.*]], label [[FOR_COND_PREHEADER:%.*]]
; CHECK:       for.cond.preheader:
; CHECK-NEXT:    [[AND:%.*]] = and i32 [[LEN]], -15
; CHECK-NEXT:    [[CMP722:%.*]] = icmp sgt i32 [[AND]], 0
; CHECK-NEXT:    br i1 [[CMP722]], label [[FOR_BODY_15:%.*]], label [[FOR_BODY_PREHEADER:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[I_0_LCSSA:%.*]] = phi i32 [ 0, [[FOR_COND_PREHEADER]] ], [ [[INC_15:%.*]], [[FOR_BODY_15]] ]
; CHECK-NEXT:    [[CMP226415:%.*]] = icmp slt i32 [[I_0_LCSSA]], [[LEN]]
; CHECK-NEXT:    br i1 [[CMP226415]], label [[FOR_BODY_CLONE:%.*]], label [[RETURN]]
; CHECK:       for.body.15:
; CHECK-NEXT:    [[I_023:%.*]] = phi i32 [ [[INC_15]], [[FOR_BODY_15]] ], [ 0, [[FOR_COND_PREHEADER]] ]
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[I_023]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[ARRAYIDX]], align 2
; CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP0]] to i32
; CHECK-NEXT:    [[MUL8:%.*]] = mul nsw i32 [[I_023]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[ARRAYIDX9]], align 2
; CHECK-NEXT:    [[CONV10:%.*]] = sext i16 [[TMP1]] to i32
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[CONV10]], [[CONV]]
; CHECK-NEXT:    [[SHR:%.*]] = ashr i32 [[ADD]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11:%.*]] = trunc i32 [[SHR]] to i16
; CHECK-NEXT:    [[MUL12:%.*]] = mul nsw i32 [[I_023]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12]]
; CHECK-NEXT:    store i16 [[CONV11]], ptr [[ARRAYIDX13]], align 2
; CHECK-NEXT:    [[INC:%.*]] = or disjoint i32 [[I_023]], 1
; CHECK-NEXT:    [[MUL_1:%.*]] = mul nsw i32 [[INC]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_1]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[ARRAYIDX_1]], align 2
; CHECK-NEXT:    [[CONV_1:%.*]] = sext i16 [[TMP2]] to i32
; CHECK-NEXT:    [[MUL8_1:%.*]] = mul nsw i32 [[INC]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_1:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_1]]
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[ARRAYIDX9_1]], align 2
; CHECK-NEXT:    [[CONV10_1:%.*]] = sext i16 [[TMP3]] to i32
; CHECK-NEXT:    [[ADD_1:%.*]] = add nsw i32 [[CONV10_1]], [[CONV_1]]
; CHECK-NEXT:    [[SHR_1:%.*]] = ashr i32 [[ADD_1]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_1:%.*]] = trunc i32 [[SHR_1]] to i16
; CHECK-NEXT:    [[MUL12_1:%.*]] = mul nsw i32 [[INC]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_1:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_1]]
; CHECK-NEXT:    store i16 [[CONV11_1]], ptr [[ARRAYIDX13_1]], align 2
; CHECK-NEXT:    [[INC_1:%.*]] = or disjoint i32 [[I_023]], 2
; CHECK-NEXT:    [[MUL_2:%.*]] = mul nsw i32 [[INC_1]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_2]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[ARRAYIDX_2]], align 2
; CHECK-NEXT:    [[CONV_2:%.*]] = sext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[MUL8_2:%.*]] = mul nsw i32 [[INC_1]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_2:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_2]]
; CHECK-NEXT:    [[TMP5:%.*]] = load i16, ptr [[ARRAYIDX9_2]], align 2
; CHECK-NEXT:    [[CONV10_2:%.*]] = sext i16 [[TMP5]] to i32
; CHECK-NEXT:    [[ADD_2:%.*]] = add nsw i32 [[CONV10_2]], [[CONV_2]]
; CHECK-NEXT:    [[SHR_2:%.*]] = ashr i32 [[ADD_2]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_2:%.*]] = trunc i32 [[SHR_2]] to i16
; CHECK-NEXT:    [[MUL12_2:%.*]] = mul nsw i32 [[INC_1]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_2:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_2]]
; CHECK-NEXT:    store i16 [[CONV11_2]], ptr [[ARRAYIDX13_2]], align 2
; CHECK-NEXT:    [[INC_2:%.*]] = or disjoint i32 [[I_023]], 3
; CHECK-NEXT:    [[MUL_3:%.*]] = mul nsw i32 [[INC_2]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_3]]
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[ARRAYIDX_3]], align 2
; CHECK-NEXT:    [[CONV_3:%.*]] = sext i16 [[TMP6]] to i32
; CHECK-NEXT:    [[MUL8_3:%.*]] = mul nsw i32 [[INC_2]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_3:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_3]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr [[ARRAYIDX9_3]], align 2
; CHECK-NEXT:    [[CONV10_3:%.*]] = sext i16 [[TMP7]] to i32
; CHECK-NEXT:    [[ADD_3:%.*]] = add nsw i32 [[CONV10_3]], [[CONV_3]]
; CHECK-NEXT:    [[SHR_3:%.*]] = ashr i32 [[ADD_3]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_3:%.*]] = trunc i32 [[SHR_3]] to i16
; CHECK-NEXT:    [[MUL12_3:%.*]] = mul nsw i32 [[INC_2]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_3:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_3]]
; CHECK-NEXT:    store i16 [[CONV11_3]], ptr [[ARRAYIDX13_3]], align 2
; CHECK-NEXT:    [[INC_3:%.*]] = or disjoint i32 [[I_023]], 4
; CHECK-NEXT:    [[MUL_4:%.*]] = mul nsw i32 [[INC_3]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_4]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[ARRAYIDX_4]], align 2
; CHECK-NEXT:    [[CONV_4:%.*]] = sext i16 [[TMP8]] to i32
; CHECK-NEXT:    [[MUL8_4:%.*]] = mul nsw i32 [[INC_3]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_4:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_4]]
; CHECK-NEXT:    [[TMP9:%.*]] = load i16, ptr [[ARRAYIDX9_4]], align 2
; CHECK-NEXT:    [[CONV10_4:%.*]] = sext i16 [[TMP9]] to i32
; CHECK-NEXT:    [[ADD_4:%.*]] = add nsw i32 [[CONV10_4]], [[CONV_4]]
; CHECK-NEXT:    [[SHR_4:%.*]] = ashr i32 [[ADD_4]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_4:%.*]] = trunc i32 [[SHR_4]] to i16
; CHECK-NEXT:    [[MUL12_4:%.*]] = mul nsw i32 [[INC_3]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_4:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_4]]
; CHECK-NEXT:    store i16 [[CONV11_4]], ptr [[ARRAYIDX13_4]], align 2
; CHECK-NEXT:    [[INC_4:%.*]] = or disjoint i32 [[I_023]], 5
; CHECK-NEXT:    [[MUL_5:%.*]] = mul nsw i32 [[INC_4]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_5]]
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[ARRAYIDX_5]], align 2
; CHECK-NEXT:    [[CONV_5:%.*]] = sext i16 [[TMP10]] to i32
; CHECK-NEXT:    [[MUL8_5:%.*]] = mul nsw i32 [[INC_4]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_5:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_5]]
; CHECK-NEXT:    [[TMP11:%.*]] = load i16, ptr [[ARRAYIDX9_5]], align 2
; CHECK-NEXT:    [[CONV10_5:%.*]] = sext i16 [[TMP11]] to i32
; CHECK-NEXT:    [[ADD_5:%.*]] = add nsw i32 [[CONV10_5]], [[CONV_5]]
; CHECK-NEXT:    [[SHR_5:%.*]] = ashr i32 [[ADD_5]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_5:%.*]] = trunc i32 [[SHR_5]] to i16
; CHECK-NEXT:    [[MUL12_5:%.*]] = mul nsw i32 [[INC_4]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_5:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_5]]
; CHECK-NEXT:    store i16 [[CONV11_5]], ptr [[ARRAYIDX13_5]], align 2
; CHECK-NEXT:    [[INC_5:%.*]] = or disjoint i32 [[I_023]], 6
; CHECK-NEXT:    [[MUL_6:%.*]] = mul nsw i32 [[INC_5]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_6]]
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[ARRAYIDX_6]], align 2
; CHECK-NEXT:    [[CONV_6:%.*]] = sext i16 [[TMP12]] to i32
; CHECK-NEXT:    [[MUL8_6:%.*]] = mul nsw i32 [[INC_5]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_6:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_6]]
; CHECK-NEXT:    [[TMP13:%.*]] = load i16, ptr [[ARRAYIDX9_6]], align 2
; CHECK-NEXT:    [[CONV10_6:%.*]] = sext i16 [[TMP13]] to i32
; CHECK-NEXT:    [[ADD_6:%.*]] = add nsw i32 [[CONV10_6]], [[CONV_6]]
; CHECK-NEXT:    [[SHR_6:%.*]] = ashr i32 [[ADD_6]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_6:%.*]] = trunc i32 [[SHR_6]] to i16
; CHECK-NEXT:    [[MUL12_6:%.*]] = mul nsw i32 [[INC_5]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_6:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_6]]
; CHECK-NEXT:    store i16 [[CONV11_6]], ptr [[ARRAYIDX13_6]], align 2
; CHECK-NEXT:    [[INC_6:%.*]] = or disjoint i32 [[I_023]], 7
; CHECK-NEXT:    [[MUL_7:%.*]] = mul nsw i32 [[INC_6]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_7]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[ARRAYIDX_7]], align 2
; CHECK-NEXT:    [[CONV_7:%.*]] = sext i16 [[TMP14]] to i32
; CHECK-NEXT:    [[MUL8_7:%.*]] = mul nsw i32 [[INC_6]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_7:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_7]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[ARRAYIDX9_7]], align 2
; CHECK-NEXT:    [[CONV10_7:%.*]] = sext i16 [[TMP15]] to i32
; CHECK-NEXT:    [[ADD_7:%.*]] = add nsw i32 [[CONV10_7]], [[CONV_7]]
; CHECK-NEXT:    [[SHR_7:%.*]] = ashr i32 [[ADD_7]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_7:%.*]] = trunc i32 [[SHR_7]] to i16
; CHECK-NEXT:    [[MUL12_7:%.*]] = mul nsw i32 [[INC_6]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_7:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_7]]
; CHECK-NEXT:    store i16 [[CONV11_7]], ptr [[ARRAYIDX13_7]], align 2
; CHECK-NEXT:    [[INC_7:%.*]] = or disjoint i32 [[I_023]], 8
; CHECK-NEXT:    [[MUL_8:%.*]] = mul nsw i32 [[INC_7]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_8:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_8]]
; CHECK-NEXT:    [[TMP16:%.*]] = load i16, ptr [[ARRAYIDX_8]], align 2
; CHECK-NEXT:    [[CONV_8:%.*]] = sext i16 [[TMP16]] to i32
; CHECK-NEXT:    [[MUL8_8:%.*]] = mul nsw i32 [[INC_7]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_8:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_8]]
; CHECK-NEXT:    [[TMP17:%.*]] = load i16, ptr [[ARRAYIDX9_8]], align 2
; CHECK-NEXT:    [[CONV10_8:%.*]] = sext i16 [[TMP17]] to i32
; CHECK-NEXT:    [[ADD_8:%.*]] = add nsw i32 [[CONV10_8]], [[CONV_8]]
; CHECK-NEXT:    [[SHR_8:%.*]] = ashr i32 [[ADD_8]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_8:%.*]] = trunc i32 [[SHR_8]] to i16
; CHECK-NEXT:    [[MUL12_8:%.*]] = mul nsw i32 [[INC_7]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_8:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_8]]
; CHECK-NEXT:    store i16 [[CONV11_8]], ptr [[ARRAYIDX13_8]], align 2
; CHECK-NEXT:    [[INC_8:%.*]] = or disjoint i32 [[I_023]], 9
; CHECK-NEXT:    [[MUL_9:%.*]] = mul nsw i32 [[INC_8]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_9:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_9]]
; CHECK-NEXT:    [[TMP18:%.*]] = load i16, ptr [[ARRAYIDX_9]], align 2
; CHECK-NEXT:    [[CONV_9:%.*]] = sext i16 [[TMP18]] to i32
; CHECK-NEXT:    [[MUL8_9:%.*]] = mul nsw i32 [[INC_8]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_9:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_9]]
; CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[ARRAYIDX9_9]], align 2
; CHECK-NEXT:    [[CONV10_9:%.*]] = sext i16 [[TMP19]] to i32
; CHECK-NEXT:    [[ADD_9:%.*]] = add nsw i32 [[CONV10_9]], [[CONV_9]]
; CHECK-NEXT:    [[SHR_9:%.*]] = ashr i32 [[ADD_9]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_9:%.*]] = trunc i32 [[SHR_9]] to i16
; CHECK-NEXT:    [[MUL12_9:%.*]] = mul nsw i32 [[INC_8]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_9:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_9]]
; CHECK-NEXT:    store i16 [[CONV11_9]], ptr [[ARRAYIDX13_9]], align 2
; CHECK-NEXT:    [[INC_9:%.*]] = or disjoint i32 [[I_023]], 10
; CHECK-NEXT:    [[MUL_10:%.*]] = mul nsw i32 [[INC_9]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_10:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_10]]
; CHECK-NEXT:    [[TMP20:%.*]] = load i16, ptr [[ARRAYIDX_10]], align 2
; CHECK-NEXT:    [[CONV_10:%.*]] = sext i16 [[TMP20]] to i32
; CHECK-NEXT:    [[MUL8_10:%.*]] = mul nsw i32 [[INC_9]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_10:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_10]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[ARRAYIDX9_10]], align 2
; CHECK-NEXT:    [[CONV10_10:%.*]] = sext i16 [[TMP21]] to i32
; CHECK-NEXT:    [[ADD_10:%.*]] = add nsw i32 [[CONV10_10]], [[CONV_10]]
; CHECK-NEXT:    [[SHR_10:%.*]] = ashr i32 [[ADD_10]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_10:%.*]] = trunc i32 [[SHR_10]] to i16
; CHECK-NEXT:    [[MUL12_10:%.*]] = mul nsw i32 [[INC_9]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_10:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_10]]
; CHECK-NEXT:    store i16 [[CONV11_10]], ptr [[ARRAYIDX13_10]], align 2
; CHECK-NEXT:    [[INC_10:%.*]] = or disjoint i32 [[I_023]], 11
; CHECK-NEXT:    [[MUL_11:%.*]] = mul nsw i32 [[INC_10]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_11:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_11]]
; CHECK-NEXT:    [[TMP22:%.*]] = load i16, ptr [[ARRAYIDX_11]], align 2
; CHECK-NEXT:    [[CONV_11:%.*]] = sext i16 [[TMP22]] to i32
; CHECK-NEXT:    [[MUL8_11:%.*]] = mul nsw i32 [[INC_10]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_11:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_11]]
; CHECK-NEXT:    [[TMP23:%.*]] = load i16, ptr [[ARRAYIDX9_11]], align 2
; CHECK-NEXT:    [[CONV10_11:%.*]] = sext i16 [[TMP23]] to i32
; CHECK-NEXT:    [[ADD_11:%.*]] = add nsw i32 [[CONV10_11]], [[CONV_11]]
; CHECK-NEXT:    [[SHR_11:%.*]] = ashr i32 [[ADD_11]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_11:%.*]] = trunc i32 [[SHR_11]] to i16
; CHECK-NEXT:    [[MUL12_11:%.*]] = mul nsw i32 [[INC_10]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_11:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_11]]
; CHECK-NEXT:    store i16 [[CONV11_11]], ptr [[ARRAYIDX13_11]], align 2
; CHECK-NEXT:    [[INC_11:%.*]] = or disjoint i32 [[I_023]], 12
; CHECK-NEXT:    [[MUL_12:%.*]] = mul nsw i32 [[INC_11]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_12:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_12]]
; CHECK-NEXT:    [[TMP24:%.*]] = load i16, ptr [[ARRAYIDX_12]], align 2
; CHECK-NEXT:    [[CONV_12:%.*]] = sext i16 [[TMP24]] to i32
; CHECK-NEXT:    [[MUL8_12:%.*]] = mul nsw i32 [[INC_11]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_12:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_12]]
; CHECK-NEXT:    [[TMP25:%.*]] = load i16, ptr [[ARRAYIDX9_12]], align 2
; CHECK-NEXT:    [[CONV10_12:%.*]] = sext i16 [[TMP25]] to i32
; CHECK-NEXT:    [[ADD_12:%.*]] = add nsw i32 [[CONV10_12]], [[CONV_12]]
; CHECK-NEXT:    [[SHR_12:%.*]] = ashr i32 [[ADD_12]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_12:%.*]] = trunc i32 [[SHR_12]] to i16
; CHECK-NEXT:    [[MUL12_12:%.*]] = mul nsw i32 [[INC_11]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_12:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_12]]
; CHECK-NEXT:    store i16 [[CONV11_12]], ptr [[ARRAYIDX13_12]], align 2
; CHECK-NEXT:    [[INC_12:%.*]] = or disjoint i32 [[I_023]], 13
; CHECK-NEXT:    [[MUL_13:%.*]] = mul nsw i32 [[INC_12]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_13:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_13]]
; CHECK-NEXT:    [[TMP26:%.*]] = load i16, ptr [[ARRAYIDX_13]], align 2
; CHECK-NEXT:    [[CONV_13:%.*]] = sext i16 [[TMP26]] to i32
; CHECK-NEXT:    [[MUL8_13:%.*]] = mul nsw i32 [[INC_12]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_13:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_13]]
; CHECK-NEXT:    [[TMP27:%.*]] = load i16, ptr [[ARRAYIDX9_13]], align 2
; CHECK-NEXT:    [[CONV10_13:%.*]] = sext i16 [[TMP27]] to i32
; CHECK-NEXT:    [[ADD_13:%.*]] = add nsw i32 [[CONV10_13]], [[CONV_13]]
; CHECK-NEXT:    [[SHR_13:%.*]] = ashr i32 [[ADD_13]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_13:%.*]] = trunc i32 [[SHR_13]] to i16
; CHECK-NEXT:    [[MUL12_13:%.*]] = mul nsw i32 [[INC_12]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_13:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_13]]
; CHECK-NEXT:    store i16 [[CONV11_13]], ptr [[ARRAYIDX13_13]], align 2
; CHECK-NEXT:    [[INC_13:%.*]] = or disjoint i32 [[I_023]], 14
; CHECK-NEXT:    [[MUL_14:%.*]] = mul nsw i32 [[INC_13]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_14:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_14]]
; CHECK-NEXT:    [[TMP28:%.*]] = load i16, ptr [[ARRAYIDX_14]], align 2
; CHECK-NEXT:    [[CONV_14:%.*]] = sext i16 [[TMP28]] to i32
; CHECK-NEXT:    [[MUL8_14:%.*]] = mul nsw i32 [[INC_13]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_14:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_14]]
; CHECK-NEXT:    [[TMP29:%.*]] = load i16, ptr [[ARRAYIDX9_14]], align 2
; CHECK-NEXT:    [[CONV10_14:%.*]] = sext i16 [[TMP29]] to i32
; CHECK-NEXT:    [[ADD_14:%.*]] = add nsw i32 [[CONV10_14]], [[CONV_14]]
; CHECK-NEXT:    [[SHR_14:%.*]] = ashr i32 [[ADD_14]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_14:%.*]] = trunc i32 [[SHR_14]] to i16
; CHECK-NEXT:    [[MUL12_14:%.*]] = mul nsw i32 [[INC_13]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_14:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_14]]
; CHECK-NEXT:    store i16 [[CONV11_14]], ptr [[ARRAYIDX13_14]], align 2
; CHECK-NEXT:    [[INC_14:%.*]] = or disjoint i32 [[I_023]], 15
; CHECK-NEXT:    [[MUL_15:%.*]] = mul nsw i32 [[INC_14]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_15:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_15]]
; CHECK-NEXT:    [[TMP30:%.*]] = load i16, ptr [[ARRAYIDX_15]], align 2
; CHECK-NEXT:    [[CONV_15:%.*]] = sext i16 [[TMP30]] to i32
; CHECK-NEXT:    [[MUL8_15:%.*]] = mul nsw i32 [[INC_14]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_15:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_15]]
; CHECK-NEXT:    [[TMP31:%.*]] = load i16, ptr [[ARRAYIDX9_15]], align 2
; CHECK-NEXT:    [[CONV10_15:%.*]] = sext i16 [[TMP31]] to i32
; CHECK-NEXT:    [[ADD_15:%.*]] = add nsw i32 [[CONV10_15]], [[CONV_15]]
; CHECK-NEXT:    [[SHR_15:%.*]] = ashr i32 [[ADD_15]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_15:%.*]] = trunc i32 [[SHR_15]] to i16
; CHECK-NEXT:    [[MUL12_15:%.*]] = mul nsw i32 [[INC_14]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_15:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_15]]
; CHECK-NEXT:    store i16 [[CONV11_15]], ptr [[ARRAYIDX13_15]], align 2
; CHECK-NEXT:    [[INC_15]] = add nuw nsw i32 [[I_023]], 16
; CHECK-NEXT:    [[EXITCOND_NOT_15:%.*]] = icmp slt i32 [[INC_15]], [[AND]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_15]], label [[FOR_BODY_15]], label [[FOR_BODY_PREHEADER]]
; CHECK:       for.body.clone:
; CHECK-NEXT:    [[I_023_CLONE:%.*]] = phi i32 [ [[INC_CLONE:%.*]], [[FOR_BODY_CLONE]] ], [ [[I_0_LCSSA]], [[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[MUL_CLONE:%.*]] = mul nsw i32 [[I_023_CLONE]], [[STEP1]]
; CHECK-NEXT:    [[ARRAYIDX_CLONE:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT1]], i32 [[MUL_CLONE]]
; CHECK-NEXT:    [[TMP32:%.*]] = load i16, ptr [[ARRAYIDX_CLONE]], align 2
; CHECK-NEXT:    [[CONV_CLONE:%.*]] = sext i16 [[TMP32]] to i32
; CHECK-NEXT:    [[MUL8_CLONE:%.*]] = mul nsw i32 [[I_023_CLONE]], [[STEP2]]
; CHECK-NEXT:    [[ARRAYIDX9_CLONE:%.*]] = getelementptr inbounds [2 x i8], ptr [[INPUT2]], i32 [[MUL8_CLONE]]
; CHECK-NEXT:    [[TMP33:%.*]] = load i16, ptr [[ARRAYIDX9_CLONE]], align 2
; CHECK-NEXT:    [[CONV10_CLONE:%.*]] = sext i16 [[TMP33]] to i32
; CHECK-NEXT:    [[ADD_CLONE:%.*]] = add nsw i32 [[CONV10_CLONE]], [[CONV_CLONE]]
; CHECK-NEXT:    [[SHR_CLONE:%.*]] = ashr i32 [[ADD_CLONE]], [[SHIFT]]
; CHECK-NEXT:    [[CONV11_CLONE:%.*]] = trunc i32 [[SHR_CLONE]] to i16
; CHECK-NEXT:    [[MUL12_CLONE:%.*]] = mul nsw i32 [[I_023_CLONE]], [[STEP_OUT]]
; CHECK-NEXT:    [[ARRAYIDX13_CLONE:%.*]] = getelementptr inbounds [2 x i8], ptr [[OUTPUT]], i32 [[MUL12_CLONE]]
; CHECK-NEXT:    store i16 [[CONV11_CLONE]], ptr [[ARRAYIDX13_CLONE]], align 2
; CHECK-NEXT:    [[INC_CLONE]] = add nuw nsw i32 [[I_023_CLONE]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_CLONE:%.*]] = icmp eq i32 [[INC_CLONE]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_CLONE]], label [[RETURN]], label [[FOR_BODY_CLONE]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 458755, [[ENTRY:%.*]] ], [ 0, [[FOR_BODY_PREHEADER]] ], [ 0, [[FOR_BODY_CLONE]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp eq ptr %input1, null
  %cmp1 = icmp eq ptr %input2, null
  %or.cond = or i1 %cmp, %cmp1
  %cmp4 = icmp eq ptr %output, null
  %or.cond21 = or i1 %or.cond, %cmp4
  br i1 %or.cond21, label %return, label %for.cond.preheader

for.cond.preheader:                               ; preds = %entry
  %cmp722 = icmp sgt i32 %len, 0
  br i1 %cmp722, label %for.body, label %return

for.body:                                         ; preds = %for.body, %for.cond.preheader
  %i.023 = phi i32 [ %inc, %for.body ], [ 0, %for.cond.preheader ]
  %mul = mul nsw i32 %i.023, %step1
  %arrayidx = getelementptr inbounds i16, ptr %input1, i32 %mul
  %0 = load i16, ptr %arrayidx, align 2
  %conv = sext i16 %0 to i32
  %mul8 = mul nsw i32 %i.023, %step2
  %arrayidx9 = getelementptr inbounds i16, ptr %input2, i32 %mul8
  %1 = load i16, ptr %arrayidx9, align 2
  %conv10 = sext i16 %1 to i32
  %add = add nsw i32 %conv10, %conv
  %shr = ashr i32 %add, %shift
  %conv11 = trunc i32 %shr to i16
  %mul12 = mul nsw i32 %i.023, %step_out
  %arrayidx13 = getelementptr inbounds i16, ptr %output, i32 %mul12
  store i16 %conv11, ptr %arrayidx13, align 2
  %inc = add nuw nsw i32 %i.023, 1
  %exitcond.not = icmp eq i32 %inc, %len
  br i1 %exitcond.not, label %return, label %for.body

return:                                           ; preds = %for.body, %for.cond.preheader, %entry
  %retval.0 = phi i32 [ 458755, %entry ], [ 0, %for.cond.preheader ], [ 0, %for.body ]
  ret i32 %retval.0
}
