; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf  < %s | FileCheck %s

; ModuleID = 'dspm_mult_s16_ansi.c'
source_filename = "dspm_mult_s16_ansi.c"
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "riscv32-esp-unknown-elf"

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite)
define dso_local noundef i32 @dspm_mult_s16_ansi(ptr nocapture noundef readonly %A, ptr nocapture noundef readonly %B, ptr nocapture noundef writeonly %C, i32 noundef %m, i32 noundef %n, i32 noundef %k, i32 noundef %shift) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local noundef i32 @dspm_mult_s16_ansi(
; CHECK-SAME: ptr noundef readonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]], ptr noundef writeonly captures(none) [[C:%.*]], i32 noundef [[M:%.*]], i32 noundef [[N:%.*]], i32 noundef [[K:%.*]], i32 noundef [[SHIFT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP100:%.*]] = icmp sgt i32 [[M]], 0
; CHECK-NEXT:    br i1 [[CMP100]], label %[[FOR_COND1_PREHEADER_LR_PH:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_LR_PH]]:
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[SHIFT]], -15
; CHECK-NEXT:    [[CMP268:%.*]] = icmp sgt i32 [[K]], 0
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 32767, [[SHIFT]]
; CHECK-NEXT:    [[CONV:%.*]] = zext nneg i32 [[SHR]] to i64
; CHECK-NEXT:    [[CMP665:%.*]] = icmp sgt i32 [[N]], 0
; CHECK-NEXT:    [[TMP0:%.*]] = and i32 [[K]], 7
; CHECK-NEXT:    [[CMP22:%.*]] = icmp eq i32 [[TMP0]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = sub nsw i32 15, [[SHIFT]]
; CHECK-NEXT:    [[TMP2:%.*]] = zext nneg i32 [[TMP1]] to i64
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[SUB]] to i64
; CHECK-NEXT:    [[TMP3:%.*]] = lshr i64 [[CONV]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = trunc nuw nsw i64 [[TMP3]] to i16
; CHECK-NEXT:    [[SHL_US:%.*]] = shl i64 [[CONV]], [[SH_PROM]]
; CHECK-NEXT:    [[CONV20_US:%.*]] = trunc i64 [[SHL_US]] to i16
; CHECK-NEXT:    br i1 [[CMP268]], label %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US:.*]], label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_COND1_PREHEADER_LR_PH_SPLIT_US]]:
; CHECK-NEXT:    [[CMP18:%.*]] = icmp sgt i32 [[SHIFT]], 15
; CHECK-NEXT:    br i1 [[CMP18]], label %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_US:.*]], label %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_US]]:
; CHECK-NEXT:    br i1 [[CMP665]], label %[[FOR_COND1_PREHEADER_US_US_US:.*]], label %[[FOR_COND1_PREHEADER_US_US:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_US_US_US]]:
; CHECK-NEXT:    [[I_0101_US_US_US:%.*]] = phi i32 [ [[INC35_US_US_US:%.*]], %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_US_SPLIT_US_US_US_US:.*]] ], [ 0, %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_US]] ]
; CHECK-NEXT:    [[MUL_US_US_US:%.*]] = mul nuw nsw i32 [[I_0101_US_US_US]], [[N]]
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i16, ptr [[A]], i32 [[MUL_US_US_US]]
; CHECK-NEXT:    [[MUL21_US_US_US:%.*]] = mul nuw nsw i32 [[I_0101_US_US_US]], [[K]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i16, ptr [[C]], i32 [[MUL21_US_US_US]]
; CHECK-NEXT:    br label %[[FOR_BODY4_US_US_US_US_US:.*]]
; CHECK:       [[FOR_BODY4_US_US_US_US_US]]:
; CHECK-NEXT:    [[J_069_US_US_US_US_US:%.*]] = phi i32 [ 0, %[[FOR_COND1_PREHEADER_US_US_US]] ], [ [[INC32_US_US_US_US_US:%.*]], %[[FOR_COND5_FOR_COND_CLEANUP8_CRIT_EDGE_US_US_US_US_US:.*]] ]
; CHECK-NEXT:    [[INVARIANT_GEP_US_US_US_US_US:%.*]] = getelementptr i16, ptr [[B]], i32 [[J_069_US_US_US_US_US]]
; CHECK-NEXT:    br label %[[FOR_BODY9_US_US_US_US_US:.*]]
; CHECK:       [[FOR_BODY9_US_US_US_US_US]]:
; CHECK-NEXT:    [[S_067_US_US_US_US_US:%.*]] = phi i32 [ 0, %[[FOR_BODY4_US_US_US_US_US]] ], [ [[INC_US_US_US_US_US:%.*]], %[[FOR_BODY9_US_US_US_US_US]] ]
; CHECK-NEXT:    [[ACC_066_US_US_US_US_US:%.*]] = phi i64 [ [[CONV]], %[[FOR_BODY4_US_US_US_US_US]] ], [ [[ADD17_US_US_US_US_US:%.*]], %[[FOR_BODY9_US_US_US_US_US]] ]
; CHECK-NEXT:    [[ARRAYIDX_US_US_US_US_US:%.*]] = getelementptr i16, ptr [[TMP5]], i32 [[S_067_US_US_US_US_US]]
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr [[ARRAYIDX_US_US_US_US_US]], align 2, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[CONV10_US_US_US_US_US:%.*]] = sext i16 [[TMP7]] to i32
; CHECK-NEXT:    [[MUL11_US_US_US_US_US:%.*]] = mul nuw nsw i32 [[S_067_US_US_US_US_US]], [[K]]
; CHECK-NEXT:    [[GEP_US_US_US_US_US:%.*]] = getelementptr i16, ptr [[INVARIANT_GEP_US_US_US_US_US]], i32 [[MUL11_US_US_US_US_US]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[GEP_US_US_US_US_US]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[CONV14_US_US_US_US_US:%.*]] = sext i16 [[TMP8]] to i32
; CHECK-NEXT:    [[MUL15_US_US_US_US_US:%.*]] = mul nsw i32 [[CONV14_US_US_US_US_US]], [[CONV10_US_US_US_US_US]]
; CHECK-NEXT:    [[CONV16_US_US_US_US_US:%.*]] = sext i32 [[MUL15_US_US_US_US_US]] to i64
; CHECK-NEXT:    [[ADD17_US_US_US_US_US]] = add nsw i64 [[ACC_066_US_US_US_US_US]], [[CONV16_US_US_US_US_US]]
; CHECK-NEXT:    [[INC_US_US_US_US_US]] = add nuw nsw i32 [[S_067_US_US_US_US_US]], 1
; CHECK-NEXT:    [[EXITCOND145_NOT:%.*]] = icmp eq i32 [[INC_US_US_US_US_US]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND145_NOT]], label %[[FOR_COND5_FOR_COND_CLEANUP8_CRIT_EDGE_US_US_US_US_US]], label %[[FOR_BODY9_US_US_US_US_US]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       [[FOR_COND5_FOR_COND_CLEANUP8_CRIT_EDGE_US_US_US_US_US]]:
; CHECK-NEXT:    [[SHL_US_US_US_US_US:%.*]] = shl i64 [[ADD17_US_US_US_US_US]], [[SH_PROM]]
; CHECK-NEXT:    [[CONV20_US_US_US_US_US:%.*]] = trunc i64 [[SHL_US_US_US_US_US]] to i16
; CHECK-NEXT:    [[ARRAYIDX23_US_US_US_US_US:%.*]] = getelementptr i16, ptr [[TMP6]], i32 [[J_069_US_US_US_US_US]]
; CHECK-NEXT:    store i16 [[CONV20_US_US_US_US_US]], ptr [[ARRAYIDX23_US_US_US_US_US]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INC32_US_US_US_US_US]] = add nuw nsw i32 [[J_069_US_US_US_US_US]], 1
; CHECK-NEXT:    [[EXITCOND146_NOT:%.*]] = icmp eq i32 [[INC32_US_US_US_US_US]], [[K]]
; CHECK-NEXT:    br i1 [[EXITCOND146_NOT]], label %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_US_SPLIT_US_US_US_US]], label %[[FOR_BODY4_US_US_US_US_US]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       [[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_US_SPLIT_US_US_US_US]]:
; CHECK-NEXT:    [[INC35_US_US_US]] = add nuw nsw i32 [[I_0101_US_US_US]], 1
; CHECK-NEXT:    [[EXITCOND147_NOT:%.*]] = icmp eq i32 [[INC35_US_US_US]], [[M]]
; CHECK-NEXT:    br i1 [[EXITCOND147_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND1_PREHEADER_US_US_US]], !llvm.loop [[LOOP13:![0-9]+]]
; CHECK:       [[FOR_COND1_PREHEADER_US_US]]:
; CHECK-NEXT:    [[I_0101_US_US:%.*]] = phi i32 [ [[INC35_US_US:%.*]], %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_US_SPLIT_US113_US:.*]] ], [ 0, %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_US]] ]
; CHECK-NEXT:    [[MUL21_US_US:%.*]] = mul nuw nsw i32 [[I_0101_US_US]], [[K]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr i16, ptr [[C]], i32 [[MUL21_US_US]]
; CHECK-NEXT:    br label %[[FOR_BODY4_US_US108_US:.*]]
; CHECK:       [[FOR_BODY4_US_US108_US]]:
; CHECK-NEXT:    [[J_069_US_US109_US:%.*]] = phi i32 [ 0, %[[FOR_COND1_PREHEADER_US_US]] ], [ [[INC32_US_US111_US:%.*]], %[[FOR_BODY4_US_US108_US]] ]
; CHECK-NEXT:    [[ARRAYIDX23_US_US110_US:%.*]] = getelementptr i16, ptr [[TMP9]], i32 [[J_069_US_US109_US]]
; CHECK-NEXT:    store i16 [[CONV20_US]], ptr [[ARRAYIDX23_US_US110_US]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INC32_US_US111_US]] = add nuw nsw i32 [[J_069_US_US109_US]], 1
; CHECK-NEXT:    [[EXITCOND143_NOT:%.*]] = icmp eq i32 [[INC32_US_US111_US]], [[K]]
; CHECK-NEXT:    br i1 [[EXITCOND143_NOT]], label %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_US_SPLIT_US113_US]], label %[[FOR_BODY4_US_US108_US]], !llvm.loop [[LOOP12]]
; CHECK:       [[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_US_SPLIT_US113_US]]:
; CHECK-NEXT:    [[INC35_US_US]] = add nuw nsw i32 [[I_0101_US_US]], 1
; CHECK-NEXT:    [[EXITCOND144_NOT:%.*]] = icmp eq i32 [[INC35_US_US]], [[M]]
; CHECK-NEXT:    br i1 [[EXITCOND144_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND1_PREHEADER_US_US]], !llvm.loop [[LOOP13]]
; CHECK:       [[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT]]:
; CHECK-NEXT:    br i1 [[CMP665]], label %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_SPLIT_US:.*]], label %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_SPLIT:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_SPLIT_US]]:
; CHECK-NEXT:    br i1 [[CMP22]], label %[[FOR_COND1_PREHEADER_US_US119_US:.*]], label %[[FOR_COND1_PREHEADER_US_US119:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_US_US119_US]]:
; CHECK-NEXT:    [[I_0101_US_US120_US:%.*]] = phi i32 [ [[INC35_US_US122_US:%.*]], %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_US_US_US_SPLIT_US_US:.*]] ], [ 0, %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_SPLIT_US]] ]
; CHECK-NEXT:    [[MUL_US_US121_US:%.*]] = mul nuw nsw i32 [[I_0101_US_US120_US]], [[N]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr i16, ptr [[A]], i32 [[MUL_US_US121_US]]
; CHECK-NEXT:    [[TMP11:%.*]] = mul nuw nsw i32 [[I_0101_US_US120_US]], [[K]]
; CHECK-NEXT:    [[TMP12:%.*]] = getelementptr i16, ptr [[C]], i32 [[TMP11]]
; CHECK-NEXT:    br label %[[FOR_BODY4_US70_US_US_US_US:.*]]
; CHECK:       [[FOR_BODY4_US70_US_US_US_US]]:
; CHECK-NEXT:    [[J_069_US71_US_US_US_US:%.*]] = phi i32 [ 0, %[[FOR_COND1_PREHEADER_US_US119_US]] ], [ [[INC32_US76_US_US_US_US:%.*]], %[[FOR_COND5_FOR_COND_CLEANUP8_CRIT_EDGE_US92_US_US_US_US:.*]] ]
; CHECK-NEXT:    [[INVARIANT_GEP_US72_US_US_US_US:%.*]] = getelementptr i16, ptr [[B]], i32 [[J_069_US71_US_US_US_US]]
; CHECK-NEXT:    br label %[[FOR_BODY9_US78_US_US_US_US:.*]]
; CHECK:       [[FOR_BODY9_US78_US_US_US_US]]:
; CHECK-NEXT:    [[S_067_US79_US_US_US_US:%.*]] = phi i32 [ 0, %[[FOR_BODY4_US70_US_US_US_US]] ], [ [[INC_US89_US_US_US_US:%.*]], %[[FOR_BODY9_US78_US_US_US_US]] ]
; CHECK-NEXT:    [[ACC_066_US80_US_US_US_US:%.*]] = phi i64 [ [[CONV]], %[[FOR_BODY4_US70_US_US_US_US]] ], [ [[ADD17_US88_US_US_US_US:%.*]], %[[FOR_BODY9_US78_US_US_US_US]] ]
; CHECK-NEXT:    [[ARRAYIDX_US81_US_US_US_US:%.*]] = getelementptr i16, ptr [[TMP10]], i32 [[S_067_US79_US_US_US_US]]
; CHECK-NEXT:    [[TMP13:%.*]] = load i16, ptr [[ARRAYIDX_US81_US_US_US_US]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[CONV10_US82_US_US_US_US:%.*]] = sext i16 [[TMP13]] to i32
; CHECK-NEXT:    [[MUL11_US83_US_US_US_US:%.*]] = mul nuw nsw i32 [[S_067_US79_US_US_US_US]], [[K]]
; CHECK-NEXT:    [[GEP_US84_US_US_US_US:%.*]] = getelementptr i16, ptr [[INVARIANT_GEP_US72_US_US_US_US]], i32 [[MUL11_US83_US_US_US_US]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[GEP_US84_US_US_US_US]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[CONV14_US85_US_US_US_US:%.*]] = sext i16 [[TMP14]] to i32
; CHECK-NEXT:    [[MUL15_US86_US_US_US_US:%.*]] = mul nsw i32 [[CONV14_US85_US_US_US_US]], [[CONV10_US82_US_US_US_US]]
; CHECK-NEXT:    [[CONV16_US87_US_US_US_US:%.*]] = sext i32 [[MUL15_US86_US_US_US_US]] to i64
; CHECK-NEXT:    [[ADD17_US88_US_US_US_US]] = add nsw i64 [[ACC_066_US80_US_US_US_US]], [[CONV16_US87_US_US_US_US]]
; CHECK-NEXT:    [[INC_US89_US_US_US_US]] = add nuw nsw i32 [[S_067_US79_US_US_US_US]], 1
; CHECK-NEXT:    [[EXITCOND140_NOT:%.*]] = icmp eq i32 [[INC_US89_US_US_US_US]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND140_NOT]], label %[[FOR_COND5_FOR_COND_CLEANUP8_CRIT_EDGE_US92_US_US_US_US]], label %[[FOR_BODY9_US78_US_US_US_US]], !llvm.loop [[LOOP10]]
; CHECK:       [[FOR_COND5_FOR_COND_CLEANUP8_CRIT_EDGE_US92_US_US_US_US]]:
; CHECK-NEXT:    [[TMP15:%.*]] = ashr i64 [[ADD17_US88_US_US_US_US]], [[TMP2]]
; CHECK-NEXT:    [[TMP16:%.*]] = trunc i64 [[TMP15]] to i16
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr i16, ptr [[TMP12]], i32 [[J_069_US71_US_US_US_US]]
; CHECK-NEXT:    store i16 [[TMP16]], ptr [[TMP17]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INC32_US76_US_US_US_US]] = add nuw nsw i32 [[J_069_US71_US_US_US_US]], 1
; CHECK-NEXT:    [[EXITCOND141_NOT:%.*]] = icmp eq i32 [[INC32_US76_US_US_US_US]], [[K]]
; CHECK-NEXT:    br i1 [[EXITCOND141_NOT]], label %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_US_US_US_SPLIT_US_US]], label %[[FOR_BODY4_US70_US_US_US_US]], !llvm.loop [[LOOP12]]
; CHECK:       [[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_US_US_US_SPLIT_US_US]]:
; CHECK-NEXT:    [[INC35_US_US122_US]] = add nuw nsw i32 [[I_0101_US_US120_US]], 1
; CHECK-NEXT:    [[EXITCOND142_NOT:%.*]] = icmp eq i32 [[INC35_US_US122_US]], [[M]]
; CHECK-NEXT:    br i1 [[EXITCOND142_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND1_PREHEADER_US_US119_US]], !llvm.loop [[LOOP13]]
; CHECK:       [[FOR_COND1_PREHEADER_US_US119]]:
; CHECK-NEXT:    [[I_0101_US_US120:%.*]] = phi i32 [ [[INC35_US_US122:%.*]], %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_US_US_US_SPLIT:.*]] ], [ 0, %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_SPLIT_US]] ]
; CHECK-NEXT:    [[MUL_US_US121:%.*]] = mul nuw nsw i32 [[I_0101_US_US120]], [[N]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr i16, ptr [[A]], i32 [[MUL_US_US121]]
; CHECK-NEXT:    [[TMP19:%.*]] = mul nuw nsw i32 [[I_0101_US_US120]], [[K]]
; CHECK-NEXT:    [[TMP20:%.*]] = getelementptr i16, ptr [[C]], i32 [[TMP19]]
; CHECK-NEXT:    br label %[[FOR_BODY4_US70_US_US:.*]]
; CHECK:       [[FOR_BODY4_US70_US_US]]:
; CHECK-NEXT:    [[J_069_US71_US_US:%.*]] = phi i32 [ 0, %[[FOR_COND1_PREHEADER_US_US119]] ], [ [[INC32_US76_US_US:%.*]], %[[FOR_COND5_FOR_COND_CLEANUP8_CRIT_EDGE_US92_US_US:.*]] ]
; CHECK-NEXT:    [[INVARIANT_GEP_US72_US_US:%.*]] = getelementptr i16, ptr [[B]], i32 [[J_069_US71_US_US]]
; CHECK-NEXT:    br label %[[FOR_BODY9_US78_US_US:.*]]
; CHECK:       [[FOR_BODY9_US78_US_US]]:
; CHECK-NEXT:    [[S_067_US79_US_US:%.*]] = phi i32 [ 0, %[[FOR_BODY4_US70_US_US]] ], [ [[INC_US89_US_US:%.*]], %[[FOR_BODY9_US78_US_US]] ]
; CHECK-NEXT:    [[ACC_066_US80_US_US:%.*]] = phi i64 [ [[CONV]], %[[FOR_BODY4_US70_US_US]] ], [ [[ADD17_US88_US_US:%.*]], %[[FOR_BODY9_US78_US_US]] ]
; CHECK-NEXT:    [[ARRAYIDX_US81_US_US:%.*]] = getelementptr i16, ptr [[TMP18]], i32 [[S_067_US79_US_US]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[ARRAYIDX_US81_US_US]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[CONV10_US82_US_US:%.*]] = sext i16 [[TMP21]] to i32
; CHECK-NEXT:    [[MUL11_US83_US_US:%.*]] = mul nuw nsw i32 [[S_067_US79_US_US]], [[K]]
; CHECK-NEXT:    [[GEP_US84_US_US:%.*]] = getelementptr i16, ptr [[INVARIANT_GEP_US72_US_US]], i32 [[MUL11_US83_US_US]]
; CHECK-NEXT:    [[TMP22:%.*]] = load i16, ptr [[GEP_US84_US_US]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[CONV14_US85_US_US:%.*]] = sext i16 [[TMP22]] to i32
; CHECK-NEXT:    [[MUL15_US86_US_US:%.*]] = mul nsw i32 [[CONV14_US85_US_US]], [[CONV10_US82_US_US]]
; CHECK-NEXT:    [[CONV16_US87_US_US:%.*]] = sext i32 [[MUL15_US86_US_US]] to i64
; CHECK-NEXT:    [[ADD17_US88_US_US]] = add nsw i64 [[ACC_066_US80_US_US]], [[CONV16_US87_US_US]]
; CHECK-NEXT:    [[INC_US89_US_US]] = add nuw nsw i32 [[S_067_US79_US_US]], 1
; CHECK-NEXT:    [[EXITCOND137_NOT:%.*]] = icmp eq i32 [[INC_US89_US_US]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND137_NOT]], label %[[FOR_COND5_FOR_COND_CLEANUP8_CRIT_EDGE_US92_US_US]], label %[[FOR_BODY9_US78_US_US]], !llvm.loop [[LOOP10]]
; CHECK:       [[FOR_COND5_FOR_COND_CLEANUP8_CRIT_EDGE_US92_US_US]]:
; CHECK-NEXT:    [[TMP23:%.*]] = ashr i64 [[ADD17_US88_US_US]], [[TMP2]]
; CHECK-NEXT:    [[TMP24:%.*]] = trunc i64 [[TMP23]] to i16
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr i16, ptr [[TMP20]], i32 [[J_069_US71_US_US]]
; CHECK-NEXT:    store i16 [[TMP24]], ptr [[TMP25]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INC32_US76_US_US]] = add nuw nsw i32 [[J_069_US71_US_US]], 1
; CHECK-NEXT:    [[EXITCOND138_NOT:%.*]] = icmp eq i32 [[INC32_US76_US_US]], [[K]]
; CHECK-NEXT:    br i1 [[EXITCOND138_NOT]], label %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_US_US_US_SPLIT]], label %[[FOR_BODY4_US70_US_US]], !llvm.loop [[LOOP12]]
; CHECK:       [[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_US_US_US_SPLIT]]:
; CHECK-NEXT:    [[INC35_US_US122]] = add nuw nsw i32 [[I_0101_US_US120]], 1
; CHECK-NEXT:    [[EXITCOND139_NOT:%.*]] = icmp eq i32 [[INC35_US_US122]], [[M]]
; CHECK-NEXT:    br i1 [[EXITCOND139_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND1_PREHEADER_US_US119]], !llvm.loop [[LOOP13]]
; CHECK:       [[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_SPLIT]]:
; CHECK-NEXT:    br i1 [[CMP22]], label %[[FOR_COND1_PREHEADER_US_US124:.*]], label %[[FOR_COND1_PREHEADER_US:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_US_US124]]:
; CHECK-NEXT:    [[I_0101_US_US125:%.*]] = phi i32 [ [[INC35_US_US126:%.*]], %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_SPLIT_US_US_US:.*]] ], [ 0, %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_SPLIT]] ]
; CHECK-NEXT:    [[TMP26:%.*]] = mul nuw nsw i32 [[I_0101_US_US125]], [[K]]
; CHECK-NEXT:    [[TMP27:%.*]] = getelementptr i16, ptr [[C]], i32 [[TMP26]]
; CHECK-NEXT:    br label %[[FOR_BODY4_US94_US_US:.*]]
; CHECK:       [[FOR_BODY4_US94_US_US]]:
; CHECK-NEXT:    [[J_069_US95_US_US:%.*]] = phi i32 [ 0, %[[FOR_COND1_PREHEADER_US_US124]] ], [ [[INC32_US98_US_US:%.*]], %[[FOR_BODY4_US94_US_US]] ]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr i16, ptr [[TMP27]], i32 [[J_069_US95_US_US]]
; CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP28]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INC32_US98_US_US]] = add nuw nsw i32 [[J_069_US95_US_US]], 1
; CHECK-NEXT:    [[EXITCOND135_NOT:%.*]] = icmp eq i32 [[INC32_US98_US_US]], [[K]]
; CHECK-NEXT:    br i1 [[EXITCOND135_NOT]], label %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_SPLIT_US_US_US]], label %[[FOR_BODY4_US94_US_US]], !llvm.loop [[LOOP12]]
; CHECK:       [[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_SPLIT_US_US_US]]:
; CHECK-NEXT:    [[INC35_US_US126]] = add nuw nsw i32 [[I_0101_US_US125]], 1
; CHECK-NEXT:    [[EXITCOND136_NOT:%.*]] = icmp eq i32 [[INC35_US_US126]], [[M]]
; CHECK-NEXT:    br i1 [[EXITCOND136_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND1_PREHEADER_US_US124]], !llvm.loop [[LOOP13]]
; CHECK:       [[FOR_COND1_PREHEADER_US]]:
; CHECK-NEXT:    [[I_0101_US:%.*]] = phi i32 [ [[INC35_US:%.*]], %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_SPLIT_US106:.*]] ], [ 0, %[[FOR_COND1_PREHEADER_LR_PH_SPLIT_US_SPLIT_SPLIT]] ]
; CHECK-NEXT:    [[TMP29:%.*]] = mul nuw nsw i32 [[I_0101_US]], [[K]]
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr i16, ptr [[C]], i32 [[TMP29]]
; CHECK-NEXT:    br label %[[FOR_BODY4_US102:.*]]
; CHECK:       [[FOR_BODY4_US102]]:
; CHECK-NEXT:    [[J_069_US103:%.*]] = phi i32 [ 0, %[[FOR_COND1_PREHEADER_US]] ], [ [[INC32_US104:%.*]], %[[FOR_BODY4_US102]] ]
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr i16, ptr [[TMP30]], i32 [[J_069_US103]]
; CHECK-NEXT:    store i16 [[TMP4]], ptr [[TMP31]], align 2, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INC32_US104]] = add nuw nsw i32 [[J_069_US103]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC32_US104]], [[K]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_SPLIT_US106]], label %[[FOR_BODY4_US102]], !llvm.loop [[LOOP12]]
; CHECK:       [[FOR_COND1_FOR_COND_CLEANUP3_CRIT_EDGE_SPLIT_SPLIT_SPLIT_US106]]:
; CHECK-NEXT:    [[INC35_US]] = add nuw nsw i32 [[I_0101_US]], 1
; CHECK-NEXT:    [[EXITCOND134_NOT:%.*]] = icmp eq i32 [[INC35_US]], [[M]]
; CHECK-NEXT:    br i1 [[EXITCOND134_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND1_PREHEADER_US]], !llvm.loop [[LOOP13]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  %cmp100 = icmp sgt i32 %m, 0
  br i1 %cmp100, label %for.cond1.preheader.lr.ph, label %for.cond.cleanup

for.cond1.preheader.lr.ph:                        ; preds = %entry
  %sub = add nsw i32 %shift, -15
  %cmp268 = icmp sgt i32 %k, 0
  %shr = lshr i32 32767, %shift
  %conv = zext nneg i32 %shr to i64
  %cmp665 = icmp sgt i32 %n, 0
  %0 = and i32 %k, 7
  %cmp22 = icmp eq i32 %0, 0
  %1 = sub nsw i32 15, %shift
  %2 = zext nneg i32 %1 to i64
  %sh_prom = zext nneg i32 %sub to i64
  %3 = lshr i64 %conv, %2
  %4 = trunc nuw nsw i64 %3 to i16
  %shl.us = shl i64 %conv, %sh_prom
  %conv20.us = trunc i64 %shl.us to i16
  br i1 %cmp268, label %for.cond1.preheader.lr.ph.split.us, label %for.cond.cleanup

for.cond1.preheader.lr.ph.split.us:               ; preds = %for.cond1.preheader.lr.ph
  %cmp18 = icmp sgt i32 %shift, 15
  br i1 %cmp18, label %for.cond1.preheader.lr.ph.split.us.split.us, label %for.cond1.preheader.lr.ph.split.us.split

for.cond1.preheader.lr.ph.split.us.split.us:      ; preds = %for.cond1.preheader.lr.ph.split.us
  br i1 %cmp665, label %for.cond1.preheader.us.us.us, label %for.cond1.preheader.us.us

for.cond1.preheader.us.us.us:                     ; preds = %for.cond1.preheader.lr.ph.split.us.split.us, %for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us.us.us.us
  %i.0101.us.us.us = phi i32 [ %inc35.us.us.us, %for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us.us.us.us ], [ 0, %for.cond1.preheader.lr.ph.split.us.split.us ]
  %mul.us.us.us = mul nuw nsw i32 %i.0101.us.us.us, %n
  %5 = getelementptr i16, ptr %A, i32 %mul.us.us.us
  %mul21.us.us.us = mul nuw nsw i32 %i.0101.us.us.us, %k
  %6 = getelementptr i16, ptr %C, i32 %mul21.us.us.us
  br label %for.body4.us.us.us.us.us

for.body4.us.us.us.us.us:                         ; preds = %for.cond5.for.cond.cleanup8_crit_edge.us.us.us.us.us, %for.cond1.preheader.us.us.us
  %j.069.us.us.us.us.us = phi i32 [ 0, %for.cond1.preheader.us.us.us ], [ %inc32.us.us.us.us.us, %for.cond5.for.cond.cleanup8_crit_edge.us.us.us.us.us ]
  %invariant.gep.us.us.us.us.us = getelementptr i16, ptr %B, i32 %j.069.us.us.us.us.us
  br label %for.body9.us.us.us.us.us

for.body9.us.us.us.us.us:                         ; preds = %for.body9.us.us.us.us.us, %for.body4.us.us.us.us.us
  %s.067.us.us.us.us.us = phi i32 [ 0, %for.body4.us.us.us.us.us ], [ %inc.us.us.us.us.us, %for.body9.us.us.us.us.us ]
  %acc.066.us.us.us.us.us = phi i64 [ %conv, %for.body4.us.us.us.us.us ], [ %add17.us.us.us.us.us, %for.body9.us.us.us.us.us ]
  %arrayidx.us.us.us.us.us = getelementptr i16, ptr %5, i32 %s.067.us.us.us.us.us
  %7 = load i16, ptr %arrayidx.us.us.us.us.us, align 2, !tbaa !6
  %conv10.us.us.us.us.us = sext i16 %7 to i32
  %mul11.us.us.us.us.us = mul nuw nsw i32 %s.067.us.us.us.us.us, %k
  %gep.us.us.us.us.us = getelementptr i16, ptr %invariant.gep.us.us.us.us.us, i32 %mul11.us.us.us.us.us
  %8 = load i16, ptr %gep.us.us.us.us.us, align 2, !tbaa !6
  %conv14.us.us.us.us.us = sext i16 %8 to i32
  %mul15.us.us.us.us.us = mul nsw i32 %conv14.us.us.us.us.us, %conv10.us.us.us.us.us
  %conv16.us.us.us.us.us = sext i32 %mul15.us.us.us.us.us to i64
  %add17.us.us.us.us.us = add nsw i64 %acc.066.us.us.us.us.us, %conv16.us.us.us.us.us
  %inc.us.us.us.us.us = add nuw nsw i32 %s.067.us.us.us.us.us, 1
  %exitcond145.not = icmp eq i32 %inc.us.us.us.us.us, %n
  br i1 %exitcond145.not, label %for.cond5.for.cond.cleanup8_crit_edge.us.us.us.us.us, label %for.body9.us.us.us.us.us, !llvm.loop !10

for.cond5.for.cond.cleanup8_crit_edge.us.us.us.us.us: ; preds = %for.body9.us.us.us.us.us
  %shl.us.us.us.us.us = shl i64 %add17.us.us.us.us.us, %sh_prom
  %conv20.us.us.us.us.us = trunc i64 %shl.us.us.us.us.us to i16
  %arrayidx23.us.us.us.us.us = getelementptr i16, ptr %6, i32 %j.069.us.us.us.us.us
  store i16 %conv20.us.us.us.us.us, ptr %arrayidx23.us.us.us.us.us, align 2, !tbaa !6
  %inc32.us.us.us.us.us = add nuw nsw i32 %j.069.us.us.us.us.us, 1
  %exitcond146.not = icmp eq i32 %inc32.us.us.us.us.us, %k
  br i1 %exitcond146.not, label %for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us.us.us.us, label %for.body4.us.us.us.us.us, !llvm.loop !12

for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us.us.us.us: ; preds = %for.cond5.for.cond.cleanup8_crit_edge.us.us.us.us.us
  %inc35.us.us.us = add nuw nsw i32 %i.0101.us.us.us, 1
  %exitcond147.not = icmp eq i32 %inc35.us.us.us, %m
  br i1 %exitcond147.not, label %for.cond.cleanup, label %for.cond1.preheader.us.us.us, !llvm.loop !13

for.cond1.preheader.us.us:                        ; preds = %for.cond1.preheader.lr.ph.split.us.split.us, %for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us113.us
  %i.0101.us.us = phi i32 [ %inc35.us.us, %for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us113.us ], [ 0, %for.cond1.preheader.lr.ph.split.us.split.us ]
  %mul21.us.us = mul nuw nsw i32 %i.0101.us.us, %k
  %9 = getelementptr i16, ptr %C, i32 %mul21.us.us
  br label %for.body4.us.us108.us

for.body4.us.us108.us:                            ; preds = %for.cond1.preheader.us.us, %for.body4.us.us108.us
  %j.069.us.us109.us = phi i32 [ 0, %for.cond1.preheader.us.us ], [ %inc32.us.us111.us, %for.body4.us.us108.us ]
  %arrayidx23.us.us110.us = getelementptr i16, ptr %9, i32 %j.069.us.us109.us
  store i16 %conv20.us, ptr %arrayidx23.us.us110.us, align 2, !tbaa !6
  %inc32.us.us111.us = add nuw nsw i32 %j.069.us.us109.us, 1
  %exitcond143.not = icmp eq i32 %inc32.us.us111.us, %k
  br i1 %exitcond143.not, label %for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us113.us, label %for.body4.us.us108.us, !llvm.loop !12

for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us113.us: ; preds = %for.body4.us.us108.us
  %inc35.us.us = add nuw nsw i32 %i.0101.us.us, 1
  %exitcond144.not = icmp eq i32 %inc35.us.us, %m
  br i1 %exitcond144.not, label %for.cond.cleanup, label %for.cond1.preheader.us.us, !llvm.loop !13

for.cond1.preheader.lr.ph.split.us.split:         ; preds = %for.cond1.preheader.lr.ph.split.us
  br i1 %cmp665, label %for.cond1.preheader.lr.ph.split.us.split.split.us, label %for.cond1.preheader.lr.ph.split.us.split.split

for.cond1.preheader.lr.ph.split.us.split.split.us: ; preds = %for.cond1.preheader.lr.ph.split.us.split
  br i1 %cmp22, label %for.cond1.preheader.us.us119.us, label %for.cond1.preheader.us.us119

for.cond1.preheader.us.us119.us:                  ; preds = %for.cond1.preheader.lr.ph.split.us.split.split.us, %for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split.us.us
  %i.0101.us.us120.us = phi i32 [ %inc35.us.us122.us, %for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split.us.us ], [ 0, %for.cond1.preheader.lr.ph.split.us.split.split.us ]
  %mul.us.us121.us = mul nuw nsw i32 %i.0101.us.us120.us, %n
  %10 = getelementptr i16, ptr %A, i32 %mul.us.us121.us
  %11 = mul nuw nsw i32 %i.0101.us.us120.us, %k
  %12 = getelementptr i16, ptr %C, i32 %11
  br label %for.body4.us70.us.us.us.us

for.body4.us70.us.us.us.us:                       ; preds = %for.cond5.for.cond.cleanup8_crit_edge.us92.us.us.us.us, %for.cond1.preheader.us.us119.us
  %j.069.us71.us.us.us.us = phi i32 [ 0, %for.cond1.preheader.us.us119.us ], [ %inc32.us76.us.us.us.us, %for.cond5.for.cond.cleanup8_crit_edge.us92.us.us.us.us ]
  %invariant.gep.us72.us.us.us.us = getelementptr i16, ptr %B, i32 %j.069.us71.us.us.us.us
  br label %for.body9.us78.us.us.us.us

for.body9.us78.us.us.us.us:                       ; preds = %for.body9.us78.us.us.us.us, %for.body4.us70.us.us.us.us
  %s.067.us79.us.us.us.us = phi i32 [ 0, %for.body4.us70.us.us.us.us ], [ %inc.us89.us.us.us.us, %for.body9.us78.us.us.us.us ]
  %acc.066.us80.us.us.us.us = phi i64 [ %conv, %for.body4.us70.us.us.us.us ], [ %add17.us88.us.us.us.us, %for.body9.us78.us.us.us.us ]
  %arrayidx.us81.us.us.us.us = getelementptr i16, ptr %10, i32 %s.067.us79.us.us.us.us
  %13 = load i16, ptr %arrayidx.us81.us.us.us.us, align 2, !tbaa !6
  %conv10.us82.us.us.us.us = sext i16 %13 to i32
  %mul11.us83.us.us.us.us = mul nuw nsw i32 %s.067.us79.us.us.us.us, %k
  %gep.us84.us.us.us.us = getelementptr i16, ptr %invariant.gep.us72.us.us.us.us, i32 %mul11.us83.us.us.us.us
  %14 = load i16, ptr %gep.us84.us.us.us.us, align 2, !tbaa !6
  %conv14.us85.us.us.us.us = sext i16 %14 to i32
  %mul15.us86.us.us.us.us = mul nsw i32 %conv14.us85.us.us.us.us, %conv10.us82.us.us.us.us
  %conv16.us87.us.us.us.us = sext i32 %mul15.us86.us.us.us.us to i64
  %add17.us88.us.us.us.us = add nsw i64 %acc.066.us80.us.us.us.us, %conv16.us87.us.us.us.us
  %inc.us89.us.us.us.us = add nuw nsw i32 %s.067.us79.us.us.us.us, 1
  %exitcond140.not = icmp eq i32 %inc.us89.us.us.us.us, %n
  br i1 %exitcond140.not, label %for.cond5.for.cond.cleanup8_crit_edge.us92.us.us.us.us, label %for.body9.us78.us.us.us.us, !llvm.loop !10

for.cond5.for.cond.cleanup8_crit_edge.us92.us.us.us.us: ; preds = %for.body9.us78.us.us.us.us
  %15 = ashr i64 %add17.us88.us.us.us.us, %2
  %16 = trunc i64 %15 to i16
  %17 = getelementptr i16, ptr %12, i32 %j.069.us71.us.us.us.us
  store i16 %16, ptr %17, align 2, !tbaa !6
  %inc32.us76.us.us.us.us = add nuw nsw i32 %j.069.us71.us.us.us.us, 1
  %exitcond141.not = icmp eq i32 %inc32.us76.us.us.us.us, %k
  br i1 %exitcond141.not, label %for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split.us.us, label %for.body4.us70.us.us.us.us, !llvm.loop !12

for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split.us.us: ; preds = %for.cond5.for.cond.cleanup8_crit_edge.us92.us.us.us.us
  %inc35.us.us122.us = add nuw nsw i32 %i.0101.us.us120.us, 1
  %exitcond142.not = icmp eq i32 %inc35.us.us122.us, %m
  br i1 %exitcond142.not, label %for.cond.cleanup, label %for.cond1.preheader.us.us119.us, !llvm.loop !13

for.cond1.preheader.us.us119:                     ; preds = %for.cond1.preheader.lr.ph.split.us.split.split.us, %for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split
  %i.0101.us.us120 = phi i32 [ %inc35.us.us122, %for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split ], [ 0, %for.cond1.preheader.lr.ph.split.us.split.split.us ]
  %mul.us.us121 = mul nuw nsw i32 %i.0101.us.us120, %n
  %18 = getelementptr i16, ptr %A, i32 %mul.us.us121
  %19 = mul nuw nsw i32 %i.0101.us.us120, %k
  %20 = getelementptr i16, ptr %C, i32 %19
  br label %for.body4.us70.us.us

for.body4.us70.us.us:                             ; preds = %for.cond5.for.cond.cleanup8_crit_edge.us92.us.us, %for.cond1.preheader.us.us119
  %j.069.us71.us.us = phi i32 [ 0, %for.cond1.preheader.us.us119 ], [ %inc32.us76.us.us, %for.cond5.for.cond.cleanup8_crit_edge.us92.us.us ]
  %invariant.gep.us72.us.us = getelementptr i16, ptr %B, i32 %j.069.us71.us.us
  br label %for.body9.us78.us.us

for.body9.us78.us.us:                             ; preds = %for.body9.us78.us.us, %for.body4.us70.us.us
  %s.067.us79.us.us = phi i32 [ 0, %for.body4.us70.us.us ], [ %inc.us89.us.us, %for.body9.us78.us.us ]
  %acc.066.us80.us.us = phi i64 [ %conv, %for.body4.us70.us.us ], [ %add17.us88.us.us, %for.body9.us78.us.us ]
  %arrayidx.us81.us.us = getelementptr i16, ptr %18, i32 %s.067.us79.us.us
  %21 = load i16, ptr %arrayidx.us81.us.us, align 2, !tbaa !6
  %conv10.us82.us.us = sext i16 %21 to i32
  %mul11.us83.us.us = mul nuw nsw i32 %s.067.us79.us.us, %k
  %gep.us84.us.us = getelementptr i16, ptr %invariant.gep.us72.us.us, i32 %mul11.us83.us.us
  %22 = load i16, ptr %gep.us84.us.us, align 2, !tbaa !6
  %conv14.us85.us.us = sext i16 %22 to i32
  %mul15.us86.us.us = mul nsw i32 %conv14.us85.us.us, %conv10.us82.us.us
  %conv16.us87.us.us = sext i32 %mul15.us86.us.us to i64
  %add17.us88.us.us = add nsw i64 %acc.066.us80.us.us, %conv16.us87.us.us
  %inc.us89.us.us = add nuw nsw i32 %s.067.us79.us.us, 1
  %exitcond137.not = icmp eq i32 %inc.us89.us.us, %n
  br i1 %exitcond137.not, label %for.cond5.for.cond.cleanup8_crit_edge.us92.us.us, label %for.body9.us78.us.us, !llvm.loop !10

for.cond5.for.cond.cleanup8_crit_edge.us92.us.us: ; preds = %for.body9.us78.us.us
  %23 = ashr i64 %add17.us88.us.us, %2
  %24 = trunc i64 %23 to i16
  %25 = getelementptr i16, ptr %20, i32 %j.069.us71.us.us
  store i16 %24, ptr %25, align 2, !tbaa !6
  %inc32.us76.us.us = add nuw nsw i32 %j.069.us71.us.us, 1
  %exitcond138.not = icmp eq i32 %inc32.us76.us.us, %k
  br i1 %exitcond138.not, label %for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split, label %for.body4.us70.us.us, !llvm.loop !12

for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split: ; preds = %for.cond5.for.cond.cleanup8_crit_edge.us92.us.us
  %inc35.us.us122 = add nuw nsw i32 %i.0101.us.us120, 1
  %exitcond139.not = icmp eq i32 %inc35.us.us122, %m
  br i1 %exitcond139.not, label %for.cond.cleanup, label %for.cond1.preheader.us.us119, !llvm.loop !13

for.cond1.preheader.lr.ph.split.us.split.split:   ; preds = %for.cond1.preheader.lr.ph.split.us.split
  br i1 %cmp22, label %for.cond1.preheader.us.us124, label %for.cond1.preheader.us

for.cond1.preheader.us.us124:                     ; preds = %for.cond1.preheader.lr.ph.split.us.split.split, %for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us.us.us
  %i.0101.us.us125 = phi i32 [ %inc35.us.us126, %for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us.us.us ], [ 0, %for.cond1.preheader.lr.ph.split.us.split.split ]
  %26 = mul nuw nsw i32 %i.0101.us.us125, %k
  %27 = getelementptr i16, ptr %C, i32 %26
  br label %for.body4.us94.us.us

for.body4.us94.us.us:                             ; preds = %for.body4.us94.us.us, %for.cond1.preheader.us.us124
  %j.069.us95.us.us = phi i32 [ 0, %for.cond1.preheader.us.us124 ], [ %inc32.us98.us.us, %for.body4.us94.us.us ]
  %28 = getelementptr i16, ptr %27, i32 %j.069.us95.us.us
  store i16 %4, ptr %28, align 2, !tbaa !6
  %inc32.us98.us.us = add nuw nsw i32 %j.069.us95.us.us, 1
  %exitcond135.not = icmp eq i32 %inc32.us98.us.us, %k
  br i1 %exitcond135.not, label %for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us.us.us, label %for.body4.us94.us.us, !llvm.loop !12

for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us.us.us: ; preds = %for.body4.us94.us.us
  %inc35.us.us126 = add nuw nsw i32 %i.0101.us.us125, 1
  %exitcond136.not = icmp eq i32 %inc35.us.us126, %m
  br i1 %exitcond136.not, label %for.cond.cleanup, label %for.cond1.preheader.us.us124, !llvm.loop !13

for.cond1.preheader.us:                           ; preds = %for.cond1.preheader.lr.ph.split.us.split.split, %for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us106
  %i.0101.us = phi i32 [ %inc35.us, %for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us106 ], [ 0, %for.cond1.preheader.lr.ph.split.us.split.split ]
  %29 = mul nuw nsw i32 %i.0101.us, %k
  %30 = getelementptr i16, ptr %C, i32 %29
  br label %for.body4.us102

for.body4.us102:                                  ; preds = %for.cond1.preheader.us, %for.body4.us102
  %j.069.us103 = phi i32 [ 0, %for.cond1.preheader.us ], [ %inc32.us104, %for.body4.us102 ]
  %31 = getelementptr i16, ptr %30, i32 %j.069.us103
  store i16 %4, ptr %31, align 2, !tbaa !6
  %inc32.us104 = add nuw nsw i32 %j.069.us103, 1
  %exitcond.not = icmp eq i32 %inc32.us104, %k
  br i1 %exitcond.not, label %for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us106, label %for.body4.us102, !llvm.loop !12

for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us106: ; preds = %for.body4.us102
  %inc35.us = add nuw nsw i32 %i.0101.us, 1
  %exitcond134.not = icmp eq i32 %inc35.us, %m
  br i1 %exitcond134.not, label %for.cond.cleanup, label %for.cond1.preheader.us, !llvm.loop !13

for.cond.cleanup:                                 ; preds = %for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us106, %for.cond1.for.cond.cleanup3_crit_edge.split.split.split.us.us.us, %for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split, %for.cond1.for.cond.cleanup3_crit_edge.split.split.us.us.us.split.us.us, %for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us113.us, %for.cond1.for.cond.cleanup3_crit_edge.split.us.split.us.us.us.us, %for.cond1.preheader.lr.ph, %entry
  ret i32 0
}

attributes #0 = { nofree norecurse nosync nounwind memory(argmem: readwrite) "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic-rv32" "target-features"="+32bit,+a,+c,+f,+m,+relax,+xesppie,+zaamo,+zalrsc,+zicsr,+zifencei,+zmmul,-b,-d,-e,-experimental-sdext,-experimental-sdtrig,-experimental-smctr,-experimental-ssctr,-experimental-svukte,-experimental-xqcia,-experimental-xqciac,-experimental-xqcicli,-experimental-xqcicm,-experimental-xqcics,-experimental-xqcicsr,-experimental-xqciint,-experimental-xqcilo,-experimental-xqcilsm,-experimental-xqcisls,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvkgs,-h,-sha,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smdbltrp,-smepmp,-smmpm,-smnpm,-smrnmi,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssdbltrp,-ssnpm,-sspm,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-supm,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-svvptc,-v,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xmipscmove,-xmipslsp,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zabha,-zacas,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }

!llvm.module.flags = !{!0, !1, !2, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"ilp32f"}
!2 = !{i32 6, !"riscv-isa", !3}
!3 = !{!"rv32i2p1_m2p0_a2p1_f2p2_c2p0_zicsr2p0_zifencei2p0_zmmul1p0_zaamo1p0_zalrsc1p0_xesppie1p0"}
!4 = !{i32 8, !"SmallDataLimit", i32 0}
!5 = !{!"Espressif clang version 17.0.1 (https://gitlab.espressif.cn:6688/idf/llvm-project.git llvmorg-19.1.2-277-gbe3198f esp-18.1.2_20240912-657-ge1dc1cc esp-18.1.2_20240912-657-ge1dc1cc esp-18.1.2_20240912-685-g8c39bf5 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 esp-18.1.2_20240912-694-g4a14fa0 esp-18.1.2_20240912-694-g4a14fa0 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-282-gf0df22b llvmorg-19.1.2-282-g61f783f llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-289-g6ab7981 llvmorg-19.1.2-294-ga687ee8 llvmorg-19.1.2-282-gded6180 llvmorg-19.1.2-295-gd6b9c67 llvmorg-19.1.2-296-g2bb38d3 llvmorg-19.1.2-302-gb46e43e llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-ga193982 llvmorg-19.1.2-310-g012c995 llvmorg-19.1.2-373-g483ac18 llvmorg-19.1.2-373-g483ac18 llvmorg-19.1.2-373-g483ac18 esp-19.1.2_20250225-2-g2444a40 esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g5a99af4 esp-19.1.2_20250225-2-g5a99af4 esp-19.1.2_20250225-4-g6ad288c esp-19.1.2_20250225-2-g78646ff esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312-1-gbfbef3f esp-19.1.2_20250225-3-g153f4c7 esp-19.1.2_20250312-2-gf1328c0 esp-19.1.2_20250312-1-ga44194f esp-19.1.2_20250312-2-g6ad288c esp-19.1.2_20250225-5-gabba736 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-1-ge8e26d4 esp-19.1.2_20250225-6-g1102ab9 esp-19.1.2_20250312-1-ga44194f esp-19.1.2_20250312-1-gfaf5f34 esp-19.1.2_20250312-2-g912da7e esp-19.1.2_20250312-12-g40fcb86 esp-19.1.2_20250312-22-g150517d esp-19.1.2_20250312-36-g3725281 esp-19.1.2_20250312-36-g3725281 esp-19.1.2_20250312-37-gd7ad151 esp-19.1.2_20250312-43-g1fdfc46 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250312-67-g1b9c1af esp-19.1.2_20250312-67-g1b9c1af esp-19.1.2_20250312-2-g590a30f esp-19.1.2_20250312-2-g590a30f esp-19.1.2_20250312-68-g65bae88 esp-19.1.2_20250312-68-g65bae88 llvmorg-19.1.2-286-g58c0b0a esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-2-gaccea5b esp-19.1.2_20250312-79-g85b8bac esp-19.1.2_20250312-1-g5bd87a5 esp-19.1.2_20250312-2-g398f0e9 esp-19.1.2_20250312-2-gfa1159a esp-19.1.2_20250312 esp-19.1.2_20250312-1-g190f2f0 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312-1-gdb3618a esp-19.1.2_20250312-5-g53503ec esp-19.1.2_20250312-14-gbd1030c esp-19.1.2_20250312-14-gbd1030c esp-19.1.2_20250312-94-ga50fb83 esp-19.1.2_20250312-21-g2d4e527 esp-19.1.2_20250312-22-gd828f8c esp-19.1.2_20250312-25-ga0db53c esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-50-g36efec3 esp-19.1.2_20250312-49-g66c7bd3 esp-19.1.2_20250312-68-gef601b8 esp-19.1.2_20250312-84-g3338f1a esp-19.1.2_20250225-105-gfa4c43d esp-19.1.2_20250312-99-gcad4d17 esp-19.1.2_20250312-2-g7c53768 esp-19.1.2_20250312-2-g7c53768 esp-19.1.2_20250312-3-g77450217 esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-7-ge58b5b9 esp-19.1.2_20250312-7-ge58b5b9 esp-19.1.2_20250312-9-gf8d929c esp-19.1.2_20250312-9-gf8d929c esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-14-gcc23a57 esp-19.1.2_20250312-15-gb030eec esp-19.1.2_20250312-16-g5e690f7 esp-19.1.2_20250312-18-g64518b8 esp-19.1.2_20250312-19-gf837620 esp-19.1.2_20250312-30-gce11723 esp-19.1.2_20250312-36-gc4a4385 esp-19.1.2_20250312-45-gb1f78a1 esp-19.1.2_20250312-45-gb1f78a1 llvmorg-20.1.1-294-g54395c3 esp-19.1.2_20250312-54-gdd06c183 llvmorg-20.1.1-295-g4acb682 esp-19.1.2_20250312-55-g38d03d5 esp-19.1.2_20250312-57-g94f4e0b esp-19.1.2_20250312-58-gefb38fa esp-19.1.2_20250312-58-gefb38fa esp-19.1.2_20250312-59-g65810cd esp-19.1.2_20250312-68-g8571eac esp-19.1.2_20250312-3-g77450217 esp-19.1.2_20250312-77-g1941a49 esp-19.1.2_20250225-2-g5384b3c esp-19.1.2_20250312-80-g25b2378 llvmorg-20.1.1-292-gd2afeba llvmorg-20.1.1-292-g50b226d llvmorg-20.1.1-292-g50b226d esp-19.1.2_20250312-3-geb75cb5 llvmorg-20.1.1-290-gcc1c2fc llvmorg-20.1.1-290-gcc1c2fc llvmorg-20.1.1-290-gcc1c2fc llvmorg-20.1.1-292-g50b226d llvmorg-20.1.1-290-gcc1c2fc llvmorg-20.1.1-290-g64a73de llvmorg-20.1.1-290-gae1fe28 llvmorg-20.1.1-290-gae1fe28 esp-19.1.2_20250312-3-geb75cb5 llvmorg-20.1.1-290-g78197bd llvmorg-20.1.1-290-g8cf4429 llvmorg-20.1.1-290-g404545a esp-19.1.2_20250312-80-g25b2378 llvmorg-20.1.1-292-ga09200d llvmorg-20.1.1-290-g56858ea llvmorg-20.1.1-290-g56858ea llvmorg-20.1.1-290-g56858ea llvmorg-20.1.1-294-g417d26e llvmorg-20.1.1-290-gfaa84cc llvmorg-20.1.1-290-g9f9302d llvmorg-20.1.1-294-g9f00800 esp-19.1.2_20250312-81-g6c8bfdc esp-19.1.2_20250312-81-g6c8bfdc esp-19.1.2_20250312-81-g6c8bfdc esp-19.1.2_20250312-81-g6c8bfdc esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 llvmorg-20.1.1-294-g9f00800 llvmorg-20.1.1-294-g9f00800 esp-19.1.2_20250312-83-gfb339b7 llvmorg-20.1.1-297-ge0e1152 esp-19.1.2_20250312-83-gfb339b7 esp-19.1.2_20250312-90-ga331fb4 esp-19.1.2_20250312-62-gd04b8d6 esp-19.1.2_20250312-106-g747850b esp-19.1.2_20250312-62-gd04b8d6 esp-19.1.2_20250312-106-g747850b esp-19.1.2_20250312-62-gd04b8d6 esp-19.1.2_20250312-106-g747850b esp-19.1.2_20250312-106-g747850b esp-19.1.2_20250312-106-g747850b esp-19.1.2_20250312-115-g596469c llvmorg-20.1.1-300-g8a2d605 llvmorg-20.1.1-300-g8a2d605 llvmorg-20.1.1-300-g8a2d605 llvmorg-20.1.1-300-g8a2d605 llvmorg-20.1.1-300-g8a2d605 llvmorg-20.1.1-300-g8a2d605 llvmorg-20.1.1-300-g8a2d605 llvmorg-20.1.1-298-g5df1c75 esp-20.1.1_20250812-39-g8fd161b esp-19.1.2_20250225-2-g761bb45 esp-20.1.1_20250812-2-g8a2d605 esp-20.1.1_20250812-5-g9908fc01 esp-20.1.1_20250812-47-g5173103 esp-20.1.1_20250812-66-g5a643bf esp-20.1.1_20250812-86-g3edfaae llvmorg-19.1.2-281-gc84ed4e esp-19.1.2_20250312-127-g3407862 esp-19.1.2_20250225-2-g5384b3c esp-20.1.1_20250829-142-gfcec0eb esp-20.1.1_20250829-142-gfcec0eb esp-20.1.1_20250829-143-g1b5ddf3 esp-20.1.1_20250812-112-gba39f00 esp-20.1.1_20250829-143-g1b5ddf3)"}
!6 = !{!7, !7, i64 0}
!7 = !{!"short", !8, i64 0}
!8 = !{!"omnipotent char", !9, i64 0}
!9 = !{!"Simple C/C++ TBAA"}
!10 = distinct !{!10, !11}
!11 = !{!"llvm.loop.mustprogress"}
!12 = distinct !{!12, !11}
!13 = distinct !{!13, !11}
;.
; CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; CHECK: [[META7]] = !{!"short", [[META8:![0-9]+]], i64 0}
; CHECK: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; CHECK: [[META9]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]]}
; CHECK: [[META11]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[LOOP12]] = distinct !{[[LOOP12]], [[META11]]}
; CHECK: [[LOOP13]] = distinct !{[[LOOP13]], [[META11]]}
;.
