; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32p4-loop-versioning -riscv-esp32p4-loop-versioning=true < %s | FileCheck %s


; Function Attrs: nofree norecurse nosync nounwind memory(readwrite, inaccessiblemem: none)
define dso_local noundef i32 @dsps_fird_s16_ansi(ptr nocapture noundef %fir, ptr nocapture noundef readonly %input, ptr nocapture noundef writeonly %output, i32 noundef %len) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local noundef i32 @dsps_fird_s16_ansi(
; CHECK-SAME: ptr noundef captures(none) [[FIR:%.*]], ptr noundef readonly captures(none) [[INPUT:%.*]], ptr noundef writeonly captures(none) [[OUTPUT:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SHIFT:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 16
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[SHIFT]], align 4, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP0]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[CONV]], -15
; CHECK-NEXT:    [[ROUNDING_VAL:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 24
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ROUNDING_VAL]], align 4, !tbaa [[TBAA13:![0-9]+]]
; CHECK-NEXT:    [[CONV1:%.*]] = sext i32 [[TMP1]] to i64
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i16 [[TMP0]], -1
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[CONV]] to i64
; CHECK-NEXT:    [[SHR:%.*]] = ashr i64 [[CONV1]], [[SH_PROM]]
; CHECK-NEXT:    br label %[[IF_END:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[SUB9:%.*]] = sub nsw i32 0, [[CONV]]
; CHECK-NEXT:    [[SH_PROM10:%.*]] = zext nneg i32 [[SUB9]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl i64 [[CONV1]], [[SH_PROM10]]
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[ROUNDING_0_IN:%.*]] = phi i64 [ [[SHR]], %[[IF_THEN]] ], [ [[SHL]], %[[IF_ELSE]] ]
; CHECK-NEXT:    [[ROUNDING_0:%.*]] = and i64 [[ROUNDING_0_IN]], 1099511627775
; CHECK-NEXT:    [[CMP12153:%.*]] = icmp sgt i32 [[LEN]], 0
; CHECK-NEXT:    br i1 [[CMP12153]], label %[[FIR_RUNTIME_CHECK:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FIR_RUNTIME_CHECK]]:
; CHECK-NEXT:    [[DECIM:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 12
; CHECK-NEXT:    [[D_POS:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 14
; CHECK-NEXT:    [[POS:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 10
; CHECK-NEXT:    [[COEFFS_LEN:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 8
; CHECK-NEXT:    [[DELAY:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 4
; CHECK-NEXT:    [[CMP79:%.*]] = icmp sgt i16 [[TMP0]], 15
; CHECK-NEXT:    [[SUB88:%.*]] = sub nsw i32 15, [[CONV]]
; CHECK-NEXT:    [[SH_PROM89:%.*]] = zext nneg i32 [[SUB88]] to i64
; CHECK-NEXT:    [[SH_PROM82:%.*]] = zext nneg i32 [[SUB]] to i64
; CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[DECIM]], align 4, !tbaa [[TBAA14:![0-9]+]]
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DELAY]], align 4, !tbaa [[TBAA15:![0-9]+]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[COEFFS_LEN]], align 4, !tbaa [[TBAA16:![0-9]+]]
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[FIR]], align 4, !tbaa [[TBAA17:![0-9]+]]
; CHECK-NEXT:    [[IS_FAST_PATH:%.*]] = icmp slt i16 [[TMP0]], 15
; CHECK-NEXT:    br i1 [[IS_FAST_PATH]], label %[[FOR_COND14_PREHEADER_FAST_PH:.*]], label %[[FOR_COND14_PREHEADER_SLOW_PH:.*]]
; CHECK:       [[FOR_COND14_PREHEADER_FAST_PH]]:
; CHECK-NEXT:    br label %[[FOR_COND14_PREHEADER_FAST:.*]]
; CHECK:       [[FOR_COND14_PREHEADER_FAST]]:
; CHECK-NEXT:    [[I_0156_FAST:%.*]] = phi i32 [ 0, %[[FOR_COND14_PREHEADER_FAST_PH]] ], [ [[INC96_FAST:%.*]], %[[FOR_COND_CLEANUP63_FAST:.*]] ]
; CHECK-NEXT:    [[INPUT_POS_0154_FAST:%.*]] = phi i32 [ 0, %[[FOR_COND14_PREHEADER_FAST_PH]] ], [ [[INPUT_POS_1_LCSSA_FAST:%.*]], %[[FOR_COND_CLEANUP63_FAST]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[D_POS]], align 2, !tbaa [[TBAA18:![0-9]+]]
; CHECK-NEXT:    [[CMP18138_FAST:%.*]] = icmp sgt i16 [[TMP2]], [[TMP6]]
; CHECK-NEXT:    br i1 [[CMP18138_FAST]], label %[[FOR_BODY21_LR_PH_FAST:.*]], label %[[FOR_COND_CLEANUP20_FAST:.*]]
; CHECK:       [[FOR_BODY21_LR_PH_FAST]]:
; CHECK-NEXT:    br label %[[FOR_BODY21_FAST:.*]]
; CHECK:       [[FOR_BODY21_FAST]]:
; CHECK-NEXT:    [[J_0140_FAST:%.*]] = phi i32 [ 0, %[[FOR_BODY21_LR_PH_FAST]] ], [ [[INC32_FAST:%.*]], %[[IF_END28_FAST:.*]] ]
; CHECK-NEXT:    [[INPUT_POS_1139_FAST:%.*]] = phi i32 [ [[INPUT_POS_0154_FAST]], %[[FOR_BODY21_LR_PH_FAST]] ], [ [[INC_FAST:%.*]], %[[IF_END28_FAST]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr [[POS]], align 2, !tbaa [[TBAA19:![0-9]+]]
; CHECK-NEXT:    [[DOTDEC:%.*]] = sub i16 [[TMP7]], 1
; CHECK-NEXT:    [[DOTDEC_IS_NEG:%.*]] = icmp slt i16 [[DOTDEC]], 0
; CHECK-NEXT:    [[DOTMINUS_1:%.*]] = sub i16 [[TMP4]], 1
; CHECK-NEXT:    [[DOTNEW:%.*]] = select i1 [[DOTDEC_IS_NEG]], i16 [[DOTMINUS_1]], i16 [[DOTDEC]]
; CHECK-NEXT:    [[CMP24_NOT_FAST:%.*]] = icmp slt i16 [[TMP7]], [[TMP4]]
; CHECK-NEXT:    br label %[[IF_END28_FAST]]
; CHECK:       [[IF_END28_FAST]]:
; CHECK-NEXT:    [[INC_FAST]] = add nsw i32 [[INPUT_POS_1139_FAST]], 1
; CHECK-NEXT:    [[ARRAYIDX_FAST:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[INPUT_POS_1139_FAST]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[ARRAYIDX_FAST]], align 2, !tbaa [[TBAA20:![0-9]+]]
; CHECK-NEXT:    store i16 [[DOTNEW]], ptr [[POS]], align 2
; CHECK-NEXT:    [[IDXPROM_FAST:%.*]] = sext i16 [[DOTNEW]] to i32
; CHECK-NEXT:    [[ARRAYIDX31_FAST:%.*]] = getelementptr inbounds i16, ptr [[TMP3]], i32 [[IDXPROM_FAST]]
; CHECK-NEXT:    store i16 [[TMP8]], ptr [[ARRAYIDX31_FAST]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[INC32_FAST]] = add nuw nsw i32 [[J_0140_FAST]], 1
; CHECK-NEXT:    [[CONV15_FAST:%.*]] = sext i16 [[TMP2]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = load i16, ptr [[D_POS]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[CONV16_FAST:%.*]] = sext i16 [[TMP9]] to i32
; CHECK-NEXT:    [[SUB17_FAST:%.*]] = sub nsw i32 [[CONV15_FAST]], [[CONV16_FAST]]
; CHECK-NEXT:    [[CMP18_FAST:%.*]] = icmp slt i32 [[INC32_FAST]], [[SUB17_FAST]]
; CHECK-NEXT:    br i1 [[CMP18_FAST]], label %[[FOR_BODY21_FAST]], label %[[FOR_COND_CLEANUP20_FAST]], !llvm.loop [[LOOP21:![0-9]+]]
; CHECK:       [[FOR_COND_CLEANUP20_FAST]]:
; CHECK-NEXT:    [[INPUT_POS_1_LCSSA_FAST]] = phi i32 [ [[INPUT_POS_0154_FAST]], %[[FOR_COND14_PREHEADER_FAST]] ], [ [[INC_FAST]], %[[IF_END28_FAST]] ]
; CHECK-NEXT:    store i16 0, ptr [[D_POS]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[POS]], align 2, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[CONV39_FAST:%.*]] = sext i16 [[TMP10]] to i32
; CHECK-NEXT:    [[CONV42_FAST:%.*]] = sext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[CMP43142_FAST:%.*]] = icmp slt i16 [[TMP10]], [[TMP4]]
; CHECK-NEXT:    br i1 [[CMP43142_FAST]], label %[[FOR_BODY46_LR_PH_FAST:.*]], label %[[FOR_COND58_PREHEADER_FAST:.*]]
; CHECK:       [[FOR_BODY46_LR_PH_FAST]]:
; CHECK-NEXT:    br label %[[FOR_BODY46_FAST:.*]]
; CHECK:       [[FOR_BODY46_FAST]]:
; CHECK-NEXT:    [[COEFF_POS_0145_FAST:%.*]] = phi i16 [ 0, %[[FOR_BODY46_LR_PH_FAST]] ], [ [[COEFF_POS_INC:%.*]], %[[FOR_BODY46_FAST]] ]
; CHECK-NEXT:    [[N_0144_FAST:%.*]] = phi i32 [ [[CONV39_FAST]], %[[FOR_BODY46_LR_PH_FAST]] ], [ [[INC55_FAST:%.*]], %[[FOR_BODY46_FAST]] ]
; CHECK-NEXT:    [[ACC_0143_FAST:%.*]] = phi i64 [ [[ROUNDING_0]], %[[FOR_BODY46_LR_PH_FAST]] ], [ [[ADD_FAST:%.*]], %[[FOR_BODY46_FAST]] ]
; CHECK-NEXT:    [[IDXPROM47_FAST:%.*]] = sext i16 [[COEFF_POS_0145_FAST]] to i32
; CHECK-NEXT:    [[ARRAYIDX48_FAST:%.*]] = getelementptr inbounds i16, ptr [[TMP5]], i32 [[IDXPROM47_FAST]]
; CHECK-NEXT:    [[TMP11:%.*]] = load i16, ptr [[ARRAYIDX48_FAST]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV49_FAST:%.*]] = sext i16 [[TMP11]] to i32
; CHECK-NEXT:    [[ARRAYIDX51_FAST:%.*]] = getelementptr inbounds i16, ptr [[TMP3]], i32 [[N_0144_FAST]]
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[ARRAYIDX51_FAST]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV52_FAST:%.*]] = sext i16 [[TMP12]] to i32
; CHECK-NEXT:    [[MUL_FAST:%.*]] = mul nsw i32 [[CONV52_FAST]], [[CONV49_FAST]]
; CHECK-NEXT:    [[CONV53_FAST:%.*]] = sext i32 [[MUL_FAST]] to i64
; CHECK-NEXT:    [[ADD_FAST]] = add nsw i64 [[ACC_0143_FAST]], [[CONV53_FAST]]
; CHECK-NEXT:    [[INC55_FAST]] = add nsw i32 [[N_0144_FAST]], 1
; CHECK-NEXT:    [[COEFF_POS_INC]] = add i16 [[COEFF_POS_0145_FAST]], 1
; CHECK-NEXT:    [[EXITCOND_NOT_FAST:%.*]] = icmp eq i32 [[INC55_FAST]], [[CONV42_FAST]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT_FAST]], label %[[FOR_COND58_PREHEADER_LOOPEXIT_FAST:.*]], label %[[FOR_BODY46_FAST]], !llvm.loop [[LOOP23:![0-9]+]]
; CHECK:       [[FOR_COND58_PREHEADER_LOOPEXIT_FAST]]:
; CHECK-NEXT:    [[ADD_FAST_LCSSA:%.*]] = phi i64 [ [[ADD_FAST]], %[[FOR_BODY46_FAST]] ]
; CHECK-NEXT:    [[COEFF_POS_LCSSA_PARTIAL_FAST:%.*]] = phi i16 [ [[COEFF_POS_INC]], %[[FOR_BODY46_FAST]] ]
; CHECK-NEXT:    br label %[[FOR_COND58_PREHEADER_FAST]]
; CHECK:       [[FOR_COND58_PREHEADER_FAST]]:
; CHECK-NEXT:    [[ACC_0_LCSSA_FAST:%.*]] = phi i64 [ [[ROUNDING_0]], %[[FOR_COND_CLEANUP20_FAST]] ], [ [[ADD_FAST_LCSSA]], %[[FOR_COND58_PREHEADER_LOOPEXIT_FAST]] ]
; CHECK-NEXT:    [[COEFF_POS_0_LCSSA_FAST:%.*]] = phi i16 [ 0, %[[FOR_COND_CLEANUP20_FAST]] ], [ [[COEFF_POS_LCSSA_PARTIAL_FAST]], %[[FOR_COND58_PREHEADER_LOOPEXIT_FAST]] ]
; CHECK-NEXT:    [[CMP61148_FAST:%.*]] = icmp sgt i16 [[TMP10]], 0
; CHECK-NEXT:    br i1 [[CMP61148_FAST]], label %[[FOR_BODY64_LR_PH_FAST:.*]], label %[[FOR_COND_CLEANUP63_FAST]]
; CHECK:       [[FOR_BODY64_LR_PH_FAST]]:
; CHECK-NEXT:    br label %[[FOR_BODY64_FAST:.*]]
; CHECK:       [[FOR_BODY64_FAST]]:
; CHECK-NEXT:    [[N57_0151_FAST:%.*]] = phi i32 [ 0, %[[FOR_BODY64_LR_PH_FAST]] ], [ [[INC77_FAST:%.*]], %[[FOR_BODY64_FAST]] ]
; CHECK-NEXT:    [[COEFF_POS_1150_FAST:%.*]] = phi i16 [ [[COEFF_POS_0_LCSSA_FAST]], %[[FOR_BODY64_LR_PH_FAST]] ], [ [[COEFF_POS_INC1:%.*]], %[[FOR_BODY64_FAST]] ]
; CHECK-NEXT:    [[ACC_1149_FAST:%.*]] = phi i64 [ [[ACC_0_LCSSA_FAST]], %[[FOR_BODY64_LR_PH_FAST]] ], [ [[ADD75_FAST:%.*]], %[[FOR_BODY64_FAST]] ]
; CHECK-NEXT:    [[COEFF_POS_INC1]] = add i16 [[COEFF_POS_1150_FAST]], 1
; CHECK-NEXT:    [[IDXPROM67_FAST:%.*]] = sext i16 [[COEFF_POS_1150_FAST]] to i32
; CHECK-NEXT:    [[ARRAYIDX68_FAST:%.*]] = getelementptr inbounds i16, ptr [[TMP5]], i32 [[IDXPROM67_FAST]]
; CHECK-NEXT:    [[TMP13:%.*]] = load i16, ptr [[ARRAYIDX68_FAST]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV69_FAST:%.*]] = sext i16 [[TMP13]] to i32
; CHECK-NEXT:    [[ARRAYIDX71_FAST:%.*]] = getelementptr inbounds i16, ptr [[TMP3]], i32 [[N57_0151_FAST]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i16, ptr [[ARRAYIDX71_FAST]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV72_FAST:%.*]] = sext i16 [[TMP14]] to i32
; CHECK-NEXT:    [[MUL73_FAST:%.*]] = mul nsw i32 [[CONV72_FAST]], [[CONV69_FAST]]
; CHECK-NEXT:    [[CONV74_FAST:%.*]] = sext i32 [[MUL73_FAST]] to i64
; CHECK-NEXT:    [[ADD75_FAST]] = add nsw i64 [[ACC_1149_FAST]], [[CONV74_FAST]]
; CHECK-NEXT:    [[INC77_FAST]] = add nuw nsw i32 [[N57_0151_FAST]], 1
; CHECK-NEXT:    [[EXITCOND159_NOT_FAST:%.*]] = icmp eq i32 [[INC77_FAST]], [[CONV39_FAST]]
; CHECK-NEXT:    br i1 [[EXITCOND159_NOT_FAST]], label %[[FOR_COND_CLEANUP63_FAST]], label %[[FOR_BODY64_FAST]], !llvm.loop [[LOOP24:![0-9]+]]
; CHECK:       [[FOR_COND_CLEANUP63_FAST]]:
; CHECK-NEXT:    [[ACC_1_LCSSA_FAST:%.*]] = phi i64 [ [[ACC_0_LCSSA_FAST]], %[[FOR_COND58_PREHEADER_FAST]] ], [ [[ADD75_FAST]], %[[FOR_BODY64_FAST]] ]
; CHECK-NEXT:    [[SHR90_FAST:%.*]] = ashr i64 [[ACC_1_LCSSA_FAST]], [[SH_PROM89]]
; CHECK-NEXT:    [[FAST_SHIFT_AMT:%.*]] = sub i16 15, [[TMP0]]
; CHECK-NEXT:    [[TMP15:%.*]] = sext i16 [[FAST_SHIFT_AMT]] to i64
; CHECK-NEXT:    [[FAST_ASHR:%.*]] = ashr i64 [[ACC_1_LCSSA_FAST]], [[TMP15]]
; CHECK-NEXT:    [[SHR90_SINK_FAST:%.*]] = select i1 [[CMP79]], i64 [[FAST_ASHR]], i64 [[SHR90_FAST]]
; CHECK-NEXT:    [[CONV91_FAST:%.*]] = trunc i64 [[SHR90_SINK_FAST]] to i16
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[I_0156_FAST]]
; CHECK-NEXT:    store i16 [[CONV91_FAST]], ptr [[TMP16]], align 2
; CHECK-NEXT:    [[INC96_FAST]] = add nuw nsw i32 [[I_0156_FAST]], 1
; CHECK-NEXT:    [[EXITCOND160_NOT_FAST:%.*]] = icmp eq i32 [[INC96_FAST]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND160_NOT_FAST]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND14_PREHEADER_FAST]], !llvm.loop [[LOOP25:![0-9]+]]
; CHECK:       [[FOR_COND14_PREHEADER_SLOW_PH]]:
; CHECK-NEXT:    br label %[[FOR_COND14_PREHEADER:.*]]
; CHECK:       [[FOR_COND14_PREHEADER]]:
; CHECK-NEXT:    [[I_0156:%.*]] = phi i32 [ 0, %[[FOR_COND14_PREHEADER_SLOW_PH]] ], [ [[INC96:%.*]], %[[FOR_COND_CLEANUP63:.*]] ]
; CHECK-NEXT:    [[INPUT_POS_0154:%.*]] = phi i32 [ 0, %[[FOR_COND14_PREHEADER_SLOW_PH]] ], [ [[INPUT_POS_1_LCSSA:%.*]], %[[FOR_COND_CLEANUP63]] ]
; CHECK-NEXT:    [[TMP17:%.*]] = load i16, ptr [[D_POS]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[CMP18138:%.*]] = icmp sgt i16 [[TMP2]], [[TMP17]]
; CHECK-NEXT:    br i1 [[CMP18138]], label %[[FOR_BODY21_LR_PH:.*]], label %[[FOR_COND_CLEANUP20:.*]]
; CHECK:       [[FOR_BODY21_LR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY21:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    [[RESULT_0_LCSSA:%.*]] = phi i32 [ 0, %[[IF_END]] ], [ [[LEN]], %[[FOR_COND_CLEANUP63]] ], [ [[LEN]], %[[FOR_COND_CLEANUP63_FAST]] ]
; CHECK-NEXT:    ret i32 [[RESULT_0_LCSSA]]
; CHECK:       [[FOR_COND_CLEANUP20]]:
; CHECK-NEXT:    [[INPUT_POS_1_LCSSA]] = phi i32 [ [[INPUT_POS_0154]], %[[FOR_COND14_PREHEADER]] ], [ [[INC:%.*]], %[[IF_END28:.*]] ]
; CHECK-NEXT:    store i16 0, ptr [[D_POS]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[TMP18:%.*]] = load i16, ptr [[POS]], align 2, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[CONV39:%.*]] = sext i16 [[TMP18]] to i32
; CHECK-NEXT:    [[CONV42:%.*]] = sext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[COEFF_POS_0141:%.*]] = add i16 [[TMP4]], -1
; CHECK-NEXT:    [[CMP43142:%.*]] = icmp slt i16 [[TMP18]], [[TMP4]]
; CHECK-NEXT:    br i1 [[CMP43142]], label %[[FOR_BODY46_LR_PH:.*]], label %[[FOR_COND58_PREHEADER:.*]]
; CHECK:       [[FOR_BODY46_LR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY46:.*]]
; CHECK:       [[FOR_BODY21]]:
; CHECK-NEXT:    [[J_0140:%.*]] = phi i32 [ 0, %[[FOR_BODY21_LR_PH]] ], [ [[INC32:%.*]], %[[IF_END28]] ]
; CHECK-NEXT:    [[INPUT_POS_1139:%.*]] = phi i32 [ [[INPUT_POS_0154]], %[[FOR_BODY21_LR_PH]] ], [ [[INC]], %[[IF_END28]] ]
; CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[POS]], align 2, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[CMP24_NOT:%.*]] = icmp slt i16 [[TMP19]], [[TMP4]]
; CHECK-NEXT:    br i1 [[CMP24_NOT]], label %[[IF_END28]], label %[[IF_THEN26:.*]]
; CHECK:       [[IF_THEN26]]:
; CHECK-NEXT:    store i16 0, ptr [[POS]], align 2, !tbaa [[TBAA19]]
; CHECK-NEXT:    br label %[[IF_END28]]
; CHECK:       [[IF_END28]]:
; CHECK-NEXT:    [[TMP20:%.*]] = phi i16 [ 0, %[[IF_THEN26]] ], [ [[TMP19]], %[[FOR_BODY21]] ]
; CHECK-NEXT:    [[INC]] = add nsw i32 [[INPUT_POS_1139]], 1
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[INPUT_POS_1139]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[ARRAYIDX]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[INC30:%.*]] = add nsw i16 [[TMP20]], 1
; CHECK-NEXT:    store i16 [[INC30]], ptr [[POS]], align 2, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[IDXPROM:%.*]] = sext i16 [[TMP20]] to i32
; CHECK-NEXT:    [[ARRAYIDX31:%.*]] = getelementptr inbounds i16, ptr [[TMP3]], i32 [[IDXPROM]]
; CHECK-NEXT:    store i16 [[TMP21]], ptr [[ARRAYIDX31]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[INC32]] = add nuw nsw i32 [[J_0140]], 1
; CHECK-NEXT:    [[CONV15:%.*]] = sext i16 [[TMP2]] to i32
; CHECK-NEXT:    [[TMP22:%.*]] = load i16, ptr [[D_POS]], align 2, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[CONV16:%.*]] = sext i16 [[TMP22]] to i32
; CHECK-NEXT:    [[SUB17:%.*]] = sub nsw i32 [[CONV15]], [[CONV16]]
; CHECK-NEXT:    [[CMP18:%.*]] = icmp slt i32 [[INC32]], [[SUB17]]
; CHECK-NEXT:    br i1 [[CMP18]], label %[[FOR_BODY21]], label %[[FOR_COND_CLEANUP20]], !llvm.loop [[LOOP21]]
; CHECK:       [[FOR_COND58_PREHEADER_LOOPEXIT:.*]]:
; CHECK-NEXT:    [[ADD_LCSSA:%.*]] = phi i64 [ [[ADD:%.*]], %[[FOR_BODY46]] ]
; CHECK-NEXT:    [[TMP23:%.*]] = add i16 [[TMP18]], -1
; CHECK-NEXT:    br label %[[FOR_COND58_PREHEADER]]
; CHECK:       [[FOR_COND58_PREHEADER]]:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi i64 [ [[ROUNDING_0]], %[[FOR_COND_CLEANUP20]] ], [ [[ADD_LCSSA]], %[[FOR_COND58_PREHEADER_LOOPEXIT]] ]
; CHECK-NEXT:    [[COEFF_POS_0_LCSSA:%.*]] = phi i16 [ [[COEFF_POS_0141]], %[[FOR_COND_CLEANUP20]] ], [ [[TMP23]], %[[FOR_COND58_PREHEADER_LOOPEXIT]] ]
; CHECK-NEXT:    [[CMP61148:%.*]] = icmp sgt i16 [[TMP18]], 0
; CHECK-NEXT:    br i1 [[CMP61148]], label %[[FOR_BODY64_LR_PH:.*]], label %[[FOR_COND_CLEANUP63]]
; CHECK:       [[FOR_BODY64_LR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY64:.*]]
; CHECK:       [[FOR_BODY46]]:
; CHECK-NEXT:    [[COEFF_POS_0145:%.*]] = phi i16 [ [[COEFF_POS_0141]], %[[FOR_BODY46_LR_PH]] ], [ [[COEFF_POS_0:%.*]], %[[FOR_BODY46]] ]
; CHECK-NEXT:    [[N_0144:%.*]] = phi i32 [ [[CONV39]], %[[FOR_BODY46_LR_PH]] ], [ [[INC55:%.*]], %[[FOR_BODY46]] ]
; CHECK-NEXT:    [[ACC_0143:%.*]] = phi i64 [ [[ROUNDING_0]], %[[FOR_BODY46_LR_PH]] ], [ [[ADD]], %[[FOR_BODY46]] ]
; CHECK-NEXT:    [[IDXPROM47:%.*]] = sext i16 [[COEFF_POS_0145]] to i32
; CHECK-NEXT:    [[ARRAYIDX48:%.*]] = getelementptr inbounds i16, ptr [[TMP5]], i32 [[IDXPROM47]]
; CHECK-NEXT:    [[TMP24:%.*]] = load i16, ptr [[ARRAYIDX48]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV49:%.*]] = sext i16 [[TMP24]] to i32
; CHECK-NEXT:    [[ARRAYIDX51:%.*]] = getelementptr inbounds i16, ptr [[TMP3]], i32 [[N_0144]]
; CHECK-NEXT:    [[TMP25:%.*]] = load i16, ptr [[ARRAYIDX51]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV52:%.*]] = sext i16 [[TMP25]] to i32
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[CONV52]], [[CONV49]]
; CHECK-NEXT:    [[CONV53:%.*]] = sext i32 [[MUL]] to i64
; CHECK-NEXT:    [[ADD]] = add nsw i64 [[ACC_0143]], [[CONV53]]
; CHECK-NEXT:    [[INC55]] = add nsw i32 [[N_0144]], 1
; CHECK-NEXT:    [[COEFF_POS_0]] = add i16 [[COEFF_POS_0145]], -1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC55]], [[CONV42]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND58_PREHEADER_LOOPEXIT]], label %[[FOR_BODY46]], !llvm.loop [[LOOP23]]
; CHECK:       [[FOR_COND_CLEANUP63]]:
; CHECK-NEXT:    [[ACC_1_LCSSA:%.*]] = phi i64 [ [[ACC_0_LCSSA]], %[[FOR_COND58_PREHEADER]] ], [ [[ADD75:%.*]], %[[FOR_BODY64]] ]
; CHECK-NEXT:    [[SHR90:%.*]] = ashr i64 [[ACC_1_LCSSA]], [[SH_PROM89]]
; CHECK-NEXT:    [[SHL83:%.*]] = shl i64 [[ACC_1_LCSSA]], [[SH_PROM82]]
; CHECK-NEXT:    [[SHR90_SINK:%.*]] = select i1 [[CMP79]], i64 [[SHL83]], i64 [[SHR90]]
; CHECK-NEXT:    [[CONV91:%.*]] = trunc i64 [[SHR90_SINK]] to i16
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[I_0156]]
; CHECK-NEXT:    store i16 [[CONV91]], ptr [[TMP26]], align 2
; CHECK-NEXT:    [[INC96]] = add nuw nsw i32 [[I_0156]], 1
; CHECK-NEXT:    [[EXITCOND160_NOT:%.*]] = icmp eq i32 [[INC96]], [[LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND160_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_COND14_PREHEADER]], !llvm.loop [[LOOP25]]
; CHECK:       [[FOR_BODY64]]:
; CHECK-NEXT:    [[N57_0151:%.*]] = phi i32 [ 0, %[[FOR_BODY64_LR_PH]] ], [ [[INC77:%.*]], %[[FOR_BODY64]] ]
; CHECK-NEXT:    [[COEFF_POS_1150:%.*]] = phi i16 [ [[COEFF_POS_0_LCSSA]], %[[FOR_BODY64_LR_PH]] ], [ [[DEC66:%.*]], %[[FOR_BODY64]] ]
; CHECK-NEXT:    [[ACC_1149:%.*]] = phi i64 [ [[ACC_0_LCSSA]], %[[FOR_BODY64_LR_PH]] ], [ [[ADD75]], %[[FOR_BODY64]] ]
; CHECK-NEXT:    [[DEC66]] = add i16 [[COEFF_POS_1150]], -1
; CHECK-NEXT:    [[IDXPROM67:%.*]] = sext i16 [[COEFF_POS_1150]] to i32
; CHECK-NEXT:    [[ARRAYIDX68:%.*]] = getelementptr inbounds i16, ptr [[TMP5]], i32 [[IDXPROM67]]
; CHECK-NEXT:    [[TMP27:%.*]] = load i16, ptr [[ARRAYIDX68]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV69:%.*]] = sext i16 [[TMP27]] to i32
; CHECK-NEXT:    [[ARRAYIDX71:%.*]] = getelementptr inbounds i16, ptr [[TMP3]], i32 [[N57_0151]]
; CHECK-NEXT:    [[TMP28:%.*]] = load i16, ptr [[ARRAYIDX71]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV72:%.*]] = sext i16 [[TMP28]] to i32
; CHECK-NEXT:    [[MUL73:%.*]] = mul nsw i32 [[CONV72]], [[CONV69]]
; CHECK-NEXT:    [[CONV74:%.*]] = sext i32 [[MUL73]] to i64
; CHECK-NEXT:    [[ADD75]] = add nsw i64 [[ACC_1149]], [[CONV74]]
; CHECK-NEXT:    [[INC77]] = add nuw nsw i32 [[N57_0151]], 1
; CHECK-NEXT:    [[EXITCOND159_NOT:%.*]] = icmp eq i32 [[INC77]], [[CONV39]]
; CHECK-NEXT:    br i1 [[EXITCOND159_NOT]], label %[[FOR_COND_CLEANUP63]], label %[[FOR_BODY64]], !llvm.loop [[LOOP24]]
;
entry:
  %shift = getelementptr inbounds i8, ptr %fir, i32 16
  %0 = load i16, ptr %shift, align 4, !tbaa !6
  %conv = sext i16 %0 to i32
  %sub = add nsw i32 %conv, -15
  %rounding_val = getelementptr inbounds i8, ptr %fir, i32 24
  %1 = load i32, ptr %rounding_val, align 4, !tbaa !13
  %conv1 = sext i32 %1 to i64
  %cmp = icmp sgt i16 %0, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %sh_prom = zext nneg i32 %conv to i64
  %shr = ashr i64 %conv1, %sh_prom
  br label %if.end

if.else:                                          ; preds = %entry
  %sub9 = sub nsw i32 0, %conv
  %sh_prom10 = zext nneg i32 %sub9 to i64
  %shl = shl i64 %conv1, %sh_prom10
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %rounding.0.in = phi i64 [ %shr, %if.then ], [ %shl, %if.else ]
  %rounding.0 = and i64 %rounding.0.in, 1099511627775
  %cmp12153 = icmp sgt i32 %len, 0
  br i1 %cmp12153, label %for.cond14.preheader.lr.ph, label %for.cond.cleanup

for.cond14.preheader.lr.ph:                       ; preds = %if.end
  %decim = getelementptr inbounds i8, ptr %fir, i32 12
  %d_pos = getelementptr inbounds i8, ptr %fir, i32 14
  %pos = getelementptr inbounds i8, ptr %fir, i32 10
  %coeffs_len = getelementptr inbounds i8, ptr %fir, i32 8
  %delay = getelementptr inbounds i8, ptr %fir, i32 4
  %cmp79 = icmp sgt i16 %0, 15
  %sub88 = sub nsw i32 15, %conv
  %sh_prom89 = zext nneg i32 %sub88 to i64
  %sh_prom82 = zext nneg i32 %sub to i64
  %2 = load i16, ptr %decim, align 4, !tbaa !14
  %3 = load ptr, ptr %delay, align 4, !tbaa !15
  %4 = load i16, ptr %coeffs_len, align 4, !tbaa !16
  %5 = load ptr, ptr %fir, align 4, !tbaa !17
  br label %for.cond14.preheader

for.cond14.preheader:                             ; preds = %for.cond.cleanup63, %for.cond14.preheader.lr.ph
  %i.0156 = phi i32 [ 0, %for.cond14.preheader.lr.ph ], [ %inc96, %for.cond.cleanup63 ]
  %input_pos.0154 = phi i32 [ 0, %for.cond14.preheader.lr.ph ], [ %input_pos.1.lcssa, %for.cond.cleanup63 ]
  %6 = load i16, ptr %d_pos, align 2, !tbaa !18
  %cmp18138 = icmp sgt i16 %2, %6
  br i1 %cmp18138, label %for.body21.lr.ph, label %for.cond.cleanup20

for.body21.lr.ph:                                 ; preds = %for.cond14.preheader
  br label %for.body21

for.cond.cleanup:                                 ; preds = %for.cond.cleanup63, %if.end
  %result.0.lcssa = phi i32 [ 0, %if.end ], [ %len, %for.cond.cleanup63 ]
  ret i32 %result.0.lcssa

for.cond.cleanup20:                               ; preds = %if.end28, %for.cond14.preheader
  %input_pos.1.lcssa = phi i32 [ %input_pos.0154, %for.cond14.preheader ], [ %inc, %if.end28 ]
  store i16 0, ptr %d_pos, align 2, !tbaa !18
  %7 = load i16, ptr %pos, align 2, !tbaa !19
  %conv39 = sext i16 %7 to i32
  %conv42 = sext i16 %4 to i32
  %coeff_pos.0141 = add i16 %4, -1
  %cmp43142 = icmp slt i16 %7, %4
  br i1 %cmp43142, label %for.body46.lr.ph, label %for.cond58.preheader

for.body46.lr.ph:                                 ; preds = %for.cond.cleanup20
  br label %for.body46

for.body21:                                       ; preds = %if.end28, %for.body21.lr.ph
  %j.0140 = phi i32 [ 0, %for.body21.lr.ph ], [ %inc32, %if.end28 ]
  %input_pos.1139 = phi i32 [ %input_pos.0154, %for.body21.lr.ph ], [ %inc, %if.end28 ]
  %8 = load i16, ptr %pos, align 2, !tbaa !19
  %cmp24.not = icmp slt i16 %8, %4
  br i1 %cmp24.not, label %if.end28, label %if.then26

if.then26:                                        ; preds = %for.body21
  store i16 0, ptr %pos, align 2, !tbaa !19
  br label %if.end28

if.end28:                                         ; preds = %if.then26, %for.body21
  %9 = phi i16 [ 0, %if.then26 ], [ %8, %for.body21 ]
  %inc = add nsw i32 %input_pos.1139, 1
  %arrayidx = getelementptr inbounds i16, ptr %input, i32 %input_pos.1139
  %10 = load i16, ptr %arrayidx, align 2, !tbaa !20
  %inc30 = add nsw i16 %9, 1
  store i16 %inc30, ptr %pos, align 2, !tbaa !19
  %idxprom = sext i16 %9 to i32
  %arrayidx31 = getelementptr inbounds i16, ptr %3, i32 %idxprom
  store i16 %10, ptr %arrayidx31, align 2, !tbaa !20
  %inc32 = add nuw nsw i32 %j.0140, 1
  %conv15 = sext i16 %2 to i32
  %11 = load i16, ptr %d_pos, align 2, !tbaa !18
  %conv16 = sext i16 %11 to i32
  %sub17 = sub nsw i32 %conv15, %conv16
  %cmp18 = icmp slt i32 %inc32, %sub17
  br i1 %cmp18, label %for.body21, label %for.cond.cleanup20, !llvm.loop !21

for.cond58.preheader.loopexit:                    ; preds = %for.body46
  %12 = add i16 %7, -1
  br label %for.cond58.preheader

for.cond58.preheader:                             ; preds = %for.cond58.preheader.loopexit, %for.cond.cleanup20
  %acc.0.lcssa = phi i64 [ %rounding.0, %for.cond.cleanup20 ], [ %add, %for.cond58.preheader.loopexit ]
  %coeff_pos.0.lcssa = phi i16 [ %coeff_pos.0141, %for.cond.cleanup20 ], [ %12, %for.cond58.preheader.loopexit ]
  %cmp61148 = icmp sgt i16 %7, 0
  br i1 %cmp61148, label %for.body64.lr.ph, label %for.cond.cleanup63

for.body64.lr.ph:                                 ; preds = %for.cond58.preheader
  br label %for.body64

for.body46:                                       ; preds = %for.body46, %for.body46.lr.ph
  %coeff_pos.0145 = phi i16 [ %coeff_pos.0141, %for.body46.lr.ph ], [ %coeff_pos.0, %for.body46 ]
  %n.0144 = phi i32 [ %conv39, %for.body46.lr.ph ], [ %inc55, %for.body46 ]
  %acc.0143 = phi i64 [ %rounding.0, %for.body46.lr.ph ], [ %add, %for.body46 ]
  %idxprom47 = sext i16 %coeff_pos.0145 to i32
  %arrayidx48 = getelementptr inbounds i16, ptr %5, i32 %idxprom47
  %13 = load i16, ptr %arrayidx48, align 2, !tbaa !20
  %conv49 = sext i16 %13 to i32
  %arrayidx51 = getelementptr inbounds i16, ptr %3, i32 %n.0144
  %14 = load i16, ptr %arrayidx51, align 2, !tbaa !20
  %conv52 = sext i16 %14 to i32
  %mul = mul nsw i32 %conv52, %conv49
  %conv53 = sext i32 %mul to i64
  %add = add nsw i64 %acc.0143, %conv53
  %inc55 = add nsw i32 %n.0144, 1
  %coeff_pos.0 = add i16 %coeff_pos.0145, -1
  %exitcond.not = icmp eq i32 %inc55, %conv42
  br i1 %exitcond.not, label %for.cond58.preheader.loopexit, label %for.body46, !llvm.loop !23

for.cond.cleanup63:                               ; preds = %for.body64, %for.cond58.preheader
  %acc.1.lcssa = phi i64 [ %acc.0.lcssa, %for.cond58.preheader ], [ %add75, %for.body64 ]
  %shr90 = ashr i64 %acc.1.lcssa, %sh_prom89
  %shl83 = shl i64 %acc.1.lcssa, %sh_prom82
  %shr90.sink = select i1 %cmp79, i64 %shl83, i64 %shr90
  %conv91 = trunc i64 %shr90.sink to i16
  %15 = getelementptr inbounds i16, ptr %output, i32 %i.0156
  store i16 %conv91, ptr %15, align 2
  %inc96 = add nuw nsw i32 %i.0156, 1
  %exitcond160.not = icmp eq i32 %inc96, %len
  br i1 %exitcond160.not, label %for.cond.cleanup, label %for.cond14.preheader, !llvm.loop !24

for.body64:                                       ; preds = %for.body64, %for.body64.lr.ph
  %n57.0151 = phi i32 [ 0, %for.body64.lr.ph ], [ %inc77, %for.body64 ]
  %coeff_pos.1150 = phi i16 [ %coeff_pos.0.lcssa, %for.body64.lr.ph ], [ %dec66, %for.body64 ]
  %acc.1149 = phi i64 [ %acc.0.lcssa, %for.body64.lr.ph ], [ %add75, %for.body64 ]
  %dec66 = add i16 %coeff_pos.1150, -1
  %idxprom67 = sext i16 %coeff_pos.1150 to i32
  %arrayidx68 = getelementptr inbounds i16, ptr %5, i32 %idxprom67
  %16 = load i16, ptr %arrayidx68, align 2, !tbaa !20
  %conv69 = sext i16 %16 to i32
  %arrayidx71 = getelementptr inbounds i16, ptr %3, i32 %n57.0151
  %17 = load i16, ptr %arrayidx71, align 2, !tbaa !20
  %conv72 = sext i16 %17 to i32
  %mul73 = mul nsw i32 %conv72, %conv69
  %conv74 = sext i32 %mul73 to i64
  %add75 = add nsw i64 %acc.1149, %conv74
  %inc77 = add nuw nsw i32 %n57.0151, 1
  %exitcond159.not = icmp eq i32 %inc77, %conv39
  br i1 %exitcond159.not, label %for.cond.cleanup63, label %for.body64, !llvm.loop !25
}

attributes #0 = { nofree norecurse nosync nounwind memory(readwrite, inaccessiblemem: none) "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic-rv32" "target-features"="+32bit,+a,+c,+f,+m,+relax,+xespv,+zicsr,+zifencei,+zmmul,-b,-d,-e,-experimental-smmpm,-experimental-smnpm,-experimental-ssnpm,-experimental-sspm,-experimental-ssqosid,-experimental-supm,-experimental-zacas,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-h,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smepmp,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-v,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }

!llvm.module.flags = !{!0, !1, !2, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"ilp32f"}
!2 = !{i32 6, !"riscv-isa", !3}
!3 = !{!"rv32i2p1_m2p0_a2p1_f2p2_c2p0_zicsr2p0_zifencei2p0_zmmul1p0_xespv1v2p1"}
!4 = !{i32 8, !"SmallDataLimit", i32 8}
!5 = !{!"Espressif clang version 17.0.1 (https://gitlab.espressif.cn:6688/idf/llvm-project.git llvmorg-19.1.2-277-gbe3198f esp-18.1.2_20240912-657-ge1dc1cc esp-18.1.2_20240912-657-ge1dc1cc esp-18.1.2_20240912-685-g8c39bf5 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 esp-18.1.2_20240912-694-g4a14fa0 esp-18.1.2_20240912-694-g4a14fa0 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-282-gf0df22b llvmorg-19.1.2-282-g61f783f llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-289-g6ab7981 llvmorg-19.1.2-294-ga687ee8 llvmorg-19.1.2-282-gded6180 llvmorg-19.1.2-295-gd6b9c67 llvmorg-19.1.2-296-g2bb38d3 llvmorg-19.1.2-302-gb46e43e llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-ga193982 llvmorg-19.1.2-310-g012c995 llvmorg-19.1.2-373-g483ac18 llvmorg-19.1.2-373-g483ac18 llvmorg-19.1.2-373-g483ac18 esp-19.1.2_20250225-2-g2444a40 esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g5a99af4 esp-19.1.2_20250225-2-g5a99af4 esp-19.1.2_20250225-4-g6ad288c esp-19.1.2_20250225-2-g78646ff esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312-1-gbfbef3f esp-19.1.2_20250225-3-g153f4c7 esp-19.1.2_20250312-2-gf1328c0 esp-19.1.2_20250312-1-ga44194f esp-19.1.2_20250312-2-g6ad288c esp-19.1.2_20250225-5-gabba736 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-1-ge8e26d4 esp-19.1.2_20250225-6-g1102ab9 esp-19.1.2_20250312-1-ga44194f esp-19.1.2_20250312-1-gfaf5f34 esp-19.1.2_20250312-2-g912da7e esp-19.1.2_20250312-12-g40fcb86 esp-19.1.2_20250312-22-g150517d esp-19.1.2_20250312-36-g3725281 esp-19.1.2_20250312-36-g3725281 esp-19.1.2_20250312-37-gd7ad151 esp-19.1.2_20250312-43-g1fdfc46 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250312-67-g1b9c1af esp-19.1.2_20250312-67-g1b9c1af esp-19.1.2_20250312-2-g590a30f esp-19.1.2_20250312-2-g590a30f esp-19.1.2_20250312-68-g65bae88 esp-19.1.2_20250312-68-g65bae88 llvmorg-19.1.2-286-g58c0b0a esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-2-gaccea5b esp-19.1.2_20250312-79-g85b8bac esp-19.1.2_20250312-1-g5bd87a5 esp-19.1.2_20250312-2-g398f0e9 esp-19.1.2_20250312-2-gfa1159a esp-19.1.2_20250312 esp-19.1.2_20250312-1-g190f2f0 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312-1-gdb3618a esp-19.1.2_20250312-5-g53503ec esp-19.1.2_20250312-14-gbd1030c esp-19.1.2_20250312-14-gbd1030c esp-19.1.2_20250312-94-ga50fb83 esp-19.1.2_20250312-21-g2d4e527 esp-19.1.2_20250312-22-gd828f8c esp-19.1.2_20250312-25-ga0db53c esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-50-g36efec3 esp-19.1.2_20250312-49-g66c7bd3 esp-19.1.2_20250312-68-gef601b8 esp-19.1.2_20250312-84-g3338f1a esp-19.1.2_20250225-105-gfa4c43d esp-19.1.2_20250312-99-gcad4d17 esp-19.1.2_20250312-2-g7c53768 esp-19.1.2_20250312-2-g7c53768 esp-19.1.2_20250312-3-g77450217 esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-7-ge58b5b9 esp-19.1.2_20250312-7-ge58b5b9 esp-19.1.2_20250312-9-gf8d929c esp-19.1.2_20250312-9-gf8d929c esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-14-gcc23a57 esp-19.1.2_20250312-15-gb030eec esp-19.1.2_20250312-16-g5e690f7 esp-19.1.2_20250312-18-g64518b8 esp-19.1.2_20250312-19-gf837620 esp-19.1.2_20250312-30-gce11723 esp-19.1.2_20250312-36-gc4a4385 esp-19.1.2_20250312-45-gb1f78a1 esp-19.1.2_20250312-45-gb1f78a1 llvmorg-20.1.1-294-g54395c3 esp-19.1.2_20250312-54-gdd06c183 llvmorg-20.1.1-295-g4acb682 esp-19.1.2_20250312-55-g38d03d5)"}
!6 = !{!7, !11, i64 16}
!7 = !{!"fir_s16_s", !8, i64 0, !8, i64 4, !11, i64 8, !11, i64 10, !11, i64 12, !11, i64 14, !11, i64 16, !8, i64 20, !12, i64 24, !11, i64 28, !11, i64 30, !11, i64 32, !11, i64 34, !11, i64 36}
!8 = !{!"any pointer", !9, i64 0}
!9 = !{!"omnipotent char", !10, i64 0}
!10 = !{!"Simple C/C++ TBAA"}
!11 = !{!"short", !9, i64 0}
!12 = !{!"int", !9, i64 0}
!13 = !{!7, !12, i64 24}
!14 = !{!7, !11, i64 12}
!15 = !{!7, !8, i64 4}
!16 = !{!7, !11, i64 8}
!17 = !{!7, !8, i64 0}
!18 = !{!7, !11, i64 14}
!19 = !{!7, !11, i64 10}
!20 = !{!11, !11, i64 0}
!21 = distinct !{!21, !22}
!22 = !{!"llvm.loop.mustprogress"}
!23 = distinct !{!23, !22}
!24 = distinct !{!24, !22}
!25 = distinct !{!25, !22}
;.
; CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META11:![0-9]+]], i64 16}
; CHECK: [[META7]] = !{!"fir_s16_s", [[META8:![0-9]+]], i64 0, [[META8]], i64 4, [[META11]], i64 8, [[META11]], i64 10, [[META11]], i64 12, [[META11]], i64 14, [[META11]], i64 16, [[META8]], i64 20, [[META12:![0-9]+]], i64 24, [[META11]], i64 28, [[META11]], i64 30, [[META11]], i64 32, [[META11]], i64 34, [[META11]], i64 36}
; CHECK: [[META8]] = !{!"any pointer", [[META9:![0-9]+]], i64 0}
; CHECK: [[META9]] = !{!"omnipotent char", [[META10:![0-9]+]], i64 0}
; CHECK: [[META10]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[META11]] = !{!"short", [[META9]], i64 0}
; CHECK: [[META12]] = !{!"int", [[META9]], i64 0}
; CHECK: [[TBAA13]] = !{[[META7]], [[META12]], i64 24}
; CHECK: [[TBAA14]] = !{[[META7]], [[META11]], i64 12}
; CHECK: [[TBAA15]] = !{[[META7]], [[META8]], i64 4}
; CHECK: [[TBAA16]] = !{[[META7]], [[META11]], i64 8}
; CHECK: [[TBAA17]] = !{[[META7]], [[META8]], i64 0}
; CHECK: [[TBAA18]] = !{[[META7]], [[META11]], i64 14}
; CHECK: [[TBAA19]] = !{[[META7]], [[META11]], i64 10}
; CHECK: [[TBAA20]] = !{[[META11]], [[META11]], i64 0}
; CHECK: [[LOOP21]] = distinct !{[[LOOP21]], [[META22:![0-9]+]]}
; CHECK: [[META22]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[LOOP23]] = distinct !{[[LOOP23]], [[META22]]}
; CHECK: [[LOOP24]] = distinct !{[[LOOP24]], [[META22]]}
; CHECK: [[LOOP25]] = distinct !{[[LOOP25]], [[META22]]}
;.
