; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32p4-loop-versioning -riscv-esp32p4-loop-versioning=true < %s | FileCheck %s


; Function Attrs: nofree norecurse nosync nounwind memory(readwrite, inaccessiblemem: none)
define dso_local i32 @dsps_firmr_s16_ansi(ptr nocapture noundef %fir, ptr nocapture noundef readonly %input, ptr nocapture noundef writeonly %output, i32 noundef %input_len) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local i32 @dsps_firmr_s16_ansi(
; CHECK-SAME: ptr noundef captures(none) [[FIR:%.*]], ptr noundef readonly captures(none) [[INPUT:%.*]], ptr noundef writeonly captures(none) [[OUTPUT:%.*]], i32 noundef [[INPUT_LEN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SHIFT:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 16
; CHECK-NEXT:    [[TMP0:%.*]] = load i16, ptr [[SHIFT]], align 4, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[DOTFR:%.*]] = freeze i16 [[TMP0]]
; CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[DOTFR]] to i32
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[CONV]], -15
; CHECK-NEXT:    [[ROUNDING_VAL:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 24
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ROUNDING_VAL]], align 4, !tbaa [[TBAA13:![0-9]+]]
; CHECK-NEXT:    [[CONV1:%.*]] = sext i32 [[TMP1]] to i64
; CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i16 [[DOTFR]], -1
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[SH_PROM:%.*]] = zext nneg i32 [[CONV]] to i64
; CHECK-NEXT:    [[SHR:%.*]] = ashr i64 [[CONV1]], [[SH_PROM]]
; CHECK-NEXT:    br label %[[IF_END:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[SUB9:%.*]] = sub nsw i32 0, [[CONV]]
; CHECK-NEXT:    [[SH_PROM10:%.*]] = zext nneg i32 [[SUB9]] to i64
; CHECK-NEXT:    [[SHL:%.*]] = shl i64 [[CONV1]], [[SH_PROM10]]
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[ROUNDING_0_IN:%.*]] = phi i64 [ [[SHR]], %[[IF_THEN]] ], [ [[SHL]], %[[IF_ELSE]] ]
; CHECK-NEXT:    [[ROUNDING_0:%.*]] = and i64 [[ROUNDING_0_IN]], 1099511627775
; CHECK-NEXT:    [[START_POS:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 36
; CHECK-NEXT:    [[CMP13175:%.*]] = icmp sgt i32 [[INPUT_LEN]], 0
; CHECK-NEXT:    br i1 [[CMP13175]], label %[[FOR_BODY_LR_PH:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_BODY_LR_PH]]:
; CHECK-NEXT:    [[DELAY:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 4
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[DELAY]], align 4, !tbaa [[TBAA14:![0-9]+]]
; CHECK-NEXT:    [[POS:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 10
; CHECK-NEXT:    [[INTERP:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 32
; CHECK-NEXT:    [[DELAY_SIZE:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 30
; CHECK-NEXT:    [[CMP67:%.*]] = icmp sgt i16 [[DOTFR]], 15
; CHECK-NEXT:    [[SUB76:%.*]] = sub nsw i32 15, [[CONV]]
; CHECK-NEXT:    [[SH_PROM77:%.*]] = zext nneg i32 [[SUB76]] to i64
; CHECK-NEXT:    [[SH_PROM70:%.*]] = zext nneg i32 [[SUB]] to i64
; CHECK-NEXT:    [[DECIM:%.*]] = getelementptr inbounds i8, ptr [[FIR]], i32 12
; CHECK-NEXT:    [[DOTPRE188:%.*]] = load i16, ptr [[POS]], align 2, !tbaa [[TBAA15:![0-9]+]]
; CHECK-NEXT:    br i1 [[CMP67]], label %[[FOR_BODY_US_PREHEADER:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    [[TMP3:%.*]] = load i16, ptr [[INTERP]], align 4, !tbaa [[TBAA16:![0-9]+]]
; CHECK-NEXT:    [[TMP4:%.*]] = load i16, ptr [[DELAY_SIZE]], align 2, !tbaa [[TBAA17:![0-9]+]]
; CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[FIR]], align 4, !tbaa [[TBAA18:![0-9]+]]
; CHECK-NEXT:    [[TMP6:%.*]] = load i16, ptr [[DECIM]], align 4, !tbaa [[TBAA19:![0-9]+]]
; CHECK-NEXT:    [[CONV19165:%.*]] = sext i16 [[TMP3]] to i32
; CHECK-NEXT:    [[CONV26:%.*]] = sext i16 [[TMP4]] to i32
; CHECK-NEXT:    [[CONV84:%.*]] = sext i16 [[TMP6]] to i32
; CHECK-NEXT:    [[SUB100:%.*]] = add i16 [[TMP4]], -1
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY_US_PREHEADER]]:
; CHECK-NEXT:    [[TMP7:%.*]] = load i16, ptr [[INTERP]], align 4, !tbaa [[TBAA16]]
; CHECK-NEXT:    [[TMP8:%.*]] = load i16, ptr [[DELAY_SIZE]], align 2, !tbaa [[TBAA17]]
; CHECK-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[FIR]], align 4, !tbaa [[TBAA18]]
; CHECK-NEXT:    [[TMP10:%.*]] = load i16, ptr [[DECIM]], align 4, !tbaa [[TBAA19]]
; CHECK-NEXT:    [[CONV19165_US:%.*]] = sext i16 [[TMP7]] to i32
; CHECK-NEXT:    [[CONV26_US_US:%.*]] = sext i16 [[TMP8]] to i32
; CHECK-NEXT:    [[CONV84_US_US:%.*]] = sext i16 [[TMP10]] to i32
; CHECK-NEXT:    [[SUB100_US:%.*]] = add i16 [[TMP8]], -1
; CHECK-NEXT:    br label %[[FOR_BODY_US:.*]]
; CHECK:       [[FOR_BODY_US]]:
; CHECK-NEXT:    [[TMP11:%.*]] = phi i16 [ [[TMP16:%.*]], %[[FOR_INC104_US:.*]] ], [ [[DOTPRE188]], %[[FOR_BODY_US_PREHEADER]] ]
; CHECK-NEXT:    [[I_0177_US:%.*]] = phi i32 [ [[INC105_US:%.*]], %[[FOR_INC104_US]] ], [ 0, %[[FOR_BODY_US_PREHEADER]] ]
; CHECK-NEXT:    [[RESULT_0176_US:%.*]] = phi i32 [ [[RESULT_1_LCSSA_US:%.*]], %[[FOR_INC104_US]] ], [ 0, %[[FOR_BODY_US_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX_US:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[I_0177_US]]
; CHECK-NEXT:    [[TMP12:%.*]] = load i16, ptr [[ARRAYIDX_US]], align 2, !tbaa [[TBAA20:![0-9]+]]
; CHECK-NEXT:    [[IDXPROM_US:%.*]] = sext i16 [[TMP11]] to i32
; CHECK-NEXT:    [[ARRAYIDX15_US:%.*]] = getelementptr inbounds i16, ptr [[TMP2]], i32 [[IDXPROM_US]]
; CHECK-NEXT:    store i16 [[TMP12]], ptr [[ARRAYIDX15_US]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[TMP13:%.*]] = load i16, ptr [[START_POS]], align 4, !tbaa [[TBAA21:![0-9]+]]
; CHECK-NEXT:    [[CONV17_US:%.*]] = sext i16 [[TMP13]] to i32
; CHECK-NEXT:    [[CMP20166_US:%.*]] = icmp slt i16 [[TMP13]], [[TMP7]]
; CHECK-NEXT:    br i1 [[CMP20166_US]], label %[[FOR_BODY22_US_US_PREHEADER:.*]], label %[[FOR_END86_US:.*]]
; CHECK:       [[FOR_BODY22_US_US_PREHEADER]]:
; CHECK-NEXT:    br label %[[FOR_BODY22_US_US:.*]]
; CHECK:       [[FOR_END86_US_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[FOR_END86_US]]
; CHECK:       [[FOR_END86_US]]:
; CHECK-NEXT:    [[RESULT_1_LCSSA_US]] = phi i32 [ [[RESULT_0176_US]], %[[FOR_BODY_US]] ], [ [[RESULT_2_US_US:%.*]], %[[FOR_END86_US_LOOPEXIT]] ]
; CHECK-NEXT:    [[M_0_LCSSA_US:%.*]] = phi i32 [ [[CONV17_US]], %[[FOR_BODY_US]] ], [ [[ADD85_US_US:%.*]], %[[FOR_END86_US_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP14:%.*]] = trunc i32 [[M_0_LCSSA_US]] to i16
; CHECK-NEXT:    [[CONV90_US:%.*]] = sub i16 [[TMP14]], [[TMP7]]
; CHECK-NEXT:    store i16 [[CONV90_US]], ptr [[START_POS]], align 4, !tbaa [[TBAA21]]
; CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[POS]], align 2, !tbaa [[TBAA15]]
; CHECK-NEXT:    [[DEC_US:%.*]] = add i16 [[TMP15]], -1
; CHECK-NEXT:    store i16 [[DEC_US]], ptr [[POS]], align 2, !tbaa [[TBAA15]]
; CHECK-NEXT:    [[CMP95_US:%.*]] = icmp slt i16 [[DEC_US]], 0
; CHECK-NEXT:    br i1 [[CMP95_US]], label %[[IF_THEN97_US:.*]], label %[[FOR_INC104_US]]
; CHECK:       [[IF_THEN97_US]]:
; CHECK-NEXT:    store i16 [[SUB100_US]], ptr [[POS]], align 2, !tbaa [[TBAA15]]
; CHECK-NEXT:    br label %[[FOR_INC104_US]]
; CHECK:       [[FOR_INC104_US]]:
; CHECK-NEXT:    [[TMP16]] = phi i16 [ [[SUB100_US]], %[[IF_THEN97_US]] ], [ [[DEC_US]], %[[FOR_END86_US]] ]
; CHECK-NEXT:    [[INC105_US]] = add nuw nsw i32 [[I_0177_US]], 1
; CHECK-NEXT:    [[EXITCOND187_NOT:%.*]] = icmp eq i32 [[INC105_US]], [[INPUT_LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND187_NOT]], label %[[FOR_COND_CLEANUP_LOOPEXIT:.*]], label %[[FOR_BODY_US]], !llvm.loop [[LOOP22:![0-9]+]]
; CHECK:       [[FOR_BODY22_US_US]]:
; CHECK-NEXT:    [[M_0168_US_US:%.*]] = phi i32 [ [[ADD85_US_US]], %[[FOR_COND_CLEANUP48_US_US:.*]] ], [ [[CONV17_US]], %[[FOR_BODY22_US_US_PREHEADER]] ]
; CHECK-NEXT:    [[RESULT_1167_US_US:%.*]] = phi i32 [ [[RESULT_2_US_US]], %[[FOR_COND_CLEANUP48_US_US]] ], [ [[RESULT_0176_US]], %[[FOR_BODY22_US_US_PREHEADER]] ]
; CHECK-NEXT:    [[TMP17:%.*]] = load i16, ptr [[POS]], align 2, !tbaa [[TBAA15]]
; CHECK-NEXT:    [[CONV24_US_US:%.*]] = sext i16 [[TMP17]] to i32
; CHECK-NEXT:    [[CMP27153_US_US:%.*]] = icmp slt i16 [[TMP17]], [[TMP8]]
; CHECK-NEXT:    br i1 [[CMP27153_US_US]], label %[[FOR_BODY30_LR_PH_US_US:.*]], label %[[FOR_COND43_PREHEADER_US_US:.*]]
; CHECK:       [[FOR_COND_CLEANUP48_US_US_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP48_US_US]]
; CHECK:       [[FOR_COND_CLEANUP48_US_US]]:
; CHECK-NEXT:    [[ACC_1_LCSSA_US_US:%.*]] = phi i64 [ [[ACC_0_LCSSA_US_US:%.*]], %[[FOR_COND43_PREHEADER_US_US]] ], [ [[ADD63_US_US:%.*]], %[[FOR_COND_CLEANUP48_US_US_LOOPEXIT]] ]
; CHECK-NEXT:    [[SHL71_US_US:%.*]] = shl i64 [[ACC_1_LCSSA_US_US]], [[SH_PROM70]]
; CHECK-NEXT:    [[CONV72_US_US:%.*]] = trunc i64 [[SHL71_US_US]] to i16
; CHECK-NEXT:    [[ARRAYIDX74_US_US:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[RESULT_1167_US_US]]
; CHECK-NEXT:    store i16 [[CONV72_US_US]], ptr [[ARRAYIDX74_US_US]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[RESULT_2_US_US]] = add nsw i32 [[RESULT_1167_US_US]], 1
; CHECK-NEXT:    [[ADD85_US_US]] = add nsw i32 [[M_0168_US_US]], [[CONV84_US_US]]
; CHECK-NEXT:    [[CMP20_US_US:%.*]] = icmp slt i32 [[ADD85_US_US]], [[CONV19165_US]]
; CHECK-NEXT:    br i1 [[CMP20_US_US]], label %[[FOR_BODY22_US_US]], label %[[FOR_END86_US_LOOPEXIT]], !llvm.loop [[LOOP24:![0-9]+]]
; CHECK:       [[FOR_BODY49_US_US:.*]]:
; CHECK-NEXT:    [[N42_0161_US_US:%.*]] = phi i32 [ 0, %[[FOR_BODY49_LR_PH_US_US:.*]] ], [ [[INC65_US_US:%.*]], %[[FOR_BODY49_US_US]] ]
; CHECK-NEXT:    [[COEFF_POS_1160_US_US:%.*]] = phi i32 [ [[COEFF_POS_0_LCSSA_US_US:%.*]], %[[FOR_BODY49_LR_PH_US_US]] ], [ [[INC54_US_US:%.*]], %[[FOR_BODY49_US_US]] ]
; CHECK-NEXT:    [[ACC_1159_US_US:%.*]] = phi i64 [ [[ACC_0_LCSSA_US_US]], %[[FOR_BODY49_LR_PH_US_US]] ], [ [[ADD63_US_US]], %[[FOR_BODY49_US_US]] ]
; CHECK-NEXT:    [[ARRAYIDX51_US_US:%.*]] = getelementptr inbounds i16, ptr [[TMP2]], i32 [[N42_0161_US_US]]
; CHECK-NEXT:    [[TMP18:%.*]] = load i16, ptr [[ARRAYIDX51_US_US]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV52_US_US:%.*]] = sext i16 [[TMP18]] to i32
; CHECK-NEXT:    [[INC54_US_US]] = add nuw nsw i32 [[COEFF_POS_1160_US_US]], 1
; CHECK-NEXT:    [[MUL57_US_US:%.*]] = mul nsw i32 [[COEFF_POS_1160_US_US]], [[CONV19165_US]]
; CHECK-NEXT:    [[GEP164_US_US:%.*]] = getelementptr i16, ptr [[INVARIANT_GEP163_US_US:%.*]], i32 [[MUL57_US_US]]
; CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[GEP164_US_US]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV60_US_US:%.*]] = sext i16 [[TMP19]] to i32
; CHECK-NEXT:    [[MUL61_US_US:%.*]] = mul nsw i32 [[CONV60_US_US]], [[CONV52_US_US]]
; CHECK-NEXT:    [[CONV62_US_US:%.*]] = sext i32 [[MUL61_US_US]] to i64
; CHECK-NEXT:    [[ADD63_US_US]] = add nsw i64 [[ACC_1159_US_US]], [[CONV62_US_US]]
; CHECK-NEXT:    [[INC65_US_US]] = add nuw nsw i32 [[N42_0161_US_US]], 1
; CHECK-NEXT:    [[EXITCOND186_NOT:%.*]] = icmp eq i32 [[INC65_US_US]], [[CONV24_US_US]]
; CHECK-NEXT:    br i1 [[EXITCOND186_NOT]], label %[[FOR_COND_CLEANUP48_US_US_LOOPEXIT]], label %[[FOR_BODY49_US_US]], !llvm.loop [[LOOP25:![0-9]+]]
; CHECK:       [[FOR_BODY30_US_US:.*]]:
; CHECK-NEXT:    [[N_0156_US_US:%.*]] = phi i32 [ [[CONV24_US_US]], %[[FOR_BODY30_LR_PH_US_US]] ], [ [[INC41_US_US:%.*]], %[[FOR_BODY30_US_US]] ]
; CHECK-NEXT:    [[COEFF_POS_0155_US_US:%.*]] = phi i32 [ 0, %[[FOR_BODY30_LR_PH_US_US]] ], [ [[INC_US_US:%.*]], %[[FOR_BODY30_US_US]] ]
; CHECK-NEXT:    [[ACC_0154_US_US:%.*]] = phi i64 [ [[ROUNDING_0]], %[[FOR_BODY30_LR_PH_US_US]] ], [ [[ADD40_US_US:%.*]], %[[FOR_BODY30_US_US]] ]
; CHECK-NEXT:    [[ARRAYIDX32_US_US:%.*]] = getelementptr inbounds i16, ptr [[TMP2]], i32 [[N_0156_US_US]]
; CHECK-NEXT:    [[TMP20:%.*]] = load i16, ptr [[ARRAYIDX32_US_US]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV33_US_US:%.*]] = sext i16 [[TMP20]] to i32
; CHECK-NEXT:    [[INC_US_US]] = add nuw nsw i32 [[COEFF_POS_0155_US_US]], 1
; CHECK-NEXT:    [[MUL_US_US:%.*]] = mul nsw i32 [[COEFF_POS_0155_US_US]], [[CONV19165_US]]
; CHECK-NEXT:    [[GEP_US_US:%.*]] = getelementptr i16, ptr [[INVARIANT_GEP_US_US:%.*]], i32 [[MUL_US_US]]
; CHECK-NEXT:    [[TMP21:%.*]] = load i16, ptr [[GEP_US_US]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV37_US_US:%.*]] = sext i16 [[TMP21]] to i32
; CHECK-NEXT:    [[MUL38_US_US:%.*]] = mul nsw i32 [[CONV37_US_US]], [[CONV33_US_US]]
; CHECK-NEXT:    [[CONV39_US_US:%.*]] = sext i32 [[MUL38_US_US]] to i64
; CHECK-NEXT:    [[ADD40_US_US]] = add nsw i64 [[ACC_0154_US_US]], [[CONV39_US_US]]
; CHECK-NEXT:    [[INC41_US_US]] = add nsw i32 [[N_0156_US_US]], 1
; CHECK-NEXT:    [[EXITCOND185_NOT:%.*]] = icmp eq i32 [[INC_US_US]], [[TMP22:%.*]]
; CHECK-NEXT:    br i1 [[EXITCOND185_NOT]], label %[[FOR_COND43_PREHEADER_US_US_LOOPEXIT:.*]], label %[[FOR_BODY30_US_US]], !llvm.loop [[LOOP26:![0-9]+]]
; CHECK:       [[FOR_COND43_PREHEADER_US_US_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_COND43_PREHEADER_US_US]]
; CHECK:       [[FOR_COND43_PREHEADER_US_US]]:
; CHECK-NEXT:    [[ACC_0_LCSSA_US_US]] = phi i64 [ [[ROUNDING_0]], %[[FOR_BODY22_US_US]] ], [ [[ADD40_US_US]], %[[FOR_COND43_PREHEADER_US_US_LOOPEXIT]] ]
; CHECK-NEXT:    [[COEFF_POS_0_LCSSA_US_US]] = phi i32 [ 0, %[[FOR_BODY22_US_US]] ], [ [[TMP22]], %[[FOR_COND43_PREHEADER_US_US_LOOPEXIT]] ]
; CHECK-NEXT:    [[CMP46158_US_US:%.*]] = icmp sgt i16 [[TMP17]], 0
; CHECK-NEXT:    br i1 [[CMP46158_US_US]], label %[[FOR_BODY49_LR_PH_US_US]], label %[[FOR_COND_CLEANUP48_US_US]]
; CHECK:       [[FOR_BODY30_LR_PH_US_US]]:
; CHECK-NEXT:    [[INVARIANT_GEP_US_US]] = getelementptr i16, ptr [[TMP9]], i32 [[M_0168_US_US]]
; CHECK-NEXT:    [[TMP22]] = sub nsw i32 [[CONV26_US_US]], [[CONV24_US_US]]
; CHECK-NEXT:    br label %[[FOR_BODY30_US_US]]
; CHECK:       [[FOR_BODY49_LR_PH_US_US]]:
; CHECK-NEXT:    [[INVARIANT_GEP163_US_US]] = getelementptr i16, ptr [[TMP9]], i32 [[M_0168_US_US]]
; CHECK-NEXT:    br label %[[FOR_BODY49_US_US]]
; CHECK:       [[FOR_COND_CLEANUP_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_COND_CLEANUP_LOOPEXIT1:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    [[RESULT_0_LCSSA:%.*]] = phi i32 [ 0, %[[IF_END]] ], [ [[RESULT_1_LCSSA_US]], %[[FOR_COND_CLEANUP_LOOPEXIT]] ], [ [[RESULT_1_LCSSA:%.*]], %[[FOR_COND_CLEANUP_LOOPEXIT1]] ]
; CHECK-NEXT:    ret i32 [[RESULT_0_LCSSA]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[TMP23:%.*]] = phi i16 [ [[TMP34:%.*]], %[[FOR_INC104:.*]] ], [ [[DOTPRE188]], %[[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[I_0177:%.*]] = phi i32 [ [[INC105:%.*]], %[[FOR_INC104]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[RESULT_0176:%.*]] = phi i32 [ [[RESULT_1_LCSSA]], %[[FOR_INC104]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i16, ptr [[INPUT]], i32 [[I_0177]]
; CHECK-NEXT:    [[TMP24:%.*]] = load i16, ptr [[ARRAYIDX]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[IDXPROM:%.*]] = sext i16 [[TMP23]] to i32
; CHECK-NEXT:    [[ARRAYIDX15:%.*]] = getelementptr inbounds i16, ptr [[TMP2]], i32 [[IDXPROM]]
; CHECK-NEXT:    store i16 [[TMP24]], ptr [[ARRAYIDX15]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[TMP25:%.*]] = load i16, ptr [[START_POS]], align 4, !tbaa [[TBAA21]]
; CHECK-NEXT:    [[CONV17:%.*]] = sext i16 [[TMP25]] to i32
; CHECK-NEXT:    [[CMP20166:%.*]] = icmp slt i16 [[TMP25]], [[TMP3]]
; CHECK-NEXT:    br i1 [[CMP20166]], label %[[FOR_BODY22_PREHEADER:.*]], label %[[FOR_END86:.*]]
; CHECK:       [[FOR_BODY22_PREHEADER]]:
; CHECK-NEXT:    br label %[[FOR_BODY22:.*]]
; CHECK:       [[FOR_BODY22]]:
; CHECK-NEXT:    [[M_0168:%.*]] = phi i32 [ [[ADD85:%.*]], %[[FOR_COND_CLEANUP48:.*]] ], [ [[CONV17]], %[[FOR_BODY22_PREHEADER]] ]
; CHECK-NEXT:    [[RESULT_1167:%.*]] = phi i32 [ [[RESULT_2:%.*]], %[[FOR_COND_CLEANUP48]] ], [ [[RESULT_0176]], %[[FOR_BODY22_PREHEADER]] ]
; CHECK-NEXT:    [[TMP26:%.*]] = load i16, ptr [[POS]], align 2, !tbaa [[TBAA15]]
; CHECK-NEXT:    [[CONV24:%.*]] = sext i16 [[TMP26]] to i32
; CHECK-NEXT:    [[CMP27153:%.*]] = icmp slt i16 [[TMP26]], [[TMP4]]
; CHECK-NEXT:    br i1 [[CMP27153]], label %[[FOR_BODY30_LR_PH:.*]], label %[[FOR_COND43_PREHEADER:.*]]
; CHECK:       [[FOR_BODY30_LR_PH]]:
; CHECK-NEXT:    [[INVARIANT_GEP:%.*]] = getelementptr i16, ptr [[TMP5]], i32 [[M_0168]]
; CHECK-NEXT:    [[TMP27:%.*]] = sub nsw i32 [[CONV26]], [[CONV24]]
; CHECK-NEXT:    br label %[[FOR_BODY30:.*]]
; CHECK:       [[FOR_COND43_PREHEADER_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND43_PREHEADER]]
; CHECK:       [[FOR_COND43_PREHEADER]]:
; CHECK-NEXT:    [[ACC_0_LCSSA:%.*]] = phi i64 [ [[ROUNDING_0]], %[[FOR_BODY22]] ], [ [[ADD40:%.*]], %[[FOR_COND43_PREHEADER_LOOPEXIT]] ]
; CHECK-NEXT:    [[COEFF_POS_0_LCSSA:%.*]] = phi i32 [ 0, %[[FOR_BODY22]] ], [ [[TMP27]], %[[FOR_COND43_PREHEADER_LOOPEXIT]] ]
; CHECK-NEXT:    [[CMP46158:%.*]] = icmp sgt i16 [[TMP26]], 0
; CHECK-NEXT:    br i1 [[CMP46158]], label %[[FOR_BODY49_LR_PH:.*]], label %[[FOR_COND_CLEANUP48]]
; CHECK:       [[FOR_BODY49_LR_PH]]:
; CHECK-NEXT:    [[INVARIANT_GEP163:%.*]] = getelementptr i16, ptr [[TMP5]], i32 [[M_0168]]
; CHECK-NEXT:    br label %[[FOR_BODY49:.*]]
; CHECK:       [[FOR_BODY30]]:
; CHECK-NEXT:    [[N_0156:%.*]] = phi i32 [ [[CONV24]], %[[FOR_BODY30_LR_PH]] ], [ [[INC41:%.*]], %[[FOR_BODY30]] ]
; CHECK-NEXT:    [[COEFF_POS_0155:%.*]] = phi i32 [ 0, %[[FOR_BODY30_LR_PH]] ], [ [[INC:%.*]], %[[FOR_BODY30]] ]
; CHECK-NEXT:    [[ACC_0154:%.*]] = phi i64 [ [[ROUNDING_0]], %[[FOR_BODY30_LR_PH]] ], [ [[ADD40]], %[[FOR_BODY30]] ]
; CHECK-NEXT:    [[ARRAYIDX32:%.*]] = getelementptr inbounds i16, ptr [[TMP2]], i32 [[N_0156]]
; CHECK-NEXT:    [[TMP28:%.*]] = load i16, ptr [[ARRAYIDX32]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV33:%.*]] = sext i16 [[TMP28]] to i32
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[COEFF_POS_0155]], 1
; CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[COEFF_POS_0155]], [[CONV19165]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i16, ptr [[INVARIANT_GEP]], i32 [[MUL]]
; CHECK-NEXT:    [[TMP29:%.*]] = load i16, ptr [[GEP]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV37:%.*]] = sext i16 [[TMP29]] to i32
; CHECK-NEXT:    [[MUL38:%.*]] = mul nsw i32 [[CONV37]], [[CONV33]]
; CHECK-NEXT:    [[CONV39:%.*]] = sext i32 [[MUL38]] to i64
; CHECK-NEXT:    [[ADD40]] = add nsw i64 [[ACC_0154]], [[CONV39]]
; CHECK-NEXT:    [[INC41]] = add nsw i32 [[N_0156]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], [[TMP27]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND43_PREHEADER_LOOPEXIT]], label %[[FOR_BODY30]], !llvm.loop [[LOOP26]]
; CHECK:       [[FOR_COND_CLEANUP48_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP48]]
; CHECK:       [[FOR_COND_CLEANUP48]]:
; CHECK-NEXT:    [[ACC_1_LCSSA:%.*]] = phi i64 [ [[ACC_0_LCSSA]], %[[FOR_COND43_PREHEADER]] ], [ [[ADD63:%.*]], %[[FOR_COND_CLEANUP48_LOOPEXIT]] ]
; CHECK-NEXT:    [[SHR78:%.*]] = ashr i64 [[ACC_1_LCSSA]], [[SH_PROM77]]
; CHECK-NEXT:    [[CONV79:%.*]] = trunc i64 [[SHR78]] to i16
; CHECK-NEXT:    [[ARRAYIDX81:%.*]] = getelementptr inbounds i16, ptr [[OUTPUT]], i32 [[RESULT_1167]]
; CHECK-NEXT:    store i16 [[CONV79]], ptr [[ARRAYIDX81]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[RESULT_2]] = add nsw i32 [[RESULT_1167]], 1
; CHECK-NEXT:    [[ADD85]] = add nsw i32 [[M_0168]], [[CONV84]]
; CHECK-NEXT:    [[CMP20:%.*]] = icmp slt i32 [[ADD85]], [[CONV19165]]
; CHECK-NEXT:    br i1 [[CMP20]], label %[[FOR_BODY22]], label %[[FOR_END86_LOOPEXIT:.*]], !llvm.loop [[LOOP24]]
; CHECK:       [[FOR_BODY49]]:
; CHECK-NEXT:    [[N42_0161:%.*]] = phi i32 [ 0, %[[FOR_BODY49_LR_PH]] ], [ [[INC65:%.*]], %[[FOR_BODY49]] ]
; CHECK-NEXT:    [[COEFF_POS_1160:%.*]] = phi i32 [ [[COEFF_POS_0_LCSSA]], %[[FOR_BODY49_LR_PH]] ], [ [[INC54:%.*]], %[[FOR_BODY49]] ]
; CHECK-NEXT:    [[ACC_1159:%.*]] = phi i64 [ [[ACC_0_LCSSA]], %[[FOR_BODY49_LR_PH]] ], [ [[ADD63]], %[[FOR_BODY49]] ]
; CHECK-NEXT:    [[ARRAYIDX51:%.*]] = getelementptr inbounds i16, ptr [[TMP2]], i32 [[N42_0161]]
; CHECK-NEXT:    [[TMP30:%.*]] = load i16, ptr [[ARRAYIDX51]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV52:%.*]] = sext i16 [[TMP30]] to i32
; CHECK-NEXT:    [[INC54]] = add nuw nsw i32 [[COEFF_POS_1160]], 1
; CHECK-NEXT:    [[MUL57:%.*]] = mul nsw i32 [[COEFF_POS_1160]], [[CONV19165]]
; CHECK-NEXT:    [[GEP164:%.*]] = getelementptr i16, ptr [[INVARIANT_GEP163]], i32 [[MUL57]]
; CHECK-NEXT:    [[TMP31:%.*]] = load i16, ptr [[GEP164]], align 2, !tbaa [[TBAA20]]
; CHECK-NEXT:    [[CONV60:%.*]] = sext i16 [[TMP31]] to i32
; CHECK-NEXT:    [[MUL61:%.*]] = mul nsw i32 [[CONV60]], [[CONV52]]
; CHECK-NEXT:    [[CONV62:%.*]] = sext i32 [[MUL61]] to i64
; CHECK-NEXT:    [[ADD63]] = add nsw i64 [[ACC_1159]], [[CONV62]]
; CHECK-NEXT:    [[INC65]] = add nuw nsw i32 [[N42_0161]], 1
; CHECK-NEXT:    [[EXITCOND183_NOT:%.*]] = icmp eq i32 [[INC65]], [[CONV24]]
; CHECK-NEXT:    br i1 [[EXITCOND183_NOT]], label %[[FOR_COND_CLEANUP48_LOOPEXIT]], label %[[FOR_BODY49]], !llvm.loop [[LOOP25]]
; CHECK:       [[FOR_END86_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_END86]]
; CHECK:       [[FOR_END86]]:
; CHECK-NEXT:    [[RESULT_1_LCSSA]] = phi i32 [ [[RESULT_0176]], %[[FOR_BODY]] ], [ [[RESULT_2]], %[[FOR_END86_LOOPEXIT]] ]
; CHECK-NEXT:    [[M_0_LCSSA:%.*]] = phi i32 [ [[CONV17]], %[[FOR_BODY]] ], [ [[ADD85]], %[[FOR_END86_LOOPEXIT]] ]
; CHECK-NEXT:    [[TMP32:%.*]] = trunc i32 [[M_0_LCSSA]] to i16
; CHECK-NEXT:    [[CONV90:%.*]] = sub i16 [[TMP32]], [[TMP3]]
; CHECK-NEXT:    store i16 [[CONV90]], ptr [[START_POS]], align 4, !tbaa [[TBAA21]]
; CHECK-NEXT:    [[TMP33:%.*]] = load i16, ptr [[POS]], align 2, !tbaa [[TBAA15]]
; CHECK-NEXT:    [[DEC:%.*]] = add i16 [[TMP33]], -1
; CHECK-NEXT:    store i16 [[DEC]], ptr [[POS]], align 2, !tbaa [[TBAA15]]
; CHECK-NEXT:    [[CMP95:%.*]] = icmp slt i16 [[DEC]], 0
; CHECK-NEXT:    br i1 [[CMP95]], label %[[IF_THEN97:.*]], label %[[FOR_INC104]]
; CHECK:       [[IF_THEN97]]:
; CHECK-NEXT:    store i16 [[SUB100]], ptr [[POS]], align 2, !tbaa [[TBAA15]]
; CHECK-NEXT:    br label %[[FOR_INC104]]
; CHECK:       [[FOR_INC104]]:
; CHECK-NEXT:    [[TMP34]] = phi i16 [ [[DEC]], %[[FOR_END86]] ], [ [[SUB100]], %[[IF_THEN97]] ]
; CHECK-NEXT:    [[INC105]] = add nuw nsw i32 [[I_0177]], 1
; CHECK-NEXT:    [[EXITCOND184_NOT:%.*]] = icmp eq i32 [[INC105]], [[INPUT_LEN]]
; CHECK-NEXT:    br i1 [[EXITCOND184_NOT]], label %[[FOR_COND_CLEANUP_LOOPEXIT1]], label %[[FOR_BODY]], !llvm.loop [[LOOP22]]
;
entry:
  %shift = getelementptr inbounds i8, ptr %fir, i32 16
  %0 = load i16, ptr %shift, align 4, !tbaa !6
  %.fr = freeze i16 %0
  %conv = sext i16 %.fr to i32
  %sub = add nsw i32 %conv, -15
  %rounding_val = getelementptr inbounds i8, ptr %fir, i32 24
  %1 = load i32, ptr %rounding_val, align 4, !tbaa !13
  %conv1 = sext i32 %1 to i64
  %cmp = icmp sgt i16 %.fr, -1
  br i1 %cmp, label %if.then, label %if.else

if.then:                                          ; preds = %entry
  %sh_prom = zext nneg i32 %conv to i64
  %shr = ashr i64 %conv1, %sh_prom
  br label %if.end

if.else:                                          ; preds = %entry
  %sub9 = sub nsw i32 0, %conv
  %sh_prom10 = zext nneg i32 %sub9 to i64
  %shl = shl i64 %conv1, %sh_prom10
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %rounding.0.in = phi i64 [ %shr, %if.then ], [ %shl, %if.else ]
  %rounding.0 = and i64 %rounding.0.in, 1099511627775
  %start_pos = getelementptr inbounds i8, ptr %fir, i32 36
  %cmp13175 = icmp sgt i32 %input_len, 0
  br i1 %cmp13175, label %for.body.lr.ph, label %for.cond.cleanup

for.body.lr.ph:                                   ; preds = %if.end
  %delay = getelementptr inbounds i8, ptr %fir, i32 4
  %2 = load ptr, ptr %delay, align 4, !tbaa !14
  %pos = getelementptr inbounds i8, ptr %fir, i32 10
  %interp = getelementptr inbounds i8, ptr %fir, i32 32
  %delay_size = getelementptr inbounds i8, ptr %fir, i32 30
  %cmp67 = icmp sgt i16 %.fr, 15
  %sub76 = sub nsw i32 15, %conv
  %sh_prom77 = zext nneg i32 %sub76 to i64
  %sh_prom70 = zext nneg i32 %sub to i64
  %decim = getelementptr inbounds i8, ptr %fir, i32 12
  %.pre188 = load i16, ptr %pos, align 2, !tbaa !15
  br i1 %cmp67, label %for.body.us.preheader, label %for.body.preheader

for.body.preheader:                               ; preds = %for.body.lr.ph
  %3 = load i16, ptr %interp, align 4, !tbaa !16
  %4 = load i16, ptr %delay_size, align 2, !tbaa !17
  %5 = load ptr, ptr %fir, align 4, !tbaa !18
  %6 = load i16, ptr %decim, align 4, !tbaa !19
  %conv19165 = sext i16 %3 to i32
  %conv26 = sext i16 %4 to i32
  %conv84 = sext i16 %6 to i32
  %sub100 = add i16 %4, -1
  br label %for.body

for.body.us.preheader:                            ; preds = %for.body.lr.ph
  %7 = load i16, ptr %interp, align 4, !tbaa !16
  %8 = load i16, ptr %delay_size, align 2, !tbaa !17
  %9 = load ptr, ptr %fir, align 4, !tbaa !18
  %10 = load i16, ptr %decim, align 4, !tbaa !19
  %conv19165.us = sext i16 %7 to i32
  %conv26.us.us = sext i16 %8 to i32
  %conv84.us.us = sext i16 %10 to i32
  %sub100.us = add i16 %8, -1
  br label %for.body.us

for.body.us:                                      ; preds = %for.inc104.us, %for.body.us.preheader
  %11 = phi i16 [ %16, %for.inc104.us ], [ %.pre188, %for.body.us.preheader ]
  %i.0177.us = phi i32 [ %inc105.us, %for.inc104.us ], [ 0, %for.body.us.preheader ]
  %result.0176.us = phi i32 [ %result.1.lcssa.us, %for.inc104.us ], [ 0, %for.body.us.preheader ]
  %arrayidx.us = getelementptr inbounds i16, ptr %input, i32 %i.0177.us
  %12 = load i16, ptr %arrayidx.us, align 2, !tbaa !20
  %idxprom.us = sext i16 %11 to i32
  %arrayidx15.us = getelementptr inbounds i16, ptr %2, i32 %idxprom.us
  store i16 %12, ptr %arrayidx15.us, align 2, !tbaa !20
  %13 = load i16, ptr %start_pos, align 4, !tbaa !21
  %conv17.us = sext i16 %13 to i32
  %cmp20166.us = icmp slt i16 %13, %7
  br i1 %cmp20166.us, label %for.body22.us.us.preheader, label %for.end86.us

for.body22.us.us.preheader:                       ; preds = %for.body.us
  br label %for.body22.us.us

for.end86.us.loopexit:                            ; preds = %for.cond.cleanup48.us.us
  br label %for.end86.us

for.end86.us:                                     ; preds = %for.end86.us.loopexit, %for.body.us
  %result.1.lcssa.us = phi i32 [ %result.0176.us, %for.body.us ], [ %result.2.us.us, %for.end86.us.loopexit ]
  %m.0.lcssa.us = phi i32 [ %conv17.us, %for.body.us ], [ %add85.us.us, %for.end86.us.loopexit ]
  %14 = trunc i32 %m.0.lcssa.us to i16
  %conv90.us = sub i16 %14, %7
  store i16 %conv90.us, ptr %start_pos, align 4, !tbaa !21
  %15 = load i16, ptr %pos, align 2, !tbaa !15
  %dec.us = add i16 %15, -1
  store i16 %dec.us, ptr %pos, align 2, !tbaa !15
  %cmp95.us = icmp slt i16 %dec.us, 0
  br i1 %cmp95.us, label %if.then97.us, label %for.inc104.us

if.then97.us:                                     ; preds = %for.end86.us
  store i16 %sub100.us, ptr %pos, align 2, !tbaa !15
  br label %for.inc104.us

for.inc104.us:                                    ; preds = %if.then97.us, %for.end86.us
  %16 = phi i16 [ %sub100.us, %if.then97.us ], [ %dec.us, %for.end86.us ]
  %inc105.us = add nuw nsw i32 %i.0177.us, 1
  %exitcond187.not = icmp eq i32 %inc105.us, %input_len
  br i1 %exitcond187.not, label %for.cond.cleanup.loopexit, label %for.body.us, !llvm.loop !22

for.body22.us.us:                                 ; preds = %for.cond.cleanup48.us.us, %for.body22.us.us.preheader
  %m.0168.us.us = phi i32 [ %add85.us.us, %for.cond.cleanup48.us.us ], [ %conv17.us, %for.body22.us.us.preheader ]
  %result.1167.us.us = phi i32 [ %result.2.us.us, %for.cond.cleanup48.us.us ], [ %result.0176.us, %for.body22.us.us.preheader ]
  %17 = load i16, ptr %pos, align 2, !tbaa !15
  %conv24.us.us = sext i16 %17 to i32
  %cmp27153.us.us = icmp slt i16 %17, %8
  br i1 %cmp27153.us.us, label %for.body30.lr.ph.us.us, label %for.cond43.preheader.us.us

for.cond.cleanup48.us.us.loopexit:                ; preds = %for.body49.us.us
  br label %for.cond.cleanup48.us.us

for.cond.cleanup48.us.us:                         ; preds = %for.cond43.preheader.us.us, %for.cond.cleanup48.us.us.loopexit
  %acc.1.lcssa.us.us = phi i64 [ %acc.0.lcssa.us.us, %for.cond43.preheader.us.us ], [ %add63.us.us, %for.cond.cleanup48.us.us.loopexit ]
  %shl71.us.us = shl i64 %acc.1.lcssa.us.us, %sh_prom70
  %conv72.us.us = trunc i64 %shl71.us.us to i16
  %arrayidx74.us.us = getelementptr inbounds i16, ptr %output, i32 %result.1167.us.us
  store i16 %conv72.us.us, ptr %arrayidx74.us.us, align 2, !tbaa !20
  %result.2.us.us = add nsw i32 %result.1167.us.us, 1
  %add85.us.us = add nsw i32 %m.0168.us.us, %conv84.us.us
  %cmp20.us.us = icmp slt i32 %add85.us.us, %conv19165.us
  br i1 %cmp20.us.us, label %for.body22.us.us, label %for.end86.us.loopexit, !llvm.loop !24

for.body49.us.us:                                 ; preds = %for.body49.lr.ph.us.us, %for.body49.us.us
  %n42.0161.us.us = phi i32 [ 0, %for.body49.lr.ph.us.us ], [ %inc65.us.us, %for.body49.us.us ]
  %coeff_pos.1160.us.us = phi i32 [ %coeff_pos.0.lcssa.us.us, %for.body49.lr.ph.us.us ], [ %inc54.us.us, %for.body49.us.us ]
  %acc.1159.us.us = phi i64 [ %acc.0.lcssa.us.us, %for.body49.lr.ph.us.us ], [ %add63.us.us, %for.body49.us.us ]
  %arrayidx51.us.us = getelementptr inbounds i16, ptr %2, i32 %n42.0161.us.us
  %18 = load i16, ptr %arrayidx51.us.us, align 2, !tbaa !20
  %conv52.us.us = sext i16 %18 to i32
  %inc54.us.us = add nuw nsw i32 %coeff_pos.1160.us.us, 1
  %mul57.us.us = mul nsw i32 %coeff_pos.1160.us.us, %conv19165.us
  %gep164.us.us = getelementptr i16, ptr %invariant.gep163.us.us, i32 %mul57.us.us
  %19 = load i16, ptr %gep164.us.us, align 2, !tbaa !20
  %conv60.us.us = sext i16 %19 to i32
  %mul61.us.us = mul nsw i32 %conv60.us.us, %conv52.us.us
  %conv62.us.us = sext i32 %mul61.us.us to i64
  %add63.us.us = add nsw i64 %acc.1159.us.us, %conv62.us.us
  %inc65.us.us = add nuw nsw i32 %n42.0161.us.us, 1
  %exitcond186.not = icmp eq i32 %inc65.us.us, %conv24.us.us
  br i1 %exitcond186.not, label %for.cond.cleanup48.us.us.loopexit, label %for.body49.us.us, !llvm.loop !25

for.body30.us.us:                                 ; preds = %for.body30.lr.ph.us.us, %for.body30.us.us
  %n.0156.us.us = phi i32 [ %conv24.us.us, %for.body30.lr.ph.us.us ], [ %inc41.us.us, %for.body30.us.us ]
  %coeff_pos.0155.us.us = phi i32 [ 0, %for.body30.lr.ph.us.us ], [ %inc.us.us, %for.body30.us.us ]
  %acc.0154.us.us = phi i64 [ %rounding.0, %for.body30.lr.ph.us.us ], [ %add40.us.us, %for.body30.us.us ]
  %arrayidx32.us.us = getelementptr inbounds i16, ptr %2, i32 %n.0156.us.us
  %20 = load i16, ptr %arrayidx32.us.us, align 2, !tbaa !20
  %conv33.us.us = sext i16 %20 to i32
  %inc.us.us = add nuw nsw i32 %coeff_pos.0155.us.us, 1
  %mul.us.us = mul nsw i32 %coeff_pos.0155.us.us, %conv19165.us
  %gep.us.us = getelementptr i16, ptr %invariant.gep.us.us, i32 %mul.us.us
  %21 = load i16, ptr %gep.us.us, align 2, !tbaa !20
  %conv37.us.us = sext i16 %21 to i32
  %mul38.us.us = mul nsw i32 %conv37.us.us, %conv33.us.us
  %conv39.us.us = sext i32 %mul38.us.us to i64
  %add40.us.us = add nsw i64 %acc.0154.us.us, %conv39.us.us
  %inc41.us.us = add nsw i32 %n.0156.us.us, 1
  %exitcond185.not = icmp eq i32 %inc.us.us, %22
  br i1 %exitcond185.not, label %for.cond43.preheader.us.us.loopexit, label %for.body30.us.us, !llvm.loop !26

for.cond43.preheader.us.us.loopexit:              ; preds = %for.body30.us.us
  br label %for.cond43.preheader.us.us

for.cond43.preheader.us.us:                       ; preds = %for.cond43.preheader.us.us.loopexit, %for.body22.us.us
  %acc.0.lcssa.us.us = phi i64 [ %rounding.0, %for.body22.us.us ], [ %add40.us.us, %for.cond43.preheader.us.us.loopexit ]
  %coeff_pos.0.lcssa.us.us = phi i32 [ 0, %for.body22.us.us ], [ %22, %for.cond43.preheader.us.us.loopexit ]
  %cmp46158.us.us = icmp sgt i16 %17, 0
  br i1 %cmp46158.us.us, label %for.body49.lr.ph.us.us, label %for.cond.cleanup48.us.us

for.body30.lr.ph.us.us:                           ; preds = %for.body22.us.us
  %invariant.gep.us.us = getelementptr i16, ptr %9, i32 %m.0168.us.us
  %22 = sub nsw i32 %conv26.us.us, %conv24.us.us
  br label %for.body30.us.us

for.body49.lr.ph.us.us:                           ; preds = %for.cond43.preheader.us.us
  %invariant.gep163.us.us = getelementptr i16, ptr %9, i32 %m.0168.us.us
  br label %for.body49.us.us

for.cond.cleanup.loopexit:                        ; preds = %for.inc104.us
  br label %for.cond.cleanup

for.cond.cleanup.loopexit1:                       ; preds = %for.inc104
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit1, %for.cond.cleanup.loopexit, %if.end
  %result.0.lcssa = phi i32 [ 0, %if.end ], [ %result.1.lcssa.us, %for.cond.cleanup.loopexit ], [ %result.1.lcssa, %for.cond.cleanup.loopexit1 ]
  ret i32 %result.0.lcssa

for.body:                                         ; preds = %for.inc104, %for.body.preheader
  %23 = phi i16 [ %34, %for.inc104 ], [ %.pre188, %for.body.preheader ]
  %i.0177 = phi i32 [ %inc105, %for.inc104 ], [ 0, %for.body.preheader ]
  %result.0176 = phi i32 [ %result.1.lcssa, %for.inc104 ], [ 0, %for.body.preheader ]
  %arrayidx = getelementptr inbounds i16, ptr %input, i32 %i.0177
  %24 = load i16, ptr %arrayidx, align 2, !tbaa !20
  %idxprom = sext i16 %23 to i32
  %arrayidx15 = getelementptr inbounds i16, ptr %2, i32 %idxprom
  store i16 %24, ptr %arrayidx15, align 2, !tbaa !20
  %25 = load i16, ptr %start_pos, align 4, !tbaa !21
  %conv17 = sext i16 %25 to i32
  %cmp20166 = icmp slt i16 %25, %3
  br i1 %cmp20166, label %for.body22.preheader, label %for.end86

for.body22.preheader:                             ; preds = %for.body
  br label %for.body22

for.body22:                                       ; preds = %for.cond.cleanup48, %for.body22.preheader
  %m.0168 = phi i32 [ %add85, %for.cond.cleanup48 ], [ %conv17, %for.body22.preheader ]
  %result.1167 = phi i32 [ %result.2, %for.cond.cleanup48 ], [ %result.0176, %for.body22.preheader ]
  %26 = load i16, ptr %pos, align 2, !tbaa !15
  %conv24 = sext i16 %26 to i32
  %cmp27153 = icmp slt i16 %26, %4
  br i1 %cmp27153, label %for.body30.lr.ph, label %for.cond43.preheader

for.body30.lr.ph:                                 ; preds = %for.body22
  %invariant.gep = getelementptr i16, ptr %5, i32 %m.0168
  %27 = sub nsw i32 %conv26, %conv24
  br label %for.body30

for.cond43.preheader.loopexit:                    ; preds = %for.body30
  br label %for.cond43.preheader

for.cond43.preheader:                             ; preds = %for.cond43.preheader.loopexit, %for.body22
  %acc.0.lcssa = phi i64 [ %rounding.0, %for.body22 ], [ %add40, %for.cond43.preheader.loopexit ]
  %coeff_pos.0.lcssa = phi i32 [ 0, %for.body22 ], [ %27, %for.cond43.preheader.loopexit ]
  %cmp46158 = icmp sgt i16 %26, 0
  br i1 %cmp46158, label %for.body49.lr.ph, label %for.cond.cleanup48

for.body49.lr.ph:                                 ; preds = %for.cond43.preheader
  %invariant.gep163 = getelementptr i16, ptr %5, i32 %m.0168
  br label %for.body49

for.body30:                                       ; preds = %for.body30, %for.body30.lr.ph
  %n.0156 = phi i32 [ %conv24, %for.body30.lr.ph ], [ %inc41, %for.body30 ]
  %coeff_pos.0155 = phi i32 [ 0, %for.body30.lr.ph ], [ %inc, %for.body30 ]
  %acc.0154 = phi i64 [ %rounding.0, %for.body30.lr.ph ], [ %add40, %for.body30 ]
  %arrayidx32 = getelementptr inbounds i16, ptr %2, i32 %n.0156
  %28 = load i16, ptr %arrayidx32, align 2, !tbaa !20
  %conv33 = sext i16 %28 to i32
  %inc = add nuw nsw i32 %coeff_pos.0155, 1
  %mul = mul nsw i32 %coeff_pos.0155, %conv19165
  %gep = getelementptr i16, ptr %invariant.gep, i32 %mul
  %29 = load i16, ptr %gep, align 2, !tbaa !20
  %conv37 = sext i16 %29 to i32
  %mul38 = mul nsw i32 %conv37, %conv33
  %conv39 = sext i32 %mul38 to i64
  %add40 = add nsw i64 %acc.0154, %conv39
  %inc41 = add nsw i32 %n.0156, 1
  %exitcond.not = icmp eq i32 %inc, %27
  br i1 %exitcond.not, label %for.cond43.preheader.loopexit, label %for.body30, !llvm.loop !26

for.cond.cleanup48.loopexit:                      ; preds = %for.body49
  br label %for.cond.cleanup48

for.cond.cleanup48:                               ; preds = %for.cond.cleanup48.loopexit, %for.cond43.preheader
  %acc.1.lcssa = phi i64 [ %acc.0.lcssa, %for.cond43.preheader ], [ %add63, %for.cond.cleanup48.loopexit ]
  %shr78 = ashr i64 %acc.1.lcssa, %sh_prom77
  %conv79 = trunc i64 %shr78 to i16
  %arrayidx81 = getelementptr inbounds i16, ptr %output, i32 %result.1167
  store i16 %conv79, ptr %arrayidx81, align 2, !tbaa !20
  %result.2 = add nsw i32 %result.1167, 1
  %add85 = add nsw i32 %m.0168, %conv84
  %cmp20 = icmp slt i32 %add85, %conv19165
  br i1 %cmp20, label %for.body22, label %for.end86.loopexit, !llvm.loop !24

for.body49:                                       ; preds = %for.body49, %for.body49.lr.ph
  %n42.0161 = phi i32 [ 0, %for.body49.lr.ph ], [ %inc65, %for.body49 ]
  %coeff_pos.1160 = phi i32 [ %coeff_pos.0.lcssa, %for.body49.lr.ph ], [ %inc54, %for.body49 ]
  %acc.1159 = phi i64 [ %acc.0.lcssa, %for.body49.lr.ph ], [ %add63, %for.body49 ]
  %arrayidx51 = getelementptr inbounds i16, ptr %2, i32 %n42.0161
  %30 = load i16, ptr %arrayidx51, align 2, !tbaa !20
  %conv52 = sext i16 %30 to i32
  %inc54 = add nuw nsw i32 %coeff_pos.1160, 1
  %mul57 = mul nsw i32 %coeff_pos.1160, %conv19165
  %gep164 = getelementptr i16, ptr %invariant.gep163, i32 %mul57
  %31 = load i16, ptr %gep164, align 2, !tbaa !20
  %conv60 = sext i16 %31 to i32
  %mul61 = mul nsw i32 %conv60, %conv52
  %conv62 = sext i32 %mul61 to i64
  %add63 = add nsw i64 %acc.1159, %conv62
  %inc65 = add nuw nsw i32 %n42.0161, 1
  %exitcond183.not = icmp eq i32 %inc65, %conv24
  br i1 %exitcond183.not, label %for.cond.cleanup48.loopexit, label %for.body49, !llvm.loop !25

for.end86.loopexit:                               ; preds = %for.cond.cleanup48
  br label %for.end86

for.end86:                                        ; preds = %for.end86.loopexit, %for.body
  %result.1.lcssa = phi i32 [ %result.0176, %for.body ], [ %result.2, %for.end86.loopexit ]
  %m.0.lcssa = phi i32 [ %conv17, %for.body ], [ %add85, %for.end86.loopexit ]
  %32 = trunc i32 %m.0.lcssa to i16
  %conv90 = sub i16 %32, %3
  store i16 %conv90, ptr %start_pos, align 4, !tbaa !21
  %33 = load i16, ptr %pos, align 2, !tbaa !15
  %dec = add i16 %33, -1
  store i16 %dec, ptr %pos, align 2, !tbaa !15
  %cmp95 = icmp slt i16 %dec, 0
  br i1 %cmp95, label %if.then97, label %for.inc104

if.then97:                                        ; preds = %for.end86
  store i16 %sub100, ptr %pos, align 2, !tbaa !15
  br label %for.inc104

for.inc104:                                       ; preds = %if.then97, %for.end86
  %34 = phi i16 [ %dec, %for.end86 ], [ %sub100, %if.then97 ]
  %inc105 = add nuw nsw i32 %i.0177, 1
  %exitcond184.not = icmp eq i32 %inc105, %input_len
  br i1 %exitcond184.not, label %for.cond.cleanup.loopexit1, label %for.body, !llvm.loop !22
}

attributes #0 = { nofree norecurse nosync nounwind memory(readwrite, inaccessiblemem: none) "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic-rv32" "target-features"="+32bit,+a,+c,+f,+m,+relax,+xesppie,+zicsr,+zifencei,+zmmul,-b,-d,-e,-experimental-smmpm,-experimental-smnpm,-experimental-ssnpm,-experimental-sspm,-experimental-ssqosid,-experimental-supm,-experimental-zacas,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-h,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smepmp,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-v,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }

!llvm.module.flags = !{!0, !1, !2, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"ilp32f"}
!2 = !{i32 6, !"riscv-isa", !3}
!3 = !{!"rv32i2p1_m2p0_a2p1_f2p2_c2p0_zicsr2p0_zifencei2p0_zmmul1p0_xesppie1p0"}
!4 = !{i32 8, !"SmallDataLimit", i32 8}
!5 = !{!"Espressif clang version 17.0.1 (https://gitlab.espressif.cn:6688/idf/llvm-project.git llvmorg-19.1.2-277-gbe3198f esp-18.1.2_20240912-657-ge1dc1cc esp-18.1.2_20240912-657-ge1dc1cc esp-18.1.2_20240912-685-g8c39bf5 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 esp-18.1.2_20240912-694-g4a14fa0 esp-18.1.2_20240912-694-g4a14fa0 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-282-gf0df22b llvmorg-19.1.2-282-g61f783f llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-280-g353ae76 llvmorg-19.1.2-289-g6ab7981 llvmorg-19.1.2-294-ga687ee8 llvmorg-19.1.2-282-gded6180 llvmorg-19.1.2-295-gd6b9c67 llvmorg-19.1.2-296-g2bb38d3 llvmorg-19.1.2-302-gb46e43e llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-g92c3b79 llvmorg-19.1.2-282-ga193982 llvmorg-19.1.2-310-g012c995 llvmorg-19.1.2-373-g483ac18 llvmorg-19.1.2-373-g483ac18 llvmorg-19.1.2-373-g483ac18 esp-19.1.2_20250225-2-g2444a40 esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g77f93cb esp-19.1.2_20250225-2-g5a99af4 esp-19.1.2_20250225-2-g5a99af4 esp-19.1.2_20250225-4-g6ad288c esp-19.1.2_20250225-2-g78646ff esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312-1-gbfbef3f esp-19.1.2_20250225-3-g153f4c7 esp-19.1.2_20250312-2-gf1328c0 esp-19.1.2_20250312-1-ga44194f esp-19.1.2_20250312-2-g6ad288c esp-19.1.2_20250225-5-gabba736 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-6-gea26128 esp-19.1.2_20250312-1-ge8e26d4 esp-19.1.2_20250225-6-g1102ab9 esp-19.1.2_20250312-1-ga44194f esp-19.1.2_20250312-1-gfaf5f34 esp-19.1.2_20250312-2-g912da7e esp-19.1.2_20250312-12-g40fcb86 esp-19.1.2_20250312-22-g150517d esp-19.1.2_20250312-36-g3725281 esp-19.1.2_20250312-36-g3725281 esp-19.1.2_20250312-37-gd7ad151 esp-19.1.2_20250312-43-g1fdfc46 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250225-9-gbdf8145 esp-19.1.2_20250312-67-g1b9c1af esp-19.1.2_20250312-67-g1b9c1af esp-19.1.2_20250312-2-g590a30f esp-19.1.2_20250312-2-g590a30f esp-19.1.2_20250312-68-g65bae88 esp-19.1.2_20250312-68-g65bae88 llvmorg-19.1.2-286-g58c0b0a esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-75-gc8e87f2 esp-19.1.2_20250312-2-gaccea5b esp-19.1.2_20250312-79-g85b8bac esp-19.1.2_20250312-1-g5bd87a5 esp-19.1.2_20250312-2-g398f0e9 esp-19.1.2_20250312-2-gfa1159a esp-19.1.2_20250312 esp-19.1.2_20250312-1-g190f2f0 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312 esp-19.1.2_20250312-1-gdb3618a esp-19.1.2_20250312-5-g53503ec esp-19.1.2_20250312-14-gbd1030c esp-19.1.2_20250312-14-gbd1030c esp-19.1.2_20250312-94-ga50fb83 esp-19.1.2_20250312-21-g2d4e527 esp-19.1.2_20250312-22-gd828f8c esp-19.1.2_20250312-25-ga0db53c esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-30-g872c496e esp-19.1.2_20250312-50-g36efec3 esp-19.1.2_20250312-49-g66c7bd3 esp-19.1.2_20250312-68-gef601b8 esp-19.1.2_20250312-84-g3338f1a esp-19.1.2_20250225-105-gfa4c43d esp-19.1.2_20250312-99-gcad4d17 esp-19.1.2_20250312-2-g7c53768 esp-19.1.2_20250312-2-g7c53768 esp-19.1.2_20250312-3-g77450217 esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-7-ge58b5b9 esp-19.1.2_20250312-7-ge58b5b9 esp-19.1.2_20250312-9-gf8d929c esp-19.1.2_20250312-9-gf8d929c esp-19.1.2_20250312-1-g0b10ac7 esp-19.1.2_20250312-14-gcc23a57 esp-19.1.2_20250312-15-gb030eec esp-19.1.2_20250312-16-g5e690f7 esp-19.1.2_20250312-18-g64518b8 esp-19.1.2_20250312-19-gf837620 esp-19.1.2_20250312-30-gce11723 esp-19.1.2_20250312-36-gc4a4385 esp-19.1.2_20250312-45-gb1f78a1 esp-19.1.2_20250312-45-gb1f78a1 llvmorg-20.1.1-294-g54395c3 esp-19.1.2_20250312-54-gdd06c183 llvmorg-20.1.1-295-g4acb682 esp-19.1.2_20250312-55-g38d03d5 esp-19.1.2_20250312-57-g94f4e0b esp-19.1.2_20250312-58-gefb38fa esp-19.1.2_20250312-58-gefb38fa esp-19.1.2_20250312-59-g65810cd esp-19.1.2_20250312-68-g8571eac esp-19.1.2_20250312-3-g77450217 esp-19.1.2_20250312-77-g1941a49 esp-19.1.2_20250225-2-g5384b3c esp-19.1.2_20250312-80-g25b2378 llvmorg-20.1.1-292-gd2afeba llvmorg-20.1.1-292-g50b226d llvmorg-20.1.1-292-g50b226d esp-19.1.2_20250312-3-geb75cb5 llvmorg-20.1.1-290-gcc1c2fc llvmorg-20.1.1-290-gcc1c2fc llvmorg-20.1.1-290-gcc1c2fc llvmorg-20.1.1-292-g50b226d llvmorg-20.1.1-290-gcc1c2fc llvmorg-20.1.1-290-g64a73de llvmorg-20.1.1-290-gae1fe28 llvmorg-20.1.1-290-gae1fe28 esp-19.1.2_20250312-3-geb75cb5 llvmorg-20.1.1-290-g78197bd llvmorg-20.1.1-290-g8cf4429 llvmorg-20.1.1-290-g404545a esp-19.1.2_20250312-80-g25b2378 llvmorg-20.1.1-292-ga09200d llvmorg-20.1.1-290-g56858ea llvmorg-20.1.1-290-g56858ea llvmorg-20.1.1-290-g56858ea llvmorg-20.1.1-294-g417d26e llvmorg-20.1.1-290-gfaa84cc llvmorg-20.1.1-290-g9f9302d llvmorg-20.1.1-294-g9f00800 esp-19.1.2_20250312-81-g6c8bfdc esp-19.1.2_20250312-81-g6c8bfdc esp-19.1.2_20250312-81-g6c8bfdc esp-19.1.2_20250312-81-g6c8bfdc esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0 esp-19.1.2_20250312-82-g98420c0)"}
!6 = !{!7, !11, i64 16}
!7 = !{!"fir_s16_s", !8, i64 0, !8, i64 4, !11, i64 8, !11, i64 10, !11, i64 12, !11, i64 14, !11, i64 16, !8, i64 20, !12, i64 24, !11, i64 28, !11, i64 30, !11, i64 32, !11, i64 34, !11, i64 36}
!8 = !{!"any pointer", !9, i64 0}
!9 = !{!"omnipotent char", !10, i64 0}
!10 = !{!"Simple C/C++ TBAA"}
!11 = !{!"short", !9, i64 0}
!12 = !{!"int", !9, i64 0}
!13 = !{!7, !12, i64 24}
!14 = !{!7, !8, i64 4}
!15 = !{!7, !11, i64 10}
!16 = !{!7, !11, i64 32}
!17 = !{!7, !11, i64 30}
!18 = !{!7, !8, i64 0}
!19 = !{!7, !11, i64 12}
!20 = !{!11, !11, i64 0}
!21 = !{!7, !11, i64 36}
!22 = distinct !{!22, !23}
!23 = !{!"llvm.loop.mustprogress"}
!24 = distinct !{!24, !23}
!25 = distinct !{!25, !23}
!26 = distinct !{!26, !23}
;.
; CHECK: [[TBAA6]] = !{[[META7:![0-9]+]], [[META11:![0-9]+]], i64 16}
; CHECK: [[META7]] = !{!"fir_s16_s", [[META8:![0-9]+]], i64 0, [[META8]], i64 4, [[META11]], i64 8, [[META11]], i64 10, [[META11]], i64 12, [[META11]], i64 14, [[META11]], i64 16, [[META8]], i64 20, [[META12:![0-9]+]], i64 24, [[META11]], i64 28, [[META11]], i64 30, [[META11]], i64 32, [[META11]], i64 34, [[META11]], i64 36}
; CHECK: [[META8]] = !{!"any pointer", [[META9:![0-9]+]], i64 0}
; CHECK: [[META9]] = !{!"omnipotent char", [[META10:![0-9]+]], i64 0}
; CHECK: [[META10]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[META11]] = !{!"short", [[META9]], i64 0}
; CHECK: [[META12]] = !{!"int", [[META9]], i64 0}
; CHECK: [[TBAA13]] = !{[[META7]], [[META12]], i64 24}
; CHECK: [[TBAA14]] = !{[[META7]], [[META8]], i64 4}
; CHECK: [[TBAA15]] = !{[[META7]], [[META11]], i64 10}
; CHECK: [[TBAA16]] = !{[[META7]], [[META11]], i64 32}
; CHECK: [[TBAA17]] = !{[[META7]], [[META11]], i64 30}
; CHECK: [[TBAA18]] = !{[[META7]], [[META8]], i64 0}
; CHECK: [[TBAA19]] = !{[[META7]], [[META11]], i64 12}
; CHECK: [[TBAA20]] = !{[[META11]], [[META11]], i64 0}
; CHECK: [[TBAA21]] = !{[[META7]], [[META11]], i64 36}
; CHECK: [[LOOP22]] = distinct !{[[LOOP22]], [[META23:![0-9]+]]}
; CHECK: [[META23]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[LOOP24]] = distinct !{[[LOOP24]], [[META23]]}
; CHECK: [[LOOP25]] = distinct !{[[LOOP25]], [[META23]]}
; CHECK: [[LOOP26]] = distinct !{[[LOOP26]], [[META23]]}
;.
