; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32-p4-memmove -riscv-esp32-p4-memmove=true < %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "riscv32-esp-unknown-elf"


define void @test_src8_dst16_size_16(ptr %a, ptr %b) {
;
;
; CHECK-LABEL: define void @test_src8_dst16_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    call void @llvm.memmove.p0.p0.i32(ptr align 16 [[A]], ptr align 8 [[B]], i32 16, i1 false), !riscv.esp32p4.memmove.no_reprocess [[META0:![0-9]+]]
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 8
; CHECK-NEXT:    [[DST_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 0
; CHECK-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[SRC_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[DST_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = inttoptr i32 [[TMP2]] to ptr
; CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i32 [[TMP3]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP4]], i32 -8) #[[ATTR3:[0-9]+]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC2]], <8 x i8> [[VLDL64IP_M_VEC]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP6]], ptr [[TMP5]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP7:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR3]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = ptrtoint ptr [[VST128IP_M]] to i32
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(16) %a, ptr noundef nonnull align 8 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_src8_dst16_size_48(ptr %a, ptr %b) {
;
;
; CHECK-LABEL: define void @test_src8_dst16_size_48(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    call void @llvm.memmove.p0.p0.i32(ptr align 16 [[A]], ptr align 8 [[B]], i32 48, i1 false), !riscv.esp32p4.memmove.no_reprocess [[META0]]
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 40
; CHECK-NEXT:    [[DST_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 32
; CHECK-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[SRC_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[DST_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = inttoptr i32 [[TMP2]] to ptr
; CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i32 [[TMP3]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP4]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC2]], <8 x i8> [[VLDL64IP_M_VEC]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP6]], ptr [[TMP5]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP7:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR3]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = ptrtoint ptr [[VST128IP_M]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = inttoptr i32 [[TMP7]] to ptr
; CHECK-NEXT:    [[TMP10:%.*]] = inttoptr i32 [[TMP8]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP9]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR6]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC8]], <8 x i8> [[VLDL64IP_M_VEC5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP11]], ptr [[TMP10]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR9]] to i32
; CHECK-NEXT:    [[TMP13:%.*]] = ptrtoint ptr [[VST128IP_M10]] to i32
; CHECK-NEXT:    [[TMP14:%.*]] = inttoptr i32 [[TMP12]] to ptr
; CHECK-NEXT:    [[TMP15:%.*]] = inttoptr i32 [[TMP13]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP14]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDL64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR13]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M14]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M14]], 1
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC15]], <8 x i8> [[VLDL64IP_M_VEC12]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP16]], ptr [[TMP15]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP17:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR16]] to i32
; CHECK-NEXT:    [[TMP18:%.*]] = ptrtoint ptr [[VST128IP_M17]] to i32
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(48) %a, ptr noundef nonnull align 8 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}

define void @test_src8_dst16_size_128(ptr %a, ptr %b) {
;
;
; CHECK-LABEL: define void @test_src8_dst16_size_128(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    call void @llvm.memmove.p0.p0.i32(ptr align 16 [[A]], ptr align 8 [[B]], i32 128, i1 false), !riscv.esp32p4.memmove.no_reprocess [[META0]]
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 120
; CHECK-NEXT:    [[DST_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 112
; CHECK-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[SRC_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[DST_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = inttoptr i32 [[TMP2]] to ptr
; CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i32 [[TMP3]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP4]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC2]], <8 x i8> [[VLDL64IP_M_VEC]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP6]], ptr [[TMP5]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP7:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR3]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = ptrtoint ptr [[VST128IP_M]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = inttoptr i32 [[TMP7]] to ptr
; CHECK-NEXT:    [[TMP10:%.*]] = inttoptr i32 [[TMP8]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP9]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR6]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC8]], <8 x i8> [[VLDL64IP_M_VEC5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP11]], ptr [[TMP10]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR9]] to i32
; CHECK-NEXT:    [[TMP13:%.*]] = ptrtoint ptr [[VST128IP_M10]] to i32
; CHECK-NEXT:    [[TMP14:%.*]] = inttoptr i32 [[TMP12]] to ptr
; CHECK-NEXT:    [[TMP15:%.*]] = inttoptr i32 [[TMP13]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP14]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDL64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR13]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M14]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M14]], 1
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC15]], <8 x i8> [[VLDL64IP_M_VEC12]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP16]], ptr [[TMP15]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP17:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR16]] to i32
; CHECK-NEXT:    [[TMP18:%.*]] = ptrtoint ptr [[VST128IP_M17]] to i32
; CHECK-NEXT:    [[TMP19:%.*]] = inttoptr i32 [[TMP17]] to ptr
; CHECK-NEXT:    [[TMP20:%.*]] = inttoptr i32 [[TMP18]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M18:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP19]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M18]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M18]], 1
; CHECK-NEXT:    [[VLDL64IP_M21:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR20]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 1
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC22]], <8 x i8> [[VLDL64IP_M_VEC19]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP21]], ptr [[TMP20]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP22:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR23]] to i32
; CHECK-NEXT:    [[TMP23:%.*]] = ptrtoint ptr [[VST128IP_M24]] to i32
; CHECK-NEXT:    [[TMP24:%.*]] = inttoptr i32 [[TMP22]] to ptr
; CHECK-NEXT:    [[TMP25:%.*]] = inttoptr i32 [[TMP23]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M25:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP24]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 1
; CHECK-NEXT:    [[VLDL64IP_M28:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR27]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M28]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M28]], 1
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC29]], <8 x i8> [[VLDL64IP_M_VEC26]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M31:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP26]], ptr [[TMP25]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP27:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR30]] to i32
; CHECK-NEXT:    [[TMP28:%.*]] = ptrtoint ptr [[VST128IP_M31]] to i32
; CHECK-NEXT:    [[TMP29:%.*]] = inttoptr i32 [[TMP27]] to ptr
; CHECK-NEXT:    [[TMP30:%.*]] = inttoptr i32 [[TMP28]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP29]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M32]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR34]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[TMP31:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC36]], <8 x i8> [[VLDL64IP_M_VEC33]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M38:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP31]], ptr [[TMP30]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP32:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR37]] to i32
; CHECK-NEXT:    [[TMP33:%.*]] = ptrtoint ptr [[VST128IP_M38]] to i32
; CHECK-NEXT:    [[TMP34:%.*]] = inttoptr i32 [[TMP32]] to ptr
; CHECK-NEXT:    [[TMP35:%.*]] = inttoptr i32 [[TMP33]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP34]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDL64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR41]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M42]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M42]], 1
; CHECK-NEXT:    [[TMP36:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC43]], <8 x i8> [[VLDL64IP_M_VEC40]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP36]], ptr [[TMP35]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP37:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR44]] to i32
; CHECK-NEXT:    [[TMP38:%.*]] = ptrtoint ptr [[VST128IP_M45]] to i32
; CHECK-NEXT:    [[TMP39:%.*]] = inttoptr i32 [[TMP37]] to ptr
; CHECK-NEXT:    [[TMP40:%.*]] = inttoptr i32 [[TMP38]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M46:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP39]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M46]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M46]], 1
; CHECK-NEXT:    [[VLDL64IP_M49:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR48]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M49]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M49]], 1
; CHECK-NEXT:    [[TMP41:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC50]], <8 x i8> [[VLDL64IP_M_VEC47]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP41]], ptr [[TMP40]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP42:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR51]] to i32
; CHECK-NEXT:    [[TMP43:%.*]] = ptrtoint ptr [[VST128IP_M52]] to i32
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(128) %a, ptr noundef nonnull align 8 dereferenceable(128) %b, i32 128, i1 false)
  ret void
}

define void @test_src8_dst16_size_256(ptr %a, ptr %b) {
;
;
; CHECK-LABEL: define void @test_src8_dst16_size_256(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    call void @llvm.memmove.p0.p0.i32(ptr align 16 [[A]], ptr align 8 [[B]], i32 256, i1 false), !riscv.esp32p4.memmove.no_reprocess [[META0]]
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 248
; CHECK-NEXT:    [[DST_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 240
; CHECK-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[SRC_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[DST_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = inttoptr i32 [[TMP2]] to ptr
; CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i32 [[TMP3]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP4]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M]], 1
; CHECK-NEXT:    [[VLDL64IP_M1:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC2:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR3:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M1]], 1
; CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC2]], <8 x i8> [[VLDL64IP_M_VEC]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP6]], ptr [[TMP5]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP7:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR3]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = ptrtoint ptr [[VST128IP_M]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = inttoptr i32 [[TMP7]] to ptr
; CHECK-NEXT:    [[TMP10:%.*]] = inttoptr i32 [[TMP8]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M4:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP9]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC5:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR6:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M4]], 1
; CHECK-NEXT:    [[VLDL64IP_M7:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR6]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC8:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR9:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M7]], 1
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC8]], <8 x i8> [[VLDL64IP_M_VEC5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M10:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP11]], ptr [[TMP10]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR9]] to i32
; CHECK-NEXT:    [[TMP13:%.*]] = ptrtoint ptr [[VST128IP_M10]] to i32
; CHECK-NEXT:    [[TMP14:%.*]] = inttoptr i32 [[TMP12]] to ptr
; CHECK-NEXT:    [[TMP15:%.*]] = inttoptr i32 [[TMP13]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M11:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP14]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC12:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR13:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M11]], 1
; CHECK-NEXT:    [[VLDL64IP_M14:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR13]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC15:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M14]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR16:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M14]], 1
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC15]], <8 x i8> [[VLDL64IP_M_VEC12]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M17:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP16]], ptr [[TMP15]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP17:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR16]] to i32
; CHECK-NEXT:    [[TMP18:%.*]] = ptrtoint ptr [[VST128IP_M17]] to i32
; CHECK-NEXT:    [[TMP19:%.*]] = inttoptr i32 [[TMP17]] to ptr
; CHECK-NEXT:    [[TMP20:%.*]] = inttoptr i32 [[TMP18]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M18:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP19]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC19:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M18]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR20:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M18]], 1
; CHECK-NEXT:    [[VLDL64IP_M21:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR20]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC22:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR23:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M21]], 1
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC22]], <8 x i8> [[VLDL64IP_M_VEC19]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M24:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP21]], ptr [[TMP20]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP22:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR23]] to i32
; CHECK-NEXT:    [[TMP23:%.*]] = ptrtoint ptr [[VST128IP_M24]] to i32
; CHECK-NEXT:    [[TMP24:%.*]] = inttoptr i32 [[TMP22]] to ptr
; CHECK-NEXT:    [[TMP25:%.*]] = inttoptr i32 [[TMP23]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M25:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP24]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC26:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR27:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M25]], 1
; CHECK-NEXT:    [[VLDL64IP_M28:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR27]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC29:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M28]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR30:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M28]], 1
; CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC29]], <8 x i8> [[VLDL64IP_M_VEC26]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M31:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP26]], ptr [[TMP25]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP27:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR30]] to i32
; CHECK-NEXT:    [[TMP28:%.*]] = ptrtoint ptr [[VST128IP_M31]] to i32
; CHECK-NEXT:    [[TMP29:%.*]] = inttoptr i32 [[TMP27]] to ptr
; CHECK-NEXT:    [[TMP30:%.*]] = inttoptr i32 [[TMP28]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M32:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP29]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC33:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M32]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR34:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M32]], 1
; CHECK-NEXT:    [[VLDL64IP_M35:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR34]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC36:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR37:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M35]], 1
; CHECK-NEXT:    [[TMP31:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC36]], <8 x i8> [[VLDL64IP_M_VEC33]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M38:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP31]], ptr [[TMP30]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP32:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR37]] to i32
; CHECK-NEXT:    [[TMP33:%.*]] = ptrtoint ptr [[VST128IP_M38]] to i32
; CHECK-NEXT:    [[TMP34:%.*]] = inttoptr i32 [[TMP32]] to ptr
; CHECK-NEXT:    [[TMP35:%.*]] = inttoptr i32 [[TMP33]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M39:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP34]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC40:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR41:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M39]], 1
; CHECK-NEXT:    [[VLDL64IP_M42:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR41]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC43:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M42]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR44:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M42]], 1
; CHECK-NEXT:    [[TMP36:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC43]], <8 x i8> [[VLDL64IP_M_VEC40]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M45:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP36]], ptr [[TMP35]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP37:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR44]] to i32
; CHECK-NEXT:    [[TMP38:%.*]] = ptrtoint ptr [[VST128IP_M45]] to i32
; CHECK-NEXT:    [[TMP39:%.*]] = inttoptr i32 [[TMP37]] to ptr
; CHECK-NEXT:    [[TMP40:%.*]] = inttoptr i32 [[TMP38]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M46:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP39]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC47:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M46]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR48:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M46]], 1
; CHECK-NEXT:    [[VLDL64IP_M49:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR48]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC50:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M49]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR51:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M49]], 1
; CHECK-NEXT:    [[TMP41:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC50]], <8 x i8> [[VLDL64IP_M_VEC47]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M52:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP41]], ptr [[TMP40]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP42:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR51]] to i32
; CHECK-NEXT:    [[TMP43:%.*]] = ptrtoint ptr [[VST128IP_M52]] to i32
; CHECK-NEXT:    [[TMP44:%.*]] = inttoptr i32 [[TMP42]] to ptr
; CHECK-NEXT:    [[TMP45:%.*]] = inttoptr i32 [[TMP43]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M53:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP44]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC54:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M53]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR55:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M53]], 1
; CHECK-NEXT:    [[VLDL64IP_M56:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR55]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC57:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M56]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR58:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M56]], 1
; CHECK-NEXT:    [[TMP46:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC57]], <8 x i8> [[VLDL64IP_M_VEC54]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M59:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP46]], ptr [[TMP45]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP47:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR58]] to i32
; CHECK-NEXT:    [[TMP48:%.*]] = ptrtoint ptr [[VST128IP_M59]] to i32
; CHECK-NEXT:    [[TMP49:%.*]] = inttoptr i32 [[TMP47]] to ptr
; CHECK-NEXT:    [[TMP50:%.*]] = inttoptr i32 [[TMP48]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M60:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP49]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC61:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M60]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR62:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M60]], 1
; CHECK-NEXT:    [[VLDL64IP_M63:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR62]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC64:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR65:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M63]], 1
; CHECK-NEXT:    [[TMP51:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC64]], <8 x i8> [[VLDL64IP_M_VEC61]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M66:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP51]], ptr [[TMP50]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP52:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR65]] to i32
; CHECK-NEXT:    [[TMP53:%.*]] = ptrtoint ptr [[VST128IP_M66]] to i32
; CHECK-NEXT:    [[TMP54:%.*]] = inttoptr i32 [[TMP52]] to ptr
; CHECK-NEXT:    [[TMP55:%.*]] = inttoptr i32 [[TMP53]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M67:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP54]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC68:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR69:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M67]], 1
; CHECK-NEXT:    [[VLDL64IP_M70:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR69]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC71:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M70]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR72:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M70]], 1
; CHECK-NEXT:    [[TMP56:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC71]], <8 x i8> [[VLDL64IP_M_VEC68]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M73:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP56]], ptr [[TMP55]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP57:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR72]] to i32
; CHECK-NEXT:    [[TMP58:%.*]] = ptrtoint ptr [[VST128IP_M73]] to i32
; CHECK-NEXT:    [[TMP59:%.*]] = inttoptr i32 [[TMP57]] to ptr
; CHECK-NEXT:    [[TMP60:%.*]] = inttoptr i32 [[TMP58]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M74:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP59]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC75:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M74]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR76:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M74]], 1
; CHECK-NEXT:    [[VLDL64IP_M77:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR76]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC78:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M77]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR79:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M77]], 1
; CHECK-NEXT:    [[TMP61:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC78]], <8 x i8> [[VLDL64IP_M_VEC75]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M80:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP61]], ptr [[TMP60]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP62:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR79]] to i32
; CHECK-NEXT:    [[TMP63:%.*]] = ptrtoint ptr [[VST128IP_M80]] to i32
; CHECK-NEXT:    [[TMP64:%.*]] = inttoptr i32 [[TMP62]] to ptr
; CHECK-NEXT:    [[TMP65:%.*]] = inttoptr i32 [[TMP63]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M81:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP64]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC82:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M81]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR83:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M81]], 1
; CHECK-NEXT:    [[VLDL64IP_M84:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR83]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC85:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M84]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR86:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M84]], 1
; CHECK-NEXT:    [[TMP66:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC85]], <8 x i8> [[VLDL64IP_M_VEC82]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M87:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP66]], ptr [[TMP65]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP67:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR86]] to i32
; CHECK-NEXT:    [[TMP68:%.*]] = ptrtoint ptr [[VST128IP_M87]] to i32
; CHECK-NEXT:    [[TMP69:%.*]] = inttoptr i32 [[TMP67]] to ptr
; CHECK-NEXT:    [[TMP70:%.*]] = inttoptr i32 [[TMP68]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M88:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP69]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC89:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M88]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR90:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M88]], 1
; CHECK-NEXT:    [[VLDL64IP_M91:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR90]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC92:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M91]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR93:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M91]], 1
; CHECK-NEXT:    [[TMP71:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC92]], <8 x i8> [[VLDL64IP_M_VEC89]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M94:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP71]], ptr [[TMP70]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP72:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR93]] to i32
; CHECK-NEXT:    [[TMP73:%.*]] = ptrtoint ptr [[VST128IP_M94]] to i32
; CHECK-NEXT:    [[TMP74:%.*]] = inttoptr i32 [[TMP72]] to ptr
; CHECK-NEXT:    [[TMP75:%.*]] = inttoptr i32 [[TMP73]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M95:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP74]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC96:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR97:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M95]], 1
; CHECK-NEXT:    [[VLDL64IP_M98:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR97]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC99:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M98]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR100:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M98]], 1
; CHECK-NEXT:    [[TMP76:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC99]], <8 x i8> [[VLDL64IP_M_VEC96]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M101:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP76]], ptr [[TMP75]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP77:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR100]] to i32
; CHECK-NEXT:    [[TMP78:%.*]] = ptrtoint ptr [[VST128IP_M101]] to i32
; CHECK-NEXT:    [[TMP79:%.*]] = inttoptr i32 [[TMP77]] to ptr
; CHECK-NEXT:    [[TMP80:%.*]] = inttoptr i32 [[TMP78]] to ptr
; CHECK-NEXT:    [[VLDL64IP_M102:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[TMP79]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC103:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M102]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR104:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M102]], 1
; CHECK-NEXT:    [[VLDL64IP_M105:%.*]] = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip.m(ptr [[VLDL64IP_M_NEXTPTR104]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VLDL64IP_M_VEC106:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 0
; CHECK-NEXT:    [[VLDL64IP_M_NEXTPTR107:%.*]] = extractvalue { <8 x i8>, ptr } [[VLDL64IP_M105]], 1
; CHECK-NEXT:    [[TMP81:%.*]] = shufflevector <8 x i8> [[VLDL64IP_M_VEC106]], <8 x i8> [[VLDL64IP_M_VEC103]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VST128IP_M108:%.*]] = call ptr @llvm.riscv.esp.vst.128.ip.m(<16 x i8> [[TMP81]], ptr [[TMP80]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[TMP82:%.*]] = ptrtoint ptr [[VLDL64IP_M_NEXTPTR107]] to i32
; CHECK-NEXT:    [[TMP83:%.*]] = ptrtoint ptr [[VST128IP_M108]] to i32
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 16 dereferenceable(256) %a, ptr noundef nonnull align 8 dereferenceable(256) %b, i32 256, i1 false)
  ret void
}

;.
; CHECK: [[META0]] = !{}
;.
