; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32-p4-memmove -riscv-esp32-p4-memmove=true < %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "riscv32-esp-unknown-elf"

define void @test_src16_dstunalign_constant_size_16(ptr %a, ptr %b) {
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    [[FWD_CP_SRC_I64:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 0
; CHECK-NEXT:    [[FWD_CP_LD_I64:%.*]] = load i64, ptr [[FWD_CP_SRC_I64]], align 8
; CHECK-NEXT:    [[FWD_CP_DST_I64:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 0
; CHECK-NEXT:    store i64 [[FWD_CP_LD_I64]], ptr [[FWD_CP_DST_I64]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I641:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 8
; CHECK-NEXT:    [[FWD_CP_LD_I642:%.*]] = load i64, ptr [[FWD_CP_SRC_I641]], align 8
; CHECK-NEXT:    [[FWD_CP_DST_I643:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 8
; CHECK-NEXT:    store i64 [[FWD_CP_LD_I642]], ptr [[FWD_CP_DST_I643]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_END:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 16
; CHECK-NEXT:    [[DST_END:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 16
; CHECK-NEXT:    [[SRC_BYTE:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -1
; CHECK-NEXT:    [[DST_BYTE:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -1
; CHECK-NEXT:    [[BYTE_DATA:%.*]] = load i8, ptr [[SRC_BYTE]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA]], ptr [[DST_BYTE]], align 1
; CHECK-NEXT:    [[SRC_BYTE4:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -2
; CHECK-NEXT:    [[DST_BYTE5:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -2
; CHECK-NEXT:    [[BYTE_DATA6:%.*]] = load i8, ptr [[SRC_BYTE4]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA6]], ptr [[DST_BYTE5]], align 1
; CHECK-NEXT:    [[SRC_BYTE7:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -3
; CHECK-NEXT:    [[DST_BYTE8:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -3
; CHECK-NEXT:    [[BYTE_DATA9:%.*]] = load i8, ptr [[SRC_BYTE7]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA9]], ptr [[DST_BYTE8]], align 1
; CHECK-NEXT:    [[SRC_BYTE10:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -4
; CHECK-NEXT:    [[DST_BYTE11:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -4
; CHECK-NEXT:    [[BYTE_DATA12:%.*]] = load i8, ptr [[SRC_BYTE10]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA12]], ptr [[DST_BYTE11]], align 1
; CHECK-NEXT:    [[SRC_BYTE13:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -5
; CHECK-NEXT:    [[DST_BYTE14:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -5
; CHECK-NEXT:    [[BYTE_DATA15:%.*]] = load i8, ptr [[SRC_BYTE13]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA15]], ptr [[DST_BYTE14]], align 1
; CHECK-NEXT:    [[SRC_BYTE16:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -6
; CHECK-NEXT:    [[DST_BYTE17:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -6
; CHECK-NEXT:    [[BYTE_DATA18:%.*]] = load i8, ptr [[SRC_BYTE16]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA18]], ptr [[DST_BYTE17]], align 1
; CHECK-NEXT:    [[SRC_BYTE19:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -7
; CHECK-NEXT:    [[DST_BYTE20:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -7
; CHECK-NEXT:    [[BYTE_DATA21:%.*]] = load i8, ptr [[SRC_BYTE19]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA21]], ptr [[DST_BYTE20]], align 1
; CHECK-NEXT:    [[SRC_BYTE22:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -8
; CHECK-NEXT:    [[DST_BYTE23:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -8
; CHECK-NEXT:    [[BYTE_DATA24:%.*]] = load i8, ptr [[SRC_BYTE22]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA24]], ptr [[DST_BYTE23]], align 1
; CHECK-NEXT:    [[SRC_BYTE25:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -9
; CHECK-NEXT:    [[DST_BYTE26:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -9
; CHECK-NEXT:    [[BYTE_DATA27:%.*]] = load i8, ptr [[SRC_BYTE25]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA27]], ptr [[DST_BYTE26]], align 1
; CHECK-NEXT:    [[SRC_BYTE28:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -10
; CHECK-NEXT:    [[DST_BYTE29:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -10
; CHECK-NEXT:    [[BYTE_DATA30:%.*]] = load i8, ptr [[SRC_BYTE28]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA30]], ptr [[DST_BYTE29]], align 1
; CHECK-NEXT:    [[SRC_BYTE31:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -11
; CHECK-NEXT:    [[DST_BYTE32:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -11
; CHECK-NEXT:    [[BYTE_DATA33:%.*]] = load i8, ptr [[SRC_BYTE31]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA33]], ptr [[DST_BYTE32]], align 1
; CHECK-NEXT:    [[SRC_BYTE34:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -12
; CHECK-NEXT:    [[DST_BYTE35:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -12
; CHECK-NEXT:    [[BYTE_DATA36:%.*]] = load i8, ptr [[SRC_BYTE34]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA36]], ptr [[DST_BYTE35]], align 1
; CHECK-NEXT:    [[SRC_BYTE37:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -13
; CHECK-NEXT:    [[DST_BYTE38:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -13
; CHECK-NEXT:    [[BYTE_DATA39:%.*]] = load i8, ptr [[SRC_BYTE37]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA39]], ptr [[DST_BYTE38]], align 1
; CHECK-NEXT:    [[SRC_BYTE40:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -14
; CHECK-NEXT:    [[DST_BYTE41:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -14
; CHECK-NEXT:    [[BYTE_DATA42:%.*]] = load i8, ptr [[SRC_BYTE40]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA42]], ptr [[DST_BYTE41]], align 1
; CHECK-NEXT:    [[SRC_BYTE43:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -15
; CHECK-NEXT:    [[DST_BYTE44:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -15
; CHECK-NEXT:    [[BYTE_DATA45:%.*]] = load i8, ptr [[SRC_BYTE43]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA45]], ptr [[DST_BYTE44]], align 1
; CHECK-NEXT:    [[SRC_BYTE46:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -16
; CHECK-NEXT:    [[DST_BYTE47:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -16
; CHECK-NEXT:    [[BYTE_DATA48:%.*]] = load i8, ptr [[SRC_BYTE46]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA48]], ptr [[DST_BYTE47]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(16) %a, ptr noundef nonnull align 16 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_1(ptr %a, ptr %b) {
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_1(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    [[FWD_CP_SRC_I8:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 0
; CHECK-NEXT:    [[FWD_CP_LD_I8:%.*]] = load i8, ptr [[FWD_CP_SRC_I8]], align 1
; CHECK-NEXT:    [[FWD_CP_DST_I8:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 0
; CHECK-NEXT:    store i8 [[FWD_CP_LD_I8]], ptr [[FWD_CP_DST_I8]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_END:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 1
; CHECK-NEXT:    [[DST_END:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 1
; CHECK-NEXT:    [[SRC_BYTE:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -1
; CHECK-NEXT:    [[DST_BYTE:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -1
; CHECK-NEXT:    [[BYTE_DATA:%.*]] = load i8, ptr [[SRC_BYTE]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA]], ptr [[DST_BYTE]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(1) %a, ptr noundef nonnull align 16 dereferenceable(1) %b, i32 1, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_7(ptr %a, ptr %b) {
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_7(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    [[FWD_CP_SRC_I32:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 0
; CHECK-NEXT:    [[FWD_CP_LD_I32:%.*]] = load i32, ptr [[FWD_CP_SRC_I32]], align 4
; CHECK-NEXT:    [[FWD_CP_DST_I32:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 0
; CHECK-NEXT:    store i32 [[FWD_CP_LD_I32]], ptr [[FWD_CP_DST_I32]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I16:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 4
; CHECK-NEXT:    [[FWD_CP_LD_I16:%.*]] = load i16, ptr [[FWD_CP_SRC_I16]], align 2
; CHECK-NEXT:    [[FWD_CP_DST_I16:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 4
; CHECK-NEXT:    store i16 [[FWD_CP_LD_I16]], ptr [[FWD_CP_DST_I16]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I8:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 6
; CHECK-NEXT:    [[FWD_CP_LD_I8:%.*]] = load i8, ptr [[FWD_CP_SRC_I8]], align 1
; CHECK-NEXT:    [[FWD_CP_DST_I8:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 6
; CHECK-NEXT:    store i8 [[FWD_CP_LD_I8]], ptr [[FWD_CP_DST_I8]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_END:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 7
; CHECK-NEXT:    [[DST_END:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 7
; CHECK-NEXT:    [[SRC_BYTE:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -1
; CHECK-NEXT:    [[DST_BYTE:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -1
; CHECK-NEXT:    [[BYTE_DATA:%.*]] = load i8, ptr [[SRC_BYTE]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA]], ptr [[DST_BYTE]], align 1
; CHECK-NEXT:    [[SRC_BYTE1:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -2
; CHECK-NEXT:    [[DST_BYTE2:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -2
; CHECK-NEXT:    [[BYTE_DATA3:%.*]] = load i8, ptr [[SRC_BYTE1]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA3]], ptr [[DST_BYTE2]], align 1
; CHECK-NEXT:    [[SRC_BYTE4:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -3
; CHECK-NEXT:    [[DST_BYTE5:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -3
; CHECK-NEXT:    [[BYTE_DATA6:%.*]] = load i8, ptr [[SRC_BYTE4]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA6]], ptr [[DST_BYTE5]], align 1
; CHECK-NEXT:    [[SRC_BYTE7:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -4
; CHECK-NEXT:    [[DST_BYTE8:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -4
; CHECK-NEXT:    [[BYTE_DATA9:%.*]] = load i8, ptr [[SRC_BYTE7]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA9]], ptr [[DST_BYTE8]], align 1
; CHECK-NEXT:    [[SRC_BYTE10:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -5
; CHECK-NEXT:    [[DST_BYTE11:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -5
; CHECK-NEXT:    [[BYTE_DATA12:%.*]] = load i8, ptr [[SRC_BYTE10]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA12]], ptr [[DST_BYTE11]], align 1
; CHECK-NEXT:    [[SRC_BYTE13:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -6
; CHECK-NEXT:    [[DST_BYTE14:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -6
; CHECK-NEXT:    [[BYTE_DATA15:%.*]] = load i8, ptr [[SRC_BYTE13]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA15]], ptr [[DST_BYTE14]], align 1
; CHECK-NEXT:    [[SRC_BYTE16:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -7
; CHECK-NEXT:    [[DST_BYTE17:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -7
; CHECK-NEXT:    [[BYTE_DATA18:%.*]] = load i8, ptr [[SRC_BYTE16]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA18]], ptr [[DST_BYTE17]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(7) %a, ptr noundef nonnull align 16 dereferenceable(7) %b, i32 7, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_8(ptr %a, ptr %b) {
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_8(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    [[FWD_CP_SRC_I64:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 0
; CHECK-NEXT:    [[FWD_CP_LD_I64:%.*]] = load i64, ptr [[FWD_CP_SRC_I64]], align 8
; CHECK-NEXT:    [[FWD_CP_DST_I64:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 0
; CHECK-NEXT:    store i64 [[FWD_CP_LD_I64]], ptr [[FWD_CP_DST_I64]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_END:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 8
; CHECK-NEXT:    [[DST_END:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 8
; CHECK-NEXT:    [[SRC_BYTE:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -1
; CHECK-NEXT:    [[DST_BYTE:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -1
; CHECK-NEXT:    [[BYTE_DATA:%.*]] = load i8, ptr [[SRC_BYTE]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA]], ptr [[DST_BYTE]], align 1
; CHECK-NEXT:    [[SRC_BYTE1:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -2
; CHECK-NEXT:    [[DST_BYTE2:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -2
; CHECK-NEXT:    [[BYTE_DATA3:%.*]] = load i8, ptr [[SRC_BYTE1]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA3]], ptr [[DST_BYTE2]], align 1
; CHECK-NEXT:    [[SRC_BYTE4:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -3
; CHECK-NEXT:    [[DST_BYTE5:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -3
; CHECK-NEXT:    [[BYTE_DATA6:%.*]] = load i8, ptr [[SRC_BYTE4]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA6]], ptr [[DST_BYTE5]], align 1
; CHECK-NEXT:    [[SRC_BYTE7:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -4
; CHECK-NEXT:    [[DST_BYTE8:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -4
; CHECK-NEXT:    [[BYTE_DATA9:%.*]] = load i8, ptr [[SRC_BYTE7]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA9]], ptr [[DST_BYTE8]], align 1
; CHECK-NEXT:    [[SRC_BYTE10:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -5
; CHECK-NEXT:    [[DST_BYTE11:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -5
; CHECK-NEXT:    [[BYTE_DATA12:%.*]] = load i8, ptr [[SRC_BYTE10]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA12]], ptr [[DST_BYTE11]], align 1
; CHECK-NEXT:    [[SRC_BYTE13:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -6
; CHECK-NEXT:    [[DST_BYTE14:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -6
; CHECK-NEXT:    [[BYTE_DATA15:%.*]] = load i8, ptr [[SRC_BYTE13]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA15]], ptr [[DST_BYTE14]], align 1
; CHECK-NEXT:    [[SRC_BYTE16:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -7
; CHECK-NEXT:    [[DST_BYTE17:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -7
; CHECK-NEXT:    [[BYTE_DATA18:%.*]] = load i8, ptr [[SRC_BYTE16]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA18]], ptr [[DST_BYTE17]], align 1
; CHECK-NEXT:    [[SRC_BYTE19:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -8
; CHECK-NEXT:    [[DST_BYTE20:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -8
; CHECK-NEXT:    [[BYTE_DATA21:%.*]] = load i8, ptr [[SRC_BYTE19]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA21]], ptr [[DST_BYTE20]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(8) %a, ptr noundef nonnull align 16 dereferenceable(8) %b, i32 8, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_9(ptr %a, ptr %b) {
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_9(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    [[FWD_CP_SRC_I64:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 0
; CHECK-NEXT:    [[FWD_CP_LD_I64:%.*]] = load i64, ptr [[FWD_CP_SRC_I64]], align 8
; CHECK-NEXT:    [[FWD_CP_DST_I64:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 0
; CHECK-NEXT:    store i64 [[FWD_CP_LD_I64]], ptr [[FWD_CP_DST_I64]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I8:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 8
; CHECK-NEXT:    [[FWD_CP_LD_I8:%.*]] = load i8, ptr [[FWD_CP_SRC_I8]], align 1
; CHECK-NEXT:    [[FWD_CP_DST_I8:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 8
; CHECK-NEXT:    store i8 [[FWD_CP_LD_I8]], ptr [[FWD_CP_DST_I8]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_END:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 9
; CHECK-NEXT:    [[DST_END:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 9
; CHECK-NEXT:    [[SRC_BYTE:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -1
; CHECK-NEXT:    [[DST_BYTE:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -1
; CHECK-NEXT:    [[BYTE_DATA:%.*]] = load i8, ptr [[SRC_BYTE]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA]], ptr [[DST_BYTE]], align 1
; CHECK-NEXT:    [[SRC_BYTE1:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -2
; CHECK-NEXT:    [[DST_BYTE2:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -2
; CHECK-NEXT:    [[BYTE_DATA3:%.*]] = load i8, ptr [[SRC_BYTE1]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA3]], ptr [[DST_BYTE2]], align 1
; CHECK-NEXT:    [[SRC_BYTE4:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -3
; CHECK-NEXT:    [[DST_BYTE5:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -3
; CHECK-NEXT:    [[BYTE_DATA6:%.*]] = load i8, ptr [[SRC_BYTE4]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA6]], ptr [[DST_BYTE5]], align 1
; CHECK-NEXT:    [[SRC_BYTE7:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -4
; CHECK-NEXT:    [[DST_BYTE8:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -4
; CHECK-NEXT:    [[BYTE_DATA9:%.*]] = load i8, ptr [[SRC_BYTE7]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA9]], ptr [[DST_BYTE8]], align 1
; CHECK-NEXT:    [[SRC_BYTE10:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -5
; CHECK-NEXT:    [[DST_BYTE11:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -5
; CHECK-NEXT:    [[BYTE_DATA12:%.*]] = load i8, ptr [[SRC_BYTE10]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA12]], ptr [[DST_BYTE11]], align 1
; CHECK-NEXT:    [[SRC_BYTE13:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -6
; CHECK-NEXT:    [[DST_BYTE14:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -6
; CHECK-NEXT:    [[BYTE_DATA15:%.*]] = load i8, ptr [[SRC_BYTE13]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA15]], ptr [[DST_BYTE14]], align 1
; CHECK-NEXT:    [[SRC_BYTE16:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -7
; CHECK-NEXT:    [[DST_BYTE17:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -7
; CHECK-NEXT:    [[BYTE_DATA18:%.*]] = load i8, ptr [[SRC_BYTE16]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA18]], ptr [[DST_BYTE17]], align 1
; CHECK-NEXT:    [[SRC_BYTE19:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -8
; CHECK-NEXT:    [[DST_BYTE20:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -8
; CHECK-NEXT:    [[BYTE_DATA21:%.*]] = load i8, ptr [[SRC_BYTE19]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA21]], ptr [[DST_BYTE20]], align 1
; CHECK-NEXT:    [[SRC_BYTE22:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -9
; CHECK-NEXT:    [[DST_BYTE23:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -9
; CHECK-NEXT:    [[BYTE_DATA24:%.*]] = load i8, ptr [[SRC_BYTE22]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA24]], ptr [[DST_BYTE23]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(9) %a, ptr noundef nonnull align 16 dereferenceable(9) %b, i32 9, i1 false)
  ret void
}

define void @test_src16_dstunalign_constant_size_47(ptr %a, ptr %b) {
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_47(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    [[FWD_CP_SRC_I64:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 0
; CHECK-NEXT:    [[FWD_CP_LD_I64:%.*]] = load i64, ptr [[FWD_CP_SRC_I64]], align 8
; CHECK-NEXT:    [[FWD_CP_DST_I64:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 0
; CHECK-NEXT:    store i64 [[FWD_CP_LD_I64]], ptr [[FWD_CP_DST_I64]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I641:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 8
; CHECK-NEXT:    [[FWD_CP_LD_I642:%.*]] = load i64, ptr [[FWD_CP_SRC_I641]], align 8
; CHECK-NEXT:    [[FWD_CP_DST_I643:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 8
; CHECK-NEXT:    store i64 [[FWD_CP_LD_I642]], ptr [[FWD_CP_DST_I643]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I644:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 16
; CHECK-NEXT:    [[FWD_CP_LD_I645:%.*]] = load i64, ptr [[FWD_CP_SRC_I644]], align 8
; CHECK-NEXT:    [[FWD_CP_DST_I646:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 16
; CHECK-NEXT:    store i64 [[FWD_CP_LD_I645]], ptr [[FWD_CP_DST_I646]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I647:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 24
; CHECK-NEXT:    [[FWD_CP_LD_I648:%.*]] = load i64, ptr [[FWD_CP_SRC_I647]], align 8
; CHECK-NEXT:    [[FWD_CP_DST_I649:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 24
; CHECK-NEXT:    store i64 [[FWD_CP_LD_I648]], ptr [[FWD_CP_DST_I649]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I6410:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 32
; CHECK-NEXT:    [[FWD_CP_LD_I6411:%.*]] = load i64, ptr [[FWD_CP_SRC_I6410]], align 8
; CHECK-NEXT:    [[FWD_CP_DST_I6412:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 32
; CHECK-NEXT:    store i64 [[FWD_CP_LD_I6411]], ptr [[FWD_CP_DST_I6412]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I32:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 40
; CHECK-NEXT:    [[FWD_CP_LD_I32:%.*]] = load i32, ptr [[FWD_CP_SRC_I32]], align 4
; CHECK-NEXT:    [[FWD_CP_DST_I32:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 40
; CHECK-NEXT:    store i32 [[FWD_CP_LD_I32]], ptr [[FWD_CP_DST_I32]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I16:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 44
; CHECK-NEXT:    [[FWD_CP_LD_I16:%.*]] = load i16, ptr [[FWD_CP_SRC_I16]], align 2
; CHECK-NEXT:    [[FWD_CP_DST_I16:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 44
; CHECK-NEXT:    store i16 [[FWD_CP_LD_I16]], ptr [[FWD_CP_DST_I16]], align 1
; CHECK-NEXT:    [[FWD_CP_SRC_I8:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 46
; CHECK-NEXT:    [[FWD_CP_LD_I8:%.*]] = load i8, ptr [[FWD_CP_SRC_I8]], align 1
; CHECK-NEXT:    [[FWD_CP_DST_I8:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 46
; CHECK-NEXT:    store i8 [[FWD_CP_LD_I8]], ptr [[FWD_CP_DST_I8]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_END:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 47
; CHECK-NEXT:    [[DST_END:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 47
; CHECK-NEXT:    [[SRC_BYTE:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -1
; CHECK-NEXT:    [[DST_BYTE:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -1
; CHECK-NEXT:    [[BYTE_DATA:%.*]] = load i8, ptr [[SRC_BYTE]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA]], ptr [[DST_BYTE]], align 1
; CHECK-NEXT:    [[SRC_BYTE13:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -2
; CHECK-NEXT:    [[DST_BYTE14:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -2
; CHECK-NEXT:    [[BYTE_DATA15:%.*]] = load i8, ptr [[SRC_BYTE13]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA15]], ptr [[DST_BYTE14]], align 1
; CHECK-NEXT:    [[SRC_BYTE16:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -3
; CHECK-NEXT:    [[DST_BYTE17:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -3
; CHECK-NEXT:    [[BYTE_DATA18:%.*]] = load i8, ptr [[SRC_BYTE16]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA18]], ptr [[DST_BYTE17]], align 1
; CHECK-NEXT:    [[SRC_BYTE19:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -4
; CHECK-NEXT:    [[DST_BYTE20:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -4
; CHECK-NEXT:    [[BYTE_DATA21:%.*]] = load i8, ptr [[SRC_BYTE19]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA21]], ptr [[DST_BYTE20]], align 1
; CHECK-NEXT:    [[SRC_BYTE22:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -5
; CHECK-NEXT:    [[DST_BYTE23:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -5
; CHECK-NEXT:    [[BYTE_DATA24:%.*]] = load i8, ptr [[SRC_BYTE22]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA24]], ptr [[DST_BYTE23]], align 1
; CHECK-NEXT:    [[SRC_BYTE25:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -6
; CHECK-NEXT:    [[DST_BYTE26:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -6
; CHECK-NEXT:    [[BYTE_DATA27:%.*]] = load i8, ptr [[SRC_BYTE25]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA27]], ptr [[DST_BYTE26]], align 1
; CHECK-NEXT:    [[SRC_BYTE28:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -7
; CHECK-NEXT:    [[DST_BYTE29:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -7
; CHECK-NEXT:    [[BYTE_DATA30:%.*]] = load i8, ptr [[SRC_BYTE28]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA30]], ptr [[DST_BYTE29]], align 1
; CHECK-NEXT:    [[SRC_BYTE31:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -8
; CHECK-NEXT:    [[DST_BYTE32:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -8
; CHECK-NEXT:    [[BYTE_DATA33:%.*]] = load i8, ptr [[SRC_BYTE31]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA33]], ptr [[DST_BYTE32]], align 1
; CHECK-NEXT:    [[SRC_BYTE34:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -9
; CHECK-NEXT:    [[DST_BYTE35:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -9
; CHECK-NEXT:    [[BYTE_DATA36:%.*]] = load i8, ptr [[SRC_BYTE34]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA36]], ptr [[DST_BYTE35]], align 1
; CHECK-NEXT:    [[SRC_BYTE37:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -10
; CHECK-NEXT:    [[DST_BYTE38:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -10
; CHECK-NEXT:    [[BYTE_DATA39:%.*]] = load i8, ptr [[SRC_BYTE37]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA39]], ptr [[DST_BYTE38]], align 1
; CHECK-NEXT:    [[SRC_BYTE40:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -11
; CHECK-NEXT:    [[DST_BYTE41:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -11
; CHECK-NEXT:    [[BYTE_DATA42:%.*]] = load i8, ptr [[SRC_BYTE40]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA42]], ptr [[DST_BYTE41]], align 1
; CHECK-NEXT:    [[SRC_BYTE43:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -12
; CHECK-NEXT:    [[DST_BYTE44:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -12
; CHECK-NEXT:    [[BYTE_DATA45:%.*]] = load i8, ptr [[SRC_BYTE43]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA45]], ptr [[DST_BYTE44]], align 1
; CHECK-NEXT:    [[SRC_BYTE46:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -13
; CHECK-NEXT:    [[DST_BYTE47:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -13
; CHECK-NEXT:    [[BYTE_DATA48:%.*]] = load i8, ptr [[SRC_BYTE46]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA48]], ptr [[DST_BYTE47]], align 1
; CHECK-NEXT:    [[SRC_BYTE49:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -14
; CHECK-NEXT:    [[DST_BYTE50:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -14
; CHECK-NEXT:    [[BYTE_DATA51:%.*]] = load i8, ptr [[SRC_BYTE49]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA51]], ptr [[DST_BYTE50]], align 1
; CHECK-NEXT:    [[SRC_BYTE52:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -15
; CHECK-NEXT:    [[DST_BYTE53:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -15
; CHECK-NEXT:    [[BYTE_DATA54:%.*]] = load i8, ptr [[SRC_BYTE52]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA54]], ptr [[DST_BYTE53]], align 1
; CHECK-NEXT:    [[SRC_BYTE55:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -16
; CHECK-NEXT:    [[DST_BYTE56:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -16
; CHECK-NEXT:    [[BYTE_DATA57:%.*]] = load i8, ptr [[SRC_BYTE55]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA57]], ptr [[DST_BYTE56]], align 1
; CHECK-NEXT:    [[SRC_BYTE58:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -17
; CHECK-NEXT:    [[DST_BYTE59:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -17
; CHECK-NEXT:    [[BYTE_DATA60:%.*]] = load i8, ptr [[SRC_BYTE58]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA60]], ptr [[DST_BYTE59]], align 1
; CHECK-NEXT:    [[SRC_BYTE61:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -18
; CHECK-NEXT:    [[DST_BYTE62:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -18
; CHECK-NEXT:    [[BYTE_DATA63:%.*]] = load i8, ptr [[SRC_BYTE61]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA63]], ptr [[DST_BYTE62]], align 1
; CHECK-NEXT:    [[SRC_BYTE64:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -19
; CHECK-NEXT:    [[DST_BYTE65:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -19
; CHECK-NEXT:    [[BYTE_DATA66:%.*]] = load i8, ptr [[SRC_BYTE64]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA66]], ptr [[DST_BYTE65]], align 1
; CHECK-NEXT:    [[SRC_BYTE67:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -20
; CHECK-NEXT:    [[DST_BYTE68:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -20
; CHECK-NEXT:    [[BYTE_DATA69:%.*]] = load i8, ptr [[SRC_BYTE67]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA69]], ptr [[DST_BYTE68]], align 1
; CHECK-NEXT:    [[SRC_BYTE70:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -21
; CHECK-NEXT:    [[DST_BYTE71:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -21
; CHECK-NEXT:    [[BYTE_DATA72:%.*]] = load i8, ptr [[SRC_BYTE70]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA72]], ptr [[DST_BYTE71]], align 1
; CHECK-NEXT:    [[SRC_BYTE73:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -22
; CHECK-NEXT:    [[DST_BYTE74:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -22
; CHECK-NEXT:    [[BYTE_DATA75:%.*]] = load i8, ptr [[SRC_BYTE73]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA75]], ptr [[DST_BYTE74]], align 1
; CHECK-NEXT:    [[SRC_BYTE76:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -23
; CHECK-NEXT:    [[DST_BYTE77:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -23
; CHECK-NEXT:    [[BYTE_DATA78:%.*]] = load i8, ptr [[SRC_BYTE76]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA78]], ptr [[DST_BYTE77]], align 1
; CHECK-NEXT:    [[SRC_BYTE79:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -24
; CHECK-NEXT:    [[DST_BYTE80:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -24
; CHECK-NEXT:    [[BYTE_DATA81:%.*]] = load i8, ptr [[SRC_BYTE79]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA81]], ptr [[DST_BYTE80]], align 1
; CHECK-NEXT:    [[SRC_BYTE82:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -25
; CHECK-NEXT:    [[DST_BYTE83:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -25
; CHECK-NEXT:    [[BYTE_DATA84:%.*]] = load i8, ptr [[SRC_BYTE82]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA84]], ptr [[DST_BYTE83]], align 1
; CHECK-NEXT:    [[SRC_BYTE85:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -26
; CHECK-NEXT:    [[DST_BYTE86:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -26
; CHECK-NEXT:    [[BYTE_DATA87:%.*]] = load i8, ptr [[SRC_BYTE85]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA87]], ptr [[DST_BYTE86]], align 1
; CHECK-NEXT:    [[SRC_BYTE88:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -27
; CHECK-NEXT:    [[DST_BYTE89:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -27
; CHECK-NEXT:    [[BYTE_DATA90:%.*]] = load i8, ptr [[SRC_BYTE88]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA90]], ptr [[DST_BYTE89]], align 1
; CHECK-NEXT:    [[SRC_BYTE91:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -28
; CHECK-NEXT:    [[DST_BYTE92:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -28
; CHECK-NEXT:    [[BYTE_DATA93:%.*]] = load i8, ptr [[SRC_BYTE91]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA93]], ptr [[DST_BYTE92]], align 1
; CHECK-NEXT:    [[SRC_BYTE94:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -29
; CHECK-NEXT:    [[DST_BYTE95:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -29
; CHECK-NEXT:    [[BYTE_DATA96:%.*]] = load i8, ptr [[SRC_BYTE94]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA96]], ptr [[DST_BYTE95]], align 1
; CHECK-NEXT:    [[SRC_BYTE97:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -30
; CHECK-NEXT:    [[DST_BYTE98:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -30
; CHECK-NEXT:    [[BYTE_DATA99:%.*]] = load i8, ptr [[SRC_BYTE97]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA99]], ptr [[DST_BYTE98]], align 1
; CHECK-NEXT:    [[SRC_BYTE100:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -31
; CHECK-NEXT:    [[DST_BYTE101:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -31
; CHECK-NEXT:    [[BYTE_DATA102:%.*]] = load i8, ptr [[SRC_BYTE100]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA102]], ptr [[DST_BYTE101]], align 1
; CHECK-NEXT:    [[SRC_BYTE103:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -32
; CHECK-NEXT:    [[DST_BYTE104:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -32
; CHECK-NEXT:    [[BYTE_DATA105:%.*]] = load i8, ptr [[SRC_BYTE103]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA105]], ptr [[DST_BYTE104]], align 1
; CHECK-NEXT:    [[SRC_BYTE106:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -33
; CHECK-NEXT:    [[DST_BYTE107:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -33
; CHECK-NEXT:    [[BYTE_DATA108:%.*]] = load i8, ptr [[SRC_BYTE106]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA108]], ptr [[DST_BYTE107]], align 1
; CHECK-NEXT:    [[SRC_BYTE109:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -34
; CHECK-NEXT:    [[DST_BYTE110:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -34
; CHECK-NEXT:    [[BYTE_DATA111:%.*]] = load i8, ptr [[SRC_BYTE109]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA111]], ptr [[DST_BYTE110]], align 1
; CHECK-NEXT:    [[SRC_BYTE112:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -35
; CHECK-NEXT:    [[DST_BYTE113:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -35
; CHECK-NEXT:    [[BYTE_DATA114:%.*]] = load i8, ptr [[SRC_BYTE112]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA114]], ptr [[DST_BYTE113]], align 1
; CHECK-NEXT:    [[SRC_BYTE115:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -36
; CHECK-NEXT:    [[DST_BYTE116:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -36
; CHECK-NEXT:    [[BYTE_DATA117:%.*]] = load i8, ptr [[SRC_BYTE115]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA117]], ptr [[DST_BYTE116]], align 1
; CHECK-NEXT:    [[SRC_BYTE118:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -37
; CHECK-NEXT:    [[DST_BYTE119:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -37
; CHECK-NEXT:    [[BYTE_DATA120:%.*]] = load i8, ptr [[SRC_BYTE118]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA120]], ptr [[DST_BYTE119]], align 1
; CHECK-NEXT:    [[SRC_BYTE121:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -38
; CHECK-NEXT:    [[DST_BYTE122:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -38
; CHECK-NEXT:    [[BYTE_DATA123:%.*]] = load i8, ptr [[SRC_BYTE121]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA123]], ptr [[DST_BYTE122]], align 1
; CHECK-NEXT:    [[SRC_BYTE124:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -39
; CHECK-NEXT:    [[DST_BYTE125:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -39
; CHECK-NEXT:    [[BYTE_DATA126:%.*]] = load i8, ptr [[SRC_BYTE124]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA126]], ptr [[DST_BYTE125]], align 1
; CHECK-NEXT:    [[SRC_BYTE127:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -40
; CHECK-NEXT:    [[DST_BYTE128:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -40
; CHECK-NEXT:    [[BYTE_DATA129:%.*]] = load i8, ptr [[SRC_BYTE127]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA129]], ptr [[DST_BYTE128]], align 1
; CHECK-NEXT:    [[SRC_BYTE130:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -41
; CHECK-NEXT:    [[DST_BYTE131:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -41
; CHECK-NEXT:    [[BYTE_DATA132:%.*]] = load i8, ptr [[SRC_BYTE130]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA132]], ptr [[DST_BYTE131]], align 1
; CHECK-NEXT:    [[SRC_BYTE133:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -42
; CHECK-NEXT:    [[DST_BYTE134:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -42
; CHECK-NEXT:    [[BYTE_DATA135:%.*]] = load i8, ptr [[SRC_BYTE133]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA135]], ptr [[DST_BYTE134]], align 1
; CHECK-NEXT:    [[SRC_BYTE136:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -43
; CHECK-NEXT:    [[DST_BYTE137:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -43
; CHECK-NEXT:    [[BYTE_DATA138:%.*]] = load i8, ptr [[SRC_BYTE136]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA138]], ptr [[DST_BYTE137]], align 1
; CHECK-NEXT:    [[SRC_BYTE139:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -44
; CHECK-NEXT:    [[DST_BYTE140:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -44
; CHECK-NEXT:    [[BYTE_DATA141:%.*]] = load i8, ptr [[SRC_BYTE139]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA141]], ptr [[DST_BYTE140]], align 1
; CHECK-NEXT:    [[SRC_BYTE142:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -45
; CHECK-NEXT:    [[DST_BYTE143:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -45
; CHECK-NEXT:    [[BYTE_DATA144:%.*]] = load i8, ptr [[SRC_BYTE142]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA144]], ptr [[DST_BYTE143]], align 1
; CHECK-NEXT:    [[SRC_BYTE145:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -46
; CHECK-NEXT:    [[DST_BYTE146:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -46
; CHECK-NEXT:    [[BYTE_DATA147:%.*]] = load i8, ptr [[SRC_BYTE145]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA147]], ptr [[DST_BYTE146]], align 1
; CHECK-NEXT:    [[SRC_BYTE148:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -47
; CHECK-NEXT:    [[DST_BYTE149:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -47
; CHECK-NEXT:    [[BYTE_DATA150:%.*]] = load i8, ptr [[SRC_BYTE148]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA150]], ptr [[DST_BYTE149]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(47) %a, ptr noundef nonnull align 16 dereferenceable(47) %b, i32 47, i1 false)
  ret void
}

; Negative: Size == SIMPLE_UNROLL_THRESHOLD (48) must NOT take fwd.cp bypass.
define void @test_src16_dstunalign_constant_size_48(ptr %a, ptr %b) {
; CHECK-LABEL: define void @test_src16_dstunalign_constant_size_48(
; CHECK:       forward.copy:
; CHECK:         call void @llvm.memmove.p0.p0.i32(ptr align 1 {{.*}}, ptr align 16 {{.*}}, i32 48,
; CHECK-NOT:     load i64
; CHECK:       backward.copy:
; CHECK:         load i8,
; CHECK:       memmove.end:
; CHECK:         ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(48) %a, ptr noundef nonnull align 16 dereferenceable(48) %b, i32 48, i1 false)
  ret void
}
