; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32-p4-memmove -riscv-esp32-p4-memmove=true < %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "riscv32-esp-unknown-elf"

; Small overlapping dst-below-src sample (size 4, src = dst+2) so FileCheck
; covers the full backward unroll without a 32-byte CHECK wall.
define dso_local void @test_basic_forward_offset() {
; CHECK-LABEL: define dso_local void @test_basic_forward_offset() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BUFFER:%.*]] = alloca [8 x i8], align 1
; CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[BUFFER]])
; CHECK-NEXT:    [[SRC:%.*]] = getelementptr inbounds i8, ptr [[BUFFER]], i32 2
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[BUFFER]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[SRC]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    call void @llvm.memmove.p0.p0.i32(ptr align 1 [[BUFFER]], ptr align 1 [[SRC]], i32 4, i1 false), !riscv.esp32p4.memmove.no_reprocess [[META0:![0-9]+]]
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_END:%.*]] = getelementptr inbounds i8, ptr [[SRC]], i64 4
; CHECK-NEXT:    [[DST_END:%.*]] = getelementptr inbounds i8, ptr [[BUFFER]], i64 4
; CHECK-NEXT:    [[SRC_BYTE:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -1
; CHECK-NEXT:    [[DST_BYTE:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -1
; CHECK-NEXT:    [[BYTE_DATA:%.*]] = load i8, ptr [[SRC_BYTE]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA]], ptr [[DST_BYTE]], align 1
; CHECK-NEXT:    [[SRC_BYTE1:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -2
; CHECK-NEXT:    [[DST_BYTE2:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -2
; CHECK-NEXT:    [[BYTE_DATA3:%.*]] = load i8, ptr [[SRC_BYTE1]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA3]], ptr [[DST_BYTE2]], align 1
; CHECK-NEXT:    [[SRC_BYTE4:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -3
; CHECK-NEXT:    [[DST_BYTE5:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -3
; CHECK-NEXT:    [[BYTE_DATA6:%.*]] = load i8, ptr [[SRC_BYTE4]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA6]], ptr [[DST_BYTE5]], align 1
; CHECK-NEXT:    [[SRC_BYTE7:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i64 -4
; CHECK-NEXT:    [[DST_BYTE8:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i64 -4
; CHECK-NEXT:    [[BYTE_DATA9:%.*]] = load i8, ptr [[SRC_BYTE7]], align 1
; CHECK-NEXT:    store i8 [[BYTE_DATA9]], ptr [[DST_BYTE8]], align 1
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[BUFFER]])
; CHECK-NEXT:    ret void
;
entry:
  %buffer = alloca [8 x i8], align 1
  call void @llvm.lifetime.start.p0(i64 8, ptr nonnull %buffer)
  %src = getelementptr inbounds i8, ptr %buffer, i32 2
  call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 1 dereferenceable(4) %buffer, ptr noundef nonnull align 1 dereferenceable(4) %src, i32 4, i1 false)
  call void @llvm.lifetime.end.p0(i64 8, ptr nonnull %buffer)
  ret void
}

;.
; CHECK: [[META0]] = !{}
;.
