; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32-p4-memmove -riscv-esp32-p4-memmove=true < %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "riscv32-esp-unknown-elf"

define void @test_src16_dst16_variable_size(ptr %a, ptr %b, i32 %size) {
; CHECK-LABEL: define void @test_src16_dst16_variable_size(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]], i32 [[SIZE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[IS_SMALL:%.*]] = icmp ult i32 [[SIZE]], 16
; CHECK-NEXT:    br i1 [[IS_SMALL]], label %[[SMALL_DIRECT:.*]], label %[[LARGE_DISPATCH:.*]]
; CHECK:       [[SMALL_DIRECT]]:
; CHECK-NEXT:    call void @llvm.memmove.p0.p0.i32(ptr align 16 [[A]], ptr align 16 [[B]], i32 [[SIZE]], i1 false), !riscv.esp32p4.memmove.no_reprocess [[META0:![0-9]+]]
; CHECK-NEXT:    br label %[[MEMMOVE_REST:.*]]
; CHECK:       [[LARGE_DISPATCH]]:
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LT_SRC:%.*]] = icmp ult i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LT_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    call void @llvm.memmove.p0.p0.i32(ptr align 16 [[A]], ptr align 16 [[B]], i32 [[SIZE]], i1 false), !riscv.esp32p4.memmove.no_reprocess [[META0]]
; CHECK-NEXT:    br label %[[MEMMOVE_REST]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[IS_MEDIUM:%.*]] = icmp ult i32 [[SIZE]], 128
; CHECK-NEXT:    br i1 [[IS_MEDIUM]], label %[[MEDIUM_BACKWARD:.*]], label %[[LARGE_BACKWARD:.*]]
; CHECK:       [[MEMMOVE_REST]]:
; CHECK-NEXT:    ret void
; CHECK:       [[MEDIUM_BACKWARD]]:
; CHECK-NEXT:    [[REMAINDER16:%.*]] = urem i32 [[SIZE]], 16
; CHECK-NEXT:    [[BLOCKS16:%.*]] = udiv i32 [[SIZE]], 16
; CHECK-NEXT:    [[SRC_END:%.*]] = getelementptr inbounds i8, ptr [[B]], i32 [[SIZE]]
; CHECK-NEXT:    [[DST_END:%.*]] = getelementptr inbounds i8, ptr [[A]], i32 [[SIZE]]
; CHECK-NEXT:    [[HAS_REMAINDER:%.*]] = icmp ne i32 [[REMAINDER16]], 0
; CHECK-NEXT:    br i1 [[HAS_REMAINDER]], label %[[MEDIUM_REMAINDER:.*]], label %[[MEDIUM_BLOCKS16:.*]]
; CHECK:       [[LARGE_BACKWARD]]:
; CHECK-NEXT:    [[BLOCKS128:%.*]] = udiv i32 [[SIZE]], 128
; CHECK-NEXT:    [[REM128:%.*]] = urem i32 [[SIZE]], 128
; CHECK-NEXT:    [[BLOCKS16_R:%.*]] = udiv i32 [[REM128]], 16
; CHECK-NEXT:    [[REMAINDER_R:%.*]] = urem i32 [[REM128]], 16
; CHECK-NEXT:    [[HAS_REMAINDER_R:%.*]] = icmp ne i32 [[REMAINDER_R]], 0
; CHECK-NEXT:    br i1 [[HAS_REMAINDER_R]], label %[[STEP1_REMAINDER:.*]], label %[[STEP2_BLOCKS16:.*]]
; CHECK:       [[BACKWARD_EXIT:.*]]:
; CHECK-NEXT:    br label %[[MEMMOVE_REST]]
; CHECK:       [[MEDIUM_REMAINDER]]:
; CHECK-NEXT:    [[TMP2:%.*]] = sub i32 0, [[REMAINDER16]]
; CHECK-NEXT:    [[REMAINDER_SRC:%.*]] = getelementptr inbounds i8, ptr [[SRC_END]], i32 [[TMP2]]
; CHECK-NEXT:    [[TMP3:%.*]] = sub i32 0, [[REMAINDER16]]
; CHECK-NEXT:    [[REMAINDER_DST:%.*]] = getelementptr inbounds i8, ptr [[DST_END]], i32 [[TMP3]]
; CHECK-NEXT:    switch i32 [[REMAINDER16]], label %[[SMALL_BACK_DEFAULT:.*]] [
; CHECK-NEXT:      i32 0, label %[[SMALL_BACK_CASE_0:.*]]
; CHECK-NEXT:      i32 1, label %[[SMALL_BACK_CASE_1:.*]]
; CHECK-NEXT:      i32 2, label %[[SMALL_BACK_CASE_2:.*]]
; CHECK-NEXT:      i32 3, label %[[SMALL_BACK_CASE_3:.*]]
; CHECK-NEXT:      i32 4, label %[[SMALL_BACK_CASE_4:.*]]
; CHECK-NEXT:      i32 5, label %[[SMALL_BACK_CASE_5:.*]]
; CHECK-NEXT:      i32 6, label %[[SMALL_BACK_CASE_6:.*]]
; CHECK-NEXT:      i32 7, label %[[SMALL_BACK_CASE_7:.*]]
; CHECK-NEXT:      i32 8, label %[[SMALL_BACK_CASE_8:.*]]
; CHECK-NEXT:      i32 9, label %[[SMALL_BACK_CASE_9:.*]]
; CHECK-NEXT:      i32 10, label %[[SMALL_BACK_CASE_10:.*]]
; CHECK-NEXT:      i32 11, label %[[SMALL_BACK_CASE_11:.*]]
; CHECK-NEXT:      i32 12, label %[[SMALL_BACK_CASE_12:.*]]
; CHECK-NEXT:      i32 13, label %[[SMALL_BACK_CASE_13:.*]]
; CHECK-NEXT:      i32 14, label %[[SMALL_BACK_CASE_14:.*]]
; CHECK-NEXT:      i32 15, label %[[SMALL_BACK_CASE_15:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[MEDIUM_BLOCKS16]]:
; CHECK-NEXT:    [[HAS_BLOCKS16:%.*]] = icmp ne i32 [[BLOCKS16]], 0
; CHECK-NEXT:    [[BLOCKS_TOTAL_SIZE:%.*]] = mul i32 [[BLOCKS16]], 16
; CHECK-NEXT:    [[LAST_BLOCK_START:%.*]] = sub i32 [[BLOCKS_TOTAL_SIZE]], 16
; CHECK-NEXT:    [[TMP4:%.*]] = add i32 [[LAST_BLOCK_START]], 0
; CHECK-NEXT:    [[TMP5:%.*]] = add i32 [[LAST_BLOCK_START]], 0
; CHECK-NEXT:    [[INITIAL_SRC_ADDR:%.*]] = getelementptr inbounds i8, ptr [[B]], i32 [[TMP4]]
; CHECK-NEXT:    [[INITIAL_DST_ADDR:%.*]] = getelementptr inbounds i8, ptr [[A]], i32 [[TMP5]]
; CHECK-NEXT:    br i1 [[HAS_BLOCKS16]], label %[[SIMD_LOOP:.*]], label %[[BACKWARD_EXIT]]
; CHECK:       [[SIMD_LOOP]]:
; CHECK-NEXT:    [[BLOCK_COUNTER:%.*]] = phi i32 [ [[BLOCKS16]], %[[MEDIUM_BLOCKS16]] ], [ [[NEW_COUNTER:%.*]], %[[SIMD_LOOP]] ]
; CHECK-NEXT:    [[CURRENT_SRC_ADDR:%.*]] = phi ptr [ [[INITIAL_SRC_ADDR]], %[[MEDIUM_BLOCKS16]] ], [ [[VLD128IP_M_NEXTPTR:%.*]], %[[SIMD_LOOP]] ]
; CHECK-NEXT:    [[CURRENT_DST_ADDR:%.*]] = phi ptr [ [[INITIAL_DST_ADDR]], %[[MEDIUM_BLOCKS16]] ], [ [[VST128IP_M:%.*]], %[[SIMD_LOOP]] ]
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[CURRENT_SRC_ADDR]], i32 -16) #[[ATTR3:[0-9]+]]
; CHECK-NEXT:    [[VLD128IP_M_VEC:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[VLD128IP_M_NEXTPTR]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[VST128IP_M]] = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> [[VLD128IP_M_VEC]], ptr [[CURRENT_DST_ADDR]], i32 -16) #[[ATTR3]]
; CHECK-NEXT:    [[NEW_COUNTER]] = sub i32 [[BLOCK_COUNTER]], 1
; CHECK-NEXT:    [[CONTINUE:%.*]] = icmp ne i32 [[NEW_COUNTER]], 0
; CHECK-NEXT:    br i1 [[CONTINUE]], label %[[SIMD_LOOP]], label %[[BACKWARD_EXIT]]
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 16 %a, ptr noundef nonnull align 16 %b, i32 %size, i1 false)
  ret void
}
;.
; CHECK: [[META0]] = !{}
;.
