; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=riscv32-esp-unknown-elf -passes=riscv-esp32-p4-memmove -riscv-esp32-p4-memmove=true < %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128"
target triple = "riscv32-esp-unknown-elf"


define void @test_src16_dst8_size_16(ptr %a, ptr %b) {
;
;
;
; CHECK-LABEL: define void @test_src16_dst8_size_16(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[A]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = ptrtoint ptr [[B]] to i32
; CHECK-NEXT:    [[DST_LEQ_SRC:%.*]] = icmp ule i32 [[TMP0]], [[TMP1]]
; CHECK-NEXT:    br i1 [[DST_LEQ_SRC]], label %[[FORWARD_COPY:.*]], label %[[BACKWARD_COPY:.*]]
; CHECK:       [[FORWARD_COPY]]:
; CHECK-NEXT:    call void @llvm.memmove.p0.p0.i32(ptr align 8 [[A]], ptr align 16 [[B]], i32 16, i1 false), !riscv.esp32p4.memmove.no_reprocess [[META0:![0-9]+]]
; CHECK-NEXT:    br label %[[MEMMOVE_END:.*]]
; CHECK:       [[BACKWARD_COPY]]:
; CHECK-NEXT:    [[SRC_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 0
; CHECK-NEXT:    [[DST_START_ADDR:%.*]] = getelementptr inbounds i8, ptr [[A]], i64 8
; CHECK-NEXT:    [[TMP2:%.*]] = ptrtoint ptr [[SRC_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[DST_START_ADDR]] to i32
; CHECK-NEXT:    [[TMP4:%.*]] = inttoptr i32 [[TMP2]] to ptr
; CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i32 [[TMP3]] to ptr
; CHECK-NEXT:    [[VLD128IP_M:%.*]] = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr [[TMP4]], i32 -16) #[[ATTR3:[0-9]+]]
; CHECK-NEXT:    [[VLD128IP_M_VEC:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 0
; CHECK-NEXT:    [[VLD128IP_M_NEXTPTR:%.*]] = extractvalue { <16 x i8>, ptr } [[VLD128IP_M]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i8> [[VLD128IP_M_VEC]], <16 x i8> [[VLD128IP_M_VEC]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i8> [[VLD128IP_M_VEC]], <16 x i8> [[VLD128IP_M_VEC]], <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[VSTL64IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP9]], ptr [[TMP5]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[VST128IP_M:%.*]] = call ptr @llvm.riscv.esp.vst.l.64.ip(<8 x i8> [[TMP8]], ptr [[VSTL64IP_M]], i32 -8) #[[ATTR3]]
; CHECK-NEXT:    [[TMP6:%.*]] = ptrtoint ptr [[VLD128IP_M_NEXTPTR]] to i32
; CHECK-NEXT:    [[TMP7:%.*]] = ptrtoint ptr [[VST128IP_M]] to i32
; CHECK-NEXT:    br label %[[MEMMOVE_END]]
; CHECK:       [[MEMMOVE_END]]:
; CHECK-NEXT:    ret void
;
entry:
  tail call void @llvm.memmove.p0.p0.i32(ptr noundef nonnull align 8 dereferenceable(16) %a, ptr noundef nonnull align 16 dereferenceable(16) %b, i32 16, i1 false)
  ret void
}

;.
; CHECK: [[META0]] = !{}
;.
