; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; Negative post-increment offsets (memmove backward path).
; Regression 1: selectESP used getTargetConstant(ImmVal) → APInt assert on -8/-16.
; Regression 2: ESP_VLD_L_64_IP hardcoding emitted 2.1 opcode under pure +xespv2p2.
; The CHECKs pin the signed negative immediate operands on the MIR lines, so a
; silently unsigned-encoded offset (4294967280/4294967288) cannot pass.
; RUN: llc -O2 -mtriple=riscv32-esp-unknown-elf -mcpu=esp32p4 -mattr=+espv-lowering \
; RUN:   -stop-after=finalize-isel -verify-machineinstrs %s -o - \
; RUN:   | FileCheck %s --check-prefix=ESPV22
; RUN: llc -O2 -mtriple=riscv32-esp-unknown-elf -mcpu=esp32p4eco4 -mattr=+espv-lowering \
; RUN:   -stop-after=finalize-isel -verify-machineinstrs %s -o - \
; RUN:   | FileCheck %s --check-prefix=ESPV21

define ptr @vld_vst_128_neg(ptr %dst, ptr %src) {
  ; ESPV22-LABEL: name: vld_vst_128_neg
  ; ESPV22: bb.0.entry:
  ; ESPV22-NEXT:   liveins: $x10, $x11
  ; ESPV22-NEXT: {{  $}}
  ; ESPV22-NEXT:   [[COPY:%[0-9]+]]:gprpie = COPY $x11
  ; ESPV22-NEXT:   [[COPY1:%[0-9]+]]:gprpie = COPY $x10
  ; ESPV22-NEXT:   [[ESP_VLD_128_IP_2P2_:%[0-9]+]]:qr, [[ESP_VLD_128_IP_2P2_1:%[0-9]+]]:gprpie = ESP_VLD_128_IP_2P2 [[COPY]], -16 :: (load (s128) from %ir.src)
  ; ESPV22-NEXT:   [[ESP_VST_128_IP_2P2_:%[0-9]+]]:gprpie = ESP_VST_128_IP_2P2 killed [[ESP_VLD_128_IP_2P2_]], [[COPY1]], -16 :: (store (s128) into %ir.dst)
  ; ESPV22-NEXT:   $x10 = COPY [[ESP_VST_128_IP_2P2_]]
  ; ESPV22-NEXT:   PseudoRET implicit $x10
  ;
  ; ESPV21-LABEL: name: vld_vst_128_neg
  ; ESPV21: bb.0.entry:
  ; ESPV21-NEXT:   liveins: $x10, $x11
  ; ESPV21-NEXT: {{  $}}
  ; ESPV21-NEXT:   [[COPY:%[0-9]+]]:gprpie = COPY $x11
  ; ESPV21-NEXT:   [[COPY1:%[0-9]+]]:gprpie = COPY $x10
  ; ESPV21-NEXT:   [[ESP_VLD_128_IP:%[0-9]+]]:qr, [[ESP_VLD_128_IP1:%[0-9]+]]:gprpie = ESP_VLD_128_IP [[COPY]], -16 :: (load (s128) from %ir.src)
  ; ESPV21-NEXT:   [[ESP_VST_128_IP:%[0-9]+]]:gprpie = ESP_VST_128_IP killed [[ESP_VLD_128_IP]], [[COPY1]], -16 :: (store (s128) into %ir.dst)
  ; ESPV21-NEXT:   $x10 = COPY [[ESP_VST_128_IP]]
  ; ESPV21-NEXT:   PseudoRET implicit $x10
entry:
  %load = call { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr %src, i32 -16)
  %value = extractvalue { <16 x i8>, ptr } %load, 0
  %next = call ptr @llvm.riscv.esp.vst.128.ip(<16 x i8> %value, ptr %dst, i32 -16)
  ret ptr %next
}

define <8 x i8> @vld_l_64_neg(ptr %src) {
  ; ESPV22-LABEL: name: vld_l_64_neg
  ; ESPV22: bb.0.entry:
  ; ESPV22-NEXT:   liveins: $x10, $x11
  ; ESPV22-NEXT: {{  $}}
  ; ESPV22-NEXT:   [[COPY:%[0-9]+]]:gprpie = COPY $x11
  ; ESPV22-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; ESPV22-NEXT:   [[COPY2:%[0-9]+]]:gprpie = COPY [[COPY1]]
  ; ESPV22-NEXT:   [[ESP_VLD_L_64_IP_2P2_:%[0-9]+]]:qr, [[ESP_VLD_L_64_IP_2P2_1:%[0-9]+]]:gprpie = ESP_VLD_L_64_IP_2P2 [[COPY]], -8 :: (load (s64) from %ir.src)
  ; ESPV22-NEXT:   [[ESP_VST_L_64_IP_2P2_:%[0-9]+]]:gprpie = ESP_VST_L_64_IP_2P2 killed [[ESP_VLD_L_64_IP_2P2_]], [[COPY2]], 0 :: (store (s64))
  ; ESPV22-NEXT:   PseudoRET
  ;
  ; ESPV21-LABEL: name: vld_l_64_neg
  ; ESPV21: bb.0.entry:
  ; ESPV21-NEXT:   liveins: $x10, $x11
  ; ESPV21-NEXT: {{  $}}
  ; ESPV21-NEXT:   [[COPY:%[0-9]+]]:gprpie = COPY $x11
  ; ESPV21-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x10
  ; ESPV21-NEXT:   [[COPY2:%[0-9]+]]:gprpie = COPY [[COPY1]]
  ; ESPV21-NEXT:   [[ESP_VLD_L_64_IP:%[0-9]+]]:qr_64, [[ESP_VLD_L_64_IP1:%[0-9]+]]:gprpie = ESP_VLD_L_64_IP [[COPY]], -8 :: (load (s64) from %ir.src)
  ; ESPV21-NEXT:   [[ESP_VST_L_64_IP:%[0-9]+]]:gprpie = ESP_VST_L_64_IP killed [[ESP_VLD_L_64_IP]], [[COPY2]], 0 :: (store (s64))
  ; ESPV21-NEXT:   PseudoRET
entry:
  %load = call { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr %src, i32 -8)
  %value = extractvalue { <8 x i8>, ptr } %load, 0
  ret <8 x i8> %value
}

declare { <16 x i8>, ptr } @llvm.riscv.esp.vld.128.ip(ptr, i32)
declare ptr @llvm.riscv.esp.vst.128.ip(<16 x i8>, ptr, i32)
declare { <8 x i8>, ptr } @llvm.riscv.esp.vld.l.64.ip(ptr, i32)
